### PR TITLE
I18n sync Down & Out 04/02

### PR DESCRIPTION
**Pull request by deploy-code-org**

### CODE REVIEW

**Comment by Hamms** [comment]
Looks like this PR is including a bunch of unwanted DSLS changes

**Comment by bethanyaconnor** [comment]
The DSLS changes should've been reverted in 3075c43. I forgot to revert them before creating the PR. :(

**Review by nkiruka — APPROVED** [review]

**Comment by Hamms** [comment]
Hmm, I still see a bunch of dsls changes, even with that commit. See https://github.com/code-dot-org/code-dot-org/pull/27808/commits/9e9ecf1e202e3ffcfcf063abf7a16271bbaeb5be#diff-3897cafef89522bfdd34100a0b8b518a

**Comment by bethanyaconnor** [comment]
I think the individual commits will still show those diffs but they should've all been undone later.

`ubuntu@i18n:~/code-dot-org$ git diff i18n-sync-down-out-04-02..staging | grep "dsls"
ubuntu@i18n:~/code-dot-org$ `

What is our "normal" way of undoing these changes if the PR has already been created? I just checked them all out again from staging but I'm fairly novice at git. :)

**Comment by Hamms** [comment]
Oh, right you are! Yeah, checking them out from staging has been my approach in the past.

**Review by Hamms — APPROVED** [review]

**Pull request merged**
