### PR TITLE
fix js error about Petition on csedweek.org

### PR DESCRIPTION
**Pull request by laurelfan**

### CODE REVIEW

**Comment by tanyaparker** [comment]
Oh yeah, Oct 6 I did replace the csedweek petition with the map. But I just hid the view, didn't edit the js...

**Comment by tanyaparker** [comment]
This looks fine to me, but I don't understand why the js error was only happening now?

**Comment by laurelfan** [comment]
I don't think it was only happening now, probably nobody looked at the js
errors. There was a spike today at the deploy so I started tracking down
the heavy hitters.

This appears to be referencing something that was in the petition view that
you removed.

Also, there are a lot of conditionals like `- if request.site == 'code.org'`
will those ever be true?

**Comment by tanyaparker** [comment]
Ah, I see. I totally went color blind when I first saw this and thought you added that code. Makes more sense that you removed it.

I think this is left over when code.org/csedweek.org homepages used to be shared. Whenever I touch a certain part of the page I clear up what I touch, but yeah we should do a full clean of these pages.

**Pull request merged**
