### PR TITLE
Make sure has_lesson_plan is not null

### PR DESCRIPTION
**Pull request by dmcavoy**
Migration to make sure that has_lesson_plan is not null. This should already be true for all the lessons since we set has_lesson_plan based on lockable and lockable is currently not allowed to be null. 

In addition I update the fixtures for lessons by hand to add has_lesson_plan to all the lessons based on lockable. I did it by hand instead of the script to generate them because using the script caused issues because the ids got updated and that was causing problems with the seeding of scripts because of the seed_key on script_levels. It was saying that a matching key already existed. We probably need to follow up on this but since I could work around it for now I will.  (Tracked in backlog https://codedotorg.atlassian.net/browse/PLAT-738)

### CODE REVIEW

**Comment by dmcavoy** [comment]
Sorry @davidsbailey this is not ready to review because I ended up needing to merge in some previous PRs to make updating fixtures make the most sense.

**Comment by dmcavoy** [comment]
Alright @davidsbailey I think this is ready for review.

**Review by bethanyaconnor — APPROVED** [review]
Looks great! Tested this out locally and has a little bit of trouble with the migration because of local lessons I'd created but it was a simple time to fix them manually.

**Review by davidsbailey — APPROVED** [review]
thank you for doing this! Seems reasonable to work around the fixtures problem, given that it wasn't introduced by this PR.

**Pull request merged**
