### PR TITLE
Parameterized behaviors

### PR DESCRIPTION
**Pull request by joshlory**
Address TODO in https://github.com/code-dot-org/code-dot-org/pull/22940#discussion_r193572271.

behavior-params

The serialized XML for the block looks like this:

```xml
<block type="gamelab_behavior_get">
  <mutation>
    <arg name="amount" type="Number"></arg>
  </mutation>
  <title name="VAR">growing</title>
  <value name="ARG0">
    <block type="math_number">
      <title name="NUM">3</title>
    </block>
  </value>
</block>
```

Note that we're not storing the procedure name in the mutation, unlike procedure calls.  I did this because we're already storing the name as a "VAR" title instead.

### CODE REVIEW

**Comment by joshlory** [comment]
["gamelab_behavior_get" block should implement setProcedureParameters](https://trello.com/c/L0NcyH1u/187-gamelabbehaviorget-block-should-implement-setprocedureparameters)

**Comment by joshlory** [comment]
As I look at this again, I _really_ think we should be parameterizing the "add behavior" block and not the behavior itself.

image

Does this replace the existing behavior, changing the growth rate to 5?  Or does it add a second behavior, so the bear is growing at rate 3 **and** growing at rate 5 (total of 8 units every tick)?  Does the "stops" block stop both behaviors, or neither because the param doesn't match?  As implemented today, the bear will be growing at rate 8 with the above code.

Cleaner (I think) as:

image

One downside: the "add behavior" block would mutate based on which behavior is attached, which might be weird.

+cc @mrjoshida @ryansloan

**Comment by joshlory** [comment]
Merging as-is for now.  I'll create an option to test out the other variant.

**Comment by ryansloan** [comment]
Agreed we should build something to test out the other variant, but glad to have this merged in the meantime

**Pull request merged**
