### PR TITLE
Run eyes tests on CircleCI

### PR DESCRIPTION
**Pull request by bcjordan**
This enables eyes test runs on CircleCI. This includes the marking of 3 consistently failing-on-CircleCI tests as `@no_circle`. The table below represents 3 failing test runs each.

This has been run 13 times in a row successfully, results below. 
#13 consecutive passes of defdbb6
1. [#18597](https://circleci.com/gh/code-dot-org/code-dot-org/18597)
2. [#18598](https://circleci.com/gh/code-dot-org/code-dot-org/18598)
3. [#18599](https://circleci.com/gh/code-dot-org/code-dot-org/18599)
4. [#18600](https://circleci.com/gh/code-dot-org/code-dot-org/18600)
5. [#18601](https://circleci.com/gh/code-dot-org/code-dot-org/18601)
6. [#18602](https://circleci.com/gh/code-dot-org/code-dot-org/18602)
7. [#18603](https://circleci.com/gh/code-dot-org/code-dot-org/18603)
8. [#18604](https://circleci.com/gh/code-dot-org/code-dot-org/18604)
9. [#18605](https://circleci.com/gh/code-dot-org/code-dot-org/18605)
10. [#18606](https://circleci.com/gh/code-dot-org/code-dot-org/18606)
11. [#18607](https://circleci.com/gh/code-dot-org/code-dot-org/18607)
12. [#18608](https://circleci.com/gh/code-dot-org/code-dot-org/18608)
13. [#18609](https://circleci.com/gh/code-dot-org/code-dot-org/18609)
# Consistently failing tests marked `@no_circle`

The intent with marking these `@no_circle` now and merging in the stable passing tests is to lock down the majority of which are working and provide an easy way of experimenting with fixes for these in Circle (merge off of staging, push a prospective fix, rinse and repeat). For each one below, there are 3 failed runs, their associated log outputs, and an initial guess as to failure cause.

| **Test Name** | **Likely Cause** | **Circle Build #** | **Sauce Build (requires login)** | **Cucumber Run** | **Applitools run (requires login)** |
| --- | --- | --- | --- | --- | --- |
| logged out code.org homepage | localhost.code.org:3000 going to Code Studio homepage | [#18595](https://circleci.com/gh/code-dot-org/code-dot-org/18595) | [sauce run](https://saucelabs.com/tests/fd224b7fdee7497685116b6ab11fbaf3) | [output.html](https://cucumber-logs.s3.amazonaws.com/eyes-circle/ChromeLatestWin7_eyes_eyes_output.html?versionId=XLq_h6ugyWcSi6n_mwIiVrf1OSFOiG6o) | [comparison](https://eyes.applitools.com/app/sessions/00000251931824587971/00000251931824587674/steps/2?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110) |
| "" |  | [#18594](https://circleci.com/gh/code-dot-org/code-dot-org/18594) | [sauce run](https://saucelabs.com/tests/264b2a9e8ea14dce860eb308b1de5fb3) | [output.html](https://cucumber-logs.s3.amazonaws.com/eyes-circle/ChromeLatestWin7_eyes_eyes_output.html?versionId=gmkaV3BnIV93DBIEeaC9hwgPP22w72Ki%27) | [comparison](https://eyes.applitools.com/app/sessions/00000251931824550317/00000251931824550130/steps/2?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110) |
| "" |  | [#18592](https://circleci.com/gh/code-dot-org/code-dot-org/18592) | [sauce run](https://saucelabs.com/tests/8044082be900495db5a470114b3711df) | [output.html](https://cucumber-logs.s3.amazonaws.com/eyes-circle/ChromeLatestWin7_eyes_eyes_output.html?versionId=MiTs7mcKkYCXaQq_Izqm_ZwP6GshcRM9) | [comparison](https://eyes.applitools.com/app/sessions/00000251931837295266/00000251931837295110/steps/2?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110) |
| maze | missing noautoplay=true on ar-sa visit | [#18595](https://circleci.com/gh/code-dot-org/code-dot-org/18595) | [sauce run](https://saucelabs.com/tests/11c5b9fc674a4d3981bdde6c72f46e23) | [output.html](https://cucumber-logs.s3.amazonaws.com/eyes-circle/ChromeLatestWin7_eyes_eyes_output.html?versionId=XLq_h6ugyWcSi6n_mwIiVrf1OSFOiG6o) | [comparison](https://eyes.applitools.com/app/sessions/00000251931824464260/00000251931824463969/steps/1?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110) |
| "" |  | [#18594](https://circleci.com/gh/code-dot-org/code-dot-org/18594) | [sauce run](https://saucelabs.com/tests/7a882892cb4c483083e2d57556b94080) | [output.html](https://cucumber-logs.s3.amazonaws.com/eyes-circle/ChromeLatestWin7_eyes_eyes_output.html?versionId=gmkaV3BnIV93DBIEeaC9hwgPP22w72Ki%27) | [comparison](https://eyes.applitools.com/app/sessions/00000251931824424518/00000251931824424361/steps/1?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110) |
| "" |  | [#18592](https://circleci.com/gh/code-dot-org/code-dot-org/18592) | [sauce run](https://saucelabs.com/tests/741e596434054a2085d8773db23ab46c) | [output.html](https://cucumber-logs.s3.amazonaws.com/eyes-circle/ChromeLatestWin7_eyes_eyes_output.html?versionId=MiTs7mcKkYCXaQq_Izqm_ZwP6GshcRM9) | [comparison](https://eyes.applitools.com/app/sessions/00000251931837181781/00000251931837181609/steps/1?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110) |
| top instructions in CSF | login just not taking | [#18595](https://circleci.com/gh/code-dot-org/code-dot-org/18595) | [sauce run](https://saucelabs.com/tests/3e8cbf0f690447fdb95c771dbea51b14) | [output.html](https://cucumber-logs.s3.amazonaws.com/eyes-circle/ChromeLatestWin7_topInstructions_eyes_output.html?versionId=NSKtfbXoiuPSyKef86Dv1uPDWyTsXE7o) | [comparison](https://eyes.applitools.com/app/sessions/00000251931825422332/00000251931825422155/steps/1?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110) |
| "" |  | [#18594](https://circleci.com/gh/code-dot-org/code-dot-org/18594) | [sauce run](https://saucelabs.com/tests/7d64e918cf7349a9923652785d0c1aeb) | [output.html](https://cucumber-logs.s3.amazonaws.com/eyes-circle/ChromeLatestWin7_topInstructions_eyes_output.html?versionId=amEUz9JqMZgJKooYDPXN.Usv33Be1lYI%27) | [comparison](https://eyes.applitools.com/app/sessions/00000251931825484754/00000251931825484551/steps/1?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110) |
| "" |  | [#18592](https://circleci.com/gh/code-dot-org/code-dot-org/18592) | [sauce run](https://saucelabs.com/tests/d2c5c0f1e80c4d41ba8593dccce6a98e) | [output.html](https://cucumber-logs.s3.amazonaws.com/eyes-circle/ChromeLatestWin7_topInstructions_eyes_output.html?versionId=532m836YwI7wJYKdkoA5Oz3MeEROiiLQ%27) | [comparison](https://eyes.applitools.com/app/sessions/00000251931838158835/00000251931838158663/steps/1?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110) |

### CODE REVIEW

**Comment by islemaster** [comment]
Overall LGTM.  Couple of questions :

Why --parallel 26? Is that plus 30 for UI tests going to be too much?

Why are we using retry count 3 instead of magic retry on circle?

#code-(review-)on-the-road

**Comment by bcjordan** [comment]
@islemaster thanks!

Re: 30 -> 26, that had actually been changed on staging for the main set of tests already in https://github.com/code-dot-org/code-dot-org/pull/9887 (just merged staging into this and kicking off more tests) — initially after running a smoke test of 14 builds of staging with the 4 browsers, 1 of the 14 builds ran out of memory in the UI test container (and seemed to be going along smoothly up until the memory issue): https://circleci.com/gh/code-dot-org/code-dot-org/18536

Re: `--magic-retry`, I will test swapping that in in a new branch. I was initially concerned the Circle tests would have a different flakiness pattern from those recorded on the main test server, & was looking to lock down the list of consistently failing Circle tests so was originally preferring long runs—but now that they seem to be consistent fewer retries makes sense.

**Comment by bcjordan** [comment]
@islemaster updated with details/logs from the 3 consistently Circle-failing tests being initially marked as `@no_circle` and rationale for merging with marking (rather than blocking this merge on investigation/resolutions for each).

**Comment by bcjordan** [comment]
Ran 8 more with staging merged in, all green. Noticed `SafariYosemite_maze` (non-Eyes test) do 1 "flaky rerun" on 3/8 branches, may just need explicit wait, prospective fix: https://github.com/code-dot-org/code-dot-org/pull/9891

**Pull request merged**
