### PR TITLE
Make Infosys logo appear in donor footer

### PR DESCRIPTION
**Pull request by islemaster**
Reported by @dju90 [in #plc-engineering](https://codedotorg.slack.com/archives/CC4U03GA0/p1584126038032200): The Infosys logo was missing when trying to thank them in the donor footer:

image (24)

Root cause: The donor is named as `Infosys Foundation USA` in [cdo-donor-schools.csv](https://github.com/code-dot-org/code-dot-org/blob/4c29179d62951f2bc1cc779708d31cce90f3182d/pegasus/data/cdo-donor-schools.csv#L702), which eventually drives the donor name for a particular user.  Donor logos are looked up by this same name in HomeController:

https://github.com/code-dot-org/code-dot-org/blob/4707717186c3b2718327a75528af45661efd2a37/dashboard/app/controllers/home_controller.rb#L199

But the Infosys logo was stored with the donor name `Infosys`, so no logo was found for `Infosys Foundation USA`.

Our solution is to move the logo to the correct location.

## Testing story

Checked manually - it's working now.

image

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dju90** [comment]
Lgtm!

**Review by hacodeorg — APPROVED** [review]

**Comment by breville** [comment]
I stick by my feedback from last year.. simple filenames are good: https://github.com/code-dot-org/code-dot-org/pull/30748#issuecomment-531422999

:)

**Comment by dju90** [comment]
We could change the filename to simply "infosys.png" as long as the folder name remains the same

**Comment by breville** [comment]
@dju90 In this case I think it's having a folder name with uppercase letters and spaces that is worth improving even more than the image filename.

**Comment by dju90** [comment]
The problem is that in the cdo-donors gsheet, the donor is called "Infosys Foundation USA"...are we okay having a mismatch between that name and the name in the cdo-donors-schools gsheet?

**Comment by breville** [comment]
We can use the "friendly string" but convert it to something cleaner for a file name before looking for a file, e.g.
``` 
> "Test string".parameterize(separator: '_')
=> "test_string"
```

**Pull request merged**
