### PR TITLE
Skip flaky workshops controller tests relating to time differences

### PR DESCRIPTION
**Pull request by TurnerRiley**
Comments out flaky workshop controller tests related to checking timing.

## Links
Discussion in this slack thread: [here](https://codedotorg.slack.com/archives/C0T0PNTM3/p1688410256254169?thread_ts=1688409788.597469&cid=C0T0PNTM3)

## Testing story
Locally ran test file with skipped tests and it was successful.

## Deployment strategy
Merging upon approval to unblock DTT. Will return to it soon to debug and re-enable (tracked in [this Jira ticket](https://codedotorg.atlassian.net/jira/software/c/projects/ACQ/boards/64?modal=detail&selectedIssue=ACQ-701)).

## PR Checklist:
- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by Hamms — COMMENTED** [review]
Rather than commenting out these tests, can we add `skip` directive explaining why we've done so? See https://github.com/code-dot-org/code-dot-org/blob/26334f6f8938fe99b901bcec813a98bc23a2ac74/dashboard/test/controllers/api/v1/pd/teacher_attendance_report_controller_test.rb#L84 for an example

**Comment by breville** [comment]
It looks like we just call `skip` with a message in some other tests?

**Review by thomasoniii — APPROVED** [review]
sure, lgtm 🚀 

About the only ruby code I'd feel I understand enough to approve. 😄

**Comment by TurnerRiley** [comment]
> Rather than commenting out these tests, can we add `skip` directive explaining why we've done so? See
> 
> https://github.com/code-dot-org/code-dot-org/blob/26334f6f8938fe99b901bcec813a98bc23a2ac74/dashboard/test/controllers/api/v1/pd/teacher_attendance_report_controller_test.rb#L84
> 
> for an example

Oh amazing I'll do that thank you!

**Pull request merged**
