### PR TITLE
Modified Notifications component to be tab navigable for co-teacher

### PR DESCRIPTION
**Pull request by kobryan0619**
In our bug bash we identified that when teachers are added as co-teachers and recieve the notification on their dashboard, that notification is not tab navigateable.  After some research, I determined this is due to how the `Notification` component renders its `buttons`.  

While reluctant to make changes to `Notification` because the component is used in 23 files, the `buttons` prop is only used in the `CoteacherInviteNotification` component.  None of the other files has this prop.  I modified the `Notifications` component to render the `buttons` without the `__useDeprecatedTag`.  Just in case, I added some logic to make sure if a button in `buttons` had a `link`, that would include the `__useDeprecatedTag`.  This is just an extra layer of protection to ensure that nothing breaks if in the future someone adds a button in the `buttons` prop that uses a `link` vs an `onClick`. 

image

[Jira Ticket](https://codedotorg.atlassian.net/jira/software/projects/TEACH/boards/65?selectedIssue=TEACH-731)

### CODE REVIEW

**Comment by dju90** [comment]
Thanks for making this notification more accessible for our users, Kaitie!

**Comment by lfryemason** [comment]
The `buttons` prop was something that I added [here](https://github.com/code-dot-org/code-dot-org/pull/54068) in order to create this notification, so I don't think we need to worry about breaking anything else.

Could we just use `tabIndex=0` to make the buttons navigable?

**Comment by lfryemason** [comment]
Or just remove the `__useDeprecatedTag` since nothing else is using the buttons prop and I probably just added that from copy/pasting the `button` prop? If this is an issue in the future, then we can add something similar to the code you added.

**Comment by kobryan0619** [comment]
> The `buttons` prop was something that I added [here](https://github.com/code-dot-org/code-dot-org/pull/54068) in order to create this notification, so I don't think we need to worry about breaking anything else.
> 
> Could we just use `tabIndex=0` to make the buttons navigable?

That makes more sense now.  I think I will go the route of just rending the buttons without the href option and remove the `useDeprecatedTag` since that is the direction we want to go in overall in our codebase.   I made this change - let me know if that looks good to you!

**Review by lfryemason — APPROVED** [review]
LGTM

**Review by lfryemason — APPROVED** [review]

**Pull request merged**
