### PR TITLE
Fix re-layout-during-deletion exception

### PR DESCRIPTION
**Pull request by bcjordan**
# Before

param-deletion-issue-broken
# After

param-deletion-issue-fixed

### CODE REVIEW

**Comment by bcjordan** [comment]
This may actually be a good candidate for a blockly-core test

**Comment by islemaster** [comment]
I still don't really how replacing the parameter causes the null-relayout, but the fix makes sense.

To test this, would you essentially write a test that sets up the contract editor, swaps the block, then closes it?

**Comment by bcjordan** [comment]
@islemaster it's actually just having a block within the function definition block that used to trigger the error:

simple-repro

**Comment by islemaster** [comment]
LGTM :grin:

**Pull request merged**
