### PR TITLE
Fix some scripts that were associated with released professional lear…

### PR DESCRIPTION
**Pull request by mehalshah**
…ning courses, move them to the legacy courses

### CODE REVIEW

**Comment by mehalshah** [comment]
Diffed against staging because this is a candidate for Wednesday deploy.

Right now, there are a number of scripts associated with CS in Algebra PD, CS in Science PD, and ECS Support that shouldn't be there. These are abandoned or incomplete scripts for the most part, but they show up as "Coming Soon" on the course view and are confusing to users.

**Comment by aoby** [comment]
This looks fine, but I'm unfamiliar with the script setup and therefore a little unclear as to what this is doing. Is that a valid script name? How will this rename fix the issue? Will they show up in a different script, or just not show up?

**Comment by aoby** [comment]
After syncing offline, LGTM

**Comment by mehalshah** [comment]
image

Thats what it looks like right now

**Pull request merged**
