### PR TITLE
allow headless blockSpace on IE

### PR DESCRIPTION
**Pull request by Hamms**
##### Background

A recent feature added "Initialization Blocks" (#8204); the option to declare some blocks in levelbuilder which would run before the user's code, allowing us to do things like define functions and declare constants.
##### Problem

The feature achieved this by running the saved XML through a headless, temporary BlockSpace to generate the initialization code, then prepending this code to the user's before execution. Here, "headless" is defined as "a BlockSpace built into an HTML element that isn't actually in the DOM." Although this setup is technically allowed by Blockly, it appears to be unused other than in this case, as evidenced by the fact that this feature is broken in IE11.

Specifically, the method `getComputedTextLength`, although defined for `text` elements, throws an `Unexpected call to method or property access` error when called on elements not in the DOM.

Double-checking that the element in question is actually in the DOM is a decent workaround, but it highlights the fact that we should perhaps not be instantiating an entire BlockSpace just for the purpose of converting some XML to code.
##### Potential alternatives include:
1. Save both the XML and the computed code in levelbuilder. We want to edit this code through the Blockly interface to support non-technical level designers, and a code-to-xml converter is way, way outside the scope of this feature, so saving just the code is not an option, but we could save both. There are many disadvantages to this approach, as there always are when saving the same thing twice.
2. Use the existing mainBlockSpace to generate the code. Either by storing the blocks invisibly in this BlockSpace alongside the user's blocks or by running them through it to generate the code before populating them with the start/user's blocks. In both cases, this is messy at best. The original motivation for the separate initialization section is because the levelbuilders were originally handling initialization blocks by putting them invisibly in the BlockSpace; this led to many problems.
3. Convert the XML directly to blocks and then to code without passing them through a BlockSpace. Currently, the xml-to-block creation - and Block initialization in general - is entangled with the concepts of BlockSpace compatibility and SVG creation, neither of which we care about in this specific case. We could disentangle them and allow for the creation of Blocks that have no BlockSpace. This has the potential to be complicated, but could result in something useful, and feels like the cleanest option.

I'm not convinced that any of these is a great solution, but I am convinced that the current approach is a bad one.

Thoughts? Ideas? General criticisms?

### CODE REVIEW

**Comment by Hamms** [comment]
@islemaster @Bjvanminnen @bcjordan I'd love to get your comments as well (along with anyone else who plays in Blockly land)

**Comment by islemaster** [comment]
Without much context, my intuition likes 3 best.  It seems likely to reuse the most existing code.  Conceptually, it seems like the easiest thing to build and test entirely within blockly-core, which may make it the most resilient option against future interactions with upstream blockly.

**Comment by Bjvanminnen** [comment]
Agree that number 3 sounds appealing, though I worry that it might be more challenging than we'd like.

**Comment by balderdash** [comment]
LGTM for this PR's temporary workaround.

**Comment by Hamms** [comment]
I fully expect that number 3 will end up being quite the hydra, but I very much like the idea of continuing to remove some of Blockly's many assumptions about global state. I'll poke at the beast a bit and see how riled up it gets.

Thanks!

**Pull request merged**
