### PR TITLE
Throw error on failed user migration

### PR DESCRIPTION
**Pull request by Hamms**
Now that we've been tracking migration failures for a while, we've
confirmed that in every situation in which a user account fails to
migrate, it does so because there is already an existing account with
matching credentials, and the user ended up on the "sign up" handler
when they should have ended up on the "sign in" handler.

With this change, users who do still end up on the "sign up" handler
will see an error; which should prompt them to try again; which should
direct them to the "sign in" handler. It's far from a perfect solution,
but it should prevent users from getting logged into an incorrect
account while we figure out a better one.

### CODE REVIEW

**Comment by maddiedierker** [comment]
should this work (or follow-up) include updating `User.find_by_hashed_email` to `User.find_by_credential` (from [this thread](https://github.com/code-dot-org/code-dot-org/pull/29646#discussion_r302793197))? this should help with the issue where users are ending up on the "sign up" route instead of "sign in"

**Comment by Hamms** [comment]
I don't think we actually want to do that; I dug into it a bit farther, and ran into issues where accounts were trying to take themselves over.

I think we actually do only want to do a takeover when we specifically find an account with a matching email, because that represents two accounts being created by two different and _distinct_ authorization methods (ie, email login and oauth login). The problem we're running into here represents two accounts being created by two pathways but with the same authorization method (ie, google classroom import and manual oauth account creation).

I think the solution is not to adjust the account takeover such that the manually created account correctly takes over the automatically created account, but rather to adjust the manual creation pathway so that it doesn't even happen if an automatically created account is present.

**Review by maddiedierker — APPROVED** [review]

**Comment by Hamms** [comment]
Added some test fixes & tweaks; PTAL

**Review by islemaster — APPROVED** [review]
Awesome!

**Review by maddiedierker — APPROVED** [review]

**Pull request merged**
