### PR TITLE
Track Experiment usage in GA

### PR DESCRIPTION
**Pull request by Hamms**
also update experiments.js to use ES6 variable declarations

### CODE REVIEW

**Comment by Hamms** [comment]
@ashercodeorg @Bjvanminnen FYI

**Comment by joshlory** [comment]
Looks like CircleCI is failing with `Can't find variable: trackEvent`.

One high-level question: this tracks when users turn experiments on and off — do we also want to track when an experimental feature is used?

**Comment by Hamms** [comment]
dang test environment not initializing all globals.

I'd say we want to do that on a case-by-case basis. Some experiments like unusedBlocks we already track, whereas others like topInstructions we can sort of assume are being used if the experiment is enabled.

**Comment by joshlory** [comment]
LGTM

**Comment by Bjvanminnen** [comment]
Not sure how widely we use trackEvent, but I know we've also used New Relic to track this sort of thing in some places in apps. Seems like it would be worthwhile for us to figure out when we prefer one over the other (and maybe just always use one).

**Pull request merged**
