### PR TITLE
Always show static projects link on dashboard page, don't remove if g…

### PR DESCRIPTION
**Pull request by jeremydstone**
For Hour of Code, we would like to turn on the existing gatekeeper flag `logged_in_studio_homepage` which removes non-static elements of the student/teacher logged in landing page.

Unfortunately the `logged_in_studio_homepage` flag is overambitious in one respect and also removes links to view projects and make a new app. These links are otherwise not very discoverable. This is static content and safe to show even during hour of code.

With this change, the Project section (shown in red box in screenshot) now appears with `logged_in_studio_homepage`=false, where previously it did not appear.
image

### CODE REVIEW

**Comment by breville** [comment]
To what degree is "View My Projects" static?  It's custom per-user, isn't it?

**Comment by breville** [comment]
Also the description says we now show that box when logged_in_studio_homepage=false, but aren't we attempting to turn this flag on, i.e. true?

**Comment by poorvasingal** [comment]
@breville - it's the same link for everyone (studio.code.org/projects), so we should be fine with keeping that here.

**Comment by jeremydstone** [comment]
In normal mode, that flag is true, we would like to turn it to false for HOC.

**Comment by jeremydstone** [comment]
@breville good question on if the links are per-user. I believe they are entirely static, but please sanity check me on this.

`render partial: 'home/projects'` renders this partial:
https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/views/home/_projects.html.haml

Which seems entirely static. It also renders this partial:
https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/views/projects/_links.html.haml 

Which also seems entirely static. But see if you agree w/me on that assessment!

**Comment by breville** [comment]
Ah, so description should say that we're actually turning that gatekeeper flag off?

When I visit studio.code.org/projects it makes me sign in and then it generates a custom list of my existing projects.  Not sure that counts as static?

**Comment by jeremydstone** [comment]
Yes, I did not articulate the flag change clearly.
For HOC I would like to change `logged_in_studio_homepage` from not present (defaults to `true`; gives our current production behavior) to `false`, which turns off most dynamic features on the homepage.

You pointed out a problem in my PR; I was causing the project links to show up when NOT signed in, where they had not appeared previously. Fixed. Now the non-signed in home page is identical before and after my PR. The signed-in page is identical in our normal mode (`logged_in_studio_homepage` not present, or `true`). But now in `logged_in_studio_homepage` => `false` mode, dynamic features are dropped (as they were before my change) but Project static links now show.

**Comment by breville** [comment]
The screenshot still shows a "View My Projects" button which, when signed in, takes the user to a page with a custom generated list of my projects.  Are we still showing that button when in scale mode, and is that destination page desirable?

**Comment by poorvasingal** [comment]
Yes showing that button is desirable so CSP students know how to access their projects page.  I might be wrong but I believe CSF students don't use /projects very much, so we shouldn't be getting a ton of traffic to that page.

**Comment by breville** [comment]
If @poorvasingal is good with behaviour than code lgtm.

**Pull request merged**
