### PR TITLE
Update oauth2 and faraday in preparation for omniauth upgrade

### PR DESCRIPTION
**Pull request by joshlory**
Extracted from PR https://github.com/code-dot-org/code-dot-org/pull/27248. Updated with:

```
bundle update --source oauth2 faraday
```

### CODE REVIEW

**Review by maddiedierker — COMMENTED** [review]
have you verified locally that google sign-in still works with just this change (i.e., minus other changes in #27249)? i want to double-check because the [`googleauth`](https://github.com/code-dot-org/code-dot-org/blob/5b7f28def10c171aa329e3f6b10161641d6e465f/Gemfile.lock#L459) and [`signet`](https://github.com/code-dot-org/code-dot-org/blob/5b7f28def10c171aa329e3f6b10161641d6e465f/Gemfile.lock#L784) gems require faraday ~>0.9

**Comment by joshlory** [comment]
I think `faraday 0.15.4` still satisfies the `~> 0.9` requirement, based on my understanding of the ["twiddle wakka" operator](http://robots.thoughtbot.com/post/2508037841/twiddle-wakka) (great name). It should translate to `>= 0.9.0` and `< 1.0.0` which we're meeting w/ the new version.

**Comment by maddiedierker** [comment]
ah, okay, i had misunderstood `~> 0.9` to mean `0.9.0 >= x < 0.10.0`, but i've definitely never been tested on that knowledge before 😅

**Review by maddiedierker — APPROVED** [review]

**Comment by joshlory** [comment]
Same, I had to look it up 😄. I think `~> 0.9.0` would mean `0.9.0 >= x < 0.10.0` but without specifying a patch version it only locks major version.

**Pull request merged**
