### PR TITLE
Reverts PR#8383.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This migration was killed, as a result of taking longer than expected. Since we do not want to run with the next DTP, it is being reverted. As later migrations ran successfully, there is no change to the timestamp in the schema.rb file.

The intent is to run this migration as a script sometime in the future.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @laurelfan @balderdash

**Comment by bcjordan** [comment]
LGTM

**Comment by balderdash** [comment]
How do you know it got killed? It shows up as `up` when I run `rake db:migrate:status`.

**Comment by balderdash** [comment]
Oh sorry, yeah we had to kill it to get the DTP out, but I started it again on production-console after the push was complete, and the migration finished after ~5 hours.

I should probably have sent out my DotD report earlier.

**Comment by ashercodeorg** [comment]
Per @balderdash, here is confirmation.

```
ubuntu@production-console:~/production/dashboard$ rake db:migrate:status
   up     20160517131521  Populate hashed email skipping validation
```

and

```
mysql> SELECT COUNT(0)
FROM users
WHERE email IS NOT NULL AND email <> "" AND (hashed_email IS NULL OR hashed_email = "");
+----------+
| COUNT(0) |
+----------+
|        0 |
+----------+
```

**Pull request closed without merging**
