### PR TITLE
Make donors page mobile-ready

### PR DESCRIPTION
**Pull request by hacodeorg**
1 of 2 requirements in [PLC-365](https://codedotorg.atlassian.net/browse/PLC-365).
https://code.org/about/donors

**Before**
Screen Shot 2019-09-09 at 12 25 39 PM

**After**
Screen Shot 2019-09-09 at 12 25 52 PM

### CODE REVIEW

**Review by breville — APPROVED** [review]
I tried it out and it works well.

**Review by clareconstantine — APPROVED** [review]
I'm not familiar with the change you made/how this system works, but the before and afters look good to me!

**Comment by breville** [comment]
cc @Erin007 who's the expert on this process.

**Comment by Erin007** [comment]
Yay! Nice work, Ha. Resizing and code looks good to me.

**Pull request merged**
