### PR TITLE
use unicorn instead of rackup/WEBrick to run dashboard in CircleCI UI tests

### PR DESCRIPTION
**Pull request by davidsbailey**
### Summary
use `unicorn` instead of `rackup` to run dashboard server during CircleCI UI tests, borrowing the command line for doing so from https://github.com/code-dot-org/code-dot-org/pull/5348.

### Results
passing:
* https://circleci.com/gh/code-dot-org/code-dot-org/27911 (without pixelation fix)
* https://circleci.com/gh/code-dot-org/code-dot-org/27913 (without pixelation fix)
* https://circleci.com/gh/code-dot-org/code-dot-org/27914 (pixelation disabled)
* https://circleci.com/gh/code-dot-org/code-dot-org/27916
* https://circleci.com/gh/code-dot-org/code-dot-org/27918
* https://circleci.com/gh/code-dot-org/code-dot-org/27921
* https://circleci.com/gh/code-dot-org/code-dot-org/27922
* https://circleci.com/gh/code-dot-org/code-dot-org/27923
* https://circleci.com/gh/code-dot-org/code-dot-org/27925

failing badly:
* https://circleci.com/gh/code-dot-org/code-dot-org/27920 selenium errors include:
  * undefined method `[]' for nil:NilClass (NoMethodError)
  * timed out after 120 seconds (Selenium::WebDriver::Error::TimeOutError)
  * timed out after 120 seconds (no such element: Unable to locate element: {"method":"id","selector":"runButton"}
    * --> saucelabs error: "The requested URL could not be retrieved. Zero size reply." ([sauce](https://saucelabs.com/tests/6d88b46f6c0e442fbaf2e691c7ec473c))

### Problem tests
Throughout the last few test runs, the same tests continue to fail initially, then pass on retry:
```
Davids-MacBook-Pro-2:~/src/cdo2 (circle-unicorn-bundle)$ bin/circle/search-circle-builds --grep "UI tests failed with" --start 27907 --end 27925 --whole-lines | grep -o "UI tests failed with <b>[^<]\+</b>" | cut -d ' ' -f 5 | sort | uniq -c | sort -r -n -k 1
  24 <b>ChromeLatestWin7_plc_courseUnitNavigation</b>
  24 <b>ChromeLatestWin7_pixelation</b>
  16 <b>ChromeLatestWin7_teacher-dashboard</b>
  12 <b>ChromeLatestWin7_netsim_lobby</b>
   9 <b>ChromeLatestWin7_craft_dialogs</b>
   7 <b>ChromeLatestWin7_hourOfCodeFinish</b>
   5 <b>ChromeLatestWin7_disableToolboxMaze</b>
   5 <b>ChromeLatestWin7_applab_sharedApps</b>
...
```

### Conclusions
* running unicorn in CircleCi works, but doesn't seem to fix any current problems.
* The "Zero size reply" error appears to be new, but may be a different form of a previously encountered error that just looks different with unicorn.
* "undefined method `[]' for nil:NilClass (NoMethodError)" must not be entirely the fault of rackup or WEBrick since it shows up here running unicorn instead.

### Caveats
I noticed that while running `unicorn` in a circleci container we appear to be reaching the open file limit:
```
ubuntu@box270:~/code-dot-org/dashboard$ tail -f log/test.log 
tail: inotify resources exhausted
tail: inotify cannot be used, reverting to polling
```
This warning did not appear when running dashboard via `rackup` during UI tests. This is concerning, but doesn't seem to be directly causing any problems with the test run.

### CODE REVIEW

**Comment by davidsbailey** [comment]
Request for comments @islemaster and @bcjordan . I'm not currently planning on merging this unless we think there is a reason to do so, and then probably only after a day or two to see what impact other recent fixes have had.

**Comment by islemaster** [comment]
Scanning this build range for error messages and known issues, maybe to compare against frequency in past reports and on [my experiment branch](https://github.com/code-dot-org/code-dot-org/pull/12293).

Manually filtering results to builds 27911, ...13, ...14, ...16, ...18, ...20, ...21, ...22, ...23, ...25.

# Bad Gateway
Only happens once in ten runs, notable since in the past we've seen Bad Gateway errors continue until the end of a run.
```
╰○ bin/circle/search-circle-builds --start 27911 --end 27925 --grep "Bad Gateway" --count

Build https://circleci.com/gh/code-dot-org/code-dot-org/27920 output contains 1 of: Bad Gateway
```
Here's the [Circle log](https://circleci.com/gh/code-dot-org/code-dot-org/27920#tests/containers/1), [Cucumber log](https://cucumber-logs.s3.amazonaws.com/circle/27920/ChromeLatestWin7_jigsaw2_output.html?versionId=pvKE6YPClpPheqUpO9NqfRcFAx9hP0AR), [SauceLabs session](https://saucelabs.com/tests/5ecbe24850f24355bb5128f29af8e646) for the one Bad Gateway error.  Doesn't reveal much - it's not the beginning or end of a series of failures, and it happens in build 27920 which had myriad other issues.

# sd_markdown_render
As expected, I found no evidence of the `RedCarpet` crash in these builds.

# too many connection resets
Only happens once in ten runs, similar frequency to what we get with proposed `idle_timeout` fix [over here](https://github.com/code-dot-org/code-dot-org/pull/12293).
```
╰○ bin/circle/search-circle-builds --start 27911 --end 27925 --grep "too many connection resets" --count

Build https://circleci.com/gh/code-dot-org/code-dot-org/27916 output contains 1 of: too many connection resets
```
Here's the full error (from the [CircleCI build log](https://circleci.com/gh/code-dot-org/code-dot-org/27916#tests/containers/1))
```
ChromeLatestWin7_plc_courseUnitNavigation first selenium error: too many connection resets (due to end of file reached - EOFError) after 0 requests on 29040220, last used 1481002858.4733398 seconds ago (Net::HTTP::Persistent::Error)
```

# Timed out after
```
╰○ bin/circle/search-circle-builds --start 27911 --end 27925 --grep "timed out after" --count

Build https://circleci.com/gh/code-dot-org/code-dot-org/27911 output contains 3 of: timed out after
Build https://circleci.com/gh/code-dot-org/code-dot-org/27913 output contains 3 of: timed out after
Build https://circleci.com/gh/code-dot-org/code-dot-org/27914 output contains 4 of: timed out after
Build https://circleci.com/gh/code-dot-org/code-dot-org/27916 output contains 3 of: timed out after
Build https://circleci.com/gh/code-dot-org/code-dot-org/27918 output contains 2 of: timed out after
Build https://circleci.com/gh/code-dot-org/code-dot-org/27920 output contains 50 of: timed out after
Build https://circleci.com/gh/code-dot-org/code-dot-org/27921 output contains 3 of: timed out after
Build https://circleci.com/gh/code-dot-org/code-dot-org/27922 output contains 1 of: timed out after
Build https://circleci.com/gh/code-dot-org/code-dot-org/27923 output contains 3 of: timed out after
Build https://circleci.com/gh/code-dot-org/code-dot-org/27925 output contains 3 of: timed out after
```

Build 27920 (the bad one) has an awful lot of these timeout errors, and most of them are on a page like this if you click through to the screencast:
image
What is [Squid](http://www.squid-cache.org/) and how did it get involved here?

Checking a few of the other builds I don't see this type of failure - it seems more like one-off flakiness caused by different timing of how things load.  In general it's looking like unicorn bounces back from problems better than rackup does, giving re-runs better odds of success.

# First selenium error
Not sure how helpful this is, but here's detail on the selenium errors encountered in these builds.  Excluding 27920 which isn't particularly helpful since there's some sort of catastrophic server failure there.
```
╰○ bin/circle/search-circle-builds --start 27911 --end 27925 --grep "first selenium error" --whole-lines

Build https://circleci.com/gh/code-dot-org/code-dot-org/27911 output contains lines:
  ChromeLatestWin7_teacher-dashboard first selenium error: timed out after 120 seconds (no such element: Unable to locate element: {"method":"id","selector":"user_name"}
  ChromeLatestWin7_craft_dialogs first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_hourOfCodeFinish first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_netsim_lobby first selenium error: expected: true
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"

Build https://circleci.com/gh/code-dot-org/code-dot-org/27913 output contains lines:
  ChromeLatestWin7_pixelation first selenium error: expected: "0000001100000010010"
  ChromeLatestWin7_craft_dialogs first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_hourOfCodeFinish first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_pixelation first selenium error: expected: "00000011000000100101"
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"
  ChromeLatestWin7_applab_sharedApps first selenium error: timed out after 120 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_teacher-dashboard first selenium error: unexpected response, code=404, content-type="text/plain"

Build https://circleci.com/gh/code-dot-org/code-dot-org/27914 output contains lines:
  ChromeLatestWin7_functionEditor first selenium error: timed out after 120 seconds (no such element: Unable to locate element: {"method":"id","selector":"runButton"}
  ChromeLatestWin7_disableToolboxMaze first selenium error: timed out after 120 seconds (no such element: Unable to locate element: {"method":"id","selector":"runButton"}
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"
  ChromeLatestWin7_bounce first selenium error: timed out after 120 seconds (no such element: Unable to locate element: {"method":"id","selector":"runButton"}
  ChromeLatestWin7_craft_dialogs first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_teacher-dashboard first selenium error: unexpected response, code=404, content-type="text/plain"
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"

Build https://circleci.com/gh/code-dot-org/code-dot-org/27916 output contains lines:
  ChromeLatestWin7_teacher-dashboard first selenium error: timed out after 120 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_craft_dialogs first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_netsim_lobby first selenium error: timed out after 120 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: too many connection resets (due to end of file reached - EOFError) after 0 requests on 29040220, last used 1481002858.4733398 seconds ago (Net::HTTP::Persistent::Error)

Build https://circleci.com/gh/code-dot-org/code-dot-org/27918 output contains lines:
  ChromeLatestWin7_pixelation first selenium error: expected: "000001000000001000000011000111100010001110111"
  ChromeLatestWin7_craft_dialogs first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"
  ChromeLatestWin7_pixelation first selenium error: expected: "000000110000001001011111"
  ChromeLatestWin7_netsim_lobby first selenium error: timed out after 120 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_teacher-dashboard first selenium error: unexpected response, code=404, content-type="text/plain"

Build https://circleci.com/gh/code-dot-org/code-dot-org/27921 output contains lines:
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"
  ChromeLatestWin7_hourOfCodeFinish first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_netsim_lobby first selenium error: timed out after 30 seconds (no such element: Unable to locate element: {"method":"css selector","selector":".join-button"}
  ChromeLatestWin7_applab_sharedApps first selenium error: timed out after 120 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"
  ChromeLatestWin7_teacher-dashboard first selenium error: unexpected response, code=404, content-type="text/plain"

Build https://circleci.com/gh/code-dot-org/code-dot-org/27922 output contains lines:
  ChromeLatestWin7_teacher-dashboard first selenium error: unknown error: Cannot read property 'click' of undefined
  ChromeLatestWin7_pixelation first selenium error: expected: "00000011000000100101"
  ChromeLatestWin7_multi2 first selenium error: expected: true
  ChromeLatestWin7_applab_embed first selenium error: no selenium error found
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"
  ChromeLatestWin7_netsim_lobby first selenium error: expected: true
  ChromeLatestWin7_applab_sharedApps first selenium error: timed out after 120 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_teacher-dashboard first selenium error: unexpected response, code=404, content-type="text/plain"
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"

Build https://circleci.com/gh/code-dot-org/code-dot-org/27923 output contains lines:
  ChromeLatestWin7_applab_embed first selenium error: timed out after 120 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_craft_dialogs first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_netsim_lobby first selenium error: timed out after 120 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_teacher-dashboard first selenium error: unexpected response, code=404, content-type="text/plain"
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"

Build https://circleci.com/gh/code-dot-org/code-dot-org/27925 output contains lines:
  ChromeLatestWin7_craft_dialogs first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_plc_courseUnitNavigation first selenium error: unexpected response, code=404, content-type="text/plain"
  ChromeLatestWin7_hourOfCodeFinish first selenium error: timed out after 20 seconds (Selenium::WebDriver::Error::TimeOutError)
  ChromeLatestWin7_netsim_lobby first selenium error: timed out after 30 seconds (no such element: Unable to locate element: {"method":"css selector","selector":".join-button"}
  ChromeLatestWin7_teacher-dashboard first selenium error: unexpected response, code=404, content-type="text/plain"
```

**Comment by islemaster** [comment]
My own conclusions here:

* Failure rate baseline of 10% being on par with the experiments branch is great.
* ~This appears to solve the `RedCarpet` crash as expected :+1: Not sure if it includes Josh's workaround?~ Actually, this branch contains [Josh's `RedCarpet` workaround](https://github.com/code-dot-org/code-dot-org/pull/12247) so we can't really say whether unicorn fixes that problem.  Could revert that PR on this branch to verify.
   ```
   ╰○ git branch -a --contains 4846afa
     remotes/origin/circle-unicorn-bundle
   ```
* Not _sure_ it's solved but I haven't found clear evidence of mixed-up requests (I've been digging through screencasts of timeout errors, which is where those have showed up in the past).  That supports the hypothesis that the mix-ups are caused by our servers not being thread-safe, not by sauceconnect.
* I'd _really_ like to know more about the catastrophic failure in [27920](https://circleci.com/gh/code-dot-org/code-dot-org/27920) and the associated squid-cache error.  It might be worth more trials on unicorn to estimate the rate of these catastrophic failures, and how it compares to the catastrophic "Bad Gateway" errors we get on Rackup (that's currently 5% on the experiment branch).
* **All other things being equal, I think switching to unicorn is a good idea** :white_check_mark: because it means fewer differences between Circle and our real test & prod environments.  In fact, it's probably worth dealing with a few new Circle issues to do this.

**Comment by bcjordan** [comment]
Agree, sounds worth the switch ✅ :+1:.

**Comment by davidsbailey** [comment]
To answer your question, Josh's targeted fix for the markdown issue https://github.com/code-dot-org/code-dot-org/pull/12247 was included in all of the above test runs.

I'm in agreement with you guys that we should merge this now.

**Pull request merged**
