### PR TITLE
Update oldest_active_level to work with new ScriptLevel props

### PR DESCRIPTION
**Pull request by balderdash**
ScriptLevel level properties are now under properties['variants'], not at the top level. Update `oldest_active_level` and the ScriptLevel controller tests accordingly.

### CODE REVIEW

**Comment by balderdash** [comment]
Yeah, level swaps stopped taking effect, e.g. new students who go to https://studio.code.org/s/course2/stage/4/puzzle/7 are getting the old, not-so-great level at the moment.

**Comment by Bjvanminnen** [comment]
Does this indicate a gap in our test coverage that we were able to regress this?

**Comment by balderdash** [comment]
Yes, but I'm not sure how best to fix this.

The tests we have would have caught this if not for the mismatch between the format of the properties blob used in our real data and the one we used in the tests. We could test against real scripts, but then levelbuilder changes could break dashboard unit tests, which feels wrong. Maybe we should be validating the shape of the properties blob?

**Comment by Bjvanminnen** [comment]
Would it make sense to have a variant level in `allthethings` (that does not also exist elsewhere, and thus will not be changed by LBs) + an eyes test?

**Pull request merged**
