### PR TITLE
Fallback to loading startBlocks if lastAttempt throws an exception

### PR DESCRIPTION
**Pull request by joshlory**
Also fixes 'Start Over' on project levels.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
lgtm. do we have any visual indicator on whether the blocks in the workspace are currently the default start blocks vs. blocks loaded from my last run?

**Comment by islemaster** [comment]
Should I be concerned that this introduces an infinite recursion if the default start blocks throw an exception while being loaded?

**Comment by joshlory** [comment]
Yep the progress dot will be green or yellow if you've previously attempted the level:

screen shot 2015-03-10 at 10 48 18 am

But we show this even if the attempt is identical to the start blocks, so we don't need to reset the UI if loading the last attempt failed.

**Comment by joshlory** [comment]
Good catch Brad, I'll fix.

**Comment by islemaster** [comment]
Totally my bad.  There is not infinite recursion, you already took care of it.  Might be nice to re-throw the exception if we're not going to handle it though.

**Comment by joshlory** [comment]
Ah, you're right.  I should read my own code more carefully :smile:.  Updated to re-throw in 8da6784.

**Pull request merged**
