### PR TITLE
ARIA labels for chevrons in applab

### PR DESCRIPTION
**Pull request by bencodeorg**
We have several expand/collapse chevrons in Applab. Adds ARIA labels for each of these, and an `aria-expanded` attribute to describe the state of the chevron.

## Links

https://codedotorg.atlassian.net/browse/A11Y-26

## Testing story

Tested with a screen reader in Applab and Gamelab projects that tab navigating to each of these read the correct label.

## Follow-up work

Unfortunately, there's a similar chevron once you click "Design" in Applab that isn't currently tab navigable. Work item here to make it tab navigable and add an ARIA label. 

https://codedotorg.atlassian.net/browse/SL-440

### CODE REVIEW

**Review by epeach — COMMENTED** [review]
I think this is a great place to add ARIA tags to cover this dynamic experience. While I was reviewing, I was reminded of the `aria-expanded` attribute: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded
It might be worth looking in to that attribute to see if that might be useful here to express when the debug/toolbox are open/closed. Thoughts?

**Comment by bencodeorg** [comment]
> I think this is a great place to add ARIA tags to cover this dynamic experience. While I was reviewing, I was reminded of the `aria-expanded` attribute: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded It might be worth looking in to that attribute to see if that might be useful here to express when the debug/toolbox are open/closed. Thoughts?

This looks quite promising, thanks! Let me dig into it

**Comment by bencodeorg** [comment]
@epeach took another pass, LMK what you think! The chrome screenreader read "[aria-label] [aria-expanded current state] button", so "toolbox expanded button" in the case where the toolbox is currently expanded. Does that sound right?

**Review by epeach — APPROVED** [review]
Looks good to me! Thanks for bringing in aria-expanded - great to see that!

**Pull request merged**
