### PR TITLE
Skip validation on user save in SchoolInfoInterstitialHelper.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes this [Honeybadger issue](https://app.honeybadger.io/projects/3240/faults/33496135). Issue is caused by teachers missing an email address.

### CODE REVIEW

**Comment by breville** [comment]
Is this the right fix?  Or do we want to make sure our validation is expanded?

**Comment by aoby** [comment]
@breville Ideally we'll fix the underlying issue, but at the moment some of our old data (teachers who converted from student accounts before we required emails) don't pass validation. Yet we want the validation for future upgrades.

Actually we could scope that validation to only `if: :email_changed?`. This might be a better general solution, to grandfather in existing users as long as they're not changing their email. Like [here](https://github.com/code-dot-org/code-dot-org/blob/6536262fdc048b293608a5b8a1f7c5b4a3a58d26/dashboard/app/models/pd/workshop_material_order.rb#L64)

**Comment by ashercodeorg** [comment]
This is something I don't think we want to do, as it would allow further violations by allowing a user to change from a student account to teacher account.

**Comment by aoby** [comment]
We could gate it on `if: -> {email_changed? || user_type_changed?}`

**Comment by ashercodeorg** [comment]
That's a thought. Let me think on it.

**Pull request merged**
