### PR TITLE
Rename 'Hour of Code' tutorial title to 'Classic Maze'

### PR DESCRIPTION
**Pull request by breville**
**studio.code.org**
screenshot 2015-12-03 13 03 38

**teacher dashboard**
screenshot 2015-12-03 13 03 47

**script overview**
screenshot 2015-12-03 13 04 16

**script title**
screenshot 2015-12-03 13 04 29

### CODE REVIEW

**Comment by breville** [comment]
fyi @philbogle

**Comment by philbogle** [comment]
LGTM

**Comment by tanyaparker** [comment]
Can you also update for /learn? Both in HocTutorials and in i18n gsheet, I think key is hourofcode_name.

**Comment by breville** [comment]
Fixed those gsheets with @tanyaparker looking over my shoulder.  They'll be scooped on staging as usual.

**Pull request merged**
