### PR TITLE
Revert websocket connection test

### PR DESCRIPTION
**Pull request by bencodeorg**
Removes code from our websocket connection test, which we turned off (via DCDO flag) this afternoon.

[Basically reverts this PR](https://github.com/code-dot-org/code-dot-org/pull/43941/files), but GitHub couldn't do an automatic revert for some reason.

## Testing story

Tested manually that I could load the teacher dashboard and an Applab project after this change.

### CODE REVIEW

**Review by sanchitmalhotra126 — COMMENTED** [review]
Is there any reason we might want to keep this code around? Would it make sense to hide it behind a flag instead of deleting it entirely? I can't think of why we'd need to keep it around, but just curious.

**Comment by bencodeorg** [comment]
> Is there any reason we might want to keep this code around? Would it make sense to hide it behind a flag instead of deleting it entirely? I can't think of why we'd need to keep it around, but just curious.

The core of it still exists here:

https://code.org/educate/websocket
https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/educate/websocket.html#L48

Of course it's in our history if we really want it back, but I figure it's better to declutter without any clear immediate use case.

**Comment by sanchitmalhotra126** [comment]
> > Is there any reason we might want to keep this code around? Would it make sense to hide it behind a flag instead of deleting it entirely? I can't think of why we'd need to keep it around, but just curious.
> 
> The core of it still exists here:
> 
> https://code.org/educate/websocket https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/educate/websocket.html#L48
> 
> Of course it's in our history if we really want it back, but I figure it's better to declutter without any clear immediate use case.

Cool yep, makes sense.

**Review by sanchitmalhotra126 — APPROVED** [review]

**Review by jmkulwik — APPROVED** [review]
Nice cleanup!

**Pull request merged**
