### PR TITLE
Make sure that the assign text and buttons show in the right spot

### PR DESCRIPTION
**Pull request by dmcavoy**
[Amanda reported](https://codedotorg.slack.com/archives/CNZP84FJ5/p1621549314044000) that the assign text and icon on the student view in Safari looked weird. I went in and updated things so everything aligns nicely now on safari and chrome.

Screen Shot 2021-05-24 at 5 18 52 PM
Screen Shot 2021-05-24 at 5 18 48 PM
Screen Shot 2021-05-24 at 5 18 59 PM

### CODE REVIEW

**Comment by bethanyaconnor** [comment]
The assign to section button isn't looking right to me:

on latest staging:
Screen Shot 2021-05-25 at 9 36 23 AM

on this branch:
Screen Shot 2021-05-25 at 9 41 24 AM

(I get the same behavior on chrome and safari)

**Comment by dmcavoy** [comment]
Screen Shot 2021-05-25 at 1 06 09 PM

@bethanyaconnor i think i fixed

**Comment by bethanyaconnor** [comment]
Not to be that person but the buttons are still a bit mis-aligned, though not nearly as noticeably
Screen Shot 2021-05-25 at 11 14 08 AM

My opinion is that this isn't a ship-blocker though.

**Review by bethanyaconnor — APPROVED** [review]

**Comment by dmcavoy** [comment]
@bethanyaconnor you are totally right. I will go back and try to track that down too. Thank you for your thoughtful review

**Comment by dmcavoy** [comment]
Screen Shot 2021-05-25 at 12 52 36 PM

**Comment by dmcavoy** [comment]
Screen Shot 2021-05-25 at 2 53 27 PM

**Pull request merged**
