### PR TITLE
Refresh DataViews after each data modifying action

### PR DESCRIPTION
**Pull request by snickell**
This is related to, and intended to fix https://github.com/code-dot-org/code-dot-org/issues/56347

### CODE REVIEW

**Comment by snickell** [comment]
@cnbrenci and I traced how calls flow when you change the DataView to the Key Value Pairs tab by clicking it:

1. In the browser, we click Key Value tab
2. The onClick handler runs: `this.props.onViewChange(DataView.PROPERTIES)`
3. onViewChange() is passed in from DataBrowser.jsx, which runs `dispatch(changeView(DataView.PROPERTIES, null))`
4. On dispatch, redux store runs `case CHANGE_VIEW` which runs state.set('view', DataView.PROPERTIES)
5. in applab, setupReduxSubscribers is subscribed to store.subscribe(), so this hook gets called because state changed
6. the setupReduxSubscribes subscription then inspects state.view and calls onDataViewChange(DataView.PROPERTIES, null, null)
7. onDataViewChange then invokes `Applab.storage.subscribeToKeyValuePairs()` to load relevant data, and sets callbacks when the data is loaded
8. The callbacks from Applab.storage.subscribeToKeyValuePairs() then calls redux to update the loaded kvp data: `getStore().dispatch(updateKeyValueData(keyValueData))`

**Comment by snickell** [comment]
So lets focus on the Key Value Pair tab's "Add Pair button" 
1. Add Pair Buttons `onClick` handler in AddKeyRow.jsx calls `storageBackend().setKeyValue(newKey, newVal)`

IN FIREBASE MODE:
- `loadDataForView()` has setup a callback `storage.subscribeToKeyValuePairs()`, which sets up a Firebase Subscription to notify when any key value data changes in Firebase
- Firebase notices that a key value has changed, and calls the callback, which invokes a redux change: `getStore().dispatch(updateKeyValueData(keyValueData))`
- Which invokes `state.set('keyValueData')`
- This triggers redux's connect() function changing the keyValueData prop passed to KVPairs(), which then redraws the rows with the new Key Value Pair row.

IN DATABLOCK MODE:
TBD

**Comment by snickell** [comment]
TODO next time: test implementation of clicking "Add pairs" button in Key Value Pair tab

**Review by cnbrenci — APPROVED** [review]
Yaaaaaaaaaaas!!

**Pull request merged**
