### PR TITLE
FND-1431: Section Lock

### PR DESCRIPTION
**Pull request by JamesHankinsDev**
##### *_***NOTE: This PR is dependent on PR-#40172: Create i18n translations on client and server side_*

User Story: As a teacher, I can lock down my section code and prevent users from joining it

#### _API Changes to `dashboard/`_:
- Add migration to include `restrict_section` column in sections table
- Update `add_student` reject logic to include restricted
- Introduce restricted logit to `follower_controller` and `sections_controller`
- Created new `inline_alert` flash for `folowers_controller` and included conditional alert in `student_user_new` haml
- ###### _**Automatic file changes made to models inheritting from `Section` model_

#### _Front-End Changes to `apps/`_:
- Create 'Restrict this section' field in `EditSectionForm`
- Add `JoinSectionRestrictedNotification` for `JoinSectionNotifiaction`
- Include new `restrictSection` field in `sectionShape` and `teacherSectionsRedux`

Screenshots/video at the end

## Links

- spec: [Probelm 2](https://docs.google.com/document/d/1Pl7sOO_TKo9zWH0Qv8_HBKzaIM2JNTXnE5Fq0YYUv3I/edit#heading=h.x757xf8ral1d)
- jira ticket: [Section Lock Down: FND-1431](https://codedotorg.atlassian.net/browse/FND-1431)

## Testing story

Existing tests comparing data shapes for AJAX requests, as well as comparing newly created `:Section` models updated to include new data point.

Client-side and Server-side tests added to confirm error and alert handling for new `retsrict_section` functionality.

##### Client-side
- `JoinSectionRestrictedNotification` case added to `JoinSectionNotifications` test in `JoinSectionNotificationsTest.rb` file

##### Server-side
- `join with a restricted section code` test added to `sections_controller_test.rb` file
- `student_user_new errors when joining a restricted section` test added to `followers_controller_test.rb` file

##### Client-side
- `restrict_section` and `restrictSection` values/variables added to `teacherSectionsReduxTest` file.
- `restrict_section`/`restrictSection` validation case added to `transfers some fields directly, mapping from snake_case to camelCase` test in `teacherSectionsReduxTest` file.

##### Server-side
- `restrict_section` field added to mock `:Section` objects for comparison in `section_test.rb` file

##### i18n integration for client and server-side.
- These locations should be commented with a `TODO`

## PR Checklist:

- [X] Tests provide adequate coverage
- [X] Privacy and Security impacts have been assessed
- [X] Code is well-commented
- [X] New features are translatable or updates will not break translations
- [X] Relevant documentation has been added or updated
- [X] User impact is well-understood and desirable
- [X] Pull Request is labeled appropriately
- [X] Follow-up work items (including potential tech debt) are tracked and linked

#### Before
Before
#### After
After

#### Before
https://user-images.githubusercontent.com/25508215/115083858-e51f3500-9ebc-11eb-94e3-9c231a37296a.png

https://user-images.githubusercontent.com/25508215/115083789-c9b42a00-9ebc-11eb-9719-4edf4006a823.png
#### Before
https://user-images.githubusercontent.com/25508215/115083917-fc5e2280-9ebc-11eb-99a7-1edfaee5e2f4.mov
#### After
https://user-images.githubusercontent.com/25508215/115084343-9b831a00-9ebd-11eb-983f-ee9d926758b5.mov

#### Before
https://user-images.githubusercontent.com/25508215/115083936-02540380-9ebd-11eb-90be-71da505f0560.mov
#### After
https://user-images.githubusercontent.com/25508215/115084351-a2119180-9ebd-11eb-8acb-827e531caa55.mov

#### Before
https://user-images.githubusercontent.com/25508215/115083938-02ec9a00-9ebd-11eb-9b29-6ce33683eeae.mov
#### After
https://user-images.githubusercontent.com/25508215/115084354-a2aa2800-9ebd-11eb-9bdf-d4ce3f01e809.mov

### CODE REVIEW

**Comment by dju90** [comment]
Can we use the i18n strings in this PR? In general, shipping features that are translatable from the start is the direction we'd like to move as an organization.

**Comment by JamesHankinsDev** [comment]
Hey @dju90  -> Sorry for the delay in getting the other PR up. You should be linked to that one as a reviewer as well, but it can be found here: PR- #40172: Create i18n translations on client and server side

I've rebased this branch to be dependent on that one, so and additionally have updated this branch to remove the strings and only utilize the i18n functionality set up in PR-#40172: Create i18n translations on client and server side 

Let me know if there are any other changes/alterations you'd like to see on this branch!

**Comment by dju90** [comment]
In the fourth screencap it looks like the sign in flow hits the error pathway. Per the spec,

> Req 3. Students who are already in the section should still be able to sign in using the section code
> This flow should work as normal: 
> Picture password: Sign in -> type in section code -> choose name -> select picture password
> Word password: Sign in -> type in section code -> choose name -> type in word password
> Email: Sign in -> enter email and password

This is an easy adjustment for picture and secret word login types (and may already be accounted for in your code).

For the email + password login type, we'll still want to prompt the user the register for an account (as we do today) with the link to sign in if they already have one (since this is a possible entry point for existing students in the section). If the user opts to register for an account, currently we redirect them to the Unit page of the course assigned to that section with a success message on top, like so:
image
For locked sections, we should instead redirect them to My Dashboard (https://studio.code.org/home) and show the error message surfaced in these other places ("We couldn't add you to section {sectionId} because it is locked. Please contact your teacher for help.")

Sorry for the addition to the original spec, but I didn't realize this was an entry point until now! So thank you for finding this edge case.

**Comment by dju90** [comment]
Erring on the side of caution, the worst case scenario is that we have a surge of teachers using this feature and a resulting deluge of tickets complaining that students can't join sections via the section code. With this in mind, can we ship this under a feature flag so that if needed we can quickly roll it back if necessary? After it's been out in the wild for a bit, we can remove the flag.

**Comment by JamesHankinsDev** [comment]
@dju90 Sorry for the time it took to get these updates implemented. Pending drone test checks, this should be good for another look now.

A quick note, I'm not sure how to check the firehose triggers, but used some of the other firehose event triggers as a template here. I'm guessing there is either a GoogleAnalytics component or something similar to check impressions, and this is to just log engagement, but would love to confirm that here if possible?

**Comment by dju90** [comment]
sounds good; depending on when you merge, we can schedule a bug bash on staging. maybe we can merge on Wednesday morning?

I'm pretty sure we query firehose logs in Redshift; we can do `SELECT * FROM analysis.events WHERE study='lock_section' AND study_group='display_lock_section'`

**Comment by dju90** [comment]
Alternatively, if we want to avoid the risk of having to revert due to something discovered during the bug bash, we can spin up an ad-hoc and test it there. Let me know what you prefer!

**Comment by JamesHankinsDev** [comment]
@dju90 No preference for me. Is one messier and/or more of a standard than the other?

**Comment by dju90** [comment]
I think we usually use ad-hocs for things that require extensive testing. Doesn't seem to me like we have too many test cases for this feature, so I think staging should be sufficient if you're confident it works on localhost.

**Comment by JamesHankinsDev** [comment]
@dju90 Sounds good. Just double checked everything locally and that all feels pretty good on my end!

**Review by hacodeorg — APPROVED** [review]
LGTM! You really understand our codebase. Thanks for doing this, James.

**Pull request merged**
