### PR TITLE
Add set/remove tint blocks for gamelab jr

### PR DESCRIPTION
**Pull request by balderdash**
image

FYI @caleybrock, @mrjoshida: With this PR, `Sprite.tint` and `Group.setTintEach` will work in gamelab sr, but I'm not adding it to the palette or the autocomplete config because there's no documentation yet.

### CODE REVIEW

**Comment by mrjoshida** [comment]
We've wanted this for Senior for a while, let's not block on documentation getting it into the pallete. I'll work on getting a documentation page up.

**Comment by balderdash** [comment]
Added them to the palette, @epeach could you take a look at https://github.com/code-dot-org/code-dot-org/pull/21557/commits/5051a49ee686841d1480dc7872c4acee571c02e1?

**Comment by epeach** [comment]
LGTM! I'm excited to see this in GL!

**Comment by balderdash** [comment]
@joshlory there's no "tint amount" option, so you can only vary the color intensity by using more/less saturated tint colors. In a pinch, you can do this:

image

**Pull request merged**
