### PR TITLE
Organize level models inside a `levels/` directory

### PR DESCRIPTION
**Pull request by joshlory**
Put all the models for the `Level` single table inheritance into one folder.  Based on the answer to this question: http://stackoverflow.com/questions/18934115/rails-4-organize-rails-models-in-sub-path-without-namespacing-models.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
My vote would be to keep `Level` (the base class) in the "base" directory. Otherwise, this looks awesome!

**Comment by ashercodeorg** [comment]
Though tab completion simplicity would be nice, it'd also be nice to see the model files for DB tables in the base directory (e.g., there is a `levels` table, though not a `applab` table). By no means am I blocking the PR as-is, though.

**Comment by joshlory** [comment]
Any further comments here?  I'm leaning slightly towards leaving `Level` in `models/levels/level.rb`.

**Comment by ashercodeorg** [comment]
SGTM. And it'd be trivial to move the file later, if we find a compelling reason to do so.

**Pull request merged**
