### PR TITLE
Add display_name to lesson group properties

### PR DESCRIPTION
**Pull request by dmcavoy**
# Background
A couple times last week we ran into issues with the deploy process because of an error message about lesson groups:

https://codedotorg.slack.com/archives/C0T0PNTM3/p1593212136198600
https://codedotorg.slack.com/archives/C0T0PNTM3/p1593117321183600
This issue is resulting from the fact that when someone adds a brand new lesson group to the script dsl we can't serialize the .script file with the correct display name because the scripts.en.yml file needs to be reloaded before it registers the new entry for the new lesson group.

# Fix
My plan was to add the properties field to lesson groups. 
Then save the display name into the properties field. <- **We are here.**
Then change the serialization to pull from the property instead of directly from the localized string. <- **and here.**

# Testing

I ran bundle exec rake build locally and then check a couple objects in my database to make sure they got the correct information. I also tested the issue that I had repo'd before and it was no longer an issue.

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
Nice fix!

**Comment by davidsbailey** [comment]
Is it important for the lesson group properties display_name to get updated during seed? or does that not actually affect anything?

**Comment by dmcavoy** [comment]
@davidsbailey it will impact the serialization of the lesson group. For example when you go to hit edit on a script that serialization will be based on the display_name in the properties

**Review by davidsbailey — COMMENTED** [review]
OK, I see it now. Looks good!

**Pull request merged**
