### PR TITLE
Fix CSF workshop attendance gsheet export

### PR DESCRIPTION
**Pull request by clareconstantine**
In https://github.com/code-dot-org/code-dot-org/pull/39120, I updated the development version of `config.yml.erb` but didn't add the gsheet key to the production version; correcting that now.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by bencodeorg — APPROVED** [review]
I'm confused why this is necessary, as I think in [the PR you're basing this off](https://github.com/code-dot-org/code-dot-org/pull/32597) of did not do this? Any ideas (for my understanding)?

**Comment by bencodeorg** [comment]
@sureshc has explained this to me before but I forget 🤦 . He might be able to help us understand best practices here!

**Comment by sureshc** [comment]
The problem appears to be that even though #39120 was merged a few days ago, the key it added to `.config.yml.erb` is not present in the version of that file in the latest commit in the `production` branch.

https://github.com/code-dot-org/code-dot-org/blob/7afafe266114218c7bf3d41397412145844c8fc2/config.yml.erb#L456-L459

We shouldn’t need the change in this Pull Request. We should review the commit history on the `staging`, `test`, and `production` branches to identify how the change in the original Pull Request got reverted.

**Comment by bencodeorg** [comment]
> The problem appears to be that even though #39120 was merged a few days ago, the key it added to `.config.yml.erb` is not present in the version of that file in the latest commit in the `production` branch.
> 
> https://github.com/code-dot-org/code-dot-org/blob/7afafe266114218c7bf3d41397412145844c8fc2/config.yml.erb#L456-L459
> 
> We shouldn’t need the change in this Pull Request. We should review the commit history on the `staging`, `test`, and `production` branches to identify how the change in the original Pull Request got reverted.

Thanks for the clarification!

**Pull request closed without merging**
