### PR TITLE
Add qwikcamps to OAUTH_PROVIDERS list.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Does [ApplicationHelper#external_oauth_sign_out_url](https://github.com/code-dot-org/code-dot-org/blob/aa23981e2a1b04f4d57a5015c4dec04e17dd9a40/dashboard/app/helpers/application_helper.rb#L125-L134) need updating as well? If so, with what values?

Note that this was precipitated by some data checking for tangential feature development by @ewjordan.

**Comment by ewjordan** [comment]
I'm fine with adding this to the list, I think, but do we have any idea what it actually is and whether it works? I'd really love @jeremydstone or @wjordan to comment, I don't know that I have enough background to approve it.

**Comment by jeremydstone** [comment]
Discussed with @ashercodeorg. The LTI provider is a little unusual in that it may authorize a number of different applications from the same provider gem. Each LTI+application combination gets written out as a unique provider in the users table. I wanted to understand the intent of adding the `lti_lti_prod_kids.qwikcamps.com` string to the list and it turns out it is to make the `user.oauth?` method do the right thing here by comparing to what's stored in `user.provider`. So this looks like the right thing to do. LGTM.

**Comment by ashercodeorg** [comment]
@jeremydstone: Can you address my question on `ApplicationHelper#external_oauth_sign_out_url`?

**Comment by ewjordan** [comment]
@jeremydstone does that mean that in general, people can use oauth providers that we haven't explicitly added support for? How would that login/connect flow even work?

**Comment by jeremydstone** [comment]
@ashercodeorg there is not a Qwikcamps custom "you are signed out" page that I am aware of so we don't need to add anything to `external_oauth_sign_out_url` for LTI/Qwikcamps

**Comment by jeremydstone** [comment]
@ewjordan great question. Any additional LTI applications need to form a relationship out of band with us and we exchange a key pair that authorizes them. That gets stored in `CDO.lti_credentials`. An LTI application uses the LTI oauth framework to authorize and signs with an application-specific key that we verify. Right now the only LTI application we have done key exchange with is Qwikcamps.

**Comment by joshlory** [comment]
Is it possible to test these OAuth flows?

**Pull request merged**
