### PR TITLE
Enforce Format of Resource Key

### PR DESCRIPTION
**Pull request by Hamms**
This will be required for the resourcelink preprocessor syntax, but it's also just generally good practice.

## Testing story

Added a unit test, updated a couple existing tests that were using invalid keys

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by Hamms** [comment]
Discussion topic: do we actually _want_ to support periods in these keys? I'm inclined to say we shouldn't

**Comment by bethanyaconnor** [comment]
> do we actually want to support periods in these keys? I'm inclined to say we shouldn't

I agree. We likely only need to support letters, numbers, and some sort of delimiter (dashes and/or underscores will do)

**Review by bethanyaconnor — APPROVED** [review]

**Comment by Hamms** [comment]
It does occur to me that we likely have several Resources throughout our various environments that are currently violating this rule. I'm not familiar with all the ways Resources are currently created or updated; is that going to cause problems?

**Comment by bethanyaconnor** [comment]
The majority of the resources in our system were created by the import script, which just copied the keys directly from curriculum builder. I'm going to guess that's the bulk of resources with a key that's violating this rule. Going forward, resources should only be created through the lesson editor, or the all resources page (which doesn't yet exist). That editor doesn't allow keys to be set manually on resources so they should all be going through `generate_key_from_name`.

The key shouldn't be updated, though I don't think we have any explicit checks in place for that on the model. But again, keys can't be manually updated in the editor so the chance is low.

**Review by dmcavoy — APPROVED** [review]

**Comment by Hamms** [comment]
It looks like `generate_key` only happens on create; if keys can't be updated manually, that means that any resource which currently has an invalid key will be unable to be updated at all. Is that going to cause problems?

**Comment by bethanyaconnor** [comment]
Ah yeah that will likely be a problem. Do you have an estimate on how many resources have invalid keys? Either way we should create a ticket to clean up the resources with invalid keys, but the urgency is likely tied to how many there are.

**Comment by Hamms** [comment]
Oh! I didn't know Resources were seeded from script_json. I'll just update all invalid keys here in this PR

**Comment by bethanyaconnor** [comment]
There will likely be a follow up step to check if those keys are used anywhere in the markdown. But that could definitely be done as a follow up (and might already be on your radar).

**Comment by Hamms** [comment]
Haha, yep; markdown syntax was unsurprisingly one of the first things on my mind :)

**Comment by bethanyaconnor** [comment]
haha I figured, just mentioned it because that's part of the reason we copied the keys directly from CB when we did the import :)

**Review by bethanyaconnor — APPROVED** [review]

**Pull request merged**
