### PR TITLE
Remove unit redirects

### PR DESCRIPTION
**Pull request by dmcavoy**
We are removing the unit redirects between units in a unit group. To do this we need to remove `version_year` and `family_name` from units in unit groups. To do this I ran the following in the dashboard console. 

```
Script.all.each do |script|
  if script.unit_group && (script.version_year || script.family_name)
    script.version_year = nil
    script.family_name = nil
    script.update!(skip_name_format_validation: true)
    script.write_script_json
  end
end
```

## Links

https://codedotorg.atlassian.net/browse/PLAT-1135

## Testing story

- Removed UI test for csp redirect

### CODE REVIEW

**Review by davidsbailey — COMMENTED** [review]
What happens now when you go to /s/csd1?

It looks like we might also need to remove these from https://github.com/code-dot-org/code-dot-org/blob/06b4cdb603f0ce4aa03a4f6917c7b463bf5c7b42/lib/cdo/script_constants.rb#L298

**Comment by dmcavoy** [comment]
> What happens now when you go to /s/csd1?

It gives an error. We can have it permanently go to a certain year instead.

> It looks like we might also need to remove these from
> 
> https://github.com/code-dot-org/code-dot-org/blob/06b4cdb603f0ce4aa03a4f6917c7b463bf5c7b42/lib/cdo/script_constants.rb#L298

Why do you think we need to remove these?  Some of the things in the list are still being used directly. The whole list is only used in one place which does not impact this.

**Comment by davidsbailey** [comment]
> > What happens now when you go to /s/csd1?
> 
> It gives an error. We can have it permanently go to a certain year instead.

I think the most work we would want to do here is to send any /s/csd[1-N] to /courses/csd (and same for csp), and the least we should do is to 404 (rather than 5xx). normally I would ask Tess what she thinks in this situation :-) my inclination would be not to break the URL, and add permanent redirects (e.g. to /courses/csd).

> 
> > It looks like we might also need to remove these from
> > https://github.com/code-dot-org/code-dot-org/blob/06b4cdb603f0ce4aa03a4f6917c7b463bf5c7b42/lib/cdo/script_constants.rb#L298
> 
> Why do you think we need to remove these? Some of the things in the list are still being used directly. The whole list is only used in one place which does not impact this.

Just to clarify, I am only suggesting removing the items from this list which are no longer being used as family names, e.g. csp1 thru N, csd1 thru N. The reason to remove them would be if those entries have become dead code, or if they are leading to wrong behavior (e.g. an error response).

Sorry not to have dug in yet here, but i guess my counter question would be whether entries in this list like csd1 are still being used for anything?

**Comment by dmcavoy** [comment]
I'll hold on this PR until Tess is back or we can get someone from product to weigh in on the redirect. I was doing it while it was top of mind from the maker homepage work but it can wait a little bit.

**Comment by davidsbailey** [comment]
waiting seems fine to me, but this also seems like a perfectly reasonable thing to ask another product person to weigh in on if you'd rather not let it sit for too long. your choice :-)

**Pull request closed without merging**
