### PR TITLE
School Info Confirmation Dialog:  remove experiment flag

### PR DESCRIPTION
**Pull request by nkiruka**
This PR is to remove the SCHOOL_INFO_CONFIRMATION_DIALOG experiment flag so that the schoolInfoConfirmationDialog is shown when a teacher is prompted to update school info.

[Reference: Set Experiment Flag](https://github.com/code-dot-org/code-dot-org/pull/28653)

### CODE REVIEW

**Review by bethanyaconnor — APPROVED** [review]
🎉 

Will [the flag itself](https://github.com/code-dot-org/code-dot-org/blob/8b929fab1151bdd64b7b30f07deb9e1ea7e346ee/apps/src/util/experiments.js#L24) be removed in a future PR?

**Comment by Erin007** [comment]
_Also_ remove from here: https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/util/experiments.js#L24 please.

**Review by Erin007 — APPROVED** [review]
Wahooo! Excited for this to launch! Great work here and throughout to get this ready for the world.

**Comment by bethanyaconnor** [comment]
➕ to what Erin said!

**Comment by nkiruka** [comment]
Thanks y'all.  Merged.

**Pull request merged**
