### PR TITLE
prevent overwriting existing file when creating new dsl level

### PR DESCRIPTION
**Pull request by davidsbailey**
Finishes https://codedotorg.atlassian.net/browse/PLAT-1371 . A brief overview of the codepath is available [here](https://docs.google.com/document/d/1f7zYx9zrj75_5QQMG_YIW0-VZAhsFyizf4gt5QdU5Zs/edit).

## Screenshots

After creating an External level named "foo bar" locally, a file named "foo_bar.external" appears. Then I am prevented from creating a level named "foo_bar":

### create

https://user-images.githubusercontent.com/8001765/138184532-8cb4b303-071f-40df-a4ed-4db41421d975.mov

### clone

https://user-images.githubusercontent.com/8001765/138184538-c8b1baa1-e2dc-4af5-841a-10cb3bfa305d.mov

## Testing story

* screenshots show manual testing
* New unit tests cover added behavior
* UI test failure in drone run looks unrelated

### CODE REVIEW

**Review by dmcavoy — APPROVED** [review]
Looks good. Did you check the AddLevelsDialog to make sure the errors get surfaced there as well?

**Comment by davidsbailey** [comment]
> Looks good. Did you check the AddLevelsDialog to make sure the errors get surfaced there as well?

Whoa, good catch, I had no idea that we were creating levels from that dialog! This appears to be failing even for valid level names:
Screen Shot 2021-10-21 at 11 57 54 AM

the error in the XHR response is: `Validation failed: Name is too short (minimum is 1 character)`. It's possible this was never working for DSL levels, which expect the level name to be in the `dsl_text` param, unlike other level types. I'm opening an issue to track this here: https://codedotorg.atlassian.net/browse/PLAT-1392

So, to validate that my PR isn't making things any worse, I confirmed that the AddLevelDialog is hitting the same `LevelsController#create` method. when I put a `raise` in the beginning of that method, I get the same blanket "Could not create level" warning shown in the screenshot, and the error details are printed to the js error console. I think that probably means we are good here, but it would be nice to show the error details, so I'll make a super short follow up PR for that: https://github.com/code-dot-org/code-dot-org/pull/43115

**Comment by dmcavoy** [comment]
Thanks for checking. Its sounds likely that it wasn't heavily tested because it wasn't used a lot when migrating over courses.  You can also clone levels in the Find Level side. Can you also just check that works as planned?

**Comment by davidsbailey** [comment]
Here is one more quick improvement, to show a shorter error message when we hit the new check in this PR:
Screen Shot 2021-10-21 at 12 46 49 PM

**Comment by davidsbailey** [comment]
> Thanks for checking. Its sounds likely that it wasn't heavily tested because it wasn't used a lot when migrating over courses. You can also clone levels in the Find Level side. Can you also just check that works as planned?

Another good catch! Cloning seems to be working for dsl levels there, and I was able to confirm that my new error message is showing up:
Screen Shot 2021-10-21 at 12 51 02 PM

**Pull request merged**
