### PR TITLE
Remove content from promote

### PR DESCRIPTION
**Pull request by CaptainStack**
- Removed Change.org content and associated JavaScript which, according to Amy, will not be used in the future.
- Removed some of the stats/informational content from the infobox
- Moved remaining JavaScript to a helpers file in /shared.

### CODE REVIEW

**Comment by CaptainStack** [comment]
@breville Should just take a quick minute. There's not really anything in here we didn't go over in the office.

**Comment by joshlory** [comment]
Can we just deleted the commented out code?  We can always pull it back later from the source history.

**Comment by CaptainStack** [comment]
@joshlory Yeah no reason we can't. I figured leaving it in might be a convenience for the developer who has to put it back in, especially if that developer isn't and doesn't have a ton of context for what was removed, when, and why. That said, I don't feel super strongly about it.

**Comment by wjordan** [comment]
- This pull request would serve as our reference if we ever happen to need to re-add this feature in the future. If our current stance is that we won't need to use this moving forward, I'm also in favor of removing the code from our main branch rather than leaving commented-out code mixed in with our other website logic.

- If this feature is being removed, do we no longer need to proxy api.change.org through our Varnish config? If so, then we should remove code blocks [here](https://github.com/code-dot-org/code-dot-org/blob/remove-content-from-promote/cookbooks/cdo-varnish/templates/default/default.vcl.erb#L269-L287) and [here](https://github.com/code-dot-org/code-dot-org/blob/remove-content-from-promote/cookbooks/cdo-varnish/templates/default/default.vcl.erb#L400-L406) from `default.vcl.erb` as well.

**Comment by CaptainStack** [comment]
@wjordan The stance is we don't need it for now, but might in the future. That said, it sounds like there's enough push to remove it, so I will.

Regarding your second question, I'd say we probably should remove that from the Varnish config, but I'd run it past @breville as he wrote that part of the code.

**Comment by breville** [comment]
lgtm.  fair comments about always removing dead code; though sometimes i'll leave something behind if there's an ongoing debate about the content being included or not.

i don't recall writing any varnish config support but agreed it's worth taking out if possible.

**Pull request merged**
