### PR TITLE
Revert "Revert "Application refactor""

### PR DESCRIPTION
**Pull request by tim-dot-org**
Depends on: https://github.com/code-dot-org/code-dot-org/pull/42389

See https://github.com/code-dot-org/code-dot-org/pull/40789 for the contents of the "revert revert" commit

From that PR:

All of the teacher application models-by-year are consolidated into a single TeacherApplication. The model-by-year was intended to let each year have specific logic, but only the most recent one is actually used and generally built off the previous years anyways. We can still subclass the new TeacherApplication model in case we want to have the old one temporarily (such as for when we make the switch over to the new application each year), but then it should be merged into the single TeacherApplication to keep maintenance low.
Similar changes for the PrincipalApprovalApplication.
Constants all merged into respective files. The constants files generate js files to be used on the front-end, but only the most recent year's file was being used currently.
Testing factories needed the most changes, as some old application models were still being used for testing (as in the teachercon/fit weekend tests).
Out of scope for this refactor is removing all the references to teachercon / fit weekend / facilitator applications. Some of these were referencing old versions of application models-by-year, but they were mostly referencing something from the base model, so that could be updated in place to the consolidated TeacherApplication.
No changes are needed on the front-end, since it references only the latest teacher application versions.

## Links

- jira ticket: [PLAT-1196](https://codedotorg.atlassian.net/browse/PLAT-1196)
- honeybadger error from first deployment: [error](https://app.honeybadger.io/projects/3240/faults/80317164)

## Testing story

Tested manually on local environment both up and down.

## Deployment strategy

At this point, probably a good idea to wait for the applications to be closed on Sept 20th.
Manually verify after migration using `bin/dashboard-sql-reader` with `select distinct(type) from pd_applications;`

### CODE REVIEW

**Comment by davidsbailey** [comment]
hi @tim-dot-org , I just took a high-level look at this. unless there's a special reason to bundle these, I'd suggest shipping the migration ahead of the code change. this is a best practice that we follow so that if the code change needs to be reverted, we don't have to tackle the tricky problem of rolling back the migration in production and other environments.

**Comment by tim-dot-org** [comment]
> 
> 
> hi @tim-dot-org , I just took a high-level look at this. unless there's a special reason to bundle these, I'd suggest shipping the migration ahead of the code change. this is a best practice that we follow so that if the code change needs to be reverted, we don't have to tackle the tricky problem of rolling back the migration in production and other environments.

Oh, good idea, that makes sense.

**Comment by bencodeorg** [comment]
If I remember correctly, the first attempt at this failed because we hadn't tested with older applications. Were you able to test with older applications this time around? Worth getting a production clone DB set up to check it out with some real data?

**Comment by tim-dot-org** [comment]
> 
> 
> If I remember correctly, the first attempt at this failed because we hadn't tested with older applications. Were you able to test with older applications this time around? Worth getting a production clone DB set up to check it out with some real data?

I've tested it locally using the https://github.com/code-dot-org/code-dot-org/pull/42389 (that PR is what really fixes the issue, this PR is exactly the same as the original) but doing a production clone would be a good idea, I'll look into getting that set up!

**Comment by bencodeorg** [comment]
Ah right, sorry should have commented there. Yeah I think this refactor is generally a big enough change worth testing with real data.

**Pull request merged**
