### PR TITLE
Submitted eyes test

### PR DESCRIPTION
**Pull request by Bjvanminnen**
We've broken the purple dots for submitted levels a couple times, so I thought we should add an eyes test. I didn't realize we had force_submittable, so I went and made a way to create students attached to teacher accounts via the UI. It's a little brittle in that it depends on some things like the first input element when adding a section being the section name, but I don't think that UI will be changing a lot.

I changed the other instances to also use this new approach, and then got rid of force_submittable.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Just realized we have a multi_submittable.feature that gets around this feature using force_submittable. I can probably fix that up to use this.

**Comment by breville** [comment]
Very cool.  Would it also be good to test that the dots get a submittable purple styling class associated with them, as well as an eyes test?  Still, this goes a long way to more deeply testing submittable which is great.  LGTM.

**Comment by Bjvanminnen** [comment]
If the dots don't get a purple styling class, that should break the eyes test already (since the second screen shot is after you've submitted and should have a purple dot).

**Comment by breville** [comment]
Of course.  Was just thinking that checking the styling on the DOM in addition to the eyes test would make for extra robust testing at a slightly deeper level than final pixels.

**Pull request merged**
