### PR TITLE
Restore version: Handle missing S3 version

### PR DESCRIPTION
**Pull request by islemaster**
Reverts code-dot-org/code-dot-org#21495, restores code-dot-org/code-dot-org#21459.

I can't locally repro the VCR failures we encountered yesterday with this change - it looks like something changed the channel id / project id in the test environment, but I'm not sure why:

```
VCR failure in get_source_blocks_profanity_violations:
Expected: GET https://cdo-v3-sources.s3.amazonaws.com/?encoding-type=url&prefix=sources_test/1/1/
Actual:   GET https://cdo-v3-sources.s3.amazonaws.com/?encoding-type=url&prefix=sources_test/3/3/
```

It's also passing on Circle.  Is it possible some other test is leaking state in the DB causing different channels to be assigned?

### CODE REVIEW

**Comment by islemaster** [comment]
Not necessarily ready for review - @wjordan do you have an recommendations for reproing this particular issue?

**Comment by islemaster** [comment]
:grimacing: `SourceTest` is consistently passing on Circle, and on my local machine both when I run that file in isolation and when I run `rake test` in `shared`.  I know it's crazy, but I'm tempted to just give this another shot as-is.  Concerns?

**Comment by islemaster** [comment]
I am seeing intermittent failures locally with `AssetsTest:test_assets_quota_newrelic_logging` that might be related to ordering - but it's not a VCR failure.

**Comment by epeach** [comment]
I'm down to give it another go. If it fails, we might be able to get more info about the cause.

**Pull request merged**
