### PR TITLE
Creates the bin/oneoff directory and adds invalidate_level_source_images.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
FYI @Hamms

**Comment by ashercodeorg** [comment]
FYI @aoby, if we do further clean-up of the `bin` directory, the `oneoff` subdirectory now exists.

**Comment by ashercodeorg** [comment]
Is `archive` a better name than `oneoff`?

**Comment by aoby** [comment]
`oneoff` is more appropriate here. I think of `archive` as the place we would store scripts only for reference purposes. They would never be executed from archive.

**Comment by jeremydstone** [comment]
LGTM

**Pull request merged**
