### PR TITLE
Major simplifications for donors page, fixing some UI glitches too.

### PR DESCRIPTION
**Pull request by breville**

### CODE REVIEW

**Comment by breville** [comment]
@CaptainStack how does this change look?

**Comment by CaptainStack** [comment]
I'd say this looks pretty good. Screenshot?

**Comment by breville** [comment]
i did center the platinum folks now, including the Ballmer item.. which i think is okay, but obviously the left-alignment could be done special just for that one

screenshot 2015-01-09 08 02 49
screenshot 2015-01-09 08 02 58
screenshot 2015-01-09 08 03 07

**Comment by CaptainStack** [comment]
Big improvement. Looks good to me!

**Comment by breville** [comment]
Thanks.  It turns out "border-collapse: collapse;" was the magic that let us do these grids nicely.

**Pull request merged**
