### PR TITLE
Pegasus DB: Add deleted_at column to poste_urls

### PR DESCRIPTION
**Pull request by molly-moen**
Enable soft deletion of poste_urls. See [PLC-937](https://codedotorg.atlassian.net/browse/PLC-937) for more details.

## Links

- [jira](https://codedotorg.atlassian.net/browse/PLC-937)

## Testing story
Tested that this column gets added as expected and existing rows have a deleted_at value of null.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by islemaster — COMMENTED** [review]
Are you planning to use [the `paranoia` gem](https://github.com/rubysherpas/paranoia) to interact with the `deleted_at` column?  If so, it might be a good idea to [follow their example](https://github.com/rubysherpas/paranoia#run-your-migrations-for-the-desired-models) and also add an index on `deleted_at`.  I'm not sure it gets used for much more than checking whether it's empty or not, but since the gem will implicitly include that column in all queries it's probably helpful for performance.

**Comment by molly-moen** [comment]
> Are you planning to use [the `paranoia` gem](https://github.com/rubysherpas/paranoia) to interact with the `deleted_at` column? If so, it might be a good idea to [follow their example](https://github.com/rubysherpas/paranoia#run-your-migrations-for-the-desired-models) and also add an index on `deleted_at`. I'm not sure it gets used for much more than checking whether it's empty or not, but since the gem will implicitly include that column in all queries it's probably helpful for performance.

@islemaster will paranoia work with a pegasus table?

**Comment by islemaster** [comment]
> @islemaster will paranoia work with a pegasus table?

:facepalm: Nope!  My bad.  Please disregard my comment.

**Review by islemaster — APPROVED** [review]

**Comment by sureshc** [comment]
I think we'll need the index on `deleted_at` since we'll be implementing queries that are very similar to what ActiveRecord and the paranoia gem generate. There are 3.5M rows currently in the table, so probably necessary to ensure lookups where `deleted_at IS NULL` are fast.

**Comment by islemaster** [comment]
It probably wouldn't hurt, but for this specific table I'm not sure it's necessary.  Every query I can find for `poste_urls` is using either the `id` or `hash` column to retrieve a single row.  Each of these columns already has a high-cardinality index and it's likely the query optimizer would use them over a `deleted_at` index even after we added a `deleted_at` constraint to the existing queries.  Unless we're planning to add queries for many rows (e.g. `where url=?`) I'm not sure we'll see a benefit from a `deleted_at` index.

**Review by sureshc — APPROVED** [review]

**Comment by molly-moen** [comment]
I think @islemaster is right, the queries on `poste_urls` will use the `deleted_at` column in addition to an `id` or `hash`. I'm not sure of the details of query optimization, @sureshc do you agree if all the queries are already per-row we wouldn't need an index on `deleted_at`?

**Comment by sureshc** [comment]
@islemaster logic sounds correct to me, so I approved the Pull Request. We could test by [cloning the production database](https://github.com/code-dot-org/code-dot-org/blob/f64dccc6233845c41b961872f82b36f54c1cd8a3/lib/rake/rds.rake#L4-L18), applying the schema change, and then running some queries (and asking the clone to provide the query plan as well). We could even provision an adhoc that uses that clone database and test the performance of the click tracking URL. Might be less effort to go ahead and add the index, since it's a common practice with ActiveRecord + paranoia.

We've had a few small performance glitches in production over the past year due to insufficient indexing. We operate at a large enough scale that even minor features can populate tables with several million rows. Indexes consume storage space (I think more than half of the storage on our production cluster are indices) and they incur a penalty during writes, because the index has to be updated at the same time that the row is inserted/updated/deleted, but I don't believe either of those are factors here.

**Comment by molly-moen** [comment]
@sureshc , makes sense. I think I will go ahead and add the index since it seems like the safest path.

**Comment by islemaster** [comment]
Agreed, adding an index seems safe in this case.

@sureshc to better inform my recommendations on this sort of thing in the future:

> Indexes consume storage space (I think more than half of the storage on our production cluster are indices) and they incur a penalty during writes, because the index has to be updated at the same time that the row is inserted/updated/deleted, but I don't believe either of those are factors here.

Are these not factors in this case because 3.5 million rows is not large enough for an index to be noticeably expensive?  I don't know much about implementation details here, but 3.5m DateTimes is about 27MB, which seems affordable enough. I'm also not sure what optimization happens for this case where most of them are null.  I don't have an intuition about how expensive writes are in that scenario.  Or are you referring to the fact that our production system isn't adding rows to this table anymore, so any write penalty is a moot point?

**Comment by sureshc** [comment]
@islemaster Sorry I wasn't clear. Yes - I think that an index on a date time column on a table with 3.5M rows would not consume much space (in comparison to the indexes on large tables like user_levels). And also, yes, we're not writing to this table anymore.

**Pull request merged**
