### PR TITLE
update team page

### PR DESCRIPTION
**Pull request by tanyaparker**
- make team photos consistently 100x100px
- add all team photo to top of page

**Before**
image

**After**
image

**Team photo**
image

### CODE REVIEW

**Comment by tanyaparker** [comment]
@breville some quick touch ups to this page. square works better with horizontal images. I tried making them wider, but Megan would still have to individually crop to make heads fit better. With square, we just need to resize the vertical images (which I think is just you and Brent).

**Comment by tanyaparker** [comment]
This view is used for our team page, leadership page, and contributors. And looks better across the board.

**Comment by breville** [comment]
That's fine with me.  I'm messaged you with my own crop of that team photo I did a while ago, which might cut down on the weird carpet colour a bit :)

I'm starting to prefer parameters that are a hash rather than just true/false fields, e.g. { square_photo: true }, just to improve readability.  But for a single new option it's not crucial.

**Comment by tanyaparker** [comment]
Ah, k. Using that image. And I'll rename to square_photo since that's better, and keep in mind to use hash for multi-param.

**Pull request merged**
