### PR TITLE
Allow editing blocks on view-only spritelab levels.

### PR DESCRIPTION
**Pull request by jmkulwik**
# Description
This is in response to a Zendesk ticket regarding: https://studio.code.org/s/express-2019/stage/26/puzzle/1 

OLD:
image

NEW:
image

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by epeach — APPROVED** [review]
This looks good - and I recognize that we need to unblock students. So not blocking, but can students edit the behavior once they view it? If so, is it possible to make that read-only?

**Review by maddiedierker — APPROVED** [review]
i'm unfamiliar with this area, but this logic makes sense to me 👍 

post-merge, can you add a jira task to cover this bug with a unit or UI test?

**Comment by jmkulwik** [comment]
> This looks good - and I recognize that we need to unblock students. So not blocking, but can students edit the behavior once they view it? If so, is it possible to make that read-only?

Great question. Viewing the behavior won't let them edit it. That is also read-only.

**Comment by jmkulwik** [comment]
> post-merge, can you add a jira task to cover this bug with a unit or UI test?

👍

**Pull request merged**
