### PR TITLE
Simplify count == 0 to empty?.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Is there a performance (other) reason to prefer `limit(1).count?`?

**Comment by philbogle** [comment]
I believe that in general limit(1).count is actually more efficient in some cases than the empty? implementation.  See the source code below, they actually count all the matching and then compare with 0. 

For this use case, there could be a decent number of usernames matching a particular prefix, so the difference could matter; therefore we probably don't want this change.   For readability, we could create an is_empty_relation? helper that does the efficient test.

```
def empty?
      return @records.empty? if loaded?

      if limit_value == 0
        true
      else
        c = count(:all)
        c.respond_to?(:zero?) ? c.zero? : c.empty?
      end
    end
```

**Comment by ashercodeorg** [comment]
Right, the `empty?` will be more performant in some cases (when `loaded`) and less in others (when a full count is done). Since we presumably care about the worst case, I agree with you, keeping the `limit(1)` makes sense.

That said, I think it makes sense to simplify the `count == 0` to `empty?`, so keeping that much since the PR is already here.

**Comment by philbogle** [comment]
LGTM

**Pull request merged**
