### PR TITLE
remove Secure Version link from dashboard footer

### PR DESCRIPTION
**Pull request by tanyaparker**
**before**
image

**after**
image

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @mehalshah , as this will touch some eyes tests.

**Comment by ashercodeorg** [comment]
Excising text LGTM. Given how forward facing this is, we should confirm it looks fine on various browsers and sizes?

**Comment by tanyaparker** [comment]
Confirmed on Chrome, Safari, FF, mobile, tablet.

**Comment by mehalshah** [comment]
Sorry I didn't see this earlier - this broke some tests as expected and I'll accept the new baseline

**Pull request merged**
