### PR TITLE
Update the buttons on code.org/districts

### PR DESCRIPTION
**Pull request by kelbyhawn**
Replace the existing **Enroll in Code.org’s District Program** button with two buttons: **Learn more** and **Enroll now** on https://code.org/districts

**Jira ticket:** [ACQ-1231](https://codedotorg.atlassian.net/browse/ACQ-1231)

----

## Before
Screenshot 2023-11-29 at 9 46 04 AM
Screenshot 2023-11-29 at 9 46 10 AM

## After
Screenshot 2023-11-29 at 9 45 33 AM
Screenshot 2023-11-29 at 9 45 44 AM

### CODE REVIEW

**Comment by dmcavoy** [comment]
Looks good to me!

**Review by bethanyaconnor — APPROVED** [review]

**Review by jmkulwik — APPROVED** [review]

**Review by cat5inthecradle — APPROVED** [review]

**Review by cat5inthecradle — CHANGES_REQUESTED** [review]
please rebase to staging

**Review by cat5inthecradle — APPROVED** [review]

**Comment by wilkie** [comment]
Canceling test run.

**Comment by cat5inthecradle** [comment]
pending drone run
https://drone.cdn-code.org/code-dot-org/code-dot-org/37000

**Pull request merged**
