### PR TITLE
update dance puzzle 12 translations

### PR DESCRIPTION
**Pull request by davidsbailey**
rename all translations belonging to level `Dance_Party_11.5` to point instead to level `Dance_Party_11_5`, carefully excluding any references to level `Dance_Party_11.5_test`.

### CODE REVIEW

**Comment by breville** [comment]
Does the key also need to be changed in `dashboard/config/scripts/levels/Dance_Party_11.5_test.level` and `dashboard/config/scripts/levels/Dance_Party_11_5.level`?

**Comment by breville** [comment]
There seem to be 24 "authored_hints" changes but 26 "long_instructions" files and 25 "short_instructions" files and 1 "callouts" file.  Are those expected discrepancies?

**Comment by davidsbailey** [comment]
Thanks for the attention to detail on this, Brendan!

> Does the key also need to be changed in dashboard/config/scripts/levels/Dance_Party_11.5_test.level 

No, I'm leaving this level alone in this PR. The callout id referenced there is still defined in callouts.en.yml. Also, that level is not referenced in any script, so there wouldn't be any user-facing impact if I've missed something.

> and dashboard/config/scripts/levels/Dance_Party_11_5.level?

Yes, nice catch! I've updated the callout `localization_key` to `dance_party_11_5_groups`. However, I'm leaving https://tts.code.org/sharon22k/180/100/9003baa437b4aa76484191d252a5c801/Dance_Party_11.5.mp3 because renaming that would break the url. I'm not sure how to keep this link from breaking in the next sync, but I can make a note to check it after the next i18n sync and/or follow up with @Hamms  on Monday.

> There seem to be 24 "authored_hints" changes but 26 "long_instructions" files and 25 "short_instructions" files and 1 "callouts" file. Are those expected discrepancies?

Good observation, however this discrepancy already exists in our codebase. What I've done here is replace every instance of `Dance_Party_11.5` appears to refer to level `Dance_Party_11.5` and not level `Dance_Party_11.5_test`. 

To embellish a bit more: callouts are singular because they are not translated. I believe the other discrepancies are simply because the individual phrases have been translated in a some languages but not others. for example, a few days ago I pushed branch https://github.com/code-dot-org/code-dot-org/compare/staging...dance-11-5-translations?expand=1 which modified only 43 occurrences because that's how many existed before the yesterday's i18n sync, whereas this PR now modifies ~76 occurences.

**Comment by davidsbailey** [comment]
My plan is to test this on staging in a few different languages, and then pull in Elijah for further review before the next i18n sync.

**Comment by davidsbailey** [comment]
I was able to verify that this is working on an adhoc: https://adhoc-dance-12-translations-studio.cdn-code.org/s/dance/stage/1/puzzle/12 so I haven't merged it to staging yet and will wait for triage before doing so.

**Pull request merged**
