### PR TITLE
Add header parameter to startWebRequest

### PR DESCRIPTION
**Pull request by evilcrash**
api.amadeus.com was recently added to the API, despite the fact it can't be used without a certain header. with newer APIs tending to use API keys and having them be passed through a request header, it seems only logical to allow headers to be passed through to startWebRequest.

this PR expands upon startWebRequest's implementation of XMLHttpRequest by checking if the header parameter is passed to startWebRequest. if so, then take that header and pass it to req.

## Testing story
the tests in this PR are sufficient as I'm simply adding a parameter

## PR Checklist:
- [X] Tests provide adequate coverage
- [X] Privacy and Security impacts have been assessed
- [X] Code is well-commented
- [X] New features are translatable or updates will not break translations
- [X] Relevant documentation has been added or updated
- [X] User impact is well-understood and desirable
- [X] Pull Request is labeled appropriately
- [X] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by evilcrash** [comment]
@ajpal @Erin007

**Comment by epeach** [comment]
@evilcrash - Thanks for opening this PR. We are tracking this task internally and will loop back when it's prioritized and assigned.

**Comment by evilcrash** [comment]
sounds good to me

**Comment by jmkulwik** [comment]
Hi @evilcrash, please take a look at our [contributing guidelines](https://github.com/code-dot-org/code-dot-org/blob/01eb4573ff66c719783dd6eae97e385e4fd45741/CONTRIBUTING.md). We can't accept pull requests from anyone who hasn't signed our Contributor License Agreement. Please start with that step and we'll go from there!

**Comment by evilcrash** [comment]
signed as me@elijahs.space

**Comment by evilcrash** [comment]
any updates?

**Pull request closed without merging**
