### PR TITLE
package changes for node v6

### PR DESCRIPTION
**Pull request by Bjvanminnen**
Ended up being a minimal set of changes.

As part of the upgrade we'll also want to do the following things on both dev machines and build machines.
`rm -rf node_modules`
`npm install`
`npm run clean` (or just `rm -rf build`)

Not sure if it makes more sense to do these as manual one offs, or to create a rake task.

In terms of testing I did:
I ran for a couple of days with node v6 and node v6 installed node_modules
Made sure website worked, tests passed, `npm run storybook` still seemed to work.

We'll probably want to do some amount of monitoring when we merge these node 6 PRs. Not sure when the best time to do this will be.

### CODE REVIEW

**Comment by wjordan** [comment]
LGTM as far as I can tell. is `grunt-parallel` added here as a newly-required optional/transitive dependency, or something else entirely?
We'll also want to update the [`engines`](https://docs.npmjs.com/files/package.json#engines) fields in our various `package.json` files to reflect the change, though that field is more informative/documentation than anything important (won't break anything if it's out of date if i recall).

**Comment by Bjvanminnen** [comment]
The grunt-parallel thing was a little bit weird. If grunt-express doesn't see a loaded grunt-parallel, it tries to load it itself. However, it was failing to find the package when doing so (I assume this is because newer versions of npm end up with a different directory structure for node_modules). By explicitly stating a dependency on grunt-parallel, it ends up being loaded into grunt as part of our wildcard grunt-load-tasks, such that grunt-express doesn't then try to load it.

I'll update engines.

**Comment by Bjvanminnen** [comment]
@islemaster The issue I'd seen on circle seemed to be linux specific. Do you think you could try this PR out some point? (You'll want to upgrade to node v6.9 then blow away/reinstall node_modules, and probably also delete apps/build to be safe).

**Comment by islemaster** [comment]
I can check this out tomorrow.

**Comment by islemaster** [comment]
Switched to Node v6.9.0 and removed apps/node_modules and apps/build.  Was able to successfully do the following:
- [x] `npm install`
- [x] `npm test`
- [x] `npm run build`
- [x] `npm run build:dist`
- [x] `npm start`

Local dev environment seemed to be working well after each one.  This LGTM!

**Pull request merged**
