### PR TITLE
Remove Playground

### PR DESCRIPTION
**Pull request by bencodeorg**
Remove code related to Javabuilder's "playground" mini-app type, which we are deprecating. I removed playground code on the Javabuilder side in [this PR](https://github.com/code-dot-org/javabuilder/pull/337) -- I don't think it matters which order in which we merge these PRs, since we already [removed the playground lambda (ie, users can't run playground projects)](https://github.com/code-dot-org/javabuilder/pull/336/files).

## Links

- jira ticket: [JAVA-623](https://codedotorg.atlassian.net/browse/JAVA-623)

## Testing story

Tested manually that theater, neighborhood, and console levels continued to work as expected against local javabuilder after this change.

### CODE REVIEW

**Review by molly-moen — COMMENTED** [review]
Can you also delete the playground allthethings level along with this?

**Comment by bencodeorg** [comment]
> Can you also delete the playground allthethings level along with this?

Yeah [I was just checking on best practices for that with ep-tools](https://codedotorg.slack.com/archives/C02EEGWLHR8/p1658510499009079), sounds like it might create some weirdness in bubble numbers (ie, there'd be no level 9 in the lesson) but I think I'd still prefer for it to be gone than have a broken level yeah?

**Comment by molly-moen** [comment]
> > Can you also delete the playground allthethings level along with this?
> 
> Yeah [I was just checking on best practices for that with ep-tools](https://codedotorg.slack.com/archives/C02EEGWLHR8/p1658510499009079), sounds like it might create some weirdness in bubble numbers (ie, there'd be no level 9 in the lesson) but I think I'd still prefer for it to be gone than have a broken level yeah?

Yeah I'd prefer to have there not be a broken level in there. Alternatively we could sub out a different level 9 maybe? Not sure what would be useful though

**Comment by bencodeorg** [comment]
Oops I was wrong, level numbers changed once I his save on the lesson 🤦 , so no gap in numbers. I had to adjust some of our UI tests to use the right level, included those changes as well (in addition to removing the allthethings level) in the most recent commit.

**Review by molly-moen — APPROVED** [review]

**Review by sanchitmalhotra126 — APPROVED** [review]

**Pull request merged**
