### PR TITLE
Bounce singleton

### PR DESCRIPTION
**Pull request by Bjvanminnen**
Use StudioApp singleton for bounce instead of a global.

The second commit here isnt strictly necessary, and I could be convinced to abandon it. I saw a bunch of places where we had code inside try/catch. This (a) looked kind of messy and (b) meant that if we want to start logging these errors in some way, we would need code changed in a bunch of places. It felt like it made sense to have a single place for all this. Right now I'll log the error to the console if there is one (I'm pretty sure this is a case where we don't expect errors and want to know if we get them). In the future, we may also want to try to integrate with honey badger (I have a bug tracking this in general).

### CODE REVIEW

**Comment by islemaster** [comment]
Cool.  Did you run the UI tests for this one?

**Comment by Bjvanminnen** [comment]
They're running right now. Won't commit if they fail.

**Comment by cpirich** [comment]
I always wrapped calling the generated code in try/catch because I believe the generated code could throw Infinity or other things like this. Good idea to log it. Perhaps we should make that function available for all apps to share?

**Comment by Bjvanminnen** [comment]
Good idea. I'll add it to our candidate list for sharing (since we're already doing something like this in turtle I know).

**Pull request merged**
