### PR TITLE
Increase Drone clone depth for i18n sync

### PR DESCRIPTION
**Pull request by sureshc**
Because of the winter break, the i18n sync feature branch [contains more than 100 commits](https://github.com/code-dot-org/code-dot-org/pull/38360/commits), causing the Drone Build to fail for this sync because [merging `staging` into the feature branch fails](http://drone.cdn-code.org/code-dot-org/code-dot-org/2372/2/2):

```
+ git clone --branch $DRONE_SOURCE_BRANCH  --depth 100 $DRONE_GIT_HTTP_URL .
2	Cloning into '.'...
3	Updating files:   9% (6342/68017)
Updating files:  10% (6802/68017)
Updating files:  11% (7482/68017)

<snip>

Updating files: 100% (68017/68017)
Updating files: 100% (68017/68017), done.
4	+ git reset --hard $DRONE_COMMIT
5	HEAD is now at 57170297 adding single quotes in i18n/dance/km_kh.json consistent with other languages
6	+ git remote set-branches --add origin $DRONE_TARGET_BRANCH
7	+ git fetch --depth 100 origin $DRONE_TARGET_BRANCH
8	From https://github.com/code-dot-org/code-dot-org
9	 * branch                  staging    -> FETCH_HEAD
10	 * [new branch]            staging    -> origin/staging
11	+ git config user.name "Drone"
12	+ git config user.email "drone-fake-user@code.org"
13	+ git merge origin/$DRONE_TARGET_BRANCH
14	fatal: refusing to merge unrelated histories
```

Increase git clone depth on the feature branch to 200.

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by sureshc** [comment]
Should we make this change permanent? Or is this a rare use case that we should revert after this i18n sync is unblocked?

**Comment by annaxuphoto** [comment]
According to @Hamms a similar issue happened after winter break last year, so unless there's a major disadvantage, I'd prefer to keep the change

**Review by annaxuphoto — APPROVED** [review]
Thanks for doing this so quickly!

**Comment by Hamms** [comment]
I think I recall that when we discussed this last year, it was pointed out (I don't remember by whom) that increasing this across the board would result in longer Drone times, because each clone would take longer

**Comment by sureshc** [comment]
> I think I recall that when we discussed this last year, it was pointed out (I don't remember by whom) that increasing this across the board would result in longer Drone times, because each clone would take longer

I'll monitor and will revert this change, if it's negatively impacting Drone Build performance after these i18n syncs are complete.

**Pull request merged**
