### PR TITLE
Bump dance for new character

### PR DESCRIPTION
**Pull request by epeach**
# Description
Screenshot here: 
https://codedotorg.slack.com/archives/CC2QHV7SR/p1573162846154600?thread_ts=1573160392.151500&cid=CC2QHV7SR

cc: @joshlory

## Testing story
Manually tested. It would be great to have a few other folks do a quick manual check on it to make sure there aren't bugs hiding for a random char at a random dance.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by ajpal** [comment]
Do I need to rebuild/reconfigure something to get the new spritesheet to load? If I just pull this branch, I'm getting this error: 
image

**Comment by epeach** [comment]
@ajpal I do not repro that. I `rake built` when I checked this branch out in order to rebuild with the 0.0.47 changes and the level changes. Can you try that and if you are still repro-ing this, include the steps you took to repro? Thanks!

**Comment by ajpal** [comment]
Working now!
image

**Review by ajpal — APPROVED** [review]

**Comment by ajpal** [comment]
Spot checked with a handful of dancer/dance combos and looks good!

**Pull request merged**
