### PR TITLE
Unhide iceage script

### PR DESCRIPTION
**Pull request by caleybrock**
This one will likely be merged on Wednesday

### CODE REVIEW

**Comment by tanyaparker** [comment]
Do you know what the difference is between explicitly including `hidden: false` and not having `hidden: true`? I think putting it explicitly adds it to the dropdown when a teacher creates a new section and selects a class for the section. Do we want it for all of these hoc tutorials? I don't see why not, just curious.

**Comment by caleybrock** [comment]
I was just copying the setting on the starwars script, but I know it adds it to the dropdown. @breville ?

**Comment by breville** [comment]
I think ideally you could just remove the 'hidden: true' line and it would be un-hidden and appear on the dropdown, however because we only write database entries when we encounter a line in the .script file (since it's a ruby DSL) we need to explicitly say 'hidden: false' to un-hide it.

**Comment by tanyaparker** [comment]
Good to know

**Pull request merged**
