### PR TITLE
flag levels at the beginning of stages as having important instructions

### PR DESCRIPTION
**Pull request by Hamms**
Namely, those levels that are uneditable in levelbuilder.

Based on [this list](https://docs.google.com/document/d/1o8fOCS7Pkl0ZhHmA00dDtRlAO-UY0QHGzrqr4xUkAYk/edit?ts=58094883)

### CODE REVIEW

**Comment by joshlory** [comment]
Should this be set for the first level of every stage instead of on specific levels?  If the levels are reordered or used elsewhere they'll still have this attribute set.

**Comment by Hamms** [comment]
That's probably a discussion worth having with Ryan; could be we'd want to do both

**Comment by joshlory** [comment]
+cc @ryansloan

**Comment by ryansloan** [comment]
In the long run we should probably do both, but for the sake of getting it out there we're starting this way.

**Comment by joshlory** [comment]
Sounds good, this change LGTM!

**Pull request merged**
