### PR TITLE
Enforce consistency in the /pd/international_workshop country field stored values

### PR DESCRIPTION
**Pull request by smusoke**
**What**
Country values within the PD InternationalOptIn form are titleized during form creation.

**Why**
To have the values stored in a capitalized format and be consistent with other stored country values across our database (ex. `user_geos`,`form_geos`).

## Links

- jira ticket: [FND-1232](https://codedotorg.atlassian.net/browse/FND-1232)

## Testing story

- Tested locally
Completed local form with no changes and one with these changes. The stored country value was successfully capitalized as intended.

https://user-images.githubusercontent.com/48133820/129109188-4f3d34c6-4159-4ae4-a585-bbd40fa4da98.mov

## Follow-up work

As mentioned in [this ticket](https://codedotorg.atlassian.net/browse/FND-1232) we need to clean up old country values from being in other languages/translated incorrectly.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by KatieShipley — APPROVED** [review]

**Review by annaxuphoto — APPROVED** [review]
Looks great! Can you add a quick comment to explain that we want to capitalize country names?

**Comment by smusoke** [comment]
> Looks great! Can you add a quick comment to explain that we want to capitalize country names?

@annaxuphoto Updated the **why** section to be clearer on the capitalization.

**Comment by annaxuphoto** [comment]
> > Looks great! Can you add a quick comment to explain that we want to capitalize country names?
> 
> @annaxuphoto Updated the **why** section to be clearer on the capitalization.

Thanks! I more so meant, could you put a comment in the code so anyone trying to understand what's going on there knows? 

Also, I took another look at the Jira task and am a little confused on what Bryan is asking, so maybe hold off on merging until he's back and can approve himself @dju90

**Comment by smusoke** [comment]
> > > Looks great! Can you add a quick comment to explain that we want to capitalize country names?
> > 
> > 
> > @annaxuphoto Updated the **why** section to be clearer on the capitalization.
> 
> Thanks! I more so meant, could you put a comment in the code so anyone trying to understand what's going on there knows?
> 
> Also, I took another look at the Jira task and am a little confused on what Bryan is asking, so maybe hold off on merging until he's back and can approve himself @dju90

Ohh yes that's a good idea. I'll hold off until Monday 👍

**Comment by dju90** [comment]
LGTM! @annaxuphoto for clarification, we want the first letter of the country names to be capitalized in the database (which is how user_geos and form_geos store them) (and retain the current behavior where the country names are still stored in English even if the user fills out the form in non-EN)

**Pull request merged**
