### PR TITLE
Move close-button to the left in RTL locales

### PR DESCRIPTION
**Pull request by joshlory**
Before:
screen shot 2015-03-31 at 4 59 15 pm

After:
screen shot 2015-03-31 at 5 00 01 pm

### CODE REVIEW

**Comment by joshlory** [comment]
This affect all close buttons.  I checked the ones I could find to verify they don't overlap content.

Before:


After:

**Comment by joshlory** [comment]
Before:
screen shot 2015-03-31 at 5 14 08 pm

After:
screen shot 2015-03-31 at 5 14 51 pm

**Comment by joshlory** [comment]
I went ahead and flipped the instructions modal as well:

**Comment by tanyaparker** [comment]
LGTM. Thanks for doing this!

**Pull request merged**
