### PR TITLE
Move angular code back into apps, serve unminified

### PR DESCRIPTION
**Pull request by Bjvanminnen**
Some of our angular code was running into problems when using minified code. Based on this link, that appears to be semi-expected https://docs.angularjs.org/guide/di.
image

I was able to fix the particular instance of this issue that was failing, but then ran into another one. I'm not sure how many more are lurking, and so I decided to instead just serve unminified code.

This unrevert PR makes it so that we go back to sending this code through the apps pipeline, but we serve the unminified version of it. Much of this code is moving to React in the near future, but even so it might be worth trying to fix all of these issues in a separate PR so that we can go back to serving this minified.

I'd also tried adding `ng-strict-di` mentioned in the above link, but unfortunately still did not see failures in my unminified code.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
For posterity, the fix for the actual issue I'd run into is 
image

The revert PR this is undoing is https://github.com/code-dot-org/code-dot-org/pull/15626

**Comment by Bjvanminnen** [comment]
Also fixes a bug I found where we were giving two options in the student gender dropdown, both of which were female.

**Comment by joshlory** [comment]
I do wonder if it's worth keeping this code quarantined outside of apps build.

Presumably there are lint benefits to bringing it under the /apps umbrella.  But if we plan to entirely replace these components with new React components my preference would be to keep the old Angular components isolated.

**Comment by Bjvanminnen** [comment]
There are lint benefits (linting already caught one bug I introduced). It also means less worrying about cross browser issues (i.e. I don't have to worry about using some method that exists in Chrome but not IE).

As we replace these, it's probably not going to be wholesale. We'll be moving a bit at a time. I feel much better about making those changes with this code in the apps pipeline then isolated outside of it.

**Comment by joshlory** [comment]
Note that this PR moves the code to /apps.  It's currently outside of /apps.

**Comment by joshlory** [comment]
Does all Pegasus JS eventually belong in an /apps bundle?

**Comment by Bjvanminnen** [comment]
I think probably yes, though not sure we ever actually hit 100%.

**Pull request merged**
