### PR TITLE
update all level content to use double spaces to indent lists

### PR DESCRIPTION
**Pull request by Hamms**
Our current markdown parser (`marked`) allows you to nest lists with just a single space, like:

```
* Repeat 2 times:
 * Move forward
 * Make 3 honey
* Move backward
```

But this is both technically incorrect markdown and unsupported by remark, which has the side effect of causing the internationalization redaction to break.

To fix this, I just update all levels using this indentation in instructions, markdown instructions, or authored hints to look like:

```
* Repeat 2 times:
  * Move forward
  * Make 3 honey
* Move backward
```

### CODE REVIEW

**Comment by Hamms** [comment]
FYI @kiki-lee @mrjoshida

**Comment by balderdash** [comment]
I found a few more files containing the string `\n *`. The first couple are instances of incorrect indentation, but I didn't check all of them:
```
levels/CSD U2 text style decoration_2018.level
levels/CSD U2 text style font family_2018.level
levels/CSD U2 text style text align_2018.level
levels/CSP U5L18 SFLP.level
levels/CSPU5_ChoosingGoodIds.level
levels/CSPU5_EventDrivenProgrammingPatterns.level
levels/CSPU5_U3 - Loops - 1.level
levels/CSPU5_U3 - Loops - 1_2018.level
levels/CSPU5_U3L15 Student Lesson Intro - new.level
levels/CSPU5_U3L34 Student Lesson Introduction.level
levels/U3 - Loops - 1.level
```

**Comment by Hamms** [comment]
Hah, yeah, I just found those, too. I realized that my script also wasn't accounting for `\n - `, so I ran and updated version and all of those changes fell out, too.

Another commit incoming.

**Comment by Hamms** [comment]
Note that we're specifically looking for `\n * ` with an extra space, to ignore places where we have lines that are just trying to bold or italicize

**Comment by Hamms** [comment]
[clean up existing level content so the redaction process doesn't inadvertently mutate it](https://trello.com/c/XWMWoyGZ/231-clean-up-existing-level-content-so-the-redaction-process-doesnt-inadvertently-mutate-it)

**Pull request merged**
