### PR TITLE
Instructions: Truncate Tabs

### PR DESCRIPTION
**Pull request by molly-moen**
99% a copy over of [this PR](https://github.com/code-dot-org/code-dot-org/pull/41914) from @breville, with one css update to ensure the audio button stays visible. 

This PR fixes the behavior where if the tabs on the instructions panel header were too large for the available space, one of two things would happen
- If the audio button was in the header (because text to speech was available), then no tabs would appear at all.
- If the audio button was not in the header, the first n tabs that fit in the header would show up, then the other tabs would not be visible (they were overflowing into a second row)

Now the tabs will truncate with ellipses, and have a tooltip with the full name. This isn't an ideal solution as for Java Lab now most of the time the tabs will be truncated, and sometimes the truncated version isn't very helpful. For example `Review` becomes `Revi...`. However, it is a major improvement over no tabs or invisible tabs. 

This change should only cause visible changes to Java Lab, as the instructions panel is much smaller there. The only change to other labs is if you hover over a tab name you now get a tooltip, or if you have a very narrow browser window.

### Screenshots

View with 4 tabs (Instructions, Help & Tips, Review, For Teachers Only)  

Screen Shot 2022-06-01 at 10 54 59 AM

A different set of 4 tabs (Instructions, Help & Tips, Documentation, Review)  
Screen Shot 2022-06-01 at 10 55 27 AM

View with 3 tabs (Instructions, Help & Tips, Review)  
Screen Shot 2022-06-01 at 10 55 13 AM

We can likely get rid of the help & tips tab in place of documentation once that tab is out of experiment mode, as currently help & tips links to documentation.

## Links
- [slack thread](https://codedotorg.slack.com/archives/C01EF4GJ9GE/p1654029237504789)

## Testing story
Tested locally

## Follow-up work
Some proposed better solutions that would require more dev time:
- replace the tabs with a tab library
- if there are too many tabs, have a dropdown instead of tabs

### CODE REVIEW

**Review by maureensturgeon — APPROVED** [review]
From the screenshots, it looks like there is a lot of unused space between the cut-off tabs. Would it be possible to have a little less space between the tabs and maybe we'd get a few more letters visible?

**Comment by molly-moen** [comment]
@maureensturgeon I thought about that, the downside is that it will change the spacing for every lab unless we have some special casing around when we should or should not have padding.

**Comment by maureensturgeon** [comment]
> @maureensturgeon I thought about that, the downside is that it will change the spacing for every lab unless we have some special casing around when we should or should not have padding.

What you could do is wrap the InstructionTab `a` in a div and then put the overflow hidden on that wrapper.
Before:
Screen Shot 2022-06-01 at 10 32 53 AM
After:
Screen Shot 2022-06-01 at 10 33 48 AM

**Comment by molly-moen** [comment]
@maureensturgeon thanks that is much better, incorporated that change!

**Review by sanchitmalhotra126 — APPROVED** [review]

**Pull request merged**
