### PR TITLE
Improves confirm_usage and runs it every minute.

### PR DESCRIPTION
**Pull request by ashercodeorg**
CHANGES:
- Major refactoring, allowing new table row creation checks to be specified by adding a triple to `CREATION_CHECKS`.
- Adds a table row creation check for `pegasus.forms`.
- Changes `confirm_usage` to not alert when an existing alert has not been closed (via a temporary file).

TESTING:
- Run on `production-console`, verifying `confirm_usage_alert` file works as intended (by changing `SECONDS_PER_MINUTE` to zero, causing alerts).

### CODE REVIEW

**Comment by ashercodeorg** [comment]
This PR is instead of and an extension to (the closed) #11353.

**Comment by ashercodeorg** [comment]
Note that the `forms` outage from yesterday indicates the utility of these alerts. Is it worth checking that we have various kinds of `forms`(also `users`) being created?

**Comment by ewjordan** [comment]
Assuming those circleci failures are unrelated (seems likely), and we're eventually going to turn these into PagerDuty alerts (so that firing once is all we need), this looks good to me.

**Comment by ashercodeorg** [comment]
CircleCI failures are unrelated.

**Pull request merged**
