### PR TITLE
Rename ed_programs directory to acquisition_products

### PR DESCRIPTION
**Pull request by megcrenshaw**
There is an `ed_programs` directory in UI tests that we're changing the name of.

To do this, I went into my IDE and did Refactor -> Rename
image

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
looks like a good start Meg, however I think everything under levelbuilder is ready to move into the `learning_platform` directory. CC @code-dot-org/learning-platform to make sure this matches your understanding

**Comment by davidsbailey** [comment]
also I believe instructor_in_training.feature and lesson_show.feature will be owned by LP now too.

**Comment by megcrenshaw** [comment]
Oh yikes! I misunderstood the instructions –– will update. Thanks!

**Comment by megcrenshaw** [comment]
@code-dot-org/learning-platform , I'm tagging you in because some tests are moving to y'all. Does this look right?

Who will own the `video` features –– `fallback_player_caption_dialog_link.feature` and `videoplayer_eyes.feature`? I don't think that's AP, but I don't know if it'd be LP or star labs.

**Comment by davidsbailey** [comment]
I think this one is also LP now:
* teacher_lesson_plan.feature

I'm less sure about these:
* pl_sections.feature
* plc_course_unit_navigation.feature

my understanding was that PLC is curriculum, therefore part of LP, but I could be mistaken.

**Comment by dmcavoy** [comment]
Both pl_sections.feature and plc_course_unit_navigation.feature should be LP

**Comment by bethanyaconnor** [comment]
> Who will own the video features –– fallback_player_caption_dialog_link.feature and videoplayer_eyes.feature? I don't think that's AP, but I don't know if it'd be LP or star labs.

I'm not sure either. I don't think it's acquisitions either. It's either us or student learning for sure so maybe moving it into learning platform for now and I'll ask

**Review by bethanyaconnor — APPROVED** [review]
New `learning_platform` tests look good to me!

**Review by davidsbailey — APPROVED** [review]
thank you for doing this, Meg!

**Pull request merged**
