### PR TITLE
Allow editors to move activity sections between activities

### PR DESCRIPTION
**Pull request by dmcavoy**
## Background

During the November Bug Bash it was discovered that editors could not move activity sections between activities. Being able to move activity sections between activities is critical for saving time in editing.

## Solution

Editors can now move activity sections between activities. There were a couple main issues going on:

1) We were actively preventing moving activity sections between activities by not calling moveActivity if the activity section was the first or last in an activity
2) Activity Section keys were not unique across activities

I think #1 was an attempt to prevent moving up and down when its the very top or very bottom activity section so I have updated that logic. 

Also I updated the place we look for existing activity sections to use `find_by` instead of `find` because if you moved an already saved activity section to a new activity and then tried to save it would give an ActiveRecord not found because it was only looking for the activity section in that Activity. This means we just create a new activity section for it and the old one will be deleted during the process.

move-activity-section

## Links

- [jira](https://codedotorg.atlassian.net/browse/PLAT-535)

## Testing story

Updated tests for components that were updated. Added specific tests to ActivitySectionCardTest in order to check that the new conditions around when and when not to move are working correctly.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dmcavoy** [comment]
Hold off on review for now. I tested flip flopping the activities and it seems to have messed something up :)

**Comment by dmcavoy** [comment]
Nevermind my earlier comment. Was in the wrong branch 🤦

**Comment by dmcavoy** [comment]
Turning this back to draft. Something is up with saving and I'm not sure what.

**Comment by dmcavoy** [comment]
I think this also fixes [PLAT-536](https://codedotorg.atlassian.net/browse/PLAT-536)

**Review by davidsbailey — APPROVED** [review]
Great work Dani! New tests look solid, and the write-up made it much easier to understand why things are changing.

**Pull request merged**
