### PR TITLE
Use locals to refer to variables passed in

### PR DESCRIPTION
**Pull request by pcardune**
Not sure how to test this locally other than to load http://localhost-studio.code.org:3000/s/allthethings/stage/14/puzzle/4?noautoplay=true. But I didn't see the error without this change to begin with. I think it probably has to do with minification.

### CODE REVIEW

**Comment by pcardune** [comment]
I can confirm that the code I change did execute and didn't throw an error. It's just that `locals.level` and `level` both have the same value in the development execution environment.

**Comment by Bjvanminnen** [comment]
lgtm

**Comment by joshlory** [comment]
Are there going to be other places in the codebase that have this issue (that we may not have UI test coverage for)?

**Comment by bcjordan** [comment]
Looks like a handful of places that reference `level.` in `.ejs` files (not sure if would have the same issue?):

image

**Comment by pcardune** [comment]
Yeah probably.

**Comment by Bjvanminnen** [comment]
Tried replacing all instances of `level.` in ejs files with `locals.level.` and my tests failed :(

**Pull request merged**
