### PR TITLE
Add is_stable checkbox to script edit UI

### PR DESCRIPTION
**Pull request by uponthesun**
image

## Links

- [jira](https://codedotorg.atlassian.net/browse/PLAT-47)

## Testing story

* Tested manually locally (setting and unsetting)
* ScriptsControllerTest covers setting and unsetting

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
LGTM. @dmcavoy , can you help Winter with the wording?

**Comment by dmcavoy** [comment]
I can definitely help with wording but I have a wonder first. Is stable is meant to mark that a unit is no longer being edited by a curriculum writer in major ways so a teacher can start using it without things changing out from under them. How is that different from when we mark something as visible in the Teacher Dashboard (the check box above is stable)? To me it seems like you would check both at the same time. Could we use one checkbox for both things?  (Sorry for not thinking about this earlier. The screenshot actually jogged my thinking). @davidsbailey @uponthesun @fontie715 thoughts?

**Comment by dmcavoy** [comment]
Circling back to this I think we decided on
'Can be recommended' as the title
For the description something like 'If checked this unit will be able to become the recommended version of the unit. The recommended version of a unit is the most recent stable version of the unit.'

**Comment by dmcavoy** [comment]
Also based on conversations today in the LP/curriculum meeting I'm wondering if someone should only be able to mark a course as 'visible in teacher dashboard'/'stable'?  (I understand there are challenges to this until we get CSF into courses and not just units but figured we should talk about it)

**Comment by uponthesun** [comment]
> Also based on conversations today in the LP/curriculum meeting I'm wondering if someone should only be able to mark a course as 'visible in teacher dashboard'/'stable'? (I understand there are challenges to this until we get CSF into courses and not just units but figured we should talk about it)

We discussed this in Slack and decided to proceed with this for now, and defer the rest of the work to the upcoming task to come up with a plan for ensuring all Scripts have a Course.

**Pull request merged**
