### PR TITLE
open projects links in a new window in the public gallery

### PR DESCRIPTION
**Pull request by davidsbailey**
axosoft item: https://codeorg.axosoft.com/viewitem?id=1020&type=features&force_use_number=true

@poorvasingal , can you please confirm that you want projects to open in a new window in both the public and private sections of the Project Gallery page?

### CODE REVIEW

**Comment by poorvasingal** [comment]
Ah sorry no - just the public gallery. Sorry for not clarifying earlier.

**Comment by caleybrock** [comment]
What's the private section? Just the project widget? This affects all right now.

**Comment by davidsbailey** [comment]
Thanks @caleybrock , I forgot we were going to be using the ProjectCard in other places besides the Public Gallery soon. PTAL

The private section I was referring to was the My Projects view which is still in angular. I took the change affecting that part out in response to Poorva's feedback, before I added you as a reviewer.

**Comment by poorvasingal** [comment]
I mean if you open up a project from /projects/public, we should open up the project in a new tab. This isn't about the projects widget. Your projects list in your private list should continue to open in the same tab.

**Pull request merged**
