### PR TITLE
Adds a migration that removes redundant NPS data from the users table.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This is a followup to #8171. A future followup will remove `survey2015_value` and `survey2015_comment` as serialized attributes of the `users` model.

The scope of the migration is the 22K users with Net Promoter Score responses.

```
SELECT COUNT(0) FROM users WHERE properties LIKE '%survey2015%';
+----------+
| COUNT(0) |
+----------+
|    21882 |
+----------+
```

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @laurelfan

**Comment by breville** [comment]
lgtm, but usual concerns about rehearsing on some good quality test data, and not sure about perf implications of this one.

**Comment by ashercodeorg** [comment]
In terms of testing, I've done local testing of both `rake db:migrate` and `rake db:rollback`.

**Comment by ashercodeorg** [comment]
FWIW, I've updated this PR to include `with_deleted` so that all users (soft-deleted or not) are included.

**Comment by ashercodeorg** [comment]
And I've now tested the `with_deleted` part with local deleted users.

**Pull request merged**
