### PR TITLE
Updated SoundLibrary.json with category_bell (2/29)

### PR DESCRIPTION
**Pull request by kimj42**
SoundLibrary.json uploaded only since taglib-ruby gem and script was causing drone to fail. Uploaded files from category_bell in s3 cdo-sound-library. This one includes the changes from category_app as well as category_bell because category_app hasn't been approved yet.

Count: 2/29

### CODE REVIEW

**Review by islemaster — APPROVED** [review]
Diff looks good.

More general question: Since this is (largely) an automated process, is there any benefit to doing it in 29 steps instead of one large PR?  Likewise, are any of these changes actually visible on production as we release them, without updating the list of sound library categories, here?

https://github.com/code-dot-org/code-dot-org/blob/1cad5ac667f9ed1a3aa31063e6d06bd21a78e2bd/apps/src/code-studio/components/SoundLibrary.jsx#L9-L19

Maybe what I'm really asking is, what's the rollout plan here?  Do you have one written up somewhere I can review?

**Comment by kimj42** [comment]
Refer to PR #27348, which has all the updates on the sound library as well as some readjustment to the dialog.

**Comment by kimj42** [comment]
Spoke to Brad in person about the rollout plan. Decided to have all updates in one PR and make sure all categories appear for the users once the sound library is updated. So will close this PR and create a new one.

**Comment by kimj42** [comment]
Refer to PR #27348, which has all the updates on the sound library as well as some readjustment to the dialog.

**Pull request closed without merging**
