### PR TITLE
Re-add Make a Copy feature for Resources

### PR DESCRIPTION
**Pull request by rshipp**
Reverts code-dot-org/code-dot-org#48990, re-adding #48642 with fixes for the broken buttons that were caught by Eyes tests.

The button in the failing diff can be seen here: http://localhost-studio.code.org:3000/s/allthethings/lessons/9/levels/1?section_id=1

### CODE REVIEW

**Review by bethanyaconnor — APPROVED** [review]
Looks reasonable to me but I've never seen the `:global` syntax before. Not sure if it's worth checking with Maddie to make sure there won't be any odd side effects?

**Comment by rshipp** [comment]
`:global` comes from css-modules, and tells it to reference an external class name `header` instead of autogenerating a local class name like `C9TrlUErKq7GDcQxySiL` like it does to avoid collisions with other files. https://stackoverflow.com/a/71629293

**Comment by maddiedierker** [comment]
for this change, i think this works perfectly. the only odd side effect would be if the CSS modules styles aren't unloaded after the component/module scope. from the [CSS modules documentation](https://github.com/css-modules/css-modules#exceptions), i don't feel like i understand whether or not that's true even though they kind of address this question:

> If the selector is switched into global mode, global mode is also activated for the rules. (This allows us to make animation: abc; local.)

this would be easy to test, though, and doesn't matter in this case because we don't have any styles in the root scope (they're all nested within other CSS module rules).

i feel like i'm saying a lot of words so i'll pseudocode what i mean...

```scss
// global.scss
.header a:link {
  color: red;
}

// component.module.scss
:global(.header) a:link {
  color: blue;
}
```

in this case, if we accessed the `.header a:link` selector later (outside of the CSS module component scope), would the color be red or blue?

**Review by maddiedierker — APPROVED** [review]

**Comment by rshipp** [comment]
Yeah, I couldn't understand their docs for this at all. Since the order the rules are defined is relevant in CSS, it'd also depend which rule was lower down in the document, and I'm not sure how to test around that when there are inline styles above and below application.css.

image

**Pull request merged**
