### PR TITLE
Fixes the URL redirect for sample emails.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Given that the signee is Hadi, should he review as well?

**Comment by ashercodeorg** [comment]
Note that the /promote#email links also seem broken. Let me know whether they should be redirected to /resources#sample-emails or elsewhere.

**Comment by tanyaparker** [comment]
Hadi doesn't need to review. I usually just notify him when the change is live on prod.

All the /resources#xyz links should now point to /promote/resources#xyz

And /promote#email should be /promote/resources#sample-emails

**Comment by ashercodeorg** [comment]
PTAL (please take another look), I made the suggested changes to the URLs.

**Comment by tanyaparker** [comment]
lgtm

**Comment by ashercodeorg** [comment]
Dropping this PR as part of fixing the circleci failure. New PR is #4504.

**Pull request closed without merging**
