### PR TITLE
Remove student_of_admin_required and remnants of admin_required.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Option was originally added https://github.com/code-dot-org/code-dot-org/pull/8123 - and was always a terrible idea (Brad)

### CODE REVIEW

**Comment by joshlory** [comment]
Is this change still active?  It would be great to get rid of these flags!

**Comment by ashercodeorg** [comment]
Yes, I do intend to push it through... Before being able to merge this PR, I need to modify the levels on levelbuilder to not define `admin_required` and `student_of_admin_required`.

**Comment by ashercodeorg** [comment]
The requisite levelbuilder modifications have been made. Once those get picked up and pushed through the pipeline, this PR is good to ship. Let me make sure tests pass...

**Comment by ashercodeorg** [comment]
CC @jeremydstone

**Comment by joshlory** [comment]
LGTM

**Pull request merged**
