### PR TITLE
allow duplicate levels in different lessons within the same unit

### PR DESCRIPTION
**Pull request by davidsbailey**
## Background

Fixes fallout from https://codedotorg.atlassian.net/browse/PLAT-830. The problem is that the new unit editor tries to prevent adding of duplicate levels within the same unit. However, some newly-migrated units have duplicate levels, and in fact depend on the levels being repeated within the same unit. for example https://studio.code.org/s/k5-onlinepd-2021 deliberately repeats levels so that participants in this unit can see a summary of their previous work:
Screen Shot 2021-11-04 at 8 01 13 AM

This raises the question of why we are trying to prevent duplicate levels in the first place:
1. the lesson editor might break if there are duplicate levels within the _lesson_
2. general long-term goal of having each level occupy only one location in our curriculum

because our existing units rely on duplicate levels, it seems best to keep goal (1) and let go of goal (2) for now.

A roundup of duplicate levels in units can be seen here: [duplicate levels in units](https://docs.google.com/spreadsheets/d/1R8U_3v3qELfQX2oGTm0D9UnwfZ4rgJLfMourX4Ti5Ok/edit)

## Description

The solution is to allow duplicate levels within the unit, but prevent duplicate levels within the ~script~ lesson.

## Screenshots

This screenshot shows the old and new result of editing a lesson in k5-onlinepd-2021 which contains levels that are duplicate within the unit but not within the lesson.

Screen Shot 2021-11-04 at 7 54 14 AM

## Testing story

updated unit tests to reject duplicate levels within the lesson but allow duplicates within the unit.

### CODE REVIEW

**Comment by dmcavoy** [comment]
> The solution is to allow duplicate levels within the unit, but prevent duplicate levels within the script.

This sentence does not make sense to me. Can you clarify?

I think its duplicates can exist in UNIT but not in LESSON?

**Comment by davidsbailey** [comment]
> > The solution is to allow duplicate levels within the unit, but prevent duplicate levels within the script.
> 
> This sentence does not make sense to me. Can you clarify?
> 
> I think its duplicates can exist in UNIT but not in LESSON?

hahaha, sorry about that. you are correct! updated above

**Review by dmcavoy — APPROVED** [review]
This solution looks good. I am wondering if we should check with LP on this as I know they have been doing a ton of work on progress and I wonder if this has any impacts on them.

**Comment by davidsbailey** [comment]
Will do, Dani. If we zoom out a bit, this project to migrate old units takes us from a previous state of allowing duplicate levels anywhere in the unit, to a new state of preventing duplicates within a single lesson. So I don't think that will break anything, unless LP was already assuming that levels are unique within a unit. I will check

**Comment by davidsbailey** [comment]
closing in favor of https://github.com/code-dot-org/code-dot-org/pull/43423

**Pull request closed without merging**
