### PR TITLE
Rename census map job to more accurately describe what its primary purpose is

### PR DESCRIPTION
**Pull request by bethanyaconnor**
See discussion for #30039

### CODE REVIEW

**Review by sureshc — APPROVED** [review]
Yay for intuitive names!

**Comment by breville** [comment]
Actually I think it would be better to leave the word census in there.  Even though we publicly call it the access report, if you search our source tree for related files and keywords, we seem to mostly use census as the internal name.  I think it's more important to be internally consistent in our naming in source code, even if a brand name of something changes.

**Comment by bethanyaconnor** [comment]
How about something like `summarize_census_data`?

**Comment by breville** [comment]
That sounds good.

**Review by breville — APPROVED** [review]

**Pull request merged**
