### PR TITLE
[Student Learning] Update image on /maker/setup page.

### PR DESCRIPTION
**Pull request by levadadenys**
Update image on /maker/setup page.
Fix image is missing from https://studio.code.org/maker/setup

## Links
- jira ticket: [SL-393](https://codedotorg.atlassian.net/browse/SL-393?atlOrigin=eyJpIjoiOWRiYzdkNGZiMzYwNDAzMTg0Y2UxZjY4NzFmNDFhNDciLCJwIjoiaiJ9)

## Testing story
No new tests added, just updating the image.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by breville — APPROVED** [review]
Curiously, there appears to be a tiny row of transparency across the top of this image?

**Comment by levadadenys** [comment]
> Curiously, there appears to be a tiny row of transparency across the top of this image?

yeah, it looks like it does.(haven't seen it in jira or ide) But at the same time it looks like there's usb port overlapping with that transparency row so I'm not sure whether it needs to be cropped. There was a problem with the free space at the bottom of the image (see jira) that I've cropped out only

**Comment by breville** [comment]
I wouldn't crop any more of the actual image, since that's the important part.  You could fill the transparency with white pixels.  But it's probably also fine to go in as-is for now, assuming it'll always be shown on a white background.

**Comment by levadadenys** [comment]
> I wouldn't crop any more of the actual image, since that's the important part. You could fill the transparency with white pixels. But it's probably also fine to go in as-is for now, assuming it'll always be shown on a white background.

I've filled the transparency with white so it won't make any problems in the future.
Unfortunately, I don't have right to merge my pr right now. It would be great if you could merge it, please

**Comment by mikeharv** [comment]
Thanks for fixing the transparency @levadadenys! I'll go ahead and merge.

**Pull request merged**
