### PR TITLE
New ice age promo image background

### PR DESCRIPTION
**Pull request by caleybrock**
screen shot 2015-12-01 at 10 25 36 pm

### CODE REVIEW

**Comment by breville** [comment]
I like it, though i feel like we should zoom in more on the characters to have less empty space around them.

**Comment by caleybrock** [comment]
I think it was more of an issue with character image quality than anything, but I'll make an attempt!

**Comment by caleybrock** [comment]
screen shot 2015-12-01 at 10 42 31 pm

This definitely feels more substantial

**Comment by breville** [comment]
Yes, agreed.  They fill out the frame much more nicely.

**Pull request merged**
