### PR TITLE
Ensure attribute values are strings

### PR DESCRIPTION
**Pull request by joshlory**

### CODE REVIEW

**Comment by cpirich** [comment]
LGTM - not sure which attributes we need to test to ensure that they work properly (or if we really need this API in the long-term), but this is clearly less dangerous.

**Comment by joshlory** [comment]
@davidsbailey it looks like you added these APIs in https://github.com/code-dot-org/code-dot-org/commit/bc9b88dde708752e381c043f6c73bb9ec9eb8cfb.  Is there any user-bad in changing this API to take the DOM name instead of the JavaScript name (e.g. `class` instead of `className`)?

**Comment by cpirich** [comment]
You may want to make sure it is consistent with `setAttribute` if you change it

**Comment by davidsbailey** [comment]
Unfortunately yes, this will break anyone who has already written `getAttribute('className')` in an app.

**Comment by davidsbailey** [comment]
FYI @Bjvanminnen that this would involve a backward-incompatible change, though it's not clear if it would break enough users to worry about it. FYI Josh here is the versioning doc https://docs.google.com/document/d/1dyfamwJ3o60eWl17gEd5IgsEjDDU1VZgWU3hVtI2Uhs/edit

**Comment by davidsbailey** [comment]
If this is to fix the security issue you demoed, another solution would be to add a whitelist of attributes similar to the one in place for setAttribute.

**Comment by Bjvanminnen** [comment]
Another option would be to build a whitelist mapping of old to new attributes, such that `getAttribute('class')` calls `element.getAttribute('className')` under the hood.

**Comment by joshlory** [comment]
We can also fix with `String(element[attribute])` if we want to preserve the existing behavior.

**Pull request merged**
