### PR TITLE
i18n sync down out 04/18

### PR DESCRIPTION
**Pull request by Hamms**
This PR is broken up into multiple commits to help double-check content changes.

Note that some of the changes are _enormous_. This appears to be fallout from https://github.com/code-dot-org/code-dot-org/pull/13982, in which we reordered some keys in the hashes to enforce a deterministic ordering. It would appear that the downloaded hashes from crowdin now match key order; I'm not sure why it took nearly a month for that change to come out the other end, but here we are.

This should hopefully be the last time we have to deal with unnecessary changes like this.

### CODE REVIEW

**Comment by tanyaparker** [comment]
image

LOL

**Comment by tanyaparker** [comment]
dashboard/config/locales/Telugu.yml was added, but should be added as xx-YY.yml

**Comment by Hamms** [comment]
good catch! For the sake of compartmentalization, I'm going to not include it in this PR and add it with a later sync

**Comment by tanyaparker** [comment]
Sounds good!

**Pull request merged**
