### PR TITLE
Update scripts project sharing

### PR DESCRIPTION
**Pull request by maddiedierker**
[LP-290](https://codedotorg.atlassian.net/browse/LP-290)

Add new `project_sharing` property introduced in #28100 to CSD and CSP script files.

I confirmed this is working properly by:
- Running `bundle exec rake seed:scripts`
- Confirming the affected scripts had `project_sharing` set to `true` in the database and displayed in the levelbuilder UI

### CODE REVIEW

**Review by davidsbailey — COMMENTED** [review]
Code changes look good! Do csp-explore, csp-create, and csppostap need to be updated too?

**Review by dmcavoy — APPROVED** [review]
Looks good to me. I would +1 what Dave said about the other csp scripts. Also should we turn it on for the pilot scripts csp is using too?

**Comment by maddiedierker** [comment]
good point -- looking back at `csp-explore`, `csp-create`, and `csppostap`, it does look like they would benefit from having project sharing turned on by default.

@dmcavoy re: CSP pilot scripts -- do you know the names or family names of these scripts (or where to find them)? i'm not finding those scripts in the codebase

**Comment by dmcavoy** [comment]
Looks like they are all of the form of 'csp1-pilot-staging' going from 1 to 10.

**Pull request merged**
