### PR TITLE
[Finishes #105880988] Add `zeroParamFunctions` droplet option to Level Builder

### PR DESCRIPTION
**Pull request by joshlory**

### CODE REVIEW

**Comment by davidsbailey** [comment]
Hi Josh, can you provide a bit more context (maybe before/after screencap) of what this PR accomplishes? I see Sarah's comment in the pivotal item that this is already enabled, but when I click into a zero arg function in droplet today I see I can place the cursor there in block mode but cannot add anything there.

**Comment by davidsbailey** [comment]
FYI, I patched this in and saw a weird error which I cannot repro on http://localhost.studio.code.org:3000/s/cspunit3/stage/6/puzzle/5:

screen shot 2015-10-28 at 2 40 36 pm

**Comment by davidsbailey** [comment]
LGTM

**Comment by joshlory** [comment]
@davidsbailey ready for another look when you have a chance!

**Comment by davidsbailey** [comment]
LGTM

**Pull request merged**
