### PR TITLE
Small updates to Levelbuilder UI - selecting pools/libraries

### PR DESCRIPTION
**Pull request by fisher-alice**
This PR makes small updates to selecting Blockly pools and helper libraries on the levelbuilder level edit page.
- increases the size of the select window from 4 to 12 items,
- sort the lists alphabetically ignoring case (currently sorted alphabetically case-sensitive),
- list the currently used saved items at the topc of the list,
- display the currently saved items in text below the `<select>` element.

Screenshot before update:

Screen Shot 2023-09-05 at 5 02 53 PM

Screencast video after update:

https://github.com/code-dot-org/code-dot-org/assets/107423305/77174a41-916e-4ef5-a80f-bdfccfa940d6

I checked in with curriculum writers about these updates [in this Slack thread](https://codedotorg.slack.com/archives/C03DBDN67B7/p1693523131728529).

There are additional features that the curriculum team are requesting (expandable window, checkboxes next to each item) that are [being tracked](https://codedotorg.slack.com/archives/C045UAX4WKH/p1677180433226249?thread_ts=1677180417.710299&cid=C045UAX4WKH) by the teacher-tools team.

## Links
[jira](https://codedotorg.atlassian.net/browse/LABS-59)
[Slack discussion](https://codedotorg.slack.com/archives/C03DBDN67B7/p1693523131728529)

## Testing story
I tested levelbuilder edit pages locally.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by sanchitmalhotra126 — APPROVED** [review]
Nice updates!

How tricky would it be to show the selected block pools in real time (rather than only after saving)?

**Comment by fisher-alice** [comment]
> Nice updates!

Thanks!
 
> How tricky would it be to show the selected block pools in real time (rather than only after saving)?

I am unsure about this. I'll look into whether there is any other levelbuilder field that is auto-updated. @bencodeorg do you happen to know?

**Comment by bencodeorg** [comment]
I don't know re: selected pools in real time, this seems like a great step though!

**Comment by sanchitmalhotra126** [comment]
> > How tricky would it be to show the selected block pools in real time (rather than only after saving)?
> 
> I am unsure about this. I'll look into whether there is any other levelbuilder field that is auto-updated. @bencodeorg do you happen to know?

Yeah I'd imagine it's possible but probably tricky since we're dealing with HAML. We could consider porting this into React in a future iteration though

**Comment by fisher-alice** [comment]
> > > How tricky would it be to show the selected block pools in real time (rather than only after saving)?
> > 
> > 
> > I am unsure about this. I'll look into whether there is any other levelbuilder field that is auto-updated. @bencodeorg do you happen to know?
> 
> Yeah I'd imagine it's possible but probably tricky since we're dealing with HAML. We could consider porting this into React in a future iteration though

Would this fall under Student Learning or Teacher Tools? I think there was talk about SL taking on some parts of levelbuilder...

**Pull request merged**
