### PR TITLE
Fixes violations of rubocop Security/JSONLoad.

### PR DESCRIPTION
**Pull request by asherkach**

### CODE REVIEW

**Comment by asherkach** [comment]
CC @aoby

**Comment by aoby** [comment]
Looks like we have a merge conflict and some failing tests. Let me know when it's updated and I'll fire off another circle run.

**Comment by asherkach** [comment]
Fixed merge conflict and failing tests. Another CircleCI run would be much appreciated. Thanks @aoby.

**Comment by aoby** [comment]
Running circle...

**Comment by asherkach** [comment]
FWIW, looks like CircleCI is green.

**Comment by islemaster** [comment]
I've reverted this change in https://github.com/code-dot-org/code-dot-org/pull/19582 because it caused a 500 error on https://code.org/volunteer, caught on the staging machine by @epeach before our deploy today.

The break is caused by this difference of behavior between `JSON.parse` and `JSON.load`:
```
2.2.3 > JSON.load(nil)
 => nil 
2.2.3 > JSON.parse(nil)
TypeError: no implicit conversion of nil into String
```

[Rubocop's documentation actually calls this change out](http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Security/JSONLoad) as too dangerous to autocorrect, though it doesn't mention the `nil` issue in particular:

> Autocorrect is disabled by default because it's potentially dangerous. If using a stream, like `JSON.load(open('file'))`, it will need to call `#read` manually, like `JSON.parse(open('file').read)`. If reading single values (rather than proper JSON objects), like `JSON.load('false')`, it will need to pass the `quirks_mode: true` option, like `JSON.parse('false', quirks_mode: true)`. Other similar issues may apply.

The specific case where this PR introduced a regression is [this spot in the `Form2` initializer in database.rb](https://github.com/code-dot-org/code-dot-org/pull/19439/files#diff-f915cab0d3c0ca3e1da42cf6cbc69539L99):

```diff
-    params[:data] = JSON.load(params[:data])
-    params[:processed_data] = JSON.load(params[:processed_data])
+    params[:data] = JSON.parse(params[:data])
+    params[:processed_data] = JSON.parse(params[:processed_data])
```

Which, when used this way in volunteer_engineer_form.haml, now raises an exception because `params[:processed_data]` is `nil`:

https://github.com/code-dot-org/code-dot-org/blob/46b531c671989d386315f2d6fbde9121d02d3288/pegasus/sites.v3/code.org/views/volunteer_engineer_form.haml#L1-L3

Erin and I considered a more targeted fix where we specifically guard against `params[:processed_data]` being nil, but decided it's more prudent to revert the whole PR given two factors:

1. This change hasn't shipped yet, due to lockdown, so we're not regressing any production behavior by reverting the PR.
2. Reviewing the PR diff, many of the places where we've switched from `load` to `parse` seem to be reading form data or params.  We have low confidence that each of these places is guaranteed not to pass `nil`, and it would take a while to track down and prove each case.

Let me know if you have any questions.  This points out a hole in our test coverage.  I do think we should try enabling this linter again, especially since it addresses a security issue, but it should include a more thorough examination of the path to each changed call and/or better test coverage of affected pages.  Thanks!

**Pull request merged**
