### PR TITLE
Added PLP model

### PR DESCRIPTION
**Pull request by aoby**
I included the factory, which I am using in tests for reports I'm still finishing up that I'll send out in another PR. It's not referenced here since the model is so straightforward.

### CODE REVIEW

**Comment by joshlory** [comment]
Can this be named with the full name instead of the abbreviation?

**Comment by mehalshah** [comment]
I would also prefer professional_learning_partner over plp

**Comment by aoby** [comment]
Makes sense. I'll expand it out.

**Comment by ashercodeorg** [comment]
Should this ultimately be imported into Redshift / Tableau?

**Comment by aoby** [comment]
Updated with expanded name: professional_learning_partner. 

@ashercodeorg good question. Possibly in the future, but AFAIK not immediately, and not without the associated workshops and plc courses.

**Comment by mehalshah** [comment]
LGTM

**Pull request merged**
