### PR TITLE
Load app dependencies on the client instead of in haml

### PR DESCRIPTION
**Pull request by joshlory**
This is a step towards loading all dynamic data for the tutorial pages via AJAX.  This change extracts the remaining dynamic haml in _blockly.html.haml to an external JS file.

### CODE REVIEW

**Comment by wjordan** [comment]
Do we have any tests that cover this functionality? If not, this might be a good opportunity to write one or two.

**Comment by joshlory** [comment]
This is the core code path for any level that loads blockly, so the existing UI tests will cover this change.  UI tests caught the video `reference_area` bug above.

**Comment by joshlory** [comment]
Synced with Will offline, he says good to merge.

**Comment by wjordan** [comment]
:+1:

**Pull request merged**
