### PR TITLE
automatically request reviews from the cdo/i18n team on all i18n sync PRs

### PR DESCRIPTION
**Pull request by Hamms**
also update the "label_pull_request" helper to allow calling it with a single label, rather than always requiring an array.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by wjordan** [comment]
Would [`CODEOWNERS`](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) be a helpful feature for this?

**Comment by Hamms** [comment]
Oooh, I didn't know about that!

I was planning to use https://github.com/orgs/code-dot-org/teams/i18n plus http://octokit.github.io/octokit.rb/Octokit/Client/Reviews.html#request_pull_request_review-instance_method but this looks super interesting

**Comment by Hamms** [comment]
I'm actually getting the following warning from Octokit when attempting this approach:

> WARNING: The preview version of the Reviews API is not yet suitable for production use.
You can avoid this message by supplying an appropriate media type in the 'Accept' request
header.

I haven't been able to figure out how to do that, and I really like the CODEOWNERS idea so I'm going to scrap this approach. Thanks for the suggestion!

**Comment by Hamms** [comment]
closing in favor of https://github.com/code-dot-org/code-dot-org/pull/31724

**Pull request closed without merging**
