### PR TITLE
bypass media proxy for code.org assets

### PR DESCRIPTION
**Pull request by cpirich**
* The media proxy is currently invoked when a student requests a fully qualified URL within applab, gamelab, etc. This is also true of library code written by our curriculum team that runs in the interpreter. It is not necessary to invoke the media proxy for assets under the `code.org` domain. As long as the protocol, domain, and port are the same, we won't have CORS issues or secure/insecure issues.
* Coupled with this change, if the HoC library code is updated to switch from `https://s3.amazonaws.com/cdo-curriculum/images/sprites/spritesheet/` to `https://curriculum.code.org/images/sprites/spritesheet/` and from `https://s3.amazonaws.com/cdo-curriculum/media/uploads/` to `https://curriculum.code.org/media/uploads/`, we will be able to load our assets more quickly for this year's HoC. @mrjoshida 
* Updated existing test case that expected this media proxy to be used on a `code.org` URL
* Expanded existing tests to verify the media proxy is added for fully-qualified URLs, but not `code.org` fully qualified URLs

### CODE REVIEW

**Comment by mrjoshida** [comment]
DanceLab library updated to use code.org urls.

**Comment by islemaster** [comment]
> As long as the protocol, domain, and port are the same, we won't have CORS issues or secure/insecure issues.

MDN [describes same-origin as](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) protocol, _host_ and port.  Different subdomains are different origins, and require the appropriate [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) headers on the requested resources.  I think this applies to the spritesheets from curriculum.code.org.

I'm guessing this is already set up, but can you point me to the configuration that allows `studio.code.org` to load assets from other subdomains like `curriculum.code.org`?

**Comment by cpirich** [comment]
@islemaster yes, they document it using both the term `host` and `domain` in different places. But I think you are right, that we will need to have explicit support with CORS headers in order for this to work properly in all scenarios.
Interestingly, the `p5` requests (for sounds and images) don't seem to require CORS, because I believe they are considered to be "simple requests" that don't require preflighting. But there are other places where we do need CORS to work properly (definitely for applab canvases, also it appears to be an issue when we load animations in gamelab).
I'll continue to investigate.

**Comment by cpirich** [comment]
@islemaster Ok given what I've learned, it seems simpler to just change our `p5.loadImage` override to bypass the media proxy. We're using `p5.sound` without the media proxy already. We don't seem to need it for `loadImage` in GameLab - it just happened as part of `assetPrefix.fixPath()`, which does other magic that we want to keep.

This change has zero impact on applab, which seems better.

**Pull request merged**
