### PR TITLE
Add enzyme library for testing

### PR DESCRIPTION
**Pull request by pcardune**
I'm using these in my applab import branch. Pulling out a standalone commit to make reviews easier.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
This seems fine, tho it's hard for me to judge how much value this has without seeing uses cases.

Also worth noting that circle-ci seems like it might be failing for legit reasons.

**Comment by pcardune** [comment]
Here's an example of sinon-chai and enzyme in action: https://github.com/code-dot-org/code-dot-org/blob/21c9c5dfb26bbce230c00d6dfc40b16ca4e054fb/apps/test/unit/applab/ImportProjectFormTest.js

enzyme example:

``` javascript
var form = shallow(<ImportProjectForm onProjectFetched={onProjectFetched} />);
expect(form.find('p').last().text()).to.equal(
      "We can't seem to find this project. " +
      "Please make sure you've entered a valid App Lab project URL.");
```

basically you get really nice react dom traversal api

sinon-chai example:

``` javascript
expect(sourcesApi.ajax).to.have.been.called;
// as opposed to
expect(sourceApi.ajax.called).to.be.true;
```

basically the assertions about sinon spies make more sense and you get better error messages when they fail.

**Comment by Bjvanminnen** [comment]
lgtm

**Comment by pcardune** [comment]
I've given up on adding sinon-chai. To get sinon-chai to work, we have to do one of the following:
1. upgrade to npm3
2. fork sinon-chai and change it's peerDependencies to allow any version of sinon
3. wait for sinon-2 to be released and for sinon-chai to "officially" support sinon2.

The problem is that sinon<2 does not work with webpack (except with great pain), and sinon-chai requires sinon<2 as a peer dependency, and npm2 enforces peer dependency requirements very rigidly (they are ignored in npm3).

sinon2 is supposed to get release any day now... but it hasn't happened yet.

See https://github.com/domenic/sinon-chai/issues/73

**Pull request merged**
