### PR TITLE
Cronjob for starting circle builds on a branch via their API

### PR DESCRIPTION
**Pull request by islemaster**
Since `staging-next` isn't our default branch and we don't normally run circle builds not associated with a PR and/or cancel all but the latest build on a branch, we're not currently getting much useful information out of Circle for this branch.

This cronjob will start a Circle build for the latest commit on a branch if it doesn't already have one running.  I'd like to enable it semi-regularly on staging-next so we get fairly regular feedback on the state of that branch.

### CODE REVIEW

**Comment by wjordan** [comment]
So I'm assuming the main reason why leaving open a PR to the default branch won't work to generate the CI builds we want on this branch is the lack of fine-grained 'auto-cancel redundant builds' (it's a global switch across all branches, and hard-coded to only have the default branch be the exception)? Or are there other reasons?

**Comment by islemaster** [comment]
Tested from local machine in both the case that the latest build has and has not been started.

**Comment by islemaster** [comment]
Correct: The two reasons we don't want to leave an open staging < staging-next PR are:

- We don't want someone to accidentally merge it.
- We'd still have to deal with the 'auto-cancel redundant builds' setting, which might keep us from getting useful build feedback until the end of each day.

**Comment by islemaster** [comment]
I haven't included a crontab change to enable this here, I wasn't sure yet what the best flow for that would be on staging-next.  But I've got the locals.yml on that machine all configured, so once merged someone could manually run this script to get the latest Circle build running, or we can set up a cronjob to run it every five minutes or so to ensure we get fairly granular build results on this branch.

**Comment by ewjordan** [comment]
Note: I'm taking this over and adding the cronjob change

**Pull request merged**
