### PR TITLE
Correctly strip carriage returns out of internationalized content

### PR DESCRIPTION
**Pull request by Hamms**
Follow-up to https://github.com/code-dot-org/code-dot-org/pull/21964,
which tried to strip out carriage returns by actually removing carriage
returns. But these are formatted strings, so they actually have
_escaped_ carriage returns (and newlines), not raw ones.

Update the sanitize operation accordingly.

Note that the original PR did fix one issue (the newlines introduced by wrapping the text), but the follow-up work to sync the fix up to crowdin without invalidating translations seemed to not work (see https://github.com/code-dot-org/code-dot-org/pull/22238), so I don't plan to actually merge this change until I can figure out how to sync the results without breaking things.

### CODE REVIEW

**Comment by tanyaparker** [comment]
Your explanation makes sense but I'm not super confident in reviewing, so I'll let @joshlory review. :3

**Comment by Hamms** [comment]
The direct implication is that the next i18n sync in will contain a bunch of changes like this:

```diff
diff --git a/i18n/locales/source/dashboard/instructions.yml b/i18n/locales/source/dashboard/instructions.yml
index 0e5c43a066a..bfca10e0fe0 100644
--- a/i18n/locales/source/dashboard/instructions.yml
+++ b/i18n/locales/source/dashboard/instructions.yml
@@ -3,13 +3,13 @@ en:
   data:
     instructions:
       2-3 Artist 1 new_instruction: "Hi, I'm an artist. You can write code to make me draw almost anything. Use a few blocks to make me draw over the grey lines in the picture. (Each line is 100 pixels long)"
-      2-3 Artist 11_instruction: "Give the stop sign a border by making an octagon with 100 pixels sides. \r\n\r\n"
-      2-3 Artist 12_instruction: "Create a circle to finish the eyeball!\r\n\r\nIf the artist turns 1 degree with each loop, how many times do you need to repeat the code to draw a circle? 180? 360? 500?"
+      2-3 Artist 11_instruction: "Give the stop sign a border by making an octagon with 100 pixels sides. \n\n"
+      2-3 Artist 12_instruction: "Create a circle to finish the eyeball!\n\nIf the artist turns 1 degree with each loop, how many times do you need to repeat the code to draw a circle? 180? 360? 500?"
       2-3 Artist 2 new_instruction: "This house has a half-finished wall. Each side is 100, but the half-finished wall is only 50. Complete the wall. "
       2-3 Artist 2_instruction: "This house has a half-finished wall. Each side is 100, but the half-finished wall is only 50. Complete the wall. "
       2-3 Artist 3.4_instruction: "The jump block moves the artist without drawing. Draw the dashed line using both the `jump forward` and `move forward` blocks. Each line is 50 pixels long."
       2-3 Artist 3_instruction: "This hat is 100 pixels high. Draw a hat that is 70 pixels less."
-      2-3 Artist 3new_instruction: "The red hat is 100 pixels tall. Finish drawing a black hat that is 70 pixels shorter. \r\n(Note: The width of each hat is 50 pixels.)"
+      2-3 Artist 3new_instruction: "The red hat is 100 pixels tall. Finish drawing a black hat that is 70 pixels shorter. \n(Note: The width of each hat is 50 pixels.)"
       2-3 Artist 4_instruction: "Help me complete the house for this cat."
       2-3 Artist 5_instruction: "Replace this code with a \"repeat times\" block to draw the same house using only 3 blocks."
       2-3 Artist 6_instruction: "This house needs a roof! Draw the triangle.  Hint: all three sides are the same length."
@@ -20,34 +20,34 @@ en:
       2-3 Artist 9_instruction: "Finish this kite"
       2-3 Artist Assessment 1_instruction: "Assessment: Finish drawing the last tooth. It is 25 pixels wide and 25 pixels tall."
       2-3 Artist Debugging 1_instruction: "This hat should only be 50 pixels wide.  Can you fix it?"
-      2-3 Artist Debugging 10_instruction: "The direction pad on my game controller is too narrow. \r\n\r\nCan you make it wider by 10 pixels?\r\n\r\nTry running the code first to see what's wrong."
-      2-3 Artist Debugging 11_instruction: "My snowflake is falling apart!\r\n\r\nCan you figure out what's going wrong?"
+      2-3 Artist Debugging 10_instruction: "The direction pad on my game controller is too narrow. \n\nCan you make it wider by 10 pixels?\n\nTry running the code first to see what's wrong."
+      2-3 Artist Debugging 11_instruction: "My snowflake is falling apart!\n\nCan you figure out what's going wrong?"
       2-3 Artist Debugging 12_instruction: "I'm supposed to add an ocean wave to this scene.  Can you help me?"
-      2-3 Artist Debugging 2_instruction: "This code for the cat's whiskers is wrong. \r\n\r\nFix this code to draw whiskers that are all the same length."
-      2-3 Artist Debugging 3_instruction: "My boat has a hole! \r\n\r\nWhat do you need to fix to make the ends meet?"
+      2-3 Artist Debugging 2_instruction: "This code for the cat's whiskers is wrong. \n\nFix this code to draw whiskers that are all the same length."
+      2-3 Artist Debugging 3_instruction: "My boat has a hole! \n\nWhat do you need to fix to make the ends meet?"
       2-3 Artist Debugging 4_instruction: "What is the image that we're trying to draw? Finish connecting the dots using the proper lines and angles."
```

Which will mean the `\r`s in crowdin will go away:

image

Which should hopefully make things less confusing for our translators.

**Comment by Hamms** [comment]
The _indirect_ implication is that when I sync this change up to crowdin, I'm going to want to do it in such a way that the existing translations for these strings don't get invalidated (which is what we normally want to happen when we change a string).

**Comment by Hamms** [comment]
@joshlory https://github.com/code-dot-org/code-dot-org/pull/22264 contains the content changes that happen as a result of this change (ie the changes that are going to get synced with the `update_without_changes` option).

Do you have any further concerns?

**Comment by joshlory** [comment]
Nope, LGTM!

**Pull request merged**
