### PR TITLE
set DCDO default for hoc_mode in hourofcode index

### PR DESCRIPTION
**Pull request by Erin007**
There isn't a way to set DCDO on the test machine.  UI/eyes tests run against a default setup, which means we need to set the default hoc_mode to `"soon-hoc"` to be consistent with production.

### CODE REVIEW

**Comment by tanyaparker** [comment]
Ah, so the only way to change it on test is to change what the default is on test?

**Comment by wjordan** [comment]
> It would be great if we could change test to use the same dynamic config as prod but I realize that is a much larger effort right now.

I disagree- I think the current setup, where tests never depend on ever-changing dynamic config, keeps tests reliable and reduces flakiness due to external factors like current dynamic-configuration state.

If tests depended on ever-changing dynamic config, it would mean that any dynamic-config changes (which by definition, can change quickly without going through our normal deploy-pipeline process) could cause existing tests based on the default config to break. I like the idea of writing tests against a known-good static configuration, and using dynamic config to express temporary, non-default, deviations from that baseline.

**Comment by drewsamnick** [comment]
I agree that any tests should be explicit about configuration they are using (dynamic or otherwise.)

Perhaps I'm misunderstanding the purpose of the test website environment. If it is a place to try out changes before pushing to production to make sure they actually will work once pushed then it ought to have the same configuration as production.

**Comment by wjordan** [comment]
I think you understand the `test` environment correctly- it's a `production`-like environment where we run (mostly automated unit and ui) tests on code to verify correct behavior before deploying to production.

I think the ambiguity is around our dynamic configuration variables. These are designed to intentionally circumvent our normal deploy workflow, and allow certain changes to be applied quickly without going through the normal test/verify process. This is inherently risky/unstable, and needs to be done with extreme caution (tweaking simple numeric constants or feature-flag switches, for example).

As I understand it at least, any dynamic configuration applied to an environment is by design an unstable/temporary deviation from the application's normal, stable, well-tested state. So if we want `production` and `test` to converge so that our automated tests are running against production-like configuration, we should work on updating our application-code to match the same configuration as `production` is currently running, not tweak the unstable dynamic-config settings in `test` to match what we happen to currently have set in `production`. This PR does the former, which I think is best.

When I say 'stable', I mean stable relative to our code-deploy workflow - we can update the defaults in our codebase at any point, but in doing so we would also need to update any related tests that might depend on the default behavior.

Perhaps the source of this confusion is that our use of this `hoc_mode` variable deviated from my assumed understanding of dynamic config, up until now. That is, our production environment was running with a non-default `hoc_mode` variable, which came to be seen as the 'stable' config. I think setting the `hoc_mode` default to match our current `production` setting helps clarify which setting we consider to be 'stable'.

At some point, we may want to write UI tests that cover _several_ dynamic-config permutations at once (since `production` could possibly switch between any of them at any moment), rather than only test against a single, 'stable' default configuration. This could be done with work on support for switching dynamic-config on the fly within a UI test (without affecting any other sessions running in parallel).

Hope this helps clarify my assumptions regarding this feature!

**Pull request merged**
