### PR TITLE
Enable eol-last and no-trailing-spaces

### PR DESCRIPTION
**Pull request by islemaster**
[**eol-last**](http://eslint.org/docs/rules/eol-last) ensures one newline at the end of every file.

[**no-trailing-spaces**](http://eslint.org/docs/rules/no-trailing-spaces) ensures no trailing whitespace at the end of every line.

### CODE REVIEW

**Comment by islemaster** [comment]
This change might push people to configure their editor to do this automatically. ;)

**Comment by Bjvanminnen** [comment]
Why do we care about eol last?

**Comment by islemaster** [comment]
[Because it's POSIX standard](http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline). The following is copied from StackOverflow:

Because that’s how the POSIX standard defines a line:

> 3.206 Line
> A sequence of zero or more non- <newline> characters plus a terminating <newline> character.

There's at least one hard advantage to this guideline when working on a terminal emulator: All Unix tools expect this convention and work with it. For instance, when concatenating files with cat, a file terminated by newline will have a different effect than one without:

```
$ more a.txt
foo$ more b.txt
bar
$ more c.txt
baz
$ cat *.txt
foobar
baz
```

And, as the previous example also demonstrates, when displaying the file on the command line (e.g. via more), a newline-terminated file results in a correct display. An improperly terminated file might be garbled (second line).

For consistency, it’s very helpful to follow this rule – doing otherwise will incur extra work when dealing with the default Unix tools.

**Comment by Bjvanminnen** [comment]
lgtm

**Pull request merged**
