### PR TITLE
Add Course Offerings for all Course Versions

### PR DESCRIPTION
**Pull request by dmcavoy**
Create a one-off script to run on levelbuilder to update all UnitGroups and Scripts which are acting as the top level item for a course but do not yet have a CourseVersion and/or CourseOffering. 

- For scripts make sure is_course, family_name and version_year are set for anything that is not in a unit_group. 
- For unit_groups make sure family_name and verison_year are set

We need to have CourseOfferings for everything we want to show in the dropdown including hidden scripts. 

**We could choose not to do this and just have curriculum writers add course_versions to the hidden scripts which they want in the dropdown later. Thoughts?**

## Testing story

- Ran it locally

### CODE REVIEW

**Review by bethanyaconnor — APPROVED** [review]
This makes sense to me as we're now enforcing family name/version year on script and unit group creation (for the most part). I also like how this can be rerun if script or unit groups end up not having a course version in the future.

**Comment by davidsbailey** [comment]
Hi folks, I think I am missing some of the mental model here. is the idea to get rid of units that are not standalone (and not in a course)? if so, do we also need to follow up with a code change to disallow non-standalone units (which are not in a course)?

**Comment by dmcavoy** [comment]
> Hi folks, I think I am missing some of the mental model here. is the idea to get rid of units that are not standalone (and not in a course)? if so, do we also need to follow up with a code change to disallow non-standalone units (which are not in a course)?

In order for a course/script to show up in the assignment dropdown it must have a course offering. Currently we have a bunch of hidden standalone scripts and a couple courses which do not have course offerings because they never got a family_name and version_year set. These courses currently show up for levelbuilders who have the ability to see and assign hidden scripts. To keep parity between what we have right now and what we will have after we move over to the new system these scripts need course offerings or we need to decide that its ok that they do not have course offerings and will not show in the dropdown.

**Comment by davidsbailey** [comment]
ok. to make sure we are on the same page, "hidden" now means any unlaunched published state, correct?

regardless, I think this change makes sense -- I would like to get clear on follow-up steps though. should we go ahead and get rid of `is_course` as a script property, and have `def is_course` return true for any script which is not a unit group? if not, why not? if so, let me know and I can open a follow-up item in our tech debt backlog.

**Review by davidsbailey — APPROVED** [review]

**Comment by dmcavoy** [comment]
> ok. to make sure we are on the same page, "hidden" now means any unlaunched published state, correct?
> 
> regardless, I think this change makes sense -- I would like to get clear on follow-up steps though. should we go ahead and get rid of `is_course` as a script property, and have `def is_course` return true for any script which is not a unit group? if not, why not? if so, let me know and I can open a follow-up item in our tech debt backlog.

Good questions. I think with our conversations around every Unit should have a UnitGroup it makes sense that we are moving toward a world where a Unit that is not in a UnitGroup is always a course. It seems like `def is_course` could be an intermediate step on the road to the ultimate goal of all Units have a UnitGroup so it might be worth doing. Interested to hear @bethanyaconnor thoughts.

**Comment by dmcavoy** [comment]
This reminded me that I do currently have this item in my sprint as something I wanted to do: https://codedotorg.atlassian.net/browse/PLAT-1631. I think this is another way to go about forcing this going forward. That before something moves out of in_development it has to be or a course or be in a course. This allows you to create units that you want to add to a course without them getting a course offering and course version.

As part of this one off script I could only update the scripts which are out of in_development and then let curriculum writers decide when they wish to update the in_development ones. I would do the work for PLAT-1631 before running this script if that was the plan. @davidsbailey thoughts?

**Comment by davidsbailey** [comment]
This sounds like an excellent and well-thought-out plan Dani! If it's not holding up too much stuff, I would say go for it. if this is going to end up holding up the assignment selector work, please include me as a PR reviewer (not just ep tools) so I get the proper notification.

**Comment by davidsbailey** [comment]
I just noticed something though -- when I create a script like this:
Screen Shot 2022-04-06 at 2 24 08 PM

then `is_course` gets set in my local DB. so now I am thinking that we might only be doing the extra work to allow in_development scripts to be unspecified (not is_course and not in a unit group) for the sake of relatively old scripts. How many scripts do you think we'll be wrong about if we just mark them all as `is_course`? if it is just 1 or 2, then it could be easier to set `is_course` for all scripts (like you have in this PR) and just manually fixing the setting if anyone complains.

just an idea in case this seems like less work than what you're proposing.

**Comment by dmcavoy** [comment]
Working on prepping the PR here: https://github.com/code-dot-org/code-dot-org/pull/45708

**Comment by bethanyaconnor** [comment]
> we are moving toward a world where a Unit that is not in a UnitGroup is always a course

I think this is the world we are moving to and I think that's a good thing for consistency. We're in a world where we have to handle units in unit groups and standalone units, it would be great to not have to handle scripts without course versions in their tree.

I don't have a strong opinion on whether in development scripts should be exempt, as long as it's clear to curriculum writers how to get into a good state

**Pull request merged**
