### PR TITLE
Drop the pegasus forms_schools table.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Given that the table has no data and no references to it, I assume it can be dropped. But I don't have any historical context as to why this table exists or ever existed.

```
SELECT COUNT(0) FROM forms_schools;
+----------+
| COUNT(0) |
+----------+
|        0 |
+----------+
```

```
DESCRIBE forms_schools;
+----------------------------------------+---------------------+------+-----+---------+----------------+
| Field                                  | Type                | Null | Key | Default | Extra          |
+----------------------------------------+---------------------+------+-----+---------+----------------+
| id                                     | int(10) unsigned    | NO   | PRI | NULL    | auto_increment |
| edit_token                             | varchar(50)         | NO   | UNI | NULL    |                |
| school_name                            | varchar(255)        | NO   |     | NULL    |                |
| school_address                         | text                | YES  |     | NULL    |                |
| school_website                         | varchar(255)        | NO   |     | NULL    |                |
| school_gender                          | tinyint(1) unsigned | YES  |     | NULL    |                |
| school_tuition                         | tinyint(1) unsigned | YES  |     | NULL    |                |
| contact_name                           | varchar(255)        | YES  |     | NULL    |                |
| contact_email                          | varchar(255)        | YES  |     | NULL    |                |
| contact_phone                          | varchar(255)        | YES  |     | NULL    |                |
| level_preschool                        | tinyint(1)          | YES  |     | NULL    |                |
| level_elementary                       | tinyint(1)          | YES  |     | NULL    |                |
| level_middle_school                    | tinyint(1)          | YES  |     | NULL    |                |
| level_high_school                      | tinyint(1)          | YES  |     | NULL    |                |
| level_college                          | tinyint(1)          | YES  |     | NULL    |                |
| level_vocational                       | tinyint(1)          | YES  |     | NULL    |                |
| language_alice                         | tinyint(1)          | YES  |     | NULL    |                |
| language_arduino                       | tinyint(1)          | YES  |     | NULL    |                |
| language_cplusplus                     | tinyint(1)          | YES  |     | NULL    |                |
| language_html                          | tinyint(1)          | YES  |     | NULL    |                |
| language_java                          | tinyint(1)          | YES  |     | NULL    |                |
| language_javascript                    | tinyint(1)          | YES  |     | NULL    |                |
| language_kodu                          | tinyint(1)          | YES  |     | NULL    |                |
| language_logo                          | tinyint(1)          | YES  |     | NULL    |                |
| language_mobile_apps                   | tinyint(1)          | YES  |     | NULL    |                |
| language_perl                          | tinyint(1)          | YES  |     | NULL    |                |
| language_php                           | tinyint(1)          | YES  |     | NULL    |                |
| language_python                        | tinyint(1)          | YES  |     | NULL    |                |
| language_ruby                          | tinyint(1)          | YES  |     | NULL    |                |
| language_scratch                       | tinyint(1)          | YES  |     | NULL    |                |
| language_scheme                        | tinyint(1)          | YES  |     | NULL    |                |
| language_other                         | varchar(255)        | YES  |     | NULL    |                |
| format_in_school_daily_course          | tinyint(1)          | YES  |     | NULL    |                |
| format_in_school_ap_cs                 | tinyint(1)          | YES  |     | NULL    |                |
| format_in_school_university            | tinyint(1)          | YES  |     | NULL    |                |
| format_in_school_robotics              | tinyint(1)          | YES  |     | NULL    |                |
| format_in_school_integrated            | tinyint(1)          | YES  |     | NULL    |                |
| format_in_school_summer_school         | tinyint(1)          | YES  |     | NULL    |                |
| format_in_school_other                 | tinyint(1)          | YES  |     | NULL    |                |
| format_out_of_school_summer_camp       | tinyint(1)          | YES  |     | NULL    |                |
| format_out_of_school_after_school      | tinyint(1)          | YES  |     | NULL    |                |
| format_out_of_school_all_day_1_week    | tinyint(1)          | YES  |     | NULL    |                |
| format_out_of_school_all_day_multiweek | tinyint(1)          | YES  |     | NULL    |                |
| format_out_of_school_other             | tinyint(1)          | YES  |     | NULL    |                |
| format_online_class                    | tinyint(1)          | YES  |     | NULL    |                |
| format_online_teacher_resource         | tinyint(1)          | YES  |     | NULL    |                |
| format_online_other                    | tinyint(1)          | YES  |     | NULL    |                |
| format_in_school_other_description     | varchar(255)        | YES  |     | NULL    |                |
| format_out_of_school_other_description | varchar(255)        | YES  |     | NULL    |                |
| format_online_other_description        | varchar(255)        | YES  |     | NULL    |                |
| class_description                      | text                | NO   |     | NULL    |                |
| created_at                             | datetime            | YES  |     | NULL    |                |
| created_ip                             | varchar(39)         | NO   |     | NULL    |                |
| updated_at                             | datetime            | YES  |     | NULL    |                |
| updated_ip                             | varchar(39)         | YES  |     | NULL    |                |
| contact_id                             | int(10) unsigned    | NO   | MUL | NULL    |                |
+----------------------------------------+---------------------+------+-----+---------+----------------+
```

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @breville @wjordan Does anyone know anything about the history of this table?

**Comment by tanyaparker** [comment]
This looks like the beginnings/was replaced by code.org/learn/local. Assuming removing this doesn't affect that map, lgtm to drop.

**Comment by breville** [comment]
Also not sure.  Maybe @aoby recognises?

**Comment by ashercodeorg** [comment]
@tanyaparker The page code.org/learn/local seems to be broken?

image

**Comment by ashercodeorg** [comment]
Stumbled upon https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/forms/class_submission.rb randomly. This class seems to be an object for storing similar (identical?) data. It is persisted in the `pegasus.forms` table and in `SOLR`.

**Comment by aoby** [comment]
I don't recognize it either. Seems fine to drop.

@ashercodeorg that class_submission form is exposed here https://code.org/learn/local. I don't know anything about it, but I agree it does not reference that table.

**Pull request merged**
