### PR TITLE
Fix missing goals in hoc2015 on Safari

### PR DESCRIPTION
**Pull request by islemaster**
Tries a few things, seems to have a positive effect on Safari 7 and Safari 8:
- We had incorrectly specified 16 frames in goal animation for the hoc2015x skin, which may have been causing issues with image positioning/clip rect positioning.  Maybe it was working by accident?  I've changed this to 1 frame, since we have a nonanimated goal.
- For good measure, we no longer apply a clip rect at all to nonanimated goals - it's not needed.
- I'm disabling filter effects on Safari anyway, because they are not rendering correctly: Even with the clip rect fix above, the glow filter is causing an undesired discoloration on the goal.

### CODE REVIEW

**Comment by islemaster** [comment]
- @joshlory @cpirich 

I'm going to run through existing playlab tutorials before I merge this to make sure I didn't regress goals anywhere else with the clip rect change.

**Comment by islemaster** [comment]
This breaks Playlab.  Fixing...

**Comment by breville** [comment]
lgtm

**Comment by islemaster** [comment]
s/playlab/stage/1/puzzle/6 regresses if we generally try to disable clip rects on nonanimated goals, because it uses a single frame from a sprite sheet for a nonanimated goal :angry: applying a more surgical fix to hoc2015.

**Comment by islemaster** [comment]
@breville new version of this only disables the goal clip rect in the hoc2015x skin.

**Comment by breville** [comment]
looks good.

**Comment by islemaster** [comment]
Verified against other scripts.  Will merge when tests pass.

**Comment by islemaster** [comment]
@philbogle clear to merge hoc2015 bugfix to staging?

**Comment by philbogle** [comment]
Yes, hoc2015 bugfixes are automatically approved.

**Pull request merged**
