### PR TITLE
I18n sync Down & Out 12/14

### PR DESCRIPTION
**Pull request by deploy-code-org**
# I18n Sync Down & Out

This PR contains all changes to translations made since the last sync (usually a week).

## To Review:

Look through the changes in each of the commits and verify that all changes are expected. Note that **it is not necessary to review every single "dashboard i18n update" commit.** These commits are batched by language to make it easier to review just a couple commits in this category.

### Things to Note:

- We expect translation changes to come in on a regular basis; new strings will be translated, existing translations will be updated, and source string removals will result in translations for those strings also being removed.

- We expect translations to arrive in large batches, so don't worry if you see a large group of changes in a specific language.

- We _do not_ usually expect to see a large number of formatting changes, or batches of changes that apply to strings in every single language. If you see this, it usually means either that a code change went in or that something broke.

## Known Issues:

- If the CI unit tests fail at the `grunt messages:all` step, they will typically fail with a message like:

  ```
  [2019-10-04 02:38:57] Running "messages:all" (messages) task
  [2019-10-04 02:39:00] Warning: Error processing localization file i18n/common/zh_tw.json: SyntaxError: Expected [0-9a-zA-Z$_] but "\u8A0A" found. Use --force to continue. 
  ```

  This usually means that a translator has translated one of the [MessageFormat variables](https://messageformat.github.io/messageformat/page-guide#toc2__anchor). In this case, you should find and fix the offending translation in crowdin, and then manually update the associated strings in `i18n/locales` and `apps/i18n`.

  See https://github.com/code-dot-org/code-dot-org/pull/31098/commits/ab3e5d1d740869a880f2e9da5cf0a4348886915e and https://github.com/code-dot-org/code-dot-org/pull/31098/commits/0fca37658cacaaff55d9adfc9d04c40b37cc5e2d for an example.

## To Deploy:

Once one or two people have reviewed and approved this change and the tests are passing, ship it!

It's not necessary to wait for everyone on the team to review.

### CODE REVIEW

**Comment by hacodeorg** [comment]
This is the output from the i18n PR analyzer tool (a Foundation Hackathon project). Posting it here to see if it can help reviewing i18n PRs faster.

Top 5 files sorted by number of changes:
- `bin/i18n/crowdin/codeorg_etags.json`, changes: 14907, additions: 7516, deletions: 7391
- `i18n/locales/uz-UZ/hourofcode/uz.yml`, changes: 5309, additions: 2731, deletions: 2578
- `pegasus/sites.v3/hourofcode.com/i18n/uz.yml`, changes: 5309, additions: 2731, deletions: 2578
- `dashboard/config/locales/slides.uz-UZ.yml`, changes: 4159, additions: 4158, deletions: 1
- `i18n/locales/uz-UZ/dashboard/slides.yml`, changes: 1885, additions: 1885, deletions: 0

Top 5 commits sorted by number of changes:
- eebf6719e338d7ad95df883af06decb498b8a6e2: etags updates
  - total changes: 15153
  - additions: 7639
  - deletions: 7514
  - changed files: 3
  - file with the most changes: `bin/i18n/crowdin/hour-of-code_etags.json`, changes: 178, additions: 89, deletions: 89
- 48ca06f0ab9c713202b7ece96ed86fb87f5d820d: hoc i18n updates
  - total changes: 14292
  - additions: 7358
  - deletions: 6934
  - changed files: 86
  - file with the most changes: `pegasus/sites.v3/hourofcode.com/i18n/uz.yml`, changes: 5309, additions: 2731, deletions: 2578
- 6586120f001f056bd15ccbe933d9b26fe49f955d: dashboard i18n updates - Uzbek
  - total changes: 12554
  - additions: 12423
  - deletions: 131
  - changed files: 16
  - file with the most changes: `i18n/locales/uz-UZ/dashboard/unplugged.yml`, changes: 341, additions: 337, deletions: 4
- 93c727775e4f39007f4a13c8a35b30117c2fad83: apps i18n updates
  - total changes: 6422
  - additions: 5753
  - deletions: 669
  - changed files: 58
  - file with the most changes: `i18n/locales/zh-TW/blockly-mooc/turtle.json`, changes: 2, additions: 1, deletions: 1
- cdcaa519aeaa06a2fbed31bf51a736eb2384e33e: animation library i18n updates
  - total changes: 2829
  - additions: 2608
  - deletions: 221
  - changed files: 76
  - file with the most changes: `i18n/locales/zu-ZA/animations/spritelab_animation_library.json`, changes: 8, additions: 7, deletions: 1

**Comment by Hamms** [comment]
Looks like some of the new Uzbek translations added some syntax errors. Fixing now.

**Comment by Hamms** [comment]
Broken translations:
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#404318
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#1788958
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#110735
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#2808
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#2373028
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#2422904
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#400624
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#4949
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#3094
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#2371454
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#137005
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#137006
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#134463
- https://crowdin.com/translate/codeorg/43/enus-uz?filter=basic&value=0#134465

**Comment by castro-jorge** [comment]
@Hamms I fixed the errors in Crowdin

**Comment by Hamms** [comment]
Hmmm, looks like drone isn't running for some reason

**Review by Hamms — CHANGES_REQUESTED** [review]
definitely don't merge this until we can get a drone run

**Review by Hamms — APPROVED** [review]

**Pull request merged**
