### PR TITLE
Adding potential_teachers data

### PR DESCRIPTION
**Pull request by jordan-springer**
Bringing in `potential_teachers` to redshift for RED team analysis

schema: https://github.com/code-dot-org/code-dot-org/blob/92a89e8d1d94cdd6eda58543965e26e2f250c467/dashboard/db/schema.rb#L1479

cc @nataliazm99 

## Links

- jira ticket: [DATAOPS-573](https://codedotorg.atlassian.net/browse/DATAOPS-573)

## Testing story

```
code-dot-org % export AWS_PROFILE=codeorg-admin
code-dot-org % bin/aws_access
AWS access: GoogleSignInAdmin/suresh@code.org

code-dot-org % bundle exec rake stack:data:validate RAILS_ENV=production ADMIN=true

Pending update for stack `DATA-production`:
Modify DMSCronPii [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TableMappings)
Finished stack:data:validate (1 minute)
```

## Deployment strategy

```
code-dot-org % bundle exec rake stack:data:start RAILS_ENV=production

Pending update for stack `DATA-production`:
Modify DMSCronPii [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TableMappings)
Proceed? [y/n]
y
 Stack update requested, waiting for provisioning to complete...
.2024-02-28 22:59:47 UTC- DMSCronPii [UPDATE_IN_PROGRESS]
....2024-02-28 23:00:23 UTC- DMSCronPii [UPDATE_COMPLETE]
.2024-02-28 23:00:26 UTC- DATA-production [UPDATE_COMPLETE_CLEANUP_IN_PROGRESS]

Stack update complete.
```

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
This table is being imported into the PII Redshift database as [it contains names and emails](https://github.com/code-dot-org/code-dot-org/blob/a0a417cff74187fe0543cf852afa6484ae1024f5/dashboard/app/models/potential_teacher.rb) of potential teachers.

**Review by cat5inthecradle — APPROVED** [review]

**Comment by sureshc** [comment]
> This table is being imported into the PII Redshift database as [it contains names and emails](https://github.com/code-dot-org/code-dot-org/blob/a0a417cff74187fe0543cf852afa6484ae1024f5/dashboard/app/models/potential_teacher.rb) of potential teachers.

@jordan-springer The naming conventions in this configuration file are NOT intuitive, but we need to move this entry to the `cron-pii` section so that it is exported to the `dashboard_pii` schema in Redshift.

**Comment by cat5inthecradle** [comment]
Ah, right, I misread the yaml.

**Comment by jordan-springer** [comment]
> > This table is being imported into the PII Redshift database as [it contains names and emails](https://github.com/code-dot-org/code-dot-org/blob/a0a417cff74187fe0543cf852afa6484ae1024f5/dashboard/app/models/potential_teacher.rb) of potential teachers.
> 
> @jordan-springer The naming conventions in this configuration file are NOT intuitive, but we need to move this entry to the `cron-pii` section so that it is exported to the `dashboard_pii` schema in Redshift.

I apologize for the inconsistency, it was an educated guess. What convention am I missing?

**Pull request merged**
