### PR TITLE
AiLab: Some import dialog fixes in App Lab (again)

### PR DESCRIPTION
**Pull request by breville**
Second attempt at this.  (The first attempt, https://github.com/code-dot-org/code-dot-org/pull/40302, was reverted due to a strange side effect, though it would still be my preferred approach.  This change does not have the same side effect.)

- Import now works when invoked on the design tab.
- The buttons now look the same when invoked on the design tab as when invoked on the code tab; before, some CSS from above was affecting them.
- The entire content of the dialog no longer scrolls a bit.

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
I like that this imports AI code only into applab, rather than into shared components. the previous PR imported AI code into every app which uses CodeWorkspace. this is the only part of the PR I looked at -- I'm hoping other reviewers who are more familiar with the feature can cover the rest.

there are some weird dependency problems in apps/src/code-studio which sometimes cause things to break when large new chunks of code are added to the code there. while it would be nice to diagnose and fix those at some point, at the moment those problems seem to be serving to help keep big chunks of unnecessary code out of site pages which don't need them 🤷

**Review by Erin007 — APPROVED** [review]

**Comment by Erin007** [comment]
Doesn't need to be part of this PR, but is anyone tracking adding a regression test for the Minecraft dialog?

**Comment by davidsbailey** [comment]
> Doesn't need to be part of this PR, but is anyone tracking adding a regression test for the Minecraft dialog?

@breville can you make sure this is at least tracked in Jira before you merge? I would expect that this falls on star labs, but @aaronwaggener could perhaps object.

**Comment by aaronwaggener** [comment]
No objections to tracking the addition of a test in the StarLabs project. Thank you for following up.

Edit: @breville created [STAR-1570](https://codedotorg.atlassian.net/browse/STAR-1570)

**Pull request merged**
