### PR TITLE
I18n sync Down & Out 08/14

### PR DESCRIPTION
**Pull request by deploy-code-org**
# I18n Sync Down & Out

This PR contains all changes to translations made since the last sync (usually a week).

## To Review:

Look through the changes in each of the commits and verify that all changes are expected. Note that **it is not necessary to review every single "dashboard i18n update" commit.** These commits are batched by language to make it easier to review just a couple commits in this category.

### Things to Note:

- We expect translation changes to come in on a regular basis; new strings will be translated, existing translations will be updated, and source string removals will result in translations for those strings also being removed.

- We expect translations to arrive in large batches, so don't worry if you see a large group of changes in a specific language.

- We _do not_ usually expect to see a large number of formatting changes, or batches of changes that apply to strings in every single language. If you see this, it usually means either that a code change went in or that something broke.

## Known Issues:

- If the CI unit tests fail at the `grunt messages:all` step, they will typically fail with a message like:

  ```
  [2019-10-04 02:38:57] Running "messages:all" (messages) task
  [2019-10-04 02:39:00] Warning: Error processing localization file i18n/common/zh_tw.json: SyntaxError: Expected [0-9a-zA-Z$_] but "\u8A0A" found. Use --force to continue. 
  ```

  This usually means that a translator has translated one of the [MessageFormat variables](https://messageformat.github.io/messageformat/guide/#variables). In this case, you should find and fix the offending translation in crowdin, and then manually update the associated strings in `i18n/locales` and `apps/i18n`.

  See https://github.com/code-dot-org/code-dot-org/pull/31098/commits/ab3e5d1d740869a880f2e9da5cf0a4348886915e and https://github.com/code-dot-org/code-dot-org/pull/31098/commits/0fca37658cacaaff55d9adfc9d04c40b37cc5e2d for an example.

## To Deploy:

Once one or two people have reviewed and approved this change and the tests are passing, ship it!

It's not necessary to wait for everyone on the team to review.

### CODE REVIEW

**Comment by deploy-code-org** [comment]
This comment is created by running: `bin/i18n/analyze_pr.rb -p 53281 -c`

Top 5/1558 files sorted by the number of changes:
- `bin/i18n/crowdin/codeorg_etags.json`, 40892 changes (20446 additions, 20446 deletions).
- `i18n/locales/ps-AF/hourofcode/ps.yml`, 23362 changes (11775 additions, 11587 deletions).
- `i18n/locales/hy-AM/hourofcode/hy.yml`, 23259 changes (12062 additions, 11197 deletions).
- `pegasus/sites.v3/hourofcode.com/i18n/hy.yml`, 23259 changes (12062 additions, 11197 deletions).
- `i18n/locales/fa-AF/hourofcode/af.yml`, 22963 changes (11553 additions, 11410 deletions).

Top 5/89 commits sorted by the number of changes:
- Commit: hoc i18n updates
  - 1083668 changes (555910 additions, 527758 deletions).
  - 300 files changed.
  - File with the most changes: `i18n/locales/ps-AF/hourofcode/ps.yml`, 23362 changes (11775 additions, 11587 deletions).
- Commit: etags updates
  - 49832 changes (24916 additions, 24916 deletions).
  - 3 files changed.
  - File with the most changes: `bin/i18n/crowdin/codeorg_etags.json`, 40892 changes (20446 additions, 20446 deletions).
- Commit: apps i18n updates
  - 23628 changes (671 additions, 22957 deletions).
  - 180 files changed.
  - File with the most changes: `apps/i18n/mlPlayground/it_it.json`, 2738 changes (82 additions, 2656 deletions).
- Commit: dashboard i18n updates - Ukrainian
  - 3626 changes (2283 additions, 1343 deletions).
  - 30 files changed.
  - File with the most changes: `dashboard/config/locales/activity_sections.uk-UA.json`, 1932 changes (992 additions, 940 deletions).
- Commit: dashboard i18n updates - Albanian
  - 3415 changes (2824 additions, 591 deletions).
  - 20 files changed.
  - File with the most changes: `dashboard/config/locales/activity_sections.sq-AL.json`, 2077 changes (1704 additions, 373 deletions).

**Comment by wilkie** [comment]
From what I can tell, nothing looks bad.

* There are some new strings getting translated in a variety of languages.
* Then it looks like a wide contribution of Afghanistan Pashto translations causing a huge delta of inserts/deletes since we committed english strings under that locale and those are all getting deleted and replaced with translated content.
* Same going for Armenian.

**Comment by mgc1194** [comment]
It seems sus all the deletions in the mlPlayground datasets. I'll investigate if they have been removed intentionally or accidentally.
```
Commit: apps i18n updates
23628 changes (671 additions, 22957 deletions).
180 files changed.
File with the most changes: apps/i18n/mlPlayground/it_it.json, 2738 changes (82 additions, 2656 deletions).
```

In fact, none of those changes appear in the synced-down content.

**Comment by wilkie** [comment]
Yes, good catch. I'm also not seeing those on the server right now... did things get reset?

I'm not sure why they would drop those dataset tags... they should be picked up. All the information *is* there.

**Comment by wilkie** [comment]
Superseded by https://github.com/code-dot-org/code-dot-org/pull/53306

**Pull request closed without merging**
