### PR TITLE
Add back oceans-overview image

### PR DESCRIPTION
**Pull request by bethanyaconnor**
When I deleted images in https://github.com/code-dot-org/code-dot-org/pull/60979, I only checked for `/images/oceans/`, not for `/images/fill-484x234/oceans/`. 

I searched `images/fill.*/oceans` and only found `oceans-overview` (except in an unused view, which I'm removing in #61360).

### CODE REVIEW

**Review by kelbyhawn — COMMENTED** [review]
Can you include a screenshot of where this shows up to confirm it's back?

**Review by hannahbergam — COMMENTED** [review]
Just making sure- this will have the right naming conventions to show up where it is supposed to?

**Comment by bethanyaconnor** [comment]
Screenshot 2024-09-26 at 1 23 15 PM

**Review by kelbyhawn — APPROVED** [review]

**Comment by bethanyaconnor** [comment]
@hannahbergam I don't fully understand your question but I think the answer is yes!

**Comment by hannahbergam** [comment]
> @hannahbergam I don't fully understand your question but I think the answer is yes!

Hahah it was basically Kelby's question. Looks like it's back!

**Review by hannahbergam — APPROVED** [review]
LGTM

**Pull request merged**
