### PR TITLE
Update dance party string for 2020

### PR DESCRIPTION
**Pull request by clareconstantine**
Since 2018 is no longer "last year", update this string. The new string has been added to the gsheet for translation.

**Before:**
Screen Shot 2020-11-10 at 11 52 10 AM

**After:**
Screen Shot 2020-11-10 at 11 51 10 AM

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by Hamms — COMMENTED** [review]
Is there a specific reason to add a new string here, rather than updating the existing one?

**Comment by clareconstantine** [comment]
> Is there a specific reason to add a new string here, rather than updating the existing one?

I added the new one because the old one had 2019 in the name, but now that I think about it, this string would still make sense even with 2019 in the name. Do we prefer editing existing strings rather than adding new ones?

**Comment by Hamms** [comment]
We don't have a blanket preference for one over the other, but I think in this case in makes sense. In particular, because our motivation for making a change is because the old string is no longer accurate, we should either:

1. Add a new string with the more accurate data, update _every_ place the old string is being used to instead use the new string, and then fully delete the old string. OR
2. Just update the old string to be accurate

2 is obviously much easier;  the only downside I think is that it's a bit weird to have a date in a string key, but overall I think that's a minor enough downside that it still seems reasonable.

**Comment by clareconstantine** [comment]
@elijah that makes sense! I updated the existing string and am closing this PR.

**Pull request closed without merging**
