### PR TITLE
Fix violations of and reenable Lint/InheritException.

### PR DESCRIPTION
**Pull request by asherkach**

### CODE REVIEW

**Comment by asherkach** [comment]
CC @aoby for review

**Comment by davidsbailey** [comment]
heads up that staging-next is going away, so this PR should be edited to point to staging instead.

**Comment by asherkach** [comment]
@davidsbailey, mind reopening this PR, pointing it against staging, and merging (presuming no conflicts)? Alternately @aoby?

**Comment by aoby** [comment]
Reopening, based against staging...

**Pull request merged**
