### PR TITLE
Hack Day Item #44: Remove workspace colon

### PR DESCRIPTION
**Pull request by epeach**
Removing colon when the blocks used aren't displayed. I would like sign-off from product since I went ahead and made some choices about when to keep the colon that I'd like to confirm align with their idea for this task. See https://docs.google.com/document/d/1W-5Uh94GZZDOgtuud4FvAkBztLh-_yyQxXh0TKf228w/edit?disco=AAAAItm2Zf8 and https://docs.google.com/document/d/1W-5Uh94GZZDOgtuud4FvAkBztLh-_yyQxXh0TKf228w/edit?disco=AAAAItm2Zgg

Before:
Screenshot from 2020-04-27 11-42-37
Screenshot from 2020-04-27 11-43-07
Screenshot from 2020-04-27 11-43-48
Screenshot from 2020-04-27 11-43-22

After:
Screenshot from 2020-04-27 11-36-39
Screenshot from 2020-04-27 11-36-29
Screenshot from 2020-04-27 11-35-38
Screenshot from 2020-04-27 11-36-15

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by Hamms — COMMENTED** [review]
Note that until the translations get updated, this will result in a duplicated colon for non-EN

**Comment by epeach** [comment]
@Hamms How long does it take for translations to be updated? Trying to decide if that's a blocker . . .

**Comment by ghost** [comment]
looks good!

**Comment by Hamms** [comment]
It depends on the translators! @castro-jorge might be able to provide a better estimate

**Comment by ajosuarez** [comment]
Choices on when to keep vs leave look good!

**Comment by epeach** [comment]
@Hamms  - I did a bit of brainstorming with Star labs and we decided to just delete the old strings and add new ones - if we understand the pipeline correctly - this will result in non-en falling back to the english (until translated) which will have the correct punctuation and won't result in a double colon. Can you double check our understanding on that?

**Comment by Hamms** [comment]
Yep, that's right! Although I'd double-check with the international folks (ping @castro-jorge) that that behavior is preferred over a double colon

**Comment by Hamms** [comment]
Another option would be to add the new string into the translation pipeline but not use it yet; either give it some time to get translations or coordinate with our international partners to specifically translate this string, and then start using it once we're happy with the state of translations.

**Comment by epeach** [comment]
@Hamms - Checked in with Jorge - the double colon is preferable, so we're going to go with that and he's going to try and pull the colon out manually from some of the more popular languages. :+1: Thanks for your help with this!

**Review by bethanyaconnor — APPROVED** [review]
🎉

**Pull request merged**
