### PR TITLE
hoc2023: Update input selection UI

### PR DESCRIPTION
**Pull request by breville**
This updates the emoji selection UI to the official design, which includes an opening A.I. bot head like in AI Lab, flying emojis, and the ability to deselect selected emojis.  It also makes the AI modal a little taller to allow for two lines of text.

It still needs updated A.I. bot images.

https://github.com/code-dot-org/code-dot-org/assets/2205926/53d1ef1b-c035-469e-93d1-b16fac79d9ab

### CODE REVIEW

**Review by sanchitmalhotra126 — APPROVED** [review]
Neat, nice animation work! 
One question - what happens if you click a 4th emoji? Should we grey out the rest once you've hit the limit?

**Comment by breville** [comment]
> what happens if you click a 4th emoji? Should we grey out the rest once you've hit the limit?

Oh good point.  Nothing happens if clicking a 4th emoji.  I think we'll do a finesse pass and this would be a good candidate for that.

**Comment by breville** [comment]
> what happens if you click a 4th emoji? Should we grey out the rest once you've hit the limit?

Oh good point.  Nothing happens if clicking a 4th emoji.  I think we'll do a finesse pass and that would be a good candidate for that.

**Comment by breville** [comment]
> what happens if you click a 4th emoji? Should we grey out the rest once you've hit the limit?

Oh good point.  Nothing happens if clicking a 4th emoji.  I think we'll do a finesse pass and that would be a good candidate for that.

**Pull request merged**
