### PR TITLE
Import maker discount codes

### PR DESCRIPTION
**Pull request by bencodeorg**
## Description

Updates script to import maker discount codes for 2020-2021. There are two types of discount codes: codes that include shipping for teachers in Alaska and Hawaii (full discount codes), and codes that do not.

Codes are in two different CSVs, each without a header row. Previous imports have had separate columns for a "prefix" and a "code" -- in this iteration, prefixes and codes are already combined into a single column in the CSV.

I set these to expire at the end of 2021 -- @agealy, I can change to a different date that's aligned with the last redemption window if that is more sensible.

There are a total of 50 discount codes with shipping, and 800 without shipping -- I moved the threshold for Honeybadger alerting down to 25 (from 50) so that we don't get a Honeybadger warning every time a "with shipping" discount code is used. 

The rub here is that we wouldn't get an alert until very late for the non-shipping discount codes, but we've only used ~800 over the last two years so I'd be surprised if we actually reached that point.

Will need to execute this script twice on production (once for full discount codes, and once for the other discount codes).

## Testing story

Ran the following locally:
`bundle exec ruby ./populate_discount_codes.rb true <filename with discount codes with shipping>`
`bundle exec ruby ./populate_discount_codes.rb false <filename with discount codes without shipping>`

Confirmed that what was imported was as we'd expect.

### CODE REVIEW

**Comment by agealy** [comment]
@bencodeorg If the latest we want them to use the kits is spring 2021, an expiration of something like July 1, 2021 would make sense to me. Can you run the expiration date by Amy? I'm fine with whatever date in 2021 that works for the programs team.

**Comment by bencodeorg** [comment]
Sorry, dumb question @agealy -- these all have real expiration dates (ie, when they won't be accepted by Adafruit any more) that we present to teachers on the website. I'll ask Amy for the real expiration date.

**Review by molly-moen — APPROVED** [review]

**Review by islemaster — APPROVED** [review]
Awesome! LGTM pending final news on the desired expiration date for these new codes.

**Comment by bencodeorg** [comment]
Amy confirmed real expiration date should be April 30, 2021.

**Comment by bencodeorg** [comment]
Discount codes uploaded around 5:30 PST on 1/13.

**Pull request merged**
