### PR TITLE
changed cateogry of Minecraft specific block

### PR DESCRIPTION
**Pull request by WilliamHarmonMS**

### CODE REVIEW

**Comment by joshlory** [comment]
I think this commit has some extra changes in it.  Do you just want the `craftBlock('wait')` change?

Worth re-creating this commit off latest staging?

**Comment by WilliamHarmonMS** [comment]
Yeah, that was supposed to be just the wait block category change. The other changes were from my previous pull requests. Perhaps it still registered them as not diffing properly? I can try and create a new pull request with just the craftblock('wait') change? What's the best way to handle this?

**Comment by joshlory** [comment]
Probably easiest to craft a new commit with the `craftBlock('wait')` change alone.  Then you can force-push that commit to this branch.

**Comment by WilliamHarmonMS** [comment]
Pretend this never happened

**Pull request closed without merging**
