### PR TITLE
Add family name to teacher panel

### PR DESCRIPTION
**Pull request by rshipp**
Show family name in the teacher panel, behind a feature flag.

image

This seemed too small a change to add tests.

## Links

- jira ticket: [TEACH-553](https://codedotorg.atlassian.net/browse/TEACH-553)

### CODE REVIEW

**Comment by dju90** [comment]
Are we still showing the level bubble next to the student name, or is that being removed?

**Comment by dju90** [comment]
(discussed during check-in) ah, the screenshot is showing the unit overview. Viewing the teacher panel on a level page should bring up the level bubbles next to student names. We should double check how that looks - can you please provide a screenshot of that page?

**Review by hannahbergam — APPROVED** [review]
LGTM!

**Comment by rshipp** [comment]
on a lesson page, with long names:

image

it cuts off the names if they're very long, but that's an existing problem and not unique to this addition.

**Comment by dju90** [comment]
Cool, thanks!

**Pull request merged**
