### PR TITLE
Fixes and reenables the rubocop Style/TrivialAccessors check.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by aoby** [comment]
There are some test failures here that look legit, though unrelated to this change. Please take a look, maybe merge / rebase staging and re-run the test. 

LGTM otherwise.

**Comment by ashercodeorg** [comment]
Merged and rebased staging as suggested, CircleCI is rerunning. Previous failures seemed to stem from a script DSL issue?

**Comment by ashercodeorg** [comment]
FWIW, rebased with staging, running CircleCI again.

**Comment by ashercodeorg** [comment]
As noted from conversation in #developers slack, indexes to gsheet tables are created via [here](https://github.com/code-dot-org/code-dot-org/blob/e77028412545e149576a20de9617494139eb2317/pegasus/rake/seed.rake#L103-L103).

Thus, this PR is being dropped in favor of that approach.

EDIT: Oops. This has nothing to do with this PR, meant for another PR.

**Comment by ashercodeorg** [comment]
PTAL. Note that I intend to resolve the TODO in a subsequent PR.

**Pull request merged**
