### PR TITLE
Make sounds work in exported applab apps

### PR DESCRIPTION
**Pull request by pcardune**
I had to make some adjustments to the way urls get rewritten/prefixed and to the way sounds get played when loading from the local filesystem where ajax requests are not allowed. Key changes:
- move `Sounds` library to apps package
- `forceHTML5=true` when playing sounds on a page that is loaded from the local filesystem (because ajax won't work)
- don't rewrite asset urls to run through the media proxy, because again, ajax is not going to work.

### CODE REVIEW

**Comment by pcardune** [comment]
cc @philbogle: I ended up not having to resort to anything fancy to make sound playback work. Just need to `forceHTML5=true`.

**Comment by islemaster** [comment]
This seems good. I'll caution that there's a bazillion subtle bugs with audio and testing this properly is a headache and a half.

You should probably fix `code-studio/test/audio/audio_test.html` and maybe move it and the `npm run test-audio` command to apps, if the Sound utility is moving there.

**Comment by pcardune** [comment]
Good call on audio tests. Didn't know those were there! Updated.

**Comment by islemaster** [comment]
LGTM.  @bcjordan should probably give this a quick scan too, he's familiar with the audio stuff as well.

**Pull request merged**
