### PR TITLE
Fixes violations of the rubocop Style/UnneededPercentQ check.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes generated via "bundle exec rubocop --only Style/UnneededPercentQ --auto-correct".

Further manual fixes are necessary before the rubocop check can be reenabled.

### CODE REVIEW

**Comment by islemaster** [comment]
Does this even work?  I'm having trouble finding official documentation on this technique for multiline strings in Ruby, or any reference in our styleguide(s) for preferring one style over another.  Can you point to a source/reason for this change?

**Comment by ashercodeorg** [comment]
AFAIK, it works as expected (appending newline characters).

```
$ irb
irb(main):001:0> a = %q{
irb(main):002:0'   1
irb(main):003:0'   2
irb(main):004:0'   3
irb(main):005:0' }
=> "\n  1\n  2\n  3\n"
irb(main):006:0> b = "
irb(main):007:0"   1
irb(main):008:0"   2
irb(main):009:0"   3
irb(main):010:0" "
=> "\n  1\n  2\n  3\n"
irb(main):011:0> a == b
=> true
```

As for preferring one style over another, our [STYLEGUIDE.md](https://github.com/code-dot-org/code-dot-org/blob/staging/STYLEGUIDE.md) defaults to this [style guide ](https://github.com/bbatsov/ruby-style-guide), which specifies this preference in the [Percent Literal](https://github.com/bbatsov/ruby-style-guide/blob/master/README.md#percent-literals) section.

**Comment by islemaster** [comment]
Interesting.  I believe that it works, however the style guide section you link to says

> For multi-line strings, prefer heredocs.

...which is different than what you're changing to here.  For example, you are converting

``` ruby
steps %q{
  When I press "designModeButton"
  And I wait to see Applab design mode
}
```

to 

``` ruby
steps '
  When I press "designModeButton"
  And I wait to see Applab design mode
'
```

But converting to heredoc would look like this:

``` ruby
steps <<STEPS
  When I press "designModeButton"
  And I wait to see Applab design mode
STEPS
```

Did I miss a different spot in the styleguide where it recommends quoted multiline strings?

**Comment by ashercodeorg** [comment]
You missed nothing, the rubocop auto-correct seems to be violating its own style guide. Let me change these to heredocs. And if I get ambitious, I'll submit a bug report / bug fix to bbatsov.

**Comment by islemaster** [comment]
im not crazy

Interesting... kudos on finding a possible rubocop bug :+1:

**Comment by ashercodeorg** [comment]
PTAL.

**Comment by islemaster** [comment]
:+1: LGTM

**Pull request merged**
