### PR TITLE
Fix Contact Rollups update_district

### PR DESCRIPTION
**Pull request by sureshc**
This is a proposed fix for a HoneyBadger [Error](https://app.honeybadger.io/projects/45435/faults/39270260#notice-trace).  `find_by_sql` returns an array, but downstream logic (`find_each`) is expecting `users` to be an ActiveRecord Relation so it can iterate through the entire users table in batches.

Switch to a Sequel query and stream over the results

### CODE REVIEW

**Comment by sureshc** [comment]
I think this won't work on production.  ActiveRecord will look for the view on the primary database, but in the production environment, it's on the reporting replica.

**Comment by ewjordan** [comment]
Yeah, I was going to mention that, since the view is only on the replica - I'm wondering if there's a way to work around that, though, like setting that particular database for that view alone?

It would *probably* be safe to put the view on the primary. Because it doesn't get baked into the schema dump (which has bitten us before), I think we might be fine to even just do that manually.

I do notice that this query runs directly against the prod db; I'm not sure if that's something we need or not.

**Review by ewjordan — APPROVED** [review]

**Comment by sureshc** [comment]
@ewjordan I made a couple of more changes based on attempts to run these revisions on production.  Can you take a look?

**Comment by ewjordan** [comment]
LGTM!

**Pull request merged**
