### PR TITLE
Unify and enforce JSX style

### PR DESCRIPTION
**Pull request by islemaster**
Enables linting to enforce certain JSX rules in our styleguide, and changes existing code to conform.  There are a lot of changes; we were very inconsistent before.
# Example JSX that conforms to new linting

``` jsx
const oneLine = <OneLine prop1="x" prop2="y" />;
const multiLine = (
  <MultiLine
    prop1="x"
    prop2="y"
    multiLineProp={{
      key: value,
      key: value
    }}
  >
    <ChildOne/>
    <ChildTwo>Two</ChildTwo>
  </MultiLine>
);
```
# New rules
## [jsx-curly-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md)

Don't allow spaces between curlies and their content in JSX.  Autofixable. [Required by airbnb](https://github.com/airbnb/javascript/tree/master/react#spacing).

``` jsx
// Good
<Foo prop={value}/>
// Bad
<Foo prop={ value }/>
```

We only had two existing violations of this rule, so I think it's an easy sell.  There's one caveat - this rule is a little strange when reading comments inside JSX curlies and autofix will strip comments when the rule is violated.  Examples:

``` jsx
// Good
{/* comment */}
// Bad
{/* comment */ }
// What you get after autofix in the bad case:
{}

// Good
{" "/* comment */}
// Bad
{" " /* comment */}
// What you get after autofix in the bad case:
{" "}
```

I vote that this odd behavior is worth it to be consistent everywhere else. 
## [jsx-quotes](http://eslint.org/docs/rules/jsx-quotes)

Require double quotes for all literal JSX attributes, except those that themselves contain double quotes.  Autofixable. [Required by airbnb](https://github.com/airbnb/javascript/tree/master/react#quotes).

``` jsx
// Good
<Foo prop="value"/>
<Foo prop='a "value"'/>
// Bad
<Foo prop='value'/>
```
## [jsx-closing-bracket-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md)

If a component is multiline, the closing bracket should be on its own line and should align with the opening bracket. Autofixable. [Required by airbnb](https://github.com/airbnb/javascript/tree/master/react#tags).

``` jsx
// Good
<Foo prop="value"/>
<Foo
  prop="value"
/>
// Bad
<Foo
  prop="value"/>
<Foo
  prop="value"
  />
```
## [jsx-first-prop-new-line](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-first-prop-new-line.md): multiline

The first property should always be placed on a new line when the properties are spread over multiple lines. [Required by code-dot-org styleguide](https://github.com/code-dot-org/code-dot-org/blob/staging/STYLEGUIDE.md#user-content-js-react-long-components).

``` jsx
// Good
<Foo prop="value" prop="value"/>
<Foo
  prop="value"
  prop="value"
/>
// Bad
<Foo prop="value"
  prop="value"
/>
```
## [jsx-indent-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent-props.md): 2

Require attributes in a multiline tag to be indented 2 spaces from the opening bracket. Autofixable. [2 spaces (a single indentation) is implied by airbnb](https://github.com/airbnb/javascript/tree/master/react#alignment) but [our styleguide requires 4 spaces](https://github.com/code-dot-org/code-dot-org/blob/staging/STYLEGUIDE.md#user-content-js-react-long-components).  Of our existing code, slightly more was using a 2-space indent for props.  I propose we update our styleguide and use 2 spaces to be more like airbnb.

``` jsx
// Good
<Foo
  prop="value"
  prop="value"
/>
// Bad
<Foo
    prop="value"
    prop="value"
/>
```

One argument for four-space indent was that it set props apart from child components, like so:

``` jsx
<Foo
    prop="value"/>
  <Child/>
</Foo>
```

However, when combined with the closing bracket rule, 2-space indent is also fairly readable:

``` jsx
<Foo
  prop="value"
/>
  <Child/>
</Foo>
```
## [wrap-multilines](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/wrap-multilines.md)

Wrap JSX expressions in parentheses when they span more than one line (also helps with aligning closing tags). Autofixable. [Required by airbnb](https://github.com/airbnb/javascript/tree/master/react#parentheses).

``` jsx
// Good
let x = <Foo>bar</Foo>;
let y = (
  <Foo
    prop="value"
    prop="value"
  />
    bar
  </Foo>
);
// Bad
let y = <Foo
  prop="value"
  prop="value"
/>
  bar
</Foo>;
```
## [self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md)

Require self-closing tags for components with no children. [Required by airbnb](https://github.com/airbnb/javascript/tree/master/react#tags).

``` jsx
// Good
<Foo>bar</Foo>
<Foo/>
// Bad
<Foo></Foo>
```
# Considered and rejected for now
## [jsx-space-before-closing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-space-before-closing.md)

We [call out in our styleguide](https://github.com/code-dot-org/code-dot-org/blob/staging/STYLEGUIDE.md#react) that we don't care about this.

``` jsx
// Good
<Foo/>
<Foo />
```
## [jsx-max-props-per-line](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-max-props-per-line.md)

Our styleguide [requires one prop per line for multiline components](https://github.com/code-dot-org/code-dot-org/blob/staging/STYLEGUIDE.md#user-content-js-react-long-components) but this rule would also limit props-per-line for single-line components, and I couldn't find a way to separate it out.  Because of this I'd rather trust people's judgment for now, rather than put an arbitrary limit on this; it seems silly to disallow `<Foo x="2" y="3" style={style}/>` just to avoid some more obscure constructions.

``` jsx
// Good
<Foo x="2" y="3" style={style}/>
<Foo
  x="2"
  y="3"
  style={style}
/>

// Technically not styleguide-compliant, but not caught by linting:
<Foo
  x="2" y="3"
  style={style}
/>

```

### CODE REVIEW

**Comment by pcardune** [comment]
giphy

**Comment by islemaster** [comment]
I did consider breaking this PR up into one for each rule, but in many cases these rules are interdependent and enabling just one created some weird intermediate code.  In particular jsx-closing-bracket-location, jsx-first-prop-new-line and wrap-multilines are pretty tangled.

For example, just enabling closing-bracket-location often autocorrected code like this:

``` jsx
var component = <Component prop="foo" prop="bar"
    prop="baz"/>;
```

...to this:

``` jsx
var component = <Component prop="foo" prop="bar"
    prop="baz"
                />;
```

**Comment by islemaster** [comment]
@pcardune You just said today that "There are no styleguides, only linting."

**Comment by pcardune** [comment]
yes. This actually makes me very happy. As indicated by the smile on Michael Jackson's face.

LGTM.

**Comment by islemaster** [comment]
@breville @caleybrock @mehals any comments before I merge this?

**Comment by breville** [comment]
None from me.  Read through all the recommendations and they look sound.

**Comment by caleybrock** [comment]
^same here. Read through and they all seem like a good idea.

**Pull request merged**
