### PR TITLE
Make unit description able to use markdown and preview in editor

### PR DESCRIPTION
**Pull request by dmcavoy**
## Background

As part of preparing to starting writing curriculum all on LB (CB->LB) we want the description of a unit on the Script Overview page to support markdown.

## Edit experience:

Added a preview area for the description similar to the preview of the Teacher Resources button lower down on the page.

Screen Shot 2020-08-19 at 11 37 40 AM

## Script Overview Page

Now shows the description as markdown.

Screen Shot 2020-08-18 at 10 52 21 PM

## Links

- [spec](https://docs.google.com/document/d/13ZQuoNKMR0sgJsIVjHRSUVgfRnpIadfHwG8-DONoyxE/edit#)
- [PLAT-246](https://codedotorg.atlassian.net/browse/PLAT-246)
- [PLAT-247](https://codedotorg.atlassian.net/browse/PLAT-247)

## Testing story

- Added tests to ScriptOverviewHeaderTest and ScriptEditor to check that the markdown makes it to the SafeMarkdown component correctly

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
This is going to treat existing script descriptions as markdown, right? Flipping through scripts.en.yml... are the following still going to display properly?

1. raw links (still linkified?)
```
        K5PD:
          title: K5 Professional Development (old)
          description: 'For the latest online Professional Development resources for elementary school teachers here: https://studio.code.org/s/k5-onlinepd'
```

2. `\r\n` sequences
```
        csp3-2017:
          title: CSP Unit 3 - Intro to Programming ('17-'18)
          description: "This unit introduces the foundational concepts of computer programming, which unlocks the ability to make rich, interactive apps. This course uses JavaScript as the programming language, and App Lab as the programming environment to build apps, but the concepts learned in these lessons span all programming languages and tools.\r\n\r\nThis unit was last updated October 30th, 2017. Read more about curriculum updates at forum.code.org/c/csp/updates."
```

3. square brackets
```
        cspassessment:
          title: "[Deprecated] CS Principles Culminating Assessment"
          description: 'This assessment has been deprecated and is scheduled for removal in Summer of 2017.  Students may complete the test and see their own results, but a teacher will not be able to see results for students in a section.  Please use the official CSP practice exam from the College Board.  [This 55-question multiple choice assessment covers questions across 7 big ideas of computer science: Creativity, Abstraction, Data, Algorithms, Programming, The Internet, and Global Impact.]'
```

```
        time4cs-experiment-unit-2:
          title: Time4CS Experiment Unit 2
          description_audience: ''
          description_short: "[Add description]"
          description: "[Add description]"
```

**Review by davidsbailey — APPROVED** [review]
LGTM after checking that no scripts we care about break too badly. I used this (for example) to quickly search through scripts.en.yml for problematic syntax:
```
grep -B 5 'description:' config/locales/scripts.en.yml | grep -B 5 'description:.*\['
```

**Comment by dmcavoy** [comment]
Raw links still linkify:
Screen Shot 2020-08-19 at 5 36 01 PM

\r\n sequences actually work now (they apparently did not before):
Screen Shot 2020-08-19 at 5 37 26 PM

[] still work:
Screen Shot 2020-08-19 at 5 38 20 PM

**Comment by dmcavoy** [comment]
I checked a random assortment of the 2020 scripts as well just to make sure that things seem to be working. I'm going to go ahead with this change.

**Comment by davidsbailey** [comment]
perfect, thank you for checking!

**Pull request merged**
