### PR TITLE
Remove foreign key between peer reviews and level sources

### PR DESCRIPTION
**Pull request by bencodeorg**
Migration to remove foreign key between peer reviews and level sources (in order to unblock using migration tool [gh-ost](https://github.com/github/gh-ost), which doesn't allow foreign keys). 

The relationship between peer reviews and level sources is enforced at the application level [here](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/peer_review.rb#L38), so this should be ok.

### CODE REVIEW

**Comment by bencodeorg** [comment]
@sureshc give this a shot next week locally and see if it removes the foreign key (it appears to have worked, but I forgot to look at my local database before running to confirm 🤦‍♂)

**Comment by bencodeorg** [comment]
I think we're good to run this on all environments. I tested by:

1. Rolled this back and reran this locally with verbose logging on, 
2. got the raw SQL statement being run, 
3. ran the same raw SQL on the copy of production @uponthesun and I were using for testing the level sources migration. The FK removal succeeded ~immediately, as checked by looking for the existence of a foreign key between `peer_reviews` and `level_sources`.

**Comment by bencodeorg** [comment]
@sureshc could you take a look at this when you have a minute? Check out the testing I did and see if you think it sounds legitimate. One other question had is whether the change to `schema.rb` should be included here, or if that change is implemented by the migration once it gets run?

**Review by sureshc — APPROVED** [review]
Looks good.  I think best practice is for a migration Pull Request to include both the incremental change (the migration itself) AND the new schema.rb, which is what you've done.

**Pull request merged**
