### PR TITLE
Remove dubbed videos from videos.csv as they're not working correctly.

### PR DESCRIPTION
**Pull request by bethanyaconnor**

### CODE REVIEW

**Comment by joshlory** [comment]
What is the error?

**Comment by bethanyaconnor** [comment]
Users might see the English video then the dubbed video or vice versa. It looks like the server is saving some state between requests.

**Comment by bethanyaconnor** [comment]
I *think* I have a fix in #27731

**Comment by joshlory** [comment]
Fixing-forward with PR #27731 SGTM.

**Pull request closed without merging**
