### PR TITLE
Remove important rule from icon style

### PR DESCRIPTION
**Pull request by fisher-alice**
This PR removes the `!important` rule from the style rules of icons used in a table row within id `classroom-sections` or `uitest-personal-projects`.

This is no longer needed since `!important` is no longer used for icons in `application.scss`.

This change is motivated by updates made in https://github.com/code-dot-org/code-dot-org/pull/56932. See discussion [here](https://github.com/code-dot-org/code-dot-org/pull/56932/files#r1511566155)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by bencodeorg — APPROVED** [review]
Nice! I assume you were able to confirm that `#classroom-sections` is unchanged?

**Comment by fisher-alice** [comment]
> Nice! I assume you were able to confirm that `#classroom-sections` is unchanged?

Thanks for the reminder! I hadn't confirmed - just assumed it would be okay based on Denys's comment at https://github.com/code-dot-org/code-dot-org/pull/56932#discussion_r1512968227

Checking where `#classroom-sections` is used in `TeacherSections.jsx`, this does change the settings icon to a slightly lighter gray.

BEFORE update:
darker-gray-with-important

AFTER update:
lighter-gray-removed-icon-style

@levadadenys - could you let me know if this color change is okay? If not, I can implement in a different way. Thanks @bencodeorg !

Denys - I'm actually wondering if we can remove: https://github.com/code-dot-org/code-dot-org/blob/8703117a48404682017d9298c1db0bfc98d3a105/shared/css/phase1-design-system.scss#L171-L173.
Then styling will fall back to that of the parent `td`. Then there is no need to override in the module with `!important`.

**Comment by levadadenys** [comment]
Wow, turned out to be harder then I though. Going to push changes I was able to make locally to improve overall situation. @fisher-alice feel free to revert my commit in case of anything.

Also, if/when - merging - we'll need to doublecheck the eye tests to confirm that there'll be no visual changes in the table since our `!important` styles from `phase1-design-system.scss` makes sure everything looks as we want it to look in rebranded version.

**Comment by levadadenys** [comment]
Pushed a commit from me.
* added !important back for #classroom-sections, #uitest-personal-projects th 
* updated QuickActionsCell.jsx so that we don't need !important for #classroom-sections, #uitest-personal-projects td

Reason why I added !important again for `#classroom-sections, #uitest-personal-projects th` is that when I open branch locally, sort buttons/icons looked dark on my machine (caused by some inline styles from `reactabular-table` styles I wasn't able to remove)

Before:
Знімок екрана 2024-03-06 о 13 07 22

After:
Знімок екрана 2024-03-06 о 13 13 23


@fisher-alice answering your question about completely removing icon styles from `phase1-design-system.scss` - I think it's better to keep styles for update there so that it'll be easier to maintain and make sure everything is up to date.
Also, keeping in mind believe that we'll eventually update most of the screens with design system components/elements - 
I feel like it's more long term time-efficient not to rework old tables too much, but to create a new tables and use them sooner

Initial reason of adding `!important` - inline styles usage

**Review by levadadenys — COMMENTED** [review]
Added a commit from me, which probably prevents me from approving PR since I'm a coauthor now 😄 

Left couple comments with context, I feel like this is good solution for the current situation.


a) Feel free to revert my commit
b) When/if we merge this PR - doublecheck eyes test to make sure nothing has changed visually (since current styles are approved rebrand styles)

**Comment by fisher-alice** [comment]
> * added !important back for #classroom-sections, #uitest-personal-projects th
> * updated QuickActionsCell.jsx so that we don't need !important for #classroom-sections, #uitest-personal-projects td
> 
> Reason why I added !important again for `#classroom-sections, #uitest-personal-projects th` is that when I open branch locally, sort buttons/icons looked dark on my machine (caused by some inline styles from `reactabular-table` styles I wasn't able to remove)

Interesting to know where inline styles are coming from - thanks for checking!

> @fisher-alice answering your question about completely removing icon styles from `phase1-design-system.scss` - I think it's better to keep styles for update there so that it'll be easier to maintain and make sure everything is up to date. Also, keeping in mind believe that we'll eventually update most of the screens with design system components/elements - I feel like it's more long term time-efficient not to rework old tables too much, but to create a new tables and use them sooner
> 
> Initial reason of adding `!important` - inline styles usage

This makes sense - thanks so much for your guidance!

**Comment by fisher-alice** [comment]
> Added a commit from me, which probably prevents me from approving PR since I'm a coauthor now 😄
> 
> Left couple comments with context, I feel like this is good solution for the current situation.
> 
> a) Feel free to revert my commit b) When/if we merge this PR - doublecheck eyes test to make sure nothing has changed visually (since current styles are approved rebrand styles)

This looks great! @bencodeorg - I've re-requested review since there's been an update to PR since you approved.

**Review by bencodeorg — APPROVED** [review]

**Comment by levadadenys** [comment]
> Interesting to know where inline styles are coming from - thanks for checking!

I'm 95% sure they're coming from `reactabular-table` lib (we're using it for tables right now) inner functionality for Table.Head/Header for sortable headerCell

**Pull request merged**
