### PR TITLE
New PD Certificate Image

### PR DESCRIPTION
**Pull request by islemaster**
[PLC-352](https://codedotorg.atlassian.net/browse/PLC-352): Follow-up to https://github.com/code-dot-org/code-dot-org/pull/28762 making a couple of improvements to the base certificate image.

- Change “PD” to “professional development” on the certificate.
- Remove underlines from the certificate.

Thank you @markabarrett for the changes to the base image!

| Before | After |
| --- | --- |
| cert_before | cert_after |

### Technical details

Mark provided an updated source PDF, from which I generated a PNG with [GIMP](https://www.gimp.org/) matching the dimensions of the original image.  I ran that through [`pngquant`](https://pngquant.org/) with default settings, and ended up with a _slightly_ smaller file than the original.

I think there's a slight color difference between the two versions, and I also think the new one is sharper (you can see the background pattern is much clearer using a "swipe" view).

### CODE REVIEW

**Review by clareconstantine — APPROVED** [review]
the new one definitely looks better!

**Comment by islemaster** [comment]
Visual review completed by Megan H. ([Slack thread](https://codedotorg.slack.com/archives/C0T10H26N/p1562187331459700))

**Comment by breville** [comment]
Looks great.  I did wonder if the date text itself should be a smidge lower to associate it closer with the "Date" caption.

**Comment by islemaster** [comment]
I thought about that too! But figured I'd hold off and see if anyone said anything.  Let me adjust it a bit.

**Review by breville — APPROVED** [review]

**Comment by islemaster** [comment]
Lowered the date 16 pixels:

cert_after_datelowered

**Comment by islemaster** [comment]
Updated vertical position of date again with @breville's help, squashed and pushed to branch.  I've updated the before/after in the PR description with the latest changes.

**Pull request merged**
