### PR TITLE
Rtl teacher homepage

### PR DESCRIPTION
**Pull request by Erin007**
This work switches layout for users viewing the teacher homepage in a language that reads right-to-left. 

RTL announcement
rtl announcement

RTL sections
rtl sections

RTL courses 
rtl recent courses

RTL resources 
rtl resources

RTL setup message
rtl setup sections

### CODE REVIEW

**Comment by Erin007** [comment]
KNOWN ISSUES: 

Update Stories to pass in isRtl as a prop. (Held off on this until I get confirmation that I'm taking the right path on passing isRtl as a prop for conditional styling.)

<s>Fix merge conflicts, make updates based on Brent's work with the SectionsTable file.</s>

Other components that still need RTL: 
- Header
- HeaderBanner (can we get an alternate image from Mark with the picture on the left?) 
- <s>SetUpMessages</s> 
- Notifications
- AnnouncementsCarousel

**Comment by Erin007** [comment]
cc: @tanyaparker

**Comment by Bjvanminnen** [comment]
Have you looked to see how the sections table on the teacher-homepage looks with this in RTL? Presumably I'd still need to do some work to get it to also look okay.

**Comment by Erin007** [comment]
@Bjvanminnen I have not pulled in your changes yet. The screenshot in this PR of the sections table on the teacher homepage is with my change prior to you making yours and including the export.

**Comment by Bjvanminnen** [comment]
Sorry, by teacher homepage, I meant teacher dashboard (i.e. "my" version vs. "yours"). I'd be curious to know how it looks after you've merged my changes. @poorvasingal fyi, not sure how much we care about RTL in teacher-dashboard, but might be something we need to spend a little time on.

**Comment by poorvasingal** [comment]
@tanyaparker says we already don't support RTL in sections page, so this is something we can do later. I wouldn't blocks shipping on it.

**Comment by tanyaparker** [comment]
The current teacher dashboard/sections pages do not support RTL, so as long as it's readable I'm okay with keeping the existing behavior/keep it LTR. I would like to fix it to RTL after we move it from pegasus to dashboard.

The teacher homepage HAD to be fixed because it wasn't readable at all. Plus, we might as well fix it all the way since it already was moved to dashboard.

**Comment by breville** [comment]
Impressive work.  My first impression is that RTL takes a lot of customized per-component styling, and it's pretty intensive work to build (not to mention maintain).  I wonder if there's an opportunity to factor out RTL support to some extent, so that there's less custom work required.  Are there some basic building blocks or patterns or systems (e.g. underlying responsive grid system) that can help us simplify this work?

**Comment by Erin007** [comment]
@breville Your point about maintainability and customization is well taken.  I think there is a way - though I haven't figured out how to implement yet - of having Redux manage isRtl. Then we wouldn't have to pass isRtl individually to all of the children, we could just set it in the store in the TeacherHomepage and all of the children (and grandchildren etc) would have access. (_I think?_) Secondly, there are a couple of little patterns we could think about extracting. For example, sometimes the only change that really needs to be made is providing the same amount of right margin/padding in RTL as there is left in LTR , or vice versa. I wonder what would happen if there was something that toggled left/right that could flip margin, padding and arrow directions for the styling?

**Comment by breville** [comment]
From some reading, it seems a lot of older CSS solutions indeed take care of flipping left and right for floats and padding/margin/etc. This module might be useful? https://www.npmjs.com/package/react-inline-styler-processor-rtl

Would love @Bjvanminnen's thoughts here too.

**Comment by Bjvanminnen** [comment]
Using redux will make it so that instead of having to pass around `isRtl` everywhere, you can just connect to a store and get it directly from there. It's possible that this set of React components is getting near the point of complexity where redux could have value (though that might depend  a little bit too on whether we plan to continue adding stuff).

I haven't done any research into whether there are good general purpose solutions to this sort of problem. I have to imagine some people have done thinking about this, though I'm not sure it's super common to support RTL languages.

**Pull request merged**
