### PR TITLE
Establishes routing, controller, and view for the Diversity Survey dashboard.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @Hamms (feel welcome to review, it'd be nice to get this into today's DTP)

**Comment by ashercodeorg** [comment]
Note that the test failure seems spurious.

ERROR["test_create_async_with_queueing_disabled", ActivityTest, 2016-03-03 09:15:43 +0000]
 test_create_async_with_queueing_disabled#ActivityTest (1456996543.09s)
RuntimeError:         RuntimeError: FakeSQS didn't start in time
            test/models/activity_test.rb:25:in `setup'

**Comment by breville** [comment]
lgtm.  it'd be neat to have a way to test this using mock data.

**Comment by ashercodeorg** [comment]
Going to merge as is, though I don't disagree that better test coverage would be good. On the other hand, I'm not sure simple test cases would catch anything that wasn't caught running it on prod-daemon.

**Pull request merged**
