### PR TITLE
Create separate gemfile for dms_tasks script.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This is attempting to resolve an issue where `production-daemon` cannot find the `pg` gem (despite it being manually installed on the node) as a result of the bundler context.

```
ubuntu@production-daemon:~/production/bin/cron$ ./dms_tasks 
/home/ubuntu/production/lib/cdo/redshift.rb:4:in `require': cannot load such file -- pg (LoadError)
    from /home/ubuntu/production/lib/cdo/redshift.rb:4:in `<top (required)>'
    from ./dms_tasks:11:in `require'
    from ./dms_tasks:11:in `<main>'
ubuntu@production-daemon:~/production/bin/cron$ gem list pg

*** LOCAL GEMS ***

pg (0.20.0)
```

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Ah, I was under false impressions. Your suggestion looks useful, let me try that.

**Comment by ashercodeorg** [comment]
PTAL.

**Comment by ashercodeorg** [comment]
The CircleCI failures seem to be a known issue, certainly unrelated to this change.

**Comment by ashercodeorg** [comment]
Actually, on further thought @wjordan, I'm not convinced this change is correct. Though I've wrapped the call to `RedshiftClient`, I should be wrapping the `require 'cdo/redshift'` command. Right?

**Comment by wjordan** [comment]
(as discussed offline) i do think you might be right about needing to wrap the require call, but i think you'll need to test-run the code locally to be sure.

**Pull request merged**
