### PR TITLE
CSF ScriptLevel tags: "target" and "challenge" levels

### PR DESCRIPTION
**Pull request by joshlory**
Request from @kiki-lee, @ryansloan & @sfilman.

Levels marked as "challenge" are the peak challenge puzzle in courses A-F.  They are usually followed by efficacy-repairing puzzles.  Levels marked as "target" represent the minimum bar where we expect most students to have gotten by the end of class.

Neither tags has publicly-visible effects yet — they are for internal tagging.  Sample usage:

```
stage 'Stage1'
  level 'Level 1'
  level 'Level 2'
  level 'Level 3', challenge: true
  level 'Level 4', target: true
  level 'level 5'
```

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
What sort of publicly-visible effects do we expect these to have in the future?

**Comment by joshlory** [comment]
For "challenge" puzzles we may encourage students to skip them after a certain number of tries / amount of time.  I think "target" will only be used for analytics.

**Comment by Bjvanminnen** [comment]
Feels a little weird to me to store this on the model if it's used only for analytics. Not sure I can justify why though.

We'd done another large tagging effort for levels before right (perhaps tagging them for difficulty?) Did we also store the metadata on the ScriptLevel model in that case?

Will we want more tags in the future? If so, it might be better to allow LBs to specify an arbitrary set of tags, something like `level 'Level 1', tags: 'target'.

**Comment by joshlory** [comment]
Only using this for analytics, no user-visible changes: Agree, but the practical reason for adding this to Level Builder is that the users who are doing the tagging will be working in Level Builder.

CSF Concept Difficulty tagging: This was done in a separate model and associated with Level instead of ScriptLevel.  The main difference is that there are 10+ concept difficulty tags that we want to query efficiently and we didn't want to add all those columns to every Level row.

More tags in the future: It's possible, but we want to restrict the tags to a reasonable pre-defined set.  It's unlikely for one level to be tagged both `target` and `challenge`.

**Comment by joshlory** [comment]
PTAL.

**Pull request merged**
