### PR TITLE
sign up link goes directly to student sign up instead of Code Studio …

### PR DESCRIPTION
**Pull request by tanyaparker**
…homepage

Just wanted to get this high impact and super easy change out this sprint, since the rest of the spec probably won't be done until next sprint. This removes the confusing sign up buttons from Code Studio homepage. Sign up link (from sign in page) now always leads directly to student sign up by default, and teachers can get to teacher sign up from student sign up page. Eventually it will just be one sign up page.

### CODE REVIEW

**Comment by breville** [comment]
lgtm.  would be interesting to track teacher sign up rate before/after this change to make sure we don't plummet anything?

**Comment by tanyaparker** [comment]
@ashercodeorg Would # of teacher and # student sign-ups per week be available in the Tableau data?

**Comment by ashercodeorg** [comment]
Eventually, user information (including sign-ups per day or per week) should be available in Tableau. For now, the `users` table is low priority (since there are lots of headaches associated with it (*)), so it may be a week or two before it gets integrated into Tableau.

That said, without running an AvB experiment, I'm not sure it will be easy to tell whether or not this change had a (positive or negative) impact, as there is some seasonal variability in sign-ups.

In the interim, I'm happy to track and share new user accounts by day.

**Comment by ashercodeorg** [comment]
For now, I've dumped the data into the spreadsheet here: https://docs.google.com/spreadsheets/d/1QJKzUWHALM53FcOK14t-XzG0jDqOXhSvX7QtyLgCHXI

**Comment by tanyaparker** [comment]
Thanks, @ashercodeorg, the spreadsheet is all I need if it's easier instead of Tableau. I'd like to fetch stats probably 2 weeks from now just to make sure it didn't go down to basically 0. lol Otherwise, probably another fetch a few weeks after the rest of the sign in changes. I'll ping ya when I need an update. :)

**Pull request merged**
