### PR TITLE
Fix (some) violations of rubocop Style/MutableConstant.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Note that some of these fixes involve changing `CONSTANTS` to `non_constants`, as a result of the code mutating their value.

### CODE REVIEW

**Comment by joshlory** [comment]
Should we be excluding `bin/mail` from Rubocop?  What is the long-term deprecation plan for these (presumably unused) files?

**Comment by ashercodeorg** [comment]
IMO, we should consider excluding the files associated with old emails from Rubocop, but enforcing Rubocop on the files associated with new emails. As for long-term deprecation plan, I don't think there is one, I think the thought is they serve as a record of how email lists were compiled and sent. That said, I'd be happy to blow it away. But if we do...why do we continue to check in new email files?

Very good question...

**Comment by joshlory** [comment]
I don't know the answer, but 100% agree that you raise a good question 😄.

**Comment by ashercodeorg** [comment]
Tagging @aoby for his opinion on `bin/mail/20xx-yy-zz-...`, our maintenance of old emails, and our checking in new emails.

**Comment by ashercodeorg** [comment]
If we do decide not to lint old `bin/mail` scripts, I don't see why this PR is harmful (given that the work has already been done), so I'm going to merge it.

**Comment by aoby** [comment]
Now that we actually have contacts imported into Pardot, and are supposedly starting to use it for marketing emails this week, we may not even need to keep these old email scripts around much longer and could consider deprecating / deleting them. Like Asher said, they are mainly there as a guide for creating new ones.

As far as linting retroactively, as long as we're keeping them we might as well at least for those rules like this with straightforward fixes.

**Pull request merged**
