### PR TITLE
Line breaks are removed from student answers in the Assessments tab

### PR DESCRIPTION
**Pull request by brickware**
Fixing https://codedotorg.atlassian.net/browse/LP-342 "Line breaks are removed from student answers in the Assessments tab"

Found that using the style white-space: pre-wrap solves the problem.  (found from https://stackoverflow.com/questions/2703601/how-to-line-break-from-css-without-using-br). Just pre or pre-line didn't quite work right. 

Also added a "code" test to show that this actually worked. 

Screen Shot 2019-06-25 at 4 05 21 PM

### CODE REVIEW

**Review by islemaster — APPROVED** [review]
Awesome quick fix @brickware! Congratulations on squashing your first bug in our repository!

smash_it_with_a_hammer

The drone run for this PR was [cancelled for some reason](https://drone.cdn-code.org/code-dot-org/code-dot-org/2891).  I've [started another one](https://drone.cdn-code.org/code-dot-org/code-dot-org/2899).  Everything else looks great, I'll approve and feel free to click "merge" when the run passes!

**Comment by islemaster** [comment]
I see one test failure:

```
SUMMARY:
 ✔ 4327 tests completed
 ℹ 19 tests skipped
 ✖ 1 test failed

 FAILED TESTS: 
 unit tests 
 FreeResponsesAssessmentsTable 
 ✖ renders the correct number of rows and headers 
 PhantomJS 2.1.1 (Linux 0.0.0) 
 expected {} to have a length of 5 but got 6 
```

That'll be this assertion, which was brittle to your change of the fixture in assessmentsTestHelpers.js:

https://github.com/code-dot-org/code-dot-org/blob/7ebd607755cf762f3c9258b9b87b9eb9c2d5691b/apps/test/unit/templates/sectionAssessments/FreeResponsesAssessmentsTableTest.js#L25

A little action-at-a-distance issue. :grimacing: I'll get it cleaned up.

**Comment by maddiedierker** [comment]
congrats on merging your first PR at code.org!

first PR

**Comment by Erin007** [comment]
yay! We're excited to have you here and that you've crushed your first Code.org bug! 
snoopy-dance

**Comment by hanwalden** [comment]
Congratulations!!

**Comment by fontie715** [comment]
Yay; welcome to the team!!

**Pull request merged**
