### PR TITLE
add empty-controller views to wildcard routes

### PR DESCRIPTION
**Pull request by wjordan**
Fixes issue introduced in #9973. Since `:action` segments in controller routes are deprecated in Rails 5 for security reasons, I [replaced](https://github.com/code-dot-org/code-dot-org/pull/9973#discussion_r75701463) the `/api` and `/dashboardapi` wildcard routes with explicit routing definitions based on the public instance methods in the ApiController class. However, we had some additional implicit routes that had no controller method but only a view template present, which were no longer defined.

This PR restores these missing routes by adding all template names to the list of explicitly-defined routes. I've also included an integration test to verify the missing routes are created properly.

### CODE REVIEW

**Comment by breville** [comment]
lgtm but @tanyaparker should also take a look, especially since she didn't think there was an issue with teacher_announcement but it feels like there should have been.  thanks!

**Comment by tanyaparker** [comment]
I'm unclear how teacher_announcement is different and still worked?

**Comment by wjordan** [comment]
@tanyaparker I see a 404 at https://studio.code.org/api/teacher_announcement without this PR and a 200 with this PR (locally), which suggests it's not currently working without the fix in this PR. Though I don't know anything about what the expected behavior is, so let me know if I should be looking at something different.

**Comment by tanyaparker** [comment]
image

Interesting! It still shows up on the teacher dashboard.

**Comment by wjordan** [comment]
Looking at the code, as far as I can tell the "Teacher Announcements" template view is rendered from other routes in both [Pegasus](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/teacher-dashboard/landing.haml#L7) and [Dashboard](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/views/home/index.html.haml#L37-L42), rather than via an Ajax request, so the `https://studio.code.org/api/teacher_announcement` route is not currently used anywhere on our site.

**Comment by tanyaparker** [comment]
OOH. Duh. That's right. I have a copy of the view instead of using an Ajax request. Sorry, thanks for clarifying. LGTM :)

**Comment by tanyaparker** [comment]
@breville what do you think would be better practice? I feel like I should also be using Ajax to load the teacher announcement on the teacher dashboard. This would remove the double view and also the double strings (which translators only see once, but still a little overkill). Although it will load a little slow?

**Comment by breville** [comment]
If it's already working, then not a top priority to change, but given that we frequently have to dupe our teacher announcement strings, then this seems like a good improvement.  Slightly slower load seems worth it in this case.

**Comment by tanyaparker** [comment]
Sounds good!

**Pull request merged**
