### PR TITLE
make stage header text a link to script

### PR DESCRIPTION
**Pull request by Hamms**

### CODE REVIEW

**Comment by joshlory** [comment]
Is https://github.com/code-dot-org/code-dot-org/blob/1341eda9cd839bfa9ef095ac7930db3b954519b7/code-studio/src/js/header.js#L44 now dead code?

**Comment by Hamms** [comment]
Hmm. It is perhaps redundant. Do you know why we were populating the header clientside in the first place?

**Comment by joshlory** [comment]
Will and I were working with a volunteer to make it possible to run HoC as a single-page app (and push `appOptions` config files out to S3).  When Phil joined we ended up going the route of caching each tutorial page on CloudFront.

**Comment by Hamms** [comment]
Ah, nifty! I'll remove it, then.

**Comment by joshlory** [comment]
LGTM

**Pull request merged**
