### PR TITLE
Disable REST requests to external services on milestone posts from high scale cached pages

### PR DESCRIPTION
**Pull request by philbogle**
We currently hit REST web services to try to verify that a shared level contains no profanity or street addresses.  We don't want to do this however on our very high scale cached level pages because we might take down those services or their latency might spike hurting our serving, so disable those posts for those pages.  Post November 9th we will probably revisit our approach here but we want to do something simple/viable for now.

### CODE REVIEW

**Comment by laurelfan** [comment]
Do you know if this code is even hit in hoc2015? This line:

```
     return nil unless program.match /(#{USER_ENTERED_TEXT_INDICATORS.join('|')})/
```

and the `USER_ENTERED_TEXT_INDICATORS` regexes were designed for blockly levels which are stored in xml, I don't think it would even work for droplet (meaning it returns without doing any of the regexp matching or external service calling).

**Comment by philbogle** [comment]
I didn't realize this wouldn't be hit in HOC 2015!  In that case we don't
need this PR.

**Comment by laurelfan** [comment]
It would be nice to solve this in a less accidental way though, in case someone decides to "fix" this

**Comment by laurelfan** [comment]
it might be worth verifying that this is not hit in the minecraft tutorial and in the star wars blockly mode (I think it should not be because there is no user entered text in either)

**Comment by philbogle** [comment]
Since we did okay without this change in HOC 2015 I am retiring it.

**Pull request closed without merging**
