### PR TITLE
Remove deprecated Full Load + Change Data Capture Replication Tasks

### PR DESCRIPTION
**Pull request by sureshc**
# Description

We are proposing a [new data export process](https://docs.google.com/document/d/1WrpOzYGMTUycEfYCk81NVDmvWoFPgimAtYm4QgUPoK0#bookmark=id.r2bm2l1z56g0) that carries out Full Load exports of Aurora MySQL tables once a day.  This is the first small change towards that implementation.  It deletes the Full Load + Change Data Capture Database Migration Service (DMS) Replication Tasks because they are no longer being used.  It also adds an `environment` label to the Tasks to ensure that these Tasks can be discovered programmatically by future components that Start, Monitor, and Validate Successful Completion of those tasks.

### Testing

```
$ bundle exec rake stack:data:validate RAILS_ENV=production

Listing changes to existing stack `DATA-production`:
Remove DMSCron [AWS::DMS::ReplicationTask]
Modify DMSCronFullLoad [AWS::DMS::ReplicationTask] Properties, Tags Replacement: Conditional (ReplicationTaskIdentifier, )
Remove DMSCronLevelSourcesPii [AWS::DMS::ReplicationTask]
Modify DMSCronLevelSourcesPiiFullLoad [AWS::DMS::ReplicationTask] Properties, Tags Replacement: Conditional (ReplicationTaskIdentifier, )
Remove DMSCronPii [AWS::DMS::ReplicationTask]
Modify DMSCronPiiFullLoad [AWS::DMS::ReplicationTask] Properties, Tags Replacement: Conditional (ReplicationTaskIdentifier, )
Remove DMSCronUserHierarchy [AWS::DMS::ReplicationTask]
Modify DMSCronUserHierarchyFullLoad [AWS::DMS::ReplicationTask] Properties, Tags Replacement: Conditional (ReplicationTaskIdentifier, )
Remove DMSCronUserHierarchyPii [AWS::DMS::ReplicationTask]
Modify DMSCronUserHierarchyPiiFullLoad [AWS::DMS::ReplicationTask] Properties, Tags Replacement: Conditional (ReplicationTaskIdentifier, )
Remove DMSCronUserLevels [AWS::DMS::ReplicationTask]
Modify DMSCronUserLevelsFullLoad [AWS::DMS::ReplicationTask] Properties, Tags Replacement: Conditional (ReplicationTaskIdentifier, )
```

## Links
https://codedotorg.atlassian.net/browse/INF-242

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bencodeorg** [comment]
This wouldn't get run in multiple environments, right? Just adding environment variable for some other purpose?

**Comment by sureshc** [comment]
> This wouldn't get run in multiple environments, right? Just adding environment variable for some other purpose?

The environment tag would enable the daily export job to programmatically identify the production data export Replication Tasks and to Start only those Tasks.

**Review by wjordan — APPROVED** [review]
Looks good to me. I don't fully like the `FullLoad` staying on the newly-created replication task names after the old ones are gone, but if it would be an extra pain to move the new resources to the original names it's fine to leave them as-is.

**Comment by sureshc** [comment]
> Looks good to me. I don't fully like the `FullLoad` staying on the newly-created replication task names after the old ones are gone, but if it would be an extra pain to move the new resources to the original names it's fine to leave them as-is.

I don't like that either.  I plan to drop the `FullLoad` suffix in an upcoming change.

**Comment by sureshc** [comment]
The initial proposed change failed to update the existing stack because the type of change (add tags to the ReplicationTasks) required replacement of the ReplicationTask resources.  But these resources used custom names, and CloudFormation cannot carry out a replace operation on an existing resource with a custom name:
```
2019-10-24 23:58:48 UTC- DATA-production [UPDATE_IN_PROGRESS]: User Initiated
.2019-10-24 23:58:57 UTC- DMSCronUserHierarchyPiiFullLoad [UPDATE_FAILED]: CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename cron-user-hierarchy-pii-full-load and update the stack again.
2019-10-24 23:58:57 UTC- DMSCronLevelSourcesPiiFullLoad [UPDATE_FAILED]: Resource update cancelled
2019-10-24 23:58:57 UTC- DMSCronUserHierarchyFullLoad [UPDATE_FAILED]: Resource update cancelled
2019-10-24 23:58:57 UTC- DMSCronPiiFullLoad [UPDATE_FAILED]: Resource update cancelled
2019-10-24 23:58:57 UTC- DMSCronUserLevelsFullLoad [UPDATE_FAILED]: Resource update cancelled
2019-10-24 23:58:57 UTC- DMSCronFullLoad [UPDATE_FAILED]: Resource update cancelled
2019-10-24 23:58:59 UTC- DATA-production [UPDATE_ROLLBACK_IN_PROGRESS]: The following resource(s) failed to update: [DMSCronPiiFullLoad, DMSCronLevelSourcesPiiFullLoad, DMSCronFullLoad, DMSCronUserHierarchyFullLoad, DMSCronUserHierarchyPiiFullLoad, DMSCronUserLevelsFullLoad].
.2019-10-24 23:59:06 UTC- DMSCronUserLevelsFullLoad [UPDATE_COMPLETE]
2019-10-24 23:59:06 UTC- DMSCronUserHierarchyPiiFullLoad [UPDATE_COMPLETE]
2019-10-24 23:59:06 UTC- DMSCronPiiFullLoad [UPDATE_COMPLETE]
2019-10-24 23:59:06 UTC- DMSCronUserHierarchyFullLoad [UPDATE_COMPLETE]
2019-10-24 23:59:06 UTC- DMSCronLevelSourcesPiiFullLoad [UPDATE_COMPLETE]
2019-10-24 23:59:07 UTC- DMSCronFullLoad [UPDATE_COMPLETE]
2019-10-24 23:59:07 UTC- DATA-production [UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS]
2019-10-24 23:59:08 UTC- DATA-production [UPDATE_ROLLBACK_COMPLETE]
```
 The [workaround](https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-custom-name/) is to rename the resource.

**Pull request merged**
