### PR TITLE
Ensure that force_db_access is enabled on staging-next

### PR DESCRIPTION
**Pull request by sureshc**
staging-next was not running all UI and Eyes tests because the force-db-access option was [checking the domain name](https://github.com/code-dot-org/code-dot-org/blob/675e8bc074a2fa16db72e14ca87818fbc01592c0/dashboard/test/ui/runner.rb#L218-L230) of the current system for the word `test`.

Modify the rake tasks executed during the continuous integration process to explicitly set the db access option.

### CODE REVIEW

**Comment by Hamms** [comment]
Haha, nice catch! I don't actually see the mentioned change in this PR, though, just a formatting fix? What am I missing?

**Comment by sureshc** [comment]
I added a comment to explain the new argument being passed to runner.rb.

**Comment by islemaster** [comment]
No - we already always enable this on Circle:

https://github.com/code-dot-org/code-dot-org/blob/675e8bc074a2fa16db72e14ca87818fbc01592c0/dashboard/test/ui/runner.rb#L221-L223

**Comment by sureshc** [comment]
Circle invokes runner.rb through a [different code path](https://github.com/code-dot-org/code-dot-org/blob/c904e31a05e9f264db4235c0f4171f91a43c5854/.circleci/config.yml#L194-L198).

**Pull request merged**
