### PR TITLE
Homepage: hoc2017 heroes for applab & celebs

### PR DESCRIPTION
**Pull request by breville**
The homepage now (temporarily) supports four hero variants:

```
DCDO.set("hoc_launch", {"homepage"=> nil})
DCDO.set("hoc_launch", {"homepage"=> "mc"})
DCDO.set("hoc_launch", {"homepage"=> "applab"})
DCDO.set("hoc_launch", {"homepage"=> "celebs"})
```

Non-en users get mc instead of applab/celebs.

screenshot 2017-11-18 11 33 56
screenshot 2017-11-18 11 34 40
screenshot 2017-11-18 11 35 13
screenshot 2017-11-20 17 53 33
screenshot 2017-11-20 17 53 49

### CODE REVIEW

**Comment by Erin007** [comment]
Everything looks good on mobile, too? Idea for the future: it'd be cool if you could hover over the celeb headshots for a name and why they're a big deal.

**Comment by breville** [comment]
After a lot of discussion, we're doing something extra-special for celebs, which is switching between different background images for desktop vs. mobile.  An additional image is drawn when mobile.  The two background images are preloaded but not faded, and are non-retina resolutions only.

@wjordan you might want to double-check this because of your work with these images in the past.

**Comment by breville** [comment]
More generally it will be great to remove all of this special-casing post-hoc.  If we face more customization of the homepage like this in the future, it would be interesting to reevaluate the use of ghseets and to work out a more modular system to be driven by DCDO or otherwise.

**Comment by tanyaparker** [comment]
SGTM

**Pull request merged**
