### PR TITLE
Refactor common auto-complete functions into helper

### PR DESCRIPTION
**Pull request by jopolsky**
Wanted to refactor this before I submit the district auto-complete functionality. These are the shared constants and functions.

### CODE REVIEW

**Comment by aoby** [comment]
Overall the functionality looks good, but I have some questions about the organization and design:

 1. Is there a reason that SchoolAutoComplete is a class instead of a controller concern that can be applied to the controllers where it's needed? Alternatively it could be a module that is included (mixed in) if you wanted to keep it in lib and use it in other contexts than just controllers. In any case, it doesn't appear to maintain any state which is typically why I'd want a class. I do see that you are removing the singleton mixin, which is a good step (again since there's no state), but I think this would be cleaner & easier to use as a module that can be mixed in.

 2. What is the purpose of the new `AutocompleteHelper` base class? Again I have the same questions as above. Does this need to be a class? It seems like we're creating extra hierarchy, and making this more cumbersome than it needs to be. Perhaps I just don't have enough context.

 3. nit: "Helper" has a specific meaning in Rails (on that note, this could be a controller helper instead of concern or plain old module), and beyond that I tend to dislike that suffix as not really really adding any meaning. How is `AutocompleteHelper` more descriptive than `Autocomplete`, and then I find it odd that the derived (presumably more specific) class loses the suffix.

**Comment by jopolsky** [comment]
Well, I think there is a mix of my newness to ruby and my deferring to the reviewers to indicate what the best practices are for the org.

The autocomplete_helper will be used with a new SchoolDistrictAutocomplete class, in the next PR, and generating the search string is a common function that can be extracted instead of duplicated.

**Comment by aoby** [comment]
Gotcha, so the base class will be used in both the `SchoolAutocomplete` and `SchoolDistrictAutocomplete`? 

Do we anticipate this to be applied to other contexts (like an interface), or just used as a base class in this hierarchy? If the latter then this is fine, but perhaps consider renaming it - either dropping the `Helper` entirely and just going with `Autocomplete`, renaming the derived classes to also include `Helper` or renaming the base class something like `AutocompleteBase`?

**Comment by jopolsky** [comment]
I think whatever direction it takes it should be simple to change as needed. As a first pass, I wanted to consolidate some common logic into a base class.

**Pull request merged**
