### PR TITLE
[Fit and Finish] Move forgot password question

### PR DESCRIPTION
**Pull request by epeach**
Updated with additional styling from Bryan.
Changes to style on the sign-in page. Redlines available in this ticket for those curious: https://codedotorg.atlassian.net/browse/PP-111

Before:
Screenshot from 2022-04-27 15-58-03

After:
Screenshot from 2022-04-28 15-32-46

### CODE REVIEW

**Review by kelbyhawn — APPROVED** [review]
Looks good! ✨

**Review by kelbyhawn — APPROVED** [review]
LGTM! 😎

**Review by kelbyhawn — APPROVED** [review]

**Comment by epeach** [comment]
Woo! Finally getting back to this and fixing the test that was broken.

To summarize, before:
Screenshot from 2022-07-20 16-30-01

and after:
Screenshot from 2022-07-20 16-29-45

**Comment by epeach** [comment]
cc: @dju90 - I know it's been awhile since we first took on this task, so I want to run it by you that we still want to make this change. Thanks!

**Comment by dju90** [comment]
> cc: @dju90 - I know it's been awhile since we first took on this task, so I want to run it by you that we still want to make this change. Thanks!

Yes please!

**Pull request merged**
