### PR TITLE
Minor tweaks to right side header spacing

### PR DESCRIPTION
**Pull request by bethanyaconnor**
[Jira task](https://codedotorg.atlassian.net/browse/FND-553) and [spec](https://docs.google.com/document/d/1XEdFjYf2fy9ggbu9FAzLJI4gld_kx6G1Rf6EenB1iHY/edit#heading=h.vp4jbo5edu1c)

Minor tweaks to the header. The general gist is that we're shifting the right header stuff slightly to the right and putting a bit more space between each element.

Header for production dashboard, dashboard with change, production pegasus, pegasus with change:
Screenshot 2019-07-11 at 10 19 25 AM

Dashboard and pegasus with the change. They're the same! 😄 
Screenshot 2019-07-11 at 10 30 01 AM

### CODE REVIEW

**Review by Erin007 — APPROVED** [review]

**Comment by breville** [comment]
I will just reiterate my concern that the left-margin and right-margin are no longer the same.

**Comment by dju90** [comment]
@breville Mark says: "when we were mocking it up it looked fine, even though there wasn't perfect symmetrical spacing on left and right"
How strongly do you feel about this?

**Comment by dju90** [comment]
Also, ran it past Marina and she's okay with it

**Comment by breville** [comment]
Not strongly enough to say no :)  But I do notice this on some sites and apps when it doesn't match.

**Review by breville — APPROVED** [review]

**Pull request merged**
