### PR TITLE
fix pause button spacing

### PR DESCRIPTION
**Pull request by JillianK**
Fix the spacing on the pause button in share view.

Now:
Screen Shot 2021-03-29 at 2 46 53 PM

Previously:
Screen Shot 2021-03-29 at 2 49 45 PM

## Links
- jira ticket: [STAR-1445](https://codedotorg.atlassian.net/browse/STAR-1445?atlOrigin=eyJpIjoiMjU5MjY4Y2Y2ZTViNDIwYjg1NmRkMjc2YThjOWRlMTYiLCJwIjoiaiJ9)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by epeach** [comment]
Does this impact the Soft Buttons in the development workspace? (The ones in the screenshot?)
Screenshot from 2021-03-29 15-03-15

**Comment by JillianK** [comment]
> Does this impact the Soft Buttons in the development workspace? (The ones in the screenshot?)
> Screenshot from 2021-03-29 15-03-15

Oops, it did. Just pushed a version that doesn't impact it. Here's what it looks like in the workspace:

Screen Shot 2021-03-29 at 3 41 14 PM

and in share view:
Screen Shot 2021-03-29 at 3 44 19 PM

**Comment by epeach** [comment]
Looking good! Are we tracking the rest of the work in that Jira Ticket (accessibility investigation)?

**Comment by JillianK** [comment]
> Looking good! Are we tracking the rest of the work in that Jira Ticket (accessibility investigation)?

I'm planning on doing that investigation later this week! I'll split it out into a separate ticket though so it doesnt get lost.

**Review by epeach — APPROVED** [review]

**Pull request merged**
