### PR TITLE
Upgrade to latest stable version of yarn: 0.23.2

### PR DESCRIPTION
**Pull request by pcardune**
There are a couple of bugs that have been fixed since yarn 0.16.1 which I've unfortunately run into with my js-interpreter update work. Specifically, the `bin` config in package.json is not handled properly for namespaced packages.

Everybody will need to update their version of yarn, as the format of `yarn.lock` changed ever so slightly. Depending on how they originally installed yarn, they will have to run one of the following commands:

**Ubuntu**
See the [yarn install docs](https://yarnpkg.com/lang/en/docs/install/) and run the following:

```bash
# Add the yarn repository per instructions in their docs and then run
sudo apt-get update
# Install the new specific version of yarn
sudo apt-get install yarn=0.23.2-1

# Tell the system not to auto-update yarn
sudo apt-mark hold yarn
```

**OS X**
```bash
brew unlink yarn
brew install yarn
```

**npm**
```bash
npm install -g yarn@0.23.2
```

**shell script**
```bash
curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
```

### CODE REVIEW

**Comment by islemaster** [comment]
> Fatal error: Task "sass:all" not found.

I'm kicking off a rebuild without cache.  I don't exactly understand the interactions between yarn and sass but I don't think this is entirely a fluke.

**Comment by islemaster** [comment]
Locally, got this after upgrading yarn and running `yarn && grunt clean build test`:
```
>> Error: ENOENT: no such file or directory, scandir '/home/brad/Projects/cdo/code-dot-org/apps/node_modules/grunt-sass/node_modules/node-sass/vendor'
```
Possible our build system depends on some specific node_modules install paths that have changed.

**Comment by islemaster** [comment]
Ubuntu install instructions may be too terse.  We may want to point people to the [yarn install docs](https://yarnpkg.com/lang/en/docs/install/) and add the following:

```bash
# Add the yarn repository per instructions in their docs and then run
sudo apt-get update

# Install the new specific version of yarn
sudo apt-get install yarn=0.23.2-1

# Tell the system not to auto-update yarn
sudo apt-mark hold yarn
```

**Comment by balderdash** [comment]
Looks like we hit https://github.com/sass/node-sass/issues/1804

I added the `npm rebuild node-sass` step to our build process as a workaround, and that passes on circle: https://circleci.com/gh/code-dot-org/code-dot-org/35361

**Comment by pcardune** [comment]
@balderdash awesome. want to submit a PR for that?

**Comment by pcardune** [comment]
Closing in favor of #14466

**Pull request closed without merging**
