### PR TITLE
Fixes Blockly Positioning of "arranged" blocks

### PR DESCRIPTION
**Pull request by Hamms**
Blocks that had "arrangments" that only specified X or Y coordinates
(not both) were writing both X and Y coordinates to the XML, causing
occasional `undefined` coordinates.

Additionally, blocks with X coordinates set in this way were being
positioned absolutely with Y=0. This was highly undersirable, as
Category blocks have an arrangement that positions them all this way.
The end result of all this mess was that category blocks were being
stacked up at the top of the toolbox editor, making them all but
useless.

| Before | After |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by Hamms** [comment]
fixes https://www.pivotaltracker.com/n/projects/1256652/stories/105774776

**Comment by Bjvanminnen** [comment]
Changes lgtm. Would it be easy to add a test for this, either in apps land or in blockly-core land?

**Comment by Hamms** [comment]
Possibly; the only thing that has an arrangement using only X (not both X and Y) is the category blocks, which is why it wasn't caught by any of the existing tests.

It would actually probably be best to add a UI test, but we'd have to give runner admin credentials and I don't think we want to do that.

**Comment by Bjvanminnen** [comment]
What if we create a level in mochaTest where startBlocks has one or more
blocks where X is set, but Y is not? We could then add a runBeforeClick
function that validates that the blocks are arranged as we expect.

**Comment by Hamms** [comment]
@Bjvanminnen would you give the new test a quick glance?

**Comment by Bjvanminnen** [comment]
looks good. did typo get caught because of test? :)

**Comment by Hamms** [comment]
Hah, yep. The system works!

**Pull request merged**
