### PR TITLE
Fix crontab to use login shell to pickup PATH

### PR DESCRIPTION
**Pull request by nicklathe**
We have an error in the automated i18n sync that isn't picking up the correct version of Node. This is due to crontab using the hardcoded PATH in the crontab definition rather than the PATH as set in the login shell. The correct PATH in the login shell contains the path to Node via nvm.

This PR adds the prefix `bash -lc` before the cron commands which will force crontab to use the login shell. This PR also removes the hardcoded PATH variable definition.

See [running-the-job-with-a-login-shell](https://www.baeldung.com/linux/load-env-variables-in-cron-job#running-the-job-with-a-login-shell) for using `bash -lc`.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by annaxuphoto — APPROVED** [review]
looks good to me! thanks for getting this change through :)

**Review by wilkie — APPROVED** [review]
TIL the `#i18n` i18n channel exists... somehow.

LGTM 👍 (tho, not sure what the process is to test them)

**Comment by nicklathe** [comment]
@wilkie yeah I'm not totally sure either, other than just YOLO 🤷‍♂️

**Comment by nicklathe** [comment]
Either way, this is would be easy to revert and is a non-risky change.

**Pull request merged**
