### PR TITLE
Delete empty gradeX.script files

### PR DESCRIPTION
**Pull request by Erin007**
While working on https://github.com/code-dot-org/code-dot-org/pull/28689, I found empty scripts so I'm deleting them. Looks like they were WIP placeholders before Course A-F were settled on for CSF.
I think they are safe to delete because no one would have made progress in them since they were never live.

### CODE REVIEW

**Comment by Erin007** [comment]
I found a [script to delete .script files from the db](https://github.com/code-dot-org/code-dot-org/blob/d344587164a1671898b827852c72e0e892918d79/dashboard/scripts/archive/delete_orphaned_scripts) but it looks old.  Do I still need to do that step?

**Comment by davidsbailey** [comment]
Yes, if you're gonna delete these, please remove them from the database.

Scripts like this seem fine to delete as long as they were never "visible in teacher dashboard" a.k.a. never had `hidden false` in the script file.

**Review by davidsbailey — APPROVED** [review]

**Comment by davidsbailey** [comment]
quick update: since these scripts were blanked out 2.5 years ago and don't have anything left in them that could contain progress anyway, it seems fine to remove them without checking the history for whether they ever had `hidden false`.

**Comment by joshlory** [comment]
Worth checking if there are any user levels that point to these Script IDs?

+1 for removing these from the production database as well! You could do a dry-run on staging or test.

**Pull request merged**
