### PR TITLE
[WIP] fix jmespath intermittent problem by upgrading gem?

### PR DESCRIPTION
**Pull request by laurelfan**
throwing this in a PR so I can make circle build it a few times

### CODE REVIEW

**Comment by wjordan** [comment]
I have a proposed [fix](https://github.com/code-dot-org/code-dot-org/pull/5442/files#diff-69c9c7251339be1439694fd13d262a78L59) for this test failure in #5442 (which is still pending review). It's bundled in with a lot of other stuff though so feel free to extract it into this branch

**Comment by laurelfan** [comment]
oh, interesting @wjordan! just extracting the to_a fixes it? If that works I can abandon this one, I don't know that this actually works.

FYI @ashercodeorg (since the JMESPath thing is also happening in the analyze_hoc_activity script)

**Comment by wjordan** [comment]
i think so, it seemed to work well enough to fix the issue in my local tests several months ago (if I recall)- however, since it's a random/intermittent problem it's hard to say for sure.

**Comment by laurelfan** [comment]
closing because @wjordan actually fixed

**Pull request closed without merging**
