### PR TITLE
Make category its own field, not part of aliases for searchable assets

### PR DESCRIPTION
**Pull request by ajpal**
The main reason for this change is that searching "cat" in the animation library returns unhelpful results because every animation has a "category_" alias.
Instead of having categories be part of the aliases metadata, this change separates it out.
Before:
image

After:
image

This change is a little complicated because the manifests are live in S3 now, so we need to make sure we make this code change in sync with a corresponding change to the manifest. My current plan (please weigh in if I'm missing something!):
1. Add categories field to the manifests in s3
2. merge this change
3. after DTP, delete the "category_" aliases from the manifests

## Links

- [jira](https://codedotorg.atlassian.net/browse/STAR-1147)

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bethanyaconnor** [comment]
Hmm I think this will conflict pretty badly with https://github.com/code-dot-org/code-dot-org/pull/35665 (which isn't quite done) because the localized manifests don't have the categories in them. I think this is okay: we can likely merge this PR, do another sync, then merge #35665.

This PR will also likely revert the translations for the categories. Now that we're building the ability to have localized manifests, this is definitely solvable -- we'll just add the ability to translate the categories alongside translating the aliases.

In the meantime, do you mind undeleting the category names in the i18n file? This will make sure deduplication of those strings works correctly. I'm happy to own deleting them when the categories are translated in the manifest. (This assumes that the category names aren't actually changing. If that's wrong, ignore this.)

**Comment by bethanyaconnor** [comment]
I've been thinking a bit more on this. This will be an improvement to the translator experience as well I think ("category animals" is a very strange thing to translate so getting rid of that is 👍 ). Most of my work for translating the manifests has been using `ManifestBuilder`. Do you have any ideas how these changes might be implemented in that script? Or if you're planning on doing something different to generate the manifest, what do you have in mind?

**Comment by ajpal** [comment]
Tackling the scripts is my next step. `ManifestBuilder` just processes the individual animation metadata files, right? So I think what I need to do first is modify `generateSingleFrameAnimationMetadata` to handle categories separately from aliases, then modify `ManifestBuilder` to handle the new categories field in the animation metadata.

**Comment by bethanyaconnor** [comment]
I believe so yes. I don't actually know how the animation metadata files are formatted so I'm not sure of the implementation but I would think it would be similar to what you're suggesting.

**Comment by ajpal** [comment]
See https://github.com/code-dot-org/code-dot-org/pull/35819

**Pull request closed without merging**
