### PR TITLE
Allow shared functions to be created for any pool

### PR DESCRIPTION
**Pull request by ajpal**

### CODE REVIEW

**Comment by joshlory** [comment]
No JS changes needed to load block definitions based on the current block pool?

**Review by joshlory — APPROVED** [review]
Ah I see, they're already included for all pools!

image

**Comment by ajpal** [comment]
> Ah I see, they're already included for all pools!

The blocks are loaded in shared_blockly_functions/edit.html.haml from the @block_pool value
Currently I have it set to `@block_pool = Block.for(@pools)` which loads all of the blocks regardless of pool. Should I change it to only load the blocks in the currently selected pool?

**Comment by joshlory** [comment]
Nah I think this is fine — loading a different block set whenever the dropdown changes sounds like a can of worms.

**Pull request merged**
