### PR TITLE
Replaces calls to the deprecated country_name_from_code with the non-deprecated version.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This is a continuation of #7457. Another PR will remove the table from the DB, the CSV, and the gsheet.

Tested locally by Tanya (not having solr, which the relevant pages depend on, set up locally with data myself). It'll be confirmed working on staging manually, too, after merging.

### CODE REVIEW

**Comment by tanyaparker** [comment]
@ashercodeorg since I have SOLR set up locally I just tested it. Update with `-require ‘country_codes’`

**Comment by ashercodeorg** [comment]
LG?

**Comment by tanyaparker** [comment]
Are you going to fix it in this PR or a future PR? The require path doesn't need /lib. If that's fixed, lgtm.

**Comment by ashercodeorg** [comment]
Ah, missed that (misunderstood). Fixing momentarily.

**Comment by tanyaparker** [comment]
Perf!

**Pull request merged**
