### PR TITLE
Fix App Lab text input change event

### PR DESCRIPTION
**Pull request by islemaster**
Fixes a regression in App Lab, where change event handlers on text input and text area elements did not receive any arguments.

**Minimum repro:**
1. Remix [this app](https://studio.code.org/projects/applab/ntOb_Q6sv_KyCxD21WuPuw) and run it.
2. Make a change to the textbox then click away to blur that field
3. Note that the logged statement in the console reads "event undefined on element undefined".  Expected: "event [object] on element text_input1"

I originally discovered this issue when revisiting my [Graphing Bucketed Stopwatch app](https://studio.code.org/projects/applab/-FV2Q0pmmv4jL9UDqmVx2g) and finding that it was broken.  To repro:
1. Run the app, and click the green "Start" button at the bottom to start the stopwatch
2. Change the name of any bucket and blur the text field (which triggers a save of the bucket name)
3. Notice that the stopwatch has stopped counting.  If you're editing the app, you see loads of JS error spew.

**Root cause**

It looks like this happens because the `ChangeEventHandler` does not pass event arguments through from its own handler to the callback.  It's used to try and standardize change event behavior across browsers for text input and text area fields, so I've written UI tests for those two cases.

This shouldn't be a security issue because in each case, the callback is `applabCommands.onEventFired` which sanitizes events.

Testing: Verified that minimum repro gets fixed on localhost, and ran UI tests in chromedriver against localhost.

### CODE REVIEW

**Comment by islemaster** [comment]
Assigning @davidsbailey because it looks like you originally wrote `ChangeEventHandler`.  You can review whenever you're back in the office, no rush. FYI @cpirich.

**Comment by davidsbailey** [comment]
Nice fix. I like the tests, but they seem to overlap substantially with "Scenario: Change event works in text input and text area" at https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/test/ui/features/applab/scenarios.feature#L46 . Perhaps it would make sense to put the similar tests in the same file (scenarios.feature or eventArguments.feature), and to augment existing tests where possible rather than adding new ones?

Also, beware this comment regarding testing text area key events and consider running the tests at least in IE11 locally before merging:

```
    # in a text area ... sending keystrokes (especially 'enter')
    # to a contentetiable div was too hard to test here due to browser differences.
```

**Comment by davidsbailey** [comment]
Of particular interest is this commit "Fix UI tests in non-Chrome browsers": https://github.com/code-dot-org/code-dot-org/commit/feb44c2457e4534a8e7af96703cb2ebad0d59e1e

**Comment by islemaster** [comment]
Nice catch.  I based this on my own [applab/sharedApps.feature textarea test](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/test/ui/features/applab/sharedApps.feature#L89), totally failing to notice the big fat comment I left myself there, and the `@no_ie` and `@no_safari` tags.  I'll rework this.

**Comment by islemaster** [comment]
Okay, changed to extend your test instead of adding new tests.  That feels better - it also found an edge case I originally missed.

Saucelabs now says these are passing on all browsers except Firefox.  I'll have to investigate more tomorrow.

**Comment by islemaster** [comment]
I found out that the `Event.srcElement` property (and by extention, our App Lab `Event.srcElementId` property) is nonstandard and [not supported in Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement).  I've changed the test to use `Event.targetId`, the standard property, instead.  I verified that applab/scenarios.feature passes on all browsers.

I'll tackle polyfilling/standardizing our event properties in another PR :grin:.

**Comment by davidsbailey** [comment]
It appears that the existing "Change event works in text input and text area" was already verifying that the element id and changed/added text were present on the event object, which should have prevented this regression from reaching production. What am I missing?

**Comment by islemaster** [comment]
The existing test wasn't doing anything with the event object.  Here's the code from the original test (formatted by me).  Note that the `event` argument is unused.

``` javascript
onEvent('text_input1', 'change', function(event) {
  console.log('text_input1: ' + getText('text_input1'));
});
onEvent('text_area1', 'change', function(event) {
  console.log('text_area1: ' + getText('text_area1'));
});
```

Here's the test after my change.  All I did was use `event` and depend on it having the `targetId` property.

``` javascript
onEvent('text_input1', 'change', function(event) {
  console.log(event.targetId + ': ' + getText('text_input1'));
});
onEvent('text_area1', 'change', function(event) {
  console.log(event.targetId + ': ' + getText('text_area1'));
});
```

**Comment by davidsbailey** [comment]
Ah, of course. Nice improvement! LGTM.

The element created in `applabCommands.textInput` looks similar enough to the one created in `textInput.jsx` that I think testing only the design mode text input will be sufficient to guard against this (and most) regressions, though in the spirit of DRY I do wonder if we should eventually be calling textInput.jsx --> create directly from `applabCommands.textInput`.

**Comment by islemaster** [comment]
We're not already doing that? :scream:

**Comment by davidsbailey** [comment]
I've opened https://www.pivotaltracker.com/story/show/113656117 to track the issue of duplicate implementations for creating elements.

**Pull request merged**
