### PR TITLE
Remove i18n/locales codeorg-markdown files from git

### PR DESCRIPTION
**Pull request by hacodeorg**
These markdown files are results of the sync-down step and were only manually checked into Git before. They could interfere with the i18n pipeline by preventing it from switching branches. 

We decide to remove them from Git ([Slack thread](https://codedotorg.slack.com/archives/CFTFD6BPV/p1619487590316600)). This is a step in a bigger theme of removing `/i18n/locales/<locale>` from Git since they are just temp directories for the i18n pipeline.

This PR is the opposite of https://github.com/code-dot-org/code-dot-org/pull/38767 (closed) and reverts the changes made by https://github.com/code-dot-org/code-dot-org/pull/36433 (8/2020), https://github.com/code-dot-org/code-dot-org/commit/981dd017bd751454630f6adec10dd2d59739a2f5 (10/2020), and https://github.com/code-dot-org/code-dot-org/commit/6ff2bdb5395aa6d1ada12c905de0ce706f1dd03f (11/2020).

How to remove codeorg-markdown files:
From the repo root, run `find i18n/locales -type d | egrep "codeorg-markdown$" | xargs git rm -r`

### CODE REVIEW

**Comment by Hamms** [comment]
We should consider adding a `.gitignore` entry for this and anything else we remove from that directory, to make it explicit that this incremental step is intentional until we can remove the whole thing

**Comment by hacodeorg** [comment]
> We should consider adding a `.gitignore` entry for this and anything else we remove from that directory, to make it explicit that this incremental step is intentional until we can remove the whole thing

Done :)

**Comment by daynew** [comment]
We should also remove the step from our sync process which tries to add and commit these files: https://github.com/code-dot-org/code-dot-org/blob/staging/bin/i18n/create-prs.rb#L53

**Review by daynew — APPROVED** [review]
Looks good. I also checked the create-prs.rb script and there are no direct references to codeorg-markdown, so there is nothing there to update.

**Pull request merged**
