### PR TITLE
hoc2015: update mc page with new image.

### PR DESCRIPTION
**Pull request by breville**

### CODE REVIEW

**Comment by breville** [comment]
screenshot 2015-11-14 10 31 01
screenshot 2015-11-14 10 31 10

**Comment by caleybrock** [comment]
Desktop looks fine although the text could be a little bit farther right.

Mobile looks a bit weird, it still feels like there should be something in that grey space to the right. Maybe ideally the minecraft logo could shift to the right over the grey area. I guess it's all dependent on their direction/approval though so if this is what they want, I guess it's fine?

**Comment by breville** [comment]
Updated with new image for desktop:

screenshot 2015-11-14 12 19 47
screenshot 2015-11-14 12 19 55

**Comment by caleybrock** [comment]
:+1: way better

**Pull request merged**
