### PR TITLE
[Music Lab] Add bubble choice fields to level edit page 

### PR DESCRIPTION
**Pull request by mikeharv**
Choice levels are a requirement for the new K5 module. Fortunately, we just need add the editor field to levels in order to enable this. Similar to:

- https://github.com/code-dot-org/code-dot-org/pull/59134

With this these fields, curriculum writers will now be able to add a title, description, and thumbnail image:
image

There are no changes here to how choice levels worked, but I've confirmed things work as expected. Music Lab level names can be added to the choice level configuration:

image

The choice level renders the text and images as expected:

image

## Links

https://docs.google.com/document/d/1NROqFS9gA4wklBNsxdrFQbou9HHI-fwPEetKGNm-Eho/edit#heading=h.w1c3gxdkagpg

## Testing story

Locally, I added the level shown above to a progression, surrounded on either side by a standard Music level. 
I tested that:
- completing the prior level directed you to the choice level
- selecting an option loads the expected Music sublevel
- completing the sublevel directs you back to the choice level as expected
- pressing Finish from the choice level directs you to the next level as expected
- progress bubbles fill as expected for the sublevels (when completed individually) and the main level (when at least one choice is completed)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by breville** [comment]
I'm not too familiar with these, but do they appear in the midst of a Music Lab set of levels?  If so, should do a Lab2 implementation to avoid a page reload?

**Comment by mikeharv** [comment]
> I'm not too familiar with these, but do they appear in the midst of a Music Lab set of levels? If so, should do a Lab2 implementation to avoid a page reload?

Yes, they would appear as you describe, and there is currently a page reload. This task is intended to unblock curriculum writing, so making a Lab2 implementation right now felt out of scope.

**Comment by breville** [comment]
> > I'm not too familiar with these, but do they appear in the midst of a Music Lab set of levels? If so, should do a Lab2 implementation to avoid a page reload?
> 
> Yes, they would appear as you describe, and there is currently a page reload. This task is intended to unblock curriculum writing, so making a Lab2 implementation right now felt out of scope.

I'd like to push back on this until we have a plan and commitment to implement this using Lab2.

**Comment by sanchitmalhotra126** [comment]
> > Yes, they would appear as you describe, and there is currently a page reload. This task is intended to unblock curriculum writing, so making a Lab2 implementation right now felt out of scope.
> 
> I'd like to push back on this until we have a plan and commitment to implement this using Lab2.

For some additional context, using lab2 labs as sublevels in a choice level was enabled for AI Chat [relatively recently](https://github.com/code-dot-org/code-dot-org/pull/58393). In AI Chat progressions, we do reload the page (which isn't ideal), I also agree that it would be good to develop a lab2 refresh of the bubble choice level as well. However also just noting that otherwise, we don't need any additional support to enable choice levels in Music Lab.

**Comment by mikeharv** [comment]
> > > Yes, they would appear as you describe, and there is currently a page reload. This task is intended to unblock curriculum writing, so making a Lab2 implementation right now felt out of scope.
> > 
> > 
> > I'd like to push back on this until we have a plan and commitment to implement this using Lab2.
> 
> For some additional context, using lab2 labs as sublevels in a choice level was enabled for AI Chat [relatively recently](https://github.com/code-dot-org/code-dot-org/pull/58393). In AI Chat progressions, we do reload the page (which isn't ideal), I also agree that it would be good to develop a lab2 refresh of the bubble choice level as well. However also just noting that otherwise, we don't need any additional support to enable choice levels in Music Lab.

In addition to AI Chat, we're also using choice levels for Python Lab. The Upper Lab team is planning to use them as-is for the pilot. It's understood that they aren’t perfect, but it’s better than not having them ready in time. 

I definitely agree with the long-term goal to get choice levels onto Lab2. In the meantime, I think we need to be realistic about what can get done in the short timeframe that we have. My understanding is that the new K5 curriculum can't be written without choice levels. 

@breville do you have ideas for what we could do to make choice levels work in Lab2 given the timeline we have? I'm most concerned about telling the curriculum team that they can't begin designing these lessons until we've come up with (and carried out) a plan here.

**Review by molly-moen — APPROVED** [review]
Given we are using these in other lab2 labs now (Python Lab and AI Chat), it makes sense to unblock curriculum by doing this, then figuring out a longer-term strategy for choice levels. We have been thinking about better ways of managing these anyway (ex. choice progressions).

**Comment by breville** [comment]
Okay, no objections, but would love to see a fresh Lab2 implementation relatively soon!

**Comment by mikeharv** [comment]
https://codedotorg.atlassian.net/browse/CT-728

**Pull request merged**
