### PR TITLE
Create table to store code commit comments

### PR DESCRIPTION
**Pull request by bethanyaconnor**
This comes from the [tech spec](https://docs.google.com/document/d/100y_rtquLE87dwB-S8gWyXrmiRcJGCjqEVGwOxiOBYU/edit#heading=h.uhsylvb5lyaa). I used the table name from the spec but there was a bit of discussion about it so let me know if there's a different name folks would prefer!

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by bencodeorg — APPROVED** [review]
I came to `project_versions` as a name for this as well before I noticed Suresh suggested the same thing in the tech spec :). I think probably worth renaming especially with the not obvious "metadatum" class name you get as the singular of "metadata"

**Comment by bencodeorg** [comment]
Sorry one other comment -- do you want `storage_app_id` to be unique?

**Comment by bethanyaconnor** [comment]
> do you want storage_app_id to be unique?

Oh right probably not -- we want storage_app_id/version_id to be unique and we want a non-unique index on storage_app_id. I'll fix -- good catch!

**Comment by bethanyaconnor** [comment]
> I came to project_versions as a name for this as well before I noticed Suresh suggested the same thing in the tech spec

Two votes for this is enough for me. I'll update

**Review by bakerfranke — APPROVED** [review]
LGTM. Good to know. Thanks.

**Pull request merged**
