### PR TITLE
Diagonal draw/jump blocks for K-1 Artist

### PR DESCRIPTION
**Pull request by balderdash**
image

Again, lengths are longer by a factor of sqrt(2), as are the segment lengths:

image

### CODE REVIEW

**Comment by balderdash** [comment]
I don't think that last circle failure was legitimate, rerunning...

**Comment by Hamms** [comment]
Just to confirm: we plan to do a second PR when we get the assets, yes?

**Comment by Hamms** [comment]
This looks fantastic! Very thorough. Do you know if we have specific plans to start using this? Is Kiki aware that this is incoming?

LGTM

**Comment by balderdash** [comment]
Actually Ryan's almost done with assets, so I'll just add them to this PR when he's done.

Aside from adding them to free play, I'm not sure what the specific plans are. I'll check with Ryan.

**Pull request merged**
