### PR TITLE
Fix studio goal rendering.

### PR DESCRIPTION
**Pull request by breville**
This fixes a studio goal rendering regression caused by my extensions to level.goaloverride.  Now we correctly handle all known flavours of goals.

### CODE REVIEW

**Comment by breville** [comment]
Tested with these levels:

s/playlab/stage/1/puzzle/6
s/infinity/stage/1/puzzle/5
s/hoc2015/stage/1/puzzle/4
/s/hoc2015/stage/1/puzzle/9

I had previously tested the one level that regressed, but made the mistake of not knowing what I was looking for and missing the fact that it had changed.

**Comment by breville** [comment]
fyi @caleybrock and @Bjvanminnen

**Comment by caleybrock** [comment]
thanks @breville !

**Comment by Bjvanminnen** [comment]
lgtm

**Pull request merged**
