### PR TITLE
Fixes violations of and reenables the rubocop Lint/IneffectiveAccessModifier check.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes generated manually.

```
Offenses:

pegasus/src/curriculum_router.rb:147:3: W: Lint/IneffectiveAccessModifier: private (on line 93) does not make singleton methods private. Use private_class_method or private inside a class << self block instead.
  def self.content_type_from_extname(extname)
  ^^^
pegasus/src/curriculum_router.rb:158:3: W: Lint/IneffectiveAccessModifier: private (on line 93) does not make singleton methods private. Use private_class_method or private inside a class << self block instead.
  def self.content_type_from_path(path)
  ^^^
shared/middleware/helpers/redis_table.rb:172:3: W: Lint/IneffectiveAccessModifier: private (on line 158) does not make singleton methods private. Use private_class_method or private inside a class << self block instead.
  def self.table_from_row_key(key)
  ^^^
shared/middleware/helpers/redis_table.rb:183:3: W: Lint/IneffectiveAccessModifier: private (on line 158) does not make singleton methods private. Use private_class_method or private inside a class << self block instead.
  def self.id_from_row_key(key)
  ^^^
shared/middleware/helpers/redis_table.rb:212:3: W: Lint/IneffectiveAccessModifier: private (on line 158) does not make singleton methods private. Use private_class_method or private inside a class << self block instead.
  def self.make_row(value)
  ^^^
shared/middleware/helpers/redis_table.rb:241:3: W: Lint/IneffectiveAccessModifier: private (on line 158) does not make singleton methods private. Use private_class_method or private inside a class << self block instead.
  def self.internal_key?(k)
```

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Note that the CircleCI failure is legitimate, exposing an issue with changing the visibility of the method.

**Comment by ashercodeorg** [comment]
CircleCI failures are unrelated.

**Comment by ashercodeorg** [comment]
@Bjvanminnen, PTAL.

**Comment by Bjvanminnen** [comment]
lgtm

**Comment by ashercodeorg** [comment]
CircleCI failures seem unrelated.

**Pull request merged**
