### PR TITLE
Update Pull Request template for Privacy & Security Impact

### PR DESCRIPTION
**Pull request by sureshc**
Update our Pull Request template to expand on how we assess each code change for privacy and security impacts.

### CODE REVIEW

**Review by Hamms — APPROVED** [review]
This looks good to me as a continuation of our existing pull request template work!

I will, however, note that I'm increasingly unconvinced of the value of the "reviewer checklist"; I know I personally haven't been finding any value in that in either my PRs or my reviews. I'd be interested to hear if anyone else has a different experience

**Comment by dju90** [comment]
lgtm too

**Comment by sureshc** [comment]
How would everyone feel about requesting a review from a product manager on pretty much any Pull Request to sign off on the Personal Data assessment?

**Comment by dju90** [comment]
I think it doesn't have to be every PR. In general, I (and I'm sure the other PMs) trust engineers to have a sense of whether their change is a "no" vs a "maybe" on these checklist items...and the latter is what I'd propose requesting a review from a PM for.

**Comment by tess323** [comment]
I agree with Bryan.

**Pull request merged**
