### PR TITLE
Datablock Storage: completely remove firebase

### LINKED ISSUE #56994: Remove `TODO: post-firebase-cleanup` items after full deploy
After merging https://github.com/code-dot-org/code-dot-org/pull/56279, we marked a lot of items to be removed when we're ready to remove Firebase.

### PR DESCRIPTION
**Pull request by snickell**
We previously added Datablock Storage as a dual-path alternative to Firebase in this epic PR: https://github.com/code-dot-org/code-dot-org/pull/56279

Now that we've fixed bugs and been running with Datablock Storage as the primary backend for a while, we're ready to finish the job and **remove Firebase entirely from the codebase**. That's this PR!

Fixes [#56994](https://github.com/code-dot-org/code-dot-org/issues/56994)

#### More Detailed Changes

This PR removes from the codebase:
- 'firebaseStorage.js`: the dual-path alternative to datablock storage, and removes all conditionals switching between this `storageBackend()` and datablock storage
- `TODO: post-firebase-cleanup` and `TODO: unfirebase`: places we marked in the codebase previously as requiring simplification and cleanup after we were ready to remove Firebase.
- `legacy/middleware/tables_api.rb` which is now empty after firebase is removed
- `firebase` npm
- `firebase` gem
- Virtually all references to the case-insensitive word `firebase`, including in comments, docs etc (makes it easier to verify we got them all)
- Drops a now outdated migration used for dev bootstrapping: 20240216071353_seed_datasets_from_firebase.rb
- Drops the `ProjectUseDatablockStorage` model from ActiveRecord, but does _not_ yet drop the millions-of-rows `project_use_datablock_storages` table (though it should be unused at this point), we'll do that in a followup issue: [#59822](https://github.com/code-dot-org/code-dot-org/issues/59822)
- Removes firebase seeding and rule uploading tasks in both `rake` and `grunt`
- Removes `wss://*.firebaseio.com` from `content-src` on various CSP http headers

#### TODO:
- [x] Minimize diff on .md files where VSCode insisted on reformatting the file on save.
- [x] Determine if we made `Chrome_star_labs_applab_eyes3_eyes` flakey, see: https://github.com/code-dot-org/code-dot-org/pull/59824#issuecomment-2232675855
- [x] Prior to merging this branch, merge #56993 which is already mixed in here
- [x] After merge, notify #developers to check their locals.yml and, if set, remove `firebase_name` and `firebase_secret` configs, or they'll get "Unknown property not in defaults: firebase_name" when running `bin/dashboard-server`. Most people will not have this set, because it usually comes from AWS secrets.
- [x] After merge, ping Stephen to let him know the `firebase-bolt` bits have been removed from Gruntfile.

Co-authored-by: Cassi Brenci <cnbrenci@users.noreply.github.com>

### CODE REVIEW

**Comment by snickell** [comment]
Commit [ea0e878](https://github.com/code-dot-org/code-dot-org/pull/59824/commits/ea0e878ba7746d6358b1475640fd4c138002245c) has almost all the `TODO: post-firebase-cleanup` items, except for 4 of them that I'm less 100% certain of. These will follow in individual commits.

**Comment by snickell** [comment]
Now all `TODO: post-firebase-cleanup` and `TODO: unfirebase` items have been removed, time to start searching for case-insensitive string `firebase` and removing all the stragglers like Gemfile, package.json etc etc.

**Comment by snickell** [comment]
Case-insensitive search for firebase in our repo = NO RESULTS 👁️🫦👁️:
image

Excluded files were:
1. `iam.yml.erb`: a cloudformation template granting contributors access to the firebase_secret in AWS secrets manager. Followup issue: #59831
2. `pegasus/sites.v3/code.org/i18n/public/educate`: translations of it.md, which is already updated to not reference firebase
3. `dashboard/config/levels/custom/javalab`: CSA U6 contains levels which have a giant dictionary of english terms, including the word `firebase`

**Comment by snickell** [comment]
I notice flakiness on this test, want to make sure this PR isn't causing it: `Chrome_star_labs_applab_eyes3_eyes_Data Browser` ([saucelabs](https://app.saucelabs.com/tests/437e73a69cce459fbc4cd3cb845bb130#57))

1) Eyes test succeed 5 out of 6 times, but it broke on one commit, which seems to be unrelated: [dbce232](https://github.com/code-dot-org/code-dot-org/pull/59824/commits/dbce23225dad494d95e2f5ffa510e484fb284b92)
2) The test relates to the Data Browser, which we did just switchover in UI tests over to running agains Datablock Storage.

**UPDATE**: its not this PR making it flakey, runs on other branches also recently errored-out in this spot (e.g. [this sauce run](https://app.saucelabs.com/tests/ff89031d51c641e6bd90f135c00545d0#157)). I now suspect yesterday's PR (merged yesterday, #59667) triggered flakiness by changing timings.

### Follow-up Issue:
Follow-up issue for the flakey test here: [#59834](https://github.com/code-dot-org/code-dot-org/issues/59834), including a PR with a speculative fix (adds a 1s wait).

**Comment by snickell** [comment]
We're green! I think this PR is ready for review and possibly merging.

**Review by cnbrenci — APPROVED** [review]
🥇 , don't wait for the tests, I'm 1000% confident.

**Pull request merged**
