### PR TITLE
Updates to use find_by_email_or_hashed_email.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by joshlory** [comment]
What about [this newly-merged usage](https://github.com/code-dot-org/code-dot-org/blob/0fc711e757ea47c2c4a3ce806e6601c4517231d8/dashboard/app/controllers/pd/workshop_enrollment_controller.rb#L35)?

Is there a way to undef the `find_by_email` method outside of `User` so that it isn't called accidentally?

**Comment by ashercodeorg** [comment]
Does overriding `find_by_email` within User as a protected method (passing the call to the rails method) do the trick?

Alternately, perhaps `remove_method`? http://apidock.com/ruby/v1_9_3_392/Module/remove_method

Alternately, as a larger PR, rename `find_by_email_or_hashed_email` to be `find_by_email`?

**Comment by ashercodeorg** [comment]
In terms of that newly merged usage, I have that in #8548 (separating current stuff from old stuff).

**Comment by joshlory** [comment]
I think `ActiveRecord` defines its accessors last, so I'd expect them to override any protected methods.  This might be worth a little investigation, but if it gets difficult feel free to open a Pivotal item and punt to a future PR.

**Comment by ashercodeorg** [comment]
Created 120142791 in Pivotal for tracking (https://www.pivotaltracker.com/projects/914728/stories/120142791).

**Comment by joshlory** [comment]
When investigating did it look like hiding these accessors will be difficult?

**Comment by joshlory** [comment]
LGTM

**Pull request merged**
