### PR TITLE
Implement a few minor style tweaks to the new signup page

### PR DESCRIPTION
**Pull request by Hamms**
# Description

Specifically:

1. Resize the oauth links to no longer take up the full width of the page
2. Add an asterisk to the "email" field so the student terms footer is clearly referenced by something
3. Make the asterisk and text of the footer colinear

Before | After
--- | ---
image | image

## Links

- [prereq for this jira item](https://codedotorg.atlassian.net/browse/FND-407)

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by Hamms** [comment]
Note the non-breaking space is mostly only necessary for languages that will change the length of the "email" label. See for example Spanish

### With nbsp
image

### Without
image

**Comment by dju90** [comment]
Looking at this again, I'm noticing that the "Already signed up? Sign in" text is spatially linked to the oauth buttons. Can we make the following change:
1. Move it below the orange signup button
2. Change the text from "Already signed up? Sign in" to "Already have an account?", all of which is an anchor tag/clickable
image

**Comment by dju90** [comment]
Small cosmetic nits (not absolutely necessary to fix now) that we'll want to address eventually:
- right edge oauth buttons should align with right edge of -- OR -- and text fields
- remove space between asterisk and footnote
- left side of footnote should align with left edge of [Sign up] button

**Comment by Hamms** [comment]
> Change the text from "Already signed up? Sign in" to "Already have an account?", all of which is an anchor tag/clickable

I'm not a fan of this design; as a rule, actions like clickable links should be indicated by clear statements of intent, not by vague questions. How about:

> Already have an account? [Sign in]()

**Comment by dju90** [comment]
Sounds good. Thumbs up on
> Already have an account? [Sign in]()

**Review by maddiedierker — APPROVED** [review]

**Pull request merged**
