### PR TITLE
Don't save projects when in readonlyWorkspace mode (e.g. teacher view)

### PR DESCRIPTION
**Pull request by joshlory**
[Finishes #103531916]

### CODE REVIEW

**Comment by joshlory** [comment]
Remixing level source shares uses `copy` and remixing projects uses `serverSideRemix`.  Calling `save` should only be done by the project owner.

Maybe a more complete fix would be to check `isOwner`?

**Comment by Bjvanminnen** [comment]
What would happen right now if a non-owner tried to save? Just get an error? I think it makes sense to exit early for readonlyWorkspace regardless, but it might make sense to also exit early if !isOwner

**Comment by joshlory** [comment]
Right now it ends up doing a remix, because it creates a new project where the current user is the owner.

**Comment by Bjvanminnen** [comment]
That behavior doesnt sound entirely unreasonable, but I'd say it's probably cleaner to just say that we exit if not owner if we don't actually expect non-owners to be going through this path.

**Pull request merged**
