### PR TITLE
restrict applab data browser pages to channel owner

### PR DESCRIPTION
**Pull request by davidsbailey**
This partially addresses https://www.pivotaltracker.com/n/projects/1256654/stories/95131488

### CODE REVIEW

**Comment by davidsbailey** [comment]
Hi @trevorb , I thought I'd throw this one your way since you've been looking at the data browser pages. Please don't hesitate to get in touch if you'd like more background info on channel ids and storage ids.

**Comment by trevorb** [comment]
The logic looks good. Since this is auth code, can you add tests? It'd also
probably be better if the auth logic was in one place.

On Tuesday, September 15, 2015, davidsbailey <notifications@github.com>
wrote:

> Hi @trevorb <https://github.com/trevorb> , I thought I'd throw this one
> your way since you've been looking at the data browser pages. Please don't
> hesitate to get in touch if you'd like more background info on channel ids
> and storage ids.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/code-dot-org/code-dot-org/pull/4003#issuecomment-140627563>
> .
>


-- 
Trevor
trevor@code.org

**Comment by davidsbailey** [comment]
Thanks @trevorb , I've extracted a helper method. Looking into tests.

**Comment by trevorb** [comment]
Awesome, those changes lgtm :)

**Comment by davidsbailey** [comment]
Thanks for the tip to look at http://www.sinatrarb.com/testing.html, @laurelfan ! Can you please review? It's worth noting that I'm getting some warnings which do not show up when I run the tests on the staging branch. Below is the complete test output:
```
Davids-MacBook-Pro-2:~/src/cdo/pegasus$ rake test
/Users/dsb/src/cdo/pegasus/test/test_section_api_helpers.rb:9: warning: already initialized constant DASHBOARD_DB
/Users/dsb/src/cdo/lib/cdo/db.rb:23: warning: previous definition of DASHBOARD_DB was here
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:116: warning: already initialized constant DashboardStudent::VALID_GENDERS
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:116: warning: previous definition of VALID_GENDERS was here
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:147: warning: already initialized constant DashboardStudent::PEPPER
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:147: warning: previous definition of PEPPER was here
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:148: warning: already initialized constant DashboardStudent::STRETCHES
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:148: warning: previous definition of STRETCHES was here
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:161: warning: already initialized constant DashboardSection::VALID_LOGIN_TYPES
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:161: warning: previous definition of VALID_LOGIN_TYPES was here
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:167: warning: already initialized constant DashboardSection::VALID_GRADES
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:167: warning: previous definition of VALID_GRADES was here
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:183: warning: already initialized constant DashboardSection::VALID_COURSES
/Users/dsb/src/cdo/pegasus/helpers/section_api_helpers.rb:183: warning: previous definition of VALID_COURSES was here
Loaded suite /Users/dsb/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/rake_test_loader
Started
D, [2015-09-16T15:42:59.515380 #48288] DEBUG -- : http://example.org/edit-csp-app/TP3c4-GKEI4pvQ5HayE-1w
W, [2015-09-16T15:42:59.715322 #48288]  WARN -- : 401 returned for code.org/edit-csp-app/TP3c4-GKEI4pvQ5HayE-1w
D, [2015-09-16T15:42:59.718055 #48288] DEBUG -- : http://example.org/edit-csp-table/TP3c4-GKEI4pvQ5HayE-1w/mytable
W, [2015-09-16T15:42:59.802143 #48288]  WARN -- : 401 returned for code.org/edit-csp-table/TP3c4-GKEI4pvQ5HayE-1w/mytable
D, [2015-09-16T15:42:59.804381 #48288] DEBUG -- : http://example.org/edit-csp-properties/TP3c4-GKEI4pvQ5HayE-1w
W, [2015-09-16T15:42:59.960434 #48288]  WARN -- : 401 returned for code.org/edit-csp-properties/TP3c4-GKEI4pvQ5HayE-1w
.

Finished in 0.48457 seconds.
---------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 3 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
---------------------------------------------------------------------------------------------------------------------------------------------------
2.06 tests/s, 6.19 assertions/s
Run options: --seed 31229

# Running:

.......................................

Finished in 0.170752s, 228.4014 runs/s, 732.0558 assertions/s.

39 runs, 125 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by laurelfan** [comment]
Tests look good to me.

Which warnings are you referring to? the constant definitions? Not a huge deal because it's not breaking anything, but I am guessing that something is being included twice.

**Comment by davidsbailey** [comment]
@laurelfan yes, they go away if I do not `require_relative '../router', but then my test breaks because it can't find `Documents`.

**Comment by davidsbailey** [comment]
I'm going to call this good enough for now, as at least now we have a test in pegasus which tests an actual request path.

**Pull request merged**
