### PR TITLE
Fix violations of and reenable rubocop Rails/Presence.

### PR DESCRIPTION
**Pull request by asherkach**

### CODE REVIEW

**Comment by asherkach** [comment]
Note that auto-correct failed to correctly fix `dashboard/test/test_helper.rb`. Filing a bug against rubocop for this.

**Comment by asherkach** [comment]
CC @erin (DOTD) for review.

**Comment by asherkach** [comment]
CC @Erin007 (DOTD) for review.

**Comment by asherkach** [comment]
Ah, the rubocop auto-correct issue is already fixed upstream [here](https://github.com/rubocop-hq/rubocop/commit/b67762d125e67b1f5223ea14d4b76b550818972a#diff-37ea56de5233fca2df2e97c3c14bcdc3).

**Comment by Erin007** [comment]
Happy to still take  look if needed, but @epeach is DOTD today.

**Comment by asherkach** [comment]
Ping @epeach (former DOTD) or @balderdash (current DOTD) for CircleCI run.

**Comment by balderdash** [comment]
Kicked off a circle run.

**Pull request merged**
