### PR TITLE
[Dance Party] Remove expiring songs before 11/9

### PR DESCRIPTION
**Pull request by ebeastlake**
Per @dju90, we have some Dance Party songs we could not renew and need to remove them from Dance Party by Nov 9. They are:
- Francesco Gabbani: Occidentali's Karma
- Katy Perry: Never Really Over
- KIDZ BOP Kids: If I Can't Have You
- Lil Nas X: Old Town Road

This PR removes those songs. The updated manifest has already been uploaded to S3. I documented my process for removing songs here: https://docs.google.com/document/d/1PkrqWtenjD4yz8i1yRwaA2koNFxTfNmCGaCILDF047U/edit?tab=t.0

## Links

Slack: https://codedotorg.slack.com/archives/C05DMS18MEX/p1730837473667409

## Testing story

I confirmed the songs disappear when you locally use the ?manifest=songManifest2024_v3.json URL param; see below. I also confirmed that they disappeared from the levelbuilder song selector. 

**Before (Project Level)**

Screenshot 2024-11-06 at 11 08 06 AM
Screenshot 2024-11-06 at 11 09 49 AM
Screenshot 2024-11-06 at 11 10 03 AM
Screenshot 2024-11-06 at 11 10 11 AM

**After (Project Level)**

Screenshot 2024-11-06 at 11 10 51 AM
Screenshot 2024-11-06 at 11 10 39 AM
Screenshot 2024-11-06 at 11 10 31 AM

**After (Levelbuilder)** 

Screenshot 2024-11-06 at 11 18 25 AM
Screenshot 2024-11-06 at 11 18 17 AM

**After (Banner about removed song)**

https://github.com/user-attachments/assets/df810e82-cc65-4c7d-9311-f3ecee7d46cc

## PR Checklist:

- [x] Tests provide adequate coverage
- [x] Privacy and Security impacts have been assessed
- [x] Code is well-commented
- [x] New features are translatable or updates will not break translations
- [x] Relevant documentation has been added or updated
- [x] User impact is well-understood and desirable
- [x] Pull Request is labeled appropriately
- [x] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bencodeorg** [comment]
Sorry if I'm missing this in the discussion, but were you able to confirm the "graceful fallback" for levels that use one of these songs as the default (looks like they haven't been updated in levelbuilder yet, or at least the first one in the spreadsheet you created hasn't).

**Comment by dju90** [comment]
Just got word that we might be able to keep "If I Can't Have You" by KIDZ BOP...hold please

**Comment by ebeastlake** [comment]
@bencodeorg If I go to one of the levels in the spreadsheet on levelbuilder and replace the manifest using the URL param, ex. https://levelbuilder-studio.code.org/levels/26749?manifest=songManifest2024_v3.json, I see that the level uses the first song in the available manifest and still runs as expected. 

Screenshot 2024-11-07 at 8 47 19 AM

This is the "'graceful fallback' for levels that use one of these songs as the default" testing you're referring to, yeah? If so, it looks good! Thanks for the reminder.

I plan to check with Katie before I merge this anyway (ideally), though, given the deadline, we don't _have_ to block this PR on updating the default songs.

**Review by bencodeorg — APPROVED** [review]
Nice! Thanks for documenting this process :)

**Comment by dju90** [comment]
All four songs are good to be removed, just confirmed. Thanks Emily!

**Pull request merged**
