### PR TITLE
Remove solution_level_source_id from levels.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Also see #14990 and #15410. Before merging this PR, the column data in the DB on both `levelbuilder` and `production` will be backed up.

UPDATE: Column data in DB backed up in the `dashboard_levelbuilder__levels__solution_level_source_id.tsv` and `dashboard_production__levels__solution_level_source_id.tsv` files in the `deprecated-data` bucket on `s3`.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
How do I go about removing the field from existing `level` files?

**Comment by aoby** [comment]
Wow, I didn't realize we had so many different level types 😮 
Test failure looks legit. Something may still be referring to these fields.

I'm not sure about level files. @joshlory?

**Comment by ashercodeorg** [comment]
Fixed a test issue, now CircleCI seems to be failing on the `level` files. @joshlory, do you know how I go about removing the field from them? Is simply deleting those lines sufficient (will they get reseeded)?

**Comment by ashercodeorg** [comment]
@Hamms: Do you know if simply deleting the `solution_level_source_id` entry from the `.level` files is sufficient to fix the tests? How do I make sure the column is deleted from the `.level` files in all environments? How do I make sure the column isn't reseed from some environment to another environment?

**Comment by Hamms** [comment]
I think it should be sufficient; the only environment you'll really have to worry about is levelbuilder.

What you might want to do is do a special DTL of the change after hours, when the rate of level churn is minimal and it'll be easier to verify that no changes are re-introducing this value.

**Comment by ashercodeorg** [comment]
PTAL.

**Pull request merged**
