### PR TITLE
DOES NOT WORK: Changes tests to derive from SequelTestCase rather than Minitest::Test.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Though `V2SectionRoutesTest` is not taking advantage of this presently, it will very soon after some of the TODOs are resolved (adding POST requests with updates).

### CODE REVIEW

**Comment by ashercodeorg** [comment]
My guess is that the SequelTestCase fails to rollback dashboard transactions made in the pegasus environment. Is there a fix for this that you see? If not, I may punt and keep the explicit transaction rollbacks.

**Comment by aoby** [comment]
That is disappointing :( I bet you're right, though I'd expect it to work for either db. I don't have a fix off hand, and agree it's not worth spending too much time on this refactor.

It would be nice if we can have all dashboard db interactions, even those in Pegasus, go through the dashboard active record models. One can dream.

**Comment by wjordan** [comment]
Perhaps this might work if we tried changing:

``` ruby
Sequel::Model.db.transaction(:rollback=>:always, :auto_savepoint=>true){super}
```

to: 

``` ruby
Sequel.transaction([PEGASUS_DB, DASHBOARD_DB], :rollback=>:always, :auto_savepoint=>true){super}
```

(according to the [Transactional testing with multiple databases](http://sequel.jeremyevans.net/rdoc/files/doc/testing_rdoc.html#label-Transactional+testing+with+multiple+databases) doc)

**Comment by ashercodeorg** [comment]
Good find, Will. Of course, we'd need to also include `FakeDashboard::use_fake_database` to the list of DBs. Unfortunately, doing so still yields failing tests as a result of the updates not being rolled back.

**Pull request closed without merging**
