### PR TITLE
[finishes 106897336] Disable sharing based on gatekeeper setting

### PR DESCRIPTION
**Pull request by mehalshah**
Doesn't allow user to print - future iteration may reenable that

### CODE REVIEW

**Comment by mehalshah** [comment]
image

**Comment by philbogle** [comment]
@alicesteinglass Does this look OK for when sharing is disabled? (a non-default configuration we will enable if scale is crushing us)

**Comment by philbogle** [comment]
The code changes look fine, was it not necessary to change the template to make rendering degrade nicely in this case?

Please wait for a LGTM from @alicesteinglass.  You might want to ping her on mail/chat.

**Comment by mehalshah** [comment]
No template changes were needed - print, display, share were all in one div
controlled by whether or not there was sharing

On Mon, Nov 2, 2015 at 4:04 PM, philbogle notifications@github.com wrote:

> The code changes look fine, was it not necessary to change the template to
> make rendering degrade nicely in this case?
> 
> Please wait for a LGTM from @alicesteinglass
> https://github.com/alicesteinglass. You might want to ping her on
> mail/chat.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/code-dot-org/code-dot-org/pull/5037#issuecomment-153197926
> .

## 

Mehal Shah

**Comment by philbogle** [comment]
Looks like Alice is busy, you can go ahead and checkin.

**Pull request merged**
