### PR TITLE
Fix contact rollups issue with missing a small % of PD attendees

### PR DESCRIPTION
**Pull request by jeremydstone**
This PR fixes a problem where our contact rollups output had a couple % fewer contacts marked as PD attendees than we would expect from the source data.

It turns out that for all of the contacts missing expected PD attendance information, all of those contacts had duplicate Code Studio accounts under the same email. That is not supposed to happen but it does in a small % of cases. For those duplicate accounts, we were going to pick a single winner in the rollup, which has a uniqueness constraint on email. We would assign the dashboard user ID of the winning account. We were then joining the PD attendance update based on dashboard user ID, which might not be there in the rollup depending on which account "won".

Now we update PD attendance based on email rather than dashboard user ID. This makes PD attendance always get computed correctly in the rollup even for a duplicate source account. Even in the case where a user went through PD with different and duplicate accounts, we will correctly roll up the union of all PD across the duplicate accounts.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Rather than hack around multiple accounts, we should continue to think about fixing the source of the problem.

**Comment by ashercodeorg** [comment]
LGTM.

**Comment by aoby** [comment]
@ashercodeorg do we have insight into how these duplicate accounts are created? Is it relatively easy to fix, at least to prevent it from happening in the future?

**Comment by ashercodeorg** [comment]
Not much insight. Though we have a [rails validation](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/user.rb#L445-L454), we don't enforce uniqueness at the level of the DB. In some sense, that'd be the fix, though we'd need to clean up all the existing duplicates before doing so.

**Comment by ashercodeorg** [comment]
May or may not be connected to our [retrying on uniqueness](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/controllers/registrations_controller.rb#L53-L55) errors?

**Pull request merged**
