### PR TITLE
Remove start and end time restrictions on workshops

### PR DESCRIPTION
**Pull request by clareconstantine**
We previously had dropdowns for the start and end times of workshop sessions that only showed times from 7:00am  to 7:00pm, although you could type in any time you wanted. This range was added in [this PR](https://github.com/code-dot-org/code-dot-org/pull/9878). The input is no longer a dropdown, so users can input their desired start and end times, and we have helpful error checking as shown in the screenshot.

Screen Shot 2020-10-27 at 11 55 54 AM

## Links

- [jira](https://codedotorg.atlassian.net/browse/PLC-943?atlOrigin=eyJpIjoiYzc3ODk5NTMyYjIwNDlhM2I2NjczYjZmNDM5YTZkY2QiLCJwIjoiaiJ9)

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by clareconstantine** [comment]
@tess323 Is this the right solution? We could also set expanded limits, instead of no limits, since we probably won't have workshops starting at 4am, and you can type your time in if it's outside the range we choose. Also, should I add a note to indicate that you can select or type the times, since it's not obvious you can type in any time you want?

**Review by molly-moen — APPROVED** [review]
LGTM! I think a help tip could be useful as well.

**Comment by clareconstantine** [comment]
> LGTM! I think a help tip could be useful as well.

@molly-moen Do you think we need a help tip if we no longer have the dropdown?

**Comment by molly-moen** [comment]
@clareconstantine don't think we need it with this update! Makes a lot more sense now! Out of curiosity what does a user see if they click on the clock icon?

**Comment by clareconstantine** [comment]
> @clareconstantine don't think we need it with this update! Makes a lot more sense now! Out of curiosity what does a user see if they click on the clock icon?

@molly-moen nothing - it's no longer clickable. I didn't remove it because it's kind of cute, but I wonder if leaving it there might confuse people who are used to clicking it to see the dropdown. I hadn't used this form in a long time, so it doesn't feel broken to me, but maybe leaving it there and not having it do anything will feel broken to users. What do you and @tess323 think?

**Review by jamescodeorg — APPROVED** [review]
I think I vote for removing the clock button if it doesn't do anything?

**Comment by jamescodeorg** [comment]
One more question -- do we already have tests covering the error cases that you showed in the screenshot?

**Comment by clareconstantine** [comment]
> One more question -- do we already have tests covering the error cases that you showed in the screenshot?

I don't think this area has much in the way of UI tests, but I will add some for TimeSelect. Thanks!

**Review by molly-moen — APPROVED** [review]

**Pull request closed without merging**
