### PR TITLE
Minimal set up of gem updates to enable omniauth-google-oauth2 0.6.0

### PR DESCRIPTION
**Pull request by joshlory**
Remove Google+ dependency. Updated with:

```
bundle update --source omniauth-google-oauth2 omniauth-clever omniauth-facebook omniauth-microsoft_v2_auth omniauth-windowslive omniauth-oauth2 oauth2 twilio-ruby jwt googleauth omniauth faraday
```

https://codedotorg.atlassian.net/browse/FND-144

### CODE REVIEW

**Review by wjordan — CHANGES_REQUESTED** [review]
I'm not responsible for any code/features depending on these gems, so don't have much to comment on other than it looks like some test failures are related to the update of the `twilio-ruby` gem.

I'd suggest the developer owning our Code Studio accounts-integration feature(s) (@madelynkasula if I recall?) review these dependency updates to make sure all related features are well-tested.

**Review by maddiedierker — APPROVED** [review]
caveat: i can't speak to the update to twilio-ruby. the google and clever oauth gem updates look good, and i have confirmed locally that sign in/up is working as expected.

**Comment by joshlory** [comment]
@wjordan PTAL! (or waive your review if you're not interested in reviewing)

**Comment by joshlory** [comment]
Ping @wjordan

**Review by wjordan — APPROVED** [review]
:+1:

**Pull request merged**
