### PR TITLE
Content change cherrypicks for an email campaign.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by tanyaparker** [comment]
lgtm -- is the friendly-url image part of an email? And is that email already on prod or do we need to include it in this hotfix?

**Comment by ashercodeorg** [comment]
Yes, I believe it is part of an email. And I wasn't told anything about hotfixing the email, just those two files. But let me ask...

**Comment by ashercodeorg** [comment]
No email necessary as part of the hotfix.

**Comment by ashercodeorg** [comment]
Note that the prizes changes were visually inspected on https://staging.hourofcode.com/us/prizes.

**Pull request merged**
