### PR TITLE
Drop survey_answers table and related code

### PR DESCRIPTION
**Pull request by hacodeorg**
_[FND-1584](https://codedotorg.atlassian.net/browse/FND-1584). This is a follow-up of https://github.com/code-dot-org/code-dot-org/pull/40683._ 

Drop `survey_answers` table since it's no longer needed. Also remove `bin/cron/process_jotform_data`, the only script that still has references to the `survey_answers` table. `process_jotform_data` script is not referenced anywhere.

### CODE REVIEW

**Comment by hacodeorg** [comment]
@clareconstantine Since Ben is out, could you take a look at this PR also?

**Comment by bencodeorg** [comment]
Thanks for doing this Ha! Two notes:
1. This is maybe marginally outside the scope of this work, but could you also drop the `survey_questions` table here? They're both dropped/recreated in the script you're deleting, and I'm afraid if we don't do it now we'll never do it.
2. Maybe you're already on this, but we should delete the copies of these tables that exist in Redshift as well after you do this.

**Review by bencodeorg — COMMENTED** [review]
I added a comment with a couple of general notes -- looks like Ha will be out for a while, so might need someone else to push this through if we need to get it done in the next few weeks.

**Comment by daynew** [comment]
> Maybe you're already on this, but we should delete the copies of these tables that exist in Redshift as well after you do this.

Yeah I can do this

**Review by bencodeorg — APPROVED** [review]

**Pull request merged**
