### PR TITLE
get closer to a stable sort in .script_json files

### PR DESCRIPTION
**Pull request by davidsbailey**
Continues https://codedotorg.atlassian.net/browse/PLAT-1049, specifically, makes the following changes to script json:
1. add missing trailing newline
2. sort lesson standards, lesson opportunity standards, lesson vocabs, and lesson programming expressions
2. sort vocabs
3. sort objectives
4. sort script properties hash 
5. sort resources properties hash
6. sort script student resources
7. sort script_level.level_keys
 
This PR should have no user-visible changes, due in part to https://github.com/code-dot-org/code-dot-org/pull/42981.

### script_level.level_keys

level_keys appear in two places in the serialized output:
https://github.com/code-dot-org/code-dot-org/blob/dba82385ed0ba47520575ad3be8806b4c9c2c9f3/dashboard/config/scripts_json/coursea-2021.script_json#L2836-L2846

there is still a problem where the second location (the one outside of the seeding_key) doesn't always show up until the second time an object is serialized. I didn't find a fix for this. I made a note of this in https://codedotorg.atlassian.net/browse/PLAT-1049 .

sorting level_keys is safe here, because we are only sorting them in the serialized format, not in the database. level_keys in the serialized format are only used to identify script_level objects. the `levels_script_levels` field controls what order the levels are added to script_levels.levels in the database.

## Testing story

* `Script.all.each(&:write_script_json)` passing locally. result can be seen in b32317745fd2b8a4479cdb66c0445f9c3b93c019
* between each pair of commits, reserialized and spot-checked a sample .script_json file to make sure the diffs looked roughly as I would expect
* existing tests for script serialization / seeding ensure I didn't break existing functionality
* new unit tests cover new behavior for objects in lessons (standards, vocab, programming expressions) which we are now sorting. I added tests for the update path here, which (with one exception noted in the tests) preserves the order of the existing objects. 

## Deployment strategy

After this change reaches levelbuilder, I'll reserialize all script json files there, to get all the existing .script_json files into the new format.

### CODE REVIEW

**Review by tim-dot-org — APPROVED** [review]
Looks good to me! Glad that we have lots of tests around this

Potentially out-of-scope/unrelated, I noticed this honeybadger error popping up related to the previous PR I think: https://app.honeybadger.io/projects/3240/faults/82042029 could that be fixed real quick as part of this? it seems like objectives.description is sometimes nil

**Comment by davidsbailey** [comment]
> Looks good to me! Glad that we have lots of tests around this

Thanks for jumping on this, Tim!

> Potentially out-of-scope/unrelated, I noticed this honeybadger error popping up related to the previous PR I think: https://app.honeybadger.io/projects/3240/faults/82042029 could that be fixed real quick as part of this? it seems like objectives.description is sometimes nil

Ooh, great catch! I've pushed a fix to this branch, which appears to fix this problem locally.

**Comment by davidsbailey** [comment]
@bethanyaconnor , I'd love to get your eyes on this too if you have the bandwidth. if not, no worries!

**Comment by bethanyaconnor** [comment]
Sorry just noticed the tag! I'll look today!

**Review by bethanyaconnor — APPROVED** [review]
Looks good to me! Thanks for doing all of this!

**Pull request merged**
