### PR TITLE
whitelist nuevaschool.ngrok.io and friends for startWebRequest block in applab

### PR DESCRIPTION
**Pull request by davidsbailey**
see discussion in: https://codeorg.zendesk.com/agent/tickets/111857

### CODE REVIEW

**Comment by islemaster** [comment]
I'm not really convinced that this is less of a security hole; [based on the docs](https://ngrok.com/docs#subdomain) I'm pretty sure _any_ paid ngrok account could claim `nuevaschool.ngrok.io` when it's not in use, and it's not even particularly obscure since it's here in our public repo.

**Comment by davidsbailey** [comment]
Good point. I'll follow up with the school to see if there is any way they can have a hostname on their school's web site point to this. Let me know if you have any other ideas.

**Comment by davidsbailey** [comment]
@islemaster the user claims that the hostnames they've listed are reserved (see comments in zendesk ticket above). This sounds good enough to me -- please let me know if you still have concerns.

**Comment by islemaster** [comment]
Awesome - if they are reserved, let's do it. Note this is still an external
dependency in our security. Maybe we should set a reminder to follow up
each year and see if they've still got it reserved.

**Pull request merged**
