### PR TITLE
Enable `import/order` for Applab Directories

### PR DESCRIPTION
**Pull request by Hamms**
Follow-up to https://github.com/code-dot-org/code-dot-org/pull/57247

For just representing a single one of our app types, this is a relatively big one! As usual, please check for any manual ordering logic or comments that need to be preserved.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by lfryemason — APPROVED** [review]
LGTM

**Comment by Hamms** [comment]
Also updated the circular dependencies tracker. Looks like we haven't introduced any *new* circular dependencies, just tweaked some existing ones slightly. For example, instead of:

```
"src/applab/designElements/button.jsx -> src/applab/designMode.js -> src/applab/DesignWorkspace.jsx -> src/applab/DesignModeBox.jsx -> src/applab/DesignToolbox.jsx -> src/applab/DesignToolboxElement.jsx -> src/applab/designElements/library.js -> src/applab/designElements/button.jsx",
```

We now have:

```
"src/applab/designElements/button.jsx -> src/applab/designMode.js -> src/applab/designElements/library.js -> src/applab/designElements/button.jsx",
```

@thomasoniii can you confirm that it's expected that changing the ordering of imports within a file can result in the circular dependency checker identifying circles slightly differently?

**Comment by thomasoniii** [comment]
> Also updated the circular dependencies tracker. Looks like we haven't introduced any _new_ circular dependencies, just tweaked some existing ones slightly. For example, instead of:
> 
> ```
> "src/applab/designElements/button.jsx -> src/applab/designMode.js -> src/applab/DesignWorkspace.jsx -> src/applab/DesignModeBox.jsx -> src/applab/DesignToolbox.jsx -> src/applab/DesignToolboxElement.jsx -> src/applab/designElements/library.js -> src/applab/designElements/button.jsx",
> ```
> 
> We now have:
> 
> ```
> "src/applab/designElements/button.jsx -> src/applab/designMode.js -> src/applab/designElements/library.js -> src/applab/designElements/button.jsx",
> ```
> 
> @thomasoniii can you confirm that it's expected that changing the ordering of imports within a file can result in the circular dependency checker identifying circles slightly differently?

Yep, completely expected behavior.

The circle still exists since it wasn't cleared up, but since the load order is different, we first encounter the circle at a different point so the value spit out is different.

**Review by thomasoniii — APPROVED** [review]
lgtm 🚀 

And the slightly differently worded circular deps is expected (albeit annoying) behavior.

**Pull request merged**
