### PR TITLE
Restrict Animation Library in SpriteLab

### PR DESCRIPTION
**Pull request by epeach**
Part of: https://docs.google.com/document/d/1GBeHLqyTA0nHtD77LgpxIUAvB9xcGfMshb78Ucsn7jw/edit

Only shows part of the animation library in the animation picker dialog.
Temporary change to meet a deadline.

Before:
Screenshot from 2019-04-26 09-15-59
Screenshot from 2019-04-26 09-16-09

After:
Screenshot from 2019-04-26 09-15-04
Screenshot from 2019-04-26 09-15-15

### CODE REVIEW

**Review by ajpal — APPROVED** [review]

**Comment by joshlory** [comment]
Is the "Warning: do not upload anything that contains personal info" not needed when the upload tile is hidden?

**Comment by epeach** [comment]
@joshlory Good call and easy change to make. Incoming . . .

**Review by joshlory — APPROVED** [review]
I wonder if we could save some size by marking the sprite-lab only costumes instead of shipping a separate `spriteCostumeLibrary.json` to the client? Either way, this LGTM for a first pass!

How will this change interact with the [Animation Pools spec](https://docs.google.com/document/d/1ea5qEKQWSjiautP6e9wykzEO-zjkSCu7R-VVtOO6ADY/edit)?

**Comment by epeach** [comment]
@joshlory Totally agree - ideally, I'd like to add a boolean of sorts to the animation library manifest that indicates whether something is an animation, a costume, or both. That'll save us lots of space when this is released to a broader audience.

**Comment by joshlory** [comment]
Do only users in the experiment group get the larger package, or does it increase the size for everyone?

**Comment by epeach** [comment]
Unfortunately, it increases for everyone. I think optimizing this should be one of the highest priorities after we fix the other bugs.

**Pull request merged**
