### PR TITLE
Remove code docs hosted on Pegasus

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Confirmed with Dani (and Dan) that these are no longer needed! For the other removed files:
- I searched `applab-docs` and all that remains is references to an element ID. I believe this to be unrelated to the files so I removed the files.
- The strings `simple_embedded` and `simple-embedded` don't appear anywhere else except the files deleted in this PR.
- `applab_docs_common` is only used in removed files
- `codemirror` is the most controversial one. In the Pegasus directory, the string only appears in `applab_docs_common` in the Pegasus directory. But we use the `codemirror` package in our apps/ directory. I took a quick look at the usages in apps/ and they all look like they're using the package, not the files I'm deleting here, so I believe this is safe, but open to pushback here.

### CODE REVIEW

**Comment by bethanyaconnor** [comment]
@molly-moen tagging you in this PR in case you have an objections to use removing the code.org-hosted codemirror files.

**Review by kelbyhawn — APPROVED** [review]
Thanks for removing the `simple_embedded` theme too!

**Review by molly-moen — APPROVED** [review]
The codemirror styles here are for the older version of codemirror, which I _think_ we use mostly for internal tools (levelbuilder). So I feel fine about this change, not 100% confident but I agree there shouldn't be anything related to codemirror on pegasus.

**Comment by bethanyaconnor** [comment]
Sounds good! I'll keep an eye open for any codemirror-related bug reports.

**Pull request merged**
