### PR TITLE
Code Review Groups: Add code_review_expires_at column to sections

### PR DESCRIPTION
**Pull request by bencodeorg**
Adds a column to `sections` to house a timestamp specifying whether a section has code review enabled or not.

## Testing story

Tested manually.

## Follow-up work

Once we've implemented this feature, we'll be dropping the existing `code_review_enabled` column. That work is tracked in this item:
https://codedotorg.atlassian.net/browse/CSA-1010

### CODE REVIEW

**Comment by bencodeorg** [comment]
@bethanyaconnor did you encounter any performance/db issues in your migration that added the `code_review_enabled` column?

**Comment by bethanyaconnor** [comment]
> did you encounter any performance/db issues in your migration that added the code_review_enabled column?

I did but it was due to me trying to update the value in that column during the migration. Adding the column itself wasn't the issue iirc

**Comment by bencodeorg** [comment]
@sureshc would appreciate a set of eyes from infrastructure if you have a moment. This PR adds a nullable column with no default values, so I'm not anticipating this will cause issues?

[I looked MySQL docs about online ddl operations](https://dev.mysql.com/doc/refman/5.7/en/innodb-online-ddl-operations.html#online-ddl-column-syntax-notes), which notes that this can be done with concurrent dml. Bethany noted issues adding a column to this table, but we think they were related to updating the value in the column, not adding the column itself.

**Review by molly-moen — APPROVED** [review]
LGTM, but I'll defer any database concerns to infra

**Comment by bencodeorg** [comment]
@code-dot-org/learning-platform would you have any objection to me updating this PR to add a `properties` column instead of the currently proposed code review-specific column, such that future stuff like this wouldn't require a new column (or review from infra 😆 )? cc @bethanyaconnor

**Comment by jamescodeorg** [comment]
Could you remind me if `code_review_expires_at` is going to replace `code_review_enabled` or work in conjunction with it?  If we're not replacing it, it might be weird to have one value in a column and one value in the properties blob.  Also, will RED want to query this value?

**Comment by bencodeorg** [comment]
> Could you remind me if `code_review_expires_at` is going to replace `code_review_enabled` or work in conjunction with it? If we're not replacing it, it might be weird to have one value in a column and one value in the properties blob. Also, will RED want to query this value?

Replacing. Yeah, `properties` definitely introduces querying pain, but I don't see a ton of analytic use for this value (it'll be set to 90 days from the last time that a teacher enabled code review by toggling a switch on).

**Comment by jamescodeorg** [comment]
Ok, I'm not totally sure how we decide between using a column vs. putting something in `properties`, but I don't have any objections to putting it in `properties`.

**Comment by bethanyaconnor** [comment]
> how we decide between using a column vs. putting something in properties,

The guidelines I normally use are:
1. whether we will ever want to query this field directly, i.e. get all the sections in our system that have code review enabled
2. whether RED needs this field for anything, like James asked

I don't _think_ either of these apply here but I haven't looked at any info about this version of this feature (neither applied when I implemented `code_review_enabled`).

**Review by bakerfranke — APPROVED** [review]
RED team does not currently use this value for analytic purposes.

**Comment by bencodeorg** [comment]
Closing in favor of a properties column:

https://github.com/code-dot-org/code-dot-org/pull/43368

**Pull request closed without merging**
