### PR TITLE
Add "Print Lesson Plan" button

### PR DESCRIPTION
**Pull request by Hamms**
Just a simple button linking to the new Lesson Plan pdfs:

image

Specifically, it links to them with the `download` attribute. That attribute plus the fact that we're now serving the PDFs from a code.org subdomain (thanks to https://github.com/code-dot-org/code-dot-org/pull/39221) means that this will actually function as a download button.

## Caching

PDFs are served from S3 via a CloudFront distribution with caching enabled.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dmcavoy** [comment]
The code change looks good. I reached out to Tess about the location of the button because it just feels weird to me in the middle of the right hand column. It feels like it should be towards the top of the page. @tess323 want to share your thoughts here once you are out of meetings?

**Comment by dmcavoy** [comment]
Proposal for new location of the print lesson pdf button @tess323 
110033730-a0fe1980-7cee-11eb-8369-34a37eff7069

**Comment by tess323** [comment]
Great catch @dmcavoy - this was a miss on my part as the design evolved.  @Hamms so excited to see this coming together! Thank you for architecting this solution.

**Comment by davidsbailey** [comment]
I am not a designer, but... orange is our primary call to action color. @tess323 is printing supposed to be the primary call to action for this page?

**Comment by Hamms** [comment]
Oh, good call on the design! I also just realized that if the button is in the sidebar, it also shows up in the printed PDF which is a bit odd. Putting it in the header sounds good to me, as does making a change to a less-prioritized UI color.

**Comment by tess323** [comment]
Good call lets go with grey for the button.  Sorry this was one of my first specs back as I was getting started.

**Comment by Hamms** [comment]
PTAL

**Comment by tess323** [comment]
Looks good to me

**Review by dmcavoy — APPROVED** [review]
🎉

**Pull request merged**
