### PR TITLE
disable flaky ui test scenarios in applab/versions

### PR DESCRIPTION
**Pull request by davidsbailey**

### CODE REVIEW

**Comment by davidsbailey** [comment]
there were some failures in the DTT after https://github.com/code-dot-org/code-dot-org/pull/23440 was merged, mostly in the added UI tests. this PR disables the scenarios that weren't working.
* @mehalshah please help me confirm that I got all of the failing scenarios
* @islemaster please help me confirm that this is not a bad idea

**Comment by islemaster** [comment]
> please help me confirm that this is not a bad idea

Ah, the most difficult kind of review.

**Comment by davidsbailey** [comment]
Good point Brad, it looks like there is some timing problem in IE that I do not fully understand. I am calling it a timing issue because I was able to confirm that the right thing happens when I carry out the ui test steps manually. I will follow up by debugging this in IE11 and re-enabling.

**Comment by islemaster** [comment]
:+1: Sounds great!

**Pull request merged**
