### PR TITLE
Ruby 2.6.6

### PR DESCRIPTION
**Pull request by Hamms**
Update to Ruby 2.6 by making necessary changes to Drone, Rubocop, Gemfiles, setup instructions, Chef, and Docker.

We update to 2.6.6 specifically because that's the version of Ruby installed by `apt`, via our cookbooks.

## Links

- https://rubyreferences.github.io/rubychanges/2.6.html
- https://github.com/code-dot-org/code-dot-org/pull/20879

## Testing story

- Tested on Drone with a temporary `code-dot-org:ruby-2.6.6` Docker image
- Tested on an adhoc at https://adhoc-ruby-2-6-with-adhoc-fix.cdn-code.org/; see https://github.com/code-dot-org/code-dot-org/pull/46908

## Deployment strategy

- [x] get a green drone run with the temporary `code-dot-org:ruby-2.6.6` docker image
- [x] (after PR approval) build a new main-line `code-dot-org:1.4` docker image
- [x] get a green drone run with the new main-line docker image and merge

We'll also need to notify all developers that they will need to run the Ruby portion of our setup documentation locally after pulling these changes:

```bash
rbenv install
gem install bundler -v 1.17.3
rbenv rehash
bundle install
```

**Note** that M1 Mac users will still need to apply the same M1-Mac-specific workarounds as laid out in [our setup documentation](https://github.com/code-dot-org/code-dot-org/blob/staging/SETUP.md#os-x-monterey---including-apple-silicon-m1)

## Follow-up work

After this, we'll be on the recommended version of Ruby for Rails 6.0, and should be ready to update to Rails 6.1, then to Ruby 2.7.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by cat5inthecradle — COMMENTED** [review]
Is there value in announcing this and the need to `rbenv install` at next Tuesday's tech proposal meeting while we have a good portion of engineering on a call?

**Comment by cat5inthecradle** [comment]
This looks good to me, I'm just not currently in an internet situation to test much locally today.

**Comment by Hamms** [comment]
It's definitely worth announcing it; I was thinking of doing it in the next Eng&Prod meeting, but I see we don't have one of those for a couple weeks. The technical proposal review does seem to be the next best meeting for this, but it's not a perfect fit.

How'd you feel about me announcing this in an email plus slack thread a day or so in advance of merging; think that would be sufficient?

**Comment by Hamms** [comment]
@code-dot-org/dev-tools-group could someone who has a mac test this out locally?

Specifically, run the ruby-specific parts of the SETUP.md documentation from the project root:

```bash
rbenv install
gem install bundler -v 1.17.3
rbenv rehash
bundle install
```

**Comment by cat5inthecradle** [comment]
successfully ran `optflags="-Wno-error=implicit-function-declaration" LDFLAGS="-L/opt/homebrew/opt/libffi/lib" CPPFLAGS="-I/opt/homebrew/opt/libffi/include" PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig" rbenv install`

updated gemfile lock for M1

successfully ran `gem install bundler -v 1.17.3`

successfully ran `rbenv rehash`

received error during `bundle install`:

```
Downloading mini_racer-0.4.0 revealed dependencies not in the API or the lockfile (libv8-node (~> 15.14.0.0)).
Either installing with `--full-index` or running `bundle update mini_racer` should fix the problem.
```

Rolling back `mini_racer` to `0.3.1` from `0.4.0` and trying `bundle install` again, same error.

Flipped back to `0.4.0` and trying `bundle update mini_racer`, this updated mini_racer to `0.6.2`

Successfully ran `bundle install`

**Comment by Hamms** [comment]
Just to confirm: when you updated the gemfile lock for M1, what all changes did you make? Specifically, does your new lockfile include `libv8-node (~> 15.14.0.0)`?

**Comment by Hamms** [comment]
According to https://github.com/code-dot-org/code-dot-org/blob/staging/SETUP.md#apple-silicon-m1-bundle-install-steps, you may also need to run `export LIBRARY_PATH=$LIBRARY_PATH:/opt/homebrew/opt/openssl/lib/` between `rbenv rehash` and `bundle install`

**Review by cat5inthecradle — APPROVED** [review]

**Pull request merged**
