### PR TITLE
Cloudfront static error page fallback

### PR DESCRIPTION
**Pull request by wjordan**
Adds a static error page fallback to CloudFront distribution. Response with a static html page when the origin server responds with a 502, 503 or 504 error. Error responses are not cached so as soon as the site responds with a non-error response code again, the static html page will go away.

### CODE REVIEW

**Comment by philbogle** [comment]
Now that HOC is over, do we want to check in this PR or should it be retired?

**Comment by wjordan** [comment]
Although HoC2015 is over we would still expect 5xx errors to pop up from time to time (e.g. during deployments or unexpected downtime), so having a user-friendly fallback page for the topmost CDN layer in place could provide a slightly better experience (compared to e.g. a blank white page).

However, to get this ready for check in we would want some more product discussion on the content of the fallback page(s) beyond the HoC-specific design we currently have (which is probably low-priority compared to other things going on).

**Comment by philbogle** [comment]
I think the design of the fallback pages  is a valuable discussion to have.  It doesn't necessarily have to happen during this sprint if we're fully booked, however.

**Comment by philbogle** [comment]
Unassigning myself since this is no longer under active review.

**Comment by wjordan** [comment]
Implemented in #28944.

**Pull request closed without merging**
