### PR TITLE
Update contact rollups validation

### PR DESCRIPTION
**Pull request by jeremydstone**
In production, one of the data validations we use to determine if a nightly contact rollup is sane recently started failing. The count of contacts with courses facilitated dropped from a little above 400 to a little below 400. The minimum set for validation was 400. The drop was real and for legitimate reasons. The validation was being a little too aggressive. I lowered the minimum from 400 to 100. The spirit of the validation is that it is a sanity check against grossly incorrect values. (For instance, if we ever see 0 or 1M for this value, we know that's a clear problem.) A minimum of 100 serves that purpose nicely for this value.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
LGTM. Any chance the two commits could be squashed into one?

**Comment by jeremydstone** [comment]
Thanks. Squashed.

**Comment by jeremydstone** [comment]
Note: merging prior to CircleCI finishing to get this into production today. This is just a constant change and is not even run in CircleCi.

**Comment by aoby** [comment]
Note you can include `[ci skip]` in your commit title to skip CI entirely next time it's not needed. See https://github.com/code-dot-org/code-dot-org/blob/staging/TESTING.md#using-circleci

**Pull request merged**
