### PR TITLE
Re-throw native errors

### PR DESCRIPTION
**Pull request by joshlory**
Follow up to PR https://github.com/code-dot-org/code-dot-org/pull/23842.

Treat errors in native-code-called-by-the-interpreter different from errors inside interpreted code.

### CODE REVIEW

**Comment by joshlory** [comment]
I'm worried there may be cases where we're relying on native errors being reported back to the student.  Should I be logging the error, but not re-throwing it?

**Comment by islemaster** [comment]
:confused: My impression was that you've preserved existing behavior but added more appropriate logging (at least in `CustomMarshalingInterpreter`).  Do you mean we're relying on this from a curriculum point of view?

**Comment by joshlory** [comment]
Throwing [on line 37 of JSInterpreter.js](https://github.com/code-dot-org/code-dot-org/pull/24080/commits/6c29d2ecda4f19abe8daf4f13c8c68c872416a5b#diff-a3621079cb56f8699b2aa97bc01a025eR37) instead of returning the error would be a behavior change.  I'll update to not re-throw!

**Comment by joshlory** [comment]
(To answer your earlier question, it looks like yes curriculum does rely on this.  For example this error in App Lab.)

image

From:

https://github.com/code-dot-org/code-dot-org/blob/0c75e84177dfa863cb293b88e086f9f158815ae1/apps/src/applab/commands.js#L96-L98

**Pull request merged**
