### PR TITLE
Move blockly core to separate repo

### PR DESCRIPTION
**Pull request by Hamms**
And replace it with our new [npm package](https://www.npmjs.com/package/@code-dot-org/blockly), powered by our new [githup repo](http://github.com/code-dot-org/blockly).

This commit is obviously huge, as it removes one of the larger subdirectories in our repo. I highly recommend focusing the attention of your review on [these two commits](https://github.com/code-dot-org/code-dot-org/compare/a1eb17c15618dfbdac6dfe121f8ffb63b094d25c...fba3af2b741e971131c5d185d59b2551ac40fa7a)

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
How does blockly-core get built in this new world? Is it part of CI at all, or does it require a manual rebuild?

Also, this seems like it might be a worthwhile time to make it so that dashboard/public/blockly maps gets renamed to dashboard/public/apps since (something that should have been done when we renamed blockly to apps) since blockly now very explicitly means something else.

**Comment by Hamms** [comment]
It does require a manual rebuild, which is indeed a slight step backwards. It wouldn't be too difficult to put together a simple CI build for this, but given how rarely blockly gets updated (and given that it's usually me doing the updating) I don't see the need to do that at this point.

**Comment by islemaster** [comment]
Is the story for local development on blockly-core within apps well-documented?  It looks like [this section](https://github.com/code-dot-org/code-dot-org/tree/move-blockly-core-to-separate-repo/apps#full-build-with-blockly-core-changes) within the apps README still has an outdated link to github.com/code-dot-org/blockly-core, and to build_with_core.sh which I think you've removed.

**Comment by islemaster** [comment]
A couple of comments on https://github.com/code-dot-org/blockly:
- It'd be nice if the README there had instructions for publishing an updated version, which may not be obvious to all devs.
- I'd like [the `preversion` step](https://github.com/code-dot-org/blockly/blob/staging/package.json#L22) to run tests too.
- Let's get Circle or Travis set up for that repo - I assume that hasn't happened yet because it's still private.

**Comment by islemaster** [comment]
This probably lowers our average build time, it'd be fun to measure how much.

**Comment by islemaster** [comment]
Should maybe disable issues and wiki on code-dot-org/blockly too, unless we really want to use those on that subproject.

**Comment by Hamms** [comment]
The story is not well-documented at all! I'll fix that, and update READMEs for both this repo and blockly.

The `deploy` script automatically runs tests, which means the preversion step actually runs tests twice.

I definitely intend to set up circle! Your assumption is entirely correct.

**Comment by islemaster** [comment]
Semver proposal: Go ahead and start code-dot-org/blockly at 1.0.0 (or some 1.0.x).  I think we consider it stable at this point.  google/blockly's package.json says 1.0.0, but I don't think they're actually doing releases.

**Comment by Hamms** [comment]
Updated [apps readme](https://github.com/code-dot-org/code-dot-org/tree/move-blockly-core-to-separate-repo/apps#full-build-with-blockly-changes) and [blockly readme](https://github.com/code-dot-org/blockly#building-with-apps)

**Comment by islemaster** [comment]
totally_wicked

Overall this looks excellent.  I'm pulling and trying it out right now.  Have you tested this on an adhoc server, just to verify there are no dependencies on stale built files or non-fingerprinted anything?

**Comment by islemaster** [comment]
Everything looks good in my local build.

**Comment by Hamms** [comment]
I'm getting a migration error spinning up adhoc; the error repros when trying to spin up an adhoc on staging as well, so I'm confident that _that_ particular error is not mine, but it means I've been unable to verify that there are no further errors.

**Comment by Hamms** [comment]
Thanks to @aoby 's fix for adhoc environments, I was able to spin up https://adhoc-move-blockly-core-to-separate-repo.cdn-code.org/

**Pull request merged**
