### PR TITLE
Render react elements instead of iframe for reference guides in map levels

### PR DESCRIPTION
**Pull request by tim-dot-org**
Conditionally renders a reference guide react element instead of the old iframe for concept maps.

Not sure if this is the best way to structure things, but its the way that works most easily with the existing stuff. Potentially another route would be to create a new Level type for reference guides?

## Links

- spec: [product spec](https://docs.google.com/document/d/1VZGle7QA-06ZNNxy2SkvA8Msrok8pyN7fuq5hzek888/edit)
- jira ticket: [PLAT-1694](https://codedotorg.atlassian.net/browse/PLAT-1694)

## Testing story
Tested manually, plus some unit tests

## Screenshots
levels_controller map level
image

script_levels_controller map level
image

reference guide view page
image

compare to old iframe concept map:
(we don't have the creative commons license included at the bottom, but that can be part of a separate change to add to all of them)
image

### CODE REVIEW

**Comment by dmcavoy** [comment]
I just added the creative commons license to the lesson plan here if you want to just extract it into a component for reuse in both places. https://github.com/code-dot-org/code-dot-org/pull/46060

**Review by dmcavoy — APPROVED** [review]
I think this is the right strategy since the curriculum is already launched with map levels in it. It would be much harder to change those to a different level type. I just checked that the curriculum reference levels from past years work (example if you haven't seen them: http://localhost-studio.code.org:3000/s/csp1-2018/lessons/1/levels/1). Since Map Levels are a type of curriculum reference level I want to make sure those were still good. Everything looks great! It would be awesome to add the creative commons license like was just added to the lesson plan but definitely not blocking this PR.

**Comment by tim-dot-org** [comment]
image
Pulled the copyright info into a generic component and added it to the ref guide pages.
Also translated the documentation bug text because that should be translated too!

**Review by dmcavoy — APPROVED** [review]
Thanks for extracting that component and translating the documentation bug report line.

**Pull request merged**
