### PR TITLE
fix 'sign in' button on studio.code.org homepage

### PR DESCRIPTION
**Pull request by dlittle1**
@tanyaparker 
The text was the only thing linking before. The entire button is now a link.

screen shot 2016-03-15 at 8 20 35 pm

### CODE REVIEW

**Comment by tanyaparker** [comment]
lgtm

**Comment by mehalshah** [comment]
Yay! Welcome to the team!

**Comment by mehalshah** [comment]
Glad to hear that setup wasn't a pain

**Comment by islemaster** [comment]
Awesome @dlittle1!  Thanks for contributing!

**Comment by dlittle1** [comment]
@mehalshah @islemaster Thank you! It's good to be here.

**Comment by bcjordan** [comment]
Woo, welcome and thanks for contributing @dlittle1! That button target threw me off at least once before, feels great now. :raised_hands:

**Comment by breville** [comment]
nice!

**Pull request merged**
