### PR TITLE
security: fix various security issues

### PR DESCRIPTION
**Pull request by evilcrash**
createCanvas' width and height are not properly validated and window.crypto.getRandomValues() is more cryptographically secure than Math.random() (especially used within the createUuid() context)

## Testing story
these changes were manually tested and do not affect any automatic tests

- [X] Tests provide adequate coverage
- [X] Privacy and Security impacts have been assessed
- [X] Code is well-commented
- [X] New features are translatable or updates will not break translations
- [X] Relevant documentation has been added or updated
- [X] User impact is well-understood and desirable
- [X] Pull Request is labeled appropriately
- [X] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by evilcrash** [comment]
@ajpal @davidsbailey

**Comment by davidsbailey** [comment]
is this you, @Hamms, and are you looking for a reviewer ? If so I would suggest @code-dot-org/starlabs team which, sadly, no longer includes Anjali.

**Comment by evilcrash** [comment]
not Hamms, sorry. I am however looking for a reviewer

**Comment by evilcrash** [comment]
@mikeharv

**Pull request closed without merging**
