### PR TITLE
Remove 'Join' button from router in lobby if it's already at capacity.

### PR DESCRIPTION
**Pull request by islemaster**
Before, a full router would have a "Join" button but when you clicked it the operation would fail and nothing would happen.  Now we do the user-friendly thing and hide the "Join" button if the router is full.

[Pivotal #94627790](https://www.pivotaltracker.com/story/show/94627790)

screenshot from 2015-05-22 10 32 29

### CODE REVIEW

**Comment by bcjordan** [comment]
This is a micro-ux-optimization, but as a user I think I would expect a "Full" text in place of the join button rather than the message at the end of the description.

Also see that'd require some tweaking of the code to transmit the "Full" status reasoning, so may not be worth it.

**Comment by bcjordan** [comment]
LGTM!

**Comment by islemaster** [comment]
Oooh, interesting.  Like instead of vanishing, the "Join" button would turn disabled and its text would change to "Full"?

**Comment by islemaster** [comment]
@bcjordan how about this?

screenshot from 2015-05-22 10 55 14

**Comment by bcjordan** [comment]
Looks good! You can probably also remove the "No more room." end of message now that that's there

**Comment by bcjordan** [comment]
Way too design-nitty for this stage, but totally want to push the full button one or two pixels to the left to center-align with the Join buttons :)

**Pull request merged**
