### PR TITLE
Revert "Revert "Rename "stages" to "lessons" in i18n: Step 3""

### PR DESCRIPTION
**Pull request by Hamms**
Reverts code-dot-org/code-dot-org#35009, restoring https://github.com/code-dot-org/code-dot-org/pull/34878. Depends on https://github.com/code-dot-org/code-dot-org/pull/35408. Part of the ongoing rename work.

Overall plan of attack:

1. Add all strings keyed by the term "stage" to crowdin under the key "lesson". (original: https://github.com/code-dot-org/code-dot-org/pull/34854, second attempt: https://github.com/code-dot-org/code-dot-org/pull/35408)
2. Wait for a sync; Crowdin will automatically duplicate translations for the new strings (https://github.com/code-dot-org/code-dot-org/pull/35426)
3. Update all I18n.t references currently using the key "stage" to use the new "lesson" translations (original: https://github.com/code-dot-org/code-dot-org/pull/34878, second attempt: **this PR**)
4. Remove old "stage" strings now that they are no longer used

### CODE REVIEW

**Comment by uponthesun** [comment]
Was the only reason for the revert the eyes failures?

**Comment by Hamms** [comment]
Yep!

**Comment by Hamms** [comment]
https://github.com/code-dot-org/code-dot-org/pull/35408 contains more details about what exactly went wrong the first time

**Review by davidsbailey — APPROVED** [review]
Looks good!

**Review by uponthesun — APPROVED** [review]

**Pull request merged**
