### PR TITLE
Fix Violations of and Reenable `Style/AccessModifierDeclarations`

### PR DESCRIPTION
**Pull request by Hamms**
> Access modifiers should be declared to apply to a group of methods or inline before each method, depending on configuration. EnforcedStyle config covers only method definitions. Applications of visibility methods to symbols can be controlled using AllowModifiersOnSymbols config.

I'm not sure how I feel about this one. I definitely like consistency, but I don't know which of the `EnforcedStyle` options is better:

```ruby
# EnforcedStyle: group (default)
class Foo

  private

  def bar; end
  def baz; end

end

# EnforcedStyle: inline
class Foo

  private def bar; end
  private def baz; end

end
```

My two biggest concerns with the `group` style is that it adds syntactic significance to the location of a method definition within a file, and that for particularly large model files (of which we have a few) it can be easy to not realize you're within the "private" block.

The `inline` style is slightly noisier, though, and it can be messy to have private methods scattered all throughout the class definition.

Thoughts? Preferences? Suggestions?

## Links

- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/AccessModifierDeclarations
- https://docs.rubocop.org/rubocop/cops_style.html#styleaccessmodifierdeclarations

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
Inline is my preference, but I've never worked in a codebase that supports the group option. I feel like you'd have to pair the group style with other practices (like super small classes) to keep code readable.

**Comment by Hamms** [comment]
Here's what `inline` looks like: https://github.com/code-dot-org/code-dot-org/pull/50709

**Comment by davidsbailey** [comment]
I am curious, what is the impetus for adding this style rule? 

If we did have to pick one style, I think the arguments for `inline` are stronger, even though it is much less common in our codebase and feels less familiar. but depending on the reason for wanting to do this, we could perhaps also consider not enabling this style rule.

another argument for `inline` is that it's easier to keep private helper methods closer to the public methods which use them: https://github.com/rubocop/rubocop/issues/730

also related, there are 3 ways I'm aware of to declare private class methods today:
1. `private_class_method def self.method`
2. ([example](https://github.com/code-dot-org/code-dot-org/blame/d39905eaa890eaf65d1c60c66e1e6aec1ee18f3a/dashboard/lib/services/complete_application_reminder.rb#L41))
```
class << self
  private
  def method
```
3. 
```
class << self
  private def method
```

if we choose `group` for instance methods but also want to use https://msp-greg.github.io/rubocop/RuboCop/Cop/Style/ClassMethodsDefinitions.html to disallow the use of `class << self`, we might be sad because AFAIK we'd still be stuck using an inline declaration (1) for private class methods.

**Comment by Hamms** [comment]
I wouldn't say this rule is being added so much as the exception we had in place to ignore it is being removed.

This style rule, as well as all the others in the `.rubocop_todo.yml` configuration file were not intentionally disabled; when we decided to add linting in the first place we also ran a script which automatically disabled all rules for which we had any existing violations, rather than fixing up existing code to meet style standards. We certainly do have the option of _intentionally_ disabling this rule, but I think to do that we'd need to make the argument that inconsistency in this space is somehow desirable.

I increasingly prefer the `inline` approach; it's a bigger diff to implement, yes, but it's actually smaller than I expected and explicit really is better than implicit, even if it does mean a little bit of repeating ourselves.

I do want to note, however, that there is another way to define private class methods which is compatible with either `group` or `inline` approach, and that's modules:

```ruby
class Foo
  module ClassMethods
    private

    def method
      # pass
    end
  end

  extend ClassMethods
end
```

**Comment by Hamms** [comment]
I wouldn't say this rule is being added so much as the exception we had in place to ignore it is being removed.

This style rule as well as all the others in the `.rubocop_todo.yml` configuration file were not intentionally disabled; when we decided to add linting in the first place we also ran a script which automatically disabled all rules for which we had any existing violations, rather than fixing up existing code to meet style standards. We certainly do have the option of _intentionally_ disabling this rule, but I think to do that we'd need to make the argument that inconsistency in this space is somehow desirable.

I increasingly prefer the `inline` approach; it's a bigger diff to implement, yes, but it's actually smaller than I expected and explicit really is better than implicit, even if it does mean a little bit of repeating ourselves.

I do want to note, however, that there is another way to define private class methods which is compatible with either `group` or `inline` approach, and that's modules:

```ruby
class Foo
  module ClassMethods
    private

    def method
      # pass
    end
  end

  extend ClassMethods
end
```

**Comment by davidsbailey** [comment]
ok -- i'm sold on `inline`!

**Comment by bencodeorg** [comment]
+1 to inline after reading through this :), have often missed when private methods are defined well below the `private` annotation

**Comment by Hamms** [comment]
Great, thanks! Implementation of `inline` is ready for review here: https://github.com/code-dot-org/code-dot-org/pull/50709

**Comment by Hamms** [comment]
Closing in favor of `inline`

**Pull request closed without merging**
