### PR TITLE
Removes hardcoding of the metrics['started'] value and adds a delta correction factor.

### PR DESCRIPTION
**Pull request by ashercodeorg**
The correction number is based on the computations here: https://docs.google.com/spreadsheets/d/1oSakWNiOvHsaV50oEb5zAKOiGHdQUdOAJasC_FvECks

### CODE REVIEW

**Comment by philbogle** [comment]
Can you adjust the permissions for the linked document so that everyone with the link can see it?

**Comment by ashercodeorg** [comment]
Oops, done (now permissioned for the whole org).

**Comment by philbogle** [comment]
LGTM.  You might want to add a note in the document that it is still being written.

**Comment by ashercodeorg** [comment]
@laurelfan @Hamms as FYI.

**Pull request merged**
