### PR TITLE
Send project error firehose events before reloading page

### PR DESCRIPTION
**Pull request by jamescodeorg**
There were some error scenarios where we tried to post a debug event to firehose but then immediately reloaded the page before the event could be sent.  This change fixes two specific instances of this by waiting for the Promise from sending the debug event to resolve before reloading the page.

Also, fixed an issue where we weren't exiting the `sources.put` callback function in all error cases and the "error saving project" banner would appear very briefly and then be immediately overwritten.  This wasn't noticeable before this change because the page would be immediately reloaded but is visible now that there is a small delay before the page is reloaded.

## Links

- jira ticket: [LP-2130](https://codedotorg.atlassian.net/browse/LP-2130)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by Erin007 — APPROVED** [review]
I wouldn't expect it to, but does this make the page reload noticeably slower?

**Review by maureensturgeon — APPROVED** [review]
Did you test this locally?

**Comment by jamescodeorg** [comment]
> I wouldn't expect it to, but does this make the page reload noticeably slower?

@Erin007 Good question!  There is now a pause after the error occurs before the page reloads.  The pause is as long as it takes to get the response for the firehose request.  It isn't really visible to the user in the sense that the user sees the "error saving project" icon but they are not expecting / waiting for the page to reload so it's just slightly later that they are surprised that the page reloaded on its own.  I considered an alternate fix to wait exactly a second before reloading but thought this was clearer and added acceptable risk to an already very edge-case scenario.

**Comment by jamescodeorg** [comment]
> Did you test this locally?

@maureensturgeon Yes, with some caveats. The original repro no longer works (because we fixed the bug) so I had to simulate an error response by placing a breakpoint and messing with the internal state.  I was able to observe the page reloaded as expected after that.  (As I type this, I just thought of a way to trigger the conflict error, let me give that a try and verify the behavior.)

**Comment by jamescodeorg** [comment]
Thank to Maureen's nudge, I was able to manually test a scenario end-to-end and found a pre-existing bug that was hard to spot when I was messing with things in the debugger.  That bug is now fixed and Maureen took a quick look at it so I'm going to go ahead and merge.

**Pull request merged**
