### PR TITLE
Reenable storybook deploy as part of staging apps build

### PR DESCRIPTION
**Pull request by bencodeorg**
We have a public version of our Storybook (UI library) that hasn't been updated in 5 years here:

https://code-dot-org.github.io/cdo-styleguide/

We have active collaboration happening between our design and engineering teams on a component library, and it would be nice to have a public URL that could be viewed by all parties showing the current state of existing components.

This PR implements what I think would be the minimal approach to reenabling this, based on discussion from a couple years ago (!) [here](https://codedotorg.slack.com/archives/C0T0PNR0D/p1625593468054400).

Other more modern solutions (Fargate, Github Actions) were suggested in [this more recent thread](https://codedotorg.slack.com/archives/C03CK49G9/p1689269206156649). If reenabling this doesn't work and requires more substantial work to fix, it may be worth pursuing one of these other solutions.

## Testing story

I haven't tested this -- plan on merging one afternoon after we've DTP'd so we can see what happens as part of a staging build.

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
I say give it a go! I couldn't help but explore the GitHub Actions route a little bit, so if this hits snags I can share some of that.

**Review by Hamms — APPROVED** [review]
I'm down for the "merge and see what happens" plan! What else are Summer Fridays for? :smile:

**Comment by bencodeorg** [comment]
Does this look right from a credentials perspective?

https://github.com/code-dot-org/code-dot-org/blob/4d0a4682c7148e465155ae72dfab87aa5b3b9564/apps/script/deploy-storybook.sh#L54-L55

**Comment by Hamms** [comment]
"Circle CI" is definitely a bit outdated, but I don't know how much that field matters for anything beyond labeling. The email looks right, though, which I think is the one that's important.

**Review by levadadenys — APPROVED** [review]
Fingers crossed this'll help!
LGTM, but it looks like drone build is failing for some reason :(

**Pull request merged**
