### PR TITLE
AI differentiation chat UI phase 1

### PR DESCRIPTION
**Pull request by etaderhold**
Basic rendering of messages and choices in the differentiation chat message window. Does not interact with backend at all.

image
image

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by cearachew** [comment]
Unless Tess or Molly say otherwise, we should make this so that once a preset chat choice is selected, the others are unselectable. Looks like right now you can select/ unselect any combination
Screenshot 2024-08-21 at 4 18 42 PM

**Comment by cearachew** [comment]
I'm also seeing this warning in the console, idk if one of the other users of the shared ai components has a fix for this
Screenshot 2024-08-21 at 4 19 15 PM

**Comment by etaderhold** [comment]
> Unless Tess or Molly say otherwise, we should make this so that once a preset chat choice is selected, the others are unselectable. Looks like right now you can select/ unselect any combination Screenshot 2024-08-21 at 4 18 42 PM

Good catch. I made it so you can only select a chip from the bottom of the message history, and can only select one.


> I'm also seeing this warning in the console, idk if one of the other users of the shared ai components has a fix for this Screenshot 2024-08-21 at 4 19 15 PM

Fixed!

**Review by cearachew — APPROVED** [review]
Thanks for making those fixes!! :shipit:

**Pull request merged**
