### PR TITLE
Fix broken link on inspire page

### PR DESCRIPTION
**Pull request by TurnerRiley**
We received a Zendesk ticket about a broken link on the [/educate/resources/inspire](https://code.org/educate/resources/inspire) page that sent the user to the no-longer active [/careers](https://code.org/careers-in-tech) page. This PR fixes it to send the user to [/careers-with-cs](https://code.org/careers-with-cs). It also updates `careers.moved` and a use of `/careers-in-tech` on the [/girls](https://code.org/girls) page.

### Previous /inspire page
PREV

### New /inspire page
fix_link

### Previous /girls page
old

### New /girls page
new

## Links
Zendesk ticket: [here](https://codeorg.zendesk.com/agent/tickets/488732)

## Testing story
Local testing.

### CODE REVIEW

**Review by kelbyhawn — COMMENTED** [review]
Can you update this [careers.moved](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/careers.moved) file to `/careers-with-cs` too?

**Comment by hannahbergam** [comment]
> Can you update this [careers.moved](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/careers.moved) file to `/careers-with-cs` too?

Good catch!

**Comment by TurnerRiley** [comment]
> Can you update this [careers.moved](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/careers.moved) file to `/careers-with-cs` too?

Done! Thank you for catching that!

**Comment by TurnerRiley** [comment]
> > Can you update this [careers.moved](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/careers.moved) file to `/careers-with-cs` too?
> 
> Done! Thank you for catching that!

Also found a use of it on the /girls page so I'll update that as well!

**Review by kelbyhawn — APPROVED** [review]
Thanks for updating the .moved file and the additional pages 🎉

**Pull request merged**
