### PR TITLE
Finish game on "Finish" button press rather than execution completion

### PR DESCRIPTION
**Pull request by bcjordan**
- Show fails on free play levels

http://28b03fa4.ngrok.io/s/mc/stage/1/puzzle/14

Previously, we would end the game when execution ends.

This adds a "Finish" button on first "Run" that pops up the completion/sharing dialog.

Resize behavior:

button

Now proper error on run w/ unattached block:

image

Sharing after running, when running:

sharing

### CODE REVIEW

**Comment by bcjordan** [comment]
~~TODO: update & test hourOfCodeFinish.feature to press Finish button~~

**Comment by Bjvanminnen** [comment]
lgtm

**Comment by bcjordan** [comment]
UI test passed with finish click addition locally.

**Comment by bcjordan** [comment]
@philbogle this change is for HoC requested by Alice and would be good to have in for bash today @ 4:30. Can you please sign off?

**Comment by philbogle** [comment]
LGTM

**Pull request merged**
