### PR TITLE
Added taglib-ruby gem in Gemfile

### PR DESCRIPTION
**Pull request by kimj42**
In order to run generateSoundMetadata.rb in tools/scripts, taglib-ruby had to be gem installed. However, even after `gem install taglib-ruby`, it had to be manually written in the Gemfile to be added in order to make the file run to generate the JSON for the new sound files.

Unsure whether this should be permanently added to our Gemfile or since it's for a specific case of creating JSON for new sound files, it might not be worth adding it to the Gemfile because it looks like we might not be updating the sound library that often.

### CODE REVIEW

**Comment by joshlory** [comment]
Can we add it under group: development so it's only included on dev environments?

https://github.com/code-dot-org/code-dot-org/blob/53bb5a862e23d4e0301922bf8699f92f661dafb8/Gemfile#L62-L67

**Review by islemaster — APPROVED** [review]
Looks good besides Josh's request, above.

**Comment by kimj42** [comment]
Ok! I'll add it to the group:development then push again to this branch.

**Comment by kimj42** [comment]
Spoke to JoshL and ErinP in person about drone failure when attempting to install taglib-ruby. Investigated why: taglib-ruby requires bundler version to be greater than 1.2 and the current bundler version is 1.17 as shown below. So we will close this PR. 

Instructions on generateSoundMetadata.rb writes that in order to run the script one must install taglib-ruby so that should be sufficient enough rather than merging this into staging.

Screen Shot 2019-04-03 at 11 49 57 AM
Screen Shot 2019-04-03 at 11 50 32 AM

**Pull request closed without merging**
