### PR TITLE
Add missing require (optparse).

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
No problem. Unfortunately, it isn't clear to me why this bug took until now to surface.

**Comment by joshlory** [comment]
Unfortunately I still repro after pulling the latest `bin/dotd` script:
```
Follow the prompts given by the content-push script.
  If you need to do something fancier (or if the changed files do not
  "look ok" when it asks you), log in to staging and hand-craft the commit.
levelbuilder/bin/content-push:65:in `<main>': uninitialized constant OptionParser (NameError)
Connection to ip-10-0-0-225.ec2.internal closed.
Connection to gateway.code.org closed.

Uh-oh!  It looks like the levelbuilder-staging content push failed!
```

**Comment by ashercodeorg** [comment]
Hmm. Looking at our `Gemfile`, I'm not seeing [`OptionParser`](https://rubygems.org/gems/OptionParser/versions/0.5.1) there as I'd expect. Do we think this could be the next issue?

**Comment by ashercodeorg** [comment]
Right, I would expect this to be the case until the `bin/content-push` file on levelbuilder is updated to receive this change.

**Comment by ashercodeorg** [comment]
That step now appears to work fine in the DOTD script (the fix having reached levelbuilder).

Again, not sure what changed to cause this issue to manifest itself. Nor do I think such investigation is worth the time.

**Pull request merged**
