### PR TITLE
Swap teacher homepage banner to curriculum launch banner

### PR DESCRIPTION
**Pull request by bethanyaconnor**
This updates the teacher homepage to show the curriculum launch banner once the DCDO flag is flipped. Unfortunately, it will take down the LMS banner once it hits production.

I'll merge this PR sometime on Thursday July 11, which will get it deployed either on Thursday or Friday.

### CODE REVIEW

**Review by TurnerRiley — APPROVED** [review]

**Review by TurnerRiley — APPROVED** [review]
This looks good! Kelby mentioned it being good to keep images under 200KB if possible in the [pegasus doc](https://docs.google.com/document/d/1wev8I2BQVViNXPuhLEXMpIAYSoAJb0kVoSRKaI3zEAk/edit#heading=h.7nd9103f9znl). Not sure if that's really necessary here since it's pretty close but wondering if that seems worth a change? I'm good either way!

**Comment by kelbyhawn** [comment]
> Kelby mentioned it being good to keep images under 200KB if possible…

This is fine!

**Review by kelbyhawn — APPROVED** [review]

**Comment by bethanyaconnor** [comment]
Good catch Turner! I struggled to get a decent quality image for this one (Moshe had to help me in the end 😅), so I'd rather keep it. But I appreciate you looking out -- I had totally missed that!

**Comment by bethanyaconnor** [comment]
As we discussed, I'm going to merge this PR now and update the link tomorrow morning when the blog post is ready.

**Pull request merged**
