### PR TITLE
Move blockly-core build output files from blockly-core/*.js to blockly-core/build-output/*.js [finishes #82150968]

### PR DESCRIPTION
**Pull request by bcjordan**
- Adjusts symlinks to account for new directory
- Change `aws/build.rake` to account for directory of files rather than specific filenames

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
blockly-core/demos
blockly-core/tests

Do we use these at all? Should we just get rid of them (I think the same question applies to blockly-core/apps

**Comment by bcjordan** [comment]
@Bjvanminnen going to remove `/demos` and `/apps` (Neil mentioned apps will be removed from google/blockly as well). Leaving `/tests`, they still work & there are a couple of utility tests in there. Would be good to eventually integrate into CI (Travis or otherwise) per https://www.pivotaltracker.com/story/show/81302250

**Comment by Bjvanminnen** [comment]
Sounds good :)

**Pull request merged**
