### PR TITLE
Logic and UI updates to new signup flow Login Type page

### PR DESCRIPTION
**Pull request by hannahbergam**
The email validation will come in a [followup PR](https://codedotorg.atlassian.net/browse/ACQ-2448) so as not to cause another merge conflict with Turner's PR. 

Here is a vid of the updates this pr covers (and the list of commits details each update):

https://github.com/user-attachments/assets/90a8a823-ccce-4e90-a096-548c8c7d4ba7

## Links

- spec: https://www.figma.com/design/88sbry7xnl1wcyrOgbgFtn/Sign-Up-Flow?node-id=4283-2014&node-type=canvas&t=L01N6swgnX309BCp-0
- jira ticket: https://codedotorg.atlassian.net/browse/ACQ-2403

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by TurnerRiley — APPROVED** [review]
LGTM! Should we have the checkmark icon for the password confirmation too?

**Comment by hannahbergam** [comment]
> LGTM! Should we have the checkmark icon for the password confirmation too?

Moshe decided against it, so I ended up taking that out!

**Comment by TurnerRiley** [comment]
> > LGTM! Should we have the checkmark icon for the password confirmation too?
> 
> Moshe decided against it, so I ended up taking that out!

Sounds good! Just wanted to check!

**Comment by moshebaricdo** [comment]
Looks so good! One tinyyy thing (I am so sorry 😭) is that the LTI container now seems to be not full width with the buttons and copy in this section. 
Screenshot 2024-09-24 at 1 25 19 PM

**Comment by hannahbergam** [comment]
> Looks so good! One tinyyy thing (I am so sorry 😭) is that the LTI container now seems to be not full width with the buttons and copy in this section. Screenshot 2024-09-24 at 1 25 19 PM

oh yuuuup good catch! I can remove those side margins- do you want a 1rem top margin? .5rem?

**Comment by hannahbergam** [comment]
> > Looks so good! One tinyyy thing (I am so sorry 😭) is that the LTI container now seems to be not full width with the buttons and copy in this section. Screenshot 2024-09-24 at 1 25 19 PM
> 
> oh yuuuup good catch! I can remove those side margins- do you want a 1rem top margin? .5rem?

We decided offline on the 1rem top margin!

**Pull request merged**
