### PR TITLE
Hound ESLint

### PR DESCRIPTION
**Pull request by islemaster**
Converts our ESLint config from JavaScript to YAML, because, [as reported here,](https://github.com/houndci/hound/issues/1106) the HoundCI service doesn't want to be executing JavaScript on their servers.  I'm preferring YAML to JSON here because you can still make comments in YAML, which I find useful in the oft-arcane world of linting configuration files.

Then, we enable use of ESLint in our Hound configuration.

Also fixes the `rake install:hooks` step which has been producing broken symlinks since @wjordan's (otherwise wonderful) refactor of our Rakefiles.  This should fix precommit linting for anyone who's been missing it.

I'm open to suggestions on how to thoroughly test HoundCI's use of ESLint here.  I suspect it only checks changed files/lines, so I may need to introduce and then reverse a bunch of spurious JavaScript changes in this PR to show that it's working.

### CODE REVIEW

**Comment by balderdash** [comment]
yml seem fine to me, but looks like hound had an error parsing the config.

**Comment by islemaster** [comment]
:rage: What I would give for more error output.

**Comment by islemaster** [comment]
My suspicion is that Hound is using ESLint [1.10.3](https://github.com/eslint/eslint/releases/tag/v1.10.3) right now.  I downgraded ESLint locally and was able to track down a set of rules we're using that were introduced in ESLint 2.0.0, but even after replacing those with their now-deprecated versions I'm getting lots of errors about `<` not expected in JSX files.  I suspect this hasn't been an issue under ESLint 2.x thanks to the [Autoconfig for JSX fix](https://github.com/eslint/eslint/issues/5511) released with [2.5.0](https://github.com/eslint/eslint/releases/tag/v2.5.0).  It looks like I need to also install babel-eslint and use it as the eslint parser?  Trying that...

**Comment by islemaster** [comment]
Hey, that works!  Now, the real question: Is it worth downgrading from 2.8.0 to 1.10.3 to have Hound lint our JavaScript (instead of our CircleCI build)?  @bcjordan @bjvanminnen @joshlory @davidsbailey @Hamms opinions?

I'll extract the `rake install:hooks` fix and submit it as a separate PR while we discuss.

**Comment by bcjordan** [comment]
No objection from me, sounds like Hound will give the feedback faster than Circle would 👍

**Comment by islemaster** [comment]
I will say, an ugly downside of this downgrade is that [ESLint's documentation](http://eslint.org/docs/rules/) is not versioned and mostly reflects the latest 2.x version (though it does call out which version each rule is supported in if you look at the bottom of the details page for the rule).  It makes updating and discussing our linting rules more difficult.  There's also a [Migrating to 2.0.0](http://eslint.org/docs/user-guide/migrating-to-2.0.0) guide, which I suppose might help if you can read it 'backwards'... but overall, docs for 1.x are pretty thin.

**Comment by islemaster** [comment]
But the benefits are catching JS linting errors very fast, with inline PR comments, and we can eliminate the 40-second `rake lint:javascript` step that we recently added to the Circle build.

**Comment by Hamms** [comment]
Migrating backwards an entire major version number does seem pretty extreme. This would mean we'd all have to downgrade eslint locally as well?

**Comment by islemaster** [comment]
Yeah, I'd recommend a local downgrade to stay consistent with our CI behavior.  `npm install` each for apps and code-studio will do it.

**Comment by joshlory** [comment]
Does Hound have a timeline for upgrading to ESLint 2?

**Comment by islemaster** [comment]
Somebody [opened an issue to that effect](https://github.com/houndci/eslint/issues/18) back on Feb. 13 but there hasn't been any movement in that direction that I can see.  I'm not sure there's an existing migration story for them, which may slow them down - projects that are using ESLint 1 on their service would be likely to encounter problems if they just switched to ESLint 2.

**Comment by islemaster** [comment]
Thanks for the feedback everyone.  There's actually been progress on Hound supporting ESLint 2 this week, so going to hold this and keep an eye on it.

**Comment by islemaster** [comment]
Hey all!  It looks like HoundCI may now support ESLint 2.x!
- https://github.com/houndci/eslint/issues/18
- https://github.com/houndci/eslint/pull/25

I'm really tempted to give this another shot now, although my upcoming week is going to be busy.  Anyone else interested enough it this to give it a try?

**Pull request closed without merging**
