### PR TITLE
hoc2021: Notes for new tutorials

### PR DESCRIPTION
**Pull request by breville**
This adds notes for the new Poem Art and Hello World tutorials.

### CODE REVIEW

**Review by KylieModen — APPROVED** [review]
Thanks Brendan, LGTM

**Review by maddiedierker — APPROVED** [review]
what was the process for generating these notes? was it documented somewhere, or do we need to document this?

**Comment by KylieModen** [comment]
> Thanks Brendan, LGTM



> what was the process for generating these notes? was it documented somewhere, or do we need to document this?

Not sure if there is a better process. Here was what I did:  first, going to the You Tube videos and copying the Transcripts from each and pasting into a Google Doc fixing any formatting issues. Then, going through the video and taking high quality screenshots of the relevant sections of the video we wanted to include in the notes, and then taking those images and chunking the transcript to align with the screenshots. Lastly, formatting all the image names and text so that is would be easy to copy/paste. Doc for reference https://docs.google.com/document/d/1y-OyPnVdKZO3cDAXCJvYn_HNWDkxOBnD0beyibaEqoA/edit#heading=h.8xx5mzd7az66

**Comment by breville** [comment]
> what was the process for generating these notes? was it documented somewhere, or do we need to document this?

For my part, I then took the files and renamed them to match the scheme in the directory.  I also resized them to a sensible size for large retina displays and converted them to JPEGs; since these are a fallback from video, I didn't want them to be too big for users with limited connectivity. I then pasted the text into the YML, fixing additional formatting issues if I noticed any.  The per-video YML keys (e.g. `hello_world_intro`) match the URL hit when loading the level (e.g. `https://studio.code.org/notes/hello_world_intro`).  

I can create a doc capturing this.

**Comment by breville** [comment]
> I can create a doc capturing this.

I found an [existing document](https://docs.google.com/document/d/1bDSDCLVsukU1OTVIm8qXImA5czechg4TSKufeRSMy9k/edit#heading=h.ljlcjsoxmuxz) and added a new section at the end with these two notes.

**Pull request merged**
