### PR TITLE
Pegasus fallback video player: upgrade & use Flash

### PR DESCRIPTION
**Pull request by breville**
- Adds Flash player
- Prefers Flash player which makes IE9-Edge work again
- Upgrades videojs from 5.4.6->5.6.0
- Cleans up preload attribute in video tag.  (We use preload=none to avoid preloading lots of video files.)

### CODE REVIEW

**Comment by wjordan** [comment]
Could you provide more context on what was broken and how this PR fixes them? Is this a followup fix to a recent change, or an update to address long-standing issues?

If I recall, dashboard was locked to an older version of videojs 4.x, because of known issues with the 5.x branch. It would be nice to keep our versions in sync to reduce the complexity of browser-specific issues that may appear in one and not the other.

If we've tested this version exhaustively across our full browser-support matrix, then we will want to update dashboard to match. If we haven't done exhaustive testing, we should plan to do so (or stick to the version used in dashboard, which has been fully tested).

**Comment by wjordan** [comment]
Aside from the broader questions in my previous comment, prioritizing the Flash player over html5 is the same approach we're using in Dashboard (likely to workaround similar issues), so that specific change lgtm.

**Comment by breville** [comment]
Pegasus has been using 5.4.6 since it got the fallback player back in January (https://github.com/code-dot-org/code-dot-org/pull/5776).  

This change is primarily about defaulting to the flash player, but I thought I'd upgrade video.js too.  What I propose now is upgrading this PR to the very latest - 5.10.2 - testing it on our browser matrix for Pegasus, letting it run for a week or two, and if that goes well, then we can upgrade dashboard after that.  Seem reasonable?

**Comment by wjordan** [comment]
:+1: sounds like a good plan to me. It would be excellent if we could manage to get the very latest (5.x) video.js working reliably across browsers again.

**Comment by breville** [comment]
Closing.  Finally revisiting an update in https://github.com/code-dot-org/code-dot-org/pull/32806.

**Pull request closed without merging**
