### PR TITLE
Don't cache scripts unless classes are cached too

### PR DESCRIPTION
**Pull request by balderdash**
Class reloading breaks our script cache, since we hold references to instances of the old classes while the rest of the application starts using the new versions. This leads to weird errors like [`Invalid single-table inheritance type: FreeResponse is not a subclass of Level`](https://app.honeybadger.io/projects/3240/faults/34140694#notice-summary), even though it totally is >:(

This will disable the script cache on staging and dev environments (devs who had `levelbuilder_mode: true` won't see a difference). Prod has class caching enabled, while levelbuilder and test have the script cache disabled for other reasons.

### CODE REVIEW

**Comment by balderdash** [comment]
One concern with this approach is that prod will now be the only environment with the script cache enabled, so it might be harder to notice bugs in that code.

We could instead force a script cache reload whenever classes are reloaded, but I couldn't figure out how to do that.

**Comment by Bjvanminnen** [comment]
My initial reaction is that having prod be the only env where this caching is enabled is kind of scary.

Also, if we're doing this for Script should we also be doing it for Course?

**Comment by balderdash** [comment]
Yeah, it should apply to the course cache as well.

Also I lied, the script cache is enabled on test, just not when it's running the dashboard unit tests. UI/eyes tests and otherwise browsing around test.code.org happen with the script cache enabled. (I assumed `ENV['CI']` was set on test, but that's only on circle.)

**Comment by Bjvanminnen** [comment]
okay, that sounds less scary

**Pull request merged**
