### PR TITLE
Simplify root README.md

### PR DESCRIPTION
**Pull request by islemaster**
I promised to do a pass on our root README a long time ago.  Finally, here it is.

The diff on this is terrible, so here's a side-by-side view.  Left is before, right is after.

readme_diff_1024

Note, I moved the apps-build sets to SETUP.md.

### CODE REVIEW

**Comment by islemaster** [comment]
Please discuss in depth.  I think this is a major improvement because:
- It moves setup/build/run instructions to the top.
- It's a little bit shorter
- It manages to express a lot more information about our repository structure
- It tears out quite a bit of outdated or redundant information about building and running our app (which should be in SETUP.md anyway)

**Comment by philbogle** [comment]
This looks really good to me; I think it's strictly an improvement.

**Comment by ashercodeorg** [comment]
Thanks for doing this! And thanks for including the visual diff!

**Comment by bcjordan** [comment]
Looks great, much improved experience for newcomers :+1: :+1: — thanks for doing this!

**Pull request merged**
