### PR TITLE
Part 1: Remove unminify plugin

### PR DESCRIPTION
**Pull request by davidsbailey**
### Background

See [webpack content hashing design doc](https://docs.google.com/document/d/1vJ3EpaT8ch6UMLP21IovZIgOzS-QhU4G1kv3azZPmZo/edit#)

This PR performs further simplification in advance of moving js content hashing into webpack.

Today, we use `UnminifiedWebpackPlugin` because there are two assets which we pass through webpack and want to use unminified copies of in production. The current solution is to include unminified copies of _all_ js files produced by webpack, and then let the application decide whether to request the minified or unminified asset.

All of this is fine, except that `UnminifiedWebpackPlugin` and `WebpackManifestPlugin` do not play nicely and produce the following undesirable manifest format:
```
{ 
  "cookieBanner.js": "/assets/js/cookieBanner.d90978a8439431440869.min.js",
  "cookieBanner.d90978a8439431440869.js": "/assets/js/cookieBanner.d90978a8439431440869.js",
}
```
Rather than try to fix the manifest output, I'm taking this opportunity to eliminate unnecessary duplication of assets in our apps package.

### Description
* stop providing unminified copies of all webpack js assets
* exclude `blockly.js` and `brambleHost.js` file contents from minification (though their filenames will still contain `min`)
* use `minifiable_asset_path` to access all webpack js assets including webpack-runtime.js

In production mode this gives a single, useful entry in the manifest for each asset:
```
{ 
  "cookieBanner.js": "/assets/js/cookieBanner.d90978a8439431440869.min.js"
}
```
(note that the work to turn on manifests and filename hashing is not included in this PR)

### Testing

There are 3 things I am aware of to pay special attention to in testing this change:
* blockly levels, which depend on blockly.js
* weblab levels, which depend on brambleHost.js
* applab/gamelab exporters, which use some conditional logic when deciding where to find webpack-runtime.js: https://github.com/code-dot-org/code-dot-org/blob/ef180fdd7bc08bdf3bfe1a029b176de21a63b879/apps/src/util/exporter.js#L280-L284

All 3 of these features have sufficient UI test coverage. The passing drone run indicates that these features are working properly in development mode. The test machine will verify that these are working properly in production mode. 

I have manually verified that blockly and weblab levels are still working after doing a production build locally, and inspection of the exporter code above suggests that it should be resilient as long as one copy (minified or unminified) of webpack-runtime exists in the package.

### CODE REVIEW

**Comment by islemaster** [comment]
Just a heads-up, I'm probably not going to get through this review until tomorrow morning.

**Comment by davidsbailey** [comment]
That's fine. Let's check in tomorrow before you review -- there is a chance I will no longer want to head in this direction.

**Comment by davidsbailey** [comment]
Hey Brad, Good news, I think we do want to head in this direction. However, I'd rather send you this PR plus the following one together next week so that if there's any question about the direction we can discuss both steps together. So I'll un-assign you for now and re-request next week.

**Comment by davidsbailey** [comment]
Hi Brad, this is ready for review. Please find the link to the design doc in the updated description, which also links to future PRs in the sequence.

**Review by islemaster — APPROVED** [review]
:+1:

**Pull request merged**
