### PR TITLE
[WIP] Add PR comment when Applitools merge fails

### PR DESCRIPTION
**Pull request by bcjordan**

### CODE REVIEW

**Comment by bcjordan** [comment]
`result = client.add_comment('code-dot-org/code-dot-org', 10424, 'Testing!')`

Testing!

**Comment by bcjordan** [comment]
`result = client.add_comment('code-dot-org/code-dot-org', 10424, 'I am a comment\n\nwith newlines')`

I am a comment\n\nwith newlines

**Comment by bcjordan** [comment]
`result = client.add_comment('code-dot-org/code-dot-org', 10424, "I am a comment\n\nwith newlines")`

I am a comment

with newlines

**Comment by bcjordan** [comment]
Emoji :hooray:

**Comment by bcjordan** [comment]
`result = client.add_comment('code-dot-org/code-dot-org', 10424, "Emoji :tada:")`

Emoji :tada:

**Comment by bcjordan** [comment]
`result = client.add_comment('code-dot-org/code-dot-org', 10424, "Image ")`

Image

**Comment by bcjordan** [comment]
`result = client.add_comment('code-dot-org/code-dot-org', 10424, "[Link](https://code.org] and image with link [](https://google.com)")`

[Link](https://code.org) and image with link [](https://google.com)

**Comment by bcjordan** [comment]
`result = client.update_comment('code-dot-org/code-dot-org', client.issue_comments('code-dot-org/code-dot-org', 10424).find{|i|i.body.include?('UPDATEHERE')}.id, "Comment to update: updated!")`

Comment to update: updated!

**Comment by bcjordan** [comment]
@bcjordan Testing comment from local. :tada:

**Comment by bcjordan** [comment]
@bcjordan ahoy! Testing comment from CircleCI. :tada:

**Comment by bcjordan** [comment]
@bcjordan @islemaster ahoy! Testing comment from CircleCI. :tada:

**Comment by bcjordan** [comment]
@bcjordan @islemaster ahoy! Testing comment from CircleCI. :tada:

**Comment by bcjordan** [comment]
@bcjordan @islemaster ahoy! Testing comment from CircleCI. :tada:

**Comment by bcjordan** [comment]
@bcjordan @islemaster ahoy! Testing comment from CircleCI. :tada:

**Comment by islemaster** [comment]
This is a very cool experiment that's now outdated in our system.  Closing this PR, but FYI @sureshc and @uponthesun about this potential future Applitools-related work. (Best case? They write it for us and we just install an integration!)

**Pull request closed without merging**
