### PR TITLE
Fix bug so workshop admins who are also facilitators can see all facilitator survey results

### PR DESCRIPTION
**Pull request by aoby**
and add tests

### CODE REVIEW

**Comment by aoby** [comment]
I extracted the namespace as a module in the test which indented most of the file and makes for a noisy diff. View with [whitespace changes hidden](https://github.com/code-dot-org/code-dot-org/pull/25253/files?utf8=%E2%9C%93&diff=split&w=1) for easier review:
image

**Comment by aoby** [comment]
[Workshop Admins who are also facilitators should be able to see all facilitator results](https://trello.com/c/Fgg7jvSl/747-workshop-admins-who-are-also-facilitators-should-be-able-to-see-all-facilitator-results)

**Comment by tanyaparker** [comment]
Would this also fix it for a program manager who is also a facilitator?

**Comment by aoby** [comment]
Yes, and a workshop organizer. In fact that part was already done. Only workshop admin was missing.

Now, it works like this:
 1. Is the user any of: workshop admin, organizer, program manager? Show all results
 2. Is the user a facilitator? Show their results only
 3. raise an error for unexpected user type (honeybadger)

**Comment by tanyaparker** [comment]
Yay! Thanks!

**Pull request merged**
