### PR TITLE
prune courses from ui test seeding

### PR DESCRIPTION
**Pull request by davidsbailey**
best-effort attempt to prune the courses/scripts needed for UI testing, which are seeded in drone, test, and adhoc. this should speed up seeding in those environments, though I haven't measured by exactly how much. unfortunately, the new script seeding does not appear to be fast enough to simply seed all scripts in every environment, so as long as we are stuck with this approach it seems better to minimize the number of scripts seeded.

## Testing story

because these objects are seeded only for testing, the fact that existing test coverage is passing on drone is a good indication that nothing is broken.

### CODE REVIEW

**Review by bethanyaconnor — APPROVED** [review]
Do we expect any eyes diffs related to this change?

**Comment by davidsbailey** [comment]
> Do we expect any eyes diffs related to this change?

ooh, yes! adding the level to allthethings will result in many eyes changes. it should just add a bubble in each case, which shouldn't be too alarming for the dev of the day.

**Comment by dmcavoy** [comment]
> > Do we expect any eyes diffs related to this change?
> 
> ooh, yes! adding the level to allthethings will result in many eyes changes. it should just add a bubble in each case, which shouldn't be too alarming for the dev of the day.

Won't changing some of the eyes tests from CSP 17/18 to 2019 cause diffs too? Since those courses are different

**Review by dmcavoy — APPROVED** [review]

**Comment by dmcavoy** [comment]
It seems like maybe we should do a pass to see if we should be updating tests that are using older versions of the curriculum should be updated to the current year? Then we have more insight into if anything breaks for our main use case?

**Comment by davidsbailey** [comment]
> It seems like maybe we should do a pass to see if we should be updating tests that are using older versions of the curriculum should be updated to the current year? Then we have more insight into if anything breaks for our main use case?

that is interesting, it seems like there are a few potentially different goals here  -- one goal I had in mind was to make it so that our UI tests do not depend on what the current version year is, so that we do not have to update our UI tests each year. otherwise, I don't see how we'll get out of the pattern of adding all the new courses to this list each year.

one way to frame it would be, what other steps would we have to take to convince ourselves that our logic for course versions is working well enough that what we see on levelbuilder is what we'll get in production?

**Comment by dmcavoy** [comment]
> > It seems like maybe we should do a pass to see if we should be updating tests that are using older versions of the curriculum should be updated to the current year? Then we have more insight into if anything breaks for our main use case?
> 
> that is interesting, it seems like there are a few potentially different goals here -- one goal I had in mind was to make it so that our UI tests do not depend on what the current version year is, so that we do not have to update our UI tests each year. otherwise, I don't see how we'll get out of the pattern of adding all the new courses to this list each year.
> 
> one way to frame it would be, what other steps would we have to take to convince ourselves that our logic for course versions is working well enough that what we see on levelbuilder is what we'll get in production?

A couple things I could see wanting out of these tests:

* Making sure that older versions of the curriculum are not broken by changes we make
* Making sure that new features of the curriculum which are not used in the old version are being tested in the ui tests

I do agree it would be nice to not have to update these tests every year to the new year but I do also see some value in having some eyes tests on our most used courses

**Comment by davidsbailey** [comment]
> A couple things I could see wanting out of these tests:
> 
> * Making sure that older versions of the curriculum are not broken by changes we make
> * Making sure that new features of the curriculum which are not used in the old version are being tested in the ui tests

These are good goals. In theory, old and new features of the curriculum could all be covered by UI tests on allthethings (or other allthe*things) scripts. Maybe we can discuss at standup what the limitations are of not directly testing the latest version year in our UI tests? I don't mind holding this PR open until then.

This is a tough issue... in theory, we should be treating curriculum content as just content, and test on test data the same way that we don't use production data when we test e.g. regional partners and workshops in our PLC tests, or the same way that we don't test against real users / progress / sections (including some very large sections) in our LP tests. however, curriculum content for our main courses seems important enough that we keep wanting the security of testing against the actual content in order to convince ourselves it is really working.

> I do agree it would be nice to not have to update these tests every year to the new year but I do also see some value in having some eyes tests on our most used courses

**Comment by dmcavoy** [comment]
> These are good goals. In theory, old and new features of the curriculum could all be covered by UI tests on allthethings (or other allthe*things) scripts. Maybe we can discuss at standup what the limitations are of not directly testing the latest version year in our UI tests? I don't mind holding this PR open until then.

I don't think we need to block this PR on this conversation. I do think its good for us to have a conversation about this though well we are thinking about it.

**Comment by davidsbailey** [comment]
sounds good, I made a note to discuss at standup tomorrow.

**Pull request merged**
