### PR TITLE
Beyond gsheet: fix a long description

### PR DESCRIPTION
**Pull request by breville**
A newly-added shortdescription_s in https://github.com/code-dot-org/code-dot-org/commit/194f9618ab116351e66ef38f09bb47d699eaf05f#diff-77162d3dcb224dc3d6ceeeb2d20c2cd2 was too long for some environments, and so it's been reverted for now.

### CODE REVIEW

**Review by islemaster — APPROVED** [review]
:+1: Do we also need to update the source gsheet so it doesn't get scooped right away?

**Comment by breville** [comment]
Oops, you're right.  I'll just fix the gsheet and scoop that instead.

**Comment by breville** [comment]
Well, actually, the next scoop won't happen until tomorrow noon, and it should be fixed by then.  So maybe this will do the job for now.

**Comment by breville** [comment]
I removed it from the gsheet and scooped it so that we have a good source of truth there.

**Pull request closed without merging**
