### PR TITLE
Add Microsoft Clarity heatmap tracking code to page header

### PR DESCRIPTION
**Pull request by etaderhold**
This adds code to the page header needed for Microsoft Clarity heatmap tracking analytics. 

## Links

- [JIRA](https://codedotorg.atlassian.net/browse/TEACH-812)

## Testing story

Tested locally, supplied function shows up in the header as requested.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by lfryemason — COMMENTED** [review]
@dju90 this will add clarity to every page on the site. Is this what you expected?

Do we have approval from infra security and other teams? Just want to make sure we are ready to enable this everywhere.

Otherwise this looks good

**Comment by dju90** [comment]
> @dju90 this will add clarity to every page on the site. Is this what you expected?
> 
> Do we have approval from infra security and other teams? Just want to make sure we are ready to enable this everywhere.
> 
> Otherwise this looks good

Hmm, no, I was initially thinking we would just add it to the teacher dashboard. But let me think about this and consult with those other teams too. I guess it wouldn't be the worst to have heatmap data for other pages, but I'm concerned about potential performance issues. Please hold on merging for now...

**Comment by dju90** [comment]
From https://learn.microsoft.com/en-us/clarity/faq:
> Will Clarity reduce my site's performance?
> No, not at all. Visitors to your site notice no change in site speed or performance. The Clarity JavaScript is asynchronous, it doesn't affect how quickly a website loads.

More details on https://clarity.microsoft.com/blog/does-clarity-affect-website-performance/
> In clarity, the number decreases to ~300 [bytes] after the script is downloaded for the first time (~26,000 bytes) in a day and stays the same for the entire day (the script gets cached in the browser for 1 day and needs to be downloaded again after that.)

**Comment by dju90** [comment]
Slack thread engaging infrastructure: https://codedotorg.slack.com/archives/C03CK49G9/p1705431215662299

**Comment by dju90** [comment]
We've gotten a "no" from Legal on using Clarity. Unfortunately, let's close this PR for now.

**Pull request closed without merging**
