### PR TITLE
hide setAttribute from autocomplete

### PR DESCRIPTION
**Pull request by davidsbailey**

### CODE REVIEW

**Comment by joshlory** [comment]
Also hide `getAttribute`?

**Comment by davidsbailey** [comment]
That would be nice, however it looks like people are legitimately using getAttribute, most notably to get the dimensions of images and canvases. So, I wouldn't want to hide it unless we had another way in mind to provide that functionality like we do with setAttribute.

**Comment by joshlory** [comment]
It feels a little weird to have the asymmetry of exposing `getAttribute` but not `setAttribute`.  My vote would be to keep both (with a whitelisted set of attributes) or neither, but it's a curriculum decision.

**Comment by Bjvanminnen** [comment]
I guess a more consistent world would be one in which we also had a getProperty (which does make some amount of sense if we have setProperty)?

**Comment by davidsbailey** [comment]
I like replacing getAttribute with getProperty. this is now https://www.pivotaltracker.com/story/show/117867241

**Pull request closed without merging**
