### PR TITLE
Skip `npm install` if we detect that npm is already installed.

### PR DESCRIPTION
**Pull request by islemaster**
@wjordan Does this seem like an appropriate/safe change to our `rake install` task?  Right now this step always breaks for me because I'm using nvm to manage my node/npm versions.  I've been manually disabling this step when I want to install, but wondered if there's any reason not do skip it automatically in my case?

### CODE REVIEW

**Comment by wjordan** [comment]
Last I checked we never used to install npm in this rake task, let me trace this backwards to make sure I understand what's going on and why this install script has drifted in this fashion, and to make sure this change is what we actually want.

Long-term I really hope to stop continuing to spend so much of our energy massaging this Rakefile across all of our various local-workstation edge-cases, and instead focus efforts on moving to a fully Chef-managed configuration. But that won't happen for a while.

**Comment by wjordan** [comment]
It looks like the `sudo apt-get install -y nodejs npm` command was added by #4525, and the `sudo npm install -g` command by #4539 + #4553. These were added while I was out two weeks ago so I never reviewed them, and need to be corrected.

The `which npm` check as proposed won't allow this script to update to the correct npm version in the future, which is behavior I imagine we want to maintain here. Instead, I suggest these fixes:
- The `sudo nodejs install` command was an unnecessary addition (the `cdo-nodejs` recipe already handles this for provisioned servers, and it's in our README.md setup instructions for local workstations), so it should be removed.
- The `sudo npm install -g` command should be changed to retain compatibility with non-root node installations. It seems this was modified from `RakeUtils.npm_update_g` in order to be able to pin to a specific version, rather than `@latest`, so perhaps we can add another function to `RakeUtils` like:

```
  # Updates global npm package if it's outdated
  def self.npm_pin_g(package, version)
    # cf. http://stackoverflow.com/a/33426237/5505247
    output = `npm ll -pg --depth=0 #{package} | grep -o "@.*:" | sed 's/.$//; s/^.//'`.strip
    RakeUtils.sudo 'npm', 'install', '--quiet', '-g', "#{package}@#{version}" unless output == version
  end
```

Just a thought, would love to hear other suggestions.

**Comment by wjordan** [comment]
More brainstorming/prototyping, I sketched out this replacement `npm_install_g` method a couple months ago to help support non-root npm installations (YMMV):

```
  # Installs list of global npm packages if not already installed
  def self.npm_install_g(*args)
    output = `npm list --global --parseable --long --depth=0 #{args.join ' '} 2>/dev/null`.strip
    if output.empty?
      install_args = 'npm', 'install', '--quiet', '-g', *args
      File.writable?("#{`npm config get prefix`.chomp}/lib/node_modules") ?
        system(*install_args) :
        sudo(*install_args)
    end
  end
```

**Comment by wjordan** [comment]
@islemaster shall we just get this one-line fix merged in for now, putting off any more complicated changes for later? I think the current commit is fine as a workaround for now (at least until we need to update npm in the future, which won't happen very often anyway), and is definitely better than leaving as-is for any longer.

**Comment by islemaster** [comment]
@wjordan I don't want this to introduce issues; it sounds like the root cause here is way, way deeper than what I'm addressing.  If you're okay with this one-liner I'll happily merge it and stop messing with my local Rakefile.

**Pull request merged**
