### PR TITLE
Css for download button

### PR DESCRIPTION
**Pull request by caleybrock**
screen shot 2015-10-16 at 2 26 04 pm
screen shot 2015-10-16 at 2 26 13 pm

### CODE REVIEW

**Comment by tanyaparker** [comment]
Can we also make it's font size 15px? Aside from the 2 highlighted numbers, the rest of the text is 15px. I feel like we should also make the 3.6x white and leave just the footer text grey.

**Comment by caleybrock** [comment]
updated

**Comment by caleybrock** [comment]
screen shot 2015-10-16 at 3 02 53 pm
I don't mind the other text being a bit lighter, but let me know if you feel strongly

**Comment by tanyaparker** [comment]
Nah lgtm

**Pull request merged**
