### PR TITLE
Add script property to indicate maker unit

### PR DESCRIPTION
**Pull request by bethanyaconnor**
As part of fully moving onto course offering/version, I would like to remove family names from all scripts that are not in a unit group for a few reasons:
- The family name of scripts within unit groups is not currently editable on the script overview page so it's effectively a hidden field
- Family names of scripts within unit groups are not reflected in the CourseOffering table, blocking us from using that table as the source of truth for family names
- Eventually, all scripts will be in unit groups and should not have family names at all

Maker units are hard-coded to have the family name `csd6`. This PR moves that over to a boolean `is_maker_unit` and updates all scripts with the family_name `csd6` to set that boolean to true.

Screenshot of the new checkbox on the script edit page:
Screen Shot 2021-06-24 at 1 18 51 PM

## Testing story

This doesn't change much existing behavior. I update a couple unit tests and manually tested setting the field.

## Follow-up work

- Adding a new route to find the latest maker unit for a user to replace `/s/csd6`
- Replacing that route on any current pages in a follow-up PR. I will add a redirect if possible
- Removing `family_name` from all scripts that are in a unit group

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
I can't decide if I like `is_maker_unit` as a long-term solution, but it definitely seems like a big step in the right direction because it takes away the ability for any other units within unit groups to use the family name to do redirections.

before you actually take away those redirections for other units in courses, I owe you a link to an old PR where I captured some context about what kinds of incoming links we need to make sure to keep supporting in order to not break our users.

**Comment by davidsbailey** [comment]
@bethanyaconnor I believe https://github.com/code-dot-org/code-dot-org/pull/35489 has all the context. It looks like we still want "deep" links to behave as follows:
* https://studio.code.org/s/csp1/stage/3/puzzle/4 -->  https://studio.code.org/s/csp1-2019/stage/3/puzzle/4

However, in the spirit of deprecation, you could consider breaking these links. In that case, it could be worth rerunning some of the queries in the [gsheet](https://docs.google.com/spreadsheets/d/1ZD_lW4aHRcIu8p1hMKFh5FYIngVECvsggilsXPg6mWc/edit) to see how much traffic we're still getting on them and then making a judgment call.

I'm not sure which of all this you need to do in order to make progress on the course version stuff, but I'm providing this info in case you do need to break these links to make progress.

**Review by epeach — APPROVED** [review]
Looks good to me! I like that this moves us towards a future where the Maker Toolkit is decoupled from Unit 6.

**Comment by bethanyaconnor** [comment]
I'm going to move the conversation about version redirects to Slack but I did rerun the queries from that spreadsheet (2021 version [here](https://docs.google.com/spreadsheets/d/1_FxGEENz4CUYgTWrkemaGL1MhI0FfHgxzu5Hb3pkyjM/edit#gid=542809038)) and tl;dr the numbers look pretty similar

**Pull request merged**
