### PR TITLE
Update applab urls to use https urls

### PR DESCRIPTION
**Pull request by sfilman**
The playSound, image, and setImageUrl blocks don't work by default right now because they have HTTP urls. I just added an 's' to the image blocks, as it was already the Code.org logo and could be served over HTTPS. The playSound example we were using didn't work with HTTPS so I picked a sound from the blockly sounds.

@davidsbailey can you take a look and let me know if it looks good to merge?

### CODE REVIEW

**Comment by davidsbailey** [comment]
Hi Sarah, I think we want these URLs all to look like "//code.org/images/logo.png". This inherits the protocol (http or https) from the page that is hosting the link.

**Comment by sfilman** [comment]
Talked to @davidsbailey offline, these urls are student facing, so we're going to show the whole URL.

**Comment by davidsbailey** [comment]
:+1:

**Comment by davidsbailey** [comment]
@sfilman , I merged this to staging for ya. tests passed and it appears to work:

screen shot 2015-07-13 at 1 47 37 pm

Want to take a look on staging, and make sure all the cases you care about are working?

**Pull request merged**
