### PR TITLE
I18n sync Down & Out 09/24

### PR DESCRIPTION
**Pull request by deploy-code-org**

### CODE REVIEW

**Review by nkiruka — APPROVED** [review]

**Comment by bethanyaconnor** [comment]
@nkiruka were you expecting this sync to add those blockly strings?

**Comment by nkiruka** [comment]
I am expecting the strings to be part of the sync but I am not sure why they are not.  @Hamms Any ideas?

**Comment by Hamms** [comment]
Which blockly strings?

**Comment by nkiruka** [comment]
@Hamms This string:
https://github.com/code-dot-org/code-dot-org/pull/30871/files#diff-6f99c06ee05ddc419704e1a3394f94a7R44

**Comment by Hamms** [comment]
Oh! New Blockly strings actually have to be added to the _blockly_ repo, not to the code-dot-org repo: https://github.com/code-dot-org/code-dot-org/blob/23014ed0e09ee419e343dcde385424e777cda70f/bin/i18n-codeorg/in.sh#L44-L54

**Comment by joshlory** [comment]
Link to the Blockly repo PR: https://github.com/code-dot-org/blockly/pull/190

**Pull request merged**
