### PR TITLE
Revert "Revert "Remove prettier""

### PR DESCRIPTION
**Pull request by megcrenshaw**
Reverts code-dot-org/code-dot-org#47763

### CODE REVIEW

**Review by mikeharv — APPROVED** [review]
Amazing work Meg!

**Comment by maddiedierker** [comment]
linting succeeded on the unit test container, so you're good to merge this! 🚀 after this is merged, we should let folks know to merge staging into any branches they're working on and run `yarn lint` just for good measure

**Comment by megcrenshaw** [comment]
> linting succeeded on the unit test container, so you're good to merge this! 🚀 after this is merged, we should let folks know to merge staging into any branches they're working on and run `yarn lint` just for good measure

Excellent! Should we wait until this succeeds for the message to everyone?

**Comment by maddiedierker** [comment]
> Should we wait until this succeeds for the message to everyone?

yeah, that's probably a good idea. @mikeharv we should wait to open staging until a staging build has succeeded with this change, too

**Pull request merged**
