### PR TITLE
Disable activities table writes.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This seems to be the minimal viable mechanism to disable writes to `activities`. Much further work is both planned and necessary to dismantle the `activities` framework. 

**BEFORE MERGING**: Determine whether we want to log some subset of `activities` somewhere.

For keeping track of such work and providing a centralized place for references to it, this PR will be used as a "root" node. Amongst the work items remaining to be done...
* [ ] Remove the associated queue.
* [ ] Transfer the logic in `ActivitiesController#milestone` elsewhere, presumably `UserLevel#milestone`.
* [ ] Update the milestone route.
* [ ] Determine whether we want to keep the `Activity` model, acting appropriately.
* [ ] Remove `ActivitiesController`.
* [ ] Update the massive number of tests to test the final state of affairs.
* [ ] Back up the data in both `activities` and `activities_old`.
* [ ] Drop `activities` and `activities_old`.

### CODE REVIEW

**Comment by jeremydstone** [comment]
Are there any potential risks/ramifications of not writing to `Activity` at this point? Are we sure we've removed all readers and this table is purely write-only?

**Comment by ashercodeorg** [comment]
There are definitely the obvious risks with not writing to `Activity`. That said, I'm as sure as I can be that all readers have been removed. There is also the obvious ramification, namely that we are not writing that data to the DB.

**Comment by ashercodeorg** [comment]
Creating the object without persisting is *definitely confusing*, something that should not be allowed to exist long-term. However, I do think that this is the safest incremental change possible, I'm striving to minimize impact should something go wrong. Hand-crafting the JSON means that a bug there would mean data loss, something I would rather decouple from turning off the writes in case some hidden dependency still exists.

And I do definitely intend to follow up with PRs that write the JSON directly rather than via a (non-persisted) `Activity` object. That said, as noted, it may be worth keeping around the `Activity` model for other reasons.

**Comment by ashercodeorg** [comment]
Closing, as the current feeling seems to be to want to keep the table (as a write-only table).

**Pull request closed without merging**
