### PR TITLE
Update rbspy from 0.3.8 to 0.17.0

### PR DESCRIPTION
**Pull request by sureshc**
We've been experiencing brief performance and availability issues during production releases that are carried out when usage is high. Experimenting with AWS Load Balancer Slow Start has not completely mitigated this issue. We execute `rbspy` for 120 seconds on 3 randomly selected Dashboard puma child (`worker`) processes during launch of web application servers in environments that utilize EC2 Auto Scaling Groups (currently on production). We're not able to use `rbspy` to investigate these performance issues because the version we currently install does not support Ruby 2.7.x:

```
~$ sudo rbspy record --silent --duration 120 --pid 5119
Press Ctrl+C to stop
thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.7.5. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:340:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Wrote raw data to /home/ubuntu/.cache/rbspy/records/rbspy-2023-05-11-D1qpyj9yH9.raw.gz
Writing formatted output to /home/ubuntu/.cache/rbspy/records/rbspy-2023-05-11-gz1hKUsWPe.flamegraph.svg
[2023-05-11T17:56:19Z ERROR inferno::flamegraph] No stack counts found
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: InvalidData, error: "No stack counts found" })', src/libcore/result.rs:1165:5
```

Update to the latest release for Linux x86 servers using the binaries published by the project.

## Testing story

We don't have any tests that ensure `rbspy` can successfully monitor our puma Rails worker processes. We only execute `rbspy` during launch of web application servers in environments that use EC2 Auto Scaling Group (currently only production), and we don't have reliable way to provision an adhoc environment that uses Auto Scaling, so provision an adhoc and verify we can execute `rbspy` from the command line with the same syntax that our automated processes utilize.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by Hamms** [comment]
> so provision an adhoc and verify we can execute rbspy from the command line with the same syntax that our automated processes utilize.

Just checking; is this the *plan* for testing, or did this actually get done?

**Review by Hamms — APPROVED** [review]
I'd like to know more about the testing story, but the change itself LGTM!

**Comment by sureshc** [comment]
@Hamms The name of the binary file unpacked from the new tar gz is `rbspy-x86_64-musl` in the latest release and not `rbspy`. Can you help me configure `ark` to symlink `/usr/local/bin/rbspy` to `/usr/local/bin/rbspy-1/rbspy-x86_64-musl`?

Do I need to tweak the `has_binaries` attribute? Or should I change our shell script to invoke this tool with the actual binary filenmame `rbspy-x86_64-musl`?

**Comment by Hamms** [comment]
I'm not actually familiar with `ark`, but the description in Overview here https://supermarket.chef.io/cookbooks/ark implies to me that it will automatically strip version information from the symlink. What specific undesirable behavior are you seeing?

**Comment by Hamms** [comment]
One option is to rather than configuring `ark`, just set the symlink up ourselves:

```ruby
link '/usr/local/bin/rbspy' do
  to '/usr/local/bin/rbspy-1/rbspy-x86_64-musl'
end
```

**Comment by sureshc** [comment]
> One option is to rather than configuring `ark`, just set the symlink up ourselves:

Thanks. Rather than trying to figure out how to configure `ark`, I just added your proposed logic to create the symlink to the new executable filename.

**Comment by sureshc** [comment]
Mostly taking notes for myself. This is the Chef debug log for the updated `rbpsy` recipe:

```
Recipe: cdo-apps::rbspy
  * ark[rbspy] action install
    * directory[/usr/local/rbspy-1] action create
      - create new directory /usr/local/rbspy-1
    * remote_file[/etc/chef/local-mode-cache/cache/rbspy-1.tar.gz] action create
      - create new file /etc/chef/local-mode-cache/cache/rbspy-1.tar.gz
      - update content in file /etc/chef/local-mode-cache/cache/rbspy-1.tar.gz from none to cf966d
      (new content is binary, diff output suppressed)
    * execute[unpack /etc/chef/local-mode-cache/cache/rbspy-1.tar.gz] action nothing (skipped due to action :nothing)
    * execute[set owner on /usr/local/rbspy-1] action nothing (skipped due to action :nothing)
    * link[/usr/local/bin/rbspy] action create
      - create symlink at /usr/local/bin/rbspy to /usr/local/rbspy-1/rbspy
    * link[/usr/local/rbspy] action create
      - create symlink at /usr/local/rbspy to /usr/local/rbspy-1
    * template[/etc/profile.d/rbspy.sh] action create (skipped due to only_if)
    * ruby_block[adding '/usr/local/rbspy-1/bin' to chef-client ENV['PATH']] action run (skipped due to only_if)
    * execute[unpack /etc/chef/local-mode-cache/cache/rbspy-1.tar.gz] action run
      - execute /bin/tar xzf /etc/chef/local-mode-cache/cache/rbspy-1.tar.gz
    * execute[set owner on /usr/local/rbspy-1] action run
      - execute chown -R root:0 /usr/local/rbspy-1

  * link[/usr/local/bin/rbspy] action create
    - unlink existing symlink to file at /usr/local/bin/rbspy
    - create symlink at /usr/local/bin/rbspy to /usr/local/bin/rbspy-1/rbspy-x86_64-musl
 ```

**Comment by sureshc** [comment]
OK. I’ve got it working!

``` shell
ubuntu@adhoc-update-rbspy-3:~$ sudo rbspy record --silent --duration 120 --pid 22116
rbspy is recording traces. Press Ctrl+C to stop.
Wrote raw data to /home/ubuntu/.cache/rbspy/2023-05-19-KrSzzxufKK.raw.gz
Wrote formatted output to /home/ubuntu/.cache/rbspy/2023-05-19-f0qKOXin8k.flamegraph.svg
```

Here’s how the recipe download, unpacked, and symlinked the files:
```
ubuntu@adhoc-update-rbspy-3:/usr/local/rbspy-1$ ls -al
total 10196
drwxr-xr-x  2 root root     4096 May 19 01:45 .
drwxr-xr-x 14 root root     4096 May 19 01:45 ..
-rwxr-xr-x  1 root root 10431352 Mar 31 12:09 rbspy-x86_64-musl
ubuntu@adhoc-update-rbspy-3:/usr/local/rbspy-1$ cd ..
ubuntu@adhoc-update-rbspy-3:/usr/local$ ls -al
total 56
drwxr-xr-x 14 root root 4096 May 19 01:45 .
drwxr-xr-x 11 root root 4096 May 19 00:08 ..
drwxr-xr-x  3 root root 4096 May 19 01:45 bin
drwxr-xr-x  2 root root 4096 Jul 22  2019 etc
drwxr-xr-x  2 root root 4096 Jul 22  2019 games
drwxr-xr-x  4 root root 4096 May 19 00:52 include
drwxr-xr-x 12 root root 4096 May 19 00:22 jemalloc-1
drwxr-xr-x  6 root root 4096 May 19 00:52 lib
lrwxrwxrwx  1 root root    9 Jul 22  2019 man -> share/man
drwxr-xr-x 13 root root 4096 May 19 00:51 nodejs-source-18.16.0
lrwxrwxrwx  1 root root   18 May 19 01:45 rbspy -> /usr/local/rbspy-1
drwxr-xr-x  2 root root 4096 May 19 01:45 rbspy-1
drwxr-xr-x  2 root root 4096 Jul 22  2019 sbin
drwxr-xr-x  8 root root 4096 May 19 00:52 share
drwxr-xr-x  2 root root 4096 Jul 22  2019 src
drwxr-xr-x 10 root root 4096 May 19 01:45 tippecanoe-1
```

From `/var/log/chef-boostrap-debug.log`:
```
Recipe: cdo-apps::rbspy
  * ark[rbspy] action install
    * directory[/usr/local/rbspy-1] action create
      - create new directory /usr/local/rbspy-1
    * remote_file[/etc/chef/local-mode-cache/cache/rbspy-1.tar.gz] action create
      - create new file /etc/chef/local-mode-cache/cache/rbspy-1.tar.gz
      - update content in file /etc/chef/local-mode-cache/cache/rbspy-1.tar.gz from none to cf966d
      (new content is binary, diff output suppressed)
    * execute[unpack /etc/chef/local-mode-cache/cache/rbspy-1.tar.gz] action nothing (skipped due to action :nothing)
    * execute[set owner on /usr/local/rbspy-1] action nothing (skipped due to action :nothing)
    * link[/usr/local/bin/rbspy] action create
      - create symlink at /usr/local/bin/rbspy to /usr/local/rbspy-1/rbspy
    * link[/usr/local/rbspy] action create
      - create symlink at /usr/local/rbspy to /usr/local/rbspy-1
    * template[/etc/profile.d/rbspy.sh] action create (skipped due to only_if)
    * ruby_block[adding '/usr/local/rbspy-1/bin' to chef-client ENV['PATH']] action run (skipped due to only_if)
    * execute[unpack /etc/chef/local-mode-cache/cache/rbspy-1.tar.gz] action run
      - execute /bin/tar xzf /etc/chef/local-mode-cache/cache/rbspy-1.tar.gz
    * execute[set owner on /usr/local/rbspy-1] action run
      - execute chown -R root:0 /usr/local/rbspy-1

  * link[/usr/local/bin/rbspy] action create
    - unlink existing symlink to file at /usr/local/bin/rbspy
    - create symlink at /usr/local/bin/rbspy to /usr/local/rbspy-1/rbspy-x86_64-musl
```

**Comment by sureshc** [comment]
I’ve verified that the log file and SVG output by rbspy appear to contain valid profiling data.

**Comment by sureshc** [comment]
I didn't test how this change would get applied to long running servers (including the production-AMIBuilder that already have the older release of `rbspy` installed 🤦🏽

**Comment by sureshc** [comment]
Chef log (`/var/log/chef-boostrap-debug.log`) on `staging` (presumably after this change was merged):

```
Recipe: cdo-apps::rbspy
  * ark[rbspy] action install
    * directory[/usr/local/rbspy-1] action create (up to date)
    * remote_file[/var/chef/cache/rbspy-1.tar.gz] action create (up to date)
    * execute[unpack /var/chef/cache/rbspy-1.tar.gz] action nothing (skipped due to action :nothing)
    * execute[set owner on /usr/local/rbspy-1] action nothing (skipped due to action :nothing)
    * link[/usr/local/bin/rbspy] action create
      - unlink existing symlink to file at /usr/local/bin/rbspy
      - create symlink at /usr/local/bin/rbspy to /usr/local/rbspy-1/rbspy
    * link[/usr/local/rbspy] action create (up to date)
    * template[/etc/profile.d/rbspy.sh] action create (skipped due to only_if)
    * ruby_block[adding '/usr/local/rbspy-1/bin' to chef-client ENV['PATH']] action run (skipped due to only_if)

  * link[/usr/local/bin/rbspy] action create
    - unlink existing symlink to file at /usr/local/bin/rbspy
    - create symlink at /usr/local/bin/rbspy to /usr/local/rbspy-1/rbspy-x86_64-musl
 ```

**Comment by sureshc** [comment]
New `rbspy` works on `staging`!

```
ubuntu@staging:~$ sudo rbspy record --silent --duration 120 --pid 17175
rbspy is recording traces. Press Ctrl+C to stop.
Wrote raw data to /home/ubuntu/.cache/rbspy/2023-05-19-5fpUGKH5hs.raw.gz
Wrote formatted output to /home/ubuntu/.cache/rbspy/2023-05-19-RrwJc9t8eD.flamegraph.svg
```

**Pull request merged**
