### PR TITLE
Removes the sitemap.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Besides giving a bad public experience (an empty page), the sitemap is outdated and unused. Aside, the (populated) page is publicly accessible by hitting staging or test.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
@tanyaparker: If you agree this page should go, I'll also kill all the [associated CSS](https://github.com/code-dot-org/code-dot-org/search?l=css&q=sitemap&utf8=%E2%9C%93). Do I need to kill the CSS from all those files individually?

**Comment by tanyaparker** [comment]
It was never intended to be used by customers, pretty sure only internally and isn't linked to anywhere. @breville you're the only one I know who also knows about this page. Do you still use it? Perhaps we gate on admin instead of production environment. Will that make it 404 for everyone else?

**Comment by ashercodeorg** [comment]
Gating on `admin` will take non-signed in users to the sign-in page. For signed-in users, I think it 404's.

**Comment by breville** [comment]
I haven't used it for a while, but I wouldn't mind reviving it at some point as we start rethinking some site architecture.  I guess I can always revive it from history if that happens.  (Should we gate on admin if we ever do that?)

**Comment by ashercodeorg** [comment]
SGTM, we can revive from history if someone wants to invest the time and effort to bring it up-to-date and making it accessible only to admins.

**Comment by ashercodeorg** [comment]
tanyaparker: Do I need to kill the CSS from all the files linked above one at a time?

**Comment by tanyaparker** [comment]
Cool, let's remove it for now.

No, I don't think you don't need to remove any CSS.

**Comment by ashercodeorg** [comment]
Why does the CSS not need to be removed? AFAICT, it isn't being used elsewhere.

**Comment by tanyaparker** [comment]
Oh, I misunderstood your question. I thought you meant the css for the pages linked to from the sitemap. I see now you had a link in your previous comment. Yes, I'd say remove the #sitemap css.

**Comment by ashercodeorg** [comment]
Associated CSS removed. PTAL.

**Comment by tanyaparker** [comment]
LGTM

**Pull request merged**
