### PR TITLE
Add CSF district workshop

### PR DESCRIPTION
**Pull request by megcrenshaw**
Adds a new CSF workshop called "District"––this is slightly different from other CSF courses because the "Fee Information" and "Should this appear on the k-5 workshop map" are hidden.

Screen Shot 2022-05-26 at 9 53 12 AM

## Links

- Jira Ticket: [PLAT-1836](https://codedotorg.atlassian.net/browse/PLAT-1836)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dmcavoy** [comment]
Whats happening with emails for this workshop type?

**Comment by megcrenshaw** [comment]
Good question. In the ticket, it specifies, "It is important that we can still enable emails and select facilitators for this workshop subject." –– this is still an option in the UI. My guess is that the standard email logic will be used here if they are enabled on the site

**Comment by megcrenshaw** [comment]
Just checked in with Tess about this. It should behave like the other CSF courses––`Pd::WorkshopMailer` already does this!

**Review by dmcavoy — APPROVED** [review]
Sounds like the email stuff is taken care of so this good to me from my knowledge of the workshop dashboard

**Pull request merged**
