### PR TITLE
Update Docker Image to Capture Chrome Update

### PR DESCRIPTION
**Pull request by Hamms**
Specifically, I just rebuilt the docker image with `docker build --no-cache .` to pick up a necessary update to the Headless Chrome client.

See the thread at https://codedotorg.slack.com/archives/C0T0PNTM3/p1660161851332389 for more details

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by sureshc — APPROVED** [review]

**Comment by bencodeorg** [comment]
Docker amateur here -- how does this change pick up the Chrome update? Does this change need to be merged before we'll see any changes in Drone, or are these change already live there?

**Comment by Hamms** [comment]
> Docker amateur here -- how does this change pick up the Chrome update?

It is definitely a bit opaque, what's going on here. The root of the issue is that our Dockerfile specifies that we install the latest version of Chromedriver: https://github.com/code-dot-org/code-dot-org/blob/464b5dfdcd8428637b825a906134adde0ec9ca24/docker/dockerfiles/Dockerfile#L79

But because Docker images are static, this actually means that what we install is the latest version of Chromedriver _at the time the docker image was built_; so, this change picks up the Chrome update because I built version 1.5.2 of our Docker image after that update was released.

> Does this change need to be merged before we'll see any changes in Drone, or are these change already live there?

And yes, this change did need to be merged. You should start seeing changes in Drone now!

**Comment by bencodeorg** [comment]
I see -- the new docker image exists once you built it (and you pushed it somewhere that Drone can access it?), but we don't use it in Drone until you merge this change 👍

**Comment by Hamms** [comment]
Exactly! That place is our DockerHub account; we have a little bit of documentation about that here if you're curious: https://github.com/code-dot-org/code-dot-org/tree/staging/docker#updating-the-docker-hub-image

**Pull request merged**
