### PR TITLE
Adds new sign up UI tests for student and teacher creation

### PR DESCRIPTION
**Pull request by hannahbergam**
Adds two new UI tests (with screenshots included) to the student and teacher sign up flows.

The screenshots capture the account type selection page, the login type selection page, the student finish page and the teacher finish page. 

They do not (and should not for it would take too long) cover all the scenarios in each sign up, but at least give us healthy coverage of a common flow for both students and teachers.

## Links

- spec: []()
- jira ticket: https://codedotorg.atlassian.net/browse/ACQ-1777

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by TurnerRiley — APPROVED** [review]
Yay so excited to have these added! Good call on not wanting to add too much time with covering all the scenarios. Are there any specific scenarios you're worried about that maybe we can try to cover somehow in unit tests or do you think this + our existing coverage should be good?

**Comment by hannahbergam** [comment]
> Yay so excited to have these added! Good call on not wanting to add too much time with covering all the scenarios. Are there any specific scenarios you're worried about that maybe we can try to cover somehow in unit tests or do you think this + our existing coverage should be good?

I'm just thinking of all our different branches... school association is fairly well tested on its own. But the colorado lockout, the parent email and the gdpr feel like fairly large edge cases here. I know we've tested these in smaller unit tests, but should I make a followup ticket to ui test the flow for Colorado lands a student in lockout?

**Comment by hannahbergam** [comment]
> > Yay so excited to have these added! Good call on not wanting to add too much time with covering all the scenarios. Are there any specific scenarios you're worried about that maybe we can try to cover somehow in unit tests or do you think this + our existing coverage should be good?
> 
> I'm just thinking of all our different branches... school association is fairly well tested on its own. But the colorado lockout, the parent email and the gdpr feel like fairly large edge cases here. I know we've tested these in smaller unit tests, but should I make a followup ticket to ui test the flow for Colorado lands a student in lockout?

I've decided to just make the ticket and do the ui test as a followup! https://codedotorg.atlassian.net/browse/ACQ-2663

**Comment by TurnerRiley** [comment]
> > > Yay so excited to have these added! Good call on not wanting to add too much time with covering all the scenarios. Are there any specific scenarios you're worried about that maybe we can try to cover somehow in unit tests or do you think this + our existing coverage should be good?
> > 
> > 
> > I'm just thinking of all our different branches... school association is fairly well tested on its own. But the colorado lockout, the parent email and the gdpr feel like fairly large edge cases here. I know we've tested these in smaller unit tests, but should I make a followup ticket to ui test the flow for Colorado lands a student in lockout?
> 
> I've decided to just make the ticket and do the ui test as a followup! https://codedotorg.atlassian.net/browse/ACQ-2663

Perfect, that was the edge case in particular that came to mind for me! I think since it poses a legal risk it makes sense to add a bit more test time to cover (especially in such a sensitive area).

**Comment by hannahbergam** [comment]
> > > > Yay so excited to have these added! Good call on not wanting to add too much time with covering all the scenarios. Are there any specific scenarios you're worried about that maybe we can try to cover somehow in unit tests or do you think this + our existing coverage should be good?
> > > 
> > > 
> > > I'm just thinking of all our different branches... school association is fairly well tested on its own. But the colorado lockout, the parent email and the gdpr feel like fairly large edge cases here. I know we've tested these in smaller unit tests, but should I make a followup ticket to ui test the flow for Colorado lands a student in lockout?
> > 
> > 
> > I've decided to just make the ticket and do the ui test as a followup! https://codedotorg.atlassian.net/browse/ACQ-2663
> 
> Perfect, that was the edge case in particular that came to mind for me! I think since it poses a legal risk it makes sense to add a bit more test time to cover (especially in such a sensitive area).

Love it- I'll merge this one as-is for now and get to work on that!

**Pull request merged**
