### PR TITLE
fail bin/content-push if state pdf generation is in progress

### PR DESCRIPTION
**Pull request by davidsbailey**
Here's how staging looks part way through PDF generation: 
```
ubuntu@staging:~/staging$ git status
Changes not staged for commit:
	modified:   pegasus/sites.v3/code.org/public/advocacy/state-facts/AK.pdf.fetch
	modified:   pegasus/sites.v3/code.org/public/advocacy/state-facts/AL.pdf.fetch
...
	modified:   pegasus/sites.v3/code.org/public/advocacy/state-facts/TN.pdf.fetch
	modified:   pegasus/sites.v3/code.org/public/advocacy/state-facts/TX.pdf.fetch

Untracked files:
	pegasus/sites.v3/code.org/public/advocacy/state-facts/UT.pdf
```

Here's how staging looks when PDF generation is complete:
```
ubuntu@staging:~/staging$ git status
Changes not staged for commit:
	modified:   pegasus/sites.v3/code.org/public/advocacy/state-facts/AK.pdf.fetch
	modified:   pegasus/sites.v3/code.org/public/advocacy/state-facts/AL.pdf.fetch
...
	modified:   pegasus/sites.v3/code.org/public/advocacy/state-facts/WV.pdf.fetch
	modified:   pegasus/sites.v3/code.org/public/advocacy/state-facts/WY.pdf.fetch
```

Here's how this change looks in action:
```
Davids-MacBook-Pro-2:~/src/cdo (wait-for-pdf-fetch)$ git status
Untracked files:
	pegasus/sites.v3/code.org/public/advocacy/state-facts/UT.pdf

Davids-MacBook-Pro-2:~/src/cdo (wait-for-pdf-fetch)$ bin/content-push 
Who are you? dave
Hi dave!

Aborting because state pdf generation appears to be in progress:

    A  pegasus/sites.v3/code.org/public/advocacy/state-facts/UT.pdf

Please wait 10 minutes and then try again.
```

### CODE REVIEW

**Comment by ashercodeorg** [comment]
How does this interact with the DOTD script?

**Comment by davidsbailey** [comment]
Good point guys, I hadn't tested that. Here's how it looks from within bin/dotd:
```
Should I commit content changes from staging? [Yes]/Skip/Quit: 

Follow the prompts given by the content-push script.
  If you need to do something fancier (or if the changed files do not
  "look ok" when it asks you), log in to staging and hand-craft the commit.
pwd: /Users/dsb/src/cdo3
loading bin/content-push

Aborting because state pdf generation appears to be in progress:

    A  pegasus/sites.v3/code.org/public/advocacy/state-facts/UT.pdf

Please wait 10 minutes and then try again.


Uh-oh!  It looks like the staging content push failed!
Should I ssh to staging so you can fix the problem manually? [Yes]/Skip/Quit: 
```

It wouldn't to right to do a retry for all failure types (e.g. case-only renames), but at least the current behavior shows the error and keeps you in the script.

**Comment by davidsbailey** [comment]
a middle path could be to offer Retry and SSH as options. I'll give that a whirl. (apologies Elijah this is pretty much exactly what you suggested!)

**Comment by davidsbailey** [comment]
PTAL

```
Should I commit content changes from staging? [Yes]/Skip/Quit: y

Follow the prompts given by the content-push script.
  If you need to do something fancier (or if the changed files do not
  "look ok" when it asks you), log in to staging and hand-craft the commit.

Aborting because state pdf generation appears to be in progress:

    A  pegasus/sites.v3/code.org/public/advocacy/state-facts/UT.pdf

Please wait 10 minutes and then try again.


Uh-oh!  It looks like the staging content push failed!
Should I retry the staging content push? [Yes]/Skip/Quit: y

Follow the prompts given by the content-push script.
  If you need to do something fancier (or if the changed files do not
  "look ok" when it asks you), log in to staging and hand-craft the commit.

Aborting because state pdf generation appears to be in progress:

    A  pegasus/sites.v3/code.org/public/advocacy/state-facts/UT.pdf

Please wait 10 minutes and then try again.


Uh-oh!  It looks like the staging content push failed!
Should I retry the staging content push? [Yes]/Skip/Quit: s

Should I ssh to staging so you can fix the problem manually? [Yes]/Skip/Quit: s

Should I commit content changes from levelbuilder? [Yes]/Skip/Quit: 
```

**Pull request merged**
