### PR TITLE
Fixes violations of Style/BlockEndNewline and reenables the rubocop check.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes generated by "bundle exec rubocop --only Style/BlockEndNewline --auto-correct", followed by manual removal of trailing whitespace.

Unlike in PR#7007 (reverted in PR#7009), in this PR the check was spelled correctly.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Take two. :)

**Comment by Bjvanminnen** [comment]
looks twice as good to me

**Comment by joshlory** [comment]
Nit: I think we prefer `do` ... `end` for multi-line blocks?

**Comment by Bjvanminnen** [comment]
ahh yes, i think josh is right

**Comment by ashercodeorg** [comment]
Done (do...end).

**Pull request merged**
