### PR TITLE
Add exporting tables to csv

### PR DESCRIPTION
**Pull request by trevorb**
Add the ability to export data tables to csv format.

### CODE REVIEW

**Comment by davidsbailey** [comment]
Great progress Trevor! As you noticed, there are two implementations of to_csv -- one for Table (backed by mysql) and one for DynamoTable (backed by DynamoDB). FYI, you can add the following to your locals.yml file in the root of your git repository to test against DynamoDB locally:
```
use_dynamo_tables: true
use_dynamo_properties: true
```
The tests you've added should already be hitting DynamoDB.

**Comment by trevorb** [comment]
Awesome, thanks! I'll add that and do a bit more testing.

**Comment by davidsbailey** [comment]
LGTM. Thanks for adding tests! 

Optionally, what do you think about expanding the test to enforce that after importing, then exporting, the columns are in the same order? I think we get this for free given your current implementation, provided every row contains an entry for every column. 

FYI, there may also be some future work related to adding a "schema" which enforces consistent types on each column, which could also be used to specify an order. This would let us keep a consistent ordering even when some rows are missing some columns, however we haven't committed to doing that work yet. (FYI @sfilman )

**Comment by trevorb** [comment]
Cool.  We get enforcing order for free because we are comparing the column line of the original file and result body.

**Pull request merged**
