### PR TITLE
Add descriptions for Archived Sections for both students and teachers

### PR DESCRIPTION
**Pull request by TurnerRiley**
Adds a short description on the Student and Teacher dashboards under the "Archived Sections" title. This will only show up if they have archived sections. This PR also increases the font size and line heighs for the title "Archived Sections" so that it's more distinct from the description.

_The description for students:_
Archived sections are hidden by your teachers. Your progress in You won’t be redirected to archived sections’ course assignments.

_The description for teachers:_
Archived sections are hidden on your students’ My Dashboard. Students are not redirected to archived sections’ course assignments.

### Previous vs. New Look
**Student view (no archived sections) [no change]**
Previous:
O Student no arch
New:
Student no arch

**Teacher view (no archived sections) [no change]**
Previous:
O Teacher no arch
New:
Teacher no arch

**Student view (with archived sections)**
Previous:
O Student with arch
New:
Student with arch

**Teacher view (with archived sections)**
Previous:
O Teacher with arch
New:
Teacher with arch

## Links
Spec: [here](https://docs.google.com/document/d/1bSG8FV6OpBZBQPLA63tTN9oJ9gCk7vkC_S-neQ7Dnws/edit#)
Jira ticket: [here](https://codedotorg.atlassian.net/browse/FND-1622?atlOrigin=eyJpIjoiYWEzNWIxZGRlNWQzNDkzZGI5MGRmYzY5ZTVhODgwODkiLCJwIjoiaiJ9)

## Testing story
Manual testing on multiple browsers and in mobile across multiple languages.

## Follow-up work
If teachers still have concerns or are confused by the premise of Archived vs. Removed sections, then we will look into Requirement 5 of [the spec](https://docs.google.com/document/d/1bSG8FV6OpBZBQPLA63tTN9oJ9gCk7vkC_S-neQ7Dnws/edit#).

## PR Checklist:
- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dju90** [comment]
LGTM!

**Review by daynew — APPROVED** [review]
Code looks good.

Make sure to check the styling with product. It doesn't match my personal taste. Changes I would make:
* "Archived Sections" should be the same font size as "Classroom Sections". They are both headers.
* The description for archived sections should match the font size used in the description of "Add a new classroom section". The font size in the screenshot looks too small.

**Comment by dju90** [comment]
> Code looks good.
> 
> Make sure to check the styling with product. It doesn't match my personal taste. Changes I would make:
> 
> * "Archived Sections" should be the same font size as "Classroom Sections". They are both headers.
> * The description for archived sections should match the font size used in the description of "Add a new classroom section". The font size in the screenshot looks too small.

Hey Dayne, thanks for the input. I think of Archived Sections as a subheading of Classroom Sections, so that heading should be smaller. @TurnerRiley I don't mind the Archived Sections description being 14pt as long as there's a noticeable font size difference between it and the Archived Sections heading (maybe bump it up to 18px?). Feel free to ping me with any changes you try out.

**Comment by TurnerRiley** [comment]
> > Code looks good.
> > Make sure to check the styling with product. It doesn't match my personal taste. Changes I would make:
> > 
> > * "Archived Sections" should be the same font size as "Classroom Sections". They are both headers.
> > * The description for archived sections should match the font size used in the description of "Add a new classroom section". The font size in the screenshot looks too small.
> 
> Hey Dayne, thanks for the input. I think of Archived Sections as a subheading of Classroom Sections, so that heading should be smaller. @TurnerRiley I don't mind the Archived Sections description being 14pt as long as there's a noticeable font size difference between it and the Archived Sections heading (maybe bump it up to 18px?). Feel free to ping me with any changes you try out.

All done!

**Pull request merged**
