### PR TITLE
use encodeURIComponent and quoted CSS url strings on asset filenames

### PR DESCRIPTION
**Pull request by davidsbailey**
### background

https://github.com/code-dot-org/code-dot-org/pull/20383 fixed a problem where filesnames containing parentheses like `image (1).jpg` could be uploaded to App Lab but not displayed. However, the same PR broke asset filenames containing `ñ` or `☃`. 

### description

stop using `escape` on applab asset filenames. Use encodeURIComponent on asset filenames. Use double-quoted strings when embedding the encoded result into the CSS style.backgroundImage so that filenames containing `(`, `)` or `'` do not get rejected when setting style.backgroundImage.

### notes

https://stackoverflow.com/questions/2168855/is-quoting-the-value-of-url-really-necessary

> Some characters appearing in an unquoted URI, such as parentheses, white space characters, single quotes (`'`) and double quotes (`"`), must be escaped with a backslash so that the resulting URI value is a URI token: `'\('`, `'\)'`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

```
Not Escaped:
 
    A-Z a-z 0-9 - _ . ! ~ * ' ( )
```

Conclusions:
1. the fact that we were using unquoted CSS strings explains why simply calling encodeURIComponent() rather than escape() on the user's uploaded filename was broken when the filename contained parentheses.
2. all characters not escaped by encodeURIComponent should now be allowable in the double-quoted CSS string.

### CODE REVIEW

**Comment by davidsbailey** [comment]
Thanks Brad! Sorry I fired this off too soon, I've updated the description with more detail FWIW.

**Comment by davidsbailey** [comment]
Manually tested the following characters in App Lab image filenames: `(`, `#`, ` `, `"`, `'`, `?`, `\`, `ñ`. Backslash is actually a little broken (filename truncated to exclude the backslash) but this is not a regression, appears not to be a super common filename, and is easy to work around (image with truncated filename can still be selected).

**Comment by islemaster** [comment]
Change still looks good :point_up_2:  :point_right: 
make_it_so

**Pull request merged**
