### PR TITLE
migrate HocTutorials Google Sheet to v3 format

### PR DESCRIPTION
**Pull request by sureshc**
Create a copy of the Pegasus/Data/HocTutorials in the Pegasus/v3 folder and format (with datatype suffixes).  A future Pull Request will update the Pegasus Views that display this data to pull from the new database table.  Note that the "v3" CSVtoSQL Class has been updated to explicitly specify UTF-8 as the encoding for the input CSV because there are non-ASCII characters in the HocTutorials sheet.

### CODE REVIEW

**Comment by sureshc** [comment]
@breville The Tutorials sheet contains some non-ASCII data.  The legacy Google Sheet import rake task explicitly specifies UTF-8 encoding:

https://github.com/code-dot-org/code-dot-org/blob/44c22f53cd0da1ff18788a6a7925cedc18756177/pegasus/rake/seed.rake#L218

I had to add that to the v3 `CSVtoSQL` class to ensure that the Tutorials sheet can be imported without errors.  Any thoughts on how to test this change and ensure it does non impact how the existing v3 sheets are imported?

**Comment by breville** [comment]
I don't think we have a `rake` command to force a re-retrieval of all gsheets, but you should be able to make a local modification to do this, and then look to see if there are any other CSV differences on your local machine, as a way to see if the impact of this change goes beyond the known ones in this gsheet?

Also, this change seems reasonable, but have you been able to confirm that the non-ascii characters in HocTutorials seem to be reasonable from a content point of view?

**Comment by sureshc** [comment]
The non-ASCII content is legitimate.  For example:  `Frogger™` and `Pädagogische`

**Comment by sureshc** [comment]
@breville I temporarily changed cdo-standards.gsheet on my local development environment to specify a path in Google Drive to a test copy of the cdo-standards Google Sheet, I ran `bin/cron/import_google_sheets` and verified that the contents of the pegasus_development.cdo-standards table was exactly the same before and after the import.

Does that seem like an adequate test of the UTF-8 change?

**Comment by breville** [comment]
Doesn't this change potentially affect the import of all v3 gsheets?  My suggestion was to locally force the import of all g3 spreadsheets to ensure there wasn't a problem with any of our existing content...

**Comment by sureshc** [comment]
Good point.  I'll temporarily modified the logic in my local branch to ignore the Google Sheet time stamps to force all of the sheets to be imported.  I'll be able to check for errors.  Not sure there's a good way to verify the data is exactly the same.

**Comment by breville** [comment]
If you see no differences in the generated CSV files locally then that seems a good sign that nothing changed.

**Comment by sureshc** [comment]
The UTF-8 vs ASCII-8BIT encoding error is occurring during the CSV to SQL import (not during the Google Sheet to CSV download/conversion).  Most of the existing Sheets in the `v3` format/directory contain non-ASCII characters such as curly quotes and are importing into the Pegasus database successfully with the non-ASCII characters preserved during import without using the new encoding logic I added.

I haven't yet determined what specific non-ASCII content in the HocTutorials Google Sheet requires the small change I've added in this Pull Request that explicitly specifies the encoding in the CSV is UTF-8.  I have also not conclusively determined that the existing v3 sheets are being imported exactly the same way with this change (that would probably require comparing the *full* contents of the Pegasus `cdo-*` database tables before/after import with this change.

**Pull request merged**
