### PR TITLE
Create ScriptsResource and UnitGroupsResource to eventually replace teacher resources

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Step 1 of replacing the current teacher resources with the resources model.

Steps for this will be:
1. (This PR) Create an association between scripts and resources so that resources can be associated with a script. Like with lessons, the resources should only be from the same course version as the script.
2. Add seeding of ScriptsResource
3. Replace the current way to add resources to a script with a new editor using the Resources model. Move all existing resources to the resources model (at least on migrated scripts). Display resources from the resources model in the dropdown.

Let me know if there are any issues with this plan!

## Links

- jira ticket: [PLAT-509](https://codedotorg.atlassian.net/browse/PLAT-509)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dmcavoy** [comment]
What about the teacher resources dropdown on the course page?

**Comment by dmcavoy** [comment]
For step 3 - Are we going to need to maintain the old teacher resources system for old courses as well as the new system for new courses?

**Comment by bethanyaconnor** [comment]
> What about the teacher resources dropdown on the course page?

Ah darn, I missed those. Might need to rethink this approach


> For step 3 - Are we going to need to maintain the old teacher resources system for old courses as well as the new system for new courses?

I can't remember -- are all old courses associated with a course version? If so, then I think we could move everything to the new system, if not then it might be more trouble than it's worth.

**Comment by bethanyaconnor** [comment]
Okay, I see two options here to deal with course teacher resources:
1. Also add a resource/unit group join table and continue with the plan I outlined in this PR
2. Scrap this PR and add a property `teacher_resource_keys` to both Script and UnitGroup. This will hold a list of keys to resources, no migration required. @Hamms [suggested](https://github.com/code-dot-org/code-dot-org/pull/38702#issuecomment-772004213) something like this for lessons in a different PR. Resources are still associated with lessons by a join table so this would be a bit inconsistent but would be similar to how teacher resources are currently implemented

**Comment by dmcavoy** [comment]
> I can't remember -- are all old courses associated with a course version? If so, then I think we could move everything to the new system, if not then it might be more trouble than it's worth.

I think the work to move everything onto course version is listed as part of Q2 so my guess is that we have not moved everything over.

**Comment by bethanyaconnor** [comment]
> I think the work to move everything onto course version is listed as part of Q2 so my guess is that we have not moved everything over.

Sounds good -- when I dig into actually moving the teacher resources over, I'll check if it's possible to move everything over. If it isn't, I'll create a backlog task.

**Comment by davidsbailey** [comment]
> Okay, I see two options here to deal with course teacher resources:
> 
> 1. Also add a resource/unit group join table and continue with the plan I outlined in this PR
> 2. Scrap this PR and add a property `teacher_resource_keys` to both Script and UnitGroup. This will hold a list of keys to resources, no migration required. @Hamms [suggested](https://github.com/code-dot-org/code-dot-org/pull/38702#issuecomment-772004213) something like this for lessons in a different PR. Resources are still associated with lessons by a join table so this would be a bit inconsistent but would be similar to how teacher resources are currently implemented

These seem like the right options to consider 👍  would it be possible to provide a summary of why we want to do this work in the first place? I get that we are combining two "resource" things in the system which look and work very similarly, but also wondering I guess if there is anything user-facing (teacher or editor) which depends on this? Perhaps that will help clarify whether we need the beefier option 1.

**Comment by dmcavoy** [comment]
> > Okay, I see two options here to deal with course teacher resources:
> > 
> > 1. Also add a resource/unit group join table and continue with the plan I outlined in this PR
> > 2. Scrap this PR and add a property `teacher_resource_keys` to both Script and UnitGroup. This will hold a list of keys to resources, no migration required. @Hamms [suggested](https://github.com/code-dot-org/code-dot-org/pull/38702#issuecomment-772004213) something like this for lessons in a different PR. Resources are still associated with lessons by a join table so this would be a bit inconsistent but would be similar to how teacher resources are currently implemented
> 
> These seem like the right options to consider 👍 would it be possible to provide a summary of why we want to do this work in the first place? I get that we are combining two "resource" things in the system which look and work very similarly, but also wondering I guess if there is anything user-facing (teacher or editor) which depends on this? Perhaps that will help clarify whether we need the beefier option 1.

I can offer the reason we wanted to move Teacher Resources onto the resources model. The big thing is it would allow a editor to define a resource in one place and use it in many places. Say I want to talk about the curriculum guide in lesson plans but also want to list it in the teacher resources. The ideal is that those are all connected together so if I need to update the name of that resource or its link I do it in one place and then it updates everywhere.

**Comment by davidsbailey** [comment]
> I can offer the reason we wanted to move Teacher Resources onto the resources model. The big thing is it would allow a editor to define a resource in one place and use it in many places. Say I want to talk about the curriculum guide in lesson plans but also want to list it in the teacher resources. The ideal is that those are all connected together so if I need to update the name of that resource or its link I do it in one place and then it updates everywhere.

OK, I think this goal will be met by either plan. Do you want to decide, Bethany? On the one hand, option 2 seems easier. On the other hand, option 1 is very similar to the way we link resources to lessons, so one could argue that there is no special reason to go with a different approach here.

**Comment by bethanyaconnor** [comment]
Thanks Dave and Dani, this was super helpful! I'm going to go with the join tables still as it will prevent any dangling references if a resource is deleted and it's more consistent with how we do lessons. I'll update this PR today and tag you both. :)

**Comment by davidsbailey** [comment]
> Thanks Dave and Dani, this was super helpful! I'm going to go with the join tables still as it will prevent any dangling references if a resource is deleted and it's more consistent with how we do lessons. I'll update this PR today and tag you both. :)

That seems like a good reason! We will still have dangling references to resources (and vocab and docs) within lesson plan content, but avoiding these when possible still seems like it will save us trouble.

**Comment by bethanyaconnor** [comment]
@davidsbailey @dmcavoy updated this PR with a second migration. PTAL when you get a chance!

**Review by davidsbailey — APPROVED** [review]

**Review by dmcavoy — APPROVED** [review]
LGTM! Thanks for tackling this

**Pull request merged**
