### PR TITLE
update gemfile lock for m1 compatibility

### PR DESCRIPTION
**Pull request by cat5inthecradle**
These dependency updates are required for M1 mac compatibility. I think M1 users have just been keeping this file unstaged while working.

## Links

- [Code.org Development Environment on Apple Silicon (2.5.0)](https://docs.google.com/document/d/1fH51x4HR_eHb53IWQHeTTm_-HhB8w60_FLKMmwUx9hE/edit#heading=h.fl2uxakrol5a)

## Testing story

- Need to have this tested on non M1 systems.

## Follow-up work

- update the linked M1 setup doc and SETUP.md

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by megcrenshaw — APPROVED** [review]
Looks good on an Intel Mac!

**Comment by cat5inthecradle** [comment]
@Hamms says "This installs, builds, and serves successfully on my Pop!_OS 20.04 system"

**Review by hannahbergam — APPROVED** [review]
Works on my M1 Macbook Air! Thank you for doing this!

**Comment by cat5inthecradle** [comment]
@tim-dot-org says "works on my windows+ubuntu wsl weird set up!"

**Comment by cat5inthecradle** [comment]
getting errors in staging and test, reverting via https://github.com/code-dot-org/code-dot-org/pull/46416

**Pull request merged**
