### PR TITLE
Add Mailgun API key

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Adds a MailGun API key. MailGun is a product related to MailJet (I _think_ MailGun owns MailJet). There's an API to verify email addresses we want to use that requires the MailGun API key. This PR simply sets up that API key.

### CODE REVIEW

**Comment by bethanyaconnor** [comment]
I checked in Secrets Manager and the secrets look correctly formatted. Big thanks to @sureshc for simplifying this process!

**Comment by sureshc** [comment]
Will MailGun/Jet be sending emails on our behalf? If so @code-dot-org/infrastructure will need to configure some DNS records that publicly state they are allowed to send and digitally sign emails on behalf of the `code.org` domain name.

**Comment by bethanyaconnor** [comment]
> Will MailGun/Jet be sending emails on our behalf? If so @code-dot-org/infrastructure will need to configure some DNS records that publicly state they are allowed to send and digitally sign emails on behalf of the code.org domain name.

MailJet will, MailGun will not. I started a [thread](https://codedotorg.slack.com/archives/C03CK49G9/p1710357051301349) in #infrastructure about this about a month ago but haven't followed up. We also have [a ticket](https://codedotorg.atlassian.net/browse/ACQ-1603) for this, though I don't think we've made a corresponding ticket on the infra backlog.

I did play with updating the DNS records in code myself, but had to put it down for a while because of other things. I'll need to pick that back up again soon and likely get y'all to help me out. :)

**Comment by bethanyaconnor** [comment]
@code-dot-org/infrastructure  or @code-dot-org/acquisition-products-team -- can I get a ✔️ on this PR if it looks good?

**Review by kelbyhawn — APPROVED** [review]
Looks good to me! Someone else might want to take a look too though.

**Review by TurnerRiley — APPROVED** [review]
👍

**Pull request merged**
