### PR TITLE
Organize .gitignore files

### PR DESCRIPTION
**Pull request by islemaster**
Just a proposal.  We already had most of these `.gitignore` files in our repo (the only one I had to add, surprisingly, was `apps/.gitignore`) but our root `.gitignore` contained a lot of rules for subdirectories that had their own ignore files already.  Seems like a directory should own all its own ignores.

Alternatively, we could go the other way and have one big ignore file.

Opinions?

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Memory is hazy here, but i thought we used to have a more per directory approach and decided to move in the opposite direction (towards a single file in the root).

**Comment by ashercodeorg** [comment]
At the face of it, I'm fine with having a repository-level `.gitignore` file or a per-directory `.gitignore` file (as needed). Both make it clear where exclusions do or don't happen. It doesn't make sense to me to land in the middle, with multiple `.gitignores` referring to files in (respective) subdirectories, as I now need to search (alternately run `git check-ignore`) to determine where an exclusion does or doesn't happen.

In terms of best practices, I'm quickly finding [StackOverflow](http://stackoverflow.com/questions/10274424/best-practice-for-using-multiple-gitignore-files) and [StackOverflow](http://stackoverflow.com/questions/3305869/are-multiple-gitignores-frowned-on). My instinct is for a global file. Though I'm not particularly opinionated no matter where we land.

**Comment by islemaster** [comment]
TIL `git check-ignore` :+1:

**Comment by wjordan** [comment]
I don't have a preference on single vs. per-directory file for our various application-specific exceptions to general git-ignore patterns.

In either case, I'd like us to focus efforts on trying to keep these special exceptions to a minimum by reusing global, conventional patterns for git-ignored files as much as possible.

Ideally, we wouldn't need any subdirectory-specific rules when all of the files that need to be ignored match conventional patterns established through global rules set in our root `.gitignore` file. If we ever reached that ideal we would only need a single `.gitignore` in the root without any subdirectory-specific rules in it, and we wouldn't have any further choice to make.

**Comment by islemaster** [comment]
It sounds like our ideal world is just one `.gitignore` for the repo, but we're all pretty ambivalent about how to get there.  @wjordan when you say "global, conventional patterns" do you just mean commonly ignored files/directories like `node_modules/` and `npm-debug.log`, or is there some other best-practice that I haven't heard of (like our `*~` rule which I assume excludes a lot of temporary files)?

We'll probably never reach our ideal since we'll always have dependencies that don't follow said conventions, but I'm in favor of making our own ignored files conform to some standard.  Does this mean we should rename our generated files like `/src/util/sharedConstants.js` to something like `sharedConstants~.js` or `sharedConstants.js~`?  We'd need to adjust our webpack config to support the latter, but it'd make sense to have a marker like this on all our generated files.

**Pull request closed without merging**
