### PR TITLE
I18n sync In & Up 10/27

### PR DESCRIPTION
**Pull request by deploy-code-org**
# I18n Sync In & Up

This PR contains all changes to internationalization source strings made since the last sync (usually a week).

## To Review:

1. Look through the changes in each of the commits and verify that all changes are expected

   - We expect content changes to come in on a regular basis; individual strings will get updated, added, and deleted.

   - We _do not_ usually expect to see "comprehensive" changes - or changes that apply to large numbers of strings or whole categories of strings all at once - unless we have made specific code changes.

2. Notify the International Partners team about any changes that might appear to manifest as "lost translations"

   - For example: https://github.com/code-dot-org/code-dot-org/pull/31031/files#diff-aa1910a8cf8f9290ae3baf7e39dbae3eL397-R398

     This is a change that added new strings (with both new keys and new content) and simultaneously removed some very similar old ones; we can reasonably infer that the intent here was to swap the new strings out for the old ones. Unfortunately, because the swap also included a content change to the strings the crowdin duplication system won't automatically apply translations to the new strings and so they will need to be manually re-translated.

## To Deploy:

Once one or two people have reviewed and approved this change and the tests are passing, ship it!

It's not necessary to wait for everyone on the team to review.

### CODE REVIEW

**Comment by castro-jorge** [comment]
@mgc1194 it looks it is missing [the strings](https://github.com/code-dot-org/code-dot-org/pull/54442/files#diff-f0ce04b62cc42d6c51400d175aede40af417c61dce1ec0b2136a8ae41a703b09) @kelbyhawn merged today, is that expected?

**Comment by artem-vavilov** [comment]
> @mgc1194 it looks it is missing [the strings](https://github.com/code-dot-org/code-dot-org/pull/54442/files#diff-f0ce04b62cc42d6c51400d175aede40af417c61dce1ec0b2136a8ae41a703b09) @kelbyhawn merged today, is that expected?

@castro-jorge Which strings are missed? It seems like everything is synced-in:
https://github.com/code-dot-org/code-dot-org/pull/54536/commits/43a7b598281822930e89dde0c0120fd6cb5e1015#diff-e7c16e2b5ae59e03116be8cb8c1c695ae590f7f914034be33078b26d43748704

**Review by kelbyhawn — APPROVED** [review]
New [code.org/dance](https://code.org/dance) strings are there 🙌

**Review by lfryemason — APPROVED** [review]
Coteacher strings are there!

**Pull request merged**
