### PR TITLE
Remove CS in Algebra from the Marketing Site and Old Curriculum Docs

### PR DESCRIPTION
**Pull request by dmcavoy**
We are deprecating CS in Algebra! This means we want to remove it from the marketing website. In addition we want to delete old curriculum pages from before Curriculum Builder time. 

The course lesson plans will continue to live at https://curriculum.code.org/algebra/courseA/ and https://curriculum.code.org/algebra/courseB/ if teachers want lesson plans. 

The full list of the Marketing pages can be found here: https://docs.google.com/spreadsheets/d/1hT1oms50AvJx5kERhk0ebEPLXeYH5Do4-_XJAE8fa3A/edit#gid=0. 

This is a lot of files but I did the deletion by going to the folder level. You can see the algebra, curriculum-algebra, and curriculum-docs/algebra folders which were the three primary ones I deleted. 

Screenshot 2023-05-30 at 5 12 29 PM

I search the repo for those paths to make sure there aren't things referencing these folders. It looks like there may be some referencing things in the algebra folder so I will follow up on that.

## Links

https://codedotorg.atlassian.net/browse/ACQ-619
https://docs.google.com/document/d/1KNDwrYQt5XtoI3_h-tzLqONVftIAQ5v5aACm2GT4e6c/edit

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
woohoo!

**Review by kelbyhawn — APPROVED** [review]
Also woohoo!! 

Curious: is there any redirecting needed here, or is it ok to just straight up delete?

**Comment by dmcavoy** [comment]
Update: All of the remaining references to /educate/algebra/... are in the Algebra PD scripts which have not been used in years and will be deprecated with the courses so I won't worry about them. 

We are not planning on a redirect for this because we are planning to fully deprecate the courses and do not want a bunch of marketing pages hanging around. The warning has been up on the courses for a while saying they will be going away. If people write in and ask where they went there is a support article they will be pointed to. The courses themselves will point to that support article.

**Comment by kelbyhawn** [comment]
> Update: All of the remaining references to /educate/algebra/... are in the Algebra PD scripts which have not been used in years and will be deprecated with the courses so I won't worry about them...

Awesome, sounds good to me 👍

**Comment by davidsbailey** [comment]
This makes sense to me Dani. it looks like a few broken images will appear in CS-in-A levels, and that seems ok for a course that we've warned folks is deprecated.

I did also notice this usage: https://github.com/code-dot-org/code-dot-org/blob/71e508b4b7d494702265d6a10ac8d8f5741be22b/dashboard/app/models/pd/workshop_constants.rb#L19

but since we are not allowing new workshops to be created of this type, I think this is also fine.

**Pull request merged**
