### PR TITLE
Move Theme Picker in App Lab

### PR DESCRIPTION
**Pull request by molly-moen**
Hackathon Item [#9](https://docs.google.com/document/d/1W-5Uh94GZZDOgtuud4FvAkBztLh-_yyQxXh0TKf228w/edit#)
Move App Lab theme picker from the screen design workspace to the design toolbox so it is always visible in design mode.
Before:
Screen Shot 2020-04-28 at 9 18 37 AM
After:
Screen Shot 2020-04-28 at 9 18 48 AM
Still visible if clicked on a button:
Screen Shot 2020-04-28 at 9 18 58 AM

Note that if the theme is changed and the user is not on the screen design workspace the screen design workspace will replace what was currently there, let me know if that is not desired behavior.

## Testing story
Manually verified that changing the theme in the new picker updates the theme correctly, and the picker works when switching screens and to lower level items (buttons, etc.)

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by markabarrett** [comment]
Cool!

**Comment by ghost** [comment]
@moneppo what do you think of _moving_ the theme dropdown vs duplicating it in the toolbox?  i was originally envisioning that we have it in both places (screen properties and above the controls toolbox) but seeing how Molly built it, it may be better to not duplicate the control.  one downside is that students who got used to finding it in the screen properties space will need to refind it.

**Comment by molly-moen** [comment]
> @moneppo what do you think of _moving_ the theme dropdown vs duplicating it in the toolbox? i was originally envisioning that we have it in both places (screen properties and above the controls toolbox) but seeing how Molly built it, it may be better to not duplicate the control. one downside is that students who got used to finding it in the screen properties space will need to refind it.

@boatmarina it's easy for me to put it back if we want it in both places! I agree it could cause   confusion to not be in the screen properties space anymore but it seemed weird to have it duplicated.

**Comment by ghost** [comment]
> > @moneppo what do you think of _moving_ the theme dropdown vs duplicating it in the toolbox? i was originally envisioning that we have it in both places (screen properties and above the controls toolbox) but seeing how Molly built it, it may be better to not duplicate the control. one downside is that students who got used to finding it in the screen properties space will need to refind it.
> 
> @boatmarina it's easy for me to put it back if we want it in both places! I agree it could cause confusion to not be in the screen properties space anymore but it seemed weird to have it duplicated.

yeah, i agree it's weird for it to be duplicated too.  i think if this was the first time we did this, i wouldn't duplicate it (and screen control works like all other controls - you have the specific background color property you can override in the properties panel, but the uber way to control the theme is in the toolbox).  so i lean towards doing it as you've built here and leaning on students discovering it in the new spot, which is pretty obvious.  if we don't hear back from mike today on this, let's ship it as you've built it and we can always add it back if we change our minds!

**Review by maddiedierker — APPROVED** [review]
🎉 yay, this is much more visible now!

**Pull request merged**
