### PR TITLE
Fix Immersive Reader Button alignment

### PR DESCRIPTION
**Pull request by levadadenys**
## Warning!!

We have entered Pixel Lock for Hour of Code!

Computer Science Education Week will be happening from Dec 4 - Dec 10. Alongside this event, we will
be launching our new Hour of Code activity. Please consider any risk introduced in this PR that
could affect Dance Lab, instructions, saving and logging student progress, caching, or anything
related to the Hour of Code activities, old or new. Even small changes, such as a different button
color, are considered significant during this time. If this change will affect the new Hour of Code
activity in any way, join the morning change review to get your changes approved prior to merging.
Reach out to the Student Labs team for more details!

### Fix Immersive Reader Button alignment

When immersive reader button stand next to inline audio (play) button, it's slightly of aligned.
Issue is  not reproducable locally for some reason (I can only see immersive reader button without button that stands next to it on production), I guess that’s why we haven’t spotted it yet. But on production it’s more easy to spot these issues.
(Screens with just one button(immersive reader button) represents localhost, screens with two buttons represent production)

* immersive-reader-button correct vertical and horizontal alignment when it's next to other buttons

Before:
Знімок екрана 2023-12-01 о 18 14 13
Знімок екрана 2023-12-01 о 18 12 17
Знімок екрана 2023-12-01 о 18 15 21
Знімок екрана 2023-12-01 о 18 34 29

After:
Знімок екрана 2023-12-01 о 18 12 38
Знімок екрана 2023-12-01 о 18 14 07
Знімок екрана 2023-12-01 о 18 15 27
Знімок екрана 2023-12-01 о 18 35 02

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bencodeorg** [comment]
How were you able to confirm this change fixes the issue if you can't repro locally? I just applied the change here in production and it seems like it made it worse? This is in Chrome:

image

At this point, we're probably not going to deploy this today, so might make sense to rebase your change onto `staging-next`

**Comment by levadadenys** [comment]
> were you able to confirm this change fixes the issue if you can't repro locally? I just applied the change here in production and it seem

oh wow, interesting!
Are you sure you haven't changed anything except for those two lines? Cause I've done exactly the same what you've done and that fixed the issue.
Was those buttons correctly aligned before you made these changes?

**Comment by fisher-alice** [comment]
> > were you able to confirm this change fixes the issue if you can't repro locally? I just applied the change here in production and it seem
> 
> oh wow, interesting! Are you sure you haven't changed anything except for those two lines? Cause I've done exactly the same what you've done and that fixed the issue. Was those buttons correctly aligned before you made these changes?

Another data point - locally on staging, I see the misaligned immersive reader button and after I pulled Denys's branch locally, I see the problem fixed (immersive reader button and inline audio button are aligned).

**Comment by levadadenys** [comment]
@bencodeorg  oh yeah, I see you zoomed out on your machine, that's what make it work differently.
From what I've just checked - immersive reader button changes its size 'strangely'. When I zoom out for 90% or 67%, the fix that I've added here doesn't work. Works with other zooms.
Will investigate it later, for now - will rebase it to `staging-next`.
Thanks for noticing this!

**Comment by bencodeorg** [comment]
Ah got it! Yep I was at 90%, looks better at 100.

Side note -- I've been confused by this component before, we render the ImmersiveAudio and TTS (`InlineAudio`) components completely separately (right?), which seems like the real problem in getting these to line up. Would be awesome if there was a broader refactor we could do to get them rendered in the same container (there's probably some reason this is set up this way)

**Comment by fisher-alice** [comment]
> Ah got it! Yep I was at 90%, looks better at 100.
> 
> Side note -- I've been confused by this component before, we render the ImmersiveAudio and TTS (`InlineAudio`) components completely separately (right?), which seems like the real problem in getting these to line up. Would be awesome if there was a broader refactor we could do to get them rendered in the same container (there's probably some reason this is set up this way)

I see the misalignment zoomed at 90% as well. Good catch @bencodeorg!
I was actually curious about rendering the two buttons together. I see in Hints that the TTS button is displayed but NOT the ImmersiveAudio. Not sure if that's intended, but +1 to Ben's idea on rendering them together.

**Comment by levadadenys** [comment]
Wasn't able to fully fix 90%/60% zoom out issue. The difficulty here is that our Immersive-Reader button is in fact an image (instead of icon like inline audio buttons), which sets 0.002px different height to the neighbour elements with same height.

However I was able to improve that behaviour significantly. I suggest we go ahead and approve/merge it.

90% zoom before:
Знімок екрана 2023-12-13 о 15 46 54


90% zoom after:
Знімок екрана 2023-12-13 о 15 47 31


100% zoom after: 
Знімок екрана 2023-12-13 о 15 47 40


90% zoom after:
Знімок екрана 2023-12-13 о 15 47 57

**Review by breville — APPROVED** [review]
Verified locally that this fixes the issue for my browser.

**Pull request merged**
