### PR TITLE
generate sourcemaps for minified js in staging/test/prod

### PR DESCRIPTION
**Pull request by davidsbailey**
see https://github.com/code-dot-org/code-dot-org/pull/30888

### CODE REVIEW

**Review by breville — APPROVED** [review]

**Review by islemaster — COMMENTED** [review]
Is that all it takes? This turns on sourcemap support for the UglifyJS plugin, but I think I remember needing enable it elsewhere in the Webpack process as well, before the uglify step.  Or has that been enabled all along?

I feel like this has been an option for a while, and there's a reason we haven't turned it on - whether that's build time, or some inconsistency in how it works.  It might be because inline sourcemaps add a lot of size to the final bundle.  So I'm hesitant to turn this setting on for production until we're confident it's working well on staging.  Maybe we can just set `DEBUG_MINIFIED` on staging for now?

**Comment by davidsbailey** [comment]
> Is that all it takes?

I'm really not sure. You raise a good point about downsides. I'll try this out on an adhoc first.

> Maybe we can just set DEBUG_MINIFIED on staging for now?

Perhaps, but if we go with any solution but this one, we need to do work to make sure the js package built on staging does not get put onto production.

I have a couple big webpack changes pending, so I think I might need to hold off until merging this for a day or two regardless.

**Comment by islemaster** [comment]
> > Maybe we can just set DEBUG_MINIFIED on staging for now?
> 
> Perhaps, but if we go with any solution but this one, we need to do work to make sure the js package built on staging does not get put onto production.

I totally forgot this, great point!

**Comment by davidsbailey** [comment]
closing because this seems to double the time it takes to generate an optimized webpack build from 4.5 minutes to 9 minutes.

**Pull request closed without merging**
