### PR TITLE
[WIP] Include contained dsl in i18n sync

### PR DESCRIPTION
**Pull request by Hamms**
Right now, we aren't internationalizing DSL content like http://localhost-studio.code.org:3000/s/coursee-2017/stage/8/puzzle/4 that is _contained_ in a CSF script but not a part of the script directly.

To fix that, we have a couple options:

1. Give contained levels an awareness of their containing levels, the approach currently in this PR. This is the _simplest_ change, but it includes introducing a fairly expensive (~800ms) SQL query to every DSL-defined `save` operation`.
2. Move the responsibility for syncing i18n onto the save operation on the containing level. This would be cheap, but a bit fragile, and involves a pollution of responsibilities that I don't love.
3. Refactor the syncing of dsl-defined data to happen not on save but on `sync-in`, like our other level content. This is probably the _best_ option, but the one that would require by far the most work. Additionally, our existing i18n sync doesn't have a concept of script-specific operations, so even that would have to be refactored to accommodate this new requirement.

### CODE REVIEW

**Comment by Hamms** [comment]
[Figure out how to only sync a subset of dsls.en.yml with crowdin](https://trello.com/c/UJOoFJuG/283-figure-out-how-to-only-sync-a-subset-of-dslsenyml-with-crowdin)

**Comment by Hamms** [comment]
Update to approach 3 above:

It seems like _any_ process that approaches DSL files from a script-first perspective is going to run into some issues; namely, that it turns out the relationship between the filenames and their content is a _lot_ more flexible than I had formerly thought. The files themselves contain all the relevant information for the level, but cannot always be easily found on the filesystem given just the level name (ie, the information contained in Script).

See for example https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/config/scripts/2-3/unplugged/2-3_Binary_match_1.match which is not only located in a nonstandard location, but has a nonstandard _filename_ (we would expect `name.parameterize.underscore` to produce `2_3_binary_match_1` in this situation).

**Comment by joshlory** [comment]
I'm not sure I 100% follow — how is "2-3 Binary Match 1" found if the naming is nonstandard?

If the `name` attribute in the DSL Defined level is all that matters, can we do a one-time rename pass to match all filenames to the `name` attribute, then nuke the name attribute?

**Comment by Hamms** [comment]
> I'm not sure I 100% follow — how is "2-3 Binary Match 1" found if the naming is nonstandard?

Because no where in our current system do we _try_ to find it by starting with the name and going to look for the file; everywhere we currently try to parse DSL files, we do it by grabbing all of the files and just parsing the content in them, regardless of name

> If the name attribute in the DSL Defined level is all that matters, can we do a one-time rename pass to match all filenames to the name attribute, then nuke the name attribute?

Possibly! But that would be a more comprehensive change to our DSL system than I'm comfortable making at this point

**Comment by dju90** [comment]
>Possibly! But that would be a more comprehensive change to our DSL system than I'm comfortable making at this point

What would get us to the point where we're comfortable making this change?

**Comment by Hamms** [comment]
closing in favor of https://github.com/code-dot-org/code-dot-org/pull/28548

**Pull request closed without merging**
