### PR TITLE
moved 2 JS files to be loaded later to improve performance of code.or…

### PR DESCRIPTION
**Pull request by hemabatra**
Moved the script calls for shared/js/details-polyfill/jquery.details.min.js, shared/js/details-polyfill/details-polyfill.js to be loaded at the bottom of the page instead of at the head.  This is a recommended practice for JS files. 

I added some lines to the index.haml file that had the details tag to test out the change since I was not able to find a page that is actually using it right now. 
%details
  %summary Copyright 1999-2014.
  %p - by Refsnes Data. All Rights Reserved.
  %p All content and graphics on this website are the property of the company Refsnes Data.

If you know of a page please let me know, I will gladly go test the changes on that page.  

I tested the changes I made on Chrome and FireFox and did not encounter any issues. 
I tried to install IE on my Ubuntu system, to test the change.  However, the latest version I could get was IE 8 and it did not work.  

I also tried a plugin people say works for testing, but I did not find it to be so. 

I created an HTML page with the same details tag and added the scripts jquery.details.min.js and details-polyfill.js after it.  It appeared to work. I have attached the file.  I was not able to add it as an HTML file, so the txt extension will need to be removed. 

[Details.html.txt](https://github.com/code-dot-org/code-dot-org/files/1042933/Details.html.txt)

### CODE REVIEW

**Comment by hemabatra** [comment]
Hi Will, 

When I was working on moving the JS files from pegasus/sites.v3/code.org/views/theme_common_head_before.haml to pegasus/sites.v3/code.org/views/theme_common_body_after.haml:
•	shared/js/details-polyfill/jquery.details.min.js 
•	shared/js/details-polyfill/details-polyfill.js

I started wondering if the script ‘cdn.optimizely.com/js/400912536.js'  could also be moved from theme_common_head_before.haml to theme_common_body_after.haml?

How should I verify that the move does not impact anything?

Thanks, 

Hema

**Comment by wjordan** [comment]
Some concerns:

- This script interacts with DOM elements and CSS styles. Applying it at the end of the HTML body could cause an (expensive) reflow operation, so we would need to be verify that it doesn't.
- The details polyfill contains associated CSS styles, which are still synchronously loaded in the head.
- The details-polyfill is [supported](http://caniuse.com/#feat=details) on all relevant browsers except IE, so tests on any browser other than IE aren't really relevant to this PR. We don't have any actual understanding this polyfill's behavior, until we've actually run it on IE which is the only browser that uses it.

In general I don't think this change is the right approach. I think it would be quicker and easier to just set this polyfill within an IE-only conditional, so that there's no impact at all to non-IE browsers related to this polyfill.

**Comment by wjordan** [comment]
> I started wondering if the script ‘cdn.optimizely.com/js/400912536.js' could also be moved from theme_common_head_before.haml to theme_common_body_after.haml?

No, Optimizely's [documentation](https://help.optimizely.com/Set_Up_Optimizely/Implement_the_snippet_for_Optimizely_Classic#3._Add_your_snippet_to_the_.3Chead.3E_tag_of_your_site) says that its script must load as early as possible to avoid potential page flashing when running experiments.

**Comment by hemabatra** [comment]
Thanks for the feedback. 
I will work on adding conditional statements to  load the polyfill css file and the 2 JS files /details-polyfill/jquery.details.min.js and /details-polyfill/details-polyfill.js when it is IE 11 or greater.

**Comment by hemabatra** [comment]
Reverted the original change, did not want to cause reflow operation. 
In addition to having all the files being loaded by theme_common_head_before, a check has been added to only load the details/polyfill files when the browser is IE.  The details and polyfill files are not needed on the other browsers. 

I  did test this change on Chrome/FireFox to make sure the jQuery and details-polyfill files were not loaded. 

The conditional statements that were originally used to check if the browser is IE is no longer supported. They stopped supporting that with IE 10.  
https://msdn.microsoft.com/en-us/library/hh801214(v=vs.85).aspx

I tried another way and it worked. 

I was not able to test this change with on an IE system with code.org.  I created a prototype to make sure the conditional statement worked and HTML5 details tag. I have attached my test page.  

[Details.html.txt](https://github.com/code-dot-org/code-dot-org/files/1046725/Details.html.txt)

Please let me know your thoughts.

**Comment by hemabatra** [comment]
These 3 files are not being used at all on the main page, I think we should move this to a page that is actually needs them in IE.  Would pegasus/sites/code.org/views/page_curriculum.haml be one that needs it?  I am not sure if there are others

**Comment by hemabatra** [comment]
@wjordan could you please provide me with your thoughts?

**Comment by wjordan** [comment]
Thoughts:

- #3015 is the original feature that required details polyfill. Tracking changes from that PR shows (at least some of) the many different places where we depend on the `<details>` element in our codebase.
- In order to consider moving this polyfill from the common header to specific page(s), we would need to be absolutely sure (by studying the code and tracing all references) that we have covered all cases. Based on the above PR, I'm not confident that we can be sure of this (and I don't think it's worth our time to track them all down).
- I don't like checking raw user-agents as a proxy for feature-detection, because they add extra maintenance burden (when new user-agents are released in the wild, you need to constantly review and update all of the user-agent-feature checks throughout your code). We should use feature-detection that tests the actual feature if at all possible, and we should leverage npm libraries that encapsulate this common knowledge whenever possible.
- Many polyfills contain exit-early feature-detection tests for native support of the features they're designed to polyfill, and there's often little-to-no performance impact of including them.


Taking a look at this feature from another angle, the details-polyfill currently in use is old/no longer supported, based on jQuery, requires an external css and has runtime cost even in the native-support case (due to the `$('details')` selector involved). However, there's a newer polyfill [`details-element-polyfill`](https://github.com/javan/details-element-polyfill) that appears to be more lightweight and self-contained, and shouldn't incur any runtime overhead.

To clean up this feature using our new apps-JS pipeline, we could add `details-element-polyfill` to `apps/package.json` and include this line in `theme_common_head_after.js`:

```
import 'details-element-polyfill';
```

**Comment by hemabatra** [comment]
Decided to go replace the 3 existing files for details-polyfill:
•	shared/js/details-polyfill/jquery.details.min.js
•	shared/js/details-polyfill/details-polyfill.js
         shared/css/details-polyfill.css

 with details-element-polyfill. 

PR# 15681

**Pull request closed without merging**
