### PR TITLE
Fetch additional published projects if necessary when View More is clicked

### PR DESCRIPTION
**Pull request by davidsbailey**
background: When we load the public gallery we fetch 100 published projects of each type.

Previously, the View More button just showed additional projects that were already loaded on the client, and then hid itself when there were no more to show.

Now, the View More button fetches more projects from the server when it runs out of projects on the client, and only hides itself when there are no more projects to show on the server or client.

fetch-more-published-projects

### CODE REVIEW

**Comment by caleybrock** [comment]
do we have any concern about loading forever on a page? Will the browser be able to handle that. Play Lab already has a ton of projects. Maybe we should have a max of ~500 or something?

**Comment by davidsbailey** [comment]
That's a great question @caleybrock about how the browser will handle a very long page full of images. I'm going to give a hand-wavy answer and say (1) this seems like something the browser could optimize for by swapping images that are way above the top of the screen/viewport out of memory (2) as you click View More many many times, the page will probably get slower before it totally crashes, giving the user some warning.

It will be hard to test this out prior to shipping this feature, and since few people will probably view more than 500 projects, I think a good plan would be to ship this then grab a slow laptop and see how it does scrolling to 1000 images against our production web site.

The best thing we can do for performance on this page is probably to optimize these thumbnail images the way @wjordan has us doing on the rest of our site -- currently these are 220 x 200px png images.

a related question is how we'd handle caching:

In theory, if the initial load of 100 projects of each type is cached for 1 minute, and the published_before date is determined by the contents of that response, and each subsequent published_before date is determined by the contents of the previous response, then we should be getting a lot of cache hits on these requests. 

As for the actual thumbnails, my next work item is to include a version id in the thumbnail image url, which will allow us to cache each individual thumbnail image forever, giving us great cache performance there.

**Comment by caleybrock** [comment]
Sounds good. I don't think it's unreasonable for people to try it. I can imagine a kid who published a project (a while ago) and then goes to the public gallery and just keeps loading more until they find it. That's probably a good argument to implement a search function in the gallery, but for now it'd be good to see how the browser handles it. Brendan also did some lazy loading of images on /learn we could think about copying too.

**Comment by davidsbailey** [comment]
@poorvasingal feature request: search field in the public gallery. what do you think?

**Pull request merged**
