### PR TITLE
[Weblab] Display warning dialog when disallowed HTML is found

### PR DESCRIPTION
**Pull request by maddiedierker**
Follow-up to #41366.

Before, when disallowed HTML was found in Weblab, we just removed it. Now, we will display a dialog when disallowed elements are detected, and they will be removed when that dialog is closed.

Screen Shot 2021-06-30 at 11 36 28 AM

@KylieModen and Dan will be updating the support article above to include information about what HTML is disallowed in Weblab.

## Links

- [STAR-1558](https://codedotorg.atlassian.net/browse/STAR-1558)

## Testing story

Adds/updates unit tests.

## Follow-up work

[STAR-1617](https://codedotorg.atlassian.net/browse/STAR-1617) (add storybook entries for new components created here and in #41366).

### CODE REVIEW

**Comment by KylieModen** [comment]
Can we wait to merge until Dan and I update the article?

**Comment by maddiedierker** [comment]
> Can we wait to merge until Dan and I update the article?

yep! just let me know when i can merge

**Review by epeach — APPROVED** [review]
LGTM - glad to see solid test coverage here!

**Comment by maddiedierker** [comment]
got the go-ahead from kylie that the support article has been updated, so merging this now!

**Pull request merged**
