### PR TITLE
Increase Archive time period to 15 months and Deep Archive to 3 years

### PR DESCRIPTION
**Pull request by sureshc**
We deliver CloudFront Real-Time HTTP Access Logs to an S3 Bucket where they can be searched via AWS Athena. Switch from Transitioning these log files to the S3 Intelligent-Tiering `Archive Access` tier (3-5 hours to Restore) from 3 months to 15 months to align with how long CloudWatch Metrics are retained. And increase the length of time from 6 months to 3 years when Objects are moved to the `Deep Archive Access` tier.

Note that we want to discourage Athena searches across wide date ranges due to the Athena pricing structure (we pay per GB of files scanned during each query execution).

## Deployment strategy

Note the drift between the template and the current configuration of the bucket
image

[This Stack Change Set](https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/changesets/changes?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A475661607190%3Astack%2FAccessLogs%2Fe0c55ee0-c88c-11eb-bf48-0a6e9e609c1f&changeSetId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A475661607190%3AchangeSet%2FAccessLogs-1e3erpmvnda-h5een9csl2q%2Fee716a2e-8f67-4589-aef6-5c38e89ebf3a) would potentially modify or replace a wide set of resources
image

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
Thank you, this will be a huge help!

**Comment by cat5inthecradle** [comment]
This is a 5x increase in the amount of data that we will be storing in Standard Tier storage, and likewise an increase in the data available to query.

What do you think about following this up with [INF-851](https://codedotorg.atlassian.net/browse/INF-851)

**Comment by davidsbailey** [comment]
@cat5inthecradle not sure if you intended your comment to be blocking, but I am curious if you have access to any estimates on how much we currently pay for Athena queries per year?

**Comment by davidsbailey** [comment]
ping! @sureshc @cat5inthecradle sounds like Darin's feedback is to tackle the pricing issue with a follow-up task. is there anything left blocking this PR?

I am pushing on this because there is a long lead time on it being useful -- if we want this data 12 months from now, presumably we need to change the expiration policy now.

**Review by cat5inthecradle — APPROVED** [review]

**Comment by cat5inthecradle** [comment]
Not blocking. Lets do it.

**Comment by davidsbailey** [comment]
hi folks - just checking if this is still on the list for this sprint?

**Review by cat5inthecradle — APPROVED** [review]

**Review by pablo-code-org — APPROVED** [review]

**Review by pablo-code-org — APPROVED** [review]

**Comment by cat5inthecradle** [comment]
Next step is to deploy this manually, once that is complete, we will merge the PR.

**Comment by davidsbailey** [comment]
@cat5inthecradle was this PR important to merge?

**Pull request closed without merging**
