### PR TITLE
Creates a oneoff script to purge (plaintext) emails of students from the DB.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @laurelfan

**Comment by Hamms** [comment]
have we verified that all student emails have been successfully hashed?

**Comment by ashercodeorg** [comment]
Yes.

```
SELECT COUNT(0) FROM users WHERE email IS NOT NULL AND email != "" AND (hashed_email IS NULL OR hashed_email = "");
+----------+
| COUNT(0) |
+----------+
|        0 |
+----------+
```

**Comment by Hamms** [comment]
In that case, LGTM!

Have we run the previous one-off script yet? If so, how long did it take?

**Comment by ashercodeorg** [comment]
No, it hasn't been run yet, as it did not make it into the DTP from yesterday (being in the PM DTT).

Not sure it'll get run tonight, as I may not want to be around to babysit it, should something go amiss.

**Comment by Hamms** [comment]
When we do, I'll be interested to hear how long it takes.

**Comment by ashercodeorg** [comment]
It seems safe to run with the script with intervals of 400K users. Though I didn't attempt to test the limit, I'd guess that an interval of 1M users might impact production slightly based on my seeing the query in `innotop` with 400K users.

**Pull request merged**
