### PR TITLE
[Finishes #98332908] setImageURL shouldn't resize

### PR DESCRIPTION
**Pull request by Bjvanminnen**
We would have API code call setImageURL. This would result on us hitting the onload that we still had floating around from design mode on the element, which does a resize. We don't want to hit this onload other than the once, so clear it out as soon as we hit it.

### CODE REVIEW

**Comment by joshlory** [comment]
Nit: maybe `delete backgroundImage.onload` but what you have is fine.  LGTM!

**Comment by Bjvanminnen** [comment]
Seems like there *might* still be an issue here, so I'm going to spend a little more time looking at this Monday.

**Comment by Bjvanminnen** [comment]
The original fix wasn't working, because over the course of run/reset we would apparently end up calling onPropertyChange for image. This would then create a new onload function. Each instance would only be called once, but because we could have multiple instances, we were still getting into cases where setting via the API would change the size.

New approach is that we only create our onload function when setting to a new URL. Tested the following cases:
- Set image via design mode. Resize. Change image via API. Image remains the same size.
- Set image via design mode. Set to a differently sized image. Image resizes

**Comment by Bjvanminnen** [comment]
Note: Diff looks bigger than it is. Really I'm just wrapping the onload = function() in an if block.

**Comment by islemaster** [comment]
LGTM.

**Pull request merged**
