### PR TITLE
increase selenium polling interval from 0.2s to 1s when waiting with timeout

### PR DESCRIPTION
**Pull request by davidsbailey**
`too many connection resets` is by far the most prevalent selenium error in our circleci runs:
```
Davids-MacBook-Pro-2:~/src/cdo (notify-organizers)$ bin/circle/search-circle-builds --start 25514 --end 26514 --grep "first selenium error" --whole-lines | grep "first selenium error"  | cut -d : -f 2- | cut -d '(' -f 1 | sort | uniq -c | sort -r -n -k 1
 622  too many connection resets 
 256  connection refused: localhost:4445 
 248  timed out after 120 seconds 
 104  undefined method `[]' for nil:NilClass 
  80  expected: value != "Bad Gateway"
  48  undefined method `map' for nil:NilClass 
```

Internet research suggests this problem is correlated with the network stack being overloaded. This PR attempts to alleviate the problem by making 5 times fewer requests while waiting for things to happen in the browser.

I can't find the selenium docs for this, but here is where Selenium::WebDriver::Wait is defined on my system: `/Users/dsb/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/wait.rb`
```
module Selenium
  module WebDriver
    class Wait
      ...
      # @option opts [Numeric] :timeout (5) Seconds to wait before timing out.
      # @option opts [Numeric] :interval (0.2) Seconds to sleep between polls.
      ...
      def initialize(opts = {})
        @timeout  = opts.fetch(:timeout, DEFAULT_TIMEOUT)
        @interval = opts.fetch(:interval, DEFAULT_INTERVAL)
        ...
```

### CODE REVIEW

**Comment by davidsbailey** [comment]
first 3 circle runs:
- https://circleci.com/gh/code-dot-org/code-dot-org/26541
- https://circleci.com/gh/code-dot-org/code-dot-org/26543
  - 1 too many connection resets (due to end of file reached - EOFError)
  - 1 too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout)
- https://circleci.com/gh/code-dot-org/code-dot-org/26544
  - 1 too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout)
  - 1 too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout)

**Comment by davidsbailey** [comment]
Of the 3 circle runs, two of them had 2 `too many connection resets` errors.

Over the past 2 days, we've had 474 circleci runs that ran UI tests, with 66 runs containing "too many connection resets" including:
- 22 circle runs with 20+ occurrences "too many connection resets" (mostly failing)
- 43 circle runs with 1-3 occurrences (mostly passing)
- 1 outlier not in the above buckets (14 occurrences)

So most likely this PR isn't helping as the 3 circle runs appear to fit the existing curve. It's worth noting I may have seen more failures since I ran against all browsers, but that doesn't change my conclusion.

**Comment by islemaster** [comment]
That's too bad.  Is there any correlation between the `too many connection resets` error and which features/steps are running at the time?  Your approach here seems reasonable but if it's one of 13 possible problem points maybe one of the others is the primary issue.

**Comment by davidsbailey** [comment]
`too many connection resets` appears not to correlate with the particular test case very much at all. here are the repeat offenders over the last 2 days:

```
Davids-MacBook-Pro-2:~/src/cdo (notify-organizers)$ bin/circle/search-circle-builds --start 25514 --end 26514 --grep "too many connection resets"  --whole-lines | grep "too many connection resets" | cut -d ' ' -f 1 | sort | uniq -c | sort -r -n -k 1
  28 ChromeLatestWin7_applab_scenarios
  25 ChromeLatestWin7_hourOfCode_signedIn
  23 ChromeLatestWin7_netsim_lobby
  23 ChromeLatestWin7_maze2
  23 ChromeLatestWin7_maze
  23 ChromeLatestWin7_hourOfCode
  23 ChromeLatestWin7_droplet
  22 ChromeLatestWin7_videoplayer
  22 ChromeLatestWin7_sharepage
  22 ChromeLatestWin7_plc_courseUnitNavigation
  22 ChromeLatestWin7_multi
  22 ChromeLatestWin7_match
  22 ChromeLatestWin7_legacyShareRemix
  22 ChromeLatestWin7_jigsaw2
  22 ChromeLatestWin7_jigsaw
  22 ChromeLatestWin7_hocReset
  22 ChromeLatestWin7_functionEditor
  22 ChromeLatestWin7_flappydrag
  22 ChromeLatestWin7_farmer
  22 ChromeLatestWin7_embeddedBlocks
  22 ChromeLatestWin7_disallowedsharing
  21 ChromeLatestWin7_flappy
  21 ChromeLatestWin7_dropdown
  21 ChromeLatestWin7_disableToolboxArtist
  20 ChromeLatestWin7_disableToolboxMaze
  19 ChromeLatestWin7_copypaste
  14 ChromeLatestWin7_contractEditorSections
  10 ChromeLatestWin7_stepMode
   3 ChromeLatestWin7_gamelab_levelOptions
   2 ChromeLatestWin7_starwars
   2 ChromeLatestWin7_projects
```

I'll keep this open for now, but I am going to pursue a different approach for catching and retrying the request.

**Comment by davidsbailey** [comment]
I've kicked off 3 more circle runs:
- https://circleci.com/gh/code-dot-org/code-dot-org/26590
- https://circleci.com/gh/code-dot-org/code-dot-org/26591
  - 1 too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout)
- https://circleci.com/gh/code-dot-org/code-dot-org/26592 --> bad gateway

**Pull request closed without merging**
