### PR TITLE
Fix crowdsourced hints

### PR DESCRIPTION
**Pull request by laurelfan**
- fix the page so it even loads
- load the solution view in an iframe instead of in a div so it works with the in-page scrolling
- add testing
- minor refactoring
- remove fb-comments because it doesn't work (for one, using the URL as a key isn't a good idea because the url is not a canonical representation of what you are commenting on -- ie, it's not the same hint, wrong solution, etc.)

### CODE REVIEW

**Comment by laurelfan** [comment]
test (see if github notifies me)

**Comment by tanyaparker** [comment]
Not sure how to test locally? http://localhost.studio.code.org:3000/add_pop_hint/0 redirects me to code.org/hints, and I'm signed into a teacher account.

**Comment by tanyaparker** [comment]
Oh is it because it's using local data and because there aren't any levels w/ lots of failed attempts, my idx is < 0?

I assume people won't ever run into this on production because we have tons of levels to add hints for (unless we reset)? Will they get redirected if they add a hint for every attempted level? I think it'd be confusing to keep getting redirected and not show them an error message.

**Comment by laurelfan** [comment]
The redirect happens only when there are no "frequent unsuccessful level sources" at all so is not going to happen in production.

To populate your local db with unsucessful level source data, edit this line: https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/lib/tasks/seed.rake#L155 to be `freq_cutoff = 1` and then run `rake seed:frequent_level_sources` (in dashboard directory).

**Comment by tanyaparker** [comment]
Ah, cool! Everything looks good to me. Thanks for fixing! :)

**Comment by laurelfan** [comment]
oh, and the crowdsourced hint system could definitely use some redesigning... I just didn't really want to get in to it beyond just getting it to work at all at this point.

**Comment by tanyaparker** [comment]
Agree! I'll add it to our backlog

**Pull request merged**
