### PR TITLE
manually fix a few violations of Style/OptionalBooleanParameter

### PR DESCRIPTION
**Pull request by Hamms**
I'm creating this PR which fixes a subset of violations just as a preview of what fixing this rule looks like in general. There's no autocorrection available, so before I invest any significant amount of time in manual fixes, I want to get feedback from folks on whether or not they'd be in favor of applying this rule across the codebase.

This rule:

> Checks for places where keyword arguments can be used instead of boolean arguments when defining methods. `respond_to_missing?` method is allowed by default. These are customizable with `AllowedMethods` option.

My understanding is that the biggest motivation for the rule is to improve readability when calling the affected methods; consider for example 

```ruby
state = get_us_state_abbr_from_name(state, true)
```

Versus:

```ruby
state = get_us_state_abbr_from_name(state, include_dc: true)
```

Notably, it only applies to optional positional arguments which accept boolean values, presumably because more complex values are generally more readable, and provide more contextual information from which a developer can reasonably infer what the argument represents.

What do  y'all think? I'm personally in favor of code that's more explicit and more verbose, but this does seem particularly nitpicky, even for a Style rule. Alternatively, if folks aren't in favor of us ever enabling this rule, we could instead simply promote the entry which disables it from `.rubocop_todo.yml` to `.rubocop.yml`

## Links

- https://docs.rubocop.org/rubocop/cops_style.html#styleoptionalbooleanparameter
- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/OptionalBooleanParameter
- https://stackoverflow.com/a/67391985/1810460
- https://www.rubyinrails.com/2021/12/20/define-keyword-arguments-when-defining-methods-with-boolean-arguments/

## Testing story

Relying on existing tests to verify that all uses of these methods have been updated to use the new method signature.

## Follow-up work

If this change looks good, I'll start slowly fixing these violations in a few batches as I have time, as I'm doing with the rest of the rubocop rules.

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]

**Review by cat5inthecradle — COMMENTED** [review]
```diff
- approvePullRequest(pull_request_id, true)
+ approvePullRequest(pull_request_id, withEnthusiasm: true)
```

Love the example changes, but I do wonder what the user experience is like. Does this basically forbid the `method(required_argument, optional_boolean = false)` syntax, which doesn't require the caller to explicitly name the argument? Does the `... optional_boolean: false)` syntax require the caller to specify the argument name?

**Comment by Hamms** [comment]
Yes, precisely! This rule enforces an explicit, verbose style. I do generally prefer that style myself, but I think there's definitely an argument to be made that we might not necessarily want to enforce it _everywhere_

**Comment by Hamms** [comment]
Note that if we do enable the rule globally, the experience of defining an exception isn't all that bad. Like all Rubocop rules, it can be disabled with a comment; and because the rule only checks the definitions of methods and not invocations, it only needs to be disabled once rather than for every use.

If do we find that there are particular methods for which we really don't want to ask the callers to specify the argument name, we will still have the option of doing so, it'll just be a little messy.

**Comment by cat5inthecradle** [comment]
I should have read your slack explanation! Gonna paste it here because it clarified this for me. I think it's worth doing for the readability improvement.

> There's a rubocop rule which specifies that when you have an optional parameter that accepts boolean values, rather than defining it as an optional positional argument like so:
> ```
> def some_method(bar = false)
>   puts bar
> end
> ```
> You should instead use keyword arguments like so:
> ```
> def some_method(bar: false)
>   puts bar
> end
> ```
> So that the method can be invoked in a way that makes it a little more clear what's actually happening. Ie, some_method(bar: true) rather than just some_method(true) (edited)

**Pull request merged**
