### PR TITLE
I18n sync Down & Out 05/07

### PR DESCRIPTION
**Pull request by Hamms**

### CODE REVIEW

**Comment by Hamms** [comment]
I suspect the massive diff here is a side effect of https://github.com/code-dot-org/code-dot-org/pull/22139

Possibly because I generated that PR on my local machine and this one on the i18n machine? I'll investigate

**Comment by Hamms** [comment]
Looks like I mucked something up with the "fix newline issues" sync (https://github.com/code-dot-org/code-dot-org/pull/22131); I ran it with the `update_without_changes` option, but it still seems to have affected our translations.

I'm going to roll back the changes in that sync and try again

**Comment by tanyaparker** [comment]
So I'll wait to review changes after #22264 is applied?

**Comment by Hamms** [comment]
Sort of the other way around, actually!

This massive diff is the result of me applying a formatting change similar to the one in #22264 but doing it wrong; I tried to do it in such a way that the translations wouldn't get discarded, but some of them got discarded anyway (current working theory is that the formatting change caused strings which had previously been flagged as duplicates to no longer be).

So I'm in the process of figuring out exactly what went wrong with that sync and how to fix it, after which point I should be able to do another sync out with much fewer changes and _that_ will be what I'll want you to review.

And then once I do that I'll be able to apply the formatting change in #22264 correctly, too

**Comment by tanyaparker** [comment]
Ah, got it! Ok I'll stay tuned until that sync with fewer changes. :)

**Comment by Hamms** [comment]
Closing in favor of https://github.com/code-dot-org/code-dot-org/pull/22327

**Pull request closed without merging**
