### PR TITLE
UploadImageDialog: disable save before upload

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Grays out the save button on the UploadImageDialog when the file is uploading. I didn't realize I needed to wait and thought I had a bug when testing a feature using this. 🙃 

https://user-images.githubusercontent.com/46464143/141513176-33a779c5-e1dc-4693-b4e5-e174eb338143.mov

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by tim-dot-org — APPROVED** [review]

**Review by tim-dot-org — CHANGES_REQUESTED** [review]
oh wait, maybe an indicator that shows something is uploading, like a spinner or just "uploading..."

**Review by davidsbailey — APPROVED** [review]
I tried this out, and this is what I see if i click cancel when prompted to select a file. could be worth a quick fix if there is one: 
Screen Shot 2021-11-12 at 10 48 13 AM

otherwise LGTM!

**Comment by bethanyaconnor** [comment]
Added a spinner!

https://user-images.githubusercontent.com/46464143/141540923-eec24c71-b388-4ced-82a7-bfa810a7f8a6.mov

**Comment by bethanyaconnor** [comment]
@davidsbailey strange...I can't repro that. This is what I did -- am I doing something different than what you're describing?

https://user-images.githubusercontent.com/46464143/141541092-5266836b-7480-444a-8179-1ca2b74ddb99.mov

**Review by tim-dot-org — APPROVED** [review]

**Comment by davidsbailey** [comment]
> @davidsbailey strange...I can't repro that. This is what I did -- am I doing something different than what you're describing?

oops -- yes, when I do what you show in the video I cannot repro. here's how I can repro:
1. click choose file, then select a large file --> fails with reasonable error
2. click choose file again, then click cancel  --> shows weird JSON error

**Comment by bethanyaconnor** [comment]
Thanks @davidsbailey I can repro that! It was happening because it was a change from a file to no file and was trying to upload an undefined file -- which gave some weird error. The confusing error message is from the backend but I just changed this component to not even try uploading an undefined file

**Pull request merged**
