### PR TITLE
Forum: verified teachers go into a group upon forum sign-in (second attempt)

### PR DESCRIPTION
**Pull request by breville**
When signing into the Discourse forum, verified teachers are added to the existing forum group "Verified-Teachers", and then we can have categories (which are collections of topics) only visible to that group.

Similarly, non-verified teachers are actively removed from the "Verified-Teachers" group upon forum sign-in.

`add_groups` and `remove_groups` are documented briefly at https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045.

Second attempt after https://github.com/code-dot-org/code-dot-org/pull/20750.  This second attempt updates our copy of SingleSignOn to include these newer accessors.

### CODE REVIEW

**Comment by mehalshah** [comment]
Do we need to add them to the group when they become verified teachers?

**Comment by breville** [comment]
@mehalshah great question.  Unless @tanyaparker thinks it's okay for users to have to sign back into the forum to be added to a group, we should probably add them programmatically.  It looks like there is an API for this (http://docs.discourse.org/#tag/Groups%2Fpaths%2F~1groups~1%7Bgroup_id%7D~1members.json%2Fput) though I'm not sure what version of Discourse we'll need to be using.   

Given troubles with this PR actually working on our current (old) version of Discourse, we could look at using this API as an alternative to the sign-in approach in this PR.

**Comment by breville** [comment]
@wjordan Thanks for finding this!  I had wondered the same, but [this post](https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045) documenting `add_groups` is apparently dated February 2014 so I was sure we already had it.

**Comment by wjordan** [comment]
> ##### [Updates](https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045#heading--updates):
> ###### 11-Nov-2016
> - Added note on add_groups and remove_groups

**Comment by breville** [comment]
Made an update to this PR so that we actively remove non-verified teachers from the forum group too, upon forum sign-in.  In offline discussions, we decided that it's okay to require a fresh sign-in for a teacher to join or leave the forum group.

**Pull request merged**
