### PR TITLE
[skip ui] Try to fix the plc unit tests

### PR DESCRIPTION
**Pull request by mehalshah**

### CODE REVIEW

**Comment by mehalshah** [comment]
Possible fix for the plc unit tests. Move from after_create to after_save. It's worked in circle on the first try

**Comment by joshlory** [comment]
I'm not sure I understand the fix.  Are there cases where `after_create` wasn't getting called?

Hard to know that this is the right fix without a consistent repro.

**Comment by mehalshah** [comment]
I suspect that after_create wasn't always getting called in the unit tests, and could repro it some of the time by blowing up my test db, and running tests locally. I haven't been able to repro it locally with this change

**Comment by joshlory** [comment]
LGTM, worth trying this fix!

**Pull request merged**
