### PR TITLE
Set no-cache headers on dance puzzle 13

### PR DESCRIPTION
**Pull request by davidsbailey**

### CODE REVIEW

**Comment by davidsbailey** [comment]
background: this fixes the problem where if you go directly to dance puzzle 13 without previously having obtained a session cookie, you get the wrong project id and cannot save your work.

this problem occurred due to the misconception that allowing session cookie and storage_id cookie through in http_cache.rb "disables caching". this is true only when users can be uniquely identified by these cookies. unfortunately, users without either of these cookies cannot be differentiated, so the server must set headers to disable caching on this level as done in this PR.

**Review by sureshc — APPROVED** [review]
Looks great!

In the future, could we use properties on the Script and Level models that are stored in the database to determine whether a script or level should be cacheable?

**Comment by davidsbailey** [comment]
Thanks for reviewing! We could do it based on the level type. There is a bit of complexity though -- to see how we choose which level to show, take a look at https://github.com/code-dot-org/code-dot-org/blob/3297d4062172e0875f66dd3a295be14aaad808df/dashboard/app/controllers/script_levels_controller.rb#L325-L360

I actually started down that path, but it seemed like I'd have to do some refactoring, and potentially add some db queries, in the process of moving the `select_level` calls around.

Because we'd have to explicitly list the un-cacheable script levels in the http_cache config anyway, I think I actually prefer the current approach though, since it makes it super clear which script levels it applies to, and we are unlikely to add more than 1-2 script levels to this list per year. I'm open to being convinced otherwise, though.

**Comment by davidsbailey** [comment]
Verified that the original issue is fixed on staging.

**Pull request merged**
