### PR TITLE
clean up Redshift import

### PR DESCRIPTION
**Pull request by sureshc**
Implementing feedback from #32992 

### Background

Epic - https://codedotorg.atlassian.net/browse/INF-242

## Testing story

Manually tested on `production-daemon` by pasting this updated code in the dashboard console and running it on a simple test table.
```
[production] dashboard > RedshiftImport.complete_table_import(['dashboard_production'])
Dropping existing table dashboard_production.test_queries and renaming newly imported _import_test_queries.
=> ["dashboard_production"]
```

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by wjordan — APPROVED** [review]
:+1: looks good!

**Comment by sureshc** [comment]
@wjordan - Unit tests (specifically `shared/test/test_dms.rb`) are failing because `CDO::DMS` now has a dependency on the `pg` gem, a native gem we only install on `production-daemon` and `production-console`.  Any thoughts on the best we to re-use [the conditional logic in our Gemfile](https://github.com/code-dot-org/code-dot-org/blob/d02ac31e08ee383406de2e494c8a0526e3e76ca1/Gemfile#L326-L334) to conditionally eliminate that dependency in the `Redshift` and `RedshiftImport` classes on other environments, such as development, Continuous Integration, and `test`?

**Comment by sureshc** [comment]
@wjordan - I ended up having to require `cdo/redshift and `pg` in each method that uses `RedshiftClient`, which is not a great solution.  Any alternatives to this approach?

**Comment by wjordan** [comment]
> @wjordan - I ended up having to require cdo/redshift and pgin each method that usesRedshiftClient`, which is not a great solution. Any alternatives to this approach?

It should work if you move this require: https://github.com/code-dot-org/code-dot-org/blob/c5ef61da90314845b802ab3600c4850b90e58639/lib/cdo/redshift.rb#L1

into the `initialize` method just above where the `PG::Connection` class is referenced: https://github.com/code-dot-org/code-dot-org/blob/c5ef61da90314845b802ab3600c4850b90e58639/lib/cdo/redshift.rb#L36

You also don't need to `require 'pg'` anywhere from `redshift_import.rb`, that should be handled internally within the `redshift.rb` only.

**Comment by sureshc** [comment]
Thanks!  That's much simpler.

**Pull request merged**
