### PR TITLE
Specify `twilio-ruby` Gem Version

### PR DESCRIPTION
**Pull request by Hamms**
Specifically, pin us to the latest pre-6.0 version. We're currently running version 5 and version 6 contains some breaking changes that we are neither prepared for nor desire. To avoid other updates accidentally attempting to update this Gem, we explicitly specify which version works for us.

Also update to the latest 5.x version, to pick up some minor non-breaking changes and bugfixes.

## Links

- https://github.com/twilio/twilio-ruby/releases/tag/6.0.0
- https://github.com/twilio/twilio-ruby/releases/tag/5.77.0

## Testing story

Relying on [existing tests](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/test/controllers/sms_controller_test.rb) to verify that this does not represent any change in functionality. Verified that these tests fail as expected on twilio 6.x.

### CODE REVIEW

**Comment by sureshc** [comment]
With all the stubbing and mocking of the Twilio SDK, how do we know whether the new gem actually works? Do we need an integration test? Or do the standard Ruby libraries we use to stub/mock prevent us from stubbing SDK methods with the wrong arguments, wrong method names, wrong return types, etc.?

**Review by sureshc — APPROVED** [review]

**Comment by Hamms** [comment]
That's a great question, and I'm not sure of the answers; my strategy so far has been to rely on our existing automated testing, but you're right that most of our testing is not testing Twilio itself. @code-dot-org/studentlearning do any of y'all have thoughts here? Is it safe for me to merge this based solely on our existing tests passing, or should I do some more testing of my own to verify that everything remains working here?

**Comment by bencodeorg** [comment]
@Hamms I just pulled your branch and successfully sent an applab project link to my phone via the Applab share dialog. I think that's probably sufficient basic manual testing?

**Comment by Hamms** [comment]
Hah, agreed! Thanks for doing that legwork for me

**Pull request merged**
