### PR TITLE
Fix UI tests that fail on IE11 by disabling pre-render

### PR DESCRIPTION
**Pull request by breville**
Yet to verify this fix (running against localhost using SC tunnel is having some performance issues) but presented for your consideration.

The problem we're seeing with IE11 and Selenium is described at http://stackoverflow.com/questions/40229415/how-can-i-reconnect-selenium-to-ie11-after-navigating-with-the-prerender-resourc

### CODE REVIEW

**Comment by wjordan** [comment]
This approach eliminates prerendering UI test coverage across all browsers, which exposes us to the risk that our UI tests would not catch if/when a new browser version changes its prerender implementation in a way that breaks on our site.

I'd be more in favor of either:
1. always disable prerender in IE11 (conservative- only use prerender where we maintain UI test coverage for it); or
2. disable prerender in IE11 UI tests only (slight risk- reduced UI test coverage in IE11 only)
3. revert the prerendering feature for now until the IE11 driver supports it (most conservative)

**Comment by breville** [comment]
@wjordan Given how many hours it took to make little progress on this PR last night, I suggest we revert this feature for now until we know it will pass on tests. @davidsbailey as dotd concurs.

**Comment by islemaster** [comment]
When we do put prerendering back in, I'm in favor of option 1, disabling it on IE until we figure out how to test it.

**Comment by wjordan** [comment]
agree with both comments above 👍

**Pull request closed without merging**
