### PR TITLE
Add poetry banner

### PR DESCRIPTION
**Pull request by TurnerRiley**
Sets up the responsive poetry banner behind a variable flag modeled after the strategy used in [this PR](https://github.com/code-dot-org/code-dot-org/pull/55780/files#diff-800f47fe82d55396a0472e64d0122b0c97fde37774d01e3ee98f3c4c8239f302R1) for the 2024 PL banner. The banners are set to show for now but that can be toggled off by merging a tiny PR to flip `display_poetry_banner` to `false`.

### /csc (redirects to /educate/csc) and /educate/csc
educate_csc

### /student/elementary
student-elementary

### /naipi
naipi

### /teach
teach

### /educate/curriculum/elementary-school
elementary-school

## Banner is responsive
https://github.com/code-dot-org/code-dot-org/assets/56283563/ef41285f-fa30-42f9-ab58-2be9aa662a32

## Right-to-left look
rtl

## Links
Jira ticket: [here](https://codedotorg.atlassian.net/jira/software/c/projects/ACQ/boards/64?assignee=60d62161f65054006980bd71&selectedIssue=ACQ-1572)

## Testing story
Locally tested in multiple browsers, right-to-left, and in different screen sizes.

### CODE REVIEW

**Comment by dmcavoy** [comment]
Hey @TurnerRiley  - These are looking great! For the /teach page one I think we should actually put poetry where the PL banner (with the superhero) is and then move that banner to where the AI 101 banner is and then remove the AI 101 banner.

**Comment by dmcavoy** [comment]
Also wondering if on the CSC we should bump it below the first section on the page.

**Review by kelbyhawn — APPROVED** [review]
Looks great! 🎉

**Comment by TurnerRiley** [comment]
> Also wondering if on the CSC we should bump it below the first section on the page.

@dmcavoy Made both updates and updated the screenshots above! Let me know if this looks good!

**Comment by dmcavoy** [comment]
Looking great. Thank you!

**Pull request merged**
