### PR TITLE
refactor cloudformation templates to auto-indent

### PR DESCRIPTION
**Pull request by cat5inthecradle**
Refactoring our component inserter to auto-indent. All of our components are lists of resources, so the indentation level is always 2 spaces. This change makes our component templates a little easier to work with. I also added some whitespace to split up components and other minor quality of life changes.

## Testing story

Verified the staging template by running validation commands, these revealed errors which were fixed. Each now indicates no actual stack changes.

`VERBOSE=1 bundle exec rake stack:validate RAILS_ENV=staging`

`VERBOSE=1 bundle exec rake stack:validate RAILS_ENV=test`

`VERBOSE=1 bundle exec rake stack:validate RAILS_ENV=production`

## Deployment strategy

This could absolutely have inserted a difficult-to-detect syntax error. I'm going to review this a couple of times, and I'm planning on watching as it hits each environment.

### CODE REVIEW

**Review by Hamms — COMMENTED** [review]
The high-level approach sound great and the testing strategy makes sense, but it's not clear to me how much risk this change carries. What would the consequences be of other uncaught syntax errors?

**Comment by cat5inthecradle** [comment]
> The high-level approach sound great and the testing strategy makes sense, but it's not clear to me how much risk this change carries. What would the consequences be of other uncaught syntax errors?

I'm discovering errors when performing the validate step for the three environments, fixing those now.

Risks are:
- template is invalid and we waste a deployment attempt (this is what I've been fixing)
- template is valid but wrong, leading to the unintentional editing/deletion/recreation of a resource (my tests so far indicate no actual changes detected)

Assuming my validation commands are valid, and I'm not missing an edge case, this should be pretty safe.

**Comment by cat5inthecradle** [comment]
resetting your review because there are some issues I'm working out

**Comment by cat5inthecradle** [comment]
There are a large number of modifications listed for prod:

```
Pending update for stack `autoscale-prod`:
Modify AMIac233 [Custom::AMIManager] Properties Replacement: Conditional (InstanceId)
Modify ASGCount [Custom::CountASG] Properties Replacement: Conditional (LaunchConfiguration)
Modify CPUScalingPolicy [AWS::AutoScaling::ScalingPolicy] Properties Replacement: Conditional (AutoScalingGroupName)
Modify ClassroomScaleDown [AWS::AutoScaling::ScheduledAction] Properties Replacement: Conditional (AutoScalingGroupName)
Modify ClassroomScaleUp [AWS::AutoScaling::ScheduledAction] Properties Replacement: Conditional (AutoScalingGroupName)
Modify FastSnapshotRestore [Custom::FastSnapshotRestore] Properties Replacement: Conditional (ImageIds)
Modify FrontendLaunchConfig [AWS::AutoScaling::LaunchConfiguration] Properties Replacement: True (ImageId, UserData)
Modify Frontends [AWS::AutoScaling::AutoScalingGroup] UpdatePolicy, CreationPolicy, Properties Replacement: Conditional (MaxSize, DesiredCapacity, MinSize, , , LaunchConfigurationName)
Modify WebServerAMI [AWS::EC2::Instance] Properties Replacement: Conditional (UserData)
Modify WebServerHookEventPermission [AWS::Lambda::Permission] Properties Replacement: Conditional (SourceArn)
Modify WebServerHookEventRule [AWS::Events::Rule] Properties (EventPattern)
Modify WebServerHook [AWS::AutoScaling::LifecycleHook] Properties Replacement: Conditional (AutoScalingGroupName)
Modify WeekendScaleDown [AWS::AutoScaling::ScheduledAction] Properties Replacement: Conditional (AutoScalingGroupName)
Modify WeekendScaleUp [AWS::AutoScaling::ScheduledAction] Properties Replacement: Conditional (AutoScalingGroupName)
```

Need to see what this is about.

**Comment by cat5inthecradle** [comment]
Found the issue - the `indent` function was adding extra spaces, which was editing some userdata scripts. Validating for production now also shows no changes.

**Review by Hamms — APPROVED** [review]
LGTM! The validation process in particular makes me feel much better about the potential for risk. Thanks!

**Comment by cat5inthecradle** [comment]
I'll revisit this after INF-668

**Comment by cat5inthecradle** [comment]
Too many conflicts to easily resolved, needs a dedicated chunk of time too just reimplement this in a new branch off staging.

**Pull request closed without merging**
