### PR TITLE
Unrevert "Show a React Dialog (placeholder for Animation Picker)"

### PR DESCRIPTION
**Pull request by islemaster**
Reverts code-dot-org/code-dot-org#7736

This change (specifically, moving the Dialog component from code-studio to apps) broke the staging build, even though it doesn't break my local build or the Circle/Travis builds.  Will re-merge once I figure out why.

### CODE REVIEW

**Comment by islemaster** [comment]
Here's the relevant bit of the build log:

```
> @cdo/code-studio@0.0.1 clean-js [CDO]/code-studio
> rm -rf build/js

[23:16:27] Built build/js/embedVideo.js
[23:16:35] Built build/js/plc.js
[23:16:38] Error Cannot find module '@cdo/apps/templates/Dialog.jsx' from '[CDO]/code-studio/src/js/components'
[23:16:39] Built build/js/react-only.js
[23:16:39] Built build/js/makerlab.js
+-----------------------------+
| code-studio js build failed |
+-----------------------------+
```

**Comment by islemaster** [comment]
I'm really not sure what went wrong - why this would fail on Staging but work on Circle, Travis, and local.

One theory is that my move/rename of dialog.jsx (in code-studio) to Dialog.jsx (in apps) was problematic because only the capitalization changed (and the path, but not 100% sure that matters).  I've renamed it to DialogComponent.jsx here just to make sure that's not a factor, and we can rename it back after a while.

**Comment by islemaster** [comment]
Open to other theories on why this would break.

**Comment by Bjvanminnen** [comment]
A change in case was going to be my first guess, except that you're on Linux. Not sure what else might be different. Did you do a clean and build? (could be it still had a local copy of the old file)

**Comment by Bjvanminnen** [comment]
lgtm

**Pull request merged**
