### PR TITLE
Split Applab Integration test bundle

### PR DESCRIPTION
**Pull request by ajpal**
I'm not confident this is the best way to do this, but I just split the files in half between `applab1` and `applab2` and changed the test script to run them separately.

### CODE REVIEW

**Comment by islemaster** [comment]
Can we get any before/after stats out of Karma and Webpack about these bundle sizes?  If our hypothesis is that smaller bundle sizes will lead to fewer out-of-memory errors, it'd be good to at least validate that this change results in smaller bundle sizes.

We've also got some tools for visualizing the contents of those bundles.  I've used it with Karma in the past, although I remember needing to hack it into place a bit.  That might be useful.

**Comment by davidsbailey** [comment]
Yeah, considering that we only recently split applab apart from gamelab due to the same kinds of errors, I'm thinking that these ongoing failures are an indication that further splitting in the same way is not likely to be effective. Let's make it a goal to get smaller bundles before submitting a speculative fix.

**Comment by ajpal** [comment]
Merging this now to unblock some PRs, and working on a more longer-term fix as well. 
That will include dynamically requiring apps in runLevelTest, and moving non-level tests out of the bundle

**Review by islemaster — APPROVED** [review]
Discussed in person - it's a good idea to merge this speculative split since it passed Drone and might unblock at least three engineers trying to get applab-related changes merged, then continue investigation (better split heuristics, root causes, breaking out non-leveltest integration tests) this sprint.

**Comment by davidsbailey** [comment]
No worries, makes sense!

**Pull request merged**
