### PR TITLE
only scoop files in pegasus and dashboard for a content push

### PR DESCRIPTION
**Pull request by tanyaparker**
The content-push script is used by the dev of the day to scoop content edits from non-engineers. Content can be scooped from dropbox and gsheet changes (which only affect pegasus) or levelbuilder (which only affects dashboard). Instead of scooping all file changes from root, which can accidentally scoop files sitting on the staging machine, the script now only scoops files from pegasus and dashboard.

### CODE REVIEW

**Comment by davidsbailey** [comment]
Hi Tanya,

I like where you're going with this! However it looks like the info returned by `git status` will not accurately reflect the files which are going to be committed. You could extract `CONTENT_PATHS` and call

```
"git status #{CONTENT_PATHS}"
"git add -A #{CONTENT_PATHS}"
"git commit #{CONTENT_PATHS} -m ..."
```

updating the params to `git commit` is needed to make sure that other things already `git add`ed on staging aren't silently included in the commit with this new approach. Here is a quick test script you could run from the repo root to make sure everything is working properly:

```
touch pegasus/A
touch dashboard/B
touch C
touch D
git add D
bin/content-push # A and B are listed and committed
git status # C and D are listed. D is staged for commit.
```

Hopefully this is not too much more than you bargained for?

**Comment by davidsbailey** [comment]
Oops, I realized that test script might actually commit and push A and B to staging, so you might not want to run that exactly but you get the idea!

**Comment by tanyaparker** [comment]
Good call, that's definitely more robust. Tested it works with your scenario.

**Comment by davidsbailey** [comment]
Hi Tanya, Sorry I missed your updates. I think the repetition of "dashboard pegasus" will make it too easy to update the string in only 1 or 2 out of 3 places. Can you please extract it into a constant? Here is one way:

```
CONTENT_PATHS = 'dashboard pegasus'
system("git status #{CONTENT_PATHS}")
...
```

**Comment by tanyaparker** [comment]
@davidsbailey for sure!

**Comment by davidsbailey** [comment]
Nice. LGTM!

**Pull request merged**
