### PR TITLE
Removing clickable divs on three components

### PR DESCRIPTION
**Pull request by hannahbergam**
These are one line changes each- the only difference being the box shadow, which is a design-approved direction. Fun fact- I was able to use the translated storybook stories to look at these!!!

FreeResponseDetailsDialog
Before:
Screen Shot 2022-12-13 at 10 18 37 AM

After:
Screen Shot 2022-12-13 at 10 19 06 AM

MultipleChoiceDetailsDialog
Before:
Screen Shot 2022-12-13 at 10 26 24 AM

After:
Screen Shot 2022-12-13 at 10 50 06 AM

MatchDetailsDialog
Before:
Screen Shot 2022-12-13 at 10 23 44 AM

After:
Screen Shot 2022-12-13 at 10 51 02 AM

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by megcrenshaw — APPROVED** [review]
That was easy! Just to clarify: we have design approval to *keep* the box shadow?!

**Comment by hannahbergam** [comment]
> That was easy! Just to clarify: we have design approval to _keep_ the box shadow?!

From what I understand- we have design approval to remove it! I was chatting with Erin and it sounds like design is moving in the direction of more 'flat' buttons. Does that match your understanding?

**Comment by kelbyhawn** [comment]
> From what I understand- we have design approval to remove it! I was chatting with Erin and it sounds like design is moving in the direction of more 'flat' buttons. Does that match your understanding?

I can confirm we're moving towards flat buttons 👍

**Comment by megcrenshaw** [comment]
Ah, good to know! So what *should* the button do on hover? I thought it was best practice to have it do *something* but maybe I'm off here

UPDATE: Did some research. Looks like as long as content doesn't disappear on hover (lol) then we're good

**Comment by hannahbergam** [comment]
> Ah, good to know! So what _should_ the button do on hover? I thought it was best practice to have it do _something_ but maybe I'm off here
> 
> UPDATE: Did some research. Looks like as long as content doesn't disappear on hover (lol) then we're good

I think we're moving toward color change! So these grey ones turn white on hover:)

**Pull request merged**
