### PR TITLE
Autoupdate Cloudfront trusted proxy IP addresses

### PR DESCRIPTION
**Pull request by dju90**
We use IP address to geolocate users, but have to ignore IP addresses from Cloudfront proxy servers, which change from time to time. This list is currently updated manually, like in this PR:

https://github.com/code-dot-org/code-dot-org/pull/28635

This matters because if we don't update this list of IP addresses, we start geolocating users inappropriately based on the IP of the proxy server. We purged the bad user geolocations in [this PR](https://github.com/code-dot-org/code-dot-org/pull/30214). The goal of this PR is to schedule automatic updates of the Cloudfront trusted proxy IP address list.

We created a new trusted proxies module to replace the current script in dashboard/scripts/archive. The new module has methods to generate the trusted proxies list, upload it to s3, and also download it from s3 (instead of storing it locally as a committed file in git). We then updated files that were previously reading from said local file. Lastly we added a ruby script for the crontab that calls the trusted proxies module, and added a cron entry to the crontab.

This approach may not be optimal; here's another possible solution (WIP, by Will): https://github.com/code-dot-org/code-dot-org/pull/28715

Tracked here: https://codedotorg.atlassian.net/browse/FND-591

### CODE REVIEW

**Comment by uponthesun** [comment]
Some questions I was looking for feedback on:

* Storing the file in S3 compared to git. On the one hand, I generally don't like the pattern of automated git commits. On the other hand, this adds a dependency on S3 for starting the application.
* Should we add logic / configuration to only load from S3 if the environment is using Cloudfront?
* Whether we should do in-memory or on-disk caching of the proxy data from S3 so it's not requested multiple times.

**Comment by wjordan** [comment]
> Storing the file in S3 compared to git.
> Whether we should do in-memory or on-disk caching of the proxy data from S3 so it's not requested multiple times.

Hmm, we could use the existing `CDO.shared_cache` API to cache this list:

```
# in update_trusted_proxies
CDO.shared_cache.write('trusted_proxies', TrustedProxies.generate)

# instead of TrustedProxies.get_from_s3
trusted_proxies = CDO.shared_cache.read('trusted_proxies')
```

The `SharedCache` implementation is backed by memcached when the environment has a memcached endpoint configured (`production` is configured with an ElastiCache cluster), and falls back to a temp-file in other environments. Since the generated data is ephemeral (the source list is maintained by AWS) I think it fits the shared-cache use-case reasonably well, no need to store it permanently in S3 or maintain custom logic around it.

> Should we add logic / configuration to only load from S3 if the environment is using Cloudfront?

Yes I think that makes sense, we would only need to trust the extra IPs when requests are being routed through them (when `CDO.cdn_enabled` is `true`).

**Comment by uponthesun** [comment]
That approach sounds pretty good overall, but I think we would also need logic to generate the list on-demand in the case of a cache miss (which shouldn't happen normally, but if e.g. something happened to our ElastiCache cluster).

As long as we're already heavily using the "automated git commit" pattern, it's probably fine to use that here also, so I think I'm changing my mind and leaning towards that approach so there's as little startup risk as possible.

**Comment by Hamms** [comment]
I'm also very much not a fan of the automatic git commit pattern, but do we have a sense of how often this set of addresses changes? A particularly slow expected update schedule could convince me that auto commits are a better pattern then regularly re-requesting the data.

**Comment by wjordan** [comment]
> I think we would also need logic to generate the list on-demand in the case of a cache miss (which shouldn't happen normally, but if e.g. something happened to our ElastiCache cluster).

It would be straightforward to call `fetch` instead of `read` for this logic:

```
trusted_proxies = CDO.shared_cache.fetch('trusted_proxies') { TrustedProxies.generate }
```

> do we have a sense of how often this set of addresses changes?

According to an unofficial GitHub repo [`joetek/aws-ip-ranges-json`](https://github.com/joetek/aws-ip-ranges-json) tracking changes by service, it looks like the [CloudFront list history](https://github.com/joetek/aws-ip-ranges-json/commits/master/ip-ranges-cloudfront.json) has been updated 7 times so far in 2019 (though the full list updates more frequently).

**Comment by uponthesun** [comment]
Closing in favor of https://github.com/code-dot-org/code-dot-org/pull/30919 which has been running for a few months.

**Pull request closed without merging**
