### PR TITLE
Remove admin_stats routing, controller, view, and tests.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Follow-up to #14307.

USAGE (lack thereof) GRAPH:

image

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Though I don't intend to merge this quite yet (giving people time to notice I stopped the underlying cron), I did want to PR this so it wasn't forgotten.

**Comment by ashercodeorg** [comment]
@tanyaparker, is this [pegasus page](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/private/index.md) still in use by anyone? Looking at Google Analytics, I'm not seeing any traffic to it. Can it be removed entirely? A bunch of links on it are stale.

**Comment by tanyaparker** [comment]
@ashercodeorg admin stats is probably good to go away as long as this isn't the page that used to host your hoc report? You had a good view once that showed hoc signups over time and compared to previous year(s)? I think that's the only admin stat that may still be used by Alice and me, but if that's fetchable through Tableau then no longer necessary.

I still use the /private page ever so rarely for the leaderboards during hoc season. I don't really _need_ the page since I can always fetch the data directly. The page is just slightly more convenient. I doubt other people use it often; I'd be okay with removing.

**Comment by ashercodeorg** [comment]
It did not host my HOC report. And now that the data is available through Tableau, I'd much rather have people access the data from there rather than host admin pages that grab the results of cron jobs dedicated to rolling up data that is seldom used.

As for HOC report, I think I had a Tableau workbook for this past HOC which showed the same data. Certainly, if there isn't one floating around, it would be easy to create such a Tableau workbook.

**Comment by tanyaparker** [comment]
Great. Let's just use Tableau.

**Pull request merged**
