### PR TITLE
Update Ruby garbage-collection configuration

### PR DESCRIPTION
**Pull request by wjordan**
This PR updates the out-of-band garbage-collection (OOBGC) implementation used by the `unicorn` process in our `dashboard` web-application. This change should reduce frontend CPU usage substantially, by reducing the number of 'major' GC runs occurring on each worker-process.

### Results
Simple A/B test showing a significant decrease in CPU utilization on identical shares of production traffic:

pasted image at 2017_09_27 03_02 pm

#### Ruby GC summary

- The traditional CRuby/MRI implementation (`<= 2.0`) uses a basic 'mark and sweep' garbage-collector implementation. When enough memory-allocation happens, the mark-and-sweep process would pause all computation ('stop the world') tracing through all objects in the system, first 'marking' all references as still in use and then 'sweeping' all un-marked objects by freeing their allocated memory blocks.

- Ruby 2.1 introduced a new 'generational' garbage-collector feature called [`RGenGC`](https://bugs.ruby-lang.org/issues/8339) (see e.g., [1](https://thorstenball.com/blog/2014/03/12/watching-understanding-ruby-2.1-garbage-collector/), [2](http://tmm1.net/ruby21-rgengc/), [3](http://www.atdot.net/~ko1/activities/rubyconf2013-ko1_pub.pdf), [4](https://bugs.ruby-lang.org/attachments/3686/gc-strategy-en.pdf) for details). This divides the heap space into 'young' and 'old' generations and two types of GC runs ('minor' and 'major'). On a 'minor' GC run, 'young' objects are scanned and any still-in-use objects are moved to the 'old' generation, and a 'major' GC run scans objects across all generations. Minor GC runs happen quickly/frequently catching most short-lived garbage, while major GC runs happen slowly/infrequently catching more longer-lived objects.

- Finally, Ruby 2.2 (our current version) introduced an 'incremental' garbage-collector feature called [`RIncGC`](https://bugs.ruby-lang.org/issues/10137) (see [1](https://blog.heroku.com/incremental-gc) for details). This feature is an optimization to the 'Major GC' runs (which are still 'stop-the-world' slow), spreading out its mark and sweep phases into shorter, incremental chunks that won't pause processing any longer than the 'Minor GC' runs usually do. (Ruby 2.2 also adds a third generation to the generational-GC algorithm, for what it's worth.)

#### OOBGC summary

- The previous OOBGC middleware ([`Unicorn::OobGC`](http://www.rubydoc.info/gems/unicorn/5.1.0/Unicorn/OobGC)) was designed for the classic MRI (`<= 2.0`) mark-and-sweep garbage collector, and has a [relatively simple implementation](https://bogomips.org/unicorn.git/tree/lib/unicorn/oob_gc.rb): every `N` requests (5 by default), call [`GC.start`](https://ruby-doc.org/core-2.2.0/GC.html#method-c-start) (causing a full, stop-the-world GC run) after the `N`th request is completed. This ensures minimal garbage before the next request (ensuring minimal GC activity during future request processing, so faster per-request response times), at the expense of additional total CPU load on the server (because the extra GC runs may not have been absolutely necessary). However, it  doesn't distinguish between major vs. minor GC, so it always triggers a major GC, which is usually overkill since the generational GC feature was introduced in MRI `2.1`.
- The new OobGC middleware [`GC::OOB::UnicornMiddleware`](https://github.com/tmm1/gctools/blob/master/lib/gctools/oobgc/unicorn_middleware.rb) was designed to play nice with MRI 2.1's generational GC (see ["Ruby 2.1: Out-of-Band GC"](http://tmm1.net/ruby21-oobgc/)): "Powered by 2.1's new tracepoint GC hooks, it understands both lazy vs immediate sweeping and major vs minor GC in order to make the best descision about when a collection is required." This makes it run much more conservatively than the previous OobGC implementation, avoiding unnecessary 'major' GC runs when not needed.

There's an open discussion as to whether _any_ out-of-band garbage collection is useful at all when using MRI `2.2`'s incremental GC feature. However, even with incremental GC, I believe it's still possible to maximize in-request response times at the expense of total CPU load by scheduling out-of band GCs some of the time (and the new OobGC middleware is smarter about when these will be useful). More profiling is needed to be absolutely sure that it still provides a significant benefit, but I'm choosing to leave the new OobGC in for now, given that we had previously depended on out-of-band GC to maximize our response times up until now.

### CODE REVIEW

**Comment by wjordan** [comment]
> Will there be multiple GCs running then?

- There's only one GC implementation running throughout our system (we're standardized on a single consistent Ruby version, currently `2.2`). `RGenGC` and `RIncGC` are just 'features' tacked on to the one-and-only GC implementation in recent MRI versions.

- GC runs on a per-process basis, so on any given server instance it's possible for multiple GC runs to be happening at the same time, across different worker-processes (while still other worker-processes may be in the middle of serving requests). GC can happen either while a process is responding to an HTTP request, or just after the process is finished responding (this is what 'out of band' GC does).

- In a given process Ruby execution is effectively single-threaded, so only one GC can be running per process (and GC 'stops the world', so any other code execution in that process has to pause while it happens)

**Comment by jeremydstone** [comment]
What is the safe rollout plan for shipping this without risking prod? Can we try this on 1 FE, then an increasing # of FE's, through hand edits or having some instances built this way and swapping them in in load balancer?

Really exciting potential results here!

**Comment by wjordan** [comment]
Since #17999 is now in production, we can monitor 'time spent in GC' activity across all frontends, which will help with monitoring test/rollout of this.

I'll do some spot-testing through manual edits on production instances (to confirm CPU-utilization drops without any significant impact on request-response latency or memory utilization), before rolling this out in a production deploy hopefully later this afternoon.

**Comment by wjordan** [comment]
Spot-testing with various GC tuning configurations, the following GC-tuning settings result in better average response-times (and less total time spent in GC) than the defaults (given our current m4.10xlarge frontend-instance configuration, where we can take advantage of plenty of extra RAM per worker-process):

```
RUBY_GC_HEAP_FREE_SLOTS: 600_000, # Default is 4096
```
This decides the number of slots that will be freed up after each GC run. Good rule-of-thumb is to make this a multiple of the number of objects created per request, so GC doesn't normally need to be invoked mid-request. We generate ~30k objects per request, so this should free up ~20 requests' worth of slots after a GC.

```
RUBY_GC_MALLOC_LIMIT_MAX: 134_217_728, # 128MB, default is 32MB
```
Max size the 'young'-gen heap can grow. The larger this is, the less frequent 'minor' GC will run.
```
RUBY_GC_OLDMALLOC_LIMIT_MAX: 1_000_000_000, # 1GB, default is 128MB
```
Max size the 'old'-gen heap can grow. The larger this is, the less frequent 'major' GC will run.
```
RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR: 3 # Default is 2.0
```
Max ratio of old-to-young objects before a 'major' GC happens. Setting this to `< 1.0` disables old-gen heap entirely. Generally, the greater this value, the less-frequent 'major' GC will be run (and the larger the heap can grow in the meantime). Since we have extra RAM to spare, we want to run major GC less frequently.

I've added these environment-variables to the unicorn init-script.

**Comment by wjordan** [comment]
Production-traffic test results with the above GC settings:

- Time spent in GC: **0.3%** (compared to **28%** baseline)
- Total CPU utilization: **7.7%** (compared to **39.2%** baseline)
- `ScriptLevelsController#show` response time: **177ms** average (compared to **178ms** baseline)
- Average GC-execution time per `ScriptLevelsController#show` request: **9.02ms (5.1%)** (compared to **3.63ms (2.0%)** baseline
- Memory usage: **1.85GB** (compared to **1.6GB** baseline)

**Pull request merged**
