### PR TITLE
Add social links in footer

### PR DESCRIPTION
**Pull request by kozzi**
## Changes:
- Roxanne's request: Add social links to both HOC and Code.org footers 
- Since I was already in there, I fixed the HOC mobile footer to match what Code.org does (otherwise, it overflows weirdly)
## Code.org

image
## HOC

image
#### Before:

image
#### After:

image

... which is what happens on code.org (All the About/Support/etc links just gets removed)
image

TODO:
- Since I'm changing wide.haml and wide-layout.haml, which is used by many HOC pages, I'm going to go through and check all the HOC pages. Note I also changed to default.haml just to be consistent, but AFAIK, there aren't any pages that actually use this layout.

### CODE REVIEW

**Comment by kozzi** [comment]
fyi @breville @tanyaparker

**Comment by kozzi** [comment]
Catalogued all the links I could click through on HOC. Verified the following pages at various widths that the footer changes didn't break anything.

**Layout: wide_index**
http://localhost.hourofcode.com:3000/us
http://localhost.hourofcode.com:3000/us/map

**Layout: wide**
http://localhost.hourofcode.com:3000/us/how-to
http://localhost.hourofcode.com:3000/us/how-to/afterschool
http://localhost.hourofcode.com:3000/us/how-to/companies
http://localhost.hourofcode.com:3000/us/how-to/districts
http://localhost.hourofcode.com:3000/us/how-to/events
http://localhost.hourofcode.com:3000/us/how-to/public-officials
http://localhost.hourofcode.com:3000/us/how-to/volunteers
http://localhost.hourofcode.com:3000/us/events/all
http://localhost.hourofcode.com:3000/us/promote
http://localhost.hourofcode.com:3000/us/promote/resources
http://localhost.hourofcode.com:3000/us/promote/stats
http://localhost.hourofcode.com:3000/us/promote/press-kit
http://localhost.hourofcode.com:3000/us/prizes
http://localhost.hourofcode.com:3000/us/prizes/terms
http://localhost.hourofcode.com:3000/us/tutorial-guidelines
http://localhost.hourofcode.com:3000/us/thanks

**Layout: default**
http://localhost.hourofcode.com:3000/us/partners

**Comment by breville** [comment]
fyi @tanyaparker

**Comment by breville** [comment]
Sorry to say this but hourofcode.com is designed to be fully responsive which means we expect there to be links to all those parts of the site even when mobile.  We should only take them out of the footer if we provide access to those pages in some other way.  @tanyaparker should chime in here.

**Comment by tanyaparker** [comment]
On hoc.com mobile, it should have all the same content, and then not overlap with the Q&A button. So perhaps keep the content and make the footer taller?

**Comment by kozzi** [comment]
Followed up with @tanyaparker and @breville offline. Currently, the footer is not really usable on mobile. And there's more work needed, other than the footer, to make HOC be fully responsive (e.g. the header links disappear in mobile sizes). Will separate that out as a different work item and keep this PR as-is.

**Pull request merged**
