### PR TITLE
Change paletteParams to be a list of objects and persist them

### PR DESCRIPTION
**Pull request by bethanyaconnor**
This PR persists `palette_params` to the db on seed and changes the type of `paletteParams` to be a list of objects instead of a list of strings. This is in preparation for allowing the editing of parameters in code docs.

Parameters in code docs will have a bit more information than just name, including a type, a description, and whether or not they are required. See [this spec](https://docs.google.com/document/d/1CuMG8vlECM0xLs8kq5hocUS5ToyPWipjTGU841W2wvs/edit#) for more context. I propose saving this extra data along with the name in `palette_params`. (Note that this data is not serialized as part of this PR.)

There is also a `params` field, however that is often more of an example of the value of the parameter, see [color](https://github.com/code-dot-org/code-dot-org/blob/27582e52436cb578afe4eaf70e2907cb2ffb1cee/dashboard/config/programming_expressions/applab/color.json#L8). I don't see an obvious use for the `params` field and was planning on removing it in the future.

I would recommend viewing the [Ruby diff](https://github.com/code-dot-org/code-dot-org/pull/43165/files?authenticity_token=JwPOUZ8%2BbcUqTTLTdW0tmTBZ7fH5yrTwq7%2Fe7Qj8WTedAVwK1m7Qg0PUmaEFOhrrzunRAqqOMtPkIGfI7KTiDA%3D%3D&file-filters%5B%5D=.rb) on its own first as github takes a minute to load all the json diffs.

I modified the json files using the following script:
```
Dir.glob(Rails.root.join("config/programming_expressions/{applab,gamelab,weblab,spritelab}/*.json")).each do |path|
  serialization = JSON.parse(File.read(path))
  next unless serialization['paletteParams']
  palleteParams = serialization['paletteParams'].map do |param|
    {name: param}
  end
  serialization['paletteParams'] = palleteParams
  File.write(path, JSON.pretty_generate(serialization))
end
```

## Testing story

seeded locally and manually verified the syntax of a couple expressions

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by tim-dot-org — APPROVED** [review]
Looks good!
One thing to check: i noticed you were searching weblab and spritelab too, but there aren't any json files from those directories, just applab and gamelab. Is that expected?

**Comment by dmcavoy** [comment]
This looks good. One thing can you update the script which generates the individual command files from the droplet config?

**Comment by davidsbailey** [comment]
I think I am missing / forgetting some background here on the relationship between these code doc config files, the droplet config files, the palleteParams that appears in .level files, and what gets consumed by droplet, ProgrammingExpression, or both. do the .level files containing `palleteParams` need to be updated too?

**Comment by davidsbailey** [comment]
Same question for palleteParams in droplet config -- do they need to be updated, and why/why not? https://github.com/code-dot-org/code-dot-org/blob/a13785202eb61f38d40e8891d6ec8cd10e377bd0/apps/src/applab/dropletConfig.js#L74-L79

**Comment by bethanyaconnor** [comment]
My understanding is that the droplet configs were used to generate the programming expression configs but that was done as a one-off. They're not actually well tied-in together because we have so many ways of creating/maintaining blocks. At this point, I think the only place that needs the extra data, such as description, is the the programming_expression configs but I'll double check that

**Comment by bethanyaconnor** [comment]
> One thing to check: i noticed you were searching weblab and spritelab too, but there aren't any json files from those directories, just applab and gamelab. Is that expected?

oo good catch! I'll check!

**Review by davidsbailey — APPROVED** [review]
looks good to me!

**Review by dmcavoy — APPROVED** [review]

**Comment by bethanyaconnor** [comment]
> One thing to check: i noticed you were searching weblab and spritelab too, but there aren't any json files from those directories, just applab and gamelab. Is that expected?

Looked and weblab and spritelab don't use paletteParams, though spritelab does have parameters. I think this is okay as this will be the spot to store this data, spritelab just won't get the parameters for free (at least not by this PR)

**Review by tim-dot-org — APPROVED** [review]

**Pull request merged**
