### PR TITLE
Send name to MailJet when creating a contact on signup

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Sends both `firstname` and `display_name` (which have the same value) to MailJet when we create a user on signup. This is for customization of our email templates. Our existing templates use `firstname`, but, as that's inaccurate, I'd love to support `display_name` going forward.

### Testing Story

- Added a unit test (and refactored a couple existing ones)
- Manual testing

### CODE REVIEW

**Review by TurnerRiley — COMMENTED** [review]
If `firstname` is inaccurate, should we update the templates themselves to expect `display_name` and not send `firstname` at all? Or is that outside the scope of this task

**Comment by bethanyaconnor** [comment]
That's a good question. According to @dmcavoy they're hard to change and my more limited experience with MailJet supports that, so I went with sending both. Open to more discussion though!

**Comment by dmcavoy** [comment]
Its not that bad so if we want to update it to get it right I can do that. Ali had another update that he wanted me to do anyway

**Comment by bethanyaconnor** [comment]
@dmcavoy are you going to be editing the templates anyway? If so, it would be nice to update the variable. If not, I think the solution in this PR is fine (unless @TurnerRiley disagrees!).

**Comment by TurnerRiley** [comment]
> @dmcavoy are you going to be editing the templates anyway? If so, it would be nice to update the variable. If not, I think the solution in this PR is fine (unless @TurnerRiley disagrees!).

Totally fine with me! Just wanted to get ahead of any tech debt if it was easy, but not blocking!

**Comment by bethanyaconnor** [comment]
Dani and I chatted more offline and the issue is that updating the template would mean that we lose metrics. To me, that's a big deal for a small change, so I'd like to avoid that if possible. `firstname` as a variable name bugs me because it's quite inaccurate, which is why I want to send both, but I'm open to pushback there!

**Review by TurnerRiley — APPROVED** [review]
Both works for me! Definitely not worth losing the metrics!

**Pull request merged**
