### PR TITLE
Adds a wait_until to pause an eyes test snapshot until fonts are loaded.

### PR DESCRIPTION
**Pull request by wilkie**
Attempts to tackle flaky eyes tests that cause the issues seen below where fonts are lazily loaded and not yet rendering some symbols.

This tells the driver to wait until `document.fonts.ready` is returning `true` before creating the snapshot, which is [described here](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/ready).

This often causes a flaky eyes result in our footer since things like the copyright symbol are rendered from alternative fonts that haven't yet had the chance to load, and our font settings are set to do a `swap` instead of render nothing:

image

## Links

- jira ticket: [P20-1280](https://codedotorg.atlassian.net/browse/P20-1280)

## Testing story

This needs to run on our `test` server as only that environment can actually take screenshots and coördinate with the eyes service. I'll need to run this on the `test` server while it is idle.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by wilkie** [comment]
Saw the affected tests fail about 20% of the time.

Made this change on the current deployed code on our `test` server and ran the oft-failing test via:

```
bundle exec ./runner.rb --html --eyes -c Chrome -f features/hour_of_code/hour_of_code_finish.feature
```

And watched it in SauceLabs and Applitools. It always succeeded 7 times.

image

And also

```
bundle exec ./runner.rb --html --eyes -c Chrome -f features/acquisition_products/pd/teacher_application.feature
```

Also successful 7 times.

Then I ran a full test suite. Full success.

**Comment by wilkie** [comment]
Still see some issues like this on Blockly blocks... perhaps fonts interacting with SVG elements are more complicated?

image

**Review by carl-codeorg — APPROVED** [review]
LGTM

**Comment by drizco** [comment]
@wilkie I'm seeing new failures on a flaky test that I thought I had fixed up. now it's failing on the `I see no difference` step with a js error. I'm wondering if you can't use `await` here since it's not wrapped in an `async` function? maybe a regular promise would work? `return document.fonts.ready.then(() => true);`

Screenshot 2024-11-15 at 8 59 53 AM

**Comment by drizco** [comment]
> @wilkie I'm seeing new failures on a flaky test that I thought I had fixed up. now it's failing on the `I see no difference` step with a js error. I'm wondering if you can't use `await` here since it's not wrapped in an `async` function? maybe a regular promise would work? `return document.fonts.ready.then(() => true);`
> 

trying this out here https://github.com/code-dot-org/code-dot-org/pull/62467

**Pull request merged**
