### PR TITLE
Update CS is Changing Everything video

### PR DESCRIPTION
**Pull request by sfilman**
Updated youtube link for CS is changing everything video. DL link is the same

### CODE REVIEW

**Comment by sfilman** [comment]
@Bjvanminnen will you give this a sanity check?

**Comment by sfilman** [comment]
@islemaster mind taking a quick look?

**Comment by Bjvanminnen** [comment]
lgtm

**Comment by islemaster** [comment]
LGTM!

**Comment by sfilman** [comment]
@islemaster got a failed circleci test -- any concerns?

**Comment by islemaster** [comment]
No, go ahead and merge.  This particular failure is related to recent work being done to run eyes tests in CircleCI, and is unrelated to your change.

**Pull request merged**
