### PR TITLE
Terms of service update December 2022

### PR DESCRIPTION
**Pull request by dmcavoy**
Updating terms of service with the updates Travis shared with me. 

### Update the date
Screen Shot 2022-12-12 at 2 19 38 PM

### Update content of Restrictions on Content and Use of Services
Screen Shot 2022-12-12 at 2 19 53 PM

### Update content of "Your License..." section
Screen Shot 2022-12-12 at 2 20 06 PM

Screen Shot 2022-12-12 at 2 20 15 PM

### CODE REVIEW

**Review by dju90 — APPROVED** [review]
Lgtm! With this last-updated date, we'll want to ship on that date, so that's one consideration before merging. Also, if we can get a version of this onto staging or an adhoc for Travis to review prior to the go-live, that would be great.

**Review by megcrenshaw — APPROVED** [review]
Thanks for doing this!

I don't think it's worth spinning up an adhoc for this –– I suggest screenshots instead.

**Comment by dmcavoy** [comment]
Thanks for the feedback. I have updated the date to be tomorrow. I will wait until the deploy goes out today to merge. Then share the staging link with Travis. It will then hopefully go out on Wednesday as long as we deploy. Travis said if its off by a day not to worry about it.

**Comment by dmcavoy** [comment]
Merging since it passed drone before and the only change I made was to the date.

**Pull request merged**
