### PR TITLE
Fix violations of and reenable rubocop Rails/Delegate.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes initially generated automatically by `bundle exec rubocop --only Rails/Delegate --auto-correct`, with the changes to `shared/` reverted by hand in `06c95c5`.

Note that this PR enables the check only for the `dashboard/` directory tree, as the rest of our codebase is not Rails.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
The failure seems legitimate.
```
230 tests, 779 assertions, 0 failures, 0 errors, 1 skips
Writing XML reports to /tmp/circle-junit.tEqRmXE/pegasus
[test] pegasus tests succeeded in 0:34 minutes
[test] Files affecting shared       tests *modified* from origin/staging. Starting tests. Changed files:
[test] 
    shared/test/files_api_test_base.rb
[test] Running shared tests...
RAILS_ENV=test RACK_ENV=test bundle exec rake test
Emptying /tmp/circle-junit.tEqRmXE/shared
/home/ubuntu/code-dot-org/shared/test/files_api_test_base.rb:84:in `<class:FilesApiTestBase>': undefined method `delegate' for FilesApiTestBase:Class (NoMethodError)
	from /home/ubuntu/code-dot-org/shared/test/files_api_test_base.rb:14:in `<top (required)>'
	from /home/ubuntu/code-dot-org/shared/test/test_animations.rb:1:in `require_relative'
	from /home/ubuntu/code-dot-org/shared/test/test_animations.rb:1:in `<top (required)>'
	from /home/ubuntu/code-dot-org/vendor/bundle/ruby/2.2.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:10:in `require'
	from /home/ubuntu/code-dot-org/vendor/bundle/ruby/2.2.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /home/ubuntu/code-dot-org/vendor/bundle/ruby/2.2.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:9:in `each'
	from /home/ubuntu/code-dot-org/vendor/bundle/ruby/2.2.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	from /home/ubuntu/code-dot-org/vendor/bundle/ruby/2.2.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/ubuntu/code-dot-org/vendor/bundle/ruby/2.2.0/gems/rake-11.3.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
```

**Comment by ashercodeorg** [comment]
My belief is that this is because `delegate` is a Ruby on Rails method, not a Ruby method. And `shared` is not part of dashboard.

Does it make sense to enable the rubocop and disable the check within `files_api_test_base.rb`? Does it make sense to fix the "real" violation and blacklist the check?
Does some other approach make better sense?

**Comment by davidsbailey** [comment]
Hey Asher, code in shared shouldn't have rails code in it, because it might be used in pegasus where rails isn't available. I would say that you could enable the check only for `dashboard`. Does that sound like a good option?

I don't think it makes sense to disable only for one file, and I'm not sure what you mean by 'fix the "real" violation'.

**Comment by davidsbailey** [comment]
LGTM

**Comment by ashercodeorg** [comment]
By "real" violation, I mean the violation in `dashboard/lib/pd/payment/teacher_summary.rb`. And I've updated the PR to only check the `dashboard/` directory tree.

PTAL.

**Pull request merged**
