### PR TITLE
Restyle progress dropdown and unit overview

### PR DESCRIPTION
**Pull request by joshlory**
This change is in preparation for the teacher-facing Professional Learning Course restyle.  Add borders to student-facing stages so they map to the look & feel of teacher focus areas.
#### Before: Progress Dropdown

progress_dropdown_before
#### After: Progress Dropdown

progress_dropdown_after
#### Before: Unit Overview

unit_overview_before
#### After: Unit Overview

unit_overview_after

### CODE REVIEW

**Comment by tanyaparker** [comment]
I did a rake build:dashboard and see it all white?

image

**Comment by joshlory** [comment]
You'll need to `npm run build` in `code-dot-org/code-studio` as well.

**Comment by tanyaparker** [comment]
Ah, thanks. Few more minutes. Clicking around. :) I like the beta turned blue.

**Comment by joshlory** [comment]
I shared a few other options in the #ui-ux Slack channel (including a version with the charcoal header).

**Comment by tanyaparker** [comment]
LGTM I think this is fantastic! Nicely done!

**Pull request merged**
