### PR TITLE
Use session storage for Overlay

### PR DESCRIPTION
**Pull request by Hamms**
So that tests can more reliably reset themselves.

Also clean up the helpers for trying to set and get local and session storage.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
I guess this does mean that people that currently have this key set will suddenly lose the setting. It also means that when you open a new tab, you will see the instruction overlay again.

Presumably we are okay with both of these things? Should we also make sure to get PM signoff?

**Comment by Hamms** [comment]
It does; given the proportion of our users that are using this in a shared device setting, where localStorage is presumably cleared with greater frequency than in an individualized setting, I don't expect that change to be huge.

But yeah, we should. @ryansloan, thoughts?

**Comment by ryansloan** [comment]
This is fine - if anything it will get people to remember to pay attention to the instructions when they sit back down at the computer. We'll watch support tickets and see if there's an increased volume of tickets regarding this, but I don't think it will be a problem.

**Comment by Hamms** [comment]
Reverting; it turns out that there were some places (like the share page) where the instructions overlay has been showing up when it shouldn't. That combined with this change that makes it show up a lot more frequently means it's now a lot more frequently showing up when it shouldn't, and I'm not a fan of that result.

**Comment by Bjvanminnen** [comment]
Makes sense. Are you planning to do other work here (such as make it more targeted?) or just stick with localStorage?

If the latter, we should at least make our UI test more resilient.

**Comment by Hamms** [comment]
yeah, definitely need to make it more targeted to prevent it from showing up in these unexpected places at all.

In lieu of that, I'm just gonna have that MC eyes test that triggered all this work clear localstorage so we can prevent the flakiness

**Pull request merged**
