### PR TITLE
Import North Dakota course offerings

### PR DESCRIPTION
**Pull request by sureshc**
import north dakota course offerings

@mirlew All school id lookups succeeded.

### CODE REVIEW

**Comment by sureshc** [comment]
[Import North Dakota data](https://trello.com/c/E4s8IsgR/214-import-north-dakota-data)

**Comment by mirlew** [comment]
@sureshc I see this merged to staging on Friday, but it looks like these schools haven't been updated yet. Should I check back again tomorrow, or was there an issue here that we need to look into?

**Comment by sureshc** [comment]
@mirlew Looks like I merged it at 3PM PDT Friday.  The production build for Friday was probably in progress or complete by then.  So the change was in this afternoon's deployment and will be reflected in the Access Report after the summarization process runs tonight.

**Comment by mirlew** [comment]
@sureshc got it. thanks!

**Pull request merged**
