### PR TITLE
Revert "Revert "Fix blockly loading in tests""

### PR DESCRIPTION
**Pull request by pcardune**
This reverts commit a8fb703d962f0e0dcb4505a53ac7cfcfc22b210e.

### CODE REVIEW

**Comment by pcardune** [comment]
@Bjvanminnen so I didn't actually change anything from the initial commit and I can't repro the failure on my own machine. It looks like CircleCI isn't reproing a failure either. I'm wondering how to proceed...

**Comment by Bjvanminnen** [comment]
Do you know what was actually failing? I don't see any info about that in any of the related PR descriptions.

**Comment by pcardune** [comment]
@Bjvanminnen This is the set of failing tests you mentioned in slack:

```
FAILED TESTS:
  blockUtils
    ✖ "before each" hook for "can create a block from XML"
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    Attempted to assign to readonly property.
    setupBlocklyFrame@/Users/brent/git/cdo/apps/test/index.js:232029:22 <- webpack:///test/integration/util/testBlockly.js:36:21
    setupTestBlockly@/Users/brent/git/cdo/apps/test/index.js:232007:29 <- webpack:///test/integration/util/testBlockly.js:14:2
    /Users/brent/git/cdo/apps/test/index.js:231801:44 <- webpack:///test/integration/blockUtilTests.js:11:4

  requiredBlockUtils
    ✖ "before each" hook for "can recognize matching titles in blocks"
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    Attempted to assign to readonly property.
    setupBlocklyFrame@/Users/brent/git/cdo/apps/test/index.js:232029:22 <- webpack:///test/integration/util/testBlockly.js:36:21
    setupTestBlockly@/Users/brent/git/cdo/apps/test/index.js:232007:29 <- webpack:///test/integration/util/testBlockly.js:14:2
    /Users/brent/git/cdo/apps/test/index.js:231825:44 <- webpack:///test/integration/blockUtilTests.js:35:4

  functional_cond_number
    ✖ "before each" hook for "it can addConditionalRow multiple times"
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    Attempted to assign to readonly property.
    setupBlocklyFrame@/Users/brent/git/cdo/apps/test/index.js:232029:22 <- webpack:///test/integration/util/testBlockly.js:36:21
    setupTestBlockly@/Users/brent/git/cdo/apps/test/index.js:232007:29 <- webpack:///test/integration/util/testBlockly.js:14:2
    /Users/brent/git/cdo/apps/test/index.js:232415:40 <- webpack:///test/integration/condBlockTest.js:9:4

  hasDuplicateVariablesInForLoops
    ✖ "before each" hook for "returns true for nested for loops with the same variable name"
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    Attempted to assign to readonly property.
    setupBlocklyFrame@/Users/brent/git/cdo/apps/test/index.js:232029:22 <- webpack:///test/integration/util/testBlockly.js:36:21
    setupTestBlockly@/Users/brent/git/cdo/apps/test/index.js:232007:29 <- webpack:///test/integration/util/testBlockly.js:14:2
    /Users/brent/git/cdo/apps/test/index.js:233065:40 <- webpack:///test/integration/duplicateVariablesTest.js:9:4

    ✖ "after each" hook for "returns true for nested for loops with the same variable name"
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    undefined is not an object (evaluating 'Blockly.mainBlockSpace.getTopBlocks')
    /Users/brent/git/cdo/apps/test/index.js:233073:28 <- webpack:///test/integration/duplicateVariablesTest.js:17:27

  checkForEmptyContainerBlockFailure_
    ✖ "before each" hook for "returns ALL_PASS when no blocks are present"
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    Attempted to assign to readonly property.
    setupBlocklyFrame@/Users/brent/git/cdo/apps/test/index.js:232029:22 <- webpack:///test/integration/util/testBlockly.js:36:21
    setupTestBlockly@/Users/brent/git/cdo/apps/test/index.js:232007:29 <- webpack:///test/integration/util/testBlockly.js:14:2
    /Users/brent/git/cdo/apps/test/index.js:238201:40 <- webpack:///test/integration/feedbackTests.js:21:4
```

**Comment by Bjvanminnen** [comment]
Hmm...I'll try pulling down your branch and see if tests pass for me. If they do, let's revert the revert and see whether things blow up again.

**Pull request merged**
