### PR TITLE
Remove @cdo/apps alias from package.json

### PR DESCRIPTION
**Pull request by islemaster**
The `@cdo/apps` entry in package.json was [introduced pre-Webpack](https://github.com/code-dot-org/code-dot-org/pull/2414/files) along with [`linklocal`](https://github.com/timoxley/linklocal) to allow us to use absolute paths in JavaScript imports.

We now get this ability from the Webpack [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolvealias) config setting. The `@cdo/apps` entry in package.json, and the `apps/src/package.json` file, are vestigial, and result in an unwanted `node_modules/@cdo/apps` directory.

### CODE REVIEW

**Comment by islemaster** [comment]
Code.org staff can [check out this Slack conversation](https://codedotorg.slack.com/archives/C0T0PNR0D/p1563236279126400) for further context.

**Review by jmkulwik — APPROVED** [review]
Thanks for doing this!

**Review by davidsbailey — APPROVED** [review]
This stops my IDE from "jump to definition" going into this `apps/node_modules/@cdo` directory, which is great! it doesn't seem to be able to resolve the webpack aliases to jump to the right definition, but this still seems like an incremental improvement since now I don't risk editing a source file in the wrong place.

**Comment by joshlory** [comment]
For my understanding: we'll continue to use `@cdo/apps/...` over relative imports for dependencies that aren't the same directory, this just removes one legacy way of setting up that link?

Do we have a preference for aliased vs. relative imports in general? Current files use a mix of both.

**Comment by islemaster** [comment]
Correct: This does not get rid of `@cdo/apps/...` imports, it just removes some old configuration that was no longer needed to support that feature.

I don't particularly care which people use. I have a mild personal preference for relative imports because my tools support them better. I follow a rule-of-thumb that I use relative imports to refer from `src` to `src` and `test` to `test`, and absolute imports to refer from `test` to `src`.

I'm not sure we've locked on a preference as a team.  I'm open to revisiting this but don't see it as a high priority.  I'd also like to solve my own editor's ability to read/follow aliases - I think it may already have this ability, given a less dynamic webpack config, but need to do some investigation to confirm this.

**Comment by cpirich** [comment]
I also prefer relative references while within the same project, but am opening to being persuaded if there are good arguments for the other style.

**Pull request merged**
