### PR TITLE
Eliminates a needless pass over the forms table.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
@wjordan also to review

**Comment by ashercodeorg** [comment]
Never mind, I think this change is bunk.

**Comment by wjordan** [comment]
Yeah, the `#count` will generate a query regardless, and the original one is a bit faster (0.22sec vs 1.11sec):

```
irb(main):004:0> unique_hoc_events = DB[:forms].where(kind: 'HocSignup2015').group(:email, :name).select(:name, :email, :processed_data, :data)
=> #<Sequel::Mysql2::Dataset: "SELECT `name`, `email`, `processed_data`, `data` FROM `forms` WHERE (`kind` = 'HocSignup2015') GROUP BY `email`, `name`">
irb(main):005:0> total_hoc_count = unique_hoc_events.count
I, [2015-11-17T00:57:20.495649 #22759]  INFO -- : (1.110565s) SELECT count(*) AS `count` FROM (SELECT `name`, `email`, `processed_data`, `data` FROM `forms` WHERE (`kind` = 'HocSignup2015') GROUP BY `email`, `name`) AS `t1` LIMIT 1
=> 100991
irb(main):006:0> total_hoc_count = DB[:forms].where(kind: 'HocSignup2015').group(:email, :name).select(:email, :name).count
I, [2015-11-17T00:57:29.440745 #22759]  INFO -- : (0.228834s) SELECT count(*) AS `count` FROM (SELECT `email`, `name` FROM `forms` WHERE (`kind` = 'HocSignup2015') GROUP BY `email`, `name`) AS `t1` LIMIT 1
=> 100992
```

To eliminate the extra `#count` query we could do something like:

```
total_hoc_count = 0
unique_hoc_events.each do |row|
  total_hoc_count += 1
  [...]
end
```

but shaving 0.2 seconds off a script that runs once an hour isn't really going to matter anyway!

**Comment by ashercodeorg** [comment]
Dropping (closing) this PR.

Fascinating that this goes against my intuition. Thanks, Will.

**Pull request closed without merging**
