### PR TITLE
Fail adhoc:start if branch is not up-to-date

### PR DESCRIPTION
**Pull request by islemaster**
If you run adhoc:start and haven't specified a custom branch, it will check whether your local branch is up-to-date with the remote branch of the same name to catch the mistake of forgetting to push your local changes before starting/updating an adhoc.

### CODE REVIEW

**Comment by wjordan** [comment]
I'm hesitating on this because I'd like this logic refactored into the specific stack template(s) it should be applied against - the intention (though I haven't kept it completely refactored as such at the moment) is to use this `AWS::CloudFormation` class as more of a library for manipulating all CloudFormation stacks - including those which for example don't depend on branches at all, and just create static resources.

**Comment by islemaster** [comment]
I saw how [you do that here](https://github.com/code-dot-org/code-dot-org/blob/staging/aws/cloudformation/cloud_formation_adhoc_standalone.yml.erb#L3).  I wasn't sure if that template was evaluated on the local machine or the new one - looking closer now I can see that it's local.  So you'd prefer that I move this check into that template instead?

**Comment by wjordan** [comment]
correct, the template logic is evaluated locally. It's not the perfect setup (it would be nicer having Ruby code make it into its own Ruby file for IDE purposes), but yeah, for now moving the check into the template directly would keep it out of the generic class, so that's what i'd prefer

**Comment by islemaster** [comment]
Okay, moved logic into the template and merged it with the existing check for whether the branch exists on the remote. PTAL.

**Pull request merged**
