### PR TITLE
moving 3rd party storefront to code-dot-org github

### PR DESCRIPTION
**Pull request by ajosuarez**
this is the code from a 3rd party which built a landing page that aggregates various Code.org storefronts used for providing merchandise and accessories to customers. the website is now online and linked from the https://code.org/shop path. we want to store this code in the the code-dot-org github repository in case we ever need to make any changes. this PR is comprised of static html and css files that are also stored in an Amazon S3 bucket with website hosting and URL redirection enabled; this is where the website is served when users go to https://store.code.org. from within the hosted page the visitor is able to find products hosted across Amazon Merch and Amazon.com. this PR is focused on centralizing access to the code.

image

### CODE REVIEW

**Comment by breville** [comment]
This page is a neat way to build a lightweight storefront, and it's great that we're going to archive it under source control.

That said, https://github.com/code-dot-org/code-dot-org/tree/staging/pegasus/sites.v3 is not the right place for it; `sites.v3` is where we store pages that are actually served by the Pegasus CMS.

Some thoughts on what we could do:

- archive it in our own source tree.  I don't have a strong feeling on where it should go if it's in our own source tree, but perhaps @wjordan or @islemaster have thoughts.  I don't see a top-level directory that really fits this purpose, but perhaps we could create an `external/` or `snapshot`/ directory.  

- archive it in a new repo.  This lack of obvious destination makes me think a separate repo under https://github.com/code-dot-org might be best.

- archive it in S3.   If we turn on versioning for the S3 bucket that it's already stored in, perhaps that's enough?

- this page was and is a good candidate to be authored inside Pegasus.  It could be a simple, single markdown file, and if we want to maintain the big image block styling, we could create a new partial if we can't find an existing one that looks just right.  Pegasus supports pages both under `code.org` and as subdomains as can be seen with `advocacy.code.org`.  Pegasus is designed for easy authoring by everybody in the org, and it's a concern if we don't default to authoring such pages in it.

**Comment by islemaster** [comment]
I'll vote for a separate repo.

- This doesn't seem to have any dependencies on our main repo.
- It is (and should remain) independently deployable.
  - If we expect to make frequent changes to this page, we could set up a Travis or Drone build with secrets manager to push changes on master to the S3 bucket.
- If this was built by a third-party, we might want a third-party to make changes to it in the future.  It will be simplest to give them access to a separate repo.

**Comment by ajosuarez** [comment]
thanks for the comments and suggestions. i think i'll pursue the separate repo idea for now as it addresses the feedback / concerns and offers the most flexibility. propose code-dot-org/storefront.

**Comment by ajosuarez** [comment]
reference: https://github.com/code-dot-org/storefront

**Pull request closed without merging**
