### PR TITLE
Update cron jobs for daylight savings time starting - Spring 2022

### PR DESCRIPTION
**Pull request by sureshc**
Reverts code-dot-org/code-dot-org#43295

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
There are multiple other jobs in this file that trigger at a specific hour. Should they also be changed?

**Comment by sureshc** [comment]
> There are multiple other jobs in this file that trigger at a specific hour. Should they also be changed?

Only the jobs where specific people (or teams) have an expectation that the scheduled process will run at a specific time need to change. For example, Content Editors know they need to complete their changes by a certain cutoff.

The daily export from MySQL to Redshift does not need to change because the team that relies on the job doesn't currently have a requirement that the job start or end at a specific time.

**Comment by dmcavoy** [comment]
@sureshc I have updated the times to match the new proposed times. 

Levelbuilder Commit - 12:30am PT
Staging Commit - 12:30am PT
Levelbuilder merge to staging - 12:35am PT

Levelbuilder Commit - 2:18am PT
Deploy to Levelbuilder - 2:20am PT

**Comment by cat5inthecradle** [comment]
Just leaving a comment here that WE SHOULD NOT SIMPLY REVERT THIS COMMIT IN THE FALL!

We moved the time of the content and levelbuilder scoops from noonish to midnightish
https://docs.google.com/document/d/1LnrdrB5-al_1KDWkXLflNWz8qlD7LnN8sBUyt_0OyaY/edit#heading=h.fmrfu9y5ajki

**Comment by davidsbailey** [comment]
> Just leaving a comment here that WE SHOULD NOT SIMPLY REVERT THIS COMMIT IN THE FALL!

thanks for this Darin! just noting that once these times are in the middle of the night, perhaps they don't need to be updated at all when the time change happens.

**Comment by dmcavoy** [comment]
Hey Folks - I need to merge this tomorrow before 12 PM PT in order to get it out tomorrow with the deploy. If you have any feedback please leave it before then. Thanks!

**Review by tim-dot-org — APPROVED** [review]

**Pull request merged**
