### PR TITLE
Support both Rails 5 and Rails 6 versions of the `translate_exception_class` method

### PR DESCRIPTION
**Pull request by Hamms**
As updated here : https://github.com/rails/rails/pull/34468

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by cat5inthecradle — APPROVED** [review]
Makes sense to me. Rails 6 added a third required param to translate_exception_class. TIL what `arity` does.

**Comment by Hamms** [comment]
It's real neat that Ruby makes it so easy to interact with method signatures like that! And real scary that it's sometimes necessary.

Of all the "5 to 6 compatibility" logic I've been putting into place, this is perhaps the one I'm most excited to _remove_

**Comment by cat5inthecradle** [comment]
Right, I'm surprised this one wasn't just backwards compatible. On the topic of cleanup, how are you tracking or otherwise making these cleanup opportunities easy to find? Looks like a ctrl-f for "Rails 5" would work.

**Comment by Hamms** [comment]
Likewise! I think this is a case of us reaching deeper into the Rails internals than they expect us to.

My plan is to rely on [PR tagging](https://github.com/code-dot-org/code-dot-org/labels/Rails%206) to track the relevant work that's been done, and my hope is that it won't be too much of a pain to do a pass on that list after the update is finished and identify which subset of that represents temporary/revertable work

**Pull request merged**
