### PR TITLE
Assume Database is Aurora when Configuring ProxySQL

### PR DESCRIPTION
**Pull request by sureshc**
Assume (if Chef is provisioning ProxySQL on a web application server) that the database is an Aurora cluster. This reduces our dependency on `CDO` configuration settings in Chef cookbooks, so we can hopefully eliminate the loading `/deployment.rb` during execution of the `cdo-secrets` cookbook. Currently #48809 modifies the `CDO` config / secrets functionality enough to break initialization of the `CDO` object when it’s loaded by Chef.

## Testing story

Only production currently uses ProxySQL. We may need to provision an adhoc with ProxySQL to test this change.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by Hamms — COMMENTED** [review]
Instead of making this variable always true, why not just remove it entirely? Looks like it's only used in a couple places in `proxysql.cnf`:

https://github.com/code-dot-org/code-dot-org/blob/b195b93909f2dcabef6b91762eb327b87d89f6da/cookbooks/cdo-mysql/templates/default/proxysql.cnf.erb#L5-L9

https://github.com/code-dot-org/code-dot-org/blob/b195b93909f2dcabef6b91762eb327b87d89f6da/cookbooks/cdo-mysql/templates/default/proxysql.cnf.erb#L105-L126

**Comment by sureshc** [comment]
> Instead of making this variable always true, why not just remove it entirely?

That would be my preference, but we have limited ability to test this change as ProxySQL is only provisioned on a web application server (`FrontEnd` node) that does not also serve as a `Daemon` node. Currently only production has that configuration, and we have not been successful recently provisioning a full stack adhoc. I figured that hard-coding `true` would be the lowest risk change.

**Review by Hamms — APPROVED** [review]
I'm not convinced that it's that much safer; the potential change in functionality here comes from our decision to always apply aurora logic to proxysql. Whether we implement that by having a bunch of hardcoded `if true` blocks or by taking the blocks away and executing the code directly is just a matter of hygiene, not functionality.

If we want to just release this as-is out of an abundance of caution, and then quickly follow it up with the cleanup before it gets forgotten about and turned into tech debt, that seems reasonable. But only as long as we actually do that follow-up!

**Comment by sureshc** [comment]
> If we want to just release this as-is out of an abundance of caution, and then quickly follow it up with the cleanup before it gets forgotten about and turned into tech debt, that seems reasonable. But only as long as we actually do that follow-up!

One reason I'm comfortable with hard-coding the variable assignment to `true` is that all of this ProxySQL logic is going to be deleted when we complete our transition to RDS Proxy. I'm definitely committed to the cleanup! :)

**Pull request merged**
