### PR TITLE
[Finishes #98671768] have gulp fail with exit code no failure

### PR DESCRIPTION
**Pull request by Bjvanminnen**
Gulp failures haven't actually been resulting in error codes, which means that if I run rake build:shared, it treats it as success even when we fail. This fixes that.

### CODE REVIEW

**Comment by wjordan** [comment]
have you tested whether this will cause the 'grunt dev' watch process to quit entirely if there's e.g. a syntax error in a js file? if so, that doesn't seem ideal to me.

**Comment by wjordan** [comment]
or is incremental-build watch process not enabled for the shared build at this point? if so, this would be something to look out for if/when it's added

**Comment by Bjvanminnen** [comment]
We do have a gulp dev. It does exit early when there's an error. I'll look into this.

**Comment by Bjvanminnen** [comment]
Latest commit makes it so that gulp dev logs errors instead of throwing.

**Comment by wjordan** [comment]
:+1: lgtm, this should be very helpful

**Pull request merged**
