### PR TITLE
feat(eslint): add linter configs for `frontend`

### PR DESCRIPTION
**Pull request by stephenliang**
This PR adds shared ESLint base configurations for usage in the `frontend` directory. These rules currently inherit the recommended ESLint defaults for node and react but are expected to include Code.org specific engineering rules as we develop them over time.

I originally was going to use the `code-dot-org/apps` eslint config as a reference, but there are a lot of custom rules there that override defaults and considering we are building a new code base, it is an opportunity to retain recommended defaults with a small set of overrides to reduce the amount of effort required in maintaining eslint configurations in the code base.

### CODE REVIEW

**Review by kelbyhawn — APPROVED** [review]
This looks ok to me, but someone with more linting insight might want to take a look too.

**Comment by bencodeorg** [comment]
Were you able to do a bit of digging into the existing overrides in `apps` and why they're there? Seems like there might be some "Code.org specific engineering rules" there already?

**Comment by stephenliang** [comment]
> Were you able to do a bit of digging into the existing overrides in `apps` and why they're there? Seems like there might be some "Code.org specific engineering rules" there already?

I did but there are a lot, some of which are disabling recommended rules, some are probably ones that we want to keep (like import order). I think what we can do is start with reasonable defaults (which are the recommended defaults from the plugins) and when the Standards Working Group kicks off, we can discuss merging the ones in the `apps` directory into this one with the potential eventual goal of making this the official one.

**Comment by stephenliang** [comment]
> This looks ok to me, but someone with more linting insight might want to take a look too.

I spoke with the Standards Working Group and we're going to merge the recommended defaults for now (to not block development) and circle back on any Code.org customization we want when we meet up.

**Pull request merged**
