### PR TITLE
Remove GalleryActivities model

### PR DESCRIPTION
**Pull request by Erin007**
****REMINDER: Change base!** 

[LP-1419](https://codedotorg.atlassian.net/browse/LP-1419)

Follow up to: #34453

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
yes!

**Comment by sureshc** [comment]
I suggest keeping the migration (`dashboard/db/migrate/20140408202946_create_gallery_activities.rb`).  It's a historical record of when/how we initially added that Model.

**Comment by davidsbailey** [comment]
I think you will need to remove the model before you can remove the table, right? not sure if that's why the table-dropping PR is failing in drone

**Comment by Erin007** [comment]
Rolling these into #34718 so I can get all of the changes needed merged in the correct order.

**Pull request closed without merging**
