### PR TITLE
Certificate on /congrats

### PR DESCRIPTION
**Pull request by Erin007**
This is the first step in putting the certificate on studio.code.org/congrats, mostly as  a means to confirm that the planned layout will work. 

If the user completes a Minecraft tutorial: 
screen shot 2017-11-01 at 3 26 31 pm

If the user completes any other tutorial: 
 
screen shot 2017-11-01 at 3 19 20 pm

### CODE REVIEW

**Comment by Erin007** [comment]
@tanyaparker  With these sizes and current layout plan, people will see the certificate and then the top of the images for the 3 boxes promoting other courses/activities (not shown here, but would be the same width as the teal boxes). Will that work?

**Comment by tanyaparker** [comment]
LGTM

**Comment by breville** [comment]
Do we want to share the certificate images between dashboard & pegasus?  We have a /shared/ directory for that purpose, and it then gets to use pegasus' server-side resizing.

**Comment by breville** [comment]
Also is this responsive yet?

**Comment by Erin007** [comment]
Yes, I should share the images between pegasus and dashboard. I'm just feeling paranoid about breaking the original /congrats by moving the images. The Certificate section is not yet responsive; the rest of the page so far is. I mostly wanted to put this together to make sure the layout plan wouldn't hide anything important below the fold.

**Pull request merged**
