### PR TITLE
Use fetch API when deleting rows during browser unload event

### PR DESCRIPTION
**Pull request by maddiedierker**
(Most of the useful information is in the Jira ticket.)

Rows weren't being deleted from NetSim if a user didn't explicitly disconnect from the simulation (e.g., if they refreshed the page or opened a new tab/window instead of clicking the "disconnect" button). This is because we were making a synchronous call during the browser's unload event, which is no longer supported: https://www.chromestatus.com/feature/4664843055398912

Using the fetch API with `keepalive: true` solves this issue. This means the request is async now, but the browser won't cancel it during unload like it normally would.

## Links

- [STAR-1186](https://codedotorg.atlassian.net/browse/STAR-1186)

## Testing story

Existing test coverage.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by breville** [comment]
Curious: Is an async XHR during unload actually likely to succeed?

**Comment by maddiedierker** [comment]
> Curious: Is an async XHR during unload actually likely to succeed?

not usually, but that's what the `keepalive` flag is for. normally, the browser would cancel any async requests

**Comment by breville** [comment]
That's interesting.  Are we concerned that it [doesn't seem to be implemented](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Browser_compatibility) on IE?

**Comment by maddiedierker** [comment]
i was concerned, but i tested the functionality on IE through a local saucelabs tunnel and it worked... which is more confusing

**Comment by breville** [comment]
It looks like Edge has it, [but IE11 doesn't](https://caniuse.com/fetch), if that's helpful?

fetch

Except in this case, we should make it happen :)

**Comment by maddiedierker** [comment]
we DM'd about this, but posting here for posterity --

tested again on saucelabs using Win10/IE11 and confirmed that the disconnected netsim sessions are cleared from the table ([video](https://drive.google.com/file/d/1Zw8gIz6QYnWYCxr0Elb0UKykB62Xe7Z3/view?usp=sharing)). thank you for double-checking @breville!

**Comment by maddiedierker** [comment]
another comment for future us --

we use [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch) to polyfill the fetch API in browsers that don't support it (like IE). it _does not_ support the keepalive property, which means the fetch request added here has a chance to be interrupted when the browser is unloading. i added a comment [here](https://github.com/code-dot-org/code-dot-org/pull/37268/commits/033a2906597ee47ab665f9ba833b95c4dd1e1292) so we remember that in the future. it's still an improvement over our current situation, which is not clearing any rows when the browser unloads. the alternative would be to rethink how we clean up netsim connections when a user navigates away from the page without explicitly disconnecting

**Review by breville — APPROVED** [review]
This looks like a good improvement given the current model.  Thanks for digging into it!

fetch2

**Pull request merged**
