### PR TITLE
Add key column to lesson (stage) table

### PR DESCRIPTION
**Pull request by dmcavoy**
# Background

For a long time we have used the the name of the lesson as both the key for the lesson and then display name. This leads to challenges. One example of these challenges is in translation. In order to keep the key consistent for translations we don't want levelbuilders to change the name in the Script DSL. Instead an engineer needs to update the display name in scripts.en.yml.

# Change

In order to get away from using the name as both the key and the value we are going to add a separate key value to lessons. This is going to take a couple steps:

1. Migrations to add key column to lesson(stages) table **<--- We are here**
2. Copy the value in the name column to the key column for all lessons **<--- AND We are here**
3. Update the Script DSL to use new format where a levelbuilder specifies both the key and name. Update all the existing script files to use this new format. 
4. Allow updating the display name of lessons (and lesson groups) but prevent levelbuilder from adding/deleting/changing the key of lessons and lesson groups in scripts which are marked as stable and included in the i18n pipeline. 

- [PLAT-242](https://codedotorg.atlassian.net/browse/PLAT-242)
- [PLAT-254](https://codedotorg.atlassian.net/browse/PLAT-254)

# Testing

Migration ran successfully.

Second migration successfully updated lesson key values locally.

### CODE REVIEW

**Comment by dmcavoy** [comment]
@davidsbailey This is failing because I made it so key should not be null. I think thats what we want in the long run but should I take it out for now until I do step 2 to add keys to all the lessons?

**Comment by davidsbailey** [comment]
> @davidsbailey This is failing because I made it so key should not be null. I think thats what we want in the long run but should I take it out for now until I do step 2 to add keys to all the lessons?

Ugh, fixtures. We'll probably want this requirement, but it is ok to add it in a later PR, and yeah it seems like it will not be possible to do until you've added keys to all the lessons.

**Review by davidsbailey — APPROVED** [review]
The plan looks great!

**Review by davidsbailey — APPROVED** [review]
looks great!

**Review by uponthesun — APPROVED** [review]

**Pull request merged**
