### PR TITLE
Wait for jquery before waiting for element

### PR DESCRIPTION
**Pull request by megcrenshaw**
Speculative fix for flaky teacher application tests.

The tests have been throwing an error at the end, only on Safari:
```
Then I wait until element "h1" contains text "Thank you for submitting your application!"
features/step_definitions/steps.rb:205
A JavaScript exception occured: Can't find variable: $ (Selenium::WebDriver::Error::JavascriptError)
./utils/selenium_browser.rb:39:in `create_response'
./features/step_definitions/steps.rb:206:in `block (2 levels) in '
./features/step_definitions/steps.rb:9:in `block in wait_until'
./features/step_definitions/steps.rb:8:in `wait_until'
./features/step_definitions/steps.rb:206:in `/^I wait until (?:element )?"([^"]*)" (?:has|contains) text "([^"]*)"$/'
./features/support/hooks.rb:28:in `block in '
features/acquisition_products/pd/teacher_application.feature:226:in `Then I wait until element "h1" contains text "Thank you for submitting your application!"'
37    # Replaces 'unexpected response' message with the actual parsed error from the JSON response, if provided.
38    def create_response(code, body, content_type)
39      super
40    rescue Selenium::WebDriver::Error::WebDriverError => exception
41      if (msg = exception.message.match(/unexpected response, code=(?\d+).*\n(?.*)/))
```

The `rescue Selenium::WebDriver::Error::WebDriverError` comes from the wait_until method:
https://github.com/code-dot-org/code-dot-org/blob/e62f19021bf167853920b2bf5be46645d34f4f82/dashboard/test/ui/features/step_definitions/steps.rb#L7-L19

The wait_for_jquery method includes a different rescue (`rescue Selenium::WebDriver::Error::ScriptTimeoutError`): https://github.com/code-dot-org/code-dot-org/blob/e62f19021bf167853920b2bf5be46645d34f4f82/dashboard/test/ui/features/step_definitions/steps.rb#L933-L942

I'm hopeful this will fix the flakey tests.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by megcrenshaw** [comment]
@breville Do you think it's kosher to have two separate waits?

**Review by nicklathe — APPROVED** [review]
I say let's try it, but this is a bit outside my wheelhouse so take my approval with a grain of salt.

**Comment by megcrenshaw** [comment]
I'm going to go ahead and merge this because I'm hopeful it will unblock people's builds

**Comment by breville** [comment]
Thanks for doing this; presuming it did help improve things?

I'm sometimes hesitant about putting calls like this into specific UI steps, in case they slow a lot of things down repeatedly when they really only need to be done once at page load, but it looks like this particular call has already been inserted in a few similar methods, and hopefully is close to a no-op in regular situations.

**Pull request merged**
