### PR TITLE
PL Launch 2023 - Update banner copy

### PR DESCRIPTION
**Pull request by kelbyhawn**
Updates to the PL homepage hero and skinny banners:
- New copy that focuses on middle and high school professional learning
- Change the button link to https://code.org/educate/professional-learning/middle-high

Updated on the following pages:
- https://code.org
- https://code.org/yourschool
- https://code.org/educate/curriculum/high-school
- https://code.org/educate/curriculum/middle-school
- https://code.org/teach (redirects to https://studio.code.org/courses?view=teacher)
- http://studio.code.org/home (logged in teacher account)

**Related PRs:**
- https://github.com/code-dot-org/code-dot-org/pull/49588
- https://github.com/code-dot-org/code-dot-org/pull/49556

**Asana task:** https://app.asana.com/0/0/1204109793558521

----

### Homepage banner
Screenshot 2023-03-08 at 9 55 32 AM

### Skinny banner
Screenshot 2023-03-08 at 9 56 04 AM

### Teacher dashboard (logged in) banner
Screenshot 2023-03-08 at 10 24 43 AM

### CODE REVIEW

**Review by megcrenshaw — APPROVED** [review]
Looks good! Do we have a pattern for extracting duplicate strings into a constant for use in many file types? Since the string is being used in .jsx, .json, .haml, and .yml files, I'm not sure there's a good way

**Review by dmcavoy — APPROVED** [review]
Looks good. Thanks for getting this out so quick

**Comment by kelbyhawn** [comment]
> Looks good! Do we have a pattern for extracting duplicate strings into a constant for use in many file types? Since the string is being used in .jsx, .json, .haml, and .yml files, I'm not sure there's a good way

@megcrenshaw that's an excellent question…we want to get this out asap so I'm going to merge as-is, but I can make a note to do some digging!

**Comment by megcrenshaw** [comment]
Yep, certainly not blocking! Something for the future if this keeps coming up –– don't spend time on it right now.

**Comment by mgc1194** [comment]
Text should be store as i18n strings. That allows for re-use and eventual translations.

**Comment by kelbyhawn** [comment]
> Text should be store as i18n strings. That allows for re-use and eventual translations.

@mgc1194 could we use the strings in the `pegasus/sites.v3/hourofcode.com/i18n/en.yml` file throughout?

**Comment by mgc1194** [comment]
I have seen i18n content, used in haml files, stored in `pegasus/cache/i18n/en-US.yml` but I am unsure what would be the right place for this updated strings.

**Pull request merged**
