### PR TITLE
Show Failure avatar in top instructions

### PR DESCRIPTION
**Pull request by Hamms**
Only when feedback is present, meaning that once reset is clicked or a hint
is viewed, the avatar will be reset to the regular avatar.

### CODE REVIEW

**Comment by Hamms** [comment]
This also means we can no longer be using ProtectedStatefulDiv to render the avatar ... are we losing much by this change? What was the impetus for building it that way in the first place?

**Comment by Bjvanminnen** [comment]
In general, ProtectedStatefulDiv is used when we have a bit of DOM that is modified from outside of React. This makes it so that we don't have to worry about React and non-React code having competing views of what the element should look like (React only owns initial render, after that any changes made will continue to hold).

I'd check that non-React code is currently modifying this. I'll take a look as well.

**Comment by Hamms** [comment]
It looks like [the dialogHelper](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/code-studio/levels/dialogHelper.js#L25-L31) _was_ but no longer is (and that code path should be removed). I'm not able to find anything else that'll end up influencing this element.

(also, [Circle failure](https://cucumber-logs.s3.amazonaws.com/circle/26277/ChromeLatestWin7_applab_templateBacked_output.html?versionId=jw9GvtyhGTS1mK51KGK2qZN.VdE1A_QR) is unrelated)

**Comment by Bjvanminnen** [comment]
It looks like there are a couple places in dialogHelper that reference bubble. If they really are dead code at this point, let's remove them.

If we're not being referenced outside of this component anymore, do we still need `id="bubble"`?

**Comment by Hamms** [comment]
Done and done!

**Pull request merged**
