### PR TITLE
Reimplement `cdo-varnish` Redirects in `cdo-nginx`

### PR DESCRIPTION
**Pull request by Hamms**
We are no longer using Varnish in our frontend servers, and so would like to also stop using the cookbook. As part of that effort, this PR moves the "redirects" configuration value from the varnish cookbook to the nginx cookbook, which was formerly referencing it.

Note that the redirects are also [still implemented in Varnish](https://github.com/code-dot-org/code-dot-org/blob/1026ccdf1a2940cd9d07b51e25b9030211bcfaac/cookbooks/cdo-varnish/templates/default/default.vcl.erb#L104-L112), which means we will be repeating ourselves until that cookbook can be fully removed.

Follow-up to https://github.com/code-dot-org/code-dot-org/pull/48328, which reverted https://github.com/code-dot-org/code-dot-org/pull/47982

## Testing Story

Tested on an adhoc to verify that this doesn't break any existing cookbook logic, but I'm not sure how to test the underlying functionality here outside of a production environment. Open to suggestions!

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by cat5inthecradle — COMMENTED** [review]
I'm doing a little bit of work that might allow you to just delete this code :)

**Comment by Hamms** [comment]
Even better!

**Comment by Hamms** [comment]
@cat5inthecradle what's the status on this? Have we finished implementing these redirects in cloudformation, so I can just delete this code?

**Comment by sureshc** [comment]
@dmcavoy Could @code-dot-org/acquisition-products-team work with Marketing to determine whether we can continue to own the following domain names, but STOP supporting users trying to navigate to those URLs? Enabling someone who requests a domain name like `monthofcode.com` and have our systems re-direct them to `hourofcode.com` adds significant complexity to our infrastructure.

Here are the specific domain names we suggest that we continue to own, but STOP redirecting them:

     'blockly.com'       => 'studio.code.org',
     'onehourofcode.com' => 'hourofcode.com',
     'onehourofcode.org' => 'hourofcode.com',
     'dayofcode.com'     => 'hourofcode.com',
     'dayofcode.org'     => 'hourofcode.com',
     'monthofcode.com'   => 'hourofcode.com',
     'weekofcode.org'    => 'hourofcode.com',
     'weekofcode.com'    => 'hourofcode.com',
     'yearofcode.co.uk'  => 'uk.code.org',
     'yearofcode.org.uk' => 'uk.code.org',
     'cseducationweek.com' => 'csedweek.org',
     'cseducationweek.org' => 'csedweek.org',

**Comment by sureshc** [comment]
@Hamms Note that while we continue to own csedweek.org and csedweek.com, we have identified name servers operated by the Computer Science Teachers Association to be the authoritative DNS for these domain names and they have configured those domain names to point to IP address where they host those sites.  We can definitely remove those redirects.

**Comment by dmcavoy** [comment]
> @dmcavoy Could @code-dot-org/acquisition-products-team work with Marketing to determine whether we can continue to own the following domain names, but STOP supporting users trying to navigate to those URLs? Enabling someone who requests a domain name like `monthofcode.com` and have our systems re-direct them to `hourofcode.com` adds significant complexity to our infrastructure.
> 
> Here are the specific domain names we suggest that we continue to own, but STOP redirecting them:
> 
> ```
>  'blockly.com'       => 'studio.code.org',
>  'onehourofcode.com' => 'hourofcode.com',
>  'onehourofcode.org' => 'hourofcode.com',
>  'dayofcode.com'     => 'hourofcode.com',
>  'dayofcode.org'     => 'hourofcode.com',
>  'monthofcode.com'   => 'hourofcode.com',
>  'weekofcode.org'    => 'hourofcode.com',
>  'weekofcode.com'    => 'hourofcode.com',
>  'yearofcode.co.uk'  => 'uk.code.org',
>  'yearofcode.org.uk' => 'uk.code.org',
>  'cseducationweek.com' => 'csedweek.org',
>  'cseducationweek.org' => 'csedweek.org',
> ```

@sureshc I can look into this. Can you help me with a couple things? Do you know the traffic each of these sites gets? What is the timeline we should be considering this change?

**Comment by Hamms** [comment]
That cleanup sound worth doing, but this PR is not the right place to make changes to our implementation. The goal of this PR is to move the existing implementation as-is from one cookbook to another; we can explore fixes and improvements in future changesets

**Review by cat5inthecradle — APPROVED** [review]

**Pull request merged**
