### PR TITLE
Share setting level

### PR DESCRIPTION
**Pull request by maddiedierker**
[LP-290](https://codedotorg.atlassian.net/browse/LP-290)

**Caveat:** This is the first contribution I have made to levelbuilder, so please let me know if there are any steps I'm missing!

Adds a `project_sharing` checkbox to levelbuilder. The end goal is to have this checkbox control the default behavior of the "Sharing" column in the "Manage Students" tab of teacher dashboard (this will be done in a follow-up PR).

**In levelbuilder:**
Screen Shot 2019-04-19 at 10 05 26 AM

### CODE REVIEW

**Review by davidsbailey — COMMENTED** [review]
Hi Maddie, the code that's here looks good, for going back and forth between what you see in the levelbuilder UI and what's in the database. however there is a separate flow that's missing here, which would cover (1) writing to the .script file when making levelbuilder edits and (2) updating what's in the DB from the .script file during rake seed:scripts. Both of these happen in script_dsl.rb. Take a look at another script property such as `pilot_experiment` in that file. 

For testing, please add test cases covering `ScriptDSL.parse` and `ScriptDSL.serialize_to_string` for this param in this file: https://github.com/code-dot-org/code-dot-org/blob/c5612b059c8162dbd0ac4cba5a5e04ff7bbbf439/dashboard/test/dsl/dsl_test.rb

I just discovered there are two files with the same name. ~definitely don't add your tests here by accident~:
https://github.com/code-dot-org/code-dot-org/blob/2907a608e0eb3a76edfbb07634eb823c6a9b5359/dashboard/test/models/dsl_test.rb#L3-L4

**Comment by maddiedierker** [comment]
that makes a lot of sense! thanks, @davidsbailey, i'll update and re-request review

**Comment by davidsbailey** [comment]
regarding the two dsl_test.rb files -- both are passing when I run locally. I will see which are getting run on drone and report back. if both are running and passing, we could remove that warning message in test/models/dsl_test.rb.

**Comment by maddiedierker** [comment]
PTAL! i added `project_sharing` to ScriptDSL so it can be serialized/parsed, wrote a few unit tests, and made sure that editing a script's `project_sharing` value through the UI updates both the database and the .script file

**Comment by davidsbailey** [comment]
top-level comment -- I confirmed in [this drone run](https://drone.cdn-code.org/code-dot-org/code-dot-org/932/1/4) that both dsl_test files are being run. while we are thinking about this, would you mind updating this comment to stop saying scary things about not running one of these test files (I couldn't even tell which file it was saying wouldn't be run 😂 ) and make it say instead that we should consider consolidating them? https://github.com/code-dot-org/code-dot-org/blob/2907a608e0eb3a76edfbb07634eb823c6a9b5359/dashboard/test/models/dsl_test.rb#L3-L4

**Review by davidsbailey — APPROVED** [review]
looks great Maddie! LGTM after fixing `test_create` in the drone output.

**Comment by maddiedierker** [comment]
@davidsbailey thank you for checking on those tests! i'll make a follow-up PR to remove the comment and condense those 2 test files into a single file 😄

**Pull request merged**
