### PR TITLE
Move email files in bin/ to appropriate subdirectories.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by aoby** [comment]
lgtm

This might be a good time to consolidate all the specific mailing directories (i.e. hoc-2015-*). 

Maybe something like?

```
/bin
 /mail
   /common (former contents of bin/mailing-common)
   /hoc-2015-...
   /hoc-2015-... 
```

**Comment by ashercodeorg** [comment]
How about...

/bin/cron/
  deliver_poste_messages
/bin/mailing/
  common/
    (former contents of /bin/mailing-common/ + other stuff)
  generate/
    (the generate-mailing-list-\* files in /bin/)

What subdirectory should hoc-2015-\* and mailing-1-5-advocacy-ca and such live in?

**Comment by aoby** [comment]
I like it.

I'm not sure what a good name for the parent directory of those specific
mailings would be: archive (misleading for the current one), mailings
(redundant), instances?

**Comment by ashercodeorg** [comment]
Though perhaps redundant, I think mailings is the most self-descriptive. So I went with it.

Also removed mailing from filenames and changed to numeric months.

Please take another look.

**Comment by ashercodeorg** [comment]
Since this seems more complicated than initially thought, this PR is being dropped in favor of future PRs doing the same work in more pieces and more cleanly.

**Pull request closed without merging**
