### PR TITLE
Section Setup: Show section code on Manage Students table 

### PR DESCRIPTION
**Pull request by Erin007**
[Spec](https://docs.google.com/document/d/1YaC8yPL4QUNshj0zXmCZJ1o-FcGYb1Dexv9J0-acHuM/edit#heading=h.hupraqk0xxj5) - Requirement 2
[LP-1388](https://codedotorg.atlassian.net/browse/LP-1388)

Add the section code to the top right of the Manage Students table for section types that have section codes (word, picture, email login). Clicking the section code copies the join link for the section, and a tooltip explains. 

copy-section-link

### CODE REVIEW

**Comment by Erin007** [comment]
@fontie715 The spec says "it should be obvious when the link is copied".  Is an alert what you had in mind?

**Review by clareconstantine — APPROVED** [review]
Woo! I think the alert is a very clear way to communicate to the user, but if we want something that doesn't involve another user click, we could try something like replacing the section code div with text that says "Link copied!" for 5 seconds and then go back to displaying the div with the code.

**Comment by Erin007** [comment]
Great idea, @clareconstantine! Updated: 
link-copied!

**Comment by clareconstantine** [comment]
Ooh it looks great!

**Pull request merged**
