### PR TITLE
schama changes after running ai tutor interaction feedbacks migration

### PR DESCRIPTION
**Pull request by mgc1194**
Added the schema changes for the migration ai tutor interaction feedbacks migration since @ebeastlake was not able to produce these schema changes on her environment.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by sureshc** [comment]
Our managed staging server is the authoritative source of truth for `schema.rb` and `schema_cache.yml`. It computes those by inspecting the tables in the staging database, and it commits those files (and pushes those commits to origin/GitHub) if there are differences in what it computes vs what's currently committed to the staging branch. It typically sees and computes those differences after applying Rails migrations.

We probably do not need to commit any changes to schema.rb at this point. We should investigate while Rails migrations are applying differently to some Engineer's development environments, though.

**Comment by sureshc** [comment]
Confirmed that these changes were computed, committed, and pushed by staging when it ran the migration https://github.com/code-dot-org/code-dot-org/commit/ff6a1f9d3e6db2cc732ffa0f3f550a9ce6b8c301

**Comment by ebeastlake** [comment]
Great, thanks, that's what we hoped! Thanks for weighing in, @sureshc!

**Comment by ebeastlake** [comment]
Closing due to Suresh's comments above.

**Pull request closed without merging**
