### PR TITLE
Remove translations for flex categories

### PR DESCRIPTION
**Pull request by dmcavoy**
Removes the translations for the old flex categories. We no longer need these as we have fully moved over to lesson groups (besides the script edit gui which is in process).

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
LGTM, though would like Elijah's approval too in case there is any i18n-related concern. Also, same comment from other PR applies -- if this is the PR that will break the script edit gui, then you could consider holding off on this until you've got the script edit gui moved over to lesson groups, if that makes local development of that move any easier.

**Comment by bethanyaconnor** [comment]
Sorry if you're already tracking this but it looks like these strings are still accessed [here](https://github.com/code-dot-org/code-dot-org/blob/34f5fc07675b042ca5cb00730b44178f3551dc88/dashboard/app/controllers/scripts_controller.rb#L119)

**Comment by dmcavoy** [comment]
> Sorry if you're already tracking this but it looks like these strings are still accessed [here](https://github.com/code-dot-org/code-dot-org/blob/34f5fc07675b042ca5cb00730b44178f3551dc88/dashboard/app/controllers/scripts_controller.rb#L119)

Thanks @bethanyaconnor. That is only used in the script edit gui which I am in the process of updating. Its only used internally for curriculum editing and very infrequently. I already have most of the move over to the lesson groups for script edit gui here: https://github.com/code-dot-org/code-dot-org/pull/34429 which includes that field you mentioned

**Comment by Hamms** [comment]
LGTM from an i18n perspective; I've confirmed that the lesson group strings are all in crowdin, and will inherit the translations from these when they get deleted.

**Pull request merged**
