### PR TITLE
Add adhoc to ignored hosts for milestone_parser.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Will: Should this fix the issue?

**Comment by wjordan** [comment]
Yup!

**Comment by wjordan** [comment]
Err actually no, maybe not

**Comment by ashercodeorg** [comment]
This just makes it so that we don't count lines of code done on adhoc, right?

**Comment by wjordan** [comment]
This exclusion would only make it so that the count lines of code script doesn't fetch the logs from adhoc hosts to include in the total count, across all daemon hosts in all environments. You'll need to edit the crontab entry in order to not count lines of code done on adhoc-environment instances themselves.

**Comment by ashercodeorg** [comment]
Good. As such, I think we want to keep this change (separate from my resolving the honeybadger issue).

For accuracy, we don't want to include adhoc lines of code in the count shown to users. But we do want to run the cron on an adhoc machine to keep the adhoc environment as close as possible to prod.

Sound right?

**Comment by wjordan** [comment]
Sounds good!

**Pull request merged**
