### PR TITLE
Create EnvironmentAwareDynamicConfigHelper

### PR DESCRIPTION
**Pull request by Hamms**
And extract existing environment-aware logic out of DCDOBase and GatekeeperBase into it. Specifically, this is a proposed modification to https://github.com/code-dot-org/code-dot-org/pull/45235

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by sureshc** [comment]
This looks great! How would we test it? If our production system happens to use the wrong adapter the impact could be significant. Is there a way to keep the current logic, and log an error if the new logic compute a different adapter? And then follow up with a permanent switch to the new logic?

**Comment by Hamms** [comment]
Can you clarify; are you asking about testing the change in this PR or in the base PR? Because I would note that this isn't new logic, just a reorganization of the existing logic. More specifically, of the _new_ existing logic being added in https://github.com/code-dot-org/code-dot-org/pull/45235.

I would expect that we'd test both sets of changes the same way and probably at the same time; note that this PR is not attempting to merge into staging, but rather into the other PR.

**Comment by Hamms** [comment]
Added a unit test! PTAL

**Review by sureshc — APPROVED** [review]
This is great! The tests have me feeling very confident about deploying this refactored logic :)

**Pull request merged**
