### PR TITLE
Add view lesson plan links to final Course A - F scripts

### PR DESCRIPTION
**Pull request by sfilman**
We've created /s/coursea - /s/coursef for the actual release in August. Need to light up lesson plan links for these scripts.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
This change has other impacts, including showing any teacher markdown, changing where the script redirects on completion, etc. These also all intentional and desired?

**Comment by sfilman** [comment]
@ashercodeorg can you say more about the changing where the script redirects on completion part?

For teacher-facing markdown, yes, we want that visible.

**Comment by ashercodeorg** [comment]
All I know is what I can ascertain from reading [this](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/helpers/script_levels_helper.rb#L38-L46). It looks like this change will mean that the user will get redirected to "code.org/congrats/coursea" rather than "code.org". Note that the former seems to redirect to "code.org/congrats". Perhaps this is because we haven't made Course A-F certificates?

**Comment by sfilman** [comment]
Since we haven't shipped these scripts yet, I'd like to move ahead, and I'll follow up with ryan on getting certificates. Sound OK?

**Pull request merged**
