### PR TITLE
Change the id column to be consistently a string instead of a symbol

### PR DESCRIPTION
**Pull request by trevorb**
Basically the extra id column was caused by inconsistent usage of 'id' and :id as the name of the id column in values.  Let's be consistent and use the string version since all the other columns are strings.

### CODE REVIEW

**Comment by davidsbailey** [comment]
LGTM. Nice catch Trevor! It looks like there is still a mix of strings and symbols in https://github.com/code-dot-org/code-dot-org/blob/staging/shared/test/test_tables.rb . Please also check there. You can run those tests with `cd shared; rake test` or `cd shared/test; ruby test_tables.rb` .

**Comment by trevorb** [comment]
Nice, I didn't realize you could directly run the test_tables.rb.  Good to know!

@davidsbailey Here's the changeset updating the tests

**Comment by davidsbailey** [comment]
Looks good! Yeah, I just learned about running individual ruby tests last week.

**Comment by laurelfan** [comment]
Yes you can run all ruby test files individually, they are all standalone ruby scripts (in rails you need to do -Itest to add the test helpers to the include path, in Pegasus and shared they are included for you).

**Pull request merged**
