### PR TITLE
Optimize a large gif file

### PR DESCRIPTION
**Pull request by islemaster**
This large gif is not only taking quite a bit of space in our repo: It's also responsible for some of our slowest pegasus requests:

screenshot from 2018-08-24 16-09-13

Using `gifsicle --batch --optimize=3 --colors 128` reduced from 24MB to 10MB.

Going to follow this up with a quick batch-edit of all our gifs in this part of the site.

### CODE REVIEW

**Comment by joshlory** [comment]
10mb still seems crazy-high.  Should these be [`<video>` tags](https://caniuse.com/#feat=video)?

**Comment by balderdash** [comment]
Whoops, ignore that trello card.

**Comment by wjordan** [comment]
We already have an image-optimization middleware running on our site. Hand-optimizing individual images within our repo is unnecessary. This image is already being optimized to 16804221 bytes from its original 24924082 bytes.

If you're still concerned that the image optimization already running is not producing 'ideal' images (e.g., if GIF should all be even more heavily compressed than they already are), I'd strongly recommend tuning the existing image-optimization configuration rather than giving up on it entirely and running optimizers manually on our repo content.

**Comment by islemaster** [comment]
:man_facepalming: I totally forgot about that.  Sorry Will.

This is the type of asset I'd love to offload to storage outside our repository, but I won't waste my time manually optimizing it.

**Comment by breville** [comment]
The image appears quite large in context on https://code.org/about/2017.  Furthermore, its resolution exceeds its rendered dimensions for non-retina displays, which seems unnecessary given that a lot of it is low-res pixel art.  

It would be worth confirming with whoever authored this page via @tanyaparker, but I think it would be reasonable to resize the image anywhere down to half its current size, both in terms of GIF dimensions and in terms of how it appears on the page, and there's no need to have extra pixels just for retina displays.  

Unfortunately pegasus' own URL-based resizing doesn't seem to support animated GIFs, so this would need to be done to the source GIF itself.

**Comment by wjordan** [comment]
> Unfortunately pegasus' own URL-based resizing doesn't seem to support animated GIFs

#24480 takes a stab at this

**Pull request closed without merging**
