### PR TITLE
added page numbers to k5 toc

### PR DESCRIPTION
**Pull request by kapone97**

### CODE REVIEW

**Comment by tanyaparker** [comment]
LGTM

**Comment by tanyaparker** [comment]
Oh, and is it clear to teachers what bold means? Is there a key?

**Comment by kapone97** [comment]
The bolded items are explained in each course overview. I wanted to leave this toc just about page numbers because the explanations are kind of lengthy.

**Comment by tanyaparker** [comment]
Sounds good!

**Pull request merged**
