### PR TITLE
Increase varnish `timeout_idle`

### PR DESCRIPTION
**Pull request by wjordan**
This PR changes the [`timeout_idle`](https://varnish-cache.org/docs/trunk/reference/varnishd.html#timeout-idle) parameter in `varnishd` startup settings:

> Units: seconds
Default: 5.000
Minimum: 0.000
Idle timeout for client connections. A connection is considered idle, until we have received the full request headers.

Needed for better compatibility with Elastic Load Balancer idle connection default.

### CODE REVIEW

**Comment by wjordan** [comment]
@ewjordan FYI the chef cookbook integration tests automatically run on matching branch name. The `varnish` integration tests may be broken for other unrelated reasons - it depends on an `ngrok` tunnel which might no longer be authentic sting properly.

**Comment by wjordan** [comment]
Oops, meant @ewjordan (sorry github-eric)

**Comment by ewjordan** [comment]
Ah, so this might pass if it's on actual staging or test?

**Comment by wjordan** [comment]
If the failure is in the cookbook chef integration test only, it should be
safe to ignore (these tests are not run anywhere else).

**Pull request merged**
