### PR TITLE
Remove duplicate DANCE_PARTY_NAME in script_constants 

### PR DESCRIPTION
**Pull request by Erin007**
Kept `DANCE_PARTY_NAME = 'dance'.freeze, # 2018 hour of code` on line 75.  

I think we just had multiple people who all needed this to make updates for Dance Party, and we didn't catch the dupe when we all merged.

### CODE REVIEW

**Comment by joshlory** [comment]
Spoke too soon... is the test failure related?

**Comment by Erin007** [comment]
Yes, the failure is related 😞
screen shot 2018-11-09 at 4 49 27 pm
Removing this script name changed the order of others. It's a quick fix; I'll update.

**Comment by Erin007** [comment]
@joshlory That test passes locally with my latest commit.  Wait for Circle or get this in? I know some cron jobs are failing, but I'm still fuzzy on how urgent it is to get this fix into staging.

**Comment by joshlory** [comment]
I don't know enough about the test failure to make that call, sorry 😕.

**Comment by maddiedierker** [comment]
bah, sorry @Erin007, i updated some tests to reflect the new order [here](https://github.com/code-dot-org/code-dot-org/pull/25570/files). your fix to `test_section_api_helpers.rb` is good, but circle will likely fail in `test_script_constants.rb`

**Pull request merged**
