### PR TITLE
Upgrade ejs to 2.6.1

### PR DESCRIPTION
**Pull request by islemaster**
Upgrades `ejs` from `0.8.4` to `2.6.1`.  Also updates `ejs-compiled-loader`'s dependencies so it uses the same version of `ejs` that we depend on directly.

Here's the [1.x ejs repository](https://github.com/tj/ejs) and the [2.x ejs repository](https://github.com/mde/ejs).  There are definitely breaking changes in the move to 2.0; the README in the 1.x repository says:

> NOTE: Version 2 of EJS makes some breaking changes with this version (notably, removal of the filters feature).

The [2.x Changelog](https://github.com/mde/ejs/blob/master/CHANGELOG.md#v201-2015-01-02) seems to list breaking changes in its first entry.

- Single custom delimiter (e.g., `?`) with `delimiter` option instead of `open`/`close` options
  Configuration passed to `compile` or `render` customizing EJS open/close tags.  We don't use this.
- `include` now runtime function call instead of preprocessor directive
  It looks like we never use this.
- Variable-based includes now possible
  Does not sound like a breaking change, and we don't use `include` right now.
- Comment tag support (`<%#`)
  Does not sound like a breaking change, and we don't use this combination of symbols anywhere right now.
- `data` and `options` now separate params (i.e., `render(str, data, options);`)
  This sounds like it should break our code all over the place.  However, we pass options in `compile` whose signature hasn't changed:
  https://github.com/code-dot-org/code-dot-org/blob/9231ab43e52de7b3ba8f25651022030002adf0e5/apps/tasks/ejs.js#L13-L18
  And, as far as I can tell, every place we call render we only pass `data` - and even if we didn't, these calls are backwards-compatible, just in case. See [the new usage docs](https://github.com/mde/ejs#usage)
- Removed support for filters
  I already checked and we're not using the [Filters feature](https://github.com/tj/ejs#filters).

### CODE REVIEW

**Comment by islemaster** [comment]
I'm actually _more_ worried that this passed on Circle...

**Comment by islemaster** [comment]
I've now reviewed the breaking changes in 2.0 and I'm more convinced that none of them affected us.  Doing manual testing now.

**Comment by islemaster** [comment]
Still doing manual testing, but adding reviewers now in case there are any ideas on better ways to verify this change.

**Comment by islemaster** [comment]
Manual testing of netsim and craft, two of our biggest users of ejs, revealed no problems.

**Comment by islemaster** [comment]
That sounds great!  It's already a TODO in the code:

https://github.com/code-dot-org/code-dot-org/blob/fafbac6aba2c9c8810d8f07e0570947c5b3a3f4d/apps/src/maze/levels.js#L12-L18

Do I remember correctly that you've done work in the past to move levels out of `levels.js` files and into our regular levelbuilder flow?  Seems like that's the right direction to go here.

**Comment by Hamms** [comment]
I have, and it's for precisely reasons like this that I'd like to continue that work!

**Comment by islemaster** [comment]
Noted in the tech debt roadmap under the existing item for converting levels.js content to levelbuilder.

**Pull request merged**
