### PR TITLE
Adds a terms_of_service_version column to users.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Upcoming PRs will (1) open starlabs to any student (young or old) having a teacher who has accepted the upcoming TOS update and (2) populate the column from the UI when a teacher accepts our upcoming TOS update.

Based on previous migrations adding a column to the `users` table, this PR will cause a few HoneyBadger alerts. The cost-benefit to the column suggests that this fact should not block this PR.

UPDATE: The migration took approximately twenty-two (22) minutes to complete in production when pushed at approximately noon PDT. It caused an ELB Latency page from pagerduty.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Note that I'm not specifying the position of the column as there is no "natural" place for it in my mind. Feel welcome to suggest an `:after` clause.

Note that I'm putting this in the `users` table, as I believe this to be where it belongs. That said, please think about this, I'd like to keep the `users` table as thin as possible.

EDIT (UPDATED): Hmm, the `users` table may not be right, as doing so would require us to allow students to access their teachers' `users` model. Thoughts?

**Comment by tanyaparker** [comment]
What do you mean it would require us to allow users to access other users?

**Comment by jeremydstone** [comment]
Do we want track an accepted TOS version # in addition to or instead of the timestamp? It may make it easier/clearer to do things like know if someone is on the current version of TOS. (Easier to compare against something like version=4 than timestamp > XXX.)

I have the same question as Tanya about what you mean by users accessing other users.

This seems like a core Users table thing to me. Fundamental account/login data, especially that all users must have, should go on the users table. (As a counterexample, we have a ton of miscellaneous stuff like prize tracking that I'd argue shouldn't be on users table.)

**Comment by ashercodeorg** [comment]
In terms of users accessing users, right now, a `user` is not allowed to access another `user` ([code here](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/ability.rb#L21)), noting exceptions like [this here](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/ability.rb#L66) for a teacher to access their students. This would require a student being able to access their teachers' `users`. Given that a student can join an arbitrary section (simply by knowing the section `code`), this could create a hole.

**Comment by ashercodeorg** [comment]
In terms of version number vs. timestamp, I had this discussion with @poorvasingal. The offline decision was to do timestamp, though I'm indifferent to storing the version number in addition to timestamp.

**Comment by jeremydstone** [comment]
Asher & I discussed this. To capture our discussion here: we landed thinking that an integer version of TOS that we have as a constant in the code that we increment on major TOS changes is much easier to administrate. If it's a timestamp, it's very hard to set that timestamp correctly in advance (have to have clairvoyance about the moment of DTP, or store in database or something) and ensure that you don't have ill side effects like users having to accept TOS more than once.
I still think this belongs in users table - we should figure out how to write the code to access it in ways that addresses Asher's concerns.

**Comment by ashercodeorg** [comment]
Updated DB field from `terms_accepted_at` timestamp to `terms_of_service_version` (should this be `terms_version` or `tos_version`?) integer.

**Comment by tanyaparker** [comment]
I like terms_of_service_version > tos_version > terms_version.

**Comment by jeremydstone** [comment]
I agree w/Tanya that I like terms_of_service_version, as you have it, the best.

LGTM!

**Comment by ashercodeorg** [comment]
Given that I haven't heard strong dislike of the implications of this PR (in this thread or from offline queries), I'm going to merge when DTS opens.

**Comment by ashercodeorg** [comment]
CC @aoby (as DOTD likely to DTP this DB migration): Note that this migration is expected to take a few minutes to complete.

**Pull request merged**
