### PR TITLE
Disabled STI for sections model so type column doesn't cause problems

### PR DESCRIPTION
**Pull request by aoby**
https://github.com/code-dot-org/code-dot-org/pull/9341 introduced the `type` column, but it will cause `ActiveRecord::SubclassNotFound` errors when set because rails uses that column to indicate single table inheritance by default. Fixed by renaming to `section_type`

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Thanks for attempting to fix! That said, I'm not convinced this is the best approach, I think dropping the column and (possibly) adding `section_type` makes more sense.

**Comment by aoby** [comment]
Switched to column rename. PTAL

**Comment by ashercodeorg** [comment]
LGTM.

**Comment by ashercodeorg** [comment]
Again, thanks for doing this!

**Pull request merged**
