### PR TITLE
Allow signed out users to access https://studio.code.org/certificates/batch

### PR DESCRIPTION
**Pull request by juanmanzojr**
Allows signed out users to access https://studio.code.org/certificates/batch while still preventing students from accessing.

### Signed out user
Screenshot 2023-10-13 at 11 48 39 AM

### Signed in student denied access
Screenshot 2023-10-13 at 11 51 07 AM

### Signed in teacher still has access
Screenshot 2023-10-13 at 11 52 05 AM

## Links
- jira ticket: [here](https://codedotorg.atlassian.net/jira/software/c/projects/ACQ/boards/64?selectedIssue=ACQ-1026)

## Testing story
Local

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by TurnerRiley — COMMENTED** [review]
@dmcavoy Do we want to update the message shown to students to say that you must be signed in as a teacher or signed-out to view it? Or should we keep the message the same?

**Comment by dmcavoy** [comment]
> @dmcavoy Do we want to update the message shown to students to say that you must be signed in as a teacher or signed-out to view it? Or should we keep the message the same?

I don't think we want to encourage students to get certificates for themselves so I think we keep it. Maybe it pushes someone to make a teacher account if they are actually a teacher

**Review by TurnerRiley — APPROVED** [review]
Looks great once tests are passing!

**Comment by davidsbailey** [comment]
may I ask what the goal is here for allowing signed out access?

**Comment by dmcavoy** [comment]
> may I ask what the goal is here for allowing signed out access?

The Batch Certificates page is specifically for Hour of Code certificates. We link to it from the Hour of Code site so requiring login to use it when people could be doing Hour of Code anywhere seems like it not in line with the result we want which is for people to easily be able to get their certificates for students. We are also going to add to the page to promote Code.org as well to encourage engagement beyond Hour of Code.

**Review by davidsbailey — APPROVED** [review]
Sounds great, thank you Dani!

**Pull request merged**
