### PR TITLE
Backport Production > Staging

### PR DESCRIPTION
**Pull request by islemaster**
Question: Why is there a diff here?

### CODE REVIEW

**Comment by davidsbailey** [comment]
Because @hamms did a hotfix

**Comment by Hamms** [comment]
Hmm, I thought that given that I applied the hotfix to staging then cherry-picked it into production, a backport was unnecessary. What am I missing?

**Comment by davidsbailey** [comment]
http://wiki.code.org/display/PROD/How+to+Hotfix "Finally, remember to merge from production->staging." 

cherry-pick creates a copy of the commit, and that copy will not be present in staging until backported.

**Comment by islemaster** [comment]
Even so, if the hotfix was applied on staging and then cherry-picked to production, I'd expect the backport to show commits but no actual code diff.  Do you both agree that the code diff shown here is actually putting things into the state we want them to be in?

**Comment by Hamms** [comment]
Yeah, I'm not sure why there is a diff; https://github.com/code-dot-org/code-dot-org/pull/23510 should have already applied these changes. But yes, the result of the diff does appear to be how we want things to be.

**Comment by davidsbailey** [comment]
I think this looks good to merge.

 #23510 hasn't reached production yet, so you're getting a diff between production and what production (without  #23510) looked like at the time it split from staging. 

if you were to create a new branch `git fetch; git checkout production ; git checkout -b production-staging-backport; git merge staging; git push` then https://github.com/code-dot-org/code-dot-org/compare/staging...production-staging-backport would show no diffs.

**Pull request merged**
