### PR TITLE
hoc2015: Better collisions between sprites and goals.

### PR DESCRIPTION
**Pull request by breville**
We now have accurate collisions between the sprite's collision rectangle and a nice tall rectangle appropriately placed over each goal.

screenshot 2015-11-20 16 42 27

Legacy Infinity & Playlab goal levels continue functioning as before.

### CODE REVIEW

**Comment by breville** [comment]
fyi @caleybrock @cpirich

**Comment by islemaster** [comment]
I found a bug! :stuck_out_tongue_winking_eye: 
bb8-regression

**Comment by islemaster** [comment]
There's a horizontal component to this problem too.
bb8-regression2

**Comment by islemaster** [comment]
Levels 7 and 8 feel a LOT better.  I wonder if maybe the collision rects should be even smaller; in this example, it doesn't really feel like the characters should touch.

r2-collision

I can also see the argument for leaving this as-is, since we want to be pretty forgiving.  It might be frustrating later on when you're trying to avoid characters though.

**Comment by islemaster** [comment]
Nit: This might actually be a good thing, but I feel like I should have to go left a little bit to collect this guy in puzzle 9.  That gap is wide enough that you can get through without hitting him, but you usually hit the left wall as you go through and he gets collected automatically.

r2-collision2

**Comment by islemaster** [comment]
Here's a case where I want things to be more forgiving.  Notice how much of R2 overlaps the log - there's a really nice pseudo-perspective to it.  But the Stormtrooper "touches" me before his feet are even in contact with R2's dome.

r2-collision3

This is SO MUCH better than it was though - before we had the opposite problem with an early collision when R2 was above the Stormtrooper, that was accentuated by how much taller the Stormtrooper is.

**Comment by islemaster** [comment]
This's one's probably a combination of a sprite offset that needs tweaking and collision that needs tweaking.  Look at how the Tauntauns walk on the very top edge of the "hallways" almost like they're pasted to the walls.  Then, when R2 rolls across the lower edge of the hallway like he could slip by them, they collide.

r2-collision4

**Comment by islemaster** [comment]
Overall LGTM pending fix for levels 1-6.  These levels are way more fun with better collision checks!  Nice work.

**Comment by breville** [comment]
@islemaster thanks for the excellent catches.  I fixed the bug (had to incorporate a scaled down goal image as used in levels 1-6) and also shrank the collision rectangles to 0.8 their full sizes, to require slightly closer contact.  We can tweak this more going forward, too.

I'll work on sprite/character collisions next.  Then Tauntaun positioning.

**Pull request merged**
