### PR TITLE
Make a mega section

### PR DESCRIPTION
**Pull request by Erin007**
This includes a script that will create:
- a 250 student section assigned to the script Course A 2019
- UserLevels for each student for each level in the Course A 2019 & Course A 2018 as progress, 
- a TeacherScore for each UserLevel associated with the scripts
- TeacherFeedback for each Level in the scripts for each student in the section

### CODE REVIEW

**Comment by Erin007** [comment]
Running this seed step took a long time, too. mega_section isn't part of the seed tasks (yet) and wouldn't change often so we could leverage incremental seeding to only pick up the difference? 

Screen Shot 2020-03-23 at 12 57 08 PM

I like this approach better than a factory (#33688) though because it means there could be a mega section on staging that engineers and product could play with to get a feel for user experience.  

Other thoughts?

**Comment by uponthesun** [comment]
> I like this approach better than a factory (#33688) though because it means there could be a mega section on staging that engineers and product could play with to get a feel for user experience.

Great point!
 
> Other thoughts?

I think it's still worth looking into how we can optimize this. Inserting 25000 records one at a time via ActiveRecord is going to maximize the total overhead incurred since it has to happen on each write. (Might be interesting to think about - what are all the things that happen between when you do a write and where are all the places that can add latency?)

We might have existing techniques from either backfill scripts or other seeding logic we can use, and doing general research on inserting a lot of records at once could be good too.

**Comment by Erin007** [comment]
Brad's optimizations made this run way faster! Thank you, Brad! 

Screen Shot 2020-03-26 at 11 59 15 AM

More details in #33808 and this helped me wrap my head around the changes too: https://stackoverflow.com/questions/14098031/whats-the-difference-between-the-build-and-create-methods-in-factorygirl

**Comment by Erin007** [comment]
I added progress for Course A 2018 since that course doesn't have standards associations, so we can test page load time between the two scripts and between the standards flag (standardsReport) being enabled or not.

**Review by uponthesun — APPROVED** [review]

**Pull request merged**
