### PR TITLE
Remove properties and tables apis

### PR DESCRIPTION
**Pull request by davidsbailey**
### Background
* The [Firebase cleanup checklist doc](https://docs.google.com/document/d/1XOfCIzsqXQwUMgwVYrdoDm3hDnibTkWXZHZriCUKVf8/edit#heading=h.2iv7cmdfzps5) contains a list of all the past and future firebase cleanup work, including links to past pull requests.

### Description

Now that all applab projects are using Firebase, the TablesApi and PropertiesApi REST APIs are unused. This PR removes them from Dashboard and Pegasus, and also removes the `rack-attack` gem which was used to enforce rate-limiting on those APIs. It leaves the helper classes in `shared/middleware/helpers` which allow using the underlying ruby APIs, in part to break this cleanup into smaller chunks, but also because there may be some discussion as to whether those ruby APIs should be kept around.

### CODE REVIEW

**Comment by davidsbailey** [comment]
@wjordan , can you please review? @jeremydstone and @joannepolsky , I'm CCing you in case you are interested.

**Comment by davidsbailey** [comment]
Oops, yes, the vcr fixtures for tables and properties can be removed too.

**Comment by davidsbailey** [comment]
ready for another look, @ashercodeorg

**Comment by ashercodeorg** [comment]
Looking to @wjordan or others to review, my time is tight at this point. Skimming, LGTM, other than I'm not sure how renaming the migration works if the migration were to be rerun. E.g., I don't know if the database stores the name of the file or the number of the file.

**Comment by davidsbailey** [comment]
I'm having trouble pulling the trigger on removing this code, for the reasons @wjordan listed: it represents a significant engineering effort, could potentially be useful in the future, and will be much harder to un-revert than it will be to keep around. That said, the rule in these scenarios is You Aren't Gonna Need It.

@Bjvanminnen @islemaster can you think of any reasons that we'd want to access a key-value store based on DynamoDB, via REST API, any time in the next 6-12 months? 

@jeremydstone , I believe you'd mentioned some future need for DynamoDB access, but I believe that was going to be from Ruby only, which wouldn't depend on the REST APIs being removed here.

**Comment by davidsbailey** [comment]
addendum: one alternative here is to remove the TablesApi and PropertiesApi (and the corresponding rate limiting) from dashboard and pegasus, but keep the API implementations around. That would look like this: https://github.com/code-dot-org/code-dot-org/compare/disable-properties-tables-apis?expand=1

**Comment by Bjvanminnen** [comment]
I say delete away (unless anyone has a current use case where they expect us to need this code in the near-medium future).

**Comment by islemaster** [comment]
I've got no expected use case in the next 6-12 months.

**Pull request merged**
