### PR TITLE
Delete make-professional-development-certificate and associated email copy.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Note that GitHub [search](https://github.com/code-dot-org/code-dot-org/search?q=k5-professional-development-certificate-2014) shows three usages of the [image](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/images/k5-professional-development-certificate-2014.png):
* The `make-professional-development-certificate` script being deleted in this PR.
* The `professional-development-workshop-section-receipt.md` email. This email should be deleted after all old workshops have run their course.
* The `professional-development-workshop-section-receipt.md.orig` copy being deleted in this PR.
After the old workshops have run their course, the image (possibly also the email, I don't know what our practice there is) should be deleted.

### CODE REVIEW

**Comment by aoby** [comment]
It looks like the email template is still used by the legacy [K5 workshop dashboard](https://github.com/code-dot-org/code-dot-org/blob/65a46d3b8cb8eb616dc8fb5e5ab63eeebf80bcee/pegasus/forms/professional_development_workshop.rb#L77), which still has a small number of pending workshops.

So we don't want to delete the certificate image yet. The customized certificate is generated from the header in the [email template](https://github.com/code-dot-org/code-dot-org/blob/de5769cff62576abddd4ccfec611ed2474b63bf8/pegasus/emails/professional-development-workshop-section-receipt.md#L5).

I'm ok with deleting the unused `make-professional-development-certificate` bin script however, and the (most likely accidentally committed) `.orig` file.

**Comment by ashercodeorg** [comment]
If it is still in use, should the certificate image be updated? Should Course 4 or the Accelerated Course be mentioned? Should Courses A to F? Is PD still seven hours? Etc.

**Comment by aoby** [comment]
Good question. I'll ask Ryan, but I presume we don't care much about this because it's just draining the queue and then we'll be done with it. We have low-pri longer term plans to actually deprecate it and remove the code. Workshops on the new pd dashboard have an updated certificate and email. We just don't want to break functionality while there are still active workshops in the old system.

**Comment by ashercodeorg** [comment]
Is there a reason we haven't or can't transfer old style workshops to new style workshops and kill the former?

**Comment by aoby** [comment]
Just budget AFAIK. We've talked about it, and always prioritized other work higher. If you have some spare cycles and want to take a crack at it, we wouldn't mind ;)

**Comment by ryansloan** [comment]
@ashercodeorg There are all kinds of consequences we'd have to mitigate (the facilitators have already printed marketing materials with signup URLs, etc.), and there aren't that many workshops left so we decided to just let it run its course. We may move the August workshops once we have more bandwidth (since those have no enrollments and recruitment hasn't really started).

It's fine that it uses the old messages - the K5 program hasn't changed in length or courses of focus (still focused on 1-4)

**Comment by mehalshah** [comment]
+ @Hamms who did cert stuff

**Comment by mehalshah** [comment]
Worth mentioning that we now have a generic certificate that we can append stuff to

**Comment by ashercodeorg** [comment]
Updated. PTAL.

**Comment by ashercodeorg** [comment]
CircleCI failures are known flaky tests and unrelated.

**Pull request merged**
