### PR TITLE
fix locale loading order error in embed_blocks template

### PR DESCRIPTION
**Pull request by wjordan**

### CODE REVIEW

**Comment by joshlory** [comment]
Looks fine to fix for now, but it would be cool if we could de-dupe this against `_blockly.html.haml`.  Better DRY & reduces the number of places to check for any future code changes.

**Comment by joshlory** [comment]
May be worth adding a UI test since this got regressed without any warnings from the test suite.

**Comment by wjordan** [comment]
I'll look into adding a UI test for this later, since that'll take longer to set up and this fix is needed for current MSM work. I'll merge this in as soon as I rebase / manually test again locally.

**Comment by joshlory** [comment]
Can you open a pivotal item?  I think a UI test for this feature is important or we'll continue to break it.  It's a variation of a common code path, and changes to the common code path (_blockly) are likely to break this as well without devs realizing they broke it.

**Comment by wjordan** [comment]
[#87576490](https://www.pivotaltracker.com/story/show/87576490)

**Pull request merged**
