### PR TITLE
Redirect applab docs

### PR DESCRIPTION
**Pull request by davidsbailey**
## Description

The files at code.org/applab/docs are obsolete. However, they still get 1300 page views / week, most likely due to search engine indexing. This PR makes a best-effort attempt to redirect those requests (in https://github.com/code-dot-org/code-dot-org/pull/33927/commits/9a3689baad768153d81baeb6974595408da0f23a) to the files with the same names at studio.code.org/docs/applab/ . The files in the /applab/docs1 directory did not have any page views in GA and so are not being redirected as part of this change.

## Screenshots

applab-docs-redirect

## Testing story

The flow in the screenshot shows the url format which appears in search engine results e.g. for "onEvent". The redirect also works if you omit the query param. The redirect does not work if you add a trailing slash, but we do not anticipate receiving requests in this format so I'm not doing anything to handle that case.

## Future work

We'll check cloudfront logs in a couple weeks. if traffic has died down, we'll consider removing this redirect.

## Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by breville — APPROVED** [review]
Looks like a neat fix!

**Review by dmcavoy — APPROVED** [review]

**Comment by uponthesun** [comment]
Do the old and new URLs match up for all of the files? Or is it just a large enough % that it's not worth trying to track down all of them?

**Comment by davidsbailey** [comment]
Dani had to update the studio.code.org/docs/applab pages manually to point to studio.code.org/docs/applab instead of code.org/applab/docs, and said that all of the ones she remembered updating matched exactly. It's possible there are one or two "extra" items in here, but those would all probably be blocks we don't use any more. So I think we are in the "large enough %" camp since we have not strictly tracked down every last link.

**Comment by davidsbailey** [comment]
Upon closer inspection, the top 2 hits on Google Analytics are concepts which therefore did not have corresponding pages under studio.code.org/docs/applab/: https://analytics.google.com/analytics/web/#/report/content-pages/a37745279w66217109p68074336/explorer-table.filter=~2Fapplab~2Fdocs&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=50/

Screen Shot 2020-04-01 at 10 17 08 AM

I've added specific redirects for the two concepts getting the most traffic, and I spot-checked a few of the more stale-sounding block names to make sure they had valid pages to redirect to.

Good call-out, @uponthesun !

**Pull request merged**
