### PR TITLE
removed css rules that were not being used

### PR DESCRIPTION
**Pull request by hemabatra**
The four files listed below make up the style.css file for code.org.  
-	020-bootstrap-min.css
-	030-font-awesome-min.css
-	040-page.css
-	050-theme.css

Each file was modified to remove many unused CSS rules. 
Tools used to do this were:
  - uncss (https://github.com/giakki/uncss)
 -  CSS Usage (FireFox plugin)

 uncss tool helped create smaller files for 020-bootstrap-min-css and 030-font-awesome-min.css. 

CSS Usage was used to make sure the same number of rules that were being used before any file modification matched the number of rules being used after modification.  If they did not match, I would find the rules and add them back to the appropriate file. 

I verified 22 pages. Attached is a spreadsheet of the pages I checked. 
[Pages Verified.xlsx](https://github.com/code-dot-org/code-dot-org/files/1069705/Pages.Verified.xlsx)

### CODE REVIEW

**Comment by hemabatra** [comment]
@wjordan I have completed the first pass of the changes to the files that make up style.css for code.org. 

I believe I heard there are some automated tests that can check if there are other rules missing.   Is that correct? 

I was also wondering, files 040-page.css and 050-theme.css are not minified, should I minify them?

Thanks, 
Hema

**Comment by hemabatra** [comment]
@wjordan Would it be okay with you to remove the following lines from the file theme_common_head_before?  Since these lines are no longer https://msdn.microsoft.com/en-us/library/hh801214(v=vs.85).aspx

:javascript
  var is_ie8 = false;
/[if IE 8]
  :javascript
    is_ie8 = true;

**Comment by wjordan** [comment]
@hemabatra re: the IE8 conditional comments:

- The `is_ie8` variable isn't related to the CSS changes in this PR, so if they should be touched at all, it should be done in a separate PR.
- The conditional specifically targets IE8, so it doesn't matter if the comment is ignored in IE10+. (Whether we should remove legacy IE8-support code entirely from our codebase is a separate, valid question.)
- That JS variable is still referenced in [`:learn_carousels`](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/views/learn_carousels.haml#L84-L84) view which is [used](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/learn/legacy.haml#L24-L24) on [/learn/legacy](https://code.org/learn/legacy), so it can't be removed without modifying/removing these related pages. (Whether we should remove this legacy page entirely from our codebase is a separate, valid question.)

**Comment by hemabatra** [comment]
1.  Thanks for the reminder, sometimes I have the mentality if I changed a file that could be cleaned up.  DO IT.
2.  Yes, I forget that IE 8 might still be used by people - https://www.webdesignerdepot.com/2016/01/ie8-is-back-from-the-dead/

**Comment by hemabatra** [comment]
@wjordan Thanks for testing this.  I will look into this and add back the missing rules.

**Comment by hemabatra** [comment]
glad there are UI tests to help find the rules I removed.  
The rules that I was asked to add back always were displayed as not being used. 

I have added the rule for visited links back.  I checked that if I clicked on any of the links on the last line of code.org the text did not disappear
The icons for Facebook, Twitter, Instagram, and Tumbler

**Comment by wjordan** [comment]
@hemabatra one more issue I encountered during testing: The language-selector modal dialog is broken because of some additional missing Bootstrap rules.

To repro, load https://adhoc-remove-unused-css-rules.cdn-code.org/ in a private-browser window. (Adhoc instances simulate page-loads from non-US locations which triggers a language-selection modal dialog on the homepage. For expected behavior see e.g., https://adhoc-critical-font.cdn-code.org/).

**Comment by hbbatra** [comment]
@wjordan I will connect with you in the morning.  I tried the URL https://adhoc-critical-font.cdn-code.org/ and whenever I tried to change the language for the site, nothing happened. I used the lightbox and the dropdown box at the end of the page. 

I was able to change the language for the main page on branch remove-unused-css-rules and I noticed it is only using 78 rules where it should be using 88.  I am investigating what rules are missing in this.

**Comment by hemabatra** [comment]
@wjordan I will connect with you in the morning.  I tried the URL https://adhoc-critical-font.cdn-code.org/ and whenever I tried to change the language for the site, nothing happened. I used the lightbox and the dropdown box at the end of the page. 

I was also unable to change the language on the machine https://adhoc-remove-unused-css-rules.cdn-code.org/

I was able to change the language for the main page on branch remove-unused-css-rules and I noticed it is only using 78 rules where it should be using 88.  I am investigating what rules are missing in this

**Comment by hemabatra** [comment]
@wjordan I was able to track down the CSS rules that were removed that prevented the language lightbox from appearing and verified that I could change the language from English to Spanish.

**Comment by wjordan** [comment]
OK, tested out the fixes and looks like everything's working as expected on the adhoc instance. Any other issues should be more minor and will be shaken out in the UI test runs, so I think this is ready to merge! :tada:

**Comment by hbbatra** [comment]
Thanks, Will for taking the time to test this out for me.

**Pull request merged**
