### PR TITLE
Refactor teacher dashboard nav

### PR DESCRIPTION
**Pull request by maddiedierker**
**Note: change base back to staging before merging!**

Refactoring the navbar in the new teacher dashboard based on [feedback](https://docs.google.com/document/d/1Cj3gYjkAMEHWfV3x9h-Rjxlkow39hRrBguA06XowsVI/edit?usp=sharing)!

### Before
screen shot 2019-02-18 at 8 22 00 pm

### After
When the navbar doesn't need to scroll (i.e., there is no overflow), it looks like this:
screen shot 2019-02-18 at 8 14 39 pm

When the navbar does need to scroll, it behaves like this (video is sped up a little):
navbar

### CODE REVIEW

**Review by islemaster — COMMENTED** [review]
Tests? Or maybe a story.jsx with scrolling and non-scrolling cases?

**Comment by davidsbailey** [comment]
A couple initial questions/comments:

1. at some point we should check how this looks across browsers, since scrollbar behavior is notoriously not consistent across browsers.

> based on [feedback](https://docs.google.com/document/d/1Cj3gYjkAMEHWfV3x9h-Rjxlkow39hRrBguA06XowsVI/edit?usp=sharing)!

2. Is this the item in the feedback doc you're talking about? `[Maddie] Header styling on “Text Responses” is a little wonky`

3. are parts of this really refactoring (no behavior change), or is this more of a rewrite? I'm not seeing a lot of similarity between old and new code, and I don't see any refactoring steps in individual commits.

**Comment by maddiedierker** [comment]
@islemaster good call, i'll add a storybook entry for this component

@davidsbailey to answer your questions:
1. i haven't done much cross-browser testing, so i'll make sure to do so
2. i organized all of the navbar feedback i was working off of to make it clearer: [feedback](https://docs.google.com/document/d/1Cj3gYjkAMEHWfV3x9h-Rjxlkow39hRrBguA06XowsVI/edit#heading=h.w1a2kfazfaf)
3. i called it a "refactor" because the behavior should not be changing except for 2 nice-to-haves i added: a) display left/right chevrons on user scroll, not just when the chevrons are clicked, and b) only display chevrons/scrolling if the tabs are long enough to necessitate it. this component is small enough that that meant changing a lot, so you can call it a refactor or a rewrite, whichever makes more sense to you

**Review by davidsbailey — APPROVED** [review]

**Comment by maddiedierker** [comment]
@davidsbailey i wanted to follow up on cross-browser testing. everything is looking good (somewhat to my surprise) with the scrollbars, but the `sticky` chevrons were an issue in Safari (Safari uses `position: -webkit-sticky` instead of `position: sticky`), so i added conditional styling [here](https://github.com/code-dot-org/code-dot-org/blob/714a1087852296e5bbc13b9a6ce016b5ab4d7440/apps/src/templates/teacherDashboard/TeacherDashboardNavigation.jsx#L126-L128). thanks for the heads up!

**Pull request merged**
