### PR TITLE
Remove storiesOf support in Storybook

### PR DESCRIPTION
**Pull request by bencodeorg**
After finishing the last of the Storybook migration (!), we no longer need to support the `storiesOf` Storybook format. Simplifying our Storybook testing to reflect that.

## Testing story

I ran `yarn test:storybook` before and after this change, and saw the same number of tests completed. There are also no mentions of `storiesOf` in our repo any more.

### CODE REVIEW

**Comment by bencodeorg** [comment]
@hannahbergam tagged you because you've done a lot of work here, and I think you did the last story migration yeah?

**Review by thomasoniii — APPROVED** [review]
lgtm 🚀

**Review by hannahbergam — APPROVED** [review]
YAY Thanks Ben!!

**Review by fisher-alice — APPROVED** [review]
Woo hoo!

**Review by levadadenys — APPROVED** [review]
😍

**Pull request merged**
