### PR TITLE
Avoid webpack chunk 404s in development environment

### PR DESCRIPTION
**Pull request by bencodeorg**
In our Rails code, we sometimes hard code loading JS files generated by our optimized Webpack build. This change excludes these script tags when in a development environment, where we are turning off the `splitChunks` optimization that produces these custom named files.

## Testing story

I tested manually that I saw 404s for affected files in each of the locations, they disappeared after code changes, and that (at least at a surface level) these pages appeared to be functioning normally:
- code.org homepage
- hourofcode.com homepage
- A level that hits the esoteric code changed here in `match_answer_as_embedded_blockly` in `levels_helper` ([this level on levelbuilder ](match_answer_as_embedded_blockly) is an example)
- p5 labs (dance, spritelab)
- The parent-facing letter generated in the teacher dashboard
- A music lab allthethings level

### CODE REVIEW

**Review by jmkulwik — APPROVED** [review]
Nice work finding all of these

**Review by snickell — APPROVED** [review]
The exact implications of `CDO.optimize_webpack_assets` being set is pretty far beyond my knowledge atm, so I'll have to defer to @bencodeorg whether more review is needed or if we're good to go with this. From what I see, with the limits of what I don't know, looks good to me.

I do think if there's not a 1:1 match between DEV=1 yarn builds and CDO.optimize_webpack_assets, its probably a relatively obscure case, and we can address it when it comes up?

My one idea here is that maybe we don't even have to index off a flag, what if we actually checked whether the file exists in the haml (using a helper of course)? Sketch of the idea here: https://github.com/code-dot-org/code-dot-org/pull/55707#discussion_r1465711977 . But that might not be a great idea, as it might hide errors that would otherwise manifest as a well-deserved 404 (e.g. you didn't have a built built at all, but were running in prod mode, the 404 would be swallowed). My instinct is to probably merge this unless the idea triggers a rethink on @bencodeorg 's part: I think your instincts are gonna be best here.

**Comment by bencodeorg** [comment]
Re: the exact implications of `CDO.optimize_webpack_assets` as far as I can tell are just these (and the new conditions added in this PR):

https://github.com/code-dot-org/code-dot-org/blob/9caa136951443aff115d1aa41e41d1035db07df2/lib/rake/build.rake#L28

https://github.com/code-dot-org/code-dot-org/blob/9caa136951443aff115d1aa41e41d1035db07df2/lib/cdo/asset_helper.rb#L37

I'm feeling like we roll with this and get it out to folks and see what happens!

**Comment by bencodeorg** [comment]
Added a [commit](https://github.com/code-dot-org/code-dot-org/pull/55925/commits/d8ade3e8cab8ba2cefacb270a1bec46a48270b66) not to mess with script import order in `application.html.haml` b/c we do some initialization of `window.dashboard` in `application.js`. Wanted to make sure we didn't cause any issues by loading `code-studio-common.js` before we do that:

https://github.com/code-dot-org/code-dot-org/blob/1c0817d93ad2b4dee2ae2d2991ea0f50f328b3d1/dashboard/app/assets/javascripts/application.js.erb#L34-L39

**Comment by snickell** [comment]
I think we've investigated as well as we can, this looks good, and I'd say lets merge this one into the other, and then merge them both into staging.

**Pull request merged**
