### PR TITLE
GET in files api now sets Content-Disposition

### PR DESCRIPTION
**Pull request by cpirich**
* The files API serves content from a user's project under the path `/v3/files/<project id>/<filename>` - since the intended use case is download via Ajax, we need to force browsers that hit this URL directly to also treat this as a download and not authentic website content from our domain

### CODE REVIEW

**Comment by cpirich** [comment]
@ewjordan @wjordan @ashercodeorg @jeremydstone @islemaster @Bjvanminnen

**Comment by Bjvanminnen** [comment]
This seems okay to me

**Comment by islemaster** [comment]
Any chance this will mess with viewing projects from schools that have to whitelist our domain?

**Comment by cpirich** [comment]
@islemaster I can't think of how that could be a problem, but we'll have to keep an eye out for things like that.

**Pull request merged**
