### PR TITLE
Pass list of programming environments to FindProgrammingExpressionDialog

### PR DESCRIPTION
**Pull request by dmcavoy**
Replaces hardcoded list of programming environments with the list from the database. 

## Links

- jira ticket: [PLAT-881](https://codedotorg.atlassian.net/browse/PLAT-881)

## Testing story

- Updated unit tests and storybook entry with new prop

## PR Checklist:

- [x] Tests provide adequate coverage
- [x] Privacy and Security impacts have been assessed
- [x] Code is well-commented
- [x] New features are translatable or updates will not break translations
- [x] Relevant documentation has been added or updated
- [x] User impact is well-understood and desirable
- [x] Pull Request is labeled appropriately
- [x] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by Hamms — APPROVED** [review]
oh, rad, thanks! I didn't realize these were already available in the environment, although I should have figured.

As an aside; this much currying is a clear sign that we are at - or more likely past - the point where we should implement redux. Is that already being tracked? If not, it should probably be right at the top of the list for our post-April-deadline work

**Comment by dmcavoy** [comment]
> oh, rad, thanks! I didn't realize these were already available in the environment, although I should have figured.
> 
> As an aside; this much currying is a clear sign that we are at - or more likely past - the point where we should implement redux. Is that already being tracked? If not, it should probably be right at the top of the list for our post-April-deadline work

I have not tracked this. I think I remember @cforkish mentioning that the way we were using redux to just store information like this was not ideal and just passing it down was fine. Charlie do you want to weigh in here?

**Comment by Hamms** [comment]
I disagree with that claim, but I'm open to having a conversation to address whatever concerns there may be.

**Comment by davidsbailey** [comment]
I am very interested in this topic! 🙂  🍿

**Comment by cforkish** [comment]
nope! i happily defer to y'all. :)

**Comment by dmcavoy** [comment]
Cool I'll update

**Pull request merged**
