### PR TITLE
upgrade to webpack 4 again, without breaking weblab

### PR DESCRIPTION
**Pull request by davidsbailey**
This reverts commit 38e6228d2d4a28a7f9132c065395ca97c6eb82fa from https://github.com/code-dot-org/code-dot-org/pull/27756, re-applying the webpack 4 upgrade originally done in https://github.com/code-dot-org/code-dot-org/pull/27665 . It also fixes weblab by including the webpack-runtime inside the webpack iframe, and adds a UI test to make sure that weblab's iframe contents is actually loading.

### CODE REVIEW

**Comment by islemaster** [comment]
Just thinking of other iframe-sensitive places in our application that might be missing test coverage: Have we checked the Game Lab animation tab?

**Comment by islemaster** [comment]
Yep, animation tab looks good on the adhoc.  I wonder what's different about scripts loaded in Web Lab's iframe from Game Lab's?

**Review by islemaster — APPROVED** [review]
:rocket:

**Comment by davidsbailey** [comment]
Good thing to check! Here's my best explanation:

The Animation tab in Gamelab has "/blockly/js/piskel/index.html" as its iframe src, which does load js files like /blockly/js/piskel/js/piskel-packaged-2018-04-19-02-25.js . This is not a webpack entry point of ours, rather it is a third-party file that we copy into /blockly/js using our Gruntfile, so it doesn't need our webpack-runtime.js in order to load.

Weblab loads "/weblab/host" as its iframe src. This points to a rails partial (modified in this PR) which renders an actual webpack entry point of ours. So, webpack-runtime.js is needed inside the iframe, because we are actually loading an entry point of ours inside the iframe.

**Comment by joshlory** [comment]
Looks like this may have broken `yarn storybook`:

```
=> Loading custom .babelrc
=> Loading custom addons config.
=> Loading custom webpack config (extending mode).
/Users/joshlory/Work/2k14/code-dot-org/apps/node_modules/webpack/lib/ProvidePlugin.js:19
                compiler.hooks.compilation.tap(
                               ^

TypeError: Cannot read property 'compilation' of undefined
    at ProvidePlugin.apply (/Users/joshlory/Work/2k14/code-dot-org/apps/node_modules/webpack/lib/ProvidePlugin.js:19:18)
    at Compiler.apply (/Users/joshlory/Work/2k14/code-dot-org/apps/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/joshlory/Work/2k14/code-dot-org/apps/node_modules/@storybook/react/node_modules/webpack/lib/webpack.js:33:19)
```

**Comment by davidsbailey** [comment]
I've confirmed that this was caused by the webpack upgrade. after upgrading `@storybook/react` and `@babel/core`, there is still a problem with .ejs parsing of the storybook entry point. I will investigate further. there may also be a shortcut to just stub out the problematic parts of the webpack config instead.

**Pull request merged**
