### PR TITLE
Fix verbose Radium warnings filling DroneCI logs

### PR DESCRIPTION
**Pull request by snickell**
DroneCI logs are dominated by:
```
WARN: 'Radium: property "border" in style object', Object{borderWidth: 1, borderStyle: 'solid', minWidth: 100, marginTop: 0, marginBottom: 0, marginLeft: 0, marginRight: 0, :hover: Object{boxShadow: 'none', backgroundColor: '#D4D5D7'}, backgroundColor: '#FFFFFF', border: '2px solid #292F36', color: '#292F36'}, ': do not mix longhand and shorthand properties in the same style object. Check the render method of BaseButton.', 'See https://github.com/FormidableLabs/radium/issues/95 for more information.'
```

Reducing log spam by breaking a few shorthand CSS properties (e.g. border) into longhand (borderWidth, borderStyle, borderColor).

### CODE REVIEW

**Comment by snickell** [comment]
Another example from Radium:
```
WARN: 'Radium: property "margin" in style object', Object{fontSize: 'large', height: 45, paddingTop: 12.5, paddingBottom: 12.5, paddingLeft: 10, paddingRight: 10, margin: 0, marginRight: 8, verticalAlign: 'top'}, ': do not mix longhand and shorthand properties in the same style object. Check the render method of PendingButton.', 'See https://github.com/FormidableLabs/radium/issues/95 for more information.'
```

**Comment by snickell** [comment]
Another common warning cluttering the build logs:
```
Handlebars: Access has been denied to resolve the property "statements" because it is not an "own property" of its parent.
--
1937 | You can add a runtime option to disable the check or this warning:
1938 | See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
```

Looks like updating the version of istanbul used for checking code coverage might fix this?

**Comment by snickell** [comment]
Lots of `AMPLITUDE ANALYTICS EVENT` log messages. These seem like they /might/ be of general interest in debugging tests? But probably not? In either case, they look like a good candidate to set to console.debug level logging, not info.
```
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
LOG: '[AMPLITUDE ANALYTICS EVENT]: Teacher Login. Payload: {"payload":{"user id":42}}'
```

**Comment by snickell** [comment]
Splitting 8d8e47194941de2e798307093772dc8c419fd0f6 and 6f8ab100ea0090e0e5ee6520e7fe95eef2464850 into a separate PR.

**Review by dmcavoy — APPROVED** [review]

**Review by mgc1194 — APPROVED** [review]
✨

**Pull request merged**
