### PR TITLE
Wait for loading spinner to complete when loading page

### PR DESCRIPTION
**Pull request by bcjordan**

### CODE REVIEW

**Comment by bcjordan** [comment]
N.B. have not tested this fully yet, have not confirmed whether it actually detects when loading is happening

**Comment by laurelfan** [comment]
hm, do most of the tests "wait for" something?

**Comment by bcjordan** [comment]
Most currently do, we just keep occasionally discovering new ones with long-load edge cases. Maybe it'd make sense to instead add a step "Wait for the spinner to hide" and add that to the ones that need it

**Comment by laurelfan** [comment]
sounds like a good idea

**Pull request closed without merging**
