### PR TITLE
add video-js.css back to rails asset path

### PR DESCRIPTION
**Pull request by davidsbailey**
### problem
when loading https://studio.code.org/s/csp1/stage/1/puzzle/2 , there is a 404 fetching https://studio.code.org/assets/video-js/video-js.css

### solution
The general idea is that this asset was being provided a different way and only kept working because we don't regularly clean up old assets. I verified this by loading http://localhost-studio.code.org:3000/s/csp1/stage/1/puzzle/2 and seeing whether http://localhost-studio.code.org:3000/assets/video-js/video-js.css loads on my dev machine:
* initially, the css file loads properly
* after doing `rake assets:clean` (which removes only "old" assets), the css file no longer loads
* after writing this PR and then running `rake assets:precompile`, the css file loads again

### testing
This PR doesn't offer any tests that the asset files are being loaded properly. I'm open to suggestions. One thought is that each major feature should at least be doing enough UI or eyes testing to verify that the css is loading properly.

### CODE REVIEW

**Comment by davidsbailey** [comment]
FYI @pcardune  @Bjvanminnen @islemaster in case you have opinions on this as well

**Comment by davidsbailey** [comment]
Also, any thoughts on whether to make `rake assets:clean` part of our build process on any of development, staging, test, or production? It takes 20-30 seconds to run, and seems to keep all assets from within the past few weeks, suggesting that it won't immediately break clients in production with stale code pointing to older assets.

**Comment by islemaster** [comment]
:+1: to running `assets:clean` more regularly so this gets caught.

**Comment by wjordan** [comment]
Have we tracked down when this changed, and why things broke as a result? Where is this file being generated from now, in the current pipeline?

I'm all for fixing this if it's broken on the live site, but I'd like to make sure we're fixing something we understand entirely, so we know how to protect against similar breaking changes in the future.

**Comment by davidsbailey** [comment]
I haven't tracked down why this changed. The most recent file with a similar name on production-deamon is from a year ago:
```
ubuntu@production-daemon:~/production/dashboard/public/assets$ find . -name "video-js*.css" | xargs ls -l
-rw-rw-r-- 1 ubuntu ubuntu 11691 Jan 12  2016 ./assets/video-js/video-js-f7e0c74e31bc38df1c27aeeaaeea917f.css
-rw-rw-r-- 1 ubuntu ubuntu 11519 Jan 12  2016 ./assets/video-js/video-js.min-d399f9ea5b00073b33e0bd9d72dbd897.css
-rw-rw-r-- 1 ubuntu ubuntu 11835 Sep 20  2014 ./video-js-19237f20e3711a78aad2ab70b0193dd3.css
-rw-rw-r-- 1 ubuntu ubuntu 15737 Jul 31  2015 ./video-js-827bbc04396dcb22c19bc42e5ce83b1e.css
-rw-rw-r-- 1 ubuntu ubuntu 11835 Sep 20  2014 ./video-js-953be20fd98b86c7d036dc60c15264f5.css
-rw-rw-r-- 1 ubuntu ubuntu 11835 Oct 23  2015 ./video-js-e693d5167891bc6388be81c132ae15e4.css
```
Levelbuilder looks the same. I didn't look closely at staging or test before cleaning them.

This change from July (!) seems like the most recent suspect. it touches the file that points to video-js.css as well as to the assets:precompile path in application.rb: https://github.com/code-dot-org/code-dot-org/pull/9340 "Move code-studio into apps"

Because the page doesn't look broken, it's possible that this has been 404ing for a long time.

**Comment by davidsbailey** [comment]
> Where is this file being generated from now, in the current pipeline?

This is being generated from the Gruntfile, here: https://github.com/code-dot-org/code-dot-org/blob/staging/apps/Gruntfile.js#L143-L146

**Comment by davidsbailey** [comment]
it appears to me that [this line]( https://github.com/code-dot-org/code-dot-org/pull/9340/files#diff-95a3ff350d1c2f456a1dc532e3187a43L25) of https://github.com/code-dot-org/code-dot-org/pull/9340 was generating `/assets/video-js/video-js.css`, and that PR erroneously depended on the old copy of that asset which appears to have stopped being generated at that time.

> protect against similar breaking changes in the future

Developers should run `rake assets:clean` before `rake assets:precompile` to catch problems like this. Because this PR does `rake assets:clean` on staging and test, any UI or eyes test covering a feature which depends on an asset like this would presumably break, even if the developer forgot to clean their assets first.

Checking for missing files isn't really part of our test plan -- rather, a basic UI or eyes test covering each major feature is the way that we would catch problems like this in the future.

@wjordan I think this addresses all of your questions and concerns. Please let me know if you have any additional feedback.

**Pull request merged**
