### PR TITLE
show thumbnail url input on weblab level editor page

### PR DESCRIPTION
**Pull request by davidsbailey**

### CODE REVIEW

**Comment by islemaster** [comment]
This PR just puts the field in the level editor.  Did the associated work to actually use the thumbnail already happen, or is it not needed because this property was already implemented for other level types?

**Comment by islemaster** [comment]
Answered my own question: Override thumbnail URLs were added in https://github.com/code-dot-org/code-dot-org/pull/22965!

**Review by islemaster — APPROVED** [review]
:tada: :framed_picture:

**Review by maddiedierker — APPROVED** [review]
thank you for adding this so quickly!

**Pull request merged**
