### PR TITLE
Redirect vpl summer pilot to unit overview page at end of lesson

### PR DESCRIPTION
**Pull request by dmcavoy**
Jess asked for vpl-csd-summer-pilot to redirect to the unit overview page at the end of the lessons. 

Screen Shot 2022-06-09 at 8 24 57 PM

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
seems ok to meet launch deadline.

**Comment by davidsbailey** [comment]
@dmcavoy does this need to ship today? since staging is still closed and it is now past the end of your work day, I would be happy to keep an eye on staging for you and merge this once it opens.

**Comment by dmcavoy** [comment]
@davidsbailey I told Jess that it likely would not make it today. It would be great if it could. I'll ask James if I can merge it in

**Comment by dmcavoy** [comment]
I'm going to hold it to not delay the deploy. It can go out Monday

**Pull request merged**
