### PR TITLE
Update with_google_authentication_option trait

### PR DESCRIPTION
**Pull request by nkiruka**
# Description
Change authentication_id from being a static id to a unique id in the 'with_google_authentication_option' trait.  This change ensures that each 'test user' is assigned a unique authentication id.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by joshlory** [comment]
Can you share a before/after of code in the console that hits this issue?

**Comment by nkiruka** [comment]
@joshlory I can only reproduce this error only when 'enforce_google_sso' method is defined.

```
ERROR["test_does_set_admin_to_false_when_it_is_not_a_codeorg_account", "UserTest", 530.1557489999686]
 test_does_set_admin_to_false_when_it_is_not_a_codeorg_account#UserTest (530.16s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:4165:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_does_set_admin_to_true_when_google_oauth_codeorg_account", "UserTest", 530.5992609999957]
 test_does_set_admin_to_true_when_google_oauth_codeorg_account#UserTest (530.60s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:4145:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_find_for_authentication_finds_migrated_Google_email_user", "UserTest", 533.7600649999804]
 test_find_for_authentication_finds_migrated_Google_email_user#UserTest (533.76s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:792:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_update_primary_contact_info_adds_new_email_option_for_student_if_no_matches_exist", "UserTest", 557.0873439999996]
 test_update_primary_contact_info_adds_new_email_option_for_student_if_no_matches_exist#UserTest (557.09s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:1922:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_update_primary_contact_info_adds_new_email_option_for_teacher_if_no_matches_exist", "UserTest", 557.2229809999699]
 test_update_primary_contact_info_adds_new_email_option_for_teacher_if_no_matches_exist#UserTest (557.22s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:1863:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_update_primary_contact_info_fails_safely_if_the_new_email_is_already_taken_for_oauth_user", "UserTest", 557.6719529999536]
 test_update_primary_contact_info_fails_safely_if_the_new_email_is_already_taken_for_oauth_user#UserTest (557.67s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:2003:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

DEPRECATED: Use assert_nil if expecting nil from test/models/user_test.rb:2015. This will fail in Minitest 6.                                                           ] 27% Time: 00:09:17,  ETA: 00:24:09
ERROR["test_update_primary_contact_info_oauth_option_replaces_any_existing_email_options_for_student", "UserTest", 558.3011439999682]
 test_update_primary_contact_info_oauth_option_replaces_any_existing_email_options_for_student#UserTest (558.30s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:1950:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_update_primary_contact_info_oauth_option_replaces_any_existing_email_options_for_teacher", "UserTest", 558.436652000004]
 test_update_primary_contact_info_oauth_option_replaces_any_existing_email_options_for_teacher#UserTest (558.44s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:1889:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_upgrade_to_personal_login_is_false_for_migrated_student_if_update_fails", "UserTest", 560.5653629999724]
 test_upgrade_to_personal_login_is_false_for_migrated_student_if_update_fails#UserTest (560.57s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:2067:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_upgrade_to_personal_login_is_false_for_migrated_student_if_update_primary_contact_info_fails", "UserTest", 560.6770200000028]
 test_upgrade_to_personal_login_is_false_for_migrated_student_if_update_primary_contact_info_fails#UserTest (560.68s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:2052:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_upgrade_to_personal_login_is_true_for_successfully_updated_migrated_student", "UserTest", 561.2511079999967]
 test_upgrade_to_personal_login_is_true_for_successfully_updated_migrated_student#UserTest (561.25s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:2082:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_upgrade_to_teacher_is_true_if_matching_authentication_option_is_found", "UserTest", 561.6209519999684]
 test_upgrade_to_teacher_is_true_if_matching_authentication_option_is_found#UserTest (561.62s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:2161:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

ERROR["test_upgrade_to_teacher_is_true_if_new_authentication_option_is_created", "UserTest", 561.740822999971]
 test_upgrade_to_teacher_is_true_if_new_authentication_option_is_created#UserTest (561.74s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/models/user_test.rb:2144:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'

```

**Comment by nkiruka** [comment]
@joshlory Should this change still be extracted from https://github.com/code-dot-org/code-dot-org/pull/31626

**Comment by nkiruka** [comment]
Error also occure in admin_search_controller_test
```
ERROR["test_admin_calling_get_find_students_should_receive_success", "AdminSearchControllerTest", 106.93024699995294]
 test_admin_calling_get_find_students_should_receive_success#AdminSearchControllerTest (106.93s)
ActiveRecord::RecordInvalid:         ActiveRecord::RecordInvalid: Validation failed: Credential type has already been taken
            test/factories/factories.rb:355:in `block (4 levels) in <top (required)>'
            test/test_helper.rb:464:in `block in test_user_gets_response_for'
            test/testing/setup_all_and_teardown_all.rb:22:in `run'
```

**Comment by joshlory** [comment]
I was able to repro by running `FactoryGirl::create(:admin, :with_google_authentication_option)` twice from Rails Console:

image

After applying your code fix, I'm able to run it multiple times with no issue. So I think this fix makes sense as a standalone PR!

**Comment by nkiruka** [comment]
@joshlory Sounds good!  Is there any other change for this PR?

**Review by joshlory — APPROVED** [review]
Nope, looks good to merge! 👍

**Pull request merged**
