### PR TITLE
Update webpack 2 -> 3

### PR DESCRIPTION
**Pull request by joshlory**
Follow up to PR https://github.com/code-dot-org/code-dot-org/pull/19706.  This should be a lot less painful than the webpack 1 -> 2 upgrade!

From the release announcement:

> Migrating from webpack 2 to 3, should involve no effort beyond running the upgrade commands in your terminal. We marked this as a Major change because of internal breaking changes that could affect some plugins.

https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

### CODE REVIEW

**Comment by islemaster** [comment]
Webpack 2, we hardly knew you.

:eyes: Looking...

**Comment by islemaster** [comment]
Pulled and tried locally, seems good so far.  Have you measured any perf or bundle size changes with this upgrade?

I say we go for it :grin:

**Comment by islemaster** [comment]
Oh, I have local yarn.lock changes on this upgrade too (after `rm -rf node_modules && yarn cache clean && yarn`):

**Comment by joshlory** [comment]
Doesn't `yarn` generate yarn.lock depending partially on the state of the node_modules folder?  I'm not sure it's correct to delete node_modules then regenerate yarn.lock.

Running `yarn` on this branch without deleting node_modules doesn't give me any diff.  I'm on yarn version 0.23.2.

**Comment by islemaster** [comment]
Pulling this branch and just running `yarn` I no longer see changes in the lockfile, or after running `rm -rf node_modules && yarn cache clean && yarn`.  Looks good.

**Pull request merged**
