### PR TITLE
Add support for login_required parameter for script_level urls

### PR DESCRIPTION
**Pull request by jamescodeorg**
Add support for a login_required parameter to script_level urls.  This link will be used in the soon-to-be-implemented [send lesson dialog](https://docs.google.com/document/d/1k9U-ulkQR2bNZ_BBzRi4PCyjwUAXyn4QzEzdUI4tWbE/edit#bookmark=id.ygy08ihxyzob).

For example, http://studio.code.org/s/coursee-2020/stage/3/puzzle/6?login_required=true will redirect to the login page if the user is not signed in.

Note: The login_required parameter is preserved post-login and as the student continues to other puzzles. If this becomes a problem, we will address this in a separate PR.

## Links

- [spec](https://docs.google.com/document/d/1k9U-ulkQR2bNZ_BBzRi4PCyjwUAXyn4QzEzdUI4tWbE/edit)
- [jira](https://codedotorg.atlassian.net/browse/LP-1590)

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by jmkulwik — APPROVED** [review]
Looks good! One question: You mentioned loginRequired persists on the URL after login. Will this cause any problems if the user goes to a page where login shouldn't be required and then sends the URL to another user?

**Comment by jamescodeorg** [comment]
Good question!  The only place where we will check for this parameter is when loading a script_level page (/s/xxx/stage/yyy/puzzle/zzz).  I think it's ok to require login on all of those pages, right?

**Comment by jmkulwik** [comment]
Oops meant to post this earlier but forgot to hit the "comment" button: Could you add a bit more detail regarding the "why" for this feature to the PR description?

**Comment by jmkulwik** [comment]
> Good question! The only place where we will check for this parameter is when loading a script_level page (/s/xxx/stage/yyy/puzzle/zzz). I think it's ok to require login on all of those pages, right?

I _think_ that's ok, but might be a better question for Amanda/product. The scenario that might be concerning are the HOC pages i.e. https://studio.code.org/s/dance/stage/1/puzzle/1. Maybe a better question is "How does someone get 'login_required' added to the URL in the first place?"

**Comment by jamescodeorg** [comment]
These URLs will come from the share link dialog from the unit overview page.  I reached out to Amanda and I think we're ok with leaving this behavior for now and fixing it later if it becomes a problem.  (I will probably just take a peek and see what it would take to remove the parameter anyway but it won't be part of this PR.)

**Comment by jmkulwik** [comment]
Sounds good! Thanks for checking on that!

**Pull request merged**
