### PR TITLE
Skip URL in this flaky eyes test temporarily

### PR DESCRIPTION
**Pull request by fisher-alice**
This PR skips the `mobile_portrait.feature` eyes test which has become very flaky. 
There is extensive discussion about the test in [this Slack thread](https://codedotorg.slack.com/archives/C03DBDN67B7/p1684949426239739).
This is the [jira ticket](https://codedotorg.atlassian.net/browse/SL-878) to investigate and fix this test.

@Hamms suggested removing only one of the two URLs tested in this eyes test. However, when I ran the artist level (URL that was working on test) 3 times, it failed 2 out of 3 locally so that I’m afraid even this URL is flaky. I watched the videos, and for some reason the ‘Rotate your device…’ image seems to skip around and looks like it’s playing ‘hide and seek’. 

So after discussing with @Hamms offline, we decided it's best to skip this test entirely for now.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by Hamms — COMMENTED** [review]
Looks like this test is checking two urls; is it flaky on both urls or just one? If it's possible to skip only a part of this test as a temporary workaround, I'd definitely prefer that

**Comment by fisher-alice** [comment]
> Looks like this test is checking two urls; is it flaky on both urls or just one? If it's possible to skip only a part of this test as a temporary workaround, I'd definitely prefer that

Thanks @Hamms! I removed only one of the URLs because the 'artist' url was passing. However, when I ran it locally, this version failed. When I examined the results in SauceLabs, I saw this:
Screen Shot 2023-05-25 at 4 26 35 PM

I tried the original version of the test with the 2 URLs and got the same error as well. So I feel uneasy with this update without being able to test locally with success.

**Comment by fisher-alice** [comment]
> > Looks like this test is checking two urls; is it flaky on both urls or just one? If it's possible to skip only a part of this test as a temporary workaround, I'd definitely prefer that
> 
> Thanks @Hamms! I removed only one of the URLs because the 'artist' url was passing. However, when I ran it locally, this version failed. When I examined the results in SauceLabs, I saw this: Screen Shot 2023-05-25 at 4 26 35 PM
> 
> I tried the original version of the test with the 2 URLs and got the same error as well. So I feel uneasy with this update without being able to test locally with success.

I had to add the `applitools_eyes_api_key` to `local.yml` to run the eyes test locally. Thanks @Hamms !

**Review by molly-moen — APPROVED** [review]

**Review by Hamms — APPROVED** [review]
LGTM! Thanks for trying out a few different approaches with me

**Pull request merged**
