### PR TITLE
replace crypto-js with browserify-crypto as crypto-js is no longer maintained

### PR DESCRIPTION
**Pull request by stephenliang**
Previously, crypto-js was used solely for the md5 hashing function. Since node.js has a native crypto library, we can utilize the native md5 hasher. For browsers, a polyfill `browserify-crypto` can be used which is actively being maintained.

fixes dependabot moderate [Dependabot #434](https://github.com/code-dot-org/code-dot-org/security/dependabot/434) and critical  [Dependabot #486](https://github.com/code-dot-org/code-dot-org/security/dependabot/486)

## Links

1. [crypto-js discontinued announcement](https://github.com/brix/crypto-js)
2. [crypto-browserify statement of active project status](https://github.com/browserify/crypto-browserify/issues/229)
3. [Dependabot #486](https://github.com/code-dot-org/code-dot-org/security/dependabot/486)
4. [Dependabot #434](https://github.com/code-dot-org/code-dot-org/security/dependabot/434)

## Testing story

I ran rake test and the UI tests. The following tests were run to ensure that the native md5 hasher is consistent with crypto-js:

```
apps/test/unit/templates/instructions/InlineAudioTest.js
apps/test/unit/templates/curriculumCatalog/curriculumCatalogExpandedCardTest.jsx
```

## Follow-up work

No follow up necessary.

## Privacy

This does not change any user models or interact with privacy.

## Security

This addresses the discontinued crypto-js library by switching to an actively maintained and more mainline browserify library.

## PR Checklist:

- [x] Tests provide adequate coverage
- [x] Privacy and Security impacts have been assessed
- [x] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [x] User impact is well-understood and desirable
- [x] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by wilkie** [comment]
We're replacing a deprecated library with an older unmaintained library, that feels odd but I guess that's ok.

It would be nice, if we are going to the trouble, to just have a library with an md5 implementation instead of seemingly including an entire cryptography package for the one simple hashing function. Is there one?

**Comment by wilkie** [comment]
I say unmaintained since it was pushed to npm 6 years ago and the links to the repo and homepage are broken: https://www.npmjs.com/package/crypto-browserify when I actually visit the place the repo actually is now, which is https://github.com/browserify/crypto-browserify it is still 6 years since the last push. if anything, this library is potentially _worse_ than the one we are replacing on that basis... so I'm asking if there is a more maintained, smaller package.

**Comment by stephenliang** [comment]
@wilkie browserify-crypto isn't unmaintained, however it is seemingly unmaintained by the lack of activity. This is seen from the statement of maintenance from browserify [[1]](https://github.com/browserify/crypto-browserify/issues/229)  and [[2]](https://github.com/browserify/crypto-browserify/issues/223)

For a crypto library, it's a good thing to have a lack of activity since the algorithms (such as md5) haven't changed and won't be changing and you want to have a higher standard of scrutiny. 

Regarding importing a cryptography library, it is a polyfill of the node.js Crypto library which is native built on Node.js. Since we'd do tree shaking via webpack, the rest of the algorithms which are unused will be removed out from the bundle and only md5 will make it in the end. 

Let me know if you have strong concerns about the library though, although my preference is on browserify's suite of libraries due the cross-compatability with native Node.js' core libraries, I'd be happy to take a look at alternatives if necessary.

**Comment by stephenliang** [comment]
One more thing: [crypto-js](https://github.com/brix/crypto-js) does explicitly state that we should migrate toward the node.js native crypto library:

> Active development of CryptoJS has been discontinued. This library is no longer maintained.
> 
> Nowadays, NodeJS and modern browsers have a native Crypto module. The latest version of CryptoJS already uses the > native Crypto module for random number generation, since Math.random() is not crypto-safe. Further development of > CryptoJS would result in it only being a wrapper of native Crypto. Therefore, development and maintenance has been > discontinued, it is time to go for the native crypto module.

**Review by daynew — APPROVED** [review]
The maintainer seems to be active given that they recently responded to questions.

**Pull request merged**
