### PR TITLE
add recently-added required prop to new storybook entries

### PR DESCRIPTION
**Pull request by Hamms**

### CODE REVIEW

**Comment by aoby** [comment]
Thanks for fixing!

**Comment by Bjvanminnen** [comment]
Was this breaking something? This prop wasn't recently added, but is a year and a day old https://github.com/code-dot-org/code-dot-org/commit/c524cead075fb7c40a619496d995ae5d1b49f399

**Comment by aoby** [comment]
Good point, @Bjvanminnen. This was an attempt to fix the broken staging build. I didn't look into the details. @Hamms is this the right prop?

**Comment by Hamms** [comment]
Oh weird, I misread commit ebccd06c9c81133af58b24146ac783782c02774e. This is indeed the right prop, I just failed to add it when I first added the new entries. Do we perhaps not do storybook validation on circle builds?

**Comment by Bjvanminnen** [comment]
https://github.com/code-dot-org/code-dot-org/blob/staging/apps/test-low-memory.sh#L10 we should be

**Pull request merged**
