### PR TITLE
Change from using LIKE to using REGEXP.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This should fix the weighted counts. Confirmed by running on frontend_queue_processor for dates 2015-12-04 through 2015-12-09.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
@Hamms

**Comment by Hamms** [comment]
presumably this PR should also revert the temporary HAML change Dave implemented last night

**Comment by Hamms** [comment]
could you document somewhere (in a comment by the change?) the reasons for the change slash a brief explanation of why it happened and why this change fixes it?

**Comment by ashercodeorg** [comment]
The thought is to not revert the HAML, confirm the Properties table is populated correctly on production, then revert the HAML.

Though Phil may have a different process in mind.

**Comment by philbogle** [comment]
LGTM

**Comment by ashercodeorg** [comment]
In a LIKE clause, the underscore is a reserved character representing a wildcard. For some reason, though escaping it with the backslash should do the trick (indeed, did on local and on staging), we are seeing evidence of the escaping not working on production.

Switching to a REGEXP (where the underscore is not a reserved character) seems to resolve the problem.

**Comment by Hamms** [comment]
Cool. This LGTM; where did we land on updating the HAML? Do we have the updated number, so we can plug in a new hardcoded one in this PR?

**Pull request merged**
