### PR TITLE
Nov 11 feedback

### PR DESCRIPTION
**Pull request by amy-b**
## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by mikeharv — APPROVED** [review]

**Comment by dancodedotorg** [comment]
Hmm... it might be worth comparing this to the updates Angelina made here before finalizing this - https://github.com/code-dot-org/code-dot-org/pull/49079. 

There might be something wrong with my instructions - there shouldn't be multiple commits in the PR, and I see one was from me 3 days ago (which means it wouldn't have picked up Angelina's changes). In theory, each PR like this should have just 1 commit.

**Comment by mikeharv** [comment]
@dancodedotorg Angelina's changes were already merged so there's no worry there.

**Comment by amy-b** [comment]
Oooh, this is fun.

**Comment by elf-code** [comment]
I'm clearing out the i18n review queue, I'm assuming this PR isn't going to be merged so closing it. Feel free to open if it's still active.

**Pull request closed without merging**
