### PR TITLE
Tech debt: add new relic filtering to pegasus

### PR DESCRIPTION
**Pull request by caleybrock**
follow up to: https://github.com/code-dot-org/code-dot-org/pull/14612

### CODE REVIEW

**Comment by joshlory** [comment]
Are there other Pegasus sites that need this added as well?  Or do they all fall-through to include these two JS files? +cc @tanyaparker

**Comment by caleybrock** [comment]
It's my understanding that all the rest inherit from these views, but @tanyaparker please correct me if I'm wrong.

**Comment by tanyaparker** [comment]
Do you mean other sites like csedweek.org or uk.code.org? They are built to inherit so I would think yes, but I'm not 100% positive. Caley have you tested other sites?

**Comment by caleybrock** [comment]
I checked to see if they have themes or layouts that override these, but it's hard to test this. If we see errors on those sites I'll go back and investigate more.

**Pull request merged**
