### PR TITLE
Add tooltips to app lab blocks 

### PR DESCRIPTION
**Pull request by poorvasingal**
There were several blocks in app lab that were missing descriptions, so I went ahead and added descriptions for those.  I also started making changes to existing tooltips based on Matt's recommendations but I'll do a full pass for those later.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
lgtm

**Comment by cpirich** [comment]
I think I made many of the same changes today. Can you compare with my PR from 2pm?

**Comment by cpirich** [comment]
Please hold off on merging so we can reconcile https://github.com/code-dot-org/code-dot-org/pull/7070

**Comment by cpirich** [comment]
Yeah, I got all of the same ones in the applab and many more. But I got none of the ones in common. So maybe I'll just copy your common changes into my PR?

**Comment by poorvasingal** [comment]
Ah, whoops.  That sounds good to me.  Thanks.

**Pull request closed without merging**
