### PR TITLE
add hidden column to sections

### PR DESCRIPTION
**Pull request by Bjvanminnen**
Similar to https://github.com/code-dot-org/code-dot-org/commit/2d86649e2aed5136af17d2508974ab1dca733dd8 this is adding a new column to Sections.

That migration was done after hours, but I believe the takeaway was that it needn't have been? Trying to decide how carefully I should manage this one.

### CODE REVIEW

**Comment by aoby** [comment]
Might be worth getting input from @jeremydstone as far as when / how to apply the migration.

**Comment by caleybrock** [comment]
There was a visible change in output speed in graphs when we ran the migration, but the site did not go down. We did it between 4-5pm which I think was reasonable and should probably be done again.

**Comment by Bjvanminnen** [comment]
I think I accidentally merged my commit with some other commits, so I'm going to start afresh.

**Comment by Bjvanminnen** [comment]
Closing in favor of https://github.com/code-dot-org/code-dot-org/pull/17619

**Pull request closed without merging**
