### PR TITLE
add 5px of space to the right of 'share this notice with parents'

### PR DESCRIPTION
**Pull request by dju90**
…on privacy notice page

### CODE REVIEW

**Comment by joshlory** [comment]
Heads up, it looks like you're committing with a different user from your GitHub account. You can easily fix with `git config`!

image

**Comment by breville** [comment]
Screenshot?

**Comment by dju90** [comment]
Ah sorry! Here it is:
image

**Comment by breville** [comment]
nit: given that the buttons use CSS classes defined below, it seems to make sense to use a CSS class for this styling change too.

**Comment by dju90** [comment]
fixed!

**Review by breville — APPROVED** [review]

**Pull request merged**
