### PR TITLE
update flappy to redirect to start of tutorial

### PR DESCRIPTION
**Pull request by tanyaparker**

### CODE REVIEW

**Comment by breville** [comment]
I was going to ask if we should actually redirect to https://code.org/api/hour/begin/flappy but I think we stopped using those entrypoints with updated /learn last year?

**Comment by tanyaparker** [comment]
Oh right. Well wasn't it because we created a specific entrypoint from /learn so that we could differentiate starts from /learn as opposed to starts from other parts of our site? Perhaps this _should_ be using that? If you agree, I'll update.

**Comment by breville** [comment]
Ah, /learn actually just links to the regular URL now (e.g. `/s/frozen/reset`) and simultaneously posts a GA event to tracking.  I guess the old pegasus metrics get updated using the hidden pixel instead.  So his change as-is seems right.

**Comment by tanyaparker** [comment]
Cool! Thanks for checking.

**Pull request merged**
