### PR TITLE
Mini-Toolbox Prototype

### PR DESCRIPTION
**Pull request by epeach**
whenclicked

Mini-toolbox Prototype: https://docs.google.com/document/d/1VV9qHE0qjvas1o8-7zavDpkrbxG9gUmCFRas3Xlwtx4/edit#heading=h.8u7mwfss3758

Blockly has been updated accordingly.
Temporary blocks (not in the default block set, so not visible to the public) that reference the sprite that is clicked

Next steps:
Show sprite thumbnail in the 'clicked sprite' block

### CODE REVIEW

**Comment by jmkulwik** [comment]
What happens if I have multiple "When clicked set" blocks for the same type of sprite?

**Comment by epeach** [comment]
@jmkulwik Because the 'clickedSprite' is set when the action is triggered, when there are two 'clickset' block for the same type of sprite, the sprite that gets clicked will trigger both actions.

**Review by joshlory — APPROVED** [review]
LGTM to unblock prototyping. How can we test these new blocks once they're production-ready?

**Review by jmkulwik — APPROVED** [review]

**Comment by epeach** [comment]
@joshlory Our general test coverage of blocks can definitely be improved. It might be worth setting some time aside when we don't have deadlines to build out the test harnesses that would allow us to more easily test blocks.

**Comment by joshlory** [comment]
Sounds good, let's get this tracked in Jira!

**Comment by joshlory** [comment]
@epeach link to Jira story?

**Comment by epeach** [comment]
@joshlory  https://codedotorg.atlassian.net/browse/STAR-364

**Pull request merged**
