### PR TITLE
Access report 2020 2021

### PR DESCRIPTION
**Pull request by LizGauthier**
Uploaded Access Report files for the 2020-21 year: namely by state and year --

AK | 2020
AL (2018-2019) | 2018
AL (2020-2021) | 2020
AP SCHOOLS | 2020 though 2016 (4 files)
AR | 2020
AZ | 2019
CA | 2018
CA | 2017
CSA | 2020 though 2016 (4 files)
CSP | 2020 though 2016 (4 files)
CT | 2019
DC | 2020
DE | 2020
FL | 2020
GA | 2020
HI (2018-2019 | 2018
HI (2020-2021) | 2020
IA | 2020
IL | 2019
IN | 2020
KY | 2020
LA | 2020
MD | 2019
ME | 2020
MS | 2020
MT | 2020
NC | 2020
ND | 2020
NE | 2019
NH | 2020
NJ | 2019
NM | 2020
NY | 2019
OK | 2020
PLTW | 2020
RI | 2020
SC | 2020
SD | 2018
SD | 2019
SD | 2020
SD | 2017
TEALS | 2020
TN | 2020
TX | 2019
UT | 2020
VA | 2019
VT | 2020
WA (2017-2018) | 2017
WA (2018-2019 | 2018
WI | 2020
WV | 2020
WY | 2020

Following this process for uploading data -- https://docs.google.com/document/d/1tUx1FlENfByaxA9jx3te42vOahsZaym1HaDoLeC0Z2U/edit#heading=h.v67t7p1gekea

Similar to this pull request -- https://github.com/code-dot-org/code-dot-org/pull/35710/files

### CODE REVIEW

**Review by tim-dot-org — CHANGES_REQUESTED** [review]
A few of the ap_cs_offerings and ap_school_codes files have .txt extensions, but it looks like they're .csv in s3, can you change them to .csv? the file contents look right

**Comment by tim-dot-org** [comment]
could you add the new files that you just added to s3? (bootup and the 2018 states)

**Comment by LizGauthier** [comment]
I'm planning on doing this in a few weeks with all the other files I've
ingested and once we get the final files. Wanted to commit this set we did
a while back first.

Can we close this out to merge it? And then i'll do the final batch with a
new PR in 3 weeks.

*Liz Gauthier*
Data Analyst
Research, Evaluation, and Data
Code.org
***@***.***

**Review by tim-dot-org — APPROVED** [review]
ya sounds good!

**Comment by LizGauthier** [comment]
Hi Suresh,

When you get a chance can you review this PR? Would love to close.

Cheers,
Liz

*Liz Gauthier*
Data Analyst
Research, Evaluation, and Data
Code.org
***@***.***

**Pull request merged**
