### PR TITLE
HoC student name cleanup cron script bug fixes

### PR DESCRIPTION
**Pull request by jamescodeorg**
Follow-up to #39216. 

Fixed two minor issues:
- batch_rows_updated was set to the wrong value if a batch returned rows from the db but none of them had a name.  This caused the reported count of rows updated to be too high.
- Fix formatting of Slack message.

## Links

- jira ticket: [LP-1685](https://codedotorg.atlassian.net/browse/LP-1685)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by hannahbergam — APPROVED** [review]
Quick q to make sure I understand- pulling this variable inside the while loop means it's reset back to 0 before each transaction, right? And before, it was not being reset? 

LGTM!

**Review by cforkish — APPROVED** [review]
LGTM!

**Comment by jamescodeorg** [comment]
@hannahbergam Yes, that's exactly correct!

**Comment by hannahbergam** [comment]
> @hannahbergam Yes, that's exactly correct!

Great! Thank you!

**Pull request merged**
