### PR TITLE
Adds and populates a basic_proficiency_at field to the UserProficiency model.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
@hamms, note that the test failures are legitimate, I reproduce them locally. But I don't understand their cause. Mind taking a quick glance and seeing if you can clue me in? Thanks!

**Comment by Hamms** [comment]
Oh dang, those are totally my fault. I added an `assign_attributes` method to the ConceptDifficulties helper that should have gone on the LevelConceptDifficulties model

**Comment by Hamms** [comment]
I'm a little perturbed that they were not caught earlier

**Comment by Hamms** [comment]
LGTM, pending passing of tests

**Comment by ashercodeorg** [comment]
Tests should be fixed, if you want to take another look (no need).

**Comment by ashercodeorg** [comment]
Failure was unrelated (SQS not starting in time), I'm rerunning and submitting in the interim.

**Pull request merged**
