### PR TITLE
educate: remove broken links to student/teacher of the month

### PR DESCRIPTION
**Pull request by breville**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
LGTM. For reference, these were broken by #13506.

**Comment by tanyaparker** [comment]
To clarify it's not that the links were broken since the pages still exist, but just that we don't want to actively link to them in the context of nominating someone? Because I also asked Maddie to update `pegasus/sites.v3/code.org/public/educate/resources/inspire.md` to include the wording she wanted or to remove the section. So not sure if she wants to do the same for this page.

**Comment by breville** [comment]
Correct, but good point.  I'll let her know about this change.

**Comment by tanyaparker** [comment]
Thanks!

**Pull request merged**
