### PR TITLE
add ai4k12 draft standards

### PR DESCRIPTION
**Pull request by davidsbailey**
Finishes https://codedotorg.atlassian.net/browse/PLAT-1032

Screen Shot 2021-06-14 at 10 30 05 PM

I'm calling these "draft" because that's how they're referred to here: https://ai4k12.org/ . Once these get finalized, we can decide whether to rename these standards to ai4k12, or create a new framework named ai4k12.

## Testing story

* Manually verified that new standards show up in the lesson editor
* Passing all tests except the known issue with the starwars UI test

### CODE REVIEW

**Comment by dmcavoy** [comment]
Does the draft part of the name show up user-facing on the lesson plans?

**Comment by davidsbailey** [comment]
> Does the draft part of the name show up user-facing on the lesson plans?

yes

**Comment by dmcavoy** [comment]
> > Does the draft part of the name show up user-facing on the lesson plans?
> 
> yes

Did you check with Dan that he is alright with that?

**Review by dmcavoy — APPROVED** [review]
Changes look good. Just want to make sure the curriculum team is good with the draft part of the name

**Comment by davidsbailey** [comment]
I'll check with Dan. For the record, here's how it looks on the lesson plan page:
Screen Shot 2021-06-15 at 11 20 28 PM

**Comment by davidsbailey** [comment]
updated per [conversation with Dan](https://codedotorg.slack.com/archives/CFGAVL2CA/p1623824511063000)

Screen Shot 2021-06-16 at 2 05 04 PM

Screen Shot 2021-06-16 at 2 06 38 PM

**Pull request merged**
