### PR TITLE
Create i18n translations on client and server side

### PR DESCRIPTION
**Pull request by JamesHankinsDev**
Small PR to add i18n strings for PR-#40105: FND-1431: Section Lock

Adds required strings to React and Rails i18n files 
- `apps/i18n/common/en_us.json` implements for React, 
- `dashboard/config/locales/en.yml` for Rails

**NOTE: This sets up strings to be included in PR-PR-#40105: FND-1431: Section Lock and should be reviewed/approved/merged first.

## Links
n/a

## Testing story
n/a

## Deployment strategy
n/a
## Follow-up work
Strings utilized in PR-#40105: FND-1431: Section Lock

## Privacy
n/a

## Security
n/a

## Caching
n/a
## PR Checklist:
n/a

### CODE REVIEW

**Review by daynew — APPROVED** [review]

**Comment by dju90** [comment]
found a typo in the spec: "explainRestrictedSectionWordAndPicture": "If set to ‘yes,’ students will not be able to join this section using the **section** code. You can still add students to the section manually on the Manage Students tab.", instead of "selection"

**Comment by dju90** [comment]
Nit: "restrictSectionAccess" string should read "Restrict access to **this** section", instead of "the"

**Comment by dju90** [comment]
For transparency, I'm having second thoughts about the phrasing "Restrict access to this section". I'm worried it will sound too desirable, when in reality we only want teachers using it if they need to stop unidentified students from joining the section. ~Currently considering renaming~ **Let's rename it to "Lock this section"** to make it sound more serious... I'll update the spec to match

**Comment by dju90** [comment]
Sorry for the last-minute changes, but can we also change the two instances of "We couldn't add you to this section. Please contact your teacher for help." to "We couldn't add you to section {sectionId} because it is locked. Please contact your teacher for help." ? A little more informative and if the section was locked by mistake, gives the teacher a little more information to troubleshoot the issue. I'll update the spec to match.

**Comment by JamesHankinsDev** [comment]
Hey @dju90, this update is just running through the drone testing now, but there are no changes that would impact any tests here, so should be fine once that is completed. I wanted to quickly give a summary of changes made based on your above feedback. Hoping these are as you intended, but happy to make any additional adjustments as needed.

- **en_us.json (React-based strings)**
    - correct typo in new/edit section form string 
        - `explainRestrictedSectionWordAndPicture` -> 'selection' changed to 'section'
    - Changed field title 
        - `restrictSectionAccess` -> 'Restrict access to the section' changed to 'Lock this section'
    - Error messaging updated to be more descriptive
        - `sectionsNotificationJoinRestricted` -> 'We couldn't add you to this section. Please contact your teacher for help' changed to 'We couldn't add you to section {sectionId} because it is locked. Please contact your teacher for help'.

- **en.yml (Rails-based strings)**
    - Error messaging updated to be more descriptive
        - `follower.error.restricted_section` -> 'We couldn't add you to this section. Please contact your teacher for help' changed to 'We couldn't add you to section %{sectionId} because it is locked. Please contact your teacher for help'

Let me know if there is anything I overlooked!

**Pull request merged**
