### PR TITLE
Add temporary /p/dancelab for prototyping

### PR DESCRIPTION
**Pull request by joshlory**
I'm on the fence about whether or not we should ship this.  One one hand, it makes trying out different programs easier to create & link to.  But I wonder if it's better to keep different explorations on an even playing field?  (I.e. have lots of different universes for prototyping, none of which are more "special" than any other.)

### CODE REVIEW

**Comment by joshlory** [comment]
[Dancelab project level](https://trello.com/c/jBp3Vodg/248-dancelab-project-level)

**Comment by balderdash** [comment]
What I really want is projects that are easy to make/share/remix for every universe type, so:
* The universe config includes a field for the project template level
  * If the universe doesn't specify one, we just serve up the parent universe's template level with the universe swapped out
* `/p/gamelab_jr/dancelab`, `/universe/dancelab`, or even just `/p/dancelab` takes you to a `dancelab` universe project.

I don't want to hold people back from prototyping dancelab right now while we consider this though. If there's demand for dancelab projects already, shipping this is fine with me.

**Comment by joshlory** [comment]
Ah, `/universe/dancelab` is super interesting!

Do think having a single "Universe" field is preferable to providing "Helper libraries" and "Block pool" fields?  I think you're right, because eventually we'd want the "Universe" to also specify which app visualization gets loaded.

**Comment by balderdash** [comment]
I think "universe" will be the unit that most often gets worked with. When you do want to try other combinations of libraries and block pools, it should be very quick and easy to create other universes with the combinations you want to try (and for just changing block pools, the query param provides another way to try things out).

**Comment by joshlory** [comment]
Makes sense!  I'm closing out this PR in favor of the "Universe" approach.

**Comment by joshlory** [comment]
Turns out we do want this 😂.

**Pull request merged**
