### PR TITLE
Revert "Move Overlay to AppView"

### PR DESCRIPTION
**Pull request by Bjvanminnen**
Reverts code-dot-org/code-dot-org#11504

### CODE REVIEW

**Comment by Hamms** [comment]
A quick survey of z-indexes in our system reveals that most of our z-indexes hover around various small powers of 10:

image

(note that `#window-resizer-tooltip` is a chrome plugin element, not something of ours)

Since I want this overlay to be below the rotate popup but above the footer, I propose bumping the rotate container up to 100k and the overlay up to 10k. Thoughts?

**Comment by Bjvanminnen** [comment]
If the goal is to have this be just below the rotate popup, does it make sense to just do something like 9999 and 10k? A gap of 90k seems excessive.

**Comment by Hamms** [comment]
I honestly have no idea; I have yet to see any usage of z-index that I would consider "best practice".

I think I'd want to do at least 9900 and 10k; a gap of 1 seems insufficient.

**Comment by Bjvanminnen** [comment]
That seems fine. I'm also not sure what best practices are.

If I were designing a system from scratch, it seems like it would be nice to have a singular place where you can see all the z-indexes in our system, allowing you to easily reason about where each item is layered in relation to others. Not sure we have any good way to do that tho.

**Comment by Hamms** [comment]
In purely React land, that seems doable, but not so much in a world where we mix React and CSS (and very possibly jQuery and who knows what else).

Note that in this specific instance, the Overlay defines a const that it uses for z-index and which the Top Instructions reference to set their own.

**Pull request merged**
