### PR TITLE
Migration to add published_state to course version

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Add `published_state` to the course_versions table.

First of 3 PRs to add published_state to CourseVersion:
1. (This PR) Add a column for published_state to the course_versions table
2. (#42585, in progress) Seed published_state into CourseVersion
3. (#41558, in progress) Use the published_state on course_version

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]

**Review by Sam-Hutchins — APPROVED** [review]
From what I can tell, this table is not replicated into redshift and doesn't affect the RED team.

**Comment by davidsbailey** [comment]
Thanks for looking, @Sam-Hutchins . Heads up that we're planning to move some of the fields which are shared between `courses` and `scripts` into this new table, so depending on which fields you use, it may need to start being replicated soon.

**Comment by Sam-Hutchins** [comment]
@davidsbailey can you make sure to flag it in data when the ball gets rolling on that change?  I think that will have a pretty substantial impact on our work beyond just needing the table replicated.

**Comment by davidsbailey** [comment]
@Sam-Hutchins will do. sorry to keep changing things on you. we can probably get most of the benefit by storing the info in both places, and having our application server just ignore the copy we don't need.

**Pull request merged**
