### PR TITLE
P5Lab: fix noisy exception

### PR DESCRIPTION
**Pull request by breville**

### CODE REVIEW

**Review by epeach — COMMENTED** [review]
Love the simplicity of this! Can we add some more context to the PR description for any future code archeologists?

**Comment by mikeharv** [comment]
+1 To Erin's request. I wrote the original code as part of this:
- https://github.com/code-dot-org/code-dot-org/pull/45055

I'd love to get a little more context about what we were seeing and how this addresses it. Have you confirmed that the workspace alert still work as expected? For example, it would show if you define a new Sprite Lab function, call it in your main workspace, then delete the function definition. Happy to pull and test tomorrow if that's helpful.

**Comment by breville** [comment]
> I'd love to get a little more context about what we were seeing and how this addresses it. Have you confirmed that the workspace alert still work as expected? For example, it would show if you define a new Sprite Lab function, call it in your main workspace, then delete the function definition. Happy to pull and test tomorrow if that's helpful.

Here is a screenshot of the error occurring at the end of a run of a very small program: 

Screen Shot 2022-07-13 at 3 21 59 PM

@mikeharv It would be great if you could determine whether a deeper fix is needed.  I was really addressing the symptom, without analysing the underlying issue.

**Review by mikeharv — APPROVED** [review]
This looks good to me. I pulled and tested the associated feature and found no regressions.

**Pull request merged**
