### PR TITLE
optimize user_scripts query

### PR DESCRIPTION
**Pull request by wjordan**
Fixes a bug causing a temporary table creation when calling `User#scripts`.

Before:

```
irb(main):002:0> User.first.scripts.explain
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL  ORDER BY `users`.`id` ASC LIMIT 1
  Script Load (1.1ms)  SELECT `scripts`.* FROM `scripts` INNER JOIN `user_scripts` ON `scripts`.`id` = `user_scripts`.`script_id` WHERE `user_scripts`.`user_id` = 1 AND `scripts`.`hidden` = 0  ORDER BY -completed_at asc, greatest(coalesce(started_at, 0), coalesce(assigned_at, 0), coalesce(last_progress_at, 0)) desc, id asc
=> EXPLAIN for: SELECT `scripts`.* FROM `scripts` INNER JOIN `user_scripts` ON `scripts`.`id` = `user_scripts`.`script_id` WHERE `user_scripts`.`user_id` = 1 AND `scripts`.`hidden` = 0  ORDER BY -completed_at asc, greatest(coalesce(started_at, 0), coalesce(assigned_at, 0), coalesce(last_progress_at, 0)) desc, id asc
+----+-------------+--------------+--------+-----------------------------------------------------------------------------+---------------------------------------------+---------+----------------------------------------------+------+---------------------------------+
| id | select_type | table        | type   | possible_keys                                                               | key                                         | key_len | ref                                          | rows | Extra                           |
+----+-------------+--------------+--------+-----------------------------------------------------------------------------+---------------------------------------------+---------+----------------------------------------------+------+---------------------------------+
|  1 | SIMPLE      | user_scripts | ref    | index_user_scripts_on_user_id_and_script_id,index_user_scripts_on_script_id | index_user_scripts_on_user_id_and_script_id | 4       | const                                        |    1 | Using temporary; Using filesort |
|  1 | SIMPLE      | scripts      | eq_ref | PRIMARY                                                                     | PRIMARY                                     | 4       | dashboard_development.user_scripts.script_id |    1 | Using where                     |
+----+-------------+--------------+--------+-----------------------------------------------------------------------------+---------------------------------------------+---------+----------------------------------------------+------+---------------------------------+
2 rows in set (0.00 sec)
```

After:

```
irb(main):001:0> User.first.scripts.explain
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL  ORDER BY `users`.`id` ASC LIMIT 1
  Script Load (0.5ms)  SELECT `scripts`.* FROM `scripts` INNER JOIN `user_scripts` ON `scripts`.`id` = `user_scripts`.`script_id` WHERE `user_scripts`.`user_id` = 1 AND `scripts`.`hidden` = 0  ORDER BY -completed_at asc, greatest(coalesce(started_at, 0), coalesce(assigned_at, 0), coalesce(last_progress_at, 0)) desc, user_scripts.id asc
=> EXPLAIN for: SELECT `scripts`.* FROM `scripts` INNER JOIN `user_scripts` ON `scripts`.`id` = `user_scripts`.`script_id` WHERE `user_scripts`.`user_id` = 1 AND `scripts`.`hidden` = 0  ORDER BY -completed_at asc, greatest(coalesce(started_at, 0), coalesce(assigned_at, 0), coalesce(last_progress_at, 0)) desc, user_scripts.id asc
+----+-------------+--------------+--------+-----------------------------------------------------------------------------+---------------------------------------------+---------+----------------------------------------------+------+-----------------------------+
| id | select_type | table        | type   | possible_keys                                                               | key                                         | key_len | ref                                          | rows | Extra                       |
+----+-------------+--------------+--------+-----------------------------------------------------------------------------+---------------------------------------------+---------+----------------------------------------------+------+-----------------------------+
|  1 | SIMPLE      | user_scripts | ref    | index_user_scripts_on_user_id_and_script_id,index_user_scripts_on_script_id | index_user_scripts_on_user_id_and_script_id | 4       | const                                        |    1 | Using where; Using filesort |
|  1 | SIMPLE      | scripts      | eq_ref | PRIMARY                                                                     | PRIMARY                                     | 4       | dashboard_development.user_scripts.script_id |    1 | Using where                 |
+----+-------------+--------------+--------+-----------------------------------------------------------------------------+---------------------------------------------+---------+----------------------------------------------+------+-----------------------------+
2 rows in set (0.00 sec)
```

also attn @philbogle to confirm merge into staging.

### CODE REVIEW

**Comment by laurelfan** [comment]
LGTM

side note: do you have any idea why we keep getting `NoMethodError: undefined method`search' for #JMESPath::Runtime:0x000000052d87f0` on travis

**Comment by wjordan** [comment]
@laurelfan I've added another commit that fixes the `User#teachers` query showing similar behavior, can you make sure this looks good too?

@philbogle OK to merge these two optimizations into staging?

**Comment by laurelfan** [comment]
teachers query LGTM too, thanks!

**Comment by philbogle** [comment]
LGTM

**Pull request merged**
