### PR TITLE
Handle blank foorm submissions

### PR DESCRIPTION
**Pull request by bencodeorg**
We have a honeybadger error (linked below) where we're trying to process foorm submissions for our analytics (RED) team, but fail when submissions are not parsable JSON.

Identified that submissions where the user did not answer any questions and hit submit are being stored as the string "null", which is not valid JSON. Fixing such that the JSON parsable "{}" is stored in this case going forward.

Tangentially, I deduped some repetitive test fixtures.

## Links

- honeybadger error for cronjob: https://app.honeybadger.io/projects/45435/faults/80897052
- honeybadger error for CSV export: https://app.honeybadger.io/projects/3240/faults/81044781

## Testing story

Added unit tests to cover this case, and manually inspected a simple survey submission I created where I had answered no questions.

## Follow-up work

Take existing submissions (2 at this time) where `answers` field is "null" and save as "{}", which is what will happen in the future.

### CODE REVIEW

**Review by breville — APPROVED** [review]
Seems good to me, and well tested.  One question is whether it's better to catch "no answers" at the level of these two specific forms, or whether to do it a bit more deeply?  Put another way, will we have to add the same catch to other places later, or is there one place we can add it now that will work for all future forms?

**Comment by bencodeorg** [comment]
> Seems good to me, and well tested. One question is whether it's better to catch "no answers" at the level of these two specific forms, or whether to do it a bit more deeply? Put another way, will we have to add the same catch to other places later, or is there one place we can add it now that will work for all future forms?

mmm good point -- I thought about that a bit, but was being lazy :). Maybe `before_create` callback on foorm submission?

https://api.rubyonrails.org/v6.1.4/classes/ActiveRecord/Callbacks/ClassMethods.html#method-i-before_create

**Comment by bencodeorg** [comment]
@breville give this another look :)

**Review by breville — APPROVED** [review]
This looks like a good generalised solution.  Great to see the tests all hold up.  Thanks for pursuing this.

**Pull request merged**
