### PR TITLE
Allows Gamelab levels in public scripts.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Per request from levelbuilders.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @poorvasingal

**Comment by joshlory** [comment]
Can `student_of_admin_required` go away or is this concept still needed?

**Comment by ashercodeorg** [comment]
AFAIK, this removes active usages of `student_of_admin_required`. Assuming it isn't likely to be used in the future, I'll follow up with a PR that removes the baggage surrounding it.

**Comment by joshlory** [comment]
LGTM pending followup PR to remove usages.  Nice cleanup & tests!

**Comment by ashercodeorg** [comment]
Per offline conversation with @poorvasingal, the `student_of_admin_required` baggage can be eliminated. So I'll follow up doing so.

**Pull request merged**
