### PR TITLE
use ntp cookbook

### PR DESCRIPTION
**Pull request by laurelfan**
Use ntp (network time protocol) to make sure that the time on the server is "correct". Fixes known issue with zendesk login and potentially other unknown issues.

copied will's manual install steps here:
- [x] run `berks install` to locally fetch `ntp` cookbook from chef supermarket
- [x] upload berkshelf cookbooks using `berks upload`
- [x] add cookbook to runlist(s) (base/standalone and/or production)
- [x] run chef-client to update

### CODE REVIEW

**Comment by wjordan** [comment]
since we haven't been given time to finish our Chef integration yet, are these the remaining steps we need to manually do in order to activate this?

- [ ] run `berks install` to locally fetch `ntp` cookbook from chef supermarket
- [ ] upload cookbook to our hosted chef repo with `knife cookbook upload ntp`
- [ ] add cookbook to runlist(s) (base/standalone and/or production)
- [ ] run chef-client to update

**Comment by laurelfan** [comment]
would `berks upload` also work for step 2?

**Comment by wjordan** [comment]
not sure- i've never used `berks upload`, it's possible it will work but Berkshelf doesn't seem very stable in general yet, so let me know how it goes.

**Comment by laurelfan** [comment]
Hm, do you think it would be a better idea not to use berks? what's the
alternative, copying the ntp cookbook from the github repo to /cookbooks
and checking that in?

**Comment by wjordan** [comment]
If it works, using Berkshelf should be fine. The alternatives (such as Librarian, or manually shuffling around cookbooks) would leave us even worse off. Best we can do is keep an eye out for bugs and document any workarounds we need.

My struggles with Berkshelf in the past might have been resulting more from the [vagrant-berkshelf](https://github.com/berkshelf/vagrant-berkshelf) plugin rather than the actual tool itself, so it might be more stable when used directly.

**Comment by joshlory** [comment]
This also affects projects, e.g. when you create a brand new project and it says "Saved 4 minutes ago".

**Pull request merged**
