### PR TITLE
DSCO TextField - add input props and reset styling

### PR DESCRIPTION
**Pull request by drizco**
For TextField I'm passing down some common input props like maxLength, minLength, and autoComplete. I also reset some input styles that were causing my input to overflow its label. I checked the rest of the places in the app where `TextField` is used and compared them with and without the styling changes. luckily the module styles were already fixing the issue. this just makes it easier to use going forward.

BEFORE:
Screenshot 2024-09-27 at 8 52 10 AM
Screenshot 2024-09-27 at 8 53 11 AM
Screenshot 2024-09-27 at 8 53 29 AM

AFTER:
Screenshot 2024-09-26 at 1 40 18 PM
Screenshot 2024-09-26 at 1 36 11 PM
Screenshot 2024-09-26 at 1 35 04 PM

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by levadadenys — COMMENTED** [review]
Discussed in slack 😄

**Comment by drizco** [comment]
> Discussed in slack 😄

I've scoped down these changes to only be for the TextField component, added to the changelog and am only keeping the style reset and the additional native input props 🤞

**Review by levadadenys — APPROVED** [review]
LGTM! Thanks you for the update!

p.s. non blocking nit: Might make it a little bit easier if in title of PR we specify the component we're updating right now (e.g. DSCO - TextField - add input props, minor styles update) and when adding `after` screenshots please also add `before` screenshots since it makes it much easier and faster to understand what's going on

**Comment by drizco** [comment]
> LGTM! Thanks you for the update!
> 
> p.s. non blocking nit: Might make it a little bit easier if in title of PR we specify the component we're updating right now (e.g. DSCO - TextField - add input props, minor styles update) and when adding `after` screenshots please also add `before` screenshots since it makes it much easier and faster to understand what's going on

updated! 🚀

**Pull request merged**
