### PR TITLE
Use path alias for gamelab imports

### PR DESCRIPTION
**Pull request by ajpal**
I'm planning to move SpriteLab and GameLab to both be nested under `P5Lab`, which will contain everything that's shared between SpriteLab and GameLab.

This PR will reduce the diff for that work by using the absolute path alias for imports rather than relative paths (since the directory level will change when GameLab moves under P5Lab).

### CODE REVIEW

**Comment by jmkulwik** [comment]
Do you know why these were absolute rather than relative paths in the first place? Was it for clarity or performance?

**Comment by ajpal** [comment]
I'm not sure exactly, but both relative and absolute paths seem to be used throughout the codebase, and I don't think it makes any difference.

**Review by jmkulwik — APPROVED** [review]
LGTM!

**Comment by jmkulwik** [comment]
> Do you know why these were absolute rather than relative paths in the first place? Was it for clarity or performance?

Internal folks can see this discussion for more context: https://codedotorg.slack.com/archives/C0T0PNR0D/p1563236279126400

**Pull request merged**
