### PR TITLE
update i18n test to toggle to short instructions (now that we are showing long instructions)

### PR DESCRIPTION
**Pull request by Hamms**
follow-up to https://github.com/code-dot-org/code-dot-org/pull/24188

### CODE REVIEW

**Comment by Hamms** [comment]
Oh dang, upon manually running these I realize that we actually do quite a bit of post-processing on the Minecraft instructions to get them to look as fancy as they do: http://studio.code.org/s/hero/stage/1/puzzle/1

I'm going to have to update the tests to actually toggle to the regular instructions to test this, I think.

**Comment by Hamms** [comment]
PTAL

**Comment by Erin007** [comment]
LGTM - passes locally?

**Comment by Hamms** [comment]
Yep!

**Comment by Hamms** [comment]
Gonna go ahead and merge without waiting for Circle, since this test is no-circled

**Pull request merged**
