### PR TITLE
Move build_script_level_(url|path) from levels helper to scriptlevel model

### PR DESCRIPTION
**Pull request by balderdash**

### CODE REVIEW

**Comment by Hamms** [comment]
What's the motivation for this change?

**Comment by balderdash** [comment]
Just moving some code out of levels helper that doesn't seem like it belongs there. It's not needed for anything else.

**Comment by Hamms** [comment]
I believe the intent of having it where it was previously was to emulate the native Rails `path` and `url` helpers; I'm not entirely convinced that it makes more sense in Rails land to have them on the model. @joshlory, thoughts?

**Comment by balderdash** [comment]
Oh I see, yeah it makes sense to leave them there then.

**Pull request closed without merging**
