### PR TITLE
New school and school district data ingestion from NCES for 2021-2022

### PR DESCRIPTION
**Pull request by vijayamanohararaj**
Seeding script updates to ingestion new school and school district information (through CSV files uploaded to S3) that contain latest NCES data for schools and school districts.

## Links
- jira ticket: https://codedotorg.atlassian.net/browse/ACQ-460?atlOrigin=eyJpIjoiNWU0MWIxMzM5Nzk3NDE5YmFjYzdlZDI5ZTMzY2IyNTciLCJwIjoiaiJ9 

## Testing story
Validated the changes locally by running the import scripts before making changes and bringing the environment to a similar state to production. Then ran the changes in dry run mode and then actually running the script for the seeding. 

## Deployment strategy
The seeding scripts are run as part of all the DTPs, so these changes should apply as part of the next DTP. These also have logs that would go to cloud watch, which has been confirmed for earlier runs and will use that for validation.

## Follow-up work

Once this is done, there will be an additional one off script to use this ingested data and populate the school stats by year table. That will be a separate PR.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [x] User impact is well-understood and desirable
- [x] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by hannahbergam — APPROVED** [review]
This LGTM! So comforting to have that nearly identical code right above to compare with. I think as long as those local dry runs looked right, then it's good to go! Were the reported numbers around what you'd expect from looking at the raw data?

**Review by bakerfranke — APPROVED** [review]
If it looks good to Hannah it looks good to me.  TBH I'm not really sure what I'm looking at until it hits the DB.  But I'm sure it's great!

**Comment by vijayamanohararaj** [comment]
> This LGTM! So comforting to have that nearly identical code right above to compare with. I think as long as those local dry runs looked right, then it's good to go! Were the reported numbers around what you'd expect from looking at the raw data?

Given the data had the list of all the schools, it was hard to tell the diff to be expected. But the local run summary looked promising
```

1472 new schools added.
13305 schools updated.
86385 schools unchanged (apart from specified ignored attributes).
118 duplicate schools skipped.
Among updated schools, these attributes were updated:
last_known_school_year_open: 99248
school_category: 7092
latitude: 4722
longitude: 4717
address_line1: 1662
name: 1572
zip: 521
city: 308
address_line2: 78
state_school_id: 41
school_type: 26
address_line3: 2
state: 1
```

**Comment by vijayamanohararaj** [comment]
> > This LGTM! So comforting to have that nearly identical code right above to compare with. I think as long as those local dry runs looked right, then it's good to go! Were the reported numbers around what you'd expect from looking at the raw data?
> 
> Given the data had the list of all the schools, it was hard to tell the diff to be expected. But the local run summary looked promising
> 
> ```
> 
> 1472 new schools added.
> 13305 schools updated.
> 86385 schools unchanged (apart from specified ignored attributes).
> 118 duplicate schools skipped.
> Among updated schools, these attributes were updated:
> last_known_school_year_open: 99248
> school_category: 7092
> latitude: 4722
> longitude: 4717
> address_line1: 1662
> name: 1572
> zip: 521
> city: 308
> address_line2: 78
> state_school_id: 41
> school_type: 26
> address_line3: 2
> state: 1
> ```

@hannahbergam , would you say this looks similar to the number of updates that happened last year around. @bakerfranke , please let me know if something looks particularly odd

**Comment by hannahbergam** [comment]
> > > This LGTM! So comforting to have that nearly identical code right above to compare with. I think as long as those local dry runs looked right, then it's good to go! Were the reported numbers around what you'd expect from looking at the raw data?
> > 
> > 
> > Given the data had the list of all the schools, it was hard to tell the diff to be expected. But the local run summary looked promising
> > ```
> > 
> > 1472 new schools added.
> > 13305 schools updated.
> > 86385 schools unchanged (apart from specified ignored attributes).
> > 118 duplicate schools skipped.
> > Among updated schools, these attributes were updated:
> > last_known_school_year_open: 99248
> > school_category: 7092
> > latitude: 4722
> > longitude: 4717
> > address_line1: 1662
> > name: 1572
> > zip: 521
> > city: 308
> > address_line2: 78
> > state_school_id: 41
> > school_type: 26
> > address_line3: 2
> > state: 1
> > ```
> 
> @hannahbergam , would you say this looks similar to the number of updates that happened last year around. @bakerfranke , please let me know if something looks particularly odd

Yes this seems about right to me! We'd missed a couple years of private school data so the diff was much bigger. Lower numbers of 'new' and a large majority 'unchanged' is reassuring here.

**Pull request merged**
