### PR TITLE
Experiment with retrying grunt tests once on failure

### PR DESCRIPTION
**Pull request by trevorb**

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
I'm a little bit apprehensive about doing something like this, as it makes it so that we become accustomed to finickiness in our test suite. I can get grunt tests to pass without these intermittency issues on my dev machine. It seems like there should be some set of things we can do to get into such a state on travis as well.

**Comment by trevorb** [comment]
Yea, I agree that this is not great.  I spent a bunch of time trying to figure out why they are not more reliable on Circle and got nowhere.  I don't have time right now to invest anymore time in debugging this and I'd rather there be less false positives from Circle.

**Comment by Bjvanminnen** [comment]
Fair enough. I also spent some time trying to understand the intermittent
failures, and couldn't get my branch to fail while I had logging statements
that would allow me to debug :(

**Comment by trevorb** [comment]
Circle is nice in that it allows you to ssh into the machines as they run your tests.  I was able to ssh into machines that failed on the automated run but I could run mochaTests 30 more times and never have a failure. Weird

**Pull request merged**
