### PR TITLE
Dance page - Update uplugged asset

### PR DESCRIPTION
**Pull request by nkiruka**
The PR is to update the unplugged asset in the second tile of the teacher resources section.

### Screen shot
screen shot 2018-11-07 at 9 26 17 pm

### CODE REVIEW

**Comment by maddiedierker** [comment]
are both `dance_unplugged` and `dance_unplugged_sm` PNGs needed? it looks like you're explicitly asking for a resized version of `dance_unplugged.png` in the code, but i could definitely be missing where/how we would end up needing `dance_unplugged_sm.png` as well

**Comment by nkiruka** [comment]
@madelynkasula Both images are sized differently and dance_unplugged.png worked better.  I will delete the other image.  Thanks.

**Comment by nkiruka** [comment]
@madelynkasula Deleted unused image.  All set for review.  Thanks

**Comment by Erin007** [comment]
I'm being finicky, but the robot's arm and the plug are a little cut off. Can you resize a nudge to get the whole robot in? Looks like the image has lots of extra space to the left and right of the bot. 
screen shot 2018-11-08 at 10 40 27 am

**Comment by nkiruka** [comment]
@Erin007 @madelynkasula I have the assets needed for each card.  The cutoff robot will be fixed with the new asset.  Current asset is a square but the new asset will be a rectangle.

**Pull request merged**
