### PR TITLE
Set real JotForm ids on all environments.

### PR DESCRIPTION
**Pull request by hacodeorg**
Centralizing Jotform ids on all environments to `config.yml.erb` because we sometime do manual tests on non-production environments ([slack discussion](https://codedotorg.slack.com/archives/C0T10H26N/p1572645556141600)).

Simply copy the list from `production.yml.erb` over.
https://github.com/code-dot-org/code-dot-org/blob/47a64e96a9f01777bd9c26a83d2dc6d5e3726b2f/config/production.yml.erb#L31-L111

### CODE REVIEW

**Review by agealy — APPROVED** [review]

**Comment by islemaster** [comment]
If these are not secrets, should we just put them in `config.yml.erb` so they're deduplicated and shared across all environments?

Should we be concerned about whether having these form ids configured in all environments would cause us to hit API rate limits with JotForm?

Do we do write operations to JotForm anywhere that we wouldn't want our test or staging environments to have access to for production forms?

**Comment by hacodeorg** [comment]
If we can use `config.yml.erb` that will solve this issue.

Regarding traffic to JotForm, I don't think there is any change there. All submissions from all environments to JotForm are manual. Downloading only happens on production-daemon.

**Review by islemaster — APPROVED** [review]
Yep, I'd centralize to config.yml.erb.  Otherwise, looks great!

**Comment by sureshc** [comment]
Looks great!

**Comment by davidsbailey** [comment]
This seems like perhaps a lot of application specific config in the global config file. If this doesn't need to change by environment, then I would suggest loading this from a .yml file like we do here: https://github.com/code-dot-org/code-dot-org/blob/54ebad4c02ac5ee2aada1dde834086bddf02ea34/dashboard/config/application.rb#L93

This does seem like a strict improvement over what we have today, so it seems ok if you want to stop and merge here, though.

**Comment by hacodeorg** [comment]
Thank you all! Separating all Jotform settings to its own yml file could be a great improvement. I'll consider it in the next step. The current change is enough to enable consistent testing across environments.

**Comment by wjordan** [comment]
> If this doesn't need to change by environment, then I would suggest loading this from a .yml file

I would agree with this suggestion, if these constants never change this use-case is in [`config/README.md`](https://github.com/code-dot-org/code-dot-org/blob/staging/config/README.md):

> CDO properties are not really needed for the following use-cases (though they have sometimes been used in these ways):
> 
> * Fixed constants that never change
>   * Use a standard Ruby module/class constant.

**Comment by hacodeorg** [comment]
Got it, thank you for the readme link. In this case, the form ids can change several times a year. I'll consider moving them to a constant file.

**Comment by davidsbailey** [comment]
Hi @hacodeorg , not sure if you're suggesting that changes your conclusion, but I would still consider extracting that config into a .yml file to be an improvement.

I see you updated your comment. sounds like we're on the same page.

**Pull request merged**
