### PR TITLE
Add script to list frontend servers

### PR DESCRIPTION
**Pull request by philbogle**
Add `bin/ls_frontend_servers` a simple script to list the names of all of the running frontend servers, their internal dns address, and an URL to hit dashboard directly on that servers.  (The URL is useful for troubleshooting misbehaving frontends.)

**Example run**

```
~/code-dot-org/bin$ ./ls_frontend_servers 

frontend-b4             ip-10-145-54-123.ec2.internal   http://ec2-54-204-132-24.compute-1.amazonaws.com:8080
frontend-d02            ip-10-157-137-197.ec2.internal  http://ec2-54-146-39-69.compute-1.amazonaws.com:8080
frontend-b01            ip-10-31-86-147.ec2.internal    http://ec2-54-197-105-10.compute-1.amazonaws.com:8080
..
```

The option `-p path` argument allows you to specify a relative path to append to the URL for each frontend. This is useful when you want to check a troublesome path against specific frontends because you can (e.g.) past the URLs into HipChat and click through every one to make sure they render correctly.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
lgtm. this seems like it could be very useful :)

**Comment by philbogle** [comment]
I just added an optional "-p PATH" argument to specify a relative path to append to the URL. Useful when you want to check a troublesome path against specific frontends

**Comment by wjordan** [comment]
Here's a one-liner to get the corresponding list of Chef-managed instances running the `front-end` role in the `production` environment (using `jq` to parse/transform the JSON returned by `knife --format json`):

`knife search node "roles:front-end AND chef_environment:production" --format json | jq ".rows | map({name: .name, local: .automatic.ec2.local_hostname, public: \"http://\\(.automatic.ec2.public_hostname):8080\"})"`

**Comment by philbogle** [comment]
@wjordan  Very nice.  

When I have a chance, I'll borrow some eyes from that snippet to simplify the code and rely upon chef as the authority.  I'd like to keep this in Ruby because the code is easier to read and add new features than with a shell script (e.g. for the new --path feature.)

**Comment by wjordan** [comment]
here's a version that outputs tab-delimited results:
`knife search node "roles:front-end AND chef_environment:production" --format json | jq --raw-output '.rows[] | "\(.name)\t\(.automatic.ec2.local_hostname)\thttp://\(.automatic.ec2.public_hostname):8080"'`

If extending within Ruby code is needed, you could surround the shell command with `` backticks. There's probably a way to invoke `knife` from within Ruby without using the shell command, but I haven't done it yet.

**Comment by philbogle** [comment]
Using knife via a shell command in Ruby is fine.   "jq" isn't installed by
default on developer machines, so I think we can just rely on Ruby json
parsing.

**Pull request merged**
