### PR TITLE
Adds collapsible categories to Levelbuilder

### PR DESCRIPTION
**Pull request by Hamms**
For each of the major editor categories defined in levels/form.html, we
wrap the associated partial in a collabsible div controlled by a simple
clickable label.

| Before | After |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by joshlory** [comment]
@Hamms is this PR still active?  Would love to see this feature get merged!

**Comment by Hamms** [comment]
It sort of is! The only reason I haven't merged it in is because I've received lukewarm feedback from the levelbuilders when I've showed it to them.

They also specifically requested "expand all" and "collapse all" options, which if added would I think be enough to earn a merge.

**Comment by islemaster** [comment]
Should we close this out?

**Comment by Hamms** [comment]
We should; Mei'lani's implementation is all we need from this

**Pull request closed without merging**
