### PR TITLE
Redact/Restore Course and Script overviews

### PR DESCRIPTION
**Pull request by Hamms**
Specifically, redact vocab and resource syntaxes from the markdown preprocessor.

**NOTE** that because this is the first time these files are being run through the redaction/restoration process, there will be some misc yaml formatting changes that happen the first time this is executed, which will result is a larger-than-normal sync diff.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by hacodeorg — APPROVED** [review]
Took me a while to get familiar with the redaction and restoration step again. The examples at https://github.com/code-dot-org/redactable-markdown are great. Any ideas on how we can test this?

**Comment by Hamms** [comment]
testing of our i18n sync scripts in general, you mean? Or is there some particular piece of this logic that you're interested in?

**Comment by hacodeorg** [comment]
> testing of our i18n sync scripts in general, you mean? Or is there some particular piece of this logic that you're interested in?

I'm interested in testing the redact-restore logic in the i18n pipeline. If I have to make change to that logic, I don't know how I would test it.

**Comment by Hamms** [comment]
The core redaction and restoration functionality lives in https://github.com/code-dot-org/remark-redactable, and the scripts which make it easier to execute from the command line live in https://github.com/code-dot-org/redactable-markdown; both repositories contain tests

**Pull request merged**
