### PR TITLE
Fix violations of and reenable rubocop Style/MultipleComparison.

### PR DESCRIPTION
**Pull request by asherkach**

### CODE REVIEW

**Comment by asherkach** [comment]
CC @aoby for review.

Note that the cop failed to catch the `elsif` branch in `bin/oneoff/move_census_data.rb`, am filing an issue for this.

**Comment by asherkach** [comment]
Ah, trying to create a minimal reproduction, the cop ignored the `elsif` because of the `nil?` check. Not sure what desired behavior should be, as a result.

**Comment by aoby** [comment]
That still does seem like a linter bug, right? nil is a valid value we can check against, and it works in the `[].include?` syntax. I wouldn't expect it to be exempt from this rule.

**Comment by asherkach** [comment]
Mostly? But if someone overloaded `nil?`, then checking `nil?` and comparing to `nil` could be different. Planning on filing an issue, I'm just wanting to think it through before doing so.

Also the cop could fire anyway if only some of the disjuncts were equality comparison, e.g., it could still trigger on `x == 1 || x == 2 || foo(x)`.

**Comment by aoby** [comment]
Good point. I was thinking `== nil`, but you're right `nil?` is different. And agreed, even if it ignores `nil?` that shouldn't invalidate the rest of the comparisons.

**Pull request merged**
