### PR TITLE
Re-enable data browser auth checks and corresponding test.

### PR DESCRIPTION
**Pull request by davidsbailey**
I've extended EditCspTest to include a positive test case for loading edit-csp-*/ paths. 

This fixes the issue that prevented people from accessing the data browser in classrooms. The difference is that paths beginning with `/v3` receive the `storage_id` cookie which we use to grant access to the owner of the app.

### CODE REVIEW

**Comment by islemaster** [comment]
LGTM!

**Comment by davidsbailey** [comment]
@wjordan will can you review the varnish config change I've just added?

**Comment by wjordan** [comment]
Just so I understand clearly, this varnish configuration change is intended to whitelist the `storage_id` cookie so that channels-api authentication works correctly for these routes, is this correct?

If so this extra path whitelist would work, but I'd like to consider alternatives that don't involve adding extra special-cases to the Varnish config. Is there a reason these API paths can't live within the `/v3` namespace where the rest of the storage-API communication takes place?

I'd like to keep the number of different cookie-whitelisting paths in our http-cache config as low as possible- beyond keeping things simple, CloudFront has a fixed limit on the number of different cookie-whitelisting path-exceptions (cache behaviors) it supports (currently [25](http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_cloudfront)), and we're getting dangerously close to that already (22).

**Comment by wjordan** [comment]
the Varnish change LGTM but I wanted to note that it will need to be refactored soon, no problem if that refactoring happens after this PR makes it in for now.

**Comment by davidsbailey** [comment]
Hi Will, you are correct, the config change is to allow the `storage_id` cookie so we can restrict access to `edit-csp-*` pages to the App Lab app owner.

@sfilman , any objections to adding the `/v3/` prefix to these pages (e.g. `/v3/edit-csp-app/<channel-id>`)? These are temporary URLs which will go away when we move this functionality to within the App Lab UI anyway.

**Comment by davidsbailey** [comment]
I've added the `v3/`path prefix. @islemaster can you please take another look?

**Comment by islemaster** [comment]
:eyes: Looking.

**Comment by islemaster** [comment]
Sweet!  LGTM.

**Comment by davidsbailey** [comment]
FYI @trevorb

**Pull request merged**
