### PR TITLE
Make DashboardStudent#update_if_allowed respect deleted sections.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Given that `SectionApiHelperTest` now extends `SequelTestCase`, I don't understand why the update in `update_students: update if allowed` is polluting the DB. Do you have any understanding? What needs to be done to fix?

**Comment by Bjvanminnen** [comment]
This is rather outside my area of expertise. Is it possible that it has problems with the nested describes?

**Comment by ashercodeorg** [comment]
Adding @aoby, who added `SequelTestCase`, for possible advice...

**Comment by aoby** [comment]
I don't know. We might not be doing the transaction correctly to handle nested describes? I based the `SequelTestCase` off of this page: http://sequel.jeremyevans.net/rdoc/files/doc/testing_rdoc.html. I'd look into that and MiniTest's `describe`

**Comment by ashercodeorg** [comment]
Messed around a bit, couldn't make it work. For now, adding a TODO. As the failing (commented) test does not test the functionality changed by this PR and as there are more tests than there used to be, I'm not interested in gating merging this PR on resolving the TODO. PTAL.

**Pull request merged**
