### PR TITLE
Higher Quality CSA Neighborhood Sprites

### PR DESCRIPTION
**Pull request by moneppo**
Screen Shot 2021-10-21 at 3 52 41 PM
Screen Shot 2021-10-21 at 3 52 14 PM

This PR updates the neighborhood sprites to a higher resolution (80x80 tiles) and rearranges them to ensure that adjacent tiles have matching colors to reduce the seam artifacts seen by the previous tile sets.

- [ ] Tests provide adequate coverage
- [X] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [X] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by jmkulwik — COMMENTED** [review]
Can you share some screenshots of the updated sprites in the PR description? To test this out, I'd  recommend just displaying all the sprites across a few levels - they don't need to be published, just hand-tested. Let me know if you'd like a hand making that happen.

**Comment by moneppo** [comment]
Awesome - that's what I did to verify my work in the first place. I added the results in screenshots above!

**Review by jmkulwik — APPROVED** [review]
Nice! Thanks for doing this!

**Comment by bencodeorg** [comment]
I restored this to get #44039 across the finish line, deleting now.

**Pull request merged**
