### PR TITLE
Add CSP 2020 to ScriptConstants

### PR DESCRIPTION
**Pull request by uponthesun**
## Links

- [jira](https://codedotorg.atlassian.net/browse/LP-1324)

## Testing story

Manual sanity check:
```
[development] dashboard > csp_2020_scripts = Script.all.select {|s| s.pilot_experiment == 'csp-2020-access'}}
[development] dashboard > csp_2020_script_names = csp_2020_scripts.map {|s| s.name}
=> ["csp1-2020", "csp10-2020", "csp2-2020", "csp3-2020", "csp4-2020", "csp5-2020", "csp6-2020", "csp7-2020", "csp8-2020", "csp9-2020"]
[development] dashboard > require 'set'
=> false
[development] dashboard > Set.new(csp_2020_script_names) == Set.new(ScriptConstants::CATEGORIES[:csp_2020])
=> true
```

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by davidsbailey — COMMENTED** [review]
Hey @uponthesun , can you remind us why adding these is still necessary? It would help to understand what work is left to do before we do not need these constants any more.

**Comment by uponthesun** [comment]
@davidsbailey Oh, were these only used in TTS levels? I think I'd heard that at some point but was worried that I misremembered. I'll do a bit more searching, but maybe they aren't needed and I can remove the existing ones instead.

**Comment by uponthesun** [comment]
@davidsbailey from some grepping it seems most of the individual constants aren't used by name, but `ScriptConstants.script_in_category?` has a lot of uses: 

image

It also seems like we use the CATEGORIES constant heavily in `assignable_info`: https://github.com/code-dot-org/code-dot-org/blob/f325137be4b3ebc0505b4e2b213cc32ff530d8f6/lib/cdo/script_constants.rb#L323

Which I think controls what's visible in various dropdowns?

**Comment by davidsbailey** [comment]
Good point, I think we could eliminate some of the uses of `ScriptConstants.script_in_category?`, but I had forgotten that `ScriptConstants::CATEGORIES` is used at the top level to control what we show in the `AssignmentSelector` component.

From your screenshot, `has_congrats_page?` looks like something we'll have to manually update each year. As part of the curriculum launch work, but in a different PR, would you be willing to change that to call `script.csf?` instead of checking the CSF categories? https://github.com/code-dot-org/code-dot-org/blob/587871be01b7688419a72ef1d8c713d86ec4ee36/dashboard/app/models/script.rb#L701-L703 You'll still need to check the `csf_international` category, but since that doesn't change each year, it shouldn't require any code updates during soft/hard launch.

While it would be nice to replace `ScriptConstants::i18n?` with a per-script flag, that doesn't block curriculum launch so I don't think we need to pick it up now.

**Comment by uponthesun** [comment]
> As part of the curriculum launch work, but in a different PR, would you be willing to change that to call `script.csf?` instead of checking the CSF categories?

Per discussion in https://codedotorg.atlassian.net/browse/LP-442, the longer-term fix will require a little more work, so I went with the short-term change again: https://github.com/code-dot-org/code-dot-org/pull/33924

**Review by davidsbailey — APPROVED** [review]

**Pull request merged**
