### PR TITLE
build shared as part of rake build

### PR DESCRIPTION
**Pull request by Bjvanminnen**

### CODE REVIEW

**Comment by laurelfan** [comment]
lgtm :+1:

**Comment by davidsbailey** [comment]
To be consistent, I think you should also add an entry to deployment.rb for build_shared_js

**Comment by Bjvanminnen** [comment]
What do you think about making the default true, since shared build is much quicker than apps

**Comment by davidsbailey** [comment]
default true sounds good. LGTM

**Comment by davidsbailey** [comment]
I guess the question then would be, why we have the option of use_my_shared_js, instead of just always building and using it?

**Comment by Bjvanminnen** [comment]
I can see that argument.

However, I personally never run rake build from the root. If we made use_my_shared_js the default, I would need to either start running rake build, or remember to manually build shared/js

**Comment by Bjvanminnen** [comment]
I guess theres some weirdness now that by default we'll build your shared js, but not use the built version.

**Comment by davidsbailey** [comment]
good point. seems ok to build but not use for that reason.

**Pull request merged**
