### PR TITLE
Update style guidelines

### PR DESCRIPTION
**Pull request by megcrenshaw**
After working on the [Curriculum Catalog Card](https://github.com/code-dot-org/code-dot-org/pull/50859) and doing styling for the first time in a while, I learned some new patterns we're trying to follow! This updates our style guidelines to reflect these new patterns.

UPDATE: The norm to use modules over CSS-in-JS originated in the approved [Technical Proposal](https://docs.google.com/document/d/1Y3uK_iYMhTUaCI6yIDwOAMprIJCuzXSs2fECQggwp60/edit#) that Maddie brought to the team to deprecate Radium, and part of that work involved using modules instead of CSS-in-JS. So when the summer swarm group did work to deprecate Radium, some inline styles were moved to modules. There are a few helpful comments in that doc that point to some reasoning around why we went this way.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by megcrenshaw** [comment]
Kelby, feel free to tag other folks you think should review this! This doc doesn't get updated much, so it's hard to tell who "should" be seeing it.

**Review by kelbyhawn — APPROVED** [review]
Looks good, thanks for updating this! 🎉 

Once the rebrand phases are complete we can update this further, but that's an in-the-future thing for sure.

**Comment by kelbyhawn** [comment]
@rshipp and @sanchitmalhotra126 I tagged y'all to take a look too since we've been talking about semantic vs. stylistic headers (these updates in particular aren't directly related, but this is a good place to add our solution to in the future).

**Review by sanchitmalhotra126 — APPROVED** [review]
Thanks for updating this! This was definitely due for a refresh (and I'm now seeing some other things we should probably update at some point too, such as using jQuery and how to export from JS files...)

**Pull request merged**
