### PR TITLE
Fully remove hidden from script

### PR DESCRIPTION
**Pull request by dmcavoy**
Part of the work to move off hidden/visible/is_stable onto published_state.

We already moved off of is_stable for both unit_group and script. We moved of visible for unit_group and stopped using hidden for script. Previous PR made it so hidden can be null on script.

This transitions us off using hidden for anything.

Many of the files in this PR are script and script_json files where I remove hidden. Filtering those out should make reviewing much easier

## Links

https://codedotorg.atlassian.net/browse/PLAT-1059

## Testing story

Update existing tests

## Follow-up work

- Remove hidden column: https://github.com/code-dot-org/code-dot-org/pull/41288

### CODE REVIEW

**Comment by davidsbailey** [comment]
Sorry to drag this out, but this seems like way too much code churn for a PR containing a migration. I would recommend:
1. make the column nullable (migration 1)
2. this PR, without migration
3. remove the column (migration 2)

**Comment by dmcavoy** [comment]
> Sorry to drag this out, but this seems like way too much code churn for a PR containing a migration. I would recommend:
> 
> 1. make the column nullable (migration 1)
> 2. this PR, without migration
> 3. remove the column (migration 2)

OK I will update.

**Review by davidsbailey — APPROVED** [review]
thanks for updating!

**Comment by dmcavoy** [comment]
Ok all set and updated. Just waiting for drone runs to pass before rebasing branches.

**Pull request merged**
