### PR TITLE
Disables the diversity survey.

### PR DESCRIPTION
**Pull request by ashercodeorg**
In doing so, also significantly refactors the logic in show_survey?.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
IMO, a bunch of early exits is much easier to read and modify than repeated nested conditionals. Feel welcome to disagree.

Also, I don't understand the country code RD. Is there a reason not to ignore country_code in non-production environments (as I did)?  EDIT: Reverted.

**Comment by breville** [comment]
I've seen both approaches work, but am fine with this change.

I took the country code RD technique from https://github.com/code-dot-org/code-dot-org/blob/13049e7c661f183deec9b0565d395dafeb545ca9/dashboard/app/helpers/levels_helper.rb#L323.

One advantage I can see of having it there is to somewhat test the request.location behaviour before it gets to production, even if it is slightly different.  I haven't gone backwards through history far enough to work out who first added this, but it was possibly @wjordan ?

**Comment by ashercodeorg** [comment]
PTAL.

**Comment by breville** [comment]
lgtm

**Comment by ashercodeorg** [comment]
CC @tanyaparker

**Pull request merged**
