### PR TITLE
Move NCES data load scripts to separate folder

### PR DESCRIPTION
**Pull request by jopolsky**
Now that I've had a bit of time to understand the NCES data files and load process. I wanted to move the scripts to a separate folder and separate the logic by year.

### CODE REVIEW

**Comment by jopolsky** [comment]
Well, the process year-over-year, now, will be to,
1) upload the new data files to the S3 bucket `nces-data`
2) create a new data load script for the specific data file, because column names and formats change yoy
3) run the script to load the new data, generate a new TSV to be checked in to git (this process needs to be refined still but it's still a step forward from what we had)

I figured because the scripts were moved to a separate folder `nces_data`, then we could omit the verbage as prefix. The file format I was going for was `<table_name>_<school_year_range>_<school_directory_type>`

Where the school directory is either:
* `ccd` for the common core data/public or charter, or
* `pss` for the private school surveys.

If you have suggestions to better organize, I'd love the input. I did initially just clob all the imports together, but that's because we were a bit behind on loading the data. From this point on, we should be loading the data files incrementally.

**Comment by aoby** [comment]
The `nces_data` directory name implies to me that it contains just data, when in fact it contains scripts to import the data (which is stored elsewhere on S3). I get not wanting to repeat yourself, so what about then renaming the `nces_data` directory so it's more clear that it contains scripts?

**Comment by aoby** [comment]
Also it might be worth adding a small README.md file in that directory explaining the usage and that file name format (which I like)

**Comment by jopolsky** [comment]
README.md is a good idea. Let me update.

**Pull request merged**
