### PR TITLE
Reorder Game Lab blocks by frequency of use

### PR DESCRIPTION
**Pull request by mrjoshida**
Reordering Game Lab blocks to insure that more blocks more frequently used in the curriculum show up earlier.

### CODE REVIEW

**Comment by caleybrock** [comment]
Have you tested this? It's possible you also have to change the order here: https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/gamelab/dropletConfig.js#L41

I can pull down this branch and test once all this nav launch is complete.

**Comment by mrjoshida** [comment]
Haven't tested it, my local build is borked :/ No rush

**Comment by caleybrock** [comment]
alright tested it out and this doesn't change the order. I think it's a droplet config change. 
Staging is closed for a couple of days though, so not going to rush this.

**Comment by caleybrock** [comment]
Tested this out and it didn't work, had to update it in one more place. 👍 on the change from me since we're adding the same lines we're removing, but since I did some of this work I'm going to get someone else to review too.

**Pull request merged**
