### PR TITLE
Fix typo (s/warning/warn).

### PR DESCRIPTION
**Pull request by ashercodeorg**
Attempting to fix an error reported by HoneyBadger: https://app.honeybadger.io/projects/3240/faults/30249185.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Is it a bad thing we are seeing this code path executed? Does additional work need to be done as a result of this?

**Comment by mehalshah** [comment]
@aoby to comment on Asher's question

**Comment by mehalshah** [comment]
So I'm curious to know why we have workshop attendees with no emails. I can think of the following possible reasons

1) Attendees signing up as students mistakenly
2) Attendees using some auth system that doesn't necessarily have email. It is possible to sign up for FB without an email address. What would happen if I signed up using facebook auth as a teacher?

**Comment by aoby** [comment]
Thanks @ashercodeorg. Oops, yeah that should have been `.warn`. 

This is a known issue that unfortunately happens a lot. We are working on fixing this on multiple fronts, from Brendan's signup dialog improvements (making student/teacher more clear) to automatically [converting](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/pd/workshop.rb#L213-L215) to teacher accounts and filling in the email when we have a matching workshop enrollment. We may even require teacher accounts in order to join these sections and divert to a page explaining that when students attempt to join.

@mehalshah #1, teachers signing up as students, is very common. Many attendees are also enrolled so we have their email and can fix it. However certain school districts specifically don't want their teachers to enroll (presumably because they handle that separately) and require that we allow them to just show up and join the section. We don't have emails for these, and are working on the above mitigations.

#2 is an interesting point. I didn't realize we could have a teacher account with no email. We'll have to handle that as well.

**Comment by ashercodeorg** [comment]
Re # 2, until the submission of PR#8863, it was possible to generate a teacher account without a plaintext email by creating a student account (with no plaintext email) and changing the account type (through the `Edit Account` UI). This should no longer be possible, except by manually bypassing `User` validations.

**Comment by ashercodeorg** [comment]
Though it sounds like there may be followup work, I am taking this PR as to be LGTM'ed, so am merging.

**Pull request merged**
