### PR TITLE
Change ID to string in schools

### PR DESCRIPTION
**Pull request by jopolsky**
Initial PR to kick off circle tests for the proposed change.

### CODE REVIEW

**Comment by jopolsky** [comment]
Lots of tests failing with:
`TypeError: no implicit conversion of Fixnum into String...`

Updating the PR with the factory fix shortly.

**Comment by wjordan** [comment]
Looks like we have some [factories](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/test/factories/factories.rb#L710-L730) for creating `School` model objects that assume `id` is an integer, and use `id {School.maximum(:id) + 1}` for assigning a primary-key ID, which will need to change to reflect the updated model.

**Comment by jopolsky** [comment]
Another interesting side-effect, the schools loaded from the raw NCES data files have zero padding.
```
-[{"nces_id"=>"20000100207", "name"=>"Gladys Jung Elementary", "city"=>"Bethel", "state"=>"AK", "zip"=>"99559"}]
+[{"nces_id"=>"020000100207", "name"=>"Gladys Jung Elementary", "city"=>"Bethel", "state"=>"AK", "zip"=>"99559"}]
```

From test fixture data,
https://github.com/code-dot-org/code-dot-org/blob/c2f21c44a1d3f72ee426c128696631dedb2828d2/dashboard/test/fixtures/schools.tsv

The file layout from the NCES website indicates the data type as being char of length 12.
https://nces.ed.gov/ccd/xls/2015-16_CCD_Companion_SCH_Directory.xlsx

This won't impact the data that is currently in the DB, but would impact the data that we load from data files for the new school years.

**Comment by jopolsky** [comment]
Tests have passed however, I'm going to run the full test suite locally:
`RAILS_ENV=test bundle exec rake test:all`

**Comment by jopolsky** [comment]
Wasn't able to run the test locally, trying:
`git commit --allow-empty -m "Run all tests [test all]"`

**Comment by jopolsky** [comment]
@wjordan feel free to take a look at this PR.

**Pull request merged**
