### PR TITLE
Origin/staging

### PR DESCRIPTION
**Pull request by WilliamHarmonMS**
Made changes to avoid unwanted whitespace character in block text

### CODE REVIEW

**Comment by joshlory** [comment]
I think you ended up with an extra commit in this PR!

**Comment by WilliamHarmonMS** [comment]
So it appears. That was unintentional. The aoby PR (#15431) is something I'm not familiar with. That might have been a previous Dev since before I began? No idea how it got grouped in with mine (#15570). Is there a way to separate mine out, and stash #15431? I can inquire with my lead here and see if that color change is still something we wanted to go forward with?

**Comment by joshlory** [comment]
Two possible options:
1. Create a new branch and `git cherry-pick 71064308da9cdcbbaa8d76731ebf3f92a9d204c1` on that branch (easiest).
2. Use [`git rebase --interactive`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) to remove the extra commit.

**Comment by WilliamHarmonMS** [comment]
Hey Josh,

I got some git aid here and I’ve added another pull request as well. I -think- I’ve got the hang of your process, though I will say the advice I was getting was from someone unfamiliar with forked repos. If anything else comes up to hesitate to let me know what’s wrong.

~William

**Comment by joshlory** [comment]
I think these changes are captured by PR https://github.com/code-dot-org/code-dot-org/pull/15589 and PR https://github.com/code-dot-org/code-dot-org/pull/15590 (both merged to staging).  I'm going to go ahead and close out this PR.

**Pull request closed without merging**
