### PR TITLE
Put the save button in a fixed position on script and lesson edit pages

### PR DESCRIPTION
**Pull request by dmcavoy**
Lesson Edit:
Screen Shot 2020-10-19 at 9 01 33 PM

Script Edit:

Screen Shot 2020-10-19 at 9 02 04 PM

## Links

- [spec](https://docs.google.com/document/d/1iVH3ZuFCafc_DGKVlg8k_51kzEtSU5I-QzDieAyW7Mo/edit?ts=5f8e3063#)
- [jira](https://codedotorg.atlassian.net/browse/PLAT-405)

## Testing story

Tested out saving with the button locally.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
Code changes look good. Let's ship it!

For UX the horizontal gray bar does a great job of drawing your eye to the save button -- without it, I might not notice the save button until I scrolled the page. It's a little funky that the gray bar covers part of the footer, but since this is internal-facing and doesn't interfere with any functionality I don't think that will be a problem. Let's see how folks like it and then decide what to do about the footer. The other option I can think of would be to put the save bar inside the footer, which I imagine would lead to a double-scrolling situation.

I tried this out on the existing "legacy" script edit page and I'm betting this will be immediately popular with the curriculum team. It could be worthwhile to notify them so they know this is an expected change.

**Review by bethanyaconnor — APPROVED** [review]
:shipit:

**Comment by dmcavoy** [comment]
@davidsbailey Do we need the footer on editor pages? Could it be removed or moved to the gray bar using the small footer we use on App Lab and other IDE pages?

**Comment by davidsbailey** [comment]
@dmcavoy I think it would be ok to show the smaller footer you are talking about. Removing it entirely also sounds promising, but I think we might need to check with someone first whether that is ok.

**Comment by dmcavoy** [comment]
@davidsbailey Followed up with Tess and she is going to look into what to do about the footer.

**Pull request merged**
