### PR TITLE
automatically commit and push changes to apps strings

### PR DESCRIPTION
**Pull request by tanyaparker**

### CODE REVIEW

**Comment by tanyaparker** [comment]
This script is run as part of rake build:apps. It's ok to push right after right? It'll just build again after the current staging build.

**Comment by tanyaparker** [comment]
Will, just wanted to confirm with you before merging in.

**Comment by wjordan** [comment]
The code itself looks good to me (not too worried, since this script is part of a manual process anyway). Could you do a quick documentation pass while we're updating this?

- Add a description to the sync script below the `#!` line, e.g.:
```
# Run this script to manually synchronize apps translations with Crowdin.
# See /i18n/README.md for instructions.
```

- Update the README.md to reflect the changes (step `3. Commit all .json files` should no longer be needed, correct?)

**Comment by tanyaparker** [comment]
Thanks, Will! Updated and merged.

**Pull request merged**
