### PR TITLE
Fixes violations of and reenables the rubocop Style/ClassAndModuleCamelCase check.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by islemaster** [comment]
LGTM.

**Comment by ashercodeorg** [comment]
Brad: Though my assumption had been the underscore was a typo, it seems not to be, as the ci/circleci failure is legitimate. **test/test_file.rb:4:in `<main>': FileTest is not a class (TypeError)** Presumably, this is because FileTest is a ruby module (see, e.g., http://ruby-doc.org/core-2.2.3/FileTest.html).

Given that File is also a ruby class (see, e.g., http://ruby-doc.org/core-2.2.0/File.html), I'm choosing to rename File to FileUtility. Let me know if you disagree with this approach.

**Comment by islemaster** [comment]
I'm fine with the rename, but it looks like you missed something per the new test error:

```
LoadError: cannot load such file -- [CDO]/lib/cdo/pegasus/file
```

**Comment by ashercodeorg** [comment]
Test fixed. LGTY?

**Comment by islemaster** [comment]
Lovely.  LGTM!

**Pull request merged**
