### PR TITLE
Remove unused LabeledFormComponent

### PR DESCRIPTION
**Pull request by TurnerRiley**
While refactoring the storybook for `/form_components/LabeledFormComponent.jsx`, I realized that we don't actually use this file anywhere in our site. We instead use the `/form_components_func/LabeledFormComponent.jsx` file (such as in our [Teacher Application](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/code-studio/pd/application/teacher/AboutYou.jsx#L11)). So, I think it's not only safe to delete the storybook file, but also the main file of this unused component.

## Links
Jira ticket: [here](https://codedotorg.atlassian.net/jira/software/c/projects/ACQ/boards/64?assignee=60d62161f65054006980bd71&selectedIssue=ACQ-1430)
Storybook spreadsheet: [here](https://docs.google.com/spreadsheets/d/1z8r10AcR0v3GimV_-28dJ6QaiaQ3CJoo9yXqa7U_bKs/edit#gid=0)

### CODE REVIEW

**Review by kelbyhawn — COMMENTED** [review]
Out of curiosity, how did you figure out we weren't using this version of `LabeledFormComponent`?

**Comment by TurnerRiley** [comment]
> Out of curiosity, how did you figure out we weren't using this version of `LabeledFormComponent`?

I just searched `LabeledFormComponent` in our codebase and the only places it popped up were for imports from the `form_components_func` directory.

**Review by hannahbergam — COMMENTED** [review]
I did a similar search and this seems right to me. Do we have a test file for the other component anywhere? I would hope that we'd have enough test coverage for a build to fail if we removed a 'still used' component

**Comment by TurnerRiley** [comment]
> I did a similar search and this seems right to me. Do we have a test file for the other component anywhere? I would hope that we'd have enough test coverage for a build to fail if we removed a 'still used' component

Yes the Teacher Application has eyes tests so if removing this breaks the other use of `LabeledFormComponent` it will be clear!

**Review by hannahbergam — APPROVED** [review]
Yay!! LGTM!

**Pull request merged**
