### PR TITLE
removed integrity

### PR DESCRIPTION
**Pull request by kimj42**
Integrities were added in this PR: https://github.com/code-dot-org/code-dot-org/blame/b2e9fa96a3212709ffb7256f49449f8687b43392/apps/yarn.lock#L5332

^ PR was causing any `yarn add ...` to create a big diff to integrity lines in yarn.lock.

This PR removes those integrity lines.

### CODE REVIEW

**Comment by joshlory** [comment]
Hmm, it looks like this diff also changed the minor versions of a lot of dependencies? How'd you generate the diff?

**Review by joshlory — CHANGES_REQUESTED** [review]
It looks like maybe you deleted yarn.lock and regenerated it, which will lose the locked versions we care about.

**Comment by epeach** [comment]
Ahh, that was my bad. We couldn't figure out how to trigger the yarn.lock to be rebuilt. What's the best way to force a re-build without deleting?

**Comment by joshlory** [comment]
I'm not 100% sure — I ended up doing `yarn add aws-sdk`, then reverting the package.json changes and running yarn again. Because we ask for a specific version of that package the end result seemed to be only the diff we want.

Surprised that our CI build didn't notice the unexpected diff in yarn.lock. Maybe the same reason that running `yarn` alone won't remove the integrity fields.

**Pull request closed without merging**
