### PR TITLE
Temporary App Lab Audio Fix

### PR DESCRIPTION
**Pull request by islemaster**
Don't force HTML5 Audio in App Lab's `playSound()` command.

Temporary workaround for Pivotal items [#108279582](https://www.pivotaltracker.com/story/show/108279582) and [#108115812](https://www.pivotaltracker.com/story/show/108115812) and affects [#100382204](https://www.pivotaltracker.com/story/show/100382204).
## Root cause

We are currently forcing the App Lab `playSound()` command to use HTML5 audio instead of Web Audio, even on platforms that support Web Audio.  Some browsers (definitely Chrome) send a header `Range:bytes=0-` when using HTML5 audio to indicate that they want the entire file.  Unfortunately, there's a [bug in Varnish 4.0](https://www.varnish-cache.org/trac/ticket/1643) that does not handle this header correctly and results in a truncated MP3 being returned, or `Error 416 Requested Range Not Satisfiable`.

This workaround changes `playSound()` to use Web Audio if it is available.  Eventually we will update to Varnish 4.1 which contains a fix for the root cause, but this update is considered too risky right now since Hour of Code is around the corner.  When we do that update, we should probably go back to forcing HTML5 Audio in `playSound()`.
## Side effects

The cited reason for using HTML5 audio in the [commit that introduced the change](https://github.com/code-dot-org/code-dot-org/commit/7afa67486958e4451d6050182f2dcb6926a33680) is to allow cross-site URLs in `playSound`, so this workaround is likely to break any existing apps that hotlink to offsite audio.  Audio uploaded through our Assets API is served from code.org and works fine.

Internet Explorer does not support Web Audio, so changing `forceHTML5` has no effect there.  Fortunately, it looks like IE doesn't send the header that triggers the bug, so it's working fine anyway.

HTML5 audio in Chrome would not allow a sound to be played twice simultaneously (since each URL mapped to a single `<audio>` element).  Web Audio does.  To make behavior consistent across the two systems, I've explicitly made `playSound` a no-op if the requested sound URL is already playing.  It may not be the final behavior we want, but it's most consistent with the behavior prior to this change.
## Testing

Since the Varnish bug only occurs in production (where we have Varnish enabled) I tested this approach by loading a test app on production, interrupting the `playSound()` call in the debugger to manually disable the `forceHTML5` flag, then confirming both that the sound played back correctly, and that the `Range` header was not included in the request to the assets API.

I also checked my complete change (with the fix to prevent overlapping playback of a single sound) against a local build using:
- Chrome 46 Ubuntu 15.10
- Firefox 42 Ubuntu 15.10
- Internet Explorer 11 Windows 7 _Works even though HTML5 audio is being used_
- Safari Mobile iOS 9 via Browserstack
- Chrome 46 Android 4.4.4
- Firefox 42 Android 4.4.4 _Audio did NOT work, but was broken in other ways too - this is not on our supported browser list._

### CODE REVIEW

**Comment by islemaster** [comment]
Assigned to Brent because he's here today.

FYI @philbogle @wjordan @davidsbailey  - this is a temporary workaround for the Varnish 4.0 Range header bug with regard to App Lab audio.

**Comment by Bjvanminnen** [comment]
lgtm

**Comment by islemaster** [comment]
cc @cpirich since you originally enabled forcing HTML5 audio in App Lab to allow cross-site URLs.

**Comment by wjordan** [comment]
For future reference- the varnish infrastructure should be identical across
all non-development environments so this could be tested outside of
production as well.

**Pull request merged**
