### PR TITLE
Add escape keydown handle to close function editor

### PR DESCRIPTION
**Pull request by rvarshney**
/review @bcjordan @tanyaparker

### CODE REVIEW

**Comment by tanyaparker** [comment]
@bcjordan CLA has been received. Thanks, Ruchi!

**Comment by bcjordan** [comment]
Looks good to me, thanks @rvarshney!

**Comment by islemaster** [comment]
Awesome, thanks for contributing!

**Comment by alicesteinglass** [comment]
Thanks for doing this! Definitely feels natural to hit ESC here.

**Comment by aoby** [comment]
Thanks for contributing! This is a nice improvement.

**Comment by rvarshney** [comment]
Awesome, glad I could help! Thanks for fixing this up Brian!

**Comment by hadipartovi** [comment]
Thank you for helping us @rvarshney  :-)

**Pull request merged**
