### PR TITLE
PL: Remove Plc::EnrollmentModuleAssignment model

### PR DESCRIPTION
**Pull request by breville**

### CODE REVIEW

**Comment by breville** [comment]
I no longer have context on this work, but tagged PLC as reviewers in case anybody there wanted to pick it up, if it's still applicable.

**Comment by bencodeorg** [comment]
Here's a related Jira ticket:

https://codedotorg.atlassian.net/browse/PLC-576

**Comment by bencodeorg** [comment]
Thanks for sharing Brendan! Good timing, we were just talking yesterday about how we might be able to simplify/remove some (all?) of the PLC curriculum hierarchy, finishing this up might be a good place to start. @tess323 FYI

@breville -- do you have any recollection of why this didn't end up getting merged?

**Comment by breville** [comment]
@bencodeorg I remember we discussed it a bunch but I've not found a concise explanation in the archives.  I feel like we might have found a dependency that had to be removed first, but don't remember specifically what it was.

**Comment by breville** [comment]
Closing this out since it's quite old.

**Pull request closed without merging**
