### PR TITLE
update list of courses to show banner

### PR DESCRIPTION
**Pull request by tanyaparker**

### CODE REVIEW

**Comment by laurelfan** [comment]
The files were renamed from .jpg to .png? were they actually pngs?

**Comment by tanyaparker** [comment]
I converted them. Is it better to keep as original and modify the function to accept any extension?

**Comment by laurelfan** [comment]
if you look at it in github it says "renamed without changes". it looks fine in my browser but when I download the file it actually is a jpg... I suspect this may not work in all browsers.

**Comment by laurelfan** [comment]
lgtm!

**Pull request merged**
