### PR TITLE
Change create to not move_for_same_teacher.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
The CircleCI failure does not reproduce for me locally.

That said, I'm uncertain (not knowing desired [test] behavior) whether the same change should be made [here](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/test/lib/pd/payment/payment_calculator_csf_test.rb#L71). @oaby?

**Comment by aoby** [comment]
Strange. It shouldn't matter there because that's the only section that user is a member of (it's created 2 lines above). It won't hurt, but also won't fix anything. 

Judging by the user Ids, it looks like that test failure is returning the `@unqualified_teacher` which makes even less sense and is irrelevant to that particular test case. Have you tried re-running it? I don't feel great about dismissing this without understanding it, but if it simply doesn't repro anywhere then that might be reasonable.

**Comment by aoby** [comment]
This changed code path inside the workshop attendance controller isn't even touched by the payment calculator tests.

**Comment by ashercodeorg** [comment]
As noted, I couldn't reproduce the failure locally. Rerunning CircleCI now. And I'll add the parameter in the test, though I agree it shouldn't change anything.

**Comment by ashercodeorg** [comment]
Rerunning seems to fix the issue. Going to consider my work done, feel welcome to investigate further if warranted.

**Pull request merged**
