### PR TITLE
Revert #9239: Adds auto-population of the UserGeo model upon sign-in.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This reverts #9239, fixing the issue in #9108.

TESTING: Manually confirmed multiple sign-ins and sign-outs.

Note that this PR does not include a test for multiple sign-ins as I'm still unable to get it working. My attempts at testing via a unit test have been met with failure, e.g., the following with the `SessionsControllerTest` fails to sign in the user the second time for reasons that I don't understand.

```
  test 'users can sign in and out multiple times' do                                 
    # HACK: Since ActionController::TestCase only allows one http method per         
    # test, we reset the controller between each http method.                        
    user = create :user                                                              

    post :create, user: {username: user.username, password: user.password}
    assert :success
    assert_signed_in_as user

    @controller = SessionsController.new
    delete :destroy
    assert :success
    assert_redirected_to '//test.code.org'

    @controller = SessionsController.new                                             
    post :create, user: {username: user.username, password: user.password}
    assert :success
    assert_signed_in_as user  # THIS FAILS

    @controller = SessionsController.new                                             
    delete :destroy
    assert :success
    assert_redirected_to '//test.code.org'                                    
  end
```

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Per offline conversation with @jeremydstone, I'm converting this to write a blank `UserGeo` (if one does not already exist), populating it in a cron job.

**Comment by ashercodeorg** [comment]
PTAL: Updated this PR to reflect the schema change in #9371 and the offline decision to do the geolocation via a cron job.

**Comment by ashercodeorg** [comment]
Ping. PTAL.

**Comment by jeremydstone** [comment]
Updates LGTM

**Pull request merged**
