### PR TITLE
[JIMT][update-dance-party-project-level] - updated blocks

### PR DESCRIPTION
**Pull request by thomasoniii**
3 changes to the `New Dance Lab Project.level` file:

- added `Dancelab_ai` block
- removed `Dancelab_setBackgroundEffectWithPalette` block
- added `Dancelab_setBackgroundEffectWithPaletteAI` block
- removed `Dancelab_atTimestamp` block
- added `Dancelab_atTimestampNotAfter`
- 
## Links

- spec: [HOC TUtorial Șpec 2023](https://docs.google.com/document/d/1bRtbokuZNGnjFr7l8LaG9JwPA-3GDXgRlUNKvCZGe_A/edit#bookmark=id.frj4zqunjvd)
- Trello: [Update Dance Party Project level](https://trello.com/c/iomTs2Ya/73-due-nov-9th-update-dance-party-project-level)

## Testing story

Manually tested with a few projects
- created new projects and saw the new blocks in action.
- confirmed that old projects with the old blocks still worked.
- confirmed that when old blocks are removed from old projects, they cannot be re-added.
- confirmed that new blocks can be added to old projects.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by sanchitmalhotra126 — COMMENTED** [review]
Looks good! Pulled this and manually checked
- creating a new project via /projects/dance/new
- opening an old project from My Projects
- remixing a project

One open question (will ask in Slack) - should the student be able to use blocks in standalone projects? Right now this option is turned off, so they can only use the effect (cannot convert to blocks). If we want to turn on I think we'd have to set `"aiOutput": "both"` on the level properties.

**Comment by fisher-alice** [comment]
> One open question (will ask in Slack) - should the student be able to use blocks in standalone projects? Right now this option is turned off, so they can only use the effect (cannot convert to blocks). If we want to turn on I think we'd have to set `"aiOutput": "both"` on the level properties.

Also, could you could with @samantha-code and see if we should have the static preview in the visualization column? If so, you'll need to set  "uses_preview": "true" on the level properties also.

**Comment by thomasoniii** [comment]
Confirmed with @samantha-code that we want both options enabled, so I flipped 'em both on.

**Review by sanchitmalhotra126 — APPROVED** [review]
🎉

**Pull request merged**
