### PR TITLE
[AITT-516], [AITT-535], [AITT-508], [AITT-514] Ai in teacher tools Rubric Modal visual updates

### PR DESCRIPTION
**Pull request by levadadenys**
### [AITT-516], [AITT-535], [AITT-508], [AITT-514] Ai in teacher tools Rubric Modal visual updates

Don't have the full access to modal so screenshots will only show minor part of total changes implemented.

Before:
image
image

After:
Знімок екрана 2024-03-20 о 19 53 11
Знімок екрана 2024-03-20 о 20 39 25

## Links
- jira ticket: [AITT-516](https://codedotorg.atlassian.net/browse/AITT-516),  [AITT-535](https://codedotorg.atlassian.net/browse/AITT-535),  [AITT-508](https://codedotorg.atlassian.net/browse/AITT-508),  [AITT-514](https://codedotorg.atlassian.net/browse/AITT-514)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by tess323** [comment]
Code looks great to me!  Would be helpful to see a screenshot if low lift

**Review by tess323 — APPROVED** [review]
Looks great to me!

**Comment by bethanyaconnor** [comment]
I'm not sure Acquisitions is the right team to review -- did you mean to tag @code-dot-org/ai-in-teacher-tools for review instead?

**Comment by levadadenys** [comment]
> I'm not sure Acquisitions is the right team to review -- did you mean to tag @code-dot-org/ai-in-teacher-tools for review instead?

Yep, sorry and thanks for heads up! Updated!

**Review by wilkie — APPROVED** [review]
Fired up the branch and took a look with my set of test students. Looks great! Thanks so much!

**Comment by wilkie** [comment]
image

image

**Pull request merged**
