### PR TITLE
Add foreign key linking sections to LTI integrations

### PR DESCRIPTION
**Pull request by carl-codeorg**
Adds a a new FK to the sections table. This is prerequisite work to enable us to sync rosters from LTI platforms into Code.org.

## Links

[Jira ticket
](https://codedotorg.atlassian.net/browse/P20-533)
## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by carl-codeorg** [comment]
Tagging infra in here too since it's a migration involving a big table. Feel free to ignore if it should just be RED

**Comment by Hamms** [comment]
How big is the table exactly? Migrations like this require table locks, which for large tables can be prohibitive

**Comment by Hamms** [comment]
To clarify: migrations for large tables aren't _impossible_, they just require a lot more work. Specifically, we use `gh-ost` to coordinate the creation of a phantom table to which the migration can be applied cleanly, and then the copying over of all existing data to that new table.

See previous efforts at https://github.com/code-dot-org/code-dot-org/tree/8b559323defd6d0480fcc83a3608b5937a65c5a1/bin/oneoff/gh-ost_migrations for more

**Comment by carl-codeorg** [comment]
> How big is the table exactly? Migrations like this require table locks, which for large tables can be prohibitive

Good question. I've reached out to RED on Slack to see if they can provide some stats. I suspect it's pretty big

**Comment by carl-codeorg** [comment]
@Hamms looks to be 4.8M records totaling about 468MB on disk.

Here's a screenshot of what RED was able to pull up
image

Seems to line up with what I got from poking around in production-console:
```
mysql> SELECT table_name AS 'Table', ROUND(data_length / 1024 / 1024, 2) AS 'Table size in MB',
    -> ROUND(index_length / 1024 / 1024, 2) AS 'Index size in MB',
    -> ROUND((data_length + index_length) / 1024 / 1024, 2) AS 'Total size in MB'
    -> FROM information_schema.TABLES
    -> WHERE table_name = 'sections';
+----------+------------------+------------------+------------------+
| Table    | Table size in MB | Index size in MB | Total size in MB |
+----------+------------------+------------------+------------------+
| sections |           443.92 |           190.80 |           634.72 |
+----------+------------------+------------------+------------------+
1 row in set (0.00 sec)
```

```
mysql> SELECT (data_length / COUNT(*)) AS 'Average Record Size in Bytes'
    -> FROM information_schema.TABLES, sections
    -> WHERE table_name = 'sections';
+------------------------------+
| Average Record Size in Bytes |
+------------------------------+
|                      96.0351 |
+------------------------------+
1 row in set (1.09 sec)
```

**Comment by Hamms** [comment]
Fantastic investigation, thank you! Really appreciate the thoroughness.

Unfortunately, based on that I think we can confidently say that this direct approach to adding a column will NOT work. I'd expect any table with number of rows in the millions to take on the order of 20-30 minutes to apply an ALTER to each of those rows, during which time any request that needed to touch the sections table would fail.

I think we're gonna have to `gh-ost` this one.

**Comment by carl-codeorg** [comment]
> I think we're gonna have to `gh-ost` this one.

@Hamms roger that, I'll look into writing up a gh-ost script using the others as examples. Couple questions:
1. Is there a need to account for gh-ost migrations, which happen out of band from the perspective of our Rails app, in our Rails migrations? Or are the gh-ost migrations just holes in our migration history and we rely on the schema being up to date?
2. Does gh-ost magically handle the cutover process when the switch to the new table happens? There must be a time when writes start flowing into the new table, and we have to read from both tables, then the old data gets migrated into the new table, before we can completely cut reads over to the new table.

**Comment by Hamms** [comment]
I'm actually not all that familiar with the details of gh-ost; I think @sureshc knows more, and might be able to answer your questions in greater detail.

For question 1, my expectation is that we'd also write a migration for this, but explicitly scope it to only apply in non-production environments, and then only run gh-ost in production. For question 2, I believe the answer is yes; gh-ost takes care of all the details for us.

**Comment by sureshc** [comment]
This table might be small enough to run this migration without `gh-ost`. We can clone the production database and run a test. Setup 30 minutes on my calendar and I can help with that.

**Review by jordan-springer — APPROVED** [review]
looks good to me-- from our perspective how should we interact with (if at all) the `lti_integration_id`? If that field is not null does that just mean that the data is referencable to the platform activity for that section?... cc @allison-code-dot-org

**Comment by sureshc** [comment]
Here's the documentation for how MySQL 5.7 handles different types of schema changes: https://dev.mysql.com/doc/refman/5.7/en/innodb-online-ddl-operations.html#online-ddl-column-operations

image

MySQL 5.7 will rebuild the table, while concurrently allowing reads and writes to the table. The table is likely small enough (~5M) rows and the throughout of write queries (INSERTs/UPDATEs/DELETEs) to this table is likely low.

Let's run a test to see how long this schema change would take to execute on the production database with ZERO concurrent writes to the table:

1. Clone the production database using the `rds:clone_cluster` rake task
2. Run the migration on a development environment where the raw SQL generated and executed by the migration is logged
3. Execute that raw schema change SQL on the production clone and measure how long it takes.

Also use NewRelic to estimate the write throughput to this table during peak usage. As long as it's relatively low, then we are likely safe to use the built-in features in MySQL 5.7 to rebuild this table "In Place"

**Comment by carl-codeorg** [comment]
Ran the migration on the clone and observed. The add column operation was pretty fast, taking less than a minute:
```
ALTER TABLE `sections` ADD `lti_integration_id` bigint;
Query OK, 0 rows affected (55.14 sec)
Records: 0  Duplicates: 0  Warnings: 0
```
I found this odd because the docs Suresh posted claim that adding a column requires a table rebuild, so I expected this to take longer and affect all rows.

The FK constraint took 15 minutes:
```
mysql> ALTER TABLE `sections` ADD CONSTRAINT `fk_rails_f0d4df9901`
    -> FOREIGN KEY (`lti_integration_id`)
    ->   REFERENCES `lti_integrations` (`id`);
Query OK, 4857335 rows affected (15 min 7.24 sec)
Records: 4857335  Duplicates: 0  Warnings: 0
```
But based on the docs Suresh posted, this operation is done in place without a rebuild:
Screenshot 2023-10-24 at 1 56 41 PM

[Screenshotted some metrics from Cloudwatch](https://docs.google.com/document/d/1HKSwfR-r7slyLU3cKo-CbsdmaWb5OcYYU8wUYkOFAFI/edit). Most of it looked fine, but CPU utilization was near 100% and write latency was high for the duration of the operation. Not sure if this is because the clone is a smaller cluster compared to the real prod cluster.

Screenshot 2023-10-24 at 2 02 17 PM
Screenshot 2023-10-24 at 2 05 38 PM

**Comment by carl-codeorg** [comment]
@sureshc any initial thoughts after seeing the numbers? Still looking for a go/no-go on traditional migration vs gh-ost script.

**Comment by sureshc** [comment]
> Ran the migration on the clone and observed. The add column operation was pretty fast, taking less than a minute:
> 
> ```
> ALTER TABLE `sections` ADD `lti_integration_id` bigint;
> Query OK, 0 rows affected (55.14 sec)
> Records: 0  Duplicates: 0  Warnings: 0
> ```
> 
> I found this odd because the docs Suresh posted claim that adding a column requires a table rebuild, so I expected this to take longer and affect all rows.

1 minute seems about right for a full rebuild of a table with ~5M rows on a relatively low powered database instance (`db.r5.2xlarge`) that had just powered up and doesn't have most of the table cached in memory. I would expect this to complete even more quickly on production (`db.r5.8xlarge`). I think it reports `0 rows affected` because logically no rows were UPDATEd.

While MySQL 5.7 supports concurrent DML (INSERT/UPDATE/DELETE) during the In Place rebuild of the table, the performance and reliability of this depends on the DML throughput on the table. Looking at NewRelic during a peak usage time period shows ~12 writes per minute which is low, so I think we are safe to use a standard MySQL ALTER TABLE to accomplish this change in production.
image

**Review by sureshc — APPROVED** [review]

**Pull request merged**
