### PR TITLE
Add new Daily Zendesk filters

### PR DESCRIPTION
**Pull request by bethanyaconnor**
With the new Zendesk procedures, more teams want the the Daily Zendesk. Josh Schulte gathered requests for a couple weeks and this PR adds all the ones he's collected (so far).

Overall, this was easy to do, but adding a couple of my lessons learned:
- You need the zendesk token out of secrets manager in order to do any interesting tests
- The filters are a bit of a guessing game -- I'm fairly confident on them but not 100% (and I couldn't find a filter for one group)

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dmcavoy** [comment]
Hey @bethanyaconnor could you add Curriculum Platform to this as well?  Thanks!

**Review by breville — APPROVED** [review]
With no prior context, this seems fine :)

**Comment by bethanyaconnor** [comment]
haha most of the prior context left with Brad unfortunately :/

**Comment by bethanyaconnor** [comment]
Related to Dani's request, now that we use a limited number of users, it might be worth looking into searching by user in addition to/instead of group. I want to merge this PR first because it covers most use cases though.

**Pull request merged**
