### PR TITLE
Pull JS out of Fun-O-Meter dashboards HAML files with minor style guide fixes.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Note that I'm grabbing the file naming convention from examples in dashboard/app/views/levels/. Am I copying good or bad examples?

**Comment by Hamms** [comment]
You mean the leading underscore on the haml file? Yeah, I think that's correct.

However, I'm definitely not a fan of the javascript file in views; that should probably go in `dashboard/app/assets`. Perhaps modify the function to accept an argument, then call it in the haml file?

Something like

```
 - content_for :body_scripts do
    :javascript
      var percentagesByDay = #{@ratings_by_day.map{|row| [row[0], row[1].to_f]}.try(:to_json)}
      drawChart(percentagesByDay)
```

**Comment by ashercodeorg** [comment]
My file naming convention was for the JS file, being camelCase rather than under_score.

And I followed your suggestion about how to access the JS method.

Please take another look. Thanks!

**Comment by Hamms** [comment]
Oh! Yeah, I like camelCase for js files.

LGTM!

**Comment by Bjvanminnen** [comment]
For future reference, new JS like this should go in `code-studio` rather than `dashboard/app/assets`

**Comment by ashercodeorg** [comment]
Good to know. Is there a particular subdirectory this file should live in?

**Pull request merged**
