### PR TITLE
Fix violations of and reenable rubocop Rails/RedundantReceiverInWithOptions.

### PR DESCRIPTION
**Pull request by asherkach**

### CODE REVIEW

**Comment by asherkach** [comment]
CC @breville for review.

**Comment by asherkach** [comment]
If I understand everything correctly, this `dashboard-console` session should demonstrate that the validations still operate.
```
irb(main):014:0> c = Census::CensusYourSchool2017v4.new
=> #<Census::CensusYourSchool2017v4 id: nil, type: "Census::CensusYourSchool2017v4", submitter_email_address: nil, submitter_name: nil, submitter_role: nil, school_year: nil, how_many_do_hoc: nil, how_many_after_school: nil, how_many_10_hours: nil, how_many_20_hours: nil, other_classes_under_20_hours: nil, topic_blocks: nil, topic_text: nil, topic_robots: nil, topic_internet: nil, topic_security: nil, topic_data: nil, topic_web_design: nil, topic_game_design: nil, topic_other: nil, topic_other_description: nil, topic_do_not_know: nil, class_frequency: nil, tell_us_more: nil, pledged: nil, created_at: nil, updated_at: nil, share_with_regional_partners: nil>
irb(main):015:0> c.valid?
=> false
irb(main):016:0> c.errors.full_messages
=> ["School infos is required", "Submitter email address does not appear to be a valid e-mail address", "School year is required", "School year is not a number", "Submitter role is required", "How many do hoc is required", "How many after school is required", "How many 10 hours is required", "How many 20 hours is required"]
irb(main):017:0> c.how_many_20_hours = "all"
=> "all"
irb(main):018:0> c.valid?
=> false
irb(main):019:0> c.errors.full_messages
=> ["School infos is required", "Submitter email address does not appear to be a valid e-mail address", "School year is required", "School year is not a number", "Submitter role is required", "How many do hoc is required", "How many after school is required", "How many 10 hours is required", "Topic blocks cannot be nil", "Topic text cannot be nil", "Topic robots cannot be nil", "Topic internet cannot be nil", "Topic security cannot be nil", "Topic data cannot be nil", "Topic web design cannot be nil", "Topic game design cannot be nil", "Topic other cannot be nil", "Topic do not know cannot be nil", "Class frequency is required"]
```

**Comment by asherkach** [comment]
Note that you'll need to run CircleCI and merge on my behalf.

**Comment by breville** [comment]
Circle passed in https://circleci.com/gh/code-dot-org/code-dot-org/58865

**Pull request merged**
