### PR TITLE
deflake Pd::SessionAttendanceControllerTest, and run all dashboard tests in UTC

### PR DESCRIPTION
**Pull request by davidsbailey**
in this problematic test, it looks like there is a discrepancy between the current date when the workshop is created in setup_all, and when other things are created during test cases. the following commands were run on my local machine between 5 and 6pm Pacific Standard Time. both test runs passed.

after the first commit:
```
bundle exec spring testunit ./test/controllers/pd/session_attendance_controller_test.rb --name test_attend_too_late_renders_too_late_view
setup_all run at 2021-12-01 17:23:19 -0800
test case run at 2021-12-02 01:00:00 -0800
...
```
after the second commit:
```
bundle exec spring testunit ./test/controllers/pd/session_attendance_controller_test.rb --name test_attend_too_late_renders_too_late_view
setup_all run at 2021-12-02 01:00:00 -0800
test case run at 2021-12-02 01:00:00 -0800
...
```

I can't explain exactly why this would lead to the flakiness we've been observing, so I'm proposing merging this as a speculative fix and seeing if it happens to fix our problems with the test.

### CODE REVIEW

**Comment by davidsbailey** [comment]
credit to @bethanyaconnor for the crucial tip that this was usually happening around/after 4pm: https://codedotorg.slack.com/archives/C0T0PNTM3/p1638403975392800

**Review by bethanyaconnor — APPROVED** [review]
Good find! I'm happy to try this as a speculative fix!

**Review by tim-dot-org — APPROVED** [review]
good catch!

side note: I have noticed that there are weird timezone issues with workshops on my local machine that don't appear in production, and i'm wondering if theres some global environment thing that might be affecting these tests

**Comment by davidsbailey** [comment]
@tim-dot-org do you recall any specific tests which you've had problems with? here are some other test files which contain both `freeze_time` and `setup_all`:
```
controllers/pd/workshop_enrollment_controller_test.rb
controllers/pd/session_attendance_controller_test.rb
controllers/api/v1/pd/regional_partner_workshops_controller_test.rb
controllers/api/v1/pd/applications_controller_test.rb
controllers/api/v1/pd/workshop_summary_report_controller_test.rb
controllers/api/v1/pd/teacher_attendance_report_controller_test.rb
controllers/api/v1/pd/workshops_controller_test.rb
controllers/api/v1/pd/workshop_attendance_controller_test.rb
lib/pd/payment/payment_calculator_test.rb
models/pd/attendance_test.rb
models/pd/payment_term_test.rb
models/pd/workshop_test.rb
```

**Comment by davidsbailey** [comment]
one idea is to change `freeze_time` to use `setup_all` instead of `setup`. I'm not sure if that would break some tests which rely on time being reset between test cases, or how hard those problems would be to track down, though.

**Comment by davidsbailey** [comment]
when I run
```
Dave-MBP:~/src/cdo2/dashboard (_staging2)$ time bundle exec spring testunit ./test/controllers/api/v1/pd
```

TeacherAttendanceReportControllerTest has many tests skipped with "test is flaky for 6 hours per day due to time zone differences"

WorkshopsControllerTest has 5 failing test cases. everything else passes.

unfortunately, making the same fix to WorkshopsControllerTest does not fix anything. The output looks like this:
[output.txt](https://github.com/code-dot-org/code-dot-org/files/7644280/output.txt) the errors look like a local time vs UTC problem.

For our apps tests, we have a way of enforcing that the tests run in UTC, even when run locally: https://github.com/code-dot-org/code-dot-org/blob/b4da0b0c6ed4b25bb2e370c37453b94b9e7c42f4/apps/package.json#L12

perhaps we can do something similar for dashboard tests?

**Comment by davidsbailey** [comment]
the `TZ=UTC` prefix fixes it!
Screen Shot 2021-12-02 at 10 34 30 AM

**Comment by davidsbailey** [comment]
sorry to add things on to an already-approved PR. @tim-dot-org or @bethanyaconnor , can I get a 👍  on the last commit? 

to be clear, this had the same effect as adding `TZ=UTC` on the command line, i.e. the workshops controller tests are now passing locally.

**Review by tim-dot-org — APPROVED** [review]

**Pull request merged**
