### PR TITLE
[Data Viz] Cross Tab styling

### PR DESCRIPTION
**Pull request by ajpal**
# Description
Add styling for cross tab charts. Minimum value is white, maximum is #2B77F3
image
image

## Links

- [spec](https://docs.google.com/document/d/1s1CQ4SSrpwJtLwI5gJoFzJEbcEXZHQIQ6ikAxB9H3j4/edit)
- [jira](https://codedotorg.atlassian.net/browse/STAR-754)

## Testing story
Unit tests

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by epeach** [comment]
[Not ship-blocking] One design comment and one sorting comment: 
Screenshot from 2019-11-07 14-57-01
The line-up between the rows and the title-row seems off as it switches from black to white.

Screenshot from 2019-11-07 14-57-13
Do we want to make a special case for sorting days of the week?

**Review by epeach — APPROVED** [review]
LGTM

**Comment by ajpal** [comment]
https://codedotorg.atlassian.net/browse/STAR-817 tracks figuring out what we want to do about sorting for columns like days of the week that have a natural ordering

**Comment by ajpal** [comment]
Updated the top row to also have a black border so it doesn't look off:
image

**Pull request merged**
