### PR TITLE
Add BTS to Dance Party artists on /dance

### PR DESCRIPTION
**Pull request by kelbyhawn**
Add BTS to Dance Party artists graphic, name list, and OpenGraph image on https://code.org/dance

**Asana task:**  https://app.asana.com/0/0/1204451559036467

### Before
Before

### After
After

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
not a blocker, but it would be nice to be able to see the Asana task. I clicked to request access, but not sure that has worked in the past.

**Comment by kelbyhawn** [comment]
> not a blocker, but it would be nice to be able to see the Asana task. I clicked to request access, but not sure that has worked in the past.

Just added you!

**Comment by davidsbailey** [comment]
Thanks Kelby! I requested access to the Figma too. Are there lists our team can be added to so we can see your content in Asana and Figma in the future?

**Comment by kelbyhawn** [comment]
> Thanks Kelby! I requested access to the Figma too. Are there lists our team can be added to so we can see your content in Asana and Figma in the future?

@davidsbailey I reached out to Mark and Kristin about this and will follow up on Slack once I hear more 😄

**Pull request merged**
