### PR TITLE
Bypass spam filter with complete your application reminder emails

### PR DESCRIPTION
**Pull request by megcrenshaw**
After manually sending mailers on our `staging` machine, the source of the error was in the subject line, using U+2019 ("Right Single Quotation Mark") instead of U+0027 ("Apostrophe").
Screenshot 2023-02-08 at 11 10 46 AM

I reverted the previous attempt at fixing this (https://github.com/code-dot-org/code-dot-org/pull/49897/commits/94408c3eb7ee64de0f13ae4535759426e777892c) and changed the character in both subject lines –– doing this on staging sent the email directly to the inbox. Additionally, there were minor content updates:

http://localhost-studio.code.org:3000/rails/mailers/pd_teacher_application_mailer/complete_application_initial_reminder__with_partner shows 
Screenshot 2023-02-08 at 11 42 06 AM

and http://localhost-studio.code.org:3000/rails/mailers/pd_teacher_application_mailer/complete_application_final_reminder__with_partner shows
image

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
nice find!

**Comment by sureshc** [comment]
Whoa! Pretty epic sleuthing. Could you check whether this is the issue with the Hour of Code event sign up email in Pegasus as well?

**Review by sureshc — APPROVED** [review]
Do we know why this character in the subject line is causing DKIM to fail? My understanding is that the DKIM signature is based on a hash of the subject, from, and body of the email.

**Comment by megcrenshaw** [comment]
@sureshc It does look like our [2022 English sign-up](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/emails/hoc_signup_2022_receipt_en.md) has that character as well, both in the body and the subject. Would be interesting to see if the problem persists when only the subject is fixed. Also interesting to see if other "special characters" from other languages trigger anything (do the Portuguese and Spanish versions of these get picked up by spam)?

Most of these files have `.html.haml` or `.md` extensions –– are there any linter-type catches we could have? Not sure we need the curly quotation mark anywhere in our database.

I don't know why exactly this is a problem, but I'm seeing reference to it here https://powerdmarc.com/why-does-dkim-fail/ ("minor modifications in the hash value, such as the insertion of spaces or special characters can make your body hash verification fail DKIM.") and also maybe at https://techcommunity.microsoft.com/t5/office-365-networking/microsoft-s-e-mailservers-break-dkim-on-non-ascii-characters/m-p/1774384 –– I'm wondering if default character sets on email hosts don't include certain characters so these algorithms catch them?

**Comment by cat5inthecradle** [comment]
Maybe this? https://www.npmjs.com/package/markdownlint-rule-search-replace

**Comment by megcrenshaw** [comment]
Ah nice! Also looks like we can add a custom lint rule for haml files, similar to https://github.com/sds/haml-lint/blob/main/lib/haml_lint/linter/indentation.rb?

**Comment by davidsbailey** [comment]
I would love for us to start writing custom lint rules!

**Comment by megcrenshaw** [comment]
Draft PR here https://github.com/code-dot-org/code-dot-org/pull/50195 for custom linters. The markdownlint package isn't compatible with our version of node :( –– didn't explore that path futher.

**Comment by breville** [comment]
Great find & fix!

**Pull request merged**
