### PR TITLE
Fixes violations of and reenables the rubocop Style/EmptyLineBetweenDefs check.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Initial fixes (0bc2b72) generated by "bundle exec rubocop --only Style/EmptyLineBetweenDefs --auto-correct", with later changes done manually.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Brian: Is this a check we want to enforce? Does its enforcement represent a clear gain?

**Comment by bcjordan** [comment]
@ashercodeorg yeah, think so. Instances where there were multi-line defs and no newline between feel like mistakes / don't improve scan-ability. The single-line-defs feel like they maybe could be allowed to continue to omit the newline (like defining a bunch of constants at the top of a file), but not sure if there's an easy way to do that. Doesn't feel super important to keep those next to each other

**Comment by ashercodeorg** [comment]
It is straightforward to allow adjacent (e.g., no blank lines between) one-line-defs via the configuration parameter AllowAdjacentOneLineDefs. If you agree, I'll regenerate the PR using it.

**Comment by bcjordan** [comment]
Agree, that feels right.

**Comment by ashercodeorg** [comment]
PTAL. Thanks!

**Comment by bcjordan** [comment]
LGTM, & eyeballed changes to confirm are whitespace only. :+1: :tada:

**Pull request merged**
