### PR TITLE
Make CSF Embed Levels consistent with other embed levels

### PR DESCRIPTION
**Pull request by dmcavoy**
Make all embed levels consistent! Especially move CSF embed levels to work like CSD/CSP embed levels!

# Before

Screen Shot 2019-06-10 at 5 07 43 PM

# After

(note: I clicked the hint on this level - it shows up without the hint expanded if you haven't clicked it)

Screen Shot 2019-06-10 at 5 07 09 PM

# CSD/CSP continues to look the same

Screen Shot 2019-06-10 at 5 09 28 PM

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
I like that we are getting rid of center-embedded (which AFAIK only CSF used), but are you sure we want to get rid of responsiveEmbedded? The deleted comments suggest that this behavior was only wanted in applab. the non-responsive behavior, of keeping the play space full-size even when the screen is smaller, has merit because if you are not writing any code then you don't really care how wide the workspace / instructions area is.

If we are sure this is what we want from a product perspective, then these code changes LGTM.

**Review by Erin007 — APPROVED** [review]
Nice! This simplifies things. LGTM!

**Comment by dmcavoy** [comment]
@davidsbailey Allowing it to be responsive just allows it to be resized and make both the instructions and the app area display correctly on different sized screens next to each other. It was already true for game lab embed as well and the change to make them all responsive brings us toward the consistent level feel we were hoping for. I will run it by @fontie715 too.

**Comment by joshlory** [comment]
giphy

This cleanup is AWESOME!

**Comment by davidsbailey** [comment]
Hi Dani, good point, I missed that this responsiveEmbedded was enabled for gamelab too. It looks like you have covered all the cases. LGTM!

**Pull request merged**
