### PR TITLE
Applab: easy config of palette for each level

### PR DESCRIPTION
**Pull request by cpirich**
Made it easier to create the palette (aka toolbox) for new editCode droplet levels in preparation for adding levelbuilder support for Applab
- level.codeFunctions can be an array (as it used to be) if you want to explicitly set every block in the palette - this is still used by Maze, Turtle, and Studio
- level.codeFunctions can now be an object of key/value pairs as long as the app has created a dropletConfig - this is now used by Applab
- dropletConfig.blocks specifies the defaults for each possible 'block' (function name, tooltip/title, category, parameters, type). dropletConfig.categories specifies a set of possible categories for that app (name, color).
- in Applab level.codeFunctions, the keys are the names of the blocks and the values can be null or empty if the level wants the default version of that block or the block can be modified for that level by overriding any of the default properties besides name (tooltip/title, category, parameters, or type)
- the palette will not include categories that are empty

### CODE REVIEW

**Comment by davidsbailey** [comment]
Is it possible to override any fields (especially params) in the codeFunctions block, if the levelbuilder wants the block to appear slightly differently in the toolbox for a specific level?

**Comment by cpirich** [comment]
Yes, see 4th bullet above. you can override any of the properties except the name. Not sure we will hook that up in levelbuilder right away, but it will eventually be needed.

**Comment by cpirich** [comment]
Also, I should note that we do not yet allow you to remove the 'stock' functions and categories for 'Control', 'Math', or 'Functions'. Eventually, we will want to allow that as well.

**Comment by davidsbailey** [comment]
LGTM

**Pull request merged**
