### PR TITLE
Increase durability on Reporting Database to enable Point In Time Restore

### PR DESCRIPTION
**Pull request by sureshc**
Increase durability on Reporting Database to enable AWS RDS Point in Time Restore feature.  Our recent attempts to utilize the Point In Time Restore feature have not succeeded due to settings that reduce durability (and increase write performance) on the production instance.  These settings are not needed on the reporting database, so revert it to the default (ACID compliant) values.

I did not change `binlog_format` to MIXED as suggested by AWS Support in Case 5838364571, because ROW is needed to support export to Redshift via DMS

### CODE REVIEW

**Review by wjordan — APPROVED** [review]

**Comment by sureshc** [comment]
```
kilkenny:code-dot-org suresh$ bundle exec rake stack:data:validate RAILS_ENV=production
Data layer including RedShift cluster configuration and synchronization with RDS instance.
Listing changes to existing stack `DATA-production`:
Modify DBSnapshotKey [AWS::KMS::Key] Tags ()
Modify DMSCron [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TargetEndpointArn)
Modify DMSCronLevelSourcesPii [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TargetEndpointArn)
Modify DMSCronPii [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TargetEndpointArn)
Modify DMSCronUserHierarchy [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TargetEndpointArn)
Modify DMSCronUserHierarchyPii [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TargetEndpointArn)
Modify DMSCronUserLevels [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TargetEndpointArn)
Modify PrimaryDBParameters [AWS::RDS::DBParameterGroup] Tags ()
Modify RedshiftEndpoint [AWS::DMS::Endpoint] Properties Replacement: Conditional (ServerName, Port)
Modify ReportingDBParameters [AWS::RDS::DBParameterGroup] Properties, Tags (Parameters, )
Modify Tableau [AWS::Redshift::Cluster] Tags ()
```

**Comment by wjordan** [comment]
Most of those changes are related to removing the `owner` tag from affected resources- I just applied a no-op stack update to remove these separately from this change. The updated diff should look like this:

```
Modify ReportingDBParameters [AWS::RDS::DBParameterGroup] Properties (Parameters)
```

**Review by wjordan — APPROVED** [review]

**Comment by wjordan** [comment]
> I did not change binlog_format to MIXED as suggested by AWS Support in Case 5838364571, because ROW is needed to support export to Redshift via DMS

This sounds good, we'll try it out this way and if it still causes an error (I don't expect it to) we can experiment with different `binlog_format` setting some other way (whether it's changing durability on the primary instead, or creating another read-replica with different `binlog_format`).

**Comment by sureshc** [comment]
Yup.  Now the change looks like this:
```
kilkenny:code-dot-org suresh$ bundle exec rake stack:data:validate RAILS_ENV=production
Data layer including RedShift cluster configuration and synchronization with RDS instance.
Listing changes to existing stack `DATA-production`:
Modify ReportingDBParameters [AWS::RDS::DBParameterGroup] Properties (Parameters)
```

**Comment by sureshc** [comment]
I applied this change manually from my development environment (`bundle exec rake stack:data:start RAILS_ENV=production`) at 2PM PDT 3/14/2019: 
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/arn%3Aaws%3Acloudformation%3Aus-east-1%3A475661607190%3Astack%2FDATA-production%2F26a3cdb0-38c9-11e6-9a10-50fae98a10fe/events

**Pull request merged**
