### PR TITLE
Fixes violations of and reenables Style/ClassMethods.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes generated by `bundle exec rubocop --only Style/ClassMethods --auto-correct`.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Is this really an improvement? Is this a rubocop we want to enforce?

**Comment by aoby** [comment]
I don't think so. I don't care too strongly, but it seems to me that `def self.method` is more concise and still unambiguous. Especially with longer class names the 'recommended' way could become unwieldy.

**Comment by ashercodeorg** [comment]
Your answer confuses me, as I'm interepreting the "recommended" way to mean the way rubocop enforces. The "non-recommended" could become "unwieldy" with super-long class names.

**Comment by aoby** [comment]
Ha - that's because this morning I was reading it totally backwards for some reason and what I said makes no sense. You're right, the _non-recommended_ way could become unwieldy. 

I actually do prefer the rubocop recommended `self.method` over `ClassName.method` style. 

As to whether we enforce it, I don't feel too strongly about it.

**Pull request merged**
