### PR TITLE
Show rubrics behind a pilot flag

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Use a SingleUserExperiment for the Rubrics pilot, using CanCanCan to enforce. This had the added effect of preventing non-levelbuilders from accessing the editors. I named the experiment `ai-ta-rubrics`, but am open to suggestions.

What this means:
- Developers will either need levelbuilder permissions locally or need to set up an experiment locally to see this feature. To do that, log in as an admin, go to http://localhost-studio.code.org:3000/admin/pilots, and create a pilot with the name `ai-ta-rubrics` (display name doesn't matter). Then, add any local accounts to that pilot (or, alternatively, allow joining by URL and just use that URL whenever you need it).
- Developers will also need to create a rubric locally to see this button. I've been creating one via the command line for now but if folks are interested, we could consider a pilot script with a fake rubric until the actual rubrics are ready.
- In production, we can follow the same process as above and add internal folks before any teachers have access to see the progress of the feature. (We'd also need a rubric to be live in production.)
- When we get ready to launch the pilot, we'll need to add each teacher to the pilot, the same as how we do this when we pilot curriculum.
- Students in a section assigned csd-2022 and taught by a teacher who can view rubrics can also theoretically view rubrics. They cannot see the floating action button, however, but we'll likely need this logic when we add rubrics to the student view.

I went back and forth on whether to include the ability for students to see rubrics at this stage. On one hand, we will need that logic eventually, but on the other hand, we won't need it for a couple weeks so it might make sense to add that logic then. Definitely open to feedback here!

### CODE REVIEW

**Comment by davidsbailey** [comment]
> Use a SingleUserExperiment for the Rubrics pilot, using CanCanCan to enforce. This had the added effect of preventing non-levelbuilders from accessing the editors. I named the experiment `ai-ta-rubrics`, but am open to suggestions.

in the absence of an official name for this feature to go off of, what do you think about `ai-rubrics`, to avoid user-facing mention of the sequence `ai-ta` :-)

**Comment by davidsbailey** [comment]
> * Developers will also need to create a rubric locally to see this button. I've been creating one via the command line for now but if folks are interested, we could consider a pilot script with a fake rubric until the actual rubrics are ready.

apologies to not have a good pulse on this, but are we at a point where we could have a pilot script (like allthethings, but for our specific purpose) which gets seeded into every environment, and could a fake rubric also get created by the seed process? not necessarily saying we need to do this now, but one perspective is that we'll probably at least want to set up the fake script for UI testing at some point before we launch, so if it is no "extra" work to do now then it could be worth doing now.

EDIT: to clarify, we usually want fake data in our UI tests, so that (1) we don't have to seed huge courses in our test environment, and (2) curriculum edits can't break our tests.

**Comment by bethanyaconnor** [comment]
I believe we are at a place where we could have a fake rubric for either a pilot script or a lesson in `allthethings`. Created [a task](https://codedotorg.atlassian.net/browse/AITT-105) to do that as a follow up. Do we have a preference for a standalone script or is allthethings okay?

I think I'd still like to keep the rubric behind an experiment flag for now though to avoid complicating when we show the entry point.

**Comment by davidsbailey** [comment]
> I believe we are at a place where we could have a fake rubric for either a pilot script or a lesson in `allthethings`. Created [a task](https://codedotorg.atlassian.net/browse/AITT-105) to do that as a follow up. Do we have a preference for a standalone script or is allthethings okay?
> 
> I think I'd still like to keep the rubric behind an experiment flag for now though to avoid complicating when we show the entry point.

your choice I think!

I totally agree with keeping the rubric behind an experiment flag, but I think I am missing whether you have a separate flag for it or whether it would be convenient to rely on a pilot script and its corresponding pilot experiment flag?

if you do not need a pilot script to hide the rubrics, then a lesson in allthethings seems reasonable to me. maybe we can move it to its own script if we ever get to needing more than one lesson there.

**Comment by bethanyaconnor** [comment]
> I think I am missing whether you have a separate flag for it or whether it would be convenient to rely on a pilot script and its corresponding pilot experiment flag

Maybe this is coming from my confusion about how we're planning on running the pilot. I feel like I've heard pilot script, csd 2022, and csd 2023 thrown around as to where we're doing the pilot. Do we have a plan for that yet? If we're definitely using a pilot script then this feature probably doesn't need to be behind an experiment flag at all and instead we'd only have rubrics on the pilot script (and possibly allthethings for UI testing).

**Comment by davidsbailey** [comment]
> > I think I am missing whether you have a separate flag for it or whether it would be convenient to rely on a pilot script and its corresponding pilot experiment flag
> 
> Maybe this is coming from my confusion about how we're planning on running the pilot. I feel like I've heard pilot script, csd 2022, and csd 2023 thrown around as to where we're doing the pilot. Do we have a plan for that yet? If we're definitely using a pilot script then this feature probably doesn't need to be behind an experiment flag at all and instead we'd only have rubrics on the pilot script (and possibly allthethings for UI testing).

Very good point. I think this is still an open question. currently there is no clear need for a pilot script, because we are just making the updates we need directly to csd-2023. that strategy has worked so far for rubrics, but I'm not sure where we landed on whether that works for making project levels submittable. I will follow up on that, but for now I would say it's probably better not to block on that answer, and you can create a feature experiment flag if/when you need one.

Since the feature is not being developed in secret, I am wondering if we maybe do not need any kind of experiment flag protecting it in our test scripts just yet though?

**Comment by davidsbailey** [comment]
I just confirmed we have already marked the csd-2023 project levels as submittable, so we should assume that csd-2023 is where this feature will launch for now.

**Comment by bethanyaconnor** [comment]
okay, it sounds like what we want is:
- in GA curriculum (eg csd-2023), only show the entry point to users in our pilot
- in our test curriculum (ie `allthethings`), it would be nice if we didn't hide the rubrics so that we can write tests against them

Without hardcoding exceptions, I'm not sure the best way to achieve both of those goals. Definitely open to suggestions

**Comment by davidsbailey** [comment]
> okay, it sounds like what we want is:
> 
> * in GA curriculum (eg csd-2023), only show the entry point to users in our pilot
> * in our test curriculum (ie `allthethings`), it would be nice if we didn't hide the rubrics so that we can write tests against them
> 
> Without hardcoding exceptions, I'm not sure the best way to achieve both of those goals. Definitely open to suggestions

what about (1) put the new functionality behind an experiment (2) in the UI tests, enable the experiment (either via url param, or if necessary by adding a user to a server-side experiment)?

For now, you could leave the experiment off, and wait until we are close to shipping to add it.

**Comment by bethanyaconnor** [comment]
oh one idea:
I'd forgotten that if a user has an experiment enabled in our `experiments` table, we also pass that experiment name into the `experiments` cookie on the client.

So, one option is to rely on our client-side experiment flag system. This would allow us to test in UI tests by appending `?enableExperiment=ai-rubrics` to URLs. Developers could set this flag locally and other stakeholders could set it in production.

Then, for ease of enrolling teachers in the pilot, we create an entry in the `experiments` table with the same experiment name. Originally my plan was to use `SingleUserExperiment` but then we'd have to enroll all students as well, which seemed untenable.

Then I remember a pointer you gave me a couple of weeks ago, Dave -- `SingleSectionExperiment`. With one small tweak, this also sets the experiment flag for all students in the section, so we could continue to use our `experiments` cookie. 

The downside is that we don't have an `SingleSectionExperiments` in production and no nice UI to add teachers, so an engineer will have to manually create all those rows.

**Comment by bethanyaconnor** [comment]
oops sorry -- didn't see your message. I actually think we're generally aligned, so I'll move this to an experiment flag for now and we can figure out how to add teachers/sections/users closer to the time

**Comment by bethanyaconnor** [comment]
There are enough changes here that I'm going to close this PR and open a new one

**Comment by davidsbailey** [comment]
all sounds good!

**Pull request closed without merging**
