### PR TITLE
Clear callouts and videos from the local storage when resetting the c…

### PR DESCRIPTION
**Pull request by mehalshah**
…lient state

### CODE REVIEW

**Comment by breville** [comment]
So this resets callouts when the user signs out?  Seems reasonable.

What about when somebody visits /hoc/reset?  Seems like this should also reset callouts for both signed-in and signed-out users.

@laurelfan should review these questions :)

**Comment by mehalshah** [comment]
Agreed that hoc/reset should do that - can make that a separate change. Meanwhile, I'd like to push this given approval from review

**Comment by joshlory** [comment]
This looks fine for the sign-out case.  Please open Pivotal items for the issue Brendan referenced, and for expiring session data after a certain amount of time (the issue from the email thread).  Thanks for fixing!

**Comment by joshlory** [comment]
@mehalshah Can you add the Pivotal bug numbers here to track?

**Comment by mehalshah** [comment]
Created bugs 107594184 and 107594184 to track the other issues

**Pull request merged**
