### PR TITLE
Replace catalog screenshot in how-to page

### PR DESCRIPTION
**Pull request by drizco**
swaps out the activities catalog screenshot with new activities

BEFORE:
Screenshot 2024-11-04 at 1 24 03 PM

AFTER:
Screenshot 2024-11-04 at 1 22 31 PM

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by hannahbergam — APPROVED** [review]
I'm curious about how this was working with the jpg extension before (if the image is just being replaced with the same name like this git diff indicates)! But the screenshot looks good!

**Comment by kelbyhawn** [comment]
> I'm curious about how this was working with the jpg extension before (if the image is just being replaced with the same name like this git diff indicates)! But the screenshot looks good!

The original image was a jpg and this one is a png so it's technically a new file even if the name is the same!

**Review by kelbyhawn — APPROVED** [review]
Looks good! But hold off on merging until we know what we're going to do with the Music Lab: Jam Session activity.

**Comment by drizco** [comment]
> > I'm curious about how this was working with the jpg extension before (if the image is just being replaced with the same name like this git diff indicates)! But the screenshot looks good!
> 
> The original image was a jpg and this one is a png so it's technically a new file even if the name is the same!

This was actually really weird. I found this funky `resolve_image` method used in our routing that seems like the culprit. it iterates over common image file extensions and returns the first one that resolves successfully. so the path passed to the image source can have any common image file extension (even .gif) and it will resolve with the .png or whichever file it finds first 🤯 
Screenshot 2024-11-05 at 8 27 57 AM

**Comment by kelbyhawn** [comment]
> > > I'm curious about how this was working with the jpg extension before (if the image is just being replaced with the same name like this git diff indicates)! But the screenshot looks good!
> > 
> > 
> > The original image was a jpg and this one is a png so it's technically a new file even if the name is the same!
> 
> This was actually really weird. I found this funky `resolve_image` method used in our routing that seems like the culprit. it iterates over common image file extensions and returns the first one that resolves successfully. so the path passed to the image source can have any common image file extension (even .gif) and it will resolve with the .png or whichever file it finds first 🤯 Screenshot 2024-11-05 at 8 27 57 AM

Whoa that is WILD!

**Comment by drizco** [comment]
> Looks good! But hold off on merging until we know what we're going to do with the Music Lab: Jam Session activity.

@kelbyhawn still hold on merging?

**Comment by kelbyhawn** [comment]
> > Looks good! But hold off on merging until we know what we're going to do with the Music Lab: Jam Session activity.
> 
> @kelbyhawn still hold on merging?

Yep! You should be good to merge this after the day's DTP on 11/12. I'll update your ticket.

**Pull request merged**
