### PR TITLE
Change header for census form.

### PR DESCRIPTION
**Pull request by drewsamnick**
[Task](https://trello.com/c/PuX41kzl/23-change-the-green-title-on-the-second-page-of-questions-to-thanks-for-signing-up-to-host-an-hour-of-code-please-take-a-few-minute)

screen shot 2017-10-12 at 11 10 54 am

### CODE REVIEW

**Comment by drewsamnick** [comment]
[Change the green title on the second page of questions to "Thanks for signing up to host an Hour of Code! Please take a few minutes to tell us about your school (Optional)."](https://trello.com/c/PuX41kzl/23-change-the-green-title-on-the-second-page-of-questions-to-thanks-for-signing-up-to-host-an-hour-of-code-please-take-a-few-minute)

**Comment by mirlew** [comment]
Is there something blocking us from deploying this?

**Comment by drewsamnick** [comment]
This should be in prod now.

**Comment by mirlew** [comment]
Oh sorry, it is. My bad!

**Pull request merged**
