### PR TITLE
Remove obsolete and outdated build_scripts script.

### PR DESCRIPTION
**Pull request by ashercodeorg**
After this PR is merged, the following cleanup steps remain.

- [ ] Remove the related seeding [tasks](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/lib/tasks/seed.rake#L19-L39).
- [ ] Remove the `seeded` files on `staging`.
- [ ] Remove the files from any `.gitignore`s.

This PR is being decroned in #15339.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
You have as much context as I have. My conclusion was based on the lack of these files in `dashboard/config/scripts`.

**Comment by ashercodeorg** [comment]
Also that we now seed scripts and levels and such through our rake tasks.

**Comment by ashercodeorg** [comment]
Adding @wjordan for possible further context.

**Comment by wjordan** [comment]
context: https://github.com/code-dot-org/dashboard/commit/52568c19c5c18edea55d17828f7f1d7bc029a958. It's still being referenced in [`crontab`](https://github.com/code-dot-org/code-dot-org/blob/staging/cookbooks/cdo-apps/templates/default/crontab.erb#L60-L60), so if it's indeed obsolete we should remove this line and test/confirm that it's no longer doing anything.

**Comment by ashercodeorg** [comment]
The associated `seeded` files exist on staging
```
ubuntu@staging:~/staging/dashboard/config/scripts$ ls -l .*seeded
-rw-rw-r-- 1 ubuntu ubuntu 0 Mar 11  2015 .matches_seeded
-rw-rw-r-- 1 ubuntu ubuntu 0 Mar  9  2015 .multis_seeded
-rw-rw-r-- 1 ubuntu ubuntu 0 May 19 15:12 .seeded
```
though nowhere else. Being empty, I'm going to think about disabling the cron (another PR) and seeing what happens.

**Comment by ashercodeorg** [comment]
The associated cronjob has been [removed](https://github.com/code-dot-org/code-dot-org/pull/15339) and has reached all environments. PTAL.

**Pull request merged**
