### PR TITLE
Use wildcards for fewer Cloudfront Behaviors

### PR DESCRIPTION
**Pull request by cat5inthecradle**
We can only have a limited number of cloudfront behaviors, when we added a new Dance Party path and it's Uncached final level, we hit the limit. This PR aggressively condenses cached paths (and their uncached exception cases) using wildcards.

## Links

Learn more about `?` and `*` wildcards in the [PathPattern](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html?icmpid=docs_cf_help_panel#DownloadDistValuesPathPattern) docs.

## Testing story

Unit tests should confirm that we're under the behavior limit.

## Caching

This isn't the ideal long term solution, and it arguably makes thing more complex.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by sureshc** [comment]
My memory is that the wildcard patterns supported by CloudFront behaviors are very limited. Do we have an easy way to test that these will work?

**Comment by cat5inthecradle** [comment]
> My memory is that the wildcard patterns supported by CloudFront behaviors are very limited. Do we have an easy way to test that these will work?

We've got room for one new behavior in cloudfront right now. We could try adding/editing one and see if it works.

And yes, they're very limited. We have to use `*` or `?` and can't use regex. The risk with this PR is that we could accidentally include things we don't want, like if we added `dancewithfriends` or `starwarsbutveryuncacheable` it would get cached. The docs I linked cover the limitations, and I think this change will be fine.

**Comment by sureshc** [comment]
I know we have some Ruby logic that emulates the CloudFront (and deleted Varnish) HTTP caching rules for environments that don't have those components. Do we exercise that logic for Hour of Code cached/uncached levels? If not, do we have browser user interface tests that exercise the cached/uncached logic for Hour of Code tutorials?

We could also fire up an adhoc with CloudFront (`adhoc:cdn:start`) to verify manually.

**Comment by sureshc** [comment]
I tried provisioning an adhoc with CloudFront, but it failed due to logic we have the emulates the CloudFront Behaviors in environments that don't have CloudFront (I think this logic also used to used to configure the same cache / pattern rules in Varnish):

```
code-dot-org % bundle exec rake adhoc:cdn:validate RAILS_ENV=adhoc
Finished adhoc:environment (less than a minute)
Finished adhoc:cdn:environment (less than a minute)
rake aborted!
ArgumentError: Invalid path: /s/dance-*/lessons/1/levels/10
/Users/suresh/code-dot-org/lib/cdo/legacy_varnish_helpers.rb:41:in `block in normalize_paths'
/Users/suresh/code-dot-org/lib/cdo/legacy_varnish_helpers.rb:40:in `map'
/Users/suresh/code-dot-org/lib/cdo/legacy_varnish_helpers.rb:40:in `normalize_paths'
/Users/suresh/code-dot-org/lib/cdo/legacy_varnish_helpers.rb:55:in `validate_paths'
/Users/suresh/code-dot-org/lib/cdo/aws/cloudfront.rb:237:in `block in get_app_config'
/Users/suresh/code-dot-org/lib/cdo/aws/cloudfront.rb:234:in `map'
/Users/suresh/code-dot-org/lib/cdo/aws/cloudfront.rb:234:in `get_app_config'
/Users/suresh/code-dot-org/lib/cdo/aws/cloudfront.rb:141:in `distribution_config'
/Users/suresh/code-dot-org/lib/cdo/cloud_formation/cdo_app.rb:187:in `cloudfront_config'
/Users/suresh/code-dot-org/aws/cloudformation/cloud_formation_stack.yml.erb:355:in `block in get_binding'
/Users/suresh/code-dot-org/aws/cloudformation/cloud_formation_stack.yml.erb:328:in `each'
/Users/suresh/code-dot-org/aws/cloudformation/cloud_formation_stack.yml.erb:328:in `get_binding'
/Users/suresh/code-dot-org/lib/cdo/cloud_formation/stack_template.rb:69:in `block in erb_eval'
/Users/suresh/code-dot-org/lib/cdo/cloud_formation/stack_template.rb:68:in `chdir'
/Users/suresh/code-dot-org/lib/cdo/cloud_formation/stack_template.rb:68:in `erb_eval'
/Users/suresh/code-dot-org/lib/cdo/cloud_formation/stack_template.rb:55:in `erb_file'
/Users/suresh/code-dot-org/lib/cdo/cloud_formation/stack_template.rb:34:in `render'
/Users/suresh/code-dot-org/lib/cdo/cloud_formation/cdo_app.rb:86:in `render'
/Users/suresh/code-dot-org/lib/cdo/aws/cloud_formation.rb:82:in `change_stack'
/Users/suresh/code-dot-org/lib/cdo/aws/cloud_formation.rb:56:in `validate'
/Users/suresh/code-dot-org/lib/rake/adhoc.rake:51:in `block (2 levels) in <top (required)>'
/Users/suresh/code-dot-org/lib/cdo/data/logging/timed_task_with_logging.rb:12:in `block in execute'
/Users/suresh/code-dot-org/lib/cdo/data/logging/timed_task_with_logging.rb:12:in `execute'
/Users/suresh/code-dot-org/lib/rake/adhoc.rake:85:in `block (3 levels) in <top (required)>'
/Users/suresh/code-dot-org/lib/cdo/data/logging/timed_task_with_logging.rb:12:in `block in execute'
/Users/suresh/code-dot-org/lib/cdo/data/logging/timed_task_with_logging.rb:12:in `execute'
/Users/suresh/.rbenv/versions/3.0.5/bin/bundle:23:in `load'
/Users/suresh/.rbenv/versions/3.0.5/bin/bundle:23:in `<main>'
Tasks: TOP => adhoc:validate
(See full trace by running task with --trace)
```

**Pull request closed without merging**
