### PR TITLE
JavaLab: Enable project-backed level progressions in levelbuilder

### PR DESCRIPTION
**Pull request by sanchitmalhotra126**
Enables project-backed level progressions for JavaLab in levelbuilder. Screenshot attached:

Screen Shot 2021-06-15 at 3 35 53 PM

## Links

[CSA-471](https://codedotorg.atlassian.net/browse/CSA-471)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by molly-moen — APPROVED** [review]
LGTM! Is there additional work required on the javalab side to use this field or will this just work?

**Comment by sanchitmalhotra126** [comment]
> LGTM! Is there additional work required on the javalab side to use this field or will this just work?

I believe this should just work? @jmkulwik may have more context here, but as I understand it was just a matter of adding these fields.

**Comment by jmkulwik** [comment]
> > LGTM! Is there additional work required on the javalab side to use this field or will this just work?
> 
> I believe this should just work? @jmkulwik may have more context here, but as I understand it was just a matter of adding these fields.

A quick test would be good. Let me know if you'd like a hand setting that up.

**Comment by sanchitmalhotra126** [comment]
> > > LGTM! Is there additional work required on the javalab side to use this field or will this just work?
> > 
> > 
> > I believe this should just work? @jmkulwik may have more context here, but as I understand it was just a matter of adding these fields.
> 
> A quick test would be good. Let me know if you'd like a hand setting that up.

Tested this locally with @jmkulwik - student code seems to persist across levels as expected. There will be some followup tasks for missing UI elements, but I'll merge this for now.

**Pull request merged**
