### PR TITLE
Run UI tests in parallel threads rather than processes. Pass ENV through to Open3.popen3

### PR DESCRIPTION
**Pull request by bcjordan**
**Issue**: we are periodically (5-10% of runs?) seeing test failures where the CircleCI container runs out of memory, even after merging https://github.com/code-dot-org/code-dot-org/pull/7954 .

The root cause of this issue is that our parallelization has been using `in_processes: n` ([doc](https://github.com/grosser/parallel#processes)) rather than `in_threads: n` ([doc](https://github.com/grosser/parallel#threads)).

**Fix**: This changes our UI test runner to use separate threads rather than processes, and because we are no longer running separate parent processes, begins explicitly passing the cucumber environment configuration through to `Open3.popen3`.
## TODO
- [x] Flakiness test ~10 runs with eye towards performance differences against thread baselines.
- [x] Test thread performance on actual test machine. Is performance or flakiness worse? If so, can we conditionally use parallel processes instead of threads on non-Circle builds?

### CODE REVIEW

**Comment by islemaster** [comment]
LGTM!  I look forward to seeing what this does on the actual test machine.

**Comment by bcjordan** [comment]
Current roll-out plan:
1. Run 10 runs of this on Circle tomorrow morning.
2. If looks OK, merge in to staging, kick off DTT staging -> test before first real daily DTT.
3. If run on test machine does not look good, merge this extra ["use threads on Circle only"](https://github.com/code-dot-org/code-dot-org/compare/staging...threads-parallel-circle-only#diff-9fc3d7d059b4d462baa89c51be3454d3R295) commit.

**Comment by bcjordan** [comment]
Test run data, appears to be a speed improvement:

image

# Before (main test run time in seconds)

```
945
962
881
920
936
935
904
894
939
983
1029
902
976
944
937
951
```

Median: 938
Mean: 939.875
Standard dev: 36.9682296

# After

```
899
857
835
862
862
845
891
817
806
838
876
844
820
826
```

Mean: 844.5
Median: 848.4285714
Standard dev: 27.72312083

**Comment by bcjordan** [comment]
Run #1 on main test machine

Left lump: baseline DTT
Right lump: DTT with this merged in

image

## Baseline

(2 known eyes failures across both runs)

image

image

## With this merged in (attempt #1)

image

image

**Comment by bcjordan** [comment]
Run #2 (16 flaky re-runs, 1 failure):

image

**Pull request merged**
