### PR TITLE
Clarifying decide later and adding to translation pipeline

### PR DESCRIPTION
**Pull request by hannahbergam**
This is a simple PR to update the label on the decide later box in CQA. If theres something selected in the table: 'Clear assigned curriculum'. Otherwise, 'Decide later'. This will be the same across new/edit section flows. 

Screenshot 2023-04-20 at 2 55 45 PM

Screenshot 2023-04-20 at 2 55 52 PM

## Warning!!

The AP CSP Create Performance Task is in progress from April 1 - May 1 2023. Please
consider any risk introduced by this PR that could affect our students taking AP CSP. Code.org
students taking AP CSP primarily use App Lab for their Create Task, however a small percent use Game
Lab. Carefully consider whether your change has any risk of alterering, changing, or breaking
anything in these two labs. Even small changes, such as a different button color, are considered
significant during this time period. Reach out to the Student Learning team or Curriculum team for
more details.

## Links

- spec: []()
- jira ticket: https://codedotorg.atlassian.net/browse/TEACH-423

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by rshipp** [comment]
This phrasing seems a little confusing to me. With this language, I'd expect it to represent the current state, i.e. "there is no curriculum assigned", but instead it's a checkbox I can interact with. I'm not sure how to make it clearer while keeping the checkbox though... if it was a more explicit action like "Don't assign curriculum", it'd still make me confused about what happens when I uncheck it. I almost feel like it should be an "Assign curriculum" checkbox or toggle that hides the curriculum selection stuff when it's unchecked? But that might be a whole can of worms 😞

**Comment by hannahbergam** [comment]
> This phrasing seems a little confusing to me. With this language, I'd expect it to represent the current state, i.e. "there is no curriculum assigned", but instead it's a checkbox I can interact with. I'm not sure how to make it clearer while keeping the checkbox though... if it was a more explicit action like "Don't assign curriculum", it'd still make me confused about what happens when I uncheck it. I almost feel like it should be an "Assign curriculum" checkbox or toggle that hides the curriculum selection stuff when it's unchecked? But that might be a whole can of worms 😞

Honestly... agreed. I'll check back in with Tess!

**Comment by hannahbergam** [comment]
> > This phrasing seems a little confusing to me. With this language, I'd expect it to represent the current state, i.e. "there is no curriculum assigned", but instead it's a checkbox I can interact with. I'm not sure how to make it clearer while keeping the checkbox though... if it was a more explicit action like "Don't assign curriculum", it'd still make me confused about what happens when I uncheck it. I almost feel like it should be an "Assign curriculum" checkbox or toggle that hides the curriculum selection stuff when it's unchecked? But that might be a whole can of worms 😞
> 
> Honestly... agreed. I'll check back in with Tess!

@rshipp How do you feel about this new approach?

**Comment by rshipp** [comment]
This seems clearer to me! So clicking any of the radio buttons will uncheck the checkbox, and clicking the checkbox will deselect any radio button? What happens if you uncheck the box but don't select any radio button, will it prevent submitting the form or just submit without a course and unassign if there was something assigned?

**Comment by hannahbergam** [comment]
> This seems clearer to me! So clicking any of the radio buttons will uncheck the checkbox, and clicking the checkbox will deselect any radio button? What happens if you uncheck the box but don't select any radio button, will it prevent submitting the form or just submit without a course and unassign if there was something assigned?

'Clearer' is a win! And yes- correct about the click interactions. If you don't select a radio button and you uncheck the box, the section will save with no curriculum assigned (whether you had one prior or not). There is a future ticket (potentially post launch and post-user feedback) for creating some sort of warning message around unassignment.

**Review by rshipp — APPROVED** [review]

**Comment by rshipp** [comment]
Let me know if I can help with the validation/warning piece, I did some of that with the multi-grade piece.

**Pull request merged**
