### PR TITLE
Enables admin only tests for :hoc_signups.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by laurelfan** [comment]
it looks like the new tests failed on travis

**Comment by ashercodeorg** [comment]
It initially failed because it helps to stub the object / method that needs stubbing. With the newer commits, I'm unsure why it is reaching the pegasus_db. It doesn't help that it passes locally.

**Comment by laurelfan** [comment]
it passes locally because you have a pegasus db that it's able to access. I think what's going on is that `DB[:forms]` is calling the real [] method on the DB object (which tries to access the real database), even though the where method (on what that method returns) is stubbed.

You can repro what is going on in travis by temporarily overriding your pegasus database config settings in locals.yml to point to a database that doesn't exist, something like: `pegasus_db_name: not_a_real_database_name`. I think you will have to stub the [] method on DB, or you could try using the Sequel Mock::Database stuff: http://www.rubydoc.info/github/jeremyevans/sequel/Sequel/Mock/Database (which might be overkill if you just need to mock one method call).

**Comment by ashercodeorg** [comment]
Awesome, nice catch on [] not being stubbed. The now failing test is unrelated, please take another look.

**Comment by laurelfan** [comment]
cool, LGTM

**Pull request merged**
