### PR TITLE
Remove k5pd.css.scss

### PR DESCRIPTION
**Pull request by joshlory**
Normalize styles in markdown levels.  We don't want markdown levels to set different link styles than the site-wide default.

The max width is now set by https://github.com/code-dot-org/code-dot-org/pull/9589/files#diff-239b7a0365c3ae953719e57e0ded25d2R1809 (once merged).

### CODE REVIEW

**Comment by Hamms** [comment]
woooo! How difficult would it be to get some before/after screenshots?

**Comment by breville** [comment]
Does the DSL parser for .external actually clear out the entry for css when it's deleted?  I know some of our DSL parsers needed an explicit entry to blank out prior-ingested data.

If that's good, then LGTM.

**Comment by joshlory** [comment]
Differences:
1. `max-width` of 970px instead of `width` of 800px.
2. Links are no longer underlined.
3. When hovered, links turn a slightly different shade of blue.

Before:
screen shot 2016-07-19 at 3 29 05 pm

After:
screen shot 2016-07-19 at 3 28 54 pm

**Comment by Hamms** [comment]
LGTM

**Comment by joshlory** [comment]
Good call on DSLDefined options.  To verify I re-seeded after changing the .external files and no longer get matches for this query:

``` ruby
External.all.select{ |l| l.properties['options'].try(:[], 'css') == 'k5pd' }
```

**Pull request merged**
