### PR TITLE
Add Drawn Costumes to Costume Picker

### PR DESCRIPTION
**Pull request by epeach**
Ready to merge - re: https://github.com/code-dot-org/blockly/pull/169 and https://github.com/code-dot-org/blockly/commit/ab24136b7ff070e3e8443f1d64631c2f6d1eb1eb

When new costumes are drawn in the animation tab, they are added to the list of costume dropdowns in the picker.

This is not hidden behind a flag because only people who are behind a flag can draw costumes, so this won't be accessible unless a user is behind a flag.

drawsprite

### CODE REVIEW

**Comment by jmkulwik** [comment]
When you click the dropdown, it looks like the other default sprites are missing. Is this intended?

**Comment by epeach** [comment]
Yes, intended! I removed those default sprites in this example project to make it easier to test this in development. That change is isolated to the project I was testing in and screencapped.

**Review by jmkulwik — APPROVED** [review]

**Comment by ajpal** [comment]
It looks like the block is getting rendered underneath the toolbox? Do you know why that's happening?

**Review by ajpal — APPROVED** [review]
Changes LGTM!

**Pull request merged**
