### PR TITLE
Fix `foreign key constraint failed` during Test build

### PR DESCRIPTION
**Pull request by joshlory**
Testing this change on the Test machine to fix the build.

### CODE REVIEW

**Comment by joshlory** [comment]
@laurelfan do you know why the schema needs to be explicitly loaded before running rake tests?  Looking at this commit: 141cf12b38f16b4ee0ff229540702bc406605c1c.

**Comment by laurelfan** [comment]
Something to do with the fact that unit tests assume they are being run
from an env that is not test (eg development) for purposes such as keeping
the test db up to date (by comparing with the other db). That stuff doesn't
work if there isn't another env so e have to do it manually. Some of this
stuff was kind of trial and error-y, is it not working?

**Comment by laurelfan** [comment]
Also, getting stuff to work in all 3 of development, Travis and our test
build system probably means that there are duplicate steps and inconsistent
order (I've been having some trouble trying to fix the SecretPictures
thing).

**Comment by joshlory** [comment]
I think the issue is that the tables are getting dropped & re-added sequentially during `rake db:schema:load`, which violates the foreign key from peer_reviews -> level_sources.  I don't fully understand why `db:test:prepare` works when `db:schema:load` doesn't.

Another option would be `rake db:drop db:create db:schema:load` (but then why are we running `rake db:migrate` on Test?).

**Comment by laurelfan** [comment]
we're running rake db:migrate on test-the-server because we want to test it I guess?

the unit tests are supposed to do that automatically: https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/migration.rb#L409 (but they do it via db:test:prepare not migrate)

**Pull request merged**
