### PR TITLE
Remove apps dev sandbox

### PR DESCRIPTION
**Pull request by islemaster**
Does anybody still use this?  It seems to be poorly supported at best, especially now that rebuilding and hot reloading are working fairly well across our whole project.  This is another cleanup with no advantage to our production build, but it tears out a good-sized chunk of unmaintained code from our repository - and removing our dependency on [Express](https://expressjs.com/) pulls a good-sized chunk of other dependencies, evidenced by the big change in yarn.lock.

Measured | Before | After
--- | --- | ---
`node_modules` size | 574MB | 567MB

### CODE REVIEW

**Comment by davidsbailey** [comment]
I have no objection personally, but I know that Chris has been a proponent of this in the past so you might want to solicit his input.

**Comment by Bjvanminnen** [comment]
I fully support removing this.

**Comment by islemaster** [comment]
I'm hoping to hear from @cpirich because he's the only person I think _might_ still be using this.

**Comment by cpirich** [comment]
I'm not still using it, so feel free to remove.

**Pull request merged**
