### PR TITLE
Define DASHBOARD_REPORTING_DB and PEGASUS_REPORTING_DB.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Presently, we define `DASHBOARD_REPORTING_DB` and `PEGASUS_REPORTING_DB` in various places throughout our codebase. Define them with `DASHBOARD_DB` and `PEGASUS_DB`, ~with another PR converting our codebase to use these~ and convert our codebase to use them.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Any idea why these definitions are causing test failures?

**Comment by wjordan** [comment]
> Any idea why these definitions are causing test failures?

don't seem related to me- I was able to reproduce the test failures from `staging` branch as well

**Comment by ashercodeorg** [comment]
PTAL, added another commit that makes use of the new constants (per request).

**Comment by ashercodeorg** [comment]
Closing, though I'd encourage someone else to do this cleanup in my absence.

**Comment by wjordan** [comment]
That's fine, I can follow up on this later. This LGTM as-is (just noticed you added the use of the new constants in this PR)

**Comment by ashercodeorg** [comment]
Even if LG as-is, I'm not going to be around for any fallout. So I'd rather not merge it myself. Though the cleanup is useful, it isn't super important.

**Pull request closed without merging**
