### PR TITLE
Fix etags.json and changes.json bugs in sync-down and sync-out

### PR DESCRIPTION
**Pull request by hacodeorg**
Task [FND-1838](https://codedotorg.atlassian.net/browse/FND-1838). 
This PR fixes 2 related bugs we found in the sync-down and sync-out process.

## Bug 1: Downloading failures can cause missing translations.
The sync-down has 2 steps: 
1. Fetching a list of files that have changed since the last sync.
2. Then downloading the changed files.

If step 2 fails while downloading files, the next time we run a sync-down, it won't download missing files! The problem is on this line in `Crowdin::Utils.fetch_changes` function: https://github.com/code-dot-org/code-dot-org/blob/6c0f894a2e1235cea90c6231f57f677f9ef11cdf/lib/cdo/crowdin/utils.rb#L75 

We use `*etags.json` files (1 file for each Crowdin project) to remember what versions of translation files we have locally. In the code above, `*etags.json` files are updated multiple times during step 1 (before files are actually downloaded from Crowdin). We should only update etags files after step 2 succeeds. 

## Bug 2: sync-out failures can cause missing translations
Step 1 of the `sync-down` produces `*changes.json` files (1 file for each Crowdin project) that contain lists of files to download. `*changes.json` files are also consumed by the `sync-out` to determine what recently-changed files it should process. 
https://github.com/code-dot-org/code-dot-org/blob/dde87ff1e59f90b53fc3e0b19cc5cadc24c1531e/bin/i18n/sync-out.rb#L55

However, the `sync-down` wipes out and repopulates `*changes.json` every time it runs.
https://github.com/code-dot-org/code-dot-org/blob/6c0f894a2e1235cea90c6231f57f677f9ef11cdf/lib/cdo/crowdin/utils.rb#L45

So, if for some reasons the `sync-out` fails before the `sync-down` runs again, files that are not processed during the previously failed `sync-out` won’t be processed again! This results in missing translations. 

## The fix
2 main changes:
- Updating `*etags.json` files only after translation files have been downloaded (i.e. sync-down step 2 finishes). `*etags.json` will correctly represent the files we have locally.
- Splitting `*changes.json` into `*files_to_download.json` and `*files_to_sync_out.json`. `*files_to_download.json` will be used by step 2 of the `sync-down`, while `*files_to_sync_out.json` will be used by the `sync-out`. 

The sync-down (`fetch_changes` and `download_changed_files`) and sync-out flow will look like this:
<p align="center"></p>

## Testing story
- Uni tests `bundle exec ruby -Ilib:test lib/test/cdo/crowdin/test_utils.rb`
- Did a manual test on local machine
  - Ran `Crowdin::Utils.fetch_changes` in sync-down. 
    - Verified that it created `/tmp/*files_to_download.json` and did not update `bin/i18n/crowdin/*etags.json`.
  - Ran `Crowdin::Utils.download_changed_files` in sync-down. 
    - Verified that it updated `bin/i18n/crowdin/*etags.json`, emptied `/tmp/*files_to_download.json`, and created `bin/i18n/crowdin/*files_to_sync_out.json`.
  - Run sync-out. 
    - Verified that it distributed new translations, but did not modify `bin/i18n/crowdin/*etags.json` and `bin/i18n/crowdin/*files_to_sync_out.json`.

### CODE REVIEW

**Review by smusoke — APPROVED** [review]
LGTM. Also, appreciate the detailed PR description! 👍

**Comment by hacodeorg** [comment]
I realize I didn't implement the final step to clear out `*files_to_sync_out_json` files after `sync-out` finishes. I also realize that sometime we want to rerun `sync-out` to fix buggy results (this happened today, captured by this [slack thread](https://codedotorg.slack.com/archives/CFTFD6BPV/p1639504603492800)). With this change, rerunning `sync-out` is not possible after a successful run.

I'll need to think a bit more on how to enable that scenario. Would appreciate your ideas also.

**Comment by daynew** [comment]
> I realize I didn't implement the final step to clear out `*files_to_sync_out_json` files after `sync-out` finishes. I also realize that sometime we want to rerun `sync-out` to fix buggy results (this happened today, captured by this [slack thread](https://codedotorg.slack.com/archives/CFTFD6BPV/p1639504603492800)). With this change, rerunning `sync-out` is not possible after a successful run.
> 
> I'll need to think a bit more on how to enable that scenario. Would appreciate your ideas also.

Some ideas:
* Instead of deleting `files_to_sync_out_json`, move it to `/tmp/i18n_sync/backup/files_to_sync_out_json/`.
  * Add a command line argument to target a arbitrary `files_to_sync_out_json.json` file. I recommend adding a timestamp to the filename so the developer can easily identify the file.
  * Or if the `sync-out` script can't find a local `files_to_sync_out_json.json`, load the latest one from the `backup` directory.

**Review by daynew — APPROVED** [review]
The .gitignore should be updated to ignore the new temp files.

Otherwise looks mostly good. I think you could ship this but then have a follow PR for implementing a repeatable sync-out. If you want to use the same PR, then ping me and I will review the new changes.

**Comment by hacodeorg** [comment]
Thanks @daynew. I think backing up `*files_to_sync.json` is a good solution. Will create another PR for it.

For this PR, I pushed 1 more commit to add file locations to Crowdin project settings. This change will make it easier to know where important files are. Also added manual test sequence to the PR description.

**Pull request merged**
