### PR TITLE
Store enrollment emails downcased to match User

### PR DESCRIPTION
**Pull request by aoby**

### CODE REVIEW

**Comment by joshlory** [comment]
Do we need a migration to downcase existing enrollments?

**Comment by ashercodeorg** [comment]
If a data fix is necessary, consider a script rather than a migration.

**Comment by aoby** [comment]
I already updated existing enrollments (a couple times, whenever a teacher complained) in the DB via `Pd::Enrollents.find_each{|e| e.update!(email: e.email.downcase)}`. No migration needed.

**Comment by mehalshah** [comment]
LGTM

**Comment by mehalshah** [comment]
Circle failure looks legit though

**Pull request merged**
