### PR TITLE
Droplet: experiment to create a socket for known blocks

### PR DESCRIPTION
**Pull request by breville**
### The problem

The curriculum team identified a couple issues with code like this in Droplet:

```
if (getText("id").length == 3) {
}
```

Firstly, because `*.length` was "known", it became a single block (rather than a block with a socket for the `getText("id")`), like this:

Screen Shot 2022-04-16 at 11 03 49 AM

Secondly, when dragging a function like `getText` (which returns a string) into the unfilled socket of a `.length` block, we got a runtime error, like this:

https://user-images.githubusercontent.com/2205926/163655947-d583014b-32a3-40d4-bd0c-2d13009c1a54.mov

With this error in the browser console on localhost:
```
droplet-full.js:14075 Uncaught Error: Could not retrieve location 6, blockStart
    at Document.exports.Container.Container.getFromLocation (droplet-full.js:14075:13)
    at Editor.fromCrossDocumentLocation (droplet-full.js:7372:46)
    at Editor.setCursor (droplet-full.js:9048:24)
    at Editor.<anonymous> (droplet-full.js:7884:14)
    at droplet-full.js:6366:19
```

### The ask

The ask from the curriculum team was that the `.length` block have a socket, on its left, into which we can drag a function block that returns a string.  And the same for known member functions, such as `.toUpperCase()`.

### First attempt

My first attempt at this was to still pass through the `.length` block to show in the palette, but to not pass it through as a known code function. The downside to this approach was that the `length` was also a text-editable socket, like here:

Screen Shot 2022-04-16 at 10 56 55 AM

While it was still useful to have the function in the palette, in the workspace it was treated as a regular Object property access.

### This approach

The second approach, used in this PR, goes deeper into Droplet's JavaScript implementation; the core implementation of the change can be found in https://github.com/droplet-editor/droplet/pull/226.  

Now, the code that generates the block after recognizing a known "member expression" block (e.g. `*.length`) can behave differently.  Instead of emitting a block with no sockets, it creates a block with one socket.  It does not create a socket for the property (e.g. `.length`) but it does create a socket for the object (e.g. `getText()`).

Similarly, for a known "call expression" block (e.g. `.toUpperCase()`), instead of emitting a block with no sockets, it instead creates a block with one socket for the `callee.object` (e.g. `toUpperCase()`) though not one for the `callee.property` (e.g. `.toUpperCase()`.

This approach is generalized to apply to all known blocks that we pass into Droplet.

#### Precedence

The new blocks are created with a precedence level of `3`.  This was hand-chosen as it seemed to work best for adding parentheses only when needed.  This way, code like `("Hello " + "world").toUpperCase()` will still have parentheses around the `"Hello " + "world"`, while code like `getText("id").toUpperCase()` won't have them added to look like `(getText("id")).toUpperCase()`.  I'm not a big fan of this specificity, but the existing code uses a hard-coded `10` in four places (e.g. [here](https://github.com/droplet-editor/droplet/blob/bc724da8880b278388051e5f0f7f2ddd36e005fc/src/languages/javascript.coffee#L534)) so there is some, ahem, precedence for this approach in Droplet. 

This explicit precedence helps Droplet know whether to add parentheses or not, once the block has been dragged in.

#### An experiment

Because I'm not familiar with the broader implications of this change, it's only enabled if the caller passes `createSocketForKnownBlock: true` when initializing Droplet.  The remainder of this PR wraps this parameter in an experiment also named `createSocketForKnownBlock`.  

To enable the experiment, append `?enableExperiments=createSocketForKnownBlock` to the URL of a relevant page, e.g. an App Lab project page.  To disable it again, append `disableExperiments=createSocketForKnownBlock`.

When disabled, there should be no change in existing Droplet behavior.

### Before & After

For this simple set of test code:

```
// No parentheses.
if (getText("id").length) {
}
// No parentheses.
if ("Hello world".length) {
}
// Parentheses.
if (("Hello " + "world").length) {
}
// No parentheses.
if (getText("id").toUpperCase()) {
}
// No parentheses.
if ("Hello world".toUpperCase()) {
}
// Parentheses.
if (("Hello " + "world").toUpperCase()) {
}
// Unknown member gets parentheses.
if ((getText("id")).extra) {
}
// Chaining together multiple calls.
var str = "a";
var x = str.toLowerCase().toUpperCase();

```

#### Before
Screen Shot 2022-05-04 at 9 34 07 AM

#### After
Screen Shot 2022-05-04 at 9 34 26 AM

Note that the "Unknown member gets parentheses" example, in both cases, has those parentheses added by Droplet after the `getText` block is dragged in.

As a point of curiosity, the parentheses are sometimes "fixed up" after clicking away from a newly-placed block, as can be seen here:

https://user-images.githubusercontent.com/2205926/166601558-7ad995f9-68b1-4d6c-abd0-98b46c3ad4f9.mov

### Evaluation

We've done some preliminary testing and are feeling fairly confident with this change, but the ask is on the curriculum team to evaluate this experiment across all known Droplet scenarios, and then we can decide whether it should be made public for all users.

### CODE REVIEW

**Review by KylieModen — APPROVED** [review]
LGTM, will be good to test under the experiment before shipping more broadly - if we do still have risk concerns after internal testing, we can consider sharing the experiment more broadly, or shipping in summer down time when less students/teachers would be impacted

**Review by davidsbailey — COMMENTED** [review]
nice job delving into the world of Droplet, Brendan! I'm afraid this is not a current area of expertise for me, so I'll have to defer to the starlabs team for sign off. if the team as a whole feels stuck on this and wants an outside person to dig in with, please let me know.

**Comment by mikeharv** [comment]
I don't have expertise here either, but I did pull these changes and do some testing locally. With the experiment enabled, I repo the intended fix for inserting `getText("id")` into the socket of the `.length` property. It also fixes the same case with other functions, such as `getImageURL("id")`, `getNumber("id")` and even student-defined functions like `myFunction(n)`. Not that this all works now regardless of what the functions return, which I believe is a good thing. 
Unfortunately, I don't get the same results for other method blocks that have sockets for strings, e.g. `.toUpperCase()`. I'd expect to be able to other functions in their sockets in the same way. However, the result is the same original error: `Uncaught Error: Could not retrieve location n, blockStart` 
See video:

https://user-images.githubusercontent.com/43474485/164263432-9f8fca49-22bb-496b-a8b4-1f3ebb27ce89.mp4

It seems like a step in the right direction to get `.length` working as you have. I wonder if the work to handle the other case (method blocks with sockets) is complex enough to push to a follow-up issue.
Perhaps worth noting, I don't know how to pull and test the related changes at
* https://github.com/droplet-editor/droplet/pull/226
However, it doesn't seem like I needed to in order to test the changes with this PR. Is that expected?

**Comment by breville** [comment]
> Not that this all works now regardless of what the functions return, which I believe is a good thing.

@mikeharv Thanks so much for this testing!

> Unfortunately, I don't get the same results for other method blocks that have sockets for strings, e.g. `.toUpperCase()`

Great catch!  

I have updated this PR with a change that does seem to cover that case: 

Screen Shot 2022-04-27 at 5 31 36 PM

Again, my confidence that this covers all the edge cases remains low.  It would be great if you could similarly exercise this change.

> Perhaps worth noting, I don't know how to pull and test the related changes at https://github.com/droplet-editor/droplet/pull/226

Ah, that PR contains the necessary changes to Droplet.  We don't have our own fork of Droplet, so we are currently tracking our changes in a [`code-dot-org` branch](https://github.com/droplet-editor/droplet/tree/code-dot-org) on that repo.  I rebuilt Droplet with those changes, and have taken a snapshot of the output which is then part of this PR, specifically the files in `apps/lib/droplet`.  So, by testing this PR, you are effectively testing those changes; we just need that PR to keep our branch of Droplet as the source of truth for what we snapshot into our repo.

**Comment by mikeharv** [comment]
Pulled again and tested some more. It looks to be working great! Thanks for digging in some more.

**Comment by mikeharv** [comment]
I was able to find one additional case that doesn't currently work, when using blocks to compose something like:
```
var x = str.toUpperCase().toLowerCase();
```

This might not be an expected convention taught in the curriculum, but considering it works fine in text mode, it feels like it would be good to support it here as well.

**Review by mikeharv — APPROVED** [review]

**Comment by breville** [comment]
> I was able to find one additional case that doesn't currently work

We paired up and discovered the experiment had become disabled.  Once enabled, it worked as desired.

**Comment by breville** [comment]
I've updated the PR description to cover the latest implementation.  

(Thanks to @mikeharv for lots of testing along the way.)

**Pull request merged**
