### PR TITLE
Only show hoc2015x avatar for approved scripts

### PR DESCRIPTION
**Pull request by Hamms**
For star wars levels in CSF, we want to show Rey's face only in the Markdown Instructions content, not in the instructions column itself.

Before

image

After

image

### CODE REVIEW

**Comment by breville** [comment]
Out of curiosity, does it make sense to show the face twice in any script?

**Comment by Hamms** [comment]
I don't think it does; we only added the face to the instructions content for CSF because we planned on removing it from the column with this

**Comment by ryansloan** [comment]
@breville  - Some context if you're curious. We reached an agreement with Disney Lucasfilm to use this theme in our curriculum, but that means being able to edit some kinds of content without going through their approval process (hints, feedback messages, etc.) To satisfy that, we've moved the Disney characters into the instructions bubble with a quoted, pre-approved string. This way it doesn't look like they're saying all the other stuff we change. This won't impact HOC tutorials, just the stuff that's inside CSF.

**Comment by breville** [comment]
Thanks.  Just wanted to make sure we weren't shipping a variant of the "before" case anywhere in which we showed the same face twice.

**Pull request merged**
