### PR TITLE
move funometer to code-studio

### PR DESCRIPTION
**Pull request by Bjvanminnen**
I've been working on moving all of our dashboard/assets/js into code-studio. This moves the funometer logic.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @Hamms

**Comment by ashercodeorg** [comment]
Does this mean all users load admin-only JS? Is something we should try to avoid?
(per previous comment from Elijah to me)

**Comment by Bjvanminnen** [comment]
All users do load this. Which was true in the past as well. If they shouldn't, we could create a separate bundle for this JS.

**Comment by ashercodeorg** [comment]
LGTM. We should definitely consider creating an admin-only JS bundle (including not just this file but also others [after being moved over to code-studio]).

**Pull request merged**
