### PR TITLE
AnnouncementsCollapsible container for the Teacher Homepage

### PR DESCRIPTION
**Pull request by Erin007**
AnnouncementsCollapsible container for the Teacher Homepage. This component renders one Announcement in one CollapsibleSection. 

announcements collapsible

NOTES: 
- Announcements are passed into this component in an array because eventually this component will need to render an Announcements Carousel that can scroll through many announcements. This iteration will be a placeholder on the Teacher Homepage layout.

### CODE REVIEW

**Comment by Erin007** [comment]
cc: @tanyaparker @joshlory

**Comment by Erin007** [comment]
This is the last of these CollapsibleSection container components.

**Comment by breville** [comment]
It might be worth finding a way to crop the image so that the aspect ratio is always correct.  This gives a little more protection against editors providing an incorrectly-sized image, and saving them from having to crop extremely carefully in a paint program before supplying it.

**Comment by Bjvanminnen** [comment]
based on the screenshot, i wonder whether we want some padding atop of our header?

**Pull request merged**
