### PR TITLE
Delete Unused Pegasus and Dashboard CSV Scripts

### PR DESCRIPTION
**Pull request by sureshc**
Speculative fix for `CdoTutorials can't be referred to` [HoneyBadger Errors](https://app.honeybadger.io/projects/34365/faults?q=occurred.after%3A%2224+hours+ago%22%E2%80%83environment%3A%22production%22%E2%80%83CdoTutorials++&sort=last_seen_desc).

Is the definition of the the Class `DB` in `bin/pegasus-csv` being used in this line sometimes: https://github.com/code-dot-org/code-dot-org/blob/d71e4d588cb17cd20c41f9e9bc5d94fbe72e3f61/pegasus/src/database.rb#L32

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by cat5inthecradle — APPROVED** [review]
I'm willing to do a scream test, but do we have any mechanism of logging usage of these scripts?

**Comment by elf-code** [comment]
Are the honeybadger errors indicative that these scripts are being used?

**Comment by Hamms** [comment]
This seems like a long shot to me. I'm not opposed to cleaning these up if it's on the basis that they're unused, but I don't see any connection between these scripts and the error we've been seeing.

@bencodeorg I see you touched these files in the past; do you have any insight into whether or not they're still being used?

**Comment by bencodeorg** [comment]
Sorry @Hamms I have 0 recollection here...

**Pull request merged**
