### PR TITLE
Adds NetSim.debouncedResizeFooter as a passthrough

### PR DESCRIPTION
**Pull request by Hamms**
To the local "static" netsimDebouncedResizeFooter method. So that
NetSimLobby can resize the footer after asyncronously retrieving the
lobby data and rending itself appropriately.

### CODE REVIEW

**Comment by Hamms** [comment]
### Before
image
### After
image

**Comment by islemaster** [comment]
Let's run this by @sfilman .  I'm wondering if we'd prefer to reduce the height of the whole lobby panel so the footer fits underneath it, or at least making the footer width take the additional left offset into account so it really lines up with the instructions column (right now it looks like some padding isn't being taken into account).

I'm fine with the way you've provided access to the debounced re-layout function though.

**Comment by Hamms** [comment]
Whatever we do, I'd prefer to do it consistently between Connected and Disconnected mode; if we decide to make the footer fit by raising everything up rather than by shrinking it to the left, I'd like to also do that in connected mode.

**Comment by sfilman** [comment]
I don't want to reduce the height of the whole lobby panel because then
we're losing vertical real estate benefit of having a 1/3 footer. Do think
we should make the gray align in the lobby with the instructions column.

**Comment by Hamms** [comment]
I can make the resize script clever enough to deal with the padding and offset differences, definitely.

**Comment by islemaster** [comment]
:frowning: Sorry, I wasn't thinking clearly about the 'align with instructions column' thing.  I forgot that the lobby is limited width and floating centered, it actually seems a little silly to line the footer up with the instructions column; that would make the footer very wide on larger screens, which doesn't seem great either.

Maybe it's the best we can do for now though? :grimacing: Sorry for the clumsy layout.

**Comment by Hamms** [comment]
Oh, it's not strictly aligned with the instructions, just using them to set a max width

**Comment by Hamms** [comment]
Better alignment:

image

**Comment by Hamms** [comment]
And because this is using maxWidth, this is what the footer will look like normally:

image

**Comment by Hamms** [comment]
@sfilman Brad's out, so the right of final approval goes to you :trophy:

**Comment by sfilman** [comment]
Looks good!

**Pull request merged**
