### PR TITLE
Codebridge: update continue button visibility logic

### PR DESCRIPTION
**Pull request by molly-moen**
We decided that if a level has already in the passed (green bubble) state when loading, the continue button should show up without any additional user action (passing validation for a validated level or running and editing code for a non-validated level). This PR implements this behavior. This only impacts Codebridge labs.

## Links

- jira ticket: [CT-890](https://codedotorg.atlassian.net/browse/CT-890)

## Testing story
Tested locally

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by Erin007 — APPROVED** [review]
Logic makes sense to me and looks good. Are there tests for any of this behavior yet?

**Comment by molly-moen** [comment]
> Logic makes sense to me and looks good. Are there tests for any of this behavior yet?

@Erin007 there's a UI test that tests the continue button showing up [here](https://github.com/code-dot-org/code-dot-org/blob/f905e8fa7e5e4e8a14070322da3a48ebd79b3d89/dashboard/test/ui/features/code_tools/pythonlab/pythonlab_run.feature#L17). Since this feature requires reloading a level I didn't think it made a ton of sense to add a slow UI test, and I'm had trouble setting up unit tests since we need progress to be populated correctly in redux which is...complicated.

**Comment by Erin007** [comment]
Gotcha! Makes sense to me. Absolutely not blocking on this, but noting for general consideration that maybe the most complicated things are the ones most in need of tests (or overhauling) 😅

**Comment by molly-moen** [comment]
> Gotcha! Makes sense to me. Absolutely not blocking on this, but noting for general consideration that maybe the most complicated things are the ones most in need of tests (or overhauling) 😅

totally! I will spend some time as a follow-up to try and get some better testing on this component.

**Review by thomasoniii — APPROVED** [review]
lgtm 🚀

**Pull request merged**
