### PR TITLE
Maker: Add tempSensor.F and tempSensor.C to toolbox

### PR DESCRIPTION
**Pull request by islemaster**
_To be merged after https://github.com/code-dot-org/code-dot-org/pull/14137._

Adds `tempSensor.F` and `tempSensor.C` read-only properties to the toolbox.  These properties already existed and were usable, we just weren't making them obviously usable.

Also removes  `tempSensor` from some places it was being used incorrectly:

* Stops augmenting the `Thermometer` component with the `addSensorFeatures` method - these were in a broken state anyway, the thermometer should be interacted with differently.
* Removes `tempSensor` from the `SENSOR_VARS` list, which removes it from dropdowns/autocomplete for other sensor methods like `[Sensor].getAveragedValue()`.

Finally, in several places where we list all board components (one way or another) I had `tempSensor` listed between `soundSensor` and `lightSensor`, two components that have a lot more in common with one another than with `tempSensor`.  I moved it to after `lightSensor` in these cases just to keep things organized.

### CODE REVIEW

**Comment by davidsbailey** [comment]
👀 looking...

**Comment by islemaster** [comment]
My goal is to stop treating `tempSensor` like a sensor - in fact, if we can get permission from curriculum maybe we can change it to `thermometer`.

We're no longer supporting tempSensor with `getAveragedValue` and `setScale` in part because it's unclear what these should do for a sensor that already exposes both Fahrenheit and Celsius (and unadvertised, Kelvin) values.

It's probably a bug that `soundSensor.value` doesn't have a dropdown to select `lightSensor` - I'll fix that.

**Comment by davidsbailey** [comment]
Sounds good. +1 for renaming tempSensor to thermometer if you can get permission. Seems like we could do the thing where we let `tempSensor` keep working but remove it from the UI after the rename if needed.

**Comment by islemaster** [comment]
It's apparently an existing issue that the `objectDropdown` option doesn't work for "property" blocks.  The same problem manifests with the `buttonL.isPressed` and `buttonL.holdTime` blocks, which should have a dropdown for which button is being checked.  I assume this will be a droplet-level fix that needs to happen separately.

**Comment by islemaster** [comment]
Okay, met with @mrjoshida and @poorvasingal about this and the plan of record for now is to leave `tempSensor` named as-is but to break the other sensor-related blocks out so that each sensor gets its own set of blocks (e.g. `soundSensor.value` _and_ `lightSensor.value`) and it's not so weird that we're treating `tempSensor` differently.  PTAL.  My goal is to ship this tomorrow so that Josh can rework related curricula on Wednesday.

**Pull request merged**
