### PR TITLE
get rid of level created for testing purposes

### PR DESCRIPTION
**Pull request by Bjvanminnen**
This level got created when I was testing something on LB, and should not have been committed.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
What happens to the associated DB entry (`levels`, `user_levels`, and such)?

**Comment by Bjvanminnen** [comment]
I think they still end up existing

**Comment by ashercodeorg** [comment]
What do we gain from removing the level, then?

**Comment by Bjvanminnen** [comment]
Seems dirty to have things that say "DONTCOMMIT" in our repo. Perhaps makes it more explicit that the level is not in use (though the name should already accomplish that).

 I dont feel super strongly about this. Would you prefer I jus t leave it?

**Comment by ashercodeorg** [comment]
Not necessarily, I'm just asking questions. Really, I'd like to have a way delete a level across all environments (both file and DB), as well as associated DB entries. Do as you please...

**Pull request merged**
