### PR TITLE
Restore "Use commit-specific sources directory on test environment"

### PR DESCRIPTION
**Pull request by davidsbailey**
Reverts code-dot-org/code-dot-org#22195, restoring code-dot-org/code-dot-org#22097

### CODE REVIEW

**Comment by sureshc** [comment]
When I merged this, it caused problems on the `test` environment because VCR had cached old URLs to S3 objects from previous test builds, I think.  I am not familiar with VCR.  Do we need to take steps to flush that VCR cache?

**Comment by davidsbailey** [comment]
The VCR problem you listed in the revert PR was that a unit test was trying to access sources/commithash/1/1 . In https://github.com/code-dot-org/code-dot-org/pull/23427/commits/2cc6da521de8a626e8f2b4dea6ec64abdf2bfe90 I've stubbed CDO.sources_s3_directory to use sources_test, without any commit hash, and explained how that relates to UI tests in the comments. does that help?

**Comment by davidsbailey** [comment]
a bit more about VCR can be found here: https://github.com/code-dot-org/code-dot-org/blob/staging/shared/test/README.md#using-vcr

**Comment by sureshc** [comment]
Ah!  I understand, now.  Thanks!

**Comment by davidsbailey** [comment]
CC @islemaster

**Pull request merged**
