### PR TITLE
Creates the user_profiles table.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This table is being created so that PLC can store PD information about CSP teachers, with an eye towards more general usage. It is expected to undergo significant iteration as its population, usage, and reporting get better understood.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @aoby @Hamms

**Comment by aoby** [comment]
LGTM

**Comment by mehalshah** [comment]
Sorry - I didn't get a chance to look at this until now.

I feel a little iffy about multi-column solution to this. It means that whenever we launch a new course, we have to add a column to this table. 

Could this just be a json blob with serialized properties? Or is this something that we are doing a lot of indexing on?

**Comment by ashercodeorg** [comment]
In terms of maintainability, I've been very explicitly told not to care for this. The intent is to get something into the hands of PLC as quickly as possible, without concern for long term solution.

In terms of JSON blob, that doesn't work for a myriad of reasons. Though blobs work fine in Ruby, they do not work well with SQL (Redshift / Tableau) analysis, the purpose of this table.

**Pull request merged**
