### PR TITLE
I18n sync HOC 09/09

### PR DESCRIPTION
**Pull request by Hamms**

### CODE REVIEW

**Comment by Hamms** [comment]
Looks like a handful of languages didn't get included in https://github.com/code-dot-org/code-dot-org/pull/30404, for some reason; see https://hourofcode.com/nl/gb/promote for an example of lingering ERB that will be removed by this sync.

**Comment by bethanyaconnor** [comment]
Weird, I'm not sure what happened :/

**Review by bethanyaconnor — APPROVED** [review]

**Comment by Hamms** [comment]
Looks like I had the same errors you had. The "no" one makes sense, since YAML will usually treat that as a bool rather than a string, and there's probably just one part of our system that isn't aware of that. I have no idea what's up with the fa/af thing.

**Comment by nkiruka** [comment]
Does "no" need to be in quotes so YAML doesn't treat the string as bool?

**Review by nkiruka — APPROVED** [review]

**Comment by Hamms** [comment]
> Does "no" need to be in quotes so YAML doesn't treat the string as bool?

Yep!

**Pull request merged**
