### PR TITLE
Fix stage_extras persistence on section create.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Any idea what the cause of the test failures is? In particular, I have no idea why the error dialog is popping up (e.g., see https://saucelabs.com/beta/tests/86bf780569d0498e9fc81d45f12684ae/commands#65).

**Comment by aoby** [comment]
:( This is the unhelpful [genericError](https://github.com/code-dot-org/code-dot-org/blob/76e0de488bf6a90bdbe229fe574e82bd6b5b0532/pegasus/sites.v3/code.org/public/teacher-dashboard/index.haml#L215-L215) dialog displayed here for nearly all errors.

You can display the error details, or for debugging log to console, etc, like [this](https://github.com/code-dot-org/code-dot-org/blob/76e0de488bf6a90bdbe229fe574e82bd6b5b0532/pegasus/sites.v3/code.org/public/teacher-dashboard/index.haml#L312-L318)

**Comment by aoby** [comment]
I know from playing around trying to upgrade ActiveModelSerializers (ours are a specific very outdated pre-release version), that the teacher dashboard is extremely sensitive to minor data format changes (such as [] vs. nil), and there are no unit tests :(

**Comment by ashercodeorg** [comment]
Unfortunately, I can't reproduce the error locally, the workflow works as expected (persisting as expected to the DB) without any JS errors. Am I stuck debugging through SauceLabs and CircleCI?

**Comment by aoby** [comment]
That is unfortunate. You could modify genericError to display the error details, and/or log them to the console and re-run the tests in circle perhaps.

**Comment by ashercodeorg** [comment]
Fixing `nil` vs. `false` took embarrassingly long to debug. Merging (though feel welcome to take another look).

**Pull request merged**
