### PR TITLE
Add admins from census

### PR DESCRIPTION
**Pull request by bencodeorg**
Adds the submitter role from census forms to the `submitter_role` field in `contact_rollups`. Validated locally by downloading `census_submissions` and `forms` data and noted that submitters who identified themselves as administrators were being captured correctly in `contact_rollups_daily`.

### CODE REVIEW

**Comment by jeremydstone** [comment]
Noting for posterity that census `submitter_role` unique values in production data at this time are:
NULL,'TEACHER','OTHER','PARENT','VOLUNTEER','ADMINISTRATOR'

Unique values in the `contact_rollups.form_roles` production data prior to this PR are:
NULL, 'student', 'other', 'parent', 'educator', 'engineer', 'student educator', 'teacher', 'principal', 'district_admin', 'superintendent'

The lowercasing in this PR of `submitter_role` is important for consistency.

The `submitter_role` values mostly align with our other roles from forms, with the exception of the new `administrator` role. So this is pretty consistent within our already freeform data on form submitter roles.

This looks fine, just wanted to capture the lay of the data landscape in this PR.

**Comment by bencodeorg** [comment]
Good point to document, thanks Jeremy. I think a next step would be to roll up all of those `form_roles` that indicate an administrator (e.g., district_admin, superintendent, administrator) into a single "Administrator" role in `roles`.

**Comment by jeremydstone** [comment]
@bencodeorg if you haven't already, could you please test with data with a NULL `census_data.submitter_role` against a contact that has a form submitter role from the forms table. We want to make sure that the code that concatenates `census_data.submitter_role` onto the existing `form_roles` works correctly if there is NULL value and doesn't wipe out existing values. The bug to look out for here is that in SQL, CONCAT(value, NULL) is NULL, so if you accidentally CONCAT a NULL value you will nuke the thing you are appending to and actually lose data. Please double-check that can't happen here.

**Comment by bencodeorg** [comment]
Confirmed that census submitters who left `submitter_role` = NULL are not overriding `form_roles` collected elsewhere.

**Pull request merged**
