### PR TITLE
Add Bounce, Basketball & Sports project pages

### PR DESCRIPTION
**Pull request by joshlory**
Copied levels from `bounce_12.level`, `bounce_12_basketball.level` & `bounce_12_sports.level`.

### CODE REVIEW

**Comment by joshlory** [comment]
+cc @poorvasingal

**Comment by poorvasingal** [comment]
Nice! This is the last of the projects, right? We're done after this?

**Comment by joshlory** [comment]
Yep!

**Comment by joshlory** [comment]
This wouldn't have been possible without all the work @Hamms has done to create level models for each of these new level types.  For example: PR https://github.com/code-dot-org/code-dot-org/pull/16065.

**Pull request merged**
