### PR TITLE
PL: Regional partner search shows less for closed workshops

### PR DESCRIPTION
**Pull request by breville**
When a regional partner is closed for workshop applications, show less.  In particular, the "Scholarship, discounts, and cost information:" heading and its grey box of content is not shown.

Also, the "Or, apply directly now!" link that was permanently at the top of the page is permanently removed.

### before
Screenshot 2019-07-18 00 45 35

### after
Screenshot 2019-07-18 13 58 55

### CODE REVIEW

**Review by islemaster — APPROVED** [review]
:+1: Thanks for taking this one!

**Review by agealy — CHANGES_REQUESTED** [review]
Can we leave in the "Additional Program Information" heading and populated text? The screenshot in the spec was for a school with a blank entry for this field, so I overlooked that this second field existed. We may want to revisit this page soon once I've taken a closer look at the funnel, but I think it makes sense to let partners choose what to show here. It seems they use it for a variety of purposes, but none that I've seen appear overly confusing while applications are closed.

**Comment by breville** [comment]
Thanks for catching that @agealy.  Updated.

**Review by agealy — APPROVED** [review]
LGTM, thanks for the update

**Pull request merged**
