### PR TITLE
Add Amplitude events to the CFU summary page

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Fires an Amplitude event when the CFU page is loaded, when the "Back to Level" link is clicked, and when the "Next Level" link is clicked. 

Example event when the page is loaded:
```
[AMPLITUDE ANALYTICS EVENT]: Summary Page Loaded. Payload: {"payload":{"levelId":34773,"levelType":"FreeResponse","lessonName":"Decomposition and Design","lessonId":134369,"unitName":"csa1-2022","unitId":13555,"curriculumUmbrella":"CSA"}}
```

Example event when "Back to level" is clicked:
```
[AMPLITUDE ANALYTICS EVENT]: Summary Page Back To Level Clicked. Payload: {"payload":{"levelId":34773,"levelName":"CSA U1L12-L5_2022","levelType":"FreeResponse","lessonName":"Decomposition and Design","lessonId":134369,"unitName":"csa1-2022","unitId":13555,"curriculumUmbrella":"CSA"}}
```

Example event when "Next level" is clicked:
```
[AMPLITUDE ANALYTICS EVENT]: Summary Page Next Level Clicked. Payload: {"payload":{"levelId":36783,"levelName":"CSD game variable predict_2022","levelType":"FreeResponse","lessonName":"Variables","lessonId":179909,"unitName":"csd3-2022","unitId":18516,"curriculumUmbrella":"CSD"}}
```

## Links

[TEACH-349](https://codedotorg.atlassian.net/browse/TEACH-349)
[TEACH-383](https://codedotorg.atlassian.net/browse/TEACH-383)

## Testing story

I didn't include a test here because it's a pretty straightforward change and testing useEffect is a little tricky. If folks think a test would be useful here, let me know and I'll take a look.

### CODE REVIEW

**Review by rshipp — APPROVED** [review]
lgtm. sorry for missing the last pr

**Comment by dju90** [comment]
Do amplitude events get fired locally? E.g., how did you get the example events in your PR description?

**Comment by bethanyaconnor** [comment]
@dju90 They get printed to the console but we don't actually send the event to the Amplitude service locally

**Comment by dju90** [comment]
Do I need to do anything locally to make sure the Amplitude event gets printed to the console? I've tried loading a couple of Free Response summary pages, but no Amplitude event appears in the console for me.

**Pull request merged**
