### PR TITLE
IE10 has issue with Symbol

### PR DESCRIPTION
**Pull request by Bjvanminnen**
Not entirely clear to me what using a Symbol here gets us anyways.

PR is against test with the goal of hopefully being able to get this out to prod sooner

### CODE REVIEW

**Comment by islemaster** [comment]
:shipit: :+1: LGTM.

**Comment by Bjvanminnen** [comment]
Tested against IE10 on SauceLabs.

**Comment by Bjvanminnen** [comment]
@pcardune as an FYI as the regression was caused by https://github.com/code-dot-org/code-dot-org/commit/2f013f0d9fa2f0e1bb3f06a4499a763cc146d189

**Comment by pcardune** [comment]
😢

**Pull request merged**
