### PR TITLE
Upgrade react-tooltip

### PR DESCRIPTION
**Pull request by maddiedierker**
Pulled out of #41582 as it doesn't depend on the React upgrade. Manually verified some tooltips in teacher dashboard after the upgrade.

This upgrade was causing an LP UI test to fail (level_group_multi_page_dots.feature) when inspecting progress in the dropdown. We manually verified the behavior is working as expected and decided to comment those steps out for LP to investigate later ([Slack thread](https://codedotorg.slack.com/archives/CA3KCSGTD/p1628629286025600) / [LP Jira follow-up task](https://codedotorg.atlassian.net/browse/LP-1988)).

### CODE REVIEW

**Comment by Erin007** [comment]
The Drone failure here is: learning_platform/level_types/level_group_multi_page_dots again which means maybe you've isolated the issue?

**Comment by maddiedierker** [comment]
yes! still confused as to why this upgrade causes the failure, but it's consistent, so i think we've found the root cause. this upgrade isn't essential to getting react upgraded, so i think we can pause on this or have LP revisit separately

**Review by Erin007 — APPROVED** [review]
Wahoo!

**Review by maureensturgeon — APPROVED** [review]
Thanks!!

**Pull request merged**
