### PR TITLE
Try enabling `extendedDebugging` in Sauce Labs for Chrome latest

### PR DESCRIPTION
**Pull request by joshlory**
Sauce Labs feature: https://wiki.saucelabs.com/pages/viewpage.action?pageId=70072943

### CODE REVIEW

**Comment by joshlory** [comment]
Unfortunately this is failing CircleCI 🙁.  I'm not sure it's worth investing more investigation time now.

**Comment by islemaster** [comment]
Trying again after talking with Sauce Labs and hearing this might have been a temporary issue on their end.

**Comment by islemaster** [comment]
Hey, this passed!  And here's some sample output: https://saucelabs.com/beta/tests/2f3318b7a2c3437094ef7a2a1c7b2d68/logs

```
  {
    "url": "http://localhost.code.org:3000/teacher-dashboard",
    "logs": [
      {
        "type": "debug",
        "args": [
          {
            "type": "string",
            "value": "Download the React DevTools for a better development experience: https://fb.me/react-devtools"
          }
        ],
        "timestamp": 1527724713980.6
      }
    ]
  },
```

image

**Comment by islemaster** [comment]
Passed again!  Shall we merge it?

**Pull request merged**
