### PR TITLE
Convert JoinSection clickable div to button

### PR DESCRIPTION
**Pull request by hannahbergam**
This is a standard case of just removing the useDeprecated tag! The button looks mostly the same before and after (pics below) but now I'm able to tab over to it and I added a pic of the inspect/devtool so that you can see now it's nested in a button! I also tested valid and invalid join codes to make sure the click function works.

In these images, the only difference I can detect is this minor shadow/highlight in the two versions.

Before (disabled, then not):
Screen Shot 2022-12-12 at 12 36 47 PM

Screen Shot 2022-12-12 at 12 18 24 PM

After (disabled, then not):
Screen Shot 2022-12-12 at 12 36 53 PM

Screen Shot 2022-12-12 at 12 24 55 PM

Fun bonus pic of the new button tag:

Screen Shot 2022-12-12 at 12 25 07 PM

## Links

- spec: []()
- jira ticket: https://codedotorg.atlassian.net/browse/A11Y-78

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by epeach** [comment]
Love it! Is there a visual change on hover?

**Comment by hannahbergam** [comment]
> Love it! Is there a visual change on hover?

Ah yes I should've noted! There's no difference- both turn all white (so there isn't even a weird shadow/highlight change)

**Review by epeach — APPROVED** [review]
excellent

Excellent - love how easy that was!

**Comment by hannahbergam** [comment]
> excellent [ excellent ](https://user-images.githubusercontent.com/2959170/207156726-dca6ceae-153b-4d1f-87d0-ed7cd06a2af8.gif) [ ](https://user-images.githubusercontent.com/2959170/207156726-dca6ceae-153b-4d1f-87d0-ed7cd06a2af8.gif)
> 
> Excellent - love how easy that was!

Yesss! The only hiccup- there's a ui test file looking for the clickable div 🤦🏻‍♀️ so I updated those instances!

**Pull request merged**
