### PR TITLE
Move the "required" asterisk to the beginning of labels

### PR DESCRIPTION
**Pull request by joshlory**
Context: https://codedotorg.slack.com/archives/C0T10H26N/p1556036007137300

Follow up to PR https://github.com/code-dot-org/code-dot-org/pull/27841

Sample before:

image

Sample after:

image

### CODE REVIEW

**Review by clareconstantine — APPROVED** [review]

**Comment by clareconstantine** [comment]
Thanks Josh!

**Review by Hamms — APPROVED** [review]
LGTM, but it might be nice to DRY this up a bit and make a reusable component for this

**Comment by breville** [comment]
I don’t think we should use the asterisk at the beginning of the line.  The convention of an asterisk in that situation is that you have to go find the asterisk at the end of some content that it’s designed to match to.

Also, we use asterisks to at the end of lines pretty consistent across our site (e.g. https://code.org/yourschool) and we should remain consistent.

**Comment by clareconstantine** [comment]
@breville I definitely agree on the consistency thing, but I think the when the asterisk is indicating there is more info at the bottom of the page, it's placed at the end of the line, and the extra info itself has it at the beginning.

**Comment by breville** [comment]
@clareconstantine Agreed, and I think I worded it poorly.  In our usage I think it's been this:

```
Please enter your name *
Please enter your address *

* required
```

**Comment by joshlory** [comment]
This is the difficult case: 
image

**Comment by joshlory** [comment]
image

- Option A: We can have the question be plain-text, and place the `*` at the end.
- Option B: We can use Markdown for the question, and find a different way to mark the question as "required".

Markdown _always_ produces a rectangle b(lock element) which it controls rendering inside of. We can choose to put the asterisk above, below, left or right of that square — but not inside it. Unless we treat the `*` as content not markup, which doesn't feel like a good option either.

Computers are hard!

**Comment by joshlory** [comment]
I'm excluding:
- Option C: We treat Markdown as inline in this one specific case.

... based on pushback from @Hamms and the fact that this causes issues if a label is ever more than one paragraph.

**Pull request closed without merging**
