### PR TITLE
Fix sad bee on lessons with an external markdown level

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Every lesson (in a migrated script) with an external markdown level gives a sad bee on the lesson plan page. This was introduced in #39628. The stack trace is below but the fix is to pass the user into `localized_replaced_markdown`, which requires passing the user from the controller down through the stack.

Stack trace of error:
```
ArgumentError at /s/coursef-2021/lessons/5
==========================================

> wrong number of arguments (given 0, expected 1)

app/models/levels/external.rb, line 61
--------------------------------------

ruby
   56       true
   57     end
   58   
   59     # returns a version of the markdown for this level in which
   60     # USER_ID_REPLACE_STRING is replaced by the current user's id
>  61     def localized_replaced_markdown(user)
   62       user_id = user.try(:id).to_s
   63       localized_markdown = localized_property('markdown')
   64       return localized_markdown.gsub(USER_ID_REPLACE_STRING, user_id)
   65     end
   66   


App backtrace
-------------

 - app/models/levels/external.rb:61:in `localized_replaced_markdown'
 - app/models/levels/external.rb:78:in `summarize_for_lesson_show'
 - app/models/script_level.rb:457:in `block in summarize_for_lesson_show'
 - app/models/script_level.rb:457:in `map'
```

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
This looks workable as a quick fix if needed, but what I'd recommend instead is to just gracefully handle a missing user, and not replace `<user_id/>` in the external level markdown in that case. from the example I can find, these only seem to appear in levels with survey in the name, which I am not sure we are even going to be showing in any 2021 lesson plans. 

if there isn't time to figure out whether that will work or not, then I'm fine with proceeding with this solution. hopefully automated tests will cover most of the callers of thes methods.

**Comment by bethanyaconnor** [comment]
A quicker fix that I thought of was to just use `localized_property('markdown')` here which wouldn't deal with the user id at all. If we don't need the user id replacement for 2021, that seems like a safer option to me. The potential impact would be that `<user_id/>` might be shown on the page.

**Comment by bethanyaconnor** [comment]
https://github.com/code-dot-org/code-dot-org/pull/39749 is the alternate fix I mentioned above

**Comment by bethanyaconnor** [comment]
Going to close in favor of #39749 now that I've had more time to think about it and based on the slack discussion

**Pull request closed without merging**
