### PR TITLE
Import Delaware Course Offerings

### PR DESCRIPTION
**Pull request by sureshc**
import delaware course offerings

### CODE REVIEW

**Comment by sureshc** [comment]
[Import Last of DE Schools](https://trello.com/c/YRn0v0yy/234-import-last-of-de-schools)

**Comment by bencodeorg** [comment]
Nice -- was working on this but you beat me to it! Wouldn't have known the `UNSPECIFIED_COURSE` constant, so that's good to know. Only question is that Liz said Delaware is not an "infer no" state, so we'd want to add DE to the `INFERRED_NO_EXCLUSION_LIST` right?

**Comment by bencodeorg** [comment]
Kind of an interesting case because Liz has some schools in this import listed as explicit no's, but I don't think we have a mechanism from importing a subset (instead of all non-yes's) of schools as explicit no's?

**Review by bencodeorg — APPROVED** [review]
Looks good -- so I guess we'll ignore the explicit no's that Liz noted in this file? Looks like 16 schools labeled explicitly as no. Maybe just advise her to make 16 submissions via the /yourschool page?

**Comment by sureshc** [comment]
Hmmm ... yes.  I’ll let her know.
Merging even though a UI test failed, because that is a known issue with the test and nothing in this Pull Request impacts our current set of UI tests.

**Pull request merged**
