### PR TITLE
Instructions: Truncate tabs

### PR DESCRIPTION
**Pull request by breville**
This change to `TopInstructionsHeader` causes the tab entries to truncate with ellipsis when the available space is very narrow, so that the user gets a glimpse of each tab.  Previously, the tabs' full text was shown, and the user would need to scroll the tab header horizontally to see them all.

Its impact is broad, and despite UI/Eyes tests passing, I'm uncertain as to how safe this is.

#### before
Screen Shot 2021-08-10 at 11 55 18 PM

#### after
Screen Shot 2021-08-10 at 11 49 10 PM

Chrome on macOS when hovering:

Screen Shot 2021-08-13 at 4 46 27 AM

### CODE REVIEW

**Review by maureensturgeon — COMMENTED** [review]
I'm a bit worried that students/teachers won't know what the tab is for if all they can see is "rev...", are there other alternative designs we can consider?

**Comment by maddiedierker** [comment]
what does the tab header look like as you're scrolling with this change? i'm interested to see how the ellipses-ed elements change/re-render as you're scrolling them into view, and how the scrollbar affects the experience (which would be a separate/existing thing unrelated to your change here)

**Comment by breville** [comment]
Good feedback.  The work item is [here](https://codedotorg.atlassian.net/secure/RapidBoard.jspa?rapidView=53&projectKey=CSA&modal=detail&selectedIssue=CSA-369), @markabarrett comments [here](https://app.slack.com/client/T039SAH7W/C01EF4GJ9GE/thread/C01EF4GJ9GE-1622055228.132600), and a screenshot of the scrollbar before this change is [here](https://github.com/code-dot-org/code-dot-org/pull/40768#discussion_r639944240).  The goal of this change is that the scrollbar will no longer show, because we'll always fit all the items into the visible space.  I'm pretty agnostic about this UI; CC @moneppo for thoughts.

**Review by maureensturgeon — COMMENTED** [review]
Another note, I see the work item describes adding a tooltip, should that be included here?

**Comment by breville** [comment]
> Another note, I see the work item describes adding a tooltip, should that be included here?

Yes, per internal discussion [here](https://codedotorg.slack.com/archives/C9MB4CL07/p1628753254001900), I've now added one potential approach.

**Review by maddiedierker — APPROVED** [review]
we may want approval/confirmation from LP about whether or not truncating the tabs will cause confusion for users, but the code changes here look good! thank you for adding the tooltip, too 😄

**Review by maureensturgeon — APPROVED** [review]
I don't want to block this effort, Amanda is worried about usability but I'll have her follow-up with CSA! Thanks for adding the tooltip

**Comment by moneppo** [comment]
Hi all,

I'm going to bring up this issue with Amanda and see if we can get an idea of what we ideally want, then figure out the best course of action based on that, Thanks for your patience here.

**Comment by moneppo** [comment]
Closing the loop on this - speaking with Amanda it seems we are good to use this truncation approach for Javalab as it improves the odd scrolling behavior we have today. The next step is to figure out a more consistent solution that ensures the names of the tabs are always readable; I'll be working with Amanda to put that plan together.

**Comment by breville** [comment]
Update: because this changes affects all instructions, not just JavaLab's, it's being paused until a definitive design is agreed upon.  (And we didn't want to fork the instruction behaviour further to do this only for JavaLab.)

**Comment by breville** [comment]
Closing for now, though folks are welcome to revive this work if desired.

**Pull request closed without merging**
