### PR TITLE
Feedback: log feedback expansions

### PR DESCRIPTION
**Pull request by Erin007**
[LP-525](https://codedotorg.atlassian.net/browse/LP-525) Metrics for feedback, partial 

Record an event when a feedback entry with a long comment is clicked on studio.code.org/feedback. One of the concerns of displaying the comments on the all feedback page was that it would be too cluttered; to alleviate this concern we collapse long comments. However, we want to gauge if students are actually expanding and reading the feedback.  This tracking will give us a better sense if that is happening.

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
Code changes look good.

I am not a statistician, but it seems like if you are going to measure how often the user is expanding a collapsed feedback message, then you might also need to measure how often they are being presented with one to click on.

I would recommend writing up a brief list of what you plan to record so that someone from the data team can review, to help catch any problems making the connection from what we're recording to whatever conclusions we're trying to draw.

**Comment by Erin007** [comment]
From the [spec](https://docs.google.com/document/d/1anY8vf8KKSGP_p88KAmUlTR3HVtMkoEQ9XGcUKynnmQ/edit#heading=h.b84yvdegc8bf)

**How many students go to the actual level to view the feedback?**
Direct query on teacher feedbacks. We have a visit count metric set up when a student views feedback on a level. 

**Total page views for the “Feedback” page** 
 Google Analytics

**How many students go to the feedback page?**
Google Analytics page views - _Can we differentiate between students and teachers here?_

**How many teachers leave feedback for their students on more than one level?**
Direct query on teacher feedbacks - for each teacher, count the number of unique script_level_ids associated with the feedback they've left and then count how many of those are > 1 

**How many teachers use the feedback / mini-rubrics feature?**
Direct query on the teacher feedbacks - count all of the unique teacher ids associated with feedbacks. For mini-rubrics, we'd first find all of the feedbacks that don't have null for performance (the rubric value) then count the unique teacher ids associated with those. 

**Clicks on the “View feedback” button in the banner vs. in the student account menu**
Student account menu is n/a at this time and we have Google Analytics to track button clicks from the "View Feedback" button in the notification (#30478)

**How long it takes for students to “see” and / or “read” feedback (difference in time between when feedback was first left by teacher and first viewed by the student)** 
Direct query on teacher feedbacks, diff between created at and student_first_visited_at OR seen_on_feedback_page_at (whichever is older)

**Segment to students who have used the feature at least once vs. those that haven’t**
Direct query on feedbacks -  unique student ids associated with feedback where seen_on_feedback_page_at is not null V. unique student ids associated with feedback where seen_on_feedback_page_at is null

**How much seen vs. unseen feedback do students have? (Point in time calculation)**
Direct query on feedbacks

@fontie715 or @bencodeorg is there anything else you'd like me to track?

**Comment by Erin007** [comment]
_I am not a statistician, but it seems like if you are going to measure how often the user is expanding a collapsed feedback message, then you might also need to measure how often they are being presented with one to click on._

Agreed.  The weird thing is that expandability is based on length, which in this case is really based on height, so how do I count the # of expandable comments without counting every time one of them is (re)rendered?

At least measuring clicks on the expandable feedbacks gives us a sense of whether students are doing it never or sometimes. I'm open to other ideas!

**Comment by davidsbailey** [comment]
good points, if you are just making sure that the feature is getting used then this could be enough.

**Pull request merged**
