### PR TITLE
Consolidate matrix question summaries: remove parent and prepend head…

### PR DESCRIPTION
**Pull request by aoby**
…er text to each sub-question's text

### CODE REVIEW

**Comment by mehalshah** [comment]
LGTM. I could see in v3 of the UI doing some fancy grouping, but until we do that this will be great

**Comment by bencodeorg** [comment]
@aoby how would i access the text of the response given this change (like what's in this screenshot?) Would I still need to go to the parent to get the possible options?

image

**Comment by aoby** [comment]
@bencodeorg those weren't present even in the parent. I'll add them in a followup.

Also @mehalshah and I were talking yesterday about simplifying this a bit and never assuming anything should be converted to a numeric value. I'll propose another simplification that preserves the raw text answers and provides the options...

**Comment by bencodeorg** [comment]
Ok great thanks, this is what you were probably trying to explain yesterday but couldn't get into my skull.

**Pull request merged**
