### PR TITLE
Adds a documentation skeleton of the Activity table in activity.md.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Let me know if this is the best format / place / etc. for this documentation (it very well may not be). If it is, I'll fill in descriptions for the fields, as well as create similar files for all the other dashboard tables.

Note that my understanding is that the header of activity.rb is automatically generated, otherwise it would make sense to place this documentation directly in the activity.rb header.

### CODE REVIEW

**Comment by mehalshah** [comment]
I'm not sure how valuable it is to have the raw output of desc in our codebase. I'd rather not have to maintain this every time our table changes.

I imagine there's some tool that generates a database diagram auto-magically from our tb, with relationships and keys mapped out nicely. If that's not really an option then I'm okay with this.

**Comment by Hamms** [comment]
In what way is this distinct from the Schema information in [activity.rb](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/activity.rb)?

**Comment by ashercodeorg** [comment]
Hamms: Not sure whether you are referring to the schema or the file. My answer is intended to be agnostic to your question.

The schema information is pretty similar to that in activity.rb. Probably it should be deleted, replacing it with a link to the activity.rb file.

The individual field comments (not yet populated) are not in activity.rb. Nor does there seem to be a convenient place to put them in activity.rb, given the schema is auto-generated. After the general format is approved, I'll fill that information in as part of this PR.

**Comment by Hamms** [comment]
I think I'm just confused as to why we're adding manual documentation when we already have automatic documentation. Is this part of some larger documentation effort?

To answer your original question, I believe the appropriate place for docs is the [/docs folder](https://github.com/code-dot-org/code-dot-org/tree/staging/docs)

**Comment by ashercodeorg** [comment]
The automatic documentation (both the schemas checked in and DESCRIBE my_table results) has been woefully insufficient for me to go about looking at and understanding the data (witness the frequency of questions I'm asking, noting that I'm only actually asking about the stuff I care about).

Thus, I'm trying to create documentation that explains usage (non-usage) of fields, undocumented assumptions, etc.

**Comment by Hamms** [comment]
Gotcha. In that case, I'm not sure where would be best for things like this to live. @philbogle?

**Comment by laurelfan** [comment]
My personal preference is to have any documentation about code to be a comment in the code and for documentation that's "not about code" to be in some other searchable, readable place (eg. a /doc directory, wiki, etc).

**Comment by laurelfan** [comment]
either way, I think some of our infrastructure assumes that stuff in /app is code (eg. in development mode, reloads classes when a file in /app changes) so it probably should be somewhere else if not in a comment in activity.rb

**Comment by philbogle** [comment]
Brainstorming on this a little bit:

Mysql supports comments on fields.  Suppose we let the database be the source of truth and ensured that our migrations add comments and that the annotate tool preserves them?

Might be a terrible idea, just thinking.

**Comment by ashercodeorg** [comment]
Phil: That seems optimal, I'm all for having the comments be as close as possible to the data. Should I plan on going that route?

**Comment by laurelfan** [comment]
That sounds like a great idea. If the annotate tool doesn't preserve them it should be easy to modify it so it does.

We should also make sure the comments end up in schema.rb.

**Pull request closed without merging**
