### PR TITLE
[AI Tutor] CT-544: Teacher Tab Updates

### PR DESCRIPTION
**Pull request by kakiha11**
Making updates to the Teacher Table and Tutor Tab, including:
- Formatting of timestamp to include just minute resolution
- Styling updates
- Adding the section toggle to the AI Tutor Tab

For now these features will only be exposed to pilot teachers. 

Screenshot 2024-05-08 at 12 38 12 PM

Screenshot 2024-05-08 at 12 38 27 PM

Tests showing update to section data in the database with using the toggle

Screenshot 2024-05-07 at 10 13 20 AM

image

## Links

Jira ticket: https://codedotorg.atlassian.net/browse/CT-544

## Testing story

- Added unit tests for the new `# POST /api/v1/sections/<id>/ai_tutor_enabled` route
- Updated existing redux tests related to sections
- Tested feature manually, including toggling AI tutor access for a single section and manually verifying that creating and editing other fields on the session appear unimpacted

## Follow-up work

Work with Teacher Tools and Design to decide on a long-term plan for the UI and functionality on the AI Tutor dashboard. Change styling of this toggle to match the others in the table. 

Even if there isn't a major overhaul, we should swap this to use the Design System toggle: https://codedotorg.atlassian.net/browse/CT-578

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by Nokondi — COMMENTED** [review]
Everything looks good, but just to confirm - do you have existing unit test coverage for these changes, or do you still need to create new unit tests or update existing unit tests?

**Comment by ebeastlake** [comment]
@Nokondi We do not have existing unit test coverage for these changes. We still need to create new unit tests for the new route. I filed a ticket for that here: https://codedotorg.atlassian.net/browse/CT-569. We'd like to have this feature for our pilot on May 20, so we have some test coverage tickets filed as fast-follows, but we defer to the Teacher Tools team on whether this feature is okay to merge without those unit tests.

**Comment by Nokondi** [comment]
Our general position is that unit tests should be added or updated before merging code; although we've had situations where we need to get something in at the last minute and add the tests later. My main concern is that we have other features that rely on the teacher dashboard component. @davidsbailey, what are your thoughts?

**Comment by davidsbailey** [comment]
I agree with what Mark said -- the best practice is to include unit tests in each PR. If you want to defer unit testing, I think it would be helpful to say why you think this is safe to do without putting other functionality at risk, e.g. "existing functionality X is covered by tests Y" or  "only piloters will hit codepath Z".

there is also the risk to your own feature, which runs the risk of breaking as you rush to get other features into the pilot, but I feel like it is fair for your team to manage that risk how you want to since it mostly affects your own team. we launched the fall pilot a bit light on UI tests and immediately ran into some blocking issues -- YMMV if you have neither unit tests nor UI tests.

**Comment by ebeastlake** [comment]
@davidsbailey Thanks for weighing in -- the only reason I'm proposing merging without tests is that only piloters (10 teachers) will hit the new backend code path, and this toggle is duplicated in the "edit section" area if it fails from the teacher dashboard. I'll add tests and reach out to Teacher Tools again when it's done!

**Comment by ebeastlake** [comment]
@davidsbailey @Nokondi Added unit tests for the new `/api/v1/sections/<id>/ai_tutor_enabled` route and updated the existing front-end tests related to sections. LMK how this looks!

**Review by Nokondi — APPROVED** [review]
Looks great! Thanks for adding the tests.

**Pull request merged**
