### PR TITLE
Fixed corrupted sound library filenames

### PR DESCRIPTION
**Pull request by kimj42**
- **Why** are we making this change?
   - Jira tickets: 
     - https://codedotorg.atlassian.net/secure/RapidBoard.jspa?rapidView=26&projectKey=STAR&modal=detail&selectedIssue=STAR-177
      - https://codedotorg.atlassian.net/secure/RapidBoard.jspa?rapidView=26&projectKey=STAR&modal=detail&selectedIssue=STAR-212
     - https://codedotorg.atlassian.net/secure/RapidBoard.jspa?rapidView=26&projectKey=STAR&modal=detail&selectedIssue=STAR-194
   - Filenames in the sound library should only have one underscore between each word, `hello_world.mp`
   - However, the recently updated sound library included 76 filenames that were corrupted:
      - majority of the files had double underscores, `hello__world.mp3`
      - few had underscores at the end of the filename, `hello_world_.mp3`
      - 1 file had spaces in between, `hello world.mp3`
   - Corrupted filenames don't match the current format of the existing sounds in the sound library dialog which makes it confusing for users if the filenames aren't consistent.
   
- **What** changed:
   - All of the corrupted formats above were fixed to match the existing sound formats to `hello_world.mp3`
    - In  [s3's cdo-sound-library](https://s3.console.aws.amazon.com/s3/buckets/cdo-sound-library/?region=us-east-2&tab=overview) the corrupted files were deleted but not permanently deleted so that the projects that used those corrupted filenames continue to work for users. For whatever reason, if these corrupted filenames need to be restored then the dev just needs to delete the "delete marker" on s3 to bring it back since cdo-sound-library has versioning enabled.
    - Fixed names were uploaded to the same cdo-sound-library so that the users now only see the fixed names only and no longer see the corrupted filenames. From now on, users will only have fixed names in their projects.
    - List of categories that were impacted with corrupted filenames are shown below in this format of, **category name - # of corrupted files** (total # of files including corrupted -> # of files that are shown to users with only in sound library dialog):
      - **Hits - 8** (54 -> 46):
         -  vibrant_game__big_game_horn_hit.wav
         -  vibrant_game__big_hit_1.wav
         -  vibrant_game__deep_hit.wav
         -  vibrant_game__ding_ding_bong_hit_1.wav
         -  vibrant_game__electro_hit_collect.wav
         -  vibrant_game__game_touch_5.wav
         -  vibrant_game__hit_1.wav
         -  vibrant_game__smash_hit_open_1.wav

      - **Alerts - 5** (32 -> 27):
         -  vibrant_game__correct_answer_hit
         -  vibrant_game__cute_alert_1
         -  vibrant_game__negative_affirmation
         -  vibrant_game__negative_alert
         -  vibrant_game__negative_bling_1

      - **Human - 1** (88 -> 87):
         - character_sharon_welcome_back_2_

      - **Achievements - 18** (65 -> 47):
         - vibrant_game__achievement_2
         - vibrant_game__achievement_3
         - vibrant_game__achievement_4
         - vibrant_game__cute_positive_notification_1
         - vibrant_game__game_gold_tresure_chest_open
         - vibrant_game__hype_game_positive_ring_bling
         - vibrant_game__positive_achievement_1
         - vibrant_game__positive_item_4
         - vibrant_game__positive_pick_up_1
         - vibrant_game__positive_sweep_bling
         - vibrant_game__postive_achievement_2
         - vibrant_game__postive_achievement_3
         - vibrant_game__postive_achievement_4
         - vibrant_game__power_boost
         - vibrant_game__power_booster
         - vibrant_game__power_booster_3
         - vibrant_game__slot_machine_win_3
         - vibrant_game__slot_machine_win_5

      - **Bell - 5** (23 -> 18):
         - vibrant_game__bell_ding
         - vibrant_game__bell_twinkle_positive_touch_1
         - vibrant_game__slot_machine_ding_1
         - vibrant_game__slot_machine_ding_2
         - vibrant_game__star_burst_3

      - **Collect - 14** (51 -> 37):
         - trill_stings_
         - vibrant_game__bubbly_pick_up
         - vibrant_game__coin_1
         - vibrant_game__cute_pick_up_1
         - vibrant_game__frog_item_
         - vibrant_game__key_item_1
         - vibrant_game__orb_touch_1
         - vibrant_game__pick_up_6
         - vibrant_game__positive_item_2
         - vibrant_game__power_booster_touch
         - vibrant_game__tone_bling_1
         - vibrant_game__tone_bling_2
         - vibrant_game__tone_bling_3
         - vibrant_game__tone_bling_4_

      - **Explosion - 2** (49 -> 47):
         - vibrant_game__ball_touch_1
         - vibrant_game__material_collect_3

      - **Loops - 1** (20 -> 19):
         - vibrant game coming back vibe loop 1

      - **Notifications - 7** (43 -> 36):
         - vibrant_game__ding_3
         - vibrant_game__ding_4
         - vibrant_game__ding_5
         - vibrant_game__ding_6
         - vibrant_game__ding_7
         - vibrant_game__modern_retro_touch_item_1
         - vibrant_game__power_up_soft

      - **Points - 6** (24 -> 18):
         - vibrant_game__ding_touch_1
         - vibrant_game__game_flip_ui_touch
         - vibrant_game__game_key_1
         - vibrant_game__game_touch_6
         - vibrant_game__gold_crystal_bling_touch_1
         - vibrant_game_down_to_up_correct_

      - **Pop - 1** (61 -> 60):
         - vibrant_game__harvest_collect_bubble_pop

      - **Projectile - 2** (31 -> 29):
         - vibrant_game__material_collect
         - vibrant_game__pick_up_2

      - **Tap - 3** (52 -> 49):
         - vibrant_game__key_touch_1
         - vibrant_game__liquid_touch_2
         - vibrant_game__water_drop_game_touch_1

      - **Transition - 3** (136 -> 133):
         - game_transition__musical_reverse
         - game_transition__musical_reverse_2
         - portal_reached_long_decay_

- **Where** it changed:
   - `apps/src/code-studio/soundLibrary.json`
   - s3 cdo-sound-library with `show` option on:
       - delete marker shown so not visible to user:
Screen Shot 2019-04-02 at 12 14 46 PM

   - s3 cdo-sound-library with `hide` option on:
       - only correct filenames showing:
Screen Shot 2019-04-02 at 12 15 03 PM

   - Game lab, App lab, and Sprite Lab sound library dialog:
       - **Before**:
Screen Shot 2019-04-02 at 11 28 16 AM

- Game lab, App lab, and Sprite Lab sound library dialog:
   - **After**:
Screen Shot 2019-04-02 at 11 33 11 AM

- **How I tested the change**:
   - Tested that all the filenames to make sure they don't have multiple underscores in between, before, or after words by running the `autorun_generateSoundMetadata.rb` which is written to raise an error if it the filename does not match the `hello_world.mp3` format.
    - Manually looked at Game lab, App lab, and Sprite lab's sound library dialog for category_hits to see that only the fixed files are showing up.

- **What's next**?
   - Nothing on the agenda for sound library right now unless there are other zendesk tickets regarding sound library files not working.

### CODE REVIEW

**Comment by ajpal** [comment]
How was this change generated?

**Comment by kimj42** [comment]
Great question!

I utilized the test that I already created in the past but ended up not merging to staging. That test is located on a branch and can be accessed [here](https://github.com/code-dot-org/code-dot-org/tree/test-for-checking-sound-filenames). It listed all the corrupted filenames in the console so I searched for those filenames in my Downloads folder then ran the updated script on those files which converted .wav files to .mp3 and also generated JSON metadata for each file. 

The updated script fixes the filenames to ensure they do not have any double underscores between words, underscores before or after, and spaces anywhere. The script can be found in `tools/scripts/autorun_generateSoundMetadata.rb`.

**Review by epeach — COMMENTED** [review]
Awesome documentation on your process and the changes! Were you able to test locally that projects with the 'corrupted' filenames are still able to play the audio after this change?

**Comment by kimj42** [comment]
I locally tested a few of the corrupted filenames to see if they are still able to play the audio by changing say, "hello_world.mp3" to "hello__world.mp3" in the block and made sure both sounds do work. I did a screen recording of it but it seems github won't allow me to upload that here in the comments. Also, it seems like it doesn't give me an error message in the console or some kind of error message somewhere if the sound file name can't be located in s3 so perhaps that is worth to add as a feature.

You can't hear the sounds but I'll go ahead and add a gif here to show how I tested both corrupted and fixed sounds still work since I can't attach the video. I tested the `vibrant_game__big_hit_1.wav` sound in the gif below:

testing_sound_working

**Comment by epeach** [comment]
Cool! Thanks for the gif! Good thinking that there should be some sort of error handling if there is no audio to be played. Will you add a ticket in the *Labs backlog for that?

**Review by epeach — APPROVED** [review]
LGTM!

**Comment by kimj42** [comment]
Ticket added to backlog! [https://codedotorg.atlassian.net/browse/STAR-267](url)

**Comment by kimj42** [comment]
Before merging, I did another double check to make sure all corrupted and fixed sounds work. I did this by using the tests that I wrote in the `test-for-checking-sound-filenames` branch which lists all the corrupted filenames if they exist in the soundLibrary.json. All tests passed so it's confirmed that all sounds are fixed now.

no more corrupted files

As a record, the only corrupted file that does not work is the `vibrant game coming back vibe loop 1.mp3` but that didn't work from the beginning when it was uploaded and my guess is it's because of the spaces in the filename. The actual mp3 and the JSON for this file still existed in s3 so it should have worked in theory. As a fix, this PR fixes that filename and it's confirmed that the fixed sound works when it's titled `vibrant_game_coming_back_vibe_loop_1.mp3`. Here's the Jira ticket that filed this one file not working as a bug: [](https://codedotorg.atlassian.net/browse/STAR-194).

**Pull request merged**
