### PR TITLE
Enabling new sign in flow and style fixes.

### PR DESCRIPTION
**Pull request by daynew**
We had been experimenting with a new sign up flow and the experiment
show a small improvement in sign ups. This change removes the old sign
page and the experiment code.
* Remove old sign up page, styles, and tests.
* Remove old vs new sign up experiment code.
* Fix styling on the new sign up pages.
* Improve RTL experience on the sign up pages.
* Deleted string related to getting parent permission on _finish_sign_up. This string is no longer needed and was missed in a previous PR.

### Before
image
image
image

### After
image
image
image
image

### Marked up changes
rtl_signin_changes
finish_signup_changes

## Links
- [jira](https://codedotorg.atlassian.net/browse/FND-1016)

## Testing story
* Try clicking around and setting up accounts:
  * english - https://adhoc-fnd-1016-ship-new-sign-up-exp-studio.cdn-code.org/users/sign_up/lang/en
  * arabic - https://adhoc-fnd-1016-ship-new-sign-up-exp-studio.cdn-code.org/users/sign_up/lang/ar

## Follow up tasks
- [x] Delete the experiment from [Optimizely](https://app.optimizely.com/v2/projects/12977480133/experiments/16844501916)
# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dju90** [comment]
Mocks look good to me!

**Review by bethanyaconnor — APPROVED** [review]
Pulled the branch and tested and it looks good to me!

**Comment by dju90** [comment]
Small nit that I should have caught before: we have an asterisk next to Email but not next to Password and Password Confirmation. We should remove the asterisk or put it next to all of them, but we can do this later - not important if it's annoying to do now.
image

**Comment by dju90** [comment]
Nit: alignment of the radio button labels is slightly off vertically:
image

Also, if the user submits the form while missing the opt-in field, after the error messages appear on the form, the Yes/No are comparatively farther away from the radio buttons
image

**Comment by dju90** [comment]
I have archived the Optimizely experiment and checked off that box in the reviewer checklist (follow up items)

**Pull request merged**
