### PR TITLE
Changing script_level.level to script_level.levels

### PR DESCRIPTION
**Pull request by balderdash**
`script_level.level`just grabs `script_level.levels[0]`, which could be the wrong level to use here if we ever swap out a free response/level group level.

### CODE REVIEW

**Comment by breville** [comment]
this seems okay to me, but have you managed to test it okay

**Comment by breville** [comment]
note test failure in circleci...

**Comment by balderdash** [comment]
That should fix the circle failure, and yeah I checked that the text responses and assessment/surveys tab still show responses normally.

I used stage 23, "Long assessment" from allthethings to test the assessments change. Anything else I should look at?

**Comment by breville** [comment]
Seems reasonable.  Rereading the original description, it seems like this really affects swapping out either a free_response or a text_match when it's inside a LevelGroup?

**Comment by balderdash** [comment]
It would affect swapping out the entire LevelGroup or top-level text response level, not levels within a LevelGroup. I'm not sure if we'll ever need to do that, but I just tried swapping out the assessment in stage 23 locally and it seems to work fine after this change.

**Pull request merged**
