### PR TITLE
Set course type for new course or unit when picking existing family name

### PR DESCRIPTION
**Pull request by dmcavoy**
### Background

When creating a new course (unit group or standalone unit) that is in existing family the course type (instruction type, participant audience and instructor audience) must match the other courses in that family. Right now anything new that is created and added to an existing family where the course type of the family does not match the defaults (teacher-led, teacher to student course) will fail to save when you get to the edit page.

### Change
This PR passes down the course type information for each existing family and if the user picks an exist family sets the course type information appropriately. If the user creates a new family name the course type information will just default to the normal defaults and the user can update it on the edit page.

Screen Shot 2022-04-28 at 10 31 12 AM
Screen Shot 2022-04-28 at 10 31 23 AM

https://user-images.githubusercontent.com/208083/165828378-5eb55645-1bde-4ae1-85b5-95487b0fbc06.mov

## Links

[Jira](https://codedotorg.atlassian.net/browse/PLAT-1776)

## Testing story

- Added unit tests on components and controllers
- Manually tested making a couple different types of unit groups and units

### CODE REVIEW

**Comment by davidsbailey** [comment]
trying it out locally (trying to replicate your 2nd screenshot), it seems like this result could be problematic:

* Screen Shot 2022-05-04 at 12 05 11 PM

if we did allow this, you'd have a conflict between whether to go to this unit or whether to follow the family name redirect to coursea-2021. 

thoughts on what better behavior might be?

**Comment by davidsbailey** [comment]
the other scenario I'd want to consider related to this is the one where we are taking an existing unversioned script / family name and adding a versioned script:

* Screen Shot 2022-05-04 at 12 12 27 PM

this would create a similar conflict at /s/artist.

**Comment by davidsbailey** [comment]
apologies if these are all related, but it also looks like it will let me (make me?) create a script with a name that is already taken in this scenario:
* Screen Shot 2022-05-04 at 12 23 55 PM

**Review by davidsbailey — APPROVED** [review]
nice work, Dani! It looks like the screenshots I posted earlier are all existing problems, and you are just focusing on the course type in this PR, which is fine. however I think it could be good to define what work remains here before moving on.

**Comment by dmcavoy** [comment]
@davidsbailey All of the things you have called out here are good edge cases to follow up on. I started working on one last week which will remove unversioned families from the dropdown: https://github.com/code-dot-org/code-dot-org/pull/46084. I was just waiting for drone to pass before sending it for review. I will log the others as follow up items.

**Comment by dmcavoy** [comment]
Jira tasks:
https://codedotorg.atlassian.net/browse/PLAT-1797
https://codedotorg.atlassian.net/browse/PLAT-1796
https://codedotorg.atlassian.net/browse/PLAT-1786

**Pull request merged**
