### PR TITLE
bring client api refactor back

### PR DESCRIPTION
**Pull request by pcardune**
Opted for just avoiding super() altogether. Not sure how to test this locally. Do we have shared VM images we can use?

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
lgtm. you can use your localhost on saucelabs using Sauce connect https://wiki.saucelabs.com/display/DOCS/Setting+Up+Sauce+Connect. LMK if you have any issues getting it set up and I can help out

**Comment by joshlory** [comment]
The revert (PR https://github.com/code-dot-org/code-dot-org/pull/9130) was never merged to staging.  I think you just want commit 029b27ded47fb08a66d71fc632acec470181419a from this PR?

**Comment by joshlory** [comment]
Never mind, I see that @Bjvanminnen committed the revert in https://github.com/code-dot-org/code-dot-org/commit/94b096071f4e6f90cd69c17409ea8a486a0ab771.

**Comment by Bjvanminnen** [comment]
Yeah, we originally thought we had a fix, but it ended up only fixing unminified, so then we reverted the fix and the original PR. And made things more confusing by doing those things against test instead of staging I think.

**Pull request merged**
