### PR TITLE
Creates a script that wipes User.terms_of_service_version.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @Hamms

**Comment by tanyaparker** [comment]
lgtm

**Comment by Hamms** [comment]
Why are we resetting to nil? Shouldn't the fact that the old values are old be sufficient?

**Comment by ashercodeorg** [comment]
Because we didn't reset the version number as part of the production hotfix. So we erroneously prompted users to accept the new terms (deemed version `1`) before the new terms were posted.

**Pull request merged**
