### PR TITLE
Adds a deleted_at timestamp column to the dashboard followers table.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This work is being done so as to store outdated followers information.

### CODE REVIEW

**Comment by aoby** [comment]
Is there a point in merging this migration before the field is used anywhere? 

Ideally I'd like to at least see the queries updated as well to filter out deleted entries.

**Comment by ashercodeorg** [comment]
Note that (in this PR or another PR) I'll add `acts_as_paranoid` (see https://github.com/ActsAsParanoid/acts_as_paranoid and/or https://github.com/rubysherpas/paranoia) to followers.rb. Doing so automatically causes soft deletes instead of hard deletes and restricts querying to undeleted rows. Thus, we won't need to explicitly update all the queries across our codebase.

It isn't obvious to me how organize the work into PRs to minimize risk and complexity to rollback should something go awry.

**Comment by aoby** [comment]
That ActsAsParanoid plugin looks great. I'd prefer, for organization, to add the plugin, the columns, and a test all in the same PR. But I'm also OK with shipping this first if you prefer that.

**Comment by ashercodeorg** [comment]
My concern with doing it all at once like that is if something goes awry. If we were to need to revert that PR, then the migration would be reverted, dropping the deleted_at column, causing issue if rows were (soft) deleted in the interim?

**Comment by aoby** [comment]
Ok, that makes sense. Reference this PR in the next one so we can keep them logically grouped. :ship:

**Comment by laurelfan** [comment]
FYI for now none of the pegasus section API stuff respects the rails model code so you cannot simply `acts_as_paranoid` and expect it to work ;)

Also -- reverting migrations (in git/CI) doesn't cause the migration to be reverted (in the database). So the deleted_at column won't disappear if a PR containing the migration is reverted. However that's still a weird state that's good to avoid (since database will be out of sync with migrations; schema.rb will be locally changed; general confusion will result).

**Comment by ashercodeorg** [comment]
That is super helpful to know (pegasus doesn't respect `acts_as_paranoid`). Given this, am I correct in thinking that we should probably fix the usage of the User table to respect deleted_at on the pegasus side?

**Comment by laurelfan** [comment]
User has been like that for a while.. If you find any usages that don't use
deleted_at please fix them.

**Pull request merged**
