### PR TITLE
Fix Web User Interface for Dynamic Configuration

### PR DESCRIPTION
**Pull request by sureshc**
The Gatekeeper web user interface was calling an outdated method to update the dynamic configuration cache (#54601 ). Update the method call and remove an unused DCDO method that was also invoking the deleted cache update method.

## Warning!!

We have entered Pixel Lock for Hour of Code!

Computer Science Education Week will be happening from Dec 4 - Dec 10. Alongside this event, we will
be launching our new Hour of Code activity. Please consider any risk introduced in this PR that
could affect Dance Lab, instructions, saving and logging student progress, caching, or anything
related to the Hour of Code activities, old or new. Even small changes, such as a different button
color, are considered significant during this time. If this change will affect the new Hour of Code
activity in any way, join the morning change review to get your changes approved prior to merging.
Reach out to the Student Labs team for more details!

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by sureshc** [comment]
Do we need some controller unit tests to verify that the Gatekeeper web user interface works when we update the dynamic configuration layer?

**Review by Hamms — APPROVED** [review]
LGTM, thanks for catching and fixing!

And yes, I think controller tests here are a good idea; I had totally forgotten about this web interface, and tests as always my preferred way to be reminded. I can own the work to add some.

**Comment by sureshc** [comment]
> I can own the work to add some.

Do you want to add tests to this feature branch? Or should we merge and try to get this fix out before that?

**Comment by Hamms** [comment]
Nah, go ahead and merge the fix; I'll add tests as follow-up

**Pull request merged**
