### PR TITLE
remove /v2/user routes from pegasus

### PR DESCRIPTION
**Pull request by davidsbailey**
This route became unused after https://github.com/code-dot-org/code-dot-org/pull/47244. 

## Testing story

* Code search to verify the route is unused
* using AWS Athena, I verified that the number of requests for /v2/user in our dashboard ELB logs dropped off to zero shortly after https://github.com/code-dot-org/code-dot-org/pull/47244 was merged.

### CODE REVIEW

**Comment by pablo-code-org** [comment]
This looks good once it is ready to review.

**Comment by davidsbailey** [comment]
thanks for the early review Pablo!

**Comment by jmkulwik** [comment]
I was reviewing PR 47904 (the second one linked in your description) and saw that you had mentioned it. Did you intend to link 47244 both times?

**Comment by davidsbailey** [comment]
> I was reviewing PR 47904 (the second one linked in your description) and saw that you had mentioned it. Did you intend to link 47244 both times?

oops, yes, sorry about that! it's fixed now.

**Pull request merged**
