### PR TITLE
Update warning and error strings for Java Lab demo usage

### PR DESCRIPTION
**Pull request by molly-moen**
Using `here` as link text is [not accessible](https://www.a11yproject.com/posts/creating-valid-and-accessible-links/). This updates our links to use more helpful link text:

### Near limit warning
Screenshot 2023-04-28 at 10 49 23 AM

### Over limit error
Screenshot 2023-04-28 at 10 49 35 AM

## Warning!!

The AP CSP Create Performance Task is in progress from April 1 - May 1 2023. Please
consider any risk introduced by this PR that could affect our students taking AP CSP. Code.org
students taking AP CSP primarily use App Lab for their Create Task, however a small percent use Game
Lab. Carefully consider whether your change has any risk of alterering, changing, or breaking
anything in these two labs. Even small changes, such as a different button color, are considered
significant during this time period. Reach out to the Student Learning team or Curriculum team for
more details.

## Links

- [slack discussion](https://codedotorg.slack.com/archives/C03DBDN67B7/p1682637429372399?thread_ts=1682616971.841809&cid=C03DBDN67B7)

## Testing story
Tested that the new strings show up as expected locally.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by ebeastlake — APPROVED** [review]
Thanks for making this update and teaching me something!

**Comment by ebeastlake** [comment]
nit: Would "learn more about `how to become a verified teacher`" be even better than "learn more about `becoming verified`"? And maybe similarly with `why teacher verification is needed`?

**Comment by molly-moen** [comment]
> nit: Would "learn more about `how to become a verified teacher`" be even better than "learn more about `becoming verified`"? And maybe similarly with `why teacher verification is needed`?

@ebeastlake good call, updated

**Review by jmkulwik — COMMENTED** [review]
🎉 LGTM!

**Review by jmkulwik — APPROVED** [review]

**Pull request merged**
