### PR TITLE
define 'npm run start:applab'

### PR DESCRIPTION
**Pull request by davidsbailey**
before: `npm run start -- --app=applab`
after: `npm run start:applab`

### CODE REVIEW

**Comment by davidsbailey** [comment]
@Bjvanminnen any interest in typing less dashes when starting applab?

**Comment by Bjvanminnen** [comment]
What is the benefit of even restricting to --app=applab? I just run using `npm start` and have found builds to be quite quick.

**Comment by Bjvanminnen** [comment]
I think the marginally better way of doing this might be:

```
"start:applab": "npm run start -- --app=applab"
```

This way if start were to change for some reason, start:applab would also be updated.

**Comment by Bjvanminnen** [comment]
@islemaster in case he has an opinion. I've found `npm start` to be sufficient, and am not sure I would use start:applab, but I'm also not sure I see any problems with it (though it does perhaps indicate an increased level of support for using --app)

**Comment by davidsbailey** [comment]
I see what you are saying -- I had not tried just `npm start`. I'll use that for now and reopen this PR if I have any problems with it.

**Comment by islemaster** [comment]
Brent is correct that it's probably better to define `start:applab` in terms of `start`.  I'm all for the alias.  I often run `npm start -- --app=gamelab` as it rebuilds significantly faster for me.

**Comment by islemaster** [comment]
Also, note you can always say `npm start` in place of `npm run start` [because it's one of the special magic npm script commands](https://docs.npmjs.com/misc/scripts).

**Comment by Bjvanminnen** [comment]
I personally try to avoid magic, and usually just type `npm run start` anyways =P

**Comment by davidsbailey** [comment]
`npm run start -- --app=applab` seems to rebuild a few seconds faster for me, so I'll want to keep using it. Adding one for gamelab as well.

**Pull request merged**
