### PR TITLE
BugFix 164: In levelbuilder, setting app lab debugger speed to 0 for a level doesn't work correctly.

### PR DESCRIPTION
**Pull request by jmkulwik**
StudioApp was attempting to check whether sliderSpeed had been set, but this check would return false if the value of sliderSpeed was set to 0. This change updates the condition so it checks whether sliderSpeed is a number rather than if it exists (if it doesn't exist, typeof sliderSpeed === 'number' will return false). This change also moves the check to the more testable runState.js and adds unit tests for the various possible values of sliderSpeed.
Ticket: https://codedotorg.atlassian.net/browse/STAR-164

### CODE REVIEW

**Review by ajpal — APPROVED** [review]
Is this something that would be possible to unit test so it doesn't accidentally regress?

**Comment by ajpal** [comment]
Woo! Unit tests! 🎉

**Comment by epeach** [comment]
This looks great - thanks for adding unit tests! It's good practice to use the PR description to document the change. In general, addressing: what was the issue (maybe a link to spec or zendesk, if relevant)? What did you change? And how did you test? It helps reviewers get context before reviewing and creates documentation for us to look back on in the future. I've seen Brad recommend a great informal checklist for this and if you're interested I can track it down.

**Review by epeach — APPROVED** [review]
LGTM! Thanks for the updated PR description - looks great!

**Pull request merged**
