### PR TITLE
Fix v3/animations varnish configuration

### PR DESCRIPTION
**Pull request by islemaster**
Cookies were getting stripped from requests to `v3/animations/**/*.png` due to a `**/*.png` rule in our cache configuration, resulting in 401 errors when trying to upload animations.  This adds a higher-priority rule to ensure we keep cookies on those requests.  Also adds a couple of tests to cover this cache behavior on the v3/assets and v3/animations APIs.

This does add a behavior to our dashboard CloudFront distibutions, where we have a limit of 50 behaviors.  We should have less than 30 right now.

### CODE REVIEW

**Comment by wjordan** [comment]
Generally LGTM, though you'll need to do one extra step I forgot to mention earlier:
- bump the patch-level version of `cdo-varnish` cookbook in `cookbooks/Berksfile.lock` and `cookbooks/cdo-varnish/metadata.rb`

(cf. internal-wiki [How to make cache changes](http://wiki.code.org/display/PROD/How+to+make+cache+changes) page)

**Comment by islemaster** [comment]
Should I also update the cdo-varnish versions listed in [cdo-apps/Berksfile.lock](https://github.com/code-dot-org/code-dot-org/blob/staging/cookbooks/cdo-apps/Berksfile.lock#L81), [cdo-nginx/Berksfile.lock](https://github.com/code-dot-org/code-dot-org/blob/staging/cookbooks/cdo-nginx/Berksfile.lock#L21) and [cdo-varnish/Berksfile.lock](https://github.com/code-dot-org/code-dot-org/blob/staging/cookbooks/cdo-varnish/Berksfile.lock#L16)?  At least two of those are already 'out of date'.

**Comment by wjordan** [comment]
not necessary to update any `cookbooks/[cookbook]/Berksfile.lock` files- they should have been `.gitignore`d as of aa504275f9835ba535eecdf8556df7748a2b843b (7 days ago), but I think I still need to remove existing files from version control (I'll submit a separate PR to do this).

**Comment by islemaster** [comment]
PTAL

**Comment by wjordan** [comment]
looks good! :+1:

**Comment by islemaster** [comment]
:frowning: Dangit CircleCI

```
$ cd "apps"
npm install
\|-|-|-|-|-|-|-|-|/|-|
cd "apps"
npm install
 died unexpectedly

Action failed: npm install
```

Retrying...

**Pull request merged**
