### PR TITLE
Upgrade react-bootstrap

### PR DESCRIPTION
**Pull request by maddiedierker**
Pulling this upgrade out of #41582 as it doesn't depend on the React upgrade.

### CODE REVIEW

**Comment by maddiedierker** [comment]
@code-dot-org/plc this package is mostly used by your code in `apps/` -- is there anything that should be manually checked with this upgrade, or can we rely on tests to catch regressions? we're upgrading from [`^0.32.4`](https://www.npmjs.com/package/react-bootstrap/v/0.32.4) to [`^0.33.1`](https://www.npmjs.com/package/react-bootstrap/v/0.33.1)

**Comment by bencodeorg** [comment]
I think test coverage is fairly good on core PLC tools (workshop dashboard, application dashboard, etc.), so I'd be ok relying on tests. Did you stumble across any release notes for this version (or know where I might find some)? Found back to version 1.x.x, but not 0.x.x 😬 

https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md

**Comment by maddiedierker** [comment]
@bencodeorg i couldn't find any release notes either. the release tags on GitHub (e.g., [the one for 0.33.1](https://github.com/react-bootstrap/react-bootstrap/releases/tag/v0.33.1)) have no information, but you can compare the repo across versions -- here is the 0.32.4 -> 0.33.1 comparison: https://github.com/react-bootstrap/react-bootstrap/compare/v0.32.4...v0.33.1

**Comment by bencodeorg** [comment]
Thanks Maddie! I don't have much experience with dependency management...I'm assuming not a coincidence that I see this commit in the changes in 0.33.1:

https://github.com/react-bootstrap/react-bootstrap/commit/d6c41ff589f1d73c96611d704b3e4230c8237ae1

But the point of this PR is that react-bootstrap isn't actually dependent on React 16, is that right?

**Comment by maddiedierker** [comment]
that's likely exactly the commit we need! ("need" being relative here...) if we don't upgrade react-bootstrap to 0.33.1 before upgrading react, we have to suppress a ton of extra warnings about deprecated lifecycle hooks in our tests (which means we have to allow our tests to log warnings; currently, a test will fail if a warning is logged to the console). so we want to upgrade react-bootstrap beforehand, which appears to be working fine while we're still on an older react version, so that we don't have to deal with allowing a bunch of extra deprecation warnings.

an alternative would be to temporarily allow warnings in tests, upgrade react, upgrade react-bootstrap, then go back to disallowing warnings.

**Review by tim-dot-org — APPROVED** [review]
looks good to me (ben probably has a better idea of the impact to plc stuff)! are we planning on coming back to fix the skipped tests, and if so, do we have that tracked somewhere?

**Comment by bencodeorg** [comment]
> that's likely exactly the commit we need! ("need" being relative here...) if we don't upgrade react-bootstrap to 0.33.1 before upgrading react, we have to suppress a ton of extra warnings about deprecated lifecycle hooks in our tests (which means we have to allow our tests to log warnings; currently, a test will fail if a warning is logged to the console). so we want to upgrade react-bootstrap beforehand, which appears to be working fine while we're still on an older react version, so that we don't have to deal with allowing a bunch of extra deprecation warnings.
> 
> an alternative would be to temporarily allow warnings in tests, upgrade react, upgrade react-bootstrap, then go back to disallowing warnings.

Thanks Maddie! To make sure I understand...0.33.1 does make use of some UNSAFE_ lifecycle hooks (which don't exist in React 15), but we're relying on tests to make sure that our use of react-bootstrap does not actually use these lifecycle hooks? Understood re: the part that we would get a lot of warnings about lifecycle hooks if we did not do this upgrade before upgrading to React 16.

**Review by bencodeorg — APPROVED** [review]

**Review by Erin007 — APPROVED** [review]

**Comment by maddiedierker** [comment]
> looks good to me (ben probably has a better idea of the impact to plc stuff)! are we planning on coming back to fix the skipped tests, and if so, do we have that tracked somewhere?

yes! the 3 tests i disabled are in *labs-land, so i've logged tickets for them and am going to add comments in the code for easy tracking now. i wanted to make sure i got a green build first 😄

**Comment by maddiedierker** [comment]
> Thanks Maddie! To make sure I understand...0.33.1 does make use of some UNSAFE_ lifecycle hooks (which don't exist in React 15), but we're relying on tests to make sure that our use of react-bootstrap does not actually use these lifecycle hooks? Understood re: the part that we would get a lot of warnings about lifecycle hooks if we did not do this upgrade before upgrading to React 16.

pretty much -- if we're testing a component that uses react-bootstrap and a deprecated lifecycle method is triggered, our test will fail.

i think i was wrong when i said [this](https://github.com/react-bootstrap/react-bootstrap/commit/d6c41ff589f1d73c96611d704b3e4230c8237ae1) was the commit we need -- this commit enables the PR we actually need, which should be: https://github.com/react-bootstrap/react-bootstrap/pull/4597 (gets rid of deprecation warnings by upgrading an internal component)

**Pull request merged**
