### PR TITLE
[Finishes #109269530] validate records for record blocks

### PR DESCRIPTION
**Pull request by Bjvanminnen**
Add validation for records. If they fail validation, don't bother making the API call.

image

### CODE REVIEW

**Comment by cpirich** [comment]
Looks fine to me, however, we typically have not done anything conditional based on the results of the validate functions. The underlying functions usually do that (to prevent crashes, etc.). This layer usually just provides a helpful warning before you hit the underlying API.

**Comment by Bjvanminnen** [comment]
I was wondering if I should make this an error rather than a warning for this reason. Thoughts? It does however seem silly to make a network request that we know is going to fail.

**Comment by Bjvanminnen** [comment]
Reading through your comments again, I realized that your issue may have actually just been with the layer where I was exiting early rather than the fact that I was exiting early.

I looked at this again, and in appStorage we do some additional parameter validation, in some cases repeating logic from the layer in commands.js (for example AppStorage.updateRecord will give an onError if you don't have a table name, which applabCommands.updateRecord would already have informed you about). It seems a little bit silly to give two different errors for this. Also, with the onError calls in AppStorage.js, we dont get line information.

I propose that I move all of these onError calls that happen before we actually make our XHRs into commands.js (where other param validation happens), and in the cases where it prevents us from making the XHR have it give an error (with line info) rather than a warning.

@cpirich What do you think of this plan?

**Comment by cpirich** [comment]
Yes, my comment was purely on the layer. I agree that the APIs we create should probably fail gracefully when possible.

Since we started with mostly DOM functions which already handled most errors, the "validate" functions were intended to be purely a parameter validation layer that gave helpful indications that the student didn't understand the API (of the flavor that you could turn off when we are in "share mode"). It's almost an extension of the documentation layer.

For custom APIs that we create, there seems to be a different question of how they should handle errors. Obviously, not all error conditions can be detected by inspecting the parameters. But should they be guarding against things like this or throwing errors themselves? Or should they return failure codes or call user-supplied callbacks with failure codes? (If the exceptions thrown have sufficient information, it may be just as informative (if not more) as what we get from the parameter validation layer).

The tricky thing about the data APIs is that they already have a way of indicating failure to the caller (through the onError method). So if you detect an error, it seems reasonable to use that mechanism. But another way of looking at it is: is this an error that will be hit 100% during development? if so, then the need to call `onError` seems less important as long as there will be a clearly visible error in the IDE. If the error depends on runtime state and may not be hit during development, but may be hit while in share mode, then failing in such a way that the student-written program can theoretically handle the error seems better.

It seems like cases we can detect will fail before we do the XHR fall into the former bucket. So failing "hard" will give better feedback in the IDE. If an exception is thrown to trigger that, then there is no way to call `onError`, which seems fine.

**Comment by Bjvanminnen** [comment]
@cpirich Ready for another look if you're interested. Moved a bunch of the validation from appStorage to commands.js. I then also simplified our output functions some (created an `outputWarning` and `outputError`), so that we're not always repeating args.

**Pull request merged**
