### PR TITLE
Enable `jsx-a11y/aria-role`

### PR DESCRIPTION
**Pull request by Hamms**
Note that by default, this rule inspects developer-added components as well as generics. That does mean that if we define a `role` property representing something other than an ARIA role, the rule will warn on that as well. There is currently only a single component for which that is true, and in fact we only warn on two instances of it in tests.

There is an argument to be made that we should use the `ignoreNonDOM` option to only warn on generic components, to avoid the potential for confusion when a developer is trying to use a generic term like `role` to refer to something other than an ARIA role. Ultimately, we think this is probably not that big of a deal; the rule is well-documented and the nature of the warning should be easy for any developer to discover. As Ben points out in comments below (from when this PR was going the other direction), spreading awareness of ARIA roles is a positive thing, as is providing a more-verbose name for the property in question.

What do y'all think? Is it worth it to keep the rule enabled in full, or does scoping it to just generic components that are using `role` to represent an ARIA role make sense?

## Links

https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-role.md

## Testing story

Ran `yarn lint` to verify that with this change in place, we no longer have any violations of this rule.

### CODE REVIEW

**Comment by bencodeorg** [comment]
No strong preference here -- two ideas come to mind on why we might want it just to be enabled across all uses:
- I was able to "sneak in" a `role` attribute by having a role as a prop, then destructuring `{...this.props}` into some child HTML element.
- Maybe just the presence of these warnings will encourage developers to consider what an ARIA role is, etc (although seeing this warning in non-generic element might be confusing...)

**Comment by Hamms** [comment]
Good points. It does also occur to me that the best solution to avoid this rule triggering is to use a more verbose and specific name for the property in question, which is always worth encouraging. I think I'm now leaning toward enabling this everywhere.

**Comment by Hamms** [comment]
Switched to a full enable! PTAL and let me know what you think

**Review by bencodeorg — APPROVED** [review]
Github seems to be showing the full "enable the linter" changes as part of this PR, but the two disable lines look good to me!

**Comment by Hamms** [comment]
Diff should be correct now!

**Review by bencodeorg — APPROVED** [review]

**Pull request merged**
