### PR TITLE
Translate success and error messages for dance party puzzles

### PR DESCRIPTION
**Pull request by maddiedierker**
Uses the success/error message on puzzle complete as the translation key rather than the message itself.

Tagging @ryansloan so he knows the messages currently on levelbuilder will need to updated to keys (and any additional strings needed will need to be added to [i18n/dance/en_us.json](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/i18n/dance/en_us.json))

### CODE REVIEW

**Comment by maddiedierker** [comment]
[dance party success/error messages can be localized](https://trello.com/c/UUq4jxM5/20-dance-party-success-error-messages-can-be-localized)

**Comment by ryansloan** [comment]
Yahoo! FYI, no need to create trello cards (unless it's easier for you) - I am tracking this via GitHub issues now. 

What syntax will I need to use to access these strings in validation code?

**Comment by maddiedierker** [comment]
@ryansloan in levelbuilder, you will pass the key to the fail/pass methods as a string. So if the error message is "You need to make a dancer" --

```
nativeAPI.fail("danceFeedbackNeedNewDancer");
```
A message isn't required though (it looks like there are fallback messages elsewhere? i'm unfamiliar with where this happens, though)
```
nativeAPI.pass();
```

**Comment by ryansloan** [comment]
@madelynkasula Perfect, thanks! We don't pass messages for passing solutions, but we should be passing them for failures.

**Pull request merged**
