### PR TITLE
Small update to featured projects admin table

### PR DESCRIPTION
**Pull request by fisher-alice**
This PR makes a couple small updates to the featured projects admin table available to project validators at https://studio.code.org/projects/featured.

Updates include:
- Adding 'Published' column (yes/no)
- Removing 'Unfeatured' column
- Adding ability change the status of a featured project from 'archived' to 'bookmarked'

We will only feature projects that have been 'published', or given consent to be displayed at 'projects/public'. Although we will soon remove the ability to publish projects, @samantha-code will select projects to be featured only from projects that have been published so we need to include the 'Published' column. In the future, we will allow users to submit projects to be considered as featured projects; at that point, submitted projects will be marked as 'published'.

Sam is starting to organize featured projects via the admin table and has expressed a desire to 'start over' and move featured projects to the 'bookmarked' status. Although featured projects have existed, we will soon display only featured projects at 'projects/public'.

This PR is a follow-up to https://github.com/code-dot-org/code-dot-org/pull/56585.

BEFORE UPDATE:

Columns:
Screenshot 2024-02-27 at 9 17 47 AM

Actions for archived featured projects:
Screenshot 2024-02-27 at 9 18 53 AM

AFTER UPDATE:

Columns:
Screenshot 2024-02-27 at 4 42 59 PM

Actions for archived featured projects:
Screenshot 2024-02-27 at 9 15 35 AM

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bencodeorg** [comment]
Is there currently any limitation on featuring a project that relates to its published status? Or is that something we're adding? 

I feel like we should have some explicit check there (ie, cannot feature unless published?) Or is it the other way around (ie, we're going to mark a project as published once we feature it)?

I guess I'm worried some of this feels like it requires some specific knowledge of what can/should be featured, vs the system enforcing the logic.

**Comment by fisher-alice** [comment]
> Is there currently any limitation on featuring a project that relates to its published status? Or is that something we're adding?
> 
Yes, there's currently a limitation on featuring a project [here](https://github.com/code-dot-org/code-dot-org/blob/da6db8bbad0bdaddb10ffb71ac6ba5cbdca57c7b/dashboard/lib/projects_list.rb#L239) - if the project is not published, it cannot be displayed in the public gallery.

> I guess I'm worried some of this feels like it requires some specific knowledge of what can/should be featured, vs the system enforcing the logic.
>
Great point! I could add a sentence at the top of the table that states 'Featured projects that are not published are not able to be displayed in the public gallery at 'projects/public'. @samantha-code lmk what you think about that.

**Comment by bencodeorg** [comment]
Good to know we have a limitation that excludes showing unpublished projects! It does feel a little sketchy to have it tucked away in the display logic, and I just skimmed `projects_list_test` and it doesn't look like we have a test on that scenario. Something to look out for if we could improve test coverage there if you find yourself in that code as you're proceeding with this work.

**Review by bencodeorg — APPROVED** [review]

**Comment by fisher-alice** [comment]
> Good to know we have a limitation that excludes showing unpublished projects! It does feel a little sketchy to have it tucked away in the display logic, and I just skimmed `projects_list_test` and it doesn't look like we have a test on that scenario. Something to look out for if we could improve test coverage there if you find yourself in that code as you're proceeding with this work.

Thanks! I am currently working on updating dashboard tests for fetching published active featured projects in this draft pr. https://github.com/code-dot-org/code-dot-org/pull/56828
Thanks for the feedback!

**Pull request merged**
