### PR TITLE
Fixes violations of Style/EmptyLinesAroundClassBody and reenables the rubocop check.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes generated by "bundle exec rubocop --only Style/EmptyLinesAroundClassBody --auto-correct".

### CODE REVIEW

**Comment by ashercodeorg** [comment]
It appears that many of our files follow the empty_lines option rather than [the default] no_empty_lines. Note that the PR is built around no_empty_lines (my preference), though I'm happy to change it to empty_lines if that is the team preference and/or style.

**Comment by joshlory** [comment]
I'm a little mixed on enabling cops to enforce whitespace.  I don't think the extra newlines hurt readability, and there are a lot of existing violations (suggesting we don't follow a consistent empty line style).  On the other hand, we do have `Style/TrailingBlankLines` and `Style/TrailingWhitespace` enabled.

FWIW we already have `Style/ExtraSpacing` on our wont-fix list: https://github.com/code-dot-org/code-dot-org/blob/e68341cacd5a25d57e47299a8ccb05ed6221f695/.rubocop.yml#L28-L29 (maybe we should fix & re-enable this rule?)

**Comment by ashercodeorg** [comment]
In terms of fixing and reenabling Style/ExtraSpacing, the majority of the violations are two space indents before a comment. Certainly, it would be an easy check to fix. And there doesn't seem to have been strong reason when it was added to the won't fix list (https://github.com/code-dot-org/code-dot-org/commit/d0c5d6ead1f5a6ac4f6109e47661c3bb23afaf04).

Being a pedant, I'm all for enabling the whitespace cops. Unless others way in, I'll follow your advice as to whether these should be fixed and enabled or added to the won't fix list.

**Comment by ashercodeorg** [comment]
Given the merge conflicts, going to close this PR. If we go this route, I'll create another PR.

**Pull request closed without merging**
