### PR TITLE
Non-placeholder achievements in the Finish Dialog

### PR DESCRIPTION
**Pull request by balderdash**
screenshot from 2017-12-13 14-24-47

These are the same achievements used in the gamification experiment:
* Puzzle complete (always granted)
* Fewer than/exactly/more than 'n' blocks used (shows up gray if you use too many blocks, doesn't show up at all if there is no block limit)
* Without using hints/Using just one hint/Using hints (always appears, gray if using >1 hints)

### CODE REVIEW

**Comment by joshlory** [comment]
Change LGTM.  Why also include the i18n changes in the PR, vs. letting them auto-translate via Crowdin?

**Comment by joshlory** [comment]
Bump.

**Comment by balderdash** [comment]
Whoops, thanks for the reminder.

The i18n changes come from unreverting the PR that deleted the old gamification strings. I assume that crowdin wouldn't automatically use the old translations if I put just the English strings back, so this avoids having to wait for new volunteer translations.

@Hamms Is that assumption correct, or is crowdin smart enough to reuse the old translations if I just add the English strings normally? Also, is there any risk to the i18n sync process in manually adding non-English strings?

**Comment by Hamms** [comment]
Crowdin actually should be smart enough to reuse old translations if the source string is being changed back to exactly the same thing as the old source string.

There isn't necessarily a risk to the i18n sync process by manually adding non-English strings like this, but the addition will be temporary unless the translations are also added to crowdin, since it is our ultimate source of truth.

**Comment by balderdash** [comment]
Alright, removed the non-English strings. @joshlory PTAL.

**Pull request merged**
