### PR TITLE
Change from Rspec's should to Rspec's expect.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Documentation: https://relishapp.com/rspec/rspec-expectations/v/3-5/docs/built-in-matchers

Motivation: 
image

### CODE REVIEW

**Comment by bcjordan** [comment]
Awesome, thank you. LGTM pending Circle pass!

**Comment by joshlory** [comment]
Are there other rake tests that use the deprecated `should`?

**Comment by ashercodeorg** [comment]
Good catch @joshlory, I only fixed the file flagged in `infra-test`. Adding other instances I'm finding to this PR in upcoming commits.

**Comment by ashercodeorg** [comment]
PTAL.

**Comment by bcjordan** [comment]
LGTM!

**Pull request merged**
