### PR TITLE
Moved all mailing scripts from bin/ into a subdirectory, bin/mail/ 

### PR DESCRIPTION
**Pull request by aoby**
These scripts generally refer to dependencies with relative paths so they should still work. In any case, these are mostly kept around for reference and don't need to be run again (not counting the common utilities).

Note this includes https://github.com/code-dot-org/code-dot-org/pull/6775. Once that is merged, this PR will just be moving the files.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Though this PR is fine if we want these files for archival purposes, note that they will not be runnable as is (for example, the require_relative paths needs to be updated, other filepaths may need updating, etc.).

This was what caused me to drop my PR that did these moves.

**Comment by aoby** [comment]
Right, thanks for the reminder. All the newer scripts use 

```
require_relative '../mailing-common/mailing-list-utils'
```

which is still the same relative path, but I neglected to update the relative path to pegasus from that script and other older ones.

Updated.
Since I'm about to head out on vacation, I will hold off on merging this until I get back and have time to give it a bit more scrutiny.

**Comment by aoby** [comment]
@ashercodeorg I updated the relative paths. Please take another look. I'm preparing another set of email  scripts this week so I'd like to get this into a subdirectory.

**Comment by ashercodeorg** [comment]
It looks like many of the moves are showing up as delete/add, e.g., send-ca-test-mails. If it isn't onerous (is it?), it would be nice if github showed these as moves.

**Comment by aoby** [comment]
Good call. I'm not sure how to do it with the commit history already in place here, so I'll re-apply the changes to a new branch with the mv as its own commit to preserve the file indices.

**Pull request closed without merging**
