### PR TITLE
[Playlab] Fix validation for lose condition

### PR DESCRIPTION
**Pull request by ajpal**
this is just a simple change to the level validation code to make sure we show the level fail message when needed. screenshot of the change because it's hard to review level diffs:
Before
image
After
image

Before:
image

After:
image

## Links

- [jira](https://codedotorg.atlassian.net/browse/STAR-690)

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by epeach — COMMENTED** [review]
Can you add an explanation of what the problem was and how this edit fixes it?

Also - does this address the issues in Francesco's follow-up (see Bryan's comment on the Jira ticket)?

**Comment by ajpal** [comment]
> does this address the issues in Francesco's follow-up?

I just took a look at the project he shared, and no this fix will not address that. That work would be unrelated so maybe deserves its own ticket. However, I think it's work that we would be really unlikely to do for Play Lab (much more involved than this level validation fix)

**Comment by epeach** [comment]
I see. We should probably ask Bryan to log Francesco's follow-up as a separate task.

**Review by epeach — APPROVED** [review]
Thanks for the screenshots!

**Pull request merged**
