### PR TITLE
Update piskel and re-enable gamelab test

### PR DESCRIPTION
**Pull request by caleybrock**
Update piskel to version with to alerts for saving and re-enable test. (Succeeded locally)

Disable PR: https://github.com/code-dot-org/code-dot-org/pull/10715

### CODE REVIEW

**Comment by bcjordan** [comment]
LGTM! We can watch for Circle run result

**Comment by bcjordan** [comment]
@caleybrock a prospective fix for the intermittent "timed out" fail is now on staging, if you update this branch with latest from staging it should be less likely to time out

**Comment by caleybrock** [comment]
okay, I'll do that

**Comment by caleybrock** [comment]
oh yay circle is green!!

**Pull request merged**
