### PR TITLE
disable eyes test: Mobile Star Wars share small footer

### PR DESCRIPTION
**Pull request by davidsbailey**
This scenario [sometimes passes](https://eyes.applitools.com/app/sessions/251946655676875/steps/1?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110) and [sometimes fails](https://eyes.applitools.com/app/sessions/251946643494541/steps/1?accountId=mG4DoRfv0ntEgI3XIYBulrKxlZqrHtGwbP3V103ojvLFU110).

### CODE REVIEW

**Comment by islemaster** [comment]
LGTM.  Thanks Dave, sorry I didn't knock this out on Friday.

**Comment by davidsbailey** [comment]
No problem Brad! I'm removing this from http://wiki.code.org/display/PROD/Known+Issues#KnownIssues-Applitoolscroppingmobileeyestests since it will no longer affect deploy. Do you and Andrew want a pivotal item to track it? If so, in which project?

**Comment by islemaster** [comment]
Go ahead and add to "Developers" - I have a small list of assigned tasks
there that I keep up with.  Thanks!

On Tue, Feb 16, 2016 at 1:44 PM, David Bailey notifications@github.com
wrote:

> No problem Brad! I'm removing this from
> http://wiki.code.org/display/PROD/Known+Issues#KnownIssues-Applitoolscroppingmobileeyestests
> since it will no longer affect deploy. Do you and Andrew want a pivotal
> item to track it? If so, in which project?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/code-dot-org/code-dot-org/pull/6818#issuecomment-184886621
> .

## 

Brad Buchanan
Software Engineer, Code.org
brad@code.org

**Comment by tanyaparker** [comment]
@davidsbailey can we merge this in? :)

**Pull request merged**
