### PR TITLE
New gamelab localizations

### PR DESCRIPTION
**Pull request by islemaster**
On behalf of @poorvasingal

### CODE REVIEW

**Comment by islemaster** [comment]
@poorvasingal I don't see any of these localizations showing up in gamelab when I build, and I won't be able to investigate why until after 10:30 today.  @cpirich maybe you can take a look?

**Comment by islemaster** [comment]
Tracked down the issue - we have to pass the specific app's localizations in the config object to StudioApp.init().

**Comment by davidsbailey** [comment]
LGTM

**Comment by poorvasingal** [comment]
Thanks @islemaster!

**Pull request merged**
