### PR TITLE
Update many links on code.org/apply to not open in new tab

### PR DESCRIPTION
**Pull request by dmcavoy**
We don't want all the links to open in a new window. Just ones that are outside the funnels we are hoping for people to move through.

### CODE REVIEW

**Review by kelbyhawn — COMMENTED** [review]
Thanks for updating this! 

These are no longer needed now that the target blanks are gone `rel: "noopener noreferrer"`. Want me to update it real quick? I can QA the links too if I'm in the branch.

**Comment by dmcavoy** [comment]
> Thanks for updating this!
> 
> These are no longer needed now that the target blanks are gone `rel: "noopener noreferrer"`. Want me to update it real quick? I can QA the links too if I'm in the branch.

@kelbyhawn if you don't mind that would be great

**Comment by kelbyhawn** [comment]
> @kelbyhawn if you don't mind that would be great

I have three questions before I merge:

1. The CSD, CSP, and CSA links are still opening in new tabs, do you want me to remove that on these too?
2. The `Apply now` and `Learn more` buttons link to the same place on all of these action blocks (code.org/educate/professional-learning/program-information) — is this intentional? Do we need the Learn more buttons if yes? 
3. The Outside the United States `Learn more` button links externally to support.code.org, do we want this to open in a new tab like the `Visit our support center` button does? 
Screenshot 2023-03-20 at 11 54 06 AM
Screenshot 2023-03-20 at 11 56 53 AM

**Comment by dmcavoy** [comment]
@kelbyhawn 
> I have three questions before I merge:
> 
> 1. The CSD, CSP, and CSA links are still opening in new tabs, do you want me to remove that on these too?

Yes I left those opening in new tabs because they take you away from applying.

> 2. The `Apply now` and `Learn more` buttons link to the same place on all of these action blocks (code.org/educate/professional-learning/program-information) — is this intentional? Do we need the Learn more buttons if yes?

Yes when I updated to everything going to the RP landing page it meant both buttons go to the same place. I left both because it felt like different people would want to click each one even though they go to the same place. Ideally in the future we will be able to put them to different places. I guess we could just go to a Learn more button as the primary button. Thoughts?

> 3. The Outside the United States `Learn more` button links externally to support.code.org, do we want this to open in a new tab like the `Visit our support center` button does?

For the outside the US - I kept it as in tab because if you are outside the US we are not actually worried about getting you back to convert you since you can't do our PL application. So I think this is right.

**Comment by kelbyhawn** [comment]
> (From 2.) …we could just go to a Learn more button as the primary button. Thoughts?

I like the idea of only having the Learn more button for now — I'll update that too. 

All the rest sounds good, thanks!

**Review by kelbyhawn — APPROVED** [review]

**Pull request merged**
