### PR TITLE
Enable extendedDebugging for firefox

### PR DESCRIPTION
**Pull request by drizco**
A test has been flaky specifically for firefox browser (Firefox_acquisition_products_school_info_confirmation_dialog), and when reviewing the video, the ui indicates there has been an error on the api request to update the user's school info. `extendedDebugging` would allow us to see an archive of the network tab and console for more specific errors

Screenshot 2024-11-07 at 9 51 30 AM
Screenshot 2024-11-07 at 9 51 38 AM

## Links
[jira](https://codedotorg.atlassian.net/browse/ACQ-2535)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by snickell — CHANGES_REQUESTED** [review]
I'm concerned about letting this loose on the test server, from [sauce labs on extendedDebugging](https://docs.saucelabs.com/insights/debug/):
image

This doesn't sound like something we should turn on and leave on, so if we do merge, I want a plan for when we're gonna remove it.

1. Approx how many dev-of-the-day (DOTD) test server runs would it take to repro the issue? One way to figure this out would be to answer the question: Does it happen every weekday? Every other? Once a week? Figure we do one test server run per weekday.
2. If its expected that 4 test server runs or less would repro, we should merge it post-DTP, and spend the day running test server test runs until it repros.
3. Then merge a revert. That way it'll never affect an attempt by DOTD to DTP (deploy to prod).

I'd like to take one more push at repro-ing this in Drone (our CI system, vs having to deploy this to test/prod servers). I have an idea, should have remembered this last time.

**Comment by snickell** [comment]
Ryan noticed that we actually have `extendedDebugging: true` set already for Chrome in browser.json. So.... maybe its not that bad or maybe we should revisit if its impacting Chrome perf later?

**Review by snickell — APPROVED** [review]
As long as we don't leave it on permanently (without measuring impact on test server perf, etc) I'm a ✅

We're using the [test firefox] git commit message tag to try to run a bunch of Firefox sauce instances in parallel from drone. If that repros, great, that's the way to go.

If not, in light of Chrome already having `extendedDebugging: true` I'm in favor of merging and letting it go through the normal DTP flow, and then merging a revert as soon as it repros on the test server and @drizco gets the info trace he wants.

**Comment by drizco** [comment]
> As long as we don't leave it on permanently (without measuring impact on test server perf, etc) I'm a ✅
> 
> We're using the [test firefox] git commit message tag to try to run a bunch of Firefox sauce instances in parallel from drone. If that repros, great, that's the way to go.
> 
> If not, in light of Chrome already having `extendedDebugging: true` I'm in favor of merging and letting it go through the normal DTP flow, and then merging a revert as soon as it repros on the test server and @drizco gets the info trace he wants.

I tried [test firefox] on over six drone runs and all succeeded. Since there are multiple failures every day during deployment, I have a follow up [ticket](https://codedotorg.atlassian.net/browse/ACQ-2662) to turn off `extendedDebugging` by 11/12/2024

**Comment by drizco** [comment]
oof... ui tests taking almost 3 hours on drone and not done yet 😞 

Screenshot 2024-11-07 at 5 43 22 PM

**Comment by drizco** [comment]
<s>@snickell I was able to get a drone run to finish by removing `extendedDebugging` from chrome and adding it to firefox. How do you feel about merging this?</s>

**Comment by drizco** [comment]
@snickell after some scattershot attempts to fix the flaky test, merging #62313 may have done the trick 🙌 

four clean runs on firefox and chrome since it merged 😁 

side note: should we maybe remove `extendedDebugging` from chrome to speed things up a bit?

Screenshot 2024-11-13 at 10 03 51 AM

**Pull request closed without merging**
