### PR TITLE
Enable SCSS lint rules

### PR DESCRIPTION
**Pull request by joshlory**
Fix & enable initial `scss-lint` cops for Dashboard.  If any of these seem too strict we can turn them back off.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
LGTM, though I'm definitely not an (S)CSS expert.

**Comment by breville** [comment]
lgtm.

do we ever want to force spaces after each : ?  it'd be dramatic, but i generally try to do that when i tidy up css.

**Comment by ashercodeorg** [comment]
Yes, I'm all for eventually turning on SpaceAfterPropertyColon. But that would be another (massive) PR.

**Comment by joshlory** [comment]
Opened PR https://github.com/code-dot-org/code-dot-org/pull/9176 for 'SpaceAfterPropertyColon'.

**Pull request merged**
