### PR TITLE
learn2016: Support IE11 by not using for-of & .includes

### PR DESCRIPTION
**Pull request by breville**

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
It's a little worrisome that babel doesn't take care of these for us (i.e. you _should_ be able to use these in code that we're transpiling)

**Comment by Bjvanminnen** [comment]
Includes in particular I think we use pretty significantly. I'm surprised it doesnt work in IE 11?

**Comment by Bjvanminnen** [comment]
changes look fine, tho we might want to investigate if we're broken in more places on IE (i can do this tomorrow)

**Comment by breville** [comment]
Yeah, in IE11 on SauceLabs I got errors for every use of includes.

**Comment by breville** [comment]
cool, thanks.

**Comment by Bjvanminnen** [comment]
https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/sites/studio/pages/code-studio.js#L10 I bet this is what's needed to make includes (and likely also for of) work. I wonder if we can automatically insert that into all of our entry points.

**Comment by Bjvanminnen** [comment]
@pcardune Is there a good webpacky way to make sure the polyfill ends up in every output file without manually inserting it into entry files?

**Comment by pcardune** [comment]
@Bjvanminnen I think the easiest way to do this is just to change `Gruntfile.js` to turn every entry point string into an array that includes `'babel-polyfill`. I will throw up a diff.

**Pull request merged**
