### PR TITLE
replace properties instead of merging

### PR DESCRIPTION
**Pull request by Bjvanminnen**
Are there reasons not to do this?

I also added --color=never to the grep. On my localhost, it was getting color info in the filename, and then wasn't managing to find the right file as a result.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Ran rake tests, and validated that on a multi puzzle I can remove properties. Are there other good scenarios to validate?

**Comment by laurelfan** [comment]
_1980 in history: June 1 – The first 24-hour news channel Cable News Network (CNN) is launched._

**Comment by wjordan** [comment]
Code change seems ok to me. The tests should be covering all of the existing scenarios worth validating, I can't think of any additional ones (though it might be worth adding a test to validate the scenario this PR is intended to fix).

**Comment by Bjvanminnen** [comment]
Added a new test in a place where it will be run. Opened https://www.pivotaltracker.com/story/show/92090332 to track the fact that existing dsl tests are not run, and would fail if they were run.

**Pull request merged**
