### PR TITLE
allow more tags and elements during html sanitization

### PR DESCRIPTION
**Pull request by davidsbailey**
Based on the logs at https://insights.newrelic.com/accounts/501463/query?hello=overview&query=SELECT%20currentUrl,channelId,removedHtml,safeHtml,unsafeHtml,sanitizationTarget,userAgentName,userAgentOS,userAgentVersion,city,regionCode,countryCode%20from%20PageAction%20where%20actionName%20%3D%20%27SanitizedLevelHtml%27%20since%201%20week%20ago%20limit%201000

### CODE REVIEW

**Comment by islemaster** [comment]
What are 'kl_vkbd_parsed' and 'pmbx_context'?

**Comment by davidsbailey** [comment]
The latter is from a chrome plugin:
http://stackoverflow.com/questions/24562263/what-is-pmbx-context-that-gets-injected-into-input-fields-etc
I
assume the former is too. The goal of adding these is to reduce the noise
level in our sanitization log events. It's not an ideal solution to keep
having to add things to the whitelist, but I'm not sure there's an easy way
to omit these attributes from our error logs without possibly masking other
things which sanitization is rejecting as well.

**Comment by islemaster** [comment]
Why can't we also add a 'squelch list' - blacklisted attributes that we don't need to log about?  Storing attributes for people's browser plugins just to avoid logspam feels like a slippery slope to me - and, in the worst case, could lead to people depending on behavior their plugins add in the apps they write.

**Comment by davidsbailey** [comment]
Good idea. That seems doable.

**Comment by davidsbailey** [comment]
Merging just the changes for `<font>` and `title=`, and punting on an ignore-list for plugin-specific attributes.

**Pull request merged**
