### PR TITLE
Denormalize Teacher Application constants into different years

### PR DESCRIPTION
**Pull request by islemaster**
Continuing work started in https://github.com/code-dot-org/code-dot-org/pull/31093 to replace the convoluted constant inheritance system we've used for teacher applications with duplicated (but admittedly simpler) configuration, as a cleanup step on our way to a more comprehensive refactor of how we model teacher applications.

The reason we believe this is a step in the right direction is that we've experienced quite a bit of pain in the past with the inheritance of constants for different application years and with the inheritance of the Teacher Application models from one another.  Application models for past years should be fixed, but we have changes in surprising places every year and it ends up taking more care to ensure we don't change past applications because they are so entangled.  

Bob Martin writes in _Clean Architecture_:

>  If two apparently duplicated sections of code evolve along different paths —if they change at different rates, and for different reasons— then they are not true duplicates.

...and, IMO, that's exactly the case we have here with annual revisions fixed in time and an "active" version that may yet evolve.

Next steps here will be work to deprecate and remove as much of past years' application code as possible, since we only need access to them as a read-only record.  I also believe that a lot of this teacher application code is really configuration, and should be treated as such.  Beyond that (and I hope we can address this late summer 2020) it would be amazing to get back to having only one Teacher Application model, and do the work to make applications readable/reproducible without a hard dependency on the code that created them.  Also the facilitator application and some of our other forms suffer from the same problem.

## Testing

I've leaned on existing application tests for this change, which as of this year are fairly thorough.  I've also tried to make the changes through small, well understood refactoring steps and have left each of those steps in as a separate commit for review purposes.

### CODE REVIEW

**Comment by islemaster** [comment]
Hey @clareconstantine will you please review this and let me know if it's the direction you expected to go?  I think this PR might be a good stopping point, even though it introduces quite a bit of duplication.

I found that I had to pull some methods up out of `TeacherApplicationBase` in order to get rid of `TeacherCommonApplicationConstants` entirely, but in most cases that just meant copying them into `Teacher1819Application` because `1920` and `2021` already had completely custom behavior.  The exception was `def self.options` which really is _mostly_ duplicated across the three applications; but in a sense, it's also just constants/configuration that changes a little each year, so I might be fine leaving it flattened/duplicated as well.

I haven't worked out where to go from here.  I'm assuming this starts to feel like a big win when we can tear out most of the code for past teacher applications.  Interested to hear your thoughts.

**Review by clareconstantine — APPROVED** [review]
This is the direction I was imagining. Although this is more duplication, it will definitely simplify the process of making a new application version, and we won't have to worry about breaking past years' tests because they won't be using the same constants.

**Comment by clareconstantine** [comment]
And yes - past applications are read-only, so we don't need most of the code in those models. We need to be able to either display them on the site or generate a CSV of them (at least this is my understanding of the outstanding ask), but we don't need most of the code in the models that isn't being used. Removing that code and the unit tests and just saving the question constants to be able to display the application content would feel like a big step.

**Comment by islemaster** [comment]
Thank you Clare!  The context is very helpful.  @hacodeorg will you also code review please?

**Review by hacodeorg — APPROVED** [review]
I agree with untangling annual applications. It's easier to delete dead code without worrying about side-effect to active code. (I also want to do the same thing with our email templates.)

**Pull request merged**
