### PR TITLE
Revert "Revert "Build Maze app from external repo""

### PR DESCRIPTION
**Pull request by Hamms**
Reverts code-dot-org/code-dot-org#21388

### CODE REVIEW

**Comment by Hamms** [comment]
Finally figured out what was going on here. Turns out, the strict mode violation fixed in this PR was actually causing an fully breaking error on iOS, and this PR was pointing against a version of Maze that did not include that PR.

Updating the dependency version is all it took!

**Comment by joshlory** [comment]
Hmm, I wonder why the error didn't repro on my iOS device test then?  Either way — nice find!

**Comment by Hamms** [comment]
It also turns out that it only manifests when apps code is built with `NODE_ENV=production`

**Comment by Hamms** [comment]
Seems like circle still isn't picking up these changes correctly. Reverting again

**Pull request merged**
