### PR TITLE
HoC.com - Remove "Advisors" language from footer and FAQ

### PR DESCRIPTION
**Pull request by kelbyhawn**
Remove "Advisors" language from footer and FAQ on hourofcode.com:
- Remove the words "and Advisors" from the "Partners and Advisors" link on the hourofcode.com footer
- Update the answer on the "Who is behind the Hour of Code?" question in the FAQ section

**Relevant info:** [Asana task](https://app.asana.com/0/1202773141567416/1202915781399790/f)

----

### Footer
_Before:_ 
Screen Shot 2022-09-06 at 2 46 36 PM

_After:_
after

----

### FAQ
_Before:_
before

_After:_
Screen Shot 2022-09-07 at 9 30 55 AM

### CODE REVIEW

**Review by bethanyaconnor — COMMENTED** [review]
Have you updated these strings in the gsheet?

**Comment by kelbyhawn** [comment]
> Have you updated these strings in the gsheet?

@bethanyaconnor I thought this file was the only place to update ([Slack convo context](https://codedotorg.slack.com/archives/C0T0UQH0R/p1661883185017169)), but I can def update the gsheet as well if needed! Can you share a link to it? I'm having trouble finding it.

**Review by bethanyaconnor — APPROVED** [review]
🤦‍♀️ didn't notice that you were updating the hourofcode.com files for some reason

**Comment by kelbyhawn** [comment]
@bethanyaconnor haha no worries! 😄

**Pull request merged**
