### PR TITLE
Re-enable `a11y/no-autofocus`

### PR DESCRIPTION
**Pull request by bencodeorg**
Interestingly, this is a rule that outlaws React's [own implementation of autoFocus](https://react.dev/reference/react-dom/components/input#props) (rather than [the HTML `autofocus` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus)).

Three cases of this in our code base currently (all in Java Lab 😬 ), and they all represent slightly different cases:
1.  **The console:** the existing `autoFocus` usage seems generally not super useful (across users), as it drops the cursor into the console on page load, where you can't really do anything until your program is running. If we were going to `autoFocus` anywhere, I'd expect we'd want to do it into the editor rather than the console. I've updated it to only focus the console when a student is running their program. This is helpful for cases where a program prompts a user for input, so that your cursor remains at the end of the most recent console log (eg, "What's your name?").
2. **The file name editing modal:** this seems more like a fine place to have `autoFocus` across users -- there's not much else you can do in the modal, and we drop you right into the place you'd want to be to edit a file name. That said, I removed the `autoFocus` (and basically reimplemented what I think React generally does by focusing the element when we open the modal), but would be open to just allowing `autoFocus` here if we think that's better. Upside is that we're explicit about when we're focusing (rather than relying on React's logic).
3. **The code review editing experience:** once a user opens the "Review" tab in the Instructions panel in Java Lab, we drop users directly into the input where you can write comments. This seems ok for sighted users, but I think could be confusing for unsighted/low vision users, as there is other functionality in the code review tab that you might want to be aware of before writing a comment (eg, a "Refresh" button, the ability to add code styling to your comment, etc). Removing `autoFocus` here seemed like a good in-between solution, as it still scrolls to the bottom of the content of the Review tab (it can get lengthy if you have a bunch of comments), but requires the student to click into the comment editing area. People using tab navigation would tab from the top, hitting the "Refresh" button, etc before landing in the comment editing area.

## Links

- [no-autofocus rule details](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-autofocus.md)

## Testing story

I tested each of these components manually in Chrome -- in particular, focus in the console when soliciting user input (at /s/allthethings/lessons/44/levels/2) appeared to function as it did previously. The cursor is placed at the end of the last console log -- here's an example:

image

### CODE REVIEW

**Review by bethanyaconnor — APPROVED** [review]
This change makes sense to me -- thanks for the thorough description!

**Review by thomasoniii — APPROVED** [review]
lgtm 🚀

**Review by Hamms — APPROVED** [review]
LGTM! Unfortunate that the code review editing experience is ever so slightly less convenient for sighted users, but agree that the improvement to the screen reader experience is worth it.

**Comment by breville** [comment]
Great write-up!

**Pull request merged**
