### PR TITLE
Build Maze app from external repo

### PR DESCRIPTION
**Pull request by Hamms**
All the code required to run a basic Maze game has been extracted to https://github.com/code-dot-org/maze; this PR removes all the code that now lives in that repo and updates everything remaining to reference it instead of our local code.

### CODE REVIEW

**Comment by joshlory** [comment]
Do we need to update this list so any ES6 in the Maze repo gets transpiled?

https://github.com/code-dot-org/code-dot-org/blob/d4f0aa7bc6376720f3f2cc83bb5e8e414bd01d0b/apps/webpack.js#L11-L21

**Comment by Hamms** [comment]
That should be being handled by the Maze repo itself, but I'll verify

**Comment by Hamms** [comment]
Confirmed that the package being built by maze is fully transpiled

**Comment by Hamms** [comment]
Ah, dang. Okay, so the package being built by maze is fully transpiled, but unfortunately we in the code are not actually _using_ the package being built by maze but instead just directly referencing the source files. This is following the same pattern as we use for Minecraft (and thus Josh's point about needing to add maze to the webpack config is 100% correct), but it's in violation of how externally-built dependencies should in general be used.

For now, I'll update the webpack config to make things work as they currently are. I created an issue here https://github.com/code-dot-org/maze/issues/5 to eventually improve this process.

**Comment by balderdash** [comment]
Does that mean we're not (yet) getting faster builds from having these apps in separate repos?

**Comment by Hamms** [comment]
That's correct; we are getting faster test runs but not yet faster builds

**Comment by Hamms** [comment]
@joshlory @balderdash finally got circle tests passing. PTAL

**Pull request merged**
