### PR TITLE
Switch to using browserify-inc to speed up grunt builds

### PR DESCRIPTION
**Pull request by trevorb**
Incremental rebuild for browserify
Update any source file and re-bundle, and only changed files will be parsed, so it will build super fast (even with big dependencies like React!).

How is this different from watchify?
browserify-incremental can detect changes which occured in between runs, which means it can be used as part of build systems which are invoked on demand, without requiring a long lived process. Whereas watchify is slow for the first run upon each startup, browserify-incremental is fast every time after the very first.

https://github.com/jsdf/browserify-incremental

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
I wonder whether the cache-file should live in the build directory (rather than in a /tmp file outside of the repo). This means on rebuild (clean + build) we lose our cache, but that seems like it might be the expected behavior. What do you think?

Also, should this be dev only? I'm not sure if there are any dangers to running this for our production build. If we move the config file, this becomes moot, since we'll be doing a clean + build.

**Comment by trevorb** [comment]
I'm not familiar with the code.org build and deploy system yet so I'll defer to you on how you think it should work.   I'll update the pull request and move the cache file to the build directory and add it to git ignore.

I'm always in favor of making dev and prod as similar as possible so I'd lean toward using browserify-incremental in production as well. Let me know if you feel strongly otherwise.

**Comment by Bjvanminnen** [comment]
lgtm. thanks for doing this :)

**Comment by trevorb** [comment]
Cool.  Given that I'm adding a new package do I need to do anything special when deploying?

**Comment by Bjvanminnen** [comment]
Nope. The CI system should be smart enough to npm install. Devs however are not always smart enough to do so, and may hit problems.

**Pull request merged**
