### PR TITLE
Upgrade Appium

### PR DESCRIPTION
**Pull request by aoby**
We have been seeing periodic test failures on iOS with a sudden `ERROR Selenium Server stopped responding`.

Sauce labs support looked into a few of the failures and notices they all had this:
```
2017-10-17 23:26:39:339 - error: uncaughtException: "callback" argument must be a function date=Tue Oct 17 2017 16:26:39 GMT-0700 (PDT), pid=6244, uid=600, gid=4294967295, cwd=/Volumes/Sauce/selenium/appium-v1.4.16, execPath=/usr/local/Cellar/node/6.9.1/bin/node,
```

Which they think is a bug in Appium, likely fixed already because we're using an outdated version. This is upgrading us from `1.4.16` to `.1.6.5`, currently the latest version supported by SauceLabs for iOS 9.2.

### CODE REVIEW

**Comment by davidsbailey** [comment]
If you have not done so already, it seems worth running the UI tests on iOS. You can run these on circle by adding `[test ios]` to the commit message. Here is an example of a PR with UI tests passing on circle on ipad: https://github.com/code-dot-org/code-dot-org/pull/18291

**Comment by aoby** [comment]
Thanks for the suggestion. Running now with `[test ios]`...

**Comment by aoby** [comment]
Tests failed with a new error. Following up with SauceLabs...

**Comment by davidsbailey** [comment]
It looks like all the failures are on iPhone. It might be worth ruling out whether this was an existing problem with the older version of appium + iphone + our ui tests + circle.

**Comment by aoby** [comment]
It looks like half and half (iPad/iPhone) to me. Am I missing something?

image

**Comment by davidsbailey** [comment]
Nope, you are correct. contacting SauceLabs sounds right.

**Comment by joshlory** [comment]
@aoby great suggestion on catching the "Element does not exist in cache" — that seems to have fixed the UI tests for the new version of Appium.  I think this PR is ready to merge!

**Pull request merged**
