### PR TITLE
Revert "Revert "Move react to code studio""

### PR DESCRIPTION
**Pull request by islemaster**
Reverts code-dot-org/code-dot-org#6321

### CODE REVIEW

**Comment by islemaster** [comment]
I'm still not sure what went wrong.

0a34543 is the commit by staging, that _should_ have been its rebuild following my change (you can see my PR merge in the commit list). It _does_ include changes to code-studio-package, but not enough of them - it should include the rename of leveltype_widget.js to levels/widget.js, among others.  If you look at the staging server now, it's code-studio-package has the `levels` directory (which is created before the browserify step) but there's nothing in it - almost like the build failed, or got skipped, or something.

Here's the HipChat staging log right after my merge:

screenshot from 2016-01-13 16-26-01

Stuff seems significantly out-of-order, which can happen in HipChat, but it doesn't make me feel any better.

**Comment by Bjvanminnen** [comment]
So is the plan to just try again and hope things are different this time?

**Comment by islemaster** [comment]
I guess I'm asking your opinion - you've been looking at the aws/build.rake stuff, right?  Do you have any idea why staging would fail to build/commit an updated code-studio package?

**Comment by Bjvanminnen** [comment]
A little, though I haven't really been in the meat of what were currently doing much yet. I wonder if it's worth initially adding a bunch more logging (like maybe all the things in the code-studio package) that we can scale back once we have a little more confidence.

**Comment by islemaster** [comment]
Added some logging.  Other than that, I don't have a better idea than to try this again and monitor it closely on staging.

**Comment by Bjvanminnen** [comment]
Me neither. Have at it :)

**Pull request merged**
