### PR TITLE
Updating manage students table to account for additional column

### PR DESCRIPTION
**Pull request by hannahbergam**
This PR is admittedly still an imperfect solution, but takes additional measures to account for column widths when there is the additional sharing column:

Screenshot 2023-09-07 at 3 34 50 PM
Screenshot 2023-09-07 at 1 05 35 PM
Screenshot 2023-09-07 at 1 06 18 PM
Screenshot 2023-09-07 at 1 10 32 PM

## Links

- spec: []()
- jira ticket: https://codedotorg.atlassian.net/browse/TEACH-664

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by kobryan0619 — APPROVED** [review]
Looks good to me!  You mentioned it is an "imperfect" solution - are you planning a "perfect" solution later?  If so is that work documented?

**Review by etaderhold — APPROVED** [review]
Seems kinda weird that you can set fixed widths for these individual columns and then the overall width looks good whether the additional column is included or not, but the screenshots don't lie!

I see there's no space between the two buttons at the top of the page in the Arabic language view. Log a bug?

**Comment by hannahbergam** [comment]
> Looks good to me! You mentioned it is an "imperfect" solution - are you planning a "perfect" solution later? If so is that work documented?

I'd love to do a refactor of the formatting on this table (and likely, all our similar teacher tables) because we'd ideally have a much more centralized way to set min and max widths relative to the header names. Right now feels like whack-a-mole instead! I'll create a ticket for our backlog to capture this.

**Comment by hannahbergam** [comment]
> > Looks good to me! You mentioned it is an "imperfect" solution - are you planning a "perfect" solution later? If so is that work documented?
> 
> I'd love to do a refactor of the formatting on this table (and likely, all our similar teacher tables) because we'd ideally have a much more centralized way to set min and max widths relative to the header names. Right now feels like whack-a-mole instead! I'll create a ticket for our backlog to capture this.

https://codedotorg.atlassian.net/browse/TEACH-668

**Comment by hannahbergam** [comment]
> Seems kinda weird that you can set fixed widths for these individual columns and then the overall width looks good whether the additional column is included or not, but the screenshots don't lie!
> 
> I see there's no space between the two buttons at the top of the page in the Arabic language view. Log a bug?

First of all- arabic bug: https://codedotorg.atlassian.net/browse/TEACH-669. 

And more importantly- there's some magic going on there around '100%' widths that helps with the resizing scenarios. It's also maddening to work with because there's some fun hierarchy around which width gets priority in which scenario. I made a ticket here to refactor and unify this formatting across all our tables. https://codedotorg.atlassian.net/browse/TEACH-668

**Pull request merged**
