### PR TITLE
[Finishes #107783528] better sound url

### PR DESCRIPTION
**Pull request by Bjvanminnen**
The existing url for playSound does not actually exist.

We had two goals here. (1) To use a sound that exists (2) to get a shorter url.

This has some weirdness in that the "fixed" block still won't work in any of our environments until the new sound (which is the bee win sound) makes it to production.

Ideally I would also create a test that made sure that we don't delete this sound file at some point in the future without realizing it's use. However, I couldn't come up with a good way to do that, in part because Phantomjs does not support audio. Open to ideas.

### CODE REVIEW

**Comment by islemaster** [comment]
URL swap LGTM.  Checking whether audio actually plays is a tricky task, as you can probably see in my other PR.  Would it be sufficient to write a UI test that creates a playSound block and reads the default URL, then hits that default URL and confirms that it's not a 404?

**Comment by Bjvanminnen** [comment]
Not sure of the best way to do that even. I tried just extracting the url from dropletConfig and doing an ajax of the url, but that was failing because of cross domain reasons.

**Comment by islemaster** [comment]
Oh - will that sound not work in any environment other than production, since it's got a production URL?

**Comment by Bjvanminnen** [comment]
It will work, because within playSound we proxy assets. It might be the case that I can just do that proxying in my test and that will work.

**Comment by Bjvanminnen** [comment]
Try to get the test working with the proxy is still not working, for reasons that aren't clear to me. I've already spent more time on this than is justified, so I'm going to merge the URL change without any sort of test coverage.

**Pull request merged**
