### PR TITLE
[Finishes #114815849] prevent nested execution from onTick

### PR DESCRIPTION
**Pull request by Bjvanminnen**
I don't fully understand when there are valid situations to be nesting calls to executeInterpreter, but it looks like we have code that explicitly supports this, so I assume there are some. I suspect we should never be calling it from onTick if we're already in the process of executing, but again I could be wrong.

The behavior I'm trying to guard against can be represented by the following code:

```
setTimeout(function () {
  console.log('timeout');
}, 1);

var result = prompt('hi');
console.log('prompt');
```

In most browsers, this will always print prompt, then timeout. In Firefox, it will occasionally print timeout first.

What this means for us is that sometimes our onTick (which gets schedule via setTimeout) ends up being called immediately after a call to prompt. This means that if I have the following code:

```
console.log(prompt('asdf'))
```

console.log ends up being executed by the interpreter before it has put the result of prompt('asdf') onto the stack. This means we instead end up logging the last thing that was putting on the stack, which is 'asdf'.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
cc @joshlory

**Comment by cpirich** [comment]
LGTM

I don't think we ever want to call `executeInterpreter` when it is already on the stack. The only place I see `executeLoopDepth` being used for today is to avoid doing the same thing. But in that case, the alternative needs to queue up an event. In this case, it makes sense just to skip this call to `executeInterpreter`. We may want to move this code directly into `executeInterpreter` in case other apps try to expose `prompt` or `alert`.

**Comment by Bjvanminnen** [comment]
What would moving this code into `executeInterpreter` look like? Just return immediately if `executeLoopDepth > 0`? if that's the case, would it make more sense to just have this be a bool `isExecuting`?

**Comment by cpirich** [comment]
Yes and yes. The only hesitation I have is burying the "error". Any way we could log this as a warning?

**Comment by cpirich** [comment]
Perfect - thank you!

**Pull request merged**
