### PR TITLE
P20-1075: Add cron job to send warnings about CAP sections to teachers

### PR DESCRIPTION
**Pull request by artem-vavilov**
## Links
- JIRA task: [P20-1075](https://codedotorg.atlassian.net/browse/P20-1075)
- Related PR: https://github.com/code-dot-org/code-dot-org/pull/60645

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
~This seems overly complicated.~

~Why does the implementation code need to be in an ActiveJob class? To be clear, I don't think the implementation code belongs in the cron job either - I recommend putting implementation code in an easy to test class which is called by any scripts or jobs that need it.~

I redact that. I think I see what you're doing here and I like it!

In a world where our Jobs are on their own compute resources, this makes perfect sense. Lightweight scheduling via cron, delegating the actual work to the job worker resources.

**Review by cat5inthecradle — APPROVED** [review]
One thing to consider is that we have a single queue, and the timely execution of jobs like this depends on the queue being empty with workers ready to take new tasks. This job looks like it can safely wait a few minutes/hours if the queue is busy, but other jobs in the future might not be able to handle that.

In the future we'll probably want to update this to support enqueuing things to different queues or with different priorities (if our backend supports it). We may want a time-specific task to jump the line.

**Review by daynew — APPROVED** [review]
Wow thank you for creating a general solutions others will be able to use as well!

**Comment by artem-vavilov** [comment]
> In a world where our Jobs are on their own compute resources, this makes perfect sense. Lightweight scheduling via cron, delegating the actual work to the job worker resources.

@daynew, thank you for the idea!

**Review by daynew — APPROVED** [review]
Thank you for updating the schedule!

**Pull request merged**
