### PR TITLE
Teacher view of student work shouldn't save progress locally

### PR DESCRIPTION
**Pull request by breville**
We shouldn't update local session storage for progress with a student's work, when we're a teacher viewing the student's work.

### CODE REVIEW

**Comment by breville** [comment]
The second two commits do this more elegantly, and prevent it from writing both when viewing the header, and when opening the course progress dropdown.

**Comment by Bjvanminnen** [comment]
Presumably this issue has been live for a while vs. being a recent regression?

If the URL is something like: http://localhost-studio.code.org:3000/s/allthethings/stage/30/puzzle/1/page/1?user_id=1&section_id=1
Instead of passing viewingOtherUser around everywhere, could we just check to see whether we have a user_id query param?

**Comment by breville** [comment]
It does seem as though this has probably existed for a while.

I was checking window.location down in progress.js in the original commit, but added the parameter so that we could check for the param in Ruby (in the view haml) and not be relying on having access to window.location in progress.js, which felt a bit more proper.

**Comment by joshlory** [comment]
We should de-duplicate this against the existing code:

``` javascript
var isViewingStudentAnswer = !!clientState.queryParams('user_id');
```

https://github.com/code-dot-org/code-dot-org/blob/30bf42d3289e0ad0611d236826b2dd4b36faa560/apps/src/code-studio/initApp/loadApp.js#L39

**Comment by breville** [comment]
@joshlory @Bjvanminnen  Can you suggest the best way to do that?

**Comment by breville** [comment]
Okay, I think this simplifies things for now.  

Couldn't see an obvious way to generate the value in a single place because of the different paths into setting up the app vs. the header.  But we seem to be okay with using clientState to examine the params.   I also considered hoisting the check into clientState.batchTrackProgress itself, but that would make a strong assumption about how the function is used.

**Comment by Bjvanminnen** [comment]
This lgtm. I do think I like this better :)

**Pull request merged**
