### PR TITLE
Update playlab names for indiegogo donors.

### PR DESCRIPTION
**Pull request by breville**
- penguin -> Waddles, cave girl -> Jasmine, robot -> Spiff
- dropdown shows new name in parentheses after old name
- instructions updated to use new name only

### CODE REVIEW

**Comment by sfilman** [comment]
@breville Will this affect existing programs? Just want to make sure that playlab projects and autoloaded code in levels won't break with this.

**Comment by Bjvanminnen** [comment]
Changes are only to text (rather than block names), so this shouldn't break existing projects in any way AFAIK.

**Comment by tanyaparker** [comment]
@breville I confirm these are all the instructions and there aren't any callouts that mention them. The "Course 4 Play Lab Vars 1 (copy 1)" level from instructions.en.yml isn't being used. I've deleted it on levelbuilder. OK to merge, it will just be removed from instructions.en.yml after next sync.

**Comment by tanyaparker** [comment]
@breville actually can we wait on merging? There will be a slight delay between English and non-English. The non-English will keep old translations. Can we wait for translations and merge Monday or Tuesday?

**Comment by breville** [comment]
@tanyaparker sure.  do we need to commit any part of this PR so we have something to translate?

**Comment by tanyaparker** [comment]
Just to update everyone: since the commitment is only for a month and not permanent we will not re-translate. I'll notify our translators not to re-translate these strings when they see it's been updated with these names.

So the PR Is ready to merge and can be merged any time.

**Pull request merged**
