### PR TITLE
fix ref guide links in vpl-csd-summer-pilot-ci and self-paced PL courses

### PR DESCRIPTION
**Pull request by davidsbailey**
FInishes [PLAT-1875](https://codedotorg.atlassian.net/browse/PLAT-1875). See analysis in [ref guide PL units](https://docs.google.com/spreadsheets/d/1O0j89OPhXq0Zkq6wzXxVIu1SLlPYqhx9NfzKdJ4219k/edit#gid=0) gsheet. 

## Testing story

Manually verified a link or two in each commit to confirm that the old link was broken and the new link was fixed

### CODE REVIEW

**Comment by dmcavoy** [comment]
Just double checking: there are two different pilot pl courses `vpl-csd-summer-pilot-ci-2022` and `vpl-csd-summer-pilot-2022`. When I looked quickly it looked like you were working on `vpl-csd-summer-pilot-ci-2022` but just wanted to make sure

**Review by dmcavoy — APPROVED** [review]

**Comment by dmcavoy** [comment]
Do we still need to check the script to figure out what happened?

**Comment by davidsbailey** [comment]
> Just double checking: there are two different pilot pl courses `vpl-csd-summer-pilot-ci-2022` and `vpl-csd-summer-pilot-2022`. When I looked quickly it looked like you were working on `vpl-csd-summer-pilot-ci-2022` but just wanted to make sure

Hi Dani, yes, that's correct. Thanks for checking. In 8b39196d2d661c576ffb63d6d4c284086562cc72 I used the following find-replace: `/courses/vpl-csd\d-ci-pilot-2022` --> `/courses/vpl-csd-summer-pilot-ci-2022`. Unlike the previous PR, the course name is not simply the unit name minus the number. Then I did similar replacements for each of
```
/courses/self-paced-pl-csd\d-2022 --> self-paced-pl-csd-2022
/courses/self-paced-pl-csp\d-2022 --> self-paced-pl-csp-2022
/courses/self-paced-pl-csa\d-2022 --> self-paced-pl-csa-2022
```

**Comment by davidsbailey** [comment]
> Do we still need to check the script to figure out what happened?

It looks like the problem is here, where we use the `course_name` (which IIRC is actually the script name) rather than the course version name: https://github.com/code-dot-org/code-dot-org/blob/4aff13fd48f4a033aae3944a2eaacf1c44fb5340/bin/curriculum/migrate_reference_guides.rb#L99

I can't think of a scenario where we would need to run this script again, so my thought would be not to spend time on fixing it.

**Pull request merged**
