### PR TITLE
Don't override global `appOptions` in multi levels with embedded blocks

### PR DESCRIPTION
**Pull request by joshlory**
Fix submitting multi levels with embedded blocks, regressed in PR https://github.com/code-dot-org/code-dot-org/pull/19224.

### CODE REVIEW

**Comment by ryansloan** [comment]
fyi @mrjoshida

**Comment by joshlory** [comment]
Do you prefer that fix instead?  I was trying to keep the fix as conservative as possible, in case any apps depend on overwriting `window.appOptions` at some point during the init process.  The idea would be that we could add `nonGlobal` to options of apps as we discover they don't need to be attached to window.

**Comment by joshlory** [comment]
Granted, that seems pretty unlikely.  That's what's scary about global vars — no dependency tracking 😄.

**Comment by Hamms** [comment]
Bleh, good point.

I think I like this approach, but only with some pretty verbose comments in loadApp explaining what's going on

**Comment by joshlory** [comment]
Hmm, actually, I think you're right.  We should make the "right" change now and deal with any potential fallout.  I can't think of any other places we'd set `appOptions` multiple times.  It should be obvious if there are any regressions.

**Comment by joshlory** [comment]
@Hamms I'm still running into test failures, now in UI tests.  Going to switch back to the original more conservative approach.

**Pull request merged**
