### PR TITLE
Update piskel package to use new styles

### PR DESCRIPTION
**Pull request by caleybrock**

### CODE REVIEW

**Comment by islemaster** [comment]
LGTM!

**Comment by caleybrock** [comment]
Just to note to the next dev of the day if you happen to be looking at this, this PR will purposely break eyes tests, but those eyes tests won't run on this PR because you have to be logged in to view gamelab.

screen shot 2016-09-02 at 12 02 08 pm

**Comment by caleybrock** [comment]
@islemaster I pulled from staging to try to fix this, but it's still failing on `ChromeLatestWin7_publicKeyCryptography_eyes_eyes failed`

**Comment by caleybrock** [comment]
@bcjordan do you think this is still okay to merge despite tests?

**Comment by bcjordan** [comment]
Notes re: eyes failure from looking & discussion with Caley:
- Should be fine to merge, eyes failure looks unrelated.
- The branch seems to have cached "no baseline" as its baseline for newly added steps in `ChromeLatestWin7_publicKeyCryptography_eyes_eyes`
- A [staging CircleCI run](https://circleci.com/gh/code-dot-org/code-dot-org/20802) from the same time which should have the same contents / baselines passed.
- Running a merge from staging into the branch produces a conflict, seeming to suggest somehow the Eyes branch cached "no baseline" for those steps during its [first failing run #20776](https://circleci.com/gh/code-dot-org/code-dot-org/20776)

```
Brians-MacBook-Pro:code-dot-org brian$ rake eyes:merge[staging,update-piskel-package]
development: 🔀  Merging baselines {:branch=>"staging", :base=>"update-piskel-package"}
 409 Conflict
```

Given all of this, I expect the next staging build with this branch's merge will output during the `rake eyes:merge_eyes_baselines` step a conflict trying to merge the branch's eyes baselines -> staging.

Will ask Applitools team about this scenario and see if we can dig up how that run cached the non-accepted new baselines.

**Pull request merged**
