### PR TITLE
Fix the location of video download icon for games when the language bidi is rtl

### PR DESCRIPTION
**Pull request by rezasafi**
This fix will resolve the issue with the location of the download icon for the games' intro video. Before this change the download arrow was almost hiding behind the close icon. As an example you can see this for dance party video:
Screen Shot 2020-01-26 at 4 03 21 PM
The same issue exists for mine craft as well.
After this fix the download arrow will be shown to the right of the gray bar as you can see here:
Screen Shot 2020-01-26 at 4 17 36 PM
I checked for a few games and verified that the issue is fixed for those after applying this change.

### CODE REVIEW

**Comment by rezasafi** [comment]
@daynew I appreciate your review here. Thanks in advance.

**Comment by Hamms** [comment]
I'm seeing a sizing/padding difference in the header between the two versions:

Before | After
--- | ---
image | image

Looks like the hover effect has also changed; @rezasafi, do you repro?

**Comment by rezasafi** [comment]
@Hamms I will take a closer look over the weekend to see why this is happening. Thanks for catching this.

**Comment by rezasafi** [comment]
@Hamms it seems that using inherent in css('float', 'inherent') has  caused those problems that you discovered. I pushed a new fix by not using inherent. I also tested it and the issue that you discovered didn't occur using the new fix. Thanks in advance.

**Review by Hamms — COMMENTED** [review]
Does `inline-start` work for both RTL and LTR?

```js
  var download = $('<a/>')
    .append($('<img src="/shared/images/download_button.png"/>'))
    .addClass('download-video')
    .css('float', 'inline-start')
    .attr('href', options.download)
    .click(function() {
      // track download in Google Analytics
      trackEvent('downloadvideo', 'startdownloadvideo', options.key);
      return true;
    });
```

**Comment by rezasafi** [comment]
@Hamms using "inline-start" created the same error as "inherent" when I tested locally:
Screen Shot 2020-02-09 at 8 26 19 PM

Notice the sizing/padding that is there.

**Review by Hamms — APPROVED** [review]
oh, weird. In that case, this LGTM!

I'll run the automated tests against what you've got here

**Comment by Hamms** [comment]
[Tests passed!](https://drone.cdn-code.org/code-dot-org/code-dot-org/9930) I'll merge.

Thanks for your thoroughness here!

**Pull request merged**
