### PR TITLE
Fix invalid font: Gotham 3r -> Gotham 4r

### PR DESCRIPTION
**Pull request by breville**
We don't have a "Gotham 3r", so update all such references to "Gotham 4r".

### CODE REVIEW

**Review by bencodeorg — APPROVED** [review]
For my understanding, where do we specify which fonts we have? Always have trial and errored this sort of thing in the past.

**Comment by kelbyhawn** [comment]
> For my understanding, where do we specify which fonts we have? Always have trial and errored this sort of thing in the past.

I'd also be interested in seeing what it would take to refactor how fonts are implemented across the site so instead of using `font-family` to define a weight we can use the `font-weight` property.

**Review by kelbyhawn — APPROVED** [review]

**Comment by maddiedierker** [comment]
@bencodeorg and @kelbyhawn great questions! i did a deep dive on this somewhat recently so i figured i'd knowledge-share here...

this is how fonts are created/loaded **in dashboard and apps**:
- `@font-face`s are created in [`dashboard/vendor/assets/stylesheets/gotham-font.css`](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/vendor/assets/stylesheets/gotham-font.css). @kelbyhawn this file is the reason why we have to use `font-family` instead of `font-weight` (you'll see all font faces are set to "normal" font-weight, which is not ideal!)
- [`shared/css/font.scss`](https://github.com/code-dot-org/code-dot-org/blob/staging/shared/css/font.scss) sets those font faces to SCSS variables
- `dashboard/app/assets/stylesheets/application.scss` imports both [gotham-font](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/assets/stylesheets/application.scss#L16) and [font.scss](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/assets/stylesheets/application.scss#L32)

@breville do you know how this works for pegasus? i know pegasus can access shared/css/font.scss since it's in shared/, but does it piggyback on any of the other dashboard setup, or are fonts completely separate in pegasus?

**Review by maddiedierker — APPROVED** [review]
thank you for doing this clean-up!!

**Comment by breville** [comment]
It appears that Pegasus uses its own full set of the fonts in [`code.org/public/fonts`](https://github.com/code-dot-org/code-dot-org/tree/a909990ddfb01b7f9d5425b6769d439f24eac8d1/pegasus/sites.v3/code.org/public/fonts).  It also has a subset in [`code.org/public/css/fonts.css`](https://github.com/code-dot-org/code-dot-org/blob/a909990ddfb01b7f9d5425b6769d439f24eac8d1/pegasus/sites.v3/code.org/public/css/fonts.css), which are used before the full set are loaded, as implemented [here](https://github.com/code-dot-org/code-dot-org/pull/16031).

**Pull request merged**
