### PR TITLE
Add columns to gdrive

### PR DESCRIPTION
**Pull request by megcrenshaw**
Eric F in marketing requested two more columns on our gdrive export: the school name and the school district. Luckily, those are both methods defined in our TeacherApplication model.

I tested this in production, running the script manually –– can see the results here: https://docs.google.com/spreadsheets/d/1hyF__4aDzCveA0j2VvckgskEqaeBHd-VfKgAzxARuVU/edit#gid=1332401829

image

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
> I tested this in production, running the script manually –– can see the results here: https://docs.google.com/spreadsheets/d/1hyF__4aDzCveA0j2VvckgskEqaeBHd-VfKgAzxARuVU/edit#gid=1332401829

wrong link? I don't see the new headers there

**Comment by megcrenshaw** [comment]
Ah, good point -- they got overridden by the auto run of this job (which has the old code)

**Comment by megcrenshaw** [comment]
I took a screenshot of what I could but didn't want to include the school names themselves

**Comment by davidsbailey** [comment]
ahh I see. ok, looks good!

**Review by davidsbailey — APPROVED** [review]

**Pull request merged**
