### PR TITLE
recover gracefully when fetching stage descriptions

### PR DESCRIPTION
**Pull request by davidsbailey**
Quick fix for broken pull-through of stage descriptions when levelbuilder has more stages than curriculum builder does. See https://codedotorg.slack.com/archives/CA3KCSGTD/p1585949395130800 for more context.

## Testing story

manually verified locally that when LB has more stages than CB, the operation succeeds instead of failing, and there is enough info in the output to see which stages are missing from CB:
Screen Shot 2020-04-03 at 3 34 23 PM

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by mvkski — APPROVED** [review]
LGTM! Is it possible to also add unit tests for this case? Possibly after shipping, if this is time sensitive

**Comment by davidsbailey** [comment]
Good idea! Please take another look.

**Comment by davidsbailey** [comment]
I confirmed that this test passes locally, but if i run it without the code change, it fails in the way we were seeing on levelbuilder:
```
FAILED TESTS:
  entry tests
    StageDescriptions
      ✖ recovers when importedDescriptions are missing
        PhantomJS 2.1.1 (Mac OS X 0.0.0)
      Fake XHR onreadystatechange handler threw exception: undefined is not an object (evaluating 'importedStage.descriptionStudent')
      webpack:///src/lib/script-editor/StageDescriptions.jsx:155:47 <- test/entry-tests.js:108306:56
```

**Review by mvkski — APPROVED** [review]
👍👍

**Pull request merged**
