### PR TITLE
fix(dsco): stub css and sass for jest

### PR DESCRIPTION
**Pull request by stephenliang**
When in jest, sass and css files need to be stubbed out as jest does not render out css/sass.

### CODE REVIEW

**Review by levadadenys — APPROVED** [review]
Checked locally, everything working! Thank you!

**Review by kelbyhawn — APPROVED** [review]
Does anything need to be done on our end locally, or should this do what we need automatically?

**Comment by stephenliang** [comment]
> Does anything need to be done on our end locally, or should this do what we need automatically?

Nope! This is pretty standard setup for jest when you also use css/sass. `apps` does this too.

**Comment by kelbyhawn** [comment]
> > Does anything need to be done on our end locally, or should this do what we need automatically?
> 
> Nope! This is pretty standard setup for jest when you also use css/sass. `apps` does this too.

Nice! More learning ✨

**Pull request merged**
