### PR TITLE
CAUTION: Drop courses table

### PR DESCRIPTION
**Pull request by davidsbailey**
## Background

One of many steps to complete [PLAT-234](https://codedotorg.atlassian.net/browse/PLAT-234).  Step 3 of 3 to rename the courses table to unit_groups. please see [courses table rename proposal](https://docs.google.com/document/d/1-Dxlk00DSFPa35SqvWL2YkHJ0kfUy2a50xBZkiD4pBI/edit#heading=h.xz5b9e31july) for context. 

* Step 1: #35949
* Step 2: #35952
* Step 3: #35953 (this PR)

## Description

Drops the courses table, and adds foreign key constraints on the new unit_groups table. 

CAVEAT: This migration is not reversible. If someone does need to reverse it, and needs to further reverse back to where the courses table had data in it, they might be able to use syntax from https://github.com/code-dot-org/code-dot-org/pull/35949 to copy the data from unit_groups back to courses, but I didn't have enough confidence in this working to include this syntax in the migration.

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by uponthesun** [comment]
> CAVEAT: This migration is not reversible. If someone does need to reverse it, and needs to further reverse back to where the courses table had data in it, they might be able to use syntax from #35949 to copy the data from unit_groups back to courses, but I didn't have enough confidence in this working to include this syntax in the migration.

How come? Is there a reason it should be different from #35949?

I think I'd rather have the `down` method implemented here and manually tested so we have something available to run if we need to, rather than having to figure that out if we have a problem. Unless you think that the manual steps we'd try to revert would be different from what you would put here.

I also assume we would wait for a while to see that everything is working with the `unit_groups` table in production before merging and deploying this migration, which should mitigate the risk significantly. But it doesn't seem like a lot of extra work given you've already done #35949, correct me if I'm wrong.

**Comment by davidsbailey** [comment]
If someone is trying to revert this migration, do you think it is fair to assume that they successfully copied the contents of the courses table into unit_groups? I could add the SQL statements to make this work in the expected case, but I'm a bit worried that someone could end up with an empty table if they are reverting because they ran into a problem. if that happened, they'd be able to regenerate the table contents via `rake seed`, but they'd have lost any section assignments, which is probably fine everywhere except production.

**Comment by davidsbailey** [comment]
> I also assume we would wait for a good while to see that everything is working with the unit_groups table in production before running this migration, which should mitigate the risk significantly. But it doesn't seem like a lot of extra work given you've already done #35949, correct me if I'm wrong.

OK, I think you've convinced me here -- sorry for the partial response above. Waiting a substantial period of time before merging this PR does seem like it would go a long way toward mitigating potential risks. After the PR before this one is merged, I could also send mail requesting developers to migrate / seed their local environments to help uncover one-off issues in development.

**Comment by davidsbailey** [comment]
@uponthesun please take another look. Verification steps I've done after reversing the migration (in my test DB):
* courses and unit_groups tables appear identical again
* at least 1 unit test passes
* schema.rb returned to it's original state (no output for `git diff use-unit-groups-table -- dashboard/db/schema.rb`)

**Comment by davidsbailey** [comment]
@uponthesun PTAL: https://github.com/code-dot-org/code-dot-org/blob/61068eba74d806627e096c22ef151f74d7715c49/dashboard/db/migrate/20200722231459_drop_courses_table.rb#L3-L5

**Pull request closed without merging**
