### PR TITLE
Remove merge operation from i18n sync

### PR DESCRIPTION
**Pull request by Hamms**
As a follow-up to https://github.com/code-dot-org/code-dot-org/pull/23706, which does a sync without the merge, this removes the merge operation entirely from our sync process, extracting the sanitization and serialization work that it also did as a side effect.

### CODE REVIEW

**Comment by Hamms** [comment]
[single source of truth for translations](https://trello.com/c/iwKaJZN2/210-single-source-of-truth-for-translations)

**Comment by Hamms** [comment]
[figure out what's up with the outdated apps translations](https://trello.com/c/U0tpbPio/17-figure-out-whats-up-with-the-outdated-apps-translations)

**Comment by Hamms** [comment]
[Investigate: Some strings are not appearing in crowdin](https://trello.com/c/3rBawzjb/215-investigate-some-strings-are-not-appearing-in-crowdin)

**Comment by tanyaparker** [comment]
I'll let Josh review the code. The concept of this PR LGTM. :)

**Pull request merged**
