### PR TITLE
Update instructions to how to get properties encryption key

### PR DESCRIPTION
**Pull request by bencodeorg**
Update how to get properties encryption key (AWS Secrets Manager).

### CODE REVIEW

**Comment by davidsbailey** [comment]
When I recommended this, I didn't realize we already had a link to this secret in chef. Perhaps @wjordan can confirm whether this change moves us in the right direction (from chef to AWS secrets)?

**Comment by bencodeorg** [comment]
Yeah apologies I didn't see this comment originally, my locals.yml is old and didn't have the Chef recommendation. I thought Secrets Manager was the preferred way of accessing secrets now?

**Review by davidsbailey — APPROVED** [review]
That was my impression as well. LGTM, then!

**Comment by bencodeorg** [comment]
Oops, I've messed something up git-wise...won't merge until resolved.

**Comment by bencodeorg** [comment]
Did something wonky, closing in favor of https://github.com/code-dot-org/code-dot-org/pull/35965 (cherry picked version of same commit reviewed here).

**Pull request closed without merging**
