### PR TITLE
Create script to set audiences on UnitGroup and Script

### PR DESCRIPTION
**Pull request by dmcavoy**
Set the participant_audience and instructor_audience for UnitGroup and Scripts based on the [list provided by product](https://docs.google.com/document/d/1Fxujn_bdHu0Z_0XMnAfaOom3uh0uAizT6wiEwSjfKlI/edit).  The default is for instructor_audience to be teacher and participant_audience to be student. Also if a Script is in a UnitGroup we just set the UnitGroup values.

## Links

- [Part of Part 2 of Eng Plan](https://docs.google.com/document/d/1V61xONU0-mleMEEdHWNxhvZtYIPRCB31mT_hbUXusCQ/edit#)
- [Product Spec](https://docs.google.com/document/d/1qZpc90daxQiiqpcQUiUiGV2tQoaYEQUzOA72UZzBlVE/edit#)
- [Jira](https://codedotorg.atlassian.net/browse/PLAT-1342)

## Testing story

- Ran the script locally

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
the code looks good! my understanding is that, because we did not update the old script seed path, these changes will not stick on unmigrated scripts. If there is no time pressure, I would suggest waiting to merge this until plc courses are migrated. 

there is a problem right now which I am working on today preventing plc courses (those with professional_learning_course) from being migrated safely. I should have plc courses safe to migrate by the end of this week. let's talk during standup about how much bashing we feel needs to be done before migrating this list of scripts.

**Comment by dmcavoy** [comment]
I'm planning to merge this and wait to run it. I will run it once migrating scripts is complete. Tracked here: https://codedotorg.atlassian.net/browse/PLAT-1405

**Comment by dmcavoy** [comment]
Also to answer your question @davidsbailey about bashing. Setting these fields right now will not impact anything because its not being used yet. As we start to use it we plan to bug bash along the way

**Comment by davidsbailey** [comment]
sorry, I was unclear. I meant bashing the plc scripts to make sure it is safe to migrate them, not to set these fields.

**Pull request merged**
