### PR TITLE
adding alt text to the images on the Unit Overview page

### PR DESCRIPTION
**Pull request by hannahbergam**
I've spoken with Tess and Molly about grabbing new icons for this (or moving to text labeled buttons instead?) in the future. Because we are going to rework this page entirely in the next 6ish months, I elected to just add the alt text for now, and rethink the icons later.

The buttons are used to toggle between a summary and detail view of the unit lesson information.
The images aren't currently labeled for screen readers, so this pr adds alt text to both images.

Because these images are buttons, it's especially painful to not have any alt text here.

Screen Shot 2022-10-17 at 4 30 36 PM

## Links

- spec: []()
- jira ticket: https://codedotorg.atlassian.net/browse/LP-3054

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by epeach** [comment]
Can you add screenshots of the images you are adding alt-text for? I think that will help document context here.

**Comment by hannahbergam** [comment]
> Can you add screenshots of the images you are adding alt-text for? I think that will help document context here.

Hi sorry- yes! I forgot that I created the pr before writing a new title and description.

**Review by fisher-alice — APPROVED** [review]
LGTM - Thanks for doing this!

**Review by mgc1194 — APPROVED** [review]

**Review by epeach — APPROVED** [review]
Woot woot!

**Comment by megcrenshaw** [comment]
Party time! Thanks for getting us started on this 🥳

**Pull request merged**
