### PR TITLE
Disable autofocus on new account page

### PR DESCRIPTION
**Pull request by ewjordan**
At least via the Chrome simulator, works fine on mobile:

screen shot 2017-10-20 at 4 54 11 pm

### CODE REVIEW

**Comment by breville** [comment]
It would be good to see this on a real iOS device before committing, because they pop a custom selector down the bottom of the screen, and I don't recall ever seeing a page pop that by default.  So.. am just curious what the UX is like in that case.

Also on desktop browsers, does the dropdown expand when it has default focus?  I wonder if this feels a bit broken if it doesn't.

**Comment by ewjordan** [comment]
No, the dropdown doesn't expand by default, it's just highlighted:

screen shot 2017-10-20 at 5 16 32 pm

We could also just not auto-focus anything, which might make more sense if this doesn't help very much.

**Comment by breville** [comment]
An alternative would be to set initial focus to Email field, with assumption that only a small number of visitors will want to switch their account type.  @tanyaparker would have opinions here too.

**Comment by tanyaparker** [comment]
I definitely don't want to switch focus to email. Since account type doesn't default to anything, they should pick that first. If we autofocus to account type and we automatically open the dropdown, I think that's broken/annoying. It should only highlight but not open. My preference:

1. No autofocus at all
2. Autofocus account type and don't open dropdown automatically
3. Autofocus account type and open dropdown automatically

**Comment by ewjordan** [comment]
I guess for now I'll switch to no autofocus at all, unless there are any objections? Always easy to change later if we feel like we need to.

**Comment by tanyaparker** [comment]
SGTM

**Pull request merged**
