### PR TITLE
Reporting changes due to renaming of CSP and CSD

### PR DESCRIPTION
**Pull request by bencodeorg**
The versions of CSP and CSD taught in 2017-18 were renamed `csp-2017` and `csd-2017`, and new versions of the courses for next year were created as `csp-2018` and `csd-2018`. This PR:

1. Creates a redshift-specific table called `course_names` that rolls up the two versions of the course into one.
2. Fixes issues introduced by this change by using `course_names` to apply a meta naming of courses across their various versions.

### CODE REVIEW

**Comment by bencodeorg** [comment]
@davidsbailey just FYI, should be good to go on course renaming/reporting.

**Comment by davidsbailey** [comment]
These changes look good! I'm not sure how important these are to fix, but here a few other places I am still seeing `'csp'` in redshift code:
https://github.com/code-dot-org/code-dot-org/blob/038bc63c22e6250741a5d32cfc97d45779952f48/aws/redshift/views/csp_csd_completed_teachers.sql#L26
https://github.com/code-dot-org/code-dot-org/blob/8edd88950a1b773287c3e939f97ba8eaf83bd757/aws/redshift/views/csp_assessments.sql#L58
https://github.com/code-dot-org/code-dot-org/blob/36013c8e5476456cda27c087b02497ac23dcde53/aws/redshift/tables/regional_partner_stats.sql#L7

**Comment by bencodeorg** [comment]
Thanks for looking Dave -- those are all references to the `'csp'` in the `course_name_short` column of the new `analysis.course_names` table instead of the name in `courses` that have the year suffixes on them, so I think we're good to go.

**Comment by bencodeorg** [comment]
I wouldn't be shocked if I missed something though so thanks for keeping an eye out!

**Pull request merged**
