### PR TITLE
Standards instrumentation Take 2

### PR DESCRIPTION
**Pull request by dmcavoy**
Re-implements #33124 

@epeach said that the original PR had issues with "after each" hook for "renders a detail progress cell for each stage for each student" (https://codedotorg.slack.com/archives/C0T0PNTM3/p1584558080376200). I ran that locally and it had no issue. So I'm going to wait for drone to run on this again and then maybe we try merging again ?

### CODE REVIEW

**Comment by davidsbailey** [comment]
@dmcavoy I took a look at the test failure and saw `addCommonValues` which is in firehose. it looks like the following code depends on pageConstants, which is usually only available in script level pages:
```
  addCommonValues(data, includeUserId, useProgressScriptId) {
      ...
      if (includeUserId) {
        const constants = state.pageConstants;
        ...
```
if you must include user id, one way to make it work would be to make that method check a number of redux locations, including pageConstants as well as a different location you provide when not on script level pages. before picking a location, it would be good to check if user id is already provided on other LP-related pages and then reuse that location. another option would be to pass in the user id explicitly when you make the putRecord call.

**Comment by dmcavoy** [comment]
@davidsbailey thanks for the pointer. I noticed that it gets the value in the console when I test out firehose locally so I wonder if its just that the tests need that redux store. Going to try that now.

**Comment by davidsbailey** [comment]
oh, hah, it already does the thing I was talking about if I read a few lines further:
```
      if (includeUserId) {
        const constants = state.pageConstants;
        const currentUserId = state.currentUser.userId;
        if (constants) {
          data['user_id'] = constants.userId;
        } else if (currentUserId) {
          data['user_id'] = currentUserId;
```
if you haven't already added pageConstants, it would be better if you provided currentUser rather than pageConstants, since that's what'll get provided on non-script-level pages. otherwise, ok to leave for next time.

**Review by davidsbailey — APPROVED** [review]
Updates look good!

**Pull request merged**
