### PR TITLE
Add lessons standards to replication task

### PR DESCRIPTION
**Pull request by Sam-Hutchins**
This PR adds the suite of lesson standard tables to the replication task so the RED team can use the standards to perform analysis on curriculum features.

## Links

[RED Team Doc:](https://docs.google.com/document/d/14_YoXVtKue0usJyzy-c9zH8dxOXbUPLkSbu-S0mhwFQ/edit#)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
looks like the right set of tables to me!

**Review by bakerfranke — APPROVED** [review]

**Comment by sureshc** [comment]
@bakerfranke Drop a note in #infrastructure to coordinate when we run the manual commands to actually deploy this change (merging this Pull Request does not automatically deploy this new functionality).

**Comment by cat5inthecradle** [comment]
This change looks valid.

```
> bundle exec rake stack:data:validate RAILS_ENV=production
...
...
Modify DMSCron [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TableMappings)
```

Let us know when you're ready for this to go live. There is a CLI command that we need to run **after** you've merged this PR.

**Review by cat5inthecradle — APPROVED** [review]

**Comment by cat5inthecradle** [comment]
Successfully deployed.

```
> bundle exec rake stack:data:start RAILS_ENV=production

...
...
 Stack update requested, waiting for provisioning to complete...
..2022-03-16 21:54:26 UTC- DMSCronPii [UPDATE_IN_PROGRESS]
.2022-03-16 21:54:27 UTC- DMSCron [UPDATE_IN_PROGRESS]
.......2022-03-16 21:55:13 UTC- DMSCron [UPDATE_COMPLETE]
2022-03-16 21:55:17 UTC- DMSCronPii [UPDATE_COMPLETE]
.2022-03-16 21:55:20 UTC- DATA-production [UPDATE_COMPLETE_CLEANUP_IN_PROGRESS]

Stack update complete.
Outputs:
```

**Pull request merged**
