### PR TITLE
Lab2: some renaming

### PR DESCRIPTION
**Pull request by breville**
Some renaming from `labs` to `lab2`, and associated adjustments.

### CODE REVIEW

**Review by molly-moen — APPROVED** [review]
🎉

**Comment by molly-moen** [comment]
I couldn't put a comment on the file because it was just a rename, but can we make `lab2Registry` -> `Lab2Registry`?

**Comment by breville** [comment]
> I couldn't put a comment on the file because it was just a rename, but can we make `lab2Registry` -> `Lab2Registry`?

Oh, I gave the filename a lowercase `lab` to be consistent with the naming of `lab2Redux.ts` in the same directory.  

It seems that we start `.jsx/.tsx` files with uppercase letters, but we start `.js/.ts` with lowercase letters, which is what I made a bit more consistent here, though not whether that's the right solution overall.

**Comment by molly-moen** [comment]
> It seems that we start `.jsx/.tsx` files with uppercase letters, but we start `.js/.ts` with lowercase letters, which is what I made a bit more consistent here, though not whether that's the right solution overall.

I think since `Lab2Registry` is a class (vs `lab2Redux` is not) we should keep it uppercase. We also probably want to rename the class as well.

**Comment by breville** [comment]
> > It seems that we start `.jsx/.tsx` files with uppercase letters, but we start `.js/.ts` with lowercase letters, which is what I made a bit more consistent here, though not whether that's the right solution overall.
> 
> I think since `Lab2Registry` is a class (vs `lab2Redux` is not) we should keep it uppercase. We also probably want to rename the class as well.

I see.  I'll rename the file as well as the class.

**Review by molly-moen — APPROVED** [review]

**Review by sanchitmalhotra126 — APPROVED** [review]

**Comment by pablo-code-org** [comment]
I am always scared of this "renaming" PRs, always something goes wrong when I do them :p But it looks good to me!

**Pull request merged**
