### PR TITLE
Update privacy policy

### PR DESCRIPTION
**Pull request by poorvasingal**
Add the necessary language related to longitudinal study.

The pegasus version is updated in #14681.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Don't we also need to update pegasus/sites.v3/code.org/public/privacy.md?

**Comment by tanyaparker** [comment]
She has it in a separate PR because she edits it through github UI.

**Comment by ashercodeorg** [comment]
Ah, awesome. Any chance the related PRs can be cross-linked in the PR summary?

**Comment by tanyaparker** [comment]
Good call. I'll let Poorva know for next time.

**Pull request merged**
