### PR TITLE
[Student Learingn] [SL-587, A11Y-121] Update Button.jsx, Get rid of __useDeprecatedTag in DropdownButton.jsx

### PR DESCRIPTION
**Pull request by levadadenys**
### [Student Learingn] [SL-587, A11Y-121] Update Button.jsx, Get rid of __useDeprecatedTag in DropdownButton.jsx
* Button.jsx improvements (style updates, minor refactor, prop for defaultLineHeight)
* remove __useDeprecatedTag from DropdownButton.js
* DropdownButton.js is now a button, not a clickable div

We need to carefully merge this PR and check if nothing is broken. If all is ok - we have a quick way to get rid of clickable divs.

`useDefaultLineHeight` prop is needed to set line height from initial button module styles. In this particular case - we need that prop because parent element of `DropdonButton.jsx` is `display: inline-block;` and previous lineHeight is not working properly for that case.

Before:
Знімок екрана 2023-04-05 о 15 10 12

After:
Знімок екрана 2023-04-05 о 16 01 09
## Links

- jira ticket: [A11Y-121](https://codedotorg.atlassian.net/browse/A11Y-121?atlOrigin=eyJpIjoiN2RlNjliMTI2Y2U3NGJkZGJjOTVkODc5ZTA2OTM2M2QiLCJwIjoiaiJ9), part of [SL-587](https://codedotorg.atlassian.net/browse/SL-587?atlOrigin=eyJpIjoiODVkYTQyMDViOTRiNDAzOGE0N2Q0YWE2YmQxNzIwNGEiLCJwIjoiaiJ9)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by rshipp** [comment]
Looks like this causes some vertical shifting for the inline `small` dropdown buttons we use for resources in `ResourceList`:

image
image


Compare with the old version:

image
image


Ideally the buttons would be vertically centered with the text, but I think I did some manual pixel offsets here because I was having trouble getting that to work.

**Comment by levadadenys** [comment]
> Looks like this causes some vertical shifting for the inline `small` dropdown buttons we use for resources in `ResourceList`:
> 
> image image
> 
> Compare with the old version:
> 
> image image
> 
> Ideally the buttons would be vertically centered with the text, but I think I did some manual pixel offsets here because I was having trouble getting that to work.

Nice catch, thank you!
Fixed, here's the screenshot of updated styling: 
Знімок екрана 2023-04-07 о 16 16 39

**Review by rshipp — APPROVED** [review]
🎉

**Review by bencodeorg — APPROVED** [review]

**Review by bethanyaconnor — APPROVED** [review]

**Comment by bethanyaconnor** [comment]
Merging for Denys

**Pull request merged**
