### PR TITLE
Add extra links to curriculum builder show pages

### PR DESCRIPTION
**Pull request by megcrenshaw**
This adds the extra links gray box for levelbuilders for both reference guides and data docs. We can add this to the index page for data docs as well, once the edit_all page is complete @TurnerRiley .

I tested this manually by clicking around, but we can add this to our UI test for data docs once the edit feature is merged in as well.

Screen Shot 2022-10-04 at 10 35 27 AM
Screen Shot 2022-10-04 at 10 15 35 AM

The links to view the page in levelbuilder:
image
image

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
one initial comment:

> For data docs, I made myself an admin locally and turned off levelbuilder mode:

for other levelbuilder features, we use the levelbuilder permission in production in order to decide whether to show the "view on levelbuilder" link

**Comment by megcrenshaw** [comment]
> one initial comment:
> 
> > For data docs, I made myself an admin locally and turned off levelbuilder mode:
> 
> for other levelbuilder features, we use the levelbuilder permission in production in order to decide whether to show the "view on levelbuilder" link

Ah, I was following the pattern I saw in `programming_expressions`, `programming_environments`, and `lessons` (e.g. https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/views/lessons/show.html.haml#L13)

But it looks like this pattern would be better? https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/views/courses/show.html.haml#L23

**Comment by davidsbailey** [comment]
> > one initial comment:
> > > For data docs, I made myself an admin locally and turned off levelbuilder mode:
> > 
> > 
> > for other levelbuilder features, we use the levelbuilder permission in production in order to decide whether to show the "view on levelbuilder" link
> 
> Ah, I was following the pattern I saw in `programming_expressions`, `programming_environments`, and `lessons` (e.g. https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/views/lessons/show.html.haml#L13)
> 
> But it looks like this pattern would be better? https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/views/courses/show.html.haml#L23

hmm, I hadn't looked at the implementation yet, so my comment in itself was just about the end behavior. 

Taking a peek at the code, I would say the the way it works for lessons (via `can? :edit`) is great, but in that case you need to 
1. make it not work for admins, like here: https://github.com/code-dot-org/code-dot-org/blob/d3fa4ff2a9356cf236998303a5ca34375a5f0c47/dashboard/app/models/ability.rb#L470, and
2. make it work for levelbuilders, like here: https://github.com/code-dot-org/code-dot-org/blob/d3fa4ff2a9356cf236998303a5ca34375a5f0c47/dashboard/app/models/ability.rb#L392

note that ReferenceGuide is the best example to follow for permissions because they are not part of a script, unlike the other examples you listed.

**Comment by davidsbailey** [comment]
hmm, actually my suggestion won't quite work because when you use that approach for determining who can edit, then it is only allowed in the levelbuilder environment, which means it won't work for deciding whether to show the gray box on prod.

in theory you could add a new cancan permission for viewing the gray boxes, but I'm not sure that's worth the investment so I think the courses/show.html.haml example is fine to follow and will get you the behavior you want.

**Comment by megcrenshaw** [comment]
Ah, I was allowing admins to see data docs. We don't want that? What's the reasoning there?

To make sure I understand ...
1) Admins should *not* be able to see data docs, and therefore should not be able to see the extra links box on prod
2) Folks with levelbuilder permissions who are not admins should be able to see and edit data box, and should get the extra links box on prod (to view on levelbuilder) and on levelbuilder (to edit)

**Comment by davidsbailey** [comment]
> Ah, I was allowing admins to see data docs. We don't want that? What's the reasoning there?

I will start by saying that i don't particularly agree with the reasoning here :-) but the reasoning for locking down what admins can do is that
1. we should only have people logged into admin accounts a minimum amount of the time, and blocking them from certain non-admin pages helps with that
2. we want to prevent admins from viewing curriculum pages to eliminate a category of security risks that could allow someone to take over an admin's account.

This came about when an engineer figured out how to write an applab app that would take over your code studio account when you viewed it.

that said, given that most of our curriculum stuff is not visible or editable by admins, I think it is slightly easier for curriculum writers to navigate if we keep saying "curriculum can't be accessed by admins". 

this isn't great but seems better than starting to be inconsistent, and we have never put up a big enough stink about UN restricting everything except the actual dangerous pages (levels). I would welcome a specific proposal on what exactly we thought admins should and shouldn't be able to do here, keeping in mind that we generally expect people to use admin accounts sparingly.

@sureshc has spent a lot of time thinking about admin account security and may have something to add.

> To make sure I understand ...
> 
> 1. Admins should _not_ be able to see data docs, and therefore should not be able to see the extra links box on prod

yes, except once the `cannot :manage` these pages, my understanding is they won't be able to view data docs pages either.  but really we are going for consistency.

> 2. Folks with levelbuilder permissions who are not admins should be able to see and edit data box, and should get the extra links box on prod (to view on levelbuilder) and on levelbuilder (to edit)

correct!

**Comment by megcrenshaw** [comment]
That's very helpful, thanks, Dave! I pushed some new stuff to (a) ensure admins can't see (view) data docs, and (b) check for levelbuilder permissions, not edit ability, before showing the box.

**Review by davidsbailey — APPROVED** [review]
Looks great, thank you! The admin situation is def not great and a proposal there really would be welcome if you feel so inclined :-)

**Pull request merged**
