### PR TITLE
Gamelab debugger: Initial connection

### PR DESCRIPTION
**Pull request by islemaster**
Adds the debugger UI to gamelab.  This gets the UI in place, but it's not especially usable yet because you can't set breakpoints in the editor, and while you can use "pause" to stop interpreter execution, right now p5play continues running at full speed while you're broken.  We'll tackle those issues next.

### CODE REVIEW

**Comment by islemaster** [comment]
FYI @cpirich 

There are some outstanding issues here, but this seemed like a good place to merge back in.  Things I want to fix pretty quick:
1. Hide the speed slider (until we decide to enable it)
2. ~~Allow placing breakpoints in the editor~~
3. Figure out how to pause p5play when broken

**Comment by davidsbailey** [comment]
looking...

**Comment by davidsbailey** [comment]
@islemaster any chance you can add a screenshot or two?

**Comment by davidsbailey** [comment]
LGTM

**Comment by islemaster** [comment]
Here's the debugger in Gamelab while editing code:
screenshot from 2016-02-05 15-43-49

And here it is on a breakpoint:
screenshot from 2016-02-05 15-44-14

Not much else to see right now, honestly.  The REPL works when broken (just like applab) and all the buttons work as expected, though as I mentioned breaking in the draw loop is weird because the game engine continues to do some stuff behind the scenes.

**Comment by davidsbailey** [comment]
Thanks for the screenshot. I think I was confused about where it would appear, because it was being provided as `extraControlRows`, but I see now that's how it's done in applab too.

**Pull request merged**
