### PR TITLE
set progression on script level when activity section name is present

### PR DESCRIPTION
**Pull request by davidsbailey**
Finishes [PLAT-462].

## Testing story

Added unit test showing that progression set based on activity section name. Also verified the following scenarios manually:

| lesson edit | lesson overview | script overview |
|---|---|---|
| Screen Shot 2020-10-28 at 1 00 28 PM | Screen Shot 2020-10-28 at 1 00 58 PM  | Screen Shot 2020-10-28 at 1 01 27 PM  |
| Screen Shot 2020-10-28 at 1 23 05 PM | Screen Shot 2020-10-28 at 1 25 10 PM | Screen Shot 2020-10-28 at 1 25 23 PM |

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

[PLAT-462]: https://codedotorg.atlassian.net/browse/PLAT-462

### CODE REVIEW

**Comment by dmcavoy** [comment]
@davidsbailey do you think this is the way we want to do this in the long run or is this something to make it work for now? I feel like the goal is to get rid of the progression setting on script level as we move to Activity Sections. I get that the old courses use it and therefore this is the easy way to get this to display the way we want it to but I think we will want to instead move toward using activity sections to set up the display of the new courses on the script overview page. This sets us up in the long run to be able to show other information about activitys and activity sections.

**Comment by davidsbailey** [comment]
Good questions Dani. Let me try to think through it in writing.


In the future we will have to support only these configurations:

| model | view |
|---|---|
| new data model | new script overview page |
| new data model | lesson overview page |

In this world, we will definitely want to format the script overview page using activity section instead of progression.

Right now, we have a situation where we have to support the following configurations:

| model | view |
|---|---|
| old data model | old script overview page |
| new data model | old script overview page |
| new data model | lesson overview page |

For now, I think it makes sense to put a minimum amount of work in to get the new data model to work with the old script overview page.

So, to answer your question, I think this not something we want in the long run, but is something we may want to keep more or less like this until we get all scripts onto the new system.

**Comment by dmcavoy** [comment]
@davidsbailey Alright I'm on board with that. I would love to see a task to follow up on this and I think that we probably need a follow up conversation on this with PMs because if we end up wanting to show Activities on the Script Overview page we won't be able to use this work around.

**Review by dmcavoy — APPROVED** [review]

**Comment by davidsbailey** [comment]
Good point Dani, starting to show activity sections without levels could be a reason to start dealing with activity sections on the script overview page. I am happy to move in the direction as the need arises.

**Pull request merged**
