### PR TITLE
Stop recreating dsl i18n on every seed

### PR DESCRIPTION
**Pull request by Hamms**
In https://github.com/code-dot-org/code-dot-org/pull/24183, I added some logic to only sync CSF dsls i18n strings on level save. Unfortunately, I didn't realize that we also do a full dsls sync on every seed, which is both entirely unnecessary and is a method of syncing that makes it super difficult to determine whether or not the level in question is CSF.

So, I'm just going to disable that sync, and also revert `dsls.en.yml` back to what we expect it to be.

### CODE REVIEW

**Review by balderdash — APPROVED** [review]

**Comment by Hamms** [comment]
[Figure out how to only sync a subset of dsls.en.yml with crowdin](https://trello.com/c/UJOoFJuG/283-figure-out-how-to-only-sync-a-subset-of-dslsenyml-with-crowdin)

**Comment by Hamms** [comment]
Turns out this legit breaks things (details in the trello card)

**Comment by joshlory** [comment]
@Hamms can you pull the details out here as well? Is the issue from https://github.com/code-dot-org/code-dot-org/pull/24183#discussion_r215080498 ?

**Comment by Hamms** [comment]
Yep! My "entirely unnecessary" comment in the PR description here turns out to be entirely untrue; it's _absolutely_ necessary to recreate the dsl i18n on every seed because we rely on the dsl i18n not just for rendering translations, but also for rendering the English version. (My comment about this method of syncing making things harder than they need to be remains valid).

I address this is https://github.com/code-dot-org/code-dot-org/pull/27881 by making rendering the English version work fine regardless of the state of the dsl i18n.

**Comment by joshlory** [comment]
Got it, thx for clarifying!

**Pull request closed without merging**
