### PR TITLE
Fix Violations of and Reenable `Style/TrailingUnderscoreVariable`

### PR DESCRIPTION
**Pull request by Hamms**
This is an odd one; this rule "[Checks for extra underscores in variable assignment.](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/TrailingUnderscoreVariable)"

Specifically, when you're assigning the results of a call that returns an iterable to multiple variables and want to ignore some variables later in the iterable, this rule discourages you from using plain underscores as placeholder variable names, and prefers that you instead simply omit the variables.

Repeating the examples from the documentation linked above:

```
# bad
a, b, _ = foo()
a, b, _, = foo()
a, _, _ = foo()
a, _, _, = foo()

# good
a, b, = foo()
a, = foo()
*a, b, _ = foo()
# => We need to know to not include 2 variables in a
a, *b, _ = foo()
# => The correction `a, *b, = foo()` is a syntax error
```

The `a, b, _` pattern is definitely a bit gross, but is certainly familiar. The recommended `a, b,` pattern is certainly odd, but it has the benefit of not actually resulting in an unwanted variable assignment. I'm open to feedback about whether we'd prefer to have this rule enabled or disabled.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by pablo-code-org — APPROVED** [review]

**Comment by bencodeorg** [comment]
Not blocking, but count me a vote to keep this disabled. Keeping underscores is more readable to me, which I think is more valuable than skipping an unnecessary variable assignment.

**Review by bethanyaconnor — APPROVED** [review]
I feel more mixed about this one (trailing commas are not my favorite) but in general, I'd rather us lean towards the general ruby style guide so I'm okay with it.

**Comment by bethanyaconnor** [comment]
FYI, the link in your description is broken for me

**Comment by Hamms** [comment]
I feel more conflicted about this one the more I think about it. After some consideration and discussion with the infrastructure team, I think what I'd most prefer here is that we encourage developers to use actual named variables in this scenario, just prefixed with an underscore to make it clear they're unused:

```
# good
a, b, _something = foo()
```

**Comment by Hamms** [comment]
Bethany, I've found that `rubydoc.info` links are a bit unreliable, and sometimes just spontaneously fail to load. Can you check the link again? It's working for me currently

**Comment by bethanyaconnor** [comment]
It works now thanks! 

I like the idea of naming all of the variables and prefixing an underscore to the ones that aren't used.

**Pull request closed without merging**
