### PR TITLE
Add key to programming_expression

### PR DESCRIPTION
**Pull request by dmcavoy**
Add key to programming_expression. Key is also the slug used for the block in the url. I think having both name and key will be necessary. We will want name for searching for blocks and key for urls.

### CODE REVIEW

**Review by bethanyaconnor — APPROVED** [review]
There aren't any ProgrammingExpressions in any environment yet right? If not, this seems good to me!

**Review by Hamms — COMMENTED** [review]
Could we also add a unique index?

**Comment by dmcavoy** [comment]
I added a validation for uniqueness `validates_uniqueness_of :key, scope: :programming_environment_id` in https://github.com/code-dot-org/code-dot-org/pull/39274/files. I can add the index if we think we also need that

**Comment by Hamms** [comment]
We probably do want an index; if we're ever going to be trying to find a programming expression by key alone, we will want an index that lets us do that

**Pull request merged**
