### PR TITLE
Preserve hint prompt threshold

### PR DESCRIPTION
**Pull request by joshlory**
Fix for https://github.com/code-dot-org/code-dot-org/pull/22048#pullrequestreview-115646926.

> Note that we'll also need to do something to get this data into the level files themselves so it doesn't get lost again

### CODE REVIEW

**Comment by joshlory** [comment]
Yes sorry — I wanted to see how gross it would be to keep the data on `ScriptLevel`.  What do you think about this as a temporary fix?  It would fix the immediate bug but not change where the data is stored.

**Comment by joshlory** [comment]
[Re-calculate hint prompt data to enable them on Course A-F levels](https://trello.com/c/PCu4Khtm/64-re-calculate-hint-prompt-data-to-enable-them-on-course-a-f-levels)

**Comment by joshlory** [comment]
Ping @Hamms

**Comment by Hamms** [comment]
It's a little gross, but this seems fine for a temporary fix. I would like to see some TODO comments at the very least, though. When are we planning to apply the actual fix?

**Comment by joshlory** [comment]
You're right, moving to the `Level` model is way cleaner!  Sorry 😛.  Abandoning this change in favor of PR https://github.com/code-dot-org/code-dot-org/pull/22241.

**Pull request closed without merging**
