### PR TITLE
Upgraded karma-chrome-launcher to v2 to enable ChromeHeadless for unit tests

### PR DESCRIPTION
**Pull request by jmkulwik**

### CODE REVIEW

**Comment by islemaster** [comment]
PR description please!  When you say "enable ChromeHeadless" do you mean for unit tests, or UI tests?

**Review by islemaster — APPROVED** [review]

**Review by Hamms — COMMENTED** [review]
How do we use this package? Are there any breaking changes between v1 and v2 we need to be concerned of?

**Comment by jmkulwik** [comment]
Responding to Elijah's question: We use this package to debug our js unit tests with the chrome debugger. 
Their release notes don't show any breaking changes. I think they did a major version increment because it was a larger set of changes. I've tested our "normal" use case, and everything worked as expected.

**Review by Hamms — APPROVED** [review]
Great! LGTM

**Pull request merged**
