### PR TITLE
Update Teacher Apps Accepted Email

### PR DESCRIPTION
**Pull request by TurnerRiley**
Desired outcome from [the jira task](https://codedotorg.atlassian.net/browse/ACQ-222?atlOrigin=eyJpIjoiODY3NjJkMTllN2YyNDljZjhjMzQ4MjYzMmU1MjdjOTQiLCJwIjoiaiJ9):
1. We went from 3 accepted states down to 1 this year. We should make sure that the new accepted email fires at the right time. An accepted email should send to a teacher who is moved into the “Accepted” status and the regional partners has auto emails turned on.
2. We also send a registration reminder email. That should be updated to send after 7 days instead of 14.

For outcome 1, in looking through `teacher_application.rb`, I believe no changes are necessary. First off, on line 65, "accepted" is a status that automatically triggers the queueing of its respective email. Then, on line 377, a status email (such as "accepted") is only sent if the regional partner has auto emails turned on.

For outcome 2, the changes in this PR cover the shift from waiting 2 weeks to 1 week to send a registration reminder email for teachers that have been accepted but have yet to register for any workshop.

## Links
Jira task: [here](https://codedotorg.atlassian.net/browse/ACQ-222?atlOrigin=eyJpIjoiODY3NjJkMTllN2YyNDljZjhjMzQ4MjYzMmU1MjdjOTQiLCJwIjoiaiJ9)

## Testing story
Drone tests passing.

## PR Checklist:
- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by megcrenshaw — CHANGES_REQUESTED** [review]
Thanks for laying out where this logic lives! It looks like https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/pd/application/teacher_application.rb#L377 will run `queue_email(accepted)` but there is no `email_type` of name `accepted`.

Could you update the `accepted_no_cost_registration` to be just `accepted`? Are there any text changes that need to be made to this email, and if so, will you do that in this PR or a separate one?

**Review by megcrenshaw — COMMENTED** [review]
Yikes I didn't mean to review that with the scary red icon 😨

**Comment by TurnerRiley** [comment]
> Thanks for laying out where this logic lives! It looks like https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/pd/application/teacher_application.rb#L377 will run `queue_email(accepted)` but there is no `email_type` of name `accepted`.
> 
> Could you update the `accepted_no_cost_registration` to be just `accepted`? Are there any text changes that need to be made to this email, and if so, will you do that in this PR or a separate one?

Yes just did in the PR for updating the emails (along with some of their names): https://github.com/code-dot-org/code-dot-org/pull/48918. Thank you for pointing this out, I got mixed up with some of the different status vs. email names.

**Comment by TurnerRiley** [comment]
> Yikes I didn't mean to review that with the scary red icon 😨

:O

**Review by megcrenshaw — APPROVED** [review]

**Comment by megcrenshaw** [comment]
Looks great! Cross-checked with https://github.com/code-dot-org/code-dot-org/pull/48918/files –– thanks for the link!

**Pull request merged**
