### PR TITLE
skip yourschool test

### PR DESCRIPTION
**Pull request by clareconstantine**
This test is failing, but the user experience is fine. PLC will own re-enabling these ASAP.

### CODE REVIEW

**Review by islemaster — APPROVED** [review]
:+1: Follow-up tracked as [PLC-454](https://codedotorg.atlassian.net/browse/PLC-454)

**Review by nkiruka — APPROVED** [review]

**Comment by joshlory** [comment]
I thought we were only skipping on mobile?

**Comment by joshlory** [comment]
Should we abandon this now that the root cause seems to be the React 15.6 upgrade?

**Comment by clareconstantine** [comment]
> Should we abandon this now that the root cause seems to be the React 15.6 upgrade?

Yep, I'll close this out. Thanks!

**Pull request closed without merging**
