### PR TITLE
Disable editing vocabulary word

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Follow up to [this Slack discussion](https://codedotorg.slack.com/archives/CNZP84FJ5/p1612312060123600). We currently set the key of vocab equal to the word to 1. prevent duplicate definitions (for now) and 2. to make the vocab markdown syntax intuitive. This means that if a vocab word is edited, its key will be out of sync with these objectives. 

The biggest downside to this solution is that if there's a typo in the word, it will be difficult to edit without creating a new object. I added a warning to that effect (open to suggestion on wording!) but this approach might need to be revisited if we hear feedback about this.

Updated add vocab dialog:
Screen Shot 2021-02-04 at 4 01 38 PM

Updated edit dialog:
Screen Shot 2021-02-04 at 3 56 09 PM

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bethanyaconnor** [comment]
Also tagging @tess323 mostly for fyi but in case she has any objections!

**Comment by tess323** [comment]
Thanks for the heads up! Only feedback would be to make that alert red if its a low lift

**Review by davidsbailey — APPROVED** [review]
Looks great!

**Comment by dmcavoy** [comment]
@bethanyaconnor Does having word match the key prevent CSF from having two of the same words with different definitions for the common sense media lessons?

**Comment by bethanyaconnor** [comment]
Currently yes. I thought we were going to address that after April launch but I might've misunderstood something. Ideally I'd like a way to generate a key that makes sense for those vocabulary, i.e. `debugging_cse` or something.

FWIW I don't think it will be much work to implement this now if it's needed now.

**Comment by davidsbailey** [comment]
> FWIW I don't think it will be much work to implement this now if it's needed now.

I'm open to this. What would this look like exactly in terms of changes that need to be made?

**Comment by bethanyaconnor** [comment]
Kind of depends how we want the UI to look. I've been envisioning a checkbox or something to mark a vocabulary as common sense media. Then modifying [this function](https://github.com/code-dot-org/code-dot-org/blob/96c49a1718158d5a52c245ce7d495fc08ab88cfd/dashboard/app/models/vocabulary.rb#L60) to take that into account. Then maybe disallowing editing for common sense media vocabulary (as that seems to be the requirement).

I didn't add `properties` to the vocabulary model because it wasn't needed originally but that would be an easy migration. But even with that, I think this would be less than a day of work.

**Comment by davidsbailey** [comment]
It could be worth considering if it helps us in the short term -- otherwise, if we're not quite sure how we want it to look yet, I would probably lean toward deferring it.

**Comment by bethanyaconnor** [comment]
I created a [ticket](https://codedotorg.atlassian.net/browse/PLAT-746) in our backlog for that work so we can talk about it at planning. It isn't directly related to this PR though so I'm going to go ahead and merge this.

**Pull request merged**
