### PR TITLE
Added Fixed Positioning of filters on curriculum catalog

### PR DESCRIPTION
**Pull request by juanmanzojr**
Filters will stay at the top of the page when scrolling through the curriculum catalog. Language filter will also stick if shown.

### Regular Filters
https://github.com/code-dot-org/code-dot-org/assets/137838584/424b4c0f-9df1-46b7-a62e-eeeb9aa6ba4b

### Regular and Language Filters
https://github.com/code-dot-org/code-dot-org/assets/137838584/f0c82fc4-ca73-484a-a0fb-d85f67912a63

## Links

- jira ticket: [here](https://codedotorg.atlassian.net/jira/software/c/projects/ACQ/boards/64?modal=detail&selectedIssue=ACQ-717)

## Testing story

Local testing

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by TurnerRiley — COMMENTED** [review]
This looks great! One thing is it looks like there's more space now below the filters and above the catalog cards, could you please remove that so the spacing is as it was before and is consistent whether the language filter is present or not please?

This is the studio.code.org/catalog view:
Studio

Here's what it looks like now with this PR:
localhost

**Comment by juanmanzojr** [comment]
### Updated Padding to match studio.code.org/catalog view
This PR:
Screenshot 2023-07-19 at 12 14 02 PM
studio.code.org/catalog view:
Screenshot 2023-07-19 at 12 14 12 PM

https://github.com/code-dot-org/code-dot-org/assets/137838584/d7648152-764f-4a64-9a69-08e93fd62813
### English:
Screenshot 2023-07-19 at 12 18 46 PM

**Review by TurnerRiley — APPROVED** [review]
Thank you! This looks amazing!

**Comment by megcrenshaw** [comment]
Thanks for doing this, Juan! Would you feel comfortable, once this is merged in, following up in this thread https://codedotorg.slack.com/archives/C04540KNGDQ/p1689380051796549? Brendan might like an update on it since he offered it!

**Comment by juanmanzojr** [comment]
Thank you! Ill make sure to follow up with Brendan in that thread.

**Pull request merged**
