### PR TITLE
Clicking assign button without sections prompts section setup

### PR DESCRIPTION
**Pull request by megcrenshaw**
This PR addresses what happens when a teacher clicks the "Assign Button" when they don't have sections. The spec'd implementation is for the "Add Sections" dialog to appear on top of the first dialog, so first you see this dialog:

image

and clicking on "Create section" would make this dialog appear:

image

I tried to implement that functionality, but was running into problems with the "Cancel" button (see commits aec597247cd7e9a1de0eb3afa7d103715cb73b9b and 72cc3dfd78ffd14cd1ce76f36d9d3bd3939e6f24 that were reverted). Rather than continuing down this path (and risking not implementing this functionality before I head OOO), I instead chose to re-direct to the home page with params that force the correct dialog to be shown. Demo (my computer is very slow):

https://github.com/code-dot-org/code-dot-org/assets/9142121/f2b918bf-b0ec-4b4b-91ed-d3bf9f58f8e2

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by megcrenshaw** [comment]
@dmcavoy Heads up this is different from what was spec'd. I think if we really want to try getting this functionality as spec'd, getting someone to start on it from https://github.com/code-dot-org/code-dot-org/commit/aec597247cd7e9a1de0eb3afa7d103715cb73b9b might make sense

**Comment by dmcavoy** [comment]
This seems like a great solution for now @megcrenshaw. Thanks for being so thoughtful!

**Comment by dmcavoy** [comment]
@TurnerRiley @davidsbailey can we get review of this PR asap this week and once its approved merge it for Meg so that we can start testing it.

**Review by TurnerRiley — APPROVED** [review]
Love this clever solution!

**Pull request merged**
