### PR TITLE
I18n sync In & Up 06/20

### PR DESCRIPTION
**Pull request by deploy-code-org**

### CODE REVIEW

**Comment by bethanyaconnor** [comment]
This is my bad but I forgot to merge https://github.com/code-dot-org/code-dot-org/pull/29031 so the course_content changes need to be added manually. Assuming the changes are there, `git add i18n/locales/source/course_content` should be all that's needed to add those files. Sorry :/

**Comment by bethanyaconnor** [comment]
I think the large diff in blocks.yml is due to https://github.com/code-dot-org/code-dot-org/pull/28985 and is expected.

**Review by Hamms — COMMENTED** [review]
Looks good, pending addition of the `course_content` changes

**Comment by nkiruka** [comment]
course_content changes have been added!

**Review by bethanyaconnor — APPROVED** [review]

**Review by Hamms — APPROVED** [review]

**Pull request merged**
