### PR TITLE
remove extra line

### PR DESCRIPTION
**Pull request by tanyaparker**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
LGTM.

**Comment by ashercodeorg** [comment]
CC @aoby

**Comment by aoby** [comment]
Thanks @tanyaparker! 

Any idea why that style error didn't show up when I checked in the file, in hound, or in the circleCI test associated with https://github.com/code-dot-org/code-dot-org/pull/9264?

**Comment by ashercodeorg** [comment]
That rubocop check was de-blacklisted earlier in the day. Your pull off
staging wasn't updated to include it, so the check wasn't done in your
branch.

**Pull request merged**
