### PR TITLE
Revert "refactor clientApi to make it easier to extend"

### PR DESCRIPTION
**Pull request by islemaster**
Reverts code-dot-org/code-dot-org#9090

Introduced a regression on IE9, IE10, IE11 and Safari < 9, because babel-polyfill is not available to embedded blocks right now (specifically `Symbol`)

### CODE REVIEW

**Comment by pcardune** [comment]
😢 😢 😢

**Comment by pcardune** [comment]
LGTM I guess...

**Comment by islemaster** [comment]
UI Tests FTW

**Comment by pcardune** [comment]
This sums up how I feel after getting to 98% code coverage on what you just reverted
image
😢 😢 😢

**Comment by islemaster** [comment]
Closing as unnecessary because the fix is ready!

**Pull request closed without merging**
