### PR TITLE
Fix Minecraft share dialog line breaking in IE RTL

### PR DESCRIPTION
**Pull request by bcjordan**
### IE11 RTL

image
### Chrome RTL

image
### Chrome RTL

image
### IE11 RTL Tall

image
### IE11 RTL Short

image

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Was this a regression from recent changes, or something that's been broken all along? Have we looked to see how much RTL traffic we're getting on MC? (I suspect a decent amount given MC's popularity)

**Comment by Bjvanminnen** [comment]
Is this just IE RTL, or all browsers?

**Comment by bcjordan** [comment]
@Bjvanminnen updated screenshots, all browsers, RTL only. Has been broken all along, https://github.com/code-dot-org/code-dot-org/pull/5972 hasn't been merged in yet.

**Comment by Bjvanminnen** [comment]
Change seems fine to me. Very limited in scope (should be only mc and only rtl).

**Pull request closed without merging**
