### PR TITLE
attempt to install python3.8 in chef-managed environments

### PR DESCRIPTION
**Pull request by davidsbailey**
## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by sureshc** [comment]
Do we only need these versions of python installed on `daemon` servers? If so, we can put some Chef logic in this recipe to narrow the types of servers where we install these packages. We have some examples of how to do this. Look for `['daemon']` in our `/cookbooks`.

**Comment by davidsbailey** [comment]
Yes, I think we could get away without installing these on production frontends for now, since we plan to only call pycall from within Active Job to start, which in production will have its workers running on production-daemon. We would need pycall on the test machine as well as adhocs, which should be ok since AFAIK these are daemons also. 

It seems likely that we'll eventually want to use pycall from our production frontends too, but I'm fine with waiting until a specific need arises to install python 3.8 there.

**Comment by davidsbailey** [comment]
one caveat -- the Active Job adapter that we are initially configuring does run directly on the web frontends, so if we do not install python3.8 on production frontends then we won't be able to test out python-related features on production at all until we set up a different adapter such as resque or delayed_job.

**Comment by davidsbailey** [comment]
per discussion with @cat5inthecradle today, infra team is going to take over getting python3.8 installed via chef. also we are in agreement that for now this can be installed only on daemon machines (therefore not installed on prod web servers).

**Comment by davidsbailey** [comment]
Hi @cat5inthecradle @sureshc @pablo-code-org (cc @wilkie), I have two mild concerns with the idea of installing python3.8 only on production-daemon which I'd like to share, but feel free to make your own decision:

1. pycall will still be invoked on production frontends using an older, unsupported version of python, which seems not to break anything but is nonetheless a bit concerning:
a. in order to get `pycall` onto production daemon, we'll put it in the Gemfile
b. when the rails application loads, it requires everything in the Gemfile: https://github.com/code-dot-org/code-dot-org/blob/ddb7bb5746a4d7a85bb8afad6c62c507e3b528fd/dashboard/config/application.rb#L19-L21
c. when `pycall` is required, it will invoke python
d. in the absence of python 3.8, it will invoke version 3.6.9, which is not supported by pycall

I've tried this on an adhoc without python3.8 installed and there is no error, but still makes me a little nervous that we're invoking pycall with a version of python which it does not support, and (for example) upgrading pycall could theoretically cause production frontends to break.

2. if we were to extend our python functionality, it could break production frontends without breaking anything else (development, drone, test, production-daemon):
  a. [some python functionality](https://github.com/mrkn/pycall.rb#special-notes-for-specific-libraries) requires additional pycall gems, such as `numpy`
  b. adding `numpy` to the Gemfile without python3.8 installed causes rails application to fail to load, since it invokes pycall which invokes python in a way that does fail if python 3.8 is not available

We're happy to agree not to adopt this particular gem until after the ubuntu 20 upgrade, but it does highlight how the absence of python3.8 on production frontends makes us more vulnerable to failures very late in the deploy pipeline.

**Pull request closed without merging**
