### PR TITLE
Peer Review status should show up in puzzle dots

### PR DESCRIPTION
**Pull request by mehalshah**

### CODE REVIEW

**Comment by joshlory** [comment]
LGTM.  Thank you for fixing!

Worth adding UI test coverage?

**Comment by mehalshah** [comment]
Late this week, I'm planning on doing fake peer reviews in UI tests. Now that we have the All The PLC Things, this is easier to do and verify

**Comment by joshlory** [comment]
Sounds good!  Is this work tracked somewhere?

**Comment by mehalshah** [comment]
In the sprint plan

**Pull request merged**
