### PR TITLE
Update flush_cache

### PR DESCRIPTION
**Pull request by wjordan**
fix error message
[ci skip]

### CODE REVIEW

**Comment by wjordan** [comment]
[`CDO.daemon`](https://github.com/code-dot-org/code-dot-org/blob/staging/deployment.rb#L144) is true on one instance per environment. An instance counts as daemon unless it's a frontend (in which case, another instance in the environment counts as the daemon).

**Comment by wjordan** [comment]
`adhoc` is a bit of a special-case since each 'adhoc' instance is effectively its own (self-contained, standalone) environment. Until recently, all adhoc instances had `CDO.daemon = false`; since #15386 every adhoc instance now has `CDO.daemon = true`.

**Comment by ewjordan** [comment]
If we're running this script on, for instance, test or an adhoc, do we actually want it to be flushing the (production) Cloudfront cache as well as varnish?

**Comment by wjordan** [comment]
@ewjordan currently, the script should flush the local varnish cache, flush any varnish caches on all frontends in the environment (which in most environments other than production, is an empty-set), and invalidate the cloudfront caches in its environment, [which it derives from](https://github.com/code-dot-org/code-dot-org/blob/staging/lib/cdo/aws/cloudfront.rb#L89-L90) the (environment-specific) `CDO.pegasus_hostname` / `CDO.dashboard_hostname` config methods.

adhoc-instances currently lack the needed permissions to perform this AWS-API operation themselves, but this should be working correctly in all other environments.

**Pull request merged**
