### PR TITLE
Don't overwrite level_source_id with nil.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This prevents us from overwriting a previous `level_source_id` with `nil`.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
joshlory: Is it clear this is the behavior we want to adopt? Though I assume so, I'm not completely certain. The impetus is that I'm seeing a lot of instances of this when backfilling the column.

**Comment by ashercodeorg** [comment]
CC @Hamms

**Comment by joshlory** [comment]
Can we add unit test coverage?  Otherwise LGTM!

**Comment by ashercodeorg** [comment]
Added unit test. Thanks for the prompt to do so!

**Pull request merged**
