### PR TITLE
Replace dangeroulsySetInnerHtml in Abuse error with UnsafeRenderedMarkdown

### PR DESCRIPTION
**Pull request by nkiruka**
Abuse error message is shown when users attempt to open a project that is marked as abusive.

### Before 
Screen Shot 2019-04-04 at 9 31 31 PM

### After
Screen Shot 2019-04-05 at 3 20 19 PM

### CODE REVIEW

**Review by Hamms — COMMENTED** [review]
Looks like the `textStyle` style is no longer working with this change. Can that be fixed?

**Comment by nkiruka** [comment]
@Hamms Yes, that's right.  Will adding a style prop to the UnsafeRenderedMarkdown component so styles can be passed into the component be an option?

**Comment by Hamms** [comment]
Unfortunately, no; the paragraph elements these styles would be applied to are generated from the markdown rather than being developer-added React components to which we could apply the properties.

**Review by islemaster — APPROVED** [review]
In this case I think that's fine - we use this component in very particular circumstances and it looks okay.

**Comment by Hamms** [comment]
In that case, I'd recommend removing the property entirely so as not to be misleading

**Pull request merged**
