### PR TITLE
Updates more controller tests to use keyword arguments.

### PR DESCRIPTION
**Pull request by ashercodeorg**
All of ConfirmationsControllerTest, FeatureModeControllerTest, GalleryActivitiesControllerTest, and HintViewRequestsControllerTest.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Why didn't CircleCI run?

**Comment by davidsbailey** [comment]
CircleCI is running now

**Comment by ashercodeorg** [comment]
Thanks, @davidsbailey. Did you do something to kick it off?

**Comment by davidsbailey** [comment]
nope, it had just started running a few minutes ago when I looked.

**Pull request merged**
