### PR TITLE
[Bad Guys] Support for sharing and publishing

### PR DESCRIPTION
**Pull request by mikeharv**
Builds on the work started in:
- https://github.com/code-dot-org/code-dot-org/pull/45449
Alternative to:
- https://github.com/code-dot-org/code-dot-org/pull/45468

At a high level, this PR adds support for the Bad Guys project type. Users will be able to create new projects which can be shared, remixed, published and viewed. The Bad Guys projects are in fact Sprite Lab projects (using a separate level), and are categorized as such in the gallery.

### Engineering Work
* Designate that `New The Bad Guys.level` is a project level.
* Create a project type for The Bad Guys
* Categorize `'spritelab'` and `'thebadguys'` projects both as "Sprite Lab"
* Add translation strings and thumbnail.
* Ensure the project shows in the Create dropdown correctly (it will not be a default there, but will show when working on a Bad Guys project)

*Public gallery showing a variety of projects. The Bad Guys projects are categorized as Sprite Lab:*
image

*Viewing all Sprite Lab projects...*
image

*Bad Guys option showing in the create menu when on a Bad Guy project:*
image

*Bad Guys option NOT showing in the create menu when on a different project:*
image

## Links
Jira Issue:
- [STAR-2164: [Bad Guys] Create New Level Type for Bad Guys](https://codedotorg.atlassian.net/browse/STAR-2164)

## Follow-up Work
* [STAR-2188: [Bad Guys] Final polish on freeplay level ](https://codedotorg.atlassian.net/browse/STAR-2188)
Mike will be making any final adjustments to the level, including any additional assets or changes to blocks and instructions.
* [STAR-2192: [Bad Guys] Enable The Bad Guys Project in /Projects](https://codedotorg.atlassian.net/browse/STAR-2192)
Assigned to Mike. After this PR merges, this should be a single-line code change that can be merged just ahead of the campaign launch. ([`StartNewProject.jsx`](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/templates/projects/StartNewProject.jsx))
* [STAR-2190: [Bad Guys] Enable marketing changes](https://codedotorg.atlassian.net/browse/STAR-2190)
Kelby will be working to update the homepage, create a landing page, and update the Projects page - Brendan will be assisting and helping ramp up Kelby
* [STAR-2187: [Bad Guys] DCDO flip live 4/11](https://codedotorg.atlassian.net/browse/STAR-2187)
Brendan will coordinate timing with Marketing.

## Local Testing Instructions
* Create and publish a The Bad Guy project at http://localhost-studio.code.org:3000/projects/thebadguys
* Confirm that The Bad Guys button shows up correctly under the Create menu, but only from within that project.
* Look for the new project in the Sprite Lab public gallery at http://localhost-studio.code.org:3000/projects/

### CODE REVIEW

**Review by breville — APPROVED** [review]
Great write-up and scenario coverage!

**Comment by breville** [comment]
> * Ensure the project shows in the Create dropdown correctly (it will not be a default there, but will show when working on a Bad Guys project)

Out of curiosity, where is the logic for this conditional behaviour?

**Comment by mikeharv** [comment]
> > * Ensure the project shows in the Create dropdown correctly (it will not be a default there, but will show when working on a Bad Guys project)
> 
> Out of curiosity, where is the logic for this conditional behaviour?

@breville It looks like it is controlled here: https://github.com/code-dot-org/code-dot-org/blob/8e91b4fa9c46e5d1900bdde1f52109f71f9580da/lib/cdo/create_header.rb#L49-L65

**Review by KylieModen — APPROVED** [review]
LGTM, we also confirmed with Min that published projects combined with Sprite Lab works for this campaign

**Pull request merged**
