### PR TITLE
ignore links that aren't broken

### PR DESCRIPTION
**Pull request by tanyaparker**

### CODE REVIEW

**Comment by tanyaparker** [comment]
Oops I did not mean to include that .jpg link -- removing.

That's weird! I'm able to see their profiles fine in incognito. But it looks like they redirect. Can you test if these links instead work for you?

https://www.linkedin.com/in/howard-ding-00703832/
https://www.linkedin.com/in/ander-rivas-695766a8

**Comment by Erin007** [comment]
The LinkedIn links work for me if I am NOT logged in to LinkedIn.  If I am, I end up at the Profile Not Found page. Must have to do with their public/privacy settings for who can 'friend' them.

**Comment by tanyaparker** [comment]
Oh. :/ Well... since the link technically works in some cases and these links have small visibility (not a lot of people will be clicking on these) I feel like it's safe to ignore. What do you think?

**Comment by Erin007** [comment]
I think it's fine to leave them in. It's low visibility and low likelihood someone will run in to the exact same conditions.

**Pull request merged**
