### PR TITLE
Applab export build fix

### PR DESCRIPTION
**Pull request by pcardune**
In order to fix this, I switched to using the prebuilt version of jszip which comes with the jszip npm package. This is a workaround and not the ideal fix. I'm not sure what the ideal fix is though. It seems like many of our js dependencies (including jszip) depend on the `isarray` package and for some reason browserify doesn't include the right `isarray` package in the resulting bundle (or at least it doesn't include it at the right path) so you get an error when the page loads. By using the prebuilt version of jszip, we get around this problem.

My suspicion is the webpack might not have this problem, so perhaps if and when we switch to webpack we can get rid of this hack.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Note: branch has merge conflicts

**Comment by Bjvanminnen** [comment]
Why do you suspect `isarray` to be the cause? afaict we don't actually include it anywhere. I also don't see it as a dependency of jszip (though I suppose one of jszip's dependencies might have a dependency on it). Would listing isarray as a dependency of our own solve this problem too?

**Comment by pcardune** [comment]
I suspect `isarray` because that's the last thing in the error stack trace when you try to load applab. it's a dependency of `readable-stream`, which is dependency of `jszip`. A lot of packages depend on `readable-stream` too, but for whatever reason, the error is with `isarray` and not `readable-stream`. I tried listing `isarray` as a dependency of our own, but that didn't work either.

The following is the path that shows up in the error stack trace:
`/Users/pcardune/programming/code-dot-org/apps/node_modules/jszip/node_modules/isarray/index.js`

Browserify seems to build a map from file paths to functions that load the associated module at that file path.  While the file mentioned above exists in my file system, it isn't in the map. _however_, `isarray/index.js` does show up in the map but under a different directory hierarchy. It either showed up in  `/Users/pcardune/programming/code-dot-org/apps/node_modules/jszip/node_modules/readable-stream/node_modules/isarray/index.js` or `/Users/pcardune/programming/code-dot-org/apps/node_modules/isarray/index.js`.

So it seems like when browserify replaces the `require()` statements, it uses one path, and when it build the map that actually resolves the file paths, it uses a different path, causing this issue.  It might be a problem with factor-bundle too. I haven't tried debugging that part yet.

**Comment by pcardune** [comment]
By the way, I just confirmed that this works in the adhoc environment.

**Comment by Bjvanminnen** [comment]
Change seems ok to me if it works. Might be worth adding a comment above the require explaining why we're requiring this version.

**Pull request merged**
