### PR TITLE
[Finishes #118859591] move delete/duplicate to upper right

### PR DESCRIPTION
**Pull request by Bjvanminnen**
movebuttons

Move the buttons to the upper right so we dont have to worry about having to scroll to see them. Also did some cleanup of styles so that they more closely follow our style guidelines (which have been changing over time).

### CODE REVIEW

**Comment by davidsbailey** [comment]
this degrades somewhat poorly when you shrink the window: 
screen shot 2016-05-09 at 2 58 20 pm

**Comment by Bjvanminnen** [comment]
Yeah, but you have to go < 1024x768 so I think we're okay with that?

**Comment by davidsbailey** [comment]
LGTM

Not sure how recently we started using Radium, but it looks like we could move things like `hover-pointer`into Radium/React now, and that there are workarounds to move pseudoelement-like behavior inside react as well: https://github.com/FormidableLabs/radium/issues/3

**Comment by davidsbailey** [comment]
I'm not sure to what extent we try to support smaller resolutions. I would say "not totally broken" is the min bar, and this PR definitely clears that bar since you can still see and click the buttons. 👍

**Pull request merged**
