### PR TITLE
Use custom error page when web servers are experiencing issues

### PR DESCRIPTION
**Pull request by sureshc**
Configure CloudFront to return a static webpage that is served from the `cdo-dist` S3 bucket when the Ruby web application servers (pegasus and dashboard) are returning HTTP 5XX errors.

### CODE REVIEW

**Comment by sureshc** [comment]
Currently the static html pages must be manually deployed to environment specific directories (`adhoc`, `test`, `production`, etc.) in the `cdo-dist` S3 bucket.  Can we deploy this content automatically from our source code repository to S3 via our asset pipeline?

**Comment by uponthesun** [comment]
Just want to check - have you confirmed the error code we get when dashboard/pegasus are stopped? Is it 503?

**Comment by sureshc** [comment]
image

**Comment by sureshc** [comment]
@uponthesun Currently `dashboard` is stopped and `pegasus` is running on the adhoc.

Pegasus (works) - https://adhoc-configure-cloudfront-error-pages.cdn-code.org/about
Pegasus (custom 404 from app server) - https://adhoc-configure-cloudfront-error-pages.cdn-code.org/does_not_exist
Dashboard - https://adhoc-configure-cloudfront-error-pages-studio.cdn-code.org/courses

**Review by uponthesun — APPROVED** [review]

**Pull request merged**
