### PR TITLE
Fix violations of rubocop Style/MutableConstant.

### PR DESCRIPTION
**Pull request by asherkach**
A followup to #19545, fixing further violations. There are more to be fixed, left for future PRs. But the needle is moving in the right direction.

### CODE REVIEW

**Comment by asherkach** [comment]
CC @breville as DOTD for review.

**Comment by asherkach** [comment]
Ping.

**Comment by asherkach** [comment]
Rebased to `staging`, please kick off a CircleCI run. Thanks!

**Comment by breville** [comment]
Started https://circleci.com/gh/code-dot-org/code-dot-org/58995

**Comment by asherkach** [comment]
And rebased to `staging` again, try again... Why is `circle.yml` changing so much these days?

**Comment by asherkach** [comment]
Ping @breville for CircleCI run.

**Comment by breville** [comment]
@ashercodeorg Looks like just a lot of tweaking: https://github.com/code-dot-org/code-dot-org/commits/staging/.circleci/config.yml

**Comment by breville** [comment]
Success in https://circleci.com/gh/code-dot-org/code-dot-org/59802.  Merging.

**Pull request merged**
