### PR TITLE
[WIP] Redux teacher homepage

### PR DESCRIPTION
**Pull request by Erin007**
- Establishes connection between `TeacherHomepage` and isRtlRedux 
- Connects all components used on the TeacherHomepage to redux store 
- Wraps parent components in Providers for Storybook as needed
- Removes `isRtl` as a passed prop, as components will now pull that data from the store 
- Establishes connection between other uses of `ContentContainer` and isRtlRedux

This is the starting point that will allow us to move other information into the TeacherHomepage Redux store.

### CODE REVIEW

**Comment by Erin007** [comment]
@davidsbailey @breville This isn't ready for review yet, but I looped you in if you want to peak at the progress since it touches so many files. 

cc: @tanyaparker

**Comment by davidsbailey** [comment]
Looks like a great start Erin! I know you're having to touch quite a large number of files to do this, but part of the benefit will be that you won't have to touch very many files at all to add more props to the child components later. Let me know when you're ready for a closer look or if you have any questions.

**Comment by Erin007** [comment]
There's more to cleanup I'm sure, but I think this beast is in need of some more 👀 before it becomes even more unwieldy than it already is.

**Comment by Erin007** [comment]
Oooh.  All good points, @islemaster. This came about mostly because I needed a way to learn Redux, it seemed like Redux shines most when you need to pass the same info to a bunch of components, and we thought it might be a good initial step to get the Redux store hooked up to the homepages. That being said, if it doesn't really make sense to do it this way, I could easily be convinced to close this PR, count it as practice, and implement a cleaner, global solution. 

I don't expect upcoming features to change RTL on the fly. The only way to change it now is to change the language.

**Comment by islemaster** [comment]
:sweat_smile: Sorry!  Redux really shines when you need to pass the same info to a bunch of components, _and_ you expect that info to change and want all the components to update in response to that change.  Constants in Redux might be an anitpattern - although we use it liberally in [places like `pageConstants`](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/redux/pageConstants.js) and it's definitely better than manually passing those props through a deep tree of React components!

That's what I would do anyway.  @davidsbailey, thoughts?

**Comment by islemaster** [comment]
BTW, I'm not saying you haven't done a very nice job in this PR :+1: I just think there may be a fundamentally different approach that's better.

**Comment by davidsbailey** [comment]
Hi Brad,

Good point, it does seem like isRtl should just be a global constant.

In addition to learning redux, the other goal of this PR was to get the teacher homepage onto redux so that new data could be stored there rather than piped up and down via props and callbacks. I'd be sad to revert this PR, because I think it does a good thing by setting up teacher homepage with redux. I also don't love the idea of removing isRtl and keeping all the redux plumbing without it actually doing anything.

Perhaps an ideal compromise would be to find some other parts of teacher homepage that would more appropriately belong in redux, so that most of the redux goodness in this PR can be preserved?

**Comment by islemaster** [comment]
That sounds good to me.  Any thoughts on what else we could move into redux that `TeacherHomepage` needs?  It's actually a fairly simple component in concept and may not need to be connected - it's just adding other (probably themselves connected) components to the page in a particular order.  The other props `TeacherHomepage` takes are fairly static too - courses, announcements.

It might be nice to pull announcements out into a redux module.  Are announcements dismissable right now?  That would be a state change we could handle in redux.  I could also see us supporting more complex behavior with announcements down the road - async-loading them, live-updating, or otherwise making them updatable without a DTP.  Maybe persisting dismissed announcements in local storage so it stays dismissed across page loads.

That's all speculation though, not sure if it's particularly useful.

**Comment by davidsbailey** [comment]
Brad, good point that Redux shines when it manages state that (1) changes and (2) is shared by many components. As a starting point, I searched for `getInitialState` within `apps/src/templates/studioHomepages`, to see which react components are storing state. However the state appears to be well-contained in each case. So based on that, I don't see any great candidates for redux.

Erin, can you tell us a bit more about any upcoming changes planned for the teacher homepage (or any other react components you plan to work on really), and we can assess whether they are good candidates for redux? As Brad mentioned, it sounds like announcements might be a good candidate, but only if there are certain types of future work planned there.

Thanks Brad for enlightening us on when to use or not use redux, and apologies Erin for sending you down the wrong rabbit hole! :-/

**Comment by Erin007** [comment]
It's okay - I still learned things in this rabbit hole.

I don't know of any upcoming changes to the homepages ( @tanyaparker ? ).

Announcements are a special kind of `Notification`. `Notifications` are dismissible, but that is just a straightforward open/closed state. The only possible change to Announcements that there was rumble of when the page was first designed was to have a way to cycle through multiple. There are (currently un-used) separate `Announcement` and `AnnouncementsCarousel` components that handle showing multiple announcements. I think that idea has been abandoned and might not warrant Redux anyway...

It also doesn't look like I'm slated to do much with React this sprint.  😞

**Comment by tanyaparker** [comment]
We'll want to add a table of sections that a teacher has joined to the teacher's homepage. Otherwise no other planned updates to homepage.

**Comment by davidsbailey** [comment]
That sounds like something that wouldn't update except on a hard refresh of the page. @Erin007 Based on this discussion, I'd say the way forward is to close this PR 😢 . Moving isRtl to a global constant could be a future work item, but since the impetus for this PR was to learn about redux, let's say mission accomplished for now and don't feel obligated to do the work for turning isRtl into a global.

I learned things in this rabbit hole too! We'll be more careful about picking any other work items which are not required for delivering features.

**Pull request closed without merging**
