### PR TITLE
Fix violations of and reenable rubocop Style/OrAssignment.

### PR DESCRIPTION
**Pull request by asherkach**
Fixes auto-generated via `bundle exec rubocop --only Style/OrAssignment --auto-correct`.

### CODE REVIEW

**Comment by asherkach** [comment]
CC @jeremydstone for review.

**Comment by asherkach** [comment]
CircleCI run? Merge? Thanks!

**Comment by asherkach** [comment]
Ping @jeremydstone.

**Comment by jeremydstone** [comment]
Running Circle now

**Comment by jeremydstone** [comment]
@asherkach circle.yml has changed, could you please merge latest staging and ping me to rerun Circle.
```bin/circle/merge-base:32:in `<main>': .circleci/config.yml has changed. Please merge the origin/staging branch into your branch and try again. (RuntimeError)```

**Comment by asherkach** [comment]
@jeremydstone rebased with latest staging.

**Comment by jeremydstone** [comment]
Passed on Circle. Sorry for the delay on the Circle run, @asherkach

**Pull request merged**
