### PR TITLE
App Lab: add api.sportsdata.io

### PR DESCRIPTION
**Pull request by breville**
Add support for `api.sportsdata.io` to be accessed using `startWebRequest`.

**Tip:** Use `bundle exec rake seed:code_docs` in `dashboard/` to see the updated documentation locally at `docs/ide/applab/expressions/startWebRequest`.

### CODE REVIEW

**Comment by bencodeorg** [comment]
Were you able to test this? It looks paid (or at least requires an API key)?

**Comment by bencodeorg** [comment]
TIL re: `seed:code_docs`!

**Comment by breville** [comment]
> Were you able to test this? It looks paid (or at least requires an API key)?

I did not test the service.

**Review by bencodeorg — APPROVED** [review]
Presumably this will unblock some student who wrote in who wants to use it? Seems like we allow other APIs that require keys (eg, https://coinlayer.com/documentation), so that's not anything new here.

**Comment by breville** [comment]
> Presumably this will unblock some student who wrote in who wants to use it? Seems like we allow other APIs that require keys (eg, https://coinlayer.com/documentation), so that's not anything new here.

Yes, this came from a user request.  And we do permit APIs so long as the key can be passed by query parameter, which is possible here.

**Pull request merged**
