### PR TITLE
Update congrats page constants for 2020

### PR DESCRIPTION
**Pull request by uponthesun**
Same changes as https://github.com/code-dot-org/code-dot-org/pull/28779/files for 2020  (except `CATEGORIES` had already been updated.)

I've added names for course A-F, express, and pre-reader express 2020 to the i18n gsheet: https://docs.google.com/spreadsheets/d/1Tq7VqZALgRA0wYk0HDfEOTyRI0TM2Dir2rloXIPGCgU/edit#gid=0 (search for `coursea-2020_name`)

## Links

- [jira](https://codedotorg.atlassian.net/browse/LP-1324)

## Testing story

`congrats/coursea-2020` page works locally after changes (except for missing translations, but those should get scooped soon.)

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by Erin007 — APPROVED** [review]
LGTM! Do we have time this year to future proof this as follow up?

**Comment by uponthesun** [comment]
We could, but it's competing with CB/LB consolidation work, and I'd rather make progress on that right now I think? I'd love to come back to automating shipping curriculum before next year, though.

**Comment by Erin007** [comment]
> We could, but it's competing with CB/LB consolidation work, and I'd rather make progress on that right now I think? I'd love to come back to automating shipping curriculum before next year, though.

That makes sense.  I just wanted to know if/how automating shipping curriculum stacked up to other priorities. Agreed - these little one-offs can be tedious but are ultimately known, tracked, and mostly quick to implement; let's leverage our time for bigger impact PLAT work for now. Thanks!

**Review by davidsbailey — APPROVED** [review]
thank you for the research you put into this. LGTM!

**Pull request merged**
