### PR TITLE
copy changes + combine 'see privacy policy' into one string

### PR DESCRIPTION
**Pull request by tanyaparker**

### CODE REVIEW

**Comment by tanyaparker** [comment]
I'm pretty sure we can sub the url in dashboard and pegasus. I don't think we can in apps, so made the entire string the link. Is it ok if these are treated differently? If not, then we can make the entire string a link in dashboard and pegasus too.

**Comment by tanyaparker** [comment]
To be merged after https://github.com/code-dot-org/code-dot-org/pull/22540 (depending on what changes Erin makes for apps). I haven't tested this yet. Will test with Erin's guidance on Monday.

**Comment by Erin007** [comment]
I'm only using the strings in `apps/i18n/common/en_us.json`.  The React GDPR dialog replaces the haml partial. We can leave this PR as is, but one of the last clean up items on my lists is to remove `shared/haml/gdpr_eu_dialog.haml` and the related strings in `pegasus/sites.v3/hourofcode.com/i18n/en.yml` and `dashboard/config/locales/en.yml`.

**Comment by tanyaparker** [comment]
Fixed with https://github.com/code-dot-org/code-dot-org/pull/22574

**Pull request closed without merging**
