### PR TITLE
Export new_feature_feedbacks MySQL Table to Redshift

### PR DESCRIPTION
**Pull request by jordan-springer**
```
schema:
user_id (int),
form_key (int),
satisfied (bool),
created_at (datetime (6),
updated_at (datetime (6)
```

See slack thread
_Issue created in Slack from a_ [_message_|https://codedotorg.slack.com/archives/C071T8M847J/p1716379204881919?thread_ts=1716379204.881919&cid=C071T8M847J\_._|https://codedotorg.slack.com/archives/C071T8M847J/p1716379204881919?thread_ts=1716379204.881919&amp;cid=C071T8M847J].]

## Testing story

```
code-dot-org $ export AWS_PROFILE=codeorg-admin
code-dot-org $ bin/aws_access
AWS access: GoogleSignInAdmin/suresh@code.org
code-dot-org $ bundle exec rake stack:data:validate RAILS_ENV=production ADMIN=true

Pending update for stack `DATA-production`:
Modify DMSCron [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TableMappings)
Finished stack:data:validate (less than a minute)
```

## PR Checklist:

- [ ] Tests provide adequate coverage
- [x] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by cat5inthecradle — APPROVED** [review]

**Comment by cat5inthecradle** [comment]
LGTM, Infra will need to deploy this manually.

**Comment by jordan-springer** [comment]
@cat5inthecradle can you merge this?

**Comment by jordan-springer** [comment]
> LGTM, Infra will need to deploy this manually.

Hey @sureshc can you push this for me (or someone else on Infra)?

**Comment by sureshc** [comment]
Deployed

```
code-dot-org $ export AWS_PROFILE=codeorg-admin
code-dot-org $ bin/aws_access
AWS access: GoogleSignInAdmin/suresh@code.org
code-dot-org $ bundle exec rake stack:data:start RAILS_ENV=production ADMIN=true
Pending update for stack `DATA-production`:
Modify DMSCron [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TableMappings)
Proceed? [y/n]
y
 Stack update requested, waiting for provisioning to complete...
.2024-05-24 17:50:08 UTC- DMSCron [UPDATE_IN_PROGRESS]
......2024-05-24 17:50:55 UTC- DMSCron [UPDATE_COMPLETE]
2024-05-24 17:50:56 UTC- DATA-production [UPDATE_COMPLETE_CLEANUP_IN_PROGRESS]

Stack update complete.
Outputs:
Finished stack:data:start (1 minute)
```

**Pull request merged**
