### PR TITLE
Set `EnforcedStyle` to `inline` for `Style/AccessModifierDeclarations`

### PR DESCRIPTION
**Pull request by Hamms**
Alternative to https://github.com/code-dot-org/code-dot-org/pull/50457; rather than defaulting to `group` style, explicitly set `inline` style.

## Links

- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/AccessModifierDeclarations
- https://docs.rubocop.org/rubocop/cops_style.html#styleaccessmodifierdeclarations

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bencodeorg** [comment]
Was this done automated-ly or manually?

**Comment by bencodeorg** [comment]
I [saw this note on autocorrection](https://docs.rubocop.org/rubocop/cops_style.html#safety), so I think manually?

_Autocorrection is not safe, because the visibility of dynamically defined methods can vary depending on the state determined by the group access modifier._

**Comment by Hamms** [comment]
Sort of manual, but I used vim macros to apply the changes so it's definitely possible that we have some weird exceptions somewhere that slipped under the radar.

I'm mostly relying on existing tests to make sure that none of these changes affect any actual functionality

**Review by bencodeorg — APPROVED** [review]
Didn't examine every file in detail (LMK if you think worth doing so), but as a style update I think it looks great!

**Pull request merged**
