### PR TITLE
Add `INFINITE_LOOP_TRAP` back to non-Maze app types

### PR DESCRIPTION
**Pull request by joshlory**
Some interesting history here:

 - `Blockly.JavaScript.INFINITE_LOOP_TRAP` was renamed to `BlocklyApps.INFINITE_LOOP_TRAP` [almost 5 years ago](https://github.com/code-dot-org/apps-archived/commit/d3e3d8e67a1113df490744ce15d4054951bc3090#diff-1d8397621863ecd2087bf85b240afdd7L470), accidentally breaking Blockly's [built-in infinite loop detection](https://github.com/code-dot-org/blockly/blob/04705fd7494610e1f6a2b682b3f33ebbc3fb3161/generators/javascript/loops.js#L35).
- Someone noticed that we didn't seem to have infinite loop detection and [updated the comment](https://github.com/code-dot-org/apps-archived/commit/9d923a549f4e1849490890ea87c2c37244d09500#diff-1d8397621863ecd2087bf85b240afdd7R112).  But that comment [was later removed](https://github.com/code-dot-org/code-dot-org/commit/93fa89637b923e22c0f285b2e501a7fded3f10cb#diff-c247f8ed0f7ba067c7c2f0aa3962e1bdL237) 😂.

I picked half a million steps sort-of-arbitrarily.  It takes about 5 seconds to catch the infinite loop.  I tried to balance user experience (don't freeze the browser too long) against not cutting off programs early that draw complex things.

The thrown exception is caught here: https://github.com/code-dot-org/code-dot-org/blob/ba8124e21f81223e94adb1681a9c40d868d50b6e/apps/src/turtle/artist.js#L693-L696

### CODE REVIEW

**Comment by joshlory** [comment]
Play Lab goes through the `CustomMarshalingInterpreter.evalWithEvents` path.  This should only affect Artist, Craft, Eval & Calc which use `CustomMarshalingInterpreter.evalWith`.

**Comment by Hamms** [comment]
Awesome! Have you verified the timeout against some of the longer artist drawings? And can we also remove the maze special case for this?

**Comment by joshlory** [comment]
It looks like codegen is wrong for [`functional_definition` blocks](https://github.com/code-dot-org/blockly/blob/04705fd7494610e1f6a2b682b3f33ebbc3fb3161/generators/javascript/functional_procedures.js#L46-L49) 🙄 when `INFINITE_LOOP_TRAP` is non-empty:

```js
Globals.f = function(x) {
return   executionInfo.checkTimeout(); if (executionInfo.isTerminated()){return;}
  (  x +   1)
}
; return(  (  2 +   1) ==   Globals.f(  2))
```

**Comment by joshlory** [comment]
@Hamms PTAL!

**Comment by joshlory** [comment]
Hmm — 500,000 steps is a lot.  A program like that would noticeably hang most browsers.  What cutoff do you think is best?

**Comment by Hamms** [comment]
Oh dang, right you are. Even https://studio.code.org/projects/artist/Ut6coOwiXo_fg_B6Eh2CAA/edit only takes ~50k steps.

Worry sated! This LGTM

**Pull request merged**
