### PR TITLE
Deeper Learning: Only destroy unassigned peer reviews on unsubmit

### PR DESCRIPTION
**Pull request by islemaster**
Fixes [PLC-138](https://codedotorg.atlassian.net/browse/PLC-138) - at least part of it!

The :handle_unsubmit method of UserLevel was being called as a before_save hook, with no conditions.  Within that method we were destroying unassigned PeerReview records on any save, not only when an unsubmit had occurred.  I believe this is the root cause of the disappearing peer reviews bug that led us to add the backfill cronjob in the first place!

This could cause us to have only one peer review for a `UserLevel`, which in turn could cause our backfill cronjob to create two new reviews for that UserLevel putting it back in a 'pending' state even when it had already been accepted.

The fix is to make the `before_save` hook properly conditional on an unsubmit actually occurring.

Looks like this problem was originally introduced in https://github.com/code-dot-org/code-dot-org/pull/17660 where we tested the positive case (does unsubmitting destroy peer reviews) but not the negative case (does saving other fields _not_ destroy peer reviews).  I've added a negative-case test here.

## Next steps
After this change ships, let's monitor the cronjob for a week.  If we don't see reviews being backfilled anymore, I believe we can safely disable that cronjob, removing a moving part from this already-complex system.

### CODE REVIEW

**Comment by islemaster** [comment]
Thanks @joshlory for pairing with me on this investigation! I don't think I'd ever have spotted this issue without your help.

**Comment by hacodeorg** [comment]
This is an interesting investigation!

**Review by joshlory — APPROVED** [review]
Awesome! 🎉

**Comment by islemaster** [comment]
I think so but I intend to monitor for a week after this ships before we
disable it. I'd expect backfill to fall to zero.

**Review by clareconstantine — APPROVED** [review]

**Comment by islemaster** [comment]
Hi @mehalshah! @clareconstantine mentioned you'd probably want to hear about this fix. :grinning:

**Pull request merged**
