### PR TITLE
Fix Lesson Names That Changed to Old Names

### PR DESCRIPTION
**Pull request by dmcavoy**
Yesterday a change was included in the deploy to update the process of how we update scripts.en.yml for i18n when we seed/update/edit scripts. PR: https://github.com/code-dot-org/code-dot-org/pull/35946. This change makes it so we will update the the value stored in the scripts.en.yml file with the new value instead of always defaulting to the old value. 

This change caused a problem with some lesson names where we were keeping the old lesson name in the script file but had updated a new display name in the scripts.en.yml file. I believe this was left over from the past when lessons could not be deleted from a script. 

I went through the [changes to scripts.en.yml](https://github.com/code-dot-org/code-dot-org/commit/83579a5807f6c1afadf8803c888dcbdcdfa209b5#diff-4dd86a63364f80108e38bf905790e96cR11698) from yesterdays deploy to see what lesson names changed and updated the script files if that lesson still exists in the script (there are lessons in scripts.en.yml file where that lesson is not actually in the script anymore).  I then ran `bundle exec rake build` to make sure I got all the changes to the scripts.en.yml file that would occur from the seeding process.

### CODE REVIEW

**Comment by dmcavoy** [comment]
I went through all the CSF scripts and matched the lesson names between LB and CB.

**Review by uponthesun — COMMENTED** [review]
What would've been the manual testing we could've done to catch this regression? Would it be doing a full seed locally and inspecting the resulting `script.en.yml` changes?

**Comment by davidsbailey** [comment]
If I understand correctly, this change may break translations in CSF courses until the next i18n sync. @Hamms can you confirm?

**Comment by davidsbailey** [comment]
Until / unless we are sure this approach is safe, I think a better short-term fix would be to revert any changes to scripts.en.yml, and then manually make sure that the same set of wrong changes does not get scooped up from levelbuilder again.

**Pull request closed without merging**
