### PR TITLE
Upgrade Sauce Connect to 4.4.5

### PR DESCRIPTION
**Pull request by joshlory**
No longer need the pre-release build added in https://github.com/code-dot-org/code-dot-org/pull/13109.

This public build includes the fix for the mixed HTTP responses issue (we've had the pre-release fix on CircleCI since early February).

### CODE REVIEW

**Review by islemaster — APPROVED** [review]
:+1:

**Comment by joshlory** [comment]
Bad news, something about the new version is causing many of our UI tests to fail:

https://circleci.com/gh/code-dot-org/code-dot-org/33522
https://circleci.com/gh/code-dot-org/code-dot-org/33549
https://circleci.com/gh/code-dot-org/code-dot-org/33584
https://circleci.com/gh/code-dot-org/code-dot-org/33606

The most common error is:
```
too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 4 requests on 28169980, last used 300.101323835 seconds ago (Net::HTTP::Persistent::Error)
```

**Comment by islemaster** [comment]
Seems like SauceLabs has had some issues today - I saw at least one of these on staging this afternoon, long after their issue this morning was supposedly resolved.  I'd try this again tomorrow.

**Comment by joshlory** [comment]
Rebased this change against latest staging.  Still getting the same UI test timeouts:

https://circleci.com/gh/code-dot-org/code-dot-org/34388
https://circleci.com/gh/code-dot-org/code-dot-org/34405
https://circleci.com/gh/code-dot-org/code-dot-org/34429

**Comment by islemaster** [comment]
It's not on their wiki yet, but the tool itself has started reporting that 4.4.6 is available.  Worth a try?
```
18 Apr 12:56:20 - ***********************************************************
18 Apr 12:56:20 - A newer version of Sauce Connect (build 3525) is available!
18 Apr 12:56:20 - Download it here:
18 Apr 12:56:20 - https://saucelabs.com/downloads/sc-4.4.6-linux.tar.gz
18 Apr 12:56:20 - ***********************************************************
```

**Comment by joshlory** [comment]
Nice find!  I'll update the PR.

**Comment by joshlory** [comment]
Update from Sauce Labs support:
> This is likely to be a Sauce Connect bug. Our engineering team is looking in it and we will let you know as soon as we have any update.

**Comment by islemaster** [comment]
Not sure this will do anything, but it had an effect in my local setup - it's worth a shot. See https://circleci.com/docs/1.0/configuration/#hosts and https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy+FAQS#SauceConnectProxyFAQS-CanIAccessApplicationsonlocalhost?.

**Comment by islemaster** [comment]
Having opened a followup ticket with Sauce Labs about the challenges we've had with this upgrade, I'm verifying that sc 4.4.7 works correctly on my local machine.  I've confirmed that the following tests (referenced as examples in the helpdesk ticket) pass running from my own machine, but failed in the latest Circle build on this branch:

- videoplayer.feature
- studio.feature
- simpledrag.feature

**Pull request closed without merging**
