### PR TITLE
Level: add validation to check for colon(s) in level name

### PR DESCRIPTION
**Pull request by nkiruka**
Currently, content editors can assign a levelbuilder_key a name that includes a colon. This naming prevents show notes from being displayed for a particular video/level.

Validation is added to the Level model to check if the name of a level contains a colon.  I verified that the new validation added did not break previous tests.

### CODE REVIEW

**Comment by joshlory** [comment]
It looks like there are some levels that don't currently pass this validation:

```rb
[21] pry(main)> Level.where("name like '%:%'").count
=> 280
```

I'm looking at the seed failure in the Drone test pass for this PR:

```
+ bundle exec rake circle:seed_ui_test --trace
--
1145 | ** Invoke circle:seed_ui_test (first_time)
1146 | ** Execute circle:seed_ui_test
1147 | RAILS_ENV=test RACK_ENV=test bundle exec rake seed:cached_ui_test
1148 | rake aborted!
1149 | ActiveRecord::RecordInvalid: Validation failed: Name is invalid
```

**Comment by joshlory** [comment]
Ah ok, I think I see what happened! I got confused by PR https://github.com/code-dot-org/code-dot-org/pull/27658 and thought you were asking about the level key. Now I see you were asking about the video key.

I think we should update this PR (or abandon and create a new PR) that enforces snake_case for video keys. It should be the same exact process, just in video.rb instead of level.rb.

https://github.com/code-dot-org/code-dot-org/blob/2e2ad92cb4ead3cb47887056d95669e274a5dd42/dashboard/app/models/video.rb#L26

Sorry again for my confusion!

**Comment by joshlory** [comment]
In order to get that validation to pass Drone, you'll need to update all occurrences of the `Teaching CS Fundamentals: How the Course Works` video key to `teaching_csf_how_it_works`. I get the following 11 matches, although you'll want to verify:

image

You can open a PR with that change separately (atomic PRs!), as long as you merge it before the validation PR.

**Comment by nkiruka** [comment]
A new PR will be generated to add validation for video key.

**Pull request closed without merging**
