### PR TITLE
[App Lab] Add Console.clear()

### PR DESCRIPTION
**Pull request by sanchitmalhotra126**
This adds `console.clear()` to AppLab, GameLab, and WebLab. Note that this does *not* add any documentation for the console.clear() method - it didn't seem like that was a requirement for this task given the description, but I'll mention it in the JIRA as well.

https://user-images.githubusercontent.com/85528507/165839448-c12e8daf-033a-459f-b0bc-cbaf970d48a8.mov

This can be added as a block to the toolbox as well:
Screen Shot 2022-04-28 at 6 10 30 PM
Screen Shot 2022-04-28 at 6 11 17 PM

## Links

JIRA: https://codedotorg.atlassian.net/browse/PP-77

## Testing story

Tested on AppLab, GameLab, and WebLab.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by mikeharv** [comment]
I'm not sure why we'd need to support this command with Web Lab, considering A) there is no student console, and B) Web Lab only supports student HTML and CSS.
Separately, it seems like we'd want to add `console.clear()` to the default palette when creating a level, and allow levelbuilders to add the command to the droplet toolbox. I think a good starting place for doing this is at `lib/cdo/shared_constants.rb`. `console.log()` is usually categorized with "Variables".

**Review by davidsbailey — APPROVED** [review]
looks about right to me, but my knowledge of this code may be super outdated by now. things I would check:
1. do you want this to show up in the toolbox? probably not, since console.log does not, but just checking
2. does it work in /projects/applab, as well as on level pages which have a reduced set of blocks available in the toolbox?

**Comment by davidsbailey** [comment]
e.g. https://studio.code.org/s/applab-intro/lessons/1/levels/2

**Comment by sanchitmalhotra126** [comment]
> I'm not sure why we'd need to support this command with Web Lab, considering A) there is no student console, and B) Web Lab only supports student HTML and CSS. Separately, it seems like we'd want to add `console.clear()` to the default palette when creating a level, and allow levelbuilders to add the command to the droplet toolbox. I think a good starting place for doing this is at `lib/cdo/shared_constants.rb`. `console.log()` is usually categorized with "Variables".

Hmm yeah the reason it's in WebLab is just because I added `console.clear` where `console.log` was being referenced. On localhost I was able to add a `<script>` tag and insert JS that way, but looks like that's disabled on production.

Re: adding to the toolbox - thanks for the heads up! I'll include this wherever `console.log()` is included.

**Comment by davidsbailey** [comment]
apologies, I missed mike's comment and didn't mean to contradict, since mike is of course right -- console.log does appear in the toolbox.

**Comment by sanchitmalhotra126** [comment]
> looks about right to me, but my knowledge of this code may be super outdated by now. things I would check:
> 
> 1. do you want this to show up in the toolbox? probably not, since console.log does not, but just checking
> 2. does it work in /projects/applab, as well as on level pages which have a reduced set of blocks available in the toolbox?

1. Good question - on projects/applab/new I do see `console.log()` show up in the toolbox, so I guess yes? Edit: Just saw your second comment, yep makes sense :)
Screen Shot 2022-04-28 at 5 24 27 PM

2. Hmm good call, this works on standalone applab ~~but doesn't look like it's working on the level with limited blocks that you linked (though it does work in the debugger). I'll take a look~~ Edit: I was looking at production by accident :) on localhost with these changes, it does work on that level

**Comment by davidsbailey** [comment]
> Hmm good call, this works on standalone applab but doesn't look like it's working on the level with limited blocks that you linked (though it does work in the debugger). I'll take a look

ok, now that mike is on the case I'd defer to him on verifying this -- but i think perhaps it is possible that this is not supposed to work if it is not in the toolbox for a particular level.

**Comment by sanchitmalhotra126** [comment]
> > Hmm good call, this works on standalone applab but doesn't look like it's working on the level with limited blocks that you linked (though it does work in the debugger). I'll take a look
> 
> ok, now that mike is on the case I'd defer to him on verifying this -- but i think perhaps it is possible that this is not supposed to work if it is not in the toolbox for a particular level.

Turns out I was just looking at production by accident :) on localhost with these changes, it does indeed work both in the editor and the debugger.

**Comment by KylieModen** [comment]
Curriculum writers/managers can decide where console.clear() should be included in toolboxes. If students/teachers write valid code in levels with limited toolboxes, that is not blocked. So if a student uses console.log or console.clear that will still work even if not included in the toolbox. 

image

**Review by mikeharv — APPROVED** [review]
Pulled and tested again. I confirmed that the new command works as expected. I was also able to add and remove it from a level's toolbox using the levelbuilder level edit interface. LGTM!

**Comment by sanchitmalhotra126** [comment]
Never got around to merging this after the hackathon week (thanks @mikeharv for the reminder!). I just re-merged staging and will go ahead and merge once drone passes.

**Pull request merged**
