### PR TITLE
Fix Infinity tutorial levels 3 & 7.

### PR DESCRIPTION
**Pull request by breville**
These two levels had regressed.  

Both had JavaScript errors which appear to result from more stringent requirements in the JS success criteria function, particularly declaring a var explicitly and referring to window variables explicitly.

Level 3 also no longer turned the other actors around when they were touched.  In lieu of a deeper change, the JS code in the level now sets the "last moved" value with the current studio tick so that the turn plays once, and the level itself sets a much longer time to turn back to facing south; longer than the level timeout, in fact.  The only difference is that the actor now plays a walking animation while they're facing north, but this seems like a small price to pay to keep this change as small as possible with no code changes to studio itself.

### CODE REVIEW

**Comment by breville** [comment]
Code review please, from @cpirich @islemaster or @Bjvanminnen .. whoever can get to it first.

**Comment by Bjvanminnen** [comment]
How did we catch this issue?

Can we have successTime live on Studio instead of window? Makes this a little cleaner. Ideally, we then also initialize successTime to something (probably null?) in Studio.init, so that we have a reference to this in code. Perhaps also worth a short comment next to the init describing where/how it is used.

**Comment by Bjvanminnen** [comment]
If Immediate goal is to get this fixed on prod, I'm okay with taking this change, and then making the cleaner change in a future PR, as long as that future PR happen in the near future :)

**Comment by breville** [comment]
Not sure how it was caught. @ashercodeorg mentioned it in a room last week..

Agreed on successTime change, however that will impact seven Infinity levels instead of just these two.  Also, I think I can remove successTime completely and use a flag I added for hoc2015 instead.  Added to my to-do list.

**Comment by ashercodeorg** [comment]
There was a Zendesk ticket report.

**Pull request merged**
