### PR TITLE
Support Blockly field customizations without direct overrides

### PR DESCRIPTION
**Pull request by bencodeorg**
Allows us to use a completely custom field (FieldButton), an extension of an existing field (FieldImageDropdown), and an override of an existing field (FieldDropdown) without directly overriding a Blockly property, which is not an approach that the Google Blockly team wants us to use any more. Also updates a [previous (already functional) refactor of FieldVariable](https://github.com/code-dot-org/code-dot-org/pull/46726) to use this approach as well, for consistency.

## Links

- https://codedotorg.atlassian.net/browse/SL-154
- https://codedotorg.atlassian.net/browse/SL-157
- https://codedotorg.atlassian.net/browse/SL-156
- [Blockly Custom Fields docs](https://developers.google.com/blockly/guides/create-custom-blocks/fields/customizing-fields/overview). These are pretty comprehensive, but the way they suggest doing custom fields doesn't look a lot like the way we've done it, as far as I can tell.

## Testing story

Scenarios tested (only included screenshots for Google Blockly, others matched / were same as what's seen in production)

- **FieldDropdown, Google Blockly level, custom block:** tested manually that the "???" in the hint that appears after you run your code for the first time here continues to function after this change. It regressed after removing the existing override. This is the main customization that our FieldDropdown supports, per the PR where it was added.
  - /flappy/3
  - https://github.com/code-dot-org/code-dot-org/pull/36678

image

- **FieldDropdown, Google Blockly level, "core" block:** core blocks that Blockly renders itself looked as expected. "Core blocks" identified by comparing to what is found in this Blockly playground.
  - /s/alltheblocklythings/lessons/2/levels/1?blocklyVersion=Google
  - https://blockly-demo.appspot.com/static/tests/playground.html 

image

- **FieldDropdown, CDO Blockly level, custom block**
  - /s/alltheblocklythings/lessons/2/levels/1
- **FieldDropdown, CDO Blockly level, "core" block:**
  - /s/alltheblocklythings/lessons/2/levels/1
- **FieldButton (location picker), Google Blockly level**
  - /s/poem-art-2021/lessons/1/levels/6
- **FieldButton (location picker), CDO Blockly level**
  - /s/alltheblocklythings/lessons/2/levels/2?blocklyVersion=Cdo
- **FieldImageDropdown, CDO Blockly level**
    - /s/alltheblocklythings/lessons/2/levels/2
- **FieldImageDropdown, Google Blockly level**
  - /s/poem-art-2021/lessons/1/levels/6

### CODE REVIEW

**Comment by bencodeorg** [comment]
@mikeharv could use your two cents here on whether my approach here is (un)acceptable considering our general approach to the Blockly migration...have a slight feeling that what I'm doing here might be questionable.

**Review by mikeharv — APPROVED** [review]
I actually like this a lot! The un/registering looks exactly right and setting the classes onto the wrapper allows us to continue making new `blockly.FieldDropdown` regardless of Blockly version. This solution works because we're not patching. `Blockly.FieldDropdown` should still point to Google's file and not ours.  It seems like we're basically aliasing our field into this other space that we control so Blockly shouldn't have any issues there.
When we eventually deprecate the old fork, a cleanup tasks could be to move this stuff out of the wrapper and update the code everywhere to just reference the field directly (and shrink the wrapper down gradually until we don't even need it).

**Comment by bencodeorg** [comment]
> I actually like this a lot! The un/registering looks exactly right and setting the classes onto the wrapper allows us to continue making new `blockly.FieldDropdown` regardless of Blockly version. This solution works because we're not patching. `Blockly.FieldDropdown` should still point to Google's file and not ours. It seems like we're basically aliasing our field into this other space that we control so Blockly shouldn't have any issues there. When we eventually deprecate the old fork, a cleanup tasks could be to move this stuff out of the wrapper and update the code everywhere to just reference the field directly (and shrink the wrapper down gradually until we don't even need it).

Cool! Just to make sure I understand, is there a distinction between how you're using lower case `blockly` and upper case `Blockly` in this comment?

**Comment by bencodeorg** [comment]
> When we eventually deprecate the old fork, a cleanup tasks could be to move this stuff out of the wrapper and update the code everywhere to just reference the field directly (and shrink the wrapper down gradually until we don't even need it).

Was thinking something similar, really like this idea 👍

**Comment by bencodeorg** [comment]
@mikeharv added one more commit to update FieldImageDropdown as well, LMK if that looks ok. It extends a field type (FieldGridDropdown) that is defined in a standalone package, which is different than the two initial cases, but I think the same approach works ok:

https://www.npmjs.com/package/@blockly/field-grid-dropdown

**Comment by bencodeorg** [comment]
Alrighty @mikeharv, refactored FieldVariable as well for consistency. LMK what you think!

**Comment by mikeharv** [comment]
> > I actually like this a lot! The un/registering looks exactly right and setting the classes onto the wrapper allows us to continue making new `blockly.FieldDropdown` regardless of Blockly version. This solution works because we're not patching. `Blockly.FieldDropdown` should still point to Google's file and not ours. It seems like we're basically aliasing our field into this other space that we control so Blockly shouldn't have any issues there. When we eventually deprecate the old fork, a cleanup tasks could be to move this stuff out of the wrapper and update the code everywhere to just reference the field directly (and shrink the wrapper down gradually until we don't even need it).
> 
> Cool! Just to make sure I understand, is there a distinction between how you're using lower case `blockly` and upper case `Blockly` in this comment?

Yes, there's a distinction. `blockly` refers to the wrapper object (cdoBlocklyWrapper or googleBlocklyWrapper) whereas `Blockly` is what we're importing directly from the Blockly repo (code-dot-org/blockly or google/blockly).

**Comment by bencodeorg** [comment]
> Yes, there's a distinction. `blockly` refers to the wrapper object (cdoBlocklyWrapper or googleBlocklyWrapper) whereas `Blockly` is what we're importing directly from the Blockly repo (code-dot-org/blockly or google/blockly).

Oh interesting, I was under the impression upper case Blockly referred to the wrapper b/c of what I saw here:

https://github.com/code-dot-org/code-dot-org/blob/3c28765c0eddfd99998686a4538af559e51b121e/apps/src/sites/studio/pages/googleblockly.js#L8

**Review by mikeharv — APPROVED** [review]
This looks great Ben! Thanks for also refactoring CdoFieldVariable. I'm excited for this approach.

**Pull request merged**
