### PR TITLE
Temporarily Ignore Anonymous Abuse Reports

### PR DESCRIPTION
**Pull request by Hamms**
In response to some ongoing abuse of the abuse functionality, temporarily allow only verified teachers to report abuse and stop accepting abuse reports from anonymous users.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by hannahbergam — APPROVED** [review]
Makes sense. And we'd accompany this by removing all the aws blocks?

**Comment by Hamms** [comment]
Yep!

**Review by pablo-code-org — APPROVED** [review]

**Comment by Hamms** [comment]
merging ahead of drone to unblock our ability to report abuse

**Comment by Hamms** [comment]
oops, should not have done that; following up with a fix to a test

**Pull request merged**
