### PR TITLE
Update settings for UnitGroups for PLC Courses

### PR DESCRIPTION
**Pull request by dmcavoy**
Follow up to https://github.com/code-dot-org/code-dot-org/pull/44478.

This will update all the existing UnitGroups for PLC coures in all environments with the correct:

- instruction type
- participant audience
- instructor audience
- published state

## Testing story

- Ran migration locally

### CODE REVIEW

**Comment by davidsbailey** [comment]
> * Ran migration locally

just checking if were you able to verify that all PLC unit groups were updated correctly?

**Comment by dmcavoy** [comment]
> > * Ran migration locally
> 
> just checking if were you able to verify that all PLC unit groups were updated correctly?

I hand checked a couple of them. I can do something more through if you would like

**Comment by davidsbailey** [comment]
> > > * Ran migration locally
> > 
> > 
> > just checking if were you able to verify that all PLC unit groups were updated correctly?
> 
> I hand checked a couple of them. I can do something more through if you would like

my suggestion would be a ruby command to print out for each PLC ~course~ unit group: name, instruction type, audiences, published state. and then just look over the output to make sure none are blank or strange looking.

**Comment by dmcavoy** [comment]
```
[development] dashboard > Plc::Course.all.each do |pl_course| puts pl_course.unit_group.inspect end
  Plc::Course Load [NO INDEX] (1.0ms)  SELECT `plc_courses`.* FROM `plc_courses`
  UnitGroup Load (0.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 1 LIMIT 1
#<UnitGroup id: 1, name: "CS in Science Legacy", properties: {}, created_at: "2020-09-11 00:59:18", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (12.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 2 LIMIT 1
#<UnitGroup id: 2, name: "CS Principles Support", properties: {}, created_at: "2020-09-11 00:59:23", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.3ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 3 LIMIT 1
#<UnitGroup id: 3, name: "ECS Support Legacy", properties: {}, created_at: "2020-09-11 00:59:30", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 4 LIMIT 1
#<UnitGroup id: 4, name: "Equity Support", properties: {}, created_at: "2020-09-11 00:59:39", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.5ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 5 LIMIT 1
#<UnitGroup id: 5, name: "K5 Support", properties: {}, created_at: "2020-09-11 00:59:40", updated_at: "2022-01-26 21:11:56", published_state: "pilot", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.5ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 6 LIMIT 1
#<UnitGroup id: 6, name: "Other plc course", properties: {}, created_at: "2020-09-11 00:59:42", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (14.1ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 7 LIMIT 1
#<UnitGroup id: 7, name: "CS in Algebra Legacy", properties: {}, created_at: "2020-09-11 00:59:43", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 8 LIMIT 1
#<UnitGroup id: 8, name: "CS in Algebra Support", properties: {}, created_at: "2020-09-11 00:59:50", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.3ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 9 LIMIT 1
#<UnitGroup id: 9, name: "All The PLC Things", properties: {}, created_at: "2020-09-11 01:00:00", updated_at: "2022-01-25 00:36:53", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (0.3ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 10 LIMIT 1
#<UnitGroup id: 10, name: "Andrea Test", properties: {"is_deeper_learning_course"=>true}, created_at: "2020-09-11 01:00:06", updated_at: "2022-01-26 07:27:11", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (0.5ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 11 LIMIT 1
#<UnitGroup id: 11, name: "CS Discoveries Facilitator in Training 2018-2019", properties: {}, created_at: "2020-09-11 01:04:55", updated_at: "2022-01-25 00:36:54", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (14.3ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 12 LIMIT 1
#<UnitGroup id: 12, name: "CS Discoveries Facilitator in Training", properties: {}, created_at: "2020-09-11 01:05:08", updated_at: "2022-01-25 00:36:54", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 13 LIMIT 1
#<UnitGroup id: 13, name: "CS Discoveries TeacherCon Novice", properties: {}, created_at: "2020-09-11 01:09:59", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.7ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 14 LIMIT 1
#<UnitGroup id: 14, name: "CS Principles Facilitator in Training 2018-2019", properties: {}, created_at: "2020-09-11 01:12:28", updated_at: "2022-01-25 00:36:54", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (0.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 15 LIMIT 1
#<UnitGroup id: 15, name: "CS Principles Curriculum Training for Facilitators", properties: {}, created_at: "2020-09-11 01:12:34", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (16.0ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 16 LIMIT 1
#<UnitGroup id: 16, name: "CS Principles Facilitator in Training", properties: {}, created_at: "2020-09-11 01:13:28", updated_at: "2022-01-26 21:10:37", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.3ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 17 LIMIT 1
#<UnitGroup id: 17, name: "CSP Support", properties: {}, created_at: "2020-09-11 01:13:45", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.5ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 18 LIMIT 1
#<UnitGroup id: 18, name: "CS Discoveries Deeper Learning 2019 - 2020", properties: {}, created_at: "2020-09-11 01:25:17", updated_at: "2022-01-25 00:36:55", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 19 LIMIT 1
#<UnitGroup id: 19, name: "CS Principles Deeper Learning 2019 - 2020", properties: {}, created_at: "2020-09-11 01:25:22", updated_at: "2022-01-25 00:36:55", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (0.5ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 20 LIMIT 1
#<UnitGroup id: 20, name: "ECS Support", properties: {}, created_at: "2020-09-11 01:25:56", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (13.7ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 21 LIMIT 1
#<UnitGroup id: 21, name: "FIT Weekend In Person", properties: {}, created_at: "2020-09-11 01:29:04", updated_at: "2022-01-25 00:36:55", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 22 LIMIT 1
#<UnitGroup id: 22, name: "Facilitators in Training Summer Reflections 2019", properties: {}, created_at: "2020-09-11 01:29:05", updated_at: "2022-01-25 00:36:55", published_state: "preview", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.3ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 23 LIMIT 1
#<UnitGroup id: 23, name: "Facilitators in Training Summer 2019", properties: {}, created_at: "2020-09-11 01:29:08", updated_at: "2022-01-25 00:36:55", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (0.3ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 24 LIMIT 1
#<UnitGroup id: 24, name: "CS in Science Support", properties: {}, created_at: "2020-09-11 01:38:56", updated_at: "2021-06-15 05:15:27", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
  UnitGroup Load (0.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 57 LIMIT 1
#<UnitGroup id: 57, name: "2021 CS Discoveries Deeper Learning", properties: {}, created_at: "2021-09-07 22:30:53", updated_at: "2022-01-25 00:36:56", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (16.8ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 58 LIMIT 1
#<UnitGroup id: 58, name: "2021 CS Principles Deeper Learning", properties: {}, created_at: "2021-09-07 22:30:53", updated_at: "2022-01-25 00:36:56", published_state: "beta", instruction_type: "teacher_led", instructor_audience: "plc_reviewer", participant_audience: "facilitator">
  UnitGroup Load (0.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 59 LIMIT 1
#<UnitGroup id: 59, name: "Tess Test Course", properties: {}, created_at: "2021-09-07 22:32:11", updated_at: "2021-09-07 22:32:11", published_state: "in_development", instruction_type: "teacher_led", instructor_audience: "teacher", participant_audience: "student">
```

**Comment by dmcavoy** [comment]
```
Plc::Course.all.each do |pl_course|
    puts ""
    puts "NAME: " + pl_course.unit_group.name
    puts "published_state: " + pl_course.unit_group.published_state
    puts "instruction_type: " + pl_course.unit_group.instruction_type
    puts "participant_audience: " + pl_course.unit_group.participant_audience
    puts "instructor_audience: " + pl_course.unit_group.instructor_audience
  end
  Plc::Course Load [NO INDEX] (0.5ms)  SELECT `plc_courses`.* FROM `plc_courses`

  UnitGroup Load (6.2ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 1 LIMIT 1
NAME: CS in Science Legacy
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 2 LIMIT 1
NAME: CS Principles Support
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (0.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 3 LIMIT 1
NAME: ECS Support Legacy
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (9.3ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 4 LIMIT 1
NAME: Equity Support
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (0.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 5 LIMIT 1
NAME: K5 Support
published_state: pilot
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (16.2ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 6 LIMIT 1
NAME: Other plc course
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (0.8ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 7 LIMIT 1
NAME: CS in Algebra Legacy
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (1.0ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 8 LIMIT 1
NAME: CS in Algebra Support
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (0.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 9 LIMIT 1
NAME: All The PLC Things
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 10 LIMIT 1
NAME: Andrea Test
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (0.3ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 11 LIMIT 1
NAME: CS Discoveries Facilitator in Training 2018-2019
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 12 LIMIT 1
NAME: CS Discoveries Facilitator in Training
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (16.7ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 13 LIMIT 1
NAME: CS Discoveries TeacherCon Novice
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (0.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 14 LIMIT 1
NAME: CS Principles Facilitator in Training 2018-2019
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (0.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 15 LIMIT 1
NAME: CS Principles Curriculum Training for Facilitators
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (0.5ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 16 LIMIT 1
NAME: CS Principles Facilitator in Training
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (2.0ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 17 LIMIT 1
NAME: CSP Support
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 18 LIMIT 1
NAME: CS Discoveries Deeper Learning 2019 - 2020
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 19 LIMIT 1
NAME: CS Principles Deeper Learning 2019 - 2020
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (17.0ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 20 LIMIT 1
NAME: ECS Support
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (1.0ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 21 LIMIT 1
NAME: FIT Weekend In Person
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (3.6ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 22 LIMIT 1
NAME: Facilitators in Training Summer Reflections 2019
published_state: preview
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (0.7ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 23 LIMIT 1
NAME: Facilitators in Training Summer 2019
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (0.5ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 24 LIMIT 1
NAME: CS in Science Support
published_state: beta
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher

  UnitGroup Load (0.3ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 57 LIMIT 1
NAME: 2021 CS Discoveries Deeper Learning
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (0.4ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 58 LIMIT 1
NAME: 2021 CS Principles Deeper Learning
published_state: beta
instruction_type: teacher_led
participant_audience: facilitator
instructor_audience: plc_reviewer

  UnitGroup Load (15.0ms)  SELECT  `unit_groups`.* FROM `unit_groups` WHERE `unit_groups`.`id` = 59 LIMIT 1
NAME: Tess Test Course
published_state: in_development
instruction_type: teacher_led
participant_audience: student
instructor_audience: teacher
```

**Review by davidsbailey — APPROVED** [review]

**Pull request merged**
