### PR TITLE
Move Devise Customization into Subdirectory

### PR DESCRIPTION
**Pull request by Hamms**
In preparation for some upcoming work-in-progress changes to [enable automatic lockout for teachers](https://github.com/code-dot-org/code-dot-org/pull/57515) and [allow users to log out of all existing sessions](https://github.com/code-dot-org/code-dot-org/pull/59763), we'd like to move our existing customization to Devise functionality into a subdirectory and associated Module so that the upcoming functionality can be organized into the same place.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by sureshc** [comment]
Are there any tests that exercise the existing logic?

**Review by sureshc — APPROVED** [review]
Might be worth having someone in Platform Team take a glance?

**Comment by Hamms** [comment]
> Are there any tests that exercise the existing logic?

None that I could find; I tested manually, but might check to see if it would be quick to add one

**Comment by Hamms** [comment]
I checked; I'm guessing the reason there isn't already a test for this is that it looks like it would actually be quite a pain to add one. @code-dot-org/platform, what do you all think; is it worth adding a test for this functionality or do you think it's already adequately covered by existing tests?

**Review by carl-codeorg — APPROVED** [review]
The code being moved is pretty small, and has existed for 10 years. If it's been around that long without specific unit tests, we're probably fine.

**Pull request merged**
