### PR TITLE
Mini Rubric: Shrink Vertical Space

### PR DESCRIPTION
**Pull request by dmcavoy**
Change sizing of elements in feedback tab in order to shrink vertical space. Also some style changes to layout of rubric fields.

## Before
Screen Shot 2019-03-13 at 10 38 58 AM

### Teacher
Screen Shot 2019-03-13 at 5 08 08 PM
Screen Shot 2019-03-13 at 5 08 15 PM

### Student
Screen Shot 2019-03-13 at 5 10 03 PM

### CODE REVIEW

**Review by maddiedierker — APPROVED** [review]
good call, this is definitely a spot where space conservation is important :shipit:

**Comment by maddiedierker** [comment]
out of curiosity, what happens when the "Key Concept" description is really long? (i think you may have addressed this in a previous PR, but i'm not sure where)

**Review by davidsbailey — APPROVED** [review]

**Comment by dmcavoy** [comment]
@madelynkasula It has to get pretty long for it to be an issue but once it does it extends the page vertically.
### Long Key Concept: No Issue
Screen Shot 2019-03-13 at 2 11 45 PM

### No Key Concept: Extend Area
Screen Shot 2019-03-13 at 2 12 27 PM

**Comment by davidsbailey** [comment]
I think the "No Key Concept: Extend Area" screenshot shows that you could afford to trim a bit more ~horizontal~ vertical space away above the "Teacher Feedback" heading.

**Review by maddiedierker — APPROVED** [review]

**Pull request merged**
