### PR TITLE
Prevent admins from joining sections as a student.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This prevents teachers from commandeering an admin account by resetting the password for an admin user in their section.

Note that #15978 will prevent upgrading a teacher account with sections_as_student to be an admin account.

Finally, we'll handle existing violations in an adhoc manner.

### CODE REVIEW

**Comment by davidsbailey** [comment]
Thanks for owning this, Asher! Would you mind including a screenshot of what this looks like when access to the join link is denied?

**Comment by ashercodeorg** [comment]
@poorvasingal Do we need (want) prettier UI for an error message?

**Comment by davidsbailey** [comment]
What will the user see when they hit this error in production? I don't think we show a stack trace in that case. This doesn't need to be pretty, but it also shouldn't look the same, visually, as the site being down.

**Comment by poorvasingal** [comment]
You guys are the user for this, so I'll let you decide if you need prettier UI. My guess is no...

**Comment by ashercodeorg** [comment]
Per offline conversation, I've changed it so that attempting to join a new section through the `FollowerController` now redirects to the admin directory.

PTAL.

**Pull request merged**
