### PR TITLE
Use smaller batch size in contact rollups and change cronjob time

### PR DESCRIPTION
**Pull request by megcrenshaw**
Adds a DCDO flag to set our batch size. I've currently set this flag to be 1000:
image

But kept the default value at what it's been.

## Follow-up work

I added a plan to [this document](https://docs.google.com/document/d/1NnhJQS06PH1gPLWYQQJZsF9rhkFshl8yjHcmMfVbbYA/edit), but there are two possible follow-ups from here:
- Suresh is working on getting our reporting database cluster set up for use, and we can take advantage of that once it's ready, but it won't be trivial (i.e. we'll need to refactor some parts to use it)
- Other refactors might take some time, but it'd be great to do if Acq Prod has the bandwidth

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by sureshc — APPROVED** [review]
Thanks for leading this! What Jira Task will we use to track the larger architectural performance improvements?

**Comment by megcrenshaw** [comment]
Jira task for future work is here https://codedotorg.atlassian.net/browse/ACQ-10

**Review by pablo-code-org — COMMENTED** [review]
It looks good to me, 

Also FYI, if you do want to measure the optimization of your change, you should do one change at a time....

For example, if the load is lower after these 2 changes, is it because you changed the time it runs? or is it because of the batch size?

If I were to deploy this, I would just update the batch size first and this is why:

1) you would want to monitor things potentially, doing it at 4 pm is better than doing it at 1am :D . Your new batch size could make the script for too long or even not finish (this is 10% of what it used to be) so in theory it could take 10x time 

2) for the reason mentioned above, you want to compare apples to apples. and if you see a reduction at 4pm, then you know the batch size was what was needed. 

I believe that understanding how the change affects the db load is knowledge more valuable. For example, next time we have a similar issue, we know how batching affects the performance with anecdotal data.

Other ideas:
- Turn this into a DCDO variable so you can update easily and find the right value. Batching is tricky, because we don't know what is the right number. There are many factors. You could in theory overbatching (for example, batch_size = 1 is the extreme).

One way to figure this out is to do a binary search with your performance metric and find the right number. 

cc: @sureshc  that is dotd

**Comment by pablo-code-org** [comment]
also, we have some database CPU overload right now, not sure if we want to push this change right now. Again @sureshc  is the right one to answer this

**Review by pablo-code-org — APPROVED** [review]

**Comment by megcrenshaw** [comment]
Ah, I love these ideas, Pablo! I was under the impression that the time change was semi-urgent to reduce load during higher usage. Is that not the case?

I'll go ahead and add a DCDO flag for the batch size. Good idea!

**Comment by pablo-code-org** [comment]
@sureshc  we are good in terms of db resources after your upgrade last night right so it is no longer critical to move the time this week right?

**Review by davidsbailey — APPROVED** [review]

**Review by pablo-code-org — APPROVED** [review]

**Comment by pablo-code-org** [comment]
I am curious, just for my own education.

What happens if this script fails or gets too stale?

**Comment by megcrenshaw** [comment]
> What happens if this script fails or gets too stale?

I'm not seeing anything to gracefully exit out of the script if it's taking too long. I'm seeing some [allusions to the script failing](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/lib/contact_rollups_v2.rb#L85), but mostly just `ensure` statements [for logging metrics](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/lib/contact_rollups_v2.rb#L142).

**Comment by megcrenshaw** [comment]
@sureshc I'm assuming it's no longer critical to move this script to a different time. If that's wrong, let me know and I can put out a PR for that.

**Pull request merged**
