### PR TITLE
Upgrade blockly to 9.3.3

### PR DESCRIPTION
**Pull request by fisher-alice**
This PR upgrades the `blockly` package version to the `9.3.3`. This update will unblock the work for adding new procedure blocks and disabling modal input.

In order to standardize the process of upgrading this package to the latest version, we updated the [Google Blockly testing document](https://docs.google.com/spreadsheets/d/1luw0WVl6v-LvpkHlRreY_j_Y0SIudTgpGVtAezpJ9h8/edit#gid=937149361) and created a manual testing checklist to help with version updates.

When I upgraded locally, I checked to make sure I was on the most recent version by typing in the browser console `Blockly.blockly_.VERSION`.

## Testing story
[Manual testing checklist](https://docs.google.com/spreadsheets/d/1luw0WVl6v-LvpkHlRreY_j_Y0SIudTgpGVtAezpJ9h8/edit#gid=937149361)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by bencodeorg — APPROVED** [review]
LGTM! Testing document will be very helpful 🙌  -- one idea, could we include links to levels to test in there as well (I see columns have them listed)? And, do we need to test both standalone project and curriculum levels for each lab, or is that not necessary?

**Comment by sanchitmalhotra126** [comment]
Question - I remember @mikeharv had recently rolled back to an older version of Blockly due to some breaking changes (I think with scrolling on touch devices?). Have those regressions been fixed in this version?

**Comment by jmkulwik** [comment]
>In order to standardize the process of upgrading this package to the latest version, we updated the [Google Blockly testing document](https://docs.google.com/spreadsheets/d/1luw0WVl6v-LvpkHlRreY_j_Y0SIudTgpGVtAezpJ9h8/edit#gid=937149361) and created a manual testing checklist to help with version updates.

^ Is there a place in the repo where a README could be added for this documentation?

**Review by mikeharv — APPROVED** [review]
As @sanchitmalhotra126 mentioned, we recently had to [downgrade to 9.1 from 9.2](https://github.com/code-dot-org/code-dot-org/pull/50826) due to [core Blockly bug](https://github.com/google/blockly/issues/6759) related to scrolling on touch devices. This bug has been [fixed](https://github.com/google/blockly/pull/6911) and 9.3.3 includes the fix.

**Comment by mikeharv** [comment]
@bencodeorg 
> And, do we need to test both standalone project and curriculum levels for each lab, or is that not necessary?

We do currently need to test a few curriculum levels and other places for some some different uses of read-only workspaces:
- **Embedded blocks** - The first levels of dance-2019, poem-art-2021, and flappy each contain different types of hints/instructions with embedded blocks.
- **Block pools** - We should check that all blocks are rendered without errors on the poetry and dance block pool indexes, and also check an edit page to make sure it is being created correctly.

Because embedded blocks currently include some amount of direct SVG manipulation, we should be checking for regressions in RTL mode as well.

**Comment by mikeharv** [comment]
@jmkulwik Good suggestion about the README. I'd propose this location: 
https://github.com/code-dot-org/code-dot-org/tree/staging/apps/src/blockly

I created a Jira issue to track this: https://codedotorg.atlassian.net/browse/SL-820

**Comment by fisher-alice** [comment]
> As @sanchitmalhotra126 mentioned, we recently had to [downgrade to 9.1 from 9.2](https://github.com/code-dot-org/code-dot-org/pull/50826) due to [core Blockly bug](https://github.com/google/blockly/issues/6759) related to scrolling on touch devices. This bug has been [fixed](https://github.com/google/blockly/pull/6911) and 9.3.3 includes the fix.

Thanks for answering this @mikeharv and including the references!

**Pull request merged**
