### PR TITLE
Foorm: New Facilitator Post-Workshop Survey

### PR DESCRIPTION
**Pull request by molly-moen**
Move the facilitator post-workshop survey from JotForm to Foorm
[Existing JotForm survey](https://form.jotform.com/201595646393161)

## Testing story
Validated the new survey works locally.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by molly-moen** [comment]
@lauraschute fyi

**Review by lauraschute — APPROVED** [review]
Looks good to me!

**Review by bencodeorg — APPROVED** [review]

**Comment by bencodeorg** [comment]
One comment -- should the survey name reflect that it's CSP/D only (I think it is)?

**Comment by molly-moen** [comment]
> One comment -- should the survey name reflect that it's CSP/D only (I think it is)?

@bencodeorg do you mean the name of the file?

**Comment by bencodeorg** [comment]
> > One comment -- should the survey name reflect that it's CSP/D only (I think it is)?
> 
> @bencodeorg do you mean the name of the file?

Yes, sorry that's what I meant. Not sure how committed we have been to keeping the actual title of the survey in alignment with the file name, but I wouldn't be opposed to having the course in the actual survey title as well (might be a little redundant, but telling a facilitator its a "Facilitator Post-Workshop Survey" is maybe already redundant so it's ok)?

Anyway, yeah I think file name change at least would be helpful.

**Review by lauraschute — COMMENTED** [review]
@bencodeorg  I am not against having CSD/CSP included in the title.

**Comment by molly-moen** [comment]
renamed file and removed duplicated title on the survey

**Pull request merged**
