### PR TITLE
Upgrade to sinon 4

### PR DESCRIPTION
**Pull request by islemaster**
Upgrade from sinon 3.2.1 to sinon 4.5.0.

Here's the upgrade guide: https://sinonjs.org/guides/migrating-to-4.0.html

Only breaking change: `sinon.stub(obj, 'nonExistingProperty')` now throws.

Also updated `sinon-chai` to 2.13.0 to 3.3.0.  It added support for sinon 4+ in 2.14.0 and requires sinon 4 as of 3.0.0 ([source](https://github.com/domenic/sinon-chai/releases)).

### Context

- Remove fake-fetch: https://github.com/code-dot-org/code-dot-org/pull/29648
- Remove sinon-chai-in-order: https://github.com/code-dot-org/code-dot-org/pull/29675
- Sinon 4: **This pull request**
- Sinon 5: https://github.com/code-dot-org/code-dot-org/pull/29642
- Sinon 6: https://github.com/code-dot-org/code-dot-org/pull/29643
- Sinon 7: https://github.com/code-dot-org/code-dot-org/pull/29645

### CODE REVIEW

**Review by Hamms — APPROVED** [review]
love this one-major-version-at-a-time plan!

Looks like we were using `sinon@^4.5.0` previously; any ideas what that's about?

**Comment by Hamms** [comment]
Notably, it looks like we're _still_ depending on 4.5 after updating to 5: https://github.com/code-dot-org/code-dot-org/pull/29642/files#diff-1b28c39bb54275ba36a716e98f13b8cbR14413

**Comment by islemaster** [comment]
That's due to the `fake-fetch` package.  Per discussion, updating my plan to remove it first, then proceed with this upgrade.

**Comment by islemaster** [comment]
Eek - seeing more failing tests than I expected here.  I guess we've been a bit haphazard with our stub calls, especially in integration tests.

**Comment by islemaster** [comment]
Well, realized we should tear out `sinon-chai-in-order` too, which means delaying this PR just a little longer :cry:

**Comment by islemaster** [comment]
There we go - clean yarn.lock update, passing tests!

**Pull request merged**
