### PR TITLE
Javalab: Update colors to match branding

### PR DESCRIPTION
**Pull request by sanchitmalhotra126**
Updates the background and Finish button colors to match branding. We didn't have a color constant for the desired dark grey background, so I added one and just called it "~~darkest_slate_grey~~ background_black" for now.

Before:
Screen Shot 2022-02-01 at 11 29 42 AM

After:
Screen Shot 2022-02-02 at 10 47 14 AM

## Links

JIRA: https://codedotorg.atlassian.net/browse/JAVA-429
Spec: https://docs.google.com/document/d/1eaNGb-etGnTU4_qPHWHxuzdNIjrBISiW0khBz87_nY0/edit#
Figma: https://www.figma.com/file/fZo4fcZmDUioOCaz04Gza4/Javalab-Design-Spec?node-id=1609%3A5076

## Testing story

Tested locally

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by molly-moen — APPROVED** [review]

**Comment by jmkulwik** [comment]
Can you check in with Mike about changing the background color independent of the editor color? With just updating the background color, I'm finding it difficult to see where the background ends and the editor starts.

**Comment by sanchitmalhotra126** [comment]
> Can you check in with Mike about changing the background color independent of the editor color? With just updating the background color, I'm finding it difficult to see where the background ends and the editor starts.

Sure - FWIW though, it looks like the mocks have the same background color for the page background and the editor background which would make it even harder to differentiate the editor from the page - is that what we want?

**Comment by moneppo** [comment]
I messed up the color mapping by missing an additional shade of gray. The page background color should be #121416 and the editor background should be #25292D. Apologies!

**Comment by jmkulwik** [comment]
Mind updating the "after" image?

**Comment by sanchitmalhotra126** [comment]
> Mind updating the "after" image?

Done!

**Review by jmkulwik — APPROVED** [review]
LGTM!

**Pull request merged**
