### PR TITLE
create pd_applications_status_logs table

### PR DESCRIPTION
**Pull request by davidsbailey**
Starts [ACQ-196](https://codedotorg.atlassian.net/browse/ACQ-196). This PR just contains the migration to create the table. The next PR (https://github.com/code-dot-org/code-dot-org/pull/48849) populates it with data. Here is what the table looks like, after populating it with a few rows:

```
mysql> describe pd_applications_status_logs;
+-------------------+--------------+------+-----+---------+----------------+
| Field             | Type         | Null | Key | Default | Extra          |
+-------------------+--------------+------+-----+---------+----------------+
| id                | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| pd_application_id | bigint(20)   | NO   |     | NULL    |                |
| status            | varchar(255) | NO   |     | NULL    |                |
| timestamp         | datetime     | NO   |     | NULL    |                |
| position          | int(11)      | NO   |     | NULL    |                |
+-------------------+--------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)

mysql> select * from pd_applications_status_logs;
+----+-------------------+--------------------------+---------------------+----------+
| id | pd_application_id | status                   | timestamp           | position |
+----+-------------------+--------------------------+---------------------+----------+
|  1 |                 1 | confirmation_email       | 2022-10-25 21:44:12 |        0 |
|  2 |                 1 | principal_approval_email | 2022-10-25 21:44:12 |        1 |
|  3 |                 1 | unreviewed               | 2022-10-25 21:44:12 |        2 |
+----+-------------------+--------------------------+---------------------+----------+
3 rows in set (0.00 sec)
```

## Testing story

Ran the script in https://github.com/code-dot-org/code-dot-org/pull/48849 locally to generate the above output

### CODE REVIEW

**Review by megcrenshaw — APPROVED** [review]
This looks good, but I do have one question:

There's the `status_log` and the `status_timestamp_change_log`. It looks like this takes the data from `status_log` and doesn't worry about the extra stuff in the `status_timestamp_change_log` (changing_user_name, changing_user_id, more detailed status). Is that right?

**Comment by davidsbailey** [comment]
> This looks good, but I do have one question:
> 
> There's the `status_log` and the `status_timestamp_change_log`. It looks like this takes the data from `status_log` and doesn't worry about the extra stuff in the `status_timestamp_change_log` (changing_user_name, changing_user_id, more detailed status). Is that right?

Hmm good question, I had missed the status_log. Here is what I see for the one pd application in my local db:
```
                 properties: {"status_log":[{"status":"unreviewed","at":"2022-10-25T21:44:12.723Z"}]}
status_timestamp_change_log: [{"time":"2022-10-25T21:44:12.855Z","title":"confirmation_email"},{"time":"2022-10-25T21:44:12.890Z","title":"principal_approval_email"},{"title":"unreviewed","changing_user_id":1,"changing_user_name":"DaveAll","time":"2022-10-25T21:44:12.896Z"}]
```
status_timestamp_change_log has more entries, but they aren't necessarily desirable entries, because the "confirmation_email" and "principal_approval_email" states don't seem like states we were expecting (right?)

I will do some more investigating on prod data. thanks for pointing this out!

**Comment by davidsbailey** [comment]
> It looks like this takes the data from status_log and doesn't worry about the extra stuff in the status_timestamp_change_log (changing_user_name, changing_user_id, more detailed status). Is that right?

https://github.com/code-dot-org/code-dot-org/pull/48849 currently takes the data from `status_timestamp_change_log`, not `status_log`, ignoring changing_user_name and changing_user_id.

**Comment by megcrenshaw** [comment]
Sounds good! Thanks for the clarification 👍

**Comment by davidsbailey** [comment]
again great find @megcrenshaw ! the status_log field looks like the data we want. @dmcavoy , heads up that I'm planning to update the next PR to read from status_log rather than status_timestamp_change_log. I'll include some details in that PR.

**Pull request merged**
