### PR TITLE
[Dance Party] Change to use Google Blockly

### PR DESCRIPTION
**Pull request by mikeharv**
1. Changes Dance levels to always use Google Blockly
2. Updates `dance_party.feature` for Google Blockly
3. Updates all dance levels to disable modal function editor.
4. Use a level's Blockly version to determine if we should allow levelbuilders to enable modal function editor.

|CDO Blockly|Google Blockly|
|-|-|
|image|image|

## Links

Bug Bash: [Google Doc: Dance Party Bug Bash](https://docs.google.com/document/d/1Vskz2UVRIhf0aTsreLBd14wQkXuYpt02yxdCTMc5tC0/edit)

Jira ticket: [SL-68: [Dance Party] Change to use Google Blockly](https://codedotorg.atlassian.net/browse/SL-68)

The following issues should be resolved and merged ahead of this pull request:
- https://github.com/code-dot-org/code-dot-org/pull/49059
- https://github.com/code-dot-org/code-dot-org/pull/49073
- https://github.com/code-dot-org/code-dot-org/pull/49087
- https://github.com/code-dot-org/code-dot-org/pull/49082

Previous flip for Bounce:
- https://github.com/code-dot-org/code-dot-org/pull/46030

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bencodeorg** [comment]
Reminder to update _blockly.html.haml to use the `uses_google_blockly` method in this PR per discussion here:

https://github.com/code-dot-org/code-dot-org/pull/48857#discussion_r1006163346

**Comment by bencodeorg** [comment]
Just confirmed that the modal change (https://github.com/code-dot-org/code-dot-org/pull/49082) looks good in production on iPad (no modal when editing "after # measures" on dance level 4, audio plays after editing # of measures).

**Comment by bencodeorg** [comment]
@mikeharv could you make the change suggested in this comment? Looks good otherwise:

https://github.com/code-dot-org/code-dot-org/pull/48860#issuecomment-1292769955

**Comment by mikeharv** [comment]
@bencodeorg Thanks for the reminder!

**Review by bencodeorg — APPROVED** [review]

**Pull request merged**
