### PR TITLE
Upgrade karma and friends to --latest

### PR DESCRIPTION
**Pull request by snickell**
Followup to #53841 

- [x] `yarn test:unit` passes
- [x] `yarn test:integration` passes
- [x] `yarn test` passes
- [x] drone passes

Upgrading Karma messed with some of the Sinon stub calls which needed to be resolved in order to pass unit tests.

Screenshot 2024-03-26 at 10 02 37 AM

https://github.com/code-dot-org/code-dot-org/pull/56776#issuecomment-2021241934

### CODE REVIEW

**Comment by snickell** [comment]
This PR is a continuation of #53931, which was mis-closed by the Git LFS migration (#55759).

### Previous Comments:
- **snickell** [commented](https://github.com/code-dot-org/code-dot-org/pull/53931#issuecomment-1734719608) - It appears that switching from karma-coverage to karma-coverage-istanbul (https://github.com/code-dot-org/code-dot-org/pull/31612) may not have paid off. karma-coverage is still maintained, while the latter is not. Considering switching back...
- **snickell** [commented](https://github.com/code-dot-org/code-dot-org/pull/53931#issuecomment-1734736347) - Running `yarn test:unit`, I get a few of these, otherwise good:
 ```
 Chrome Headless 117.0.5938.62 (Mac OS 10.15.7) ERROR
   Uncaught TypeError: Cannot read properties of undefined (reading 'then')
   at node_modules/sinon/lib/sinon/proxy-invoke.js:84:1 <- build/karma/commons.js:1726224:9
   
   TypeError: Cannot read properties of undefined (reading 'then')
       at src/code-studio/initApp/project.js:1318:7 <- build/karma/commons.js:844574:51
       at Object.<anonymous> (test/unit/code-studio/initApp/projectTest.js:1240:52 <- build/karma/commons.js:1194549:14)
       at Object.invoke (node_modules/sinon/lib/sinon/behavior.js:177:1 <- build/karma/commons.js:1724251:32)
       at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:42:1 <- build/karma/commons.js:1727528:43)
       at Function.invoke (node_modules/sinon/lib/sinon/proxy-invoke.js:50:1 <- build/karma/commons.js:1726190:47)
       at Object.functionStub [as getAnimationList] (node_modules/sinon/lib/sinon/proxy.js:265:1 <- build/karma/commons.js:1726504:26)
       at Object.getUpdatedSourceAndHtml_ (src/code-studio/initApp/project.js:1317:24 <- build/karma/commons.js:844573:24)
       at Object.autosave (src/code-studio/initApp/project.js:1533:10 <- build/karma/commons.js:844792:10)
       at WebLab.beforeUnload (src/weblab/WebLab.js:320:13 <- build/karma/commons.js:1156048:25)
       at navigateContextTo (http://localhost-studio.code.org:9876/karma.js:146:18)
 
 ✖ Error while running the tests! Exit code: 1
 ```

### Previous Reviews:

**Review by wilkie — APPROVED** [review]
LGTM. Thankfully quite straightforward.

Would you mind writing a description for the PR about the changes you made in a post here and linking it in the PR description above? I think the PR should have at least a bit of that for the sake of posterity.

**Comment by stephenliang** [comment]
Looks great, thank you both!

**Comment by juanmanzojr** [comment]
> LGTM. Thankfully quite straightforward.
> 
> Would you mind writing a description for the PR about the changes you made in a post here and linking it in the PR description above? I think the PR should have at least a bit of that for the sake of posterity.

The logic for selecting and running tests has been refactored into separate functions, allowing for the passing of different contexts for karma tests. Additionally, upgrading Karma messed with some of the Sinon stub calls in unit tests as tests were expecting a Promise. Adding `.resolves()` to the stubbed methods ensured a Promise was returned.

**Pull request merged**
