### PR TITLE
Maker 2.0 Launch - Misc updates

### PR DESCRIPTION
**Pull request by kelbyhawn**
Update links and content on the following pages:
- https://code.org/educate/curriculum/high-school
  - Update `Explore Creating Apps with Devices Unit` button copy and link*
- https://code.org/educate/curriculum/middle-school
  - Update `Explore Creating Apps with Devices Unit` button copy and link*
- https://code.org/educate/csp
  - Update `Explore Unit` link
- https://code.org/educate/applab
  - Update the `Creating Apps With Devices` row copy, image, and link (screenshot below)
Screenshot 2023-03-21 at 10 06 03 AM

*Uses same partial file `/views/csp_standalone_units.haml`

**Asana task:** https://app.asana.com/0/1204178505869103/1204227334996074/f

**Related PRs:**
- https://github.com/code-dot-org/code-dot-org/pull/50785
- https://github.com/code-dot-org/code-dot-org/pull/50761

### CODE REVIEW

**Comment by megcrenshaw** [comment]
Are these URLs supposed to go to https://code.org/maker/pick-a-device? I can't find the page

**Comment by kelbyhawn** [comment]
> Are these URLs supposed to go to https://code.org/maker/pick-a-device? I can't find the page

They are — the page is [created](https://github.com/code-dot-org/code-dot-org/pull/50785/files#diff-782794e362b2f1f68690271890968551097e1ad573e54a53655fcc11b92c76bc) in this PR: https://github.com/code-dot-org/code-dot-org/pull/50785 (it should all work together when everything is merged into staging)

**Comment by megcrenshaw** [comment]
> > Are these URLs supposed to go to https://code.org/maker/pick-a-device? I can't find the page
> 
> They are — the page is [created](https://github.com/code-dot-org/code-dot-org/pull/50785/files#diff-782794e362b2f1f68690271890968551097e1ad573e54a53655fcc11b92c76bc) in this PR: #50785 (it should all work together when everything is merged into staging)

Ah got it, thanks!

**Review by megcrenshaw — APPROVED** [review]
🎉

**Review by dmcavoy — APPROVED** [review]
Looks good!

**Pull request merged**
