### PR TITLE
Allow silent login via oauth for Google, Microsoft, and Facebook accounts

### PR DESCRIPTION
**Pull request by ewjordan**
If the email address on a user's Google, MS, or Facebook account matches an email/password Code.org account, automatically log in the user rather than pushing them to an error page.

We specifically do not include Clever, because it is easy to create accounts that point at an email you do not control there.

### CODE REVIEW

**Comment by ewjordan** [comment]
Hmm, this might not work perfectly as-is, because it doesn't store away the oauth token. Will have to figure out how to test that.

**Comment by wjordan** [comment]
Maybe worth checking the [`email_verified` Claim](http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) on the ID token returned from the Provider:

> When this Claim Value is `true`, this means that the OP [OpenID Provider] took affirmative steps to ensure that this e-mail address was controlled by the End-User at the time the verification was performed.

Verifying the presence of this Claim (in addition to whitelisting only the providers we trust in this way) would give extra security for these silent-takeover cases.

**Comment by joshlory** [comment]
Test coverage?

**Comment by ewjordan** [comment]
@wjordan and I discussed the `email_verified` matter - at the moment, we're going to hold off on this because the data format appears to be different depending on the provider and we're having trouble finding the test credentials for FB and MS accounts. We will return to it later, though.

Tests I'm going to put in another PR (https://github.com/code-dot-org/code-dot-org/pull/16493), those are also not straightforward to get working (the happy path test case that works manually fails in test because it ultimately involves multiple calls to a controller, and the second doesn't see the results of the first within the test). This is fixable, but I don't know yet how long it will take or how much restructuring, so I'm going to split the PRs.

**Pull request merged**
