### PR TITLE
[AI Chat] Limit user messages to 10,000 characters

### PR DESCRIPTION
**Pull request by ebeastlake**
This sets the max length of users' text area to enter AIChat messages to 10,000 characters. 

Below is an expandable table showing the number of current messages in our database bucketed by 500-character ranges.

<details>
<summary>Current Messages Bucketed by 500-Character Ranges</summary>

```csv
"length_range","count"
0,55312
500,203
1000,45
1500,23
2000,27
2500,10
3000,4
3500,2
4000,8
4500,5
5000,3
5500,1
6000,5
6500,1
7000,2
7500,3
8000,3
8500,2
9000,1
9500,1
10500,2
11000,1
11500,1
12500,5
13000,13
13500,3
15000,1
16500,1
17500,2
21000,1
21500,1
23000,1
26000,1
26500,1
27500,1
28500,1
29500,1
32000,1
33000,1
34500,1
35000,3
35500,1
36000,1
39500,2
41500,1
52500,1
54500,1
59500,1
65500,1
70000,1
71000,1
73000,1
79000,1
86000,1
87000,1
93000,1
94000,3
95500,1
102500,1
105500,1
110500,1
137000,1
138000,2
148000,1
158500,1
192500,1
197000,1
198000,1
217000,1
326500,1
457500,1
464500,1
471500,1
810500,1
1115000,1
1408000,1
1580000,1
1724500,1
1938500,1
3837500,1
4748500,1
5466000,1
```
</details>

## Links

Slack context: 
- https://codedotorg.slack.com/archives/C0T0PNTM3/p1732334823803929
- https://codedotorg.slack.com/archives/C06FELVTV0Q/p1732581328485809

## Testing story

Tested locally by:
1. Generating a string of 10,000 a's with a b at the end
2. Copying and pasting into the AIChat window and verifying the b gets cut off
3. Counting the length of the remaining string and verifying its length is 10,000

Screenshot 2024-11-26 at 8 04 47 AM
Screenshot 2024-11-26 at 8 05 39 AM
Screenshot 2024-11-26 at 8 06 31 AM

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by cnbrenci** [comment]
Do we want to enforce this anywhere server-side? (Like in the AiChatRequest model or aichat_controller start_chat_completion?

**Comment by ebeastlake** [comment]
Yes, @cnbrenci! I thought I would break out server-side into a separate PR (I was thinking DB, but AiChatRequest model or aichat_controller start_chat_completion could go in that PR, too).

**Review by cnbrenci — APPROVED** [review]
🎉

**Comment by fisher-alice** [comment]
> Yes, @cnbrenci! I thought I would break out server-side into a separate PR (I was thinking DB, but AiChatRequest model or aichat_controller start_chat_completion could go in that PR, too).

Just a quick note that chat messages are also stored in AichatEvents (for DB/model). Thanks!

**Review by cat5inthecradle — APPROVED** [review]

**Pull request merged**
