### PR TITLE
Creates a script that drops the pegasus forms_hoc_certificates table.

### PR DESCRIPTION
**Pull request by ashercodeorg**
From `pegasus-reporting-sql` on `production-console`:

```
SELECT COUNT(0) FROM forms_hoc_certificates;
+----------+
| COUNT(0) |
+----------+
|        0 |
+----------+
```

The script has been tested locally, both with and without the existence of the `forms_hoc_certificates` table.

### CODE REVIEW

**Comment by tanyaparker** [comment]
LGTM

**Comment by breville** [comment]
Does certificate customisation continue working with this change?  It'd be interesting to figure out when/why this was created, but seems fine to me if we are sure it's not in use right now.

**Comment by bcjordan** [comment]
If the pegasus tests pass (Circle will run those) then certificate customization still works.

Did a quick search around and couldn't find any reference related to this or its fields. Does this table exist only on production? AFAICT doesn't seem to have been programmatically created, perhaps auto-created from some forms logic?

**Comment by ashercodeorg** [comment]
This table is definitely not related to certificate customization. As bcjordan noted, the table appears to exist only in the production environment (thus the failing tests, as well as why it wasn't noticed and removed much earlier).

**Comment by ashercodeorg** [comment]
Given the table seems to only exist on production environments (not local, staging, or test), should I (a) drop this PR and remove the table manually on `production-daemon` or (b) modify the PR to only drop the table if it exists and remove the `down` action?

**Comment by bcjordan** [comment]
@ashercodeorg (a) sounds slightly better. Given the environment states (and sounds like it must have been added as a one-off or experiment) it would feel OK to remove it as a one-off operation (could maybe fit in `/bin/oneoff` for future reference).

**Comment by ashercodeorg** [comment]
@bcjordan That sounds good, except I'm unsure how to drop the table outside of a migration. Note that [Sequel::Migration](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Migration.html) and [Sequel::Migrator](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Migrator.html) do not seem to offer the necessary functionality. Am I missing a way to do so?

Aside, ActiveRecord seems to offer this functionality via `ActiveRecord::Migration.drop_table(:my_table)`.

**Comment by bcjordan** [comment]
Ah. Would something like https://github.com/code-dot-org/code-dot-org/blob/staging/bin/oneoff/fix-allow-contact-on#L35 using [Sequel's `Sequel.drop_table`](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Database.html#method-i-drop_table) do the trick?

Short of that, even just performing a more manual step in the database and maybe adding a note somewhere about the old table structure and what was done seems fine (e.g. maybe in a `./bin/oneoff/drop-forms_hoc_certificates.txt` / `.md` / `.sql`).

**Comment by ashercodeorg** [comment]
Good call, bcjordan. Let me try that.

**Comment by bcjordan** [comment]
LGTM :+1:

**Pull request merged**
