### PR TITLE
[⭐️Josh S. Wish ⭐️] Section edit option ordering and icon update 

### PR DESCRIPTION
**Pull request by Erin007**
It's not immediately obvious to teachers how to manage section settings, such as editing section details, which includes changing course assignment. Currently this is done via a dropdown opened by clicking on a chevron.  

BEFORE:

Screen Shot 2020-02-06 at 3 46 07 PM

To be more consistent with our own site and externally, we're switching to use a gear icon here as that more clearly indicates settings controls.  Additionally,  I re-ordered the options to bump "Edit Section Details" to the first option. 

AFTER:
Screen Shot 2020-02-06 at 3 41 49 PM

### CODE REVIEW

**Review by maddiedierker — COMMENTED** [review]
beautiful!! it looks like we had a "selected" style for the old chevron icon:

Screen Shot 2020-02-06 at 3 51 35 PM

can we add/update that style to apply to the new gear icon?

**Comment by maddiedierker** [comment]
tagging @fontie715 on this so she can give product input on this

**Comment by Erin007** [comment]
Added different styles for icon when the pop up is open. 

settings-open-style

**Review by maddiedierker — APPROVED** [review]

**Pull request merged**
