### PR TITLE
Add support for processing images through webpack

### PR DESCRIPTION
**Pull request by pcardune**
This PR adds support for importing/requiring images from inside js instead of just referring to "magic" static resource urls.

Here is how this works. Given the following code:

```js
import someImageUrl from './path/to/image/file.png';
const img = new Image();
img.src = someImageUrl;
document.body.appendChild(img);
```

Webpack will automatically generate a javascript module for `./path/to/image/file.png` which has a single export. The single export is just a url to the image file. The url for the image comes in two possible forms:

1. If the image in question is less than 10,000 bytes (this number is configurable), then the url will just be a data url that is embedded in the final javascript bundle produced by webpack.
1. If the image file is larger than 10,000 bytes, then webpack will copy the image to the same output directory where all the javascript bundles get written to. The filename for the image will be an opaque unique hash based on the image file's contents. The resulting url will point to the copied image file, prefixed with the `publicPath` defined in the webpack config (currently `/assets/js/`).

Since our rails assets pipeline already serves the files inside webpack's output directory, this should "just work" -- so long as rails does not change the filename.

Todo:
- [x] determine what the appropriate threshold is for images to be inlined with data urls.
- [x] figure out how to stop rails from renaming the already hashed image files.

### CODE REVIEW

**Comment by pcardune** [comment]
Ok, I discovered that non-digested files end up at `/blockly/js`, so switched to using that for the publicPath option in webpack config. This solves the rails digest problem listed in the todo section above.

**Comment by islemaster** [comment]
It'll be great to have this capability.  Can you describe in more detail how these assets in the apps package get handled by the rails asset pipeline?  Can we test this in a more production-like environment and make sure everything still connects?

**Comment by pcardune** [comment]
So, any rails config that has `config.assets.digest = true` will take all the assets in the paths defined [here](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/config/application.rb#L103) and copy them into the `public/assets/` directory, but renaming them to `<filename>-<hashdigest>.<ext>`. The `public/blockly/` folder is symblinked to the webpack output directory, so basically everything that webpack spits out will get digested. However, even when digesting, the source files are left in place, unchanged.

Everything in the `public` folder gets uploaded to S3, and cloudfront just proxies the requests, so both the digested and non-digested files end up on S3, just in different folders.

The configuration for all of our environments except development have asset digests turned on, so if there is a problem, it should show up in the eyes tests. I also enabled digests locally and confirmed that it worked. So I think we should be pretty well covered by our regular testing pipeline.

**Comment by pcardune** [comment]
ok, I think this is ready for prime time if someone wants to give a thumbs up!

**Pull request merged**
