### PR TITLE
Fix milestone posting for levels with matching - they don't always ha…

### PR DESCRIPTION
**Pull request by mehalshah**
…ve appOptions and appOptions.postMilestone may be unset

### CODE REVIEW

**Comment by joshlory** [comment]
Worth adding a test?

**Comment by wjordan** [comment]
I don't understand this code well enough to say it looks good yet.

I'm wondering whether this will disable completion-tracking completely for the affected non-Blockly level-types, since I recall these may have been tracked prior to this change (and if this change is intended, we might want to at least be confident that disabling them won't cause any unintended side-effects in our analytics pipeline).

**Comment by mehalshah** [comment]
It's worth it, but I'm not sure how yet. I'd need to automate completing a matcher level.

@wjordan - when you say "this change" do you mean my fix, or what the original change was?

**Comment by wjordan** [comment]
@mehalshah I was referring to the original multi/match puzzle types, before any recent changes including this fix. The original puzzle types _may_ (I don't recall for sure) have tracked completion progress through milestone responses, which I don't want us to unintentionally remove here, at least not without confirming it's a behavior change we intend to make.

I don't know what the original changes involved, which is part of why I can't quickly review whether this PR is will cause such a side-effect.

**Comment by wjordan** [comment]
I think I misinterpreted the `x !== false || y` part of the conditional on first glance. So this fix will allow the Ajax post through if the new property is not provided? On my first read, I thought that it would not allow it by default if not provided. This should be enough to allow the original milestone to pass through as expected.

**Comment by mehalshah** [comment]
Abandoning this approach - there's a better way which is in a different PR

**Pull request closed without merging**
