### PR TITLE
Factor out filter component on Curriculum Catalog page

### PR DESCRIPTION
**Pull request by TurnerRiley**
Refactors filtering components into separate file to help make `CurriculumCatalog.jsx` more readable and concise.

### Demo that behavior through clicking and tab-navigation still works as expected
https://github.com/code-dot-org/code-dot-org/assets/56283563/3e20db4f-cf85-46ab-bd89-9c042f2a3e44

## Links
Jira ticket: [here](https://codedotorg.atlassian.net/jira/software/c/projects/ACQ/boards/64?modal=detail&selectedIssue=ACQ-640&assignee=60d62161f65054006980bd71)

## Testing story
Local testing and passing drone build.

## PR Checklist:
- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
> Demo that behavior through clicking and tab-navigation still works as expected

Just curious if this is something we have UI tests for yet, and if not whether that work is tracked?

**Review by davidsbailey — APPROVED** [review]
nice extraction!

**Comment by TurnerRiley** [comment]
> > Demo that behavior through clicking and tab-navigation still works as expected
> 
> Just curious if this is something we have UI tests for yet, and if not whether that work is tracked?

Some of it yes but not the tab navigation. Do we have the tools to test tab navigation?

**Comment by davidsbailey** [comment]
> Some of it yes but not the tab navigation. Do we have the tools to test tab navigation?

oh I see. Yes, some tab navigation can be tested in UI tests:
Screenshot 2023-08-01 at 9 25 58 AM

**Comment by TurnerRiley** [comment]
> > Some of it yes but not the tab navigation. Do we have the tools to test tab navigation?
> 
> oh I see. Yes, some tab navigation can be tested in UI tests: Screenshot 2023-08-01 at 9 25 58 AM

Oh sweet! Here's the Jira task to track that work: https://codedotorg.atlassian.net/browse/ACQ-756?atlOrigin=eyJpIjoiZmViMmZiMTc2NzUwNGM4YmIzNWE1ZjVmOTFmODMwM2UiLCJwIjoiaiJ9

**Pull request merged**
