### PR TITLE
Restyle h1 and h2 to match Pegasus

### PR DESCRIPTION
**Pull request by joshlory**
This is a prerequisite to level markdown cleanup.  Pulling this out to a separate PR so I can resolve any Eyes test failures.

### CODE REVIEW

**Comment by tanyaparker** [comment]
Pictures would be nice. :) But otherwise lgtm.

**Comment by joshlory** [comment]
Good call!  The main differences are:
1. The font size of both headings are slightly smaller to match Pegasus.
2. `<h2>` Has changed from black to teal (to match Pegasus).

## Projects

Before:
projects-before
After:
projects-after

**Edit:** The screenshots below aren't great examples because in each one I've changed the `<h2>` to `<h1>`.  The old `<h1>` was already purple but larger (40px vs. 32px).

## Unit overview

Before:
unit-overview-before
After:
unit-overview-after

## Multi levels

Before:
multi-before
After:
multi-after

## Example of teal `<h2>`

Before:
plc-before
After:
plc-after

**Comment by tanyaparker** [comment]
@breville fyi. I think overall it looks better to have purple headers everywhere for consistency. The one place I like the "black" header is the course overview page, but I think it still works as purple and prefer that it's the same as the rest.

**Comment by tanyaparker** [comment]
I like the size. lgtm!

**Comment by breville** [comment]
yeah, this looks good to me too.  Agreed that the purple header on the course page felt a bit jarring after seeing black.. possibly it started feeling more like a clickable link.. but for consistency's sake it seems like the right thing to do.  nice work.

**Pull request merged**
