### PR TITLE
I18n sync Down & Out 05/21

### PR DESCRIPTION
**Pull request by deploy-code-org**

### CODE REVIEW

**Comment by bethanyaconnor** [comment]
A *lot* of deleted lines here due to the DSL sync.

**Comment by Hamms** [comment]
Wow, no kidding.

Just from glancing through, it looks like everything that was removed is in CSD and CSP, but was indeed translated. We should confirm that we're okay with losing translations from CSD and CSP stuff. @dju90 can you figure out who the stakeholders are for that decision?

**Comment by dju90** [comment]
Are these potentially-lost translations just for CSD and CSP in DSL levels?

**Comment by bethanyaconnor** [comment]
Skimming through a couple of the diffs, it looks like the strings removed are from CSD, CSP, and PD DSL levels.

It's worth noting that we've already lost the translations (with attribution) in Crowdin I believe when I uploaded the new source.

**Comment by bethanyaconnor** [comment]
Based on the decision today at the product sync, I'm going to merge this PR.

**Pull request merged**
