### PR TITLE
Remove browserify-related dependencies

### PR DESCRIPTION
**Pull request by wjordan**
The three dependencies `factor-bundle`, `mochify` and `require-globify` were related to the Browserify toolchain which was replaced by webpack a while ago and so are no longer used.

### CODE REVIEW

**Comment by joshlory** [comment]
image

👏  🏆  🎉

**Comment by islemaster** [comment]
Fabulous!  Let me pull this and try it out.  I wonder how much smaller node_modules got

**Comment by islemaster** [comment]
We should also have someone on OSX pull this branch and try it.  I know it _shouldn't_ make a difference, but still...

**Comment by islemaster** [comment]
`yarn run build:dist` works locally for me without these dependencies.

Metric | Before | After | Notes
--- | --- | --- | ---
node_modules size | 594MB | 575MB |
build/package/js size | 112MB | 112MB | No change detected in any bundles :+1:
Time to `yarn` without node_modules | 28.18s | 27.10s |

**Pull request merged**
