### PR TITLE
Making a new level in levelbuilder for Theater mode

### PR DESCRIPTION
**Pull request by hannahbergam**
This PR creates a new all the things level (Java Lab 4) for Theater mode. It's currently fairly bare, but can be expanded as we add functionality to Theater.

Jira: https://codedotorg.atlassian.net/browse/CSA-438

### CODE REVIEW

**Review by jmkulwik — APPROVED** [review]
🎉

**Review by jmkulwik — COMMENTED** [review]
Does this need to get added to a lesson in order to show up on the allthethings level? /s/allthethings/lessons/44/levels/4

**Comment by molly-moen** [comment]
> Does this need to get added to a lesson in order to show up on the allthethings level? /s/allthethings/lessons/44/levels/4

Yes, it should be added [here](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/config/scripts/allthethings.script#L290)

**Comment by hannahbergam** [comment]
> > Does this need to get added to a lesson in order to show up on the allthethings level? /s/allthethings/lessons/44/levels/4
> 
> Yes, it should be added [here](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/config/scripts/allthethings.script#L290)

Excellent- thank you! Done

**Review by molly-moen — APPROVED** [review]
nice!

**Pull request merged**
