### PR TITLE
[Design System] [Checkbox] Checkbox component updates (implement all possible states of checkbox)

### PR DESCRIPTION
**Pull request by levadadenys**
### [Design System] [Checkbox] Checkbox component updates
* add checkbox disabled state
* add indeterminate state support
* add sizes support (once updated typography is ready we'll need to update label/span sizes)

image
image

## Links
- jira ticket: [Des-287](https://codedotorg.atlassian.net/browse/DES-287?atlOrigin=eyJpIjoiNWIwZGE4OGFmNjU1NGI5OWExYWIxNjI1YjM1OTYxODYiLCJwIjoiaiJ9)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bencodeorg** [comment]
Hey Denys -- are the screenshots here from Figma or Storybook?

**Review by molly-moen — APPROVED** [review]
LGTM!

**Comment by megcrenshaw** [comment]
Exciting to see this progress!

What is the desired behavior between hovering and focus? Here, I'm hovering over the first one while the last one is focused:
image

It also doesn't seem accessible –– the contrast I don't think is high enough for the focus state. Has it been confirmed that this is meeting the accessibility guidelines?

Also, any idea why the indeterminate state isn't showing for me?
image

**Comment by levadadenys** [comment]
> Hey Denys -- are the screenshots here from Figma or Storybook?

Those are screenshots from figma, to se the full scope of work done. You can see examples in storybook as well, but screenshots from it I guess are not as represenative

**Comment by levadadenys** [comment]
> Exciting to see this progress!
> 
> What is the desired behavior between hovering and focus? Here, I'm hovering over the first one while the last one is focused: image
> 
> It also doesn't seem accessible –– the contrast I don't think is high enough for the focus state. Has it been confirmed that this is meeting the accessibility guidelines?
> 
> Also, any idea why the indeterminate state isn't showing for me? image

1. I might not understand the question correctly, but the behaviour here is expected. You can hover and focus different elements, that's how browsers support those state.
2.  Those are made by designers and approved. @markabarrett should be the best person to ask this question.
3. Yeah, that's known issue. We don't have font awesome 6 pro for storybook for some reason. If you try using component in the dashboard where we have font awesome 6 - it should work properly.

**Comment by megcrenshaw** [comment]
> 1. I might not understand the question correctly, but the behaviour here is expected. You can hover and focus different elements, that's how browsers support those state.
> 2. Those are made by designers and approved. @markabarrett should be the best person to ask this question.
> 3. Yeah, that's known issue. We don't have font awesome 6 pro for storybook for some reason. If you try using component in the dashboard where we have font awesome 6 - it should work properly.

Thanks, Denys! Helpful context. I'm going to ask in the #design channel and tag Mark about the contrast for the hover –– looking at this calculator https://www.myndex.com/APCA/?BG=ffffff&TXT=abdfe5&DEV=G4g&BUF=A22 with these level guidelines https://github.com/Myndex/SAPC-APCA/discussions/39 indicate that it's not compliant.

**Review by megcrenshaw — APPROVED** [review]
Asking in the design channel about the focus state: https://codedotorg.slack.com/archives/C0SUN2SSF/p1686590767166309. That can be a follow-up item though.

This looks great!

**Comment by megcrenshaw** [comment]
Ack, Denys, you don't have access to the #design channel! Working on that ... but Denise responded, and they said the focus color can be `$brand_primary_default: #009EB0` instead of`$brand_primary_light: #ABDFE5`. Could you change that here, or create a follow-up PR with that fix?

**Comment by levadadenys** [comment]
> Ack, Denys, you don't have access to the #design channel! Working on that ... but Denise responded, and they said the focus color can be `$brand_primary_default: #009EB0` instead of`$brand_primary_light: #ABDFE5`. Could you change that here, or create a follow-up PR with that fix?

I can update it in this PR. But before that I guess it should be updated in figma and checked for other components is design system (figma and front-end)

**Comment by megcrenshaw** [comment]
> I can update it in this PR. But before that I guess it should be updated in figma and checked for other components is design system (figma and front-end)

I don't think there's harm in going ahead and getting it "right" here –– I believe the design team will update it in Figma, and we can keep an eye out for other components that have this problem. The "new" focus state here matches the button focus state, so the button at least is already good to go.

**Comment by megcrenshaw** [comment]
My fault, Denys. The teal color is now 0093A4, which is "Teal 500." The Figmas have been updated:
https://www.figma.com/file/ahYTsb3I7rsJNW0n2vnXm6/DISCO---Design-System?type=design&node-id=146-3792&t=aU1dFwwKAHsD410F-0

But Molly said she's not sure what the rollout plan is. I'm not sure what all is worth modifying here: I will leave that up to you, Denys.

**Comment by levadadenys** [comment]
> > I can update it in this PR. But before that I guess it should be updated in figma and checked for other components is design system (figma and front-end)
> 
> I don't think there's harm in going ahead and getting it "right" here –– I believe the design team will update it in Figma, and we can keep an eye out for other components that have this problem. The "new" focus state here matches the button focus state, so the button at least is already good to go.

That's part of design system and should be communicated with rebranding (team?) because of high cohesion of components done/in proggress/to be done. The plan is to use design tokens in the future so if one component will have a problem it might mean that all the components will have that problem as well. The button component that we have currently is currently rather part of old system that might look like a new one. (New Button component to be done in the future).

Talking about current problem again - I've talked with Serhii and everything turned out simple enough - it's just my fault, will fix it. We have correct styles in figma already, I've just missed the correct color for focus while developing the component. Thanks for noticing!

**Comment by megcrenshaw** [comment]
> Talking about current problem again - I've talked with Serhii and everything turned out simple enough - it's just my fault, will fix it. We have correct styles in figma already, I've just missed the correct color for focus while developing the component. Thanks for noticing!

Excellent, thank you!

**Pull request merged**
