### PR TITLE
Revert "Revert "Fix user_stats to color bubbles by best result""

### PR DESCRIPTION
**Pull request by balderdash**
Retrying https://github.com/code-dot-org/code-dot-org/pull/10467, but it no longer tries to drop the empty list at the end of `script_level[:ids]`, since I removed that in https://github.com/code-dot-org/code-dot-org/pull/10584.

Also added a UI test for the course progress page in teacher dashboard. Something about teacher dashboard on circle is broken, it tries to hit http://localhost.code.org:3000:3000/v2/sections/1 and errors out. I just disabled the UI test on circle.

### CODE REVIEW

**Comment by Hamms** [comment]
Why was this reverted originally?

**Comment by balderdash** [comment]
It broke progress dot coloring on the course overview page on teacher dashboard.

`script_level[:ids]` from `Script#summarize` used to contain a (usually empty) list of contained_level ids at the end, and I had a fragile workaround for that in the original PR. I removed that list between creating and merging this PR, and I forgot to update this one accordingly. The fix is in https://github.com/code-dot-org/code-dot-org/pull/10903/commits/1811e183eb3d8a5109fb7a4f4d4bae65ddd2eec8.

**Comment by Hamms** [comment]
Makes sense and LGTM!

**Comment by balderdash** [comment]
The set of UI tests that failed in the rerun all passed in the original circle run, so they're just flakes. Merging.

**Pull request merged**
