### PR TITLE
adding alt text to images in middle-school.erb

### PR DESCRIPTION
**Pull request by annaxuphoto**
This PR adds alt text to the images on https://code.org/educate/curriculum/middle-school
I'd love some feedback on whether this alt text is too verbose and should just be an empty string and treated as a decorative image

## Links

Jira (part of the acchack): https://codedotorg.atlassian.net/browse/A11Y-21?atlOrigin=eyJpIjoiYTgwMmQzMjY2NjRjNGI1OTkzMGI0ZDYzNTYwMGMyMjYiLCJwIjoiaiJ9

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by megcrenshaw** [comment]
I'd call these decorative, but happy for pushback.

Regardless, can you put these strings in the i18n pipeline?

**Comment by annaxuphoto** [comment]
I'll just leave them as empty strings then!

**Comment by megcrenshaw** [comment]
@bencodeorg might have beat you to it? https://github.com/code-dot-org/code-dot-org/pull/49469

I'll let y'all fight it out! 😆

**Comment by annaxuphoto** [comment]
ooooooops, closing

**Comment by bencodeorg** [comment]
Cool, will merge the other one!

**Pull request closed without merging**
