### PR TITLE
[Fixes #118526169] Should highlight code after step over operation

### PR DESCRIPTION
**Pull request by joshlory**

### CODE REVIEW

**Comment by cpirich** [comment]
LGTM (but I have some thoughts on a possible better fix.. just a moment)

**Comment by cpirich** [comment]
In this case, you are breaking from the main loop in `executeInterpreter()` and preparing to return because `doneUserLine` is now true. In "max speed" mode, you didn't do code highlighting as you went. So you need to highlight once before you exit. The check at the bottom could also be changed to `(reachedBreak || doneUserLine) && atMaxSpeed`. This may be a better fix because your change doesn't address "step out", which will likely have the same problem as "step over".

**Comment by joshlory** [comment]
Good call, that makes a lot more sense.  Amended the previous commit.

**Comment by joshlory** [comment]
Stale PR, abandoning.

**Pull request closed without merging**
