### PR TITLE
Fix generate missing pdfs

### PR DESCRIPTION
**Pull request by davidsbailey**
In the last PR for generating missing PDFs, we couldn't figure out a way to safely test it. when I went to run it on staging today, it failed with some errors. I've figured out a way to safely test this locally and this PR fixes the errors.

## Testing story

commented out lines which call `Services::CurriculumPdfs.generate_...` or `Services::CurriculumPdfs.upload_...`, then ran the following (output abbreviated): 
```
Dave-MBP:~/src/cdo/dashboard (fix-locate-missing-pdfs *)$ bundle exec rake curriculum_pdfs:generate_missing_pdfs
GetSecretValue: development/cdo/slack_bot_token
Generating missing PDFs for Exploring Websites (from csd2-2017)
Generating missing PDFs for Websites for Expression  (from csd2-2017)
...
Generating missing Script Resources PDF for csd2-2017
Generated all missing PDFs for csd2-2017; uploading results to S3
Generating missing PDFs for Exploring Websites (from csd2-2018)
...
Generating missing Script Overview PDF for time4csdemo
Generating missing Script Resources PDF for time4csdemo
Generated all missing PDFs for time4csdemo; uploading results to S3
Finished generating missing PDFs
```
complete output: [generate-missing-pdfs.txt](https://github.com/code-dot-org/code-dot-org/files/9057769/generate-missing-pdfs.txt)

### CODE REVIEW

**Comment by dmcavoy** [comment]
Thanks for figuring out how to test this. That output seems a little concerning because its generating PDFS for 2017/2018/2019/2020 courses which would have been before we moved over to using this PDF system for lessons so I think something still might not be right here.

**Comment by davidsbailey** [comment]
Output looks better after fixing up the logic. the follwing is after pulling latest staging (which had a successful staging build complete on it) and then doing `rake seed:all` locally:
[updated-pdf-output.txt](https://github.com/code-dot-org/code-dot-org/files/9069185/updated-pdf-output.txt)

**Comment by davidsbailey** [comment]
just to clarify:
* the `Found pdf-enabled script` stuff is more logging I added
* I want to dig a bit more to figure out if I can confirm that the `Generated ...` lines are all actually expected. it still seems odd that so many PDFs are getting generated, so this is not quite ready for review again yet, but I wanted to share in case you had insights

**Comment by davidsbailey** [comment]
ok, this is ready for another review!
* debug output (including which scripts were scanned, even if we found no pdfs to generate):  [pdf-skip-student-debug.txt](https://github.com/code-dot-org/code-dot-org/files/9073460/pdf-skip-student-debug.txt)
* short output (representative of what we'll see when we run this next on staging):
```
Dave-MBP:~/src/cdo/dashboard (fix-locate-missing-pdfs *)$ bundle exec rake curriculum_pdfs:generate_missing_pdfs
GetSecretValue: development/cdo/slack_bot_token
Generating missing Script Overview PDF for hello-world-draft
Generating missing Script Resources PDF for hello-world-draft
Generated all missing PDFs for hello-world-draft; uploading results to S3
Generating missing PDFs for Mini-Project: On-The-Go App (from csd6-projects)
Generating missing PDFs for Project: Human Device Interaction (from csd6-projects)
Generating missing PDFs for Mini-Project: Interactive Art (from csd6-projects)
Generating missing Script Overview PDF for csd6-projects
Generating missing Script Resources PDF for csd6-projects
Generated all missing PDFs for csd6-projects; uploading results to S3
Finished generating missing PDFs
```

To test this, I spot-checked some of the PDFs this output says are missing, and confirmed that they really are missing in production.

**Comment by davidsbailey** [comment]
just noting for later that on home wifi, the process of checking for missing PDFs (excluding loading the rails environment, and without actually generating any PDFs) takes 22 seconds.

**Review by dmcavoy — APPROVED** [review]

**Pull request merged**
