### PR TITLE
Teacher Dashboard: print single student login card

### PR DESCRIPTION
**Pull request by Erin007**
[LP-1320](https://codedotorg.atlassian.net/browse/LP-1320)

Teachers now have the option to print a single student's login card from the Manage Students table. 
print-single-login-picture-3

This includes changes to the login cards:

Picture
Screen Shot 2020-03-19 at 10 09 09 AM

Word
Screen Shot 2020-03-19 at 10 12 03 AM

And a print icon in the print login cards button: 
Screen Shot 2020-03-19 at 10 09 13 AM

### CODE REVIEW

**Comment by Erin007** [comment]
re: commit 1d8ca0e code.org/join redirects to studio.code.org/join, so we should just use the studio prefix.  I thought about using urlHelpers eg. `studio('/join')` but we still need the full studioUrlPrefix since we print that text out in the context of the login card.

**Comment by Erin007** [comment]
> would it also be possible to get rid of the 'pegasusUrlPrefix' property in favor of using a url helper? It seems like it might be nice to do so if thats the case, if we have the time to look into it now.

Yep! ✅ Good catch.

**Review by clareconstantine — APPROVED** [review]
This looks good to me Erin! Thanks for cleaning up the pegasusUrlPrefix props everywhere :)

**Comment by mvkski** [comment]
Yep ty! LGTM as well

**Pull request merged**
