### PR TITLE
Better phantomjs dependency in blockly-core

### PR DESCRIPTION
**Pull request by islemaster**
Instead of depending on Will's custom build of phantomjs>2 (which we've moved away from in other parts of our code), depend on the phantomjs-prebuilt package which has been fairly reliable lately.

Also, invoke phantomjs via `npm bin`/phantomjs instead of the full installed path inside node_modules, which we really shouldn't have any knowledge of (and which can change - as in this particular package change).

### CODE REVIEW

**Comment by islemaster** [comment]
Making this change because @larrypo had some trouble with the `rake build` due to phantomjs in blockly-core not working.  Turns out we were installing and using phantomjs in an outdated and not-best-practices way.  This should make it better.

**Comment by Hamms** [comment]
LGTM! Have you manually verified that `test.sh` still works as intended?

**Comment by islemaster** [comment]
Yep!  Here was my local test:

```
rm -rf node_modules && ./test.sh; npm install && ./test.sh
```

The first invocation gives this expected error and quits:

```
PhantomJS not found.  Run `npm install` from blockly-core first.
```

The second succeeds, running and passing all the blockly-core tests:

```
Blockly-Core tests passed
```

**Comment by islemaster** [comment]
Merged staging - CircleCI build failed due to the S3 upload timing out, which should now be fixed.

**Pull request merged**
