### PR TITLE
Add lesson total time to top of lesson plan

### PR DESCRIPTION
**Pull request by dmcavoy**
Add total duration to top of lesson

Screen Shot 2022-03-09 at 2 04 32 PM

Also remove time for activity sections from Agenda on lesson plan.

Screen Shot 2022-03-10 at 12 08 24 PM

Question: In order for this change to be on the lesson plan pdfs do we need to regenerate all of them? Should we have some way to regenerate all lesson plan pdfs when a UI change is made to the lesson plan?

Doc: https://docs.google.com/document/d/15PIOiSzs3dd1nuu1Y0HUcoT7NksG8AQ_SnZ3-JycXIw/edit

### CODE REVIEW

**Comment by dmcavoy** [comment]
Question: Should we be updating lesson plan pdfs when we make changes to the layout of the lesson plan page?

**Comment by davidsbailey** [comment]
> Question: In order for this change to be on the lesson plan pdfs do we need to regenerate all of them? Should we have some way to regenerate all lesson plan pdfs when a UI change is made to the lesson plan?

Good questions... I'm a bit hesitant to keep making improvements to the existing pdf publishing system when a good workaround exists, since it seems like we might want to overhaul it or replace it soon. it seems like if a ruby command that can be run on levelbuilder like `Script.all.select(&:launched?).each {|s| s.touch}`  (or `...{|s| s.update!(serialized_at: Time.now)` can be called to trigger republishing, then this might be a good thing to record as a future requirement but not necessarily build right now.

**Review by davidsbailey — APPROVED** [review]

**Comment by dmcavoy** [comment]
Ok I will follow up and publish pdfs

**Comment by dmcavoy** [comment]
```
Script.all.select(&:launched?).select{ |script| script.lessons.any?(&:has_lesson_plan)}.each do |s| 
  s.touch
  s.write_script_json
end
```

**Pull request merged**
