### PR TITLE
Update unplugged property on lessons where display_as_unplugged is true

### PR DESCRIPTION
**Pull request by dmcavoy**
Step 2 of https://codedotorg.atlassian.net/browse/PLAT-344. Step 1 was https://github.com/code-dot-org/code-dot-org/pull/39040.

For the Standards Report in the Progress View of the Teacher Dashboard we use a function called display_as_unplugged to check if a lesson is a "unplugged" lesson. It is based on if they use either the old or new version of the unplugged level anywhere in the lesson. As we moved over to LB from CB we have created an unplugged property on a lesson which we want to start using instead since curriculum writers can control it. This PR sets the unplugged property for all lessons that previous would have had display_as_unplugged be true. 

What I did to generate the updates to the script and script_json files. Update all the lessons that would have had display_as_unplugged as true to set unplugged property to true:

```
Lesson.all.each do |lesson|
  if lesson.display_as_unplugged
    lesson.properties[:unplugged] = true
    lesson.save!
  end
end
```

Update the script DSL:

```
Script.all.each do |script|
  script.write_script_dsl
end

Update script_json for migrated scripts:

Script.where("properties -> '$.is_migrated' = ?", true).each do |script|
  script.write_script_json
end
```

## Testing story

I looked through the files to make sure there were only changes to the unplugged property on lessons. In the script_json files there is some reordering of properties which is not ideal but is logged in Jira as something to fix. 

I also picked a handful of script and check the lessons that were marked to make sure they were unplugged lessons.

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
Looks good! In the worst case, what would happen if we get this setting wrong for a particular lesson?

**Comment by dmcavoy** [comment]
@davidsbailey This PR just sets a lesson to have the unplugged which we currently only use for lesson plans so I don't think there is real risk to this PR. The risk comes in https://github.com/code-dot-org/code-dot-org/pull/39039 where if we set something wrong here then when we switch to using unplugged for the standards report, it might mark a lesson as unplugged that we didn't want unplugged or the other way around. Its only CSF 19-20 and CSF 20-21 scripts which are included in that standards report so I can hand check them with the next PR locally.

**Comment by davidsbailey** [comment]
> The risk comes in #39039 where if we set something wrong here then when we switch to using unplugged for the standards report, it might mark a lesson as unplugged that we didn't want unplugged or the other way around. Its only CSF 19-20 and CSF 20-21 scripts which are included in that standards report so I can hand check them with the next PR locally.

OK, on the standards report I see an "update unplugged progress" button, so I assume that in the worst case, if we fail to add `unplugged` to a lesson then progress will fail to update for those lessons, or something like that. double-checking the lessons you mentioned sounds good.

**Comment by dmcavoy** [comment]
I just double checked all the lessons in the next PR which includes this one and everything looked good.

**Pull request merged**
