### PR TITLE
Delete https://code.org/review-hociyskvuwa/index and event review process

### PR DESCRIPTION
**Pull request by kelbyhawn**
Deletes https://code.org/review-hociyskvuwa and related files now that we're removing the events map. I'm not entirely sure what this does (that's one heck of an acronym!), so if anyone has more background or knows of other things we could delete in relation to this please let me know!

## Links
Jira ticket: [ACQ-2221](https://codedotorg.atlassian.net/browse/ACQ-2221)

### CODE REVIEW

**Review by bethanyaconnor — APPROVED** [review]
This page is used to approve special events for Hour of Code. I went down a bit of a rabbit hole to figure out the acronym and the best explanation I found was "security through obscurity" 🫠

**Comment by bethanyaconnor** [comment]
Actually, any chance you could squeeze in removing the `authentication_required!` [function](https://github.com/code-dot-org/code-dot-org/blob/6b184d06fcf504365f0fda5e4f76610de006c2c8/pegasus/helpers.rb#L19-L25) as this is the last remaining use of it? Also could be done as a follow-up, of course.

**Comment by kelbyhawn** [comment]
> Actually, any chance you could squeeze in removing the `authentication_required!` [function](https://github.com/code-dot-org/code-dot-org/blob/6b184d06fcf504365f0fda5e4f76610de006c2c8/pegasus/helpers.rb#L19-L25) as this is the last remaining use of it? Also could be done as a follow-up, of course.

Yes, done! https://github.com/code-dot-org/code-dot-org/pull/60653/commits/7069ed2953322a4fbf1006026bc17e07d66446fa Thanks for finding that.

**Comment by bethanyaconnor** [comment]
Thank you! It was actually Dave I think that noted it in [this ticket](https://codedotorg.atlassian.net/browse/XTEAM-405) a while ago! (Also excited to close that ticket once this PR is merged!)

**Comment by kelbyhawn** [comment]
> Thank you! It was actually Dave I think that noted it in [this ticket](https://codedotorg.atlassian.net/browse/XTEAM-405) a while ago! (Also excited to close that ticket once this PR is merged!)

Just resolved that ticket!

**Pull request merged**
