### PR TITLE
migration for autoplay_enabled

### PR DESCRIPTION
**Pull request by indhu-gunda**
migration for autoplay_enabled and the resulting model updates & schema change

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]

**Comment by dmcavoy** [comment]
Hey @indhu-gunda I'm running the drone run for this right now but noticed that it says there are merge conflicts. Can you pull the latest version of staging and fix those merge conflicts and then push that here?

**Comment by dmcavoy** [comment]
@indhu-gunda Looks like the drone run failed. Want to take a look?

**Comment by indhu-gunda** [comment]
@dmcavoy I merged with upstream/staging but did not have any merge conflicts.

**Comment by dmcavoy** [comment]
@indhu-gunda my bad - looks like I used the wrong branch

**Comment by dmcavoy** [comment]
@indhu-gunda sorry about that earlier. I now have the right branch running through tests and it looks like there are some tests that failed. Check out the results on the linked PR.

**Comment by indhu-gunda** [comment]
@dmcavoy Should work now

**Comment by dmcavoy** [comment]
@indhu-gunda Drone is running now with the updates.

**Comment by dmcavoy** [comment]
Tests passed! Merging!

**Pull request merged**
