### PR TITLE
[i18n] Update static TTS messages

### PR DESCRIPTION
**Pull request by elf-code**
I was poking around at random JIRA/Zendesk tasks - specifically this one https://codedotorg.atlassian.net/browse/P20-49 which led me down this path cause it was about translations and TTS.

I noticed while testing in es-MX that the message "Keep coding! Something's not quite right" wasn't being read aloud. :( I tracked down that that mp3 file wasn't in the S3 bucket and looked for where it should be generated. Which led me to this script. I was scared of running the script (since calls to acapela cost real money) but it turns out that I don't have the credentials to acapela set up so it's fine!

I modified the script to `puts` true or false if the string/mp3/translated TTS was already in S3 giving the output below (of running this script via `./dashboard/scripts/update_tts_i18n_static_messages.rb`). From counting the trues and falses, 31 "static messages" are missing from S3 right now. :(

I don't fully understand the i18n pipeline yet, but it seems like the sync-out script gets run in a weekly crontab on the `i18-dev` server, so this PR updates that script to also check for new static messages.

I would love some help with
- testing this
- is this the right approach?
- anything else to consider??
- do we use pastebin or similar for large outputs like what I just put in the description??

<details>
```
en-US
        jigsaw
                reinfFeedbackMsg
true
        studio
                hoc2015_shareGame
true
                shareGame
true
        common
                emptyBlocksErrorMsg
true
                emptyFunctionBlocksErrorMsg
true
                errorEmptyFunctionBlockModal
true
                errorGenericLintError
true
                errorIncompleteBlockInFunction
true
                errorParamInputUnattached
true
                errorQuestionMarksInNumberField
true
                errorUnusedFunction
true
                errorUnusedParam
true
                extraTopBlocks
true
                hintPromptInline
true
                keepPlaying
true
                levelIncompleteError
true
                missingRecommendedBlocksErrorMsg
true
                missingRequiredBlocksErrorMsg
true
                nestedForSameVariable
true
                nextPuzzle
true
                recommendedBlockContextualHintTitle
true
                shareFailure
true
                tooMuchWork
true
                tryAgain
true
                tryBlocksBelowFeedback
true
        craft
                generatedCodeDescription
true
                reinfFeedbackMsg
true
        maze
                collectorCollectedNothing
true
                collectorCollectedTooMany
true
                didNotCollectEverything
true
                didNotPlantEverywhere
true
                flowerEmptyError
true
                honeycombFullError
true
                insufficientHoney
true
                insufficientNectar
true
                notAtFlowerError
true
                notAtHoneycombError
true
                plantInNonSoilError
true
                uncheckedCloudError
true
                uncheckedPurpleError
true
        turtle
                lengthFeedback
true
                reinfFeedbackMsg
true
                shareDrawing
true
        dance
                danceFeedbackNeedNewDancer
true
                danceFeedbackNoDancers
true
                danceFeedbackNoBackground
true
                danceFeedbackTooManyDancers
true
                danceFeedbackUseSetSize
true
                danceFeedbackUseSetTint
true
                danceFeedbackUseStartMapping
true
                danceFeedbackStartNewMove
true
                danceFeedbackNeedDifferentDance
true
                danceFeedbackNeedEveryTwoMeasures
true
                danceFeedbackNeedMakeANewDancer
true
                danceFeedbackKeyEvent
true
                danceFeedbackDidntPress
true
                danceFeedbackPressedKey
true
                danceFeedbackNeedTwoDancers
true
                danceFeedbackOnlyOneDancerMoved
true
                danceFeedbackNeedLead
false
                danceFeedbackNeedBackup
true
                danceFeedbackSetSize
true
es-ES
        jigsaw
                reinfFeedbackMsg
true
        studio
                hoc2015_shareGame
true
                shareGame
true
        common
                emptyBlocksErrorMsg
true
                emptyFunctionBlocksErrorMsg
true
                errorEmptyFunctionBlockModal
true
                errorGenericLintError
true
                errorIncompleteBlockInFunction
true
                errorParamInputUnattached
true
                errorQuestionMarksInNumberField
true
                errorUnusedFunction
true
                errorUnusedParam
true
                extraTopBlocks
true
                hintPromptInline
true
                keepPlaying
true
                levelIncompleteError
true
                missingRecommendedBlocksErrorMsg
true
                missingRequiredBlocksErrorMsg
true
                nestedForSameVariable
true
                nextPuzzle
true
                recommendedBlockContextualHintTitle
true
                shareFailure
true
                tooMuchWork
true
                tryAgain
true
                tryBlocksBelowFeedback
true
        craft
                generatedCodeDescription
true
                reinfFeedbackMsg
true
        maze
                collectorCollectedNothing
false
                collectorCollectedTooMany
true
                didNotCollectEverything
false
                didNotPlantEverywhere
true
                flowerEmptyError
true
                honeycombFullError
true
                insufficientHoney
false
                insufficientNectar
true
                notAtFlowerError
true
                notAtHoneycombError
true
                plantInNonSoilError
true
                uncheckedCloudError
true
                uncheckedPurpleError
true
        turtle
                lengthFeedback
true
                reinfFeedbackMsg
true
                shareDrawing
true
        dance
                danceFeedbackNeedNewDancer
false
                danceFeedbackNoDancers
true
                danceFeedbackNoBackground
true
                danceFeedbackTooManyDancers
false
                danceFeedbackUseSetSize
false
                danceFeedbackUseSetTint
false
                danceFeedbackUseStartMapping
false
                danceFeedbackStartNewMove
true
                danceFeedbackNeedDifferentDance
false
                danceFeedbackNeedEveryTwoMeasures
false
                danceFeedbackNeedMakeANewDancer
true
                danceFeedbackKeyEvent
true
                danceFeedbackDidntPress
true
                danceFeedbackPressedKey
true
                danceFeedbackNeedTwoDancers
false
                danceFeedbackOnlyOneDancerMoved
true
                danceFeedbackNeedLead
false
                danceFeedbackNeedBackup
false
                danceFeedbackSetSize
false
es-MX
        jigsaw
                reinfFeedbackMsg
true
        studio
                hoc2015_shareGame
true
                shareGame
true
        common
                emptyBlocksErrorMsg
true
                emptyFunctionBlocksErrorMsg
true
                errorEmptyFunctionBlockModal
true
                errorGenericLintError
true
                errorIncompleteBlockInFunction
true
                errorParamInputUnattached
true
                errorQuestionMarksInNumberField
true
                errorUnusedFunction
true
                errorUnusedParam
true
                extraTopBlocks
true
                hintPromptInline
false
                keepPlaying
true
                levelIncompleteError
false
                missingRecommendedBlocksErrorMsg
true
                missingRequiredBlocksErrorMsg
true
                nestedForSameVariable
true
                nextPuzzle
true
                recommendedBlockContextualHintTitle
false
                shareFailure
true
                tooMuchWork
true
                tryAgain
true
                tryBlocksBelowFeedback
true
        craft
                generatedCodeDescription
true
                reinfFeedbackMsg
true
        maze
                collectorCollectedNothing
true
                collectorCollectedTooMany
false
                didNotCollectEverything
true
                didNotPlantEverywhere
false
                flowerEmptyError
true
                honeycombFullError
true
                insufficientHoney
true
                insufficientNectar
true
                notAtFlowerError
true
                notAtHoneycombError
true
                plantInNonSoilError
true
                uncheckedCloudError
true
                uncheckedPurpleError
true
        turtle
                lengthFeedback
true
                reinfFeedbackMsg
true
                shareDrawing
true
        dance
                danceFeedbackNeedNewDancer
true
                danceFeedbackNoDancers
true
                danceFeedbackNoBackground
true
                danceFeedbackTooManyDancers
true
                danceFeedbackUseSetSize
true
                danceFeedbackUseSetTint
true
                danceFeedbackUseStartMapping
true
                danceFeedbackStartNewMove
true
                danceFeedbackNeedDifferentDance
true
                danceFeedbackNeedEveryTwoMeasures
true
                danceFeedbackNeedMakeANewDancer
true
                danceFeedbackKeyEvent
true
                danceFeedbackDidntPress
true
                danceFeedbackPressedKey
true
                danceFeedbackNeedTwoDancers
true
                danceFeedbackOnlyOneDancerMoved
true
                danceFeedbackNeedLead
false
                danceFeedbackNeedBackup
true
                danceFeedbackSetSize
true
it-IT
        jigsaw
                reinfFeedbackMsg
true
        studio
                hoc2015_shareGame
true
                shareGame
true
        common
                emptyBlocksErrorMsg
true
                emptyFunctionBlocksErrorMsg
true
                errorEmptyFunctionBlockModal
true
                errorGenericLintError
true
                errorIncompleteBlockInFunction
true
                errorParamInputUnattached
true
                errorQuestionMarksInNumberField
true
                errorUnusedFunction
true
                errorUnusedParam
false
                extraTopBlocks
true
                hintPromptInline
true
                keepPlaying
true
                levelIncompleteError
false
                missingRecommendedBlocksErrorMsg
true
                missingRequiredBlocksErrorMsg
true
                nestedForSameVariable
true
                nextPuzzle
true
                recommendedBlockContextualHintTitle
true
                shareFailure
true
                tooMuchWork
true
                tryAgain
true
                tryBlocksBelowFeedback
true
        craft
                generatedCodeDescription
true
                reinfFeedbackMsg
true
        maze
                collectorCollectedNothing
true
                collectorCollectedTooMany
false
                didNotCollectEverything
true
                didNotPlantEverywhere
true
                flowerEmptyError
true
                honeycombFullError
true
                insufficientHoney
true
                insufficientNectar
true
                notAtFlowerError
true
                notAtHoneycombError
true
                plantInNonSoilError
true
                uncheckedCloudError
true
                uncheckedPurpleError
true
        turtle
                lengthFeedback
true
                reinfFeedbackMsg
true
                shareDrawing
true
        dance
                danceFeedbackNeedNewDancer
true
                danceFeedbackNoDancers
true
                danceFeedbackNoBackground
true
                danceFeedbackTooManyDancers
true
                danceFeedbackUseSetSize
true
                danceFeedbackUseSetTint
true
                danceFeedbackUseStartMapping
true
                danceFeedbackStartNewMove
true
                danceFeedbackNeedDifferentDance
true
                danceFeedbackNeedEveryTwoMeasures
true
                danceFeedbackNeedMakeANewDancer
true
                danceFeedbackKeyEvent
true
                danceFeedbackDidntPress
true
                danceFeedbackPressedKey
true
                danceFeedbackNeedTwoDancers
true
                danceFeedbackOnlyOneDancerMoved
true
                danceFeedbackNeedLead
false
                danceFeedbackNeedBackup
true
                danceFeedbackSetSize
true
pt-BR
        jigsaw
                reinfFeedbackMsg
false
        studio
                hoc2015_shareGame
true
                shareGame
true
        common
                emptyBlocksErrorMsg
true
                emptyFunctionBlocksErrorMsg
true
                errorEmptyFunctionBlockModal
true
                errorGenericLintError
true
                errorIncompleteBlockInFunction
true
                errorParamInputUnattached
true
                errorQuestionMarksInNumberField
true
                errorUnusedFunction
true
                errorUnusedParam
true
                extraTopBlocks
true
                hintPromptInline
true
                keepPlaying
false
                levelIncompleteError
true
                missingRecommendedBlocksErrorMsg
true
                missingRequiredBlocksErrorMsg
true
                nestedForSameVariable
true
                nextPuzzle
true
                recommendedBlockContextualHintTitle
true
                shareFailure
true
                tooMuchWork
true
                tryAgain
true
                tryBlocksBelowFeedback
true
        craft
                generatedCodeDescription
true
                reinfFeedbackMsg
true
        maze
                collectorCollectedNothing
true
                collectorCollectedTooMany
true
                didNotCollectEverything
true
                didNotPlantEverywhere
true
                flowerEmptyError
true
                honeycombFullError
true
                insufficientHoney
true
                insufficientNectar
true
                notAtFlowerError
true
                notAtHoneycombError
true
                plantInNonSoilError
true
                uncheckedCloudError
true
                uncheckedPurpleError
true
        turtle
                lengthFeedback
true
                reinfFeedbackMsg
true
                shareDrawing
true
        dance
                danceFeedbackNeedNewDancer
true
                danceFeedbackNoDancers
true
                danceFeedbackNoBackground
false
                danceFeedbackTooManyDancers
true
                danceFeedbackUseSetSize
true
                danceFeedbackUseSetTint
true
                danceFeedbackUseStartMapping
true
                danceFeedbackStartNewMove
true
                danceFeedbackNeedDifferentDance
true
                danceFeedbackNeedEveryTwoMeasures
true
                danceFeedbackNeedMakeANewDancer
true
                danceFeedbackKeyEvent
false
                danceFeedbackDidntPress
true
                danceFeedbackPressedKey
true
                danceFeedbackNeedTwoDancers
true
                danceFeedbackOnlyOneDancerMoved
true
                danceFeedbackNeedLead
false
                danceFeedbackNeedBackup
true
                danceFeedbackSetSize
false
```
</details>

### CODE REVIEW

**Review by daynew — APPROVED** [review]
> testing this

The easiest thing might be to temporarily take over the `i18n-dev` server, checkout this branch, and run the script. You could also borrow the Acapela credentials from the i18n-dev server.

> is this the right approach?

I think so. There is even a TODO in `update_tts_i18n_static_messages.rb` to do this. Perhaps you should delete that TODO as well? You could also ask Elijah about this work.

> do we use pastebin or similar for large outputs like what I just put in the description??

What you did is fine to me. Pastebin would be fine as well. I don't know if there is a standard.

**Comment by carl-codeorg** [comment]
> do we use pastebin or similar for large outputs like what I just put in the description??

Since we're in Github, you can use a [gist](https://gist.github.com/)

**Comment by elf-code** [comment]
Ran this script as a one-off on the `i18n-dev` server
`ubuntu@i18n-dev:~/code-dot-org$ ./dashboard/scripts/update_tts_i18n_static_messages.rb `
The output is pretty standard - what I have above without any of the true/falses.

Then when running the level I was looking at https://studio.code.org/s/coursec-2021/lessons/13/levels/2 - the TTS in es_MX is now playable.

I was nervous about checking out my branch on the i18n-dev server since it has some pending changes already, which I figure is part of that big i18n diagram that I don't understand yet.

```
ubuntu@i18n-dev:~/code-dot-org$ git checkout origin/elf-first-feature-branch 
error: Your local changes to the following files would be overwritten by checkout:
	bin/i18n/sync-out.rb
	dashboard/config/scripts_json/pl-csd-summer-day1.script_json
	dashboard/config/scripts_json/pl-csd-summer-day2.script_json
	dashboard/config/scripts_json/pl-csd-summer-day3.script_json
	dashboard/config/scripts_json/pl-csd-summer-day4.script_json
	dashboard/config/scripts_json/pl-csd-summer-day5.script_json
	dashboard/config/scripts_json/self-paced-pl-csd5-2023.script_json
Please commit your changes or stash them before you switch branches.
Aborting
```

Planning to remove the TODO and then commit this!

**Comment by wilkie** [comment]
Looks great! Already sweeping up a few cobwebs in our i18n scripting. Love this.

Also a lesser known feature which is to embed HTML `<details>` blocks for inline log dumps etc.

```
<details>
  <summary>Really long log</summary>

  ```blahhhhhhhhhhhhhhh```
</details>
```

Gives you:

<details>
  <summary>Really long log</summary>

```
blahhhhhhhhhhhhhhh
```
</details>

**Pull request merged**
