### PR TITLE
remove file that shouldn't have been committed

### PR DESCRIPTION
**Pull request by Bjvanminnen**
This file shouldn't have made it into the repo. This removes it from the repo. After this commit makes it to LB we may want to manually add the file back to that machine (at which point it will be gitignored).

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Another option, to make sure we don't forget to add the file back to levelbuilder, would be to cherry-pick this commit and the gitignore commit to LB immediately, and add back the file.

**Comment by ashercodeorg** [comment]
Not knowing the purpose of the file, I'm not willing to stamp its removal. Reassigning to Will.

**Comment by Bjvanminnen** [comment]
Note: This is just removing from the repo (where it didnt exist until I accidentally committed it from levelbuilder). It will result in the file being removed from the LB machine once this commit makes it there, which we may not want. I can add it back manually once that happens.

**Comment by Bjvanminnen** [comment]
I'm going to merge this as soon as DTP finishes so that I can focus on getting out the next DTT/DTP. I've also given myself a slack reminder to add the file back to levelbuilder once the commit makes it there.

**Pull request merged**
