### PR TITLE
Cleanup script published state

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Cleans up the published_state of scripts within unit groups. There were four general cases:
- Scripts that accidentally got their published_state set to their unit group's. This was fixed in #42469.
- Scripts that had a published_state of `preview` when their unit group has a published_state of `stable`. I figured this was just an oversight and set the published_state of the scripts in those cases to `nil`.
- One course uses alternate_scripts: csp-2017. When I removed the published_state of that script (`csp3-a`), it caused UI tests to fail. I think we should consider getting rid of alternate_scripts as it's hardly being used.
- time4cs relies on a couple of their scripts being in the pilot state when the rest are `stable`. There are only two scripts and this would be a pretty big behavior shift, I decided to leave those as is. 3950532c45dd95043d74b6d6ee6dd9475f7e6f35 reverts changes to those scripts.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
> * One course uses alternate_scripts: csp-2017. When I removed the published_state of that script (`csp3-a`), it caused UI tests to fail. I think we should consider getting rid of alternate_scripts as it's hardly being used.

+💯 . here's where we are with that: https://codedotorg.atlassian.net/browse/PLAT-1180

**Comment by davidsbailey** [comment]
> time4cs relies on a couple of their scripts being in the pilot state when the rest are stable.

@tess323 do you know if we're relying on the time4cs scripts that were set up for the broward partnership any more?

**Review by davidsbailey — APPROVED** [review]
LGTM! Thanks for cleaning up!

**Comment by tess323** [comment]
@davidsbailey i do not.  Want me to ask around edprograms?

**Comment by davidsbailey** [comment]
> @davidsbailey i do not. Want me to ask around edprograms?

@tess323 yes please. it seems like we're starting to make special cases to support this material, so I'd like to avoid the extra eng burden if possible.

**Comment by dmcavoy** [comment]
@tess323 @davidsbailey the time4cs scripts were from when broward was going to start building stuff on our system. @fontie715 would be the person to check with on that. I think they are not being used and were never finished because we did not end up following through on that partnership when they lost funding

**Comment by davidsbailey** [comment]
I thought the same thing, but apparently Amy, Emily and Mike have been talking with them more recently: https://codedotorg.slack.com/archives/CFGAVL2CA/p1628694002024500

**Comment by tess323** [comment]
@davidsbailey - I will check with Amanda next week and then run it by Emily as well. At a high level can you give me a sense of what we are special casing and what we would do if we were no longer supporting the script?

**Comment by davidsbailey** [comment]
good question @tess323 . @bethanyaconnor , what's the user-visible difference if you were to set the published state to nil for the broward units in question?

**Comment by bethanyaconnor** [comment]
> what's the user-visible difference if you were to set the published state to nil for the broward units in question?

They would be accessible by anyone because they unit group has the `beta` published state. I didn't want to move the script from a pilot to not a pilot without checking around first.

In general, it would be nice to clean these two scripts up but having two scripts having mismatched published states doesn't seem like the end of the world to me.

**Comment by tess323** [comment]
sounds good -- thank you!

**Pull request merged**
