### PR TITLE
Rubocop lint fixes

### PR DESCRIPTION
**Pull request by joshlory**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
LGTM.

**Comment by joshlory** [comment]
@ashercodeorg I added a few more.

**Comment by ashercodeorg** [comment]
LGTM. FWIW, my preference would be for one PR per type of change. Much easier to verify correctness, see what is happening, make sure nothing else is happening, etc.

**Comment by joshlory** [comment]
Can you verify commit-by-commit?  One PR per lint change feels heavy-handed IMHO.

**Comment by ashercodeorg** [comment]
This PR is fine, feel welcome to submit as-is. Mostly, I'm expressing a preference (based on past experience) that paying the upfront (heavy-handed) cost of small and simple PRs is cheaper than paying the cost of regression hunting and/or looking at code etymology.

If the team culture disagrees, I'm certainly willing to go with the flow.

**Pull request merged**
