### PR TITLE
small tweaks to cloudformation and chef setup

### PR DESCRIPTION
**Pull request by wjordan**
rename lambda => lambda_fn
remove code-studio build step
bootstrap the npm builds on a new instance

### CODE REVIEW

**Comment by wjordan** [comment]
@Bjvanminnen can you just confirm that we no longer need to build `code-studio` in our new-instance setup, since it was removed?

**Comment by Bjvanminnen** [comment]
We shouldn't. The one thing you might want to watch for is if we're creating our new instance from an old image, the old image may have some code-studio files sitting around on it. The new code-studio build steps have logic to clean that cruft up.

**Comment by wjordan** [comment]
Thanks for the heads up. I'll test this install process on an adhoc instance before merging.

**Comment by wjordan** [comment]
adhoc instance looked good

**Pull request merged**
