### PR TITLE
Incubator page - add AI rubrics pilot

### PR DESCRIPTION
**Pull request by cearachew**
## Warning!!

The [AP CSP Create Performance Task](https://apcentral.collegeboard.org/courses/ap-computer-science-principles/exam) is in progress. The most critical dates are from April 3 - April 30, 2024. Please consider any risk introduced by this PR that could affect our students taking AP CSP. Code.org students taking AP CSP primarily use App Lab for their Create Task, however a small percent use Game Lab. Carefully consider whether your change has any risk of alterering, changing, or breaking anything in these two labs. Even small changes, such as a different button color, are considered significant during this time period. Reach out to the Student Learning team or Curriculum team for more details.

Adds the AI rubrics pilot information to the incubator page. Description includes a link to the edweek article, button goes to the AI rubrics info/sign-up page.

Screenshot 2024-04-19 at 10 41 10 AM

## Links

Jira ticket: https://codedotorg.atlassian.net/browse/AITT-577

## Testing story

Tested locally, all links work and go to where they're expected to. 

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
just curious @tess323 if we want this to go out with any kind of metrics to see who we get through the incubator page?

**Comment by tess323** [comment]
There is a chat going on in the PM channel about instrumenting the incubator so I would maybe wait for that comprehensive view.  But I can offer us to do that work.

**Review by davidsbailey — APPROVED** [review]
code changes look good. @tess323 can you please clarify whether the PM discussion should block this PR?

**Comment by tess323** [comment]
is not blocking

**Pull request merged**
