### PR TITLE
Improve assume identity

### PR DESCRIPTION
**Pull request by larrypo**
This adds an "Assumed Identity" warning whenever an admin assumes the identity of a user.
Code changes include:
- Whitelisting cookie to be changed (http_cache.rb)
- css for new tag (application.scss)
- Add cookie when assuming identity (admin_users_controller.rb)
- Show warning when cookie is present (application.html.haml)
- Remove cookie when logging out (devise.rb)
image

### CODE REVIEW

**Comment by wjordan** [comment]
Unless I'm mistaken we should be able to use the existing Rails session-cookie for this feature, which would make the code a bit simpler:

admin_users_controller.rb:
```rb
session[:assumed_identity] = true
```

application.html.haml:
```haml
if session[:assumed_identity]
  #assumed_identity_tag= 'Assumed identity'
```

**Review by Hamms — COMMENTED** [review]
Is it intentional that this will overlap with the existing environment indicator?

image

**Comment by dju90** [comment]
In the [spec](https://docs.google.com/document/d/1-CQQKGnAYppLeshQT2M2PBr75yTs_pWBSYdhMPSi2RM/edit#), this was the option that was most popular. Do people frequently assume identity in non-prod environments?

**Comment by larrypo** [comment]
Will: Done, thanks for the suggestion.

Any other comments? Should I try to show both "Assumed identity" and "development" tags?

**Comment by dju90** [comment]
@wjordan @Hamms Do people frequently assume identity in non-prod environments?

**Comment by Hamms** [comment]
I doubt it, but I don't know for sure. Regardless, if this is meant to supplant the environment tag then I'd strongly prefer it use same element as the tag, and if the two are meant to work independently then they should be able to do so.

**Comment by larrypo** [comment]
How about this? This will now show the environment in the assume identity tag if it's not prod.

Note that the environment tag can be dismissed by clicking on it, but the assume identity tag (with or without environment) can't be dismissed. This is intentional.

I feel this is reaching the level of complexity that a unit test would be appropriate, but I don't know where that would be written. Any suggestions?

Screen Shot 2019-09-27 at 2 26 00 PM

**Review by Hamms — COMMENTED** [review]
This looks great! Agreed about the need for a unit test. `dashboard/test/controllers/application_controller_test.rb`, maybe?

**Comment by larrypo** [comment]
Unit tests added, PTAL.

**Review by Hamms — APPROVED** [review]
LGTM!

**Comment by larrypo** [comment]
I've added some small changes to fix https://codedotorg.atlassian.net/browse/FND-733, which I have verified manually and with a unit test change. I think this is ready to merge.

**Pull request merged**
