### PR TITLE
Reapply ActionView in Sinatra

### PR DESCRIPTION
**Pull request by Hamms**
Reverts https://github.com/code-dot-org/code-dot-org/pull/33228, reapplying https://github.com/code-dot-org/code-dot-org/pull/33192

The last PR caused a template rendering error on production, because some views rely on being able to access the `locals` hash directly. Rather than try to identify all views with this dependency and update them, I chose to [make the locals hash accessible](https://github.com/code-dot-org/code-dot-org/commit/aa8b14650884089738369826c5761e30eb6e4d11). Tracking longer-term work [here](https://codedotorg.atlassian.net/browse/FND-1033) to look through all the templates and remove this functionality.

I also chose not to add a UI test for the routes that failed, because they are in the process of being deprecated. Relevant slack thread [here](https://codedotorg.slack.com/archives/CC4U03GA0/p1582231497051600).

## Links

- [honeybadger error](https://app.honeybadger.io/projects/34365/faults/61013904)

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by Hamms** [comment]
Given that there are likely more routes not being tested which could conceal rendering errors (even though no others were triggered during the three or so hours this was previously live), I was considering deploying this behind a DCDO flag. Open to feedback on whether or not that seems necessary!

**Comment by wjordan** [comment]
> Given that there are likely more routes not being tested which could conceal rendering errors

This sounds like the critical problem here- I think it will continue to be difficult to make maintainable changes to our system moving forward without addressing this issue up front.

Should we look into tracking down as many of these un-tested routes/features individually and at least schedule/track work for adding test coverage for each, to make development more reliable in general moving forward? Or at least track down the specific one that triggered this specific error, to make sure it's covered moving forward?

To sketch out how exactly adding coverage to these un-tested Pegasus routes would work- we already have an integration test that enumerates every Pegasus page, but it notably doesn't cover 'splat' routes like [`/pd-workshop-survey/*](https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/pd-workshop-survey/splat.haml). It should be possible to extend the integration test to build and maintain a set of 'splat fixtures' that specify test inputs to provide to these dynamic routes for coverage. We don't need to add fixtures for every splat up front, but once a harness is built it should be simple enough to add new splat-fixtures when we encounter new pages we want to add to test coverage.

**Review by wjordan — APPROVED** [review]
See my note above on adding extra test coverage, but if we're confident enough with the added fixes and it continues to pass the existing tests I'm fine with trying this again.

**Review by islemaster — APPROVED** [review]
:+1: Since the regressed view is already scheduled for removal, this seems good.  Will, the integration tests on splat-paths is a very cool idea; I'll ask PLC to explore that, if Elijah doesn't take the bait first. :grin: But given my understanding of the priority of this work, I think we can move forward with this change.

**Comment by Hamms** [comment]
I'm fully in support of improving our pegasus coverage. I added a work item [here](https://codedotorg.atlassian.net/browse/PLC-772) to track this, and I'll see if we can get some time on a foundations sprint to address this.

**Pull request merged**
