### PR TITLE
Remove dashboard/README.md.

### PR DESCRIPTION
**Pull request by ashercodeorg**
The file is sufficiently redundant and out of date that it seems more helpful gone than in its current state.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Tanya, if you think it is worth investing time to clean up its contents, let me know, I'm happy to do so. But I feel like the information it contains is already documented elsewhere.

**Comment by islemaster** [comment]
Please fix references to the dashboard README in [CONTRIBUTING.md](https://github.com/code-dot-org/code-dot-org/blob/staging/CONTRIBUTING.md#code-style) and [the apps README](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/README.md#contributing) while you're at it.

**Comment by tanyaparker** [comment]
Thanks for reminder, Brad. lgtm to remove

**Comment by ashercodeorg** [comment]
Fixed references.

**Pull request merged**
