### PR TITLE
Upcase Us in 'Help Us' nav bar link on pegasus and dashboard

### PR DESCRIPTION
**Pull request by Erin007**
Quick fix to upcase the U in "Help Us"  link on Pegasus and Dashboard navbar. 

BEFORE: 
before

AFTER:
after

### CODE REVIEW

**Comment by breville** [comment]
Oh, I actually did this on purpose to match the downcasing we did in the hamburger.  Is it consistent there?

**Comment by Erin007** [comment]
It's "Help Us" with an capital U in the hamburger. Is that what we want?

screen shot 2017-05-19 at 3 06 41 pm

**Comment by breville** [comment]
@tanyaparker should make the call on what's desired.  I thought it looked a bit odd to be capitalising Us but no strong opinion.  At any rate, the dashboard header might need to be changed as well since it's currently "Help us".

**Comment by tanyaparker** [comment]
I think it's weird that it's the only nav link that isn't capitalized, comparing to Project Gallery and Professional Learning. I think all the nav links should be capitalized because they're like titles, titles of the page they lead to.

**Pull request merged**
