### PR TITLE
Allow user to override the default username for logging into gateway …

### PR DESCRIPTION
**Pull request by mehalshah**
…when running the script. Useful if your gateway username isn't the username on the box you are running on

### CODE REVIEW

**Comment by philbogle** [comment]
LGTM

**Comment by trevorb** [comment]
lgtm

**Comment by laurelfan** [comment]
Would it be possible to respect the users .ssh configuration by default (eg: 
http://stackoverflow.com/questions/10197559/ssh-configuration-override-the-default-username)

People who don't have the same username on gateway as their laptops probably have this anyway? Or should? :)

**Comment by mehalshah** [comment]
I'll look into laurel's suggestion seperately

**Pull request merged**
