### PR TITLE
Changes /admin/level_completions to display data (with a warning) if the data from Google Analytics is sampled rather than throwing an exception.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by wjordan** [comment]
Code looks good.

What does "numbers are not scaled" mean? I thought Google Analytics did scale the numbers when returning sampled data, is that only correct in the web interface?

**Comment by wjordan** [comment]
And if so, we might want to scale the numbers ourselves based on the additional data returned through the API- otherwise, the sampled numbers returned wouldn't be meaningful at all if they're just an unknown percentage of the total.

**Comment by ashercodeorg** [comment]
Changed the wording associated with the sampled data warning.

Note that I can't quite tell whether the returned data is scaled from the documentation at https://developers.google.com/analytics/devguides/reporting/core/v3/reference. But I'm happy to believe it is scaled, if you know it to be so.

**Comment by wjordan** [comment]
:+1:

**Pull request merged**
