### PR TITLE
bootstrap react in applab.

### PR DESCRIPTION
**Pull request by davidsbailey**
requires re-running one of the following two commands:
~/cdo$ rake install apps
~/cdo/apps$ npm install reactify 

EDIT: Mocha tests are passing.

### CODE REVIEW

**Comment by wjordan** [comment]
Glad you got this up and running! Looks like a nice, simple example that should make a good test case for this integration. A couple notes:

- Global installation of `reactify` via `npm install -g` (whether manually or via changes to the Rakefile) shouldn't be needed. Once you add an npm package dependency to `package.json` (which I see you did already), you can just run `npm install` (which is the usual command you need to run after adding any new npm dependency) and the dependency will be installed local to the project folder, which is the preferred approach.

- The current mocha tests won't be able to make use of the reactify transform, because they are currently run through node js rather than through browserify. The work I and Brent have been doing on refactoring the `/apps` test framework should make it possible to make use of browserify features such as this reactify transform in tests moving forward. This should be okay temporarily, as long as the current tests still pass- if this PR breaks existing tests as well, we'd want to either find a workaround before merging or hold off on this until the test-framework changes are finished.

**Comment by davidsbailey** [comment]
Thanks Will!  Should the -g option be removed from "npm install -g grunt-cli" as well?

Mocha tests pass. I'm psyched for the js pipeline work to land!

It's worth noting that while JSX syntax is normally allowed in JS files, I've intentionally avoided it here to make mochaTest and jshint pass. Once reactify is part of our pipeline, there is a JSHint + JSX integration that could allow us to relax this restriction.

**Comment by davidsbailey** [comment]
To give some background on why mocha tests pass, there are applab mocha tests today, but they do not cover design mode. This is why JSX files can be conditionally ignored in tests.

**Comment by wjordan** [comment]
you don't need to run `npm install reactify` at all, either manually or in the `Rakefile` script - the regular `npm install` (nothing afterwards) will install all of the project's local dependencies listed in `package.json`.

`grunt-cli` is the one exception, it's the only dependency that currently needs to be installed globally due to the way `grunt` is invoked directly from the command-line in our current build scripts and documented developer workflow. It's actually possible to run `grunt` without installing it globally too, either by invoking it indirectly through [`npm scripts`](https://docs.npmjs.com/misc/scripts) or via an explicit local path (e.g. \`npm bin\`/grunt). Changing this is something else I was looking into in the refactor branch.

**Pull request merged**
