### PR TITLE
Dance AI: Fix delayed foreground effects in live preview

### PR DESCRIPTION
**Pull request by sanchitmalhotra126**
Fix for delayed foreground effects in live preview appearing in the AI modal. This is done by creating a separate static preview-metadata.json file that has known working values for the "centroid" property. At runtime, this static file is updated with the current song's artist and title, so that the "text" background effect still renders with the correct information.

To create the preview metadata file, I just copied an existing metadata file ('Synthesize') and replaced the centroid value with the default of 6500. I also removed the URL, artist, and title and set the BPM to a default of 120.

After update (the displayed FG effects were the ones that were previously appearing delayed):

https://github.com/code-dot-org/code-dot-org/assets/85528507/8e259747-7613-430f-885b-2743b333a752

After update with text BG effect:

https://github.com/code-dot-org/code-dot-org/assets/85528507/ddbac617-adf5-4d3f-8534-3ecdd095e31e

Before (notice the delay before the rainbows appear):

https://github.com/code-dot-org/code-dot-org/assets/85528507/ce29b0c2-9eb7-4e27-a278-83a0cb7c4750

## Links

https://trello.com/c/JBnm3rAe

## Testing story

Tested locally with a variety of FG/BG effect combinations

### CODE REVIEW

**Review by breville — APPROVED** [review]
This looks great.  It's an elegant approach and good to see it didn't take too much code.

I think it's right to bake `preview-metadata.json` into the build, but any concerns about its size?

**Comment by fisher-alice** [comment]
> This looks great. It's an elegant approach and good to see it didn't take too much code.
> 
+1
> I think it's right to bake `preview-metadata.json` into the build, but any concerns about its size?
>
Could we reduce the size of the file? I don't think we need the preview animation to be longer than say 10-15 sec? And curious what happens if the user views for a longer duration than the metadata provides? Or we could loop?

**Comment by sanchitmalhotra126** [comment]
> I think it's right to bake `preview-metadata.json` into the build, but any concerns about its size?

@breville good call. I think we can trim some of the unused data (ex. 'peaks') and could reduce the duration like Alice suggested below, but some things to note (below).

> Could we reduce the size of the file? I don't think we need the preview animation to be longer than say 10-15 sec? And curious what happens if the user views for a longer duration than the metadata provides? Or we could loop?

@fisher-alice good suggestion and good question. I tried limiting the duration of the song metadata and it does work fine, but certain background effects that animate based off song data (usually "isPeak") will just stop changing. FWIW, this happens in actual playback as well, but most of the time validation will stop the song early so we never hit that stage.

Example (here I've limited the metadata to 10s - notice that the background stops changing after that):

https://github.com/code-dot-org/code-dot-org/assets/85528507/5db35461-d82e-43f3-adb5-b48154186074

10-15s sounds like a good limit anyway though. Trimming to 15s reduces the file size from 94KB -> 56KB.

**Comment by breville** [comment]
> 10-15s sounds like a good limit anyway though. 

Could we loop the metadata while the visual effect is continuous, so that we never stop the elements from changing?  (Say by retrieving metadata based on current time modulo the loop duration?)

No worries if not easy, but I can imagine an advantage in having these backgrounds continuing to change over a longer period of time, especially for users who step away and come back.  In a classroom it could make for a cool kiosk/attract mode (to borrow arcade game parlance), keeping our UI alive all the time.

**Comment by breville** [comment]
> 10-15s sounds like a good limit anyway though. 

Could we loop the metadata while the visual effect is continuous, so that we never stop the elements from changing?  (Say by retrieving metadata based on current time modulo the loop duration?)

No worries if not easy, but I can imagine an advantage in having these backgrounds continuing to change over a longer period of time, especially for users who step away and come back.  In a classroom it could make for a cool kiosk/attract mode (to borrow arcade game parlance), keeping our UI alive all the time.

**Comment by sanchitmalhotra126** [comment]
> Could we loop the metadata while the visual effect is continuous, so that we never stop the elements from changing? (Say by retrieving metadata based on current time modulo the loop duration?)
> 
> No worries if not easy, but I can imagine an advantage in having these backgrounds continuing to change over a longer period of time, especially for users who step away and come back. In a classroom it could make for a cool kiosk/attract mode (to borrow arcade game parlance), keeping our UI alive all the time.

I'll give that a shot! Should be easy enough but need to look into how dance-party manages the event list

**Comment by sanchitmalhotra126** [comment]
> Could we loop the metadata while the visual effect is continuous, so that we never stop the elements from changing? (Say by retrieving metadata based on current time modulo the loop duration?)

@breville good suggestion! I've implemented this the dance-party layer and will follow up with a separate PR. This allowed me to shorten the metadata duration to 4s which shrinks the file to 17KB.

**Pull request merged**
