### PR TITLE
Public Key Cryptography: Use Virtualized Select

### PR DESCRIPTION
**Pull request by islemaster**
Uses [`react-virtualized-select`](https://bvaughn.github.io/react-virtualized-select/) for dropdowns in the crypto widget instead of regular `<select>` tags.  This is primarily for performance reasons - turns out even React gets bogged down when asked to add ten thousand `<option>` elements to a `<select>`.  The 'virtualized' part means only options scrolled into view are actually in the DOM, saving React a bunch of work.  As an added bonus, the search behavior of these dropdowns is better than the native one - a nice feature for our use case.

The messiest part of this change was that it wants CSS from `react-virtualized`, `react-select`, and `react-virtualized-select` to all be on the page.  I'm pulling the needed stylesheets out of their respective npm packages and into the apps package, then symlinking them to the PKC directory and including them as a one-off for this widget.  If we want to use them elsewhere, we should probably work out how to import them as partials into our application.css.

### CODE REVIEW

**Comment by Hamms** [comment]
:+1: for searchable `<select>`s!

It's not clear to me why we can't just `import` the css like they do in [the provided example](https://github.com/bvaughn/react-virtualized-select/#simple-example)

**Comment by islemaster** [comment]
Doing so would require [a couple of loaders](https://webpack.github.io/docs/stylesheets.html) that we haven't added to webpack in our build process.  I think we could go ahead and do this, but maybe there's a cost to adding another way to drop CSS onto the page?

**Comment by islemaster** [comment]
PTAL - updated to be more like the example, using webpack to load CSS directly.

Note that pinning react-addons-shallow-compare, is part of the base for this PR, and is being merged separately in https://github.com/code-dot-org/code-dot-org/pull/10186.

**Comment by islemaster** [comment]
(New eyes baseline accepted, circle re-run and passing!)

**Comment by Hamms** [comment]
L(great)TM!

**Pull request merged**
