### PR TITLE
Update the UI to accommodate updated teaches_cs values

### PR DESCRIPTION
**Pull request by TurnerRiley**
This PR updates the [code.org/yourschool](https://code.org/yourschool) MapBox UI to remove the "maybe" `teaches_cs` value and accommodate "excluded" and "unknown" `teaches_cs` values.

#### Previous legend
LEGEND_OLD

#### New legend
new_map

## (unchanged) "Yes" values (both "Yes" and "Historical Yes")
"Yes" and "historical yes" remain unchanged!

#### Previous "Yes"
old_YES

#### New "Yes" (unchanged)
new_YES

#### Previous "Historical Yes"
old_teaches_cs_HISTORICAL_YES

#### New "Historical Yes" (unchanged)
new_HISTORICAL_YES

## (mostly unchanged) "No" values (both "No" and "Historical No")
The behavior of "no" and "historical no" is unchanged, but the text was updated to remove "limited" phrasing.

#### Previous "No"
old_NO

#### New "No"
new_NO

#### Previous "Historical No"
old_HISTORICAL_NO

#### New "Historical No"
new_HISTORICAL_NO

## (removed) "Maybe" values (both "Maybe" and "Historical Maybe")
As per [the spec](https://docs.google.com/document/d/1ZcvnXAUfOwnmWdS8Z8JwwYDdHWTF6CrCWCmpgiKlw4U/edit#heading=h.rizng6chl91e), we are removing the values of "Maybe" and "Historical Maybe." This is already reflected in [the data](https://s3.console.aws.amazon.com/s3/object/cdo-census?region=us-east-1&prefix=access-report-data-files-2023/final_csv/final_csv_2023_09_19.csv) which contains no entries of "M" or "HM."

#### Previously
old_MAYBE

#### New
new_NOT_MAYBE

## (new) "Unknown" values (replacing "No data")
As per [the spec](https://docs.google.com/document/d/1ZcvnXAUfOwnmWdS8Z8JwwYDdHWTF6CrCWCmpgiKlw4U/edit#heading=h.rizng6chl91e), "inconclusive" and "no data" are no longer options, and "unknown" is taking its place along with the white color. Because of this, and because the map defaults to white without an explicit "yes", "no", or "excluded" (just like how "no data" was treated), I don't believe any change is needed to support "unknown" values.

#### Previously
old_NO_DATA

#### New (visually unchanged but this school is now marked as "unknown")
NEW_UNKNOWN

## (new) "Excluded" values
A new "excluded" `teaches_cs` value was added so any school with that value will be filtered out from being shown on the map.

#### Previously
old_teaches_cs_SHOULD_BE_EXCLUDED

#### New (now that school's point on the map is filtered out)
new_teaches_cs_EXCLUDED

## Links
Jira ticket: [here](https://codedotorg.atlassian.net/jira/software/c/projects/ACQ/boards/64?modal=detail&selectedIssue=ACQ-798&assignee=60d62161f65054006980bd71)
Spec: [here](https://docs.google.com/document/d/1ZcvnXAUfOwnmWdS8Z8JwwYDdHWTF6CrCWCmpgiKlw4U/edit#heading=h.rizng6chl91e)

## Testing story
I spun up an adhoc with this PR's changes and the changes from the [update_census_mapbox cronjob PR](https://github.com/code-dot-org/code-dot-org/pull/53972) so that I could test the UI changes on the updated map, then I found schools in the new year's data of each type of value to compare to the previous year's map.

## Follow-up work
My plan was to merge this PR and the script that updates the map close together so that the discrepencies in the map are minimized. For the most part it should be safe as the changes are being made to schools that have conflicted data, no data, or are excluded (meaning most will be shown as a white dot until the script runs and many will be excluded/recategorized).

## PR Checklist:
- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
Hi Turner, it looks like this PR goes a step further than the jira description of adding support for "excluded" and "unknown", by also removing the support for "maybe". this means the map will be out of sync for a period of time between when this PR ships and the restored census cronjob runs. I think this is probably ok, as long as you merge the cronjob PR close to when you merge this PR.

**Comment by TurnerRiley** [comment]
> Hi Turner, it looks like this PR goes a step further than the jira description of adding support for "excluded" and "unknown", by also removing the support for "maybe". this means the map will be out of sync for a period of time between when this PR ships and the restored census cronjob runs. I think this is probably ok, as long as you merge the cronjob PR close to when you merge this PR.

Yes my plan was to merge them close together! The visual difference for the "maybes" will be that before the other PR's script is run, they will be listed as "No data" (which many of them will be after the script anyways) with a couple discrepencies that would be resolved shortly by running the script. I will add that to my "Followup work"

**Comment by TurnerRiley** [comment]
> Hi Turner, it looks like this PR goes a step further than the jira description of adding support for "excluded" and "unknown", by also removing the support for "maybe". this means the map will be out of sync for a period of time between when this PR ships and the restored census cronjob runs. I think this is probably ok, as long as you merge the cronjob PR close to when you merge this PR.

Does this PR look good to ship then assuming it'll be merged close together with the update_census_mapbox script and I'll run that script once they're in production?

**Review by davidsbailey — APPROVED** [review]
yes, sorry, I had meant to approve!

**Pull request merged**
