### PR TITLE
Disables violations of Style/IndenticalConditionalBranches and reenables the check.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Looking at the offense below, I think the current implementation is much more readable than the suggestion. That said, I think there is value in reenabling the check, so I'm choosing to disable the check for these lines. Feel welcome to express an alternate opinion.

Offenses:

aws/build_and_mail_log:45:7: C: Style/IdenticalConditionalBranches: Move HipChat.developers commit_url, color: 'gray', message_format: 'text' out of the conditional.
      HipChat.developers commit_url, color: 'gray', message_format: 'text'
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aws/build_and_mail_log:53:7: C: Style/IdenticalConditionalBranches: Move HipChat.developers commit_url, color: 'gray', message_format: 'text' out of the conditional.
      HipChat.developers commit_url, color: 'gray', message_format: 'text'
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### CODE REVIEW

**Comment by joshlory** [comment]
I agree the recommended "fix" is less readable.  I'm not sure this rule provides much value if 1) it doesn't detect any other issues in our codebase and 2) the issue it does detect doesn't improve readability.

**Comment by joshlory** [comment]
Maybe this is an issue that should be caught by CR instead?  I like the idea of the cop, but in practice I don't see it catching many issues.  It looks like the rule only does exact matching, and only for the last lines of the conditional.

**Comment by ashercodeorg** [comment]
Though code review should catch violations, it should also catch most other violations that we are enforcing. :)

My very slight preference is to enable the cop via this PR, considering its removal if we find ourselves needing to disable it elsewhere. Otherwise, I'm happy to drop this PR and add this check to the list of checks we do not intend to enforce in the future.

**Comment by joshlory** [comment]
Yeah good call.  My only thought was that CR might have more nuance to say which was more readable.

My vote would be to either "fix" the violation and enable it globally (without the `rubocop:disable`), or move the rule to `.rubocop.yml`.  What do you think?

**Comment by ashercodeorg** [comment]
Let me ponder this a bit.

**Comment by ashercodeorg** [comment]
Going to disable the rule by moving it to .rubocop.yml.

Since this PR now has merge conflicts, I'm going to close this PR and disable the rule in another PR (referencing the discussion here in the new PR).

**Pull request closed without merging**
