### PR TITLE
Allow emojis in teacher feedback

### PR DESCRIPTION
**Pull request by drew-beckmen**
This PR contains a migration that modifies the `teacher_feedbacks` table to allow for emojis in teacher comments.
 

image

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by jmkulwik — APPROVED** [review]
🎉 Looks great!

**Comment by jmkulwik** [comment]
@drew-beckmen - Just going through old PRs from the team. Is this one ready to merge?

**Comment by drew-beckmen** [comment]
> @drew-beckmen - Just going through old PRs from the team. Is this one ready to merge?

Yes, it is. I'll resolve the merge conflict and push again.

**Comment by drew-beckmen** [comment]
Closing this PR - refer to updated PR with test here #38358

**Pull request closed without merging**
