### PR TITLE
Remove the Levels Fixture

### PR DESCRIPTION
**Pull request by Hamms**
Remove the Levels Fixture and the code that generates it. Also remove the code which generates the fixture as well as the Level Concept Difficulties feature (which depends on the code that generates the Levels Fixture, and on which no tests depend).

Follow-up to [these pull requests](https://github.com/code-dot-org/code-dot-org/issues?q=label%3Afixtures-to-factories+is%3Aclosed) updating various tests and test helpers to use factories rather than fixtures for test Level objects.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
flame-thrower

Very exciting to see this go! 

Is there any other info you can capture from what you've learned from working on this to help whoever works on it next? in particular, I am wondering:
1. do all tests pass after regenerating fixtures?
2. any ideas for how much work remains to remove other fixtures, in particular the script levels fixture (58K lines)?

no worries if you don't have these exact answers, but anything you can share here while it's fresh in your mind could be helpful.

**Comment by Hamms** [comment]
I'm not sure I took any real learnings away from this one: it was just a slog. There were something like 400 tests that needed to be fixed. Granted, the vast majority of them were covered by a few major changes (manually seeding all project template levels, filling out the fixture-provided scripts, etc), but that still left quite a few tests (about a dozen pull requests worth!) that needed to be manually updated. Just a matter of working through them one at a time, taking the time at each one to understand what the test is actually testing, and what subset of the fixture-provided data it's relying on is part of what it actually cares about so it can be recreated in a more targeted way through factories. So an interesting slog, but a slog nonetheless.

1. I'll open up a PR to double-check, but I confirmed locally that regenerating fixtures doesn't produce any changes more significant than timestamp updates so I'm not expecting anything.
2. According to [this trial PR](https://github.com/code-dot-org/code-dot-org/pull/42386), removing the scripts fixture will require fixing up 149 failures and 426 errors in our unit tests, so I'd expect it to be about comparable in required work to this one.

**Review by davidsbailey — APPROVED** [review]
Sounds great, thanks for these notes!

**Comment by Hamms** [comment]
According to https://github.com/code-dot-org/code-dot-org/pull/42725, there are 3 failures and 0 errors after regenerating fixtures. However, it looks like those exact same failures manifest if we regenerate fixtures _without_ removing the levels fixture first, so I'm not going to consider that blocking for this PR, merely a reminder that we'll be much better off with all the rest of them removed, too.

**Pull request merged**
