### PR TITLE
Fix application serializer when school is not found

### PR DESCRIPTION
**Pull request by hacodeorg**
https://app.honeybadger.io/projects/3240/faults/48339046#notice-comments

- How tested:
Test ApplicationSerializer class and other classes using it.
```
bin/rails test test/serializers/api/v1/pd/application_serializer_test.rb
bin/rails test test/controllers/api/v1/pd/applications_controller_test.rb
bin/rails test test/controllers/pd/application/principal_approval_application_controller_test.rb
```

### CODE REVIEW

**Review by clareconstantine — COMMENTED** [review]
Could you add a test for this case to `application_serializer_test.rb`?

**Comment by hacodeorg** [comment]
Do you mean an unit test for the `return` line or an integration test for the general case that application serializer shouldn't raise error even when application data has invalid fields? 

> Could you add a test for this case to `application_serializer_test.rb`?

**Comment by clareconstantine** [comment]
I was thinking just a unit test

**Comment by hacodeorg** [comment]
I add an unit test that could have caught this honeybadger error. It is also extensible to cover other invalid data cases that we can think of. (Right now I don't find any obvious invalid data to add to it beside of invalid school code.)

**Review by clareconstantine — APPROVED** [review]

**Pull request merged**
