### PR TITLE
[i18n] update crontab -lc -> -l -c

### PR DESCRIPTION
**Pull request by elf-code**
As the i18n / Platform point person, I'm looking at i18n sync and it seems like the cronjob still isn't running

Looked at  https://github.com/code-dot-org/code-dot-org/pull/52369 and it seems like maybe the `l` and `c` flags need to be separated (since `c` takes an argument).

🤷  seems like a YOLO update, but it's broken right now, so we've only got upside.

### CODE REVIEW

**Review by nicklathe — APPROVED** [review]
Thanks, this is the exact fix I was going to recommend (or get around to doing)!

**Review by mgc1194 — APPROVED** [review]
🤞

**Comment by elf-code** [comment]
trying to get this to work locally on the i18n-dev server before checking it in

**Comment by elf-code** [comment]
went with a different update (in addition to this)

**Pull request closed without merging**
