### PR TITLE
Add Algebra course A and CSD unit 3 lesson plan links

### PR DESCRIPTION
**Pull request by mrjoshida**
Add lesson plan links to algebraa and csd3 scripts

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Though I'm not too familiar with this, I assume these scripts should exist in all environments before we start referencing them. Right now, I see `algebraa` on production, though not `csd3`. Can this wait for `csd3` to hit production before merging this with staging?

**Comment by mrjoshida** [comment]
Dani just put together `csd3` today - was hoping to send out to reviewers tomorrow with links to lesson plans included. If it's a problem we can wait to merge this and just email the lesson plan url separately.

**Comment by ashercodeorg** [comment]
If it isn't urgent, I vote for merging tomorrow AM. At this point, it won't be included in today's DTP. So there is no downside and lots of upside in waiting until tomorrow. LGTM as of tomorrow AM.

**Comment by mrjoshida** [comment]
Works for me, thanks.

**Pull request merged**
