### PR TITLE
Allow selecting text from the ai-diff container

### PR DESCRIPTION
**Pull request by cearachew**
This adds a handle to the draggable element of the aiDiff container so it can only be dragged by clicking the header. This allows selecting text inside the container body for copy/paste

https://github.com/user-attachments/assets/87d4a3be-8743-4a35-8238-d33ca0ac7ca9

Based on Tess and Molly's go-ahead, also making this change for the AI Rubrics container.

## Links

https://codedotorg.atlassian.net/browse/AITT-812
https://codedotorg.atlassian.net/browse/AITT-807

## Testing story

Updated the rubrics container test to drag by the header handle. 

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by cearachew** [comment]
@tess323 @MollyPeredo - adding a handle turned out to be super easy once I actually found the docs on how to do it, do you want me to make this change for the AI Rubrics container too so teachers can copy text from the rubric? IMO it seems intuitive to only move it from the header

**Review by etaderhold — APPROVED** [review]
That was easy!

**Comment by MollyPeredo** [comment]
@cearachew Whooo, this is great! Final decision is Tess's, but I say yes to adding this to the Rubric container too.

**Comment by tess323** [comment]
ship it 😃

**Review by etaderhold — APPROVED** [review]
🚢

**Pull request merged**
