### PR TITLE
Re-enable brace-style rule, fixing violations in dashboard.

### PR DESCRIPTION
**Pull request by islemaster**
#7650 broke our staging build because, unbeknownst to me, we started linting dashboard JavaScript using our ESLint config as well and I hadn't fixed violations there.

In the process I also learned that we're not linting dashboard JavaScript anywhere _before_ staging.  In #7660 I'd like to try enabling Hound ESLint support, so that these sorts of mistakes don't hit staging.

### CODE REVIEW

**Comment by islemaster** [comment]
FYI @breville I think I'm touching some of your code here, want to make sure you're aware of / okay with us enabling this style rule.

**Comment by breville** [comment]
Thanks for the heads up & fix.  Looks good, though I braced myself for the worst.

**Comment by islemaster** [comment]
:laughing:

**Comment by bcjordan** [comment]
LGTM!

**Pull request merged**
