### PR TITLE
migration: make objectives.key column non-null and backfill as needed

### PR DESCRIPTION
**Pull request by davidsbailey**
Follow-up from https://github.com/code-dot-org/code-dot-org/pull/38223#discussion_r543715668 . backfills development and adhoc environment with unique keys. omits test environment because (unlike resources) there are no objectives in our test fixtures, so most people probably won't have any of these.

## Testing story

ran the migration forward, backward and forward again in my local environment. 600+ objectives were backfilled with unique keys. I also verified that there are no objectives in my local test db, or on the `test` or `levelbuilder` machines. This gives a pretty good indication that the migration will succeed in all environments.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by bethanyaconnor — COMMENTED** [review]
Are you missing a migration?

**Comment by davidsbailey** [comment]
> Are you missing a migration?

😆  yup. good thing we do code reviews :-)

**Review by bethanyaconnor — APPROVED** [review]

**Comment by davidsbailey** [comment]
all unit tests and both of our UI tests have passed in drone, so I'm calling this good!

**Comment by dmcavoy** [comment]
Could have been a great moment to see if the diff check on drone runs was working :)

**Comment by davidsbailey** [comment]
> Could have been a great moment to see if the diff check on drone runs was working :)

I'm afraid it might not be. the first two drone runs on this PR should have resulted in a schema diff, but it ran to completion without reporting the problem. not sure why 🤷

**Comment by davidsbailey** [comment]
@bethanyaconnor heads up that I think this broke the import script:
```
bundler: failed to load command: ./bin/oneoff/import_unit_details.rb (./bin/oneoff/import_unit_details.rb)
ActiveRecord::NotNullViolation: Mysql2::Error: Field 'key' doesn't have a default value: INSERT INTO `objectives` (`properties`, `lesson_id`, `created_at`, `updated_at`) VALUES ('{\"description\":\"Reframe a sequence of steps as an encoded program\"}', 7146, '2020-12-17 02:55:23', '2020-12-17 02:55:23')
  /Users/dsb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
  ...
  /Users/dsb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/associations/builder/association.rb:116:in `objectives='
  /Users/dsb/src/cdo/lib/cdo/lesson_import_helper.rb:42:in `update_lesson'
  /Users/dsb/src/cdo/bin/oneoff/import_unit_details.rb:105:in `block (2 levels) in main'
  /Users/dsb/src/cdo/bin/oneoff/import_unit_details.rb:104:in `each'
  /Users/dsb/src/cdo/bin/oneoff/import_unit_details.rb:104:in `block in main'
  /Users/dsb/src/cdo/bin/oneoff/import_unit_details.rb:82:in `each'
  /Users/dsb/src/cdo/bin/oneoff/import_unit_details.rb:82:in `main'
  /Users/dsb/src/cdo/bin/oneoff/import_unit_details.rb:329:in `<top (required)>'
```
I will try to fix it next time I'm online.

**Comment by davidsbailey** [comment]
fix prepped in https://github.com/code-dot-org/code-dot-org/pull/38305

**Pull request merged**
