### PR TITLE
use cacheable thumbnails when sharing to twitter

### PR DESCRIPTION
**Pull request by davidsbailey**

### CODE REVIEW

**Comment by davidsbailey** [comment]
This is important for scalability because the `/v3/files-public` api allows cloudfront to cache for 1 hour, while the `/v3/files` api will allow every view of this thumbnail to make our frontend servers hit s3.

I put the brakes on this change in yesterday because I misunderstood the impact -- this only affects social (twitter and facebook) image urls.

**Comment by Erin007** [comment]
Better to make this change the way you have it or use the helper https://github.com/code-dot-org/code-dot-org/blob/0387e4493fbbd12330fe9fbe2cee222d42c57e17/shared/middleware/helpers/storage_apps.rb#L121 on the url where we use it for sharing: https://github.com/code-dot-org/code-dot-org/blob/65ffe431e181a54c9d4c4671eac8c3506b72ea81/dashboard/app/views/shared/_sharing_meta_tags.html.haml#L30?  I don't really know if it matters just curious.

**Comment by Erin007** [comment]
And worth doing for Artist shares too?

**Comment by davidsbailey** [comment]
Actually, @erin007, do you know how to repro the original problem in the wild? If so, would you be able to check and see if Twitter is exposing our link to the world, or whether they are just serving their own cached copy of it?

Will respond to other feedback when I'm at my laptop.

**Comment by davidsbailey** [comment]
> Better to make this change the way you have it or use the helper

Good question. We really shouldn't be constructing this URL at all -- we should be retrieving it from the database, since the format could change at any point (switch to jpeg, start including s3 version id, etc). But since we are constructing it, it seems simpler to just construct it how we want it with `files-public`, rather than using the helper url whose purpose is to operate on existing urls.

> And worth doing for Artist shares too?

That would require changing the API, because `/v3/files-public` is effectively only implemented for thumbnails:
https://github.com/code-dot-org/code-dot-org/blob/6269b4bd42aba22c90b47d3061ff148a635ee69b/shared/middleware/files_api.rb#L865-L869
this could be a good post-hoc follow up item, though.

**Comment by davidsbailey** [comment]
closing because twitter appears to be reading our urls once and then caching them for us. for example:
* https://twitter.com/islemaster/status/1068000711969886208
* https://pbs.twimg.com/card_img/1067970133153304576/93Km2vAc?format=jpg&name=386x202

**Pull request closed without merging**
