### PR TITLE
Renames readme.txt to README.md.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Note that the file contains markdown within it already.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Brad: Do you know if the images in this directory (this directory) should be included in our "Proprietary Materials" list in our LICENSE (https://github.com/code-dot-org/code-dot-org/blob/staging/LICENSE)?

**Comment by islemaster** [comment]
I suspect yes, since the [README.md at apps/assets](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/assets/README.md) suggests that it contains source files that correspond to final assets in apps/static, and apps/static is listed in the license.

Rename LGTM.

**Comment by ashercodeorg** [comment]
Note that I'm ignoring the ci/circleci failure.

**Comment by ashercodeorg** [comment]
In another PR, I'll add this directory (probably also other directories, after I hear back on another email thread) to the list of "Proprietary Materials" directories.

**Pull request merged**
