### PR TITLE
Download new about.md translations

### PR DESCRIPTION
**Pull request by Hamms**
And add a simple script for easy future downloading.

### CODE REVIEW

**Comment by breville** [comment]
Do we need English placeholders for every locale?  The pegasus router will fallback to a default English file if it doesn't find a translation for the current locale.

**Comment by Hamms** [comment]
This is what I was asking about in the #i18n room today; do we want to only sync a subset of languages that we know we want, or just sync 'em all

**Comment by tanyaparker** [comment]
Right now they look like unnecessary placeholders because they're all in English, but soon translations will trickle in. So we'll have many files with partial translations and we want to show all of the translations that we have. We don't want to wait until the whole file is translated before showing it. I think it's more work than it's worth to have to check if at least 1 string in each file is translated before storing it in this folder. I'm okay with having all the files in there, even if it seems like a lot of English.

**Comment by joshlory** [comment]
Will we get in trouble with the case conflict in pegasus/sites.v3/code.org/i18n/public/international/about.es-MX.md vs https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/sites.v3/code.org/public/international/about.es-mx.md?

I think we generally use lowercase URLs on the site.

**Comment by Hamms** [comment]
Note that the url will just be code.org/international/about, and we do indeed want the locale uppercased, since that matches the format of `request.locale`

**Comment by breville** [comment]
That said, we could downcase if we prefer to keep our filenames all lowercase...

**Pull request merged**
