### PR TITLE
Creates a script to fix (DB) and reindex (SOLR) buggy forms.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This is expected to modify 4532 rows.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
PR is now ready for review. Thanks!

**Comment by ashercodeorg** [comment]
Ping Tanya. CircleCI failure is spurious (unrelated).

**Comment by tanyaparker** [comment]
Sorry for delay. LGTM too, thank you so much!

**Comment by ashercodeorg** [comment]
This script has been run on `production-console`. Let me know if it should be run on other environments (e.g., staging, test, or levelbuilder).

**Comment by tanyaparker** [comment]
Great! I don't _need_ it run on other environments since there is enough good data for testing but if it's better for consistency/cleanup it needs to be run on staging too.

**Comment by ashercodeorg** [comment]
Also run on staging.

**Comment by tanyaparker** [comment]
Thank you!

**Pull request merged**
