### PR TITLE
Funometer css change

### PR DESCRIPTION
**Pull request by jeremydstone**
change heart hover color to be brighter red to look clicked - by zoe

### CODE REVIEW

**Comment by breville** [comment]
Screenshot in PR would be handy for future reference.  At any rate, LGTM!

**Comment by jeremydstone** [comment]
For posterity: old color of selected heart when hovered over (dark, almost doesn't appear clicked after you click on it)
image

**Comment by jeremydstone** [comment]
New color of selected heart when hovered over: brighter red, more clearly selected
image

**Comment by breville** [comment]
Nice!

**Comment by breville** [comment]
Also this should be live on staging now.

**Pull request merged**
