### PR TITLE
don't show any dialog on syntax errors in applab script levels

### PR DESCRIPTION
**Pull request by davidsbailey**
previously we were getting dialogs like this if you ran an applab program on a script level with a syntax error in it:
screen shot 2017-03-07 at 4 35 51 pm

this PR makes those pesky dialogs go away, and skips playing the failure sound too.

### CODE REVIEW

**Comment by davidsbailey** [comment]
@poorvasingal please chime in if you'd like the failure sound to still be played.

**Comment by poorvasingal** [comment]
Oh no.  Let's please not play a sound, haha.

**Comment by Bjvanminnen** [comment]
This seems reasonable to me. Looked at the other apps where we do this (gamelab, playlab). Playlab does call onPuzzleComplete, but I think that probably makes sense for it. Gamelab does not, but has a TODO asking if we should. Might be a good time to remove that TODO :)

**Comment by davidsbailey** [comment]
@Bjvanminnen please take another look as I've made some substantial changes to deal with test failures.

This broke applab level tests containing applab syntax errors because they were relying on `Applab.onPuzzleComplete` being called in response to the error in order to trigger the `done` callback. It didn't _look_ like the broken tests were relying on this because they were specifying the usual:
```js
      runBeforeClick: function () {
        tickWrapper.runOnAppTick(Applab, 2, function () {
          Applab.onPuzzleComplete();
        });
      },
```
However that code was never getting executed because we were (and still are) killing the tick loop before the `runOnAppTick` callback could be called.

The solution I'm proposing to this replaces the above block with a new optional `onExecutionError` callback:
```js
      onExecutionError: function () {
        // Trigger the custom validator and done callback
        Applab.onPuzzleComplete();
      },
```
and then does any necessary validation in the `customValidator`. We can't just do the validation in `onExecutionError` without introducing more hacks because we would need access to `assert` in that context.

**Pull request merged**
