### PR TITLE
Updated VisualizationResizeBarTest to be compatible with Enzyme 3

### PR DESCRIPTION
**Pull request by jmkulwik**
https://codedotorg.atlassian.net/browse/STAR-185 : Update *labs tests to be compatible with Enzyme v3.

### CODE REVIEW

**Comment by jmkulwik** [comment]
Will wait to merge this PR until the upgrade to enzyme 3

**Comment by epeach** [comment]
Why did you decide to wait to merge this PR?

**Comment by jmkulwik** [comment]
> Why did you decide to wait to merge this PR?

Because it relies on a feature that only exists in Enzyme 3 - calling "instance" on a sub-component

**Comment by epeach** [comment]
Sounds good. Do we have a task tracked to remind us that these need to be merged together?

**Review by epeach — APPROVED** [review]

**Comment by jmkulwik** [comment]
> Sounds good. Do we have a task tracked to remind us that these need to be merged together?

This is all a sub-task of https://codedotorg.atlassian.net/browse/STAR-489 (upgrade react to 15.6)
I'll make sure these PRs get added in the notes for the task.

**Pull request merged**
