### PR TITLE
Make trackEvent importable

### PR DESCRIPTION
**Pull request by islemaster**
The maker `SetupChecklist` tests were failing in isolation (and occasionally in a full run?) after https://github.com/code-dot-org/code-dot-org/pull/15085 because they depended on `window.trackEvent` being available and apparently in tests it isn't guaranteed to be around.  My best guess for why this would ever work at all is that we [add a stub to window in `testUtils.setExternalGlobals()`](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/test/util/testUtils.js#L51) so as long as that was called prior to this test in the suite it would pass.

My solution is to hide the global dependency away in an importable helper that can gracefully no-op if `window.trackEvent` hasn't been set up.  I then went ahead and made sure we use this helper everywhere in apps, so we only depend on this global in one place.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Nice cleanup!

I wonder if we actually want this to fail in non-test environments though if `trackEvent` is undefined.   We could use something like `IN_UNIT_TEST` or `process.env.NODE_ENV` to gate on whether it's allowed to be undefined.

**Comment by islemaster** [comment]
Is there a benefit to having this fail in non-test environments?  We don't expect a user-bad if, for example, somebody's VPN blocks Google Analytics (mine does, but it seems to fail gracefully).  This seems very fire-and-forget, and I'm not sure we want to risk a JS error if something goes wrong.

**Comment by Bjvanminnen** [comment]
My worry was that we change something like which set of partials we include in places, such that we end up not defining trackEvent in places where we expect it. Things fail silently, and we dont realize that we're no longer tracking the events we think we are.

**Comment by islemaster** [comment]
:angry: Circle keeps failing UI tests, on a different test every time I run it on this branch.  99% sure this has nothing to do with my changes, but I'll keep re-running...

**Comment by islemaster** [comment]
:rage: Merging in spite of not being able to pass tests - all failures seem to be unrelated.

**Pull request merged**
