### PR TITLE
Remove unused variables from JS.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by Hamms** [comment]
Looks like @tanyaparker is the one who [originally added the if statement](https://github.com/code-dot-org/code-dot-org/commit/a61d58e42678b757d55290596a2c646d8a8a02ac) ... Tanya, do you have some context for why this was necessary?

**Comment by tanyaparker** [comment]
This was some legacy code. I broke the page (there were a lot of js errors)
after I removed it, so I added it back in.

On Fri, Jul 8, 2016 at 2:02 PM, Elijah Hamovitz notifications@github.com
wrote:

> Looks like @tanyaparker https://github.com/tanyaparker is the one who originally
> added the if statement
> https://github.com/code-dot-org/code-dot-org/commit/a61d58e42678b757d55290596a2c646d8a8a02ac
> ... Tanya, do you have some context for why this was necessary?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/code-dot-org/code-dot-org/pull/9399#issuecomment-231471892,
> or mute the thread
> https://github.com/notifications/unsubscribe/AB1OEoMt4z3fZD-MBi-fMUf_E6jgyUuKks5qTrregaJpZM4JIWuG
> .

## 

Tanya Parker
Product Manager, Code.org
+1 (562) 318-4137

**Comment by tanyaparker** [comment]
This was the original file when we combined repos:
https://github.com/code-dot-org/code-dot-org/blob/7564066231e74aaeee763becfb3af70a84ce5dc5/pegasus/sites.v3/code.org/public/promote/index.haml

On Fri, Jul 8, 2016 at 2:21 PM, Tanya Parker tanya@code.org wrote:

> This was some legacy code. I broke the page (there were a lot of js
> errors) after I removed it, so I added it back in.
> 
> On Fri, Jul 8, 2016 at 2:02 PM, Elijah Hamovitz notifications@github.com
> wrote:
> 
> > Looks like @tanyaparker https://github.com/tanyaparker is the one who originally
> > added the if statement
> > https://github.com/code-dot-org/code-dot-org/commit/a61d58e42678b757d55290596a2c646d8a8a02ac
> > ... Tanya, do you have some context for why this was necessary?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/code-dot-org/code-dot-org/pull/9399#issuecomment-231471892,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AB1OEoMt4z3fZD-MBi-fMUf_E6jgyUuKks5qTrregaJpZM4JIWuG
> > .
> 
> ## 
> 
> Tanya Parker
> Product Manager, Code.org
> +1 (562) 318-4137

## 

Tanya Parker
Product Manager, Code.org
+1 (562) 318-4137

**Comment by Hamms** [comment]
Asher, does removing this still break the page?

**Comment by tanyaparker** [comment]
I can't find what my first change was that broke the page. Maybe I just did it wrong that first time.

**Comment by ashercodeorg** [comment]
Nope. AFAICT, removing this code has no effect on this page or any other pegasus page (based on a limited sample).

**Comment by Hamms** [comment]
LGTM, then!

**Pull request merged**
