### PR TITLE
Update levelbuilder_permission to use existing methods.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Tested (trial by fire) by running the updated script in levelbuilder, noting that I wanted the side effects of it.

### CODE REVIEW

**Comment by Hamms** [comment]
The side effects being removal of admin permissions?

**Comment by ashercodeorg** [comment]
Nope, this script doesn't actually remove `admin` status. It gives all admins the `UserPermission::LEVELBUILDER` permission. After verifying (with a guinea pig - see my request in levelbuilder slack room) that everything continues to work with this permission and without admin status, I'll start removing admin status from levelbuilder admins.

**Comment by ashercodeorg** [comment]
Though it _should_ be safe to revoke `admin` status as part of this script, my preference was to error on the side of safety and not risk a widespread disruption to levelbuilders.

**Comment by Hamms** [comment]
sounds great!

**Pull request merged**
