### PR TITLE
Create CSA family and curriculum umbrella

### PR DESCRIPTION
**Pull request by dmcavoy**
This is part of the work to create a new course with units for CSA. In order to be able to use things like resources in a course it must have a course version. In order to have a course version you need to select a family name. This adds CSA to the family name dropdown on Unit and Course edit pages. 

Course Edit Page:
Screen Shot 2021-02-17 at 2 59 53 PM

Unit Edit Page: 
Screen Shot 2021-02-17 at 2 59 08 PM

## Testing

Added to existing tests to make sure that you can create a CSA unit.

### CODE REVIEW

**Comment by dmcavoy** [comment]
I checked locally and I was able to make a new CSA course after adding this and able to add resources to lessons.

1. Created course and scripts
2. Added scripts to course
2. Made scripts migrated
3. Set course and script family name to csa
4. Set courser version year
5. Seed scripts (I don't know if this could have been skip)
6. Seed courses

Screen Shot 2021-02-17 at 3 25 18 PM

**Review by davidsbailey — APPROVED** [review]
LGTM!

**Comment by davidsbailey** [comment]
> 4. Set course and script family name to csa

scripts in courses should not have family names.

> 6. Seed scripts (I don't know if this could have been skip)
> 7. Seed courses

before you can add vocab or resources to these, you will likely need to seed scripts again as step 8.

**Comment by dmcavoy** [comment]
> > 1. Set course and script family name to csa
> 
> scripts in courses should not have family names.

My bad on the script it is setting the core course setting.
> 
> > 1. Seed scripts (I don't know if this could have been skip)
> > 2. Seed courses
> 
> before you can add vocab or resources to these, you will likely need to seed scripts again as step 8.

I was able to get the editor to be available without doing this again. Are you saying that the changes wouldn't save without seeding scripts again?

@davidsbailey

**Comment by davidsbailey** [comment]
> I was able to get the editor to be available without doing this again. Are you saying that the changes wouldn't save without seeding scripts again?

I think I got this slightly wrong, but I was referring to this constraint: https://github.com/code-dot-org/code-dot-org/blob/f89b9a6fbfb84ff61c17b46cef5108ad4a4b337a/dashboard/lib/services/script_seed.rb#L166-L169

it looks like you are fine in this scenario, because you are not trying to seed any resources or vocab out of .script_json.

**Pull request merged**
