### PR TITLE
add eyes test for advocacy.code.org

### PR DESCRIPTION
**Pull request by tanyaparker**
Modeled after [hour_of_code_dot_com.feature](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/test/ui/features/hour_of_code_dot_com.feature).

### CODE REVIEW

**Comment by tanyaparker** [comment]
@breville is this good enough? Is there a way to confirm before it gets to test machine?

**Comment by breville** [comment]
Actually, you can probably just add an entry here: https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/test/ui/features/other_sites.feature

**Comment by tanyaparker** [comment]
@breville cool! PTAL

**Comment by tanyaparker** [comment]
@breville yup! Content wise we're ready to go! Checking with Will on any other infrastructure items to get it ready for launch.

**Comment by breville** [comment]
oh, nevermind, https://test-advocacy.code.org/ is already active and this will hit that site, so you can merge when you like.

**Pull request merged**
