### PR TITLE
Add Amplitude event for Teacher Homepage visits

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Adds a basic Amplitude event for the teacher homepage! Short and sweet :)

Screenshot 2024-04-25 at 11 59 08 AM

## Warning!!

The [AP CSP Create Performance Task](https://apcentral.collegeboard.org/courses/ap-computer-science-principles/exam) is in progress. The most critical dates are from April 3 - April 30, 2024. Please consider any risk introduced by this PR that could affect our students taking AP CSP. Code.org students taking AP CSP primarily use App Lab for their Create Task, however a small percent use Game Lab. Carefully consider whether your change has any risk of alterering, changing, or breaking anything in these two labs. Even small changes, such as a different button color, are considered significant during this time period. Reach out to the Student Learning team or Curriculum team for more details.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bethanyaconnor** [comment]
(Tagging teacher tools here as an FYI -- always happy for a review but likely won't block on it.)

**Review by TurnerRiley — APPROVED** [review]
Looks great! Just confirming we only want this for Amplitude and not also Statsig right?

**Comment by dju90** [comment]
This logs just for signed-in teachers, is that correct?

**Comment by dju90** [comment]
Dani mentioned that this was to help figure out how many teachers were clicking on the welcome email. This event only tracks visits to the homepage - I'm assuming that the tracking of "where did the user come from" is coming from a different source like UTM tracking? In general, this looks great and we will definitely use this on the teacher dashboard side.

**Comment by dmcavoy** [comment]
> Dani mentioned that this was to help figure out how many teachers were clicking on the welcome email. This event only tracks visits to the homepage - I'm assuming that the tracking of "where did the user come from" is coming from a different source like UTM tracking? In general, this looks great and we will definitely use this on the teacher dashboard side.

Yes we are using UTM to track where they came from. We need the event to be able to see that they came to the page with certain UTMs

**Comment by bethanyaconnor** [comment]
> Looks great! Just confirming we only want this for Amplitude and not also Statsig right?

Oh good question! I think just Amplitude for now as I don't think we've been told to start migrating any other events to Statsig (could be wrong though)

**Comment by bethanyaconnor** [comment]
> This logs just for signed-in teachers, is that correct?

Yep! Signed out users are redirected to the sign in page and students see the corresponding `StudentHomepage` component!

**Pull request merged**
