### PR TITLE
Removed unused newrelic package

### PR DESCRIPTION
**Pull request by jmkulwik**
Clearing out some unused packages from our package.json.

The newrelic npm package was [added a while back](https://github.com/code-dot-org/code-dot-org/pull/8294) in order to track our build times. The usage was [removed a few years ago](https://github.com/code-dot-org/code-dot-org/pull/29597), but the npm package and one of the scripts were missed in the cleanup. This just does a little more cleanup to clear those out. This shouldn't impact our production monitoring via newrelic - from my investigation that's added to the window object from the backend and this package was only used for the specific scenario mentioned earlier - however, @sureshc, I could definitely use a second pair of eyes to validate that understanding.

This was discovered using [depcheck](https://www.npmjs.com/package/depcheck)

### CODE REVIEW

**Review by Erin007 — APPROVED** [review]
Good find! Thanks for clearing out the rest of these long-forgotten tendrils. 🧹

**Review by davidsbailey — APPROVED** [review]
🚮 💯

**Comment by jmkulwik** [comment]
@sanchitmalhotra126 - I think you might be the right person to tag - Suresh said he only knows about how the backend NewRelic logging works. Can you take a quick look and let me know if I'm overlooking anything from your perspective? I couldn't find any usage of the newrelic NPM package and am pretty sure that we use the ruby gem to set up our front end monitoring. But could use a second pair of eyes.

**Comment by sanchitmalhotra126** [comment]
> @sanchitmalhotra126 - I think you might be the right person to tag - Suresh said he only knows about how the backend NewRelic logging works. Can you take a quick look and let me know if I'm overlooking anything from your perspective? I couldn't find any usage of the newrelic NPM package and am pretty sure that we use the ruby gem to set up our front end monitoring. But could use a second pair of eyes.

Yeah, this sounds right to me - I'm only aware of [logToCloud.js](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/logToCloud.js) that reports to New Relic from the front end, and that uses the newrelic object on the window as you mentioned.

**Pull request merged**
