### PR TITLE
Eyes gem: Upgrade eyes_selenium gem to version 3.2.2

### PR DESCRIPTION
**Pull request by breville**
As suggested by Applitools' support team.

(`Gemfile.lock` generated by running `bundle install` after making the change to `Gemfile`.)

### CODE REVIEW

**Comment by islemaster** [comment]
Wow, no other API changes in a major version upgrade?

**Comment by islemaster** [comment]
Fun fact: This update includes [my only Applitools bugfix](https://github.com/applitools/Eyes.Selenium.Ruby/pull/46) which shipped in 2.39.0.

**Comment by islemaster** [comment]
Sorry, I'm going to investigate further for possible API changes before I approve.  It's not just a major version, this gem has changed GitHub repositories ([before](https://github.com/applitools/Eyes.Selenium.Ruby), [after](https://github.com/applitools/eyes.sdk.ruby)) since our current version - who knows what that means :man_shrugging:.

**Comment by islemaster** [comment]
Well, they definitely copied parts of the old repo over - here's [the test I added](https://github.com/applitools/eyes.sdk.ruby/blob/v3.2.1/spec/driver_passthrough_spec.rb#L40-L48), now attributed to an "initial import."

**Comment by islemaster** [comment]
Hmm, this is the thing I most expect to break:

```ruby
  batch = Applitools::Base::BatchInfo.new(ENV['BATCH_NAME'])
  batch.id = ENV['BATCH_ID']
  @eyes.batch = batch
```

The `Applitools::Base` namespace is [definitely documented for v2.38.0](http://www.rubydoc.info/gems/eyes_selenium/2.38.0/Applitools) but [not for v3.2.1](http://www.rubydoc.info/gems/eyes_selenium/3.2.1/Applitools/Selenium).  The [docs on the Applitools wiki](https://applitools.atlassian.net/wiki/display/Java/Selenium+-+Ruby) still refer to `Applitools::Base::BatchInfo` but they also still use `Applitools::Eyes.new` instead of `Applitools::Selenium::Eyes.new`, leading me to believe those docs assume a 2.x version - so it's possible the API for setting up a test batch has changed entirely.  I'll open a question on their new repo about this.

**Comment by islemaster** [comment]
Found it (while writing https://github.com/applitools/eyes.sdk.ruby/issues/28) - `Applitools::Base::BatchInfo` was moved to `Applitools::BatchInfo`.  I'd update that in this PR too.

**Comment by davidsbailey** [comment]
Nice! LGTM. Anything in particular we're getting from eyes_selenium 3.2.1 to look forward to?

**Comment by breville** [comment]
@davidsbailey Nothing specific, but their support suggested we upgrade when we described the timeouts we saw in taking screenshots.  If it doesn't solve this issue, then we can gather more logs and submit them.

Currently blocked on hearing from their support about an (as yet) undocumented API change.

**Comment by islemaster** [comment]
Looks like batch support in the new library [has been merged](https://github.com/applitools/eyes.sdk.ruby/pull/29/files) and is landing in v3.2.2.

**Pull request merged**
