### PR TITLE
Organize UI tests by cabal

### PR DESCRIPTION
**Pull request by Erin007**
UI test flakiness slows down our deployment pipeline.  One way to decrease UI flakiness is to establish clear ownership over each test such that the correct people can be identified to resolve any issues.  This re-organizes our current feature files based on the current cabal structure (Foundations, Learning Platform, StarLabs, PLC, Hour of Code). Thus, when a test needs attention, the developer of the day can easily determine whom to ask for assistance.

### CODE REVIEW

**Comment by bethanyaconnor** [comment]
I believe TTS is on a seam between LP and FND so `text_to_speech.feature` could possibly be in FND but no strong opinions either way from me.

**Review by bethanyaconnor — APPROVED** [review]

**Comment by ajpal** [comment]
General question on the usefulness of having an Hour of Code directory: if an hour of code test breaks while I'm dotd, who would I talk to about it?
I wonder if it would be better to separate the hoc tests into which cabal would most likely be responsible for fixing them (ex: starwars.feature and ml_hoc.feature goes to star labs, tutorial_landing_pages.feature probably goes to PLC, etc?)

**Comment by ajpal** [comment]
I might be wrong but I thought the share dialog was owned by LP, not star labs.
Looking at share_buttons.feature, legacy_share_remix.feature, shared_apps.feature, sharing_from_script_level.feature, etc.

**Comment by ajpal** [comment]
Thank you for doing this @Erin007! I think it's going to be super helpful for us deflaking UI tests across the team 😀

**Review by hacodeorg — APPROVED** [review]
Thanks Erin, this will be helpful! Since our cabal structure doesn't change often, it's okay to organize code by cabals. Otherwise, organizing code by areas of ownership (rather than the owners) could be more stable.

**Pull request merged**
