### PR TITLE
Dance teacher resources section

### PR DESCRIPTION
**Pull request by nkiruka**
### NOTE switch base to staging before merging.

This PR is to display the teacher resources section

### Implementation
- Add dance teacher resources partial
- Change font size of section heading
- Adjust height and of tile boxes
- Adjust font size of tile box title
- Update I18n strings

### Screen shot
screen shot 2018-11-06 at 10 54 08 am

### CODE REVIEW

**Comment by Erin007** [comment]
Do you have an ETA on the image/gif for these blocks? And confirmation on their responsive design? Is this PR instead of the one related to the translation link and chevron? (I see those changes here too, but they appear updated?)

**Comment by nkiruka** [comment]
@Erin007 Waiting on Mark to confirm ETA.  I created this branch off the add chevron icon branch.  I have switched the base branch to add chevron icon, so only applicable commits are visible.

**Comment by nkiruka** [comment]
@Erin007 I am getting one the assets later today.

**Comment by nkiruka** [comment]
@Erin007 Base branch has been switched please review

**Review by Erin007 — APPROVED** [review]

**Pull request merged**
