### PR TITLE
Add a banner for user research to the teacher homepage

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Screenshot 2024-08-15 at 3 31 53 PM

This will likely cause eyes diffs on the teacher homepage.

### CODE REVIEW

**Review by kelbyhawn — COMMENTED** [review]
It looks like the image needs to be on a white background ([see Figma](https://www.figma.com/design/liPou77RuNL0Ik7YujsEjN/One-Time-Projects?node-id=1190-881&t=t2C4Jobn8Wz1yC7A-1)); I updated it so you can use this!

Also I can merge this for you if it doesn't pass drone before you head out!

banner-user-research-aug-2024

**Comment by bethanyaconnor** [comment]
hmm, I checked with Molly yesterday. Let me double check

**Comment by kelbyhawn** [comment]
> hmm, I checked with Molly yesterday. Let me double check

This is what it's showing in Figma, but if she's ok w/ it having a transparent background that works for me!

Screenshot 2024-08-16 at 8 34 56 AM

**Comment by bethanyaconnor** [comment]
Molly confirmed it's good as-is with the transparent background!

**Review by kelbyhawn — APPROVED** [review]
🎉

**Comment by bethanyaconnor** [comment]
> This is what it's showing in Figma, but if she's ok w/ it having a transparent background that works for me!

It was a good catch! I appreciate you asking :)

**Pull request merged**
