### PR TITLE
Preview Activity and ActivitySection that will be deleted

### PR DESCRIPTION
**Pull request by dmcavoy**
Shows a preview of the Activity or Activity section that is about to be deleted to help make sure its the one the user intended to delete.

### Deleting Activity
Screen Shot 2021-01-07 at 9 46 34 PM

### Delete Activity Section

With Content
Screen Shot 2021-01-07 at 9 46 41 PM

With Tip:
Screen Shot 2021-01-07 at 9 47 08 PM

With No Content:
Screen Shot 2021-01-07 at 9 46 47 PM

## Links

- [jira](https://codedotorg.atlassian.net/browse/PLAT-661)

## Testing story

Updated OrderControlsTest

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
Do we get a scroll bar if we are deleting content that is too big to fit in the dialog?

**Review by bethanyaconnor — APPROVED** [review]
Looks awesome -- thanks for jumping on this :)

**Comment by dmcavoy** [comment]
@davidsbailey Yes it scrolls

scroll-delete

**Review by davidsbailey — APPROVED** [review]
LGTM after making sure there is vertical scrolling for Activity previews which do not fit on the screen.

**Pull request merged**
