### PR TITLE
Add standards to seed process

### PR DESCRIPTION
**Pull request by Erin007**
Rather than importing from a csv, we need Standards available in all environments, particularly test; so I moved them to be part of the seeding process. 

Screen Shot 2020-03-11 at 1 49 23 PM

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
Looks great!

**Comment by davidsbailey** [comment]
hmm actually, this is abbreviated data, right? and in production there are many more standards? if that's right, then do we need to make sure the full standards data doesn't get overwritten when we seed in production or levelbuilder?

**Comment by Erin007** [comment]
This abbreviated data in that it is only CSTA standards for CSF 2019 courses. There are more standards on Curriculum Builder, but these 39 are the only ones we care about on Code Studio in any environment right now. If we expand the feature to other courses, we'll need to add to the csv.

**Comment by davidsbailey** [comment]
OK, great. in that case, `dashboard/config` would be a better place for this file, since it's not a test-only fixture, rather it's production data which we also need in tests. Sorry for the late request!

**Comment by Erin007** [comment]
> OK, great. in that case, `dashboard/config` would be a better place for this file, since it's not a test-only fixture, rather it's production data which we also need in tests. Sorry for the late request!

No worries - I should've waited to merge.  I'll move the file in a follow-up.

**Pull request merged**
