### PR TITLE
make it safe to migrate units containing legacy teacher resources

### PR DESCRIPTION
**Pull request by davidsbailey**
FInishes [PLAT-1427] add [PLAT-1426]. see [migrating old units - work plan](https://docs.google.com/document/d/1aH_YxmhSXsYcDHmDIU4MDtIu2KoqCgxih6nhGd1SBdo/edit#) for background, and see [migrating teacher resources](https://docs.google.com/document/d/1yIL2Z7aqFTdbCi24-RpUhPO_B3wRdsiKRTB1EEs17EY/edit#) doc for what steps would come after this. Generally speaking, the goal of this PR is to get us to where we can safely migrate units which contain unmigrated teacher resources, to unblock other teammates and hit the HOC lockdown deadline. the follow-up work to migrate teacher resources doesn't necessarily have to happen before HOC, though it may still make the deadline.

Previously, migrating units containing legacy teacher resources was not safe, because the UI would only look for migrated resources in migrated units. This PR does the following:

fix up existing data to eliminate some complexity
* 0902934aa5281133ac20a056377572a7c62d640e add course_version to all units with unmigrated teacher resources
  * this is a cherry-pick of dba36c6 made via levelbuilder

fix how we display + edit teacher resources
* 540a66f005a8afce61c34070025fbe40ea80b3fe on unit overview page, show legacy teacher resources in migrated units 
  * more specifically, allows legacy teacher resources to override migrated teacher resources when both are present in migrated units, so that recently-migrated teacher resources can have time to be translated before they go live
* b79d8bfed15ffce605686d991402f7475aaa56b3 show something reasonable for resource editor on unit edit page for migrated units which do not have fully migrated resources
  * a matrix of expected new behavior can be seen on the "resource editor behavior" tab of this [gsheet](https://docs.google.com/spreadsheets/d/1wqwPYxgi5HpNGPAtfx0NIphYJ4RG8SfwkZ8kIjfwlMQ/edit#gid=0).

fix up our migration tools
* 10d1124b2d676223a9e59836f1d970dba3da55ce allow migrate_unit.rb to migrate units containing legacy teacher resources 
* 71dc0d032b6c2dc43c5219645074c3606222ce0a modify migrate_teacher_resources.rb to preserve legacy teacher resources 

**Question for reviewers**: am I missing anything that could break if we migrate units before migrating their teacher resources?

## Testing story

* new + existing unit tests cover new behavior on unit overview page and unit edit page
* manually verified several combinations listed in the "manual testing" sheet of this [gsheet](https://docs.google.com/spreadsheets/d/1wqwPYxgi5HpNGPAtfx0NIphYJ4RG8SfwkZ8kIjfwlMQ/edit#gid=26759932)

## Follow-up work

The remaining work in this space can all be done after we finish migrating all units. For details, see [migrating teacher resources](https://docs.google.com/document/d/1yIL2Z7aqFTdbCi24-RpUhPO_B3wRdsiKRTB1EEs17EY/edit#) eng plan.

[PLAT-1427]: https://codedotorg.atlassian.net/browse/PLAT-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLAT-1426]: https://codedotorg.atlassian.net/browse/PLAT-1426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by davidsbailey** [comment]
> **Question for reviewers**: am I missing anything that could break if we migrate units before migrating their teacher resources?

I am just realizing that this plan does not really account for editing. I tried migrating coursea-2020, and it looks fine on the unit overview page (several teacher resources), but the edit page lets you edit the migrated teacher resources, which are initially empty. this is not great -- I am considering doing the following for migrated units:

option X:
* if there are legacy teacher resources but no migrated teacher resources, allow editing legacy teacher resources
* if there are legacy teacher resources AND migrated teacher resources, allow editing migrated teacher resources

option Y:
the simpler alternative would be to just (temporarily) disable editing of teacher resources for all migrated units which have legacy teacher resources.

Input welcome. I will hold off on this PR (at least the part of it that removes the restriction from migrate_unit.rb) until I have a plan here.

**Comment by davidsbailey** [comment]
OK folks, this is ready for review. I've attempted to fix the problem with the resource editor, and updated the PR description above to describe what I did.

**Comment by bethanyaconnor** [comment]
Are there any courses that with unmigrated resources that also need to be covered by this change? Right now, I think we make the decision on which resources to use for teacher resources on the course by seeing if any of the scripts are migrated ([here](https://github.com/code-dot-org/code-dot-org/blob/d788c4797a51c0483db648608ca389f705ebe89d/dashboard/app/models/unit_group.rb#L376)).

I guess courses can probably just have their resources migrated without worrying too much about translations as CSF uses standalone units, so maybe this isn't actually a concern

**Comment by bethanyaconnor** [comment]
CSP 2017 is a good example of what I'm thinking of -- the scripts and the course both have teacher resources that aren't migrated yet. That dropdown works fine as with this PR, but I haven't checked what happens if I migrate the csp scripts

**Comment by bethanyaconnor** [comment]
Apologies for the stream of consciousness, but I migrated the csp 2017 units locally and the resources did disappear from the course overview page. I think a similar change can be made in [CourseOverviewTopRow](https://github.com/code-dot-org/code-dot-org/blob/d788c4797a51c0483db648608ca389f705ebe89d/apps/src/templates/courseOverview/CourseOverviewTopRow.js#L36) or we can just remember to migrate the course resources when migrating these units.

**Comment by davidsbailey** [comment]
Thanks @bethanyaconnor , great catch! I was able to repro locally after migrating csp1-2017 locally, then verified things look good on csp-2017 (legacy resources) and csp-2021 (migrated resources) after making the fix.

**Comment by davidsbailey** [comment]
> I guess courses can probably just have their resources migrated without worrying too much about translations as CSF uses standalone units, so maybe this isn't actually a concern

meaning, this line shouldn't need to change? https://github.com/code-dot-org/code-dot-org/blob/71dc0d032b6c2dc43c5219645074c3606222ce0a/bin/curriculum/migrate_teacher_resources.rb#L55

**Comment by bethanyaconnor** [comment]
Yeah, I don't know how much care we need to give to preserving translations for unit groups, so we could still set `teacher_resources` to the empty list for unit groups in the migration regardless. Up to you, though. Thanks for updating!

**Review by bethanyaconnor — APPROVED** [review]

**Comment by davidsbailey** [comment]
> Yeah, I don't know how much care we need to give to preserving translations for unit groups, so we could still set `teacher_resources` to the empty list for unit groups in the migration regardless. Up to you, though. Thanks for updating!

I think I'm comfortable with a short period of translations being missing on teacher resources in units which we do not officially support translations, but we can also revisit this when we go to actually run migrate_teacher_resources.rb if we want to.

**Pull request merged**
