### PR TITLE
Add @raise method annotations to and tests for DevelopersTopic.

### PR DESCRIPTION
**Pull request by asherkach**

### CODE REVIEW

**Comment by asherkach** [comment]
@tanyaparker: Feel welcome to assign a reviewer.

**Comment by jeremydstone** [comment]
Congratulations "First-time contributor" @asherkach on your "first" PR!

**Comment by asherkach** [comment]
Since Circle CI may not have been run, copying in a local run of the `test_developers_topic.rb`.
```
$ bundle exec ruby -Itest lib/test/cdo/test_developers_topic.rb 
Started with run options --seed 12873

dtt
  test_0001_returns DTT message                                   PASS (0.00s)
  test_0002_raises when DTT is missing                            PASS (0.00s)

dotd
  test_0001_returns the dotd (excluding @ symbol)                 PASS (0.00s)
  test_0002_raises an exception if topic is malformed             PASS (0.00s)

set_dts
  test_0001_sets DTS message                                      PASS (0.00s)
  test_0002_raises when DTS is missing                            PASS (0.00s)

set_dtp
  test_0002_raises when DTP is missing                            PASS (0.00s)
  test_0001_sets DTP message                                      PASS (0.00s)

dts?
  test_0003_returns false when DTS is missing                     PASS (0.00s)
  test_0001_returns true when DTS is yes                          PASS (0.00s)
  test_0002_returns false when DTS is no                          PASS (0.00s)

dtl?
  test_0001_returns true when DTL is yes                          PASS (0.00s)
  test_0002_returns false when DTL is no                          PASS (0.00s)
  test_0003_returns false when DTL is missing                     PASS (0.00s)

dtp?
  test_0001_returns true when DTP is yes                          PASS (0.00s)
  test_0002_returns false when DTP is no                          PASS (0.00s)
  test_0003_returns false when DTP is missing                     PASS (0.00s)

dtl
  test_0001_returns DTL message                                   PASS (0.00s)
  test_0002_raises when DTL is missing                            PASS (0.00s)

dtt?
  test_0001_returns true when DTT is yes                          PASS (0.00s)
  test_0002_returns false when DTT is no                          PASS (0.00s)
  test_0003_returns false when DTT is missing                     PASS (0.00s)

dtp
  test_0002_raises when DTP is missing                            PASS (0.00s)
  test_0001_returns DTP message                                   PASS (0.00s)

set_dtt
  test_0002_raises when DTT is missing                            PASS (0.00s)
  test_0001_sets DTT message                                      PASS (0.00s)

set_dtl
  test_0001_sets DTL message                                      PASS (0.00s)
  test_0002_raises when DTL is missing                            PASS (0.00s)

dts
  test_0002_raises when DTS is missing                            PASS (0.00s)
  test_0001_returns DTS message                                   PASS (0.00s)

Finished in 0.01765s
30 tests, 34 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by tanyaparker** [comment]
Oh yeah, it wasn't. Thanks for the verification!

**Pull request merged**
