### PR TITLE
Save and view empty lesson

### PR DESCRIPTION
**Pull request by davidsbailey**
Follow-up to https://github.com/code-dot-org/code-dot-org/pull/37220#issuecomment-709491231

1. removes an explicit check to prevent lessons from being saved when they do not contain any levels
2. fixes 1 server-side and several client-side problems when levels are not present
3. shows placeholder text when levels are not present

### Details view
empty-lesson-details

### Summary view
Screen Shot 2020-10-15 at 1 36 08 PM

## Testing story

Mostly relying on existing test coverage. It's likely we'll get some additional coverage of this in the future when we add more UI tests to cover the flow of adding a lesson using the script gui editor.

EDIT: I also tested out the following scenario:
1. create a new script at /s/new
2. use the script edit gui to create a new, empty lesson (succeeds)
3. go back to script edit gui and click through to the lesson edit page

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dmcavoy** [comment]
I think it might be a good idea to also check some of these things but if you feel its outside of the scope right now feel free to ignore.
- What happens if you go to one of the levels in the next lesson?
- What happens if Lesson 1 and Lesson 3 have levels but Lesson 2 does not? If you are in the last level of Lesson 1 and click next does it go to the correct place?
- Teacher Dashboard does the progress view work ok?

**Review by dmcavoy — APPROVED** [review]
Looks good to me once its passes tests. I think checking a couple more places bubbles show up would be good if you can.

**Comment by davidsbailey** [comment]
> I think it might be a good idea to also check some of these things but if you feel its outside of the scope right now feel free to ignore.
> 
> * What happens if you go to one of the levels in the next lesson?
> * What happens if Lesson 1 and Lesson 3 have levels but Lesson 2 does not? If you are in the last level of Lesson 1 and click next does it go to the correct place?
> * Teacher Dashboard does the progress view work ok?

Good questions! I think all of these scenarios will become important as we start to consider having lessons / activities with no levels in them. I think that work is part of the plan for April, right? If that is the case, I think it's ok to aim for basic functionality / best effort not to break things or let them look broken for now.

To test these I made Course A 2020 Lesson 3 empty instead of lesson 1.

To my surprise, the first two scenarios you listed both work great. The progress view does not look great but does render without errors:
Screen Shot 2020-10-15 at 11 17 49 PM

also the MiniView on the script level page renders but the styles are a bit wacky:
Screen Shot 2020-10-15 at 11 19 53 PM

I think it will be worthwhile for me to make a best-effort attempt to make both of these scenarios look less broken, then get this PR merged so that we can unblock ourselves and actually be able to use the lesson editor.

**Comment by davidsbailey** [comment]
Updated MiniView (Details + Summary):
Screen Shot 2020-10-16 at 8 23 48 AM

Screen Shot 2020-10-16 at 8 28 34 AM

No change to script overview page from previous screenshots.

**Comment by davidsbailey** [comment]
Updated progress details view:
Screen Shot 2020-10-16 at 8 55 13 AM

**Comment by davidsbailey** [comment]
Lesson Extras:
Screen Shot 2020-10-16 at 9 01 30 AM

**Comment by dmcavoy** [comment]
The updates look great @davidsbailey !

**Pull request merged**
