### PR TITLE
Active regional partners

### PR DESCRIPTION
**Pull request by bencodeorg**
"Active" regional partners implemented using paranoia gem, so we can soft delete inactive regional partners. A couple things to look out for:
A) this is my first migration, so general check on whether I'm missing any key steps.
B) is there any package import required for `acts_as_paranoid`? Example PRs didn't appear to have anything but I might have missed something.
C) I overwrote my initial PR on the same branch (where I switched `rural` to `active`) -- I don't think there are any remnants from that attempt that are still present here, but could use a second pair of eyes.
D) @aoby -- do I need to update tests to reflect that there's a new column?

### CODE REVIEW

**Comment by aoby** [comment]
@bencodeorg 

A) no, unless we want to handle the dependent destroys (see Suresh's comment and below)
B) no - bundler automatically imports the `acts_as_paranoid` gem (and any gem in the Gemfile without `require: false`) for the entire Rails environment.
C) Looks fine
D) No. All tests passed, and unless you want a specific test for the soft delete functionality (which has its own tests in the `paranoia` gem) there's no need to change them.

@sureshc `paranoia` does honor `dependent: :destroy` associations and will call them with the same method. See https://github.com/rubysherpas/paranoia#destroying-through-association-callbacks. So, in our case we would expect the [mappings](https://github.com/code-dot-org/code-dot-org/blob/e3a93a21bcaec3cf58d4b3d69bd7baba8db3ffb6/dashboard/app/models/regional_partner.rb#L38) association to destroy all associated mappings when a regional partner is soft-deleted. We should probably also add `deleted_at` to the mappings so they will all be soft deleted together. And ideally we'd also add a `dependent: :destroy` to the [regional_partner_program_managers](https://github.com/code-dot-org/code-dot-org/blob/e3a93a21bcaec3cf58d4b3d69bd7baba8db3ffb6/dashboard/app/models/regional_partner.rb#L32) association, and add soft-delete to that model too.

**Comment by bencodeorg** [comment]
Wait so @aoby the mapping (i.e., the `regional_partner_id` field in `pd_workshops`) would be nulled out once a partner is deleted?

**Comment by aoby** [comment]
@bencodeorg no, not `regional_partner_id`. Only associations marked with `dependent: :destroy`, which currently is only [mappings](https://github.com/code-dot-org/code-dot-org/blob/e3a93a21bcaec3cf58d4b3d69bd7baba8db3ffb6/dashboard/app/models/regional_partner.rb#L38). In other words it will essentially call `.destroy` on each associated `RegionalPartnerMapping`

**Comment by bencodeorg** [comment]
I see, so gets rid of the geo mappings. Thanks.

**Comment by aoby** [comment]
Right. But we could also make them soft-delete if we wanted to keep them around and have the opportunity to restore. Similarly this will orphan regional partner associations, so ideally we'd also make that soft-deletable and add a `dependent: :destroy` to that association.

**Comment by bencodeorg** [comment]
@aoby @sureshc noted that he would have expected circle to fail given that my migration syntax was off, but I believe it passed all tests even before I got the syntax right. Is this expected (i.e., are all migrations run at some point in the circle process?)

**Comment by aoby** [comment]
Strange. Yes, circle will run pending migrations. It looks like the first [circle run on this branch](https://circleci.com/gh/code-dot-org/code-dot-org/tree/active-regional-partners) was after merging staging, just before you fixed the syntax, so indeed it did succeed before. I'm not sure why. Perhaps the bad syntax didn't cause it to fail, but rather just not do what we expect?

I think we're ok as long as you verified locally you can migrate and rollback, and circle passes now (which it does).

**Comment by bencodeorg** [comment]
Confirmed `rake db::rollback` was successful locally (in addition to previous testing of the actual migration). @aoby cool to merge?

**Comment by aoby** [comment]
LGTM, but I still have the open question - what should we do about the associations? Right now it's inconsistent and not ideal, as I stated above: `mappings` will be hard deleted, and `regional_partner_program_managers` will be left alone (orphaned).

**Comment by bencodeorg** [comment]
Yep, good point @sureshc suggested tracking as tech debt? @tanyaparker FYI -- I'm not sure I can describe the issue well but generally something along the lines of ("consistency in approach to deleting inactive regional partners and associated entities") @aoby?

**Comment by tanyaparker** [comment]
You got it! Adding to our tracker.

**Pull request merged**
