### PR TITLE
Remove LevelDetailsDialog storybook

### PR DESCRIPTION
**Pull request by bethanyaconnor**
I added these to be able to iteratively develop on the component. Now that it's been in production for a year and we have UI/eyes tests covering it, we don't need this storybook entry anymore. 

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by dmcavoy — APPROVED** [review]
I'm on board with removing this but when I asked about removing a storybook recently there was concern about losing the ability to iterate in the future using storybook. @jamescodeorg thoughts on removing this?

**Comment by bethanyaconnor** [comment]
I'm not sure we've got a clear view of what we use Storybook for in general. My logic is that I added this specifically for iterating during development and now that the component is pretty stable I should clean it up. Plus, we can use lesson plans now to see this component.

If folks think there is value in keeping this around though, I'm happy to close this PR. I was on a bit of a delete code spree yesterday :)

**Comment by davidsbailey** [comment]
I am interested to hear James's thoughts, as well as @tim-dot-org 's. I don't have a fully-formed recommendation, but my initial thoughts are: (UPDATED)

1. In addition to making it easier to modify the component in the future, we also get some **test coverage** from storybook entries. these are much easier to add than writing new unit tests, and make it easy to quickly verify that a component renders without errors (or warnings... right?) given a number of configuration of props. given how many react warnings I see in the console when using the lesson editor, this seems like a good thing.

2. while storybook tests may be somewhat redundant with unit tests, storybook tests run much faster (45s to run all) and are much **less brittle** than, for example, "unit" tests which do deep rendering (via `mount`) and then test child component contents. most of the time, if I change a deeply nested component, it will NOT break the parent storybook test. one exception would be if I change things around in redux, in which case I might need to update a number of storybook entries to provide redux (or provide more specific things via redux). though infrequent, this can be kind of a pain to do. there are surely other scenarios where storybook breaks that I'm not remembering.

3. a situation where I WOULD want to eliminate a storybook file would be in the case where the component can be **fully exercised by a parent storybook**. (FWIW, that doesn't seem to be true in this case, because the parent LevelToken does not have a storybook, but also because you have to interact with the LevelToken component in order to get it to even show the LevelTokenDetails component, which would not be possible to do in a LevelToken storybook entry).

4. in other situations (including this one) I'm not quite sure what the best option is -- I'm a little rusty on frontend development, so I'm blanking a little on how often a storybook entry catches a bug vs. how much time is spent fixing unexpected storybook breakages in situations where there is no bug. I'd love to know how others feel on this 

5. all of this should be considered in the context of whether we're going to land on **shallow-rendering vs RTL**. pure unit testing via shallow-rendering is no longer well supported by the community. RTL is supported by the community, but favors deep rendering (not pure unit testing).  if we go RTL, we have to decide whether every component will still have a test, or whether we'll focus on testing groups of components, etc. so, one idea would be to **not establish clear policies here yet** until that bigger question is settled.

**Comment by jamescodeorg** [comment]
I don't have a strong opinion here, but here are my thoughts:

These storybook entries seem useful because they allow someone working on the component quickly try out a change against a range of expected property inputs.  If these entries were useful when initially developing the component, it seems like they could also be useful when making future updates to the component.

That said, there can be a significant cost to maintaining these storybook entries.  If we frequently find that we need to update storybook entries that are unrelated to the change that we are making then that seems to point to undesired coupling between components (which definitely exists in some components currently).  (Incidentally, this same coupling is probably what makes it hard to figure out how data flows from the backend to the frontend and to determine how a change would affect the system.)

As long as the person who's making the change has weighed this tradeoff, I trust whatever decision they make.  (It would also be really nice if we had more clear guidelines around this at some point.  Perhaps that's something the QA consultant can help us with.)

**Comment by davidsbailey** [comment]
quick note: I just realized I was looking at the wrong component, so some of my notes in my (3) and (4) are off.  recalculating...

**Comment by davidsbailey** [comment]
apologies -- I see now this is `LevelDetailsDialog` not `LevelTokenDetails`. for the reasons listed earlier, I think it would make sense to keep this component, in particular this functionality (test coverage + ability to use storybook to add new features) doesn't seem to be covered by another storybook entry of one of its parents -- but I don't feel strongly about this, and I'm fine with removing it if folks think that's best. in particular I have not felt the pain of storybook tests breaking recently, and I am certainly sympathetic to that factor, and/or just generally feeling like the benefits of keeping this are not that compelling.

**Comment by bethanyaconnor** [comment]
Sounds like there's some consensus. I opened it mainly as there has been some discussion about what to do with these kinds of components that were used for development once development is done and one option has been to just delete them. I personally don't find storybook super useful except in the case I created this one for. It sounds like others find more usefulness out of it though, so I'm happy to keep it and close this PR!

**Pull request closed without merging**
