### PR TITLE
Add lesson_extras alias for Section.stage_extras

### PR DESCRIPTION
**Pull request by uponthesun**
I'm not positive this is a good pattern, but it at least seems easy to undo. Thoughts?

## Testing story

* drone tests

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by dmcavoy — COMMENTED** [review]
For my understanding: Why is not worth renaming the column in the database?

**Comment by uponthesun** [comment]
Good question, I'm not 100% sure. What gives me pause is that the table isn't tiny (though not massive either):
```
[production] dashboard > Section.count
=> 2382156
```

I don't have experience doing changes to large production tables in MySQL, and I'm not sure offhand that it's safe to just deploy a migration to rename the column. (It probably wouldn't be too bad, but I could see having a few minutes of errors.) We could do some testing and research to figure out if it is.

In the past we've used tools for safe online schema changes, specifically https://github.com/github/gh-ost, though that was for much larger tables. That tool no longer works for us though after the move to Aurora.

My other thought was that it's not too big a benefit to rename in the DB either, if the field is aliased in the ruby code. There are situations where the alias doesn't work though, like passing in a hash of values to the `update` method. So I could see an argument that we do want to rename it in the DB.

Interested in thoughts one way or the other.

**Comment by davidsbailey** [comment]
I think when we discussed this previously regarding the term "stage" in general, the consensus was that there were so many places that we'd need to update field names in the DB (like this one), and we get 95% of the benefit by renaming the association which will appear across our codebase, so it basically wasn't worth the hassle. then we said we'd try to live with that and see if the inconsistency between association name and DB column name was causing confusion, and if it was then we'd consider renaming actual DB columns and/or table names.

renaming columns is tricky because we couldn't "just" rename the column -- we'd either need to take planned downtime (presumably using it to rename many tables / columns at once), or else have both the old and new column both be present temporarily to avoid a period of server errors between `rake db:migrate` and whenever the new servers are deployed.

Does that help at all Dani?

**Review by davidsbailey — APPROVED** [review]

**Comment by dmcavoy** [comment]
> I think when we discussed this previously regarding the term "stage" in general, the consensus was that there were so many places that we'd need to update field names in the DB (like this one), and we get 95% of the benefit by renaming the association which will appear across our codebase, so it basically wasn't worth the hassle. then we said we'd try to live with that and see if the inconsistency between association name and DB column name was causing confusion, and if it was then we'd consider renaming actual DB columns and/or table names.
> 
> renaming columns is tricky because we couldn't "just" rename the column -- we'd either need to take planned downtime (presumably using it to rename many tables / columns at once), or else have both the old and new column both be present temporarily to avoid a period of server errors between `rake db:migrate` and whenever the new servers are deployed.
> 
> Does that help at all Dani?

Yes thank you @davidsbailey !

**Pull request merged**
