### PR TITLE
move components into instructions directory

### PR DESCRIPTION
**Pull request by Bjvanminnen**
This moves a bunch of our instructions related components into their own directory within templates. This is done again in part to prepare for me adding some more instructions-related components.

Would love feedback on the following
- Is there a better directory name than `instructions`?
- Do some of these files not really belong in `instructions`?
- Are there other files that should also be in this directory?
- Might it make sense to somehow combine this directory and the templates/feedback directory?

### CODE REVIEW

**Comment by Hamms** [comment]
`DialogButtons` is used by more than just instructions; feedback, most notably.

**Comment by Hamms** [comment]
If we consider authored hints to be a component of the larger `instructions` concept, then I think the rest of these changes make sense.

I'd say it would make sense _for right now_ to combine instructions and feedback into something like `dialogs`, but given that the two elements are only going to continue to diverge I think leaving them separate makes more sense.

**Comment by Hamms** [comment]
I'd suggest `DialogButtons` be returned to where it was; otherwise, this LGTM!

**Comment by Bjvanminnen** [comment]
Strange that the line from `feedback.js`
`var DialogButtons = require('./templates/DialogButtons.jsx');`
didn't break the build in this PR

**Comment by Bjvanminnen** [comment]
DialogButtons uses Lightbulb, so I moved both back to where they were.

Also, upon finding out that the build didn't break when requiring non-existent files (kind of scary) I took a closer look at references to moved files, and found some that I'd missed, and cleaned those up.

**Comment by Bjvanminnen** [comment]
mochaTests pass locally (despite having failed in circle-ci) so I'm going to push (and will revert from staging if it has issues there).

**Pull request merged**
