### PR TITLE
Start button all locales

### PR DESCRIPTION
**Pull request by tanyaparker**
This is a follow-up fix for #19456 and an alternative to #19457.

This manually copies over all the translations of the `applabTutorialButton` string in `common.json` to a new `startButton` string in `tutorialExplorer.json`. This is a quick/temporary fix. If we want to preserve this, we need to make sure not to do a partial sync where the content in i18n/locales will overwrite this. We should do a full sync so that crowdin will copy over the translations from the translation memory.

### CODE REVIEW

**Comment by islemaster** [comment]
Uh... this seems like something we are likely to accidentally break down the road.  I figured we would just import the common locale into tutorialDetail.jsx and use it directly.  Is there a reason we can't do that, besides that it would increase the bundle size for the tutorial explorer a bit?  It seems much less risky to me.

**Comment by breville** [comment]
@islemaster Check out https://github.com/code-dot-org/code-dot-org/pull/19457 for that approach.  We prepped both approaches to compare and contrast.

**Comment by Bjvanminnen** [comment]
It doesn't end up in the bundle. It's a separate file, which  means making sure we import it in all the right places. The first attempt at this already missed a couple of places (we think we have them all now). This also means a slightly slower load time because of the extra file.

**Comment by islemaster** [comment]
Ah, in that case this makes more sense.

**Pull request merged**
