### PR TITLE
migration and new model files for fit weekend registrations

### PR DESCRIPTION
**Pull request by clareconstantine**
merge before (https://github.com/code-dot-org/code-dot-org/pull/26276)

### CODE REVIEW

**Comment by clareconstantine** [comment]
[Update FiT Registration for 1920](https://trello.com/c/zAc6Ffdf/771-update-fit-registration-for-1920)

**Review by Hamms — COMMENTED** [review]
Is there a specific reason to keep the 1819 registrations in their own table, rather than migrating them to the new one?

**Comment by clareconstantine** [comment]
@Hamms just a matter of prioritization - ideally we will eventually migrate them over but there is no need to do that at the moment, so I kept this simple to get the 1920 app up and running asap.

**Review by Hamms — APPROVED** [review]
LGTM!

**Pull request merged**
