### PR TITLE
Enable object-curly-spacing

### PR DESCRIPTION
**Pull request by islemaster**
[**object-curly-spacing**](http://eslint.org/docs/rules/object-curly-spacing) requires no padding spaces inside object literals. ([Google styleguide](https://google.github.io/styleguide/javascriptguide.xml?showone=Code_formatting#Code_formatting)).  Also autofixable.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
tbh, i like having a space in there

**Comment by islemaster** [comment]
@Bjvanminnen would you prefer enforcing "always" (space in curlies, e.g. `{ x: 1 }`) or not enforcing?

**Comment by Bjvanminnen** [comment]
I'm okay with either. Would personally prefer either of those to enforcing no space.

**Comment by islemaster** [comment]
If we're not in agreement on this, I'd prefer we don't enforce and make a note in our styleguide that we don't conform to that bit of Google's styleguide.  I'll update this PR to that effect.

**Comment by islemaster** [comment]
PR updated to disable object-curly-spacing and note deviation in styleguide.  @Bjvanminnen PTAL.

**Comment by Bjvanminnen** [comment]
lgtm

**Pull request merged**
