### PR TITLE
Set up objective migrations and basic model

### PR DESCRIPTION
**Pull request by bethanyaconnor**
In the future we may want to connect objectives to assessments or standards, but for now they're only associated with lessons.

Generated with `bundle exec rails generate model Objective properties:text lesson:references`.

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
Looks good except maybe missing the actual migration file?

**Comment by bethanyaconnor** [comment]
🤦‍♀️ 🤦‍♀️ 🤦‍♀️ 🤦‍♀️ 

Adding now....

**Review by davidsbailey — APPROVED** [review]
no worries 🙂

**Review by dmcavoy — APPROVED** [review]
🎉

**Pull request merged**
