### PR TITLE
AccHack - Increase footer background and text contrast

### PR DESCRIPTION
**Pull request by kelbyhawn**
Increase the background color and text contrast on the footers across https://studio.code.org/ and https://code.org/

**Jira ticket:** https://codedotorg.atlassian.net/browse/A11Y-51

----

#### Before
Screenshot 2022-12-13 at 10 36 51 AM

#### After
Desktop_pegasus

----

#### Before
Screenshot 2022-12-13 at 10 37 01 AM

#### After
Desktop_dashboard

### CODE REVIEW

**Review by megcrenshaw — APPROVED** [review]
I see the specs in the ticket, but I'm curious if a designer signed off on this? It's a big change! But I'm so happy about the higher contrast

**Comment by kelbyhawn** [comment]
> I see the specs in the ticket, but I'm curious if a designer signed off on this? It's a big change! But I'm so happy about the higher contrast

Yep! Molly (Peredo) and I both wanted to make this change 🎉

**Review by hannahbergam — APPROVED** [review]
YAY I AM EXCITED ABOUT THIS!!!

**Comment by megcrenshaw** [comment]
Wahooo! That's wonderful 🥳

**Pull request merged**
