### PR TITLE
Create a cronjob to run a Redshift script on the i18n-dev server

### PR DESCRIPTION
**Pull request by hacodeorg**
[FND-1509](https://codedotorg.atlassian.net/browse/FND-1509)
Enables the i18n-dev server to run Redshift script by adding necessary gem and Redshift secrets.
Creates a cronjob to run `update_translation_status.rb` at midnight (UTC) everyday.

## Testing story
- Installs `pg` gem required by the `RedshiftClient` wrapper using `bundle install`.
  - `pg` gem requires `pg_config` tool, which we can get using the instruction for Ubuntu [here](https://wikimatze.de/installing-postgresql-gem-under-ubuntu-and-mac/).

- Run `bundle exec bin/i18n/update_translation_status.rb` locally and on the i18n-dev machine.

## Next steps
**Before merging**
- [x] Create a separate Redshift account to be used in the i18n-dev machine. Then, add the account's username and password to AWS Secrets Manager. [Slack discussion on INF channel](https://codedotorg.slack.com/archives/C03CK49G9/p1618507476367200)
- [x] Create a cronjob that runs once a day. [Slack discussion on FND channel](https://codedotorg.slack.com/archives/CFTFD6BPV/p1618509191234800).
- [x] Clean up local changes on the i18n-dev machine.
- [x] ~~Wait until https://codedotorg.atlassian.net/browse/FND-1505 is done.~~ FND-1505 work is now merged into this PR.

**After merging**
- [ ] Enable the new cronjob to run on the i18n-dev machine.

### CODE REVIEW

**Comment by dju90** [comment]
After you merge this, will the get_string_keys_from_tracking_events() function be included in the update_translation_status.rb that @daynew is working on that includes the method to actually upsert translation status for the distrinct string keys? If so, then the name of the file makes sense; if not, I would consider renaming the file (if that function is going to be all alone)

**Comment by hacodeorg** [comment]
> After you merge this, will the get_string_keys_from_tracking_events() function be included in the update_translation_status.rb that @daynew is working on that includes the method to actually upsert translation status for the distrinct string keys? If so, then the name of the file makes sense; if not, I would consider renaming the file (if that function is going to be all alone)

AFAIK the only use case for `get_string_keys_from_tracking_events` is in the translation status updating context. If the function is used in more cases later, we can move it to a helper module. @daynew to confirm.

**Comment by daynew** [comment]
> AFAIK the only use case for `get_string_keys_from_tracking_events` is in the translation status updating context. If the function is used in more cases later, we can move it to a helper module. @daynew to confirm.

Yes I have the task which will actually make use of the helper method @hacodeorg created in this PR.

**Review by daynew — APPROVED** [review]
One minor change if you are up for it. Could you move `updater_translation_status.rb` into the `translation_status` subfolder? So the whole path is `bin/i18n/translation_status`. I'm trying to get all the files related to this feature in a single folder so there is some separation from the i18n sync. If you don't have time, I could move this file in a future PR.

**Pull request merged**
