### PR TITLE
Add p5.play attribution in copyright notices and NOTICE file.

### PR DESCRIPTION
**Pull request by islemaster**
We're using [p5.play](https://github.com/molleindustria/p5.play) which is licensed under the GNU LGPL.  Under the terms of that license we need to provide attribution (among possibly other things... discussion is underway).

This adds p5.play to our notice file, and to our small copyright footer, with links to the full text of the GNU LGPL.

Small footer:

screenshot from 2016-03-21 10-14-30

### CODE REVIEW

**Comment by islemaster** [comment]
Poorva, will you get the wording on these notices approved?

**Comment by poorvasingal** [comment]
I sent an email to Michelle to make sure the wording is okay.  Thanks Brad.

**Comment by islemaster** [comment]
@poorvasingal based on the thread with Michelle I've updated this so that we only include the attribution in the small footer (which is always present when p5.play is being used) and to point the full license text link in the footer to gnu.org.  Otherwise, my understanding of our discussion is that this notice and having a copy of the license in our repository more than puts us in compliance with LGPL 2.1.

@joshlory quick review?

**Comment by joshlory** [comment]
Followed up offline with a few concerns.

**Comment by Bjvanminnen** [comment]
Note: This failed a bunch of eyes tests because our copyright is now bigger (and in the case of the eyes tests starts to overlap the play area). I suspect we don't care, but want to be sure.

**Pull request merged**
