### PR TITLE
Build minimum required set of dependencies for changed portions on CircleCI

### PR DESCRIPTION
**Pull request by bcjordan**
**Motivation**: quite often times a PR will have changes to just one or two sub-projects—a style change in `apps/`, a `.haml` change in `dashboard/`. The hope with this PR is to reduce the 8.5 minute `rake install` and 16 minute `rake build` steps for PRs with minimal contents.
# `locals.yml` auto-configuration

This PR refactors the "if changed in branch" checking/logging used for test running to apply to constructing the `locals.yml` `build_my_` and `use_my_` portions as well. It also includes a helper to modify a YAML file by passing in a block that lets the caller modify the file's content as a simple hash, saving at the end.
# Linting

Additionally, since not all dependencies will be built in some scenarios now, this branch adds a `rake lint:changed` target that uses the same dependency change checking but applied to file linting. Worth noting—`circle.yml` was previously running only `rake lint:javascript`, and this changes it to run all of the linting for changed files.

Also added the `:test` group to the `Gemfile`'s linting dependencies section.

Two questions, given Hound runs as well:
- Should this be stepped back to only lint javascript?
- Could Hound run all linting and Circle skip doing any?

### CODE REVIEW

**Comment by bcjordan** [comment]
@islemaster @Bjvanminnen @joshlory which subset of `rake:lint` should CircleCI be running (versus Hound)?

Currently runs: `rake lint:javascript`

My current understanding is our current Hound lints ruby, haml, but does not lint JavaScript, is that correct?

Wondering if this has been unblocked—from searching convo archives it looks we were blocked on ESLint 2 on Hond, the original issue is in a [deleted repo](https://github.com/houndci/eslint/issues/18#issuecomment-213621687), but it looks like it moved to https://github.com/houndci/linters/blob/master/package.json#L6 which appears to have ESLint 2 now and the blockers for that seem to be merged upstream https://github.com/littlebits/code-standards-js/issues/9 https://github.com/littlebits/code-standards-js/pull/10

**Comment by bcjordan** [comment]
Found @islemaster's original Hound ESLint thread https://github.com/code-dot-org/code-dot-org/pull/8005#issuecomment-223778639 , looks like is now possible :+1:. Have hands full landing CircleCI UI test changes so will leave `rake lint:javascript` in for this branch, if anyone's interested in doing the Hound ESLint 2.x conversion likely following similar steps to #8005 they are then free to remove the `circle.rake` `rake lint:javascript` lines once Hound is covering instead!

**Comment by islemaster** [comment]
You are correct re:Hound - it does not currently lint JavaScript, but I think we could revisit that now and remove linting from our Circle builds.

**Comment by islemaster** [comment]
This all looks nice and clean to me.  Do you have any stats on what the speedup is in different cases?

**Comment by bcjordan** [comment]
@islemaster thanks, great question. Wondering best way to realistically test all the different scenarios before merging to staging—hard part is that `staging` is considered the base branch for any non-`staging`/`test`/`production` branch at the moment when we do "what files changed" detection.

I might be able to temporarily patch that so that branches starting with `minimal-build-` are considered to be branched off of this `minimal-builds` branch, which would mean I could make branches that each have small changes in a given sub-project to test them all. Think I will go with that approach, will add to roll-out checklist in description.

Alternatively, and this might be more ultimately externally useful, I could have Circle check if there's a GitHub PR associated with a given run, and if so, target its given base branch. That might be worth doing in any case, and would give us a leg up for future GitHub PR features (e.g. pass config strings in the PR title, auto-merge after green test).

Hmm!

**Comment by islemaster** [comment]
> have Circle check if there's a GitHub PR associated with a given run, and if so, target its given base branch

It doesn't already do this, or our scripts don't already do this?  This seems like an important behavior to fix - can we actually trust our Circle staging/test/production builds right now?

**Comment by bcjordan** [comment]
Our scripts already do target the correct base branch for staging/test/prod and most other branches that target staging. It infers the base branch via a mapping, staging -> test, test -> prod, [otherwise] -> staging.

But this wouldn't behave properly for the case where you branch off of another branch off of staging. The failure scenario is that it will OVER run the tests, though, so not a terrible thing.

**Comment by islemaster** [comment]
Looking forward to seeing what difference this makes!  LGTM

**Comment by islemaster** [comment]
Closing stale PR.  Sorry Brian!  I think our CI setup has changed enough since this work that it's not something we'll ever merge.

**Pull request closed without merging**
