### PR TITLE
add appModern style to designModeViz

### PR DESCRIPTION
**Pull request by davidsbailey**

### CODE REVIEW

**Comment by joshlory** [comment]
This looks like it fixes Design Mode images, but buttons and dropdowns still show the issue.

**Comment by davidsbailey** [comment]
please take another look, Josh

You can see how I didn't update the rules properly the first time here: https://github.com/code-dot-org/code-dot-org/pull/4464/files#diff-d905fb78b016f1751b45c125fe320c17

**Comment by joshlory** [comment]
LGTM!

I couldn't figure out why this wasn't working locally until I finally did `grunt rebuild` instead of `grunt build` :disappointed:.

**Comment by davidsbailey** [comment]
Yeah, I ran into the same thing. I don't remember having to do that before. weird.

**Pull request merged**
