### PR TITLE
Fixes violations of and reenables the rubocop Style/RedundantReturn check.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes auto-generated by "bundle exec rubocop --only Sytle/RedundantReturn --auto-correct".

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Is this a check we want to enable? Coming from a C++ background, I'm a fan of redundant returns.

**Comment by laurelfan** [comment]
I vote for enabling. Ruby often encourages using a more declarative (this is) style rather than the imperative (do this) C/Java style. Though thinking about it in this way I can see why it would be jarring to be constantly assigning values right before an implicit return.

**Comment by philbogle** [comment]
Let's get more input from the rest of the team on this question of style.

Personally, I like explicitness and explicit returns rather than implicit ones, so I'm not sure how I feel about forcing hte implicit style.

It's unfortunate, for example, that many Ruby methods "accidentally" whatever happens to be the last expression in the code without documenting what they are supposed to return.  Code comes to rely on the return value, which is then inadvertantly changed.

**Comment by ashercodeorg** [comment]
Though I agree with you Phil, if code is relying on the (implicit) return value, could one argue that the return value contract should be documented (via a comment) if there is any reliance on the (implicit) return value? By and large, our methods seem to have inadequate comments describing purpose, inputs, and outputs.

**Comment by Hamms** [comment]
I'm a python fanboy; explicit is better than implicit.

**Comment by philbogle** [comment]
Since there is not a strong consensus that we want to disallow explicit returns, I propose to retire this PR and not do so.  Explicit returns are allowed at the discretion of the code author and reviewer.

@ashercodeorg  I agree with your points regarding documenting return values.  I have seen a number of gems that don't explicitly document return values and assume you will read the source code, and during the Rails 4.2 upgrade we were broken by changes in the types of the return values.

**Comment by ashercodeorg** [comment]
Per lack of consensus, I am closing this PR. In another PR, I will add Style/RedundantReturn to .rubocop.yml as part of the list of rules we do not intend to enforce in the foreseeable future.

**Pull request closed without merging**
