### PR TITLE
Markdown dialogs slide down to the right place with this change.

### PR DESCRIPTION
**Pull request by breville**
The dialog can't just set "margin: 0 auto" because the slide animation wants to take it off-center.

### CODE REVIEW

**Comment by breville** [comment]
@bcjordan and @tanyaparker what do you think?  The downside is that it goes back to fixed 640px width dialogs, whereas it seems with markdown they were more dynamic?  Is there a good middle-ground here?

**Comment by bcjordan** [comment]
LGTM! I suspect it should be OK to have a fixed width of 640px for it

**Comment by sfilman** [comment]
Does this affect App Lab documentation as well?

**Comment by sfilman** [comment]
@breville @bcjordan The positioning for App Lab documentation did regress recently (thanks @davidsbailey for pointing this out). I don't know if it's a direct result of this change, but it's now showing up not centered:

image

Could one of you take a look?

**Comment by breville** [comment]
Oops, sorry for missing that @sfilman .. now fixed with https://github.com/code-dot-org/code-dot-org/pull/3741

**Comment by sfilman** [comment]
Thanks!

**Pull request merged**
