### PR TITLE
Add "copy rerun command" button to test status page

### PR DESCRIPTION
**Pull request by Hamms**
image

### CODE REVIEW

**Comment by islemaster** [comment]
Nah, this is a terrible idea.

tumblr_inline_o6mwfs7r3f1slxns3_500

Just kidding, it's brilliant.  One question: Does the textbox have to be visible at all?

**Comment by Hamms** [comment]
Haha, that is the goal!

And yes; that's a browser-level restriction to prevent websites from doing sneaky shit. I'm actually surprised they let me get away with making it as small as I did.

**Comment by islemaster** [comment]
If you feel like adding magic we could pull [clipboardjs](https://clipboardjs.com/) from their CDN to do this without the textbox.  Either way this LGTM!

**Comment by breville** [comment]
@Hamms This is awesome.  Thanks for doing it!

**Comment by Hamms** [comment]
Glad it's helpful!

**Pull request merged**
