### PR TITLE
hoc2021: Homepages get banner image for mobile widths

### PR DESCRIPTION
**Pull request by breville**
https://code.org/ and https://hourofcode.com/ now get a banner image for mobile widths, shown when the left & right images added in https://github.com/code-dot-org/code-dot-org/pull/42902 are hidden due to the narrower widths.

### code.org/
localhost code org_3000_

### hourofcode.com/
localhost hourofcode com_3000_us

### CODE REVIEW

**Review by Erin007 — APPROVED** [review]

**Review by maddiedierker — APPROVED** [review]
not blocking this PR, but do we have a way to share assets across pegasus domains? it seems common that we would want to share them like we do in this case

**Comment by breville** [comment]
@madelynkasula Good question, and it turns out we do have [/shared/images](https://github.com/code-dot-org/code-dot-org/tree/staging/shared/images) which will work between https://studio.code.org, https://code.org, and https://hourofcode.com.  I might clean this up in a followup.

**Review by KylieModen — APPROVED** [review]
lgtm!

**Comment by breville** [comment]
@madelynkasula The common images have been moved to `/shared/images` in https://github.com/code-dot-org/code-dot-org/pull/42965.

**Pull request merged**
