### PR TITLE
Census state data

### PR DESCRIPTION
**Pull request by drewsamnick**
Tables and models to support state data for census. Rather than having a new table to map from NCES school id to state school id I have added a state_school_id column to the schools table. We get the state school id from the same data file that gives us the rest of the data in schools.

### CODE REVIEW

**Comment by drewsamnick** [comment]
[Create table for state top down data](https://trello.com/c/KyotikGB/83-create-table-for-state-top-down-data)

**Comment by davidsbailey** [comment]
Hi Drew, it looks like this PR broke the staging build due to a ruby lint error: https://codedotorg.slack.com/archives/C03CK8E51/p1515691954000389 I'll go ahead and fix, but please make sure you have the git pre-commit hooks installed.

**Comment by drewsamnick** [comment]
@davidsbailey Hmmm, that's odd. I generally can't commit if there are errors like this. Any idea why this failed on staging but not the feature branch?

**Comment by davidsbailey** [comment]
Hi Drew, I'm really not sure, but we did have a similar trailing whitespace error break staging on Monday as well. It's possible there is some difference between the rubocop/lint rules used on staging vs what's in the pre-commit hooks. Thanks for the background info. I will follow up on this.

**Pull request merged**
