### PR TITLE
Show disabled bubble warning on HOC scripts

### PR DESCRIPTION
**Pull request by Erin007**
[LP-2109](https://codedotorg.atlassian.net/browse/LP-2109), partial of [LP-2082](https://codedotorg.atlassian.net/browse/LP-2082)

A few updates to the warnings we show when the site is in emergency mode and progress isn't saved for HOC and CSF courses: 
1.) Update the link to a new support article in both the modal and level warning (currently a placeholder, but Josh is working on content and will publish) 
2.) Show the modal on HOC scripts; we previously weren't.
3.) Tweak the language to clarify that users can still do HOC tutorials, but progress will not be saved.

### CODE REVIEW

**Review by jamescodeorg — APPROVED** [review]
Thanks for taking care of this!

Do you know if it's likely we'll get the new `disabledProgress3` translated before HoC?  (Ok if not, but just good to keep in mind that non-English locales will see the old message.)

**Comment by Erin007** [comment]
> Do you know if it's likely we'll get the new `disabledProgress3` translated before HoC? (Ok if not, but just good to keep in mind that non-English locales will see the old message.)

As far as I know the translator deadline is 11/25 so it's possible that this string will be translated by HOC; but, I don't think it's crucial if it doesn't get translated given (what I hope is) the very low likelihood we'll need to show this banner 🤞 and that the surrounding strings are already translated so folks viewing in non-English will have some context and the crux of the message.

**Comment by Erin007** [comment]
I still don't love how brittle these tests are and it feels a little excessive to have a file that exports one variable, but having to make a change in one place rather than four in the future feels like an incremental improvement.

**Review by clareconstantine — APPROVED** [review]
Thanks Erin!

**Pull request merged**
