### PR TITLE
Upgrade Enzyme to version 3

### PR DESCRIPTION
**Pull request by jmkulwik**
This brings together the final set of changes to upgrade to Enzyme version 3. Some changes in this PR are tests that were updated in a way so they are compatible with Enzyme V3, but not V2. These were already reviewed. Changes that have not been reviewed are:
- Upgrading Enzyme to V3: https://github.com/code-dot-org/code-dot-org/pull/29266/commits/da068e162308f3da9713fb32ccd3789eb2a409e2
- Adding Enzyme Adapter to Storybook tests: https://github.com/code-dot-org/code-dot-org/pull/29266/commits/bdd68c6061308c960e9ce85ae11da7e76eb72c46
- Fixing an unhandled promise rejection @islemaster @madelynkasula: https://github.com/code-dot-org/code-dot-org/pull/29266/commits/ebf079a9970c43ad84321423d306639008db2d3f

Issue: https://codedotorg.atlassian.net/browse/STAR-545
Epic (React Upgrade): https://codedotorg.atlassian.net/browse/XTEAM-61

### CODE REVIEW

**Comment by jmkulwik** [comment]
For those curious, drone has already passed on this PR: https://drone.cdn-code.org/code-dot-org/code-dot-org/2839
I made some minor changes to one of the commits before requesting a review, so drone restarted.

**Comment by jmkulwik** [comment]
> nit: use `console.error` instead of `console.log`

That also causes promise rejection :(

**Comment by maddiedierker** [comment]
@jmkulwik ah, that makes sense. you're good to leave as-is and i'll create a jira ticket for us to address a long-term fix for this code [edit: created [LP-550](https://codedotorg.atlassian.net/browse/LP-550) to track]

**Review by ajpal — APPROVED** [review]
lgtm! great job tracking down all the loose ends!

**Comment by islemaster** [comment]
Awesome work on this massive upgrade!
eevee

**Pull request merged**
