### PR TITLE
add ability to refresh autoscaling group instances

### PR DESCRIPTION
**Pull request by cat5inthecradle**
This adds an EC2 Autoscaling module with an instance refresh method.

Question: Should this have logging added, or should the calling code contain necessary logging?

## Links

Jira Ticket: https://codedotorg.atlassian.net/browse/INF-1373
Required For: https://codedotorg.atlassian.net/browse/TEACH-1116

## Testing story

This has NOT been tested manually because we only have one autoscaling group - the production one. We should find a time to manually test this during non-peak usage.

```ruby
require 'cdo/aws/ec2_autoscaling'
AWS::EC2Autoscaling.refresh_instances
```

This verifies the accuracy of the code, as well as the IAM permissions on the server.

## Follow-up work

* Leverage this as part of TEACH-1116.

## Security

Requires the `autoscaling:StartInstanceRefresh` permission, with both engineers and production-daemon have on `resource: "*"`

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
FYI @vijayamanohararaj

@etaderhold I'm curious what your use case is going to look like, where are you hoping to initiate an instance refresh from? There's a little more work for us to meet in the middle, but I want to check in on where you're at.

**Comment by etaderhold** [comment]
> FYI @vijayamanohararaj
> 
> @etaderhold I'm curious what your use case is going to look like, where are you hoping to initiate an instance refresh from? There's a little more work for us to meet in the middle, but I want to check in on where you're at.

Thanks for starting on this! I just put a comment in my other PR #59930 indicating where the instance refresh would occur: after seeding content into the database we'd start up new instances that prime their caches with the new content.

**Comment by cat5inthecradle** [comment]
@etaderhold Ok, the missing piece then is "how to determine which load balancer to refresh". There are a couple of options depending on what assumptions we want to make.

* Every environment only has one load balancer

Given that, we could search load balancers by tag. Both `production-daemon` and the load balancer have the stack tag `aws:cloudformation:stack-name`

* The load balancers are named like `Frontends-<environment-name>`

Given that, we could generate the name.

That's all future-proofing, we could just hardcode the production load balancer name and wrap it all in an `if(prod)` because we only have the one load balancer, but I'd like to avoid the code making that assumption.

**Review by etaderhold — COMMENTED** [review]
I'm unqualified to review this PR, just popping in to say I like the one-line method call this makes available!

**Review by sureshc — APPROVED** [review]

**Pull request merged**
