### PR TITLE
Applab partition

### PR DESCRIPTION
**Pull request by Bjvanminnen**
Move all commands into commands.js. I also extracted out a couple other pieces of logic that were needed by both applab.js and commands.js

The way I've set up commands.js is a little funky, in that it needs to be explicitly initialized. This is because it's still operating on the Applab namespace, which is intentionally not a global. Instead, we pass the object into our loadCommands function and augment it with our commands.

Long term, the cleaner approach would likely to be to have a separate commands namespace.

I've run mochaTests, played around a little on my localhost, and will also run UI tests against chromedriver before committing.

### CODE REVIEW

**Comment by davidsbailey** [comment]
Why is Applab intentionally not a global in commands.js?

**Comment by Bjvanminnen** [comment]
None of our apps are globals, because globals are bad.

**Comment by davidsbailey** [comment]
What is preventing us from using a non-circular dependency graph where api.js requires commands.js, and commands.js requires applab.js ? Presumably you would need to move the "other pieces of logic that were needed by both applab.js and commands.js" back into applab.js.

**Comment by Bjvanminnen** [comment]
Applab.js requires api.js (so that would be applab -> api -> commands -> applab).

It does look like we actually have Applab as a global - I was mistaken in this. This means there is probably a cleaner solution. I will explor efurther.

**Comment by Bjvanminnen** [comment]
command.js now gets its own namespace, which we export. Some of the commands still depend on Applab being a global, but this dependency is now at runtime instead of load time.

**Comment by davidsbailey** [comment]
LGTM. the separate namespace is a big improvement!

**Comment by Bjvanminnen** [comment]
Be on the lookout for commands that break from this!

It seems like one mochaTest worth creating at some point might be one that just executes every command.

**Pull request merged**
