### PR TITLE
[DES-248][Phase 1.5 Rebranding] [Student Learning]  Additional code workspace changes

### PR DESCRIPTION
**Pull request by levadadenys**
### [Phase 1.5 Rebranding] [Student Learning]  Additional code workspace changes

Changes to look on screenshots: 
- yes/no buttons for instructions
- the dialog - text&button colors

Before:
Знімок екрана 2023-03-10 о 19 48 31
Знімок екрана 2023-03-10 о 19 48 21

After:
Знімок екрана 2023-03-14 о 17 08 46
Знімок екрана 2023-03-14 о 17 07 44

## Links
- jira ticket: [DES-248](https://codedotorg.atlassian.net/browse/DES-248?atlOrigin=eyJpIjoiMmM0YzEyNWQyZDZlNDJkMmI0ZTM5ZjAyNjJhMDQ5MzQiLCJwIjoiaiJ9)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by sanchitmalhotra126 — COMMENTED** [review]
Code looks fine to me! In the screenshot however, it looks like the sample code is missing from the dialog/looks collapsed - is that intentional?

**Comment by levadadenys** [comment]
> Code looks fine to me! In the screenshot however, it looks like the sample code is missing from the dialog/looks collapsed - is that intentional?

Not intentional, but the reason is only that I don't have access to generated code locally. Should work as before on integrated ends

**Comment by levadadenys** [comment]
Updated PR description and screenshot to highlight the changes

**Review by breville — APPROVED** [review]
Thanks for adding the list of changes & the matching screenshots!

**Pull request merged**
