### PR TITLE
raise if dsl filename not found

### PR DESCRIPTION
**Pull request by davidsbailey**
dsl-defined levels names do not exactly match their filenames. Because of this, it is easy to make a case error when running `rake seed:dsls DSL_FILENAME=...`. also there is no warning if the file is not found. therefore, this PR raises if the file was not found, making it a bit easier to figure out what went wrong.

## Testing story

manually verified the following:
* `rake seed:scripts` succeeds (needed to run this rather than `rake seed:dsls` directly so that some pre-requisites would also be run)
* `rake seed:dsls DSL_FILENAME=k-1_Artistloops_multi1.multi` succeeds. this is the correct filename
* `rake seed:dsls DSL_FILENAME=k-1_ARTISTLOOPS_multi1.multi` succeeds. filename differs only by case. I think this might differ from what @hannahbergam saw because of some OS settings on filename case sensitivity. Hannah, if you run this, I would expect it to raise.
* `rake seed:dsls DSL_FILENAME=bogus.multi` raises

### CODE REVIEW

**Comment by davidsbailey** [comment]
quick note: I abandoned the idea of downcasing, because not all dsl filenames are all lower case.

**Review by hannahbergam — COMMENTED** [review]
Awesome. Is there any way to raise something slightly more descriptive? Like one that mentions a potential case mismatch? Though I'm sure there are a plethora of other potential issues..

**Comment by davidsbailey** [comment]
@hannahbergam it's possible to make the error more descriptive, do you have any suggestions? I don't think we can check for case mismatches easily, since we'd have to check all possible filenames which differ only in case.

**Comment by davidsbailey** [comment]
but we could add "please check the case and spelling and make sure you specified a file extension" if that would be helpful?

**Comment by hannahbergam** [comment]
> but we could add "please check the case and spelling and make sure you specified a file extension" if that would be helpful?

I think this would be great. Maybe "please check local filename for exact case and spelling"?

**Review by hannahbergam — APPROVED** [review]
Looks great! Thank you!

**Review by dmcavoy — APPROVED** [review]
Nice follow up

**Pull request merged**
