### PR TITLE
allow publishing of artist zombie levels

### PR DESCRIPTION
**Pull request by davidsbailey**
axosoft item: https://codeorg.axosoft.com/viewitem?id=956&type=features&force_use_number=true

It turns out some artist levels were showing up in the [old gallery](https://studio.code.org/gallery) rather than the new [project gallery](https://studio.code.org/projects) because artist_zombie level types were not allowed to be published as projects. This PR fixes that, and fixes two stray JS errors encountered along the way.
  
example artist zombie level: https://studio.code.org/s/20-hour/stage/11/puzzle/11

### CODE REVIEW

**Comment by caleybrock** [comment]
Does this mean we need a new project type in the project widget? 
These will get published in the Artist section, right?

**Comment by davidsbailey** [comment]
Excellent questions! Because 'artist' is the default project type for various skins of artist, it turns out we get these showing up in the correct section "for free": https://github.com/code-dot-org/code-dot-org/blob/2ee3123d4637472a368f89e328949f5d3a7a686d/apps/src/code-studio/initApp/project.js#L586-L592

screen shot 2018-01-04 at 3 04 42 pm

However, from the above screenshot you can see that I forgot to fix the other logic which is used to determine the name for the new project. That's now fixed in https://github.com/code-dot-org/code-dot-org/pull/19776/commits/66430d945aae6ae9ec4fac0fe4d24b819e5adb0f .

**Comment by davidsbailey** [comment]
"after" screenshot:
screen shot 2018-01-04 at 3 11 38 pm

**Comment by caleybrock** [comment]
Cool, but sounds like we're still not exposing it as a standalone project type?

**Comment by davidsbailey** [comment]
correct, when you save/publish it, you'll start seeing the default artist character instead of the zombie character. the drawing should look the same. If you feel strongly about having a separate standalone project type with the zombie character (which seems totally reasonable), it shouldn't be too hard to do and I could take a work item to add that, or we could ask CSF to do it. We might want to run that work by a PM though.

**Comment by caleybrock** [comment]
Cool, don't feel strongly, just making sure 👍

**Pull request merged**
