### PR TITLE
run all shared tests

### PR DESCRIPTION
**Pull request by Bjvanminnen**
The default pattern for `rake test` is to only run against files in the test directory. It does not recurse into subdirectories, so we had a bunch of middleware tests that were not running. Thankfully, they appear to all still pass.

### CODE REVIEW

**Comment by caleybrock** [comment]
👍 thanks for fixing

**Comment by Bjvanminnen** [comment]
Got a green test run. Gonna rerun a couple more times to make sure we still dont have any intermittency issues.

**Comment by Bjvanminnen** [comment]
Disabled another test, and got a green run. Going to look for 3x green runs before I merge.

**Comment by Bjvanminnen** [comment]
Got a second green run (failing runs in between were SauceLabs issues). Trying for three 🤞

**Pull request merged**
