### PR TITLE
Reenable skipped test in ApiControllerTest.

### PR DESCRIPTION
**Pull request by asherkach**

### CODE REVIEW

**Comment by asherkach** [comment]
AFAICT, #14201 fixed the issue causing the test to be skipped in #13278. If this is the case (e.g., reenabling doesn't introduce any flakiness), we can work to resolve the TODO within the method.

**Comment by asherkach** [comment]
CC @ewjordan (for review) as DOTD.

**Comment by asherkach** [comment]
@davidsbailey: Mind kicking off a CircleCI run with this commit?

**Comment by davidsbailey** [comment]
the circle run on the linked PR has passed.

**Pull request merged**
