### PR TITLE
Redirect users to new sign up if they end up in wrong flow but are in experiment

### PR DESCRIPTION
**Pull request by hannahbergam**
I was able to test this locally by overriding local_mode in the statsigReporter, opening an incognito window until I got put in the test group, and then trying to go to the old flow (via url) to ensure it would query my experiment group there and redirect me back into the new flow. Video below:

https://github.com/user-attachments/assets/89cf36ce-0dda-49d2-b96b-b0fba24b588f

## Links

- spec: []()
- jira ticket: https://codedotorg.atlassian.net/browse/ACQ-2388

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by TurnerRiley — APPROVED** [review]
LGTM! Do we need the reciprocal as well or just sending from the old flow to the new flow?

**Comment by hannahbergam** [comment]
> LGTM! Do we need the reciprocal as well or just sending from the old flow to the new flow?

I am not sure I see how a user might end up in the opposite situation (whereas the old flow has a few other entry points we're not instrumenting) but that seems like a good question for @dmcavoy!

**Comment by dmcavoy** [comment]
> > LGTM! Do we need the reciprocal as well or just sending from the old flow to the new flow?
> 
> I am not sure I see how a user might end up in the opposite situation (whereas the old flow has a few other entry points we're not instrumenting) but that seems like a good question for @dmcavoy!

I didn't think the opposite problem was likely. The reason we need this assurance is there are a couple ways that you can sign up which will continue to point to the old flow and not pick based on the A/B test. So for those cases if you had seen the new flow I wanted to make sure we didn't send you into the old flow.

**Comment by TurnerRiley** [comment]
> > > LGTM! Do we need the reciprocal as well or just sending from the old flow to the new flow?
> > 
> > 
> > I am not sure I see how a user might end up in the opposite situation (whereas the old flow has a few other entry points we're not instrumenting) but that seems like a good question for @dmcavoy!
> 
> I didn't think the opposite problem was likely. The reason we need this assurance is there are a couple ways that you can sign up which will continue to point to the old flow and not pick based on the A/B test. So for those cases if you had seen the new flow I wanted to make sure we didn't send you into the old flow.

Sounds good! Thank you for the clarification!

**Pull request merged**
