### PR TITLE
DTP the new UI

### PR DESCRIPTION
**Pull request by breville**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Grumble. Is there a reason this didn't go through test? Getting merge conflicts as a result.

**Comment by breville** [comment]
We don't normally wait for circle to pass for DTT/DTP do we?  This had passed a full DTT before the DTP.

**Comment by ashercodeorg** [comment]
Not through testing, through the test environment. E.g., usually we merge test into production, not staging into production.

**Comment by breville** [comment]
Oh, that is totally my bad, and a complete mistake.  Sorry.

**Pull request merged**
