### PR TITLE
Add name and city indexes to schools

### PR DESCRIPTION
**Pull request by jopolsky**
We will need to filter on name and city, for instance:
```
select id, name, city, state, zip from schools
where name like '%?%' or city like '%?%'
order by name limit 40;
```

Here are current indices:
```
mysql> show indexes from schools \G
*************************** 1. row ***************************
        Table: schools
   Non_unique: 0
     Key_name: index_schools_on_id
 Seq_in_index: 1
  Column_name: id
    Collation: A
  Cardinality: 101505
     Sub_part: NULL
       Packed: NULL
         Null:
   Index_type: BTREE
      Comment:
Index_comment:
*************************** 2. row ***************************
        Table: schools
   Non_unique: 1
     Key_name: index_schools_on_school_district_id
 Seq_in_index: 1
  Column_name: school_district_id
    Collation: A
  Cardinality: 33835
     Sub_part: NULL
       Packed: NULL
         Null:
   Index_type: BTREE
      Comment:
Index_comment:
2 rows in set (0.00 sec)
```

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Are we certain that adding these indexes will have any effect? If the planned usage is to have a wildcard at the beginning of the string, my impression is that an index won't reduce the number of rows needing to be scanned.

Mind confirming (rejecting) the index usage by using an `EXPLAIN` for some reasonable value of `?` in the PR summary?

**Comment by jopolsky** [comment]
I didn't include all the queries, I want to get results by specific city as well. I wanted to try a few different queries on name as well.

**Comment by jopolsky** [comment]
Let me consider other options as well. It's odd to me that we would serve a static data source from the DB.

**Comment by ashercodeorg** [comment]
If there is a clear use for lookups by city and by name (not just by city fragment or name fragment), then LGTM to this PR. That said, I think it makes sense to fully understand the queries that we expect to hit this table with and the feasibility of them.

**Comment by ewjordan** [comment]
As far as index adding, this seems fine, but I do agree that considering an in-memory store of some sort might make sense here. A plain old Ruby class variable could work, though that would have per-process space cost, or maybe a local SQLite as you suggested in chat if we'd prefer to share the memory cost across processes.

**Pull request closed without merging**
