### PR TITLE
P20-1055: Add migration for new CAP columns

### PR DESCRIPTION
**Pull request by artem-vavilov**
Added user columns `cap_state` and `cap_state_date`, along with the corresponding index for efficient querying.

`CAP` - Child Account Policy
https://github.com/code-dot-org/code-dot-org/blob/180cf779efa5c7bc0918ca17ca0a3dd0e4933fb6/dashboard/config/initializers/inflections.rb#L22

Index creation script:
```bash
nohup mysql-client-dashboard-writer "CREATE INDEX index_users_on_cap_state_and_cap_state_date ON users (cap_state, cap_state_date)" &
```

## Links
- JIRA task: [P20-1055](https://codedotorg.atlassian.net/browse/P20-1055)
- Phase 1 PR: https://github.com/code-dot-org/code-dot-org/pull/59962
- Phase 2 PR: https://github.com/code-dot-org/code-dot-org/pull/59963

### CODE REVIEW

**Review by mgc1194 — APPROVED** [review]
Looks good. See https://github.com/code-dot-org/code-dot-org/pull/59962

**Comment by sureshc** [comment]
I'm not sure if this should disrupt the work you're doing, but the maximum row size of the `users` table before applying this change appears to be 71409 bytes. When the row size with a MySQL InnoDB table exceeds 65535 bytes, write performance can be degraded because InnoDB stores the overflow data in off-page storage.

**Comment by sureshc** [comment]
> I'm not sure if this should disrupt the work you're doing, but the maximum row size of the `users` table before applying this change appears to be 71409 bytes. When the row size with a MySQL InnoDB table exceeds 65535 bytes, write performance can be degraded because InnoDB stores the overflow data in off-page storage.

I did some more research ... using the `SHOW TABLE STATUS` command on our production database, it appears that the average length of a row in the `users` table is well below the 65535 bytes threshold. We have a number of other tables that exceed this length, so Platform and Infrastructure team should probably schedule some longer term work to mitigate this issue, but it should not hold up this change.

**Review by sureshc — APPROVED** [review]

**Review by coryamanda — APPROVED** [review]

**Comment by Hamms** [comment]
Manually adding the index in production seems to have succeeded; it even took less time than expected!

```
mysql> SHOW INDEXES from users;
+-------+------------+----------------------------------------------------+--------------+----------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| Table | Non_unique | Key_name                                           | Seq_in_index | Column_name          | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Visible | Expression |
+-------+------------+----------------------------------------------------+--------------+----------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| users |          0 | PRIMARY                                            |            1 | id                   | A         |   107639360 |     NULL |   NULL |      | BTREE      |         |               | YES     | NULL       |
| users |          0 | index_users_on_provider_and_uid_and_deleted_at     |            1 | provider             | A         |        4858 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          0 | index_users_on_provider_and_uid_and_deleted_at     |            2 | uid                  | A         |     3169732 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          0 | index_users_on_provider_and_uid_and_deleted_at     |            3 | deleted_at           | A         |     3532792 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          0 | index_users_on_reset_password_token_and_deleted_at |            1 | reset_password_token | A         |     3072315 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          0 | index_users_on_reset_password_token_and_deleted_at |            2 | deleted_at           | A         |     4499120 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          0 | index_users_on_username_and_deleted_at             |            1 | username             | A         |   107639376 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          0 | index_users_on_username_and_deleted_at             |            2 | deleted_at           | A         |   107639376 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          0 | index_users_on_invitation_token                    |            1 | invitation_token     | A         |         944 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          0 | index_users_on_unlock_token                        |            1 | unlock_token         | A         |        1087 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_email_and_deleted_at                |            1 | email                | A         |     6969930 |     NULL |   NULL |      | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_email_and_deleted_at                |            2 | deleted_at           | A         |     7302978 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_hashed_email_and_deleted_at         |            1 | hashed_email         | A         |    49410564 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_hashed_email_and_deleted_at         |            2 | deleted_at           | A         |    50549576 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_invitations_count                   |            1 | invitations_count    | A         |           1 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_invited_by_id                       |            1 | invited_by_id        | A         |        1104 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_birthday                            |            1 | birthday             | A         |      129994 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_studio_person_id                    |            1 | studio_person_id     | A         |     2577922 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_school_info_id                      |            1 | school_info_id       | A         |      522444 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_current_sign_in_at                  |            1 | current_sign_in_at   | A         |    68508056 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_deleted_at                          |            1 | deleted_at           | A         |      868734 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_purged_at                           |            1 | purged_at            | A         |     1634053 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_parent_email                        |            1 | parent_email         | A         |     4599102 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_cap_state_and_cap_state_date        |            1 | cap_state            | A         |           1 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
| users |          1 | index_users_on_cap_state_and_cap_state_date        |            2 | cap_state_date       | A         |           1 |     NULL |   NULL | YES  | BTREE      |         |               | YES     | NULL       |
+-------+------------+----------------------------------------------------+--------------+----------------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
25 rows in set (0.00 sec)
```

**Pull request merged**
