### PR TITLE
replace dangeroulsySetInnerHtml in NonMarkdownInstructions with UnsafeRenderedMarkdown

### PR DESCRIPTION
**Pull request by Hamms**
I thought we actually didn't use this component for rendering instructions anymore - just for rendering the title in things like anigif detail views - but it turns out we _do_ still use it to display instructions in netsim, so I can't actually remove it entirely :(

### CODE REVIEW

**Review by islemaster — APPROVED** [review]
I wonder if anyone would complain if we switched to the markdown instructions in NetSim.

**Comment by Hamms** [comment]
I'd be in favor of that.

Specifically, what we do now is use the `MarkdownInstructions` component for any netsim levels that have Long Instructions, and this component for any levels that don't (including both levels that only have Short Instructions, and any theoretical levels that have neither).

We also (for what I assume are historical reasons) use the `NonMarkdownInstructions` component to render the level title for things like the AniGif detail view.

It would probably be pretty simple to use `MarkdownInstructions` for levels that have either set of instructions, and render the `title` element as a standalone for those views that need it.

**Comment by Hamms** [comment]
Something along the lines of https://github.com/code-dot-org/code-dot-org/pull/27752 should be what we want

**Comment by islemaster** [comment]
Cool.  I'm fine with either approach, I assume we'd want curriculum input on the latter but maybe worth getting it.

**Pull request merged**
