### PR TITLE
Use with_connection in queue_procoessor to avoid thread leakage

### PR DESCRIPTION
**Pull request by philbogle**
Queue processors know wrap their handler calls with "with_connection";  this is required with multithreaded activerecord use to avoid "connection leakage", as described in the ActiveRecord connection pool document.  

Add a command line argument to adjust the update interval of process_queues.

The default queue processor now logs to STDOUT; this will work better with Linux provided daemonization and log rotation features.

Add process_queues_daemon, which uses the daemons gem to daemonize the log processor.   Supports the usual commands including start, stop, and reload.

### CODE REVIEW

**Comment by wjordan** [comment]
LGTM. I think using `'daemons'` in a wrapper script is an okay approach. The gem is pretty rough on top-level documentation so the inline comments on the options help keep track of what's going on.

Two things I'd like clarification on (probably because the documentation is sparse):
- Does the wrapper-script take a set of predefined command-line arguments and/or trap signals to start and stop the daemonized process?
- In order to integrate this into our chef-provisioned deploy, will we need to additionally provide the boilerplate sysvinit scripts in a future PR that hook into this?

**Comment by wjordan** [comment]
I came across a 2014 blog post by Mike Perham (author of Sidekiq), [Don't Daemonize Your Daemons!](http://www.mikeperham.com/2014/09/22/dont-daemonize-your-daemons/) which suggests a more lightweight approach as modern-Ruby best practice, though I haven't spent enough time looking into the whole discussion to say I fully understand the nuances yet. I'd say if the current approach works let's stick with it for now.

**Comment by philbogle** [comment]
The wrapper script takes the same commands that the SYSV init script does; start, start, reload, and status.

We will have a boilerplate sysvinit script that just sets up the path etc and calls through to Ruby script for the actual work.  I have a working adhoc version of this, just need to turn it into a recipe.  That will be a subsequent PR.  For example:

```
# ...
DAEMON=$DASHBOARD/bin/sqs/process_queues_daemon
# ...
case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        $DAEMON start
        ;;
```

etc.

**Comment by philbogle** [comment]
I saw that blog post also.  Its a bit lacking in the actual details of how
to follow the approach with the Ubuntu init system. tried using
start-stop-daemon with it's --background option.  But this didn't work and
came with some pretty heavy caveats.  Using the Gem similarly insulated me
from the cruft of daemonization in the same fashion, provided a monitor
functionality to restart the job in the event it dies, and allows the
instance to be daemonized in an adhoc fashion by running a script in the
tree vs. an init script (while making it easy to create a trival init
script that calls through to it.)

The _daemon script is entirely distinct from the main script, so we can
easily change to some other daemonization approach if we find it is better.

**Comment by philbogle** [comment]
I saw that blog post also.  Its a bit lacking in the actual details of how to follow the approach with the Ubuntu init system. tried using start-stop-daemon with it's --background option.  But this didn't work and came with some pretty heavy caveats.  Using the Gem similarly insulated me from the cruft of daemonization in the same fashion, provided a monitor functionality to restart the job in the event it dies, and allows the instance to be daemonized in an adhoc fashion by running a script in the tree vs. an init script (while making it easy to create a trival init script that calls through to it.)

The _daemon script is entirely distinct from the main script, so we can easily change to some other daemonization approach if we find it is better.

**Pull request merged**
