### PR TITLE
🧹 remove the really old redirect warning for unversioned links

### PR DESCRIPTION
**Pull request by Erin007**
Follow up to https://github.com/code-dot-org/code-dot-org/pull/42396, related to [LP-2524](https://codedotorg.atlassian.net/browse/LP-2524) I _think_

Deletes this banner and related tendrils: 

Screenshot 2024-09-11 at 11 41 46 AM

If you go to an unversioned link for csd or csp, e.g. https://studio.code.org/s/csd1, our system automatically redirects you to the 2019 version of that unit and shows the above banner. The strange thing is that banner says that we're removing this functionality in 2022, but apparently we didn't 🤔 😬. The banner is super old and it sounds like we never intended to continue supporting the redirects, so, I think after 2+ years it's safe to delete this and potentially go hunting for related redirect cruft.

### CODE REVIEW

**Review by bethanyaconnor — COMMENTED** [review]
I think we'd also want to remove the redirect it's warning about, right? I realize that that increases the scope of this PR, but it feels counter productive to remove the warning and not the redirect imo.

**Comment by Erin007** [comment]
> I think we'd also want to remove the redirect it's warning about, right? I realize that that increases the scope of this PR, but it feels counter productive to remove the warning and not the redirect imo.

True, true. I was trying be cautious on my unsanctioned just-because-I-couldn't-help-it-and-love-deleting-things side quest, but agree. Back to my rabbit hole...

**Review by etaderhold — APPROVED** [review]
The dialog box is clearly lying, so I think this is an improvement even if we maintain a silent redirect.

**Comment by Erin007** [comment]
Ok, I did a time-boxed investigation and I can meet you in the middle @bethanyaconnor I updated this PR to be a little more thorough - removed the mount point for unversioned redirect warning dialog and all of the state that we use to manage hiding/showing the dialog. The redirect code isn't super easy for my brain to parse and I don't want to unintentionally mess up any redirects that we _do_ want to keep, so I didn't fully go down the path of removing the redirect from unversioned unit urls.

**Comment by Erin007** [comment]
If we decide there is value in picking up this work again beyond my maniac personal obsession with digging around in the back of the metaphorical closets of the codebase, we could start [here](https://github.com/code-dot-org/code-dot-org/pull/46648) and even be extra cautious and look at the logs coming from [here](https://github.com/code-dot-org/code-dot-org/blob/048b83365d31b0429c891bf62aeda660df6abcad/dashboard/app/controllers/script_levels_controller.rb#L89) to ensure no one is still using the redirects.

**Pull request merged**
