### PR TITLE
Define restrictions to staging content commits.

### PR DESCRIPTION
**Pull request by ashercodeorg**
In particular, prevent committing video `mp4` files.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CC @tanyaparker: Are there any other classes of files we should be banning from commits on staging?

**Comment by tanyaparker** [comment]
Perhaps we can include `.mov` since that's the other top video file extension we use.

Somewhat related, is it possible to use this to restrict users from uploading image files as `.PNG` instead of `.png`? There are some cases where the capitalized extension doesn't work on our site/we won't show the image, and it could be an opportunity to force consistency.

**Comment by ashercodeorg** [comment]
Let me add another commit doing these two things.

**Comment by ashercodeorg** [comment]
Done. Feel welcome to take another look.

**Comment by tanyaparker** [comment]
Oh cool! Can we do `.JPG` and `.JPEG` then too? Not sure if we need both.

**Comment by ashercodeorg** [comment]
Done (per offline conversation, restricting any extension with non-lowercase letters). PTAL.

**Pull request merged**
