### PR TITLE
Removing unused jsdom and global-jsdom packages

### PR DESCRIPTION
**Pull request by jmkulwik**
Clearing out some unused packages from our package.json.

The jsdom and global-jsdom packages look like they were planned to be used when we started using react-testing library, but from what I can tell, we never ended up using them. I could definitely use an extra set of eyes on this one, in case we actually are using them in a way I missed. Additionally, I'm curious if anyone is planning to use these in the near-term future. Here's where the packages were first added: https://github.com/code-dot-org/code-dot-org/pull/51009

This was found using [depcheck](https://www.npmjs.com/package/depcheck)

### CODE REVIEW

**Comment by jmkulwik** [comment]
Note: Passed the original drone run. Rerunning to resolve some later merge conflicts. https://drone.cdn-code.org/code-dot-org/code-dot-org/1059

**Comment by lfryemason** [comment]
I found this documentation that suggests that `jsdom` and `global-jsdom` are required for running RTL in Mocha:
[docs](https://testing-library.com/docs/react-testing-library/setup/#using-without-jest).

The docs might be wrong since I would expect this PR to fail, but I would want further confirmation that this isn't required before merging

**Comment by jmkulwik** [comment]
> I found this documentation that suggests that `jsdom` and `global-jsdom` are required for running RTL in Mocha: [docs](https://testing-library.com/docs/react-testing-library/setup/#using-without-jest).
> 
> The docs might be wrong since I would expect this PR to fail, but I would want further confirmation that this isn't required before merging

Good call. That's a super helpful link. I took a look at that as well as the [jsdom](https://www.npmjs.com/package/jsdom) docs and the [global-jsdom](https://www.npmjs.com/package/global-jsdom) docs. From what I'm interpreting, it seems that jsdom and global-jsdom aren't required for all uses of RTL in Mocha; however, they are required if you want the same functionality as if you had a Jest setup with the `testEnvironment` set to `'jest-environment-jsdom'`. It looks like the two packages are useful in tests that need direct access to the document object (which we definitely have done in the past). However, since none of our RTL tests have utilized jsdom yet, and we haven't set it up globally, we don't hit test failures by removing it. 

My thought: jsdom appears to be the current industry standard for manipulation of the document object within RTL tests. However, since we aren't using it yet, I don't think we should tie ourselves to it yet. My vote would be to remove it: perhaps by the time we end up needing that functionality, it'll be built directly into RTL, or we'll be using Jest, or the industry will have moved to a different standard.

**Review by snickell — APPROVED** [review]
👍, if we're worried mostly about whether this breaks testing, its hard to argue with the tests passing 🤣 Agree with Jess that we can always add the dep back if we decide we want to use it in 2 weeks or 2 years.

Also... even if we kept it, now knowing what its for, it should be / have been in devDependencies.

**Review by levadadenys — APPROVED** [review]
We have quite unique RTL usage case 😄 (rtl+reconfigured chai) , not surprised we might not need something from documentation.
+1 to delete these if it doesn't break anything.
Also +1 to adding these as a devDependencies if we need it sometime.


Also a sidenote - RTL suggests not to manipulate DOM directly and use it's own queries instead, meaning removing these might help us in the future (one will try to use RTL native queries/functionality first before installing jsdom 😄 )

**Pull request merged**
