### PR TITLE
Reduce project gallery  UI  test flakiness

### PR DESCRIPTION
**Pull request by Erin007**
I spot checked the failing rounds of this UI test from yesterday's DTTs, and the majority of them were timing out on this step: `Then I wait until element "#ui-project-name" is in the DOM`, which ironically I only included to ensure that the element existed before I checked its contents.  However, my suspicion is that because there are multiple `"#ui-project-name"` in the DOM rather than just one, it's actually somehow hindering the tests. Furthermore, since there are multiple ui-project-name elements I've changed the id to a class. 

I ran these changes with the firefox, ie, safari and chrome_44 circle flags to ensure that they passed, and they did.

### CODE REVIEW

**Comment by davidsbailey** [comment]
Oops, sorry, I only just saw your comments in the PR description. Has the flakiness been happening in Circle or during DTTs? If this has not been confirmed to reduce flakiness in the place where we've seen it, then I'd recommend eliminating the duplicate ids.

**Comment by Erin007** [comment]
The flakiness happens in DTTs.

**Comment by Erin007** [comment]
welp. definitely didn't fix the problem, but not going to revert since it didn't make it any worse. 
screen shot 2018-04-04 at 2 21 04 pm

I'll continue investigating, but it might be low-ish priority.

**Comment by davidsbailey** [comment]
It looks like this UI test is assuming an empty gallery to start, but when I go to https://test-studio.code.org/projects/public right now, there are already many published projects. We wipe these out at the beginning of each DTT, but the gallery might not be empty when this test begins because:
* another instance of this test on another browser config may currently be running (or may have already run)
* another test which publishes projects may currently be running (or have already run)

things that could help mitigate this problem:
* only run this test in one browser
* add an init / cleanup step to unpublish / unfeature existing projects (may cause other tests to fail)
* modify the UI test to look for relative rather than absolute position in the gallery, checking that newly featured appears before recently published, but also allowing other projects from other tests to be intermingled

If existing published projects are the problem, then you can probably never repro it on circle, but you should be able to repro on your localhost.

I hope this helps, but feel free to prioritize this work accordingly / relative to the amount of pain its actually causing whoever is dev of the day.

**Comment by Erin007** [comment]
I have a background step `And I remove featured projects from the gallery` that wipes out all of the featured projects before each test run, and any new featured project should appear in the gallery first regardless of what else has been published recently or concurrently. So if the problem you're suggesting with published projects from other tests interfering is really the problem, it _should_ only affect my first test: `Published Projects Show In Recency Order`. The other two tests are specifically looking for featured projects. Does that sound accurate?

If I move forward with that assumption, what if I skip the first test for now, see if the flakiness resolves; and if it does, then circle back to re-enable that specific scenario with some of your suggestions?

**Comment by davidsbailey** [comment]
Good point, I missed that you already have a "remove featured projects" step. Agreed, that should help your second test pass. You could try disabling just the first test, however I've seen examples of the second test failing too ([1](https://cucumber-logs.s3.amazonaws.com/test/test/FirefoxLatest-2Yosemite_projects_project_gallery_output.html?versionId=Va6MH7bVbuuJ0c9iLwrQMc8RXS1pSrlf), [2](https://cucumber-logs.s3.amazonaws.com/test/test/IE11Win10_projects_project_gallery_output.html?versionId=eTdh.pQkMCatynVaKvA_Z1flrIyFiyN4)), so I don't think that will totally solve the problem.

Whether you do that or not, it could be useful to add some debug logging, e.g. print out the names of the first four projects in the public gallery. that might give us some better insight into what's going on.

In case it helps, here is an example of a different place we log things from javascript to the cucumber output: https://github.com/code-dot-org/code-dot-org/blob/d0fcdc152ff8dddf34f6b193f0a26af3e33fb071/dashboard/test/ui/features/step_definitions/steps.rb#L1109-L1111 it should be possible to use the selectors `$('. ui-project-name'):eq(0)`, `$('. ui-project-name'):eq(1)`, ... to get the first few project names.

**Pull request merged**
