### PR TITLE
Responsive(ish) yourschool

### PR DESCRIPTION
**Pull request by Erin007**
This applies some very lightweight styling to make /yourschool more responsive. 
responsive-yourschool

Note, this change affects the desktop view of the name and email fields. 
BEFORE:
desktop census form before

AFTER: 
desktop census from after

Also note: This does NOT handle responsiveness of the announcement, which will be on the page on ce DCDO flips.

### CODE REVIEW

**Comment by Erin007** [comment]
I'm viewing this as a temporary, but important, step. Temporary because when @breville makes /courses responsive in shortly upcoming changes there will be a framework that can be cross-applied here for the teal `ResourceCards`. With that change the `ResourceCards` will align in the middle of the screen rather than float left on mobile.  Important because we're expecting a big increase in users, many of whom will be on mobile devices, so we want these boxes at least stacked and legible in the interim even if they aren't aligned beautifully. 

@tanyaparker

**Comment by Erin007** [comment]
Ps. I don't know why the map isn't loading, but that's separate from this change.

**Comment by breville** [comment]
I'd be curious to see how this looks with the notification showing, just in case that single control forces a very wide width and we lose the benefits of this change otherwise.  Can you force it to show?

**Comment by Erin007** [comment]
The announcement doesn't force a wide width in this case; it just gets cut off. 
with announcement

**Comment by Erin007** [comment]
confirmed - the map should be fine, the issue on localhost was that I wasn't going to localhost.code.org:3000/yourschool so the google API was cranky because it didn't know the domain I was coming from.

**Pull request merged**
