### PR TITLE
Bring Baker Franke's odometer widget in as an External HTML level

### PR DESCRIPTION
**Pull request by joshlory**
This is an import of Baker Franke's odometer widget.  The widget reuses the "External HTML" DSL type which was added in #1271.

The original widget used an odometer library which is GPL v3 licensed.  GPL v3 is incompatible with the Apache License 2.0 that the rest of our curriculum is licensed under.  Other open source odometers I found didn't support radixes other than base 10.  I wrote a small odometer from scratch to avoid any future licensing issues.

screen shot 2015-05-05 at 2 17 18 pm

All credit to Baker for the widget. You can view his original widget here: http://cspdashboard-c9-bfranke.c9.io/Odometers/

### CODE REVIEW

**Comment by joshlory** [comment]
Besides fixing bugs it's probably not worth making too many changes to the imported code, but open to feedback!

**Comment by sfilman** [comment]
@joshlory Is it worth setting up an ngrok for me & Baker to look at it before it's on staging? It may just be worth waiting until it's on staging, but let me know.

**Comment by joshlory** [comment]
Sure, I can set up a tunnel tomorrow.

**Comment by islemaster** [comment]
That's awesome! :+1: I don't see anything that worries me.

**Pull request merged**
