### PR TITLE
Add Arabic and French

### PR DESCRIPTION
**Pull request by dju90**
## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dju90** [comment]
Out of curiosity, why do we always specify a language-locale like ar-ar in Curriculum Builder, but not always on Code Studio (/lang/ar works, but not /lang/ar-ar)?

**Comment by Hamms** [comment]
Code Studio has routing logic in place that can infer four-letter codes from two-letter codes.

CurriculumBuilder is just an S3 bucket with a bunch of static HTML files

**Review by Hamms — COMMENTED** [review]
The new languages should also be removed from the `additional_languages` list

**Comment by dju90** [comment]
> The new languages should also be removed from the `additional_languages` list

Ah it looks like the previous entry in `additional_languages` was ar-sa. Should I change it to ar-sa in both https://github.com/code-dot-org/curriculumbuilder/pull/312 and here?

**Comment by Hamms** [comment]
Oh, yes please!

**Review by Hamms — APPROVED** [review]

**Pull request merged**
