### PR TITLE
Rename default template from 'default' => 'custom' to match other apps, ...

### PR DESCRIPTION
**Pull request by islemaster**
...remove additional templates, fill out level files with values for all parameters.

Hoping this change will make it easier for the Ed team to build on the existing NetSim levels.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Is there any risk that these levels are also being editting on LB and will conflict?

If not, LGTM

**Comment by islemaster** [comment]
Only for `NetSim_SendingABTest.level` and even then I think it's unlikely.  This might be a breaking change to a couple other netsim scratchpad levels on levelbuilder, but they should be easy enough to correct after a merge.

**Comment by islemaster** [comment]
Found a couple more levels that needed changes and an important change in the `net_sim.rb` model.

**Comment by Bjvanminnen** [comment]
In general we try to avoid editing .level files outside of levelbuilder so that we don't have to worry about merge conflicts. Might be good for you to manage the LB/staging merge once your changes are in so that you can be sure to address any conflicts.

**Comment by islemaster** [comment]
Okay.  We probably won't merge to LB again until tomorrow, I could do that myself first thing.  I'm optimistic that the merge will be straightforward; I'm editing .level files that were originally created outside of levelbuilder (my own example levels) and, in the few cases where I'm not, I am only changing the value of a field that you can't modify from within levelbuilder.

**Comment by Bjvanminnen** [comment]
:+1:

**Pull request merged**
