### PR TITLE
Progress: style the lesson of interest column

### PR DESCRIPTION
**Pull request by Erin007**
column-of-interest

### CODE REVIEW

**Comment by Erin007** [comment]
Given that we can also now [scroll precisely to the column of interest](https://github.com/code-dot-org/code-dot-org/pull/21901/files), rather than just scroll it somewhere into the view, do we still want conditional styling for the column of interest? If so, how do we feel about the teal with white and slightly bigger font (it seemed to be the standout option from @tanyaparker 's mock ups in the design Slack channel).  Do we want something similar for the DetailView? @poorvasingal

**Comment by caleybrock** [comment]
If we keep jump to lesson on the summary view, I think we'll still want it, especially since sometimes when a lesson is near the end there isn't enough space for it scroll to the front. 

If jump to lesson is only on detail view, or just jumps to the detail from summary, having a teal column header feels a little bold since it'll take up so much space. Not totally sure.

Code LGTM so if we get a 👍 from Poorva/Tanya, feel free to merge.

**Comment by poorvasingal** [comment]
This looks good and I'm fine shipping it for now, but my guess is that we're going to land on not using this to scroll in the summary view itself.

**Comment by Erin007** [comment]
Merging this now - we can get feedback and remove if needed once we have a solid plan about if we want the jump to lesson dropdown here, etc.

**Pull request merged**
