### PR TITLE
Music: fix small validation bug

### PR DESCRIPTION
**Pull request by sanchitmalhotra126**
## Warning!!

The [AP CSP Create Performance Task](https://apcentral.collegeboard.org/courses/ap-computer-science-principles/exam) is in progress. The most critical dates are from April 3 - April 30, 2024. Please consider any risk introduced by this PR that could affect our students taking AP CSP. Code.org students taking AP CSP primarily use App Lab for their Create Task, however a small percent use Game Lab. Carefully consider whether your change has any risk of alterering, changing, or breaking anything in these two labs. Even small changes, such as a different button color, are considered significant during this time period. Reach out to the Student Learning team or Curriculum team for more details.

## Description

Fix a small validation bug spotted in the elementary pilot. When a student plays multiple sounds together, we should consider the "played_sounds_together" conditions satisfied if they played the required number of sounds or more. However, we were accidentally only checking the exact number of sounds, and so if they played more than the passing threshold, they wouldn't pass the level.

## Links

https://codedotorg.slack.com/archives/C043WM7TCH3/p1713295216389199

## Testing story

Tested with elementary and intro progression.

### CODE REVIEW

**Review by thomasoniii — APPROVED** [review]
lgtm 🚀

**Review by breville — APPROVED** [review]
Thanks for this.  I think the original design was intentional so that we didn't create an unbounded number of satisfied conditions, but this change seems reasonable.

**Comment by sanchitmalhotra126** [comment]
> Thanks for this. I think the original design was intentional so that we didn't create an unbounded number of satisfied conditions, but this change seems reasonable.

Fair point, and I don't mind reinstating the limit if you think it's a good idea? The issue was just that we were just using the wrong variable - I just removed the limit as an added change while I was here.

**Comment by breville** [comment]
> > Thanks for this. I think the original design was intentional so that we didn't create an unbounded number of satisfied conditions, but this change seems reasonable.
> 
> Fair point, and I don't mind reinstating the limit if you think it's a good idea? The issue was just that we were just using the wrong variable - I just removed the limit as an added change while I was here.

Oh this seems alright.  I think there's a bigger architectural discussion about how we can have conditions that are a bit more expressive, but that can be done separately!

**Pull request merged**
