### PR TITLE
asset:sync fix: skip digesting already-digested webpack assets

### PR DESCRIPTION
**Pull request by wjordan**
This PR swaps out the `asset:no_digests` postprocessing task for a targeted patch to the `Sprockets::Asset` class, which causes Sprockets to write already-digested webpack-assets to an identical filename in its output directory.

The code is a bit shorter, but more importantly, this makes the assets available in the Sprockets manifest under their original webpack-generated filename, which will cause them to be picked up and processed by the custom `assets:sync` task and uploaded to S3 as expected.

I updated the comment, and added a note (which was also true in the old implementation):

> This means that the digest for these assets is based on the webpack content
> and not the Sprockets-processed output, so the wp-digest will not get
> updated if there are any changes to Sprockets processors.

Followup to #26568, #15316

### CODE REVIEW

**Review by islemaster — COMMENTED** [review]
I want to make sure I understand the tradeoff here.

**Before:** It looks like the `no_digests` task was already solving the problem by copying the double-digested version to the webpack-digest path; but this stopped happening on production, so did we start skipping the `no_digests` task somehow?

**New approach:** Patch Sprockets to never add a digest to webpack-digested assets.  Con: Changes to our Sprockets preprocessors won't cause these asset digests to change because we're skipping this step.  Question: Wasn't that also a problem with the previous approach, assuming clients were always requesting the file with only the webpack digest anyway?

**Comment by wjordan** [comment]
> did we start skipping the no_digests task somehow?

No, what changed in #26568 was that instead of scanning the _filesystem_ for (all) assets to sync to S3, the `:sync` task now scans the _Sprockets manifest_ for (only newly-added) assets to copy. Only the double-digest asset ended up in the Sprockets manifest, not the one output by the `no_digests` file-copy.

> Con: Changes to our Sprockets preprocessors won't cause these asset digests to change because we're skipping this step. Question: Wasn't that also a problem with the previous approach, assuming clients were always requesting the file with only the webpack digest anyway?

Yes, I mentioned this was 'also true in the old implementation' in the PR [description](https://github.com/code-dot-org/code-dot-org/pull/26788#issue-248328020). We just didn't call this out specifically in the previous code-comment. So this isn't a con compared to the previous approach, really.

**Review by islemaster — APPROVED** [review]
Sweet, thanks for clarifying and sorry I didn't get it the first time around.  With that context, this approach looks good to me!

**Comment by wjordan** [comment]
also one more note: we're not skipping the Sprockets processing step (either before or after this PR), here we're just tweaking the output filename so that it doesn't append the SHA256 digest to it. The output image should still be compressed by the `image_optim` processor before it gets uploaded to S3.

**Comment by islemaster** [comment]
:+1: I had that misconception the first time I read through this, then realized my mistake (since it's important that we still do the preprocessing, etc). I see I echoed the concept back incorrectly.  I meant to say we "skipped" appending the digest but even that isn't really correct. I suppose it's more accurate to say we're monkeypatching that digest-naming step so it runs but in some cases is a no-op.

**Comment by wjordan** [comment]
> we're monkeypatching that digest-naming step so it runs but in some cases is a no-op.

Not quite a no-op- even without the processor step, the pipeline reads assets from their source paths (in this case `[Rails.root]/public/blockly`, which is a symlink to `/apps/build/package`) and writes them to the precompiled-asset destination path (`[Rails.root]/public/assets`). So in this case, `public/blockly/js/imagewp[md5].png` gets written to `public/assets/js/imagewp[md5].png`.

(Previously, it was written to `public/assets/js/imagewp[md5]-[sha256].png`, then copied over to `public/assets/js/imagewp[md5].png`.)

Or I guess it's a no-op, in that the 'digest path' is unchanged from the 'logical path'.

**Comment by islemaster** [comment]
:bulb: Got it.  That context (that we're still performing a copy from one place to another) is helpful.  Thanks!

**Pull request merged**
