### PR TITLE
Fix continue button on external video levels

### PR DESCRIPTION
**Pull request by Erin007**
## Description
[LP-952](https://codedotorg.atlassian.net/browse/LP-952)

Previously the continue button on external video levels was not advancing the user to the next level in the progression as reported on [Zendesk](https://codeorg.zendesk.com/agent/tickets/254782). 

Now, it is: 
continue-continues

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [x] Code is well-commented
- [x] New features are translatable or updates will not break translations
- [x] Relevant documentation has been added or updated
- [x] User impact is well-understood and desirable
- [x] Pull Request is labeled appropriately
- [x] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by dmcavoy — APPROVED** [review]
🎉 

Does this case need a regression test?

**Comment by davidsbailey** [comment]
> Does this case need a regression test?

Generally yes, bug fixes should have regression tests when it's not too difficult to add one. @Erin007  I think you could add one pretty easily by copying this example: https://github.com/code-dot-org/code-dot-org/blob/95145abc11e7b34453f2228e6c80f558d0baebde/dashboard/test/ui/features/videoplayer_eyes.feature#L49 

when pressing buttons that use page navigations, you should use the `to load a new page` steps like these to make sure you wait for the page transition before checking the new url:
Screen Shot 2019-11-06 at 9 44 48 AM

**Comment by Erin007** [comment]
Added a quick test to cover this scenario. Thanks for the suggestions!

**Comment by davidsbailey** [comment]
👍 looks great!

**Pull request merged**
