### PR TITLE
Strip display and family names before save

### PR DESCRIPTION
**Pull request by rshipp**
Strip starting and trailing whitespace from `user.name` (display names) and `user.properties['family_name']` in a `before_save` callback. Fixes some strange display/sorting behavior in the UI.

Turns out we can do this on the serialized `properties` without any extra effort, so I went with Eric's suggestion of doing it in the model rather than making sure to catch every place in the controller(s).

Tagging platform/infra for optional review because this is a model change, just in case you know of something this could break.

## Links

- jira ticket: [TEACH-648](https://codedotorg.atlassian.net/browse/TEACH-648)

### CODE REVIEW

**Review by etaderhold — APPROVED** [review]
LGTM!

**Review by Hamms — COMMENTED** [review]
This doesn't look like it'll break anything to me! I am curious, though; do we have any desire to apply this retroactively to existing `name` and `family_name` values? I do note that right now, this only applies as things are being changed.

**Comment by dju90** [comment]
I'll create a follow-up clean up task for existing display names and family names. If we write and run a script for that, will there be any downtime concerns since Users is such a large table?

**Comment by dju90** [comment]
One concern I can think of is that the `updated_at` timestamp will suddenly be around the same for a large number of accounts. Not sure how problematic that would be.

**Comment by Hamms** [comment]
Any attempt to comprehensively update all existing entries should absolutely be done in a way that avoids touching the `updated_at` timestamp, and given our total number of users could be prohibitive.

I was more thinking, why are we only attempting to strip the fields when the fields change? As-is, we will only strip whitespace from the name when the name is specifically being updated. Is there any reason not to apply this change on _every_ save? My understanding of ActiveRecord (which should be verified) is that it will detect when assigning to a field whether or not that assignment represents an actual change or is a no-op, so executing `self.name = name.strip` on every save should effectively apply this fix to all active user accounts.

**Comment by cat5inthecradle** [comment]
> Any attempt to comprehensively update all existing entries should absolutely be done in a way that avoids touching the `updated_at` timestamp, and given our total number of users could be prohibitive.

[Update_columns](https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_columns) perhaps? Or would it make sense to do something like this in a migration and run something like `UPDATE users set name = TRIM(name);`

**Comment by rshipp** [comment]
> why are we only attempting to strip the fields when the fields change?

I don't have a strong reason for this, I just thought it would be less intrusive. the issue we're trying to solve is mostly for a new feature that's not live yet, so I wasn't really concerned with fixing old data. if we'd rather do it without the `will_save_change` checks, i'm happy to make that change

**Comment by Hamms** [comment]
I don't have a strong preference either way, just wanted to call out some of the minor implications of this implementation.

**Comment by rshipp** [comment]
i'll go ahead and merge this, then. we can always remove the checks later, if we decide we want to apply it more liberally.

**Pull request merged**
