### PR TITLE
Remove AFE teacher of the year banner

### PR DESCRIPTION
**Pull request by maureensturgeon**
Removes AFE teacher of the year banner.

Reverts adding the banner here https://github.com/code-dot-org/code-dot-org/pull/39080 (but keeps the refactor and actual banner for future use)
## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bencodeorg** [comment]
Is this a straight revert of the PR to add the banner?

**Comment by maureensturgeon** [comment]
> Is this a straight revert of the PR to add the banner?

No, there was a refactor of the banner component in that PR, I also left the AmazonTeacherOfYearBanner component because we plan on using it again in the future. 

Here is the original PR https://github.com/code-dot-org/code-dot-org/pull/39080

**Comment by jamescodeorg** [comment]
To what extent will the code that we add the next time we turn this on be the same as the code you're removing now?  I'm wondering if we should just hide the banner behind a switch or something if it's something we'll want to turn on/off annually?

**Comment by jamescodeorg** [comment]
Also, side note, next year we'll have to use a different flag in local storage because this year's flag will persist indefinitely, right?

**Comment by maureensturgeon** [comment]
> To what extent will the code that we add the next time we turn this on be the same as the code you're removing now? I'm wondering if we should just hide the banner behind a switch or something if it's something we'll want to turn on/off annually?

Yes, we'll have to use a different flag. I guess I was trusting the developer who implements this next time to realize that. I'm not sure if we'll want the logic of how and where it appears to be the same next year, so I removed all of that as not to clutter the TeacherHomepage component.

I did actually consider leaving all the logic and just setting the show/hide to false with a comment, but it felt messy to leave all of that unused code there for a year, so I decided to remove it.

**Comment by jamescodeorg** [comment]
Sounds good for now.  I think this is something we can talk about at some point.  A lot of the website changes are annual in nature and it'd be good to establish some common patterns around how to handle that (preferably with as little engineer intervention as possible each year :-)

**Review by bencodeorg — APPROVED** [review]

**Pull request merged**
