### PR TITLE
Remove duplicate level file

### PR DESCRIPTION
**Pull request by islemaster**
Both of these files existed, and had duplicate contents:

- `dashboard/config/scripts/levels/AppLab Intro 4 - Video onEvent.level`
- `dashboard/config/scripts/levels/AppLab Intro 4 - video onEvent.level`

image 4

Our seeding code was implicitly deduplicating these.  On levelbuilder, it shoulds up with a capitalized `Video` so I'm deleting the lowercase one.

image 5

### CODE REVIEW

**Comment by davidsbailey** [comment]
also, dashboard/config/locales/markdown_instructions.en.yml appears to refer to the capitalized version, and I don't see any references to the lower case. 👍

**Comment by Hamms** [comment]
Oh, hmm, I actually _was_ able to find a reference to the lower-case version; both in that file and on Crowdin itself.

That being said, I don't think that should prevent us from moving forward; it is not really that different from just destroying an existing level from an i18n perspective.

**Comment by davidsbailey** [comment]
because this files AFAIK just appears in markdown instructions, it seems like the amount of damage we could do by removing the wrong one is minimal. we should be very careful if this happens again on a level that users have progress on.

**Comment by davidsbailey** [comment]
After syncing past this PR on staging, I see the following in my git client on OS X:

* screen shot 2018-07-19 at 4 37 19 pm

easily resolved via `git checkout 'dashboard/config/scripts/levels/AppLab Intro 4 - Video onEvent.level'`.

**Comment by islemaster** [comment]
Oh, weird.  Sorry about that!

**Pull request merged**
