### PR TITLE
Music: fix repeat translation

### PR DESCRIPTION
**Pull request by breville**
This updates the Music Lab `repeat` block to [use](https://developers.google.com/blockly/guides/configure/web/translations#:~:text=To%20reference%20the%20translated%20string%20in%20your%20block%2C%20use%20Blockly.Msg%5B%27HELLO%27%5D%20which%20should%20contain%20the%20string%20for%20the%20locale%20you%27ve%20configured.) Google Blockly's [strings](https://github.com/google/blockly/blob/1a1face205a5ed5acdbc088136f272413343aa01/msg/messages.js) and their [translations](https://github.com/google/blockly/tree/1a1face205a5ed5acdbc088136f272413343aa01/msg/json).

### CODE REVIEW

**Review by mikeharv — COMMENTED** [review]
Is there a thread or other link with context about this change? I found a [thread](https://codedotorg.slack.com/archives/C04TH8400AU/p1716230254956089) from yesterday about correcting a translation for the `play sound` block, but that seems to already have been [resolved](https://github.com/code-dot-org/code-dot-org/pull/58779) or at least [in progress](https://github.com/code-dot-org/code-dot-org/pull/58778).

Is there a mis-translation we are hoping this will fix?

**Comment by sanchitmalhotra126** [comment]
> Is there a thread or other link with context about this change? I found a [thread](https://codedotorg.slack.com/archives/C04TH8400AU/p1716230254956089) from yesterday about correcting a translation for the `play sound` block, but that seems to already have been [resolved](https://github.com/code-dot-org/code-dot-org/pull/58779) or at least [in progress](https://github.com/code-dot-org/code-dot-org/pull/58778).
> 
> Is there a mis-translation we are hoping this will fix?

We're noticing that this string doesn't appear translated when the language on the page changes. My understanding was that the "BKY_CONTROLS_REPEAT_TITLE" Blockly string would be translated automatically by Blockly, but is there some other configuration we're missing here?

**Comment by breville** [comment]
> > Is there a thread or other link with context about this change? I found a [thread](https://codedotorg.slack.com/archives/C04TH8400AU/p1716230254956089) from yesterday about correcting a translation for the `play sound` block, but that seems to already have been [resolved](https://github.com/code-dot-org/code-dot-org/pull/58779) or at least [in progress](https://github.com/code-dot-org/code-dot-org/pull/58778).
> > Is there a mis-translation we are hoping this will fix?
> 
> We're noticing that this string doesn't appear translated when the language on the page changes. My understanding was that the "BKY_CONTROLS_REPEAT_TITLE" Blockly string would be translated automatically by Blockly, but is there some other configuration we're missing here?

Following our further [discussion](https://codedotorg.slack.com/archives/C04TH8400AU/p1716328810133539), I've updated the PR to use Blockly's strings for this block in all languages.  By using Blockly's strings, we'll ensure that occurrences of the block are consistent across all labs, in english or otherwise.

**Comment by breville** [comment]
> > Is there a thread or other link with context about this change? I found a [thread](https://codedotorg.slack.com/archives/C04TH8400AU/p1716230254956089) from yesterday about correcting a translation for the `play sound` block, but that seems to already have been [resolved](https://github.com/code-dot-org/code-dot-org/pull/58779) or at least [in progress](https://github.com/code-dot-org/code-dot-org/pull/58778).
> > Is there a mis-translation we are hoping this will fix?
> 
> We're noticing that this string doesn't appear translated when the language on the page changes. My understanding was that the "BKY_CONTROLS_REPEAT_TITLE" Blockly string would be translated automatically by Blockly, but is there some other configuration we're missing here?

Following our further [discussion](https://codedotorg.slack.com/archives/C04TH8400AU/p1716328810133539), I've updated the PR to use Blockly's strings for this block in all languages.  By using Blockly's strings, we'll ensure that occurrences of the block are consistent across all labs, for all languages.

**Review by mikeharv — APPROVED** [review]

**Review by thomasoniii — APPROVED** [review]
lgtm 🚀

**Review by sanchitmalhotra126 — APPROVED** [review]

**Pull request merged**
