### PR TITLE
studio.code.org: redirect to /home if signed in, otherwise /courses

### PR DESCRIPTION
**Pull request by breville**
This revisits the changes of https://github.com/code-dot-org/code-dot-org/pull/17350 so that, when visiting https://studio.code.org, signed in users are taken to /home, and signed out users are taken to /courses.

### CODE REVIEW

**Comment by tanyaparker** [comment]
fyi @poorvasingal

**Comment by Erin007** [comment]
Is the change we really want #17470 where students go to the course overview page for their top course?

**Comment by tanyaparker** [comment]
Yes, we want this change and yours in #17470. This change is a better experience for signed out users (goes to /courses) and teachers (goes to /home). For signed-in students, studio.code.org should still redirect to studio.code.org/home. But, the first time they log in (if they have an assigned course) takes them to their course overview/script page. These two redirects should be independent. So a signed in student going to studio.code.org shouldn't be taking them to their course overview page. That should still be going to /home.

**Comment by breville** [comment]
So this implementation is currently missing this part of the scenario: ```But, the first time they log in (if they have an assigned course) takes them to their course overview/script page.```  

Currently we have such functionality for word/picture accounts (using the code at https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/controllers/sections_controller.rb#L31-L34) upon every log in; we'll need to build something similar for all accounts but for first time log in only.

**Comment by breville** [comment]
From talking to @tanyaparker we've decided to merge this in as-is, with more of the above-described work to come later.

**Pull request merged**
