### PR TITLE
Make regional_partner_mappings paranoid

### PR DESCRIPTION
**Pull request by molly-moen**
Pre-work for [PLC-730](https://codedotorg.atlassian.net/browse/PLC-730) and follow-up to [33030](https://github.com/code-dot-org/code-dot-org/pull/33030)
Make regional_partner_mappings table paranoid to facilitate undo of bad mapping updates. The required migration was done in PR listed above.

## Links
- [jira](https://codedotorg.atlassian.net/browse/PLC-730)

## Testing story
Validated that mappings are now correctly soft-deleted.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by islemaster — APPROVED** [review]

**Review by breville — APPROVED** [review]

**Comment by bencodeorg** [comment]
@agealy might want to get this on @boatmarina's radar before we start using it -- we use these mappings in a lot of Tableau reports to regional partners (eg, which schools they see when they look at a map of schools in their region).

I think we assume that a zip code will only be mapped to a single partner -- this PR lets us start "soft deleting" mappings (ie, we keep the row, but assign a `deleted_at` timestamp to keep track of which ones have been deleted). As a result, we'll eventually have 2+ rows in the `pd_regional_partner_mappings` table mapping the same zip code to multiple partners (where one has been "soft deleted" and the other has not). Probably as easy as finding queries where we use these mapping and adding a `deleted_at is null` filter, but worth keeping on our radar.

**Comment by molly-moen** [comment]
Thanks @bencodeorg, yes if we have queries on the table we will need to make sure deleted_at is null to keep them up to date.

**Comment by bencodeorg** [comment]
Molly is responding ^^^ to this comment, which I accidentally deleted:

> 
> Andrew, might want to get this on Marina's radar before we start using it -- we use these mappings in a lot of Tableau reports to regional partners (eg, which schools they see when they look at a map of schools in their region).
>
> I think we assume that a zip code will only be mapped to a single partner -- this PR lets us start “soft deleting” mappings (ie, we keep the row, but assign a deleted_at timestamp to keep track of which ones have been deleted). As a result, we’ll eventually have 2+ rows in the pd_regional_partner_mappings table mapping the same zip code to multiple partners (where one has been “soft deleted” and the other has not). Probably as easy as finding queries where we use these mapping and adding a deleted_at is null filter, but worth keeping on our radar.

**Comment by agealy** [comment]
Makes sense, good call out @bencodeorg

**Pull request merged**
