### PR TITLE
Show versioned course name on teacher homepage

### PR DESCRIPTION
**Pull request by davidsbailey**
### Background

bug bash feedback on curriculum versioning is that the course version suffix `'17-'18` or `'18-'19` should appear in the Course column on the teacher homepage. EDIT: `'17-'18` or `'18-'19` should now also appear in the version selector on the course overview page (see screenshots).

Also see https://github.com/code-dot-org/code-dot-org/pull/22113 and [terminology comparison spreadsheet](https://docs.google.com/spreadsheets/d/1naiSH_RfWw-RijhbWKy4ZwNOctZBtd2Cm7RegL0bPdY/edit#gid=0) for more context

### Description

The solution is for the server to 
* add the version suffix to the assignment (course or script) title, e.g. "CS Principles" --> "CS Principles '17-'18"
* also provide the title of the "assignment family" (e.g. "Frozen", "Course A", "CS Principles", "CS Discoveries") without a version suffix, rather than trying to infer it from the assignment title which now has a version suffix

### screenshots

| before | after |
|---|---|
| screen shot 2018-05-09 at 11 25 56 pm | screen shot 2018-05-09 at 11 26 17 pm |
| assignment-family-title-before | no change |
| screen shot 2018-05-09 at 4 50 31 pm |  screen shot 2018-05-10 at 8 29 14 am 
 |

### CODE REVIEW

**Comment by davidsbailey** [comment]
Also no change to the category names in the script selector dropdown in the progress tab, which come from a different place entirely (pegasus)

screen shot 2018-05-09 at 11 41 56 pm

**Comment by davidsbailey** [comment]
I'm sneaking one more thing into this PR: the version selector on the course page now shows '17-18 or '18-'19 instead of 2017 or 2018. I've updated the screenshots in the PR description to reflect this.

**Comment by caleybrock** [comment]
Why doesn't the section edit screenshot (the second one) have `2017` instead of `17-18` like the others?

**Comment by davidsbailey** [comment]
Great question @caleybrock ! the "edit section" screenshot will require some additional changes to the AssignmentSelector. I have started on those in a separate PR.

**Pull request merged**
