### PR TITLE
update UK page to have David Cameron as first homepage image

### PR DESCRIPTION
**Pull request by tanyaparker**

### CODE REVIEW

**Comment by breville** [comment]
is this desired pixel size & file size?  (i.e. cost-effective? :)

**Comment by tanyaparker** [comment]
The other homepage images are
- 1200x675 (189 KB)
- 1440x960 (387 KB)
- 1440x962 (355 KB)
- 2800x1924 (275 KB)
- 2880x1378 (6.1 MB)
- 5760x3840 (4.7 MB)

At 1800x1200 (1 MB) I thought it was in a good range. No?

**Comment by breville** [comment]
That seems reasonable, though seems like we should be able to get it below 500 KB without quality change if the others are all in the 200-400KB range).  

We should definitely reduce the size of those big two if we're ever actually serving them.  (Are we?)

**Comment by tanyaparker** [comment]
Gotcha. The 6.1 MB is Malala and the 4.7 in unused. Will follow up with adjustments in another PR.

**Comment by breville** [comment]
Of course, the important thing is the size of what we serve.  It's fine to have large master images if we're getting Pegasus to resize & reencode to a smaller file when it serves.

**Pull request merged**
