### PR TITLE
Add a basic eyes test for printable lesson plans

### PR DESCRIPTION
**Pull request by Hamms**
Specifically:

- Add some javascript which emulates viewing the page in print mode (sourced from [this SO answer](https://stackoverflow.com/a/24144530/1810460))
- Add a URI param which conditionally includes that JS
- Write an Eyes test which includes said URI param

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by davidsbailey — APPROVED** [review]
This looks awesome! Nice find!

**Review by dmcavoy — APPROVED** [review]
Thanks for adding this test!

**Comment by Hamms** [comment]
Looks like the test is failing because `allthemigratedthings` isn't seeded on Drone. Anyone know how to change that?

**Comment by dmcavoy** [comment]
@Hamms there is a fix for this in Jillians Create Student Lesson Plan Page PR. You have to add it to the seed list for UI tests. https://github.com/code-dot-org/code-dot-org/pull/39136/commits/8919a6d32988b5aa751f513f543860fb8d120f99

**Pull request merged**
