### PR TITLE
hoc2015: show beta in header, and shrink text on small devices.

### PR DESCRIPTION
**Pull request by breville**

### CODE REVIEW

**Comment by breville** [comment]
We're adding a beta tag to the header for our new tutorial.

Even without it, the length of the tutorial name was causing text to run out of space on 1024-wide screens.

screenshot 2015-11-06 12 55 43

So this change also shrinks the text on such devices.

screenshot 2015-11-06 13 25 21

Definitely not my favourite idea for an implementation (having a script name in .haml like this is gross) but this is coming in pretty hot.  The beta tag will go away soon.  The text shrinking will likely be useful for some other scripts going forward.

**Comment by breville** [comment]
fyi @philbogle

**Comment by breville** [comment]
fyi @laurelfan

**Comment by davidsbailey** [comment]
Sorry for the delay in responding to this. css and haml all looks ok to me, but I'm not sure I have the expertise to spot a problem with the haml.

**Pull request merged**
