### PR TITLE
App Lab dropdown index property

### PR DESCRIPTION
**Pull request by larrypo**
This change implements the "index" property on a dropdown control. Initially set to 0, it can be set in design mode or via setProperty, and read via getProperty. If set out of bounds, by default it will get set to -1, and nothing will be selected.

### CODE REVIEW

**Comment by islemaster** [comment]
Tests for this feature?

**Comment by epeach** [comment]
This looks good, but I agree with Brad - I'd love to see some tests for this feature.

**Comment by larrypo** [comment]
Tests, smests.

OK, I'll do them next week.

I've also been rethinking the correct behavior for out of bounds assignments. Rather than set to -1, perhaps it should be unchanged? Can it show an error message somewhere? When I change a width property to a negative value, it doesn't change, but I don't see an error message. I'll discuss with when I'm back in the office.

**Comment by epeach** [comment]
Thanks for adding those tests! I was reading your comment from last week about the correct behavior when the index is out of bounds and I like your suggestion of a useful error message and no change. I'm not sure from a curriculum stand-point, but if the input is out-of-bounds and -1 is out-of-bounds, then I'm not sure what is gained by switching from one out-of-bounds situation to another, other than that -1 is slightly more obviously out-of-bounds. Thoughts?

**Comment by islemaster** [comment]
Looks good!  I've started a test build, and will merge when it passes!

**Comment by islemaster** [comment]
Whoops!  Sorry for merging without having your last comment addressed, @epeach.  @larrypo what do you think?  Can we look at the error message in a follow-up pull request?

**Pull request merged**
