### PR TITLE
seed standards in all frameworks from new csv files

### PR DESCRIPTION
**Pull request by davidsbailey**
Finishes [PLAT-762]. For more background, see [Lesson Standards design doc](https://docs.google.com/document/d/1zvdv7y8VuRz8KqT1rzqeJAmvirCvUr1jS8OWy0p9FHk/edit#).

This PR starts seeding all standards from the new config files in https://github.com/code-dot-org/code-dot-org/tree/staging/dashboard/config/standards, and removes the old seed methods and input file.

## Testing story

* automated tests cover seeding from scratch
* Manually verified that running new seed process on my local DB does not modify the contents or ids of existing CSTA standards

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

[PLAT-762]: https://codedotorg.atlassian.net/browse/PLAT-762

### CODE REVIEW

**Comment by davidsbailey** [comment]
I did notice that there are more CSTA standards created by the new seed process than there were in the old seed process. I couldn't find place that this would appear to the user so I think we are good here. @Erin007 if you can think of a place I might have missed where we might show all CSTA standards to the user, please let me know.

**Comment by Erin007** [comment]
> I did notice that there are more CSTA standards created by the new seed process than there were in the old seed process. I couldn't find place that this would appear to the user so I think we are good here. @Erin007 if you can think of a place I might have missed where we might show all CSTA standards to the user, please let me know.

The only place I know of where we show standards is the CSF Standards Report generated from the Progress View of the Teacher Dashboard.  There are pages like [this one](https://curriculum.code.org/csf-19/standards/) on curriculum builder, but there isn't a general list of all standards anywhere in Code Studio.  The old standards csv was specific to CSF 2019-2020 so it's reasonable that the additional CSTA standards you're seeing are for 2020-2021 or another course. Regardless, it's better to have them and not need them than need them and not have them, so I think you're good to go with the extras 👍

**Comment by dmcavoy** [comment]
I looks like this is based off the removing deprecated columns PR. Any chance you could base it off that for easy review?

**Comment by davidsbailey** [comment]
@dmcavoy the base has been updated.

**Review by dmcavoy — APPROVED** [review]

**Pull request merged**
