### PR TITLE
Fix styling for long description

### PR DESCRIPTION
**Pull request by megcrenshaw**
Fixes an error in styling.

Old version: 
image

Updated but still wrong:
Screen Shot 2022-04-04 at 9 28 00 AM

Final version:
image

## Links

- spec: https://codedotorg.atlassian.net/browse/PLAT-1637

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dmcavoy** [comment]
Thanks for improving Meg! I don't think this needs to be blocking but I'm wondering if the button should be centered in the height of the area?

**Review by dmcavoy — APPROVED** [review]

**Review by tim-dot-org — APPROVED** [review]
same comment as dani, I think its the 'marginTop' rule that's causing the offset

**Comment by megcrenshaw** [comment]
Ah, strong point! Will fix––thanks

**Comment by megcrenshaw** [comment]
See screenshot for updated version

**Pull request merged**
