### PR TITLE
Allow LBs to give external levels map/stop icons

### PR DESCRIPTION
**Pull request by Bjvanminnen**
It's worth noting that though this PR is related to progress redesign work, it will also affect existing views (once level builders start giving levels stop and map icons).

I also moved a bunch of JS out of all.html.haml and into a JS file.

Let LevelBuilder's specify that external level should have a different icon
image

Some screens of what these look like
image
image
image

image
image
image

### CODE REVIEW

**Comment by joshlory** [comment]
Any reason these shouldn't be their own level types?  Additional types are super cheap to create, and if these have different classes of behaviors it's helpful to be able to find all the levels of a given type.

**Comment by Bjvanminnen** [comment]
I suspect you have a better sense of the differences/similarities between all of the different dsl based levels than I do, and whether or not they should be unified. If I were to break this out, I would presumably need to either duplicate the next few lines in dsl.html.haml (https://github.com/code-dot-org/code-dot-org/pull/13214/files#diff-1514f30aa6e8764312feafd5e50f793fR43) in my external version, or make them a partial included in both. Thoughts?

**Comment by Bjvanminnen** [comment]
Realizing I might have misunderstood the question. Are you actually asking if Map/Stop should be their own level types? If so, it seems unnecessary given that the only difference between them and other External levels is the icon that they show.

**Comment by joshlory** [comment]
Will the `stop` levels always have the same content?  (E.g. "Wait here until your teacher tells you to keep going")

**Comment by Bjvanminnen** [comment]
@poorvasingal Do you know the answer to Josh's question?

**Comment by mrjoshida** [comment]
No, stop levels each have unique content. Sometimes it's just wait, sometimes it's some additional challenges to work on while you wait

**Comment by poorvasingal** [comment]
A couple of things: 
1) A bunch of these levels have already been created.  It'd be easier if LBs could just go in and change the icon they want to use.
2) The only difference these levels have is their icon type.  True, there might end up being other differences later but can't we query based on which icon they chose?  
3) We might want to extend the stop concept to other levels later.  For example, we've discussed making a normal programming level a "Stop" level so that the student knows to stop on that level once they get there. 

Thoughts based on this?

**Comment by joshlory** [comment]
Even if there is existing content, it's easier to switch that content over at the time the new type is created (vs. having to do the same work + any additional levels that have been created in the interim).

That said, I don't have objections to merging this change as-is.  My caveat is that we've had this request before (allow level builders to chose a specific icon) and it's always turned out that the levels were distinct enough it was worth creating a new type.  New level types are very cheap to create, and moving existing levels over is work that will only get harder as more levels are created that will need to be moved.

**Comment by joshlory** [comment]
To summarize the offline discussion:

I feel strongly that `Level` types are very cheap to add, and this is the correct way to implement polymorphism in the Single Table Inheritance `:levels` table.  Even if the new type is as simple as:

```ruby
DefinitionMap < External
  def icon
    'fa-map'
  end
end
```

@poorvasingal has added `DefinitionMap` level types to the CSD meeting agenda.  If there's anything specific to these level types (shared styling, etc.) we're all in agreement that we should spin off a new type now, and move over the existing ~10 levels by hand.

The idea that a level type has exactly 1 icon is not something we're sticking to going forward.  "Stop" and "Assessment" flags may override the native icon for a given type.  However, we don't want to go to the complete other end of the spectrum and allow level builders to choose any icon for any level (that would be chaos).  We've standardized on a small set of icons because we believe they are useful for identifying different types of content across all courses.

**Pull request merged**
