### PR TITLE
hoc2021: Update Minecraft page

### PR DESCRIPTION
**Pull request by breville**
This just updates the "Available in Minecraft: Education Edition" section.

localhost code org_3000_minecraft

### CODE REVIEW

**Review by KylieModen — APPROVED** [review]
LGTM!

**Review by maddiedierker — APPROVED** [review]
likely a post-HoC task, but if we're still using `minecraft2018.css` and `minecraft_2019.haml`, should they be renamed to remove years from the filenames?

**Review by Erin007 — APPROVED** [review]
looks good! Do we need to remember somewhere that the yellow "new" tag needs to be removed at some point, like next year? Not a big deal, just curious.

**Comment by breville** [comment]
> likely a post-HoC task, but if we're still using `minecraft2018.css` and `minecraft_2019.haml`, should they be renamed to remove years from the filenames?

Good call.  I've opened a [tracking issue](https://codedotorg.atlassian.net/browse/STAR-1911) for that.

> looks good! Do we need to remember somewhere that the yellow "new" tag needs to be removed at some point, like next year? Not a big deal, just curious.

@KylieModen Would you like to track this?  For what it's worth, the "new" tag was still on the most recent one until this change effectively reused it for the new one.

**Comment by KylieModen** [comment]
> > likely a post-HoC task, but if we're still using `minecraft2018.css` and `minecraft_2019.haml`, should they be renamed to remove years from the filenames?
> 
> Good call. I've opened a [tracking issue](https://codedotorg.atlassian.net/browse/STAR-1911) for that.
> 
> > looks good! Do we need to remember somewhere that the yellow "new" tag needs to be removed at some point, like next year? Not a big deal, just curious.
> 
> @KylieModen Would you like to track this? For what it's worth, the "new" tag was still on the most recent one until this change effectively reused it for the new one.

Ideally Microsoft/Minecraft would let us know their desired behavior. It could read "new" up until another is release as it has previously, or we could establish an earlier cut off for when to remove the "new" tag. Given they made no specific request, keeping the established pattern is fine from my perspective.

**Pull request merged**
