### PR TITLE
Revert "Revert "use minifiable and digested js assets for tutorialExplorer in pegasus""

### PR DESCRIPTION
**Pull request by davidsbailey**
Reverts code-dot-org/code-dot-org#13408 with mutex fixes for pegasus test failures on circle

### CODE REVIEW

**Comment by davidsbailey** [comment]
The "Asset map not initialized" and "Asset not found in asset map" errors were not fixed by adding a mutex. See failures:
* https://circleci.com/gh/code-dot-org/code-dot-org/31723#queue-placeholder/containers/0
* https://circleci.com/gh/code-dot-org/code-dot-org/31724#tests/containers/0

**Comment by aoby** [comment]
Ok, something else is going on here now: `RuntimeError: Asset not found in asset map: 'js/en_us/tutorialExplorer_locale.js'`

**Comment by davidsbailey** [comment]
I've removed the mutex after noticing that singleton.rb already puts a mutex around instantiating itself. Some local test runs reveal that the primary problem is shared state leaking between test runs -- all tests get required into a single glob, and then each test gets run.

I tried adding tutorialExplorer to the test fixture and requiring that into the test that needs it, which worked but doesn't seem scalable as we add more similar assets.

I ended up on the solution of explicitly skipping the asset map during unit tests. Currently I'm assuming pegasus unit tests which use `asset_path`  will do so by including `mock_pegasus`. If a new unit test wants to skip the asset map in the future, they can include `mock_pegasus` or just set `CDO.pegasus_skip_asset_map` themselves.

What do you think @aoby?

Manually tested in `pegasus/`:
* `rake test`
* `rake test TEST=./test/test_hoc_routes.rb`
* `rake test TEST=./test/test_asset_helpers.rb`

**Comment by aoby** [comment]
Nice. I don't know why we didn't just look at the Singleton [code](http://apidock.com/ruby/Singleton/__init__/class) earlier. That makes way more sense that it's thread-safe.

Hmm, I'm not sure I like requiring tests to opt-in for asset_path to work, especially since the failure depends on external state and is sporadic and unpredictable. What if we reverse it, always skip in both development and test, then selectively re-enable the asset path for relevant tests that explicitly want to test that path (like of course the asset path test itself)?

**Comment by davidsbailey** [comment]
I would love to do what you are suggesting. The way I would do that is to skip when rack env == test. The problem with that is that then UI tests on test and circle will skip asset map lookup also, which is bad because it could allow a bug to be concealed in UI tests but then error out in prod. Any ideas for how to detect that we are running in a Pegasus unit test besides rack env?

**Comment by aoby** [comment]
Good point. I'm not sure we can since the pegasus tests don't have a common dependency, like `test_helper` in dashboard.

I'm still a bit confused, and not quite sure this will fix it. Note the first [failure](https://circleci.com/gh/code-dot-org/code-dot-org/31723#queue-placeholder/containers/0) you linked above failed in `test_site.rb` which is not using `MockPegasus`. So that might still fail, right?

I also don't quite understand how we got into the failure mode. Presumably, the dashboard assets are created during the build, before tests are run. So why would they then sometimes appear to not exist during the test run?

**Comment by davidsbailey** [comment]
It does look like our deploy process typically compiles dashboard assets before running pegasus unit tests, but it doesn't seem right for a unit test to rely on that.

Good catch on test_site.rb. I've set `CDO.pegasus_skip_asset_map` in that file. This covers all pegasus unit test files containing `/learn`. If the 4 pending circle runs all come back green then this all seems like pretty good evidence to me that we've eliminated enough flakiness to move forward.

To answer your question, we got into this mode because of the following changes:
1. /learn started using asset_path and minifiable_asset_path, which pull a manifest file from CDO.dashboard_assets_dir
2. test_asset_helpers started altering CDO.dashboard_assets_dir

if 1 happened without 2, then test_site and test_hoc_routes would still be passing on circle and test, by relying on the fully-populated manifest file generated by compiling dashboard assets earlier in the build process.

**Comment by aoby** [comment]
I agree we don't want unit tests to rely on preliminary external processes (i.e. build), but it is reasonable (not to mention necessary) that the UI tests do rely on a fully built website. Unfortunately I still don't see an easy way of separating them without a common test dependency, so this looks fine.

I don't agree with 2. AFAICT, test_asset_helpers is only stubbing `CDO.dashboard_assets_dir`, which is scoped only to the individual test case. If stubs bled into other test cases, we'd have all kinds of problems.

It still seems like there's something else going on here. Maybe just timing, sometimes the assets are built before the /learn tests run and other times not?

**Comment by davidsbailey** [comment]
To respond to your comment about 2 above, its true that CDO.dashboard_asset_dir is stubbed only for the duration of each test case. However we use the value of CDO.dashboard_asset_dir to initialize the asset map, and the value of the asset map persists for the rest of the test run, which would allow state to leak between test cases.

**Comment by aoby** [comment]
Ok, that makes way more sense! Thanks for explaining. 
Now that we understand the problem, we can and should fix it. I still contend these tests should not mess up state for other tests. 

I found [this](http://stackoverflow.com/a/37364787) suggestion to clone the singleton for testing, and I did a little experiment test that worked.

```ruby
# Do this in the setup, then refer to @asset_map for the test. 
# Each one will be independent.
@asset_map = AssetMap.clone.instance
```

**Comment by davidsbailey** [comment]
Nice find @aoby . That seems like a good improvement! I've already merged this PR but I'd be happy to review a follow-on since it sounds like you've got it working already.

**Pull request merged**
