### PR TITLE
/learn page updates

### PR DESCRIPTION
**Pull request by tanyaparker**
- move bee header to bottom of the page, add all the teacher links, and add a signup button
- decrease the width and height of the banner
- change carousel controls from chevron to caret
- add sign up button to learn tabs
- remove large headers and rename secondary headers as "Partner tutorials..."
- restyle Go button to be inline with the quick links
- tested all browsers (yes IE8), csedweek.org/learn, uk.code.org/learn, i18n, mobile

TODO: 
- [x] replace star wars banner image

**code.org/learn**
image

**csedweek.org/learn**
image

**teacher banner at bottom of code.org/learn**
image

### CODE REVIEW

**Comment by tanyaparker** [comment]
@breville @caleybrock if you could take a look

**Comment by breville** [comment]
Looks good to me.  Really nice improvements.  

I wonder if "sign up your event" might test better as "add your event" but that could be a little a/b test if we care a lot.

**Comment by caleybrock** [comment]
design looks awesome! big improvements :)

**Comment by breville** [comment]
@tanyaparker one thing i've noticed at https://code.org/learn is that pressing the new carousel buttons rapidly doesn't fire every time.. are we secretly playing a long animation and they are disabled until it's over?

**Comment by tanyaparker** [comment]
@breville correct, but I'm fixing animation today

**Pull request merged**
