### PR TITLE
[Finishes #108375104] border-box box-sizing for design elements where we add a border

### PR DESCRIPTION
**Pull request by Bjvanminnen**
When dragging various elements (chart, canvas, image) to take up the entire play area in design mode, they would still only be 310x440 instead of 320x450. This is because the 5px border was counting against them. By setting border-box to box-sizing, the border is internal to the element and we can drag to properly take up the entire area.

Tested all three element types on chrome and FF (will also give IE a look, though it sounds like everyone other than FF should support the standard border-box)

### CODE REVIEW

**Comment by davidsbailey** [comment]
I see the following in base.scss:

```
#divApplab, #designModeViz, .draggingParent {
  input, div[contenteditable=true], button, select, img, label {
    box-sizing: border-box;
    ...
```

That's probably messing some things up in Firefox. Maybe now would be a good time to add `box-sizing: -moz-border-box;` there too?

**Comment by Bjvanminnen** [comment]
That would explain why it didn't seem like img was having issues before, but canvas/chart were. Probably does make sense to add moz there.

**Comment by davidsbailey** [comment]
Also it seems like we want this to work even if the modern theme is not enabled. So maybe all the css changes in this PR belong in base.scss? Seems kind of arbitrary given that AFAIK we're not testing the non-modern theme, though.

**Comment by davidsbailey** [comment]
A more pertinent question is whether this same problem exists in code mode / in divApplab in which case that block in base.scss would be better place for these rules.

**Comment by Bjvanminnen** [comment]
I think it does not, because it doesnt have the border there

**Comment by Bjvanminnen** [comment]
FWIW, I put them in modern.scss since that's where we set the border. I'll explore some more if it makes more sense to put them elsewhere.

**Comment by Bjvanminnen** [comment]
It's hard to argue what belongs in base vs. modern when we only have one theme. I think that setting box-sizing where I do does make sense, if only because that's where we're setting a border (which necessitates it).

I think that for where we currently set box-sizing in base, we should probably also set moz-box-sizing, although I didn't see any issues for img on latest firefox without doing that.

**Comment by davidsbailey** [comment]
LGTM

**Pull request merged**
