### PR TITLE
I18n sync Down & Out 07/11

### PR DESCRIPTION
**Pull request by Hamms**
Including external markdown changes!

### CODE REVIEW

**Comment by Hamms** [comment]
looks like blockfield restoration didn't work

**Comment by Hamms** [comment]
Ahh, I ran the sync in from the `add-external-markdown` branch rather than from staging, so the "copy from dashboard to locales" script didn't run, so the stuff in `i18n/locales/original` was actually the redacted copy, not the unredacted copy, so the restoration process didn't have access to the unredacted content.

Rerunning the sync out with correct originals now.

**Comment by nkiruka** [comment]
> looks like blockfield restoration didn't work

**Comment by Hamms** [comment]
Fixed! PTAL

**Review by bethanyaconnor — APPROVED** [review]

**Pull request merged**
