### PR TITLE
Update JS-Interpreter through NeilFraser/JS-Interpreter@95268a9

### PR DESCRIPTION
**Pull request by joshlory**
This includes the fix for https://github.com/NeilFraser/JS-Interpreter/issues/61.

Fixes a regression on https://studio.code.org/s/course4/stage/16/puzzle/5 that occurred when Maze was updated to use the JSInterpreter.  The generated code looks like this:

``` javascript
var left;
var right;

left = 0;
right = 1;
var right;
var left;
// ...
```

### CODE REVIEW

**Comment by islemaster** [comment]
I think @caleybrock reported this, but we found some gamelab issues with group methods (which may be related to changed array methods in the interpreter).  Example code not working:

``` javascript
var sprite0 = createSprite(100, 200);
var sprite1 = createSprite(300, 50);
var sprite2 = createSprite(300, 200);
var sprite3 = createSprite(300, 350);
var group = createGroup();
stroke("blue");
group.add(sprite1);
group.add(sprite2);
group.add(sprite3);

var count = 0;
function draw() {
  background("white");
  (sprite0.position).x = Game.mouseX;
  sprite0.position.y = Game.mouseY;
  if (sprite0.isTouching(group)) {
    console.log("touching: " + count); 
  }
  drawSprites();
  count++;
}
```

Here we expect to log to the console when sprite0 (under the mouse) overlaps any of the other sprites, but it's not.  Notably, this example works if you change `sprite0.isTouching(group)` to a more specific `sprite0.isTouching(sprite1)` or some such, which suggests the array changes to me.

**Comment by islemaster** [comment]
Good news is, other custom/deep-marshalled stuff seems to be working okay - properties mapped into the `Game` namespace are okay, sprites and `drawSprites` all operating as expected.  I'll keep looking for edge cases.

**Comment by joshlory** [comment]
Pushing pause on this upgrade for now.  Here's what I've found so far on the JSInterpreterTest failure:

The "hits a breakpoint" test is failing because [`executeInterpreter` loops indefinitely](https://github.com/code-dot-org/code-dot-org/blob/1097d08d930117cf0fb423c7097e76b90b87e76b/apps/test/unit/JSInterpreterTest.js#L29).  This happens because the updated Interpreter skips `ExpressionStatement` when stepping, I believe due to this change: https://github.com/NeilFraser/JS-Interpreter/commit/a4ded3ed1de7960cda9177d1bacb6a2526440d14#diff-966ad2ec9f775b3820dd37b4d36b650aR116.

We end up unwinding past the breakpoint and looping forever when the Interpreter runs out of code to execute.

**Comment by joshlory** [comment]
You can see the different behavior with this sample program.  Before upgrading, pressing "Run" hits the first breakpoint.  After upgrading, neither breakpoint is hit.

screen shot 2016-08-29 at 4 32 17 pm

**Pull request closed without merging**
