### PR TITLE
Replace `mockfirebase` with `firebase-mock`

### PR DESCRIPTION
**Pull request by joshlory**
The old project was no longer maintained. The new project supports v3 of the Firebase API, and doesn't link to `browserify` as a dependency.

### CODE REVIEW

**Comment by joshlory** [comment]
No longer includes `browserify` in node_modules: https://github.com/code-dot-org/code-dot-org/pull/14380/files#diff-1b28c39bb54275ba36a716e98f13b8cbL1870

**Comment by davidsbailey** [comment]
Questions/comments, not necessarily requiring code changes, since we are very likely going to want to refer back to this PR to figure out what's going on:
1. In this PR description: "Using a fork of the original project", I think you mean "new project" not "original project"
2. I realize you're copying other examples, but it would be ideal for this to live under code-dot-org on github rather than your personal account. Fine to leave like this for now if that's hard to do.
3. It looks like your fork of firebase-mock has no changes with respect to the upstream project, is that correct?
4. What is "the browserify devDependency fix" -- is that something we're doing in our project, something we're proposing in the upstream project, or something we're assuming they will do in the upstream project eventually? If there's an issue or PR in the upstream project, we should link to that here.

**Comment by joshlory** [comment]
Great feedback Dave!  The upstream project already accepted my pull request, so I've rebased this change to use version 1.0.5 of `firebase-mock` from npm.

`firebase-mock` is about 34 commits ahead of `mockfirebase`.

**Comment by davidsbailey** [comment]
It looks like MockDataSnapshot has `key` as a property instead of having `key()` as a method that returns a value. This is fixable but not a 1 minute task. I can help you with it tomorrow.

**Comment by davidsbailey** [comment]
I don't see an easy way to define our own MockDataSnapshot.prototype.key().

it looks like `snapshot.key` is the new Firebase 3.0 syntax. I would say, replace `snapshot.key()` with `typeof snapshot.key === 'function' ? snapshot.key() : snapshot.key` in two places in `applab.js` with an explanatory comment, and I can take care of upgrading our code to Firebase 3.0 syntax next week.

**Comment by joshlory** [comment]
PTAL.

**Pull request merged**
