### PR TITLE
Seed csp-post-survey-2018 in drone ui tests

### PR DESCRIPTION
**Pull request by davidsbailey**
### Background

~Finishes~ related to [LP-374](https://codedotorg.atlassian.net/browse/LP-374). Baker will do the actual work via levelbuilder to unhide the post course survey. additional context in https://github.com/code-dot-org/code-dot-org/pull/28316. 

### Description

All this PR does now is make sure tests don't break when Baker adds the post course survey to csp-2018, by adding csp-post-survey-2018 to the list of courses to seed in drone ui tests.

### Verification

From the trail of commits and drone runs, you can see that this will allow tests to pass once the post survey is added to csp 2018.

### CODE REVIEW

**Comment by davidsbailey** [comment]
Closing in favor of letting Baker do this via levelbuilder at the time of his choosing.

**Comment by davidsbailey** [comment]
Except wait, we'll still need the csp-post-survey-2018 to be added to UI test seeding in order for things not to break when Baker pulls the trigger on this. Reopening and having this PR change only the UI test config.

**Comment by davidsbailey** [comment]
Apologies for the mess here Maddie -- I've tried to document what's going on the comments/description but please feel free to ping me if its unclear.

**Review by maddiedierker — APPROVED** [review]
awesome, thank you for getting ahead of this and making sure tests don't break!

**Pull request merged**
