### PR TITLE
Playlab announce

### PR DESCRIPTION
**Pull request by caleybrock**
screen shot 2015-12-03 at 11 33 34 am
Not sure what the text should be but I put something in the gsheet.

### CODE REVIEW

**Comment by tanyaparker** [comment]
Did we get an OK from Roxanne for the text? I think she can make it more exciting. And we should link to /learn?

**Comment by caleybrock** [comment]
I replaced the png version of this image too, because it was overriding the jpeg in some places.

**Comment by caleybrock** [comment]
and roxanne is looking at the text, I'll update it in the gsheet

**Comment by tanyaparker** [comment]
Then looks good! Should we wait to merge until after today's DTP so it goes out with tomorrow's DTP?

**Comment by caleybrock** [comment]
text updated on the gsheet, I'll wait till this afternoon to merge this though

**Pull request merged**
