### PR TITLE
[Phase 1.5] [DES-253] Update google blockly dark theme

### PR DESCRIPTION
**Pull request by levadadenys**
### [Phase 1.5] [DES-253] Update google blockly dark theme
Google blocky dark theme - lighten background

Before:
Знімок екрана 2023-03-17 о 19 55 32
Знімок екрана 2023-03-17 о 19 44 50

After:
Знімок екрана 2023-03-17 о 22 10 59
Знімок екрана 2023-03-17 о 22 06 53

## Links
- jira ticket: [DES-253](https://codedotorg.atlassian.net/browse/DES-253?atlOrigin=eyJpIjoiOTI0OGNlNGYwYjU0NGJhZDk4YzAyOWRlYTUyMGEyZDAiLCJwIjoiaiJ9)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by mikeharv** [comment]
The timeline looks off... There should be vertical measure markers and numbers along the bottom.
image

I'm not sure how your change could be causing that...

**Comment by levadadenys** [comment]
> The timeline looks off... There should be vertical measure markers and numbers along the bottom. image
> 
> I'm not sure how your change could be causing that...

interesting...
Checked on chrome, everything looks fine there. Updated screenshots.

 I guess it can be somehow related to safari browser, cause chrome work as expected. And in safari I'm having this issue with both pr and staging branches

**Review by sanchitmalhotra126 — COMMENTED** [review]
I just pulled the change locally and it looks ok on Chrome and Safari to me?

Screenshot 2023-03-17 at 11 33 13 AM

Screenshot 2023-03-17 at 11 33 31 AM

**Comment by levadadenys** [comment]
@sanchitmalhotra126 oh, cool, thank you very much!
I hope it's the problem with my safari only then

**Comment by levadadenys** [comment]
Added opacity to flyout as @breville suggested. (change is approved by @mikeharv and @markabarrett )
Updated screenshots in description

**Review by breville — APPROVED** [review]

**Pull request merged**
