### PR TITLE
Don't trigger pan-drag when clicking in to editable-but-unmovable blocks (e.g. /s/course4/stage/10/puzzle/3)

### PR DESCRIPTION
**Pull request by bcjordan**
We were seeing an issue introduced by https://github.com/code-dot-org/code-dot-org/pull/3494 where levels such as https://studio.code.org/s/course4/stage/10/puzzle/3 would not open editable fields.

This is because those blocks were movable but editable on the inside.

This makes pan dragging not activate when the click target is a block with editable insides. The main use case for pan-dragging-on-blocks is the CSinA.

image

Which is not editable, and continues to pan the workspace properly with this fix in place.
# Before

click-into-unmovable-before
# After

click-into-unmovable

### CODE REVIEW

**Comment by bcjordan** [comment]
Looking in to whether I can trigger a click event from within core phantom test

**Comment by Bjvanminnen** [comment]
lgtm

**Comment by bcjordan** [comment]
@Bjvanminnen added test coverage, please re-review

**Comment by Bjvanminnen** [comment]
lgtm

**Pull request merged**
