### PR TITLE
Fix treating all numbers as integers in the data browser

### PR DESCRIPTION
**Pull request by trevorb**
Fixes: 
image
@islemaster

### CODE REVIEW

**Comment by islemaster** [comment]
I don't know this code well enough to review (maybe @davidsbailey does?).

* Was allowing integers originally desired behavior?
* Is that the only code you need to touch?
* Can we pin the correct behavior here with a test?

**Comment by islemaster** [comment]
Not to seem ungrateful :smiley: thanks for finding this so quick!

**Comment by davidsbailey** [comment]
LGTM after adressing (2) and maybe (3) below. To answer Brad's questions:
1. No. The idea was to infer from the entered text whether it should be a number or string. forcing it to be an integer definitely seems wrong. 
2. Good catch. there is another copy of this function in `edit-csp-properties`. That should be updated too. I'm on the fence about whether there's enough shared code to warrant extracting it.
3. We don't have any tests on the data browser right now. There are some basic pegasus unit tests for these pages now: https://github.com/code-dot-org/code-dot-org/blob/staging/pegasus/test/test_edit_csp.rb These could be extended to add some data `put` or `post` to the v3 APIs and then assert that the added strings appear in the body of  `get /v3/edit-csp-tables/<channel-id>/<table-name>` . This would at least make sure the page comes up and loads data.

**Comment by trevorb** [comment]
3. The /edit-csp-tables page loads data via an ajax request to the v3 api, so unfortunately we won't be able to just assert the strings appear in the response body. I'll look into adding some mocha tests.

**Pull request merged**
