### PR TITLE
Dashboard: /courses & header look better on RTL languages

### PR DESCRIPTION
**Pull request by breville**
#### signed-out
_courses_nobody

#### student
_courses_student

#### teacher
_courses_teacher

### CODE REVIEW

**Comment by breville** [comment]
@Erin007 Notice that the CourseCard in teacher view is still floated left.  I think it would be more proper for all such content to float right when RTL, so that the ordering of the cards themselves are RTL, but this will have a flow-on effect related to spacers, etc. so I have punted on that work for this change.  What do you think?

**Comment by Erin007** [comment]
@breville  I see what you mean about the CourseCards still floating left. I'm fine if you punt on this because it's not critical for RTL users that the cards be sorted by recency - it's kind of nice to have, but they can still access all of the information about all of their courses and the content on the cards is RTL.

**Comment by tanyaparker** [comment]
Is it possible to flip the hero image as well? So that the text doesn't cover the image?

And agreed that technically the course cards ordering should start from the right, but I'm considering that lower priority. We won't do it for back to school, but I'll track as polish when we revisit our RTL support as a whole.

**Comment by Erin007** [comment]
The hero/header is all one image. To flip it, I think we would need Mark to make us a new image with the girl on the left then load that if we're in RTL.

**Comment by tanyaparker** [comment]
Oh. What about when we add RTL support in the navbar?

**Comment by breville** [comment]
@tanya Do you mean w should flip the images later when we add RTL support to navbar?

At any rate, navbar and banner image are treated as separate components.  navbar along with rest of header is implemented in HAML.  HeaderBanner is implemented in React and essentially rendered as part of page body.  The header just happens to be rendered over the top of it.

**Comment by tanyaparker** [comment]
I'm not sure I understand what you're talking about with the terminology. Is header: navbar + hero + title + description? Let's talk about it at cabal today.

**Pull request merged**
