### PR TITLE
Migration to support Schoology reporting

### PR DESCRIPTION
**Pull request by nicklathe**
This migration adds a join table to support a many-to-many relationship between LtiUserIdentity to LtiDeployment.

### Background

Institutions that install the Code.org LTI tool via the Schoology app store (the primary recommended mechanism) end up sharing the same client_id, therefore the same LtiIntegration in our system. This is due to how Schoology has implemented their app store, essentially using the same LTI Tool instance across multiple institutions/accounts. This is fine from a functionality standpoint, however presents an issue when trying to report numbers on individual Schoology installations and users, as there is no way to differentiate which schools users belong to, as they are all associated to this single LTI Integration.

### Solution

In order to associate a group of users to a specific institution, we can use LtiDeployment. Schoology does provide us a unique deployment ID per institution/account, which is how we can determine individual school installations of our LTI tool. However, there is currently no way to associate an LTI User to an LTI Deployment.

This PR (1 of 2) adds a join table for LtiUserIdentity and LtiDeployment. This allows us to query the total number of users for a particular deployment. An example using an Active Record query is: `LtiDeployment.find(<some id>).lti_user_identities.count`, which would return the number of users associated to a particular LTI Deployment. Or similarly, an SQL query
```
SELECT COUNT(*)
FROM lti_user_identities
WHERE lti_deployment_id = <some_id>;
```

NOTE: I considered adding a `name` column to `LtiDeployment` as well, to make it easier when visually grepping through a list of LTI Deployments, however I think that may be unnecessary for the reporting needed. I'm open to feedback on this decision. We could grab the name of the institution from the `https://purl.imsglobal.org/spec/lti/claim/tool_platform` claim in the JWT

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by carl-codeorg — COMMENTED** [review]
Are there any cases where we would want this to be a many-to-many? Schoology seems to have deployments pretty well-defined as one per installation of the tool, but Canvas lets an admin create multiple deployments from a single developer key. Not sure how it would play out in a real world scenario, but it definitely seems like a single user in Canvas could have two different courses with two different deployments of the Code.org developer key.

If we keep it one-to-many, is the plan that we would just update the deployment ID for the lti_user_identity if we get an ID token for a known user with a different deployment ID?

**Comment by nicklathe** [comment]
> Are there any cases where we would want this to be a many-to-many? Schoology seems to have deployments pretty well-defined as one per installation of the tool, but Canvas lets an admin create multiple deployments from a single developer key. Not sure how it would play out in a real world scenario, but it definitely seems like a single user in Canvas could have two different courses with two different deployments of the Code.org developer key.
> 
> If we keep it one-to-many, is the plan that we would just update the deployment ID for the lti_user_identity if we get an ID token for a known user with a different deployment ID?

This is a really good point. It does feel like we should support a many-to-many here from that standpoint. However from a reporting standpoint (for Schoology, which is what this is trying to enable), could this generate an artificial over count if there were a single user with more than 1 deployment id's connected to them, since we would assume a deployment id == single school/district? Maybe not, if Schoology only issues a single deployment id per installation of the tool, it shouldn't matter if this were many-to-many. And for Canvas where this could happen, I don't think we'll use this association for reporting anyways.

As you've outlined, we really have two options. 1) change this to a many-to-many LtiDeployment <-> LtiUserIdentity to support cases when there are more than one deployment id in a single installation. 2) Keep this as a one-to-many LtiDeployment -> LtiUserIdentity and update the LtiUserIdentity if we detect a new/different deployment id.

I think I'm leaning towards the first option, and updating this to be many-to-many.

**Comment by carl-codeorg** [comment]
> > Are there any cases where we would want this to be a many-to-many? Schoology seems to have deployments pretty well-defined as one per installation of the tool, but Canvas lets an admin create multiple deployments from a single developer key. Not sure how it would play out in a real world scenario, but it definitely seems like a single user in Canvas could have two different courses with two different deployments of the Code.org developer key.
> > If we keep it one-to-many, is the plan that we would just update the deployment ID for the lti_user_identity if we get an ID token for a known user with a different deployment ID?
> 
> This is a really good point. It does feel like we should support a many-to-many here from that standpoint. However from a reporting standpoint (for Schoology, which is what this is trying to enable), could this generate an artificial over count if there were a single user with more than 1 deployment id's connected to them, since we would assume a deployment id == single school/district? Maybe not, if Schoology only issues a single deployment id per installation of the tool, it shouldn't matter if this were many-to-many. And for Canvas where this could happen, I don't think we'll use this association for reporting anyways.
> 
> As you've outlined, we really have two options. 1) change this to a many-to-many LtiDeployment <-> LtiUserIdentity to support cases when there are more than one deployment id in a single installation. 2) Keep this as a one-to-many LtiDeployment -> LtiUserIdentity and update the LtiUserIdentity if we detect a new/different deployment id.
> 
> I think I'm leaning towards the first option, and updating this to be many-to-many.

Yeah I think I'm leaning in the same direction. The current implementation of `school_info` is support for many-to-many IMO. It seems like we started by having a one-to-many, since the User model has a `school_info_id` foreign key. Then later we wanted to be able to associate a user with multiple schools and/or preserve a history of their school associations, so we added a new many-to-many bridging table `user_school_infos`. Now there's a weird situation where we add a new entry to `user_school_infos`, but also have to update `school_info_id` to make sure it's pointing to the most recent school_info.

If we just start with the many-to-many here, we avoid this problem, and we can still get the most recently active deployment for a user by just querying for the most recent one.

**Comment by nicklathe** [comment]
@carl-codeorg PR has been updated to add a join table to support a many-to-many relationship as discussed.

**Review by carl-codeorg — APPROVED** [review]
LGTM. Agree that for the name property, we probably don't need it now. If it's something that it turns out we do need for reporting, we can always add it later.

**Pull request merged**
