### PR TITLE
Add "View more..." string to be translated

### PR DESCRIPTION
**Pull request by hacodeorg**
Continuation of https://github.com/code-dot-org/code-dot-org/pull/34469: add new string, "**View more...**", to be translated. This string will be used as the heading for the ViewMore tile.

### CODE REVIEW

**Review by islemaster — APPROVED** [review]

**Comment by Hamms** [comment]
+100 to the pattern of adding strings for translation well in advance of using them!

**Comment by hacodeorg** [comment]
> +100 to the pattern of adding strings for translation well in advance of using them!

How long do you think we should wait until we can actually use a new string?

**Comment by dju90** [comment]
For this one, we have an existing translation in memory that I can go into Crowdin to manually apply, so once it gets synced up next week, the week after is probably when we'd be able to do the sync down to fetch the translation. For larger sets of new strings, depending on the feature and its visibility, we would probably give a few weeks for our translation agency to finish translating the strings + us to be able to sync them

**Comment by Hamms** [comment]
@dju90 are we confident that the addition of ellipses is uniform across all the languages we want to manually update?

**Comment by dju90** [comment]
I intended to use it as a design indicator as opposed to a linguistic one, a la https://en.wikipedia.org/wiki/Ellipsis#Usage_in_menus

**Comment by Hamms** [comment]
That would be inaccurate, then; this represents a link, not a menu option; when they click it, the thing that's going to happen (navigation) happens immediately, not after they select from additional prompted options.

**Comment by dju90** [comment]
It's certainly not indicating missing words or as an etcetera replacement. In my view, it's much closer to a design indicator in function:
> an ellipsis means that upon selection more options (sometimes in the form of a dialog box) will be displayed, where the user can or must make a choice

The "View more" tile does not take a user directly to a HoC activity like the other tiles do - it takes the user to a page where more options are displayed, and the user must make a choice to actually reach the desired goal state (an activity).

**Comment by Hamms** [comment]
I disagree with your interpretation of user expectations here, but we should pursue this conversation in another medium.

Alternatively, I'd actually suggest that we not include an ellipsis at all here; just "View more" seems both preferable and easier to implement.

**Comment by dju90** [comment]
The addition of the ellipses on my suggestion was just a nit, so leaving the design as it is currently (sans ellipses) is fine. Does that mean reverting this commit?

**Comment by dju90** [comment]
(to remove the string from the sync, not to change any UI)

**Comment by hacodeorg** [comment]
Will this string be helpful in other scenarios in the near future? I just don't want to remove it now (already merged) to add it back later. If that is not the case, I'll revert the PR to avoid polluting this file.

**Comment by Hamms** [comment]
I'd prefer to re-add it later if necessary; until we get the string tracking stuff up and running, I'd like to avoid the practice of having strings in Crowdin we don't have a need for. Thanks!

**Comment by hacodeorg** [comment]
That makes sense. I will revert this PR.

**Comment by dju90** [comment]
Thanks Ha!

**Pull request merged**
