### PR TITLE
Add AnswerDash to some PD pages

### PR DESCRIPTION
**Pull request by breville**
This is an attempt to include the AnswerDash snippet on

- https://studio.code.org/pd/workshops/[id]/enroll, and
- https://studio.code.org/pd/application/teacher

It also uses the snippet partial on six markdown pages that had already included its content manually.

#### teacher application
screenshot 2018-04-02 11 25 09

#### enroll
screenshot 2018-04-02 11 25 32

### CODE REVIEW

**Comment by tanyaparker** [comment]
I'll let Andrew review the code. :)

Since the same snippet is in pegasus, did you decide that it doesn't work well to have it in shared? Better to have a copy each in pegasus and dashboard?

**Comment by breville** [comment]
@tanyaparker I updated to make it a shared HAML file now.  That said, it appears that the one Pegasus teacher dashboard page that includes this snippet isn't in use right now.

**Comment by tanyaparker** [comment]
Hmm... Marina added it to the following pages. Is it slightly different?

* https://code.org/educate/professional-learning-2018
* https://code.org/educate/professional-learning (all pages in the folder)
* https://code.org/professional-development-workshops

**Comment by caleybrock** [comment]
I'm used to seeing this UI is it the same thing?
screen shot 2018-04-02 at 12 04 16 pm

**Comment by breville** [comment]
@caleybrock yes, I just took screenshots with it expanded after clicking on it.

**Comment by breville** [comment]
@tanyaparker I didn't realise we had the snippet pasted in all those other places.  Will clean them up to use the partial too.

**Pull request merged**
