### PR TITLE
Turn on watchers in game lab

### PR DESCRIPTION
**Pull request by caleybrock**

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Will new levels get this on by default?

**Comment by Bjvanminnen** [comment]
Do we need to worry about merge conflicts from LBs editting these levels?

**Comment by caleybrock** [comment]
I've already talked to levelbuilders, there should be no conflicts. I'm going to do a follow up PR that has the default on.

**Comment by caleybrock** [comment]
:thinking: lots of csd3 levels are edited on levelbuilder. I might end up running the script that I did locally on the levelbuilder machine, but I'll coordinate tomorrow.

**Pull request merged**
