### PR TITLE
Gamelab animation upload

### PR DESCRIPTION
**Pull request by caleybrock**
PR credit @fauziaaslam

These are the rest of the animations required for gamelab. The changes are generated from a script after uploading all the correct files to S3. I tested locally and they look good. Thanks so much @fauziaaslam for working on this! 👍 💯 🎉 
screen shot 2017-01-18 at 3 32 57 pm

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Is there anything here worth me spending time trying to review? I suspect the answer is no, especially given that you've already taken the time to test locally :)

If my assumption is correct, lgtm.

**Comment by caleybrock** [comment]
@Bjvanminnen no it's kind of hard to review by reading these changes. thanks for looking.

**Comment by bcjordan** [comment]
@fauziaaslam thanks for your awesome work, excited to use these animations!

**Comment by davidsbailey** [comment]
Nice work @fauziaaslam, thank you for your contribution!

**Comment by jeremydstone** [comment]
Congrats & thanks @fauziaaslam

**Comment by aoby** [comment]
Nice work @fauziaaslam. I can't wait to write & play games with these new animations!

**Comment by breville** [comment]
Thank you @fauziaaslam!

**Comment by fauziaaslam** [comment]
Excited for kids to start using these!

**Pull request merged**
