### PR TITLE
i18n for "AI for Oceans" activity

### PR DESCRIPTION
**Pull request by bethanyaconnor**
# Description

Relies on a merge and publish of https://github.com/code-dot-org/ml-activities/pull/343.

This approach is based off how we do i18n in Blockly. In `ml-activities`, we will expose a json of the strings we use. Our i18n pipeline will copy that file into the source directory and sync it to Crowdin.

Because we currently don't have any other `fish` strings, I'm copying the `ml-activities` source strings to `i18n/locales/source/blockly-mooc/fish.json` which will mean (after a full sync), translations will end up in `apps/i18n/fish/<lang>.json` which should allow translations to "just work". However, if we ever add strings to this activity directly in this repo, we'll need to change this approach (it will overwrite any string).

Open to thoughts/suggestions on this approach.

### Full process for translating `ml-activities` strings
In the `code-dot-org` repo, we use `MessageFormat` in our apps code. This repo will use the same version. The steps the strings will go through to be translated are:
1. Strings are added to `oceans.json`
2. The i18n pipeline will copy this file into a source directory and upload it to Crowdin
3. The strings get translated on Crowdin
4. The translations are downloaded and distributed to `apps/i18n/fish/<lang>.json`
5. The translations are passed into the initialization of the fish tutorial.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by Hamms** [comment]
I am concerned about step 5; that process is currently undefined for our Blockly I18n, and I'd really like to make sure we have a solid plan for how to address that (for both this and Blockly, ideally) before we commit to this pattern.

**Comment by bethanyaconnor** [comment]
Yeah, I don't love the pattern we have for Blockly and I wasn't super excited to commit harder to it. Open to thoughts on better ways to handle this.

However, I don't fully understand what your question is. What is undefined?

**Comment by bethanyaconnor** [comment]
@Hamms after our discussion last week, any feedback on this PR? I think this goes in the general direction we talked about on Friday

**Review by maddiedierker — APPROVED** [review]

**Review by Hamms — APPROVED** [review]
This looks great! I'm excited to see how this approach works in practice and to update our blockly i18n strategy to match

**Comment by bethanyaconnor** [comment]
I'm bumping `ml-activities` here as if we do need to rollback the `ml-activities` bump, we'll also need to rollback the i18n pipeline change.

**Pull request merged**
