### PR TITLE
When logging objects with console.log, JSON stringify them appropriately

### PR DESCRIPTION
**Pull request by mehalshah**

### CODE REVIEW

**Comment by mehalshah** [comment]
I see that we're doing some implicit vsprintf with occasionally bad results. I didn't want to make this too detailed and fix it.

**Comment by davidsbailey** [comment]
This does accomplish the stated goal, but it also replaces the nice expandable/collapsible view of objects and arrays that get printed via native console.log with JSON. Can we move this logic into outputApplabConsole to preserve the native console.log behavior for objects and arrays? I think it will be fine to only JSON.stringify if the argument there is an object or array, unless you can think of other types we'd want to stringify.

**Comment by davidsbailey** [comment]
also, what are the bad results you're seeing from vsprintf?

**Comment by mehalshah** [comment]
console.log("hi", "there") should print "hi there". However, instead it prints "hi" because we're interpreting a multi-argument call to the function as a string that should be formatted, and vsprintf("hi", "there") would just return "hi"

**Comment by davidsbailey** [comment]
LGTM

Thanks for changing approaches. It looks like you handled the vsprintf stuff correctly, but please do at least one quick test that the vsprintf stuff still works the same for parameter validation, e.g. that the output from `button('id', 'text'); button('id', 'text');` has not changed. (I think this is handled by tests somewhere but I'm not sure exactly where)

**Pull request merged**
