### PR TITLE
Navigation updates - Update Create menu to be called New project

### PR DESCRIPTION
**Pull request by kelbyhawn**
Updates the "Create" dropdown label to "New project" to prepare for the [Create Account button A/B test](https://docs.google.com/document/d/1RDQv2IAjkdJvxfxWFgisRNM9GuJInfqwf7v4Muifgt8/edit#heading=h.b3v9yoxdyveu). Putting this into review now and will check the translations once the i18n Down & Out sync is merged. 

## Links
Jira ticket: [ACQ-1780](https://codedotorg.atlassian.net/browse/ACQ-1780)
i18n Down & Out PR: 
 - https://github.com/code-dot-org/code-dot-org/pull/59092

## Testing story
Tested locally and in SauceLabs

## Followup
- Additional Navigation updates:
  - A/B Test: Adding Create Account button - [ACQ-1545](https://codedotorg.atlassian.net/browse/ACQ-1545)

----

## Signed Out
| Before | After |
| ---- | ---- |
| SignedOut_Before | After |

## Signed In
| Before | After |
| ---- | ---- |
| SignedIn_Before | After |

### CODE REVIEW

**Review by bethanyaconnor — COMMENTED** [review]
I'm wondering if we just skip straight to `new_project_low_cap` -- it looks like it's got roughly the same translation coverage after the next down & out.

**Comment by kelbyhawn** [comment]
> I'm wondering if we just skip straight to `new_project_low_cap` -- it looks like it's got roughly the same translation coverage after the next down & out.

I'd love that — it would mean that a handful of languages might not be translated when this goes live, but since we aren't doing the full list maybe that doesn't matter as much now? cc @dmcavoy should we ask Forest about this?

**Comment by dmcavoy** [comment]
> > I'm wondering if we just skip straight to `new_project_low_cap` -- it looks like it's got roughly the same translation coverage after the next down & out.
> 
> I'd love that — it would mean that a handful of languages might not be translated when this goes live, but since we aren't doing the full list maybe that doesn't matter as much now? cc @dmcavoy should we ask Forest about this?

If its roughly the same coverage I say we go with the one we want long term

**Comment by kelbyhawn** [comment]
> > > I'm wondering if we just skip straight to `new_project_low_cap` -- it looks like it's got roughly the same translation coverage after the next down & out.
> > 
> > 
> > I'd love that — it would mean that a handful of languages might not be translated when this goes live, but since we aren't doing the full list maybe that doesn't matter as much now? cc @dmcavoy should we ask Forest about this?
> 
> If its roughly the same coverage I say we go with the one we want long term

Works for me! I'll update it here and clean up the followup ticket.

**Comment by kelbyhawn** [comment]
@bethanyaconnor @dmcavoy the Down & Out PR was just merged 🎉 It looks like there will be 6 languages not translated w/ the low cap version of the string ([ref](https://github.com/search?q=repo%3Acode-dot-org%2Fcode-dot-org+new_project_low_cap&type=code&p=1)).

**Comment by dmcavoy** [comment]
> @bethanyaconnor @dmcavoy the Down & Out PR was just merged 🎉 It looks like there will be 6 languages not translated w/ the low cap version of the string ([ref](https://github.com/search?q=repo%3Acode-dot-org%2Fcode-dot-org+new_project_low_cap&type=code&p=1)).

Lets give Jorge the heads up that this is our plan and see if he has any concerns about those 6 languages

**Comment by kelbyhawn** [comment]
> Lets give Jorge the heads up that this is our plan and see if he has any concerns about those 6 languages

Looks like Jorge is OOO, I'll follow up after Codechella since I won't be able to merge this until after then anyway.

**Comment by kelbyhawn** [comment]
@bethanyaconnor @dmcavoy Jorge [said](https://codedotorg.slack.com/archives/C0T0UQH0R/p1718654808999029?thread_ts=1717074843.526549&cid=C0T0UQH0R) we're good to go w/ this once it's reviewed/passes drone 🎉

**Review by bethanyaconnor — APPROVED** [review]

**Pull request merged**
