### PR TITLE
Script: clear prior announcements when none provided in .script file

### PR DESCRIPTION
**Pull request by breville**
Prior to this change, if a script had `script_announcements`, but they were later removed from the `.script` file, they wouldn't be removed from the database.  Now, they are.

### CODE REVIEW

**Comment by breville** [comment]
Yes this should allow some changes already made to go live.  I'm not familiar with testing the seeding process; do we have any good examples?

**Comment by islemaster** [comment]
This test looks like a good example:

https://github.com/code-dot-org/code-dot-org/blob/3aa480298ca204309879b938a56728e6d348dfa7/dashboard/test/models/script_test.rb#L966-L997

**Comment by islemaster** [comment]
And possibly the DSL tests: https://github.com/code-dot-org/code-dot-org/blob/9990d2246103c08d15cfd970f3ac799bb6ebee73/dashboard/test/dsl/dsl_test.rb

**Comment by breville** [comment]
That first one was perfect, thanks.  (I was thinking I'd need to test the rake task, but of course it's just testing the script model.)

**Pull request merged**
