### PR TITLE
Removes output by silencing the curl command.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes https://app.honeybadger.io/projects/45435/faults/29346552.

Tested on `staging`.

### CODE REVIEW

**Comment by bcjordan** [comment]
Odd that a `return 0` process would be categorized as an error on Honeybadger, any theory why that might happen?

Fix LGTM!

**Comment by ashercodeorg** [comment]
My (weak) belief is that our cron setup takes any output (stdout? stderr? otherwise?) and logs it to HoneyBadger?

**Comment by wjordan** [comment]
@bcjordan for whatever historical reason, our [`cronjob`](https://github.com/code-dot-org/code-dot-org/blob/staging/bin/cronjob) wrapper script (which is used by all cron tasks) has always had logic to treat a process exiting with any output as `warning` rather than `success`, presumably to encourage writing 'clean' cron scripts that return no output to stdout/stderr (which would get ignored in an automated process). For Honeybadger, apparently only output to stderr triggers a warning (see the line of code [here](https://github.com/code-dot-org/code-dot-org/blob/staging/lib/cdo/honeybadger.rb#L15)).

**Comment by bcjordan** [comment]
Great, thanks for closing the loop on that @wjordan!

**Pull request merged**
