### PR TITLE
Fix assignment dialog with courses

### PR DESCRIPTION
**Pull request by megcrenshaw**
Dave investigated a fix for a bug https://codedotorg.slack.com/archives/C04540KNGDQ/p1688060803595729, and this PR implements a solution. The bug happens in the following sequence:

Suppose I have these courses assigned to sections:
Screenshot 2023-07-03 at 10 11 33 PM

I then go to the catalog page, and when I click on Computer Science A, I see this:
Screenshot 2023-07-03 at 10 10 34 PM

indicating that CSA is already assigned to both sections (it is not). This bug is happening only for UnitGroups, because the CurriculumCatalogCard is not passing in a necessary prop to MultipleSectionAssigner.

I tested this manually. Once I added the fix, I instead saw this on the dialog:
Screenshot 2023-07-03 at 10 17 54 PM

When I assigned one section a "Unit" (aka Script) and another section a "UnitGroup" (aka Course), I have the sections looking like this on the Dashboard:
Screenshot 2023-07-03 at 10 20 49 PM

And when I click on the Unit, I see this
Screenshot 2023-07-03 at 10 20 11 PM

And when I click on the UnitGroup, I see this
Screenshot 2023-07-03 at 10 20 18 PM

If I click on an unassigned Unit, I see this
image

And if I click on an unassigned UnitGroup, I see this
image

## Testing story

I tested manually (see above). I think this sort of testing makes a lot of sense to do in a UI test, but not a unit test. I'm open to comments pushing for unit tests here, but if we go that way, I'd love to address that in a follow-up PR given that this is time sensitive.

## Follow-up work

Does the `isStandAloneUnit` prop also need to be passed in? If so, how do we know if a unit is standalone or not? Is it always the opposite of a Course or no?

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by megcrenshaw** [comment]
Flagging the question raised in the Follow-Up Work Section: Does the isStandAloneUnit prop also need to be passed in? If so, how do we know if an offering is standalone or not? Is it always the opposite of it being a course or no? I'm getting lost with the `isStandAloneUnit`, `courseVersionId`, `scriptId`, and `courseId` props.

**Review by bethanyaconnor — APPROVED** [review]
Change looks good to me!

**Comment by bethanyaconnor** [comment]
@kobryan0619 correct me if I'm wrong but there are 3 scenarios we had to handle here:
1. The user is on the course page and wants to assign the course (`isOnCoursePage` is true, `isStandaloneUnit` is false). Only the course should be assigned.
2. The user is on a standalone unit page and wants to assign the unit (`isOnCoursePage` is false, `isStandaloneUnit` is true). Only the unit should be assigned.
3. The user is on a unit-within-a-course page (`isOnCoursePage` is false, `isStandaloneUnit` is false). Both the course _and_ unit should be assigned.

My understanding is that case 3 isn't relevant for the curriculum catalog, so `isStandaloneUnit` technically isn't needed for that page, but it is needed for the unit overview page

**Comment by megcrenshaw** [comment]
Thanks, Bethany! I'm going to go ahead and merge this in, but if I need to provide the `isStandloneUnit` prop too, I'll do that in a follow-up PR.

**Comment by kobryan0619** [comment]
@bethanyaconnor your three scenarios are correct.  

For scenario #1, we said that if a specific Unit from a Course is assigned, the checkbox will still show as checked for those sections.  Ex: If I have a section assigned Unit 2 from CSD and I am on the course landing page of CSD, I will see that section as "checked" in the pop-up.   That is a weird behavior, but the one that Tess, Molly, and I settled on for now.  I don't know if that is relevant here, but just wanted to raise it just in case.

**Comment by megcrenshaw** [comment]
Thanks, @kobryan0619 ! So it sounds like since we don't assign specific units that are also part of a course from the catalog, we're safe to have `isStandaloneUnit` being false on all offerings from the catalog?

**Pull request merged**
