### PR TITLE
Add school_stats_by_years to schools DMS task

### PR DESCRIPTION
**Pull request by jopolsky**
Adding the school_stats_by_years to the DMS task for schools.

### CODE REVIEW

**Comment by bencodeorg** [comment]
I think this change should be made through AWS UI, and then we scoop the change that you've made here into our repo.

**Comment by bencodeorg** [comment]
I should say, in general -- I don't think our DMS tasks actually run based on the criteria in this code, just that this serves as a place to track changes to the tasks we run and gives us something to start with in case AWS DMS loses our settings.

**Comment by jopolsky** [comment]
Yes, but the review process is make the change here. Then modify the DMS task.

**Comment by bencodeorg** [comment]
FYI @wjordan -- spoke with Joanne offline, and I'm going to let her know anytime I'm making a relatively large change to our DMS task (e.g., adding a large table or creating an entirely new task). I'll continue to add small tables to existing tasks though through the AWS UI without review.

**Comment by jopolsky** [comment]
I've updated the task in DMS, we can check if it gets scooped. Looks like it's daily at 7AM -
https://github.com/code-dot-org/code-dot-org/blob/760937e59e4d80c8219702df9ca097f35c79592e/cookbooks/cdo-apps/templates/default/crontab.erb#L63

I think the process described is fine until we move the configuration to CloudFormation.

**Comment by jopolsky** [comment]
Looks like it did not update. I will check if the cronjob is still active.

**Comment by bencodeorg** [comment]
Hmm weird, let me know what you find.

**Comment by jopolsky** [comment]
Closing the PR. The last PR change to include DMS tasks in the scoop, seemed to have scooped the updated config.

**Pull request closed without merging**
