### PR TITLE
Updates the analyze_hoc_activity cron to make use of session weights.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Running MySQL locally...

mysql> SELECT id, session FROM hoc_activity ORDER BY id;
+----+-------------------------------------+
| id | session                             |
+----+-------------------------------------+
|  1 | e017e5e584ad40de72bef55ed0739486    |
|  2 | 32efa689a707f7ef92f71dd3ecb5c073    |
|  3 | bab9dc01d4db70c6fcfc4ea37d7c6e74    |
|  4 | 02933614b67dda09eba0e997ae4385b2    |
|  5 | 94c01b4600dfb8baafd4613d7a67bfdd    |
|  6 | 4a30a0e4d01a1b64a9925aefebf1acc9    |
|  7 | cc03ead6ebae1ab684313be29974430a    |
|  8 | 37ffd319994768a97d2dec753e9e4111    |
|  9 | b2faee85a107cc33f1d240354584ccc7    |
| 10 | 8bc7762304f65f79b9aa80509f05fc8d    |
| 11 | 7994d0d32f40389269ec6fb990a670cb    |
| 12 | ad9395cc20c53b22b974374ea29c9151    |
| 13 | _1_bfb0db6634ea595e84053605c2caef89 |
+----+-------------------------------------+
13 rows in set (0.00 sec)

mysql> SELECT SUM(IF(session LIKE '_%_%', SUBSTRING(SUBSTRING_INDEX(session, '_', 2) FROM 2), 1)) AS count FROM hoc_activity;
+-------+
| count |
+-------+
|    13 |
+-------+
1 row in set (0.00 sec)

**Comment by ashercodeorg** [comment]
@caleybrock 

Not yet ready for review, I need to add some testing...

**Comment by caleybrock** [comment]
fyi @tanyaparker

**Comment by ashercodeorg** [comment]
Dropping this PR, so as to incorporate the refactoring in PR#5977 to accommodate testing.

**Pull request closed without merging**
