### PR TITLE
Fix Violations of and Reenable `Style/AccessorGrouping`

### PR DESCRIPTION
**Pull request by Hamms**
Quoting from the documentation:

> Checks for grouping of accessors in `class` and `module` bodies. By default it enforces accessors to be placed in grouped declarations, but it can be configured to enforce separating them in multiple declarations.

Fix was applied automatically with `bundle exec rubocop --auto-correct --only Style/AccessorGrouping`. I then manually tweaked each of the new calls to more-closely match the manual organization we had applied (including [one](https://github.com/code-dot-org/code-dot-org/pull/48499/files#diff-c08a97b4b9e0db68cc2740bfab5cd758f631c6fb455d83fd62298a9999b8b368R20) that needed parens added to contain a splat operator).

## Links

- https://docs.rubocop.org/rubocop/cops_style.html#styleaccessorgrouping
- https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/AccessorGrouping

## Testing story

Relying on existing tests to verify that this doesn't represent any change in functionality.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
I'll let the Ruby devs weigh in on this one. I prefer the per-line style, but I'm not the one reading this code on a daily basis.

**Comment by bethanyaconnor** [comment]
> I prefer the per-line style, but I'm not the one reading this code on a daily basis.

+1 -- I'm not sure I like having all of these accessors on one line. I like the attempt we've made at organizing them, even if it's imperfect

**Review by sureshc — APPROVED** [review]

**Comment by sureshc** [comment]
Can we multi-line the single call to the attribute accessor method the way we do for other method calls with a large number of arguments?

``` ruby
 attr_accessor
  :child_users,
  :data_transfer_agreement_required,
  :email_preference_form_kind,
  :email_preference_opt_in,
  :email_preference_opt_in_required,
  :email_preference_request_ip,
  :email_preference_source,
  :login,
  :parent_email_preference_email,
  :parent_email_preference_opt_in,
  :parent_email_preference_opt_in_required,
  :parent_email_preference_request_ip,
  :parent_email_preference_source,
  :parent_email_update_only,
  :raw_token,
  :share_teacher_email_reg_partner_opt_in_radio_choice
```

**Comment by Hamms** [comment]
I think part of the problem here is that some of our models are much larger than recommended, leading to us having a lot more accessors than are recommended. I agree that the grouped style isn't ideal for our purposes. We could alternatively standardize around a "separated" style (which looks like this: https://github.com/code-dot-org/code-dot-org/pull/48903), or simply decide that we in fact do _not_ want to start enforcing this rule at all and explicitly disable it (https://github.com/code-dot-org/code-dot-org/pull/48904). Thoughts?

**Comment by Hamms** [comment]
> Can we multi-line the single call to the attribute accessor method the way we do for other method calls with a large number of arguments?

We can! We in fact already do this in a couple places, and can even add some comments and do some loose organization: https://github.com/code-dot-org/code-dot-org/blob/02691f87dc778e2f16b44f9895d59afa900018f8/dashboard/lib/pd/jot_form/question.rb#L9-L16

I'll see if that looks better

**Review by bethanyaconnor — APPROVED** [review]
I personally like this _a lot_ better!

**Pull request merged**
