### PR TITLE
Update Poste and Poste2 to use hashed_email rather than email.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Sadly, there are no tests for any of the code I'm touching. Equally sadly, I'm not adding them as part of this PR.

### CODE REVIEW

**Comment by aoby** [comment]
lgtm. 

re: no tests. I have added a couple [small ones](https://github.com/code-dot-org/code-dot-org/blob/staging/shared/test/test_poste.rb), but sadly no-tests is the state for most of poste :(

**Comment by ashercodeorg** [comment]
Ah, missed seeing those. Those are a sight for sore eyes, thanks for adding them. Let me add a few more (related to these changes) as part of this PR.

**Comment by ashercodeorg** [comment]
Added a few more tests. At some point, I intend to split `poste.rb` into two files (one per module), splitting the test file similarly.

**Comment by ashercodeorg** [comment]
Note that this last commit fixed an existing bug (referencing `unsubscribed_on` rather than `unsubscribed_at`). Not sure how this didn't yield errors in the interim two weeks.

**Comment by ashercodeorg** [comment]
PTAL.

**Comment by aoby** [comment]
Nice tests. Slowly but surely... ;)

LGTM

**Pull request merged**
