### PR TITLE
Assignment Updates: auto open EditSectionDialog 

### PR DESCRIPTION
**Pull request by Erin007**
### Description
[LP-1001](https://codedotorg.atlassian.net/browse/LP-1001) 
[spec ](https://docs.google.com/document/d/1vJySqyKozUxknkhY1KyQXWzbV-0c1vdnpKvRsAsVrdI/edit)

Following the example in the soon-to-be-deprecated [AssignToSection](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/templates/courseOverview/AssignToSection.js) component, I pass along `scriptId` and `courseId` to the new TeacherSectionSelector so they can be used as query params to force open the EditSectionDialog on the teacher homepage when the "Add New Section" link is clicked in the dropdown. 

add-new-section-opens-dialog

Previously the user would navigate to the teacher homepage, but the dialog would not be open.

### Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by dmcavoy** [comment]
Could we pop that dialog up over the course view instead of sending them home?

**Comment by Erin007** [comment]
> Could we pop that dialog up over the course view instead of sending them home?

I can see it both ways. I don't know that would ultimately be much of an advantage for teachers because they would still have to go to the teacher dashboard to add students.  If their main goal was assigning the course or scrip they are currently viewing, they also have that option in the edit section dialog on the home page. It might be nice to auto populate the assignment dropdowns in the edit section dialog  with the course or unit that the teacher was viewing when they clicked "Add New Section", but not sure if that's worth doing? @fontie715 What do you think? @dmcavoy did you have something else in mind?

**Comment by dmcavoy** [comment]
>  @dmcavoy did you have something else in mind?

I just wonder if I'm setting up a class maybe I just want to get the section and the course set up and maybe add students later?  Moving away from the page feels a little bit to me like I'm losing the page I worked hard to get to.

**Review by davidsbailey — APPROVED** [review]

**Comment by davidsbailey** [comment]
Code changes look good! @dmcavoy I like what you're suggesting but perhaps because we're reviewing such a long list of H1 2020 potential next work items I'm tempted to ask, is doing this more important than the next work item on our list? I think parity with previous behavior (what @Erin007 has here) is probably good enough but I think @fontie715 should have final say.

**Comment by Erin007** [comment]
Confirmed with Amanda that opening the section edit dialog in the context of the script/course overview page is a nice-to-have, but not worth the time trade off in the immediacy. It's a great idea though, so we're tracking in [LP-1018](https://codedotorg.atlassian.net/browse/LP-1018) to potentially re-visit.

**Pull request merged**
