### PR TITLE
fix funOMeter test

### PR DESCRIPTION
**Pull request by Hamms**
and also actually fix Fun-O-Meter for iPad. The touch events for the rating buttons were broken on iOS. They no longer are.

### CODE REVIEW

**Comment by wjordan** [comment]
:+1: Seems safe enough if you've confirmed working locally. Let's get this merged into test so CI can verify the fix

**Comment by Hamms** [comment]
It's close but not quite there. This is priority #1 for me this morning

**Comment by davidsbailey** [comment]
It should be possible to check in the test and mark it @no_ie, if it only fails in IE.

**Comment by Hamms** [comment]
It's iOS, actually. I'm hoping to have an actual fix in early today, I just didn't want to delay the DTT while I work

**Comment by davidsbailey** [comment]
oops, I meant @no_mobile rather than @no_ie

**Pull request merged**
