### PR TITLE
Add high_needs? function to school model

### PR DESCRIPTION
**Pull request by jopolsky**
Ben wanted me to put in a function before I left to show how to pull data from the `school_stats_by_years` table, in relation to `schools`. The high needs property will be required to determine if a teacher is eligible for a discount when purchasing circuit kits.

Here, just connecting the models.

### CODE REVIEW

**Comment by bencodeorg** [comment]
Are there associated tests? Want to make sure this works as expected with various null states of # of students and # of students on free and reduced meals

**Comment by bencodeorg** [comment]
Added brad since he would use this to determine teacher eligibility for Adafruit discount codes.

**Comment by jopolsky** [comment]
I can add tests after if I have some more time tomorrow. I also need to work on the school districts auto-complete. I did test it locally for all the different variants, but we don't seed any data in `school_stats_by_years` currently.

Tests should include:
- row in school_stats_by_years for the school with null students_total, false
- row in school_stats_by_years for the school with null frl_eligible_total, false
- row in school_stats_by_years for the school with frl_eligible_total less than 50% of students_total, false
- row in school_stats_by_years for the school with frl_eligible_total more than 50% of students_total, true
- multiple rows in school_stats_by_years for the school, and test same above conditions
- no rows in school_stats_by_years for the school, false

**Comment by bencodeorg** [comment]
Ok nvm seems simple enough, I've been burned so many times by unexpected postgres interpretation of null values that I'm paranoid.

**Pull request merged**
