### PR TITLE
Commit content on LB before deploying to LB.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
A few things aren't clear to me, feedback welcome.

(1) Is it most helpful to commit content on LB before the PR is created, before the PR is merged, or (as done) before the PR is both created and merged?

(2) This PR violates that the only communication between machines is between GitHub merges. Is it better to run `bin/cron/commit_content` on `levelbuilder` via cron just before the `deploy_to_levelbuilder` cron (which needs to run on `test`)? Of course, though this prevents this violation, it also disconnects and obfuscates what is happening.

**Comment by ashercodeorg** [comment]
@wjordan especially curious about your opinion on (2).

**Comment by jeremydstone** [comment]
I don't have the background to know what the right thing to do is here. Interested in what @davidsbailey and @Hamms think. What did the old DOTD script do and with this change are we doing the same steps it used to do?

**Comment by ashercodeorg** [comment]
@jeremydstone, you can see the old DOTD script at [bin/cron/dotd_old](https://github.com/code-dot-org/code-dot-org/blob/staging/bin/dotd_old). It does what I do here. The question is whether we would rather allow cross environment behavior or split a process into separate crons.

**Comment by davidsbailey** [comment]
(1) sounds good. I'm opposed to (2), because a timing dependency between cronjobs on different machines seems like a legitimate potential source of bugs, whereas a rule about machines not interacting with each other seems like more of a nice-to-have.

One high-level question -- it looks like we're deploying directly from the test branch to levelbuilder, without going through a `dtp_candidate` branch. How will deploys to levelbuilder work on days when we are not DTPing the most recent test branch? or is the implementation that we DTL every green test run, such that we never have to DTL an "old" green build?

If you decide to DTL from a dtp candidate branch, one advantage would be that levelbuilder could (3) update itself from the dtp candidate branch after committing its own content. this would let you keep the machines from interacting directly with each other, as you had expressed a desire to accomplish in the PR description.

**Comment by ashercodeorg** [comment]
Talking with @wjordan, we are going to (at least for now) go the route of timing dependencies. Though evil, it is the path of least resistance (this method would involve setting up the requisite ssh keys). And if we go the route of frequent content commits (e.g., LBs committing to GitHub directly), this approach becomes more practical.

That said, someone should own (re)evaluating this (possibly poor) decision.

**Pull request closed without merging**
