### PR TITLE
Updates the CS Ed Week FAQ to reflect 2015 dates.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Note that we may or may not want to separately consider mention of doing the HOC in the week(s) prior or after the official week.

**Comment by ashercodeorg** [comment]
Tanya: Are there any i18n ramifications that I should be aware of with this change?

**Comment by ashercodeorg** [comment]
@caleybrock

**Comment by caleybrock** [comment]
It's markdown so it should be fine. lgtm

**Comment by tanyaparker** [comment]
:+1:

**Pull request merged**
