### PR TITLE
Use objective key to identify objectives

### PR DESCRIPTION
**Pull request by bethanyaconnor**
This is
1. much cleaner
2. fixes a bug where the fake key would get sent back to the server preventing the lesson from being saved ([slack thread](https://codedotorg.slack.com/archives/CNZP84FJ5/p1608162502019700?thread_ts=1608156821.014200&cid=CNZP84FJ5))

## Links

- [spec]()
- [jira]()

## Testing story

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
I'm not totally sure I understand what's going on here. is the key generated by the client being used as the key on the server?

**Comment by davidsbailey** [comment]
OK, I caught up on the slack thread and see what's going on now. this looks like a good fix. thanks for getting to the bottom of this!

**Review by davidsbailey — APPROVED** [review]
FWIW this seems like the kind of thing that a UI test could catch, although I don't want to block this PR on writing one.

**Comment by bethanyaconnor** [comment]
Yeah, the key wasn't being used on the server but was being passed back in `originalLessonData` as it was edited server-side.

I agree that it would be good to have an end-to-end test on editing an entirely populated lesson to try to catch things like this. I'll add something to our backlog

**Review by dmcavoy — APPROVED** [review]
Looks good. Thanks for tackling. I can try to tackle figuring out how to create a test for this

**Comment by davidsbailey** [comment]
> Looks good. Thanks for tackling. I can try to tackle figuring out how to create a test for this

I think just adding some objectives (and other curriculum object types) to `TestController#create_migrated_script` would cover this

**Pull request merged**
