### PR TITLE
Update google_drive gem to 2.1.2 and google-api-client gem to 0.10.3

### PR DESCRIPTION
**Pull request by joshlory**
`bundle update --source google-api-client google_drive`

### CODE REVIEW

**Comment by joshlory** [comment]
+cc @breville @tanyaparker

**Comment by ashercodeorg** [comment]
Did this cause the breakage [here](https://app.honeybadger.io/projects/45435/faults/33933800)?

**Comment by wjordan** [comment]
Yes, [`update_hoc_map`](https://github.com/code-dot-org/code-dot-org/blob/staging/bin/cron/update_hoc_map#L67-L76) will need to be upgraded. See [Media Uploads](https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md#media-uploads) section of the MIGRATING doc for details.

**Comment by ashercodeorg** [comment]
Also see [here](https://developers.google.com/apis-explorer/#search/fusiontables/fusiontables/v2/fusiontables.table.replaceRows) for Fusion Tables documentation.

**Comment by tanyaparker** [comment]
Just letting you know I've seen this thread and I'm tracking fixing `update_hoc_map` asap. Thanks!

**Pull request merged**
