### PR TITLE
add 2-day subjects and rename academic year subjects for consistency

### PR DESCRIPTION
**Pull request by tanyaparker**
image

screen shot 2018-06-06 at 3 22 22 pm

### CODE REVIEW

**Comment by tanyaparker** [comment]
I confirmed the new subject names with Dani. We decided to stay in this order (instead of increasing order of days) because this follows the chronological order of when we'd set up these workshops.

We're keeping TeacherCon and Facilitator Weekend for now, but after this summer we'll remove the TeacherCon subject and move the Facilitator Weekend subject to the `Facilitator` course.

**Comment by tanyaparker** [comment]
@aoby hehe :facepalm: migration added!

**Comment by aoby** [comment]
LGTM. Make sure you run the migration up and down locally (`bundle exec rake db:migrate` and `bundle exec rake db:rollback`) to make sure it works. You might want to check in the `schema.rb` file after running the migration, so it contains the newer schema number, though this is not necessary since DTS will do it.

**Comment by tanyaparker** [comment]
Thanks for the reminder! They ran successfully, and I confirmed the schema number updated appropriately in `schema.rb`. Now fixing circle test...

**Pull request merged**
