### PR TITLE
Host poster downloads on S3

### PR DESCRIPTION
**Pull request by islemaster**
Move the following poster downloads out of Dropbox and into the `downloads.code.org` S3 bucket:

- https://downloads.code.org/posters/poster_steph.pdf
- https://downloads.code.org/posters/poster_malala.pdf
- https://downloads.code.org/posters/poster_hadi.pdf
- https://downloads.code.org/posters/poster_mary.pdf
- https://downloads.code.org/posters/poster_satya.pdf
- https://downloads.code.org/posters/poster_shakira.pdf

You can find downloads for these posters on the following pages:

- https://hourofcode.com/us/promote/resources#posters **(currently broken)**
- https://code.org/educate/resources/posters
- https://code.org/educate/resources/inspire

Note that I've uploaded these files [to the target location in S3](https://s3.console.aws.amazon.com/s3/buckets/downloads.code.org/posters/?region=us-east-1&tab=overview) before opening this PR, with the appropriate `application/pdf` mime type.

I'm doing this because these downloads keep breaking when Dropbox removes the files on somebody's behalf.  Each time I've tried to track this down, the person blamed by Dropbox history claims they didn't do anything intentional.  I'm not sure why Dropbox has issues with these files in particular, but they haven't changed in a long time and it seems reasonable to host them on S3 anyways.

Issue history in Slack:

- [January 14th, 2020](https://codedotorg.slack.com/archives/C06E60KL4/p1579025229008800?thread_ts=1579025229.008800)
- [November 11th, 2019](https://codedotorg.slack.com/archives/C06E60KL4/p1573490670134900?thread_ts=1573490670.134900)
- [October 8th, 2019](https://codedotorg.slack.com/archives/C06E60KL4/p1570547548004200?thread_ts=1570547548.004200)
- [September 27th, 2019](https://codedotorg.slack.com/archives/C0T0PNTM3/p1569604000183400)

## Testing story

These links now go directly to the S3 download no matter which environment you're on or language you're viewing in.  You can check them directly with the links at the top of this PR description.  I've also run all the changed pages in local development and checked that the links open as expected.

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by breville — APPROVED** [review]
Since we have a dependency on a lot of other content in S3, this seems reasonable.  But it's a pity to lose version history like this.  And it would be very interesting to understand why it's just these files that have issues, and not other pegasus binaries...

**Review by Hamms — APPROVED** [review]
+1 that it would be nice to understand this better, but this seems like a great workaround.

Is there a desire to support managing binary files via dropbox in the long term?

**Comment by islemaster** [comment]
> And it would be very interesting to understand why it's just these files that have issues, and not other pegasus binaries...

I'm not totally sure it is just these files - we've had more significant issues in the last couple of days with the `hourofcode.com` folder and others.  I'm starting to get generally suspicious of Dropbox shares with too many owners.  But these in particular have broken without anyone noticing several times, and I'm interested in removing them from the equation in case they add noise to the broader conversation.

> Is there a desire to support managing binary files via dropbox in the long term?

I believe so, yes.  I could see a transition at the far end of platformization that moves all pegasus content into a different system, but for now Dropbox-managed content is a powerful and flexible tool for our content editors, including the ability to add images, PDFs, etc. without engineer help.

**Comment by islemaster** [comment]
In fact, I haven't been able to track down "who" removed the files in this latest case because of the other Dropbox issues we're having at the moment.

**Pull request merged**
