### PR TITLE
Turn on SCSS static analysis (`rake lint` and HoundCI)

### PR DESCRIPTION
**Pull request by joshlory**
Adds static analysis for SCSS files in Dashboard.  [HoundCI](https://houndci.com/configuration#haml) will comment on SCSS issues in Pull Requests, and staging will fail the build if errors are detected.

For now I've only turned on linters that we already pass with the current codebase.  For the full list of available linters see: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md.

The `rake lint` task now includes `rake lint:scss`.

### CODE REVIEW

**Comment by joshlory** [comment]
Sample HoundCI message:

houndci-scss-lint

**Comment by joshlory** [comment]
This PR also upgrades `sass-rails` from 4.0.5 -> 5.0.4 and `sass` from 3.2.19 -> 3.4.22.  I spot-checked the site and didn't see any issues from this change, but let me know if you have concerns about changing these gem versions!

**Comment by ashercodeorg** [comment]
LGTM! Do we have any plans to try to clean up our SCSS codebase? Note that I don't author SCSS, so you might want a SCSS author as a reviewer as well.

Note that I've fallen off the bandwagon of cleaning up our ruby and haml, I'll try to carve some time to hop back on.

**Comment by joshlory** [comment]
Yes!  Adding the linter is the first step for cleanup — it will ensure we don't regress any cleanup we do in the future.  After this is merged I'll open PRs to fix & re-enable some of the low-hanging `scss-lint` rules.

**Comment by wjordan** [comment]
integration part LGTM, though I haven't authored any SCSS in a while either so I can't add much on that front

**Pull request merged**
