### PR TITLE
chore/ai_tutor_instructors

### PR DESCRIPTION
**Pull request by jordan-springer**
bringing this data to redshift
see: https://codedotorg.atlassian.net/browse/DATAOPS-575

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
Is the removal of `prompt` because of PII or lack of usefulness?

Should `ai_response` also be removed?

Link to model/schema reference: https://github.com/code-dot-org/code-dot-org/blob/8203e3d073f726b11ec5b11aaebb97976a8914a4/dashboard/app/models/ai_tutor_interaction.rb

**Comment by jordan-springer** [comment]
@cat5inthecradle it was in anticipation of that being a potential pii field (also agree with ai_reponse)

**Review by jordan-springer — COMMENTED** [review]
adding a few more tables, excluded potential pii fields

**Comment by sureshc** [comment]
Successful test:

```
Pending update for stack `DATA-production`:
Modify DMSCron [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TableMappings)
Finished stack:data:validate (1 minute)
```

**Comment by sureshc** [comment]
Deployed:
`code-dot-org % bundle exec rake stack:data:start RAILS_ENV=production ADMIN=true`

```
 Stack update requested, waiting for provisioning to complete...
.2024-03-22 23:51:49 UTC- DMSCron [UPDATE_IN_PROGRESS]
....2024-03-22 23:52:24 UTC- DMSCron [UPDATE_COMPLETE]
2024-03-22 23:52:25 UTC- DATA-production [UPDATE_COMPLETE_CLEANUP_IN_PROGRESS]

Stack update complete.
Outputs:
Finished stack:data:start (2 minutes)
```

**Review by sureshc — APPROVED** [review]
I looked at every varchar/text column and agree that the ones that could contain sensitive data are being excluded in this export.

**Comment by cat5inthecradle** [comment]
@jordan-springer @sureshc Is this ready for Infra to deploy?

**Pull request closed without merging**
