### PR TITLE
Add teacher permissions to special events

### PR DESCRIPTION
**Pull request by caleybrock**
review @tanyaparker

### CODE REVIEW

**Comment by laurelfan** [comment]
Hm, we want to allow any teachers to approve special events? This wasn't intended to be admins?

**Comment by caleybrock** [comment]
@laurelfan We want someone to be able to approve special events, but we don't want to give them admin access so we decided to change the url (and not link to it anywhere) and give teacher permissions. Is there a better way?

**Comment by tanyaparker** [comment]
@laurelfan We're giving a CS Ed Week lady access so that she can be the one to approve these instead of Laura. We're making it teacher only so we don't have to make her admin. Special events just get their own page and a different styled pin on the map.

**Comment by tanyaparker** [comment]
lgtm

**Pull request merged**
