### PR TITLE
add back images accidentally removed in e86e1b7529

### PR DESCRIPTION
**Pull request by davidsbailey**

### CODE REVIEW

**Comment by davidsbailey** [comment]
verified post-merge that there are no deleted files in the DTP that would result from shipping  e86e1b7 plus this fix.

**Comment by Erin007** [comment]
Do we know how they disappeared in the first place?

**Comment by davidsbailey** [comment]
nope :-( the only context we have is what's in #developers.

**Comment by tanyaparker** [comment]
Thanks for restoring this!

**Pull request merged**
