### PR TITLE
[Draft] update node lambdas to nodejs 18

### PR DESCRIPTION
**Pull request by cat5inthecradle**
AWS is ending support for Node lambdas older than 14. This PR updates all Node Lambdas to 18, the same as the rest of the project.

Testing this is somewhat challenging. See testing story below.

I've chosen to reorganize these lambdas, rather than leaving them in the root of the `aws/cloudformation` path. Lambdas that are included "inline" in the cloudformation template are moved to their own directory, as these lambdas can only use a short list of external modules. Lambdas that require `npm install`ed modules are each moved to their own directory (IN PROGRESS). Some custom resource lambdas are unused, and are thus removed.

I've also renamed some ruby helper functions to better describe what they do, and be more searchable. Added tests for some of these as well.

## Links

Jira: [INF-689](https://codedotorg.atlassian.net/browse/INF-689)

## Testing story

I've done a couple of things to test this change:

* Added a test for every lambda js file (all but the S3BucketConfiguration lambda, which is hardcoded). These tests only verify that the file can be `require`d and that the `handler` function can be called. These tests all pass under Node 18, but do not confirm full compatibility, as we never had full test coverage.
* Added eslint, configured to check syntax (no style enforcement). These pass under Node 18, suggesting syntax compatibility.
* Updated most dependencies to newer versions **this is just as likely as the Node 18 update to cause problems**

Are we still using the API's correctly for dependencies? Looks good to me, but I have not executed the code with the new dependencies.

* cfn-response (not tested)
* honeybadger (should be fully tested)
* aws-sdk (partially tested)

## Deployment strategy

Monitor the deployment of this change. Any lambda that is a custom resource will fail at the Cloudformation Deploy phase of the deployment.

Test & monitor other lambdas after deployment. Lambdas that are not custom resources should be tested manually after this change is deployed. Logs for the lambda should be reviewed to make sure regular traffic is successful.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by sureshc** [comment]
We should put together a deployment plan. Most of the Lambda Functions modified here are provisioned by the `lambda` Stack and can be validated with a rake task (`bundle exec rake stack:lambda:validate RAILS_ENV=production ADMIN=1`) using the `codeorg-admin` AWS client profile.

The Lambda in the offsite account likely needs to be updated manually by uploading the new static template file.

**Review by sureshc — APPROVED** [review]
I can help with the offsite deployment!

**Comment by cat5inthecradle** [comment]
@sureshc I think this is good to go. We can find time next week to deploy.

**Comment by sureshc** [comment]
I deployed this using the instructions in the READ ME today at ~1:30 PM PT.

**Comment by snickell** [comment]
@cat5inthecradle is my understanding correct that because these lambdas are node-6, we can't deploy new versions without bumping the node version at the same time?

Its intimidating because ideally it would be nice to get the tests in place with the old node 6 passing, and then use the tests to make the transition to a newer node less scary.

**Comment by cat5inthecradle** [comment]
Re-requesting review now that this is bumped to Node 18.

**Pull request closed without merging**
