### PR TITLE
Abandon the "Go Beyond" level type

### PR DESCRIPTION
**Pull request by joshlory**
Convert existing levels back to `ExternalLink` levels.  Per conversation with @ryansloan we're no longer planning to use `GoBeyond` in Course A-F.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Should [this](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/models/levels/level.rb#L281) also be removed?

**Comment by ashercodeorg** [comment]
Do any of these levels exist on levelbuilder or production?

**Comment by joshlory** [comment]
Yes — I'm keeping the empty model to avoid "subclass type does not exist" exceptions.

**Comment by joshlory** [comment]
After the level changes are deployed to all environments I will remove the ideal level source ref @ashercodeorg mentioned above, and I'll clean up the remaining code changes from PR https://github.com/code-dot-org/code-dot-org/pull/14594.

**Pull request merged**
