### PR TITLE
Datablock Storage: disable Firebase

### LINKED ISSUE #58950: UI tests for data blocks and data tabs
The ec_data_blocks tests are proving to be difficult to mock and what we really want is end-to-end tests instead.

There are eyes tests for data blocks already (but they are missing getColumn so as long as we add that we should be able to remove the ec_data_blocks tests for that block without reducing coverage)

https://github.com/code-dot-org/code-dot-org/blob/f35aff5378a59c3c66603184a475664a0208c22c/dashboard/test/ui/features/star_labs/applab/data_blocks.feature/#L3-L14

We want to modify allthethings and add to these tests

### LINKED ISSUE #59800: Datablock Storage: Change tab style back to rounded

### PR DESCRIPTION
**Pull request by snickell**
**This PR disables Firebase in active code paths**, including test (but does not remove it, see #56994), and modifies test code so it works with Datablock Storage.

- Disable Firebase for Applab and Gamelab, so `initStorage(DATABLOCK_STORAGE)` is the only option
- All tests now run against DatablockStorage, fix callback(success) instances to pass `dataBlocks.feature`
- Remove `ec_data_blocks.js` integration test, this is covered by `dataBlocks.feature`, and isn't a very useful integration test without access to the backend (plus mocking isn't easy to support inside the levelSolutions test structure).
- Adds a testGetColumn() clause to dataBlocks.feature:
```
function testGetColumn() {
  console.log('testGetColumn ' + elapsedTime());
  var col = getColumn(table, 'name');
  if (col.length >= 1 && col[col.length-1] == 'Bob') {
    testDelete();
  } else {
    console.log('error in testGetColumn: expected ["Bob"] but got: ' + col);
  }
}
```

Fixes [#58950](https://github.com/code-dot-org/code-dot-org/issues/58950)
Fixes [#59800](https://github.com/code-dot-org/code-dot-org/issues/59800)

### CODE REVIEW

**Comment by snickell** [comment]
Failed unit tests:

While we don't modify ec_canvas.js, it looks like we maybe don't terminate our UI test, or something like that? In any case, our modification shifting ec_datablocks.js into ec_simple.js doesn't seem to have "taken".
```

SUMMARY:
--
2293 | ✔ 67 tests completed
2294 | ✖ 40 tests failed
2295 |  
2296 | FAILED TESTS:
2297 | integration tests
2298 | Level tests
2299 | ./applab1/ec_canvas.js
2300 | ✖ Canvas
2301 | Chrome Headless 125.0.6422.141 (Linux x86_64)
2302 | Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
2303 |  
2304 | ✖ drawImageURL with callback
2305 | Chrome Headless 125.0.6422.141 (Linux x86_64)
2306 | Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Failed UI tests ([s3 log]( https://cucumber-logs.s3.amazonaws.com/circle/10021/Chrome_star_labs_applab_data_tab_output.html?versionId=n_r6fR1umWbrUOWs_Fsm6q8NYCjk0fzU)):
```
[test] [star_labs/applab/data_tab] <b>dashboard</b> UI tests failed with <b>Chrome_star_labs_applab_data_tab</b> (2:31 minutes, 1 failed with 2 reruns) <a href='https://cucumber-logs.s3.amazonaws.com/circle/10021/Chrome_star_labs_applab_data_tab_output.html?versionId=n_r6fR1umWbrUOWs_Fsm6q8NYCjk0fzU'>☁ Log on S3</a><br/>rerun:<br/>bundle exec ./runner.rb --html -c Chrome -f features/star_labs/applab/data_tab.feature
--
807 | [star_labs/applab/data_tab] UI tests for Chrome_star_labs_applab_data_tab failed (2:31 minutes, 1 failed with 2 reruns)
```

**Comment by snickell** [comment]
1. **Unit tests are passing**, which suggests that [Remove references to firebase from runLevelTest.js](https://github.com/code-dot-org/code-dot-org/pull/59667/commits/38506cea8a87dc81b6e500c2672bac6c8162b9c4)  (a commit which we never tested by itself) was successful.
2. **UI tests are still not passing**, so the seed data introduced by merging in `datablock/seed-manifest` wasn't enough to fix everything all by itself, but we're getting much further. It shows the data, the preview page works, but nothing appears on import. Are we maybe hitting the "doesn't always refresh on adding shared table" bug (#58456)?
  - Here's the [sauce labs link](https://app.saucelabs.com/tests/1bc0e728e8e048329948e023ac479f8e#42) for the previous run

#### SauceLabs run breakdown

1. UI seeding is working at the most basic level, "100 Birds of the World" shows up in sauce: image
2. Preview button on the dataset even works: image
3. And the preview popup closes when "import" is clicked, but nothing appears in the table list: image.

Could this be the "need refresh before showing up" bug (#58456)?

**Comment by snickell** [comment]
Update, yup, I think this is the UI test showing a genuine bug,  this repros consistently for me on prod (but not locally, so its probably a timing thing), moving further discussion over to issue #58456:

https://github.com/user-attachments/assets/78b9c0d6-fddf-4864-b43c-6f3c8d4cfa56

**Comment by snickell** [comment]
Fixed by #59799, which makes the calls properly sequential (even with 3s of latency introduced by chrome):
image

Merging branch in here to see if it fixes our UI test.

**Comment by snickell** [comment]
Full green: are we ready to merge? 👀

**Review by cnbrenci — APPROVED** [review]
We did it!

**Pull request merged**
