### PR TITLE
Fixes violations of Style/CollectionMethods and reenables the rubocop check.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes generated by "bundle exec rubocop --only Style/CollectionMethods --auto-correct".

### CODE REVIEW

**Comment by joshlory** [comment]
Let's [align with the style guide and use `find`, `map`, `select`, & `reduce`](https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size).

This is the [rubocop default](https://github.com/bbatsov/rubocop/blob/eda0370be2a622cdcfe36aac1577e1751ebea6c8/config/default.yml#L309-L322) but it looks like Hound has [overridden the defaults in their config](https://github.com/houndci/hound/blob/cd69261b3c6d0626a04089e8a2728f3629f96e8d/config/style_guides/ruby.yml#L6-L15).

After that change, LGTM!

**Comment by ashercodeorg** [comment]
Hmm. Though I don't understand the override graph, looking, I would expect https://github.com/code-dot-org/code-dot-org/blob/staging/.rubocop_hound.yml#L14 (which aligns with the style guide) to take precedence. How do I prevent those rules from being overriden?

**Comment by joshlory** [comment]
Weird, this looks like a rubocop bug.  I tried adding the following to our `.rubocop.yml` and re-running auto-correct, but it corrected zero issues:

``` yml
Style/CollectionMethods:
  PreferredMethods:
    detect: 'find'
    inject: 'reduce'
```

**Comment by ashercodeorg** [comment]
My guess is that the lack of corrections was an issue of priority: it must be that our .rubocop_hound.yml has higher precedence than our .rubocop.yml?

**Comment by ashercodeorg** [comment]
Indeed, rubocop_hound.yml has higher precedence than rubocop.yml.

From https://github.com/bbatsov/rubocop:

_The optional inherit_from directive is used to include configuration from one or more files. This makes it possible to have the common project settings in the .rubocop.yml file at the project root, and then only the deviations from those rules in the subdirectories. The files can be given with absolute paths or paths relative to the file where they are referenced. The settings after an inherit_from directive override any settings in the file(s) inherited from. When multiple files are included, the first file in the list has the lowest precedence and the last one has the highest._

**Comment by joshlory** [comment]
> The settings after an inherit_from directive override any settings in the file(s) inherited from.

I read that to mean settings in `.rubocop.yml` have higher precedence than `.rubocop_hound.yml` as long as they occur _after_ the `inherit_from` directive.

**Comment by ashercodeorg** [comment]
Ah, right, I misread. Hmm.

**Pull request closed without merging**
