### PR TITLE
Add Mapbox jobs to Crontab

### PR DESCRIPTION
**Pull request by bethanyaconnor**
Relies on #30035

### CODE REVIEW

**Comment by sureshc** [comment]
I should have brought this up a long time ago, but I think both the old job and the new `update_census_mapbox` job invoke `census::CensusSummary.summarize_census_data` a long running batch/aggregation method that computes which schools do and do not teacher Computer Science.  Looks like these jobs will run side-by-side for a period of time, so they might be both trying to carry out batch/aggregation updates of the same census school summary logic at the same time.

I think it might be time to extract the Census summarization logic to run in its own job.  That’s partly to make it easier for other engineers to find it.  It wasn’t intuitive to me that a job that updates a map also, first, updates the Access Report data.  This would add its own complexity, because the scheduled process that uploads Access Report data to Fusion Tables and MapBox would, ideally, be dependent on the Access Report summarization job completing first.  There may also be logic in the upload jobs that is dependent on invoking the summarization logic.

**Comment by bethanyaconnor** [comment]
Oh interesting -- I'll be honest that I don't fully understand what the census job does. I'll look into how much work it'll take to separate these out -- if it's not too much I'm happy to do it. I've split out enabling the hoc mapbox job to run into PR #30048 as that is a very quick job that shouldn't be blocked by this.

**Comment by bethanyaconnor** [comment]
Thinking about this more and I'm considering either just removing the `Census::CensusSummary.summarize_census_data` from Mapbox script if the tolerance for staleness is high enough or putting both the update to Fusion Tables and the update to Mapbox into the same script. It definitely isn't worth it to run `summarize_census_data` twice in one night.

WRT splitting up the job, I'm not sure the best way to ensure this dependency. In all honesty, the best option might be to simply rename this job -- updating the map is the end result but doesn't really cover everything it does. I'm not fully convinced they need to be separate jobs, but I'm also not totally sure of what the census summary is used for other than the annual access report and this map.

**Comment by sureshc** [comment]
I think removing the call to `Census::CensusSummary.summarize_census_data` from the MapBox job is a decent short term solution.  Staleness of the data in the map is probably not a significant issue.

The Access Report data produced by the summarization job is used by many Tableau Reports, ad hoc reports, the annual state of CS report, and the `/yourschool` map.  It is confusing to me that we bury the actual data summarization logic in a script whose name indicates that its primary job is to upload map data.

Renaming the job to something like `summarize_access_report_data` and having that single job upload data to MapBox seems better.  That way there's no need to manage dependencies between multiple cron jobs.  We can use Ruby logic to decide whether a problem with the summarization should control whether or not to proceed with uploading the data to MapBox.

**Comment by bethanyaconnor** [comment]
Okay sounds good. I'm going to close this PR, create a PR that removes the `Census::CensusSummary.summarize_census_data` from the Mapbox job and one that enables the job so the Mapbox work can be unblocked.

I'll also create a PR to rename the job and we can continue this discussion in that PR.

**Pull request closed without merging**
