### PR TITLE
Switch from CircleCI 1 to 2

### PR DESCRIPTION
**Pull request by jeremydstone**
This PR switches our CircleCI build from v1 to v2. It removes our CircleCI v1 config file and adds a CircleCI v2 config file. (The v1 config file was `circle.yml` in the root directory; the v2 config file is `.circleci/config.yml`.) The v2 config file was put together by the CircleCI migration team and they have run it with green builds.

I got the contents of the v2 config file, at CircleCI's direction, by copying and pasting from the "Config" tab from one of our CIrcleCI 2 builds: https://circleci.com/gh/code-dot-org/code-dot-org/47541#config/containers/0

### CODE REVIEW

**Comment by islemaster** [comment]
LGTM! This is going to break some of our Circlarify tools, but we can fix
that up later.

**Comment by islemaster** [comment]
Bundler's exit status 5 is apparently an [`InstallError`](https://github.com/bundler/bundler/blob/a400c5ed9eca82598a76f9818a1bf7129515a2a0/lib/bundler.rb#L59), which is deeply unhelpful on its own.

**Comment by islemaster** [comment]
Pushed three changes I've selected after experimenting on a separate branch:

- Install `libmysqlclient-dev` and `libsqlite3-dev` which are required for some gems to build native extensions.  I suspect we had some builds passing earlier just because cached gems didn't need to rebuild native extensions.
- Remove `bundle config specific_platform true`.  This is a setting about how we build our Gemfile.lock file, but Circle CI should never be modifying Gemfile.lock so it's unnecessary.
- Add the `--deployment` flag to the `bundle install` call - again because Circle should never modify `Gemfile.lock`.  [Deployment mode](http://bundler.io/man/bundle-install.1.html#DEPLOYMENT-MODE) is designed for deployment and CI, and seems to add some validation and guarantee that we won't update Gemfile.lock.

**Comment by islemaster** [comment]
So, we've got multiple `bundle install` calls in our build (within different subdirectories).  Most of these don't have the `--path` flag used in our top-level bundler step in config.yml.  It looks like we're [hitting a permissions error](https://circleci.com/gh/code-dot-org/code-dot-org/48236) when this happens, and it's not clear to me what bundler is trying to write.

```
'bundle --without development production adhoc staging levelbuilder integration --quiet --jobs 36' returned 23
The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
There was an error while trying to write to
`/home/circleci/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions`.
It is likely that you need to grant write permissions for that path.
```

I've got a few ideas for chasing this:
- Skip `bundle install` steps in `rake install` and `rake build` on Circle (when `ENV['CIRCLECI']`) since we already ran it with correct settings earlier.  I'm not sure what's different about running `bundle install` inside the dashboard and pegasus directories though, so I'm not sure this will work.
- Add the appropriate `--path` flag to every `bundle install` call in our build process when on Circle.  This seems invasive and maybe fragile, but also maybe more likely to work?
- Add `--deployment` flag to every `bundle install` call in our build process when `ENV['CI']`.  This seems like a smarter idea (possibly a best practice) and might generate more useful failure output, especially if these errors are happening because our bundle install calls are trying to change our Gemfile.lock.
- Some global config change, either getting permission to write to the directory in question or globally changing the default Gem directory to sidestep this issue altogether.

Since I'm out for a couple weeks, someone else will have to follow up on these ideas.  I think we're getting close though!  Don't forget that builds will sometimes pass if cached gems are already in a good state, so "rebuild without cache" to verify that things are really working.

**Comment by balderdash** [comment]
I'm pretty sure the permissions issue was the result of running bundle as `root` here: https://github.com/code-dot-org/code-dot-org/blob/12a7aee7deb03b5e892ff70de3095364e1142364/.circleci/config.yml#L98-L99

Removing `sudo` from those lines seems to be helping: https://circleci.com/gh/code-dot-org/code-dot-org/48271

**Pull request merged**
