### PR TITLE
alphabetize artist names

### PR DESCRIPTION
**Pull request by tanyaparker**
[Spec](https://docs.google.com/document/d/1f8l-Vdyp60lDfgX7GO-Q98rHe_Muy8yGtnH7bdpNyHo/edit)

### CODE REVIEW

**Comment by tanyaparker** [comment]
@breville I added a few that were missing. Did you not put these names in on purpose? Perhaps not finalized licenses? Perhaps I missed your PR where you already updated to this spec?

**Comment by breville** [comment]
@tanyaparker Thanks.  I had just kept using the prior list until I heard what our master list was going to be for this page.

**Comment by breville** [comment]
It looks like the song manifest has changed again: https://staging-studio.code.org/api/v1/sound-library/hoc_song_meta/songManifest.json

Though it needs to be [fixed](https://github.com/code-dot-org/dance-party/issues/307) to be properly alphabetical.

Let me know if you want me to do an update to this PR to match it.

And note that I decided not to sort the homepage ones programmatically at this stage because we might end up wanting to do something special, especially with DCDO, where they're not purely alphabetical.

**Comment by ryansloan** [comment]
Note that some of these weren't properly alphabetized in that document - I fixed but in case you were using it @breville

**Comment by breville** [comment]
Thanks @ryansloan.  @tanyaparker The doc does seem to have some differences in artist names, versus the cached manifest I shared, so presumably the doc is now the source of truth.

**Comment by tanyaparker** [comment]
@breville yes please - go ahead and update to this PR.

**Comment by breville** [comment]
Updated, but sent some open questions your way.

**Comment by breville** [comment]
Updated post discussion.

**Pull request merged**
