### PR TITLE
Fix cron job git error on test environment

### PR DESCRIPTION
**Pull request by sureshc**
#23574 did not work.  Explicitly detect Rails server to determine whether current execution environment is the Dashboard server or a cron job.

### CODE REVIEW

**Comment by wjordan** [comment]
This logic doesn't make sense to me on first glance- the relation between `Rails::Server` and determining the s3 sources directory on bootup is a very confusing set of workarounds for very specific error cases. I can't predict whether this will fix the error described, or if it's even doing what we want in the first place (providing the correct directory). I'd like to simplify the logic here, especially since we got this wrong once, since this definitely will confuse us and/or break in some other unexpected way in the future if we leave it like this.

**Comment by wjordan** [comment]
On a second read, given the method comment (`use a new S3 sources directory for each Test Build to prevent a UI test from inadvertently using a channel id from a previous Test Build.`), I'm pretty sure this will revert to using the same sources directory for each test build, breaking the original fix this method performed.

**Comment by davidsbailey** [comment]
how about 
```ruby
revision = GitUtils.git_revision_short rescue nil
...
elsif environment == :test && !ENV['CIRCLECI'] && revision
```
or something approach like that which clearly ensures that we recover from any error if no git revision is found?

**Comment by wjordan** [comment]
> or something approach like that which clearly ensures that we recover from any error if no git revision is found?

That might work- it would depend on the assumption that the actual process invoking the UI tests has a working directory within the Git project, which should currently hold since `ci_build` changes directory before invoking `rake ci` in a separate subprocess: https://github.com/code-dot-org/code-dot-org/blob/ee1fdd8f0f783d3b14415da6309663616b011546/aws/ci_build#L62

I think a more reliable fix would be to cron-proof the `GitUtils` methods themselves to explicitly `chdir` to the project's directory before shelling out to the `git` commands, to make sure they always work as intended. Or maybe both- fix the `GitUtils` methods _and_ add the `rescue nil` fallback for good measure.

**Comment by sureshc** [comment]
I think `rescue nil` would not address the problem.  Calling out to a shell to execute `git rev-parse --short=8 HEAD` outside of the project directory seems to output the error "fatal: Not a git repository (or any of the parent directories): .git" to Standard Out, and our cron infrastructure raises a HoneyBadger error if anything is written to Standard Out.

**Comment by sureshc** [comment]
My initial understanding was that the `sources_s3_directory` setting was only used by the dashboard service and that skipping the git revision lookup when not executing in a Rails server would suffice.  A quick search for `CDO.sources_s3_directory` in the project proves my assumption was incorrect as there are [test scripts](https://github.com/code-dot-org/code-dot-org/blob/f8d8d35f60fa6ef66f00a8a14cb5d4bc4ec42bfd/shared/test/test_sources.rb#L586) that execute outside the dashboard service that reference that value.

**Comment by wjordan** [comment]
Another option would be to silence the standard error output- e.g., add either ` 2>/dev/null` (redirect stderr to `dev/null`) or ` 2>&-` (close stderr) to the shell command: https://github.com/code-dot-org/code-dot-org/blob/b3193571b75b820da3ae5a6fb8b98d136cd7dcf7/lib/cdo/git_utils.rb#L61-L63

**Comment by sureshc** [comment]
@wjordan Here's my latest thought on solving this problem.  I've tested locally by setting my rails environment to `test` and executing a cron job from a directory outside the project directory.

EDIT:  The CircleCI build fails executing some methods in GitUtils, so never mind.  I have some diagnosis to do.

**Pull request merged**
