### PR TITLE
use selenium to click elements by id when possible

### PR DESCRIPTION
**Pull request by davidsbailey**

### CODE REVIEW

**Comment by Erin007** [comment]
Looks like a slew of related test failures. Do elements need to be scrolled into view?

**Comment by davidsbailey** [comment]
unlikely, because the error shown after clicking the "more" link in circle is: `unknown error: Element <a class="button-signin linktag" href="//localhost-studio.code.org:3000/users/sign_in" id="signin_button">...</a> is not clickable at point (1063, 0). Other element would receive the click: <div class="header_right">...</div>`. It looks like this is not the right element try to click with selenium. when I inspect in via chrome debugger, it is 0px and off the page. so a more fine-grained approach may be required here. recalculating...

**Comment by davidsbailey** [comment]
new plan: this PR is going to be the "shotgun approach" which targets only .feature files. any that fail, I'll just revert and submit what remains. I'll fire up a separate PR for the sign-in tests which takes a more careful approach.

I'm hesitant to run firefox, safari, ie, etc because I know those don't always pass on circle even without any changes from staging. testing the extent of this here before subjecting my PR to it: https://circleci.com/gh/code-dot-org/code-dot-org/81417

**Comment by Erin007** [comment]
@davidsbailey if you're going to break up the tests anyway and the sign-in tests need extra work, I'm happy to take them back on.  Just let me know!

**Comment by davidsbailey** [comment]
Hi @Erin007 , don't worry about it, I think I know what to do for the sign in steps. I'll send something shortly.

**Comment by davidsbailey** [comment]
FWIW, the following 12 configurations failed after reruns on circle against staging:
```
Firefox45Win7_teacher_homepage
Firefox45Win7_yourschool
IE11Win10_applab_clipping
IE11Win10_applab_embed
IE11Win10_disallowedsharing
IE11Win10_gdpr_dialog
IE11Win10_manage_assets
IE11Win10_projects_applab_project
IE11Win10_sharepage
IE11Win10_sharepage_logo
IE11Win10_signing_in
SafariYosemite_spritelab_dancelab
```
I'll run this PR against safari and firefox, skipping IE to keep the noise down: https://circleci.com/gh/code-dot-org/code-dot-org/81460

**Pull request merged**
