### PR TITLE
Pass REQUIRED_BLOCKS to feedback

### PR DESCRIPTION
**Pull request by islemaster**
**I'd like an in-person code review for this PR**

There was an outstanding TODO the pass the `StudioApp.REQUIRED_BLOCKS` value into `FeedbackUtils.getMissingRequiredBlocks_()` instead of letting feeback reach into StudioApp internals.  This PR should tackle that issue.  It also:
- Renames `REQUIRED_BLOCKS` => `requiredBlocks_` to annotate it as a private member.
- Initializes `requiredBlocks_` to an empty array instead of undefined; there's never a reason for this to have an invalid value.
- Adds parameters to several methods in feedback.js so that required blocks are always passed in.
- Updates related tests.

### CODE REVIEW

**Comment by islemaster** [comment]
Got an in-person CR from Brian.

**Comment by Bjvanminnen** [comment]
very nice. much cleaner.

it seems like there are a number of fields on StudioApp the get set once at config/init time, and are unchanged from there on out. I wonder if there's a good way of making those things explicit and/or whether there is value in doing so.

**Comment by islemaster** [comment]
Hm.  I'm not currently aware of any systems for enforcing single-assignment/name-binding in Javascript.  It's possible that the best we can do for now is to treat+annotate these values as private and only set them in `StudioApp.prototype.configure` so that it's easy to prove that they are only set once.  You often can't protect a class from itself; it has to respect its own guts, and the best we can do is guard them from other parts of the system.

That said, I'd love to find an annotation that JSHint would read and enforce about this.

**Comment by Bjvanminnen** [comment]
I'm not sure of how we might do this either. The thing I was maybe thinking was having an object on StudioApp that holds these items.  Something like the following, but maybe better named.  Again, I'm not entirely certain there's necessarily value in this.
```
Studio.configState = {
  requiredBlocks: [],
  ...
};

**Comment by islemaster** [comment]
Hmm... I wouldn't be totally opposed to that.  I'm more comfortable with 'options' blobs if they're strictly treated as const.

**Pull request merged**
