### PR TITLE
Adds a blockly EMR that emits all lines associated with the blockly tutorial, defining the trivial reducer in the process.

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
hamms: Quick sanity check appreciated.

**Comment by ashercodeorg** [comment]
Note that this PR will be used to zero-in on the blockly tutorial to understand the discrepancy between ELB logs and our DB data.

**Comment by Hamms** [comment]
Can we get some documentation (even if just inline) somewhere of what we expect these lines to look like?

**Comment by ashercodeorg** [comment]
Done (added inline example).

**Comment by Hamms** [comment]
LGTM

**Pull request merged**
