### PR TITLE
re-enable PDF generation

### PR DESCRIPTION
**Pull request by kobryan0619**
This is PR will re-enable the PDF auto-generation for curriculum PDFs.  These were disabled in [this PR](https://github.com/code-dot-org/code-dot-org/pull/53936/files). 

I have tested PDF generation locally on staging, and it looks good to go.  I am prepared to revert this PR if it causes issues with the staging build.  I will also let the DoTD know before merging that this is coming. 

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by bethanyaconnor — APPROVED** [review]
fyi that there will likely be a lot of pdfs generated after this is re-enabled, so it's worth trying to merge this either early in the day or after a DTP

**Comment by kobryan0619** [comment]
Thanks for the heads up @bethanyaconnor!  I will shoot for after the DTP!

**Comment by davidsbailey** [comment]
It looks like PDF generation was:
* disabled in https://github.com/code-dot-org/code-dot-org/pull/52774 after it was broken by the ruby upgrade
* enabled in https://github.com/code-dot-org/code-dot-org/pull/52960 after disabling generation of resource PDFs
* disabled in https://github.com/code-dot-org/code-dot-org/pull/53936 

so, why was it disabled in #53936 and what has changed that makes us think it is safe to enable again?

**Comment by bethanyaconnor** [comment]
Long thread but some context is here: https://codedotorg.slack.com/archives/C0T0PNTM3/p1695669458162549. No one had a clear theory as to why it stopped working, other than fast that it stopped working right after the Ubuntu upgrade. If Kaitie has tested on staging and not seen the issue re-appear, then it seems reasonable to try again?

I think I also started a thread in the private teacher tools channel, but I've since left that channel, so I can't link to it.

**Comment by davidsbailey** [comment]
Thanks Bethany. 2 takeaways from the thread:
* https://github.com/code-dot-org/code-dot-org/pull/53936 disabled it due to issues around the time of the ubuntu upgrade, which may have been transient
* the conclusion at the end of the thread is that PDF generation might be flaky rather than completely broken, and so retrying it is a good idea

I think this change looks good, and let's keep in mind to try restarting the staging build if it fails again.

**Review by davidsbailey — APPROVED** [review]

**Comment by kobryan0619** [comment]
Thanks all - I am going to pause this PR for the moment and consult with someone on infra to confirm that this is ready.  I went to test out a few more units on staging, and started to get some flaky issues again which is confusing to me, but given this, I don't want to merge this in today before I leave for a break.

**Pull request closed without merging**
