### PR TITLE
Add a K-1 version of the "when clicked" block

### PR DESCRIPTION
**Pull request by balderdash**
image

For the single-actor case, I'm still showing a picture of the actor. Without it, the block could look like a "click anywhere" event rather than a "click on the actor" event.

image

### CODE REVIEW

**Comment by balderdash** [comment]
Hmm, on second thought, I might wait until I find an icon to merge, since there isn't much else to this PR.

**Comment by Hamms** [comment]
Given that the actors present in a scene do not necessarily align with the start avatars, does this have the potential to be confusing?

**Comment by balderdash** [comment]
Alright, created https://github.com/code-dot-org/code-dot-org/pull/9705 to ensure that the dropdown and `startAvatars[0]` match the sprites that are visible (or can be made visible using showSprite blocks) in the play area.

**Comment by Hamms** [comment]
LGTM!

**Pull request merged**
