### PR TITLE
Moved all mailing scripts from bin/ into a subdirectory, bin/mail/

### PR DESCRIPTION
**Pull request by aoby**
This is a reorganization of https://github.com/code-dot-org/code-dot-org/pull/6780 so the file moves remain intact.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Though fine for this PR, in the future, please separate moves from edits (removing Laurel).

**Comment by ashercodeorg** [comment]
It looks like not all comments were updated, e.g., in bin/mail/hoc-2015-dec-6-mailing/send-all-real-mails. Presumably, the paths specified in the that file are sufficiently relative to work after this PR?

**Comment by ashercodeorg** [comment]
LGTM. Given the huge gain from a better directory structure going forward, I'm fine with this PR as is, even if it breaks some of the comments or paths in the moved files. However, I would add to the PR comment that such breakage may be a part of this PR.

**Comment by aoby** [comment]
Correct. In that particular script, all the paths were relative to bin. Now they will work the same, relative to bin/mail.

**Comment by aoby** [comment]
oh nm. I misread. You're talking about the comments. I'll update those too.

**Pull request merged**
