### PR TITLE
fix video appearance on /educate/it page

### PR DESCRIPTION
**Pull request by davidsbailey**
- Finishes https://codedotorg.atlassian.net/browse/ACQ-422 by eliminating the black background on the /videos/embed page. this seems safe because we are not using this route anywhere else
- Makes the video appear properly in the staging environment, and gets us one step closer to making the video appear properly in development

|  before | after  |
|---|---|
| Screenshot 2023-03-06 at 9 17 12 PM  |  Screenshot 2023-03-06 at 9 17 55 PM |
| Screenshot 2023-03-06 at 9 20 41 PM | Screenshot 2023-03-06 at 9 21 49 PM |

The /videos/embed route works by calling the js method `createVideoWithFallback`, which is the same method we call to display videos in several other places in our product, such as on level pages which have instructional videos.

## Testing story

* Manual verification shown in screenshots, which I made by modifying the styles and URLs in the DOM on code.org and staging.code.org
* also verified locally after patching in the next PR (see below)
* made sure /videos/embed isn't used elsewhere else
  * verified there are no other code uses of /videos/embed besides one unused level
  * verified in Google Analytics that the only traffic to urls starting with studio.code.org/videos/embed are to the video url on the /educate/it page, which supports the theory that this route is otherwise unused

## Follow-up work

* make the video appear properly on localhost: https://github.com/code-dot-org/code-dot-org/pull/50612

### CODE REVIEW

**Review by TurnerRiley — APPROVED** [review]
Looks great! And thank you for the evidence showing that the studio.code.org/videos/embed route is only used here. One question I had is if the styling should match the rest of the page (either by the video being larger or the spacing between the bottom of the video and the start of the next paragraph being smaller)? This doesn't feel like a reason to re-run a drone build, more just curious if this is worth a Jira task or not?

**Comment by davidsbailey** [comment]
> Looks great! And thank you for the evidence showing that the studio.code.org/videos/embed route is only used here. One question I had is if the styling should match the rest of the page (either by the video being larger or the spacing between the bottom of the video and the start of the next paragraph being smaller)? This doesn't feel like a reason to re-run a drone build, more just curious if this is worth a Jira task or not?

good question! I've removed some of the whitespace. how does this look @TurnerRiley ? 

Screenshot 2023-03-07 at 12 30 39 PM

@dmcavoy @kelbyhawn what do you think about whether we should clean this up any further?

**Comment by TurnerRiley** [comment]
> > Looks great! And thank you for the evidence showing that the studio.code.org/videos/embed route is only used here. One question I had is if the styling should match the rest of the page (either by the video being larger or the spacing between the bottom of the video and the start of the next paragraph being smaller)? This doesn't feel like a reason to re-run a drone build, more just curious if this is worth a Jira task or not?
> 
> good question! I've removed some of the whitespace. how does this look @TurnerRiley ?
> 
> Screenshot 2023-03-07 at 12 30 39 PM
> 
> @dmcavoy @kelbyhawn what do you think about whether we should clean this up any further?

Looks good to me! Thank you!

**Comment by kelbyhawn** [comment]
> Screenshot 2023-03-07 at 12 30 39 PM
> 
> @dmcavoy @kelbyhawn what do you think about whether we should clean this up any further?

Can you update the margin on the iframe to: `margin: 10px 0;` so it's left aligned with the rest of the page content? Other than that I think it's good to go! 🙌

**Comment by davidsbailey** [comment]
> Can you update the margin on the iframe to: `margin: 10px 0;` so it's left aligned with the rest of the page content? Other than that I think it's good to go!

Done - thanks Kelby!

**Review by kelbyhawn — APPROVED** [review]

**Pull request merged**
