### PR TITLE
i18n sync 2017-03-23

### PR DESCRIPTION
**Pull request by Hamms**

### CODE REVIEW

**Comment by tanyaparker** [comment]
I can't tell because it's too big but did you already automatically include blockly version updates?

**Comment by tanyaparker** [comment]
I'm trying to get a list of all the affected files. `git log --name-status` seems like the closest to what I want, do you know what I could use that just spits it all out so I don't have to scroll through?

It looks like we added Corsican and Telugu files. These should have been converted to locales like co-FR and te-IN.

**Comment by tanyaparker** [comment]
According to the command I used (unless it doesn't do what I think it does), other than the 3 files below only files in i18n/locales were affected. I find it highly unlikely that there weren't more changes in apps and dashboard, especially since it's been a couple weeks since a sync. Should I try running down and out too?

M       apps/lib/blockly/el_gr.js
M       apps/lib/blockly/nl_nl.js
M       dashboard/config/locales/ar-SA.yml

**Comment by Hamms** [comment]
No, that's accurate; only those three files were changed, and nothing was changed in blockly.

I'll try running again and verify that nothing went wrong, but please feel free to try running down and out yourself.

**Comment by tanyaparker** [comment]
Looks like there was an error and it my have stopped the dashboard sync and jumped to apps sync?

```i18n/locales/ar-SA/dashboard/base.yml + i18n/locales/source/dashboard/base.yml => dashboard/config/locales/ar-SA.yml
i18n/locales/ar-SA/dashboard/authored_hints.yml + i18n/locales/source/dashboard/authored_hints.yml => dashboard/config/locales/authored_hints.ar-SA.yml
i18n/locales/ar-SA/dashboard/callouts.yml + i18n/locales/source/dashboard/callouts.yml => dashboard/config/locales/callouts.ar-SA.yml
i18n/locales/ar-SA/dashboard/data.yml + i18n/locales/source/dashboard/data.yml => dashboard/config/locales/data.ar-SA.yml
i18n/locales/ar-SA/dashboard/devise.yml + i18n/locales/source/dashboard/devise.yml => dashboard/config/locales/devise.ar-SA.yml
i18n/locales/ar-SA/dashboard/dsls.yml + i18n/locales/source/dashboard/dsls.yml => dashboard/config/locales/dsls.ar-SA.yml
i18n/locales/ar-SA/dashboard/failure_message_overrides.yml + i18n/locales/source/dashboard/failure_message_overrides.yml => dashboard/config/locales/failure_message_overrides.ar-SA.yml
i18n/locales/ar-SA/dashboard/instructions.yml + i18n/locales/source/dashboard/instructions.yml => dashboard/config/locales/instructions.ar-SA.yml
i18n/locales/ar-SA/dashboard/markdown_instructions.yml + i18n/locales/source/dashboard/markdown_instructions.yml => dashboard/config/locales/markdown_instructions.ar-SA.yml
./bin/i18n-codeorg/lib/merge-translation.rb:24:in `block in merge_translation_tree': undefined method `key?' for []:Array (NoMethodError)
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `each_key'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:25:in `block in merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `each_key'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:25:in `block in merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `each_key'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:25:in `block in merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `each_key'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:25:in `block in merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `each_key'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:25:in `block in merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `each_key'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:23:in `merge_translation_tree'
	from ./bin/i18n-codeorg/lib/merge-translation.rb:52:in `<main>'
apps/node_modules/@code-dot-org/blockly/i18n/locales/Corsican/core.json => apps/node_modules/@code-dot-org/blockly/msg/js/corsican.js, apps/lib/blockly/corsican.js
apps/node_modules/@code-dot-org/blockly/i18n/locales/Telugu/core.json => apps/node_modules/@code-dot-org/blockly/msg/js/telugu.js, apps/lib/blockly/telugu.js
apps/node_modules/@code-dot-org/blockly/i18n/locales/ar-SA/core.json => apps/node_modules/@code-dot-org/blockly/msg/js/ar_sa.js, apps/lib/blockly/ar_sa.js```

**Comment by Hamms** [comment]
after fixing the script error, resyncing created conflicts vs staging. Closing this PR to open another one from staging latest

**Pull request closed without merging**
