### PR TITLE
Set up components to roll up standards

### PR DESCRIPTION
**Pull request by dmcavoy**
Using the recently finished component for displaying standards in lesson plan we can now add the ability to show a standards roll up. This adds the parts needed to rollup standards as well as storybook entries for Course and Unit Standards Roll up. 

## Links

- jira ticket: [PLAT-752](https://codedotorg.atlassian.net/browse/PLAT-752)

## Testing story

-Storybook entries
-Unit tests for RollupLessonEntrySection

## Follow-up work

- Adding the components to the real pages!

## PR Checklist:

- [x] Tests provide adequate coverage
- [x] Privacy and Security impacts have been assessed
- [x] Code is well-commented
- [x] New features are translatable or updates will not break translations
- [x] Relevant documentation has been added or updated
- [x] User impact is well-understood and desirable
- [x] Pull Request is labeled appropriately
- [x] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
one thing to note is that the standards currently start off collapsed. I am planning to add a prop to the LessonStandards component for the contents to be collapsed, only show first standard, or fully expanded. do you think you will want standards to be fully expanded? If you do, I could update this component once I implement that prop.

**Review by davidsbailey — APPROVED** [review]

**Comment by dmcavoy** [comment]
> one thing to note is that the standards currently start off collapsed. I am planning to add a prop to the LessonStandards component for the contents to be collapsed, only show first standard, or fully expanded. do you think you will want standards to be fully expanded? If you do, I could update this component once I implement that prop.

@tess323 Any thoughts here on how we want standards to display on the all standards roll up page?

**Comment by tess323** [comment]
For the lesson edit page, we want the first standard showing.  For the standards roll up we would want them all expanded since this page is for folks specifically really invested in getting into specifics of standards.

**Comment by dmcavoy** [comment]
> For the lesson edit page, we want the first standard showing. For the standards roll up we would want them all expanded since this page is for folks specifically really invested in getting into specifics of standards.

Sounds like it would be great @davidsbailey if you could update this when you add that prop

**Comment by davidsbailey** [comment]
> > For the lesson edit page, we want the first standard showing. For the standards roll up we would want them all expanded since this page is for folks specifically really invested in getting into specifics of standards.
> 
> Sounds like it would be great @davidsbailey if you could update this when you add that prop

Will do!

**Comment by dmcavoy** [comment]
Rebasing to staging while tests run. Will put back to other base branch after tests pass

**Pull request merged**
