### PR TITLE
Revert "Revert "Add bounciness (restitution) block""

### PR DESCRIPTION
**Pull request by caleybrock**
Reverts code-dot-org/code-dot-org#10984

### CODE REVIEW

**Comment by caleybrock** [comment]
tests didn't fail on circle, but when Brent pulled they failed. I forgot to add the new block to the ruby file.

**Comment by islemaster** [comment]
LGTM. Glad that test caught it!  I wonder what we could do to catch this on Circle, which tries to optimize by only testing changed modules, but in this case a module wasn't changed that should have been.  It's possible catching this on staging/test is good enough.

**Comment by caleybrock** [comment]
Yeah, I'm hoping it doesn't happen too often, but it's really easy to forget since it works fine locally without this file and it's not in apps.

**Comment by caleybrock** [comment]
I've re-run these tests 3 times and am getting the same set of non-gamelab related failures so I'm going to merge.

**Pull request merged**
