### PR TITLE
add photo credit for argentina partner's picture on applab page

### PR DESCRIPTION
**Pull request by tanyaparker**
**large view**
image

**medium view**
image

**small view**
image

### CODE REVIEW

**Comment by breville** [comment]
formats okay at different browser widths?

if so, lgtm

**Comment by tanyaparker** [comment]
It clashed with the anchor links on small widths. Moved into jumbotron_banner so it stays at the top next to the picture. PTAL

**Comment by tanyaparker** [comment]
@breville updated screenshots

**Comment by breville** [comment]
New screenshots look good.

**Pull request merged**
