### PR TITLE
Add a link to last year's dance party tutorial to /dance page

### PR DESCRIPTION
**Pull request by islemaster**
[PLC-643](https://codedotorg.atlassian.net/browse/PLC-643): Add a link to last year's dance party tutorial to [the /dance page](https://code.org/dance), as specified in the linked Jira item.

It's a small, two-line right-aligned message:

image

It's visible on both desktop and mobile:

desktop

Screenshot from 2019-11-26 13-55-58

The links begin the respective tutorials.

## Internationalization

This change introduces one new Pegasus string, used on code.org/dance, that will need to be translated.  FYI @castro-jorge.

I did a thoughtless thing and [committed an early version new string](https://github.com/code-dot-org/code-dot-org/pull/32158/commits/99292aa4ba600ca200058b700a1ab1d5c5860cf2) directly from staging while we were in lockdown.  Fortunately Elijah caught me and suggested a better approach:

- I've made the appropriate string changes in [our pegasus i18n spreadsheet](https://docs.google.com/spreadsheets/d/1Tq7VqZALgRA0wYk0HDfEOTyRI0TM2Dir2rloXIPGCgU/edit#gid=0).
- I've committed the corresponding change to `pegasus/cache/i18n/en-US.yml`, which we normally wouldn't edit by hand, so that it can be reviewed as part of the triage process.  Since the autocommit on staging is disabled, this shouldn't introduce a conflict.

## Testing story

This is a content change.  Tested locally.  This will also cause a diff in [tutorial_landing_pages.feature](https://github.com/code-dot-org/code-dot-org/blob/6ab8ae5017ab87a4db923f6f33930d1134de12e2/dashboard/test/ui/features/tutorial_landing_pages.feature#L19).

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by castro-jorge** [comment]
When do you expect this string to be available in Crowdin?

**Comment by islemaster** [comment]
I've got this change scheduled for triage on Monday, December 2nd, so under the current plan no sooner than that afternoon.

**Comment by castro-jorge** [comment]
Ah, that is not enough time to get it translated ahead of the last sync
before CSEdWeek. Do we have other options?

**Comment by islemaster** [comment]
Let me pull this into tomorrow's triage meeting then.  Would having it in CrowdIn tomorrow afternoon be enough lead time?

**Comment by castro-jorge** [comment]
Yes, that should give us enough time. Thank you!

**Review by Hamms — APPROVED** [review]

**Comment by islemaster** [comment]
@castro-jorge The new string `hoc2019_dance_previous_versions` is now on CrowdIn and ready for translation.  Thank you!

**Pull request merged**
