### PR TITLE
Get netsim running in standalone dev environment again

### PR DESCRIPTION
**Pull request by islemaster**
NetSim wasn't playing nice with the `grunt dev` command.  This PR makes the following changes to allow NetSim to run in the standalone mode.
- Creates a proxy to a dashboard instance running locally on port 3000, so that NetSim can access the shared-tables API and dashboard-only application.css.  Note this means you do have to be running dashboard to use NetSim in the "standalone" development environment.
-  Make jQuery and application.css available to NetSim in the standalone environment.
- Create a "playground" level configuration for use only in the dev environment, where a level is not provided by dashboard.

### CODE REVIEW

**Comment by islemaster** [comment]
Suggested improvements:
* Warn if no dashboard instance is running.
* Make sure it's reliable and doesn't negatively impact development of other apps!

**Comment by islemaster** [comment]
@Hamms how about this error in the console if you forget to start dashboard?
screenshot from 2015-07-15 15 20 44

**Comment by Hamms** [comment]
That looks ideal

**Comment by islemaster** [comment]
Note: Above error message will only show up for apps that attempt to use the dashboard proxy (so right now, only NetSim).

**Comment by bcjordan** [comment]
LGTM!

**Pull request merged**
