### PR TITLE
Added decimeta to StartWebRequest

### PR DESCRIPTION
**Pull request by jmkulwik**
A user wanted us to add decimeta.info to startWebRequest. This is a dewey decimal lookup api that seemed pretty benign. Adding it.

Example query: https://decimeta.info/api/searchForMDS.js?search=query
Page: https://decimeta.info/

## Links

https://codeorg.zendesk.com/agent/tickets/466251

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by sanchitmalhotra126 — APPROVED** [review]

**Comment by cat5inthecradle** [comment]
Sounds good to me - but do we have any criteria for approving a new allowed API?

This one, for example, "uses an unknown LLM to generate responses" and "is maintained by an individual" - both negative marks in my mind, but not necessarily enough to reject it.

**Comment by fisher-alice** [comment]
> Sounds good to me - but do we have any criteria for approving a new allowed API?
> 
> This one, for example, "uses an unknown LLM to generate responses" and "is maintained by an individual" - both negative marks in my mind, but not necessarily enough to reject it.

I see on https://studio.code.org/docs/ide/applab/expressions/startWebRequest that already added [bible-api.com](http://bible-api.com/) is maintained by an individual. But I do wonder about adding an API that uses an LLM to generate responses. It looks like https://decimeta.info/ uses [Pinecone and OpenAI](https://github.com/Lioness100/decimeta/blob/main/api/searchForMDS.js) documented at https://docs.pinecone.io/docs/openai. If we make this publicly available, would the user incur costs associated with use from other Code.org users?
I also see the requestor describe themself as a student on GH.

**Comment by cat5inthecradle** [comment]
The risk I'm worried about is the risk of the API providing harmful content to users.

It is possible the API owner would incur costs if it's used, but in this case the person requesting we add this API is the owner.

**Comment by fisher-alice** [comment]
> The risk I'm worried about is the risk of the API providing harmful content to users.

+1

**Comment by jmkulwik** [comment]
Really good catch @cat5inthecradle - While we occasionally allow benign APIs that are maintained by individuals, we don't allow APIs populated by AI at this time. I'll close.

On that note, it might be worth replacing the bible-api you mentioned @fisher-alice. It looks like there's a pretty official-looking one that's got a society associated with it that would be good to use instead. https://scripture.api.bible/ - also has much better language support. That makes me think, how many of our allow-listed APIs have a more official version somewhere? I'll at least make a note on our documentation to have us make a quick google search for more official APIs when approving an API request.

**Comment by jmkulwik** [comment]
Turns out this API has its data populated by AI, which we aren't allowing in our allow-listed App Lab API list at this time.

**Pull request closed without merging**
