### PR TITLE
Log unversioned course unit redirects

### PR DESCRIPTION
**Pull request by davidsbailey**
Finishes [PLAT-182](https://codedotorg.atlassian.net/browse/PLAT-182)

For context, see the kinds of data that we pulled out of cloudfront logs which was useful for analysis: [gsheet](https://docs.google.com/spreadsheets/d/1ZD_lW4aHRcIu8p1hMKFh5FYIngVECvsggilsXPg6mWc/edit#gid=1425542697)

request.path is listed as data_string since that could be useful to aggregate and count on, while request.path might be useful if we want to look at url params.

## Testing story

Manually verified that firehose events are created on unversioned script and script level paths.

http://localhost-studio.code.org:3000/s/csp1?foo=1 :
```
Skipped sending record to analysis-events: 
{:study=>"script-family-redirect", :event=>"unversioned-script-redirect", :data_string=>"/s/csp1", :data_json=>"{\"old_script_name\":\"csp1\",\"new_script_name\":\"csp1-2019\",\"url\":\"http://localhost-studio.code.org:3000/s/csp1?foo=1\",\"referer\":null}"}
```

http://localhost-studio.code.org:3000/s/csp3/stage/1/puzzle/1?baz=3 :
```
Skipped sending record to analysis-events: 
{:study=>"script-family-redirect", :event=>"unversioned-script-level-redirect", :data_string=>"/s/csp3/stage/1/puzzle/1", :data_json=>"{\"old_script_name\":\"csp3\",\"new_script_name\":\"csp3-2019\",\"url\":\"http://localhost-studio.code.org:3000/s/csp3/stage/1/puzzle/1?baz=3\",\"referer\":null}"}
```

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by uponthesun — COMMENTED** [review]
Can we move the logic into `Script.get_script_family_redirect_for_user` for DRY? Seems like one optional parameter will need to be added to the method but that seems ok to me.

**Comment by davidsbailey** [comment]
I've extracted `Script.log_redirect` to obey DRY. I tried to take it a step further, but ran into a problem: I realized that we want to log user type (something that was originally requested, but that I could not get out of CloudFront logs), but that can't be logged properly from within `Script.get_script_family_redirect_for_user` because `ScriptLevelsController.get_script` incorrectly passes `user: nil` to it, because `current_user` is not available from the context. I'd like to avoid changing this behavior, because it seems like that could cause problems for someone already using an LMS to point students to our materials (see examples in gsheet above). So I'm hoping we can call what I have here a good stopping point.

**Comment by davidsbailey** [comment]
new sample output:

teacher at /s/csp1:
`{:study=>"script-family-redirect", :event=>"unversioned-script-redirect", :data_string=>"/s/csp1", :data_json=>"{\"old_script_name\":\"csp1\",\"new_script_name\":\"csp1-2019\",\"method\":\"GET\",\"url\":\"http://localhost-studio.code.org:3000/s/csp1\",\"referer\":null,\"user_type\":\"teacher\"}"}`

signed out user at /s/csp2:
`{:study=>"script-family-redirect", :event=>"unversioned-script-redirect", :data_string=>"/s/csp2", :data_json=>"{\"old_script_name\":\"csp2\",\"new_script_name\":\"csp2-2019\",\"method\":\"GET\",\"url\":\"http://localhost-studio.code.org:3000/s/csp2\",\"referer\":null,\"user_type\":null}"}`

student at /s/csp3/stage/1/puzzle/1:
`{:study=>"script-family-redirect", :event=>"unversioned-script-level-redirect", :data_string=>"/s/csp3/stage/1/puzzle/1", :data_json=>"{\"old_script_name\":\"csp3\",\"new_script_name\":\"csp3-2019\",\"method\":\"GET\",\"url\":\"http://localhost-studio.code.org:3000/s/csp3/stage/1/puzzle/1\",\"referer\":null,\"user_type\":\"student\"}"}`

**Review by uponthesun — APPROVED** [review]
Thanks for looking into the refactor! 

I think you found the perfect stopping point. IMO even for "temporary" code it's valuable to spend a a little effort on good factoring. It builds good habits, but also reduces complexity of removing the code later. And I agree with not doing a larger refactor / bugfix on code we're getting rid of.

**Pull request merged**
