### PR TITLE
Dance Party level 12 changes, copied from LevelBuilder

### PR DESCRIPTION
**Pull request by Erin007**
As part of the deploy today, we want just the changes to Dance Party level 12 not all of the other change currently on levelbuilder.  This PR copies the changes from the relevant [levelbuilder content scoop ](https://github.com/code-dot-org/code-dot-org/commit/74aed99575aef409e88d9b17ca0a85d07306a6a6) so the file can go in as an isolated change.

### CODE REVIEW

**Comment by Erin007** [comment]
Ok to merge w/o waiting for Circle?

**Comment by davidsbailey** [comment]
looks like circle just completed with a UI test failure: https://cucumber-logs.s3.amazonaws.com/circle/82020/ChromeLatestWin7_spritelab_dancelab_output.html?versionId=DCHFNZ6thMf.yz8txVgxnB8_jKJomzwJ

**Comment by Erin007** [comment]
The Circle failure is for puzzle 13, but this change from LB is related to level 12 so I'm suspicious that this test is flaky somehow since I don't see how level 12 changes would affect puzzle 13; but maybe I'm missing something...

**Comment by davidsbailey** [comment]
That's not quite right -- `Dance_Party_12` actually is the level backing https://studio.code.org/s/dance/stage/1/puzzle/13. Count the off-by-one errors here:
https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/config/scripts/dance.script

**Comment by davidsbailey** [comment]
For more concrete evidence, 
1. go to https://levelbuilder-studio.code.org/levels
2. search for `Dance_Party_12`
3. click "Show"
4. see that the name is `Dance_Party_12` and the script level it appears on is listed as /s/dance/stage/1/puzzle/13

**Comment by Erin007** [comment]
Thanks for clarifying, Dave! I was missing that piece, and made a false assumption that levels would correspond in numbering to puzzles.

**Comment by Erin007** [comment]
Rather than the original 3, there are now 10 dancers. So the test needed to be updated to reflect this change. 
screen shot 2018-11-26 at 9 54 01 pm

**Comment by Erin007** [comment]
@ryansloan Is this the Dance_Party_12 change we want or are there changes beyond this that we need to consider today?

**Comment by davidsbailey** [comment]
We should be sure that the changes to Dance_Party_12 only get made once (either via lb scoop or this PR), to head off any weird merge issues.

**Pull request merged**
