### PR TITLE
Extract out ShowCodeToggle component from CodeWorkspace

### PR DESCRIPTION
**Pull request by pcardune**
This time with more unit tests...

### CODE REVIEW

**Comment by islemaster** [comment]
I re-ran your circle build, expecting some flaky failure given the number of UI tests that broke, but it failed again.  Here, at least, is the output from the end of the container 0 log, and it does look related to your changes:

```
SUMMARY:
✔ 2436 tests completed
ℹ 25 tests skipped
✖ 3 tests failed

FAILED TESTS:
  ShowCodeToggle
    ✖ "before each" hook for "renders a PaneButton with a 'Show Code' label"
      PhantomJS 2.1.1 (Linux 0.0.0)
    null is not an object (evaluating 'divApplab.firstChild')
    reset@[CDO]/apps/test/unit-tests.js:400447:39966
    [native code]
    init@[CDO]/apps/test/unit-tests.js:116338:22167
    [CDO]/apps/test/unit-tests.js:538214:31

    ✖ "after each" hook for "renders a PaneButton with a 'Show Code' label"
      PhantomJS 2.1.1 (Linux 0.0.0)
    undefined is not a function (evaluating '_StudioApp.singleton.onDropletToggle.restore()')
    [CDO]/apps/test/unit-tests.js:538226:57

  convertXmlToBlockly
    ✖ creates a block space if it detects xml
      PhantomJS 2.1.1 (Linux 0.0.0)
    TypeError: null is not an object (evaluating 'document.getElementById('codeWorkspace').clientWidth') ([CDO]/apps/test/unit-tests.js:116338)

PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: null is not an object (evaluating 'document.getElementById('codeWorkspace').clientWidth')
  at [CDO]/apps/test/unit-tests.js:116338
Fatal error: Cannot read property '14514125' of null
```

**Comment by pcardune** [comment]
ok, tests are passing now @islemaster would you like to PTAL?

**Comment by mehalshah** [comment]
May have to revert this - it is causing eyes failures because show code is appearing in unexpected places

**Comment by islemaster** [comment]
Documenting some eyes failures for us to work on when you're back in the office.  Not an exhaustive list, there were a lot of these (~10).

Case 1: [contractEditor.feature](https://github.com/code-dot-org/code-dot-org/blob/74df4fb72e2b7767b308441c3c3b72b3e92b706f/dashboard/test/ui/features/contractEditor.feature) - "Show Code" button introduced where there was none before.
image

Case 2: [eyes.feature](https://github.com/code-dot-org/code-dot-org/blob/f4b856f6b24bcc16050966cf0383ee69ab4c3b90/dashboard/test/ui/features/eyes.feature) bounce game also has new Show Code button
image

Case 3: [topInstructions.feature](https://github.com/code-dot-org/code-dot-org/blob/488f3564b5cab265d6b566069fc8723a4c166c51/dashboard/test/ui/features/topInstructions.feature) - this one _definitely_ shouldn't have a "Show Code" button.  There were at least two cases of Jigsaw levels having show code buttons, and some cases on calc levels having show code buttons which I don't think we support either.
image

**Comment by islemaster** [comment]
Diffs that are probably expected / fine:

Looks like the "Show blocks" button got a little bit wider.  You can see this in the RTL test too.
image

**Pull request merged**
