### PR TITLE
Droplet property support

### PR DESCRIPTION
**Pull request by cpirich**
- Update droplet with recent changes in `master` and `code-dot-org` branches, which includes the property support here: https://github.com/droplet-editor/droplet/commit/ac98a7eebf751428b4cec0fbc2a63eb3722feca7
- Update `dropletUtils.js` to allow entries in our `codeFunctions` blocks to specify `type: 'property'`
- Update `dropletConfig` for gamelab and applab where properties were specified to use the new `type: 'property'`
- Minor Game Lab fix to remove an unneeded call to `executeInterpreter()`

### CODE REVIEW

**Comment by islemaster** [comment]
! Why is droplet.js entirely new in this PR?

**Comment by bcjordan** [comment]
Very cool!

**Comment by cpirich** [comment]
Good catch, I shouldn't be including droplet.js

**Comment by islemaster** [comment]
Cool.  LGTM now!

**Pull request merged**
