### PR TITLE
Apply Prettier formatting to all apps code

### PR DESCRIPTION
**Pull request by Hamms**
Follow-up to https://github.com/code-dot-org/code-dot-org/pull/26858 that actually applies the newly-added rules.

Applied by running `prettier --write "src/**/*.jsx" "src/**/*.js" "test/**/*.js" "test/**/*.jsx"`, then manually fixing a few remaining issues. All manual issues fell into one of two categories; either Prettier moved comments around such that `// eslint-disable-line` helpers were no longer disabling the correct lines, or our use of the eslint `no-unexpected-multiline` rule was causing some issues, [as is expected](https://github.com/prettier/eslint-config-prettier#no-unexpected-multiline).

We may want to consider disabling that rule if it continues to be an issue moving forward, but I really don't expect it will be.

### CODE REVIEW

**Comment by davidsbailey** [comment]
Looks like there may be some legit circleci failures.

The size of this change is a bit scary, as it could be difficult to revert once other apps changes are merged into the codebase. A partial rollout could add a fair bit of work, though. Perhaps it would make sense to at least close staging when this is merged, and open it again after a green DTT?

**Comment by Hamms** [comment]
> Looks like there may be some legit circleci failures.

Yeah, turns out we were linting some generated files; I "fixed" them with `prettier --write`, then they were overwritten by the `yarn build`.

I [added a change](https://github.com/code-dot-org/code-dot-org/pull/26911/commits/2e6fe8e3f07334b9087e89c40d8d2cb6366f6767) to disable linting for generated files.

> Perhaps it would make sense to at least close staging when this is merged, and open it again after a green DTT?

That seems reasonable! I'll reach out to Jessie and try to schedule that for this evening

**Review by islemaster — APPROVED** [review]
🚢 :shipit: :rocket:

**Comment by davidsbailey** [comment]
The circle run after disabling linting on generated files appears to have a failure too. it looks flaky to me: https://84842-24250009-gh.circle-artifacts.com/0/apps-test-logs/integrationTest.log so might be worth rerunning before investigating further.

**Comment by Hamms** [comment]
Interesting. It looks like the test that's failing is performing string comparisons on some of the old `levels.js` levels; specifically, the block here which I updated: https://github.com/code-dot-org/code-dot-org/blob/2e6fe8e3f07334b9087e89c40d8d2cb6366f6767/apps/src/flappy/levels.js#L320-L326

The test itself redefines the block, but the test _also_ got updated: https://github.com/code-dot-org/code-dot-org/blob/2e6fe8e3f07334b9087e89c40d8d2cb6366f6767/apps/test/integration/levelSolutions/flappy/8.js#L1-L13

So it should still be passing, unless something is getting cached here. I'll investigate further.

**Comment by Hamms** [comment]
I'm still not entirely sure what's going on with that one test, so I bypassed it with an `eslint-disable` directive. Not pretty, but it works.

@davidsbailey PTAL

**Review by davidsbailey — APPROVED** [review]
Yesssssssss can't wait to try this out!

**Pull request merged**
