### PR TITLE
Responsive footer for HOC.com

### PR DESCRIPTION
**Pull request by kozzi**
In my quest to make HOC fully responsive, I also updated the footer to support smaller widths.
#### Wide

image
#### Medium

image
#### Narrow (<500px)

image

This is still a WIP, but largely where I want the pieces to be. If we're okay with the design, I'll do full cross-browser testing, which will probably need some additional CSS changes to support older IE browsers.

TODO:
- Test on IE8-11, Safari, Firefox, tablet, and mobile

### CODE REVIEW

**Comment by kozzi** [comment]
@tanyaparker fyi

**Comment by breville** [comment]
Nice work.  Looks good to me.  As always, broad testing is key.  Don't forget to try a few different languages.

**Comment by tanyaparker** [comment]
YAY. You're the best!

**Comment by kozzi** [comment]
Got some feedback from @alicesteinglass that the footer in the small widths look too big and prominent. Here's an updated version with it as an overlay menu similar to that on the app lab shared page.

responsive-footer

Note: I hid the more verbose copyright text in this design cause it doesn't work well with the menu. However, if we feel strongly about keeping copyright in narrow widths, I can put it back in. It does look a bit odd.

**Comment by tanyaparker** [comment]
Mhm that's fair. Totally agree now that I see it.

Not sure how required copyright is. I'm guessing not that much since we used to hide it before?

**Comment by kozzi** [comment]
Ok, I'll leave out the verbose text then. Will go ahead and clean this up and do full testing for it.

**Comment by kozzi** [comment]
So, upon testing on my phone, I hit two UX issues:
1. It's suuuuper annoying having an interactive control right up against the bottom edge, cause tapping in that area **always** brings up the browser UI first. That means it always takes two taps to really invoke the footer menu - terrible UX :(
2. The AnswerDash widget looks different on mobile (always in the bottom right corner), so it occludes the footer menu text and makes it inaccessible.

Because of that, I decided to put the copyright text back in to shift the footer menu toggle up. I also played around with the layout a bit to make it look decent. This is the final version that feels alright to me:

responsive-footer

Tested on IE8-11, Firefox, Safari, Chrome, mobile, tablet, and in select international languages.

**Comment by breville** [comment]
Does that mean you disabled AnswerDash for mobile?  Do we think AnswerDash is really a desktop solution?

Thanks for being so thorough.

**Comment by kozzi** [comment]
I didn't touch AnswerDash with this change.

It looks like when AnswerDash was first put in, it was only put in for the homepage? This has always been the case, even on Desktop. I took the animated gif above of a subpage, which is why it's missing. 

Here it is on the homepage:
responsive-footer

On mobile, it looks like this (can't do gifs, but here's a screenshot):


P.S. Should AnswerDash be there for the subpages?

**Comment by tanyaparker** [comment]
AnswerDash is intentionally only for the homepage. It's meant for the only the most popular questions right now. It's managed by Josh S and theoretically we could add it to later subpages, but only when the website is much more static and Josh has prepared questions to put into the tool.

**Comment by kozzi** [comment]
Thanks for clarifying @tanyaparker. Good to merge then? 👍

**Comment by tanyaparker** [comment]
Yep! LGTM

@joshlory fyi this may affect eyes tests for hoc.com homepage

**Comment by joshlory** [comment]
@tanyaparker I'm dev-of-day tomorrow.  Looks like @mehalshah is dev-of-day today.

**Pull request merged**
