### PR TITLE
Checks whether header is nil before looking up the litmus_tracking_id_key.

### PR DESCRIPTION
**Pull request by ashercodeorg**
The intent is to eliminate the plethora of error messages being seen in the Staging Room.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Lacking context, I'm doing the simplest thing that seems sensical. Please check carefully that the simple fix is a reasonable solution.

**Comment by aoby** [comment]
This will certainly fix the error, but I don't have enough context to know if nil tracking_id is an acceptable state downstream. @laurelfan how does this look?

**Comment by philbogle** [comment]
This is an OK short term band-aid but we definitely need to fix the root cause and then remove this code which suppressing warning about a potentially bad condition.

Without the litmus tracking, we will lose visibility as to whether a user has opened an email, so it would be bad if this started happening at a high rate and we didn't know about it! 

This code runs in a cron job so it's not trivial to have it warn even N message, perhaps we could do something probablilistic (warning 1% of the time say).

**Comment by philbogle** [comment]
Laurel mentioned a better way, we can handle the missing data gracefully and log the bad condition via honeybadger.  (They have an API which we can call to report the issue and they'll aggregate and send an email.)

**Comment by ashercodeorg** [comment]
Added TODO. Feel welcome to take another look.

**Comment by philbogle** [comment]
LGTM.  There is a tracking bug which you can reference in the TODO.
https://www.pivotaltracker.com/story/show/104750788

**Comment by ashercodeorg** [comment]
Done (phil).

**Comment by philbogle** [comment]
Thanks for jumping on this Asher.

**Comment by code-org** [comment]
was there any investigation of the root cause?

**Comment by laurelfan** [comment]
(code-org was me)

**Comment by philbogle** [comment]
Yes, Andrew is investigating, the tracking bug for the root cause
investigation is https://www.pivotaltracker.com/story/show/104756402

Separately, there are tracking bugs in HOC for logging to hipchat on
unhandled exceptions and on missing litmus_tracking_id headers so we have
good visibility into errors without spamming.

**Comment by aoby** [comment]
This fix just bumped the error upstream. From staging logs:
 /home/ubuntu/staging/bin/deliver_poste_messages:126:in `send': undefined method`[]' for nil:NilClass (NoMethodError)

Root cause is ~/staging/pegasus/emails/10-5-latam-hoc.md had no header on staging. Laura added the file yesterday, and is fixing it now...

**Comment by philbogle** [comment]
Would it make sense to add a presubmit script that verifies the emails are
well-formed before allowing them to be checked in?

**Comment by laurelfan** [comment]
That makes sense. A better pipeline for getting errors to the content authors would help too. 

If we are going to switch to having content authors type/paste emails directly in production (which is #1 on Andrew's feature list) it may not be worth doing this work though.

**Comment by philbogle** [comment]
I think we would much of the same validation logic even when they submit
via a web form (assuming there are possibly invalid headers is authored by
content providers), so worthwhile building the library that does the
validation.  Then it will hopefully be easy to call either from a presubmit
hook or from the web controller.

**Comment by laurelfan** [comment]
Hopefully in that case it can be a lot easier because the validation
library can be the same as the renderer so we don't need to do the work of
figuring out how to call the renderer from a git hook script.

In this case instead of swallowing the error we should be doing something
like:

if headers == nil
raise "headers are required"
end

(where the exception is handled and shown to the user)

**Pull request merged**
