### PR TITLE
[Sprite Lab] Check for number when prompt answered

### PR DESCRIPTION
**Pull request by mikeharv**
## Problem
Request from Emma on the curriculum team:
> I’m trying to create a [Calculator Bot](https://studio.code.org/projects/spritelab/UNk_5vVEUyXNeVFSeKOGKiCVNYViNbqu_eUqhLQorw4) in Sprite Lab and write a math function to represent adding 5 to a given number but when I use the Math block “_____ + _____” it concatenates 5 with my inputted number rather than adding 5. Interestingly the -/x operations work as expected. Furthermore, if I call the subtract 3 function first, the add 5 function works as expected.

This looks to be a bug related to prompts. I think when the initial value is entered in your program, we’re not detecting that it should be stored as a number. Instead it’s stored as a string. The + operation works with strings via concatenation, but the other operations only expect numbers. In those cases it seems like we update the type of the variable if we can convert the string to a number.

## Proposed Solution
Whenever a Sprite Lab prompt is answered, we parse the entered string and convert it to a number.

## Links

Slack thread: https://codedotorg.slack.com/archives/C1B3PNDL7/p1651597339932139

## Testing story
Tested with strings, integers, and decimal numbers.

Before change (production):

After change:

### CODE REVIEW

**Review by tim-dot-org — COMMENTED** [review]
I went looking at this a little bit!
Would make more sense to fix this on the math block? (it should probably cast its arguments to numbers first)
Consider that you can set a variable to a string at any time (not just for prompts):
image

**Comment by tim-dot-org** [comment]
that said, i couldn't actually find any definition on our side for the math_arithmetic block (i'm guessing that's a standard google blockly block?) so I'm not sure if that's doable without a push to their code.

Also, how much do we care about the generated javascript in the "show code" modal? I think that would still run into the same type issues

**Comment by mikeharv** [comment]
> I went looking at this a little bit! Would make more sense to fix this on the math block? (it should probably cast its arguments to numbers first) Consider that you can set a variable to a string at any time (not just for prompts): image

Thanks for bringing this up @tim-dot-org! I had some of the same thoughts myself, and was wondering if a "Why not both?" approach might make the most sense. 
As to your point about setting variables in other ways, students can currently only store values with prompts or directly in their code. I'd argue that prompts are more ambiguous whereas your specific code does explicitly imply it will be a string/text rather than a number. The curriculum does model using both the text and number blocks with variables, although students aren't explicitly taught about data types.
I'd suggest that this fix still makes sense for the prompt case, but I'm totally open to exploring an additional fix on the math_arithmetic block. I'll leave a separate comment with some thoughts about that.

**Comment by mikeharv** [comment]
Across our various Blockly environments, we make use of two different Blockly repos. Most environments, including Sprite Lab, use code-dot-org/blockly (which we forked in like 2013), but we're gradually moving labs over to mainline Google Blockly (google/blockly). 
The `math_arithmetic` block is defined in each repo below:
- https://github.com/code-dot-org/blockly/blob/main/generators/javascript/math.js#L36
- https://github.com/google/blockly/blob/master/generators/javascript/math.js#L27

In both cases, it's a standard Blockly block, which makes redefining it more difficult. If we did push a change to our Blockly fork, it would of course affect all labs that use it, but it would also likely revert for Sprite Lab when we move it Google Blockly. Another option would be to create our own identical block which could cast its arguments to numbers. This would probably be intuitive for students, but we'd probably want to avoid having two identical blocks out there in student projects that work differently. 
I suppose it could also be argued that any change to the `+` operator in our tools would mean it's different from standard JavaScript.
That all being said, if we think it's worth changing, we could talk to the Blockly team to see if it's something they'd expect us to be able to override in another way.

**Review by tim-dot-org — APPROVED** [review]
okay cool! that makes a lot more sense why we're doing it this way!

**Pull request merged**
