### PR TITLE
Remove Sprite.displace() customization

### PR DESCRIPTION
**Pull request by islemaster**
We previously customized `Sprite.displace()` to make it modify the displaced sprite's velocity consistent with a fully inelastic collision.  Here we are removing that customization and going back to the original behavior, which is to update the displaced sprite's position but not modify its velocity.

Finishes [axosoft 495](https://codeorg.axosoft.com/viewitem?id=495&type=features&force_use_number=true).

**Before:**

displace_before

**After:**

displace_after

The only change is that the x-velocity value of the red box in the displace case (the last one) does not change from -1 to 3, even though it is being pushed to the right.

### CODE REVIEW

**Comment by joshlory** [comment]
Looks like some extra commits got picked up in the merge of `staging` (vs. `staging-next`)?

**Comment by islemaster** [comment]
Yes - I was going to merge one more time after the next staging>staging-next integration so they should go away.  Checking now...

**Comment by islemaster** [comment]
Yes, that's better.  Probably easier to read the diff now too :grin:

**Comment by islemaster** [comment]
Unit tests are passing, but after something like six re-runs I can't get all the UI tests to pass.  Checking to see if there's some actual issue, possible unrelated to this PR.

**Comment by islemaster** [comment]
Yeah, nothing related to gamelab, and different every time.  Merging...

**Pull request merged**
