### PR TITLE
Disable toolbox autopopulate

### PR DESCRIPTION
**Pull request by balderdash**
Hiding it behind a query string param.

### CODE REVIEW

**Comment by Hamms** [comment]
Do we want to disable this or just remove it outright?

**Comment by balderdash** [comment]
I think it could come in handy, as long as you're using it on purpose.

**Comment by Hamms** [comment]
oh, absolutely, but without UI support it's a feature that will likely never be used, and I'm not thrilled about the idea of having unused code lying about. Do we have plans to add support for this in the near future?

**Comment by balderdash** [comment]
Oh, yeah without a button it probably wouldn't be used. Removed.

**Comment by Hamms** [comment]
LGTM. Moment of silence for the loss of a feature. :cry: 

Do you know if we have any plans to revisit this? Seems like it would be really great to have some validation in the editor that warns you if you have blocks that aren't in the toolbox and prompts you to autoadd them.

**Comment by balderdash** [comment]
I think we wanted to put this behind a confirmation dialog or something, but I just never got around to adding that.

**Pull request merged**
