### PR TITLE
Update Optimizely script on Hoc.com

### PR DESCRIPTION
**Pull request by tanyaparker**
Remove it from HourofCode.com theme and only include it on each individual page we need it on. To follow the same optimal behavior like how we use Optimizely on Code.org.

### CODE REVIEW

**Comment by breville** [comment]
Is top of page most efficient?  Sometimes it's possible to include at bottom of page but not sure if that'll be the case here...

**Comment by tanyaparker** [comment]
Should I try it on the bottom first?

**Comment by breville** [comment]
Hmm, this looks to be a "classic" snippet?  In fact, they recommend inside `<head>`: https://help.optimizely.com/Set_Up_Optimizely/Implement_the_snippet_for_Optimizely_Classic

**Comment by tanyaparker** [comment]
Going to merge for now and see if I can optimize later to load the script in `<head>`. We need to get the test ready before 10/18 blast.

**Pull request merged**
