### PR TITLE
[Finishes #101918240] dont redirect between view/edit if no current project

### PR DESCRIPTION
**Pull request by Bjvanminnen**
I was seeing weird behavior where if I went to projects/applab/channel_id/edit things worked fine, but if I went to /edit/ or /edit#, I would end up with a readonly workspace. I just realized what was happening.

In all cases we would call redirectEditView twice - once before the project was loaded, and once afterwards. In the /edit case, the first call would send us to /view and the second would send us back to /edit. However, when we have /edit/ or edit/#, location.href.replace(/\/edit$/, '/view') would not result in a replacement, and we would stay on the /edit page but with a readonly workspace. The second time through, we would already be on the /edit page, so we wouldn't look to modify the readonly workspace.

As I explain this, I realize we should also probably be better about making sure that replacement happens properly when the url ends in / or #

The fix as it is right now is that we don't do a redirect until we've loaded a channel (and actually know if we're the owner or not).

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Second commit makes it so that if I go to /edit/ as non-owner, it will redirect to /view/. Previously it would have given us the readonly workspace (as desired) but not done the pushState.

**Comment by davidsbailey** [comment]
LGTM

**Comment by breville** [comment]
Pardon my ignorance.. so the browser would do two redirects in a row?
Would it make sense to load the page fewer times?

**Comment by Bjvanminnen** [comment]
(1) We're not actually going redirects, just using pushState to change the url in the browser bar
(2) We were doing two in a row, with the fix we only do one.

**Pull request merged**
