### PR TITLE
Facilitator 1920 app mailer

### PR DESCRIPTION
**Pull request by clareconstantine**
(merge this after https://github.com/code-dot-org/code-dot-org/pull/26209)

Update the facilitator application mailer to 1920, including email previews and all references to it.

Update the emails according to the [spec](https://docs.google.com/document/d/1phGCBTGPmjaj_Jm8z6rd4T_GFRQMhydScKBT19IzAoE/edit#)

cc: @tanyaparker

### CODE REVIEW

**Comment by clareconstantine** [comment]
[Update Facilitator application emails and mailer](https://trello.com/c/f0bmR3XH/770-update-facilitator-application-emails-and-mailer)

**Review by Hamms — COMMENTED** [review]
Given that the old mailer is being removed, is there a reason to keep this component year-specific, rather than creating a single generic mailer and updating it every year?

**Review by Hamms — APPROVED** [review]
LGTM for now, but we are definitely going to want to bring the facilitator and teacher mailers into a consistent place as soon as we can

**Comment by clareconstantine** [comment]
To clarify - they are currently both year-specific, but since we don't preserve previous years' mailers, the follow-up is to rename both the facilitator and teacher mailers to year-agnostic names so we don't have to update the names and references every year going forward.

**Pull request merged**
