### PR TITLE
Enable script cache on levelbuilder

### PR DESCRIPTION
**Pull request by balderdash**
Unreverts https://github.com/code-dot-org/code-dot-org/pull/10967, with fix for seeding issue.

### CODE REVIEW

**Comment by wjordan** [comment]
Is there a reason why the new config property is the negative `disable_script_cache` rather than the affirmative `enable_script_cache` or more simply `script_cache`?

**Comment by wjordan** [comment]
Further, is there a reason why the `script_cache` needs to be a separate config property from `cache_classes`, or if not could we just enable/disable the script cache functionality based on the (existing) configuration of `cache_classes`, avoiding introducing a new config variable altogether?

**Comment by balderdash** [comment]
Ha, I switched from `enable_script_cache` to `disable_script_cache` during the review of the original PR, based on the argument that the production behavior should be the default. The config option can default to true of course, but I think it's more about readability than resilience. @Hamms might have more to say about that.

Doing dev work on the cache without a separate config option was pretty painful, since having the class_cache on meant I had to restart the server every time I made a change. I can see it coming in handy for anybody working on it in the future.

**Comment by wjordan** [comment]
Thanks for the extra context! Sorry I didn't notice the previous discussion.

If you see a reason for a separate config option that sounds good to me.

On the naming/semantics of the option, my preference would be to align the property with `cache_classes` (maybe named `cache_scripts` to make the similarity most clear?), but I don't have strong concerns either way (knowing the reason for its current structure is sufficient for me), so whatever's easiest / most convenient for you is fine by me.

**Pull request closed without merging**
