### PR TITLE
deflake section projects ui test by making 2 attempts to rename the project

### PR DESCRIPTION
**Pull request by davidsbailey**
A [flaky failure](https://cucumber-logs.s3.amazonaws.com/test/test/ChromeLatestWin7_teacher-dashboard_output.html?versionId=iaszMEubb1m1zXEloze62nhN3TXaNnHP) was reported where the section projects scenario in the teacher dashboard ui test was not successfully renaming the newly-created project:
project-rename

when creating a new project without renaming, there is an initial save that happens. Note the text goes from "Saved" to "Saving..." and back to "Saved":
new-project-save

It seems like the initial save is interfering somehow with the renaming. The solution proposed in this PR is to attempt to rename the project twice, so that if the initial save interferes with the first rename, then the second rename will most likely succeed.

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
Could we instead avoid doing a rename until the initial save has reported success?

**Comment by davidsbailey** [comment]
I don't see any way to do that by waiting for part of the DOM to change, but it may be possible to set something on `dashboard.project` when the initial save completes and then wait for that to happen. I'll look into it.

**Comment by Bjvanminnen** [comment]
Oh, I see - because Saved could mean we haven't started saving OR it could mean we're done saving?

If you don't see something easy, I wouldn't spend too much time on this (and we can just go with this double rename approach).

**Comment by davidsbailey** [comment]
Correct, plus we can't reliably wait for "saving..." to happen because it
may have happened already by the time we start waiting.

**Comment by davidsbailey** [comment]
@Bjvanminnen is this better? I don't think we should be opposed to production code which only exists for test purposes (we do this frequently when we add css classes to things that we then later look for only from tests), but if this seems too hacky overall I'm fine with the original approach.

**Comment by Bjvanminnen** [comment]
I don't love it, but I also don't hate it. I think it's probably fine.

We've used `window.__TestInterface` for some things like this elsewhere. Not sure if that's a better place for this. I'll leave that up to you.

I might put a short comment above `isInitialSaveCompleteForTesting` that this is used by UI tests.

**Comment by davidsbailey** [comment]
I see there are a number of places where we expose `__TestInterface` on specific modules or objects. I've gone with that approach rather than `window.__TestInterface`, since it seems just as clear but with better encapsulation.

**Pull request merged**
