### PR TITLE
take rectangular thumbnails in applab

### PR DESCRIPTION
**Pull request by davidsbailey**
Stop cropping applab thumbnail images before uploading them, because we may want the entire image for something in the future.

~~the section projects UI will now show a vertically squished image. @poorvasingal does this seem ok?~~ no change to the section projects UI, which is also covered by eyes tests (image removed).

no change to the appearance of the Public Gallery:
screen shot 2017-05-18 at 8 40 39 am

### CODE REVIEW

**Comment by Bjvanminnen** [comment]
I cannot tell the difference between your before and after images. Am I missing something?

**Comment by Bjvanminnen** [comment]
code changes lgtm

**Comment by davidsbailey** [comment]
@Bjvanminnen @poorvasingal I've updated the CSS in the section projects view to show a square center-cropped region again, so there should be no visual difference there after all. @poorvasingal , I retract my question!

@Bjvanminnen no, there's no difference in the Public Gallery image you're asking about. in retrospect I could have omitted the image and you could have taken my word for it. (we'll want eyes tests soon for these)

**Comment by Bjvanminnen** [comment]
Oh, okay. The point was that they were the same :)

**Pull request merged**
