### PR TITLE
Enable Applab themes for everyone

### PR DESCRIPTION
**Pull request by cpirich**
* Removing the `applabThemes` experiment checks, as we are now ready to enable this for all users
* Reminder: existing projects will still look the same. They will use what we call the `Classic` theme until the student decides to change an existing or new screen. New projects will use the `Default` theme.

### CODE REVIEW

**Comment by jmkulwik** [comment]
Worth doing another bug bash since there was so much code change since the last one?

**Comment by cpirich** [comment]
@ryansloan Do you think we need another bug bash? As far as I know, we've mostly reorganized code since the last one + the "unintentional default" change and the "apply theme" button was added.

**Comment by ryansloan** [comment]
@jmkulwik @cpirich I've talked about this plan with our stakeholders, there's no need for an acceptance bug bash. If we feel like test coverage is good enough on this that we don't need a QA bug bash, then I think we are good to ship it. (sorry for the delay on this, I missed my notification for this tag)

**Review by jmkulwik — APPROVED** [review]
🎉 Looks great!!

**Pull request merged**
