### PR TITLE
Move localeEnglishName into redux

### PR DESCRIPTION
**Pull request by davidsbailey**
Follow-on to https://github.com/code-dot-org/code-dot-org/pull/33832 and  #33757. This PR is pure cleanup and does the following:
* renames ambiguous `locale` variable to more specific `localeEnglishName`
* moves `localeEnglishName` into `localesRedux`

## Testing story

Existing unit tests cover most of the affected components. I verified manually that the AssignmentSelector in the EditSectionForm, and the AssignmentVersionSelector in the ScriptOverview, are both working properly in english on my local machine.

## Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by davidsbailey** [comment]
screenshots of where these show up:
Screen Shot 2020-03-25 at 3 35 40 PM

Screen Shot 2020-03-25 at 3 36 13 PM

**Comment by davidsbailey** [comment]
Apologies for the late updates. this is ready to review!

**Review by Erin007 — APPROVED** [review]
LGTM! Happy to see the reduction in props being passed down. Thanks for the follow up.

**Review by islemaster — APPROVED** [review]
:+1:

**Pull request merged**
