### PR TITLE
Removes Fun-O-Meter dashboards.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Now that this data is in Redshift, it should be analyzed and consumed via Tableau.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Added a commit removing the `window.dashboard.funometer` from `code-studio.js`.

**Comment by Hamms** [comment]
can `apps/code-studio/funometerPercentagesByDay` also be removed, then?

**Comment by ashercodeorg** [comment]
Already removed. That's how I found the other, tests failed.

**Comment by Hamms** [comment]
d'oh, of course. LGTM!

**Comment by ashercodeorg** [comment]
CircleCI failures are now unrelated.

**Pull request merged**
