### PR TITLE
Upgrade FatalErrorDialog story

### PR DESCRIPTION
**Pull request by jmkulwik**
Remove the ApplabVisualizationColumn story because it doesn't display a reusable component. 
(For now, the old ApplabVisualizationColumn can be found on our [old Storybook site](https://code-dot-org.github.io/cdo-styleguide/?selectedKind=ApplabVisualizationColumn&selectedStory=Overview&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel). I'd definitely appreciate a second set of eyes on whether it should be removed!)

Updated the FatalErrorDialog story.

New FatalErrorDialog story!
image

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by bencodeorg — APPROVED** [review]
Tangent to this PR, but curious about the "still exists on our old storybook site" point -- I remember digging into this a bit with Maddie a year ago. Looks like I wrote up a ticket that is in our "xteam" Jira graveyard:

https://codedotorg.atlassian.net/browse/XTEAM-355

@madelynkasula do you have thoughts/visions for our storybook site after the upgrade? Sorry if this was discussed at Storybook time on Friday and I missed it.

**Comment by maddiedierker** [comment]
> do you have thoughts/visions for our storybook site after the upgrade?

no vision, just that we need to fix this! since we've put some work into storybook now, it seems like a good time to address this tech debt and fix the storybook deploy so that people outside engineering can actually look at storybook. @jmkulwik how do you think we could get this work scheduled?

**Review by maddiedierker — APPROVED** [review]
good call to just remove the ApplabVisualizationColumn story -- looking back at it, that component is too specific for storybook, so it doesn't make sense to document it there

**Comment by jmkulwik** [comment]
> how do you think we could get this work scheduled?

Hmm let's chat at our next 1:1.

**Pull request merged**
