### PR TITLE
Update SETUP.md - AWS setup is optional

### PR DESCRIPTION
**Pull request by uponthesun**
Karis was able to `rake build` without AWS credentials (after debugging other issues), which is what we want. I was also able to do so using a fresh docker container without credentials. So, I think we can safely mark this step as optional, as it should be.

I don't know offhand the things that actually depend on AWS; it'd be nice to list some of them here if you guys know the major ones.

### CODE REVIEW

**Comment by davidsbailey** [comment]
I think we had a contributor complain about needing AWS credentials to set up our repo quite recently. I can't remember if I saw this in slack or zendesk but @islemaster may remember.

**Review by davidsbailey — APPROVED** [review]
I would expect that project-backed level types such as https://studio.code.org/projects/gamelab will not work properly without AWS credentials. I'm fine with saying that this step is optional, but if there is anywhere that we're tracking the breaking of dependencies on secret keys, it would be nice to note this there.

from a CI perspective, this could cause UI tests which use applab / gamelab / dance party to fail.

**Comment by islemaster** [comment]
Conversation was [in Slack here](https://codedotorg.slack.com/archives/C0T0PNTGD/p1549048567079000) (requires access) in response to a Twitter user [@arrow_dev](https://twitter.com/arrow_dev/with_replies) reaching out to us for setup help.

I'd love for us to get to a world where there are local/open alternatives for these dependencies, and I don't think there's any resistance to that on the team other than allocating resources for it.  :+1: to being more contributor-friendly!

**Comment by joshlory** [comment]
Is running our tests something we want a contributor to be able to do? (note: I think we're a long way from this today, with the Sauce Labs dependencies etc.)

**Pull request merged**
