### PR TITLE
Add Schools string for top nav

### PR DESCRIPTION
**Pull request by kelbyhawn**
Adds a new string "Schools" for use in the signed out top nav on code.org. Once this string is translated I will replace the Projects link with this Schools link in this PR: https://github.com/code-dot-org/code-dot-org/pull/56527

**Jira ticket:** [ACQ-1464](https://codedotorg.atlassian.net/browse/ACQ-1464)

### CODE REVIEW

**Review by bethanyaconnor — APPROVED** [review]
I assume we just need a full sync in/out? Said another way, do we have this string translated _somewhere_, just maybe not in this file?

**Comment by kelbyhawn** [comment]
> I assume we just need a full sync in/out? Said another way, do we have this string translated _somewhere_, just maybe not in this file?

The word "schools" is in other strings in this file and other i18n files, but not by itself — does that influence things?

**Comment by bethanyaconnor** [comment]
Yeah -- it means we can't rely on a translation already existing and will have to wait a bit longer to make the change. If it existed by itself, we'd have translations next week.

**Comment by kelbyhawn** [comment]
> Yeah -- it means we can't rely on a translation already existing and will have to wait a bit longer to make the change. If it existed by itself, we'd have translations next week.

Got it, and bummer!

**Comment by castro-jorge** [comment]
@kelbyhawn translations are in for 33 languages!

**Comment by kelbyhawn** [comment]
> @kelbyhawn translations are in for 33 languages!

Woo hoo, thanks @castro-jorge!

**Comment by kelbyhawn** [comment]
@mgc1194 ~do you know when should I be able to see this string locally? I'm still seeing the `translation missing: en-US.header_schools` error.~ Figured this out! I needed to add the string `header_schools` to the i18n gsheet 🙃

**Pull request merged**
