### PR TITLE
Stops sending PII to server for U13 petition signers.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Note that, regardless of what email is sent server-side, we store a null name and `anonymous@code.org` email in the DB for U13 petition signers as the result of [this code](https://github.com/code-dot-org/code-dot-org/blob/6dd1faddbbc82f0e4d3d3206f0cf3efa8b26c495/pegasus/forms/petition.rb#L12-L15).

```
SELECT kind, COUNT(0) FROM forms WHERE email = 'anonymous@code.org' GROUP BY 1;
+---------------------------------+----------+
| kind                            | COUNT(0) |
+---------------------------------+----------+
| ClassSubmission                 |      542 |
| CompanyProfile                  |      110 |
| HelpUs2013                      |        1 |
| HocCertificate2013              |  2113995 |
| K5ProfessionalDevelopmentSurvey |     1287 |
| Petition                        |   224572 |
+---------------------------------+----------+
```

Note that the current implementation replaces the email value in the DOM. Unfortunately, without further work, we cannot replace the email with an empty string (as done with Code Studio sign-in) [a single space] because of validation imposed on the field.
TODO(asher): Determine if we should change the validation to allow an empty string for this use case.

Note that this does not fix a warning that occurs as part of this workflow.
image

### CODE REVIEW

**Comment by Hamms** [comment]
just to make sure I'm understanding this correctly:

Currently, the client sends the server an email, and the server discards it and instead stores "anonymous@code.org"

This change causes the client to send the server "anonymous@code.org" in the first place. Presumably the server then "discards" it and replaces it with the same "anonymous@code.org" value.

Is the motivation just to prevent the server from even having the opportunity to see the user's email?

**Comment by ashercodeorg** [comment]
Your understanding is correct. Also, I'm being asked to expand the scope of this PR, so there will be another commit adding additional logic and functionality.

**Comment by Hamms** [comment]
Okay, cool. LGTM in that case!

**Comment by ashercodeorg** [comment]
PTAL (added clearing of `name` client-side).

**Comment by ashercodeorg** [comment]
CC @tanyaparker Note the warning in the summary that this PR does not resolve.

**Comment by Hamms** [comment]
LGTM

**Pull request merged**
