### PR TITLE
Convert project gallery from 1000px to 970px

### PR DESCRIPTION
**Pull request by caleybrock**
The header for this isn't perfect, but I think we should consider updating the HeadingBanner in a separate PR once /courses and /home is done because it'll affect other pages.

Production:
screencapture-studio-code-org-projects-1498766219181

Staging after my changes:
screencapture-localhost-studio-code-org-3000-projects-1498766191570

cc @tanyaparker @Erin007

### CODE REVIEW

**Comment by tanyaparker** [comment]
By header isn't perfect do you mean the component with the "My Projects" and "Public Gallery" tabs?

**Comment by tanyaparker** [comment]
Or did you mean the "Project Gallery" title doesn't left align with the rest of the page components?

**Comment by caleybrock** [comment]
@tanyaparker yep, those were made for 960px (which I'm not sure what matches) so it doesn't line up perfectly.

**Comment by caleybrock** [comment]
@tanyaparker the "Project Gallery" and the tabs are in one component, so those line up, they are just slightly off with the rest of the page.

**Comment by tanyaparker** [comment]
Great suggestions, Dave. +1

**Comment by caleybrock** [comment]
Good call. I updated that with the expectation that we may have to adjust a bit again.
screencapture-localhost-studio-code-org-3000-projects-1498772923174

**Comment by davidsbailey** [comment]
This looks better! Thanks for changing.

**Pull request merged**
