### PR TITLE
Add cap_user_events Table to Daily Redshift Export

### PR DESCRIPTION
**Pull request by jordan-springer**
pulling in new table per DWR

## Links
- spec: []()
- jira ticket: [dataops-757](https://codedotorg.atlassian.net/browse/DATAOPS-757)

## Testing story

n/a

## Follow-up work

1. validate data has arrive in Redshift
2. "" dad is accessible in Trevor

## Privacy
n/a

schema is as follows:
``` 
  create_table cap_user_events (
    name,
    user_id,
    policy,
    created_at,
    updated_at,
    state_before,
    state_after
)
```

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by cat5inthecradle — APPROVED** [review]
Out of curiosity, what does "CAP" stand for?

**Comment by jordan-springer** [comment]
> Out of curiosity, what does "CAP" stand for?

i think it's "colorado privacy act?"

**Comment by cat5inthecradle** [comment]
That's usually CPA, but I think this is related. maybe child account policy?

**Review by cat5inthecradle — APPROVED** [review]

**Comment by cat5inthecradle** [comment]
Confirmed, it's "Child Account Policy"

**Comment by unlox775-code-dot-org** [comment]
What is DWR?

**Comment by sureshc** [comment]
What is "DWR"?

**Comment by sureshc** [comment]
> What is DWR?

I'm also wondering 🙂

**Comment by jordan-springer** [comment]
> > What is DWR?
> 
> I'm also wondering 🙂

sorry, "data work request"

**Comment by jordan-springer** [comment]
@sureshc if we merge this PR, we will it still be blocked anyway by the DMS job?

**Comment by sureshc** [comment]
> @sureshc if we merge this PR, we will it still be blocked anyway by the DMS job? 

Yup. We need to fix the export process first.

**Comment by sureshc** [comment]
Deployed:

```
Pending update for stack `DATA-production`:
Modify DMSCron [AWS::DMS::ReplicationTask] Properties Replacement: Conditional (TableMappings)
Proceed? [y/n]
y
 Stack update requested, waiting for provisioning to complete...
.2024-06-28 22:23:20 UTC- DMSCron [UPDATE_IN_PROGRESS]
......2024-06-28 22:24:06 UTC- DMSCron [UPDATE_COMPLETE]
2024-06-28 22:24:07 UTC- DATA-production [UPDATE_COMPLETE_CLEANUP_IN_PROGRESS]

Stack update complete.
Outputs:
Finished stack:data:start (2 minutes)
```

**Pull request merged**
