### PR TITLE
add without_deleted followers

### PR DESCRIPTION
**Pull request by carl-codeorg**
Bryan [reported on Slack](https://codedotorg.slack.com/archives/CFTFD6BPV/p1707176682739239) that the followers helper in the User model was returning deleted followers. For some reason, with this particular relation, we have to specify without_deleted to filter out Follower records with a deleted_at date.

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by nicklathe — APPROVED** [review]
👍

**Comment by etaderhold** [comment]
I've been messing around with this trying to make sure it includes only sections the user is currently instructing as well, and I think I'm close. Please hold off on merging for a bit.

**Comment by etaderhold** [comment]
> I've been messing around with this trying to make sure it includes only sections the user is currently instructing as well, and I think I'm close. Please hold off on merging for a bit.

Okay...with this latest change:
```
irb(main):001:0> User.find(1).active_section_instructors
D, [2024-02-06T10:35:51.765441 #21414] DEBUG -- :   User Load (16.8ms)  SELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = 1 LIMIT 1
D, [2024-02-06T10:35:51.801193 #21414] DEBUG -- :   SectionInstructor Load (1.7ms)  SELECT `section_instructors`.* FROM `section_instructors` WHERE `section_instructors`.`deleted_at` IS NULL AND `section_instructors`.`instructor_id` = 1 AND `section_instructors`.`status` = 0
```
Only includes non-deleted section instructors, yay!

```
irb(main):002:0> User.find(1).sections_instructed
D, [2024-02-06T10:36:08.058225 #21414] DEBUG -- :   User Load (5.0ms)  SELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = 1 LIMIT 1
D, [2024-02-06T10:36:08.112168 #21414] DEBUG -- :   Section Load (1.4ms)  SELECT `sections`.* FROM `sections` INNER JOIN `section_instructors` ON `sections`.`id` = `section_instructors`.`section_id` WHERE `section_instructors`.`instructor_id` = 1 AND `section_instructors`.`status` = 0 AND `sections`.`deleted_at` IS NULL AND `section_instructors`.`deleted_at` IS NULL
```
Only includes non-deleted sections and non-deleted section instructors, yay!

```
irb(main):003:0> User.find(1).followers
D, [2024-02-06T10:37:08.422511 #21414] DEBUG -- :   User Load (21.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = 1 LIMIT 1
D, [2024-02-06T10:37:08.479166 #21414] DEBUG -- :   Follower Load (2.6ms)  SELECT `followers`.* FROM `followers` INNER JOIN `sections` ON `followers`.`section_id` = `sections`.`id` INNER JOIN `section_instructors` ON `sections`.`id` = `section_instructors`.`section_id` WHERE `section_instructors`.`instructor_id` = 1 AND `section_instructors`.`status` = 0 AND `sections`.`deleted_at` IS NULL AND `section_instructors`.`deleted_at` IS NULL AND `followers`.`deleted_at` IS NULL
```
Only includes non-deleted sections and non-deleted section instructors and non-deleted followers, yay!

**Comment by carl-codeorg** [comment]
@etaderhold are you cool with me merging this now? Your changes look good and tests are passing.

**Review by etaderhold — APPROVED** [review]
> @etaderhold are you cool with me merging this now? Your changes look good and tests are passing.

Absolutely!

**Pull request merged**
