### PR TITLE
Removed video from final dance AI level.

### PR DESCRIPTION
**Pull request by jmkulwik**
## Warning!!

We have entered Pixel Lock for Hour of Code!

Computer Science Education Week will be happening from Dec 4 - Dec 10. Alongside this event, we will
be launching our new Hour of Code activity. Please consider any risk introduced in this PR that
could affect Dance Lab, instructions, saving and logging student progress, caching, or anything
related to the Hour of Code activities, old or new. Even small changes, such as a different button
color, are considered significant during this time. If this change will affect the new Hour of Code
activity in any way, join the morning change review to get your changes approved prior to merging.
Reach out to the Student Labs team for more details!

---

Updates Dance AI level 10 to remove the video. 
https://studio.code.org/s/dance-ai-2023/lessons/1/levels/10 

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by cat5inthecradle — APPROVED** [review]

**Comment by cat5inthecradle** [comment]
pending drone run
https://drone.cdn-code.org/code-dot-org/code-dot-org/37001

**Review by breville — APPROVED** [review]
btw, would recommend updating PR description from its default.

**Comment by jmkulwik** [comment]
> btw, would recommend updating PR description from its default.

@breville Are you wanting further details than what's in the description?

"Updates Dance AI level 10 to remove the video.
https://studio.code.org/s/dance-ai-2023/lessons/1/levels/10"

**Comment by cat5inthecradle** [comment]
@jmkulwik did you mean to close this?

**Comment by breville** [comment]
> @breville Are you wanting further details than what's in the description?

Oh, I didn't notice this below the template's warning.  I think for long-term readability, the description should probably come first?  No big deal, though.

**Comment by jmkulwik** [comment]
> @jmkulwik did you mean to close this?

I did. I was running into an error in local development. However that has been resolved and this is once more good to go.

**Comment by wilkie** [comment]
Flaky error? (I'm assuming it is and re-running drone... UI tests also failed to spawn)

```
======ERROR["test_find_channel_owner_returns_nil_for_channel_with_no_owner", "UserTest", 675.5025734680003]
--
262 | test_find_channel_owner_returns_nil_for_channel_with_no_owner#UserTest (675.50s)
263 | Minitest::UnexpectedError:         Sequel::DatabaseError: Mysql2::Error::TimeoutError: Timeout waiting for a response from the last query. (waited 30 seconds)
264 | test/testing/projects_test_utils.rb:31:in `with_storage_id_for'
265 | test/testing/projects_test_utils.rb:9:in `with_channel_for'
266 | test/testing/projects_test_utils.rb:35:in `with_anonymous_channel'
267 | test/models/user_test.rb:4741:in `block in <class:UserTest>'
268 | test/testing/setup_all_and_teardown_all.rb:36:in `run'
```

**Comment by jmkulwik** [comment]
> Flaky error? (I'm assuming it is and re-running drone... UI tests also failed to spawn)
> 
> ```
> ======ERROR["test_find_channel_owner_returns_nil_for_channel_with_no_owner", "UserTest", 675.5025734680003]
> --
> 262 | test_find_channel_owner_returns_nil_for_channel_with_no_owner#UserTest (675.50s)
> 263 | Minitest::UnexpectedError:         Sequel::DatabaseError: Mysql2::Error::TimeoutError: Timeout waiting for a response from the last query. (waited 30 seconds)
> 264 | test/testing/projects_test_utils.rb:31:in `with_storage_id_for'
> 265 | test/testing/projects_test_utils.rb:9:in `with_channel_for'
> 266 | test/testing/projects_test_utils.rb:35:in `with_anonymous_channel'
> 267 | test/models/user_test.rb:4741:in `block in <class:UserTest>'
> 268 | test/testing/setup_all_and_teardown_all.rb:36:in `run'
> ```

There are no tests that test this change, so any test failures will be flaky tests.

**Comment by wilkie** [comment]
Going to assume tests are flaky and UI tests aren't going to be affected by this change and move things along by merging.

**Pull request merged**
