### PR TITLE
bump timeout for k1_6

### PR DESCRIPTION
**Pull request by Bjvanminnen**

### CODE REVIEW

**Comment by trevorb** [comment]
LGTM, but let's wait and see what circleci says ;)

**Comment by Bjvanminnen** [comment]
Agreed. Though last time I changed this (to be tick based) circleci DID report success

**Comment by trevorb** [comment]
Passed the first time.  I'm re-running it to double confirm

**Comment by trevorb** [comment]
I've re-run the build 4 times and it's passed all 4.  So LGTM

**Pull request merged**
