### PR TITLE
Remove plc task model

### PR DESCRIPTION
**Pull request by davidsbailey**
As part of platformization we are changing how script levels work. This will affect every component which has a script_level_id. Because Plc::Task is no longer used (citation needed), I'm proposing we remove it rather than update it.

## Testing story

Removed unit tests which verify plc task behavior. 

# Reviewer Checklist:

- [ ] Tests provide adequate coverage
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by islemaster — APPROVED** [review]
Looks great, thank you for doing this! :+1:
A little history: `Task` was part of a half-finished refactor and may never have been used, really.

**Comment by bencodeorg** [comment]
Potentially useful for the record -- how is this deprecated if we were still writing to it a couple weeks ago? Or is it just ed programs folks will be using some other mechanism to write online PD going forward?

**Comment by davidsbailey** [comment]
@bencodeorg  in the literal sense, this is deprecated because although we were writing to it a couple weeks ago, that data apparently wasn't being used for anything, and now (as part of deprecating it) we are no longer writing to it. I'm not sure if that helps? Or are you perhaps alluding to some potential current use for this data by the folks who write our online PD?

**Comment by islemaster** [comment]
We generate `Plc::Tasks` automatically in an after-save hook on `Script` for any script marked as a professional learning course.  Our curriculum writers currently interact with our main curriculum models to build curriculum, and these are generated as a side-effect, not actually used for anything.

https://github.com/code-dot-org/code-dot-org/blob/76e33ca0a4fe95c6454a56de14e23d01630691ee/dashboard/app/models/script.rb#L88

**Comment by bencodeorg** [comment]
Got it, thanks both! I think I was confused by these level names Andrea shared in the online PD script (thinking that they were actual `Task` instances, not just levels named task...):

```
level 'Mar20 Part1_Task3'
level 'Mar20 Part1_Task4'
level 'Mar20 Part1_Task5'
level 'Mar20 Part1_Task6'
level 'Mar20 Part1_Task7'
```

**Pull request merged**
