### PR TITLE
Fixes violations of and reenables the rubocop Style/RescueModifier.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes generated by `bundle exec rubocop --only Style/RescueModifier --auto-correct`, then modified manually to fix resulting lint failures.

### CODE REVIEW

**Comment by ashercodeorg** [comment]
CircleCI failures seem unrelated.

**Comment by wjordan** [comment]
I don't agree with this style rule, in all of the cases in this diff I find the original to be preferable.

I wouldn't strongly object to enforcing this rule if the rest our team agrees with it, but you'll need to find someone else that does to review this PR.

**Comment by ashercodeorg** [comment]
Note that, as is, I agree the existing format is preferable. However, the updated syntax will cause us to trap only the intended exceptions when the `rescue` block is restricted (TODO in another rubocop fixup).

FYI @wjordan.

**Comment by joshlory** [comment]
Hmm, if this is needed for another RuboCop rule I wonder if it makes sense to include both of them in the PR so it's clear what the advantage is?  My initial impression is the same as @wjordan's, the original seems more readable.

**Pull request closed without merging**
