### PR TITLE
Create <CraftDialog/> and <PlayerSelectionDialog/>

### PR DESCRIPTION
**Pull request by maddiedierker**
The first PR to refactor away EJS templates in Minecraft. This:

- Creates a `<CraftDialog/>` component (most of our EJS templates in Minecraft are dialogs, so this will be used in future PRs)
- Refactors the agent [playerSelection.html.ejs template](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/craft/agent/dialogs/playerSelection.html.ejs) to use `<PlayerSelectionDialog/>` and redux

This is a pure refactor (the HTML structure and styles have not changed), so no visible change is expected.

## Links

- [STAR-1553](https://codedotorg.atlassian.net/browse/STAR-1553)

## Testing story

Relies on existing UI/eyes tests on Minecraft dialogs.

## Follow-up Work

Refactor the player selection dialog in [simple](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/craft/simple/dialogs/playerSelection.html.ejs) and [designer](https://github.com/code-dot-org/code-dot-org/blob/staging/apps/src/craft/designer/dialogs/playerSelection.html.ejs) to use `<PlayerSelectionDialog/>`.

### CODE REVIEW

**Review by epeach — APPROVED** [review]
Wow - big changes! Is there any test coverage affected by these changes? If not, should there be?

**Comment by maddiedierker** [comment]
there are UI tests that implicitly and explicitly test this dialog (i.e., they either look specifically for this dialog, or a step of the test is dismissing/using this dialog to test something else on a minecraft level). there are a couple of tests i debated adding and weren't sure how useful they'd be (i have a follow-up PR where i can add them if you think either/both are useful):
1. a storybook entry for `<CraftDialog/>`
2. unit tests for the new craft redux store. it doesn't have any real functionality right now, but if we build on what i've added here, having some basic unit tests might be good

**Comment by epeach** [comment]
Hmm. I think option 2 would probably be the most useful, but that might be more necessary later than it would be right now. I feel like I haven't see a lot of storybook entries/edits recently. Are we still using that resource as we have in the past?

**Comment by maddiedierker** [comment]
re: storybook -- that's a great question. it is still used, although it's so disorganized right now that it has been used less and less. however, it will be a core part of documentation for the component library, so i'll be working on making it more useful as part of that project and would like to keep using it

**Pull request merged**
