### PR TITLE
Update Dockerfile for `aurora-snapshots-fargate` to Ubuntu 20

### PR DESCRIPTION
**Pull request by Hamms**
Specifically, update it to use the same version of Ubuntu used by all of our persistent managed servers, for consistency.

Note that **I have no idea how to test this**; please let me know if you do!

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by cat5inthecradle** [comment]
Two things will need to be tested here:

1. Does the dockerfile build successfully
2. Is the code valid for the latest version of Node and all modules in "package.json"

This config is VERY optimistic... This is deployed to the Offsite AWS Account, and there's no indication when it was last deployed anywhere in the AWS Console. It could honestly be running Node 6... given that the last updates to this directory were 5 years ago, and we have Node 6 specified for the Lambda's that are part of this backup infrastructure.

**Comment by cat5inthecradle** [comment]
Ok, how about this instead?

https://github.com/code-dot-org/code-dot-org/pull/55787

**Comment by Hamms** [comment]
Oh, that looks *much* better!

**Comment by Hamms** [comment]
closing in favor of https://github.com/code-dot-org/code-dot-org/pull/55787

**Pull request closed without merging**
