### PR TITLE
make regional partner pages responsive

### PR DESCRIPTION
**Pull request by davidsbailey**
Finishes https://codedotorg.atlassian.net/browse/ACQ-349

### before

https://user-images.githubusercontent.com/8001765/216182386-6397be05-f1ef-4dab-acee-1cb9e86a0ee6.mov

### after

https://user-images.githubusercontent.com/8001765/216182340-da6ed913-d0d6-4ba6-85c1-b3c8afec54eb.mov

## Testing story

* manually verified all modified pages adjust responsively on narrow screens
* pegasus rendering tests make sure all pages still render without errors

### CODE REVIEW

**Review by pablo-code-org — APPROVED** [review]

**Comment by dmcavoy** [comment]
It looks like the navigation list on the left disappears when you shrink the screen. Thoughts on ways we could show those on a small screen. Maybe have them show above the "Regional Partner Program" header? Maybe listed horizontally instead of vertically?

I don't think we need to block on this but if there is something quick we can do here lets give it a shot.

**Comment by megcrenshaw** [comment]
Yeah, I was hoping the nav list would be at the bottom, but when I run it locally, I don't see it. I don't think you can get to these pages from other places on our site, but I'm not sure.

Once the nav list question has been addressed (including deciding not to fix it), I'm good with it!

**Review by megcrenshaw — APPROVED** [review]

**Comment by davidsbailey** [comment]
> It looks like the navigation list on the left disappears when you shrink the screen. Thoughts on ways we could show those on a small screen. Maybe have them show above the "Regional Partner Program" header? Maybe listed horizontally instead of vertically?
> 
> I don't think we need to block on this but if there is something quick we can do here lets give it a shot.

I'm not seeing a quick way to do that based on other examples, so I think it would be a bigger work item requiring some design. The behavior appears to be consistent across pegasus for any page that has a nav specified like this: https://github.com/code-dot-org/code-dot-org/blob/6614045a705b06db4219cb4adb17ccc8cd762dd3/pegasus/sites.v3/code.org/public/educate/it.md#L3-L4 such as https://code.org/about or https://code.org/educate/it

I like the idea though! maybe the left nav could be collapsed into a button like we do on code.org/learn?

**Comment by dmcavoy** [comment]
Thanks for that context @davidsbailey. Let's go ahead and merge this then.

@kelbyhawn is the fact that on some marketing pages the left navigation disappears on mobile on your radar?

**Comment by kelbyhawn** [comment]
> @kelbyhawn is the fact that on some marketing pages the left navigation disappears on mobile on your radar?

@dmcavoy it wasn't on my radar, but thanks for surfacing it! I think the navigation pattern across the site in general could use a review/potential update.

**Pull request merged**
