### PR TITLE
Make Pd* models soft-delete

### PR DESCRIPTION
**Pull request by aoby**
While `deleted_at` is not necessarily honored on the Pegasus side, the only place these models are referenced there are in the exit surveys: [here](https://github.com/code-dot-org/code-dot-org/blob/5e8d575c3eb6ab0712326b6edcca34e8e05df84e/pegasus/sites.v3/code.org/public/pd-workshop-survey/splat.haml#L7-L11), [here](https://github.com/code-dot-org/code-dot-org/blob/622afefcc9663f1ce91ec7302328ccc78cde6533/pegasus/sites.v3/code.org/public/pd-workshop-survey/materials/splat.haml#L9-L14), and [here](https://github.com/code-dot-org/code-dot-org/blob/ea5ee2cecca58c59fc0f609fc78cf63d523059c5/pegasus/forms/pd_workshop_survey.rb#L83).

In the rare case where a workshop is deleted after the exit survey email went out, we should still allow the teacher to take the survey so I'm intentionally leaving `deleted_at` off of those queries.

### CODE REVIEW

**Comment by aoby** [comment]
Note the only failed circleCI test is unrelated: `ChromeLatestWin7_publicKeyCryptography_eyes_eyes`

**Comment by ashercodeorg** [comment]
Presumably there is a reason to index on the `deleted_at` columns? There will be some use case where we will want the set of all deleted objects?

**Comment by ashercodeorg** [comment]
Ideally, the database migration and the `acts_as_paranoid` insertion would be two separate PRs. For if something were to go wrong with this migration (any migration getting DTPed before this one), there would be a mismatch between the DB and the expectations of the ActiveRecord model.

No action required.

**Comment by ashercodeorg** [comment]
LGTM (see my comments)

**Comment by aoby** [comment]
RE: indexing the `deleted_at`, I was following this guidance: http://www.rubydoc.info/gems/paranoia/2.1.5

I don't have a specific query in mind that would require this. I could leave them off, and we can always add them later if the queries become expensive as we discussed offline about the combined indexes. Thoughts?

**Comment by ashercodeorg** [comment]
My vote is not to have indexes around that are never used.

**Comment by aoby** [comment]
All unit tests passed. The circleCI failure was a timeout in npm install (known transient issue) that prevented the UI tests from running - and this PR didn't change any UI. Merging...

**Pull request merged**
