### PR TITLE
Include dashboard_host in locals.yml.default

### PR DESCRIPTION
**Pull request by islemaster**
Recent discussion in Slack channel revealed that this setting is necessary for localhost-studio.code.org proxy to work after the Rails 5 upgrade.

### CODE REVIEW

**Comment by davidsbailey** [comment]
LGTM, although I'd prefer that @wjordan also comment on whether this will be necessary beyond the next week or so

**Comment by wjordan** [comment]
Any reason not to make this the default moving forward by changing the [line](https://github.com/code-dot-org/code-dot-org/blob/staging/deployment.rb#L55-L55) in `deployment.rb` instead?

**Comment by davidsbailey** [comment]
It's hard to say, because it's unclear to me why specifying 0.0.0.0 solves the problem. If this is to be the permanent fix, then changing it in deployment.rb sounds good, and a comment explaining it would be nice

**Comment by davidsbailey** [comment]
Reading about this a tiny bit more, it seems like 0.0.0.0 is a common value to use to make rackup happy, despite not finding a good explanation for it. So I'm fine with making this change to deployment.rb without explanation.

**Comment by islemaster** [comment]
Changed to alter default `dashboard_host` is deployment.rb instead of adding an entry to locals.yml.default.

**Comment by davidsbailey** [comment]
LGTM!

**Pull request merged**
