### PR TITLE
Redirect hourofcode.com/beyond to studio.code.org/users/sign_up

### PR DESCRIPTION
**Pull request by kelbyhawn**
Deprecate and redirect https://hourofcode.com/beyond to https://studio.code.org/users/sign_up. This also deprecates the carousel views used on this page and the gsheet data used to populate the carousels. 

## Links
Jira ticket: [ACQ-2227](https://codedotorg.atlassian.net/browse/ACQ-2227)

## Followup
I'm not sure if [this gsheet](https://docs.google.com/spreadsheets/d/1RZ6iutiOV8LTol1uooJ3m1GiHHPbpmssNSWkT87oTNI/edit?usp=drive_link) will get deleted when this PR is merged, or I need to manually delete it but I have a note on the ticket to check.

### CODE REVIEW

**Review by TurnerRiley — APPROVED** [review]
The changes look good to me! For my understanding, what is the purpose of redirecting the users to the sign-up page?

**Comment by kelbyhawn** [comment]
> The changes look good to me! For my understanding, what is the purpose of redirecting the users to the sign-up page?

@dmcavoy can you answer this? 🙏

**Comment by dmcavoy** [comment]
> The changes look good to me! For my understanding, what is the purpose of redirecting the users to the sign-up page?

Any existing links to hourofcode.com/beyond will now point people to signing up. We are going to replace most of the places on the site that say "go beyond the hour of code" with calls to Sign up for Code.org. I tried to find a marketing page that would make sense to point to but since it could be a student or a teacher there wasn't a great option

**Comment by TurnerRiley** [comment]
> > The changes look good to me! For my understanding, what is the purpose of redirecting the users to the sign-up page?
> 
> Any existing links to hourofcode.com/beyond will now point people to signing up. We are going to replace most of the places on the site that say "go beyond the hour of code" with calls to Sign up for Code.org. I tried to find a marketing page that would make sense to point to but since it could be a student or a teacher there wasn't a great option

Gotcha! I think my concern was that I feel like as a user if I tried to go to a page and was redirected to the sign-up page I would assume it's a page behind a wall that requires a signed-in user (which may be confusing given that we are intending to put certain pages behind a sign-up wall). I get it with not having a good alternative though. Just a thought!

**Comment by dmcavoy** [comment]
> > > The changes look good to me! For my understanding, what is the purpose of redirecting the users to the sign-up page?
> > 
> > 
> > Any existing links to hourofcode.com/beyond will now point people to signing up. We are going to replace most of the places on the site that say "go beyond the hour of code" with calls to Sign up for Code.org. I tried to find a marketing page that would make sense to point to but since it could be a student or a teacher there wasn't a great option
> 
> Gotcha! I think my concern was that I feel like as a user if I tried to go to a page and was redirected to the sign-up page I would assume it's a page behind a wall that requires a signed-in user (which may be confusing given that we are intending to put certain pages behind a sign-up wall). I get it with not having a good alternative though. Just a thought!

Thats good feedback. Thanks Turner. I think its mostly temporary until we get all the new updates to the pages set up so hopefully its not weird for long

**Pull request merged**
