### PR TITLE
Run the latest Sauce Connect

### PR DESCRIPTION
**Pull request by bcjordan**
- [ ] Kick off a few CCI runs and watch, confirm no intermittent connection failures or degradation of UI test run performance

### CODE REVIEW

**Comment by islemaster** [comment]
Why did this get reverted before again?

**Comment by bcjordan** [comment]
@islemaster just after merging, started seeing "Error bringing up tunnel VM" errors. After a bunch of intermittent failures, pulled the plug and reverted, though it's possible it was just a real coincidental intermittent issue—

```
Brians-MacBook-Pro:code-dot-org brian$ ./bin/circle/search-circle-builds --start 21860 --end 21900
Checking builds 21860, 21861, 21862, 21863, 21864, 21865, 21866, 21867, 21868, 21869, 21870, 21871, 21872, 21873, 21874, 21875, 21876, 21877, 21878, 21879, 21880, 21881, 21882, 21883, 21884, 21885, 21886, 21887, 21888, 21889, 21890, 21891, 21892, 21893, 21894, 21895, 21896, 21897, 21898, 21899, 21900 for output:
Error bringing up tunnel VM. in container 1 step run_tests
wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz in container 1 step run_tests
wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz in container 1 step run_tests
Build https://circleci.com/gh/code-dot-org/code-dot-org/21860 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21861 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21862 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21863 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21864 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21865 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21866 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21868 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21871 output contains: Error bringing up tunnel VM.
Build https://circleci.com/gh/code-dot-org/code-dot-org/21871 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21872 output contains: Error bringing up tunnel VM.
Build https://circleci.com/gh/code-dot-org/code-dot-org/21872 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21873 output contains: Error bringing up tunnel VM.
Build https://circleci.com/gh/code-dot-org/code-dot-org/21873 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21874 output contains: Error bringing up tunnel VM.
Build https://circleci.com/gh/code-dot-org/code-dot-org/21874 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21875 output contains: Error bringing up tunnel VM.
Build https://circleci.com/gh/code-dot-org/code-dot-org/21875 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21876 output contains: Error bringing up tunnel VM.
Build https://circleci.com/gh/code-dot-org/code-dot-org/21876 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21877 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21878 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21880 output contains: Error bringing up tunnel VM.
Build https://circleci.com/gh/code-dot-org/code-dot-org/21880 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21881 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21882 output contains: Error bringing up tunnel VM.
Build https://circleci.com/gh/code-dot-org/code-dot-org/21882 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21883 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21884 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21885 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21886 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21887 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21888 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21889 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21890 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21892 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21895 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21897 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21898 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
Build https://circleci.com/gh/code-dot-org/code-dot-org/21900 output contains: wget https://saucelabs.com/downloads/sc-4.4.0-rc2-linux.tar.gz
```

**Comment by islemaster** [comment]
Hmm.  Well, seems like it's worth another shot anyway.

**Comment by islemaster** [comment]
Closing, this is [not the latest SauceConnect anymore anyway](https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy).

**Pull request closed without merging**
