### PR TITLE
Log to new relic when not using watch

### PR DESCRIPTION
**Pull request by pcardune**
To get this to work, I had to change a bunch of things around in
time-grunt-nowatch. I also had to switch to synchronous file reading so
that things would happen in the right order. I also had to pass in a log
function in order to get anything to show up on the console :(

At least I think it actually really really works now.

### CODE REVIEW

**Comment by islemaster** [comment]
Works like a charm for `npm run build` and `npm start` for me now.

Just for kicks, I went offline to see what happens.  I still see this:

```
New Relic Logging
logging 3 build time events to new relic 
OK
```

and it looks like my build-times.log is still getting truncated.  Is this expected behavior?

**Comment by pcardune** [comment]
strange. If newrelic doesn't throw an exception when it can't sent events, I guess there is nothing we can do about that 😢 . The docs don't say anything about failure cases either 😢 . I would say we should just go with this, and if it doesn't log when you are not connected to the internet... oh well.

**Comment by islemaster** [comment]
LGTM for now.  I'm surprised that it doesn't fail when offline.

**Comment by pcardune** [comment]
Feel free to follow along in the discussion I started with new relic: https://discuss.newrelic.com/t/custom-event-error-handling-in-node-js/37255

**Pull request merged**
