### PR TITLE
responsive notification

### PR DESCRIPTION
**Pull request by Erin007**
This is a temporary fix for the /yourschool launch in which a Notification is being used on a responsive pegasus page and we're anticipating increased mobile traffic. To accomplish this without breaking the desktop layout for all of the various uses of `Notification` (dismissible, RTL etc), I made a lightweight copy, `ResponsiveNotification` and used it on /yourschool.

BEFORE: 
screen shot 2017-09-08 at 10 52 47 am

AFTER: 
screen shot 2017-09-08 at 1 21 01 pm

### CODE REVIEW

**Comment by Erin007** [comment]
cc: @tanyaparker

**Comment by tanyaparker** [comment]
Can we just hide the icon on mobile?

**Comment by Erin007** [comment]
The way I've done it is quick and dirty. We can't remove the icon because we're not doing a media query at any point.  The content is exactly the same just with wrapped text, so for Monday we can have an icon on both desktop and mobile or no icon on both desktop and mobile.  Over the long term we can decide what we actually want the responsive notification to look like and style it that way when the responsive framework comes in with responsive /courses.

**Comment by tanyaparker** [comment]
Got it! For Monday, let's keep icon on both desktop and mobile.

**Pull request merged**
