### PR TITLE
Revert "Revert "I18n HOC sync 10/31""

### PR DESCRIPTION
**Pull request by Hamms**
Reverts code-dot-org/code-dot-org#18923

The PR that was originally reverted caused some HoneyBadger issues over the weekend due to a handful of syntax errors introduced by the HOC translations sync.

To help ensure this PR doesn't do the same, I've [reenabled the HOC i18n routes test](https://github.com/code-dot-org/code-dot-org/blob/revert-18923-revert-18799-i18n-hoc-sync-10-31/pegasus/test/test_i18n_hoc_routes.rb).

(For context, that test was [disabled last year](https://github.com/code-dot-org/code-dot-org/pull/11850) because it started failing with a syntax error. Turns out, that's just how it actually fails when a translation introduces a syntax error, so I also added some handlers to the test to give more helpful error messages when it catches a real error)

### CODE REVIEW

**Comment by joshlory** [comment]
Is there a way to split this into smaller chunks?

**Comment by Hamms** [comment]
There will be for future syncs; the problem here is that it's been almost a year since the last time we synced HoC translations.

This PR also includes https://github.com/code-dot-org/code-dot-org/pull/18899, so it's automatically verifying every hour of code route in every language, and I am in fact using that test to to verify each of the individual "fix {language} errors" commits.

With that test enabled, I'm quite confident that once this PR is green we really are good to merge.

**Comment by Hamms** [comment]
Yep! I didn't get to download all the changes from crowdin because they only let you rebuild the project every 30 minutes or so, but I made all the changes in sync.

**Comment by tanyaparker** [comment]
What I would do to get around that is you can rebuild the project from the UI as much as you want, just not through the crowdin gem. So if you rebuild on the UI and then do a down sync, it should have the latest build I think.

**Comment by Hamms** [comment]
Oh, rad! Does the UI let you build on a per-language basis, too?

**Comment by tanyaparker** [comment]
Unfortunately not. All or nothing.

**Pull request merged**
