### PR TITLE
Course explorer - professional learning link

### PR DESCRIPTION
**Pull request by Erin007**
To increase visibility of the professional development resources, this PR adds a Professional Learning band to the Course Explorer.  The button links to code.org/educate/professional-learning.

Desktop: 

prof learning desktop

Mobile:

prof learning mobile

### CODE REVIEW

**Comment by breville** [comment]
Can we instead have this bar added as another entry in the Ruby array of choices , with parameters for its different styling?

Is there a reason this doesn't expand to give more information before clicking Learn More?

**Comment by tanyaparker** [comment]
I don't think we need to repeat the information in an expander. If they read it there and click Learn More they'll see the same stuff. Might as well take them directly to what they want.

**Comment by breville** [comment]
I would have preferred the bar entry added to the array, with parameters for the extra styling.

Aesthetically, I'm also not a fan of just adding a button to one bar, after considerable debate and effort to make it clear that the other bars clickable to expand and contract.  It feels inconsistent.

**Comment by Erin007** [comment]
I agree that aesthetically it would be more consistent to not include a button. Moreover, in an ideal world, I would advocate that this new bar shouldn't even go here. Alas, I kept it this way for two reasons: 1.) Time. Given the other work items stacking up with a looming HoC deadline, this solution was quick and matched the spec.  2.) This bar is inherently inconsistent - it doesn't match the context of the other courses in that it's about offerings for teachers rather than students, is purple, and doesn't have the same information as the others for the expanded section. 

I definitely think post-HoC this is worth revisiting to either: remove this from the course explorer and find a better way to make information about professional development available to teachers or make this bar more stylistically consistent and expandable like the others. Happy to work with you and @tanyaparker  then to keep your Course Explorer beautiful!

**Comment by tanyaparker** [comment]
Right. We're flexible for other options like putting it as a separate entity below the course explorer. Let's chat and rethink when we have more time.

**Pull request merged**
