### PR TITLE
don't use vowels in section codes to avoid generating bad words

### PR DESCRIPTION
**Pull request by laurelfan**
We got a Zendesk complaint from a 2nd grade teacher about a section with code "SEXAVF".

### CODE REVIEW

**Comment by breville** [comment]
great idea :)

**Comment by laurelfan** [comment]
thank you for the idea  @breville  :)

**Comment by breville** [comment]
yr wlcm

**Comment by philbogle** [comment]
Even omitting vowels it's not hard to generate offensive-ish words, of course.

**Comment by breville** [comment]
True, though these are just random letters that we generate, so fingers crossed it slightly reduces the chances of us generating a real word, offensive or otherwise.

**Comment by laurelfan** [comment]
I feel like if it's not literally a bad word, it's kind of their fault for
seeing it... if we generate SEX that's bad but SX is not actually a word
and could be six, sax, sox...
Also given that we've had only one complaint about this over 2 years we
probably don't have to go too crazy about it.

**Pull request merged**
