### PR TITLE
Removes the my_prizes_url link from the user menu.

### PR DESCRIPTION
**Pull request by ashercodeorg**
This is the first of many PRs to dismantle the prizes (student and teacher) framework in dashboard. This PR simply removes the option from the user menu.

BEFORE:
image

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Thanks! Updated PR topic and summary to call it the user menu.

**Comment by ashercodeorg** [comment]
And removed associated tests... Feel welcome to take another look.

**Comment by breville** [comment]
Oh good, thanks for catching the test removal too.

**Comment by tanyaparker** [comment]
LGTM

**Pull request merged**
