### PR TITLE
[DES-326] (Font Files) Change Gotham font to Metropolis font

### PR DESCRIPTION
**Pull request by levadadenys**
### [DES-326] (Font Files) Change Gotham font to Metropolis font
* add font files as base64 strings to shared/metropolis-font.scss

Will be a part of bigger PR https://github.com/code-dot-org/code-dot-org/pull/53756

## Links
- jira ticket: [DES-326](https://codedotorg.atlassian.net/browse/DES-326)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bencodeorg** [comment]
Is the idea here that we wouldn't have the actual font files in our repo at all (just the base64 encodings)?

**Comment by levadadenys** [comment]
> Is the idea here that we wouldn't have the actual font files in our repo at all (just the base64 encodings)?

Yep, only base64 string in one place instead of 3 duplicates of files in 3 different folders

**Comment by bencodeorg** [comment]
Does it make it harder to use `/shared` if we use actual font files vs. encoded versions?

I like the idea of centralizing font files in `/shared`, but it also feels like good documentation to me to have the actual font files in `/shared` (alongside the base64 versions), to show where the encodings came from (and we could use them as backup URLs, like mentioned in [this Slack thread](https://codedotorg.slack.com/archives/C0T0PNTM3/p1695337818446079))?

**Comment by levadadenys** [comment]
> Does it make it harder to use `/shared` if we use actual font files vs. encoded versions?
> 
> I like the idea of centralizing font files in `/shared`, but it also feels like good documentation to me to have the actual font files in `/shared` (alongside the base64 versions), to show where the encodings came from (and we could use them as backup URLs, like mentioned in [this Slack thread](https://codedotorg.slack.com/archives/C0T0PNTM3/p1695337818446079))?

From what I know and tried - there's no way of serving font files from `/shared` folder because of `url`s being parsed differently for different envs (dashboard/apps/pegasus). 

I'm +1 to documenting the actual font files sources somewhere. I think we can do:
a) add a comment to `metropolis-font.scss` with a link to a source font files location so that if neeeded we can find them in the future
b) add font files to `/shared` folder. (they won't be used usually, however we'll be able to quickly access them if needed anytime)

**Comment by bencodeorg** [comment]
Sorry not sure I follow about urls being parsed differently across dashboard / apps / pegasus, is there a difference between putting a font file in `/shared` and, say, an image? For example, I see this image referenced across all three:

[sad-bee-avatar.png](https://github.com/code-dot-org/code-dot-org/blob/staging/shared/images/sad-bee-avatar.png)

**Comment by levadadenys** [comment]
> Sorry not sure I follow about urls being parsed differently across dashboard / apps / pegasus, is there a difference between putting a font file in `/shared` and, say, an image? For example, I see this image referenced across all three:
> 
> [sad-bee-avatar.png](https://github.com/code-dot-org/code-dot-org/blob/staging/shared/images/sad-bee-avatar.png)

Yeah, for font files it works differently. Here're examples of the console output when I'm setting font src for `/shared` folder.
The reason for that I believe is importing `metropolis-font.scss` to `application.scss` and parsing of the `src` `url` string.
Tried different options to test and show the output - here's results.(with the url src under error, tried urls string with and without quotes, results. is the same)
Знімок екрана 2023-09-26 о 13 49 29
Знімок екрана 2023-09-26 о 13 40 48
Знімок екрана 2023-09-26 о 13 34 11
Знімок екрана 2023-09-26 о 13 29 19
Знімок екрана 2023-09-26 о 13 24 23

**Comment by bencodeorg** [comment]
Interesting -- I'm guessing we could update some configuration somewhere so that font files are also accessible at `/shared/fonts/...` routes, but maybe not worth blocking on.

I like the idea of having the actual font files alongside these compressed versions for documentation's sake (with a comment above each @font-face specifying which one it aligns with, even if we're not actively using them), but not sure if that is a universally held opinion that we should have files in our repo that aren't actually used :)

Also, could you add a comment about how you did the encoding in case someone needs to do it in the future?

**Review by bencodeorg — APPROVED** [review]

**Comment by cat5inthecradle** [comment]
Will we need to provide non-base64 fallback options for old browers?

If all browsers we claim to support will work, we may be able to skip those fallbacks.

https://code.org/educate/it

**Comment by bencodeorg** [comment]
> Will we need to provide non-base64 fallback options for old browers?
> 
> If all browsers we claim to support will work, we may be able to skip those fallbacks.
> 
> https://code.org/educate/it

My impression based on these is that we shouldn't need fallbacks? Not totally sure though:

https://caniuse.com/?search=web%20fonts
https://caniuse.com/?search=Base64

**Review by sanchitmalhotra126 — APPROVED** [review]

**Comment by levadadenys** [comment]
Based on our supported browser list I also think we don't need fallback options.
Updated the documentation of metroipolis-font.scss, added a link to download font files via code.org google drive. (If we'll find a link to the original source of these files - I'll also add it here), added link to base64 encoder that I've used and commented which font-face represents which font file.

**Pull request merged**
