### PR TITLE
Only pass school id for when it is set on registration school info

### PR DESCRIPTION
**Pull request by drewsamnick**
We currently get a bunch of honeybadger errors triggered when a user registers with an nces school but the school type doesn't match the type in the schools table. This change makes sure that we're only sending the school id and none of the other attributes when an NCES school was selected.

### CODE REVIEW

**Comment by islemaster** [comment]
Sorry for the delay on this, Drew.  I know we haven't got unit tests set up for this module, and we should.  In lieu of that, can you at least describe manual testing you did over this change?

**Comment by drewsamnick** [comment]
My testing was based on some temporary logging I added to make sure that with the change we weren't hitting the honey badger reporting code (not overwriting any passed in school info data.) I also check my local logs to verify that the correct parameters were being sent to the server. 

Do you think there would be an easy way to add some tests here? I'd like to do it, but I don't know that I have the time to get to it by the end of the week.

**Comment by islemaster** [comment]
There might be too much global stuff going on in this module.  I'm satisfied that we'll cover this soon (Eric and I will be doing more work on this page in the next few months).  If you'd like to add something right away, the first thing that comes to mind is a Sprout Class / Sprout Method approach just checking that the form data we construct is well-formed.

**Comment by ewjordan** [comment]
Yeah, this file has evolved into a giant ball of difficult to test mud, and switching it over to use the newer React component has been at the top of my "want to do" list for quite a while. When we finally do that we should be able to get some more coverage, but it's not going to be a trivial change, so now is probably not the time to try to get major testing in.

**Comment by drewsamnick** [comment]
I factored out the logic around converting the school info attributes into a separate function and added a couple of tests for that. To get this to work I had to move the code out to the top level vs. being functions defined inside the function that is assigned to `window.SignupManager`. I think that this is okay (and I verified locally that the page still works) but I'm unclear on why there are so many functions defined there rather than as more standalone bits of code. Some of them reference state from that outer block but the code I moved doesn't.

**Comment by ewjordan** [comment]
"...but I'm unclear on why there are so many functions defined there rather than as more standalone bits of code"

Yeah, this stuff is ugly as hell right now, IIRC I ran out of time to clean it up earlier on. It all needs to be pulled out and replaced with the component that you made for the census form, so next time we touch up the signup page we'll do exactly that.

**Pull request merged**
