### PR TITLE
Removes monthly_metrics, adding missing stats to admin_stats.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Note that monthly_metrics is following the trend of timing out on cloudfront.

### CODE REVIEW

**Comment by Hamms** [comment]
Are we intending to replace/repair monthly_metrics?

**Comment by ashercodeorg** [comment]
No (AFAIK). The few stats it contained are encompassed by admin/stats (pre-existing or part of this PR).

That said, I noticed it timed out today, throwing together this PR without asking whether we want to maintain the monthly_metrics page separately. Let me send an email asking?

**Comment by ashercodeorg** [comment]
Per offline conversation, there is no intent to repair monthly_metrics. It is being superseded by admin/stats.

**Comment by Hamms** [comment]
Do we also want to remove the `monthly_metrics.html.haml` view?

**Comment by ashercodeorg** [comment]
Done. Good call. :)

**Comment by Hamms** [comment]
LGTM! :D

**Pull request merged**
