### PR TITLE
Creates the admin/level_answers dashboard. 

### PR DESCRIPTION
**Pull request by ashercodeorg**

### CODE REVIEW

**Comment by ashercodeorg** [comment]
This is the reincarnation of PR #6040, which was closed because of merge issues.

**Comment by ashercodeorg** [comment]
@Hamms

**Comment by ashercodeorg** [comment]
@laurelfan Sorry for switching PRs. This should address your comments from #6040, please have another look. Thanks!

**Comment by laurelfan** [comment]
LGTM

**Pull request merged**
