### PR TITLE
white background instead of transparent background

### PR DESCRIPTION
**Pull request by tanyaparker**
Oops. When I first tested this the images had a white background. And then at some point I made it transparent and didn't test again before merging. I merged my other PR already, so this fixes the black background that I introduced with https://github.com/code-dot-org/code-dot-org/pull/26466

screen shot 2018-12-21 at 1 30 38 pm

### CODE REVIEW

**Comment by breville** [comment]
I'm surprised that transparent led to black.  Is there some CSS we can fix for this so that we can keep it transparent?

**Comment by tanyaparker** [comment]
Not sure! Don't see anything obvious from a quick google search.

**Comment by breville** [comment]
Oh, the image actually did have transparency, but when [retrieving](https://github.com/code-dot-org/code-dot-org/pull/26466/commits/a89305b9c98fbdadb7025968027a9d134baf47f6#diff-0cbc855217f9a724aff02f1328c72364R9) it as a JPG the transparent pixels were converted to black.  We'd have to have retrieved it as a PNG to maintain that transparency.

**Comment by tanyaparker** [comment]
Would you prefer I switch to transparent and fetch as .png? I think we said we should always fetch as .jpg to apply our image compression techniques?

**Comment by breville** [comment]
At 25 KB vs. 146 KB for one of these images, when JPG instead of PNG, it does seem worthwhile using the former.  Good call.

**Pull request merged**
