### PR TITLE
Reorder code so @user defined.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixing bug introduced by #13760. Honeybadger [issue](https://app.honeybadger.io/projects/3240/faults/32973526).

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Added a test. In doing so, I realize that we aren't actually using (checking) `@user.errors` in this workflow, as we end up [here](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/views/followers/student_user_new.html.haml#L9), not [here](https://github.com/code-dot-org/code-dot-org/blob/staging/dashboard/app/views/followers/student_user_new.html.haml#L17-L21).

Should this be "fixed"?

**Comment by aoby** [comment]
Yeah we might as well either not bother adding those errors in the controller, or (better) simplify the view.

**Comment by ashercodeorg** [comment]
For now, I'm going to merge this PR, as it fixes a known production regression. Let me follow up with another PR that cleans up this codepath.

**Comment by ashercodeorg** [comment]
Calling the pixelation test failure unrelated. Merging...

**Pull request merged**
