### PR TITLE
Add new LearningGoalAiEvaluation table

### PR DESCRIPTION
**Pull request by wilkie**
This follows the PR at https://github.com/code-dot-org/code-dot-org/pull/54379 which now ties a new LearningGoalAiEvaluation table to the new RubricAiEvaluation.

This code then uses both the new and the old tables.

The next PR will copy the data over and remove the old table.

## Links

- jira ticket: [AITT-272](https://codedotorg.atlassian.net/browse/AITT-272)

## Follow-up work

Task list for adding the `RubricAiEvaluation` model:

- [x] Add the migration (https://github.com/code-dot-org/code-dot-org/pull/54360)
- [x] Add the model and start writing to the new table and the old (https://github.com/code-dot-org/code-dot-org/pull/54379)
- [x] Forge new `LearningGoalAiEvaluation` record (and move old one to new name) with a foreign key to point to `RubricAiEvaluation` (**THIS PR**)
- [ ] Add a data migration to move the old data from `LearningGoalAiEvaluation` records to this one (https://github.com/code-dot-org/code-dot-org/pull/54413)
- [ ] Drop old LearningGoalAiEvaluation table and properly add in logic to write/query RubricAiEvaluation (https://github.com/code-dot-org/code-dot-org/pull/54435)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by wilkie** [comment]
Tests refused to clone for some reason. Restarting them.

**Comment by wilkie** [comment]
Another inexplicable test failure around the applab levels tests... likely relating to the project association with an unknown project. Removing that association altogether.

**Comment by wilkie** [comment]
Just getting a ton of timeout errors around Project creation:

```
FAIL["test_weblab_only_remixes_Sources_and_Files_buckets", "RemixTest", 3069.3403689900006]
--
14443 | test_weblab_only_remixes_Sources_and_Files_buckets#RemixTest (3069.34s)
14444 | Wrong response: Sequel::DatabaseError at /projects/weblab/new
14445 | =============================================
14446 |  
14447 | Mysql2::Error::TimeoutError: Timeout waiting for a response from the last query. (waited 30 seconds)
14448 |  
14449 | > To access an interactive console with this error, point your browser to: /__better_errors
14450 |  
14451 |  
14452 | app/controllers/projects_controller.rb, line 285
14453 | ------------------------------------------------
14454 |  
14455 | ``` ruby
14456 | 280
14457 | 281     def create_new
14458 | 282       return if redirect_under_13_without_tos_teacher(@level)
14459 | 283       channel = ChannelToken.create_channel(
14460 | 284         request.ip,
14461 | > 285         Projects.new(get_storage_id),
14462 | 286         data: initial_data,
14463 | 287         type: params[:key]
14464 | 288       )
14465 | 289       redirect_to(
14466 | 290         action: 'edit',
14467 | ```
14468 |  
14469 | App backtrace
14470 | -------------
14471 |  
14472 | - app/controllers/projects_controller.rb:285:in `create_new'
14473 | - app/controllers/application_controller.rb:181:in `block in with_locale'
14474 | - app/controllers/application_controller.rb:180:in `with_locale'
14475 | - test/integration/remix_test.rb:228:in `create_a_new_project'
14476 | - test/integration/remix_test.rb:184:in `assert_only_remixes_sources_files'
14477 | - test/integration/remix_test.rb:106:in `block in <class:RemixTest>'
14478 | - test/testing/setup_all_and_teardown_all.rb:36:in `run'
14479 |  
```

**Comment by wilkie** [comment]
The relevant part of the full backtrace:

```
Full backtrace
--
14481 | --------------
14482 |  
14483 | - mysql2 (0.5.5) lib/mysql2/client.rb:151:in `_query'
14484 | - mysql2 (0.5.5) lib/mysql2/client.rb:151:in `block in query'
14485 | - mysql2 (0.5.5) lib/mysql2/client.rb:150:in `handle_interrupt'
14486 | - mysql2 (0.5.5) lib/mysql2/client.rb:150:in `query'
14487 | - rack-mini-profiler (3.0.0) lib/patches/db/mysql2/alias_method.rb:22:in `query'
14488 | - sequel (5.67.0) lib/sequel/adapters/mysql2.rb:142:in `block in _execute'
14489 | - sequel (5.67.0) lib/sequel/database/logging.rb:38:in `log_connection_yield'
14490 | - sequel (5.67.0) lib/sequel/adapters/mysql2.rb:137:in `_execute'
14491 | - sequel (5.67.0) lib/sequel/adapters/utils/mysql_mysql2.rb:40:in `block in execute'
14492 | - sequel (5.67.0) lib/sequel/connection_pool/threaded.rb:92:in `hold'
14493 | - sequel (5.67.0) lib/sequel/database/connecting.rb:293:in `synchronize'
14494 | - sequel (5.67.0) lib/sequel/adapters/utils/mysql_mysql2.rb:40:in `execute'
14495 | - sequel (5.67.0) lib/sequel/adapters/mysql2.rb:71:in `execute_insert'
14496 | - sequel (5.67.0) lib/sequel/dataset/actions.rb:1203:in `execute_insert'
14497 | - sequel (5.67.0) lib/sequel/dataset/actions.rb:421:in `insert'
14498 | - /drone/src/shared/middleware/helpers/storage_id.rb:190:in `create_storage_id_for_user'
14499 | - /drone/src/shared/middleware/helpers/storage_id.rb:5:in `create_storage_id_cookie'
14500 | - /drone/src/shared/middleware/helpers/storage_id.rb:95:in `get_storage_id'
14501 | - app/controllers/projects_controller.rb:285:in `create_new'
```

In particular the last few lines just above. This shows us that `create_storage_id_for_user` is our main problem: https://github.com/code-dot-org/code-dot-org/blob/b43061474de78b2641495fa232938a7115e6ae58/shared/middleware/helpers/storage_id.rb#L188-L197

We can't fire off that query.

**Comment by wilkie** [comment]
When there is no current user and no cookie already... it creates a storage id for this session via `create_storage_id_cookie`. This creates a storage_id by simply writing `NULL` into the `user_project_storage_ids` table and returning the new row's `id`. This essentially gives you a fairly expensive incremental counter.

The code path uses `NULL` for the `user_id` of the `user_project_storage_ids` Dashboard table. This table is (albeit difficult to assert) seems to have an index on that column and making it unique. However, this is a `NULL` value... which I don't think is considered as part of the unique constraint. This feels problematic. (Although necessary for unique storage_ids for these guest accounts.)

My hypothesis is that it is allowing multiple `NULL` values and then failing to efficiently index them. This becomes a periodic problem on testing. Though, it is wild that this wouldn't present itself as a problem in production!

## Testing

Running `100.times { puts(Benchmark.measure{ 1000.times { create_storage_id_for_user(nil) } }) }` in an attempt to gauge the slow-down of adding such ids over time. Not a perfect measure. It doesn't really hammer at the index. It does show a slight slowdown of around 0.5 seconds or so from beginning to end from 4.9 seconds to create 1000 to 5.45 seconds to create 1000.

Local tests also fail with the timeout:

```
ERROR["test_find_channel_owner_returns_nil_for_channel_with_no_owner", "UserTest", 3565.202698686975]
 test_find_channel_owner_returns_nil_for_channel_with_no_owner#UserTest (3565.20s)
Minitest::UnexpectedError:         Sequel::DatabaseError: Mysql2::Error::TimeoutError: Timeout waiting for a response from the last query. (waited 30 seconds)
            test/testing/projects_test_utils.rb:31:in `with_storage_id_for'
            test/testing/projects_test_utils.rb:9:in `with_channel_for'
            test/testing/projects_test_utils.rb:35:in `with_anonymous_channel'
            test/models/user_test.rb:4653:in `block in <class:UserTest>'
            test/testing/setup_all_and_teardown_all.rb:36:in `run'
```

Yet when I look at the actual table (`SELECT * from user_project_storage_ids`), it only has around 66 rows, including just a single `NULL`. Baffling.

**Comment by wilkie** [comment]
Ok! That worked... I might just supersede the prior PR with this one for the ease of it. That means, we merge this one instead of that one... they don't need to strictly be done one after the other.

**Comment by davidsbailey** [comment]
I see what you are saying now about merging this PR instead of the previous one. That seems fine once we are sure about this PR.

I do have one big question though, which is, why do you need to move the old table and temporarily have 2 models and 2 tables? it seems like you could simplify quite a bit as follows:
1. merge https://github.com/code-dot-org/code-dot-org/pull/54360 and https://github.com/code-dot-org/code-dot-org/pull/54379
1. copy learning_goal_ai_evaluation fields to rubric_ai_evaluation, creating rubric_ai_evals as necessary (similar to https://github.com/code-dot-org/code-dot-org/pull/54413)
1. remove obsolete rows from learning_goal_ai_evaluations

I am open to the conclusion that it will be less work to do it this way given that it is already done this way, however there is also an argument that the simpler way will be better because it is doing less and therefore is less error prone.

**Comment by wilkie** [comment]
Yep. We could definitely do that... with some care. The simple thing to do was to have both data tables co-exist along with their means of being queried so the tests pass and you can augment the tests with the new pattern... asserting both. That way you know they are equivalent. I'm being, perhaps, too cautious and having too much of a preference of keeping one migration per PR. (I could have easily combined creating the rubric_ai_evaluation and new learning_goal_ai_evaluation tables... at least merge them together, but much nicer to review in pieces, perhaps.)

Then again, that third step is really quite difficult. In the old mode, you gathered and updated LearningGoalAiEvaluations in the job (they don't pre-exist) by gathering them through the Rubric itself and matching them by the learning goal name. In the new mode, you pre-emptively create a main record (RubricAiEvaluation) when you schedule the job with a "queued" status, and also create a set of unfulfilled LearningGoalAiEvaluation records associated with it before the job even runs and then the job fills them in based on success or failure.

Gathering LearningGoalAiEvaluation records is quite a chore (especially since they are queried only by the rubric and student user id... perhaps insufficiently? I guess a student never retakes a class?) and done in such a different way than before that wrapping my head around having them both work with the same tables and then removing the rows was way more brain energy (which is saying a lot) than what I did which was to just create a new table.

Now you get to review the code to add back in the rubric creation and querying all by itself.

**Comment by davidsbailey** [comment]
Thank you for sharing your thoughts on this in detail, Wilkie! There is just one part I am not following which is the last sentence:

> Now you get to review the code to add back in the rubric creation and querying all by itself.

I'm guessing this was not meant to be a particularly weighty statement, but can you help me understand what this means?

**Comment by wilkie** [comment]
> Thank you for sharing your thoughts on this in detail, Wilkie! There is just one part I am not following which is the last sentence:
> 
> > Now you get to review the code to add back in the rubric creation and querying all by itself.
> 
> I'm guessing this was not meant to be a particularly weighty statement, but can you help me understand what this means?

What I mean is that you can look at https://github.com/code-dot-org/code-dot-org/pull/54435/files without any of the migrations. Which is nice.

**Pull request merged**
