### PR TITLE
Upgraded rubocop verison to match Hound's version (0.42.0)

### PR DESCRIPTION
**Pull request by aoby**
Similar to https://github.com/code-dot-org/code-dot-org/pull/6858

Steps:
1. Change the rubocop version specified in the `Gemfile`.
2. Run `bundle update --source rubocop` to update `Gemfile.lock`.
3. Import the new `.rubocop_hound.yml` from Hound's repo (no change).
4. Run `bundle exec rubocop --auto-gen-config --exclude-limit 0` to regenerate `.rubocop_todo.yml` (the new version of rubocop has a different set of rules).
5. Run `rake lint:ruby` to verify, no errors.

NOTE - there is an error in the `Lint/ShadowedException` rule, so I added it to [rubocop_todo.yml](https://github.com/code-dot-org/code-dot-org/pull/10684/files#diff-74423563ec7c74f4cb7f74689b49e7c1R50) to be excluded manually. This still needs to be investigated so we can open an issue with `rubocop`.

Stack trace:

```
An error occurred while Lint/ShadowedException cop was inspecting /Users/andrew/Code/code-dot-org/bin/cron/deliver_poste_messages.
undefined method `loc' for nil:NilClass
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/lint/shadowed_exception.rb:59:in `offense_range'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/lint/shadowed_exception.rb:48:in `on_rescue'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:42:in `block (2 levels) in on_rescue'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:97:in `with_cop_error_handling'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:41:in `block in on_rescue'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:40:in `each'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:40:in `on_rescue'
(eval):2:in `block in on_kwbegin'
(eval):2:in `each'
(eval):2:in `on_kwbegin'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_kwbegin'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_begin'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/ast_node/traversal.rb:142:in `on_while'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_until'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_begin'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/ast_node/traversal.rb:155:in `on_block'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_block'
(eval):3:in `on_lvasgn'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_lvasgn'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_begin'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/ast_node/traversal.rb:96:in `on_def'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_def'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:46:in `on_begin'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/ast_node/traversal.rb:13:in `walk'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/commissioner.rb:59:in `investigate'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/team.rb:121:in `investigate'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/team.rb:109:in `offenses'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cop/team.rb:52:in `inspect_file'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:223:in `inspect_file'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:193:in `block in do_inspection_loop'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:183:in `loop'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:183:in `do_inspection_loop'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:93:in `block in file_offenses'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:103:in `file_offense_cache'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:91:in `file_offenses'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:82:in `process_file'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:59:in `block in inspect_files'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:57:in `each'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:57:in `inspect_files'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/runner.rb:35:in `run'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cli.rb:72:in `execute_runner'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/lib/rubocop/cli.rb:28:in `run'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/bin/rubocop:14:in `block in <top (required)>'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rubocop-0.42.0/bin/rubocop:13:in `<top (required)>'
/Users/andrew/.rbenv/versions/2.2.3/bin/rubocop:23:in `load'
/Users/andrew/.rbenv/versions/2.2.3/bin/rubocop:23:in `<top (required)>'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/andrew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/Users/andrew/.rbenv/versions/2.2.3/bin/bundle:23:in `load'
/Users/andrew/.rbenv/versions/2.2.3/bin/bundle:23:in `<main>'
```

### CODE REVIEW

**Comment by ashercodeorg** [comment]
Note that circleci failed as the result of no output for ten minutes (during DB migrations). Kicked off a rebuild...

**Comment by ashercodeorg** [comment]
LGTM.

**Comment by ashercodeorg** [comment]
Issue reported to rubocop in https://github.com/bbatsov/rubocop/issues/3532.

**Comment by aoby** [comment]
Looks like they already fixed it in `0.43.0`

**Pull request merged**
