### PR TITLE
X button in Finish Dialog for Dance closes modal instead of redirecting

### PR DESCRIPTION
**Pull request by hannahbergam**
To keep in mind: This update only applies to Dance levels.

Current behavior: the X button in the modal redirects to the next level (or certificate page if it's the last level), as does clicking anywhere outside of the modal.

New behavior: clicking the x or outside the modal closes the modal without redirecting, and the continue button still works as anticipated.

The following gif illustrates the old behavior immediately followed by the new behavior:
xGif

This part of the codebase is confusing: it is worth rewriting into a react component. That said, I tried to clean up the logic for onHidden() in Feedback (called from bootstrap when the modal is closed) and keep risk minimal by only including the new variable in Dance.js. If we discover this issue in other level types, we can utilize the doNothingOnHidden option for displayFeedback. 

I also worked to decouple the x-close button and the continueButton. The x-close will only call onContinue() if the continue button doesn't exist (among other existing conditions), and otherwise, the continue button is responsible for calling onContinue() itself when clicked. 

I'd love to hear other ideas about how to further decouple these two functions- I know the feedback dialog is a messy space so am interested in anything easy(ish) to make it cleaner.

## Links

- spec: []()
- jira ticket: https://codedotorg.atlassian.net/browse/LP-2192

## Testing story

I locally tested maze, flappy and artist to make sure the finish dialog still works elsewhere as anticipated. Worth noting- the behavior we are fixing here in dance does exist in these other level types, and is potentially worth addressing there (it would be as simple as adding a doNothingOnHidden param) for future updates. 

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Review by jamescodeorg — COMMENTED** [review]
If it's not too much trouble, could you include a video capture showing the new behavior in the PR comments?

**Comment by hannahbergam** [comment]
> If it's not too much trouble, could you include a video capture showing the new behavior in the PR comments?

Good call- I've added a gif that shows the old behavior and then the new!

**Review by jamescodeorg — APPROVED** [review]
The PR description describes redirecting to the certificate page (which only applies to the last level) but the change more general than that, right?  On any dance level, clicking "x" or outside of the dialog will now dismiss the dialog instead of continue?

**Comment by hannahbergam** [comment]
> The PR description describes redirecting to the certificate page (which only applies to the last level) but the change more general than that, right? On any dance level, clicking "x" or outside of the dialog will now dismiss the dialog instead of continue?

Good catch- I updated the description! And yes, the x (or clicking outside the modal) will now dismiss instead of continue.

**Pull request merged**
