### PR TITLE
Reduce height of shown code area

### PR DESCRIPTION
**Pull request by islemaster**
Showing code could extend the dialog beyond the page height, making the continue button unreachable.

This is a low-risk adjustment to make "Show code" safe on 1024x768.  I've got work in progress to actually fit the dialog to page height, but we're not going to do that prior to Hour of Code.

Before (1024x768):
screenshot from 2015-12-01 20-28-38

After (1024x768):
screenshot from 2015-12-01 20-28-19

### CODE REVIEW

**Comment by davidsbailey** [comment]
LGTM. FWIW you could make it 10-15 pixels less if you want the fun-o-meter buttons to be visible on small screens. Our eyes tests indicate that at 1024x768 only about 705 vertical pixels are available to the browser, so it would look something like this:
73c217e2-986e-11e5-80b8-eb8d3e294f77

**Comment by islemaster** [comment]
Oops!  Forgot the Chrome screen-size emulation doesn't capture usable space on desktop well.  I'll fix that.

**Comment by Hamms** [comment]
Does this also play nicely with feedback blocks?

**Comment by islemaster** [comment]
@Hamms I intended this change to only affect the "Show Code" area in the popup on successful completion of the level.  Can you point me to a scenario where feedback blocks would be involved?

**Comment by islemaster** [comment]
Reduced scroll area from 200px to 150px.  Here's what it looks like now, with (admittedly minimal) Chrome chrome at 762px total browser height.

screenshot from 2015-12-02 12-56-29

**Comment by Hamms** [comment]
Anytime a level has recommended blocks that aren't being used; https://studio.code.org/s/allthethings/stage/4/puzzle/5 is a simple example

**Comment by islemaster** [comment]
:angry: :facepunch: :rewind: 

screenshot from 2015-12-02 13-00-50

To be fair, this was an existing problem and I am working on a more robust, post-HOC fix.  Is this something we can live with for a month?

**Comment by Hamms** [comment]
The real problem being that we are trying to jam way too much into this poor little dialog.

LGETM (looks good enough to me)

**Comment by islemaster** [comment]
I know, I know!  It needs... TABS.

**Comment by Hamms** [comment]
https://media.giphy.com/media/12XMGIWtrHBl5e/giphy.gif

**Comment by islemaster** [comment]
FYI @philbogle low-risk "Show Code" fix hoping to go in soon.  More robust fix planned post-HOC.

**Pull request merged**
