### PR TITLE
Change 'Courses' to 'Courses from Code Studio'

### PR DESCRIPTION
**Pull request by Erin007**
Signed out users on /courses will now see 'Courses from Code Studio' rather than 'Courses' as the page heading. 

Signed out before: 
signed out courses before

Signed out after: 
signed out courses on code studio

Signed in (no change): 
signed in

### CODE REVIEW

**Comment by Erin007** [comment]
cc: @tanyaparker and @joshlory

**Comment by breville** [comment]
@tanyaparker Does this make it sound as though Code Studio is a separate organisation or publisher?

**Comment by Bjvanminnen** [comment]
I thought we were getting rid of "Code Studio" as a brand?

**Comment by Erin007** [comment]
@Bjvanminnen  I thought so too, but apparently we need to keep it around temporarily in a couple of places to maintain the trademark.

**Pull request merged**
