### PR TITLE
codemod chai and sinon to use jest equivalents

### PR DESCRIPTION
**Pull request by stephenliang**
This PR runs the jest codemod utility to bulk convert chai and sinon based unit tests to the equivalent jest syntax. For tests that failed, the tests are marked with an exception to allow continued usage of chai and sinon but new tests must be created using jest only.

The heuristic is as follows:

1. Run sinon and chai codemods
2. lint:fix
3. Run tests, mark those that failed
4. Restore failed tests from staging
5. Restrict chai and sinon from being imported as eslint rule
6. Any remaining sinon/chai due to failures are excluded (new tests must be written in jest syntax)

## Links

- [design](https://docs.google.com/document/d/1-U41r5O8Y404HeWHOAn2vxUI6G1lSJbtK7xi4j2eZsA/edit#heading=h.zfzb7h4ccnko)

## PR Checklist:

- [ ] Tests provide adequate coverage
- [ ] Privacy and Security impacts have been assessed
- [ ] Code is well-commented
- [ ] New features are translatable or updates will not break translations
- [ ] Relevant documentation has been added or updated
- [ ] User impact is well-understood and desirable
- [ ] Pull Request is labeled appropriately
- [ ] Follow-up work items (including potential tech debt) are tracked and linked

### CODE REVIEW

**Comment by bencodeorg** [comment]
Tangent, but have you ever used git's ignore-rev feature to exclude big automated changes like this from git blame?

[https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame](https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame/#fun-fact%3A-github-picks-up-%60.git-blame-ignore-revs%60)
https://github.com/orgs/community/discussions/5033

**Comment by stephenliang** [comment]
> Tangent, but have you ever used git's ignore-rev feature to exclude big automated changes like this from git blame?
> 
> [https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame](https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame/#fun-fact%3A-github-picks-up-%60.git-blame-ignore-revs%60) https://github.com/orgs/community/discussions/5033

Interesting, I haven't heard of this but this would be pretty useful. Do you know if we will want this?

**Comment by bencodeorg** [comment]
> > Tangent, but have you ever used git's ignore-rev feature to exclude big automated changes like this from git blame?
> > [https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame](https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame/#fun-fact%3A-github-picks-up-%60.git-blame-ignore-revs%60) https://github.com/orgs/community/discussions/5033
> 
> Interesting, I haven't heard of this but this would be pretty useful. Do you know if we will want this?

Not sure! Just something that had crossed my mind in the past and this PR reminded me of it :). eg, we have this [massive Prettier commit](https://github.com/code-dot-org/code-dot-org/commit/75897f9cdba8224261e8b63b1430e607bdd30fbf) that shows up in git blame in `apps` all the time. Don't want to hijack the discussion on this PR though so we can chat about it in another forum!

**Review by wilkie — APPROVED** [review]
I'm overwhelmed. But I can see the gist of what these changes entail. They look good and are really really good for the health of our test suite! Thanks for doing this!

I agree that you should add the revision to the blame ignore.

You need to coördinate with @Hamms in this PR: https://github.com/code-dot-org/code-dot-org/pull/56383

**Review by mgc1194 — APPROVED** [review]
Looks good. 
I assume the goal would be migrating all the tests that still use sinon to jest?

**Pull request merged**
