### PR TITLE
Fix HoC French translation errors

### PR DESCRIPTION
**Pull request by joshlory**

### CODE REVIEW

**Comment by joshlory** [comment]
Does the change go here, or upstream?  There's also another file in the sites.v3 folder: https://github.com/code-dot-org/code-dot-org/blob/2b70c4c9c03c8eb6e98b4cf40864b7286685758e/pegasus/sites.v3/hourofcode.com/i18n/public/fr/promote/country-resources.md#L101

**Comment by Hamms** [comment]
Oh, actually the change should go in sites.v3.

The i18n/locales file is actually the upstream, the sites.v3 is the version that's consumed by pegasus

**Comment by tanyaparker** [comment]
We need to update in all 3 places: crowdin, i18n/locales, and sites.v3.

**Comment by joshlory** [comment]
These were fixed in Crowdin.

**Pull request closed without merging**
