### PR TITLE
enable consistent reads for shared tables in DynamoDB.

### PR DESCRIPTION
**Pull request by davidsbailey**
The goal is to eliminate data consistency issues as a possible reason for unpredictable netsim behavior.

### CODE REVIEW

**Comment by davidsbailey** [comment]
documentation: http://docs.aws.amazon.com/sdkforruby/api/Aws/DynamoDB/Client.html

**Comment by islemaster** [comment]
Thanks for the documentation link.  Looks good.  I think this is definitely worth trying for a few weeks while we change over to Redis-backed NetSim.

**Comment by davidsbailey** [comment]
FYI @wjordan that I've also doubled DynamoDB read capacity on production_tables.

**Comment by davidsbailey** [comment]
testing whether @davidsbailey gets notified in slack when I type this

**Comment by davidsbailey** [comment]
testing whether davidsbailey (no at) gets notified

**Pull request merged**
