### PR TITLE
debug channel id and version history fetch in applab/templateBacked ui test

### PR DESCRIPTION
**Pull request by davidsbailey**
applab/templateBacked.feature is failing ~4x/day with a browser tab crash that leaves the version history dialog spinner showing indefinitely:
screen shot 2016-11-10 at 11 02 33 am

This has also happened at least [once](https://cucumber-logs.s3.amazonaws.com/circle/25577/ChromeLatestWin7_applab_scenarios_output.html?versionId=QhKWmGrEvvzIbx5fe_Tr4IwFtvNnW2Zy) in applab_scenarios which shares the same failing step `I reset the puzzle to the starting version`.

It's worth noting that the failing step currently opens the dialog, closes it, and then opens it again, waiting 3 seconds in between but not necessarily guaranteeing that the dialog has finished closing or that the associated data request is complete before opening it again.

Given the failure rate, a manual repro seems unlikely so I'm adding some debug output instead. The possible failure modes I can think of are:
1. a race condition with sending a second request for the version history before the first has completed
2. a race condition with trying to reopen the version history dialog before it has finished closing 
3. a problem with the data is S3 for the particular channel being fetched
4. a different problem with the data fetch

This PR attempts to fix (1) and (2) by adding the appropriate waits, and added debug logging to help diagnose (3) and (4). The debug output looks like this:
screen shot 2016-11-10 at 12 07 31 pm

### CODE REVIEW

**Comment by davidsbailey** [comment]
In debugging this problem I also saw that `applab_scenarios` and `bigGameVersion` are sometimes failing while waiting until an element is gone:

```
undefined method `map' for nil:NilClass (NoMethodError)
./step_definitions/steps.rb:132:in `block (2 levels) in '
./step_definitions/steps.rb:132:in `/^I wait until element "([.#])([^"]*)" is gone$/'
./step_definitions/steps.rb:99:in `/^I reset the puzzle to the starting version$/'
```

The culprit appears to be a bug in the selenium driver's find_elements:

```
    def find_elements(*args)
      how, what = extract_args(args)
      raise ArgumentError, "cannot find element by: #{how.inspect}" unless FINDERS[how.to_sym]
      driver.find_elements(how, what).map { |el| Applitools::Selenium::Element.new(self, el) }
    end
```

An immediate workaround is not obvious, so I'm now waiting for the element to become not visible instead using jquery which might be more reliable.

I'm also fixing a simple `$ is not defined` by waiting for the appropriate element to appear in the dom via selenium instead first.

**Comment by bcjordan** [comment]
LGTM!

**Comment by davidsbailey** [comment]
merging after container 1 passed on circle. container 0 keeps failing due to an unrelated apps test problem

**Comment by bcjordan** [comment]
Going to revert as we're seeing failures on runs.

Sample debug output from a couple of runs: https://cucumber-logs.s3.amazonaws.com/test/test/Chrome44XP_bigGameVersions_output.html?versionId=YMbxxDEKc8Liquh8O3_PkHwdVjZRFcGC

https://cucumber-logs.s3.amazonaws.com/test/test/Chrome44XP_bigGameVersions_output.html?versionId=U7UQH.gmVzcF5r8ixH.dC.vIj99LHcQ1

**Pull request merged**
