### PR TITLE
Netsim: layout adjustment

### PR DESCRIPTION
**Pull request by islemaster**
Mostly styling changes; some new UI and UI behavior changes too.  Moved lobby into left column, tore out its "closed" mode and replaced it with a status bar above the visualization.  Added ability show/hide certain panels.  All this, best represented with screenshots:

Before:
before

After:
after_2

_Update (Mar 4 @ Noon PST): New "After" image reflecting updated expand/collapse iconography_

### CODE REVIEW

**Comment by breville** [comment]
Nice.  We sometimes use the up/down triangle arrow for show/hide UI (e.g.
header above tutorials) and I wonder if we should try to be consistent
across the board?

Of course, we use a different, +/- approach, for studio.code.org homepage,
just to confuse the matter :)

**Comment by islemaster** [comment]
Oh yeah; I tried the up/down triangle by itself and didn't feel like its function was obvious.  I sort of like the plus/minus to the left of the title though; I think it's more obvious what it does.  It would save some space and be visually distinct from the orange 'action' buttons some of the panels have.

screenshot from 2015-03-04 09 26 58

**Comment by Bjvanminnen** [comment]
FWIW, we use the up/down in contract editor
image
http://staging.learn.code.org/s/algebra/stage/8/puzzle/3

**Comment by islemaster** [comment]
Eek... you mean right/down, which is different from the up/down we use in the course flyout above studio :)

Regardless of which symbol gets used, do we agree that icon to the left of the title is better than the Show/Hide buttons?  I'm also making sure you can click on the header text to trigger show/hide.

screenshot from 2015-03-04 09 50 36

**Comment by islemaster** [comment]
Added +/- icons and did some refactoring to remove boilerplate "Show or hide panels" code.
after_2

**Comment by davidsbailey** [comment]
LGTM. I've skimmed some parts of this, so let me know if there's anything in particular i should look at more closely.

**Pull request merged**
