### PR TITLE
Donor: Teacher banner improvements

### PR DESCRIPTION
**Pull request by breville**
A collection of Donor Teacher Banner improvements:

- The banner can now be dismissed on pegasus, though it only records this on the server if the user is signed in.
  - That said, pegasus will always show the banner, even if the user has previously dismissed it.  This gives users who dismissed it (whether with a "yes" or a "no") a second chance to fill it out.
  - Note that the dashboard APIs that the banner calls when running in pegasus, to get pre-populated information and set the dismissal, will both return 403 errors if there is not a signed in user, but the user should not see anything amiss unless they're looking carefully at their browser developer tools.  The API to get pre-populated information will return a 204 ("No Content") if a student is signed in.
  - Signed out user and signed in students will now also see the banner on pegasus.
- The link to the pegasus page now contains more of the sentence text.
- The permission text is updated and has two links that open in new tabs.
  - The rest of the label text still checks the checkbox.
- The banner gets a new "Learn more" button on dashboard.
-  The banner works on pegasus when there is no school.
  - While the Donor Teacher Banner on dashboard only shows when we have found an appropriate school for that teacher, on pegasus we show the banner under all conditions, including when a teacher hasn't yet set their school.  Now, we cope with the missing school and its missing fields in the pre-population information.
- The banner can appear more than once on a pegasus page.  The two implementations are driven by the same initial information but then operate independently of one other.

Followup to https://github.com/code-dot-org/code-dot-org/pull/30591

### dashboard

Screenshot 2019-09-17 15 42 54

### pegasus

Screenshot 2019-09-17 15 43 03

### CODE REVIEW

**Comment by dju90** [comment]
Hi Brendan, during our call today we discussed the behavior of hiding the banner on **dashboard** when a user had submitted the banner from either dashboard OR pegasus (by writing to the db from either); however, I believe we discussed having the banner be _always_ visible on the pegasus marketing page, regardless of whether the user had submitted before (i.e. regardless of the db value). This is to address the case that the teacher changes their mind about enrolling in AFE and goes through the footer to reach the marketing page.

Everything else looks great; awesome job getting the two components to show up!

**Comment by dju90** [comment]
Another thing: let's not show the banner on pegasus for **students**; in the meanwhile, I'm checking with marketing team if they're okay hiding the banner for logged-out users...stay tuned

**Comment by breville** [comment]
_I was so preoccupied with whether or not I could, I didn’t stop to think if I should._

**Review by clareconstantine — APPROVED** [review]

**Comment by breville** [comment]
Update per our discussion today: we will always show the banner on pegasus, whether there's a signed in user or not, and will not hide it even if it's been dismissed previously by the current user, but we will only pre-populate information in the form if the current user is a teacher.

**Pull request merged**
