### PR TITLE
P20-1273: Change `user_levels.properties` type from `text` to `json`

### PR DESCRIPTION
**Pull request by artem-vavilov**
All `user_levels.properties` columns are empty in the production database and have never been used.
## Links
- JIRA task: [P20-1273](https://codedotorg.atlassian.net/browse/P20-1273)
- Following PR: https://github.com/code-dot-org/code-dot-org/pull/62310

### CODE REVIEW

**Review by allison-code-dot-org — APPROVED** [review]

**Review by mgc1194 — APPROVED** [review]
migration looks good upon Infra approval.

**Comment by sureshc** [comment]
Changing the schema of a large table potentially requires special procedures. Please do not merge this until Infrastructure Team has had a chance to write up the special cases we need to carry out in production.

**Comment by sureshc** [comment]
MySQL 8 [completely rebuilds the table when changing the datatype of a column and does not permit INSERT/UPDATE/DELETE queries on the table while it is rebuilding.](https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl-operations.html#online-ddl-column-operations). This table has >3B rows, so this change would cause all invocations of the "milestone post" controller-action (invoked any time a student clicks Run on a level) to fail for several hours.

image

**Comment by artem-vavilov** [comment]
> MySQL 8 [completely rebuilds the table when changing the datatype of a column and does not permit INSERT/UPDATE/DELETE queries on the table while it is rebuilding.](https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl-operations.html#online-ddl-column-operations). This table has >3B rows, so this change would cause all invocations of the "milestone post" controller-action (invoked any time a student clicks Run on a level) to fail for several hours.

Since this column has never been used, we could simply drop it and create a new one with the same name and json type.

**Comment by sureshc** [comment]
One alternative would be to drop the current column and create a new one with new datatype. We carry out a high volume of writes to this table (~100 UPDATE statements per second during peak usage time periods). We may want to reserve this table for storage of transactional data ("did student X attempt/complete level Y in course Z?") and store analytical data ("how much time did they spend?", "what language were they using?", "how many attempts did they make?"?) in a different system.

**Comment by sureshc** [comment]
We are using the default configuration for [InnoDB Page Size](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_page_size) (16KB). I believe that all of the data for a row is stored in a single data page if it consumes less than half the page size. So we would benefit from keeping the row size of this high write throughput table to <8000 bytes to avoid writing to two data pages for a single row update.

https://dev.mysql.com/doc/refman/8.0/en/innodb-limits.html

>The maximum row size, excluding any variable-length columns that are stored off-page, is slightly less than half of a page for 4KB, 8KB, 16KB, and 32KB page sizes. For example, the maximum row size for the default [innodb_page_size](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_page_size) of 16KB is about 8000 bytes. However, for an InnoDB page size of 64KB, the maximum row size is approximately 16000 bytes. [LONGBLOB](https://dev.mysql.com/doc/refman/8.0/en/blob.html) and [LONGTEXT](https://dev.mysql.com/doc/refman/8.0/en/blob.html) columns must be less than 4GB, and the total row size, including [BLOB](https://dev.mysql.com/doc/refman/8.0/en/blob.html) and [TEXT](https://dev.mysql.com/doc/refman/8.0/en/blob.html) columns, must be less than 4GB.

> If a row is less than half a page long, all of it is stored locally within the page. If it exceeds half a page, variable-length columns are chosen for external off-page storage until the row fits within half a page, as described in [Section 17.11.2, “File Space Management”](https://dev.mysql.com/doc/refman/8.0/en/innodb-file-space.html).

**Comment by sureshc** [comment]
Could we leverage something like our `i18n-string-tracking-events` Firehose data stream, which writes to a Redshift table to track usage of each level across different languages?

**Comment by nataliazm99** [comment]
The purpose of this request is to be able to answer questions like 'How many users are using CSF in Filipino-Tagalog language', for tracking and reporting to donors funding these initiatives. if it is possible to add the locale to the properties in user_levels, it would be awesome. The option to track it as a Firehose event is not ideal from a data analysis point of view because of 1) joining two giant tables like `analysis.events` and `user_levels` would not be easy because the only field that can be used for the join is the user_id, all the other information would be in the events properties making it hard to work with and would have terrible performance. 2) We know we are losing too much data from events. As the localization initiatives progress, there is an even greater need for this data. 
If it isn't possible to track it as part of user_levels, would it be possible to track it in another table that logs just `user_id`, `script_id`, `level_id`, `timestamp`, and `locale`?

**Comment by artem-vavilov** [comment]
Could we simply add a new `VARCHAR(5)` column named `locale`, instead of storing it in the `properties` column?

**Comment by coryamanda** [comment]
Just chiming in to echo Natalia's point. This is really helpful information for reporting - storing it in the firehose makes it very difficult to query and debug on our side. Either a new table with links to user_levels or a new column in user_levels would work for us. Thanks!

**Pull request closed without merging**
