### PR TITLE
Fixes the location of the JSON format.

### PR DESCRIPTION
**Pull request by ashercodeorg**
Fixes "bug" propagated by #12852.

### CODE REVIEW

**Comment by wjordan** [comment]
is this just a lint/style 'bug' or something else? just curious.

**Comment by ashercodeorg** [comment]
My belief is that this is something else, that the `format: :json` should not be part of the parameters but an option to the action. Though I could very well be mistaken, someone that knows rails better should look at this.

**Comment by wjordan** [comment]
(I wonder why the original change didn't cause the affected tests to fail- perhaps the explicit `format: json` was not strictly necessary for the tests to pass in the first place? Either way this fix is appropriate.)

**Comment by ashercodeorg** [comment]
The original change was a no-op from the point of view of the code, it kept the `format: JSON` as part of the `params` rather than `options` (note that it existed in the original hash). Presumably, the JSON format was not required for the test to pass.

**Pull request merged**
